buildbuddy-io/buildbuddy

server/backends/blobstore/blobstore.go
S3 access points are a relatively new feature (https://blog.runpanther.io/s3-bucket-security/).  
These access points use a subset of the S3 API (https://docs.aws.amazon.com/AmazonS3/latest/dev/using-access-points.html) - which does not include buckets since you already need to associate a bucket with an access point.
=> don't try to create an S3 bucket for S3 access points

CONFIG.md, app/root/root.tsx, proto/config.proto, server/config/config.go, server/static/static.go
Discussed the approach on the Slack channel. Thanks for the pointers!
I don't see tests for the other config entries in the repo, but I'm happy to add some for this if I can get some guidance on what these tests might look like :)
In the meantime, I tested this manually with the new config (true and false) and without it (default false) and it's working nicely. Let me know what you think!
=> Add default_to_dense_mode config option

server/build_event_protocol/build_event_handler/build_event_handler.go, server/util/protofile/protofile.go
Flushes build event proto after the WorkspaceStatus event instead of after the hardcoded 15th event heuristic.
This is a big improvement for builds that have at a large number of configure events (when doing `build //...` we get hundreds which crowd out other important early events). This means we don't get stuck with "Loading" as the user's name for most of the build.
Also adds a flush when we get an event and haven't flushed in over a minute. 
- This is preferable to a memory based approach because progress events, depending on your configuration can be nearly empty protos, and last for 20+ minutes without flushing.
- It's also preferable to a pure sequence number based approach (e.g. flush every 100 events) because we often get hundreds of events in a very short period of time.
=> Better build event flushing

server/buildbuddy_server/buildbuddy_server.go
Depends on https://github.com/buildbuddy-io/buildbuddy/pull/77
=> Pass urlIdentifier through to the backend

server/buildbuddy_server/buildbuddy_server.go
Use `GetUser` instead of `FillUser` to get the user from the JWT. Also the argument order of `userID` and `groupID` was flipped.
=> Fix CreateGroup implementation

static/image/link.svg
Used in https://github.com/buildbuddy-io/buildbuddy-internal/pull/113
=> Add Link icon

proto/BUILD, proto/acl.proto, proto/execution_stats.proto, proto/invocation.proto
Only adding the ACL protos in this PR. Once approved I'll send follow up PRs for
* Populating the fields
* API protos for mutating the fields
=> Add ACL proto

server/buildbuddy_server/BUILD, server/buildbuddy_server/buildbuddy_server.go, server/interfaces/interfaces.go
Also removes `FillGroup` from the userDB interface per discussions with @tylerwilliams
=> Improve error message when slug is already in use

server/backends/invocationdb/invocationdb.go
Somehow this fix got lost in one of the previous PRs.
=> Fix UpdateInvocationACL

app/capabilities/capabilities.tsx, app/components/button/button.css, app/components/menu/menu.css, app/components/menu/menu.tsx, app/invocation/invocation.css, app/invocation/invocation_menu.tsx, app/invocation/invocation_overview.tsx, static/image/more-vertical.svg
The delete button doesn't do anything yet, but the menu item is disabled if the user doesn't have write access.
Test locally by setting `localStorage['delete_invocation'] = 'true'`
=> Add UI skeleton for invocation deletion

app/invocation/invocation_menu.tsx
=> Wire up deleteInvocation RPC

app/capabilities/capabilities.tsx, app/compare/compare.css, app/compare/compare_invocations.tsx, app/invocation/invocation.css, app/invocation/invocation_menu.tsx
Polish:
- Add error message to delete dialog if deletion fails
- Small screen styles for compare button
- Small screen styles for invocation comparison page
=> Polish and enable invocation comparison and deletion

server/buildbuddy_server/buildbuddy_server.go
Regex tests: https://play.golang.org/p/K_aODmaDLr-
=> Update API key redaction logic

server/build_event_protocol/build_event_handler/BUILD, server/build_event_protocol/build_event_handler/build_event_handler.go, server/interfaces/interfaces.go
Reverts buildbuddy-io/buildbuddy#144
=> Revert "Return UNAUTHENTICATED error when API key header is invalid"

app/errors/errors.css
Could've sworn I fixed this in another PR :shrug:
=> Fix centering of error banner

server/metrics/metrics.go
Branched from #161 -- feel free to wait till that one is merged before reviewing.
=> Add remote execution metrics

tools/metrics/grafana/dashboards/buildbuddy.json, tools/metrics/prometheus/prometheus.yml
=> Update Grafana dashboards & config for remote execution metrics

tools/metrics/grafana/dashboards/buildbuddy.json
=> Add blobstore and SQL dashboards

enterprise/server/backends/redis/redis.go
Bug fix (non-breaking change that fixes an issue)
=> Fix cache metrics NPE

docs/prometheus-metrics.md
=> Regenerate Prometheus docs

deps.bzl, go.mod, go.sum, server/test_environment/test_environment.go
=> Add support for executor tests

proto/remote_execution.proto, server/metrics/metrics.go
New feature (non-breaking change that adds functionality)
=> Add more RBE metrics

.github/pull_request_template.md
=> workflow: Update PR template

tools/metrics/grafana/dashboards/buildbuddy.json
=> grafana: Add "median action stage durations" chart

app/flame_chart/profile_model.ts
---
**Related issues**: Fixes https://github.com/buildbuddy-io/buildbuddy-internal/issues/210
=> flame chart: Combine skyframe threads with and without dashes

app/util/BUILD, app/util/clipboard.ts
=> Add clipboard util

proto/workflow.proto, server/libmain/libmain.go, server/testutil/auth/BUILD, server/testutil/auth/auth.go, server/workflow/BUILD, server/workflow/workflow.go, server/workflow/workflow_test.go, static/image/git-merge.svg
- Return WebhookURL in the `Workflow` response so that the user can view it later via the workflows list view
- Fix bug that workflow ID isn't returned in `GetWorkflowsResponse`
- Fix auth flow bug (authenticatedUser.groupID doesn't necessarily match the group ID in the request context)
- Modify app routes to point to workflows
- Add SVG to image dir
---
=> workflows: Add more supporting code and bugfixes

proto/api_key.proto
Figured the proto could contain a list of "positive" capabilities, and if we want to add a distinction between capabilities / restrictions (to avoid DB migrations), then we can hide that gnarliness from the frontend and handle it at the DB layer.
---
=> API keys: Add capability proto

server/util/capabilities/BUILD, server/util/capabilities/capabilities.go, server/util/capabilities/capabilities_test.go
This will be used to convert between DB capabilities and proto capabilities.
---
=> API keys: Add capability util

app/invocation/dense/dense_invocation_overview.tsx
---
**Related issues**: Fixes https://github.com/buildbuddy-io/buildbuddy-internal/issues/230
=> invocations: Add menu to dense overview page

server/metrics/metrics.go
=> prometheus: Add missing buckets for metrics

proto/execution_stats.proto
=> getExecutionNodes response and request

enterprise/server/auth/auth.go, server/backends/disk_cache/disk_cache.go, server/backends/memory_cache/memory_cache.go, server/util/lru/BUILD, server/util/lru/lru.go
=> Add Config struct to LRU to simplify usage.

enterprise/server/auth/auth.go
This PR resurrects support for using an authenticator without an authDB.
In some configurations, we run the executors pointing directly at a cache, the app writes to the cache, passes a JWT (via header) to the executor, and the executor reads/writes the necessary files directly (instead of via the app). To support this mode of operation, the executor needs to be able to install the authenticator, without an authDB, so it can validate the JWT passed to it.
This CL adds authDB presence checking around the callsites where it's used, and removes the presence check recently added in the NewAuthenticator function.
=> Resurrect support for JWT-only auth.

enterprise/server/backends/distributed/distributed_test.go, server/util/lockingbuffer/lockingbuffer_test.go
This CL fixes both races detected in our tests, unblocking us from enabling the race detector as part of CI.
=> Fix races in two tests.

tools/prettier/BUILD, tools/prettier/prettier.sh
=> workflows: Fix missing arg in prettier lint check

server/build_event_protocol/event_parser/event_parser.go
Populate command and pattern so they don't show up as "root's" in the history view.
---
=> workflows: Populate command and pattern

enterprise/server/workflow/service/service.go
=> workflows: Delete unused code

server/remote_cache/hit_tracker/hit_tracker.go
Fix size & duration prometheus metrics
---
=> Fix size & duration prometheus metrics

enterprise/server/backends/distributed/distributed_test.go, enterprise/server/util/heartbeat/heartbeat.go, server/util/consistent_hash/BUILD, server/util/consistent_hash/consistent_hash_test.go
Also add a test for consistent hash to reassure myself it's working as designed.
=> Increase distributed disk heartbeat timeout.

deps.bzl, go.mod, go.sum
Prep work to support structured logging.
=> Add zerolog to deps.bzl

server/interfaces/interfaces.go
=> container-recycling: Rename CommandRunner to CommandContainer

server/config/config.go
=> Add config option to enable docker-on-docker

server/config/config.go
=> Add task persistence config option for controlling rollout/testing.

enterprise/server/backends/redis_cache/redis_cache.go
=> Use the fast bytes method with Get as well

server/config/config.go
=> Have Configurator.GetCacheRedisTarget() return target from redis sub-config, if it's present.

enterprise/server/backends/pubsub/pubsub.go
=> Add a Redis list-based PubSub implementation.

buildfix.sh
=> Update buildfix to operate buildifier recursively

WORKSPACE
=> Back to registering both toolchains to support mac=>linux compilation

app/invocation/invocation.css, app/invocation/invocation_timing_card.tsx
Downloads the information relating to the timing sheet
=> Download profile button

enterprise/server/backends/distributed/BUILD, enterprise/server/backends/distributed/distributed.go, enterprise/server/backends/distributed/distributed_test.go, enterprise/server/util/heartbeat/heartbeat.go
=> Disable peer expiry for now

server/util/log/log.go
I made the column fixed width so it's easy to find the start of the log line.
---
=> Format logs to only include base filename.

server/config/config.go, server/libmain/libmain.go, server/util/log/log.go
=> Disable filename logging by default

server/util/log/log.go
Easy on the eyes + millisecond precision.
---
=> Set timestamp format for local logs.

server/testutil/testenv/testenv.go
=> Run tests with logLevel=debug, shortFileName=true

WORKSPACE
=> Bump go base image to latest

server/remote_cache/cachetools/cachetools.go
There are conditions where server can choose to terminate the upload
early.
---
=> Check if server closed stream early.

server/util/histogram/BUILD, server/util/histogram/histogram.go
=> Utility functions for displaying text histogram & computing percentiles.

tools/metrics/grafana/dashboards/rbeperf.json
=> Add dashboard config for RBE performance data.

server/build_event_protocol/build_event_server/build_event_server.go
=> Fix loop-var in closure

enterprise/server/util/redisutil/redisutil.go, server/config/config.go, server/environment/environment.go, server/real_environment/real_environment.go
=> Add config options to customize Redis remote execution settings.

enterprise/server/test/performance/cache/cache_test.go, server/config/config.go, server/libmain/libmain.go, server/testutil/testenv/testenv.go, server/util/log/log.go
=> Add optional zerolog hook to output log location in format compatible with GCP logging.

server/metrics/metrics.go
=> Add metric for the # of execution requests for which the client is waiting for a result.

docs/enterprise-mac-rbe.md
=> Fix typo in Mac RBE docs

server/remote_cache/action_cache_server/action_cache_server.go, server/remote_cache/content_addressable_storage_server/content_addressable_storage_server.go
=> Accept missing digests in the interfaces.Cache.ContainsMulti response.

proto/scheduler.proto, server/interfaces/interfaces.go
=> Add protos for supporting streaming task reservations over registration stream.

enterprise/server/backends/distributed/distributed.go, enterprise/server/util/cacheproxy/cacheproxy.go, server/backends/disk_cache/disk_cache.go, server/backends/memory_cache/memory_cache.go, server/remote_cache/content_addressable_storage_server/content_addressable_storage_server.go
=> Return any found digests and retry missing ones until exhausting peers.

app/flame_chart/profile_model.ts, yarn.lock
=> Organizing skyframes

.github/workflows/deps.yaml
Add original commit description
Add link to OSS repo
Preserve author information
Most importantly, remove my face from all of the Slack commit messages.
---
=> Make SHA sync commit messages more useful

server/backends/disk_cache/disk_cache.go
Initialize LRU in a background thread, and fall back to reading the disk and adding files to the LRU while loading.
All credit to @vadimberezniker for this bit of cleverness :)
=> Load LRU async to enable faster startup.

tools/metrics/grafana/dashboards/rbeperf.json
- Make sure list of workloads is refreshed automatically
- Add nicer legends for most graphs
---
=> RBE perf dashboard tweaks.

enterprise/server/backends/distributed/distributed.go, enterprise/server/backends/distributed/distributed_test.go, enterprise/server/util/heartbeat/BUILD, enterprise/server/util/heartbeat/heartbeat.go
- Don't create a new check timer for every iteration of the watch loop.
In practice the existing code will probably be okay but it's possible
that the timer branch would never be hit if the there are sufficient
number of peers sending updates.
- Use zerolog for logging
- Rename HeartbeatChannel to Channel to avoid stutter
(I'm planning to reuse this code for executor changes.)
---
=> HeartbeatChannel tweaks.

enterprise/server/backends/distributed/distributed.go, server/config/config.go
=> Bring back distributed cache healthcheck.

server/config/config.go
https://www.projectatomic.io/blog/2015/06/using-volumes-with-docker-can-cause-problems-with-selinux/
---
=> Support volume mount modes, which will allow our executors to be run on SELinux

enterprise/server/workflow/service/service.go
Depends on https://github.com/buildbuddy-io/buildbuddy/pull/319
---
=> container-recycling: Enable container and workspace reuse for CI

server/config/config.go
=> Fix missing close quote in usage string

enterprise/server/auth/auth.go
=> Support executor jwt parsing

server/config/config.go
=> container-recycling: Add config for basic runner pool limits

app/invocation/invocation.css, app/invocation/invocation.tsx, app/invocation/invocation_fetch_card.tsx, app/invocation/invocation_model.tsx, app/invocation/invocation_overview.tsx, app/invocation/invocation_tabs.tsx
=> Fetches display

buildfix.sh, proto/api_key.proto, proto/bazel_config.proto, proto/buildbuddy_service.proto, proto/context.proto, proto/distributed_cache.proto, proto/grp.proto, proto/scheduler.proto
=> cleanup: Add clang-format to buildfix.sh and fix proto format

proto/scheduler.proto, server/interfaces/interfaces.go
=> Add new task reservation method to SchedulerServer service.

server/util/disk/BUILD, server/util/disk/disk.go
=> Remove an improperly used instance of os.IsExist.

server/remote_cache/content_addressable_storage_server/content_addressable_storage_server.go
=> Make GetTree a little faster to start.

enterprise/server/backends/redis_cache/redis_cache.go
=> Avoid empty redis commands.

server/config/config.go
This option is temporary while the feature is being developed.
Eventually we can enable it by default. 
---
=> Add executor config option to enable work streaming.

enterprise/server/cmd/ci_runner/main.go, enterprise/server/test/integration/ci_runner/ci_runner_test.go
=> workflows: Default to 'test //...' if buildbuddy.yaml is missing

server/tables/tables.go
This column stores the scheduler with which the executor is registered.
This information is used to redirect task reservation requests to the scheduler that is responsible for a given executor.
---
=> Add scheduler column to executors table.

server/config/config.go
=> Add API key config option for executor.

server/remote_cache/cachetools/cachetools.go
It is unused, and causing errors in dev.
---
=> Remove unused cache dep from BatchCASUploader

BUILD, bundle.go, enterprise/server/backends/distributed/distributed.go, enterprise/server/backends/gcs_cache/gcs_cache.go, enterprise/server/backends/s3_cache/s3_cache.go, enterprise/server/util/heartbeat/heartbeat.go, enterprise/server/webhooks/bitbucket/BUILD, enterprise/server/webhooks/bitbucket/bitbucket_test.go, enterprise/server/webhooks/bitbucket/test_data/BUILD, enterprise/server/webhooks/bitbucket/test_data/test_data.go, enterprise/server/webhooks/github/BUILD, enterprise/server/webhooks/github/github_test.go, enterprise/server/webhooks/github/test_data/BUILD, enterprise/server/webhooks/github/test_data/test_data.go, enterprise/server/workflow/config/BUILD, enterprise/server/workflow/config/config_test.go, enterprise/server/workflow/config/test_data/BUILD, enterprise/server/workflow/config/test_data/test_data.go, enterprise/server/workflow/service/service.go, server/backends/disk_cache/disk_cache_test.go, server/backends/memory_cache/memory_cache_test.go, server/build_event_protocol/build_event_handler/build_event_handler_test.go, server/libmain/libmain.go, server/remote_cache/content_addressable_storage_server/content_addressable_storage_server.go, server/remote_cache/content_addressable_storage_server/content_addressable_storage_server_test.go
- Fix capture of loop variable in goroutine
- Simplify range expressions
- Simplify composite literals
- Use `go embed` directive instead of `go_embed_data` build rule
- Likely contentious change to bundle packaging
---
=> Make `gopls` and `go mod tidy` both happy

server/config/config.go
=> Add config option to require executors to present an API key.

server/tables/tables.go
=> Add group setting to use group owned executors.

server/tables/tables.go
This column indicates which group owns the executor.
---
=> Add GroupID column to ExecutionNodes table.

proto/scheduler.proto
GroupID will be part of the scheduling decisions as part of BYOR.
---
=> Add group_id to SchedulerMetadata.

app/components/button/link_button.tsx, enterprise/app/workflows/create_workflow.tsx, enterprise/app/workflows/github_import.tsx, enterprise/app/workflows/workflows.css, enterprise/app/workflows/workflows.tsx
* Add links to docs
* Change wording from "Add" to "Link"
* Don't show webhook dialog if we created a webhook automatically
Not adding the "configure" button in this PR because it requires an RPC to get the default branch name for the repo. Might add that in another PR, but I think the "Learn more" button is probably fine for now since we'll have the doc on workflow configuration that we want people to read if they decide to do more advanced configuration.
---
=> workflows: More UI improvements

enterprise/app/api_keys/api_keys.tsx
Show a tooltip on the API key label in case it is truncated w/ ellipsis.
---
=> Add title attribute to API keys

server/testutil/testenv/testenv.go
=> Instantiate Configurator once per test to avoid trigerring race detector.

enterprise/server/backends/pubsub/pubsub.go
=> Fix goroutine leak in pubsub.go

server/config/config.go
One flag to control whether the feature is enabled and one to specify
which Group ID to use for anonymous requests & for groups that do not
opt into the feature.
---
=> Add config options for enabling user owned runners.

app/capabilities/capabilities.tsx, enterprise/app/org/edit_org.tsx, enterprise/app/org/org_form.tsx, proto/config.proto, proto/grp.proto, server/buildbuddy_server/buildbuddy_server.go, server/static/static.go
This UI option is only shown if the feature is enabled on the server.
This is just the initial version to make the feature work end to
end. We will have a nicer UX before launching it to customers.
Baby's first UI change.
---
=> Add UI option to use group owned executors.

app/capabilities/capabilities.tsx, enterprise/app/api_keys/BUILD, enterprise/app/api_keys/api_keys.css, enterprise/app/api_keys/api_keys.tsx, proto/api_key.proto, proto/config.proto, server/config/config.go, server/static/static.go
=> Add ability to create API keys with 'register executor' capability.

enterprise/server/cmd/ci_runner/BUILD, enterprise/server/cmd/ci_runner/main.go, server/build_event_protocol/accumulator/BUILD, server/build_event_protocol/accumulator/accumulator.go, server/build_event_protocol/event_parser/event_parser.go
=> workflows: Add plumbing for workflow BES events

nogo_config.json
=> Disable fieldalignment analyzer for now

enterprise/server/backends/authdb/BUILD, enterprise/server/backends/authdb/authdb.go
=> Move authdb to public repo.

enterprise/server/auth/BUILD, enterprise/server/auth/auth.go, enterprise/server/backends/authdb/authdb.go, server/interfaces/interfaces.go, server/testutil/testauth/testauth.go
I decided against introducing yet another cache for group information
for the time being. We can revisit if we run into other group
information that we need to access frequently.
---
=> Add bool to JWT to indicate whether group owned executors should be used.

app/capabilities/capabilities.tsx
=> Show executors page if BYOR is enabled.

proto/scheduler.proto
=> Add version to field ExecutionNode message.

server/tables/tables.go
=> Add version column to ExecutionNodes table.

server/tables/tables.go
I took this opportunity to put the fields back to a more logical order.
---
=> Add user_id and perms columns to ExecutionNodes table.

server/rpc/filters/filters.go
=> Fix small typo in filters docstring.

server/util/log/log.go
Fixes buildbuddy-io/buildbuddy-internal#531
---
=> Fix reported source file when log_enable_gcp_logging_format is enabled.

deps.bzl
=> Fix bitset dependency in opencontainers selinux package.

server/config/config.go
=> Add config option to disable redis-native pubsub.

enterprise/server/backends/distributed/distributed.go, server/util/peerset/peerset.go
=> Fix node-duplication, backfill duplication, and double prefixing locally.

server/util/peerset/peerset.go, server/util/peerset/peerset_test.go
=> Don't attempt to backfill failed peers.

enterprise/app/executors/executors.tsx
The previous code didn't copy/paste properly into a terminal.
---
=> Fix docker command formatting.

enterprise/app/executors/executors.tsx
(This flag will go away soon.)
---
=> Fix flag format on executors page.

server/config/config.go
=> Add executor config option for default xcode version

server/backends/disk_cache/disk_cache.go
=> Lock diskcache mutex during calls to WithPrefix.

enterprise/server/backends/distributed/distributed.go
=> Set prefix and always read from local when doing hinted handoffs.

enterprise/app/executors/BUILD, enterprise/app/executors/executors.css, enterprise/app/executors/executors.tsx, enterprise/app/workflows/workflows.tsx, server/config/config.go
Nothing crazy, just a little styling polish.
---
=> Minor styling and wording tweaks for executor tab

enterprise/server/invocation_search_service/BUILD, enterprise/server/invocation_search_service/invocation_search_service.go, enterprise/server/invocation_stat_service/BUILD, enterprise/server/invocation_stat_service/invocation_stat_service.go, server/util/blocklist/BUILD, server/util/blocklist/blocklist.go
=> Add a blocklist util

enterprise/server/backends/distributed/distributed.go
=> Lock to avoid concurrent map writes.

deps.bzl, go.mod, go.sum
See https://github.com/buildbuddy-io/buildbuddy-internal/pull/569 for
motivation.
---
=> Add shellwords dependency.

tools/metrics/grafana/dashboards/buildbuddy.json
=> Add a distributed cache metrics dashboard

enterprise/server/workflow/service/service.go, server/util/lockingbuffer/BUILD
=> task-routing: Add platform props to CI runner command for improved routing

app/capabilities/capabilities.tsx, app/invocation/invocation.css, app/invocation/invocation.tsx, app/invocation/invocation_action_card.tsx, app/invocation/invocation_execution_card.tsx, app/invocation/invocation_tabs.tsx
Hopefully final attempt in creating this pr
=> Created, set up, and formatted Action Card component

server/config/config.go
=> Executor config defaults.

enterprise/server/auth/auth.go
=> Make semgrep happy in auth init code.

enterprise/server/auth/auth.go, enterprise/server/backends/authdb/authdb.go, enterprise/server/workflow/service/service.go, server/backends/invocationdb/invocationdb.go, server/build_event_protocol/target_tracker/target_tracker.go, server/interfaces/interfaces.go, server/target/target.go, server/util/db/db.go
=> OS: Run all mysql transactions with a context.

enterprise/server/util/cacheproxy/cacheproxy_test.go, server/remote_cache/byte_stream_server/byte_stream_server_test.go
This tests the fix for copyBuffer.
=> Add some tests for the copyBuffer length fix.

app/invocation/BUILD, app/invocation/invocation_action_card.tsx
=> Added remote cache address

app/format/format.tsx, app/invocation/invocation.css, app/invocation/invocation_action_card.tsx, app/invocation/invocation_execution_card.tsx
Formatted ActionCardComponent with Action Result included
=> Adding ActionResult info into ActionCardComponent

enterprise/server/workflow/service/BUILD, enterprise/server/workflow/service/service.go
=> workflows: Log more detailed errors so we can debug why workflows sometimes don't run

enterprise/server/scheduling/scheduler_server/scheduler_server.go, server/interfaces/interfaces.go
=> Add GetExecutorPoolGroupIDForUser to Scheduler interface.

tools/metrics/grafana/dashboards/buildbuddy.json
=> container-recycling: Add grafana charts for runner pool

enterprise/server/scheduling/scheduler_server/scheduler_server.go
Moved from https://github.com/buildbuddy-io/buildbuddy-internal/pull/572/files
---
=> task-routing: Respect executor ID chosen by initial scheduler probe when bouncing to another scheduler

server/config/config.go
=> [public] make task streaming on by default

app/format/format.tsx, app/invocation/invocation_action_card.tsx
removed am/pm from milli formatting
=> Quick format change on ActionCard

app/invocation/invocation_execution_card.tsx, enterprise/app/root/root.tsx
=> Deeplink fixes

tools/tcpproxy/BUILD, tools/tcpproxy/tcpproxy.go
=> Add simple TCP proxy binary for SQL access via k8s port forwarding.

enterprise/server/cmd/ci_runner/main.go
This is required to report the workflow status to GitHub.
---
=> workflows: Add missing workflow ID field to configured event

app/invocation/invocation_action_card.tsx, app/invocation/invocation_execution_card.tsx
- Remove periods from labels.
- Make entire action clickable instead of just hash header.
---
=> Slight action card tweaks

enterprise/server/backends/pubsub/pubsub.go
Otherwise, we will continue to process all messages from the beginning
of the stream.
Noticed a lot of unexpected execute status updates when I was looking at
a packet capture in dev.
---
=> Update last message ID after consuming messages from stream.

proto/workflow.proto
=> workflows: Add ExecuteWorkflow proto

.github/workflows/buildbuddy-foss.yaml
Removes enterprise directory and updates LICENSE.
---
=> Add sync workflow that updates buildbuddy-foss

enterprise/server/cmd/server/main.go, proto/workflow.proto
This makes the bundle work again
=> Update app path (inside bundle) to reflect new location.

app/format/format.tsx
- Use a more conventional dot separator for milliseconds
- Display 3 digits instead of 2 which is also more conventional
---
=> Small tweak to timestamps displayed on Action details page.

enterprise/server/backends/pubsub/BUILD, enterprise/server/backends/pubsub/pubsub_test.go, enterprise/server/testutil/testredis/testredis.go
=> Add some basic tests for the stream PubSub implementation.

buildbuddy.yaml, enterprise/server/test/performance/cache/BUILD
It's one of our slower test targets.
---
=> Run //enterprise/server/test/performance/cache:cache_test only in CI.

app/terminal/terminal.tsx
=> Clean up terminal.tsx

app/invocation/invocation_overview.tsx
Removed clickable cursor over 0 fetches
=> Zero fetches fix

enterprise/server/scheduling/scheduler_server/scheduler_server.go
=> Use AuthenticateGRPCRequest in scheduler to handle API key changes.

app/invocation/invocation_cache_card.tsx, enterprise/app/trends/trends.tsx
Use megabits per second instead of megabytes per second which is more common for networking
---
=> Show throughput in megabits per second

server/backends/chunkstore/BUILD, server/backends/chunkstore/chunkstore.go, server/backends/chunkstore/chunkstore_test.go, server/testutil/mockstore/BUILD, server/testutil/mockstore/mockstore.go
This pull request will implement chunking of blobs to support the build event log
---
=> Implement chunking for the build event log

BUILD
=> Skip the go linking phase every time you make a front-end change when using fastbuild

enterprise/BUILD
=> Enable go-less frontend fastbuild for enterprise

enterprise/server/workflow/service/service.go
=> workflows: Add missing error check

enterprise/server/test/integration/ci_runner/BUILD
It's the slowest test target in the repo at the moment.
---
=> Shard ci_runner_test to speed it up a little bit.

server/util/healthcheck/BUILD, server/util/healthcheck/healthcheck.go
=> Show healthchecks under /statusz

enterprise/server/remote_execution/execution_server/execution_server.go
=> Make failed task stream publish an error.

enterprise/app/tap/tap.tsx
=> Sort test targets in grid before paginating

app/invocation/invocation_raw_logs_card.tsx
=> Filter before paginating raw logs

server/backends/disk_cache/disk_cache.go
=> Use int64 instead of time.Time for lastUse time in fileRecords.

BUILD, server/version/BUILD, server/version/version.go
=> Read VERSION from bundle if not found elsewhere.

server/version/version.go
=> Read VERSION from bundle if not found elsewhere (redux).

app/invocation/BUILD, app/invocation/invocation.css, app/invocation/invocation.tsx, app/invocation/invocation_model.tsx, app/invocation/invocation_query_graph_card.tsx, package.json, yarn.lock
Screenshot of //app/... graph
Screenshot of //... graph
Screenshot of zooming behavior
---
=> Render DAG visualization when bazel query is run with graph output

buildbuddy.yaml
=> workflows: Move performance tests to a separate action that only runs on push to master

enterprise/server/backends/userdb/userdb.go
This extra RowsAffected check helped debug an issue with an integration test; might come in handy in the future.
---
=> userdb: Return error if group update affects 0 rows

go.mod
gopls was reporting broken imports, adding this package fixes it
---
=> Add errors pkg to `go.mod` file

proto/BUILD, proto/eventlog.proto
- proto files for event log grpc
---
=> Add proto files for the build event log

enterprise/BUILD, enterprise/bundle.go, enterprise/server/cmd/server/main.go
This is basically the same change that was made to the packaging of the normal bundle, but for enterprise
---
=> Enterprise bundle packaging change to mirror that of normal bundle

tools/probers/bazelrbe/bazelrbe.go
=> Seed random number generator in prober so that we don't generate the same inputs every time.

tools/metrics/grafana/dashboards/buildbuddy.json
Fixes https://github.com/buildbuddy-io/buildbuddy-internal/issues/653
---
=> Add prober section to Grafana dashboard.

enterprise/server/remote_execution/execution_server/BUILD, enterprise/server/remote_execution/execution_server/execution_server.go, server/metrics/metrics.go
=> Add group ID label to "pending executions" metric.

enterprise/server/util/vsock/BUILD, enterprise/server/util/vsock/vsock.go, tools/vmexec_client/BUILD, tools/vmexec_client/vmexec_client.go
We use the vsock mechanism to communicate with our vmexec server running inside the VM.
=> Add a vsock library and simple vsock client

tools/metrics/grafana/dashboards/buildbuddy.json
Otherwise we get separate time series every time the prober server
restarts.
---
=> Grafana: group prober success rate by probe

enterprise/server/remote_execution/execution_server/BUILD, enterprise/server/remote_execution/execution_server/execution_server.go, server/remote_cache/digest/digest.go, server/remote_cache/hit_tracker/BUILD, server/remote_cache/hit_tracker/hit_tracker.go, server/util/bazel_request/BUILD, server/util/bazel_request/bazel_request.go, server/util/log/BUILD, server/util/log/log.go
Will be used to add invocation ID to traces.
---
=> Extract function to get invocation ID to a separate util package.

enterprise/server/workflow/service/BUILD, enterprise/server/workflow/service/service_test.go
Don't compare proto structs directly.
---
=> Fix service_test.

enterprise/server/cmd/executor/BUILD, enterprise/server/cmd/executor/executor.go, enterprise/server/cmd/server/BUILD, enterprise/server/cmd/server/main.go, enterprise/vmsupport/bin/BUILD, server/config/config.go, server/rpc/filters/BUILD, server/rpc/filters/filters.go, server/util/grpc_server/BUILD, server/util/grpc_server/grpc_server.go, server/util/tracing/BUILD, server/util/tracing/tracing.go
=> Add basic tracing support.

enterprise/app/workflows/create_workflow.tsx
BitBucket is not fully useful as a complete CI solution yet because we don't report statuses to BitBucket. Removing the explicit mention until we fully support it.
---
=> workflows: Remove explicit BitBucket mention to reduce scope of launch

docs/workflows-setup.md
=> workflows: Add documentation on workflow execution image

server/config/config.go, server/util/tracing/tracing.go
Necessary for sending traces from local runs.
---
=> Allow Cloud Trace project ID to be specified in config.

enterprise/server/cmd/executor/BUILD, enterprise/server/cmd/executor/executor.go, enterprise/server/scheduling/scheduler_client/scheduler_client.go, enterprise/server/test/integration/remote_execution/rbetest/rbetest.go, enterprise/server/test/integration/remote_execution/remote_execution_test.go
=> Remove support for receiving tasks via incoming RPCs.

app/capabilities/capabilities.tsx, proto/config.proto, server/config/config.go, server/static/static.go
Also clean up capabilities a bit.
---
=> workflows: Set workflows capability from config flag

enterprise/server/webhooks/github/github.go
Make sure the GitHub GitProvider impl returns a gRPC error for all funcs so that we can show the complete error message from GitHub in the UI, instead of just showing "Internal error."
---
=> workflows: Fix errors displayed in UI when GitHub linking fails

enterprise/server/cmd/goinit/main.go, tools/vmexec_client/vmexec_client.go
Init: Move getty starting + root:root pw setting behind a "debugMode" flag
Init: Mount workspace filesystem on /workspace, which is the working dir set for actions
Init: Make sure Setenv sets the env to something reasonable before trying to exec commands
VMExecClient: Log when connection is setup, print cmd results to stdout/stderr
=> Tweak init and vmexec code

server/rpc/filters/filters.go, server/util/grpc_server/grpc_server.go
It's leaking goroutines. I'm looking into it.
---
=> Disable gRPC stream tracing instrumentation.

enterprise/server/testutil/testgit/testgit.go, enterprise/server/webhooks/bitbucket/bitbucket.go, enterprise/server/webhooks/bitbucket/bitbucket_test.go, enterprise/server/webhooks/github/github.go, enterprise/server/webhooks/github/github_test.go, enterprise/server/webhooks/webhook_data/BUILD, enterprise/server/webhooks/webhook_data/webhook_data.go, enterprise/server/workflow/service/BUILD, enterprise/server/workflow/service/service.go, server/interfaces/interfaces.go
Webhook payloads are now trusted whenever the event originates from within the same repo (i.e. not from a forked repo).
---
=> workflows: Update IsTrusted logic

enterprise/server/cmd/ci_runner/BUILD
Avoids a runtime dep on GLIBC.
---
=> workflows: Make the CI runner statically linked

website/sidebars.js
=> workflows: Enable sidebar section in docs site

enterprise/server/scheduling/task_router/task_router.go
=> Fix auth check in task router.

enterprise/server/remote_execution/runner/runner.go
=> Reject anon recycle attempts.

enterprise/server/auth/auth.go
=> Defensive change to make AuthenticatedUser return nil when err is set.

app/format/format.tsx, app/invocation/invocation_overview.tsx, app/root/root.css, enterprise/app/history/history_invocation_card.tsx
History cards:
Invocation overview:
---
**Related issues**: Fixes https://github.com/buildbuddy-io/buildbuddy-internal/issues/619
=> Add role badges to invocations

deps.bzl, enterprise/server/cmd/server/BUILD, enterprise/server/cmd/server/main.go, enterprise/server/util/redisutil/BUILD, enterprise/server/util/redisutil/redisutil.go, go.mod, go.sum
Issue: https://github.com/buildbuddy-io/buildbuddy-internal/issues/688
---
=> Add redis tracing instrumentation.

server/build_event_protocol/accumulator/BUILD, server/build_event_protocol/accumulator/accumulator.go, server/build_event_protocol/build_status_reporter/BUILD, server/build_event_protocol/build_status_reporter/build_status_reporter.go, server/util/timeutil/BUILD, server/util/timeutil/timeutil.go
---
**Related issues**: Fixes https://github.com/buildbuddy-io/buildbuddy-internal/issues/675
=> Show durations in GitHub statuses

app/BUILD.bazel, enterprise/app/BUILD.bazel, package.json, server/static/static.go, static/index.html, yarn.lock
This will allow us to separate locally isolated chunks of the app into separate bundles to reduce initial bundle download overhead.
---
=> Enable javascript bundle code splitting

enterprise/server/cmd/executor/executor.go, enterprise/server/cmd/server/main.go, server/util/tracing/BUILD, server/util/tracing/tracing.go
=> Give span exporter chance to flush pending spans on shutdown.

enterprise/server/remote_execution/container/BUILD, enterprise/server/remote_execution/container/container.go, enterprise/server/remote_execution/executor/BUILD, enterprise/server/remote_execution/executor/executor.go, enterprise/server/remote_execution/runner/runner.go, enterprise/server/remote_execution/workspace/BUILD, enterprise/server/remote_execution/workspace/workspace.go, enterprise/server/scheduling/priority_task_scheduler/priority_task_scheduler.go, server/util/tracing/tracing.go
=> Instrument executor task handling.

WORKSPACE, enterprise/BUILD, enterprise/server/remote_execution/containers/firecracker/BUILD, enterprise/server/remote_execution/containers/firecracker/firecracker.go, enterprise/server/remote_execution/containers/firecracker/firecracker_test.go, enterprise/vmsupport/bin/BUILD
This is still a WIP, but it functions and I'd like to get it reviewed sooner rather than later.
Tasks still remaining before this is really "ready" are:
- networking (currently there is none)
- dynamic resource limits (currently you always get 1CPU + 1GB RAM)
- diff snapshot support
- remote snapshots (where snapshots live in the cache) + snapshot compression
- agent connection setup tuning
- many more tweaks etc
=> Add a firecracker container wrapper.

server/nullauth/nullauth.go, server/testutil/testauth/testauth.go
This makes sure they're never cached by the browser - i.e. when upgrading from an unauthed to an authed.
---
=> Don't use permanent redirects in any auth code

enterprise/server/cmd/goinit/main.go, enterprise/server/remote_execution/containers/firecracker/BUILD, enterprise/server/remote_execution/containers/firecracker/firecracker.go, enterprise/server/remote_execution/containers/firecracker/firecracker_test.go, enterprise/server/util/vsock/BUILD, enterprise/server/util/vsock/vsock.go, tools/vmexec_client/BUILD, tools/vmexec_client/vmexec_client.go
=> Factor out grpc over vsock; speed up goinit, use fast kernel image.

enterprise/server/scheduling/executor_handle/BUILD, enterprise/server/scheduling/executor_handle/executor_handle.go, enterprise/server/scheduling/scheduler_server/scheduler_server.go, proto/scheduler.proto, server/config/config.go, server/interfaces/interfaces.go
=> Remove server code for non-streaming task reservations.

deps.bzl
=> Help gazelle resolve otel deps.

server/util/tracing/tracing.go
Until the first span is started on the executor side,
`trace.SpanFromContext(ctx).IsRecording` will always return false.
Change the order so that we start the span first and then check whether
it's recording.
---
=> Fix an issue with missing executor spans.

app/invocation/invocation.css, app/invocation/invocation_action_card.tsx
* Show a mini visualization of the events in ExecutedActionMetadata, color-coded by event type
* gray = waiting, orange = network, blue = command is executing, purple = misc executor work, e.g. creating the runner / workspace
* Fix the color issue of the "Worker completed" event (mentioned in https://github.com/buildbuddy-io/buildbuddy-internal/issues/672)
* Fix issue that items in the left column sometimes awkwardly break mid-word [1]
[1] Fixed left-column issue:
now renders as
---
**Version bump**: TODO 
**Related issues**: https://github.com/buildbuddy-io/buildbuddy-internal/issues/672
=> Action timeline improvements

enterprise/server/remote_execution/execution_server/BUILD, enterprise/server/remote_execution/execution_server/execution_server.go, server/util/tracing/tracing.go
=> Annotate Execute spans with task_id.

enterprise/app/trends/trends_chart.tsx
---
**Version bump**: TODO 
**Related issues**: Fixes https://github.com/buildbuddy-io/buildbuddy-internal/issues/663
=> Fix trends chart alignment

app/invocation/invocation_action_card.tsx
---
**Related issues**: Fixes https://github.com/buildbuddy-io/buildbuddy-internal/issues/709
=> Fix in-progress action card

enterprise/server/testutil/testredis/testredis.go
Fix warning that redis always logs a warning saying that it did not shut down cleanly, even though we purposely kill it in a `Cleanup` func.
---
=> Fix redis warning in tests

proto/BUILD, proto/buildbuddy_service.proto, proto/config.proto, proto/invocation.proto, server/backends/chunkstore/chunkstore.go, server/backends/chunkstore/chunkstore_test.go, server/build_event_protocol/build_event_handler/BUILD, server/build_event_protocol/build_event_handler/build_event_handler.go, server/buildbuddy_server/BUILD, server/buildbuddy_server/buildbuddy_server.go, server/config/config.go, server/eventlog/BUILD, server/eventlog/eventlog.go, server/static/static.go, server/tables/tables.go
Currently there is nothing to prevent the event logs from being written as chunks (where the frontend currently cannot retrieve them), so I intend to add a config flag to toggle this which defaults to "off" before I merge.
---
=> Server side code for log scroll

enterprise/server/scheduling/executor_handle/BUILD, enterprise/server/scheduling/executor_handle/executor_handle.go, enterprise/server/scheduling/scheduler_server/scheduler_server.go
First step towards addressing https://github.com/buildbuddy-io/buildbuddy-internal/issues/671
---
=> Clean up address-based executor ID

app/invocation/invocation_action_card.tsx
=> Don't show action result header for in-progress actions

enterprise/server/scheduling/scheduler_server/scheduler_server.go
=> Remove unused host/port from executionNode struct.

.gitignore
=> Add yarn-error.log to gitignore

enterprise/app/executors/executors.tsx, enterprise/server/scheduling/scheduler_server/scheduler_server.go, proto/scheduler.proto
Fixes https://github.com/buildbuddy-io/buildbuddy-internal/issues/549
---
=> Make executors page work for BuildBuddy group.

app/capabilities/capabilities.tsx, proto/config.proto, server/static/static.go
No more need to restrict it to BYOR-enabled installations.
---
=> Show executors page in sidebar if RBE is enabled.

app/invocation/invocation_artifacts_card.tsx
It took an extra, unused `invocationId` param which was unintentionally getting set to the event.
Also fixed a typo.
---
=> Fix event handler binding in invocation artifacts card

proto/defs.bzl
=> Fix 'Cannot read property Timestamp of undefined'

server/metrics/metrics.go, server/util/alert/BUILD, server/util/alert/alert.go
https://github.com/buildbuddy-io/buildbuddy-internal/issues/342
---
=> Add an unexpected event metric.

enterprise/app/executors/executor_card.tsx
=> Display executor ID on executors page.

server/backends/disk_cache/disk_cache.go
This will allow us to extend the disk cache to support more than one
LRU.
Part of https://github.com/buildbuddy-io/buildbuddy-internal/issues/621
---
=> Refactor disk cache to separate LRU into its own struct.

server/config/BUILD, server/config/config.go, server/util/alert/BUILD, server/util/alert/alert.go
They are not expected to be used often but are useful for specifying
more complex configuration data.
---
=> Add support for struct slice flags in configs.

enterprise/server/scheduling/scheduler_server/scheduler_server.go, enterprise/server/tasksize/tasksize.go, proto/scheduler.proto
=> Add `EstimatedComputeUnits` platform property

server/backends/disk_cache/disk_cache.go
Otherwise it doesn't show up on the statusz page.
---
=> Add default partition to partition map in fallback case.

server/backends/disk_cache/BUILD, server/backends/disk_cache/disk_cache.go
=> Ignore "not found" errors when initializing disk cache.

enterprise/server/remote_execution/runner/runner.go, enterprise/server/scheduling/priority_task_scheduler/BUILD, enterprise/server/scheduling/priority_task_scheduler/priority_task_scheduler.go, enterprise/server/scheduling/scheduler_server/BUILD, enterprise/server/scheduling/scheduler_server/scheduler_server.go, enterprise/server/tasksize/tasksize.go
=> Take resource buffer into account when determining if a task will fit on an executor

server/backends/disk_cache/disk_cache.go, server/backends/disk_cache/disk_cache_test.go, server/config/config.go
Also fixed the max size config option since it was renamed from max_size
to max_size_bytes.
---
=> Skip non-default partition directories when loading default partition.

server/tables/tables.go
=> Add redaction field to invocation table

enterprise/server/scheduling/scheduler_server/scheduler_server.go, enterprise/server/test/integration/remote_execution/rbetest/BUILD, enterprise/server/test/integration/remote_execution/rbetest/rbetest.go
=> Use the public GetExecutionNodes in tests instead of test-only GetAllExecutionNodes

enterprise/server/remote_execution/executor/executor.go
This should no longer be needed.
---
=> Remove the test timeout grace period

server/util/statusz/statusz.go
=> Fix other TZ placeholders on statusz page.

server/backends/disk_cache/disk_cache.go
=> Only skip partition dirs when initializing default partition.

enterprise/server/remote_execution/containers/docker/BUILD, enterprise/server/remote_execution/containers/docker/docker.go
=> Set Ulimits when creating docker container

.bazelrc, .github/workflows/main.yaml
=> Switch our Github Actions to use remote.buildbuddy.io

.bazelrc
=> Add `remote-dev` .bazelrc config

.bazelrc, .github/workflows/release.yaml
=> Update release config to use api key instead of certs

docs/rbe-github-actions.md
=> Update Github Actions setup guide to use api keys

app/invocation/invocation.tsx, app/invocation/invocation_model.tsx, app/invocation/invocation_targets.tsx, app/invocation/invocation_targets_card.tsx, app/root/root.css, static/image/skip-forward.svg
Skipped targets do not cause errors and are included in the target card
=> Skipped targets are nonerrors

app/footer/footer.tsx
=> Keep footer year up-to-date

app/invocation/invocation_build_logs_card.tsx, app/target/action_card.tsx, app/target/target_log_card.tsx, app/target/target_test_log_card.tsx, app/terminal/terminal.tsx, package.json, yarn.lock
Depends on https://github.com/buildbuddy-io/react-lazylog/pull/1 -- will update `package.json` / `yarn.lock` with the new commit SHA after `yarn build` + merging that PR.
---
=> Set light theme prop on terminal to improve light theme legibility.

.github/workflows/helm.yaml
=> Allow more time for executor helm chart to be released

app/auth/auth_service.ts, app/capabilities/capabilities.tsx, app/root/root.css, enterprise/app/login/BUILD, enterprise/app/login/login.tsx, enterprise/server/auth/auth.go, enterprise/server/auth/auth_test.go, enterprise/server/cmd/server/BUILD, enterprise/server/cmd/server/main.go, proto/config.proto, server/config/config.go, server/static/static.go
=> Add `Login with SSO` button

enterprise/server/remote_execution/dirtools/dirtools.go, enterprise/server/remote_execution/workspace/workspace.go
Going to use this to upload snapshot files.
=> Refactor dirhelper to accept paths instead of command.

app/flame_chart/profile_model.ts
---
**Related issues**: Fixes https://github.com/buildbuddy-io/buildbuddy-internal/issues/454
=> Sort skyframe threads numerically

rules/sha/index.bzl
This is used when generating a static js bundle release for serving via CDN.
---
=> Introduce a build rule that calculates the SHA of it inputs

app/root/root.css
- Fixes scrollbar visibility for light terminal
- Fixes dense mode shadow issue for light terminal
---
=> CSS tweaks for light terminal mode

app/invocation/invocation.tsx, app/invocation/invocation_filter.tsx, enterprise/app/tap/tap.tsx
Slashes don't currently filter correctly
---
=> Decode URL search params before filtering

app/auth/auth_service.ts, app/router/router.tsx, app/service/rpc_service.ts
=> Clean up manual encoding/decoding of URL search params

BUILD, app/BUILD.bazel, server/cmd/buildbuddy/BUILD
=> Add app bundle sha to non-enterprise target

deps.bzl
Fixes the proto packaging in `bojand/ghz` dep so that gazelle stops complaining.
---
=> Fix gazelle's proto packaging for `bojand/ghz` dep

rules/gcs/index.bzl
This will be used to release the static app bundle.
---
=> Add bazel rule for uploading files to GCS

deps.bzl
=> Fix otel package resolution and visibility.

enterprise/app/executors/executor_card.tsx, enterprise/app/executors/executors.tsx, enterprise/server/scheduling/scheduler_server/scheduler_server.go
- Organize executors by pool.
- Show version
---
=> Improvements to executors list page.

enterprise/server/scheduling/scheduler_server/scheduler_server.go
Reverts buildbuddy-io/buildbuddy#748
`zrandmember` was not added until Redis 6.2 :clown_face: :upside_down_face:
=> Revert "Track unclaimed tasks in Redis."

config/buildbuddy.dev.yaml, config/buildbuddy.local.yaml
This enables chunked event logs in local and dev configs.
---
=> Turn on chunked event logs in dev and local

docs/workflows-config.md
=> Update workflow docs

enterprise/app/history/history.tsx, enterprise/server/invocation_stat_service/invocation_stat_service.go, proto/invocation.proto
=> Filter history stats queries with global filter

enterprise/server/remote_execution/runner/runner.go, server/config/config.go
Local SSDs will be mounted using a `hostPath` volume which will appear
in a different location.
---
=> Add config option for specifying location of executor data on host.

rules/gcs/index.bzl, rules/release/index.bzl
=> Rule tweaks

enterprise/server/remote_execution/containers/firecracker/firecracker.go, enterprise/server/util/networking/networking.go, tools/enable_local_firecracker.sh
This makes networking work on vms on dev
=> Enable masquerading on the host.

app/invocation/invocation.css, app/invocation/invocation_action_card.tsx
Separated timelines for execution metadata
=> Timelines for action page

enterprise/server/remote_execution/executor/executor.go
=> Don't cache remotely executed tests that fail

enterprise/server/remote_execution/containers/firecracker/BUILD, enterprise/server/remote_execution/containers/firecracker/containeropts.go, enterprise/server/remote_execution/containers/firecracker/firecracker.go
Prevent more cross platform breakages
=> Move containeropts to a shared location (yuck).

server/util/db/db.go
Allow special chars in passwords (they'll be encoded if not already); dump out the redacted conn string on failure; pass around a URL instead of two strings
=> Improve db connection string validation/parsing.

enterprise/server/test/integration/remote_execution/remote_execution_test.go
I'm no longer able to repro the flakiness w/ 100 test runs, probably due to misc improvements we've been making to the executor + testing infra. However, it was very slow (5s) since it was copying around 100MB+ worth of files several times. So this PR updates the test to do a bit less IO (now it's about 1s which is more reasonable).
---
**Related issues**: Fixes https://github.com/buildbuddy-io/buildbuddy-internal/issues/462
=> Re-enable ComplexActionIO test

enterprise/server/remote_execution/platform/BUILD, enterprise/server/remote_execution/platform/platform.go
=> Restrict isolation types by GOOS

app/invocation/invocation.css, app/invocation/invocation_action_card.tsx
Output files in the action page can now be downloaded
=> Downloadable output files in action page

app/invocation/invocation_action_card.tsx
Patch up edits w/ css changes and internal error fixes
=> Action page fixes

server/static/static.go
=> Set cache headers for static resources with a `hash` query parameter

app/invocation/invocation.tsx, app/invocation/invocation_execution_card.tsx, app/invocation/invocation_filter.tsx
Filter/search with actionDigest for RBE actions
=> Filtering for RBE actions

enterprise/server/remote_execution/containers/firecracker/BUILD, enterprise/server/remote_execution/containers/firecracker/firecracker_test.go, server/remote_cache/cachetools/cachetools.go
=> Write files to filecache (if configured) when uploading directories.

app/invocation/invocation.tsx, app/invocation/invocation_execution_card.tsx
Moved filterComponenet inside executionComponent to remove it when there are no actions
=> Removed filter for empty actions

deps.bzl, enterprise/server/remote_execution/containers/firecracker/firecracker.go, enterprise/server/remote_execution/snaploader/BUILD, enterprise/server/remote_execution/snaploader/snaploader.go, go.mod, go.sum
=> Compress snapshots and debug log timing

proto/BUILD, proto/runner.proto
=> Add simple runner proto

enterprise/server/remote_execution/dirtools/dirtools.go
=> Fix missing error check in dirtools.getTree

server/static/static.go
Also caches a successful result so we make sure the js bundle exists on CDN, but we don't fetch a ~1MB file every 3 seconds from every App. 
---
=> Don't panic if js healthcheck returns error

enterprise/app/history/history_invocation_stat_card.tsx
=> Don't show "Unknown" users, repos, commits, hosts

app/invocation/invocation.tsx, app/invocation/invocation_model.tsx, app/target/target.tsx
They still seemed to show up as errors.
---
=> Fix up skipped targets

enterprise/app/filter/filter.css
If the breadcrumbs are too long and the filter wraps, make sure it stays on the right side of the page, since the dropdowns are anchored right.
---
=> Improve filter wrapping behavior

enterprise/server/remote_execution/executor/executor.go, enterprise/server/remote_execution/runner/runner.go
=> Pull container image outside of execution context timeout

enterprise/server/cmd/ci_runner/main.go, server/testutil/buildbuddy/BUILD
=> Support running bazel subcommands with runner.

enterprise/app/filter/filter.tsx
=> Fix off-by-one bug for date picker end date

enterprise/app/filter/filter.tsx, enterprise/app/filter/react_date_range_default_theme.css
* Make date fields editable
* Use BB blue-greyish color for date selection
---
=> Date picker tweaks

release.py
=> Make release script 2/3 compatible again.

enterprise/server/backends/distributed/distributed.go, enterprise/server/util/cacheproxy/cacheproxy.go
=> Don't trigger handoff callback until the local write is done.

enterprise/app/executors/executors.tsx
=> Delete obsolete comment from executors page code.

app/invocation/invocation_details_card.tsx, app/invocation/invocation_model.tsx, app/invocation/invocation_overview.tsx, app/router/router.tsx, enterprise/app/history/history.tsx, enterprise/app/history/history_invocation_card.tsx, enterprise/app/history/history_invocation_stat_card.tsx, enterprise/app/history/history_tabs.tsx, enterprise/app/root/root.tsx, enterprise/app/sidebar/sidebar.tsx, enterprise/app/trends/trends.tsx, enterprise/server/api/api_server.go, enterprise/server/invocation_search_service/invocation_search_service.go, enterprise/server/invocation_stat_service/invocation_stat_service.go, proto/api/v1/invocation.proto, proto/invocation.proto, proto/target.proto, server/build_event_protocol/accumulator/accumulator.go, server/build_event_protocol/build_event_handler/build_event_handler.go, server/build_event_protocol/event_parser/event_parser.go, server/tables/tables.go, server/target/target.go, static/image/git-branch-regular.svg, static/image/git-branch-white.svg
Reverts buildbuddy-io/buildbuddy#807
Squash and merge broke master.
=> Revert "Add branch info to invocations and propagate to client (buildbuddy-io/buildbuddy-internal#616)"

enterprise/server/backends/userdb/userdb.go
This has been the source of much strife a couple of times now. Better error messaging will help us to detect this early.
---
=> Add an explicit error for when we try to create a user without an email address

dockerfiles/executor_image/Dockerfile
The docker image build started failing due to the issue described here: https://www.mail-archive.com/debian-bugs-dist@lists.debian.org/msg1813971.html
```
Sending build context to Docker daemon   3.46MB
Step 1/7 : FROM gcr.io/cloud-marketplace/google/debian10@sha256:daeac4ec3dea7b7ad6f0fb689c44c02cbc43f3b6af2f0f8d43f499ac790d9298
---> 31f728ceeded
Step 2/7 : COPY data/firecracker /usr/bin/firecracker
---> 646c09c143a7
Step 3/7 : COPY data/jailer /usr/bin/jailer
---> 28d8783ce6ca
Step 4/7 : RUN apt-get update && apt-get install -y   rpm curl apt-transport-https ca-certificates gnupg-agent software-properties-common
---> Running in 9fa28d8ec9ea
Get:1 http://security.debian.org buster/updates InRelease [65.4 kB]
Get:2 http://httpredir.debian.org/debian buster InRelease [122 kB]
Get:3 …
```
=> Update executor base debian10 image to newer version.

enterprise/app/sidebar/sidebar.tsx, enterprise/server/backends/userdb/userdb.go, server/tables/tables.go
=> Display email address in sidebar and single-user group name if no name is set

app/invocation/invocation_details_card.tsx, app/invocation/invocation_model.tsx, app/invocation/invocation_overview.tsx, app/router/router.tsx, enterprise/app/history/history.tsx, enterprise/app/history/history_invocation_card.tsx, enterprise/app/history/history_invocation_stat_card.tsx, enterprise/app/history/history_tabs.tsx, enterprise/app/root/root.tsx, enterprise/app/sidebar/sidebar.tsx, enterprise/app/trends/trends.tsx, enterprise/server/api/api_server.go, enterprise/server/invocation_search_service/invocation_search_service.go, enterprise/server/invocation_stat_service/invocation_stat_service.go, proto/api/v1/invocation.proto, proto/invocation.proto, proto/target.proto, server/build_event_protocol/accumulator/accumulator.go, server/build_event_protocol/build_event_handler/build_event_handler.go, server/build_event_protocol/event_parser/event_parser.go, server/tables/tables.go, server/target/target.go, static/image/git-branch-regular.svg, static/image/git-branch-white.svg
Reverts buildbuddy-io/buildbuddy#881
Fixes `lastNDates` to `dates`
=> Add branch info to invocations and propagate to client (buildbuddy-io/buildbuddy-internal#616), second attempt

enterprise/server/invocation_stat_service/invocation_stat_service.go
=> Fix trend query column names

app/invocation/invocation.css, app/invocation/invocation_execution_card.tsx
Filtering actions by status: all, starting, cache check, queued, executing, succeeded, and errored
=> Filtering actions by status

enterprise/server/tasksize/tasksize.go
Use the default CPU estimate instead
---
=> Don't use a full CPU for small tests

server/build_event_protocol/target_tracker/target_tracker.go
=> Don't return empty target status chunk if input items are empty.

tools/rbeperf/rbeperf.go
=> Add --remote_instance_name flag to rbeperf.

app/invocation/invocation.tsx, app/invocation/invocation_execution_card.tsx, app/invocation/invocation_tabs.tsx
Tab for executions available, accessible page during dense mode
=> Execution tab when RBE enabled

enterprise/app/root/root.tsx
=> Re-enable code editor (since we serve js from GCS now)

app/invocation/invocation.tsx, app/invocation/invocation_build_logs_card.tsx
---
**Related issues**: Fixes https://github.com/buildbuddy-io/buildbuddy-internal/issues/813, Fixes https://github.com/buildbuddy-io/buildbuddy-internal/issues/694
=> Fix logs not being displayed while invocation is in progress

enterprise/app/history/history.tsx
Reverting an undesired change from #909 
---
=> Fix build history title

enterprise/app/history/history.tsx
this.state.invocations.length > 0 => Boolean(this.state.invocations?.length)
---
=> Fix history page for certain on-prem configurations

app/format/format.tsx, app/invocation/invocation.css, app/invocation/invocation_action_card.tsx, app/invocation/invocation_action_input_node.tsx
Changed to ms for <1 sec timings + output file download icon + env variable spacing
=> Action page nits / Last PR

tools/metrics/docker-compose.redis-exporter.yml, tools/metrics/grafana/dashboards/buildbuddy.json, tools/metrics/prometheus/prometheus.yml, tools/metrics/run.sh
Prometheus scraping and grafana visualization of redis metrics
=> Redis stats displayed with metrics

server/backends/disk_cache/disk_cache.go
=> Cleanup empty disk cache directories from old layout.

.github/workflows/helm.yaml
=> Wait a little longer for the executor helm chart to be published

enterprise/server/remote_execution/casfs/BUILD, enterprise/server/remote_execution/casfs/casfs.go, enterprise/server/remote_execution/casfs/casfs_darwin.go, enterprise/server/remote_execution/casfs/casfs_linux.go, enterprise/server/remote_execution/dirtools/dirtools.go
=> Make casfs lib build on Mac.

server/remote_cache/digest/digest.go
To be used by our internal tools.
---
=> Add utility to function for parsing a digest.

enterprise/server/cmd/ci_runner/main.go
=> Add API key header to build started event in synthetic workflow invocations

app/invocation/invocation_details_card.tsx
=> Remove https://github.com/ prefixes from github links

WORKSPACE
=> Bump go to latest minor version.

server/util/redact/redact.go, server/util/redact/redact_test.go
=> Remove default_override flags

docs/rbe-platforms.md
=> Add docs for private registry authentication platform props

docs/config-rbe.md
=> Add docs on static registry config

enterprise/server/remote_execution/containers/firecracker/firecracker_darwin.go, enterprise/server/remote_execution/executor/BUILD, enterprise/server/remote_execution/executor/executor.go
=> Make firecracker layout passing work on linux+mac.

enterprise/server/cmd/goinit/main.go, enterprise/server/remote_execution/dirtools/dirtools.go, enterprise/server/vmexec/BUILD, enterprise/server/vmexec/vmexec.go
Setup CASFS if the execution request contains filesystem layout
information.
---
=> Guest side changes for Firecracker CASFS support.

enterprise/server/remote_execution/casfs/casfs.go, enterprise/server/vmexec/vmexec.go, tools/vmstart/BUILD, tools/vmstart/vmstart.go
=> Update `vmstart` tool to optionally mount the FS for a given action

deps.bzl, go.mod, go.sum
Causing issues running `go fmt` on some packages.
---
=> Run `go mod tidy` to fix missing docker dep.

deps.bzl, go.mod, go.sum, server/util/db/BUILD, server/util/db/db.go
=> Remove references to `postgres`, which we don't support

enterprise/server/cmd/server/BUILD, enterprise/server/cmd/server/main.go, enterprise/server/usage_service/BUILD, enterprise/server/usage_service/usage_service.go, proto/BUILD, proto/buildbuddy_service.proto, proto/usage.proto, server/buildbuddy_server/BUILD, server/buildbuddy_server/buildbuddy_server.go, server/config/config.go, server/environment/environment.go, server/interfaces/BUILD, server/interfaces/interfaces.go, server/real_environment/real_environment.go
Getting the boring stuff out of the way
---
=> Add blank proto definition and RPC scaffolding for usage API

server/remote_cache/cachetools/cachetools.go, tools/vmstart/vmstart.go
We do this in a couple of tools already.
---
=> Add a util function to fetch action + command.

enterprise/server/backends/distributed/distributed.go, enterprise/server/backends/gcs_cache/gcs_cache.go, enterprise/server/backends/memcache/memcache.go, enterprise/server/backends/redis_cache/redis_cache.go, enterprise/server/backends/s3_cache/s3_cache.go, enterprise/server/composable_cache/composable_cache.go, enterprise/server/util/cacheproxy/BUILD, enterprise/server/util/cacheproxy/cacheproxy.go, enterprise/server/util/cacheproxy/cacheproxy_test.go, proto/distributed_cache.proto, server/backends/disk_cache/disk_cache.go, server/backends/memory_cache/memory_cache.go, server/interfaces/interfaces.go
=> Get rid of WithPrefix method on Cache.

enterprise/server/scheduling/scheduler_server/scheduler_server.go
We normally do not expect to reach the stream EOF if the leasing process
is working properly.
---
=> Bump scheduler LeaseTask stream EOF to a Warning.

enterprise/server/scheduling/scheduler_server/scheduler_server.go, enterprise/server/scheduling/task_leaser/task_leaser.go
=> Remove ping-SEND/RECV logs from lease code.

enterprise/server/scheduling/scheduler_server/scheduler_server.go
=> Add warning logs for two more error paths in task lease server.

enterprise/server/remote_execution/runner/runner.go, enterprise/server/remote_execution/workspace/workspace.go
Workspace options get set when a workspace is created - so we shouldn't re-use workspaces with differing options. 
---
=> Don't re-use workspaces with different options

server/util/hash/BUILD, server/util/hash/hash.go, server/util/hash/hash_test.go
=> Add a memhash function for later LRU use.

server/backends/disk_cache/disk_cache.go
=> Fix two data races in disk_cache.go

enterprise/server/auth/auth.go, server/backends/disk_cache/disk_cache.go, server/backends/memory_cache/memory_cache.go, server/interfaces/interfaces.go, server/util/lru/BUILD, server/util/lru/lru.go
=> Make LRU an interface; use uint64 keys in LRU.

server/backends/disk_cache/disk_cache.go, server/util/lru/BUILD, server/util/lru/lru.go
=> Support conflict keys in case of hash collision.

enterprise/server/util/vfs_server/BUILD, enterprise/server/util/vfs_server/vfs_server.go, enterprise/server/util/vfs_server/vfs_server_darwin.go, enterprise/server/util/vfs_server/vfs_server_linux.go, proto/BUILD, proto/vfs.proto
=> Add a VFS gRPC API + server based on the FUSE API.

enterprise/server/auth/auth.go, enterprise/server/backends/userdb/userdb.go, enterprise/server/saml/saml.go
=> Automatically add users who sign up via SSO to organization's group and don't add them based on domain

app/invocation/invocation_action_card.tsx
Plus misc capitalization/wording tweaks.
---
**Related issues**: Fixes https://github.com/buildbuddy-io/buildbuddy-internal/issues/862
=> Show platform props on action page

enterprise/server/backends/s3_cache/s3_cache.go, server/backends/blobstore/blobstore.go
- Adds debug logging so we can better debug hangs
- Adds 10 second timeout to waiting for bucket creation
- Builds config incrementally to stop potentially clearing the default "Endpoint" param
---
=> S3 bucket config changes

deps.bzl, go.mod, go.sum
=> Fix missing `go.mod` entries & sync deps.bzl

enterprise/server/util/vfs_server/BUILD, enterprise/server/util/vfs_server/vfs_server.go, enterprise/server/util/vfs_server/vfs_server_test.go
=> Add some basic tests for the VFS server.

docs/rbe-platforms.md
To be submitted once https://github.com/buildbuddy-io/buildbuddy/pull/967/files is merged & released.
---
=> Update docs to use remote headers for registry auth

enterprise/server/remote_execution/filecache/BUILD, enterprise/server/remote_execution/filecache/filecache.go, server/interfaces/interfaces.go, tools/vmstart/vmstart.go
=> Restore filecache from disk on startup

enterprise/server/remote_execution/containers/firecracker/firecracker_test.go
- Increase the memory from 100MB -> 200MB allotted for snapshot tests to account for the additional space needed by the vmcasfs binary.
- Add a lifecycle test that walks the fc container through its lifecycle rather than calling Run().
=> Fix firecracker tests and add one more.

docs/guide-metadata.md
=> Document branch name support for `build_metadata`

server/backends/disk_cache/disk_cache.go
storage space of "84f32b04237361149efb3ac803b8deb2defc398057729b30a90c33f65ec3f5c9" is 64 bytes.
storage space of [132 243 43 4 35 115 97 20 158 251 58 200 3 184 222 178 222 252 57 128 87 114 155 48 169 12 51 246 94 195 245 201] is 32 bytes.
Same data in both.
=> Reduce hash storage space in memory by storing as bytes.

enterprise/server/util/vfs_server/vfs_server_darwin.go
=> Fix Mac executor build.

app/invocation/invocation_logs_model.tsx
- frontend changes to support "live" event logs
Truncates the logs to not include any live section, if it exists, whenever the log updates.
Sits on top of the server-side changes branch, only changes are in `app/invocation/invocation_logs_model.tsx`
---
=> Frontend implementation for serving live event logs

enterprise/server/remote_execution/container/container.go, enterprise/server/remote_execution/runner/runner.go, server/util/capabilities/BUILD, server/util/capabilities/capabilities.go
We eventually will want a cleaner and less error-prone way to deal with anonymous users (maybe return a valid `UserInfo` object that just has an empty userID / groupID?) but this PR at least consolidates some of the existing ugliness into a centralized location.
---
=> Refactor a few anonymous user checks to use new util func

enterprise/server/cmd/server/main.go
=> Unbork for real this time

server/util/redact/redact.go
=> Redact more remote header flags

enterprise/server/remote_execution/platform/platform.go, enterprise/server/remote_execution/runner/runner.go, server/config/config.go
=> Allow for the default executor image and warmup timeout to be configurable via the executor config

deps.bzl, go.mod, go.sum, server/backends/blobstore/BUILD, server/backends/blobstore/blobstore.go, server/config/config.go
Implements an Azure blobstore for storing invocations.
Tested bucket creation and reuse, normal invocation reading / writing. All work.
=> Add an Azure blobstore implementation.

server/remote_cache/hit_tracker/hit_tracker.go
The usage tracking code was relying on the `actionCache` parameter to `makeCloseFunc`, but this was effectively always `false` and unused except by the usage tracker. `h.actionCache` is really what keeps track of whether the hit tracker is tracking hits for AC vs. CAS.
---
=> Fix usage tracking for action_cache_hits

WORKSPACE, deps.bzl, go.mod, go.sum
pre-upgrade:
Summary:
Count:	38779
Total:	10.13 s
Slowest:	183.89 ms
Fastest:	0.17 ms
Average:	1.08 ms
Requests/sec:	3829.50
Summary:
Count:	38941
Total:	10.00 s
Slowest:	232.19 ms
Fastest:	0.16 ms
Average:	1.06 ms
Requests/sec:	3893.62
post-upgrade:
Summary:
Count:	39729
Total:	10.05 s
Slowest:	161.19 ms
Fastest:	0.16 ms
Average:	1.04 ms
Requests/sec:	3953.64
Summary:
Count:	40234
Total:	10.07 s
Slowest:	255.02 ms
Fastest:	0.16 ms
Average:	1.00 ms
Requests/sec:	3995.93
=> Upgrade rules_go, protobuf, and grpc-go to latest.

enterprise/server/auth/BUILD, enterprise/server/auth/auth.go, enterprise/server/backends/userdb/userdb.go, enterprise/server/backends/userdb/userdb_test.go, enterprise/server/invocation_search_service/invocation_search_service.go, enterprise/server/saml/saml.go, server/buildbuddy_server/buildbuddy_server.go, server/interfaces/BUILD, server/interfaces/interfaces.go, server/tables/tables.go, server/testutil/testauth/BUILD, server/testutil/testauth/testauth.go
This reverts commit 273d22598346ab278cf72762e00998ba8a73ef91.
---
=> Revert "Add group roles to UserInfo interface (#1053)"

app/auth/auth_service.ts, proto/BUILD, proto/user.proto, server/buildbuddy_server/buildbuddy_server.go
Reverts buildbuddy-io/buildbuddy#1049
=> Revert "Move selected group logic to the server"

proto/.gitignore
=> gitignore symlinked protos

enterprise/server/cmd/server/main.go
=> Disable redis metrics collector

enterprise/server/cmd/executor/executor.go, enterprise/server/remote_execution/executor/executor.go, enterprise/server/remote_execution/runner/runner.go, server/config/config.go
Also removed container creation from warmup since we now know it's not
necessary.
---
=> Add config option to block executor registration on warmup.

.github/workflows/checkstyle.yaml
=> Move checkstyle "summary" outputs to "check" step

enterprise/server/remote_execution/casfs/casfs.go
This improves performance of actions that interact with many
files/directories by significantly reducing the # of kernel -> FUSE
interactions.
---
=> Allow node/attr information to be cached by the kernel.

server/remote_cache/hit_tracker/hit_tracker.go
Happens when there are no CAS hits.
---
=> Fix divide-by-0 issue in hit tracker

enterprise/app/code/BUILD, enterprise/app/code/code.tsx, enterprise/server/hostedrunner/hostedrunner.go, proto/BUILD
It's rough v0 (no commit sha or patch), and the response is just dumped into an alert - but thought it'd be nice to have these wired up.
---
=> Wire up code UI to new runner API

enterprise/server/util/cacheproxy/BUILD, enterprise/server/util/cacheproxy/cacheproxy.go, server/util/grpc_client/BUILD, server/util/grpc_client/grpc_client.go
=> Add grpc keepalive to common options and restore failfast behaviour.

enterprise/server/remote_execution/containers/docker/docker.go
Somewhat frequently while doing local RBE development I'll go into `docker.go` and patch in this code, then revert it before sending the PR for review. Figured it makes sense to add this as a flag.
---
=> Add a debug flag to stream docker command outputs to the terminal

enterprise/app/code/code.tsx
Also opens invocation in a new tab rather than just alerting the response blob.
---
=> Enable RBE for code editor

enterprise/server/remote_execution/commandutil/commandutil.go, enterprise/server/remote_execution/containers/bare/bare.go
=> Wire up stdin/stdout to support persistent workers for bare command runner

WORKSPACE, dockerfiles/executor_image/Dockerfile
=> Bump base images

server/build_event_protocol/build_event_handler/BUILD, server/build_event_protocol/build_event_handler/build_event_handler.go, server/build_event_protocol/build_event_handler/build_event_handler_test.go, server/build_event_protocol/build_event_server/BUILD, server/build_event_protocol/build_event_server/build_event_server.go, server/interfaces/interfaces.go
=> Don't return AlreadyExists errors, and mark COMPLETE only if Build Finished

enterprise/server/auth/BUILD, enterprise/server/auth/auth.go, enterprise/server/hostedrunner/BUILD, enterprise/server/hostedrunner/hostedrunner.go, server/util/authutil/BUILD, server/util/authutil/authutil.go, server/util/perms/perms.go, server/util/prefix/BUILD, server/util/prefix/prefix.go
Needed for ddisk to write user-initiated writes (managed bazel patches) with the correct prefix.
---
=> Pass effective group id along with jwt

app/root/root.css, app/terminal/terminal.tsx
=> Enable search on build logs component

enterprise/server/api/api_server.go, proto/api/v1/target.proto
=> Add tag filtering to `GetTarget` api

docs/enterprise-api.md, enterprise/server/api/api_server.go, proto/api/v1/BUILD, proto/api/v1/log.proto, proto/api/v1/service.proto, server/http/role_filter/BUILD, server/http/role_filter/role_filter.go, server/http/role_filter/role_filter_test.go
=> Add a simple `GetLog` call for fetching build logs via the API

server/util/rangemap/BUILD, server/util/rangemap/rangemap.go, server/util/rangemap/rangemap_test.go
The rangemap is used to store/lookup the range for a key.
=> Add a simple rangemap, with tests.

server/util/compression/BUILD, server/util/compression/compression.go, server/util/network/BUILD, server/util/network/network.go, server/util/retry/BUILD, server/util/retry/retry.go
These are pretty self-explan; retry is v useful
=> Add some simple utils for retry, ip parsing, and flate compression.

server/testutil/app/app.go
I rely on this heavily in gossip / raft tests where each node needs to open multiple ports and the test opens multiple nodes in parallel.
=> Make portleaser threadsafe

enterprise/app/code/code.tsx
=> Set BES args on code-initiated builds so you can debug test results

deps.bzl, go.mod, go.sum, server/gossip/BUILD, server/gossip/gossip.go, server/gossip/gossip_test.go
This is used extensively in raft to gossip information about which replicas live on which nodes.
=> Add a gossip library.

enterprise/app/code/code.tsx
We serialize the code editor's state object - this allows you to return to your changes later or refresh the page.
Now that we can serialize this state, it's easy to store this state on server / in cache instead of in local storage.
---
=> Save code editor state in local storage

enterprise/app/code/code.tsx
=> Use separate stored editor state for separate repos

enterprise/app/root/root.css
This increases available viewport when viewing on small devices like a mobile screen.
---
=> Allow the menu bar to scroll away on mobile

docs/enterprise-api.md, enterprise/server/api/BUILD, enterprise/server/api/api_server.go, enterprise/server/api/api_server_test.go, proto/api/v1/file.proto, proto/api/v1/target.proto
- Allow for target selection by label by adding `label` as a field to `TargetSelector`
- Include digest and file size when returning `File` protos
- Return `language` for targets
---
=> API improvements

enterprise/app/code/BUILD, enterprise/app/code/code.css, enterprise/app/code/code.tsx, enterprise/app/code/code_empty.tsx
=> Add code empty state

enterprise/app/code/BUILD, enterprise/app/code/code.css, enterprise/app/code/code.tsx, enterprise/app/code/code_build_button.tsx
=> Clean up code navigation and support custom commands

app/components/button/button.css, enterprise/app/code/code.css, enterprise/app/code/code.tsx, enterprise/app/code/code_build_button.tsx
=> Save custom code build/test commands and order by recency

app/components/spinner/spinner.css, app/invocation/invocation.tsx, app/invocation/invocation_build_logs_card.tsx, app/root/root.css, app/terminal/BUILD, app/terminal/terminal.tsx
=> Change the log download button on the terminal compnent so that it fetches the full log from the server

enterprise/server/test/webdriver/invocation/BUILD
=> Temporarily disable invocation webdriver test

enterprise/server/test/webdriver/invocation/BUILD, server/testutil/webtester/BUILD, server/testutil/webtester/webtester.go
=> Fix and re-enable flaky webdriver test

enterprise/config/buildbuddy.local.yaml
Enable self-auth and comment out oauth from google in the local enterprise config to simplify
running enterprise locally.
---
=> Turn on selfauth for the local enterprise config

server/util/log/log.go
Issue: https://github.com/buildbuddy-io/buildbuddy-internal/issues/977
---
=> Downgrade HTTP/gRPC request logs to debug.

enterprise/server/auth/auth.go
=> Fix loopclosure bug in auth

docs/workflows-config.md
Sending out for early review -- to be submitted after the following:
- Test workflows using `test //...` from `rules_swift` repo
---
=> Add docs for Mac workflow setup

tools/metrics/grafana/dashboards/buildbuddy.json
There's currently only one Redis instance per region.
---
=> Remove Redis instance selector from dashboard.

app/BUILD.bazel, app/components/digest/BUILD, app/components/digest/digest.css, app/components/digest/digest.tsx, app/format/format.tsx, app/invocation/BUILD, app/invocation/invocation.css, app/invocation/invocation_action_card.tsx, app/invocation/invocation_action_input_node.tsx, app/invocation/invocation_execution_card.tsx
This displays (colored) hashes and files sizes for all action inputs, which makes visually diffing action inputs easier.
Also applied these to actions outputs and the executions table.
Screenshot:
---
=> Create digest component and use it on the actions card

enterprise/server/backends/distributed/distributed.go, enterprise/server/backends/gcs_cache/gcs_cache.go, enterprise/server/backends/memcache/memcache.go, enterprise/server/backends/redis_cache/redis_cache.go, enterprise/server/backends/s3_cache/s3_cache.go, enterprise/server/composable_cache/composable_cache.go, enterprise/server/test/performance/cache/cache_test.go, enterprise/server/util/cacheproxy/cacheproxy.go, enterprise/server/util/cacheproxy/cacheproxy_test.go, proto/distributed_cache.proto, server/backends/disk_cache/disk_cache.go, server/backends/memory_cache/memory_cache.go, server/interfaces/interfaces.go
Fixes https://github.com/buildbuddy-io/buildbuddy-internal/issues/969
---
=> Delete obsolete ContainsMulti API.

app/root/root.css
Fixes https://github.com/buildbuddy-io/buildbuddy-internal/issues/481
See https://github.com/mozilla-frontend-infra/react-lazylog/issues/90#issuecomment-988285254
---
=> Fix log viewer flickering issue in non-Mac browsers

enterprise/server/remote_execution/executor/executor.go
=> Remove isActionableClientErr

tools/metrics/grafana/dashboards/buildbuddy.json, tools/metrics/grafana/provisioning/deploy/datasources/datasources.yml, tools/metrics/run.sh
Adds 'region' filter to all queries.
---
=> Switch Grafana to global prometheus instance.

enterprise/server/remote_execution/execution_server/execution_server.go, server/metrics/metrics.go, tools/metrics/grafana/dashboards/buildbuddy.json
Fixes https://github.com/buildbuddy-io/buildbuddy-internal/issues/1012
---
=> Add metric for execution request rate broken down by OS & Arch.

enterprise/app/code/code.css, enterprise/app/code/code.tsx, enterprise/app/code/code_build_button.tsx
=> Tweak code empty-state styling

enterprise/app/code/code.css, enterprise/app/code/code.tsx, enterprise/app/code/code_sidebar_node.tsx
=> More code styling tweaks

tools/metrics/docker-compose.grafana.yml, tools/metrics/docker-compose.prometheus.yml, tools/metrics/grafana/provisioning/local/datasources/datasources.yml, tools/metrics/prometheus/prometheus.yml, tools/metrics/run.sh
=> Make it possible to run local Prometheus/Grafana on mac.

enterprise/server/remote_execution/executor/BUILD, enterprise/server/remote_execution/executor/executor.go, server/metrics/metrics.go, tools/metrics/grafana/dashboards/buildbuddy.json
Use this data to display RBE prober latency by stage to make it easier
to diagnose RBE prober failures.
---
=> Add group_id to execution stage duration metric.

server/tables/tables.go
It's no longer used anywhere
---
**Related issues:** Fixes https://github.com/buildbuddy-io/buildbuddy-internal/issues/864
=> Clean up ExecutionTasks table

app/root/root.css, enterprise/app/code/code.css, enterprise/app/code/code.tsx, enterprise/app/code/code_sidebar_node.tsx, enterprise/app/root/root.tsx
* Fix issue that the page has unnecessary scrollbars on non-Mac browsers (both vertical and horizontal scrollbars)
* Sort file nodes first by type (directory vs file), then by name
* Make tree nodes clickable anywhere in the row, and add hover styling
* Avoid text wrapping of file names - instead truncate w/ ellipsis and show a tooltip
---
=> Style fixes / tweaks for BB code

tools/metrics/grafana/dashboards/buildbuddy.json
=> Fix few graphs still referencing old executor job names.

app/format/format.tsx, enterprise/app/trends/BUILD, enterprise/app/trends/cache_chart.tsx, enterprise/app/trends/trends.css, enterprise/app/trends/trends.tsx, enterprise/app/trends/trends_chart.tsx
Screenshot: https://user-images.githubusercontent.com/2414826/145885249-65a9eddc-de3d-4020-9c76-59e4c06613ba.png
---
**Related issues**: Fixes https://github.com/buildbuddy-io/buildbuddy-internal/issues/1023
=> Improve trends chart formatting

enterprise/app/code/BUILD, enterprise/app/code/code.tsx, enterprise/app/code/code_pull_request.ts
Pull `createPullRequest` into `code_pull_request.ts` and add the ability to update a pull request.
---
=> Add ability to update PR

tools/metrics/grafana/dashboards/buildbuddy.json
The pod names are slightly more useful than IPs.
---
=> Use pod names instead of IPs to identify servers in golang graphs.

tools/metrics/grafana/dashboards/buildbuddy.json
=> Retrieve list of all pools from Prometheus insetead of hardcoding.

tools/metrics/grafana/dashboards/buildbuddy.json
- Show # of ready pods in Status per-job panels.
- Show autoscaler target in autoscaler graph
- Add graph of unexpected restarts in Status row.
---
=> Integrate some useful kube state metrics into dashboard.

proto/.gitignore
=> gitignore symlinked TS defs for protos

tools/metrics/grafana/dashboards/buildbuddy.json
=> Change restart graph to show delta instead of cumulative restarts.

app/terminal/terminal.tsx
=> Don't try to wrap undefined text

tools/metrics/grafana/dashboards/buildbuddy.json
=> Add disk/network IO metrics for kubernetes nodes.

enterprise/app/sidebar/sidebar.tsx
Adding the "icon" class to get the recently added `flex-shrink: 0` styling on these.
---
=> Fix icon shrinkage in sidebar

enterprise/server/execution_service/execution_service.go
OK status code doesn't imply that exit code is zero. On linux machine,
the exit code can be 1 and status code is OK.
=> Also check exit code in tableExecToProto func

app/invocation/invocation_model.tsx
This is a response to review comments on https://github.com/buildbuddy-io/buildbuddy/pull/1356
---
=> Protect against `fileSetIDToFilesMap.get` returning undefined

app/invocation/invocation.tsx, app/invocation/invocation_action_card.tsx
Screenshot for an failed action:
=> Fetch stderr and stdout for action result

server/xcode/xcode_darwin.go
Some cleanup from code review of #1350. It will make that change apply cleaner.
---
=> Refactor XcodeLocator versionMap computation

server/util/disk/BUILD, server/util/disk/disk.go
Adds tracing to common file operations using the disk utility. Avoids changing function signatures.
---
=> Trace common disk operations

app/root/root.css, enterprise/app/root/root.css, enterprise/app/root/root.tsx
The `.page` element was updated to have absolute positioning, to the menu was rendering on top of the page.
---
=> Fix top bar CSS

deps.bzl, go.mod, go.sum
Reverts buildbuddy-io/buildbuddy#1364
=> Revert "Add cloud.google.com/go/iam dependency to fix internal build"

.github/workflows/deps.yaml
=> Copy deps.bzl to internal repo via github action

tools/metrics/grafana/dashboards/buildbuddy.json
Multiple services have the same method names (esp. names like "Read" / "Write") so the service name is used to disambiguate.
---
=> Include service name in gRPC reqs by method dashboard

server/xcode/xcode_darwin.go
`xcode-select` can even be set to the Command Line Tools, potentially allowing the executor to work without any Xcodes installed at all, as long as no non-macOS platforms are requested.
---
Fixes https://github.com/buildbuddy-io/buildbuddy-internal/issues/999.
=> Use xcode-select if default_xcode_version isn't set

deps.bzl, enterprise/server/test/integration/remote_cache/BUILD, enterprise/server/test/integration/remote_cache/remote_cache_test.go, server/testutil/testbazel/BUILD, server/testutil/testbazel/testbazel.go, server/util/bazel/BUILD
=> Add an integration test for remote cache compression

tools/metrics/grafana/dashboards/buildbuddy.json
Aggregate views will be in a separate PR.
---
=> Add CPU usage to the per-node graphs.

tools/metrics/grafana/dashboards/buildbuddy.json
=> Add cpu/disk/network overview graphs for k8s pools.

enterprise/server/auth/auth.go, enterprise/server/backends/authdb/authdb.go, enterprise/server/invocation_search_service/invocation_search_service.go, enterprise/server/invocation_stat_service/invocation_stat_service.go, enterprise/server/remote_execution/execution_server/execution_server.go, server/backends/invocationdb/invocationdb.go, server/build_event_protocol/target_tracker/target_tracker.go, server/util/db/db.go
Provide ability to specify a custom query name that will override the
labels used for exported metrics.
---
=> Reduce cardinality of some common SQL metrics.

website/blog/introducing-buildbuddy-v2.md, website/blog/meet-buildbuddy-workflows.md, website/blog/welcoming-brentley-jones.md, website/blog/welcoming-george-li-head-of-sales.md, website/blog/welcoming-lulu-zhang.md
=> Migrate a few more blog image paths that didn't make it into the last PR

website/src/css/general.css, website/src/css/markdown.css, website/src/css/nav.css
=> Misc marketing website css changes

website/package.json, website/yarn.lock
=> Upgrade docusaurus version and add lucide-react & plugin-ideal-image deps

website/src/pages/enterprise-terms.md, website/src/pages/privacy.md, website/src/pages/security-updates.md, website/src/pages/security-vulnerability-report.md, website/src/pages/security.mdx, website/src/pages/terms.md
=> Migrate static markdown pages to new marketing site

website/src/pages/team.module.css, website/src/pages/team.tsx
=> New team page on marketing website

website/src/pages/careers.module.css, website/src/pages/careers.tsx, website/src/pages/jobs/senior-site-reliability-engineer.md, website/src/pages/jobs/senior-software-engineer.md, website/src/pages/jobs/software-engineer.md, website/src/pages/jobs/solutions-engineer.md
=> Add careers page and job listings to marketing website

website/theme/BlogSidebar/index.tsx, website/theme/BlogTagsPostsPage/index.tsx
=> Tweaks to fix up marketing website theme

website/src/pages/open-source-repos.module.css, website/src/pages/open-source-repos.tsx
=> New open source repos powered by buildbuddy page

website/src/pages/pricing.module.css, website/src/pages/pricing.tsx
Self-service tier is hidden for now
---
=> New pricing page on marketing website

website/docusaurus.config.js, website/empty/index.md, website/src/css/general.css, website/src/pages/index.tsx
=> Update docusaurus config and add new homepage

website/src/components/brands/brands.module.css, website/src/components/brands/brands.tsx, website/src/pages/open-source-repos.tsx
=> Style tweaks for safari

website/src/components/apply/apply.tsx, website/src/css/common.module.css, website/src/pages/contact.tsx, website/src/pages/open-source-repos.tsx, website/src/pages/request-demo.tsx, website/src/pages/request-quote.tsx
=> Give some feedback when clicking submit on forms

website/blog/introducing-buildbuddy-v1.md, website/blog/meet-buildbuddy.md, website/src/pages/jobs/senior-site-reliability-engineer.md, website/src/pages/jobs/senior-software-engineer.md, website/src/pages/jobs/software-engineer.md, website/src/pages/jobs/solutions-engineer.md, website/src/pages/security-updates.md, website/src/pages/security.mdx
=> Fix some website typos

website/src/components/apply/apply.tsx, website/src/css/common.module.css, website/src/css/general.css, website/src/pages/careers.module.css, website/src/pages/careers.tsx, website/src/pages/contact.module.css, website/src/pages/contact.tsx, website/src/pages/jobs/senior-site-reliability-engineer.md, website/src/pages/jobs/senior-software-engineer.md, website/src/pages/jobs/software-engineer.md, website/src/pages/jobs/solutions-engineer.md, website/src/pages/open-source-repos.tsx, website/src/pages/request-demo.tsx, website/src/pages/request-quote.tsx, website/src/pages/security-updates.md, website/src/pages/security-vulnerability-report.md, website/src/pages/security.mdx
=> More marketing website polish

tools/metrics/grafana/dashboards/buildbuddy.json
=> Only show kube node/pool information for the current region.

enterprise/server/cmd/ci_runner/run_local.sh
* Update docker image version
* Fix outdated argument names
* Fix runner binary path; for some reason it doesn't get output under `bazel-bin` anymore
* Simplify/clarify configuration options
---
=> Fix CI runner run_local.sh script

enterprise/server/remote_execution/runner/runner.go
=> Don't ignore workspace creation errors

website/blog/whats-new-in-bazel-5-0.md
=> Set a better `og:description` for "What's New in Bazel 5.0"

website/blog/whats-new-in-bazel-5-0.md
- Link to the official release post
- Add some more changes
- Add periods to each change that is a sentance
---
=> Apply some updates to the "What's New in Bazel 5.0" blog post

server/tables/tables.go
In the sqlite case, we perform the invocation_uuid migration by renaming TargetStatuses to TargetStatusesOld, then letting GORM create a fresh TargetStatuses table for us, then copying the old rows to the new table and deleting the old table. But this freshly created table won't have the target_status_invocation_uuid index, so the DROP INDEX statement fails. Fixed by moving this DROP INDEX logic to the mysql case only.
---
=> Fix migration error for SQLite

app/invocation/invocation.css, app/invocation/invocation_action_card.tsx, app/invocation/invocation_model.tsx, app/root/root.css
Example:
---
**Related issues**: Fixes https://github.com/buildbuddy-io/buildbuddy-internal/issues/1074
=> Action page: provide more helpful messaging when results are not found

enterprise/app/executors/executor_card.tsx, enterprise/app/executors/executors.css
Recommend reviewing with whitespace diff disabled -- https://github.com/buildbuddy-io/buildbuddy/pull/1454/files?diff=split&w=1
Before (executor details have extra top margin):
After:
---
=> Fix and clean up executor card CSS

website/src/css/general.css
See https://css-tricks.com/fixed-headers-and-jump-links-the-solution-is-scroll-margin-top/ for background
---
=> Website: Prevent navbar from covering jump link targets

proto/target.proto
-- Add pagination token to GetTarget Request/Response
-- Add a version field to GetTarget to indicate which sql query to run.
=> TestGrid:  Proto Change for GetTargets

enterprise/server/hostedrunner/hostedrunner.go
=> Use hosted bazel pool for hosted bazel invocations.

enterprise/app/history/history_invocation_card.tsx
It's common for patterns to end in ellipsis which is displayed with 6
dots in the UI.
---
=> Remove ellipsis from in progress invocations.

website/blog/whats-new-in-bazel-5-0.md
I over-applied a change I was making.
---
=> Revert title capitalization change

app/invocation/invocation.tsx
---
**Related issues**: https://github.com/buildbuddy-io/buildbuddy-internal/issues/936
=> Fix NPE when clicking skipped targets

website/docusaurus.config.js, website/src/css/general.css, website/src/css/markdown.css, website/src/css/nav.css
Makes navigating docs easier and require much less clicking by expanding sidebar items by default.
---
=> Docs sidebar tweaks

website/blog/how-bazel-5-0-makes-your-builds-faster.md
=> Add custom og:description to "How Bazel 5.0 Makes Your Builds Faster"

server/build_event_protocol/target_tracker/target_tracker.go
Bug was introduced in https://github.com/buildbuddy-io/buildbuddy/commit/c488d640e201dcab982476adb60f776c31af99ec
=> Fix TargetStatuses Insert Statement

proto/raft.proto
Add protos to support raft functionality
=> Add protos to support raft functionality

proto/BUILD, proto/raft_service.proto
Add a raft service proto and update BUILD file
=> Add a raft service proto and update BUILD file

server/config/config.go, server/gossip/gossip.go, server/util/disk/BUILD, server/util/disk/disk.go, server/util/rangemap/rangemap.go
Misc util changes to support raft
=> Misc util changes to support raft

deps.bzl, enterprise/server/raft/config/BUILD, enterprise/server/raft/config/config.go, enterprise/server/raft/constants/BUILD, enterprise/server/raft/constants/constants.go, enterprise/server/raft/keys/BUILD, enterprise/server/raft/keys/keys.go, enterprise/server/raft/listener/BUILD, enterprise/server/raft/listener/listener.go, enterprise/server/raft/rbuilder/BUILD, enterprise/server/raft/rbuilder/rbuilder.go, go.mod
Add some basic raft dependencies and libs
=> Add some basic raft dependencies and libs

enterprise/server/raft/client/BUILD, enterprise/server/raft/client/client.go, enterprise/server/raft/nodeliveness/BUILD, enterprise/server/raft/nodeliveness/nodeliveness.go, enterprise/server/raft/nodeliveness/nodeliveness_test.go, enterprise/server/raft/rangecache/BUILD, enterprise/server/raft/rangecache/rangecache.go, enterprise/server/raft/rangecache/rangecache_test.go, enterprise/server/raft/rangelease/BUILD, enterprise/server/raft/rangelease/rangelease.go, enterprise/server/raft/rangelease/rangelease_test.go, enterprise/server/raft/registry/BUILD, enterprise/server/raft/registry/registry.go, enterprise/server/raft/registry/registry_test.go, enterprise/server/raft/sender/BUILD, enterprise/server/raft/sender/sender.go
Add a grpc client, node/range-leases, registry, and sender
=> Add a grpc client, node/range-leases, registry, and sender

enterprise/server/webhooks/github/github.go
---
**Related issues**: Fixes https://github.com/buildbuddy-io/buildbuddy-internal/issues/1090
=> Ignore branch deleted events

server/util/query_builder/query_builder.go, server/util/query_builder/query_builder_test.go
This CR is a pre-requisite for the following test grid pagination
change.
[This PR](https://github.com/buildbuddy-io/buildbuddy/pull/1482/files#diff-72fad2fce310970a3d589c6338bd9f828d6519eb05d4c3b4993ce223bd786911R184) demonstrates how this will be used.
=> Add support for join a subquery in query_builder

enterprise/server/remote_execution/containers/firecracker/firecracker.go
(I believe this was probably unintentional, but lmk if not)
---
=> Firecracker: Fix value receiver for SendExecRequestToGuest

enterprise/config/buildbuddy.raft.yaml, tools/goreman/procfiles/Procfile.raft
Add some configs for quickly running a raft cluster
=> Add some configs for quickly running a raft cluster

server/ssl/ssl.go
Set email field in certmanager.
=> Set email field in certmanager.

website/blog/meet-buildbuddy-workflows.md
Swapped the first and second sections to make the truncated version a better representation of the full article.
---
=> Make workflows blog post truncation-friendly

website/blog/whats-new-in-bazel-5-0.md
=> Remove stray period

website/blog/buildbuddy-joins-y-combinator.md
=> Fix some blog image references

website/blog/buildbuddy-v1-0-6-release-notes.md, website/blog/buildbuddy-v1-1-0-release-notes.md, website/blog/buildbuddy-v1-2-1-release-notes.md, website/blog/buildbuddy-v1-3-0-release-notes.md, website/blog/buildbuddy-v1-4-0-release-notes.md, website/blog/buildbuddy-v1-5-0-release-notes.md, website/blog/buildbuddy-v1-8-0-release-notes.md, website/blog/buildbuddy-v2-5-0-release-notes.md, website/blog/buildbuddy-v2-7-0-release-notes.md, website/blog/how-bazel-5-0-makes-your-builds-faster.md, website/blog/introducing-buildbuddy-v1.md, website/blog/introducing-buildbuddy-v2.md, website/blog/meet-buildbuddy-workflows.md, website/blog/whats-new-in-bazel-5-0.md
=> Add truncation to blog posts

docs/config-storage.md
=> Add docs for Azure storage

enterprise/server/auth/auth.go, enterprise/server/auth/auth_test.go, server/testutil/testauth/testauth.go
Fixes https://github.com/buildbuddy-io/buildbuddy-internal/issues/1037
=> Last API key should win

website/theme/BlogPostItem/index.tsx, website/theme/BlogPostItem/styles.module.css
=> More prominent "Read More" styling on blog for truncated posts

website/src/css/general.css
=> Docs table of contents styling tweaks

server/build_event_protocol/build_event_handler/build_event_handler.go
This should fix some customer builds which are often retried and run into this. The larger fix is coming as part of https://github.com/buildbuddy-io/buildbuddy-internal/issues/1039
=> Be surgical in choosing the the errors that break invocations.

tools/metrics/grafana/dashboards/buildbuddy.json
=> Grafana: filter jobs & executor pools by selection region.

docs/enterprise-mac-rbe.md
=> Add updating guidance to Mac RBE docs

enterprise/app/code/code.css, enterprise/app/code/code.tsx
=> [Code editor] Add revert button to each change in changes pane

server/tables/tables.go
invocation_pk is a primary key field so it's not nullable. We need to
set a default value otherwise insert without specifying this value will
fail
=> Drop invocation_pk index and set default value

app/invocation/invocation_execution_card.tsx
@brentleyjones pointed out that this didn't match our naming scheme anywhere else and is thus confusing to users.
---
=> Change "Worker" to "Executor Host ID" in execution card for consistency

enterprise/server/remote_execution/containers/firecracker/firecracker.go
=> Firecracker: Fix error propagation when copying outputs fails

enterprise/app/code/code.css, enterprise/app/code/code.tsx
=> [Code editor] Allow editing PR title & description when sending

enterprise/app/code/BUILD, enterprise/app/code/code.css, enterprise/app/code/code.tsx
- Pins workspace to a specific commit SHA (pins head commit if not set)
- Support updating pinned commit SHA to head
- Support resolving conflicts when updating commit SHA with a diff viewer / editor
- Adds breadcrumbs to show pinned commit SHA (and gives a UI entry-point for updating)
---
=> [Code editor] Pins commit SHA, support updating it, and add breadcrumbs

enterprise/app/code/code.tsx
=> Make sure commit SHA is up to date and there are no merge conflicts when requesting a review

proto/BUILD, proto/build_event_stream.proto, proto/failure_details.proto
Fixes https://github.com/buildbuddy-io/buildbuddy-internal/issues/1161
=> Re-add the buildbuddy changes to the build_event_stream proto

docs/troubleshooting-rbe.md
This language was way out of date.
---
=> Update wording on free-tier Cloud Macs.

server/build_event_protocol/target_tracker/target_tracker.go
https://github.com/buildbuddy-io/buildbuddy-internal/issues/1160
=> Set TestStatus to FAILED_TO_BUILD when success is false

app/components/digest/digest.css, app/invocation/invocation.css, app/invocation/invocation_action_input_node.tsx, app/invocation/invocation_execution_card.tsx
* Remove some rules that result in small/difficult-to-read text
* Fix corner rounding on digest component when its width is smaller than its parent's width
---
---
---
**Related issues**: Fixes https://github.com/buildbuddy-io/buildbuddy-internal/issues/1043
=> CSS tweaks for executions + action pages

enterprise/app/trends/trends_chart.tsx
Set explicit widths to prevent wrapping.
Before:
After:
---
=> Fix y-axis label wrapping

enterprise/app/tap/tap.tsx
- Use `response.next_page_token` to determine whether more invocations can be loaded (x-axis "load more" button) and pass the current page token along in each request
- Merge target histories from subsequent pages into the current list of target histories
TODO in subsequent PRs:
- Improve the page layout so that target names remain visible while scrolling horizontally
- I noticed that the last ~2 fetches or so fetch a very small number of commits -- need to work out whether that's a bug on the client or server. But it shouldn't block this PR, since the V1 UI should still be the same after this PR is merged.
Demo (outlined squares mean "not executed")
https://user-images.githubusercontent.com/2414826/153279082-eef99792-8d65-4970-80bc-456ceb594cda.mp4
<details>
<summary>Script that was used …
=> Implement page-by-page fetching for test grid V2

server/build_event_protocol/accumulator/accumulator.go, server/build_event_protocol/target_tracker/BUILD, server/build_event_protocol/target_tracker/target_tracker.go, server/build_event_protocol/target_tracker/target_tracker_test.go
1. Add an accumulator interface; so that I can create a fake
accumulator in the test.
2. Add tests that test the code handling TestResult, TestSummary, Aborted,
TestComplete events.
=> Add tests to target tracker

app/alert/alert.tsx
=> Fix small alert icon

app/compare/compare_invocations.tsx, app/compare/diff_preprocessing.tsx, app/invocation/invocation.tsx, app/invocation/invocation_model.tsx, app/invocation/invocation_query_graph_card.tsx, app/invocation/invocation_suggestion_card.tsx
=> Remove UI deps on inline console buffer

enterprise/server/auth/auth.go, enterprise/server/saml/saml.go, server/config/config.go
=> Add auth config for https_only_cookies

enterprise/server/api/api_server.go, enterprise/server/backends/authdb/authdb.go, enterprise/server/backends/userdb/userdb.go, enterprise/server/execution_service/execution_service.go, enterprise/server/hostedrunner/hostedrunner.go, enterprise/server/usage/usage_test.go, enterprise/server/usage_service/usage_service.go, enterprise/server/workflow/service/service.go, server/backends/github/github.go, server/backends/invocationdb/invocationdb.go, server/build_event_protocol/build_status_reporter/build_status_reporter.go, server/build_event_protocol/webhooks/webhooks.go, server/interfaces/interfaces.go, server/util/db/db.go
This is actually cleanup of the initial run for reducing dependencies on `db.go`. This CL
removes the `Raw` call from the `DBHandle` interface. This call was initially added to cut
down on the complexity of the CL that initially reduced dependencies.
The motivation for reducing depencies on the `db.go` file is that that file is forced to
use structs from an external library containing cgo, and that was breaking when we built
the executor. To avoid a recurrence of that extremely puzzling error, only files that
absolutely *must* depend on `db.go` will do so (`libmain.go` and `testenv.go`).
---
=> 1/6 Reduce db dependencies

enterprise/server/api/BUILD, enterprise/server/api/api_server.go
=> Migrate deprecated timestamp fields in api server

app/target/BUILD, app/target/target.tsx
=> Migrate test summary to new timestamp field

enterprise/server/backends/pubsub/pubsub_test.go, enterprise/server/test/integration/remote_execution/rbetest/rbetest.go, enterprise/server/test/integration/task_router/task_router_test.go, enterprise/server/testutil/buildbuddy_enterprise/buildbuddy_enterprise.go, enterprise/server/testutil/testredis/testredis.go, enterprise/server/usage/usage_test.go, enterprise/server/util/redisutil/redisutil_test.go
=> Add ability to restart Redis in tests.

enterprise/server/cmd/ci_runner/BUILD, enterprise/server/cmd/ci_runner/main.go
=> Populate StartTime and Duration in ci_runner

app/invocation/BUILD, app/invocation/dense/dense_invocation_overview.tsx, app/invocation/invocation_details_card.tsx, app/invocation/invocation_model.tsx, app/invocation/invocation_overview.tsx
=> Migrate StartTime and TotalRunDuration in invocation_model

enterprise/server/auth/BUILD, enterprise/server/auth/auth.go, server/backends/github/BUILD, server/backends/github/github.go, server/config/config.go, server/util/url/BUILD, server/util/url/url.go, server/util/url/url_test.go
Don't allow redirects that are not on this server.
=> Don't allow redirects that are not on this server

deps.bzl, go.mod, go.sum
Should fix https://github.com/buildbuddy-io/buildbuddy/security/dependabot/15
=> Update mongodb dependency version (sigh).

enterprise/server/remote_execution/containers/firecracker/firecracker.go
When recycling a runner (returning it to the runner pool) we first call `Pause`, and if `Pause` returns an error, we abort the recycle attempt and don't add the runner to the pool.
Since firecracker calls `Remove` as part of `Pause`, this PR ensures that `Pause` returns an error if `Remove` fails -- otherwise, the container might be in a weird / unexpected state when we later try to resume, due to the removal failure.
---
=> Firecracker: Don't ignore errors from `Remove`

server/build_event_protocol/webhooks/BUILD, server/build_event_protocol/webhooks/webhooks.go
=> Allow stale reads in webhook query

enterprise/server/remote_execution/containers/firecracker/firecracker.go
---
**Related issues**: Fixes https://github.com/buildbuddy-io/buildbuddy-internal/issues/1184
=> Firecracker: Handle ENXIO errors in mergeDiffSnapshot

server/backends/github/github.go
=> Validate another redirect_url

enterprise/server/auth/auth.go, server/config/config.go
Some auth providers don't support this / don't enable this.
---
=> Add option to disable requesting refresh token scope

server/build_event_protocol/build_event_handler/build_event_handler.go, server/metrics/metrics.go, tools/metrics/grafana/dashboards/buildbuddy.json
=> Add grafana charts for invocation finalizer metrics

server/build_event_protocol/build_event_handler/build_event_handler.go
Wrap all goroutines with the appropriate `errGroup.Go(func()...)` (I erroneously removed some of these in the last PR).
---
=> Fix panic during server shutdown caused by sending on closed channel

enterprise/server/scheduling/scheduler_client/scheduler_client.go, enterprise/server/test/integration/remote_execution/remote_execution_test.go
=> Make pool name case insensitive

cli/cmd/sidecar/sidecar.go, docs/cloud.md, docs/enterprise-api.md, docs/guide-auth.md, docs/rbe-setup.md, docs/workflows-config.md, enterprise/server/cmd/ci_runner/run_local.sh, server/config/config.go, tools/rbeperf/rbeperf.go, website/blog/meet-buildbuddy-workflows.md
=> Clean up remaining cloud. => remote.

enterprise/server/remote_execution/platform/platform.go, enterprise/server/remote_execution/runner/BUILD, enterprise/server/remote_execution/runner/runner.go, server/config/config.go
=> Use podman to run remote_execution

enterprise/server/scheduling/scheduler_server/scheduler_server.go
If the owning scheduler for an executor happens to be the local
scheduler, call into the scheduler code directly instead of issuing an
RPC.
This simplifies on-prem deployments with a single app as we no longer
need to care about whether the hostname is set up correctly.
Fixes https://github.com/buildbuddy-io/buildbuddy-internal/issues/1179
---
=> Short-circuit task reservation enqueues to local server.

app/alert/alert.css, app/alert/alert.tsx, app/alert/alert_service.ts, app/auth/BUILD, app/auth/auth_service.ts
Does so by calling GetUser every 30 min.
If we get a Unauthenticated or PermissionDenied error from this call, we show a yellow "Logged out" banner and redirect to the login screen.
---
=> Refresh auth token every 30 min if necessary

enterprise/server/remote_execution/runner/runner.go
=> Return p.buildRoot when docker is not enabled

server/libmain/libmain.go, server/static/static.go
Paths served by the static file server required a trailing slash, which was potentially confusing.
---
=> Remove need for trailing slash for some URLs

server/buildbuddy_server/BUILD, server/buildbuddy_server/buildbuddy_server_test.go
Add smoke tests `GetInvocation`, `UpdateInvocation`, `SearchInvocation`, and `DeleteInvocation`.
---
=> Add tests for Invocation API in `buildbuddy_server`

enterprise/server/remote_execution/containers/podman/podman.go, enterprise/server/remote_execution/runner/runner.go
Addresses @bduffany's comment in https://github.com/buildbuddy-io/buildbuddy/pull/1660.
=> Pass buildRoot to Podman in runner

enterprise/server/workflow/service/service.go
---
**Related issues**: Fixes https://github.com/buildbuddy-io/buildbuddy-internal/issues/1213
=> Disallow Mac workflows from untrusted PRs

enterprise/server/remote_execution/containers/podman/podman.go, enterprise/server/remote_execution/containers/podman/podman_test.go, enterprise/server/remote_execution/runner/runner.go
=> Implement ForceRoot option in podman

enterprise/server/scheduling/scheduler_server/scheduler_server.go
It seems to do more harm than good.
---
=> Remove useless log line.

enterprise/server/cmd/ci_runner/main.go
When running with a local executor, `HOME` is `/` which causes problems for bazelisk (it tries to write `/.cache/bazelisk`) and bazel (which needs to write `~/.cache/bazel`). Also `USER` is unset, which is needed by Bazel (it needs to write `~/.cache/bazel/_bazel_$USER`).
This PR sets `HOME` to `$PWD/.home` and `USER` to `buildbuddy` in this case.
---
=> Fix local CI runner env

.bazelrc
=> Retry flaky tests on workflows & github actions

website/docusaurus.config.js, website/src/components/brands/brands.module.css, website/src/components/brands/brands.tsx, website/src/components/hero/hero.module.css, website/src/components/hero/hero.tsx, website/src/components/integrations/integrations.module.css, website/src/components/integrations/integrations.tsx, website/src/components/logs/logs.tsx, website/src/components/oss/oss-list.tsx, website/src/components/oss/oss.tsx, website/src/pages/features.tsx, website/src/pages/team.tsx, website/src/pages/ui.tsx
- Make image loading smoother
- Enable lazy image loading in dev so we catch these kinds of issues earlier
- Set alt tags for images
---
=> Website polish

server/tables/tables.go, server/target/target.go
Reverts buildbuddy-io/buildbuddy#1696
=> Revert "Add command to test grid query"

website/docusaurus.config.js, website/src/pages/features.tsx
=> Make features nav item clickable

.bazelrc
=> De-flake PR builds too

server/config/config.go
Don't need to continue here, switch breaks from cases by default in golang and only falls through if it hits the `fallthrough` keyword
---
=> Remove extraneous continue

enterprise/server/cmd/executor/BUILD, enterprise/server/cmd/executor/main_test.go, enterprise/server/cmd/server/BUILD, enterprise/server/cmd/server/main_test.go, server/cmd/buildbuddy/BUILD, server/cmd/buildbuddy/main_test.go, server/config/config.go, server/util/testing/flags/BUILD, server/util/testing/flags/flags.go
Add tests to ensure newly added flags which contain a `.` are all known to the yaml config.
---
=> Add tests for flag correctness

proto/BUILD, proto/buildbuddy_service.proto, proto/github.proto, server/buildbuddy_server/BUILD, server/buildbuddy_server/buildbuddy_server.go, server/role_filter/role_filter.go
---
**Related issues**: https://github.com/buildbuddy-io/buildbuddy-internal/issues/1236
=> Add boilerplate for UnlinkGitHubAccount RPC

app/invocation/invocation_details_card.tsx
* Fix issue that bazel startup options shown in "original command line" are empty. Turns out that this is actually a Bazel issue and nothing to do with event handling on our side (confirmed by adding some debug logging to a local build of Bazel)
* Make flag names clickable
---
**Related issues**: Fixes https://github.com/buildbuddy-io/buildbuddy-internal/issues/1237
=> Command line UI tweaks

enterprise/server/webhooks/github/github.go
---
**Related issues**: Fixes https://github.com/buildbuddy-io/buildbuddy-internal/issues/761
=> Run workflows when PR base branch changes

server/remote_cache/cachetools/cachetools.go
=> Short-circuit upload of empty content.

cli/remotebazel/remotebazel.go
=> Don't try to patch things that haven't changed.

cli/remotebazel/remotebazel.go
=> Allow remote bazel to be launched from subdirectories.

cli/remotebazel/remotebazel.go
When a chunk is finalized, the volatile portion of the log moves from
the current chunk to the next chunk. If we draw the finalized chunk
without delay, the volatile portion is removed and then printed again
when the next (live) chunk retrieved. To avoid this flicker, we delay
printing the finalized chunk until we retrieve the next chunk with the
volatile log.
---
=> Fix log flicker when chunk is finalized.

app/auth/user.ts, app/menu/menu.tsx, enterprise/app/history/history.tsx, enterprise/app/sidebar/sidebar.tsx
=> Remove special case default group logic and enable org creation

enterprise/server/hostedrunner/BUILD, enterprise/server/hostedrunner/hostedrunner.go
Avoids having to deal with host ssh keys.
---
=> Use https for remote bazel git operations.

enterprise/server/remote_execution/executor/executor.go
This will help us understand whether there are errors other than ErrSIGKILL which need to be retried.
---
=> Log non-retriable execution errors

docs/workflows-config.md
* Add docs about the new wildcard support
* Document `buildbuddy.bazelrc`
* Re-arrange things a bit and update the wording so that things flow a bit better
To be submitted after this week's release.
---
=> Update workflows documentation

docs/rbe-microvms.md, website/sidebars.js
=> Add docs page for RBE with Firecracker

enterprise/server/remote_execution/containers/podman/podman.go
* Implement the same fix as https://github.com/buildbuddy-io/buildbuddy/pull/1698 but for podman.
* Changed the `Remove()` command to run `podman kill --signal=KILL <name>` instead of `podman rm --force <name>` to ensure that the container is immediately removed, rather than attempting a graceful shutdown. Without this change, the `bazel` process created by the CI runner keeps chugging along during executor shutdown, which is not desired. (Docker doesn't seem to have this issue.) Note that the container is still removed even though we no longer call `rm` explicitly, since we run the container with the `--rm` flag.
---
=> Ensure podman exec commands are retried during executor shutdown

enterprise/app/tap/tap.tsx
---
**Related issues**: Fixes https://github.com/buildbuddy-io/buildbuddy-internal/issues/1261
=> Don't re-fetch targets when filtering

cli/autoconfig/autoconfig.go
=> Don't attempt to modify workspace if using remote bazel

enterprise/server/cmd/ci_runner/main.go, enterprise/server/test/integration/ci_runner/ci_runner_test.go
We no longer invoke it with multiple actions. This allows some of the
code to be simplified.
---
=> Remove multiple action support from ci_runner.

enterprise/server/hostedrunner/hostedrunner.go, proto/runner.proto
@siggisim This will require some changes to the Code UI. 
---
=> Require user of Run API to specify either branch or commit_sha.

server/util/flagutil/flagutil.go
Addresses buildbuddy-io/buildbuddy-internal#1266
---
=> Fix panic when printing flag usage

server/config/config.go
=> Fix remote execution -> default redis fallback when shard config is set.

enterprise/server/cmd/ci_runner/main.go
=> Add missing newline in runner.

cli/remotebazel/remotebazel.go, enterprise/app/code/code.tsx, enterprise/server/hostedrunner/hostedrunner.go, proto/runner.proto
=> Pass patches as bytes to support binary patches.

cli/remotebazel/BUILD, cli/remotebazel/remotebazel.go, deps.bzl, go.mod, go.sum
Selected choice is stored in the repo git config.
---
=> Prompt user if the repo has multiple remotes.

enterprise/server/webhooks/github/github.go
=> Revert "Run trusted workflows on events from trusted forks (#1744)"

cli/cmd/bb/bb.go, cli/remotebazel/BUILD, cli/remotebazel/remotebazel.go
=> Propagate remote bazel exit code.

enterprise/server/scheduling/priority_task_scheduler/priority_task_scheduler.go
---
**Related issues**: https://github.com/buildbuddy-io/buildbuddy-internal/issues/1192
=> Add workaround for CloseAndRecv() hang

server/remote_cache/hit_tracker/hit_tracker.go
:point_right:  **Much easier to review with whitespace diffs hidden https://github.com/buildbuddy-io/buildbuddy/pull/1807/files?diff=split&w=1**
---
Make all inputs to `transferTimer.closeFn` struct fields of `transferTimer` and refactor `transferTimer.Close()` to directly run the code that was previously enclosed in `closeFn`, referencing the new struct fields instead of closure args.
This will let us support new methods like `t.SetResponseCode()`, `t.SetCompressedSizeBytes()` etc. and then reference these fields when calling `Close()`. These pieces of info are not known when calling `TrackDownload()` etc. so we need a way to set them after creating the timer, and it is not ergonomic to pass those to `Close()` since we want to `defer t.Close()` to make things easier to reason about.
--- …
=> Scorecard: Move transfer timer closure args to struct fields

cli/remotebazel/remotebazel.go, enterprise/server/hostedrunner/hostedrunner.go, enterprise/server/remote_execution/platform/platform.go, proto/runner.proto
Default CLI to current OS & Arch.
---
=> Allow remote Run requests to specify OS & Arch.

enterprise/server/workflow/service/service.go, server/config/config.go
Tested locally (with both cold and warm runs).
---
=> Add firecracker support for workflows

website/blog/distributed-scheduling-for-faster-builds.md
=> Add truncation marker for blog overview page and fix docs link

server/util/redact/redact.go, server/util/redact/redact_test.go
=> Strip remote headers in cmd lines

enterprise/server/usage/usage_test.go, server/config/config.go, server/testutil/testenv/BUILD, server/testutil/testenv/testenv.go, server/util/db/db.go
=> Use flags for database settings

enterprise/server/cmd/executor/executor.go, enterprise/server/cmd/goinit/main.go, enterprise/server/raft/rangecache/rangecache_test.go, enterprise/server/raft/registry/registry_test.go, enterprise/server/test/performance/cache/cache_test.go, server/config/config.go, server/libmain/libmain.go, server/testutil/testenv/testenv.go, server/util/db/BUILD, server/util/db/db.go, server/util/log/log.go, tools/rbeperf/rbeperf.go, tools/vmstart/vmstart.go
Part of encapsulating these settings in the log lib is making Configure use the settings instead of other args.
---
=> Use flags for log settings

enterprise/server/util/redisutil/redisutil.go, enterprise/server/util/redisutil/redisutil_test.go
This should give us an efficiency boost that will let us handle a higher volume of redis writes for the new cache scorecard, and also reduce our current CPU usage.
Local benchmark results:
```
NOT PIPELINED
BenchmarkCommandBuffer_Flush_HIncrBy/Keys=1,Fields=1,-8                    75475             14382 ns/op
BenchmarkCommandBuffer_Flush_HIncrBy/Keys=10,Fields=1,-8                    9128            135566 ns/op
BenchmarkCommandBuffer_Flush_HIncrBy/Keys=1,Fields=10,-8                    9097            122892 ns/op
BenchmarkCommandBuffer_Flush_HIncrBy/Keys=10,Fields=10,-8                   1006           1169771 ns/op
BenchmarkCommandBuffer_Flush_HIncrBy/Keys=100,Fields=100,-8                    9         123836555 ns/op
PIPELINED
BenchmarkCommandBuffer_Flush_HIncrBy/Keys=1,Fields=1,-8 …
```
=> Use pipelining to flush redis command buffer

enterprise/server/remote_execution/runner/runner.go
Firecracker containers can fail to unpause if their snapshots expired from filecache. In this case, we should evict them from the runner pool, otherwise we have a permanently borked container in the pool. This manifests as an error like "task failed after 5 attempts: failed to get runner from pool: missing full-mem.snap from snapshot" which reproduces on every attempt to run the same build.
---
=> Remove runners from the pool if Unpause fails

server/tables/tables.go
=> Fix index table name in migration code.

enterprise/server/backends/userdb/userdb.go, server/config/config.go
=> Use flags for userdb settings

enterprise/server/cmd/executor/executor.go, enterprise/server/cmd/server/main.go, server/config/config.go, server/util/tracing/BUILD, server/util/tracing/tracing.go
ProjectID is unused; revisit this later.
---
=> Use flags for tracing

server/config/config.go, server/static/static.go
=> Use flags for UI elements

enterprise/server/backends/userdb/userdb.go, server/config/config.go
This was very straightforward.
---
=> Use flags for org

server/backends/github/BUILD, server/backends/github/github.go, server/build_event_protocol/build_status_reporter/build_status_reporter.go, server/config/config.go, server/libmain/libmain.go, server/static/BUILD, server/static/static.go
Added Register function as well.
---
=> Use flags for github

server/backends/blobstore/blobstore.go
=> Try to configure GCS/S3/Azure for storage before falling back to disk

server/buildbuddy_server/buildbuddy_server.go, server/config/config.go
Restack of buildbuddy-io/buildbuddy/pull/1779
---
=> Use flags for cert auth enabled

server/build_event_protocol/build_event_proxy/BUILD, server/build_event_protocol/build_event_proxy/build_event_proxy.go, server/config/config.go, server/environment/environment.go, server/libmain/libmain.go
Restack of buildbuddy-io/buildbuddy/pull/1834
---
=> Use flags for build event proxy settings

server/backends/blobstore/BUILD, server/backends/blobstore/blobstore.go, server/build_event_protocol/build_event_handler/build_event_handler.go, server/build_event_protocol/build_event_handler/build_event_handler_test.go, server/buildbuddy_server/buildbuddy_server.go, server/config/config.go, server/janitor/janitor.go, server/libmain/libmain.go, server/telemetry/telemetry_client.go, server/testutil/testenv/testenv.go
Restack of buildbuddy-io/buildbuddy/pull/1835
---
=> Use flags for storage settings

enterprise/server/remote_execution/containers/docker/docker.go, enterprise/server/remote_execution/containers/podman/podman.go, enterprise/server/remote_execution/runner/runner.go, server/config/config.go
=> Add config option to enable setting docker/podman `--cap-add=`

enterprise/server/cmd/executor/executor.go, enterprise/server/cmd/server/main.go, server/backends/blobstore/BUILD, server/backends/blobstore/blobstore.go, server/build_event_protocol/build_event_handler/build_event_handler.go, server/build_event_protocol/build_event_proxy/build_event_proxy.go, server/environment/environment.go, server/janitor/janitor.go, server/libmain/libmain.go, server/real_environment/real_environment.go, server/telemetry/telemetry_client.go, server/testutil/testenv/testenv.go, server/util/tracing/BUILD, server/util/tracing/tracing.go
- Add a background context in the env
- Remove calls to context.Background()
- Buildfix
=> Remove calls to context.Background()

server/backends/slack/BUILD, server/backends/slack/slack.go, server/build_event_protocol/webhooks/webhooks.go, server/environment/environment.go, server/libmain/BUILD, server/libmain/libmain.go
Restack of buildbuddy-io/buildbuddy/pull/1855
---
=> Use flags for slack and invocation upload integrations

enterprise/server/remote_execution/containers/docker/docker.go
=> Fix missing docker action stderr/stdout

server/config/config.go, server/http/filters/filters.go, server/ssl/BUILD, server/ssl/ssl.go
Restack of buildbuddy-io/buildbuddy/pull/1853
---
=> Use flags for ssl

enterprise/server/hostedrunner/hostedrunner.go
=> Use workflow pool name from config.

enterprise/server/raft/cache/BUILD, enterprise/server/raft/cache/cache.go, enterprise/server/raft/cache/cache_test.go, enterprise/server/raft/client/client.go, enterprise/server/raft/sender/sender.go, enterprise/server/raft/store/store.go, proto/raft_service.proto
- Move writes distribution to the master, not the coordinator
- Fix typo
=> writemaster

enterprise/server/raft/cache/cache.go, enterprise/server/raft/driver/BUILD, enterprise/server/raft/driver/driver.go, enterprise/server/raft/rangecache/rangecache.go, enterprise/server/raft/replica/replica.go, enterprise/server/raft/store/store.go, proto/raft.proto
Still working out some kinks but wanted to get this in.
This CL lets the cluster auto-rebalance when it detects new machines that don't contain replicas. It also will automatically split replicas that are over size.
=> Let the driver make cluster changes

enterprise/server/remote_execution/containers/docker/docker_test.go, enterprise/server/remote_execution/containers/podman/podman_test.go
* Verified that the docker test fails when `Follow: true` in `ContainerLogsOptions` is commented out (only the first line, "Hello world" is displayed, but the "Hello again" printed after a delay is missing)
* Ported the docker test to podman as well (even though podman didn't have any issues) since it is a nice test to have.
---
=> Add regression tests for container stdout/stderr collection

enterprise/server/util/redisutil/redisutil.go, enterprise/server/util/redisutil/redisutil_test.go
Planning on using this for the cache scorecard.
---
=> Add SET command support to redis command buffer

WORKSPACE
Just updates our distroless debian images to latest.
---
=> Update base images

cli/remotebazel/remotebazel.go
=> CLI changes to setup runfiles & default args for remote run targets.

WORKSPACE
Needed security fixes in debian 11 to satisfy Vantas
---
=> Bump images to debian 11

proto/BUILD, server/util/paging/BUILD, server/util/paging/paging.go, server/util/paging/paging_test.go
=> Add utils for new OffsetLimit pagination proto

app/components/digest/digest.css, app/components/digest/digest.tsx, app/invocation/BUILD, app/invocation/cache_requests_card.tsx, app/invocation/invocation.css, app/invocation/invocation.tsx, app/invocation/invocation_model.tsx, package.json, proto/config.proto, server/static/BUILD, server/static/static.go, yarn.lock
TODO in subsequent PRs:
- Sorting/filtering controls
- Add a hovercard on each row with the complete data in list format, including precise timing data and compression ratio
---
=> Scorecard: Add initial UI for scorecard V2

WORKSPACE
We upgraded to java 17 and saw jvm errors hours later, I switched us back to 11 and they went
away. This makes that switch permanent.
---
=> Use java 11 images

enterprise/server/auth/BUILD, enterprise/server/auth/auth.go, enterprise/server/cmd/executor/BUILD, enterprise/server/cmd/executor/executor.go, enterprise/server/cmd/server/BUILD, enterprise/server/cmd/server/main.go, enterprise/server/remote_execution/execution_server/execution_server.go, enterprise/server/saml/BUILD, enterprise/server/saml/saml.go, enterprise/server/scheduling/scheduler_server/scheduler_server.go, enterprise/server/selfauth/BUILD, enterprise/server/selfauth/selfauth.go, enterprise/server/usage/usage.go, server/backends/invocationdb/invocationdb.go, server/buildbuddy_server/buildbuddy_server.go, server/config/config.go, server/interfaces/interfaces.go, server/nullauth/nullauth.go, server/role_filter/role_filter.go, server/static/BUILD, server/static/static.go, server/testutil/testauth/BUILD, server/testutil/testauth/testauth.go, server/testutil/testenv/BUILD, server/testutil/testenv/testenv.go, server/util/capabilities/BUILD, server/util/capabilities/capabilities.go, server/util/capabilities/capabilities_test.go, server/util/perms/perms.go, server/util/prefix/prefix.go
Moves the auth config into auth, the selfauth flag into selfauth, and the saml config into saml.
Biggest change is that auth config is now managed and retrieved through the Authenticator object,
which required interface changes, and that as a result, a nil authenticator is no longer a valid
state. Adds Register functions to move implementation details out of main.
---
=> Use flags for auth settings

enterprise/server/remote_execution/platform/BUILD, enterprise/server/remote_execution/platform/platform.go, enterprise/server/remote_execution/platform/platform_test.go
This will enable more flexibility when replaying actions, especially workflow actions.
---
=> Allow overriding env and args via platform props

enterprise/server/remote_execution/containers/firecracker/firecracker.go
Log errors when we see oom-kill entries in the kernel logs. This is helpful because we can't distinguish other types of kills (e.g. executor shutting down, context cancelled, etc.) from OOM kills, and also because the OOM kill may not necessarily surface in the command result (e.g. if the process killed was a child process).
For now we just log; in a subsequent PR I would like to tie these to the task. It is a bit tricky because we don't know whether the OOM is safe to ignore or not (e.g. if a non-critical child process OOM'd, the parent task can still succeed). We also don't necessarily want to spill this into the `stderr` field since it sort of violates the API. Maybe we can use the "message" field in the ExecuteResponse?
---
=> Add firecracker OOM logging

enterprise/BUILD, enterprise/server/remote_execution/containers/firecracker/BUILD
=> Don't build initrd on mac as it fails and we don't need it anyway.

enterprise/server/remote_execution/containers/docker/docker.go, enterprise/server/remote_execution/containers/podman/podman.go, enterprise/server/remote_execution/platform/platform.go, enterprise/server/remote_execution/runner/runner.go
=> Add platform prop for specifying docker/podman user

server/build_event_protocol/build_event_handler/build_event_handler.go
There is still a potential for race conditions here, but this should significantly reduce the likelihood of a disconnected invocation's status overwriting the status reported by a newer invocation.
If we still notice problems after this is submitted (unlikely), then we can introduce more fancy locking.
---
**Related issues**: https://github.com/buildbuddy-io/buildbuddy-internal/issues/1316
=> Report disconnected status only if invocation was not pre-empted

enterprise/server/execution_service/execution_service.go, enterprise/server/remote_execution/execution_server/execution_server.go, enterprise/server/remote_execution/executor/executor.go, enterprise/server/remote_execution/runner/runner.go, go.mod, server/remote_asset/fetch_server/fetch_server.go, tools/rbeperf/BUILD, tools/rbeperf/rbeperf.go
Streamlines the code a bit, taking advantage of the new protobuf API.
---
=> refactor for protobuf migration

enterprise/server/remote_execution/containers/podman/podman.go
"podman kill" can only kill running containers. Ignore this error in
killContainerIfRunning.
=> Ignore "can only kill running containers" error in killContainerIfRunning

server/build_event_protocol/build_event_handler/build_event_handler.go, server/remote_cache/scorecard/BUILD, server/remote_cache/scorecard/scorecard.go, server/remote_cache/scorecard/scorecard_test.go
=> Scorecard: Implement server-side sorting, searching, filtering, and grouping

enterprise/server/remote_execution/executor/executor.go, enterprise/server/scheduling/priority_task_scheduler/priority_task_scheduler.go, server/metrics/metrics.go, tools/metrics/grafana/dashboards/buildbuddy.json
This will give us a live view of which stages the currently executing tasks are in.
---
=> Split tasks executing metric by stage

enterprise/server/remote_execution/containers/firecracker/firecracker.go, enterprise/server/remote_execution/containers/firecracker/firecracker_test.go
Bumping to 50MB since we are seeing tasks returning 20MB of stdout/stderr.
---
=> Increase max recv msg size for vmexec.Exec

tools/metrics/grafana/dashboards/buildbuddy.json
=> Increase grafana time range + refresh interval defaults

rules/yarn/index.bzl
Fix website to work with https://github.com/buildbuddy-io/buildbuddy/pull/1929
---
=> Fix website to work with #1929

app/format/format.tsx, app/invocation/cache_requests_card.tsx, app/invocation/invocation.css
=> Add duration column to scorecard

app/invocation/invocation.css, app/invocation/invocation_filter.tsx, app/invocation/invocation_raw_logs_card.tsx, app/root/root.css, enterprise/app/tap/BUILD, enterprise/app/tap/tap.tsx
https://user-images.githubusercontent.com/2414826/166612628-943452bf-b2cd-4d4e-adf3-f0e5f8fffe99.mp4
---
=> Cleanup: Consolidate filter components

website/src/pages/security.mdx
=> Fix large SOC2 image

proto/cache.proto, server/remote_cache/scorecard/scorecard.go, server/remote_cache/scorecard/scorecard_test.go
=> Scorecard: Allow grouping results by target in GetScoreCard RPC

app/invocation/cache_requests_card.tsx, app/invocation/invocation.css, proto/cache.proto
Also make "group by target" the default grouping.
https://user-images.githubusercontent.com/2414826/166609395-510c1214-5778-4f3b-994f-62c4dac86225.mp4
---
=> Scorecard: Add "group by" selector and allow grouping by target

app/components/tooltip/BUILD, app/components/tooltip/tooltip.tsx, app/format/format.tsx, app/format/format_test.ts, app/invocation/BUILD, app/invocation/cache_requests_card.tsx, app/invocation/invocation.css, app/router/router.tsx
https://user-images.githubusercontent.com/2414826/166946187-27217920-25ed-4f33-8511-ca15ab0bf305.mp4
---
=> Add hovercard with cache request details

proto/cache.proto, server/build_event_protocol/build_event_handler/build_event_handler.go, server/remote_cache/hit_tracker/hit_tracker.go, server/remote_cache/hit_tracker/hit_tracker_test.go, server/tables/tables.go
=> Add compressed size to invocation cache stats

server/util/networking/networking.go
Add a flag to config the device to find. This can be 'default' or the
internal ip range of the subnet, e.g. 172.24.0.0/18.
Tested: set the flag to 172.24.0.0/18; and push the executor to my own
test executor pool which already have two networks configured: default
and executor with subnet 172.24.0.0/18. Run a bazel test that pings an
internal ip address in the default network and ping www.google.com.
Results:
- Test fails when running on podman b/c it can successfully ping the
internal ip address (10.138.0.88)
https://app.buildbuddy.dev/invocation/acef757d-30e9-4989-a9b0-0d6804565d72.
- Test fails when running on firecracker in dev executor pool.
(firecracker is on default network) It can
successfully ping the internal ip address. …
=> findDefaultDevice -> findDevice

enterprise/server/cmd/executor/BUILD, enterprise/server/cmd/executor/executor.go, enterprise/server/cmd/server/BUILD, enterprise/server/cmd/server/main.go, server/cmd/buildbuddy/BUILD, server/cmd/buildbuddy/main.go, server/config/BUILD, server/config/config.go, server/util/flagutil/flagutil.go
Also guard against the `config_file` flag being present in the YAML
config, as it is unsupported.
---
=> Move the remaining flag functions into flagutil

server/build_event_protocol/build_event_handler/build_event_handler.go
There are no refs to this flag, so it's safe to delete.
---
=> Delete unused flag

app/root/root.css
=> Adjust spacing / sizing of grid tooltip contents

app/invocation/cache_requests_card.tsx
We'll get a NotFound error if cache stats are not yet finalized, since we wait 500ms after the invocation is complete before finalizing.
Address this by retrying NotFound errors up to once, and just logging to the console if we still get a NotFound on the retry (since these are non-critical and we don't want to have to worry too much about these in the presence of data migrations, etc.).
---
=> Improve scorecard NotFound error handling

app/flame_chart/flame_chart.tsx
Another instance of https://github.com/buildbuddy-io/buildbuddy/pull/998
---
=> Fix stack overflow in flame chart

app/invocation/invocation_timing_card.tsx
Show a spinner while the profile is loading. This is helpful for larger invocations.
Also simplify a bunch of state.
Before:
After:
Tested with:
- In-progress invocations
- Invocations without remote cache enabled
---
=> Add loading state for timing tab

enterprise/server/scheduling/priority_task_scheduler/priority_task_scheduler.go, proto/remote_execution.proto, server/remote_cache/hit_tracker/hit_tracker.go
=> Don't store executor requests in cache scorecard

server/remote_cache/hit_tracker/BUILD, server/remote_cache/hit_tracker/hit_tracker_test.go
=> Add hit tracker usage test

app/invocation/cache_requests_card.tsx
The action links were removed in a previous iteration; adding them back.
https://user-images.githubusercontent.com/2414826/167482662-828f0fa8-0cde-41bf-abc6-e6f12458d2b9.mp4
---
=> Make action links clickable

app/invocation/invocation.css, app/root/root.css
Before (icons are on the left but should be on the right like they are for the invocation build logs, also the top padding is a bit too thin)
After
---
=> Fix styling of action page terminal

app/invocation/invocation.tsx, app/invocation/invocation_suggestion_card.tsx
This PR is intended to be a NOP. It sets us up for suggestions based on build flags, which require looking at the invocation model and not just the build logs.
---
**Related issues**: https://github.com/buildbuddy-io/buildbuddy-internal/issues/1357
=> Refactor suggestions to allow looking at invocation model

app/BUILD.bazel, enterprise/app/BUILD.bazel
```
BEFORE
size    11323 KB
gzipped 2174 KB
AFTER
size    4093 KB
gzipped 742 KB
DIFF
size    -7230 KB
gzipped -1431 KB
DIFF%
size    -63.85%
gzipped -65.84%
```
---
=> Re-enable code splitting

enterprise/app/history/history_invocation_card.tsx
=> Fix branch name clicking on invocation history page

server/backends/disk_cache/disk_cache.go, server/metrics/metrics.go
=> Add metric for duplicate disk cache writes.

enterprise/server/backends/distributed/distributed.go
=> Add flag to disable local peer shortcut for distributed writes.

app/invocation/cache_requests_card.tsx
Also change the "Name" column header to "Action"
---
=> Fix scorecard action URL for CAS request rows

app/invocation/invocation_suggestion_card.tsx, proto/config.proto, server/static/static.go
Behind a flag `--app.expanded_suggestions_enabled`
---
=> Add more invocation suggestions (round 1)

app/invocation/invocation.tsx, app/root/root.css
- Reduce padding on tabs to prevent wrapping
- Move suggestions below the build logs
---
=> Tweak invocation layout for suggestions

app/invocation/cache_requests_card.tsx, proto/cache.proto, server/remote_cache/scorecard/scorecard.go, server/remote_cache/scorecard/scorecard_test.go
=> Allow sorting scorecard by size

app/invocation/invocation_suggestion_card.tsx, app/root/root.css
=> Add remote_timeout suggestion

app/invocation/invocation.css, app/invocation/invocation_raw_logs_card.tsx
---
**Related issues**: Fixes https://github.com/buildbuddy-io/buildbuddy-internal/issues/1375
=> Add a Download JSON button to the raw tab

app/invocation/cache_requests_card.tsx
It's more interesting to see the biggest files first.
---
=> Sort descending by default when ordering scorecard results by size

enterprise/server/backends/userdb/userdb.go, proto/grp.proto, server/buildbuddy_server/buildbuddy_server.go, server/tables/tables.go
It always starts as ENABLED when creating a group, and can be disabled in the settings UI only when editing a group.
---
=> Add suggestion preference to Groups table

enterprise/server/remote_execution/execution_server/execution_server.go
=> Don't log warning if the key already doesn't exist when trying to delete.

app/components/select/select.css, app/invocation/invocation.tsx, app/invocation/invocation_suggestion_card.tsx, app/root/root.css, enterprise/app/org/create_org.tsx, enterprise/app/org/edit_org.tsx, enterprise/app/org/org.css, enterprise/app/org/org_form.tsx
- Add settings page toggle
- Tidy up the settings page a bit
- Respect suggestion preference when showing suggestions
- Add settings link to the bottom of the suggestions page
https://user-images.githubusercontent.com/2414826/169398432-92cfab41-b75a-46fe-893b-73cad0ee980b.mp4
---
=> Implement org suggestion preferences UI

app/invocation/invocation_suggestion_card.tsx, app/root/root.css
=> Add iOS execution filter and remote_cache_async suggestions

enterprise/server/invocation_search_service/invocation_search_service.go
Bonus: removes a DB lookup for `GetUser`.
---
=> Make impersonation work for build history

enterprise/app/tap/tap.tsx
=> Test grid: fix issue that changing the filter clears other URL params

enterprise/server/execution_service/execution_service.go, server/util/perms/perms.go
Checked the performance with invocations with large executions, looks unaffected by the additional join with the invocations table.
---
=> Make public invocation executions effectively public

enterprise/server/scheduling/scheduler_server/scheduler_server.go
=> Fix data race in scheduler server

enterprise/server/backends/distributed/BUILD, enterprise/server/backends/distributed/distributed.go, enterprise/server/raft/nodeliveness/BUILD, enterprise/server/raft/nodeliveness/nodeliveness.go, enterprise/server/raft/nodeliveness/nodeliveness_test.go, enterprise/server/raft/rangecache/rangecache.go, enterprise/server/raft/rangelease/rangelease.go, enterprise/server/raft/store/BUILD, enterprise/server/remote_execution/filecache/filecache.go, server/backends/chunkstore/chunkstore_test.go, server/gossip/gossip.go, server/testutil/mockstore/mockstore.go, server/util/healthcheck/healthcheck.go
- Fix gossip.go data race.
- Fix mockstore data race.
- Fix filecache lru.Size data race.
- Fix a data race in the health checker.
- Fix data race in shutdown of distributed cache
- Fix data race in nodeliveness_test.
=> Fix a bunch of data races.

enterprise/server/remote_execution/executor/executor.go, enterprise/server/scheduling/priority_task_scheduler/priority_task_scheduler.go, enterprise/server/scheduling/scheduler_server/scheduler_server.go, enterprise/server/scheduling/task_leaser/task_leaser.go, proto/scheduler.proto
=> Tweaks to executor ID logging.

server/util/flagutil/flagutil.go, server/util/flagutil/flagutil_test.go
This fixes a bug with `FlagAlias` in which if a flag and an alias flag were both
specified in YAML with different values, the behavior was non-deterministic. Now
the flags are guaranteed to be populated in the order specified in the YAML, so
for assignment-based flags the value will be the last occurence of a flag or an
alias flag, and append-based flags will have their contents appended in order.
---
=> Bug fix: Populate flags in the same order they are specified in the YAML

enterprise/server/api/api_server.go, enterprise/server/api/api_server_test.go, proto/api/v1/action.proto
=> Add target label filtering to the GetAction API endpoint

enterprise/server/api/api_server.go
This contains an expensive regex, which gets slow for invocations with a lot of output files.
---
=> Don't parse and fill output files for actions that were not requested

enterprise/server/api/api_server.go
=> Swap param order

enterprise/server/remote_execution/executor/executor.go, enterprise/server/test/integration/remote_execution/bazel_rbe/BUILD, enterprise/server/test/integration/remote_execution/bazel_rbe/bazel_rbe_test.go, enterprise/server/test/integration/remote_execution/remote_execution_test.go
---
**Related issues**: https://github.com/buildbuddy-io/buildbuddy-internal/issues/1321
=> Fix error code reported for context errors

server/util/flagutil/BUILD, server/util/flagutil/flagutil_test.go
=> Add test for using flags with protos

docs/prometheus-metrics.md, server/metrics/generate_docs.py, server/metrics/metrics.go
=> Fix prometheus docs generator and re-generate

docs/prometheus-metrics.md, server/metrics/generate_docs.py, server/metrics/metrics.go
* Make the "Label" suffix for label consts optional (it was preventing the documentation from being generated correctly)
* Clean up a few comments to make them more suitable for the docs page
---
=> Fix prometheus label docs

server/backends/invocationdb/BUILD, server/backends/invocationdb/invocationdb.go, server/interfaces/interfaces.go, server/util/db/db.go
For now, arbitrarily retries 5 times with exponential backoff.
---
=> Retry deadlocks on invocation update

enterprise/server/remote_execution/containers/podman/podman.go
https://github.com/buildbuddy-io/buildbuddy-internal/issues/1414
=> pass dns and dns-search flag to podman run

app/components/button/BUILD, app/components/button/link_button.tsx, app/invocation/invocation.tsx, app/root/root.css, app/target/BUILD, app/target/target.tsx, app/util/BUILD, app/util/git.ts, app/util/git_test.ts, enterprise/app/tap/BUILD, enterprise/app/tap/tap.tsx
https://user-images.githubusercontent.com/2414826/172223293-ddf8999d-aaa8-4485-9876-d803f951f496.mp4
---
**Related issues**: https://github.com/buildbuddy-io/buildbuddy-internal/issues/1350
=> Add a target history button

server/ssl/ssl.go
=> Add option to generate self-signed cert for SSL services.

server/remote_cache/content_addressable_storage_server/content_addressable_storage_server.go
- Allow changing treeCache seed via flag
- Change default treeCache seed from "-treecache" to "treecache"
=> Allow changing treeCache seed via flag

enterprise/server/api/api_server.go, enterprise/server/api/api_server_test.go, server/api/common/common.go
=> Set targetId = targetLabel

enterprise/server/remote_execution/execution_server/execution_server.go, enterprise/server/scheduling/scheduler_server/scheduler_server.go, server/util/log/log.go
The context is used to enrich the generated logs with additional IDs
(invocation ID, request ID) that can aid in debugging.
I've updated the app RBE code to try it out.
---
=> Add log function variants that take the context as a parameter.

enterprise/server/remote_execution/commandutil/commandutil.go, enterprise/server/remote_execution/commandutil/commandutil_test.go, enterprise/server/remote_execution/runner/BUILD, enterprise/server/remote_execution/runner/runner.go, enterprise/server/remote_execution/runner/runner_test.go, enterprise/server/remote_execution/runner/testworker/testworker.go, server/util/lockingbuffer/lockingbuffer.go
=> Show persistent worker stderr in error messages

server/util/flagutil/common/common.go, server/util/flagutil/common/common_test.go, server/util/flagutil/flagutil.go, server/util/flagutil/types/BUILD, server/util/flagutil/types/types.go, server/util/flagutil/types/types_test.go, server/util/flagutil/yaml/yaml.go, server/util/flagutil/yaml/yaml_test.go, server/util/testing/flags/flags.go
=> Enable deprecation of flags

docs/prometheus-metrics.md, enterprise/server/remote_execution/container/BUILD, enterprise/server/remote_execution/container/container.go, enterprise/server/remote_execution/containers/podman/podman.go, enterprise/server/remote_execution/runner/runner.go, server/metrics/metrics.go, tools/metrics/grafana/dashboards/buildbuddy.json
:point_right: Depends on https://github.com/buildbuddy-io/buildbuddy/pull/2138 (please review that one first)
Enables charts like this:
---
=> Add prometheus metrics for podman container resource usage

server/util/flagutil/yaml/yaml.go
This allows changing some config information dynamically without restarting the binary.
=> Re-read config file on SIGHUP

enterprise/server/remote_execution/containers/podman/podman.go
Bug: https://github.com/containers/storage/issues/1263
When "additional layer store" is enabled, podman retrieves layer
information from the additional store and commits the information to its
storage, which is shared across podman invocations. Two concurrent
podman invocations can both try to add the same layer metadata to
storage leading to a "duplicate ID" error.
A temporary workaround is to perform a synchronous pull to populate the
metadata storage before doing any "runs". Thankfully we already have
locking that guarantees only one concurrent pull for an image.
---
=> Add workaround for podman concurrency bug with streaming enabled.

enterprise/server/cmd/ci_runner/main.go
=> Add missing single quote

app/invocation/invocation_execution_card.tsx, enterprise/server/execution_service/execution_service.go, enterprise/server/remote_execution/container/BUILD, enterprise/server/remote_execution/container/container.go, enterprise/server/remote_execution/execution_server/BUILD, enterprise/server/remote_execution/execution_server/execution_server.go, enterprise/server/remote_execution/executor/BUILD, enterprise/server/remote_execution/executor/executor.go, enterprise/server/remote_execution/operation/BUILD, enterprise/server/remote_execution/operation/operation.go, enterprise/server/remote_execution/runner/BUILD, enterprise/server/remote_execution/runner/runner.go, enterprise/server/tasksize/BUILD, enterprise/server/tasksize/tasksize.go, enterprise/server/tasksize/tasksize_test.go, proto/BUILD, proto/execution_stats.proto, proto/remote_execution.proto, server/interfaces/interfaces.go
=> Move ExecutionSummary properties into the ExecutedActionMetadata

enterprise/server/auth/auth.go
=> Fix data race in auth.go

enterprise/server/backends/pebble_cache/pebble_cache.go
Useful when you need to migrate but a pebble DB has been created already. Say if you forgot to mount the volume on the init container perhaps.
=> Allow forcing the disk migration

tools/tasksize_stress/BUILD, tools/tasksize_stress/README.md, tools/tasksize_stress/tasksize_stress_test.go
These are helpful for tasksize testing.
---
=> Task sizing: Add manual tests that use a fixed amount of resources

README.md
=> Update README remote endpoint

enterprise/server/composable_cache/composable_cache.go
=> Fix `Contains` check in composable cache.

enterprise/server/tasksize/tasksize.go
* Respect EstimatedComputeUnits
* Carry over the disk estimate from the initial estimate so that we respect EstimatedDiskBytes (we don't yet do measurement-based disk estimates.)
---
=> Respect platform props for task sizing

enterprise/server/backends/distributed/distributed.go, enterprise/server/backends/distributed/distributed_test.go, enterprise/server/backends/gcs_cache/gcs_cache.go, enterprise/server/backends/memcache/memcache.go, enterprise/server/backends/pebble_cache/pebble_cache.go, enterprise/server/backends/pebble_cache/pebble_cache_test.go, enterprise/server/backends/redis_cache/redis_cache.go, enterprise/server/backends/s3_cache/s3_cache.go, enterprise/server/composable_cache/composable_cache.go, enterprise/server/raft/cache/cache.go, enterprise/server/util/cacheproxy/cacheproxy.go, proto/distributed_cache.proto, proto/raft.proto, server/backends/disk_cache/disk_cache.go, server/backends/disk_cache/disk_cache_test.go, server/backends/memory_cache/memory_cache.go, server/interfaces/interfaces.go
=> Extend Cache API to expose blob size.

server/remote_cache/byte_stream_server/byte_stream_server.go
This allows the blob size to the queried if it's not known in advance
(like in the registry blob case).
---
=> Update QueryWriteStatus to check whether digest is already in the cache.

enterprise/server/registry/BUILD, enterprise/server/registry/registry.go
=> Use QueryWriteStatus API to query layer blob size.

server/backends/disk_cache/disk_cache.go
=> Set blob size metadata when migrating from disk cache.

server/quota/quota_manager.go
Reduce the number of maps in namespaceConfig struct from 2 to 1.
=> create assignedBucket struct in quota manager

.github/workflows/website-pr.yaml, .github/workflows/website.yaml, website/src/components/oss/oss-list.tsx, website/src/pages/careers.tsx
The target didn't build with `replaceAll`, so I changed instances of that function to `replace` and a regex with the global flag set.
---
=> Build website with bazel in gitub workflows

docs/config-options-listings.mdx, enterprise/server/cmd/executor/yaml_doc/BUILD, enterprise/server/cmd/server/yaml_doc/BUILD, server/cmd/buildbuddy/yaml_doc/BUILD, website/BUILD.bazel, website/sidebars.js
Have to create `.mdx` versions of the YAML files so we can transclude them in the markdown.
---
=> Add YAML autodocs to website documentation

docs/prometheus-metrics.md, enterprise/server/remote_execution/executor/BUILD, enterprise/server/remote_execution/executor/executor.go, server/metrics/metrics.go, tools/metrics/grafana/dashboards/buildbuddy.json
This is a step towards better observability of remote execution error rate.
---
=> Add status code label to remote execution count metric

enterprise/server/remote_execution/executor/executor.go, enterprise/server/remote_execution/runner/runner.go, server/interfaces/interfaces.go, server/metrics/metrics.go
=> Add isolation type dimension to tasks executed metric
