- server/util/flagutil/yaml/yaml.go
This still isn't perfect, since the example comments sometimes exceed the bounds of the text box, but it's better.
---
> Reformat autodocs with word-wrapping head comments

- enterprise/server/backends/pebble_cache/pebble_cache.go
- enterprise/server/backends/pebble_cache/pebble_cache_test.go
before     850	   1389784 ns/op	  587863 B/op	    4241 allocs/op
after       1164	    968171 ns/op	  340427 B/op	    3043 allocs/op
> Improve pebble_cache GetMulti performance

- enterprise/server/remote_execution/execution_server/execution_server.go
> Fix for execution summary fallback

- enterprise/server/remote_execution/runner/runner.go
This should make it easier to figure out why runners are getting evicted.
---
> Add more runner pool logging

- enterprise/server/tasksize/tasksize.go
Confirmed locally that this was causing the read errors seen in the charts, and that this fixes the issue. The issue was that we were rounding any value less than 1ms down to 0. The fix is to use ceil instead of floor when rounding.
---
> Fix task size milliCPU rounding

- enterprise/server/backends/pebble_cache/pebble_cache.go
- server/metrics/metrics.go
Also change a previous metric from usec to sec.
> Add a file size bucket

- enterprise/server/backends/pebble_cache/pebble_cache.go
- enterprise/server/backends/pebble_cache/pebble_cache_test.go
- Don't close DB yet
- Skip test which requires closed db
> still open argh

- tools/metrics/grafana/dashboards/buildbuddy.json
> Add graph for invocations by bazel exit code to metrics dashboard

- enterprise/server/quota/BUILD
- enterprise/server/quota/quota_manager.go
- server/util/quota/BUILD
- server/util/quota/quota.go
So this can be added to metrics
> Move GetKey to server/util from quota manager

- server/util/flagutil/common/common.go
- server/util/flagutil/types/types.go
- server/util/flagutil/types/types_test.go
Also minor refactor to reduce code duplication
---
> Fix panic on flag Usage

- app/components/button/button.css
- app/components/dialog/BUILD
- app/components/dialog/dialog.css
- app/components/dialog/simple_modal_dialog.tsx
- app/components/input/input.css
- app/components/input/input.tsx
- app/util/proto.ts
- enterprise/app/BUILD.bazel
- enterprise/app/quota/BUILD
- enterprise/app/quota/bucket.tsx
- enterprise/app/quota/bucket_form.tsx
- enterprise/app/quota/namespace.tsx
- enterprise/app/quota/namespaces.tsx
- enterprise/app/quota/quota.css
- enterprise/app/quota/quota.tsx
- enterprise/app/quota/quota_breadcrumbs.tsx
- enterprise/app/root/root.tsx
- enterprise/app/settings/settings.tsx
- proto/BUILD
- proto/config.proto
- server/static/static.go
https://user-images.githubusercontent.com/2414826/178078194-6504baaa-f163-4c29-ad67-b7ab3aaf399d.mp4
---
> Add quota UI

- enterprise/server/remote_execution/commandutil/commandutil.go
- enterprise/server/remote_execution/commandutil/commandutil_test.go
- enterprise/server/remote_execution/containers/bare/BUILD
- enterprise/server/remote_execution/containers/bare/bare.go
- enterprise/server/remote_execution/containers/podman/podman.go
- enterprise/server/remote_execution/containers/sandbox/sandbox.go
- enterprise/server/remote_execution/runner/runner.go
- enterprise/server/util/procstats/procstats.go
- enterprise/server/vmexec/vmexec.go
> Task sizing: Export bare runner stats to prometheus

- enterprise/server/cmd/server/BUILD
- enterprise/server/cmd/server/main.go
- enterprise/server/registry/BUILD
- enterprise/server/registry/registry.go
- server/environment/BUILD
- server/environment/environment.go
- server/libmain/BUILD
- server/libmain/libmain.go
- server/real_environment/BUILD
- server/real_environment/real_environment.go
- server/util/grpc_server/grpc_server.go
This will allow us to start the service as part of the app.
Note that the registry runs on its own http/grpc ports to allow us to
treat them as internal services.
---
> Integrate registry serving into app.

- enterprise/server/remote_execution/commandutil/commandutil.go
- enterprise/server/remote_execution/commandutil/commandutil_test.go
- enterprise/server/remote_execution/container/container.go
- enterprise/server/remote_execution/container/container_test.go
- enterprise/server/remote_execution/containers/bare/bare.go
- enterprise/server/remote_execution/containers/docker/docker.go
- enterprise/server/remote_execution/containers/docker/docker_test.go
- enterprise/server/remote_execution/containers/firecracker/firecracker.go
- enterprise/server/remote_execution/containers/firecracker/firecracker_darwin.go
- enterprise/server/remote_execution/containers/podman/BUILD
- enterprise/server/remote_execution/containers/podman/podman.go
- enterprise/server/remote_execution/containers/sandbox/sandbox.go
- enterprise/server/remote_execution/runner/runner.go
- enterprise/server/util/procstats/BUILD
- enterprise/server/util/procstats/procstats.go
- proto/remote_execution.proto
> Replace container.Stats with UsageStats proto

- app/invocation/invocation_action_card.tsx
> Task sizing: Show estimated and actual resource usage on the action page

- enterprise/server/splash/BUILD
- enterprise/server/splash/splash.go
- server/interfaces/interfaces.go
- server/libmain/BUILD
- server/libmain/libmain.go
- server/splash/BUILD
- server/splash/splash.go
Also account for different lengths of URLs / ports for the pretty formatting in the splash screen, which incidentally fixes a subtle bug where the port being a different number of digits than 4 would misalign the right border.
---
> Update splash screen to use `app.build_buddy_url`

- enterprise/server/backends/pubsub/pubsub.go
- enterprise/server/remote_execution/execution_server/execution_server.go
- enterprise/server/scheduling/priority_task_scheduler/BUILD
- enterprise/server/scheduling/priority_task_scheduler/priority_task_scheduler.go
> Logging tweaks to help debug RBE issues.

- tools/metrics/grafana/dashboards/buildbuddy.json
Use the right quota metrics name.
> fix grafana error

- enterprise/server/registry/registry.go
> Fix missing return

- server/remote_cache/byte_stream_server/byte_stream_server.go
> Disable QueryWriteStatus for compressed writes

- app/invocation/invocation_model.tsx
- app/target/target_test_cases_card.tsx
- app/target/target_test_log_card.tsx
- enterprise/server/api/api_server_test.go
- enterprise/server/cmd/ci_runner/main.go
- enterprise/server/test/integration/build_logs/build_logs_test.go
- enterprise/server/test/integration/remote_execution/remote_execution_test.go
- server/api/common/common.go
- server/build_event_protocol/build_status_reporter/build_status_reporter.go
- server/build_event_protocol/event_parser/event_parser_test.go
- server/util/redact/redact.go
- server/util/redact/redact_test.go
> Update build event stream references to not use deprecated fields

- enterprise/server/registry/registry.go
If the requested image reference resolves to an image index then we
should pass the resolved target image to the conversion service rather
than the original image index reference.
---
> Fix handling of image indices.

- enterprise/server/scheduling/scheduler_server/scheduler_server.go
> Fix data race in NodeCount()

- app/invocation/invocation_suggestion_card.tsx
> Disable experimental_remote_cache_async suggestion

- enterprise/server/auth/auth.go
If the session access token is expired and the refresh token is invalid (empty, expired, invalidated by oauth provider, etc.), then the session is no longer useful, since both the access token and refresh token cannot be used anymore. As soon as we detect this, delete the session from both client cookies and the DB, so that the user is forced to go through the consent screen and request a new refresh token. (Due to the check [here](https://cs.github.com/buildbuddy-io/buildbuddy/blob/28c93f863d22951d4ac5c6a87e281428b9b20fd6/enterprise/server/auth/auth.go#L629), we only get an access token when the Session-ID cookie is set, not a refresh token, because a refresh token is only returned when authenticating via the consent screen.)
--- …
> Clear sessions with invalid refresh tokens

- enterprise/server/image_converter/image_converter.go
> Add some logs to the image converter.

- server/util/dsingleflight/dsingleflight.go
For a reason I can't figure out, an image conversion result was stored
in redis w/o expiration which caused future conversions to keep using the old
result even though the image was not valid.
---
> Use a redis txn to publish work results.

- enterprise/server/scheduling/scheduler_server/scheduler_server.go
- server/testutil/testenv/testenv.go
---
**Related issues**: Fixes https://github.com/buildbuddy-io/buildbuddy-internal/issues/1521
> Fix a few more data races in remote_execution_test

- server/remote_cache/scorecard/scorecard.go
Fixes a few cases where we show `bes-upload` in the cache requests card instead of the cross-referenced filename from BES.
* Cross-reference all `File` objects from all events, not just NamedSetOfFiles and BuildToolLogs
* Don't cross-reference files with empty filenames -- sometimes files are referenced twice, once with a filename and once without -- prefer the ones that have filenames present.
---
> Cache requests card: Improve BES filename cross-referencing

- enterprise/server/image_converter/image_converter.go
- proto/registry.proto
The TOC digest annotation is not currently used by the store, but it
will make our life easier if it starts being used in a newer version.
---
> Propagate annotations through conversion process.

- enterprise/server/tasksize/tasksize.go
- server/metrics/metrics.go
> Task sizing: Add more dimensions to prometheus metrics

- enterprise/server/remote_execution/execution_server/execution_server.go
Confirmed via the added logging that this is what's going on.
---
**Related issues**: Fixes https://github.com/buildbuddy-io/buildbuddy-internal/issues/1508
> Fix 'invalid nil Timestamp' message in logs when tasks have an error status set

- enterprise/server/image_converter/image_converter.go
This will make it more likely that layers are spread out amongst
converter instances.
---
> Dial the image converter for each layer.

- app/invocation/invocation.css
- app/invocation/invocation_buttons.tsx
- app/invocation/invocation_cancel_button.tsx
- app/invocation/invocation_model.tsx
- enterprise/server/test/integration/workflow/BUILD
- enterprise/server/test/integration/workflow/workflow_test.go
- proto/buildbuddy_service.proto
- proto/invocation.proto
- server/buildbuddy_server/BUILD
- server/buildbuddy_server/buildbuddy_server.go
- server/role_filter/role_filter.go
- Add cancel button to invocation UI
- Add RPC to role_filter
- Address PR comments
- Improve UI and integration test
Continuing off of [this PR](https://github.com/buildbuddy-io/buildbuddy/pull/2297), due to messed up git history
Fixes buildbuddy-io/buildbuddy-internal#1247
> Allow users to cancel workflows from UI

- enterprise/server/backends/distributed/distributed.go
- enterprise/server/backends/distributed/distributed_test.go
- enterprise/server/util/cacheproxy/cacheproxy.go
- enterprise/server/util/cacheproxy/cacheproxy_test.go
- proto/distributed_cache.proto
Splitting up this PR: https://github.com/buildbuddy-io/buildbuddy/pull/2288
> Add delete method to cache

- enterprise/server/backends/pebble_cache/pebble_cache.go
Fixes https://github.com/buildbuddy-io/buildbuddy-internal/issues/1532
> Prevent shutdown race in pebble_cache

- app/invocation/invocation_buttons.tsx
> Show cancel button for hosted bazel invocations too

- enterprise/server/hostedrunner/BUILD
- enterprise/server/hostedrunner/hostedrunner.go
Prerequisite for being able to cancel the executions.
---
> Associate hosted bazel execution with invocation ID.

- enterprise/server/backends/distributed/distributed.go
This should make it easier to root cause the "replication factor"
errors.
---
> Bump up log level for distributed writes.

- enterprise/server/remote_execution/containers/firecracker/firecracker.go
- enterprise/server/remote_execution/containers/firecracker/firecracker_test.go
Fixing the test before making any changes for the new ExecStreamed API.
---
> Fix firecracker test

- enterprise/server/scheduling/priority_task_scheduler/priority_task_scheduler.go
This is to rule out task sizing as a possible cause of tasks hanging.
This should never happen, but if it does, it's better to return an error to the scheduler than enqueue an unschedulable task, which can (a) cause tasks to hang if all 3 probes go to executors which cannot fit the task, and (b) inflate the queue length metric causing a scale-up that can only be reversed by killing the executors with the inflated queues.
---
> Executor: Log attempts to enqueue unschedulable tasks

- enterprise/server/registry/BUILD
- enterprise/server/registry/registry.go
- server/metrics/metrics.go
> Add metric for registry blob serving latency.

- enterprise/server/scheduling/scheduler_server/scheduler_server.go
Addresses https://github.com/buildbuddy-io/buildbuddy-internal/issues/1565
---
> Mark execution as failed if re-enqueue fails due to empty pool.

- enterprise/server/workflow/service/service.go
---
**Version bump**: TODO 
**Related issues**: https://github.com/buildbuddy-io/buildbuddy-internal/issues/1566
> Add more details to workflow logging

- enterprise/server/backends/pebble_cache/pebble_cache.go
> Fix pebble shutdown issue due to closed value being copied.

- enterprise/server/remote_execution/containers/podman/podman.go
- enterprise/server/remote_execution/platform/platform.go
- enterprise/server/remote_execution/runner/runner.go
This will give us a way to measure streaming peformance without having
to enable it by default.
---
> Add platform property for enabling image streaming.

- enterprise/server/remote_execution/dirtools/BUILD
- enterprise/server/remote_execution/dirtools/dirtools.go
- enterprise/server/remote_execution/dirtools/dirtools_test.go
---
**Related issues**: Fixes https://github.com/buildbuddy-io/buildbuddy-internal/issues/1559
> Exclude filecache-linked files from download metrics

- enterprise/server/remote_execution/containers/podman/podman.go
Also fixed a missing err check.
---
> Add debug logs for optimized image lookup.

- server/util/peerset/peerset.go
> Fix off-by-one in failed peers check.

- proto/distributed_cache.proto
> Add access and modify time to metadata API proto

- enterprise/server/raft/cache/BUILD
- enterprise/server/raft/cache/cache.go
- enterprise/server/raft/driver/BUILD
- enterprise/server/raft/driver/driver.go
- enterprise/server/raft/store/BUILD
- enterprise/server/raft/store/store.go
- server/gossip/BUILD
- server/gossip/gossip.go
- Add statusz support to gossip manager
- Add statusz support to raft cache
- Show bringup status in cache statusz
- Add newline
- Add useful info to store Statusz
- Add statusz for placement driver
> Add some raft statusz

- enterprise/server/raft/client/client.go
> Return error if we ran out of retries while running node host func.

- website/src/pages/enterprise-terms.md
- website/src/pages/privacy.md
- website/src/pages/team.tsx
> Update mailing address on website

- tools/metrics/grafana/dashboards/buildbuddy.json
---
**Version bump**: None 
Fixes https://github.com/buildbuddy-io/buildbuddy-internal/issues/1582
> Fix HPA metric name in Grafana dashboard.

- enterprise/server/raft/replica/replica.go
Run through all values in the tablet and sum their sizes to compute usage.
I think this is not optimal but should be fast for the time being and we can optimize it once we get other bugs ironed out.
> Compute size manually by summing value sizes

- tools/cas/BUILD
- tools/cas/cas.go
This makes it possible to wrangle the output using jq.
---
> CAS tool: print output in protojson format

- deps.bzl
- go.mod
- go.sum
Fixes the error `2022/08/22 17:21:58.954 FTL Error configuring database: invalid DDL, unbalanced brackets`
---
> Upgrade gorm sqlite driver to v1.3.6

- server/util/flagutil/types/types.go
- server/util/flagutil/types/types_test.go
> Fix zero construction checks in flags and add tests

- enterprise/server/raft/store/store.go
> Set file size metadata on raft writes.

- enterprise/server/raft/replica/replica.go
> Fix replica usage calculation.

- enterprise/server/backends/pebble_cache/pebble_cache.go
Unlikely to be a problem in practice though.
---
> Fix off-by-one in pebble broken file scan.

- enterprise/server/raft/replica/replica.go
I missed this one because I was only looking for db.NewIter references
and I missed all the batch newIter references.
---
> Fix split point calculation.

- enterprise/server/raft/store/store.go
I accidentally undid the change when resolving rebase conflicts.
---
> Remove duplicated code from RangeIsActive.

- tools/dev_qa.sh
Runs the test builds that we usually run, but also handles cloning the repos if not already cloned, as well as printing all the invocation links after all build commands are run so that they can be easily pasted into Slack.
---
> Add a script to automate dev QA testing

- enterprise/server/raft/driver/driver.go
> Enable raft cache splits by default.

- .bazelrc
---
**Related issues**: https://github.com/buildbuddy-io/buildbuddy-internal/issues/1575
> Bump flaky_test_attempts

- enterprise/server/raft/replica/replica.go
> Copy iterator key/value in scan request.

- enterprise/server/raft/driver/driver.go
> Fix race in driver cluster map.

- dockerfiles/executor_image/Dockerfile
> Bump podman and skopeo versions

- app/invocation/invocation.css
- app/invocation/invocation_model.tsx
- app/invocation/invocation_targets_card.tsx
- app/root/root.css
* Show a root cause badge if there are a mix of root-cause and non-root-cause targets (which can happen when `--keep_going` is set).
* Guarantee that root cause targets are sorted first in the list, though this should usually be the case anyway.
* Refactor the UI to be grid-based instead of %-based, so that the duration column takes up only as much space as it needs. This helps with really long target names which wrap prematurely, even though there is plenty of space available.
---
> Show a badge for root-cause targets

- enterprise/app/tap/tap.tsx
> Fix rendered '0' when test grid repos list is empty

- enterprise/server/raft/driver/driver.go
> Perform splits per cluster instead of per replica.

- enterprise/server/raft/store/store_test.go
- Always fetch the range descriptor from the store being fetched from.
- Construct a header that contains generation.
> Fix store test a little bit

- enterprise/server/raft/replica/replica.go
- enterprise/server/raft/sender/sender.go
- proto/raft.proto
This fixes an issue where the wrong range was looked up.
> Scan GT when looking up ranges

- app/terminal/terminal.css
> Fix invisible terminal text in action page stdout

- enterprise/server/tasksize_model/BUILD
- enterprise/server/tasksize_model/tasksize_model_darwin.go
Fix the package name in `tasksize_model_darwin.go`
---
> Fix Mac build

- enterprise/server/raft/replica/replica.go
- enterprise/server/raft/store/store_test.go
We weren't taking file size into account when finding the split point.
---
> Fix raft split point logic.

- enterprise/server/raft/cache/cache.go
- enterprise/server/raft/sender/sender.go
Sender gets a new RunMultiKey function for handling batch operations.
In the initial version, we do not attempt to parallelize requests for
different ranges.
---
> Make raft FindMissing tolerate splits.

- server/util/flagutil/types/autoflags/autoflags.go
- server/util/flagutil/types/types.go
- server/util/flagutil/types/types_test.go
Adds JSON-based struct flag.
---
> Support parsing JSON structs into flags

- enterprise/server/raft/replica/replica.go
Still working on some new store tests that exercise this, not passing yet.
> Detect postfacto splits

- enterprise/server/remote_execution/containers/docker/docker.go
- enterprise/server/remote_execution/containers/podman/podman.go
- enterprise/server/remote_execution/runner/runner.go
> Support dockerNetwork=standard

- enterprise/server/raft/cache/cache.go
- enterprise/server/raft/replica/replica.go
- enterprise/server/raft/store/store.go
- proto/raft.proto
- proto/raft_service.proto
> Implement GetMulti in raft cache.

- enterprise/server/raft/replica/replica.go
- enterprise/server/raft/store/BUILD
- enterprise/server/raft/store/store_test.go
> Fix proto written when restoring digest from peer.

- enterprise/server/backends/pebble_cache/pebble_cache.go
When set, this flag will trigger a compaction before the cache is registered in the environment.
I plan to modify the init-pod to run this so caches are compacted when we release.
> Add a flag to force pebble compaction

- enterprise/server/backends/migration_cache/BUILD
- enterprise/server/backends/migration_cache/config.go
- enterprise/server/backends/migration_cache/migration_cache.go
- enterprise/server/backends/migration_cache/migration_cache_test.go
> Add code to copy data on reads during a migration

- enterprise/server/remote_execution/execution_server/execution_server.go
- enterprise/server/remote_execution/platform/platform.go
- enterprise/server/scheduling/scheduler_server/scheduler_server.go
- enterprise/server/tasksize/BUILD
- enterprise/server/tasksize/tasksize.go
- enterprise/server/tasksize_model/tasksize_model.go
- proto/scheduler.proto
- server/interfaces/interfaces.go
> Task sizing: Use prediction model for estimates

- enterprise/server/remote_execution/runner/runner.go
- enterprise/server/remote_execution/runner/runner_test.go
The `maxRunnerMemoryBytes` config option is supposed to limit the size of individual runners added to the pool, not the total memory usage of pooled runners.
We really only need the `maxRunnerCount` limit, which, when combined with the per-runner memory limit, acts as a limit on the pool's total memory usage.
Note, after https://github.com/buildbuddy-io/buildbuddy/pull/2521 is submitted, this will be inconsequential for our deployment since we are using Firecracker, where the mem usage of paused runners will always be 0. But this is still a glaring logic bug that I noticed a while back and have been meaning to fix.
Also: Improve logging so we can see the actual memory / disk values logged when they exceed the configured limits.
---
> Remove memory check when adding runners to the pool

- enterprise/server/remote_execution/runner/runner.go
> Add logging to runner pool shutdown

- enterprise/server/backends/migration_cache/BUILD
- enterprise/server/backends/migration_cache/migration_cache.go
- enterprise/server/backends/migration_cache/migration_cache_test.go
- server/remote_cache/digest/BUILD
- server/remote_cache/digest/digest.go
- server/remote_cache/digest/digest_test.go
> Implement more functionality in migration cache

- tools/dev_qa.sh
> Increase timeout on gazelle QA builds

- app/invocation/invocation_suggestion_card.tsx
> Increase priority of DEADLINE_EXCEEDED suggestion

- enterprise/server/remote_execution/executor/BUILD
- enterprise/server/remote_execution/executor/executor.go
- enterprise/server/tasksize_model/BUILD
- enterprise/server/tasksize_model/tasksize_model.go
- server/metrics/metrics.go
- server/util/status/status.go
> Task sizing: Add latency metric for TF prediction

- enterprise/server/raft/replica/replica.go
> Log errors during raft update processing.

- enterprise/server/raft/rbuilder/rbuilder.go
- enterprise/server/raft/replica/BUILD
- enterprise/server/raft/replica/replica.go
- proto/raft.proto
> raft cache: update atimes on read

- deps.bzl
- server/testutil/testbazel/BUILD
- server/testutil/testbazel/testbazel.go
- server/util/bazel/BUILD
> Update test bazel versions to 5.3.0

- server/build_event_protocol/build_event_handler/build_event_handler.go
> Clean up todo log

- server/util/flagutil/yaml/yaml.go
- server/util/flagutil/yaml/yaml_test.go
Changes to the YAML-based flag processing to use with flagz.
---
> Flag YAML changes for flagz

- enterprise/server/backends/pebble_cache/pebble_cache.go
- enterprise/server/backends/pebble_cache/pebble_cache_test.go
- proto/raft.proto
> Store partition metadata in the pebble db to improve start up speed.

- tools/metrics/grafana/dashboards/buildbuddy.json
> Add cache filesystem usage graph.

- server/util/flagutil/yaml/yaml.go
Hard-coding of yaml style was leftover from testing; switch to using the actual specified style.
---
> Remove errant hard-coding of yaml style

- dockerfiles/executor_image/Dockerfile
I don't think this addresses the hanging issue we saw, but it doesn't hurt to pick up the fixes in this release.
https://github.com/buildbuddy-io/buildbuddy-internal/issues/1661
---
> Upgrade podman to 4.2.1

- enterprise/server/remote_execution/containers/podman/podman.go
https://github.com/buildbuddy-io/buildbuddy-internal/issues/1661
---
> Add a timeout for podman pulls.

- server/util/basicauth/BUILD
- server/util/basicauth/basicauth.go
- server/util/basicauth/basicauth_test.go
- server/util/monitoring/BUILD
- server/util/monitoring/monitoring.go
> Add optional basic auth to monitoring port

- enterprise/server/backends/migration_cache/BUILD
- enterprise/server/backends/migration_cache/migration_cache.go
- enterprise/server/backends/migration_cache/migration_cache_test.go
> Implement reader and writer for migration cache

- server/util/healthcheck/healthcheck.go
This will allow clients (LBs) to continue sending requests until they mark the backends as unready.
---
> Optional lame duck period for shutdown.

- enterprise/server/backends/migration_cache/config.go
- enterprise/server/backends/migration_cache/migration_cache.go
- enterprise/server/backends/pebble_cache/pebble_cache.go
> Add option to use group ID in pebble file path

- enterprise/server/backends/migration_cache/config.go
- enterprise/server/backends/migration_cache/migration_cache.go
- enterprise/server/backends/migration_cache/migration_cache_test.go
> Limit noisy warning log on full copy chan

- server/util/clickhouse/clickhouse.go
This will allow us to show exit code trends.
---
> Add BazelExitCode to clickhouse

- enterprise/server/execution_service/execution_service.go
- Don't filter the executions table by invocation_id. The executions table references the original invocation_id which doesn't show merged executions for other invocations.
- Stop querying "unlinked" executions. We've been populating the invocation -> execution links for a while now so it's okay to stop querying for executions that don't have these links. Older invocations may not show executions information but I don't think that's very important.
---
> Fix / cleanup executions query.

- enterprise/server/remote_execution/containers/firecracker/BUILD
- enterprise/server/remote_execution/containers/firecracker/firecracker_test.go
- enterprise/server/vmexec/vmexec.go
> Fix firecracker workspace dir perms for non-root users

- enterprise/server/util/container/container.go
non-root workflows were failing because the workflow user "buildbuddy" didn't have access to `/home/buildbuddy`. This is because all the files in the scratch disk were owned by root (even `/home/buildbuddy`), since we were passing this `--rootless` flag to `umoci unpack` which causes all files in the unpacked image to be owned by the current uid, and the executor is running as uid 0.
---
> Fix incorrect permissions when converting OCI to ext4

- enterprise/server/raft/constants/constants.go
- enterprise/server/raft/store/store.go
- enterprise/server/raft/store/store_test.go
Client side handling is not modified in this PR.
---
> Return a specialized message if range is out of date due to split.

- cli/arg/BUILD
- cli/arg/arg.go
> Convenience methods for manipulating args in the CLI

- app/invocation/invocation_details_card.tsx
---
**Related issues**: Fixes https://github.com/buildbuddy-io/buildbuddy-internal/issues/1693
> Don't render starlark flags as links

- cli/cmd/bb/BUILD
- cli/cmd/bb/bb.go
- cli/storage/BUILD
- cli/storage/storage.go
> Pull storage directory into its own package so it can be used in multiple places

- .github/workflows/deps.yaml
> Attempt to fix update deps workflow

- enterprise/server/raft/driver/driver.go
- server/gossip/gossip.go
Add newlines to driver statusz doesn't look corrupted
Add serf stats to gossip statusz for debugging long queues
> Small statusz fixes

- .github/workflows/helm.yaml
> Fix checkout paths in helm workflow

- enterprise/server/raft/store/store.go
> Return more useful error messages from SplitCluster.

- cli/tooltag/BUILD
- cli/tooltag/tooltag.go
This helps you tell which tool you're using.
We can remove this if it gets annoying, but is nice for now.
---
> Add a little CLI shout-out

- cli/cmd/bb/BUILD
- cli/cmd/bb/bb.go
- cli/log/log.go
- cli/login/BUILD
- cli/login/login.go
> Add `login` command to CLI

- cli/log/log.go
- Make the API match the underlying log API (`Print(...any)` instead of `Print(string)`)
- Add plain `Debug` and `Print` funcs
---
> Smooth out CLI logging API

- server/backends/disk_cache/disk_cache.go
- server/backends/disk_cache/disk_cache_test.go
- server/util/disk/disk.go
> Delete stale temp write files during disk cache initialization.

- enterprise/server/raft/sender/sender.go
- server/util/retry/BUILD
- server/util/retry/retry.go
- server/util/retry/retry_test.go
> Use a fixed retry interval during splits.

- cli/tooltag/tooltag.go
> Don't apply `tool_tag` if there is no command present

- server/build_event_protocol/target_tracker/target_tracker.go
- server/target/target.go
`bazel coverage` runs tests as well, so we can enable the test grid for it.
---
> Enable test grid for `bazel coverage`

- app/invocation/invocation_suggestion_card.tsx
- app/root/root.css
> Add suggestion card for coverage RBE configuration

- enterprise/server/backends/distributed/distributed.go
- enterprise/server/backends/pebble_cache/pebble_cache.go
- enterprise/server/raft/replica/replica.go
- server/remote_cache/cachetools/cachetools.go
> Make sure writer Close is called on errors.

- server/backends/disk_cache/disk_cache.go
> Clean up 0-length files during startup scan.

- buildpatches/com_github_shirou_gopsutil.patch
- deps.bzl
- go.mod
- go.sum
> Patch memory leak in gopsutil (process_darwin_cgo)

- enterprise/server/composable_cache/composable_cache.go
An incomplete read can cause an incomplete digest to be written to outer cache.
---
> Fix composable cache read-through mode.

- enterprise/server/composable_cache/BUILD
- enterprise/server/composable_cache/composable_cache_test.go
- enterprise/server/testutil/enterprise_testenv/enterprise_testenv.go
Disabled until we fix Writer and Reader.
---
> Add test for composable cache read through.

- enterprise/server/cmd/ci_runner/BUILD
- enterprise/server/cmd/ci_runner/main.go
- enterprise/server/remote_execution/runner/runner.go
- enterprise/server/remote_execution/workspace/workspace.go
- enterprise/server/remote_execution/workspace/workspace_test.go
- server/util/disk/disk.go
---
**Related issues**: https://github.com/buildbuddy-io/buildbuddy-internal/issues/1566
> Workflows: Use ForceRemove when repo sync fails

- app/invocation/invocation_model.tsx
- docs/guide-metadata.md
- server/build_event_protocol/event_parser/event_parser.go
> Allow an invocation's pattern to be overridden by build metadata / workspace status

- app/docs/setup.tsx
- app/menu/menu.tsx
- docs/cloud.md
- docs/enterprise.md
- docs/guide-auth.md
- docs/rbe-github-actions.md
- docs/workflows-config.md
- enterprise/app/sidebar/sidebar.tsx
- template-user.bazelrc
Feels more discoverable, but open to ideas:
---
> Move Settings page out of user dropdown

- app/footer/BUILD
- app/footer/footer.tsx
This is helpful for debugging which app version a user is using.
---
> Show app version in the footer if it's available

- server/backends/disk_cache/disk_cache.go
> Populate digest size metric in disk cache.

- enterprise/server/selfauth/selfauth.go
> Make selfauth user look a little nicer

- enterprise/app/root/root.tsx
This makes the CLI login flow much smoother for folks without an account.
---
> Show the login page if trying to view the settings page while logged out

- enterprise/server/workflow/service/service.go
Not quite as useful as PR number (which we don't yet have the plumbing for) but gives us enough info to correlate workflow logs with a specific PR.
---
> Add pushed branch to workflow server logs

- enterprise/server/raft/replica/replica.go
- enterprise/server/raft/replica/replica_test.go
- enterprise/server/raft/store/BUILD
- enterprise/server/raft/store/store_test.go
> Don't sync pebble WAL so often.

- enterprise/app/sidebar/sidebar.tsx
> Fix sidebar links

- server/build_event_protocol/build_event_handler/build_event_handler.go
- server/util/clickhouse/clickhouse.go
Add more logging to debug missing clickhouse data.
> add more logging for clickhouse debugging

- WORKSPACE
- dockerfiles/run_script/BUILD
- dockerfiles/run_script/Dockerfile
- dockerfiles/run_script/run_script.sh
Loosely based on https://github.com/kubernetes-retired/contrib/blob/master/startup-script/Dockerfile
---
> Add simple image to run an arbitrary bash script.

- enterprise/server/backends/migration_cache/migration_cache.go
- enterprise/server/backends/migration_cache/migration_cache_test.go
> Use correct isolation when copying data during migration

- cli/plugin/plugin.go
This code was harmless, but has no actual effect.
---
> Remove unnecessary code in plugin.Pipeline()

- app/invocation/invocation_action_card.tsx
:point_right:  Recommend reviewing with whitespace diff disabled: https://github.com/buildbuddy-io/buildbuddy/pull/2692/files?diff=split&w=1
Example:
Before, we wouldn't show the ActionResult even if we fetched it successfully but failed to fetch the Action.
---
**Related issues**: https://github.com/buildbuddy-io/buildbuddy-internal/issues/1734
> Render ActionResult in action page if available, even if Action expired from CAS

- enterprise/server/backends/pebble_cache/BUILD
- enterprise/server/backends/pebble_cache/pebble_cache.go
- server/backends/disk_cache/disk_cache.go
This is better served by the new migration support.
---
> Remove custom disk -> pebble mirroring support.

- app/invocation/cache_requests_card.tsx
- proto/cache.proto
- server/build_event_protocol/build_event_handler/BUILD
- server/build_event_protocol/build_event_handler/build_event_handler.go
- server/remote_cache/scorecard/BUILD
- server/remote_cache/scorecard/scorecard.go
- server/remote_cache/scorecard/scorecard_test.go
Started writing the field here: https://github.com/buildbuddy-io/buildbuddy/pull/2684
> Read new cache type field from cache scorecards

- app/invocation/invocation_action_card.tsx
Also check `!hasRemoteExecutor` since the executor may have executed the action, and the executor should have RW capabilities.
---
> Use new created_at_capabilities to improve action card error messaging

- enterprise/server/backends/gcs_cache/gcs_cache.go
- enterprise/server/backends/memcache/memcache.go
- enterprise/server/backends/redis_cache/redis_cache.go
- enterprise/server/backends/s3_cache/s3_cache.go
- enterprise/server/raft/cache/cache.go
- server/backends/disk_cache/disk_cache.go
- server/backends/memory_cache/memory_cache.go
- server/interfaces/interfaces.go
> Refactor caches to use ResourceName struct when generating cache keys

- enterprise/server/backends/distributed/BUILD
- enterprise/server/backends/distributed/distributed.go
- enterprise/server/backends/distributed/distributed_test.go
- enterprise/server/backends/gcs_cache/gcs_cache.go
- enterprise/server/backends/memcache/memcache.go
- enterprise/server/backends/migration_cache/migration_cache.go
- enterprise/server/backends/migration_cache/migration_cache_test.go
- enterprise/server/backends/pebble_cache/pebble_cache.go
- enterprise/server/backends/pebble_cache/pebble_cache_test.go
- enterprise/server/backends/redis_cache/redis_cache.go
- enterprise/server/backends/s3_cache/s3_cache.go
- enterprise/server/composable_cache/composable_cache.go
- enterprise/server/raft/cache/cache.go
- server/backends/disk_cache/disk_cache.go
- server/backends/disk_cache/disk_cache_test.go
- server/backends/memory_cache/memory_cache.go
- server/interfaces/interfaces.go
> Add cache contains method that takes a resourceName

- enterprise/server/backends/distributed/distributed.go
- enterprise/server/backends/distributed/distributed_test.go
- enterprise/server/backends/gcs_cache/gcs_cache.go
- enterprise/server/backends/memcache/memcache.go
- enterprise/server/backends/migration_cache/migration_cache.go
- enterprise/server/backends/migration_cache/migration_cache_test.go
- enterprise/server/backends/pebble_cache/pebble_cache.go
- enterprise/server/backends/pebble_cache/pebble_cache_test.go
- enterprise/server/backends/redis_cache/redis_cache.go
- enterprise/server/backends/s3_cache/s3_cache.go
- enterprise/server/composable_cache/composable_cache.go
- enterprise/server/raft/cache/cache.go
- enterprise/server/registry/registry.go
- enterprise/server/util/cacheproxy/cacheproxy.go
- enterprise/server/util/cacheproxy/cacheproxy_test.go
- server/backends/disk_cache/disk_cache.go
- server/backends/disk_cache/disk_cache_test.go
- server/backends/memory_cache/memory_cache.go
- server/buildbuddy_server/buildbuddy_server.go
- server/interfaces/interfaces.go
- server/remote_cache/byte_stream_server/byte_stream_server.go
> Add cache metadata method that takes a resourceName

- cli/release.py
The release process was fairly simple already, but this just saves a few steps (having to fetch tags to get the latest version, having to find the links for the current workflow progress, etc.).
---
> CLI: Add release script

- server/build_event_protocol/build_event_handler/build_event_handler.go
- server/util/clickhouse/BUILD
- server/util/clickhouse/clickhouse.go
https://github.com/buildbuddy-io/buildbuddy-internal/issues/1723
> wrap clickhouse write in a retry loop

- enterprise/server/remote_execution/containers/firecracker/firecracker.go
> Log VM logs if firecracker VM is still running after an hour.

- cli/example_plugins/go_deps/post_bazel.py
* Fix plugin always failing due to preference dir not existing initially (I didn't notice this during development because I had some earlier logic that always created the preferences dir, which I later removed)
* Fix bug that responding "always" wouldn't actually run gazelle (you'd have to run the build again to get it to actually run).
* Change preferences key name to more accurately reflect what it represents.
---
**Related issues**: Fixes https://github.com/buildbuddy-io/buildbuddy-internal/issues/1752
> CLI: Fix preferences logic for go deps plugin

- enterprise/server/api/api_server_test.go
- enterprise/server/backends/distributed/distributed.go
- enterprise/server/backends/gcs_cache/gcs_cache.go
- enterprise/server/backends/memcache/memcache.go
- enterprise/server/backends/migration_cache/migration_cache.go
- enterprise/server/backends/migration_cache/migration_cache_test.go
- enterprise/server/backends/pebble_cache/BUILD
- enterprise/server/backends/pebble_cache/pebble_cache.go
- enterprise/server/backends/pebble_cache/pebble_cache_test.go
- enterprise/server/backends/redis_cache/redis_cache.go
- enterprise/server/backends/s3_cache/s3_cache.go
- enterprise/server/composable_cache/composable_cache.go
- enterprise/server/raft/cache/cache.go
- enterprise/server/remote_execution/execution_server/execution_server.go
- enterprise/server/test/performance/cache/cache_test.go
- server/backends/disk_cache/disk_cache.go
- server/backends/disk_cache/disk_cache_test.go
- server/backends/memory_cache/memory_cache.go
- server/backends/memory_cache/memory_cache_test.go
- server/interfaces/interfaces.go
- server/remote_asset/fetch_server/fetch_server.go
- server/remote_cache/action_cache_server/action_cache_server.go
- server/remote_cache/cachetools/cachetools.go
- server/remote_cache/content_addressable_storage_server/content_addressable_storage_server.go
https://github.com/buildbuddy-io/buildbuddy/pull/2389
> Add cache get method that takes a resourceName

- enterprise/server/backends/distributed/distributed.go
- enterprise/server/backends/distributed/distributed_test.go
- enterprise/server/backends/gcs_cache/gcs_cache.go
- enterprise/server/backends/memcache/memcache.go
- enterprise/server/backends/migration_cache/migration_cache.go
- enterprise/server/backends/migration_cache/migration_cache_test.go
- enterprise/server/backends/pebble_cache/pebble_cache.go
- enterprise/server/backends/pebble_cache/pebble_cache_test.go
- enterprise/server/backends/redis_cache/redis_cache.go
- enterprise/server/backends/s3_cache/s3_cache.go
- enterprise/server/composable_cache/composable_cache.go
- enterprise/server/raft/cache/cache.go
- enterprise/server/test/performance/cache/cache_test.go
- enterprise/server/util/cacheproxy/cacheproxy.go
- server/backends/disk_cache/disk_cache.go
- server/backends/disk_cache/disk_cache_test.go
- server/backends/memory_cache/memory_cache.go
- server/backends/memory_cache/memory_cache_test.go
- server/interfaces/interfaces.go
- server/remote_cache/content_addressable_storage_server/content_addressable_storage_server.go
- server/remote_cache/content_addressable_storage_server/content_addressable_storage_server_test.go
> Add cache GetMulti method that takes a resourceName

- BUILD
Remove the commented-out analyzers that are just part of `vet=True` and enable the unsafeptr analyzer.
---
> Clean up go vet

- enterprise/server/remote_execution/containers/firecracker/firecracker.go
- enterprise/server/remote_execution/executor/executor.go
Also add logs specifically to Firecracker impl to help root cause hanging issues.
---
> Add some basic logs to executor during task execution.

- enterprise/server/remote_execution/containers/firecracker/firecracker.go
- enterprise/server/remote_execution/executor/executor.go
- enterprise/server/remote_execution/runner/runner.go
- enterprise/server/remote_execution/workspace/workspace.go
- enterprise/server/remote_execution/workspace/workspace_test.go
- enterprise/server/scheduling/priority_task_scheduler/priority_task_scheduler.go
- enterprise/server/scheduling/task_leaser/task_leaser.go
> Enrich executor logs with execution_id.

- enterprise/config/buildbuddy.release.yaml
- enterprise/server/cmd/server/BUILD
- server/cmd/buildbuddy/BUILD
There is no `/buildbuddy` directory in the release image, so we create a convenience symlink.
---
> Release config settings now use extant directories

- app/invocation/cache_requests_card.tsx
Also fix formatting issues (prettier checkstyle somehow missed these in an earlier PR)
---
> Fix rendering for CAS misses in scorecard

- enterprise/server/backends/migration_cache/migration_cache.go
- enterprise/server/backends/pebble_cache/pebble_cache.go
> Add debug logging for migration cache and fix contains logging

- server/build_event_protocol/build_event_handler/build_event_handler.go
- server/util/clickhouse/clickhouse.go
> Use CtxInfo in clickhouse logging

- cli/arg/arg.go
- cli/cmd/bb/bb.go
- cli/plugin/BUILD
- cli/plugin/plugin.go
> CLI: Add install subcommand

- cli/example_plugins/go_deps/post_bazel.sh
- cli/example_plugins/go_highlight/handle_bazel_output.sh
- cli/example_plugins/open_invocation/post_bazel.sh
- cli/example_plugins/open_invocation/pre_bazel.sh
> CLI: Gracefully handle missing system deps in plugins

- cli/cmd/bb/bb.go
> CLI: Don't invoke run script if build failed

- .github/workflows/release-cli.yaml
> CLI: Add workflow to sync plugins repo

- enterprise/server/backends/migration_cache/migration_cache.go
- enterprise/server/backends/migration_cache/migration_cache_test.go
- enterprise/server/backends/pebble_cache/pebble_cache.go
- server/remote_cache/digest/digest.go
- server/remote_cache/digest/digest_test.go
> In migration cache, copy data on FindMissing

- docs/enterprise-mac-rbe.md
Tested on mac executors.
---
**Version bump**: None 
**Related issues**: Fixes buildbuddy-io/buildbuddy-internal#847
> Add instructions to set up log rotation on mac

- docs/secrets.md
Not adding to the sidebar just yet, since it isn't launched.
---
> Add docs page for secrets

- app/router/router.tsx
- enterprise/app/settings/settings.tsx
> Add role check for secrets settings

- enterprise/server/remote_execution/execution_server/execution_server.go
- enterprise/server/remote_execution/platform/platform.go
- enterprise/server/workflow/service/service.go
> Expose secrets to trusted workflows

- enterprise/server/backends/migration_cache/migration_cache.go
* We shouldn't log destination not found errors if the src cache also had a not found error. This was making it seem like a lot more data was missing from the dest cache, when it was actually expected
* Also change a warning log -> debug log bc it was creating too much noise
> Fix logging in migration cache

- enterprise/server/backends/distributed/distributed.go
- enterprise/server/backends/gcs_cache/gcs_cache.go
- enterprise/server/backends/memcache/memcache.go
- enterprise/server/backends/migration_cache/migration_cache.go
- enterprise/server/backends/migration_cache/migration_cache_test.go
- enterprise/server/backends/pebble_cache/pebble_cache.go
- enterprise/server/backends/pebble_cache/pebble_cache_test.go
- enterprise/server/backends/redis_cache/redis_cache.go
- enterprise/server/backends/s3_cache/s3_cache.go
- enterprise/server/composable_cache/composable_cache.go
- enterprise/server/raft/cache/cache.go
- server/backends/disk_cache/disk_cache.go
- server/backends/disk_cache/disk_cache_test.go
- server/backends/memory_cache/memory_cache.go
- server/backends/memory_cache/memory_cache_test.go
- server/interfaces/interfaces.go
- server/remote_cache/content_addressable_storage_server/content_addressable_storage_server.go
- server/remote_cache/digest/digest.go
> Add cache SetMulti method that takes a resource name

- app/invocation/invocation_suggestion_card.tsx
> Disable bwtb suggestion

- enterprise/server/api/api_server.go
- enterprise/server/backends/distributed/distributed.go
- enterprise/server/backends/distributed/distributed_test.go
- enterprise/server/backends/gcs_cache/gcs_cache.go
- enterprise/server/backends/memcache/memcache.go
- enterprise/server/backends/migration_cache/migration_cache.go
- enterprise/server/backends/migration_cache/migration_cache_test.go
- enterprise/server/backends/pebble_cache/pebble_cache.go
- enterprise/server/backends/pebble_cache/pebble_cache_test.go
- enterprise/server/backends/redis_cache/redis_cache.go
- enterprise/server/backends/s3_cache/s3_cache.go
- enterprise/server/composable_cache/composable_cache.go
- enterprise/server/raft/cache/cache.go
- enterprise/server/util/cacheproxy/cacheproxy.go
- enterprise/server/util/cacheproxy/cacheproxy_test.go
- server/backends/disk_cache/disk_cache.go
- server/backends/memory_cache/memory_cache.go
- server/interfaces/interfaces.go
> Add cache delete method that takes a resource name

- enterprise/server/cmd/ci_runner/main.go
- enterprise/server/test/integration/ci_runner/BUILD
- enterprise/server/test/integration/ci_runner/ci_runner_test.go
> Expand env vars in CI runner `bazel_commands` list

- app/flame_chart/profile_model.ts
- app/invocation/invocation_timing_card.tsx
---
**Related issues**: Fixes https://github.com/buildbuddy-io/buildbuddy-internal/issues/1778
> Support partial timing profiles

- enterprise/server/backends/distributed/distributed.go
- enterprise/server/backends/distributed/distributed_test.go
- enterprise/server/backends/gcs_cache/gcs_cache.go
- enterprise/server/backends/memcache/memcache.go
- enterprise/server/backends/migration_cache/migration_cache.go
- enterprise/server/backends/migration_cache/migration_cache_test.go
- enterprise/server/backends/pebble_cache/pebble_cache.go
- enterprise/server/backends/pebble_cache/pebble_cache_test.go
- enterprise/server/backends/redis_cache/redis_cache.go
- enterprise/server/backends/s3_cache/s3_cache.go
- enterprise/server/composable_cache/composable_cache.go
- enterprise/server/composable_cache/composable_cache_test.go
- enterprise/server/raft/cache/cache.go
- enterprise/server/raft/cache/cache_test.go
- enterprise/server/registry/registry.go
- enterprise/server/util/cacheproxy/cacheproxy.go
- enterprise/server/util/cacheproxy/cacheproxy_test.go
- server/backends/disk_cache/disk_cache.go
- server/backends/disk_cache/disk_cache_test.go
- server/backends/memory_cache/memory_cache.go
- server/backends/memory_cache/memory_cache_test.go
- server/interfaces/interfaces.go
- server/remote_cache/byte_stream_server/byte_stream_server.go
> Add cache reader method that takes a resource name

- enterprise/server/backends/distributed/distributed.go
- enterprise/server/backends/gcs_cache/gcs_cache.go
- enterprise/server/backends/memcache/memcache.go
- enterprise/server/backends/migration_cache/migration_cache.go
- enterprise/server/backends/migration_cache/migration_cache_test.go
- enterprise/server/backends/pebble_cache/pebble_cache.go
- enterprise/server/backends/pebble_cache/pebble_cache_test.go
- enterprise/server/backends/redis_cache/redis_cache.go
- enterprise/server/backends/s3_cache/s3_cache.go
- enterprise/server/composable_cache/composable_cache.go
- enterprise/server/composable_cache/composable_cache_test.go
- enterprise/server/raft/cache/cache.go
- enterprise/server/raft/cache/cache_test.go
- enterprise/server/util/cacheproxy/cacheproxy.go
- enterprise/server/util/cacheproxy/cacheproxy_test.go
- server/backends/disk_cache/disk_cache.go
- server/backends/disk_cache/disk_cache_test.go
- server/backends/memory_cache/memory_cache.go
- server/backends/memory_cache/memory_cache_test.go
- server/interfaces/interfaces.go
- server/remote_cache/byte_stream_server/byte_stream_server.go
- server/remote_cache/cachetools/cachetools.go
> Add cache writer method that takes a resource name

- enterprise/app/BUILD.bazel
- enterprise/server/cmd/executor/BUILD
- enterprise/server/cmd/server/BUILD
- enterprise/server/image_converter/BUILD
- enterprise/server/tasksize/BUILD
> Update more visibilities in //enterprise that are depended on by -internal.

- server/build_event_protocol/build_event_server/build_event_server.go
> Return a more descriptive RPC error on seqno mismatch.

- enterprise/server/backends/pebble_cache/pebble_cache.go
- enterprise/server/raft/cache/cache.go
- enterprise/server/raft/client/client.go
- enterprise/server/raft/filestore/filestore.go
- enterprise/server/raft/replica/replica.go
- enterprise/server/raft/store/store.go
- enterprise/server/raft/store/store_test.go
> Move hash before isolation/type in metadata key for raft cache.

- enterprise/server/backends/distributed/distributed.go
- enterprise/server/backends/gcs_cache/gcs_cache.go
- enterprise/server/backends/memcache/memcache.go
- enterprise/server/backends/migration_cache/migration_cache.go
- enterprise/server/backends/migration_cache/migration_cache_test.go
- enterprise/server/backends/pebble_cache/pebble_cache.go
- enterprise/server/backends/pebble_cache/pebble_cache_test.go
- enterprise/server/backends/redis_cache/redis_cache.go
- enterprise/server/backends/s3_cache/s3_cache.go
- enterprise/server/composable_cache/composable_cache.go
- enterprise/server/raft/cache/cache.go
- enterprise/server/registry/registry.go
- enterprise/server/util/cacheproxy/cacheproxy.go
- enterprise/server/util/cacheproxy/cacheproxy_test.go
- server/backends/disk_cache/disk_cache.go
- server/backends/disk_cache/disk_cache_test.go
- server/backends/memory_cache/memory_cache.go
- server/buildbuddy_server/BUILD
- server/buildbuddy_server/buildbuddy_server.go
- server/interfaces/interfaces.go
- server/remote_cache/byte_stream_server/BUILD
- server/remote_cache/byte_stream_server/byte_stream_server.go
- server/remote_cache/digest/digest.go
> Clean up MetadataDeprecated function

- enterprise/server/cmd/executor/yaml_doc/BUILD
- enterprise/server/cmd/server/yaml_doc/BUILD
> Fix build visibility in enterprise/server/cmd docs so //website builds.

- enterprise/server/backends/migration_cache/migration_cache.go
- server/metrics/metrics.go
* The same bug I fixed [here](https://github.com/buildbuddy-io/buildbuddy/pull/2789) for logging was also making the metrics look worse than is true
> Fix metrics bug and add metric for copy chan size

- app/invocation/cache_requests_card.tsx
> Stop writing deprecated cache type field to cache scorecards

- enterprise/server/backends/distributed/distributed.go
- enterprise/server/backends/gcs_cache/gcs_cache.go
- enterprise/server/backends/migration_cache/migration_cache.go
- enterprise/server/backends/pebble_cache/pebble_cache.go
- enterprise/server/backends/s3_cache/s3_cache.go
- enterprise/server/composable_cache/composable_cache.go
- enterprise/server/raft/cache/cache.go
- enterprise/server/remote_execution/dirtools/dirtools_test.go
- enterprise/server/test/performance/cache/BUILD
- enterprise/server/test/performance/cache/cache_test.go
- enterprise/server/util/cacheproxy/cacheproxy_test.go
- server/backends/disk_cache/disk_cache.go
- server/backends/memory_cache/memory_cache.go
- server/backends/memory_cache/memory_cache_test.go
- server/interfaces/interfaces.go
- server/remote_cache/action_cache_server/BUILD
- server/remote_cache/action_cache_server/action_cache_server.go
- server/remote_cache/byte_stream_server/byte_stream_server_test.go
- server/remote_cache/content_addressable_storage_server/content_addressable_storage_server.go
> Cleanup SetDeprecated cache method

- enterprise/app/usage/usage.tsx
- enterprise/server/usage_service/usage_service.go
- proto/usage.proto
> Show Linux RBE minutes on usage page

- cli/plugin/plugin.go
* Set the correct dir for running `git checkout` (previously it'd run in the current working directory :sweat_smile:)
* If we fail to checkout, don't add the clone to the cache dir (otherwise the next run of "bb install" will incorrectly succeed, since we'll see that the plugin dir already exists)
---
> CLI: Fix plugin ref checkout logic

- cli/plugins/open_invocation/pre_bazel.sh
> CLI: Fix `open` plugin dependency check

- enterprise/server/backends/distributed/distributed.go
- enterprise/server/backends/gcs_cache/gcs_cache.go
- enterprise/server/backends/memcache/memcache.go
- enterprise/server/backends/migration_cache/migration_cache.go
- enterprise/server/backends/pebble_cache/pebble_cache.go
- enterprise/server/backends/pebble_cache/pebble_cache_test.go
- enterprise/server/backends/redis_cache/redis_cache.go
- enterprise/server/backends/s3_cache/s3_cache.go
- enterprise/server/composable_cache/composable_cache.go
- enterprise/server/raft/cache/cache.go
- enterprise/server/util/cacheproxy/cacheproxy.go
- server/backends/disk_cache/disk_cache.go
- server/backends/memory_cache/memory_cache.go
- server/backends/memory_cache/memory_cache_test.go
- server/interfaces/interfaces.go
- server/remote_cache/content_addressable_storage_server/BUILD
- server/remote_cache/content_addressable_storage_server/content_addressable_storage_server.go
- server/remote_cache/content_addressable_storage_server/content_addressable_storage_server_test.go
> Cleanup GetMultiDeprecated method

- app/flame_chart/BUILD
- app/flame_chart/profile_model_test.ts
> Add regression test for parseProfile

- enterprise/server/backends/distributed/distributed.go
- enterprise/server/backends/gcs_cache/gcs_cache.go
- enterprise/server/backends/memcache/memcache.go
- enterprise/server/backends/migration_cache/migration_cache.go
- enterprise/server/backends/pebble_cache/pebble_cache.go
- enterprise/server/backends/redis_cache/redis_cache.go
- enterprise/server/backends/s3_cache/s3_cache.go
- enterprise/server/composable_cache/composable_cache.go
- enterprise/server/raft/cache/cache.go
- server/backends/disk_cache/disk_cache.go
- server/backends/memory_cache/memory_cache.go
- server/interfaces/interfaces.go
- server/remote_cache/content_addressable_storage_server/content_addressable_storage_server.go
> Clean up SetMultiDeprecated

- enterprise/server/api/api_server.go
- enterprise/server/backends/distributed/distributed.go
- enterprise/server/backends/gcs_cache/gcs_cache.go
- enterprise/server/backends/memcache/memcache.go
- enterprise/server/backends/migration_cache/migration_cache.go
- enterprise/server/backends/migration_cache/migration_cache_test.go
- enterprise/server/backends/pebble_cache/pebble_cache.go
- enterprise/server/backends/redis_cache/redis_cache.go
- enterprise/server/backends/s3_cache/s3_cache.go
- enterprise/server/composable_cache/composable_cache.go
- enterprise/server/raft/cache/cache.go
- enterprise/server/util/cacheproxy/cacheproxy.go
- server/backends/disk_cache/disk_cache.go
- server/backends/memory_cache/memory_cache.go
- server/interfaces/interfaces.go
> Clean up DeleteDeprecated

- enterprise/server/backends/distributed/distributed.go
- enterprise/server/backends/gcs_cache/gcs_cache.go
- enterprise/server/backends/memcache/memcache.go
- enterprise/server/backends/migration_cache/migration_cache.go
- enterprise/server/backends/pebble_cache/pebble_cache.go
- enterprise/server/backends/redis_cache/redis_cache.go
- enterprise/server/backends/s3_cache/s3_cache.go
- enterprise/server/composable_cache/BUILD
- enterprise/server/composable_cache/composable_cache.go
- enterprise/server/composable_cache/composable_cache_test.go
- enterprise/server/raft/cache/BUILD
- enterprise/server/raft/cache/cache.go
- enterprise/server/raft/cache/cache_test.go
- enterprise/server/registry/registry.go
- enterprise/server/util/cacheproxy/cacheproxy.go
- enterprise/server/util/cacheproxy/cacheproxy_test.go
- server/backends/disk_cache/disk_cache.go
- server/backends/memory_cache/memory_cache.go
- server/backends/memory_cache/memory_cache_test.go
- server/interfaces/interfaces.go
- server/remote_cache/byte_stream_server/byte_stream_server.go
> Cleanup ReaderDeprecated

- enterprise/server/backends/distributed/distributed.go
- enterprise/server/backends/gcs_cache/gcs_cache.go
- enterprise/server/backends/memcache/memcache.go
- enterprise/server/backends/migration_cache/migration_cache.go
- enterprise/server/backends/pebble_cache/pebble_cache.go
- enterprise/server/backends/redis_cache/redis_cache.go
- enterprise/server/backends/s3_cache/s3_cache.go
- enterprise/server/composable_cache/composable_cache.go
- enterprise/server/composable_cache/composable_cache_test.go
- enterprise/server/raft/cache/cache.go
- enterprise/server/util/cacheproxy/cacheproxy.go
- enterprise/server/util/cacheproxy/cacheproxy_test.go
- server/backends/disk_cache/disk_cache.go
- server/backends/memory_cache/memory_cache.go
- server/backends/memory_cache/memory_cache_test.go
- server/interfaces/interfaces.go
- server/remote_cache/byte_stream_server/byte_stream_server.go
- server/remote_cache/cachetools/BUILD
- server/remote_cache/cachetools/cachetools.go
> Cleanup WriterDeprecated method

- docs/enterprise-mac-rbe.md
This allows it to work correctly with `multilog`.
---
**Version bump**: None.
> Add `PATH` to launch agent

- enterprise/config/executor.local.yaml
> Use per-user directories for executor root directory too.

- WORKSPACE
- app/flame_chart/flame_chart.tsx
- app/flame_chart/profile_model.ts
Populating these require these bazel flags to be set:
` --experimental_profile_include_primary_output` 
`--experimental_profile_include_target_label`
---
> Show target and out file on timing profile if they're set

- server/remote_asset/fetch_server/fetch_server.go
If we get a `Content-Length` header and the client has sent up an expected SHA256, then we know the full digest and can pipe the HTTP response body directly to cache instead of downloading it to disk first.
---
> Remote asset: Stream directly to cache if we know the digest ahead of time

- server/backends/disk_cache/disk_cache.go
- server/backends/disk_cache/disk_cache_test.go
> Fix disk cache v1 eviction bug if root dir ends with slash.

- server/backends/disk_cache/disk_cache.go
- server/backends/disk_cache/disk_cache_test.go
> Default to v2 disk cache layout for new installations.

- docs/secrets.md
- website/sidebars.js
To be submitted once the secrets UI is enabled.
---
> Add secrets to docs site sidebar

- enterprise/server/scheduling/priority_task_scheduler/priority_task_scheduler.go
- server/util/log/log.go
> Fix nil ctx in priority_task_scheduler logging.

- tools/metrics/grafana/dashboards/buildbuddy.json
- Add raft read/write QPS graphs
- Add raft ranges graph
- Add range sizes graph
- Add raft proposals QPS
- Add raft splits
- Add raft moves
- Add rangecache hit rate
- Add split duration
- Move panel down
> raft graphs

- cli/parser/parser.go
- cli/parser/parser_test.go
* Respect multiple `--bazelrc` args
* Respect `--bazelrc=/dev/null` which should cause subsequent `--bazelrc` args to be ignored
* Respect `--ignore_all_rc_files` flag
* Fix parsing of `--noworskpace_rc`, `--nosystem_rc` etc. (Bazel only allows setting these as `--workspacerc` or `--noworkspace_rc` -- other forms like `--workspace_rc=no` don't work).
* Prevent RC files from being expanded more than once, by adding `--ignore_all_rc_files` to the expanded bazelrc args. Before this fix, we'd expand default args from bazelrcs (like `build --incompatible_strict_action_env`), and then Bazel would do it again once invoked, duplicating the args from those RCs. This can cause correctness issues.
---
> CLI: More bazelrc parsing fixes

- tools/metrics/grafana/dashboards/buildbuddy.json
Previously these were just summed, now I graph the rate which is more useful.
> Graph moves/Splits by QPS

- enterprise/server/remote_execution/platform/BUILD
- enterprise/server/remote_execution/platform/platform.go
- enterprise/server/remote_execution/platform/platform_test.go
- enterprise/server/tasksize/tasksize.go
- enterprise/server/workflow/config/config.go
- enterprise/server/workflow/service/service.go
Example:
```
actions:
- name: Test
triggers: ...
resource_requests:
memory: 10GB   # = 10*(1024^3) bytes
cpu: 4         # = 4 cores
bazel_commands: ...
```
---
**Related issues**: https://github.com/buildbuddy-io/buildbuddy-internal/issues/1765
> Make workflow memory / CPU configurable

- docs/workflows-config.md
> Workflows: Update docs with new config options

- cli/plugins/go_deps/post_bazel.py
> Use a nicer color for go_deps prompt

- website/src/pages/open-source-repos.tsx
> Fix spacing on open source page of marketing website

- website/docusaurus.config.js
- website/src/components/cta/cta.tsx
- website/src/components/hero/hero.module.css
- website/src/components/hero/hero.tsx
- website/src/components/terminal/terminal.module.css
- website/src/components/terminal/terminal.tsx
- website/src/pages/cli.tsx
- website/src/pages/plugins.module.css
- website/src/pages/plugins.tsx
- website/src/util/clipboard.ts
> Add marketing website for CLI & plugin library

- docs/cli.md
- website/src/pages/cli.tsx
- website/src/pages/plugins.tsx
> Fix some broken links on the marketing website

- website/src/pages/plugins.module.css
> Make the plugin library look nice on smaller screens

- server/util/lru/lru.go
We weren't actually clearing the slice reference on removal.
---
> Fix memory leak in LRU.

- go.mod
- server/backends/disk_cache/BUILD
- server/backends/disk_cache/disk_cache.go
- server/interfaces/interfaces.go
Also show friendlier capacity units.
---
> Show number of items in disk cache in statusz.

- cli/plugins/go-deps/README.md
> Add README for go-deps plugin

- enterprise/server/cmd/ci_runner/run_local.sh
- enterprise/server/test/integration/ci_runner/BUILD
- enterprise/server/test/integration/workflow/BUILD
- enterprise/server/workflow/service/service.go
> Bump CI runner image version

- website/docusaurus.config.js
> Plugins => Plugin Library

- server/backends/disk_cache/disk_cache.go
hex.DecodeString uses twice as much memory per digest than needed.
---
> Make digest decoding slightly more memory efficient.

- docs/cli-plugins.md
> Add plugin uninstall instructions

- server/remote_asset/fetch_server/fetch_server.go
- server/remote_cache/digest/digest.go
No matter what happens, you gotta stay positive!
---
> Enhance digest validation.

- docs/cli.md
- website/src/pages/cli.tsx
> CLI: bump version in docs to 0.0.15

- website/src/pages/pricing.tsx
Submit on Wednesday for Bazelcon
---
> Bump free tier user limit

- cli/help/help.go
> CLI: Add help section for subcommands

- server/util/db/db.go
All of the 'dialect' (gorm term) references are actually references to the go sql driver names. 
It's confusing because there are places in our codebase where we refer to the gorm dialect which have different values.
---
> Fix dialect/driver naming in db.go

- enterprise/server/cmd/executor/executor.go
Doesn't cause actual harm, but we get questions from customers thinking something abnormal is going on.
---
> Don't treat idle executor->cache connection as unhealthy.

- buildbuddy.yaml
- buildpatches/bazelisk.patch
- cli/sidecar/sidecar.go
- cli/test/integration/cli/BUILD
- cli/test/integration/cli/cli_test.go
- cli/testutil/testcli/BUILD
- cli/testutil/testcli/testcli.go
- deps.bzl
- server/testutil/testbazel/BUILD
- server/testutil/testbazel/testbazel.go
- server/testutil/testfs/testfs.go
> CLI: add a few basic integration tests

- BUILD
- buildfix.sh
- rules/go/index.bzl
> Update buildfix.sh to use the gofmt tool included in rules_go

- cli/sidecar/sidecar.go
* If the sidecar exited unexpectedly (e.g. force-quit) then make sure we can recover. The recovery logic is just to remove the sidecar socket (assuming that no one is listening on the socket) and then trying again.
* When establishing the initial sidecar connection, use a faster poll rate so that we can connect as soon as it's available, rather than having to wait up to 1s after it becomes ready.
---
> CLI: Make initial sidecar connection faster and more robust

- website/src/css/nav.css
> Add subtle frosted glass effect to marketing nav bar

- app/invocation/BUILD
- app/invocation/invocation_details_card.tsx
- package.json
- yarn.lock
**Related issues**: Fixes #1756
> Wrap CLI arguments containing spaces in quotation marks when rendered on the invocation details card.

- website/src/css/nav.css
> Make the nav glass a little more opaque

- app/invocation/invocation_breakdown_card.tsx
> Fix timing breakdown titles

- server/tables/tables.go
This index will help to look up execution id -> invocation id
> add execution id index in InvocationExecutionTable

- server/http/filters/BUILD
- server/http/filters/filters.go
> Reduce cardinality of HTTP metrics

- proto/invocation.proto
add execution stats in GetTrendResponse
> add execution stats in GetTrendResponse

- server/util/log/log.go
> Fix structured logging.

- server/util/log/log.go
> Fix log level handling

- app/invocation/invocation_breakdown_card.tsx
> Add Swift and ObjC compilation to execution breakdown

- app/invocation/invocation_breakdown_card.tsx
> Fix uploading outputs label on breakdown card

- server/metrics/metrics.go
- server/util/compression/BUILD
- server/util/compression/compression.go
> Add metric for num decompressed bytes that pass through zstd encoders/decoders

- rules/go/index.bzl
> Make gofmt target run in current directory

- server/util/log/BUILD
- server/util/log/log_test.go
> Add tests for log configuration

- .bazelrc
- .github/workflows/checkstyle.yaml
- WORKSPACE
- cli/parser/parser.go
- deps.bzl
- enterprise/server/backends/distributed/distributed.go
- enterprise/server/backends/pubsub/pubsub.go
- enterprise/server/raft/store/store.go
- enterprise/server/remote_execution/filecache/filecache.go
- enterprise/server/util/redisutil/redisutil.go
- server/backends/disk_cache/disk_cache.go
- server/interfaces/interfaces.go
- server/remote_cache/action_cache_server/action_cache_server.go
- server/remote_cache/content_addressable_storage_server/content_addressable_storage_server.go
- server/remote_cache/hit_tracker/hit_tracker.go
- server/util/alert/alert.go
- server/util/approximatelru/approximatelru.go
- server/util/cache_metrics/cache_metrics.go
- server/util/canary/canary.go
- server/util/db/db.go
- server/util/flagutil/types/types.go
- server/util/networking/networking.go
- server/util/query_builder/query_builder.go
- server/util/retry/retry.go
- server/util/scratchspace/scratchspace.go
- server/version/version.go
- tools/cas/cas.go
- tools/rbeperf/rbeperf.go
Bumps the versions for `gazelle`, `rules_go`, and `bazel`.
---
> Upgrade `go` version to 1.19

- config/buildbuddy.dev.yaml
- config/buildbuddy.local.yaml
- enterprise/config/buildbuddy.local.yaml
- enterprise/server/test/integration/build_logs/build_logs_test.go
- server/build_event_protocol/build_event_handler/build_event_handler.go
- server/testutil/testenv/testenv.go
In response to buildbuddy-io/buildbuddy-internal#1828. We will re-enable this once the bug has been identified and fixed.
---
> Reverts the change which enabled chunked event logging by default

- .bazelrc
> Enable --experimental_remote_build_event_upload=minimal

- cli/release.py
- docs/cli.md
- website/src/pages/cli.tsx
(Also fix release script to pass the version correctly)
---
> CLI: bump version in docs to 0.1.1

- enterprise/server/backends/migration_cache/config.go
- enterprise/server/backends/migration_cache/migration_cache.go
- enterprise/server/backends/pebble_cache/pebble_cache.go
- enterprise/server/backends/pebble_cache/pebble_cache_test.go
- enterprise/server/raft/cache/cache.go
- enterprise/server/raft/replica/replica.go
- enterprise/server/raft/replica/replica_test.go
- enterprise/server/raft/store/store.go
- enterprise/server/raft/store/store_test.go
- proto/raft.proto
- server/backends/disk_cache/disk_cache.go
- server/metrics/metrics.go
> Compress all data above a certain size before writing to pebble cache

- enterprise/server/remote_execution/container/container.go
- enterprise/server/remote_execution/container/container_test.go
- enterprise/server/remote_execution/runner/runner.go
**Related issues**: Fixes https://github.com/buildbuddy-io/buildbuddy-internal/issues/1795
> Return InvalidArgumentErrors when either username or password for pulling container image are empty.

- cli/sidecar/sidecar.go
> CLI: Prevent Ctrl+C from killing the sidecar

- app/invocation/invocation_suggestion_card.tsx
> Hide timing suggestion card if all flags are set

- website/src/pages/security-updates.md
> Make security updates marketing page clearer

- BUILD
- enterprise/server/cmd/server/BUILD
- enterprise/server/test/integration/invocation_webhook/BUILD
- enterprise/server/test/integration/invocation_webhook/invocation_webhook_test.go
- server/libmain/libmain.go
- server/testutil/testenv/testenv.go
- server/util/db/BUILD
- server/util/db/db.go
- server/util/db/db_test.go
> Embed AWS RDS CA certs instead of packaging them in the docker image.

- docs/workflows-config.md
> Expand docs for workflows setup and configuration

- enterprise/server/backends/pebble_cache/pebble_cache.go
For decompressed data, the stored size should always equal the size in the cached digest
> Add debug logging when writing corrupted pebble metadata

- enterprise/server/remote_execution/containers/firecracker/firecracker.go
- server/util/networking/networking.go
> Fix the netns provided to Firecracker, it wasn't updated to include the new 'bb-executor' prefix

- tools/cacheload/cacheload.go
Add a flag to keep going even if an error is encountered during a cache loadtest.
Also cleanup the flag precondition checking and logging a little bit.
> Cacheload don't die

- enterprise/server/backends/pebble_cache/pebble_cache.go
> Add CAS cache type check to metadata mismatch logging

- enterprise/server/raft/store/store.go
It's much cleaner if we can request a leader transfer before shutting down so another node can take over, rather than disappearing and waiting for the rangelease to time out.
> Request leader transfer on shutdown

- server/remote_cache/byte_stream_server/byte_stream_server.go
> Revert QueryWriteStatus changes.

- server/remote_cache/byte_stream_server/byte_stream_server.go
> Delete enable_query_write_status_cache_check flag.

- enterprise/server/raft/constants/constants.go
- enterprise/server/raft/store/store.go
- proto/raft.proto
> Remove NodeUsage

- enterprise/config/executor.local.yaml
- enterprise/server/remote_execution/containers/firecracker/firecracker.go
> Flip executor.firecracker_cgroup_version to 2 everywhere.

- enterprise/server/backends/pebble_cache/pebble_cache.go
- enterprise/server/raft/cache/cache.go
- enterprise/server/raft/constants/constants.go
- enterprise/server/raft/filestore/filestore.go
- enterprise/server/raft/replica/BUILD
- enterprise/server/raft/replica/replica.go
- enterprise/server/raft/replica/replica_test.go
- enterprise/server/raft/store/store.go
- enterprise/server/raft/store/store_test.go
- proto/raft.proto
> Track # of file records & size in each replica.

- enterprise/server/backends/distributed/distributed.go
It can mess up the digest size & timestamps.
---
> Don't backfill on Metadata call.

- enterprise/server/remote_execution/execution_server/BUILD
- enterprise/server/remote_execution/execution_server/execution_server.go
In case the original context is cancelled.
---
> Use a disconnected context for execution cleanup.

- enterprise/server/backends/distributed/distributed_test.go
- enterprise/server/backends/gcs_cache/gcs_cache.go
- enterprise/server/backends/memcache/memcache.go
- enterprise/server/backends/migration_cache/migration_cache_test.go
- enterprise/server/backends/pebble_cache/pebble_cache.go
- enterprise/server/backends/pebble_cache/pebble_cache_test.go
- enterprise/server/backends/redis_cache/redis_cache.go
- enterprise/server/backends/s3_cache/s3_cache.go
- enterprise/server/registry/registry.go
- enterprise/server/util/cacheproxy/cacheproxy.go
- enterprise/server/util/cacheproxy/cacheproxy_test.go
- proto/distributed_cache.proto
- server/backends/disk_cache/disk_cache.go
- server/backends/disk_cache/disk_cache_test.go
- server/backends/memory_cache/memory_cache.go
- server/buildbuddy_server/buildbuddy_server.go
- server/interfaces/interfaces.go
- server/remote_asset/fetch_server/fetch_server.go
> Add digestSize to cache metadata API

- enterprise/server/backends/pebble_cache/BUILD
- enterprise/server/backends/pebble_cache/pebble_cache.go
- enterprise/server/backends/pebble_cache/pebble_cache_test.go
- enterprise/server/raft/bringup/bringup.go
- enterprise/server/raft/constants/constants.go
- enterprise/server/raft/keys/keys.go
- enterprise/server/raft/rangecache/BUILD
- enterprise/server/raft/rangecache/rangecache_test.go
- enterprise/server/raft/rangelease/BUILD
- enterprise/server/raft/rangelease/rangelease.go
- enterprise/server/raft/rangelease/rangelease_test.go
- enterprise/server/raft/replica/replica.go
- enterprise/server/raft/replica/replica_test.go
> Clean up duplicate MaxByte/MinByte consts.

- server/build_event_protocol/build_event_handler/build_event_handler.go
The default is `false` and we don't explicitly set it to true anywhere.
---
> Clean up `--app.require_invocation_event_parse_on_read`

- enterprise/config/executor.local.yaml
- enterprise/server/remote_execution/containers/firecracker/firecracker.go
This reverts commit 4d6fe0162cff823cb0544e3967f5718228d24e4f.
---
> Revert "Flip executor.firecracker_cgroup_version to 2 everywhere. (#3066)"

- enterprise/server/backends/migration_cache/migration_cache.go
> Return early if data already copied when dequeuing during cache migration

- server/build_event_protocol/build_event_handler/build_event_handler.go
> Remove unused writeCompletedBlob function

- docs/workflows-setup.md
- enterprise/app/workflows/create_workflow.tsx
- enterprise/app/workflows/github_import.tsx
> Workflows: Update setup docs and UI messaging

- enterprise/server/backends/migration_cache/migration_cache.go
- server/metrics/metrics.go
> Add counter for number of blobs and bytes copied during cache migration

- enterprise/server/backends/migration_cache/migration_cache.go
- enterprise/server/backends/migration_cache/migration_cache_test.go
> Fix rate limiter in migration cache

- enterprise/server/backends/migration_cache/config.go
- enterprise/server/backends/migration_cache/migration_cache.go
- enterprise/server/backends/pebble_cache/pebble_cache.go
- server/backends/disk_cache/disk_cache.go
- server/metrics/metrics.go
Fixes buildbuddy-io/buildbuddy-internal#1874
> Add configurable cache name to pebble metrics and statusz

- app/router/router.tsx
- enterprise/app/sidebar/sidebar.tsx
- server/buildbuddy_server/buildbuddy_server.go
- server/role_filter/role_filter.go
- server/role_filter/role_filter_test.go
This determines whether or not you need to be an admin to create a new group.
---
> Add `app.admin_only_create_group` config option 

- enterprise/server/backends/pebble_cache/pebble_cache.go
> Don't kill eviction goroutines on error.

- website/blog/whats-new-in-bazel-5-0.md
> Adjust some links in the Bazel 5.0 blog post

- website/blog/whats-new-in-bazel-6-0.md
> Fix spaces in Bazel 6.0 post

- enterprise/server/auth/auth.go
For API requests, we create a `Claims` based on the authenticated group and then mint a JWT from that, and store only the JWT in the context. Later, when we retrieve the claims (in `authenticatedUser`), we have to parse the JWT to reconstitute the original claims.
This PR stores both the claims and the JWT in the context so that we can just retrieve the original claims instead of having to reconstitute it from the JWT. This should reduce app CPU usage by about 9% based on current profiling data.
---
> Performance: Store claims in context to avoid parsing

- website/blog/whats-new-in-bazel-6-0.md
> Add 6.0 permalinks to 6.0 blog post

- proto/cache.proto
- server/buildbuddy_server/buildbuddy_server.go
> Add digest size to GetCacheMetadata API

- enterprise/server/backends/pebble_cache/pebble_cache.go
> Cleanup metadata size mismatch debug logging

- server/remote_asset/fetch_server/fetch_server.go
The code adding the new field was rolled out in release bb_release_20221214_142551
> Cleanup distributed rollout fallback code

- tools/metrics/grafana/dashboards/buildbuddy.json
Add:
* Server handling duration by method (for currently selected quantile)
* Client messages sent by method (QPS)
---
> Add a few more gRPC charts to Grafana

- server/gossip/gossip.go
- server/gossip/gossip_test.go
- Quiesce gossip messages and re-enable logs
- Fix test
> Coalesce gossip messages and re-enable logs

- enterprise/server/raft/driver/driver.go
This CL does not yet move the leases at all; it just computes the set of leases that might be good candidates to move.
> Compute the set of moveable leases that could be rebalanced

- server/build_event_protocol/accumulator/BUILD
- server/build_event_protocol/accumulator/accumulator.go
- server/build_event_protocol/build_event_handler/build_event_handler.go
> Log differences between accumulator/event parser

- enterprise/server/backends/migration_cache/migration_cache.go
> Add more migration logging to investigate eof error

- enterprise/app/trends/trends.tsx
Added a little function to return an empty object when getting values from the map (values will still be zero).
> Clean up a bunch of 'x might be undefined' warnings, etc., in trends component.

- enterprise/server/backends/pebble_cache/pebble_cache.go
- Use a per-partition random source to avoid lock contention
- Avoid string concatenation
---
> More efficient random key generation.

- app/invocation/invocation.css
> Prevent root cause badge from wrapping

- tools/cas/BUILD
- tools/cas/cas.go
> CAS tool: Don't append trailing newline when stdout is not a terminal

- server/build_event_protocol/accumulator/accumulator.go
- server/build_event_protocol/event_parser/event_parser.go
> Refactor: Consolidate Pattern() implementation

- enterprise/server/backends/distributed/distributed.go
- enterprise/server/backends/gcs_cache/gcs_cache.go
- enterprise/server/backends/memcache/memcache.go
- enterprise/server/backends/migration_cache/migration_cache.go
- enterprise/server/backends/pebble_cache/pebble_cache.go
- enterprise/server/backends/redis_cache/redis_cache.go
- enterprise/server/backends/s3_cache/s3_cache.go
- enterprise/server/composable_cache/composable_cache.go
- enterprise/server/raft/cache/cache.go
- server/backends/disk_cache/disk_cache.go
- server/backends/memory_cache/memory_cache.go
- server/interfaces/interfaces.go
> Rename offset to uncompressedOffset to that the semantics are clear.

- enterprise/server/backends/pebble_cache/pebble_cache.go
- enterprise/server/backends/pebble_cache/pebble_cache_test.go
> Fix seeking in compressed blobs.

- enterprise/server/backends/pebble_cache/pebble_cache.go
> Use per-partition RNG source for random key generation.

- cli/parser/BUILD
- cli/parser/parser.go
- cli/parser/parser_test.go
> CLI: Handle .bazelrc flags containing spaces

- enterprise/server/backends/pebble_cache/BUILD
- enterprise/server/backends/pebble_cache/pebble_cache.go
- server/metrics/metrics.go
> Add some metrics for monitoring eviction state.

- enterprise/server/backends/pebble_cache/pebble_cache.go
- server/metrics/metrics.go
> Metric for item count.

- docs/cli.md
- website/src/pages/cli.tsx
> CLI: bump version in docs to 0.1.4

- enterprise/server/api/BUILD
- enterprise/server/api/api_server.go
- enterprise/server/api/api_server_test.go
- proto/api/v1/invocation.proto
> Add `include_metadata` option to GetInvocationRequest API

- enterprise/server/backends/pebble_cache/pebble_cache.go
- enterprise/server/backends/pebble_cache/pebble_cache_test.go
> Fix eviction when "isolate by group ID" is on.

- cli/metadata/BUILD
- cli/metadata/metadata.go
- cli/test/integration/cli/BUILD
- cli/test/integration/cli/cli_test.go
- cli/testutil/testcli/BUILD
- cli/testutil/testcli/testcli.go
- enterprise/server/test/integration/ci_runner/BUILD
- enterprise/server/test/integration/ci_runner/ci_runner_test.go
- enterprise/server/test/integration/workflow/BUILD
- enterprise/server/test/integration/workflow/workflow_test.go
- enterprise/server/workflow/service/BUILD
- enterprise/server/workflow/service/service_test.go
- server/testutil/testgit/BUILD
- server/testutil/testgit/testgit.go
> CLI: automatically set git metadata

- tools/metrics/docker-compose.grafana.yml
- tools/metrics/grafana/dashboards/buildbuddy.json
I saved the dashboard without changes to get the migration changes out of the way.
---
> Upgrade local grafana version to latest.

- tools/metrics/grafana/dashboards/buildbuddy.json
- Filesytem graph shows % used instead of absolute numbers
- Add graph for eviction rate
- Add graph for partition usage
- Remove "time since last access" graph since the metric is not populated
---
> Update cache related metrics on dashboard:

- server/remote_cache/content_addressable_storage_server/content_addressable_storage_server.go
This fixes a bug that caused invalid digest errors when we tried to turn compression on for executors. There was a period of time where we'd added the code to support compression to pebble, but we hadn't enabled compression for callers to the cache. Because we didn't have this condition, we were reading compressed data from the cache, but later in the cas_server code there's some additional logic that checks whether the cache supports compression. Because one spot thought compression was on and the other didn't, that caused the errors.
> Fix compression bug in BatchReadBlobs

- cli/cmd/sidecar/BUILD
- cli/cmd/sidecar/sidecar.go
- enterprise/server/auth/auth.go
- enterprise/server/selfauth/BUILD
- enterprise/server/selfauth/selfauth.go
- enterprise/server/telemetry/BUILD
- enterprise/server/telemetry/telemetry_server.go
- server/backends/github/BUILD
- server/backends/github/github.go
- server/http/interceptors/BUILD
- server/http/interceptors/interceptors.go
- server/libmain/BUILD
- server/libmain/libmain.go
- server/rpc/interceptors/BUILD
- server/rpc/interceptors/interceptors.go
- server/rpc/interceptors/interceptors_test.go
- server/testutil/testenv/BUILD
- server/testutil/testenv/testenv.go
- server/util/grpc_client/BUILD
- server/util/grpc_client/grpc_client.go
- server/util/grpc_server/BUILD
- server/util/grpc_server/grpc_server.go
- Rename rpc/filters -> rpc/interceptors
- Rename http/filters -> http/interceptors
> Rename filters -> interceptors for clarity

- enterprise/server/backends/pebble_cache/pebble_cache.go
> Log item access time when evicting.

- enterprise/server/test/integration/remote_execution/rbetest/rbetest.go
- server/remote_cache/capabilities_server/BUILD
- server/remote_cache/capabilities_server/capabilities_server.go
- server/util/bazel_request/bazel_request.go
---
**Related issues**: Fixes https://github.com/buildbuddy-io/buildbuddy-internal/issues/1801
> Return update enabled capability based on API key permissions

- server/backends/disk_cache/BUILD
- server/backends/disk_cache/disk_cache.go
> Parity between disk cache and pebble cache metrics.

- enterprise/server/raft/store/store.go
- server/util/approxlru/approxlru.go
- server/util/approxlru/approxlru_test.go
> Make approxlru sampling parameters configurable.

- enterprise/server/workflow/service/service.go
- enterprise/server/workflow/service/service_test.go
Using a non-normalized repo URL would cause the UI to crash and the workflows page would become unusable even after a refresh. This PR fixes that.
---
> Workflows: Fix repo URL normalization

- enterprise/server/api/api_server.go
- server/build_event_protocol/build_event_handler/build_event_handler.go
- server/buildbuddy_server/buildbuddy_server.go
This may give us insight into what's happening with log chunking and AWS.
---
> Add logging for when GetEventLogChunk fails

- enterprise/server/backends/pebble_cache/pebble_cache.go
Until we have a more robust AC eviction implementation in place.
---
> Switch to CAS-only eviction for now.

- docs/config-olap-databases.md
write docs for OLAP database configuration
> write docs for OLAP database configuration

- server/backends/chunkstore/BUILD
- server/backends/chunkstore/chunkstore.go
- server/backends/chunkstore/chunkstore_test.go
This setting will not interoperate with chunks that were stored prior to the flag being turned on.
---
> Add flag to put every chunk in its own bucket

- app/util/BUILD
- app/util/async.ts
- app/util/proto.ts
- app/util/time_delta.ts
> Enable strict mode for app/util targets

- app/util/proto.ts
- enterprise/app/filter/BUILD
- enterprise/app/filter/filter.tsx
- enterprise/app/filter/filter_util.tsx
- enterprise/app/history/history.tsx
Starting with these because I've done the most damage in here already. I'm curious what you think of what I did to the advancedFilterStateFromUrl function and if there's a better way to solve that problem -- I thought of one, to make State a class with updating functionality, but that's a bit more involved.
**Related issues**: Unblocks https://github.com/buildbuddy-io/buildbuddy-internal/issues/936
> Fix types in //enterprise/app/filter to comply with TypeScript strict type checking.

- enterprise/server/raft/cache/cache.go
- enterprise/server/raft/store/store.go
- enterprise/server/raft/store/store_test.go
> Set store gRPC address at creation time.

- enterprise/server/backends/pebble_cache/BUILD
- enterprise/server/backends/pebble_cache/pebble_cache.go
- enterprise/server/raft/store/store.go
- server/util/approxlru/approxlru.go
- server/util/approxlru/approxlru_test.go
I'll hold off merging until after the next release to give us more time to test this in dev.
---
> Switch pebble cache to approxlru implementation.

- enterprise/server/backends/userdb/userdb.go
- enterprise/server/backends/userdb/userdb_test.go
This helps prevent confusion between personal groups and domain groups.
---
> Only add user to a personal group if not associated with a domain

- app/components/digest/BUILD
- app/components/digest/digest.tsx
- app/components/link/BUILD
- app/components/link/link.tsx
- app/components/scrollbar/BUILD
- app/components/scrollbar/scrollbar.tsx
> Enable strict mode for digest, link, and scrollbar

- enterprise/server/test/integration/remote_execution/rbetest/rbetest.go
`flags.Set()` creates a `t.Cleanup` func to reset the flag to its previous value. This cleanup func was running at the same time as `flushInvocationStatsToOLAPDB()`, a background func spawned by the build event handler. This `flush` func reads flag values (to check whether the stats flush is enabled), but the `t.Cleanup` was trying to reset the flag values at the same time (a data race).
The fix is to gracefully shut down all BB servers at the end of each test, so that the invocation stats flush completes before the flag cleanup logic is run. This is consistent with how we shut down executors at the end of each test.
---
> Fix data race in RBE test env

- enterprise/server/backends/pebble_cache/pebble_cache.go
Not sure why we are seeing so many duplicate writes...
---
> Don't update size on duplicate writes.

- enterprise/server/backends/pebble_cache/BUILD
- enterprise/server/backends/pebble_cache/pebble_cache.go
> Annotate spans that contain duplicate writes.

- enterprise/server/remote_execution/execution_server/execution_server.go
Currently, we extended the deadline to write executions in clickhouse
but not for mysql. In some cases where when the execution is
complete but the context is cancelled, we
don't write to mysql as a result, but we did write to clickhouse.
Fixes https://github.com/buildbuddy-io/buildbuddy-internal/issues/1950
> Extend context deadline for updating executions

- server/remote_cache/content_addressable_storage_server/content_addressable_storage_server.go
> Fix metrics bug caused by defer in a for loop

- enterprise/app/login/BUILD
- enterprise/app/login/login.tsx
**Related issues**: Unblocks https://github.com/buildbuddy-io/buildbuddy-internal/issues/936
> Flip strict=True for //enterprise/app/login

- enterprise/server/backends/pebble_cache/pebble_cache.go
Enabling compression might cause some stored sizes to be updated.
---
> Take existing blob size into account when updating delta.

- server/remote_cache/hit_tracker/hit_tracker.go
> Add missing return

- enterprise/server/backends/pebble_cache/pebble_cache.go
> Don't update metrics on duplicate AC writes since these are normal.

- app/invocation/invocation.tsx
- app/menu/menu.tsx
- app/root/BUILD.bazel
- app/root/root.tsx
- app/terminal/terminal.tsx
- enterprise/app/root/root.tsx
Version bump: Patch
Related issues: Unblocks https://github.com/buildbuddy-io/buildbuddy-internal/issues/936
> Flip strict=True for //enterprise/app/root

- enterprise/server/backends/authdb/authdb.go
> Redact invalid API key

- enterprise/server/workflow/service/service.go
Also attempt to clarify the ambiguous "Failed to start workflow: Record not found" error by adding more context to the Workflow table lookup.
---
> Workflows: include webhook ID in error logs

- app/invocation/invocation_details_card.tsx
- app/invocation/invocation_model.tsx
- app/invocation/invocation_overview.tsx
> Show CPU details for workflows

- docs/cli-plugins.md
- docs/workflows-config.md
- docs/workflows-setup.md
Also fix a minor issue w/ CLI docs.
---
> Update workflow docs with Ubuntu 20.04 images

- enterprise/server/backends/pebble_cache/pebble_cache.go
> By default auto-compress everything in pebble cache

- enterprise/server/raft/store/store.go
Lease verification may involve a Raft operation and this function may be called from with a Raft update preventing the lease Raft operation from completing.
---
> Fix usage deadlock.

- enterprise/server/remote_execution/vmexec_client/vmexec_client.go
> Fix panic when VM sync RPC fails

- server/metrics/metrics.go
- server/version/BUILD
- server/version/version.go
---
**Related issues**: https://github.com/buildbuddy-io/buildbuddy-internal/issues/1967
> Add metric for binary version

- website/src/css/nav.css
Fixes https://github.com/buildbuddy-io/buildbuddy-internal/issues/1975
---
> Fix sidebar being hidden on small devices by css bug

- enterprise/server/backends/pebble_cache/pebble_cache.go
Currently the metrics are updated only if there are writes or evictions which can cause artifacts when looking at aggregate data.
---
> Update partition size metrics even if there are no writes.

- enterprise/server/backends/pebble_cache/pebble_cache.go
We are already scanning over the entire pebble DB so there's no additional cost to do this.
This will give us an idea of how much uncompressed data is still present in the cache.
---
> Log number and size of uncompressed entries.

- enterprise/server/auth/auth.go
- enterprise/server/backends/authdb/authdb.go
- server/buildbuddy_server/buildbuddy_server.go
- server/interfaces/interfaces.go
- server/ssl/ssl.go
- Parses and validates certs if sent via the x-ssl-cert header (so client certs can be passed on by nginx)
- Generates new certs with api key id as the serial number rather than the value (to support short-lived certs)
- Makes these changes in a backwards-compatible way
---
> Client cert improvements

- app/auth/auth_service.ts
> Fix bug that create org flow doesn't switch to the new org after creating

- enterprise/server/remote_execution/platform/platform.go
- enterprise/server/remote_execution/platform/platform_test.go
- enterprise/server/workflow/config/config.go
- enterprise/server/workflow/service/service.go
This will allow users to work around workflows failing due to hitting disk limits.
---
> Workflows: make disk configurable

- proto/api_key.proto
- proto/grp.proto
> Update protos for user-level API keys

- enterprise/server/backends/pebble_cache/BUILD
- enterprise/server/backends/pebble_cache/pebble_cache.go
> Add option to periodically remove old AC entries.

- enterprise/server/backends/pebble_cache/BUILD
- enterprise/server/backends/pebble_cache/pebble_cache.go
> Add a rate limit for background repair mods.

- enterprise/server/auth/auth.go
- enterprise/server/saml/saml.go
- Remove unused `a` param
- Reorder `ctx, env` params to match the convention we use elsewhere
---
> Clean up `auth.ClaimsFromSubID`

- enterprise/server/auth/auth.go
- server/interfaces/interfaces.go
- server/ssl/ssl.go
> Support forwarded old-style certs

- enterprise/server/remote_execution/platform/platform.go
- enterprise/server/workflow/service/service.go
- enterprise/server/workflow/service/service_test.go
> Workflows: set env via remote_header overrides

- cli/plugin/plugin.go
- cli/terminal/terminal.go
---
**Related issues**: Fixes https://github.com/buildbuddy-io/buildbuddy-internal/issues/1972
> CLI: Write build output to stderr

- docs/cli.md
- website/src/pages/cli.tsx
> CLI: bump version in docs to 5.0.1

- release.py
> Add flag to automatically proceed release.py script without user input required

- docs/cli.md
- website/src/pages/cli.tsx
> CLI: bump version in docs to 5.0.2

- server/remote_cache/scorecard/BUILD
- server/remote_cache/scorecard/scorecard.go
- server/remote_cache/scorecard/scorecard_test.go
Concatenate Misses and Hits from scorecards for all attempts of an invocation.
---
> show all cache artifacts, including those from retries

- enterprise/server/raft/filestore/filestore.go
- enterprise/server/raft/filestore/filestore_test.go
Autosubmit robbed me and I missed your [comment](https://github.com/buildbuddy-io/buildbuddy/pull/3309/files/0786b9ec29aeb7e7f907b3313a21758a37f51cf0#r1089564811) on https://github.com/buildbuddy-io/buildbuddy/pull/3309. This change addresses it and adds a test.
> Address review feedback and add a test.

- server/remote_cache/byte_stream_server/BUILD
- server/remote_cache/byte_stream_server/byte_stream_server.go
- server/remote_cache/byte_stream_server/byte_stream_server_test.go
Co-authored w/ @sluongng 
---
**Related issues**: Fixes https://github.com/buildbuddy-io/buildbuddy-internal/issues/1187
> Short-circuit compressed writes for bazel 5.1+

- tools/dev_qa.sh
> Try to fix tensorflow google credential errors in dev qa script

- enterprise/server/backends/pebble_cache/pebble_cache.go
This changes the randomsample() function so it generates sample keys by constructing a valid PebbleKey and then serializing keyBytes at the current database version. This will allow random sampling to work correctly across database versions.
> Randomly sample by constructing a key with the specified digest

- app/docs/BUILD
- app/docs/setup.tsx
> Add error handling for GetBazelConfig

- enterprise/server/backends/pebble_cache/pebble_cache.go
Previously in some places we were often doing:
```
Rlock()
val = read()
Runlock()
```
```
Lock()
write(val)
Unlock()
```
which is not really locking. This change moves the locking up/out to calling methods so we can correctly lock around a read/modify/write.
> Move locks up to support read/modify/write locking semantics

- enterprise/server/secrets/secrets.go
I knew calling a public API method (ListSecrets) would come back to bite me when i wrote it...
> Fix secret box

- enterprise/server/backends/userdb/BUILD
- enterprise/server/backends/userdb/userdb.go
- enterprise/server/backends/userdb/userdb_test.go
- enterprise/server/test/integration/remote_execution/rbetest/rbetest.go
- enterprise/server/workflow/service/service.go
- server/buildbuddy_server/buildbuddy_server.go
- server/interfaces/interfaces.go
> Refactor GetAPIKeys

- app/invocation/invocation_suggestion_card.tsx
> Suggest --experimental_remote_build_event_upload=minimal

- app/terminal/BUILD
- app/terminal/terminal.tsx
- app/terminal/text.tsx
- rules/typescript/index.bzl
> Enable strict mode for //app/terminal

- enterprise/server/backends/pebble_cache/pebble_cache.go
- proto/raft.proto
Reverts buildbuddy-io/buildbuddy#3368
> Revert "Support min, max, and active version for clarity and better rollback support"

- enterprise/server/backends/pebble_cache/BUILD
- enterprise/server/backends/pebble_cache/pebble_cache.go
Reverts buildbuddy-io/buildbuddy#3364
> Revert "Allow reading and writing keys at multiple versions"

- enterprise/server/backends/pebble_cache/BUILD
- enterprise/server/backends/pebble_cache/pebble_cache.go
Reverts buildbuddy-io/buildbuddy#3370
> Revert "Revert "Allow reading and writing keys at multiple versions""

- enterprise/server/backends/pebble_cache/BUILD
- enterprise/server/backends/pebble_cache/pebble_cache.go
Reverts buildbuddy-io/buildbuddy#3372
> Revert "Revert "Revert "Allow reading and writing keys at multiple versions"""

- enterprise/app/usage/BUILD
- enterprise/app/usage/usage.tsx
I've done that thing where I pull this.foo out into a variable again (though we were already doing it here, this time).  Let me know if it really bothers you too much :P
> Strictify //enterprise/app/usage

- enterprise/app/api_keys/BUILD
- enterprise/app/api_keys/api_keys.tsx
> Enable strict mode for //enterprise/app/api_keys

- website/package.json
- website/src/theme/DocSidebar/index.js
- website/yarn.lock
context: https://github.com/buildbuddy-io/buildbuddy/pull/3351#discussion_r1095853234
---
> Add thin-scrollbar class to docs sidebar

- app/invocation/invocation.tsx
- app/invocation/invocation_action_card.tsx
- app/invocation/invocation_tabs.tsx
- enterprise/server/cmd/ci_runner/BUILD
- enterprise/server/cmd/ci_runner/main.go
- enterprise/server/workflow/service/service.go
This will allow users to see disk usage, peak memory, CPU etc. for the CI runner action which hosts the bazel process.
---
> Workflows: Show executions tab in the UI

- enterprise/server/backends/userdb/BUILD
- enterprise/server/backends/userdb/userdb.go
- enterprise/server/backends/userdb/userdb_test.go
- server/buildbuddy_server/buildbuddy_server.go
Move the group role checks into UserDB and add tests.
---
> Move API key Create/Update auth checks into UserDB

- enterprise/server/backends/userdb/userdb.go
- enterprise/server/backends/userdb/userdb_test.go
> Add additional validation in UpdateGroupUsers

- cli/arg/arg_test.go
- cli/sidecar/sidecar.go
- enterprise/server/cmd/ci_runner/main.go
> CLI: Disable sidecar on CI for now

- tools/cacheload/cacheload.go
> Fix write-only mode in cacheload.

- tools/dev_qa.sh
Also prevent tensorflow from running by default, because it should be unnecessary to run on every auto-deploy
> Add more builds to dev qa script

- enterprise/server/backends/userdb/userdb.go
- enterprise/server/backends/userdb/userdb_test.go
> Fix for inaccessible workflows

- deps.bzl
- enterprise/tools/check_metrics/BUILD
- enterprise/tools/check_metrics/check_metrics.go
- enterprise/tools/check_metrics/config.go
- go.mod
- go.sum
> Add script to query app liveness for canary

- enterprise/server/backends/userdb/userdb.go
- server/interfaces/interfaces.go
> Clean up some unused UserDB methods

- docs/workflows-config.md
Add doc for the config that was introduced in commit b071ad2dd3d79b6f8fbd56200e2f074b61a912e7.
---
> docs: document workflow disk space config

- tools/dev_qa.sh
> Add flaky test retries to dev qa script

- tools/dev_qa.sh
> Add flag to dev qa script to cleanup repos

- enterprise/server/backends/pebble_cache/pebble_cache.go
> Remove unused param to blobDir().

- enterprise/server/backends/pebble_cache/BUILD
- enterprise/server/backends/pebble_cache/pebble_cache.go
- enterprise/server/backends/pebble_cache/pebble_cache_test.go
> Add support for directing anon data to a different partition.

- enterprise/server/remote_execution/runner/BUILD
- enterprise/server/remote_execution/runner/runner.go
- enterprise/server/remote_execution/runner/runner_test.go
> Workflows: add resource requests to recycling key

- enterprise/app/trends/drilldown_page.tsx
- enterprise/app/trends/heatmap.tsx
- fix y axis rendering
- actually show invocation count in tooltips
> fix a couple random heatmap bugs that got messed up in refactoring

- enterprise/server/backends/authdb/BUILD
- enterprise/server/backends/authdb/authdb.go
- enterprise/server/backends/authdb/authdb_test.go
> Add unit tests for authdb

- WORKSPACE
- buildpatches/gazelle.patch
- cli/cmd/bb/BUILD
- cli/cmd/bb/bb.go
- cli/fix/BUILD
- cli/fix/fix.go
- deps.bzl
- go.mod
- go.sum
> Add `bb fix` command that calls gazelle

- docs/cli.md
- website/src/pages/cli.tsx
> CLI: bump version in docs to 5.0.3

- enterprise/server/backends/pebble_cache/BUILD
- enterprise/server/backends/pebble_cache/pebble_cache.go
Reverts buildbuddy-io/buildbuddy#3428
> Revert "Read keys across multiple versions"

- enterprise/server/backends/pebble_cache/BUILD
- enterprise/server/backends/pebble_cache/pebble_cache.go
Reverts buildbuddy-io/buildbuddy#3440
> Revert "Read keys at multiple versions"

- enterprise/app/tap/tap.css
- enterprise/app/tap/tap.tsx
> Add icons to test grid blocks for improved accessibility

- enterprise/server/backends/pebble_cache/BUILD
- enterprise/server/backends/pebble_cache/pebble_cache.go
Reverts buildbuddy-io/buildbuddy#3442
> Revert "Revert "Read keys at multiple versions""

- deps.bzl
- go.mod
- go.sum
> Bump golang.org/x/net from 0.6.0 to 0.7.0

- cli/fix/fix.go
> CLI: Fix `bb --verbose=1 fix`

- enterprise/server/backends/pebble_cache/pebble_cache.go
- server/util/approxlru/BUILD
- server/util/approxlru/approxlru.go
> Add a rate limiter for eviction.

- cli/fix/BUILD
- cli/fix/langs.go
> CLI: Add support for gazelle to manage visibility

- enterprise/server/remote_execution/containers/firecracker/firecracker.go
- enterprise/server/remote_execution/snaploader/snaploader.go
Make an interface; implement it. This will let me swap out snaploader with a different implementation.
> Better interface for snaploader

- enterprise/server/backends/pebble_cache/pebble_cache_test.go
Tests the bug described in https://github.com/buildbuddy-io/buildbuddy/pull/3468
---
> Add pebble cache tests for duplicate writes.

- app/invocation/BUILD
- app/invocation/invocation.css
- app/invocation/invocation_execution_card.tsx
This prevents this page from OOM crashing for large renders.
---
> Add some basic client pagination to executions table

- server/janitor/janitor.go
> Make cleanup batch size configurable

- cli/cmd/sidecar/sidecar.go
Allow user to proxy BES backend to multiple servers by using a
comma-separated list for `-bes_backend` flag.
---
> cli: support multiple BES backend

- app/invocation/BUILD
- app/invocation/child_invocations.tsx
> Fix workflow inner invocation duration rendering as 0s

- buildbuddy.yaml
- enterprise/server/remote_execution/commandutil/BUILD
- enterprise/server/remote_execution/commandutil/commandutil_test.go
- enterprise/server/remote_execution/runner/runner_test.go
> Add remote execution tests to Mac workflow

- tools/metrics/grafana/dashboards/buildbuddy.json
including
- queries per seconds
- query duration
- error rate
- errors per second
> Add grafana for ClickHouse SQL metrics

- server/util/bazel/defs.bzl
When running this rule under workflows locally, Bazel sometimes complains that the USER env var is not defined. And then when setting USER=nobody, it complains that it can't create some dir like `/nobody/.cache`. Fix by setting `--output_user_root` explicitly so Bazel doesn't try to create it in `~/.cache`.
---
> Fix extract_bazel_installation rule

- enterprise/tools/check_metrics/check_metrics.go
> Handle NAN values in check metrics script

- enterprise/server/backends/userdb/userdb.go
- enterprise/server/backends/userdb/userdb_test.go
- server/interfaces/interfaces.go
---
**Related issues**: Fixes https://github.com/buildbuddy-io/buildbuddy-internal/issues/2097
> Fix some group-level funcs returning user-level keys

- enterprise/app/api_keys/api_keys.tsx
- enterprise/server/test/webdriver/invocation/BUILD
- enterprise/server/test/webdriver/invocation/invocation_test.go
- enterprise/server/testutil/buildbuddy_enterprise/buildbuddy_enterprise.go
- server/testutil/webtester/webtester.go
> Add a webdriver test for user-owned API keys

- enterprise/server/scheduling/scheduler_server/BUILD
- enterprise/server/scheduling/scheduler_server/scheduler_server.go
- server/metrics/metrics.go
This will allow us to keep track of what versions are out in the wild.
---
> Add metric for executor registrations.

- server/metrics/metrics.go
> Fix executor registration metric registration.

- enterprise/app/settings/settings.tsx
> Tweak personal API keys settings description

- app/router/router.tsx
- enterprise/app/filter/filter.tsx
- enterprise/app/filter/filter_util.tsx
- enterprise/app/history/history.tsx
- enterprise/app/trends/drilldown_page.tsx
- enterprise/app/trends/trends.tsx
- proto/config.proto
- server/static/static.go
> Allow filtering by exact-match of the build target pattern.

- enterprise/server/scheduling/scheduler_server/scheduler_server.go
- enterprise/server/scheduling/scheduler_server/scheduler_server_test.go
- enterprise/server/workflow/config/config.go
- enterprise/server/workflow/service/service.go
> Support self-hosted workflows

- cli/picker/picker.go
Only query for local executable targets vs global ones.
Also ignore any errors/failures when running such query.
---
> cli/picker: narrow query scope

- app/util/proto.ts
- enterprise/app/trends/BUILD
- enterprise/app/trends/drilldown_page.tsx
- enterprise/app/trends/heatmap.tsx
- enterprise/app/trends/trends.css
This needs a better UI (should probably be floating right next to the selection) but this is at least a good starting point for  having this very-necessary feature available.
> Add an affordance to zoom in on the selected section of the heatmap

- enterprise/server/remote_execution/runner/runner.go
- server/testutil/testenv/testenv.go
This has been enabled in prod for a while now.
---
> Switch on executor context-based shutdown by default

- enterprise/server/remote_execution/containers/firecracker/firecracker.go
This helps avoid spurious errors being printed to the console. This can happen if we encounter an error during setup before the network setup step (we still call `remove()` in this case)
---
> Firecracker: Don't clean up networking in `remove()` if it hasn't been setup

- enterprise/app/tap/tap.tsx
The "Load more targets" button was applying to the pre-filtered list of targets, so there were cases in which clicking the "Load more targets" button would seemingly do nothing. Now, we only show the button if the filtered target list's length exceeds the target limit.
---
> Test grid: fix 'Load more targets' button visibility

- buildbuddy.yaml
It times out a lot - will try to debug this when I have more time.
Also strip newlines in the YAML so that the bazel command renders nicely in the UI.
---
> Disable ci_runner_test in Mac workflows for now

- server/remote_cache/cachetools/cachetools.go
- tools/vmstart/BUILD
- tools/vmstart/vmstart.go
> Move cachetools.GetActionAndCommand to vmstart

- cli/remotebazel/remotebazel.go
- enterprise/server/cmd/smash/smash.go
- enterprise/server/image_converter/image_converter.go
- enterprise/server/remote_execution/dirtools/dirtools.go
- enterprise/server/remote_execution/dirtools/dirtools_test.go
- enterprise/server/remote_execution/workspace/workspace.go
- enterprise/server/test/integration/ci_runner/BUILD
- enterprise/server/test/integration/ci_runner/ci_runner_test.go
- enterprise/server/test/integration/remote_execution/rbeclient/rbeclient.go
- server/remote_asset/fetch_server/fetch_server.go
- server/remote_cache/byte_stream_server/byte_stream_server.go
- server/remote_cache/cachetools/cachetools.go
- server/remote_cache/content_addressable_storage_server/content_addressable_storage_server_test.go
- server/remote_cache/digest/digest.go
- tools/rbeperf/rbeperf.go
Associated internal refactoring: https://github.com/buildbuddy-io/buildbuddy-internal/pull/2118
> Plumb in digest_function (part 1)

- tools/edit_instance_template/edit_instance_template.go
> Fix pool name match in edit_instance_template script

- terraform/aws/README.md
This should be usable now.
---
> tf/aws: remove do not use message

- app/invocation/BUILD
- app/invocation/invocation_execution_card.tsx
- app/invocation/invocation_execution_table.tsx
- app/invocation/invocation_execution_util.tsx
> Split out invocation-execution-table into its own component to share with trends.

- enterprise/server/cmd/executor/BUILD
> Fix executor image visibility

- app/invocation/BUILD
- app/invocation/cache_requests_card.tsx
> fix a dangling missing dep in non-strict typescript land

- server/tables/tables.go
> Make Targets and Usages tables group replication compliant.

- enterprise/server/cmd/server/BUILD
- enterprise/server/cmd/server/main.go
- enterprise/server/suggestion/BUILD
- enterprise/server/suggestion/suggestion.go
- proto/BUILD
- proto/buildbuddy_service.proto
- proto/config.proto
- proto/suggestion.proto
- server/buildbuddy_server/BUILD
- server/buildbuddy_server/buildbuddy_server.go
- server/environment/environment.go
- server/interfaces/BUILD
- server/interfaces/interfaces.go
- server/real_environment/real_environment.go
- server/role_filter/role_filter.go
- server/static/static.go
Only enabled if an OpenAI api key is provided in your config.yaml
---
> Add backend implementation for bot suggestions

- enterprise/app/trends/drilldown_page.tsx
The data doesn't exist in execution tables and doesn't particularly make sense as a filter anyway.
---
> Don't set invocaton duration filters on executions.

- app/invocation/BUILD
- app/invocation/invocation.css
- app/invocation/invocation.tsx
- app/invocation/invocation_bot_card.tsx
- app/invocation/invocation_buttons.tsx
- app/invocation/invocation_model.tsx
- app/root/root.css
> Frontend changes for bot suggestions

- app/root/root.css
> Only make bot suggestion cards have blue backgrounds

- enterprise/app/trends/drilldown_page.tsx
- enterprise/app/trends/heatmap.tsx
- enterprise/app/trends/trends.css
> Move zoom button directly next to selection in the heatmap SVG.

- BUILD
This breaks the internal build.
---
> Disable gazelle visibility plugin

- enterprise/server/remote_execution/dirtools/dirtools.go
I noticed this during refactoring and want to reduce the number of upload codepaths we have. Instead of calling cachetools.UploadProto we use the uploader (pulled out from a function we already call) and use uploader.UploadProto instead.
> Use BatchCASUploader for all uploads in UploadTree

- enterprise/server/backends/s3_cache/s3_cache.go
Some customers would prefer to re-use an existing S3 bucket to setup
BuildBuddy remote cache backend. In such cases, they would want to have
the config option to store all BuildBuddy remote cache under a specific
directory (path prefix).
---
Closes #3595
> s3_cache: add bucket path prefix

- WORKSPACE
- docs/rbe-github-actions.md
- docs/rbe-setup.md
Also added a small note into WORKSPACE to remind folks to update the
docs.
---
> docs: update buildbuddy toolchain to latest version

- server/build_event_protocol/target_tracker/target_tracker.go
https://github.com/buildbuddy-io/buildbuddy-internal/issues/2098
> Stop writing to MySQL TargetStatus and Targets

- tools/check_release_assets_uploaded.py
> Add script to poll whether all release assets have been uploaded

- website/package.json
- website/src/theme/DocSidebar/index.js
- website/yarn.lock
> Only style docs scrollbar for non-macs

- website/blog/donating-rules_xcodeproj-to-the-mobile-native-foundation.md
> Fix a consistency issue in a blog post

- server/remote_cache/cachetools/cachetools.go
Verify the hash of blobs downloaded with cachetools.GetBlobChunk.
> Verify downloaded file hash

- enterprise/app/trends/heatmap.tsx
- enterprise/app/trends/trends.css
- Make the background color darker
- Make the cursor a pointer
---
> make the selectable area of the heatmap a little more obvious.

- enterprise/app/trends/drilldown_page.tsx
- enterprise/app/trends/heatmap.tsx
- enterprise/app/trends/trends.css
> interpolate color for selected heatmap cells.

- server/tables/tables.go
Might still need to tweak uniqueness constraints etc. (e.g. can a repo be assigned to multiple groups?) But I think this is a good starting point.
---
> Add tables for GitHub app

- server/backends/invocationdb/BUILD
- server/backends/invocationdb/invocationdb.go
- server/backends/invocationdb/invocationdb_test.go
---
**Related issues**: Fixes https://github.com/buildbuddy-io/buildbuddy-internal/issues/2170
> Delete InvocationExecutions in DeleteInvocation

- enterprise/server/cmd/server/BUILD
- enterprise/server/cmd/server/main.go
- enterprise/server/githubapp/BUILD
- enterprise/server/githubapp/githubapp.go
- proto/config.proto
- server/backends/github/github.go
- server/environment/environment.go
- server/interfaces/interfaces.go
- server/libmain/libmain.go
- server/real_environment/real_environment.go
- server/static/static.go
> Add server-side OAuth flow for GitHub app

- tools/gorm/print_schema_changes.sh
> Stop throwing out bazel logs in print schema changes script. This will make it easier to debug workflow failures

- docs/cli.md
- website/src/pages/cli.tsx
> CLI: bump version in docs to v5.0.4

- .bazelrc
- buildbuddy.yaml
> Set flaky_test_attempts for Mac workflow

- docs/cli.md
- website/src/pages/cli.tsx
> Update CLI version in docs to v5.0.5

- app/invocation/invocation_suggestion_card.tsx
> Add suggestion for --nolegacy_important_outputs

- server/util/gormutil/gormutil.go
> Ignore create table operations when printing schema changes

- server/http/interceptors/interceptors.go
> Clarify `ssl.upgrade_insecure` documentation

- server/http/interceptors/BUILD
- server/http/interceptors/interceptors.go
- server/http/interceptors/interceptors_test.go
- server/libmain/libmain.go
This cherry-pick the refactoring commits from #3655 but discarded the functionality change.
Added unit test and removed unused parameter, expecting this to be a no-ops PR.
---
> Refactor and test RedirectIfNotForwardedHTTPS

- server/http/interceptors/BUILD
- server/http/interceptors/interceptors_test.go
Follow up from https://github.com/buildbuddy-io/buildbuddy/pull/3669#pullrequestreview-1361544715
---
> http/interceptors_test: switch to use flag.Set

- server/backends/blobstore/BUILD
- server/backends/blobstore/blobstore.go
- server/backends/blobstore/gcs/BUILD
- server/backends/blobstore/gcs/gcs.go
I missed this in the last PR
---
> Rename gcp -> gcs

- server/tables/tables.go
https://github.com/buildbuddy-io/buildbuddy-internal/issues/2172
> add a created_at_usec index on Executions

- proto/github.proto
> Add protos for GH app installations and git repositories APIs

- tools/replay_invocation/BUILD
- tools/replay_invocation/replay_invocation.go
This tool has broken a few times due to refactorings in OSS.
---
> Move replay_invocation tool to OSS

- tools/dev_qa.py
> Fix default repo names in dev_qa.py

- enterprise/app/trends/drilldown_page.tsx
- enterprise/app/trends/trends.css
> show a little summary of the selection in the dimensions section on the drilldowns page

- enterprise/server/remote_execution/containers/podman/podman.go
Per discussion today, there seem to still be some synchronization bugs with using additional layer stores in podman. Adding the pull before streaming images should address these as it allows us to set a timeout and allows podman to populate the layer metadata exactly once per machine-image.
> Re-add the podman pull when streaming images

- app/invocation/invocation_action_card.tsx
This allows us to render action result timelines for local actions!
---
> Render partial action result timelines (local runs only have worker and execution timestamps)

- enterprise/server/crypter_service/BUILD
- enterprise/server/crypter_service/crypter_service.go
- enterprise/server/crypter_service/crypter_service_test.go
- server/tables/tables.go
The encryption method is described in this document: https://docs.google.com/document/d/1rpvqs6FX_ibVO11IuOsfDiiZy3C5uv-DCu4RZqi4XYQ/edit
---
> Add crypter service that supports basic {enc,dec}ryption.

- enterprise/server/crypter_service/BUILD
- enterprise/server/crypter_service/crypter_service.go
> Switch encryption to XChaCha20-Poly1305.

- release.py
> Fix warning message in release.py

- enterprise/server/crypter_service/BUILD
- enterprise/server/crypter_service/crypter_service.go
- enterprise/server/crypter_service/crypter_service_test.go
- server/interfaces/interfaces.go
> Incorporate resource digest into authenticity check.

- enterprise/server/remote_execution/containers/podman/podman.go
> Give soci-store a second to start up before invoking it via filesystem

- tsconfig.json
> TypeScript: remove baseUrl to force relative imports

- server/tables/tables.go
> Set default for cache encryption column to false instead of null.

- enterprise/server/backends/pebble_cache/pebble_cache.go
Iterators are not guaranteed to get a consistent view of the underlying database. They may see keys that have already been deleted, e.g. by eviction. Without checking for existence, the migration goroutine would resurrect keys that have already been deleted.
---
> Skip keys that no longer exist during migration.

- server/tables/tables.go
> Change column type to tinyint to make gorm happy.

- .bazelrc
> Add bazelrc config for auto-release

- enterprise/server/cmd/ci_runner/main.go
This should result in the workflow task being retried in cases where bazel crashes unexpectedly (and should also make sure that the runner does not get recycled).
Note, we only do this for workflows (for now), not hosted bazel.
---
**Related issues**: https://github.com/buildbuddy-io/buildbuddy-internal/issues/2203
> Crash the CI runner when bazel crashes

- proto/soci.proto
1. Add image_id to GetArtifactsResponse so the client doesn't have to resolve the image as well (soci snapshotter operates on the image id) and
2. Make artifacts plural (is that how we do it?)
> Some small changes to soci.proto

- app/target/BUILD
- app/target/target_test_cases_card.tsx
- app/target/target_test_document_card.tsx
- tsconfig.json
> Render test logs in terminals with ANSI color support

- server/bytestream/bytestream.go
> Don't include full URL in bytestream error

- enterprise/server/githubapp/githubapp.go
- enterprise/server/workflow/service/service.go
Also add FOR UPDATE to a few related transactions that do SELECT followed by DELETE.
---
> Fix SELECT FOR UPDATE syntax in installation unlink query

- app/target/target_test_cases_card.tsx
> Don't render test.xml TerminalComponent for empty logs

- enterprise/app/tap/tap.tsx
---
**Related issues**: Fixes https://github.com/buildbuddy-io/buildbuddy-internal/issues/2223
> Test grid: show zero state when no repos are available

- app/format/BUILD
- app/format/format.tsx
- app/format/format_test.ts
> strictify //app/format

- enterprise/server/remote_execution/containers/firecracker/firecracker.go
The original reason I introduced these numbered workspace images was to fix the error "failed to remount workspace after update: structure needs cleaning". But this seems to be caused by overwriting the existing workspace disk, rather than deleting it and creating a new one.
> Firecracker: remove numbered workspace images

- enterprise/server/remote_execution/containers/firecracker/README.md
I find it hard to keep track of all the different files related to firecracker VMs so I made this diagram, partly as a reference, and partly so that I can update this diagram during a few upcoming PRs as a quick way for reviewers to see the effects of the PR on the filesystem layout.
> Add filesystem layout docs for firecracker

- server/backends/blobstore/aws/BUILD
- server/backends/blobstore/aws/aws.go
- server/backends/blobstore/azure/BUILD
- server/backends/blobstore/azure/azure.go
- server/backends/blobstore/disk/BUILD
- server/backends/blobstore/disk/disk.go
- server/backends/blobstore/gcs/BUILD
- server/backends/blobstore/gcs/gcs.go
- server/backends/blobstore/util/BUILD
- server/backends/blobstore/util/util.go
- server/interfaces/interfaces.go
- server/testutil/mockstore/BUILD
- server/testutil/mockstore/mockstore.go
Add interface to blobstore to get an `io.Writer` so we can stream to blobstore.
---
> Add Writer interface to blobstore

- app/menu/BUILD
- app/menu/menu.tsx
- enterprise/app/BUILD.bazel
> strict mode for app/menu, enterprise/app

- enterprise/server/util/ext4/ext4.go
Overwriting an existing image (rather than unlinking the existing image then writing a new one) causes corruption, so this PR adds a safeguard to make sure we never do it.
I did this accidentally a few times in other PRs, and it was hard to debug.
> Firecracker: add a safeguard in ext4.DirectoryToImage to prevent corruption

- enterprise/app/code/BUILD
- enterprise/app/code/code.tsx
- enterprise/app/code/code_build_button.tsx
- enterprise/app/code/code_empty.tsx
- enterprise/app/code/code_pull_request.ts
- enterprise/app/code/code_sidebar_node.tsx
> Strictify //enterprise/app/code

- enterprise/app/quota/BUILD
- enterprise/app/quota/bucket.tsx
- enterprise/app/quota/bucket_form.tsx
- enterprise/app/quota/namespace.tsx
> Strictify enterprise/app/quota

- app/flame_chart/BUILD
- app/flame_chart/flame_chart.tsx
- app/flame_chart/profile_model.ts
> Strictify flame chart

- enterprise/server/invocation_stat_service/BUILD
- enterprise/server/invocation_stat_service/invocation_stat_service.go
If the data is partially available for the requested period, summary
will not be exported.
> Get invocation summary from clickhouse

- enterprise/server/registry/registry.go
- enterprise/server/remote_execution/containers/podman/BUILD
- enterprise/server/remote_execution/containers/podman/podman.go
- proto/registry.proto
- server/environment/BUILD
- server/environment/environment.go
- server/libmain/BUILD
- server/libmain/libmain.go
- server/real_environment/BUILD
- server/real_environment/real_environment.go
> Remove unused optimized image API.

- enterprise/server/raft/filestore/filestore.go
- enterprise/server/raft/filestore/filestore_test.go
In order to perform sampling of AC keys, which have a group ID prefix, we must be able to first sample across group IDs. This requires the group IDs to be uniformly distributed. This is not the case with "raw" group IDs because they have variable widths.
> Pad the group ID in the v2 key format.

- app/invocation/workflow_rerun_button.tsx
- enterprise/server/workflow/service/service.go
- proto/workflow.proto
> Add option to execute multiple actions in a workflow

- server/build_event_protocol/accumulator/accumulator.go
- server/build_event_protocol/build_event_handler/BUILD
- server/build_event_protocol/build_event_handler/build_event_handler.go
Store timing profile in blobstore so we can persist it after it is no longer in the cache.
---
> Store timing profile in blobstore

- server/tables/tables.go
- server/util/clickhouse/schema/schema.go
**Related issues**: https://github.com/buildbuddy-io/buildbuddy-internal/issues/2236
> Add RemoteCacheOption to Invocation MySQL and ClickHouse

- enterprise/app/workflows/github_app_import.tsx
This shows up as an error in my IDE but doesn't fail the bazel typecheck test for some reason :thinking: 
> Fix incorrect request type

- enterprise/server/api/api_server.go
- enterprise/server/backends/authdb/authdb.go
- enterprise/server/backends/userdb/userdb.go
- enterprise/server/execution_search_service/execution_search_service.go
- enterprise/server/execution_service/execution_service.go
- enterprise/server/githubapp/githubapp.go
- enterprise/server/hostedrunner/hostedrunner.go
- enterprise/server/invocation_search_service/invocation_search_service.go
- enterprise/server/invocation_stat_service/invocation_stat_service.go
- enterprise/server/quota/quota_manager.go
- enterprise/server/quota/quota_manager_test.go
- enterprise/server/remote_execution/execution_server/execution_server.go
- enterprise/server/secrets/secrets.go
- enterprise/server/test/integration/invocation_webhook/invocation_webhook_test.go
- enterprise/server/usage/usage.go
- enterprise/server/usage/usage_test.go
- enterprise/server/usage_service/usage_service.go
- enterprise/server/workflow/service/service.go
- server/backends/github/github.go
- server/backends/invocationdb/invocationdb.go
- server/backends/invocationdb/invocationdb_test.go
- server/build_event_protocol/build_status_reporter/build_status_reporter.go
- server/build_event_protocol/target_tracker/target_tracker.go
- server/build_event_protocol/target_tracker/target_tracker_test.go
- server/build_event_protocol/webhooks/webhooks.go
- server/tables/tables.go
- server/target/target.go
- server/util/db/db.go
- server/util/db/db_test.go
- server/util/query_builder/query_builder_test.go
Reverts buildbuddy-io/buildbuddy#3821
Broke docker tests, investigating and fixing then resubmitting.
> Revert "Use ANSI quotes for queries and quote table names"

- enterprise/server/remote_execution/filecache/BUILD
- enterprise/server/remote_execution/filecache/filecache.go
- enterprise/server/remote_execution/filecache/filecache_test.go
**Related issues**: Fixes https://github.com/buildbuddy-io/buildbuddy-internal/issues/2188
> Fix bug that filecache overwrite deletes existing file

- enterprise/server/crypter_service/crypter_service.go
- enterprise/server/execution_search_service/execution_search_service.go
- server/tables/tables.go
Also a fix a couple of other queries that I noticed have not been updated.
> Update recently added encryption queries to new standard.

- enterprise/server/backends/pebble_cache/pebble_cache.go
- enterprise/server/raft/cache/cache.go
- enterprise/server/raft/filestore/filestore.go
- enterprise/server/raft/filestore/filestore_test.go
- enterprise/server/raft/replica/replica.go
- enterprise/server/raft/replica/replica_test.go
- enterprise/server/raft/store/store.go
- enterprise/server/raft/store/store_test.go
> Delete some dead code from filestore.

- enterprise/server/remote_execution/filecache/BUILD
- enterprise/server/remote_execution/filecache/filecache.go
- enterprise/server/remote_execution/filecache/filecache_test.go
- server/backends/disk_cache/disk_cache.go
- server/util/lru/lru.go
- server/util/lru/lru_test.go
> Fix bug that manual LRU deletion updates eviction metrics

- enterprise/server/backends/pebble_cache/pebble_cache.go
> Consolidate some duplicate code in pebble reader path.

- docs/enterprise-api.md
Fixes buildbuddy-io/buildbuddy-internal#2080
**Related issues**: #3774
> Add API documentation for ExecuteWorkflow

- tools/cas/cas.go
> Fix ActionResult fetching in CAS tool

- app/invocation/invocation_model.tsx
- app/invocation/invocation_timing_card.tsx
- app/service/rpc_service.ts
- server/buildbuddy_server/buildbuddy_server.go
- server/bytestream/bytestream.go
Add the `with_fallback` param to the `file/download` endpoint so we can gracefully fall back
to an alternative location for an artifact (timing profile, test logs) if it isn't found in
the first location. Also change logging around a bit so that fallbacks don't result in
noisy logs.
---
> Add fallback for `file/download` requests

- enterprise/app/trends/summary_card.tsx
- enterprise/app/trends/trends.css
> Do some cheap math just to say something about wall time.

- enterprise/server/invocation_stat_service/invocation_stat_service.go
- proto/stats.proto
> add total_cpu_time_saved to invocation trend response

- docs/cli.md
- website/src/pages/cli.tsx
> CLI: bump version in docs to v5.0.6

- enterprise/server/cmd/server/yaml_doc/BUILD
- enterprise/server/remote_execution/runner/testworker/BUILD
- enterprise/server/test/integration/remote_execution/proto/BUILD
- enterprise/server/webhooks/bitbucket/test_data/BUILD
- enterprise/server/webhooks/github/test_data/BUILD
- enterprise/server/workflow/config/test_data/BUILD
> fix default visibility

- enterprise/server/remote_execution/containers/firecracker/README.md
- enterprise/server/remote_execution/containers/firecracker/firecracker_test.go
- tools/firecracker_clean_networking.sh
> Add more firecracker testing notes/troubleshooting tools

- enterprise/server/hostedrunner/hostedrunner.go
> Use gRPC headers for some remote bazel env vars

- enterprise/app/trends/trends.tsx
> CPU time chart

- app/invocation/workflow_rerun_button.tsx
> Cleanup FE reference to deprecated actionName field in ExecuteWorkflowRequest

- app/capabilities/BUILD
- app/capabilities/capabilities.tsx
- app/compare/BUILD
- app/compare/compare_invocations.tsx
- app/compare/diff_preprocessing.tsx
> strict ts in app/{capabilities,compare}

- server/build_event_protocol/build_event_handler/build_event_handler.go
Fixes buildbuddy-io/buildbuddy-internal#2265
> Don't try to persist non-cache artifacts

- app/docs/BUILD
- app/docs/setup.tsx
- app/docs/setup_code.tsx
> strictify //app/docs

- cli/remotebazel/remotebazel.go
Made target branch required in this [PR](https://github.com/buildbuddy-io/buildbuddy/pull/3825)
> Set required target branch in remote bazel

- server/testutil/webtester/webtester.go
> Wait for the sidebar to appear after logging in to account for possible delay during webdriver tests

- app/flame_chart/BUILD
- app/format/BUILD
- app/terminal/BUILD
- app/util/async_test.ts
- rules/typescript/index.bzl
> Remove option to disable strict mode on ts_jasmine_node_test.

- enterprise/server/backends/distributed/distributed.go
> Flip enable_local_compression_lookup to true.

- enterprise/server/remote_execution/dirtools/dirtools.go
- enterprise/server/test/integration/remote_execution/BUILD
- server/remote_cache/cachetools/cachetools.go
Compression is enabled by default in the apps so it's best to exchange compressed data with the apps.
---
> Enable executor compression by default.

- enterprise/server/invocation_stat_service/config/config.go
- enterprise/server/invocation_stat_service/invocation_stat_service.go
- server/build_event_protocol/build_event_handler/build_event_handler.go
- server/static/static.go
Other than allowing the `pattern` filter, these are all implicitly or explicitly tied to the OLAP db handle existing.
> Flip a bunch of flags that have been on in dev and prod for a long time.

- enterprise/server/invocation_stat_service/invocation_stat_service.go
> filter out negative duration_usec when querying clickhouse.

- enterprise/server/workflow/service/service.go
> Cleanup BE reference to deprecated actionName field in ExecuteWorkflowRequest

- enterprise/server/backends/pebble_cache/pebble_cache.go
- enterprise/server/backends/pebble_cache/pebble_cache_test.go
- enterprise/server/crypter_service/crypter_service_test.go
The previous PR didn't fully do the job, woops.
> Actually remove dedicated partition check.

- enterprise/app/tap/BUILD
- enterprise/app/tap/tap.tsx
> Strictify //enterprise/app/tap

- enterprise/server/crypter_service/crypter_service.go
Doesn't really matter, but apparently this is more conventional.
> Use a zero-based chunk index.

- enterprise/server/crypter_service/crypter_service.go
> Pass version and group ID to HKDF-Expand.

- app/router/BUILD
- app/router/router.tsx
> strictify //app/router

- enterprise/app/encryption/encryption.tsx
> Fix AWS ARN input class name.

- enterprise/app/encryption/encryption.css
- enterprise/app/encryption/encryption.tsx
- enterprise/app/settings/settings.css
- enterprise/app/settings/settings.tsx
> Tweak CMEK styling & wording

- app/compare/compare_invocations.tsx
- app/components/link/link.tsx
- app/docs/setup_code.tsx
- app/invocation/child_invocation_card.tsx
- app/invocation/scorecard_card.tsx
- enterprise/app/executors/executors.tsx
- enterprise/app/history/history.tsx
- enterprise/app/trends/drilldown_page.tsx
- enterprise/app/workflows/github_app_import.tsx
- enterprise/app/workflows/github_import.tsx
> Don't `preventDefault()` on a `<Link>` if the meta key is pressed

- enterprise/server/remote_execution/containers/podman/podman.go
- enterprise/server/remote_execution/runner/runner.go
> Restart soci-store if it dies

- enterprise/app/history/history_invocation_card.tsx
> Fix invocation clicks

- enterprise/server/crypter_service/crypter_service.go
> Explicitly clear derived key from memory before eviction.

- enterprise/server/test/integration/workflow/workflow_test.go
- enterprise/server/workflow/service/service.go
- proto/workflow.proto
> Cleanup BE sending deprecated field in ExecuteWorkflowResponse

- enterprise/server/backends/pebble_cache/pebble_cache_test.go
- enterprise/server/crypter_service/BUILD
- enterprise/server/crypter_service/crypter_service_test.go
- server/tables/tables.go
> Unconditionally enable encryption schema.

- enterprise/server/crypter_service/BUILD
- enterprise/server/crypter_service/crypter_service.go
- server/metrics/metrics.go
> Instrument the crypter service with some metrics.

- enterprise/server/backends/openai/BUILD
- enterprise/server/backends/openai/openai.go
- enterprise/server/suggestion/BUILD
- enterprise/server/suggestion/suggestion.go
> Pull OpenAI-specific code into its own backend

- tools/metrics/grafana/dashboards/buildbuddy.json
> Add encryption Grafana dashboard.

- enterprise/server/backends/openai/BUILD
- enterprise/server/backends/openai/openai.go
- enterprise/server/backends/vertexai/BUILD
- enterprise/server/backends/vertexai/vertexai.go
- enterprise/server/suggestion/BUILD
- enterprise/server/suggestion/suggestion.go
- proto/suggestion.proto
> Add Google's VertexAI as a suggestion backend

- enterprise/BUILD
- enterprise/app/BUILD.bazel
- enterprise/server/cmd/executor/BUILD
- enterprise/server/crypter_service/BUILD
- enterprise/server/githubapp/BUILD
- enterprise/tools/rbeperf/BUILD
- enterprise/tools/vmstart/BUILD
> Remove visibility overrides for enterprise/... packages

- enterprise/BUILD
- enterprise/app/BUILD.bazel
- enterprise/server/cmd/executor/BUILD
- enterprise/tools/rbeperf/BUILD
> Revert some of the visibility overrides needed for the internal build

- enterprise/app/history/BUILD
- enterprise/app/history/history.tsx
- enterprise/app/history/history_invocation_card.tsx
- enterprise/app/history/history_invocation_stat_card.tsx
> strictify //enterprise/app/history

- app/invocation/BUILD
- app/invocation/invocation_buttons.tsx
- app/invocation/invocation_model.tsx
- app/invocation/suggestion_button.tsx
- proto/config.proto
- server/interfaces/interfaces.go
- server/static/static.go
Depends on https://github.com/buildbuddy-io/buildbuddy/pull/3954
> Add UI support for multiple "Ask Buddy" backends

- website/src/components/apply/apply.tsx
- website/src/pages/jobs/senior-site-reliability-engineer.md
- website/src/pages/jobs/senior-software-engineer.md
- website/src/pages/jobs/software-engineer.md
- website/src/pages/jobs/solutions-engineer.md
Also update the job listings to mention that folks might have to work with the rest of us too and refer to offsites.
> Let people say a little bit in the job application form if they want

- buildpatches/buildifier.patch
- cli/fix/BUILD
- cli/fix/fix.go
- deps.bzl
- go.mod
> Run buildifier on all BUILD/WORKSPACE files as part of `bb fix`

- cli/bazelisk/bazelisk.go
- cli/plugin/plugin.go
**Related issues**: https://github.com/buildbuddy-io/buildbuddy-internal/issues/2294
> Don't fail when running `bb version` outside of a workspace

- cli/bazelisk/bazelisk.go
**Related issues**: https://github.com/buildbuddy-io/buildbuddy-internal/issues/2294
> If using bb cli directly AND have a .bazelversion header, report the correct bazel version

- cli/arg/arg_test.go
- cli/cmd/bb/BUILD
- cli/cmd/bb/bb.go
- cli/parser/parser.go
- cli/parser/parser_test.go
- cli/shortcuts/BUILD
- cli/shortcuts/shortcuts.go
> Add some "shortcuts" for cli commands `b`=>`build`, `t`=>`test`, etc

- enterprise/server/cmd/ci_runner/main.go
- server/build_event_protocol/accumulator/accumulator.go
- server/build_event_protocol/target_tracker/target_tracker.go
- server/build_event_protocol/target_tracker/target_tracker_test.go
> Introduce `DISABLE_TARGET_TRACKING` metadata and set it for workflow PRs

- server/util/clickhouse/clickhouse.go
- server/util/clickhouse/schema/schema.go
> add tags to executions table in clickhouse (Just The Schema)

- enterprise/app/trends/drilldown_page.tsx
- enterprise/server/execution_search_service/BUILD
- enterprise/server/execution_search_service/execution_search_service.go
- enterprise/server/invocation_stat_service/invocation_stat_service.go
- proto/execution_stats.proto
- proto/stored_invocation.proto
- server/build_event_protocol/build_event_handler/build_event_handler.go
- server/util/clickhouse/BUILD
- server/util/clickhouse/clickhouse.go
> populate and use tags on executions.

- enterprise/app/encryption/BUILD
- enterprise/app/encryption/encryption.css
- enterprise/app/encryption/encryption.tsx
> Use a horizontal picker for KMS type.

- enterprise/server/backends/pebble_cache/pebble_cache.go
- server/metrics/metrics.go
> Expose pebble compaction/level metrics via prometheus.

- app/invocation/invocation_details_card.tsx
- app/invocation/invocation_model.tsx
- app/invocation/invocation_overview.tsx
> Render tool tag in the ui

- tools/cas/cas.go
Add Tree type to help message as it's also supported.
> tools/cas: add Tree to help msg

- app/invocation/invocation_model.tsx
> Don't assume optionsParsed is set when reading toolTag

- enterprise/server/workflow/service/BUILD
- enterprise/server/workflow/service/service.go
> Retry workflow actions on transient error

- enterprise/server/backends/pebble_cache/pebble_cache.go
- enterprise/server/raft/replica/replica.go
- enterprise/server/util/pebbleutil/BUILD
- enterprise/server/util/pebbleutil/pebbleutil.go
- enterprise/server/util/pebbleutil/pebbleutil_test.go
- server/metrics/metrics.go
The change is a little more intrusive than I would have liked, but I think it's worth the additional insight we'll have into Pebble.
> Instrument pebble operations with metrics.

- tools/metrics/grafana/dashboards/buildbuddy.json
> Add graphs for pebble op rate and latency.

- enterprise/server/invocation_stat_service/invocation_stat_service.go
Don't really want to flag guard this, but leaving one behind just in case.
> show tags bar chart in drilldowns ui

- server/metrics/metrics.go
- server/util/healthcheck/BUILD
- server/util/healthcheck/healthcheck.go
> Add prometheus metric for health check status

- server/build_event_protocol/build_event_handler/build_event_handler.go
> copy uncached action exec time out to cachestats--ooooops

- server/metrics/metrics.go
> Fix pebble table metric names.

- tools/metrics/grafana/dashboards/buildbuddy.json
> Add grafana graph for healthcheck metrics

- website/blog/clickhouse-build-trends.md
> truncate clickhouse post

- cli/add/BUILD
- cli/add/add.go
- cli/cmd/bb/BUILD
- cli/cmd/bb/bb.go
- cli/help/help.go
- cli/workspace/workspace.go
> CLI: introduce `bb add` command for adding dependencies

- tools/metrics/grafana/dashboards/buildbuddy.json
Reverts buildbuddy-io/buildbuddy#4027
This change accidentally reverted https://github.com/buildbuddy-io/buildbuddy/pull/4015/files
> Revert "Add grafana graph for healthcheck metrics"

- tools/metrics/grafana/dashboards/buildbuddy.json
> Add grafana graph for healthcheck metrics - Take 2

- app/invocation/BUILD
- app/invocation/invocation.tsx
- app/invocation/invocation_suggestion_card.tsx
- app/invocation/workflow_rerun_button.tsx
- app/target/target.tsx
> strictify a few things in app/invocation

- .github/workflows/checkstyle.yaml
- WORKSPACE
Also yanked the setup from #3831 into this.
> go: upgrade to 1.20.4

- app/flame_chart/BUILD
- app/flame_chart/flame_chart.tsx
- app/flame_chart/flame_chart_model.ts
- app/flame_chart/profile_model.ts
- app/flame_chart/style_constants.ts
- app/util/color.ts
- proto/config.proto
- server/static/static.go
Including
- Action Count
- CPU Usage (Bazel)
- CPU usage(total)
- Memory Usage (Bazel)
- Memory Usage (total)
- System load average (total)
https://github.com/buildbuddy-io/buildbuddy-internal/issues/263
[recorded screen](https://github.com/buildbuddy-io/buildbuddy/assets/3977083/9c243133-8967-4bf5-918c-d70ab6c01777)
> Support Sampled TimeSeries Chart in Timing Tab

- enterprise/server/remote_execution/containers/podman/podman.go
I keep accidentally committing a change commenting out the call to this function when I'm developing locally.
> Add a flag that enables/disables running the soci snapshotter when it's needed

- enterprise/server/backends/pebble_cache/pebble_cache.go
> Use a more realistic default for migration QPS limit flag.

- enterprise/server/cmd/server/BUILD
- enterprise/server/cmd/server/main.go
- enterprise/server/sociartifactstore/BUILD
- enterprise/server/sociartifactstore/sociartifactstore.go
- enterprise/server/sociartifactstore/sociartifactstore_darwin.go
- enterprise/server/sociartifactstore/sociartifactstore_test.go
- enterprise/server/util/dsingleflight/BUILD
- enterprise/server/util/dsingleflight/dsingleflight.go
- server/environment/environment.go
- server/interfaces/interfaces.go
- server/real_environment/real_environment.go
> Actually set the image-to-index mapping in blobstore after it's generated and add a test that exercises that functionality

- enterprise/server/remote_execution/containers/firecracker/firecracker_test.go
> Fix firecracker tests not able to find iptables cmd

- .bazelrc
- .github/workflows/release-mac.yaml
> Remove `--config=remote` from release-mac workflow

- app/invocation/invocation.tsx
> fix bad non-null assumption in invocation.tsx

- enterprise/server/remote_execution/vfs/BUILD
- enterprise/server/remote_execution/vfs/vfs.go
- enterprise/server/remote_execution/vfs/vfs_darwin.go
- enterprise/server/remote_execution/vfs/vfs_linux.go
- enterprise/server/util/vfs_server/BUILD
- enterprise/server/util/vfs_server/vfs_server.go
- enterprise/server/util/vfs_server/vfs_server_test.go
- proto/vfs.proto
> FUSE: implement Link API

- app/invocation/invocation.css
- app/invocation/invocation_targets_card.tsx
Without this, trying to select a target name causes you to "drag" the link
> Make target names selectable for copying

- enterprise/server/remote_execution/containers/firecracker/firecracker_test.go
> Firecracker: prevent "invalid cross-device link" errors in bare tests

- enterprise/server/backends/authdb/authdb.go
- enterprise/server/backends/userdb/userdb.go
> Skip DB lookup of impossible API keys.

- app/invocation/BUILD
- app/invocation/invocation_model.tsx
- app/invocation/workflow_rerun_button.tsx
- app/target/target_test_coverage_card.tsx
> strict app/invocaton/invocation_model.tsx

- enterprise/server/cmd/server/main.go
- enterprise/server/sociartifactstore/BUILD
- enterprise/server/sociartifactstore/sociartifactstore.go
- enterprise/server/sociartifactstore/sociartifactstore_darwin.go
- enterprise/server/sociartifactstore/sociartifactstore_test.go
> Store the image-to-SOCI-index mapping in the cache instead of blostore

- cli/update_docs.sh
- docs/cli.md
- website/src/pages/cli.tsx
> CLI: bump version in docs to 5.0.10

- buildbuddy.yaml
- tools/dev_qa.py
> throw some TAGS onto a few build / test commands

- app/invocation/BUILD
- app/invocation/child_invocations.tsx
- app/invocation/invocation_error_card.tsx
- app/invocation/invocation_menu.tsx
- app/invocation/invocation_not_found.tsx
- app/invocation/invocation_raw_logs_card.tsx
- app/invocation/invocation_timing_card.tsx
- app/invocation/scorecard_card.tsx
> Some low-hanging strictification in app/invocation.

- server/tables/tables.go
> Change `default:false` to `default:0`

- app/format/format.tsx
- enterprise/app/filter/filter_util.tsx
- enterprise/app/trends/summary_card.tsx
- enterprise/app/trends/trends.tsx
- split out cache to its own section
- better copy
- better icons
> Rendering tweaks for trends summary section.

- server/tables/tables.go
> Remove unnecessary `int` gorm annotations

- enterprise/server/remote_execution/containers/firecracker/firecracker.go
- server/interfaces/interfaces.go
Try to get more info about the segfault by logging kernel logs
> Add more logging for workflow segfault debugging

- app/flame_chart/flame_chart.tsx
flame_chart: Delete imported unused components
> delete unused component

- server/build_event_protocol/build_event_handler/build_event_handler.go
> Unconditionally void invocation channel when first seqno > 1

- enterprise/server/remote_execution/containers/podman/BUILD
- enterprise/server/remote_execution/containers/podman/podman.go
- server/metrics/metrics.go
> Add a handful of metrics for tracking podman image pull performance with/without image streaming enabled

- app/invocation/BUILD
- app/invocation/cache_requests_card.tsx
- app/invocation/child_invocation_card.tsx
- app/invocation/invocation_action_card.tsx
- app/invocation/invocation_action_input_node.tsx
- app/invocation/invocation_artifacts_card.tsx
- app/invocation/invocation_breakdown_card.tsx
- app/invocation/invocation_details_card.tsx
- app/invocation/invocation_execution_card.tsx
- app/invocation/invocation_execution_table.tsx
- app/invocation/invocation_execution_util.tsx
- app/invocation/invocation_filter.tsx
- app/invocation/invocation_logs_model.tsx
- app/invocation/invocation_model.tsx
- app/invocation/invocation_overview.tsx
- app/invocation/invocation_share_button.tsx
- app/invocation/invocation_targets_card.tsx
- app/util/proto.ts
- enterprise/app/trends/drilldown_page.tsx
- rules/typescript/index.bzl
> strictify app/invocation: everything else

- app/invocation/workflow_rerun_button.tsx
- enterprise/server/cmd/ci_runner/main.go
> Cleanup unused flag

- server/build_event_protocol/build_event_handler/build_event_handler.go
- server/build_event_protocol/event_parser/event_parser.go
- server/build_event_protocol/invocation_format/invocation_format.go
- server/build_event_protocol/invocation_format/invocation_format_test.go
> dedupe tags

- tools/metrics/grafana/dashboards/buildbuddy.json
> Add a lil dashboard for image streaming metrics

- enterprise/server/remote_execution/containers/firecracker/firecracker.go
The debug log was not being triggered, even when there were segfaults while running workflows
> Check stderr for segfault to trigger debug logging

- enterprise/server/backends/authdb/BUILD
- enterprise/server/backends/authdb/authdb.go
I'd like to verify it's not being used and remove it.
> Log write_token usage.

- enterprise/server/test/integration/remote_execution/rbetest/rbetest.go
- enterprise/server/test/performance/cache/cache_test.go
- enterprise/server/util/cacheproxy/cacheproxy_test.go
- server/backends/memory_cache/memory_cache_test.go
> Replace some usages of testdigest.NewRandomDigestBuf with testdigest.RandomCASResourceBuf

- enterprise/server/sociartifactstore/sociartifactstore.go
> Update soci index cache seed

- website/blog/customer-managed-encryption-keys.md
> Fix tags in the encryption blog post

- enterprise/server/backends/authdb/BUILD
- enterprise/server/backends/userdb/BUILD
- enterprise/server/backends/userdb/userdb.go
- enterprise/server/usage/BUILD
- enterprise/server/usage/usage.go
- server/backends/invocationdb/BUILD
- server/interfaces/interfaces.go
- server/libmain/libmain.go
- server/tables/tables.go
- server/testutil/testenv/BUILD
- server/testutil/testenv/testenv.go
- server/testutil/testpostgres/BUILD
- server/testutil/testpostgres/testpostgres.go
- server/util/db/db.go
- server/util/db/db_test.go
This PR actually adds support for the postgres backend via the gorm postgres
driver.
> Add support for postgres db backend

- enterprise/server/backends/configsecrets/BUILD
- enterprise/server/backends/configsecrets/configsecrets.go
> Use new YAMLIgnore tag for configsecrets flags.

- website/blog/customer-managed-encryption-keys.md
> Fix typo in CMEK blog.

- enterprise/server/backends/pebble_cache/pebble_cache.go
- enterprise/server/backends/pebble_cache/pebble_cache_test.go
> Add AC eviction support.

- app/invocation/cache_requests_card.tsx
- app/invocation/invocation.tsx
- app/invocation/invocation_buttons.tsx
- app/invocation/invocation_menu.tsx
- app/invocation/invocation_model.tsx
- app/invocation/invocation_raw_logs_card.tsx
- app/invocation/invocation_share_button.tsx
- app/invocation/invocation_suggestion_card.tsx
> Defer invocation model creation so that it always has at least one invocation.

- enterprise/server/remote_execution/containers/firecracker/firecracker.go
- enterprise/tools/vmstart/vmstart.go
> Firecracker: Remove dead workspaceDirOverride code

- enterprise/server/cmd/goinit/main.go
The test failure was probably not caught in the original PR because firecracker_test doesn't run on CI (yet).
> Fix sysctl error in firecracker_test

- enterprise/server/remote_execution/containers/firecracker/firecracker_darwin.go
Accidentally broke this in https://github.com/buildbuddy-io/buildbuddy/pull/4151
> Fix LoadSnapshot signature in firecracker_darwin

- server/backends/blobstore/gcs/gcs.go
This way the service account doesn't need to be granted more permissions than necessary.
> Don't try to create GCS bucketg if existence check can't be done.

- enterprise/server/backends/pebble_cache/pebble_cache.go
> Implicitly enable background groupid sampling when AC eviction is enabled.

- enterprise/server/workflow/service/service.go
> Add basic logging for workflow clean re-runs

- app/invocation/invocation.css
> don't wrap duration text for child invocations, ever.

- enterprise/server/scheduling/task_leaser/BUILD
- enterprise/server/scheduling/task_leaser/task_leaser.go
> Mark executor API key as secret.

- app/invocation/invocation.css
- app/invocation/invocation_targets_card.tsx
- app/root/root.css
> Make targets look more clickable

- enterprise/app/usage/usage.tsx
- enterprise/server/usage/usage.go
- enterprise/server/usage_service/usage_service.go
- proto/usage.proto
- server/remote_cache/hit_tracker/hit_tracker.go
- server/tables/tables.go
**Related issues**: https://github.com/buildbuddy-io/buildbuddy-internal/issues/2325
> add cache writes and saved cpu time in frontend

- enterprise/server/saml/saml.go
> Fix usage of inline certs

- server/backends/github/github.go
- server/build_event_protocol/build_status_reporter/build_status_reporter.go
Always apply the status name suffix, e.g. ` (dev)`, just before publishing statuses, not just in BEP status publishing.
Fixes a bug that the new "Queued" status overwrites both the dev and prod status when we just re-run the dev workflow.
> Apply GitHub status suffix everywhere

- BUILD
- server/backends/disk_cache/disk_cache.go
- server/gossip/gossip.go
> Enable golang static check analyzer S1000 (Use plain channel send or receive instead of single-case select)

- BUILD
- enterprise/server/backends/distributed/distributed.go
> Enable golang staticcheck analyzer S1002 (Omit comparison with boolean constant)

- enterprise/server/backends/configsecrets/BUILD
- enterprise/server/backends/configsecrets/configsecrets.go
- enterprise/tools/check_metrics/BUILD
- enterprise/tools/check_metrics/check_metrics.go
- server/config/BUILD
- server/config/config.go
- server/config/config_test.go
- server/util/flagutil/common/BUILD
- server/util/flagutil/common/common.go
- server/util/flagutil/types/types.go
- server/util/flagutil/yaml/BUILD
- server/util/flagutil/yaml/yaml.go
- server/util/flagutil/yaml/yaml_test.go
This allows expansion to work for flags that are specified on the command line.
> Perform flag expansion on the flag values themselves.

- BUILD
- enterprise/server/backends/pebble_cache/pebble_cache.go
- enterprise/server/raft/nodeliveness/nodeliveness.go
- enterprise/server/raft/rangelease/rangelease.go
- enterprise/server/raft/replica/replica.go
- enterprise/server/util/pebble/pebble.go
- server/util/rangemap/rangemap.go
> Enable golang staticcheck analyzer S1004 (Replace call to bytes.Compare with bytes.Equal)

- enterprise/server/backends/authdb/BUILD
- enterprise/server/backends/authdb/authdb.go
> Mark API key encryption key as secret.

- BUILD
- enterprise/server/backends/migration_cache/migration_cache.go
- enterprise/server/raft/driver/driver.go
- enterprise/server/raft/listener/listener.go
- enterprise/server/raft/store/store.go
- enterprise/server/remote_execution/platform/platform_test.go
- enterprise/server/remote_execution/workspace/workspace.go
- server/remote_cache/hit_tracker/hit_tracker.go
- server/util/lockmap/lockmap_test.go
- server/util/tracing/tracing.go
- server/xcode/xcode_darwin.go
> Enable golang staticcheck analyzer S1005 (Drop unnecessary use of the blank identifier)

- app/auth/user.ts
**Related issues**: Fixes https://github.com/buildbuddy-io/buildbuddy-internal/issues/2425
> Fix 'selectedGroup property is required'

- docs/cli.md
- website/src/pages/cli.tsx
> Bump CLI version in docs to 5.0.12

- deps.bzl
- enterprise/server/cmd/executor/BUILD
https://github.com/buildbuddy-io/soci-sn…apshotter/commit/c1b8cd5a19f8ec80bc0bb488a897d8b00a4a4723
> Upgrade soci-store binary to buildbuddy-io/soci-snapshotter@HEAD

- BUILD
- enterprise/server/backends/userdb/userdb.go
- enterprise/server/remote_execution/containers/firecracker/firecracker_test.go
- enterprise/server/remote_execution/runner/runner.go
- server/remote_cache/hit_tracker/hit_tracker.go
> Enable golang staticcheck analyzer S1007 (Simplify regular expression by using raw string literal)

- BUILD
- server/util/lru/lru.go
- server/util/networking/networking.go
> Enable golang staticcheck analyzer S1008 (Simplify returning boolean expression)

- server/build_event_protocol/build_event_handler/build_event_handler.go
Just add a flag and wrap the specification of artifacts to persist with it.
**Related issues**: buildbuddy-io/buildbuddy-internal#2436
> add flag to diable persisting cache artifacts

- enterprise/server/backends/pebble_cache/pebble_cache.go
> Include partition ID in sampling warning log.

- docs/cache-encryption-keys.md
> docs/CMEK: fix bullet point and extra spaces

- .github/workflows/checkstyle.yaml
- WORKSPACE
- deps.bzl
Must be upgraded in sync with internal repo.
> gazelle: upgrade to v0.31.1

- app/target/action_card.tsx
Fixes https://github.com/buildbuddy-io/buildbuddy-internal/issues/2449
> action_card: display failureDetail

- website/blog/buck2.md
Fixup the blog with Tobias's feedbacks.
> buck2: update benchmark

- server/backends/github/github.go
- server/build_event_protocol/build_status_reporter/build_status_reporter.go
> Always log successful GH status requests

- BUILD
- enterprise/server/remote_execution/containers/sandbox/sandbox.go
> Enable golang staticcheck analyzer S1017 (Replace manual trimming with strings.TrimPrefix)

- enterprise/server/remote_execution/blockio/BUILD
- enterprise/server/remote_execution/blockio/blockio.go
- enterprise/server/remote_execution/blockio/blockio_test.go
- enterprise/server/remote_execution/containers/firecracker/firecracker.go
- enterprise/server/remote_execution/snaploader/BUILD
- enterprise/server/remote_execution/snaploader/snaploader.go
- enterprise/server/remote_execution/snaploader/snaploader_test.go
- proto/firecracker.proto
> Allow snaploader to store and load COW artifacts

- docs/workflows-config.md
- enterprise/server/workflow/config/config.go
- enterprise/server/workflow/service/service.go
> Add a 'pool' option to the workflow config

- server/backends/github/github.go
This PR extracts two methods out of the existing http handlers so they can be called elsewhere:
- StartAuthFlow
- Exchange
It also adds one new method for requesting user information given an access token:
- GetUserInfo
> Github backend changes to prepare for auth

- deps.bzl
https://github.com/buildbuddy-io/buildbuddy/pull/4211 switched from using this one to the buildbuddy-io one referenced here.
> Delete http_file for iain-macdonald/soci-snapshotter soci-store (not used anymore)

- app/menu/menu.tsx
- app/root/root.css
- enterprise/app/login/BUILD
- enterprise/app/login/login.tsx
- enterprise/app/root/root.tsx
- proto/config.proto
- static/index.html
> Frontend changes for new login page

- enterprise/server/githubapp/githubapp.go
- enterprise/server/githubauth/BUILD
- enterprise/server/githubauth/githubauth.go
Happy to answer any questions / discuss details / decisions via Slack
> Add `githubauth` which implements HTTPAuthenticator and UserAuthenticator

- enterprise/server/auth/BUILD
- enterprise/server/auth/auth.go
- server/static/BUILD
- server/static/static.go
Last bit of wiring to enable Github auth, adds the authenticators and populates the frontend configs
> Wire up github auth

- server/build_event_protocol/build_event_handler/build_event_handler.go
- server/bytestream/bytestream.go
https://github.com/buildbuddy-io/buildbuddy-internal/issues/2463
> Downgrade streaming error to warning.

- enterprise/server/remote_execution/nbd/nbdserver/nbdserver.go
We call `hotSwapWorkspace` while the VM is still running, which calls `SetDevice()`. But while we're hot-swapping the workspace disk, the scratch disk could still have writes going on. So we need to lock the device map in order to avoid setting off the race detector.
> Fix race in nbdserver

- enterprise/server/githubauth/githubauth.go
> Populate user's githubToken if logging in via githubauth

- app/invocation/child_invocations.tsx
> Fix UI breakage when trying to render a disconnected workflow.

- server/util/disk/BUILD
- server/util/disk/disk.go
- server/util/disk/disk_test.go
- server/util/disk/disk_unix.go
- server/util/disk/disk_windows.go
Provide a Windows implementation to check directory's size.
**Related issues**: https://github.com/buildbuddy-io/buildbuddy-internal/issues/2314
> util/disk: make implementation Windows friendly

- cli/cache_proxy/BUILD
- cli/cache_proxy/cache_proxy.go
Fixes: https://github.com/buildbuddy-io/buildbuddy-internal/issues/2316
> Fix CLI offline mode: return default capabilities if unable to communicate with server

- enterprise/app/root/root.tsx
- enterprise/app/sidebar/sidebar.css
- enterprise/app/sidebar/sidebar.tsx
This also makes this collapsed sidebar the default for dense mode, and removes dense mode specific sidebar styling.
https://github.com/buildbuddy-io/buildbuddy/assets/1704556/63c2f764-fc0a-42c7-a1a1-8d33e092c40f
> Add support for collapsing the sidebar

- enterprise/app/org/org_members.tsx
- enterprise/app/settings/settings.tsx
> Fix instances where UI assumes an email address

- enterprise/server/cmd/ci_runner/main.go
- enterprise/server/test/integration/ci_runner/ci_runner_test.go
This ensures that we publish the metadata event (with `ROLE=CI_RUNNER` etc.) even if the git repo setup fails (out of disk space, transient network error, etc.)
**Related issues**: Fixes https://github.com/buildbuddy-io/buildbuddy-internal/issues/2458
> Report workflow BuildMetadata event sooner

- enterprise/server/cmd/ci_runner/main.go
Tested with a private repo. The only issue I ran into was that the GH app also needs to be configured with access to the private repo, and the error message is confusing if it doesn't have access (the error message is just "repo not found").
Decided to use a credential helper instead of the `url.{}.insteadOf` trick, to avoid storing credentials on disk.
**Related issues**: https://github.com/buildbuddy-io/buildbuddy-internal/issues/2173
> workflows: allow fetching private repo dependencies matching target repo host

- enterprise/app/workflows/workflows.tsx
> fetch workflow history for legacy workflows, too.

- docs/cli.md
- website/src/pages/cli.tsx
> CLI: bump version in docs to 5.0.17

- enterprise/server/remote_execution/containers/docker/docker.go
- enterprise/server/remote_execution/containers/podman/podman.go
- enterprise/server/remote_execution/platform/platform.go
- enterprise/server/remote_execution/runner/runner.go
- enterprise/server/workflow/service/service.go
**Related issues**: https://github.com/buildbuddy-io/buildbuddy-internal/issues/2467
> Run podman/docker workflows with --init

- cli/plugin/plugin.go
- cli/test/integration/cli/cli_test.go
- cli/testutil/testcli/BUILD
- cli/testutil/testcli/testcli.go
- server/testutil/testfs/testfs.go
> Fix bazel progress output interspersed with CLI output

- .github/workflows/checkstyle.yaml
- BUILD
- rules/go/index.bzl
- tools/fix_go_deps.sh
> Use bazel-provisioned go sdk for buildfix.sh

- .github/workflows/website-pr.yaml
> Allow running 'Build Website' workflow on dependabot PRs

- proto/BUILD
- proto/auditlog.proto
- proto/buildbuddy_service.proto
- server/buildbuddy_server/BUILD
- server/buildbuddy_server/buildbuddy_server.go
- server/role_filter/role_filter.go
> Protos for audit logging.

- proto/auditlog.proto
- server/util/clickhouse/clickhouse.go
- server/util/clickhouse/schema/schema.go
> Clickhouse schema for audit logs.

- app/invocation/cache_requests_card.tsx
- app/invocation/dense/dense_invocation_overview.tsx
- app/invocation/invocation.tsx
- app/invocation/invocation_action_card.tsx
- app/invocation/invocation_artifacts_card.tsx
- app/invocation/invocation_buttons.tsx
- app/invocation/invocation_execution_card.tsx
- app/invocation/invocation_menu.tsx
- app/invocation/invocation_model.tsx
- app/invocation/invocation_overview.tsx
- app/invocation/invocation_raw_logs_card.tsx
- app/invocation/invocation_share_button.tsx
- app/invocation/invocation_suggestion_card.tsx
- app/invocation/invocation_timing_card.tsx
- app/invocation/scorecard_card.tsx
- app/target/target_test_coverage_card.tsx
> make the invocation model really only have one invocation in it.

- enterprise/server/auditlog/BUILD
- enterprise/server/auditlog/auditlog.go
- enterprise/server/cmd/server/BUILD
- enterprise/server/cmd/server/main.go
- server/environment/environment.go
- server/interfaces/BUILD
- server/interfaces/interfaces.go
- server/real_environment/real_environment.go
- server/testutil/testolapdb/testolapdb.go
> Service for logging audit events.

- docs/cli.md
- website/src/pages/cli.tsx
> update docs for bb cli 5.0.20 release
