buildbuddy-io/buildbuddy

server/util/clickhouse/clickhouse.go

clickhouse.OpenDB always return an error if you put the settings in the
options.

Fix set clickhouse conn options

---

.github/workflows/checkstyle.yaml
app/invocation/cache_requests_card.tsx

It fails due to the `origin/master` ref not existing, probably due to the upgrade to checkout v3.
---

Fix prettier checkstyle

---

tools/metrics/grafana/dashboards/buildbuddy.json

This graph shows how much rows bb app calls clickhouse to write. This
can show errors that are not caught by clickhouse metrics agent.

add a clickhouse graph

---

enterprise/server/raft/cache/cache.go
enterprise/server/raft/replica/replica.go

- Lease DB only for metadata changes
- Return unavailable so it can be retried
- Remove unused import
Note: I still see see split lease times over a second. I believe this is because scanning (and proto deserializing) so many files that have inline metadata content is slow.

smaller leases

---

enterprise/server/remote_execution/containers/firecracker/firecracker.go

`Tail()` should return a copy so that subsequent calls to `Write()` can't mutate the returned slice.
---

Fix race in firecracker VMLog

---

enterprise/server/remote_execution/containers/firecracker/firecracker.go
enterprise/server/remote_execution/containers/firecracker/firecracker_test.go

Context: https://github.com/buildbuddy-io/buildbuddy-internal/issues/1764
Upstream mitigation: https://github.com/firecracker-microvm/firecracker-go-sdk/pull/458
Tested: `firecracker_test` still passes; runner recycling still works locally.
---

Fix firecracker goroutine leak

---

cli/bazelisk/BUILD
cli/bazelisk/bazelisk.go
cli/cmd/bb/BUILD
cli/cmd/bb/bb.go
cli/terminal/BUILD
cli/terminal/terminal.go

Write bazelisk's output to a pty whose size is inherited from the current terminal. This causes target names to be output with the correct length and also removes the need for passing `--curses=yes` and `--color=yes` since Bazel now sees that it's writing to a terminal and won't disable fancy output by default.
---
**Related issues**: Fixes https://github.com/buildbuddy-io/buildbuddy-internal/issues/1758

CLI: Fix truncated bazel output

---

cli/tooltag/BUILD
cli/tooltag/tooltag.go

The banner is a bit distracting so remove it for now; maybe we can show it at most once/week and also show a feedback link at the end of the invocation?
---

CLI: Remove banner for now

---

cli/login/login.go
cli/plugin/plugin.go
cli/sidecar/sidecar.go
cli/storage/storage.go

UserCacheDir is meant as a temporary cache and may be cleaned up periodically (e.g. by disk cleanup utilities). This PR switches `bb login` to use UserConfigDir instead so that the user doesn't get logged out when they clear their cache.
---

CLI: Use UserConfigDir for config files

---

enterprise/server/backends/kms/BUILD
enterprise/server/backends/userdb/BUILD
enterprise/server/backends/userdb/userdb.go
enterprise/server/cmd/server/BUILD
enterprise/server/cmd/server/main.go
enterprise/server/remote_execution/execution_server/execution_server.go
enterprise/server/remote_execution/platform/platform.go
enterprise/server/secrets/BUILD
enterprise/server/secrets/secrets.go
server/interfaces/interfaces.go
server/role_filter/role_filter.go
server/tables/tables.go

Add basic secrets support
- Secrets are available to workflows by default
- They can be made available to any action by setting the property "include-secrets" = "true" in the action's execution properties. (There is a small performance penalty, 2 extra mysql reads, so this is opt-in)
- Secrets are decoded using a master key from the KMS *in the app* and passed to the executor over the grpcs channel -- so they should work with BYOR
- They are appended to the environment variables of the deserialized command included in the ExecutionTask, so they are not visible in the command proto that is stored in the cache
- Secrets can be created exactly like github secrets, multi-language examples here: https://docs.github.com/en/rest/actions/secrets#example-encrypting-a-secret-using-python. There is …

secret service

---

.github/workflows/release-cli.yaml

Getting `clang: unknown argument: -fnocanonical-system-headers` for the macos-latest release ([logs](https://github.com/buildbuddy-io/buildbuddy/actions/runs/3313987715/jobs/5472802736)). [This article](https://zpjiang.me/2019/03/23/bazel-unknown-argument-fno-canonical-system-headers/) suggests `bazel clean --expunge` might fix it.
---

CLI: Try bazel clean to fix release

---

.github/workflows/release-cli.yaml
.github/workflows/release-mac.yaml

GitHub is slowly migrating `macos-latest` jobs to macOS 12, and it breaks us. This PR pins us to macOS 11 until we can find a fix.
Context https://bazelbuild.slack.com/archives/CA31HN1T3/p1666632009661389
---

Pin actions to macos-11 for now

---

cli/release.py

Getting "tag already exists" because `git tag -l` sorts alphabetically, and `0.0.10` doesn't get sorted after `0.0.9` when sorting alphabetically.
---

CLI: Fix release script

---

server/util/clickhouse/clickhouse.go

There are 2 cases last week invocations were missing due to i/o timeout.
Further invetigation shows that they were not retried. Use
strings.Contains to check the error.

Retry timeout error

---

enterprise/server/scheduling/scheduler_server/scheduler_server.go

This makes the operation atomic.
It was previously possible for the claim task to succeed but the increment to fail leading to a task that could no longer be claimed.
---

Move attempt count increment into the claim script.

---

enterprise/server/scheduling/priority_task_scheduler/priority_task_scheduler.go

The returned RPC error now indicates whether the task is already claimed so no need to speculate.
---

Simplify claim error message.

---

enterprise/server/backends/distributed/distributed.go
enterprise/server/backends/distributed/distributed_test.go
enterprise/server/backends/gcs_cache/gcs_cache.go
enterprise/server/backends/memcache/memcache.go
enterprise/server/backends/migration_cache/migration_cache.go
enterprise/server/backends/migration_cache/migration_cache_test.go
enterprise/server/backends/pebble_cache/pebble_cache.go
enterprise/server/backends/pebble_cache/pebble_cache_test.go
enterprise/server/backends/redis_cache/redis_cache.go
enterprise/server/backends/s3_cache/s3_cache.go
enterprise/server/composable_cache/composable_cache.go
enterprise/server/raft/cache/cache.go
server/backends/disk_cache/disk_cache.go
server/backends/disk_cache/disk_cache_test.go
server/backends/memory_cache/memory_cache.go
server/interfaces/interfaces.go
server/remote_cache/byte_stream_server/byte_stream_server.go

See #2389 for more info
In cleaning up the WithIsolation method, I created duplicates of every cache method that take resource name objects instead of digests. Now I am cleaning up the deprecated old versions of the methods that take digests, and switching clients to use the new methods

Cleanup cache ContainsDeprecated method

---

enterprise/server/backends/distributed/distributed.go
enterprise/server/backends/gcs_cache/gcs_cache.go
enterprise/server/backends/memcache/memcache.go
enterprise/server/backends/migration_cache/migration_cache.go
enterprise/server/backends/migration_cache/migration_cache_test.go
enterprise/server/backends/pebble_cache/pebble_cache.go
enterprise/server/backends/pebble_cache/pebble_cache_test.go
enterprise/server/backends/redis_cache/redis_cache.go
enterprise/server/backends/s3_cache/s3_cache.go
enterprise/server/composable_cache/composable_cache.go
enterprise/server/raft/cache/BUILD
enterprise/server/raft/cache/cache.go
enterprise/server/raft/cache/cache_test.go
enterprise/server/registry/registry.go
enterprise/server/util/cacheproxy/cacheproxy.go
server/backends/disk_cache/disk_cache.go
server/backends/memory_cache/memory_cache.go
server/interfaces/interfaces.go
server/remote_cache/action_cache_server/action_cache_server.go
server/remote_cache/content_addressable_storage_server/content_addressable_storage_server.go

See https://github.com/buildbuddy-io/buildbuddy/pull/2389 for more info
In cleaning up the WithIsolation method, I created duplicates of every cache method that take resource name objects instead of digests. Now I am cleaning up the deprecated old versions of the methods that take digests, and switching clients to use the new methods

Clean up cache FindMissingDeprecated method

---

app/flame_chart/profile_model.ts

Right now these get built up in the wrong order, which breaks timing profile that have the correct closing sequence.
---

Build up `trailingNonWhitespaceCharacters` in correct order

---

proto/remote_execution.proto

I also pulled in the latest comments on the other output_* fields to lessen the diff between this and the remote version, though buildfix reformatted some of the comments because they're too too long in the remote version.
**Related issues**: Unblocks https://github.com/buildbuddy-io/buildbuddy-internal/issues/1766

Add output_paths fields to remote_execution.proto

---

enterprise/server/remote_execution/containers/firecracker/firecracker.go

We usually call `Remove(ctx)` with a `ctx` returned from `context.ExtendContextForFinalization(ctx, 10s)`. The problem is that `ExtendContextForFinalization` extends the context by up to 10s, but doesn't limit it to 10s. So if an action doesn't have a timeout, it can be blocked in `Remove()` for up to 7 days (our default timeout for actions that don't specify one).
This PR makes it so we only spend up to 10 seconds when trying to remove. Failing to remove is not ideal, but it's also not the end of the world since it happens very rarely.
There's an existing TODO to make this removal happen in the background instead of blocking execution, but a proper fix for that is a bit involved.
---
**Related issues**: https://github.com/buildbuddy-io/buildbuddy-internal/issues/1 …

Apply a timeout to VM removal

---

.github/workflows/release-cli.yaml
.github/workflows/release-m1.yaml
.github/workflows/release-mac.yaml
.github/workflows/release.yaml

I also capitalized 'Artifacts' in all the titles for consistency.
---

Rename release workflows from 'Upload Artifacts' to 'Build and Upload Artifacts' if they build stuff

---

server/tables/tables.go

The current type of the secret `value` column is VARCHAR(255) which is too short. This PR changes the type to `text` which has a longer max length.
---

Increase max length of secret values

---

server/remote_asset/fetch_server/fetch_server.go
server/test/integration/remote_asset/remote_asset_test.go

We don't need to check the digest after uploading to cache, since the cache should return an error if the uploaded digest doesn't match the resource name.
This behavior was introduced here: https://github.com/buildbuddy-io/buildbuddy/pull/2826/files#diff-acc021802981fe69ea4087d3e20feb202744d3783a040b04993fb6b89d9d2ee6R218
---

Remote asset: Remove extraneous digest check after mirroring to cache

---

enterprise/server/image_converter/image_converter.go
server/libmain/libmain.go
server/util/grpc_server/grpc_server.go
server/util/monitoring/monitoring.go

This allows passing "0" as a port value to let the OS auto-assign a random available port. If running on a shared machine it is useful for avoiding port collisions.
Example usage:
```
tylerw@lunchbox:~/buildbuddy$ blaze run enterprise/server -- -grpc_port=0 -grpcs_port=0 -internal_grpc_port=0 -internal_grpcs_port=0 -internal_http_port=0 -monitoring_port=0 -port=0 -ssl_port=0 -telemetry_port=0
INFO: Streaming build results to: https://app.buildbuddy.io/invocation/cc24b289-3e25-448b-83c0-4e3c784b5812
INFO: Analyzed target //enterprise/server:server (416 packages loaded, 8433 targets configured).
INFO: Found 1 target...
Target //enterprise/server/cmd/server:buildbuddy up-to-date:
bazel-bin/enterprise/server/cmd/server/buildbuddy_/buildbuddy
INFO: Elapsed time: 8.852s, Critical Path: 7.12s …
```

Allow passing 0 as a port value to pick an unassigned port

---

enterprise/server/image_converter/image_converter.go
server/libmain/libmain.go
server/util/grpc_server/grpc_server.go
server/util/monitoring/monitoring.go

Reverts buildbuddy-io/buildbuddy#2855
My guess is this is related to dev breaking b/c readiness check never passes. Not sure why yet.

Revert "Allow passing 0 as a port value to pick an unassigned port"

---

cli/arg/arg.go
cli/cmd/bb/bb.go
cli/parser/BUILD
cli/parser/parser.go
cli/parser/parser_test.go

* Expand --config args in place instead of appending them and then later trying to remove the args which were expanded from those configs
* Fix various bugs w/ bazelrc parsing logic, precedence etc.
* TODO in a future PR: add some build_metadata (maybe?) that tells BB what the original command line was before we expanded configs in place, so we can show a nicer "explicit command line" in the UI
---

CLI: Improve bazelrc parsing logic

---

server/gossip/BUILD
server/gossip/gossip.go

This prevents an issue when initially creating new gossip clusters on k8s where a node can fail to find peers and then never find them. I've only seen this happen once when deleting / recreating a stateful set, it should not normally occur.
This change creates a retrier and keeps attempting to connect for up to 180 seconds until connection succeeds. If no peers are joined in that time a warning is logged.

Gossip: attempt join for up to 180 seconds

---

.github/workflows/checkstyle.yaml

This seemed to fix a bug I ran into ("no merge base") when trying to determine the list of changed files.
---

Update changed-files action to v34

---

server/remote_asset/fetch_server/BUILD
server/remote_asset/fetch_server/fetch_server.go

Speeds up fetches (and reduces load on the cache) by checking Metadata and renewing the cache entry with FindMissingBlobs instead of downloading the full asset using the ByteStream API.
---

Remote asset: Determine digest size using Metadata API

---

app/invocation/cache_requests_card.tsx
server/remote_cache/scorecard/scorecard.go

buildbuddy-io/buildbuddy-internal#1733
Note: After this change, old cache scorecards won’t show on the UI
For scorecards created over 15 days ago - when we merged the change to write the new cacheType field - that cacheType field will be 0 UNKNOWN_CACHE_TYPE. All these scorecard results will be filtered out [here](https://github.com/buildbuddy-io/buildbuddy/blob/master/server/remote_cache/scorecard/scorecard.go#L108).

Stop reading deprecated cache type field from cache scorecards

---

enterprise/server/raft/cache/cache.go
enterprise/server/raft/driver/driver.go
enterprise/server/raft/replica/replica.go
enterprise/server/raft/replica/replica_test.go
enterprise/server/raft/store/BUILD
enterprise/server/raft/store/store.go
proto/raft.proto

This change moves the split triggering logic out of the driver and into the store + replica. Replicas periodically check their own usage and when it is over a certain size, they request a split from the store. This change simplifies things and also reduces the time it takes for a range to split when over size. It also reduces the load on the gossip network since the store no longer needs to "poll" so aggressively to catch size changes, instead they are driven by replicas increasing in size.

local split

---

WORKSPACE
deps.bzl

`go_rules_dependencies` declares many repositories, which was causing our repository definitions with the same names to be silently ignored. To prevent this, we declare our deps first, and then apply gazelle patches as needed to the relevant libraries. Libraries that do not currently need to be patched now contain a commented-out block that would apply the patch as documentation in case the patch (or a modification of the patch) needs to be applied in the future.
---

Supercede `go_rules_dependencies` with our deps

---

buildbuddy.yaml
cli/plugins/notify/README.md
cli/plugins/notify/post_bazel.sh
cli/plugins/notify/pre_bazel.py
cli/plugins/notify/pre_bazel.sh

Allows passing a `--notify` flag that shows a desktop notification when the build completes. On macOS, notifications can also optionally show a sound (by setting the env var `BB_NOTIFY_SOUND=1`).
---

CLI: Add a plugin to get notified when a build completes

---

cli/cmd/bb/bb.go
cli/parser/BUILD
cli/parser/parser.go
cli/parser/parser_test.go

* Expand `startup` options
* Fix bug where `--config` flags specified in higher-precedence phases wouldn't expand configs defined for phases they inherit from.
* Example: If bazelrc contains the lines `build:foo --some_flag` and `test --config=foo`, we now correctly get `--some_flag` when running `bazel test`
* Fix bug that `%workspace%` was resolved to the current working directory rather than the workspace directory
* Detect circular config file references instead of panicking with a stack overflow error
* Detect circular imports instead of panicking with a stack overflow error
---

CLI: Fix more bazelrc parsing bugs

---

tools/metrics/grafana/dashboards/buildbuddy.json

Unclear why but Raft & Golang panels are broken right now.
I re-saved the dashboard and it fixed itself... :shrug:
---

Fix grafana dashboard.

---

enterprise/server/raft/driver/driver.go
enterprise/server/raft/replica/replica.go
enterprise/server/raft/replica/replica_test.go
enterprise/server/raft/store/store.go

- Move gossip broadcast from driver to store and stop polling
- Replicas now notify the store periodically of their usage
- Splits are triggered in the store, not the replica
In a follow up I will stop calling replica.Usage() from broadcast() and instead use the last observed usage value, also hopefully attempt to call ListCluster less from the driver.

Gossip less frequently (part 1)

---

cli/plugin/BUILD
cli/plugin/plugin.go
cli/plugin/plugin_test.go
cli/workspace/BUILD
cli/workspace/workspace.go
server/util/disk/disk.go

Adds support for a `--user` flag to `bb install` which installs plugins to `~/buildbuddy.yaml` instead of `./buildbuddy.yaml`.
We now also load plugins from both `~/buildbuddy.yaml` and `%workspace%/buildbuddy.yaml`. If there are duplicate plugins (same repo and path, but potentially different versions), we prefer the one in the workspace `buildbuddy.yaml`.
---

CLI: Support user-level plugins

---

enterprise/server/backends/pebble_cache/pebble_cache.go
enterprise/server/backends/pebble_cache/pebble_cache_test.go
enterprise/server/raft/filestore/filestore.go
enterprise/server/raft/replica/replica_test.go

During the isolate by group ID migration, we should also remove the duplicate partition ID in the pebble cache file name
For partition default:
- previous name would be: PTdefault/default/groupid/ac/hash
- now it will be: PTdefault/groupid/ac/hash

Remove duplicate partition ID from file path in pebble

---

tools/cas/BUILD
tools/cas/cas.go

Pass `--metadata` to log the human-readable cache metadata just before fetching. Pass `--metadata_only` to fetch the cache metadata, print it as JSON to stdout, and exit -- useful for scripts that want to fetch the metadata and process it with something like `jq`.
---

Add cas tool option to get cache metadata

---

cli/plugin/BUILD
cli/plugin/plugin.go
cli/plugin/plugin_test.go

Instead of `bb install buildbuddy-io/plugins --path=go_deps`, users can run `bb install buildbuddy-io/plugins:go_deps`
---

CLI: Allow specifying repo subdir with :path suffix

---

cli/help/BUILD
cli/help/help.go
cli/parser/parser.go

Fix `bb install --help` not working.
---

CLI: Fix subcommand help

---

enterprise/server/raft/sender/sender.go

- Update the cache whenever we consult the metarange
- Only re-order replicas when necessary
- Simplify some control flow logic
- Remove now-unused RunAll method

Fix RangeCache misses

---

cli/sidecar/BUILD
cli/sidecar/sidecar.go

* The sidecar will now write its logs to a `.log` file next to its `.sock` file.
* Log level can be figured by running the CLI like `BB_SIDECAR_ARGS='--app.log_level=debug' bb run ...`
---

CLI: Allow viewing sidecar debug logs

---

cli/arg/BUILD
cli/arg/arg.go
cli/arg/arg_test.go
cli/sidecar/sidecar.go

If there are multiple argument values of `bes_backend`, `remote_cache` etc, the last one should win.
---

CLI: Fix handling of sidecar backend args

---

enterprise/server/remote_execution/dirtools/dirtools.go
enterprise/server/remote_execution/workspace/workspace.go
enterprise/server/test/integration/remote_execution/remote_execution_test.go

rules_kotlin doesn't respect the behavior described here: https://github.com/bazelbuild/remote-apis/blob/main/build/bazel/remote/execution/v2/remote_execution.proto#L589 so this change breaks clients using those rules.

Revert "Support Command.output_paths"

---

cli/plugin/plugin.go
docs/cli-plugins.md
docs/cli.md

Instead of invoking plugins directly, we'll invoke with `/usr/bin/env bash` so that plugin authors don't have to remember to `chmod +x` each hook script.
---

CLI: Don't require hook scripts to be executable

---

cli/plugin/plugin.go
cli/plugin/plugin_test.go

I kept around the `--path` arg because of the nice ergonomics (e.g. tab completion, easier to pass to something like `xargs`, etc.)
---

CLI: Allow local plugins to be specified as :PATH

---

app/invocation/invocation_details_card.tsx
cli/bazelisk/bazelisk.go
cli/cmd/bb/BUILD
cli/cmd/bb/bb.go
cli/metadata/BUILD
cli/metadata/metadata.go

We expand `.bazelrc` default arguments and `--config` flags, causing the explicit command line to be super long. This PR lets us show the original `bb` tool command line under "explicit command line" instead of the expanded Bazel command line.
---

CLI: Override explicit command line in the UI

---

enterprise/dockerfiles/ci_runner_image/Dockerfile

- Install `python3.6-dev` apt package to satisfy python gRPC system deps. Context: https://buildbuddy.slack.com/archives/CUHBFVATU/p1668434604090649?thread_ts=1668434529.712729&cid=CUHBFVATU
- Pre-download/extract bazel 5.3.1 by default, instead of 4.0.0
- Clean up `apt-get` artifacts to reduce image size.
Overall, uncompressed image size is reduced by 282 MB.
```
Before    After
Compressed      942M      863M
Uncompressed    2.427GB   2.145GB
```
---

CI runner image improvements

---

cli/cmd/bb/bb.go
cli/watcher/BUILD
cli/watcher/watcher.go
deps.bzl
go.mod
go.sum

If a post-bazel plugin (like `go-deps`) writes a file, it causes the file watcher to immediately kick in and restart the `bb` command, clobbering the console output and preventing other fixes from running. This PR pauses the watcher while post-bazel plugins are running, so that the plugins can run to completion before the `bb` command gets restarted.
---

CLI: prevent watcher from interrupting post-bazel plugins

---

enterprise/server/remote_execution/dirtools/dirtools.go
enterprise/server/remote_execution/workspace/workspace.go
enterprise/server/test/integration/remote_execution/remote_execution_test.go

This is a rollforward (with fixes) of https://github.com/buildbuddy-io/buildbuddy/pull/2879 which was reverted in https://github.com/buildbuddy-io/buildbuddy/pull/2903 because some rules_kotlin rules expected the previous behavior of output_directories.
This PR does a few things:
Adds a more complex test for the various kinds of outputs (output_directories, output_files, and output_paths)
Supports output_paths instead of output_files and output_directories, when specified. Otherwise, falls back to output_files and output_directories. N.B. that the behavior of output_paths is slightly different than the behavior of output_files and output_directories: the executor will only create the parents of all of the specified output_paths, not the paths themselves.
Does not change the behavior when …

Support Command.output_paths (attempt #2)

---

.github/workflows/checkstyle.yaml

Disabling changed-files due to https://github.com/tj-actions/changed-files/issues/809
---

Disable changed-files action

---

cli/example_plugins/ping-remote/pre_bazel.sh

* Correctly parse args by looking only at the last `remote_executor` flag, and handling both `--remote_executor <value>` and `--remote_executor=<value>`.
* Pull in the `timeout` function from `siggisim/ping-remote`
* Handle any remote, not just `remote.buildbuddy.io`.
---

CLI: Fixes for ping-remote example plugin

---

WORKSPACE
enterprise/server/cmd/server/BUILD
server/util/db/BUILD
server/util/db/db.go
server/util/db/db_test.go

To support this functionality, users will need to use the new 'advanced' configuration stanzas. We need this to be able to generate the DSN using the short-lived tokens returned by AWS.
A typical use will look like this:
```
advanced_data_source:
driver: mysql
use_aws_iam: true
region: some-region
endpoint: some-instance:3306
username: some-user
db_name: buildbuddy
```
Most users can continue to use the simpler 'data_source' option.
The other notable change is that we now control the creation of new DB connections so that we can generate a new DSN every time since the generated AWS IAM tokens are short-lived.
---

Add AWS IAM support for DB connections.

---

server/backends/chunkstore/BUILD
server/backends/chunkstore/chunkstore.go
server/util/timeutil/timeutil.go

Addresses buildbuddy-io/buildbuddy-internal#1806
---

Use `Timer` instead of `time.After` so we can drain channels and avoid a memory leak

---

cli/BUILD
cli/bazelisk/BUILD
cli/bazelisk/bazelisk.go
cli/cmd/bb/BUILD
cli/cmd/bb/bb.go
cli/help/help.go
cli/install.sh
cli/log/log.go
cli/update/BUILD
cli/update/update.go
cli/version/version.go

This PR lets users update their CLI version to the latest version with `bb update`.
The command tries to be smart -- if bb is run via the `.bazelversion` trick, then it just updates the `.bazelversion` line to reference the new version. Otherwise it updates `/usr/local/bin/bb`. Users can override this default behavior by specifying `--workspace` and/or `--system`.
---

CLI: Add bb update command to update the CLI itself

---

cli/plugin/plugin.go

This is useful for plugins to store build artifacts, e.g. via `go build`. Plugins should create their own plugin-specific dir under this cache dir. Per-version caches can be managed by the plugin if needed, e.g.  by creating a subdir like `$USER_CACHE_DIR/my-plugin-name/$(git rev-parse HEAD)`
---

CLI: Set USER_CACHE_DIR in plugin env

---

cli/bazelisk/bazelisk.go
cli/cmd/bb/BUILD
cli/cmd/bb/bb.go
cli/help/help.go
cli/printlog/BUILD
cli/printlog/printlog.go
proto/BUILD
proto/remote_execution_log.proto

Adds a command `bb print --grpc_log=PATH` which prints a sequence of JSON-serialized LogEntry protos.
This is effectively the same as `remote_client --grpc_log` (from https://github.com/bazelbuild/tools_remote) except the output is easier to parse with something like `jq`, and also the BuildBuddy extensions to REAPI V2 are rendered with their correct names, instead of tag numbers (such as ExecutedActionMetadata.usage_stats).
Will add website docs in a separate PR.
---

CLI: Add a `print` command to view serialized bazel log files

---

enterprise/server/testutil/buildbuddy_enterprise/BUILD
enterprise/server/testutil/buildbuddy_enterprise/buildbuddy_enterprise.go
server/testutil/app/app.go

I can't repro this now, but earlier some tests were being slow (taking 20s longer than usual) since the telemetry client was timing out.
There's not much value in having telemetry enabled for tests (this probably just muddies our telemetry data) so this PR makes sure that telemetry is disabled in tests.
* Disable telemetry client for OSS app in tests, not just the enterprise app
* Disable telemetry server for enterprise app in tests
---

Disable telemetry in tests

---

BUILD
WORKSPACE

I had to do a few things to make this work:
- Remove the managed_directories directive from our WORKSPACE file and set symlink_node_modules to False in the yarn_install directive.
- Migrate to platform definitions from https://github.com/bazelbuild/platforms.
- Upgrade to version 0.7 of rules_k8s (which switches to use the platform definitions above).
- Clear the go_version passed into k8s_go_deps, otherwise it specifies a version which conflicts with ours. I thought about changing our version to match theirs but that didn't work out of the box and I thought it'd be better to have ours be the only go version definition.
You can test this yourself by running (change version & checksum for different platforms):
`wget -O /tmp/bazel-6.0.0-pre.20221020.1-linux-x86_64 …

Make repo build with bazel 6

---

website/blog/clickhouse-build-trends.md

1. millions on -> millions of
2. space after comma,
3. 24 seconds -> 24 minutes. (i incorrectly changed 23 min 45.83 seconds to 24 seconds during edits)

fix typos in the clickhouse blogpost

---

server/util/bazel_request/BUILD
server/util/bazel_request/bazel_request.go
server/util/bazel_request/bazel_request_test.go

Context: https://github.com/buildbuddy-io/buildbuddy/pull/2916#issuecomment-1314209533
This will also be useful to address https://github.com/buildbuddy-io/buildbuddy-internal/issues/1187
---

Add utilities for bazel client version parsing and comparison

---

app/flame_chart/colors.ts
app/flame_chart/flame_chart_model.ts
app/invocation/invocation.css
app/invocation/invocation_breakdown_card.tsx
app/invocation/invocation_timing_card.tsx

Also:
- Pulls getColor out of flame chart so we can use it in other places to get stable colors
- Formats durations nicely on timing page
- Adds hints for how to get better information out of your timing profile
- Adds (commented out for now) link to view suggestions based on timing profile
Screenshot:
---

Add timing breakdown card to timing profile

---

docs/config-cache.md

documented this parameter, to enable bazel 5.0 `experimental_remote_cache_compression` capabilities.

documented `zstd_transcoding_enabled`

---

app/flame_chart/BUILD
app/flame_chart/flame_chart_model.ts
app/invocation/BUILD
app/invocation/invocation_breakdown_card.tsx
app/util/BUILD
app/util/color.ts

The colors were randomly generated so they looked a bit drab and some colors were hard to tell apart.
**Before**
**After**
---

Use material colors for timing breakdown

---

enterprise/server/backends/distributed/BUILD
enterprise/server/backends/distributed/distributed.go
enterprise/server/util/cacheproxy/BUILD
enterprise/server/util/cacheproxy/cacheproxy.go
enterprise/server/util/cacheproxy/cacheproxy_test.go
proto/distributed_cache.proto

We need this change in order to pass a resource's compression type to distributed cache methods

Use resource.ResourceName in distributed cache function

---

app/invocation/invocation_artifacts_card.tsx
app/root/root.css
app/target/target_artifacts_card.tsx
enterprise/app/code/code.css
enterprise/app/code/code.tsx

Screenshot of view button next to artifacts:
Screenshot of single file code editor view:
---

Make artifacts viewable in code editor

---

cli/analyze/BUILD
cli/analyze/analyze.go
cli/bazelisk/BUILD
cli/bazelisk/bazelisk.go
cli/cmd/bb/BUILD
cli/cmd/bb/bb.go
cli/help/help.go
cli/printlog/printlog.go
proto/BUILD
proto/bazel_query.proto

* Add a `bb analyze` subcommand which accepts a PATTERN argument (defaulting to `//...`) and then analyzes the dependency graph for that pattern, using various analysis types. By default all analysis types are enabled, but specific analyses can be selected using flags.
* Add a "cost" analysis which takes into account the number of changes to a target's source files over a given time period (defaults to 4 weeks), as well as the number of transitive deps of a target. Roughly speaking it is the minimum number of invalidated actions that are caused by changes to a target's source files. (I say "roughly" and "minimum" because it only counts commits and not edits, doesn't account for historical changes to the build graph structure, and only counts the current branch, e.g. the main branch)
* Add …

CLI: Add an `analyze` command for dependency graph analysis

---

enterprise/app/code/code.tsx

This fixes an issue with displaying changes introduced by the artifact viewer change and makes the artifact viewer mode read-only.
---

Fix changes view in code editor and make single file view read-only

---

server/remote_cache/config/config.go

I've seen multiple customers run into this and I think it's safe to enable by default.

Enable zstd transcoding by default

---

enterprise/server/backends/migration_cache/config.go
enterprise/server/backends/migration_cache/migration_cache.go

* Also fix a bug in FindMissing where we were hardcoding "Compressor: repb.Compressor_IDENTITY" when queuing the data to be copied. FindMissing is always called with resources with the identity compressor anyway, so this shouldn't matter. But it's technically incorrect and could cause a subtle bug later

Implement SupportsCompressor for migration cache

---

tools/dev_qa.sh

The `~` wasn't being expanded due to being inside quotes, causing the QA repos to be cloned into the literal path `./~/buildbuddy-qa`.
---

Fix dev_qa script

---

buildfix.sh

Instead of using the gazelle binary in `$PATH`, always invoke Gazelle using `bazel run //:gazelle`.
---

Always use workspace version of gazelle for buildfix.sh

---

cli/cmd/sidecar/sidecar.go

I was seeing some behavior where `bb` builds were spending a few seconds in "Waiting for build events upload" at the end of each build. The specific command I was testing was `bb build //enterprise/server --config=cache`.
While waiting for BES uploads, the sidecar logs show that it's serving lots of `FindMissingBlobs` requests that need to be forwarded to the remote, since the blobs aren't available in the sidecar's local disk cache. The logs also show lots of cache evictions happening, which seems to be due to the small cache size.
By bumping the cache size, we can fit more BES uploads across builds in the local cache, making it so that most of the `FindMissingBlobs` requests can be served locally, so the build doesn't need to spend as long at the end.
---

CLI: Increase the sidecar's default local cache size

---

.bazelrc

Looks like these are failing on GH actions too, not just BB workflows -- probably because the default execution image (ubuntu 16.04) has an outdated gcc version.
---

Disable race detection for GH action builds

---

.bazelignore

Occasionally I get weird errors due to bazel trying to build targets under `bazel-bin`, `bazel-buildbuddy` etc. when running things like `bazel test //...`. Example:
`ERROR: error loading package 'bazel-bin/server/test/webdriver/invocation/invocation_test_chromium-local.sh.runfiles/buildbuddy/server/util/bazel/bazel-5.3.0_install/embedded_tools/src/conditions': Label '//tools/windows:windows_config.bzl' is invalid because 'tools/windows' is not a package; perhaps you meant to put the colon here: '//tools:windows/windows_config.bzl'?`
Seems like bazel should never traverse these symlinks when expanding `//...` so this is probably a weird Bazel bug, but adding the bazel convenience symlinks to `.bazelignore` seems to fix it.
---

Add bazel symlinks to .bazelignore

---

deployment/BUILD
dockerfiles/run_script/BUILD
dockerfiles/test_images/BUILD
enterprise/deployment/BUILD
enterprise/server/deployment/BUILD
release.py
tools/cacheload/BUILD
tools/probers/BUILD
tools/rbeperf/BUILD
tools/tcpproxy/BUILD

Migrate from setting the version with `--define=version=TAG` to `--//deployment:image_tag=TAG`.
Unfortunately the analysis cache is still discarded when changing starlark flags (see https://github.com/bazelbuild/bazel/issues/13591), but I figured since the docs say that "--define" is "legacy syntax" it's worth migrating to a starlark flag either way.
---

Set pushed image tag using starlark flag

---

.github/workflows/release-m1.yaml
.github/workflows/release-mac.yaml
.github/workflows/release.yaml
release.py
server/version/BUILD
server/version/version.go
tools/latest_version_tag.sh
workspace_status.sh

Instead of a starlark flag (which we could potentially forget to set), embed the version info using `workspace_status.sh`.
Also fix the way that we were embedding the commit SHA. The commit SHA could potentially be stale since it was part of the "volatile" status, which means it doesn't trigger rebuilds if changed. Prefixing it with "STABLE_" fixes this.
---

Embed version info using stamping instead of starlark flag

---

server/ssl/ssl.go

Can be set with:
```
ssl:
client_cert_lifespan: 730h # 1 month
...
```
---

Make client certificate lifespan configurable

---

server/util/redact/redact.go
server/util/redact/redact_test.go

I went back and forth a little bit in considering how to fix this bug. The issue is that when flags are specified as `--flag_name=KEY=@value` then the `KEY=@` matches the regular expression that tries to identify passwords (I think?) in flag values [here](https://github.com/buildbuddy-io/buildbuddy/blob/master/server/util/redact/redact.go#L31). Without the '@' it wouldn't match, which is why this bug isn't a bit more common.
The approach I took is to specifically look for the `--build_metadata` flag and when it's encountered treat the flag value as a list of comma-delimited, KEY=VALUE "sub-flags" and in this case just redact the values of these sub flags, leaving the keys intact. It should be easy to add additional flags to be treated this way in the future.
A couple of other approaches I …

Redact individual values in --build_metadata sub-flags instead of just redacting everything after the '='.

---

cli/log/log.go
cli/sidecar/sidecar.go
cli/test/integration/cli/BUILD
cli/test/integration/cli/cli_test.go

The sidecar shouldn't be initialized unless there is a bes_backend or remote_cache set. This logic broke in an earlier PR, and this PR fixes it.
---

CLI: Don't initialize sidecar if it won't proxy any requests

---

enterprise/server/backends/pebble_cache/pebble_cache.go
enterprise/server/backends/pebble_cache/pebble_cache_test.go

Revert metadata change to get size from the cached digest

---

enterprise/server/auth/auth.go

If the session cookie is invalid (points to a row in the DB that does not exist), this can cause the auth logic to get into a bad state where going through the login oauth flow will not grant a refresh token, because the login flow assumes that if the session cookie is set at all (valid or not) then we don't need to re-request a refresh token.
This can happen if the DB gets cleared, e.g. during local development (which uses a DB under /tmp/). I'm not sure if there are other situations where it can happen.
---

Clear login cookie if it's invalid

---

app/invocation/cache_requests_card.tsx

* In the hovercard, replace "Digest" with "Action ID", since the action ID can either be an action digest, or a string like "bes-upload". This fixes an issue that the hovercard would show "Digest: bes-upload"
* In the grouping headers, fix an issue that grouping by target would show an incorrect label in the group header if the target is missing. Before, it'd show the first action ID in the list of rows whose target label is missing. Now, it shows "(Unknown target)". We'll also show "(Unknown target) > (Uknown action)" when grouping by Action and both the action ID and action mnemonic are unknown.
---

Fix some scorecard labels

---

cli/cache_proxy/cache_proxy.go

Lots of remote writes are getting dropped due to the small queue capacity. Increasing the queue length so that the sidecar can better utilize upload bandwidth once the invocation is complete.
---

CLI: Increase cache proxy write queue size

---

enterprise/server/backends/pebble_cache/pebble_cache.go

This logging will have some false positive rate, because on dev compression is on and in those cases we'd expect the sizes to be different.

Add debug logging if pebble metadata size does not match size in cached digest

---

enterprise/server/cmd/executor/executor.go
server/util/networking/networking.go

- Use `sudo -A` to make sure the executor never gets stuck prompting for a sudo password.
- Instead of using `sudo sh -c '<script that invokes ip command>'` for ip netns cleanup, run `sudo ip` commands directly and process the intermediate results with Go, since `enable_local_firecracker.sh` only sets up passwordless sudo for the `ip` command, not the `sh` command.
- If the networking cleanup fails, log a debug message instead of `exit(1)`, since we don't want this to be a fatal err on Mac or if someone hasn't run `enable_local_firecracker.sh` on Linux.
---

Fix executor startup

---

enterprise/config/executor.local.yaml

Set firecracker_cgroup_version=2 when running executor locally.

---

enterprise/server/backends/pebble_cache/pebble_cache.go

Realized we'd get more hits on this log if we moved it to metadata lookups and writes, because the cache Metadata function doesn't get as much traffic

Add debug logging if pebble metadata size does not match size in cached digest - Move to lookups and writes

---

docs/cli.md
website/src/pages/cli.tsx

* Fixes `Ctrl+C` handling (don't forward Ctrl+C to sidecar)
* Increases the cache proxy upload buffer size so that more Write requests can occur in the background
---

CLI: bump version in docs to 0.1.2

---

cli/plugins/open-invocation/pre_bazel.py

Allows opening a specific sub-page, e.g. by setting `--open='#timing'` or `--open='?filter=...&sort=...#cache'`
Useful when iterating on a specific feature in the UI using test builds.
---

CLI: Allow opening a specific sub-page with the `--open` plugin

---

enterprise/server/remote_execution/containers/firecracker/firecracker.go

Add --executor.firecracker_kill_host_on_failure flag that kills the host executor process if there's a problem with Firecracker.

---

server/build_event_protocol/build_event_handler/build_event_handler.go
server/build_event_protocol/build_event_server/build_event_server.go

I accidentally reverted some of the changes made in
https://github.com/buildbuddy-io/buildbuddy/pull/2813 in my PR
https://github.com/buildbuddy-io/buildbuddy/pull/2837
When we call `postProcessStream`, the `ctx` was from `stream.Context()`. We didn't set the IID from the `streamID.InvocationId` explicitly. This might cause the inconsistent iid in the logs. https://github.com/buildbuddy-io/buildbuddy-internal/issues/1863

EnrichCtx before we call OpenChannel

---

server/util/networking/networking.go

When running the executor with firecracker locally, concurrent `iptables` commands can conflict with one another, returning errors like:
`2022/12/13 14:30:43.906 FTL dying on firecracker error: rpc error: code = Internal desc = Error running "/usr/bin/sudo -A ip netns exec bb-executor-f34cfb00-e3ec-43f3-89ef-6ed99154d4e6 iptables -t nat -A POSTROUTING -o veth0mmV9K -s 192.168.241.2 -j SNAT --to 192.168.0.99" Another app is currently holding the xtables lock. Perhaps you want to use the -w option?
: exit status 4`
This doesn't happen (or at least not as frequently) with --jobs=1 which makes me more confident in my diagnosis. I could have fixed this by protecting these calls with a mutex, but this seems simpler for now.

Put --wait in all iptables commands in networking.go

---

rules/yarn/index.bzl

The original code was setting `PATH=$PATH:/path/containing/bazel/provisioned/node` but that logic still causes the system nodejs to take precedence. The `$PATH` needs to go at the end to make the WORKSPACE version take precedence, not the beginning
---

Use nodejs version from WORKSPACE

---

tools/cacheload/BUILD
tools/cacheload/cacheload.go

This will let us run this thing with --keep_going  and then check errors in grafana or set prom alerts for them.

Add some prom metrics for cacheload errors

---

enterprise/config/executor.local.yaml
enterprise/server/remote_execution/containers/firecracker/firecracker.go

This PR:
- Detects the cgroup version from the system (by running `stat -fc %T /sys/fs/cgroup/` and searching for `cgroup2fs` or `tmpfs`) when `--executor.firecracker_cgroup_version` is an empty string. Otherwise, the value from `--executor.firecracker_cgroup_version` is used.
- Switches the default value of `--executor.firecracker_cgroup_version` to be an empty string, enabled the behavior above.

Support detecting cgroup version from system

---

enterprise/server/remote_execution/execution_server/execution_server.go
enterprise/server/scheduling/scheduler_server/scheduler_server.go
enterprise/server/scheduling/scheduler_server/scheduler_server_test.go
server/interfaces/interfaces.go

Even if the group has selected "default to self hosted executors", schedule workflow actions on shared executors, since we currently don't support self-hosted Linux workflows.
---

Always use shared executors for Linux workflows

---

enterprise/server/backends/pebble_cache/pebble_cache.go
server/metrics/metrics.go

In prod, the majority of blobs with a bad compression ratio (increased in size when compressed) were between 10,000B and 100,000B. This metric was added to see if there was a clear size cutoff above which compression was helpful in the majority of cases so we could use it as our minimum compression size. That doesn't seem to hold true, so the metric isn't really useful.

Remove unhelpful compression metric

---

docs/cli.md
website/src/pages/cli.tsx

Contains fixes for missing scorecard metadata and fixes bytestream:// URIs of bes-uploads.
---

CLI: bump version in docs to 0.1.3

---

enterprise/server/remote_execution/containers/firecracker/firecracker_test.go

Apparently this is not a safe assumption ([StackOverflow](https://stackoverflow.com/questions/34831861/can-i-assume-that-nobody-is-65534)) and running this on Tyler's machine the uid and gid are 99 so it fails.

Don't assume nobody is uid/gid 65534 in firecracker_test.go

---

enterprise/server/remote_execution/containers/firecracker/firecracker_test.go

This PR just asserts that they're there and then clears them for the proto comparison with the expected result.

Let there be UsageStats in the result returned to TestFirecrackerFileMapping.

---

enterprise/server/remote_execution/containers/firecracker/firecracker_test.go

In https://github.com/buildbuddy-io/buildbuddy/commit/c6fc4771eab75618e147fac4b0f9643e5850d45f

Forgot the 't' in assert.True(...)

---

tools/metrics/grafana/dashboards/buildbuddy.json

- Split disk/network IO, memory, and swap rate panels into separate expandable groups, since currently it requires scrolling down for a really long time to access each different type of metric (since we have a lot of nodes)
- Add a new "swap usage" row (currently we have swap rate, but not swap usage).
- Rename "Kubernetes nodes" with just "Nodes" to avoid confusion in the Mac case.
Before:
After:
---

Reorganize node metric panels in Grafana

---

server/build_event_protocol/build_event_handler/build_event_handler.go
server/build_event_protocol/event_parser/BUILD
server/build_event_protocol/event_parser/event_parser.go
server/build_event_protocol/event_parser/event_parser_test.go

The high level approach in this PR is to remove all calls to `fillInvocationFromEvents()`, since it reads all the invocation protos from blobstore. The reason we call `fillInvocationFromEvents` in the first place is to determine the values of certain Invocation table fields before we update invocation rows in the DB (when flushing post-workspace-status, and in FinalizeInvocation). Instead of reading the full list of events, we can just accumulate the necessary DB fields in memory throughout the invocation.
---
More details:
`fillInvocationFromEvents()` was calling `StreamingEventParser.ParseEvent()` for each build event, which has some important business logic that we want to preserve; namely populating certain invocation proto fields based on the events before we write those fields to …

Remove blobstore reads from BES handler

---

server/util/bazel_request/BUILD
server/util/bazel_request/bazel_request.go
server/util/bazel_request/bazel_request_test.go

This should save ~1-3% on app CPU based on current profiling data, and also save ~0.9KB worth of allocations per request.
```
BenchmarkGetInvocationID-8              10000000               964.0 ns/op          1184 B/op         14 allocs/op
BenchmarkFastGetInvocationID-8          10000000               128.4 ns/op           320 B/op          3 allocs/op
```
---

Performance: Optimize `bazel_request.GetInvocationID`

---

enterprise/server/raft/store/store.go

If node usage has not reached the threshold, force an update to be sent after 15 minutes to make the usage information reasonably up to date across the cache nodes.
Other changes:
- Proactively refresh replica usages every 15 seconds instead of relying on periodic updates from replicas. This makes the usage information more accurate and there's no performance hit as replica Usage() is now a cheap operation.
- When evicting data locally, speculatively update usage for remote nodes assuming they are evicting at a similar rate to avoid evicting more data from nodes that are getting more write requests.
---

Gossip node partition usages when size delta is bigger than threshold.

---

server/build_event_protocol/accumulator/BUILD
server/build_event_protocol/accumulator/accumulator.go
server/build_event_protocol/build_event_handler/BUILD
server/build_event_protocol/build_event_handler/build_event_handler.go
server/build_event_protocol/event_parser/event_parser.go
server/build_event_protocol/event_parser/event_parser_test.go
server/build_event_protocol/target_tracker/BUILD
server/build_event_protocol/target_tracker/target_tracker_test.go

This PR serves as step 1 of consolidating StreamingEventParser and Accumulator (AKA BEValues), which now serve basically the same purpose but (confusingly) provide slightly different values for things like RepoURL etc.
The remaining plan after this PR is the following:
- Replace all Accumulator methods (e.g. `RepoURL()`) with equivalent calls to invocation field getters (`acc.Invocation().GetRepoUrl()`) (We need to be careful about this part, since RepoURL() in particular has some normalization logic involved, and `BEValues` assigns different "priorities" to events than `parser` does)
- Get rid of StreamingEventParser and move all of its logic into `accumulator.go`
- (Maybe?) Rename `BEValues` to `accumulator` and replace `accumulator.NewBEValues()` with `accumulator.New()`
---
**Version …

Refactor: Move EventParser into accumulator

---

enterprise/server/backends/redis_execution_collector/BUILD
enterprise/server/backends/redis_execution_collector/redis_execution_collector.go
enterprise/server/remote_execution/execution_server/execution_server.go
server/build_event_protocol/build_event_handler/build_event_handler.go

The CommandBuffer flushes every 250 ms by default. This can cause an
issue where execution server appends the execution is reids, but when build event
handler tries to fetch the executions from redis, the execution was still in the
buffer and not in redis.
Also, added some logging to help debugging.

remove CommandBuffer in execution collector

---

enterprise/server/raft/store/store.go
server/metrics/metrics.go
server/util/approxlru/approxlru.go
server/util/approxlru/approxlru_test.go

I updated the sampling key to remove extranerous information, mainly to avoid confusion between the atime timestamp in the sample key and the atime maintained by the LRU. Now the full sample is passed on eviction to access the atime in the LRU.
---

Add Raft metric for evicted item age.

---

enterprise/server/backends/migration_cache/migration_cache.go

Don't log on EOF errors when reading chunks, because the readers from different caches could be reading at different rates. Only log on Close() if the total number of bytes read differs

Don't log on EOF errors when reading chunks in migration cache

---

enterprise/server/backends/migration_cache/migration_cache.go

Don't log on byte differences for AC records, because there could be minor differences in metadata like timestamps

In migration, only log read byte differences for cas records

---

server/build_event_protocol/event_parser/BUILD
server/build_event_protocol/event_parser/event_parser.go
server/build_event_protocol/event_parser/event_parser_test.go

This fixes an issue that the logging added in https://github.com/buildbuddy-io/buildbuddy/pull/3123 is noisy, due to repo URLs mismatching between `Accumulator` and `EventParser`, even though the normalized values are the same.
The non-normalized URLs are never used directly (*), so we should only be comparing the normalized URLs when logging whether there is a mismatch.
It is also generally more sane to normalize the repo URL as soon as we can, to avoid possible bugs involving non-normalized repo URLs.
(*) Except when serving back to the UI for the invocation page, in the `GetInvocation` response. The UI does its own normalization though, so the approach in this PR of normalizing server-side before serving back to the UI should functionally be a NOP.
---

Normalize repo URL for in-memory invocation proto

---

server/build_event_protocol/accumulator/accumulator.go
server/build_event_protocol/build_event_handler/build_event_handler.go
server/build_event_protocol/build_status_reporter/build_status_reporter.go
server/build_event_protocol/event_parser/event_parser.go
server/build_event_protocol/target_tracker/target_tracker.go
server/build_event_protocol/target_tracker/target_tracker_test.go

This PR aims to remove some methods from the `Accumulator` interface. It should be a NOP -- for any methods where the accumulator and EventParser would return different values, I left those in tact (but I still plan to consolidate those in a later PR).
- Remove `BuildExitCode()` and set the `BuildExitCode` on the invocation instead when handling the `Finished` event.
- Remove `InvocationID()` and update callers to use `Invocation().GetInvocationId()` instead.
- Remove `Command()` and update callers to use `Invocation().GetCommand()` instead.
- Remove `BranchName()` which was unused.
- Reorganize methods so it's clearer which fields we are trying to remove as the end goal of the refactoring.
---

Refactor: Trim Accumulator interface

---

enterprise/server/auth/auth.go

`lru.Get` mutates the LRU.
---

Use a regular mutex for APIKeyGroupCache

---

enterprise/server/backends/pebble_cache/pebble_cache.go

Don't log anything if the metadata key is already gone. There's a race between the scanner and the evictor.
---

Silence scanBrokenFiles noise.

---

tools/probers/bazelrbe/bazelrbe.go

When set, this option creates and builds the probed target under '//name' instead of '//' which should make it easier to idenfy prober invocations. When the option is unset, the default behavior is the same as today.
**Related issues**: Unblocks https://github.com/buildbuddy-io/buildbuddy-internal/issues/1905

Support --prober_name in bazelrbe

---

enterprise/server/auth/auth.go

JWT parsing overhead is still around 6-7% in prod, even after https://github.com/buildbuddy-io/buildbuddy/pull/3106. This should reduce that overhead by a factor of ~100.
```
BenchmarkParseJWT_Current-8       146936             16517 ns/op            4440 B/op         61 allocs/op
BenchmarkParseJWT_Cache-8       11399373               105.3 ns/op            16 B/op          1 allocs/op
```
---

Performance: Further reduce JWT parsing overhead

---

server/build_event_protocol/accumulator/accumulator.go

This is part of the refactor to consolidate `Accumulator` and `EventParser`. Before fully consolidating those two, we need to resolve any discrepancies in the way that they compute invocation fields. This PR _partially_ resolves a discrepancy in the computation of the `role` field.
For some invocations, the env var `CI` is set to an empty string. With the current logic, the `Accumulator` sees this and sets `ROLE=CI`, but `EventParser` does not.
Since `Accumulator` is used for commit status reporting and target tracking, this means commit statuses _may_ be reported and targets _may_ be tracked, since both of those require `ROLE=CI`. But since `EventParser` is used for DB columns, this means the invocation will show in the UI as a non-CI invocation.
The change in this PR attempts to resolve …

Don't assume CI role if CI env var is empty

---

enterprise/app/tap/tap.tsx

If a `GetTarget` RPC takes a long time, then switching between repos on the TAP page can result in erratic behavior, due to improper handling of in-flight RPCs. This PR fixes that.
---

TAP: Cancel in-flight RPCs

---

app/auth/user.ts
enterprise/app/group_search/BUILD
enterprise/app/group_search/group_search.tsx
enterprise/app/root/BUILD.bazel
enterprise/app/root/root.tsx
enterprise/app/sidebar/sidebar.css
enterprise/app/sidebar/sidebar.tsx

This allows impersonating a group directly (by group ID or slug), rather than needing an invocation ID (which is often inconvenient).
https://user-images.githubusercontent.com/2414826/210277974-d76a5494-e792-49d6-900b-bce15c143603.mp4
---

Add direct group navigation (admin-only)

---

deps.bzl
server/util/bazel/BUILD

I thiiiiink this will make them available to call from the probers.
**Related issues**: Unblocks https://github.com/buildbuddy-io/buildbuddy-internal/issues/1904

Add bazel-5.3.2 and bazel-6.0.0 to //server/util/bazel:bazel_binaries_tar

---

server/remote_cache/digest/BUILD
server/remote_cache/digest/digest.go
server/remote_cache/digest/digest_test.go
tools/cacheload/cacheload.go

- Allow passing `--read_compressed` or `--write_compressed` to compress reads/writes, respectively.
- Update random digest generator so that it generates blobs that are approximately 70% compressible.
---

cacheload: Support compressed reads/writes

---

tools/cacheload/cacheload.go

The existing flag defaults to -1 (meaning "use realistic blob sizes") so that we can support 0 as a valid value, but the impl doesn't handle 0 properly. This PR fixes that.
Ran into this bug while trying to use `--blob_size=0` to measure the maximum possible read QPS independent of disk I/O, since the bytestream server handles 0 as a special case and returns immediately.
---

cacheload: Fix logic for `--blob_size=0`

---

enterprise/server/backends/migration_cache/migration_cache.go
server/metrics/metrics.go

* Split up metrics for double read matches and mismatches (Fixes buildbuddy-io/buildbuddy-internal#1891)
* Add match metrics for more methods
* Remove logging if destination cache has data that source cache does not. The caches evict data independently, so this is expected if the source cache has a shorter TTL

Clean up migration not found metrics

---

enterprise/server/backends/pebble_cache/pebble_cache.go
server/metrics/metrics.go

It's like a last evicted gauge, but better.
---

Add histogram metric for item eviction age.

---

enterprise/server/remote_execution/execution_server/execution_server.go

We still want to record cancelled executions in clickhouse.
Also, add execution id in logging message b/c we didn't enrich context for
PublishOperation.

Use background context to record executions

---

enterprise/server/backends/pebble_cache/pebble_cache.go
enterprise/server/raft/store/store.go
server/metrics/metrics.go

Unfortunately Grafana heatmaps don't display units nicely if they're in microseconds, only in milliseconds.
When the values are large, Grafana displays them in seconds instead of more friendlier units like hours, days, or weeks. This is not a problem for other metrics that don't typically contain such large durations. 
---

Use milliseconds for eviction age histogram.

---

server/util/redact/BUILD
server/util/redact/redact.go
server/util/redact/redact_test.go

(Credit to @vadimberezniker for suggesting this optimization)
Instead of Marshaling/Unmarshaling each build event to redact API keys, redact by traversing the object structure with reflection and redacting any strings encountered. This should save about 1% of total CPU usage in prod.
For a stream of 1800 build events (`bb build //...` in the buildbuddy repo), saves 600K allocations totaling 44MB, and has 20X lower CPU overhead.
```
BenchmarkRedact_MarshalUnmarshal-8            16          69822699 ns/op        44800414 B/op     603938 allocs/op
BenchmarkRedact_Reflect-8                    357           3166731 ns/op             784 B/op         31 allocs/op
```
---

Performance: Optimize API key redaction

---

server/util/disk/disk.go

When `length > 0`, we make a `stat` syscall and discard the result. This PR removes the unnecessary `stat`.
---

Performance: Remove unused syscall in disk.FileReader

---

tools/metrics/grafana/dashboards/buildbuddy.json

I added a new per-partition row which now displays per-partition gaphs like eviction age and capacity.
---

Add eviction age histogram.

---

app/root/root.css
app/service/rpc_service.ts
app/target/BUILD
app/target/target.tsx
app/target/target_artifacts_card.tsx
enterprise/server/api/api_server.go
proto/BUILD
proto/buildbuddy_service.proto
proto/config.proto
proto/zip.proto
server/buildbuddy_server/BUILD
server/buildbuddy_server/buildbuddy_server.go
server/bytestream/BUILD
server/bytestream/bytestream.go
server/role_filter/role_filter.go
server/static/static.go
server/util/ziputil/BUILD
server/util/ziputil/ziputil.go

This addresses the error from #3153 where, for very large zip outputs with lots of files, we were panicking due to a negative index in the read files.
This also wraps everything in a flag (used from the client).

Allow downloading single file in zipped test outputs, behind a flag. (Revert 3153 revert 3101 split shard artifacts)

---

enterprise/app/trends/trends.tsx
enterprise/app/trends/trends_chart.tsx

i don't even necessarily know that i want to keep this chart around instead of having 50/75/90 percentile lines, but for now this seems better than what we've got.
the interfaces for mucking with the URL definitely need some love, but figured i'd do this first.

Sort the 'longest build' trend bar's landing page by build duration.

---

app/invocation/invocation_model.tsx

When buildToollogs event is missing, we currently display 0s. This PR
fallbacks to invocation.duration_usec.
Fixes https://github.com/buildbuddy-io/buildbuddy-internal/issues/1780

Fallback to invocation.duration_usec

---

server/bytestream/BUILD
server/bytestream/bytestream.go
server/bytestream/bytestream_test.go
server/util/ziputil/ziputil.go

As commented in the code, this validation isn't actually performed in the golang zip utils--it's something i wrote myself, and it turns out trying to perform it actually makes your life harder because it's sometimes not present.

add a test for zip file downloads and drop a bit of validation.

---

enterprise/server/workflow/service/service.go
enterprise/server/workflow/service/service_test.go
server/testutil/testgit/testgit.go

The client handles missing webhook permissions gracefully by showing a dialog with the webhook URL, asking the user to register it with the git provider manually (based on `registered_webhook: false` being set in the response). However, the server side logic for populating this field was broken at some point. This PR fixes it.
---

Workflows: Gracefully handle webhook registration failures

---

enterprise/server/backends/migration_cache/migration_cache.go

Fixes buildbuddy-io/buildbuddy-internal#1912

Reduce allocations for migration double reads

---

server/remote_cache/byte_stream_server/byte_stream_server.go
server/remote_cache/content_addressable_storage_server/content_addressable_storage_server.go
server/remote_cache/hit_tracker/hit_tracker.go
server/remote_cache/hit_tracker/hit_tracker_test.go
server/util/compression/compression.go

Before, we always read/wrote decompressed bytes from the cache, so we could use the digest size as the number of bytes uploaded/downloaded from the cache. Now that the cache can read/write decompressed bytes, we need to modify the metric to use the actual number of bytes transferred.

Take compression into account for cache upload/download byte metrics

---

website/blog/welcoming-son-luong-ngoc.md

A friend of mine said he was confused when clicking on the blog post author would show my profile page instead. Let's fix that.
---

blog: update correct author's url

---

enterprise/server/remote_execution/containers/firecracker/firecracker.go

This makes the `TestFirecrackerRunNOPWithZeroDisk` test pass (`bazel test --config=cache-dev //enterprise/server/remote_execution/containers/firecracker:firecracker_test --test_filter=TestFirecrackerRunNOPWithZeroDisk`) -- it is currently failing. I played around with it a bit and it looks like it only needs about 80KB-90KB more, but I figured we could give it a little bit of headroom.

Expand Firecracker scratchfs size from 30MB to 32MB

---

BUILD
app/components/button/BUILD
app/components/checkbox/BUILD
app/components/dialog/BUILD
app/components/filter_input/BUILD
app/components/input/BUILD
app/components/menu/BUILD
app/components/modal/BUILD
app/components/popup/BUILD
app/components/radio/BUILD
app/components/select/BUILD
app/components/slider/BUILD
app/components/spinner/BUILD
app/components/tooltip/BUILD
app/errors/BUILD
app/favicon/BUILD.bazel
app/footer/BUILD
app/preferences/BUILD
app/service/BUILD.bazel
app/util/BUILD
enterprise/app/group_search/BUILD
enterprise/app/sidebar/BUILD
rules/typescript/index.bzl
tsconfig_strict.json

I know that you both said you don't think we should do this but I took a closer look and:
1. There are a bunch of errors, like 100+ across 40+ files based on my sample and while most of them are straightforward, there are some that are kind of involved. So, it'll probably take a while to write, test, and deploy fixes for the entire repo.
2. This makes it easier to tackle bit by bit because at least you know which package you're working on.
3. This doesn't seem that bad to me?
Curious to hear what both of you think, though.
**Related issues**: Unblocks https://github.com/buildbuddy-io/buildbuddy-internal/issues/936

Add a 'strict' option to ts_library that runs TypeScript type checking in strict mode.

---

enterprise/server/cmd/ci_runner/main.go
enterprise/server/workflow/config/config.go

This can be used e.g. to set `USE_BAZEL_VERSION` to allow conveniently testing multiple bazel versions.
---
**Related issues**: Fixes https://github.com/buildbuddy-io/buildbuddy-internal/issues/1935

Workflows: Support setting static env vars in config

---

enterprise/server/backends/userdb/userdb.go
enterprise/server/backends/userdb/userdb_test.go

Bug:
1. User US1 with email `@foo.com` requests access to a group GR1
2. An admin of GR1 (US2) then switches on "Automatically add anyone with an **@foo.com** email to this group"
3. User US1 attempts to join the group again, but they get the error "You're already in this organization."
This error message is incorrect because they're not actually in the organization yet. They just have a membership request, which has not been approved.
The expected behavior is that the join attempt in step 3 should automatically succeed, since GR1 has set `@foo.com` as their owned domain, and US1 has an `@foo.com` email.
In a future PR, we might consider changing this behavior so that Step (2) results in the membership request in step (1) being accepted automatically. But I figure this might be a bit too …

Fix AddUserToGroup logic when user previously requested access

---

cli/example_plugins/go-highlight/handle_bazel_output.py

Also reformat the errors so that they're Ctrl+Clickable in VSCode. In VSCode you can Ctrl+Click things like `enterprise/app/root/root.tsx:100:50: some error` and it will jump to that exact code location. Ctrl+Click does not work when it's formatted w/ parens, like `enterprise/app/root/root.tsx(100,50): some error`.
---

CLI: Have the highlight plugin handle TypeScript errors too.

---

docs/cli.md
website/src/pages/cli.tsx

Bumping to 5.0.0 to skirt around an issue that Bazelisk refuses to download the arm64 version of `bb` on M1 Macs, because Bazelisk has some hard-coded logic that arm64 releases of "bazel" are only available starting with 4.1.0.
---

CLI: bump version in docs to 5.0.0

---

enterprise/server/backends/pebble_cache/pebble_cache.go

Our estimated cache size is larger than the actual disk usage numbers, meaning we aren't utilizing the full availability of our allocated disk space. A hypothesis is that the actual size on our disks is smaller because Pebble compresses the data that we inline, so it's smaller than we expect. Before we had added checks to not double compress data. To more accurately get the size that's actually written, we want to compress all data, because then it will approximate the compressed size that Pebble is writing to disk, even if this means that inlined data will be compressed again by Pebble.

Remove restrictions on double compressing inlined data in pebble

---

enterprise/server/backends/migration_cache/config.go
enterprise/server/backends/migration_cache/migration_cache.go
enterprise/server/backends/migration_cache/migration_cache_test.go
enterprise/server/backends/pebble_cache/pebble_cache.go
enterprise/server/backends/pebble_cache/pebble_cache_test.go

Now that we've validated that zstd compression is stable, we can remove this flag

Cleanup EnableZstdCompression flag

---

enterprise/server/raft/filestore/BUILD
enterprise/server/raft/filestore/filestore.go
enterprise/server/raft/filestore/filestore_test.go

Principles of Migration:
- you must always be able to read and write multiple versions of the data
- this ensures the DB is "rollback-safe"
- first ship a code change that speaks the new version, then, once you're sure it won't be rolled back, flip the flag to change current-version
- switch to the new version then once everything is migrated, bump db version so multi-version reads are no longer necessary
A **PebbleKey** is version agnostic -- it can be read or written at any version
- this is enforced by unit tests that read and write keys at all versions from min-to-max and ensure they are compatible
A **Migrator** is responsible for reading keys *and values* at one version and writing them at another
- this allows us to upgrade values if we desire
When you write a new key to the DB, …

Add PebbleKey with versions

---

.bazelrc
WORKSPACE
dockerfiles/rbe-ubuntu20-04-webtest/Dockerfile
dockerfiles/rbe-ubuntu20-04/Dockerfile
enterprise/deployment/BUILD
enterprise/server/test/integration/ci_runner/BUILD
enterprise/server/test/integration/workflow/BUILD
rules/webdriver/index.bzl

Adds an Ubuntu 20.04-based Dockerfile image as well as a webtest variant (needed for webdriver testing).
Software versions compared to the 16.04 image are listed here: https://github.com/buildbuddy-io/buildbuddy-toolchain/pull/7/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R57
The rbe-ubuntu20-04 image is roughly the same size as the current default execution image (~800 MB compressed, ~2.5GB uncompressed). This is mainly thanks to Google's minimal Clang/LLVM build for Ubuntu 20.04 which was published here: https://storage.googleapis.com/clang-builds-stable
Toolchain PR is here: https://github.com/buildbuddy-io/buildbuddy-toolchain/pull/7
This PR updates the BB repo to use the new Ubuntu 20.04 platform/toolchain added in that PR.
--- …

Add Ubuntu 20.04 execution image

---

WORKSPACE
enterprise/dockerfiles/rbe-ubuntu20-04-workflows/Dockerfile
enterprise/server/deployment/BUILD

Note, unlike the 18.04-based image, this image does not have a step that installs `build-essential`, `git 2.38.1` (from ppa), and `python3.6-dev`, because:
- `build-essential` is already installed in the new rbe-ubuntu20-04 image
- The `git` version in the rbe-ubuntu20-04 base image is sufficiently high for `git clone --filter=blob:none --no-checkout` to work (`git 2.25.1`). The version in the ppa (and in the current CI runner image) is 2.38.1, so we're downgrading the git version relative to the 18.04 image, but I figure it's worth the downgrade since we're reducing the complexity of the image. If people need a newer version for whatever reason, we can either upgrade the image later, or tell people they can use a custom image which installs git from the ppa.
- We install `python3-dev` in …

Add Ubuntu 20.04 workflows image

---

enterprise/app/trends/percentile_chart.tsx

I'll be using this on some charts for build times.
There isn't a concrete click handler for lines that provides the "closest" point, so I had to improvise a bit: this just uses the last date / x-axis value that we showed a tooltip for.  Since the percentile chart *always* shows a tooltip on hover, this seems alright to me--the user's click action will match the date that recharts thought they were hovering on.

Allow clicking on percentile charts

---

server/metrics/metrics.go
server/remote_cache/action_cache_server/action_cache_server.go
server/remote_cache/byte_stream_server/byte_stream_server.go
server/remote_cache/content_addressable_storage_server/content_addressable_storage_server.go
server/remote_cache/hit_tracker/hit_tracker.go
server/remote_cache/hit_tracker/hit_tracker_test.go

In prod, the number of bytes downloaded/uploaded from the cache don't seem to have gone down after turning on compression in the executors. Add additional metrics to look into this more and a server label to help break down where our cache requests are originating from. Also start emitting cache metrics from the action cache server.

Add metrics for bytes sent to/from server and for ac_server

---

enterprise/server/hostedrunner/hostedrunner.go
enterprise/server/remote_execution/platform/platform.go
enterprise/server/remote_execution/runner/BUILD
enterprise/server/remote_execution/runner/runner.go
enterprise/server/workflow/service/service.go

- Add the Ubuntu 20.04 RBE image and Ubuntu 20.04 CI image to the set of images to be warmed up.
- Move the workflow image warmup behind a flag, so that we don't have to warm up as many Firecracker images during scale up of the "normal" (non-workflow) executor pool. (I plan to enable this new flag only for the workflow executors)
---

Executor: Warm up new Ubuntu 20.04 images

---

enterprise/server/cmd/ci_runner/main.go
enterprise/server/workflow/config/config.go
enterprise/server/workflow/service/service.go
proto/build_event_stream.proto

- Add a `container_image` setting to workflow actions, which maps to the "container-image" platform prop and works mostly the same way as regular RBE actions.
- Let people use `ubuntu-18.04` / `ubuntu-20.04` as aliases for our Ubuntu workflow images, similar to GitHub actions' `runs-on` prop.
- Send up the `container_image` value in the `WorkflowConfigured` event so that we can show deprecation/migration warnings in the UI if needed (for example, if it's blank, we can encourage people to upgrade from the default 18.04 image to 20.04). Also set `OS` and `Arch` since the UI needs to know whether the OS is Linux to decide whether to show any warnings about `container_image`, and arch is just extra "nice to have" info which we can show in the invocation details bar just like we do for regular …

Workflows: Make container image configurable

---

buildbuddy.yaml
enterprise/server/workflow/config/test_data/basic.yaml

Also add a test case to make sure we can parse the config successfully even though the `container_image` prop is not yet recognized in prod. (Also note that the "Test" workflow in this PR is able to run even though `container_image` hasn't reached prod yet)
Verified using the workflow task ID that the `container-image` platform prop is set correctly:
```
{
"name":  "container-image",
"value":  "docker://gcr.io/flame-public/rbe-ubuntu20-04-workflows@sha256:e74147369e5ff5c6c9d56f15ab10a894d54d4f45f14455ad418f70ddb59850e3"
},
```
---

Use new Ubuntu 20.04 image for workflows

---

enterprise/app/trends/percentile_chart.tsx
enterprise/app/trends/trends.tsx

rename "onRowClicked" to "onColumnClicked", too, because that's what it actually is.  Oops.

add click behavior to duration percentile chart (clicking will show the slowest builds).

---

server/backends/blobstore/blobstore.go

This should fix the issue with chunked logs on AWS.
---

Don't return an error if an AWS blob is NotFound in the BlobExists method

---

enterprise/server/selfauth/selfauth.go

We want our webdriver tests to self-auth because google oauth has bot-prevention measures. Remove this check so that the self-auth handlers are always registered. Self-auth will still only be automatically added as an oauth provider if the flag is on. Only organization slugs that have explicitly added self-auth as an auth provider in the config will be able to use it.

Remove flag to register self-auth handlers

---

server/remote_cache/byte_stream_server/byte_stream_server.go

These numbers looked way too small to me: I was seeing 37usec read times but our prom metrics show a p50 of a ms or so. 
I think we're omitting some of the read time by creating the download tracker after calling Reader(). This change moves download tracker creation to before that call so the numbers are correct.

Include cache.Reader() call time in CAS download time

---

enterprise/dockerfiles/ci_runner_image/Dockerfile
enterprise/dockerfiles/rbe-ubuntu20-04-workflows/Dockerfile
enterprise/server/remote_execution/platform/platform.go

This is needed for rules_hermetic_python which needs to be run as a non-root user, but then sudo may be needed for certain other things (like installing dependencies with apt-get)
(If this is approved, then I will push the CI images and update the image digests in `platforms.go` before submitting.)
---

Workflows: Allow sudo for non-root users

---

server/remote_cache/byte_stream_server/byte_stream_server.go

When encountering a bad magic number we were continuing forever attempting to read which lead to the client hanging. By catching all non-nil errors here we avoid this.

Catch non-specific errors too

---

enterprise/server/backends/distributed/distributed_test.go
server/bytestream/bytestream.go
server/util/grpc_client/grpc_client.go
tools/cacheload/cacheload.go
tools/rbeperf/rbeperf.go

This PR fixes a long-standing bug that action results are not showing up in the UI for invocations that use `--remote_executor=europe.remote.buildbuddy.io`, even though the results are present in AC (as they can be fetched using `tools/cas`).
The root cause turned out to be that we were calling `DialTargetWithOptions` with the URL `actioncache://europe.remote.buildbuddy.io`, and `DialTargetWithOptions` parses that URL to the target+options `("europe.remote.buildbuddy.io", grpc.WithInsecure())`. The request fails with the error "connection closed before server preface received" because the `europe.remote.buildbuddy.io` target requires TLS.
This bug does not reproduce in the US because we first attempt to download the file from `localhost` before we attempt to download using the gRPC target …

Fix action results not showing in UI for EU invocations

---

app/invocation/invocation_breakdown_card.tsx

When a profile is generated from `bazel query` or `bazel cquery`, it would contains no executionData and thus, causes a crash in rendering "Timing" tab on the Invocation page.
Fix it by skipping the Breakdown section when the data is empty.
---

invocation: avoid crash when render query profiles

---

server/util/rlimit/rlimit.go

Inspired by https://github.com/buildbuddy-io/buildbuddy/issues/3269
---

Don't change open file limit if current limit is already larger than the target

---

.github/workflows/deps.yaml

Username could contain spaces in the middle and without quotes, git-config would not be able to parse it and throw error with exit code 129.
Fix by adding quotes between the Github Action expressions.
---

github action: ensure git user name and email are in quotes

---

enterprise/server/cmd/goinit/main.go
enterprise/server/remote_execution/containers/firecracker/BUILD
enterprise/server/remote_execution/containers/firecracker/firecracker_test.go
enterprise/server/vmexec/BUILD
enterprise/server/vmexec/vmexec.go
enterprise/server/vmexec/vmexec_test.go
proto/remote_execution.proto

Monitor peak disk usage (for scratch and workspace disks separately) throughout VM action execution and report in ExecutedActionMetadata.
This will let us (and users) confirm whether certain errors are due to the VM running out of disk space.
---

Firecracker: Monitor peak FS usage

---

app/invocation/invocation_action_card.tsx

Currently only works for regular firecracker actions, not workflows. (Some extra work is needed to properly display the CI runner action in the UI)
Screenshot:
---
---

Show peak VM disk usage in UI

---

app/BUILD.bazel
app/alert/alert.css
app/alert/alert.tsx
app/components/banner/BUILD
app/components/banner/banner.css
app/components/banner/banner.tsx
enterprise/app/executors/BUILD
enterprise/app/executors/executors.css
enterprise/app/executors/executors.tsx
enterprise/app/org/BUILD
enterprise/app/org/create_org.tsx
enterprise/app/org/org.css
enterprise/app/org/org_form.tsx

We have a bunch of these components which have an icon on the left-hand side, rounded corners, and light background color:
This next one doesn't have an icon, but an info-level note would make sense here:
Extracting a `Banner` component so we can reuse these more easily and make them more consistent.
---

Add `Banner` component

---

enterprise/server/cmd/goinit/main.go
enterprise/server/remote_execution/containers/firecracker/BUILD
enterprise/server/remote_execution/containers/firecracker/firecracker_test.go
enterprise/server/vmexec/BUILD
enterprise/server/vmexec/vmexec.go
enterprise/server/vmexec/vmexec_test.go

This PR causes actions to crash due to `syscall.Symlink` failing if `/etc/mtab` already exists.
I'm not sure why it doesn't reproduce in `firecracker_test`, but does reproduce when running actions. Need more time to understand the issue. Reverting for now to unblock the release.
---

Revert #3272: Firecracker: Monitor peak FS usage

---

server/tables/tables.go

This just adds the org-level preference for enabling/disabling user-level keys.
As for the `APIKeys` table, turns out that it already has a `user_id` column, which is always empty. Also, we always set `perms = GROUP_READ|GROUP_WRITE`. So, we can introduce user-level keys without needing a migration! :four_leaf_clover: We just have to populate `user_id` with the authenticated user ID (for user-level keys only) and set `perms = OWNER_READ|OWNER_WRITE`.
---

Update DB schema for user-level API keys

---

enterprise/server/util/container/BUILD
enterprise/server/util/container/container.go

This is mostly experimental -- if we don't see a lot of successful de-dupes logged in practice, we can revert this code.
---
**Related issues**: Fixes https://github.com/buildbuddy-io/buildbuddy-internal/issues/1906

Dedupe firecracker disk image conversion

---

app/invocation/invocation.tsx
app/invocation/invocation_build_logs_card.tsx
app/service/rpc_service.ts
app/terminal/terminal.tsx
server/backends/chunkstore/chunkstore.go
server/buildbuddy_server/BUILD
server/buildbuddy_server/buildbuddy_server.go

Logs were being loaded into memory on both the client and the server, which would be a problem
for very large logs. Instead, we now stream the logs from the blobstore chunks on the server
side and download the stream to disk on the client side.
---

Stream logs instead of loading entire logs into memory

---

enterprise/server/backends/pebble_cache/BUILD
enterprise/server/backends/pebble_cache/pebble_cache.go

Adds per-filemetadatakey locking around pebble DB reads and writes.
I started to add the version changes as well (and locking on digest) but it quickly got out of hand, so this CL just adds simple locking to pebble cache. In a follow up I will start refactoring interfaces to pass around PebbleKeys and eventually handle multiple versions / lock whole digests.
There is still an issue where we batch update atimes, and keys are not locked between the time when they are read and when they are updated. I think locking here would be problematic and merging would be better, but I'm open to ideas if you think otherwise!

Add simple locking to pebble cache

---

enterprise/server/backends/migration_cache/config.go
enterprise/server/backends/migration_cache/migration_cache.go
enterprise/server/backends/pebble_cache/pebble_cache.go
enterprise/server/backends/pebble_cache/pebble_cache_test.go

This simplifies the migration to versioned keys drastically. I don't think it should impact IO significantly because these are not synced writes.
(This also makes the pebble_cache tests finish significantly faster which is nice but a little surprising).

Don't batch atime updates; but don't sync them

---

enterprise/server/backends/pebble_cache/pebble_cache.go

This does not yet add version specific reads/writes -- just attempts to pass most data around as PebbleKeys instead of bare []byte slices.

Replace fileMetadataKey with filestore.PebbleKey in most function definitions

---

enterprise/server/backends/pebble_cache/pebble_cache.go
enterprise/server/raft/filestore/filestore.go
enterprise/server/util/pebbleutil/pebbleutil.go

This changes the pebble lock-key from a raw fileMetadataKey to a string containing:
AC: cache type, remote instance name, digest
CAS: cache type, digest

Add a LockID() string method to PebbleKey and use it

---

enterprise/server/cmd/goinit/main.go
enterprise/server/remote_execution/containers/firecracker/BUILD
enterprise/server/remote_execution/containers/firecracker/firecracker_test.go
enterprise/server/vmexec/BUILD
enterprise/server/vmexec/vmexec.go
enterprise/server/vmexec/vmexec_test.go

Fixes the "file exists" error caused by `/etc/mtab` already existing in some images.
The fix is in this commit: https://github.com/buildbuddy-io/buildbuddy/pull/3295/commits/5bee4595eb35e6250e91740427311c25542bb06b
---

Roll-forward #3272: Firecracker: Monitor peak FS usage

---

enterprise/server/raft/filestore/filestore.go
enterprise/server/raft/filestore/filestore_test.go

This moves the version to the end (as discussed) to ensure data at different versions is stored in such a way as to be adjacent (and likely in the same block). Also adds a test with exemplars of each key version.

Add version exemplars test and move version bit to end of bytes

---

server/util/clickhouse/BUILD
server/util/clickhouse/clickhouse.go
server/util/clickhouse/schema/BUILD
server/util/clickhouse/schema/schema.go
server/util/clickhouse/schema/schema_test.go

Move Table definition to its own package server/util/clickhouse/schema. This is to prevent a circular dependency in a subsequent PR. https://github.com/buildbuddy-io/buildbuddy/pull/3305

Refactor //server/util/clickhouse

---

app/auth/user.ts
app/docs/setup_code.tsx
enterprise/app/api_keys/api_keys.tsx
enterprise/app/org/edit_org.tsx
enterprise/app/org/org_form.tsx
enterprise/app/settings/settings.tsx
proto/config.proto
server/static/static.go

Setup changes:
* Add "(personal key)" label to the dropdown
* Don't show the API key value in the dropdown (since it was getting too long)
---
---
Org settings:
* Add checkbox to enable (code is commented out for now, until we're ready to launch).
* Unchecking the checkbox shows a warning banner indicating that the change will deactivate any existing keys.
---
---
Settings:
* Add tabs
* Render personal keys page
---
---
---

Implement UI for user-level API keys

---

server/metrics/metrics.go
server/util/log/BUILD
server/util/log/log.go

Adding these so that for automatic releases the metric detection script can query whether the canary has an abnormally high number of warning/error logs.

Add prometheus metrics for logs

---

enterprise/server/backends/authdb/BUILD
enterprise/server/backends/authdb/authdb.go
server/util/query_builder/query_builder_test.go

Move the common query parts to a single func since we'll be adding more fields onto this query and adding more WHERE clauses as part of user-owned API keys.
This should be a NOP.
---

Cleanup: Consolidate APIKeyGroup queries in authdb

---

cli/bazelisk/bazelisk.go
cli/plugin/plugin.go
cli/test/integration/cli/cli_test.go
cli/testutil/testcli/testcli.go

This is another fix for GOPACKAGESDRIVER, which runs `bazel info` and tries to parse the output. It's currently broken because https://github.com/buildbuddy-io/buildbuddy/pull/3312 caused all bazel output to go to stderr.
---

CLI: fix commands like `bb info | grep bazel-bin`

---

server/util/approxlru/approxlru.go

Store sample pool in reverse order and iterate backwards to avoid index out of range errors when mutating pool while iterating.

Fix possible panic in sample pool iteration

---

enterprise/app/tap/tap.tsx
proto/target.proto

Deprecate target.id. target_id=md5(repo_url, label). It was used
in mysql Target table as a primary key. But we don't need this key
in clickhouse.

use target label as the map key

---

enterprise/server/backends/userdb/userdb.go
enterprise/server/backends/userdb/userdb_test.go
server/buildbuddy_server/buildbuddy_server.go
server/interfaces/interfaces.go

Continuing to move more authorization logic into userdb and strengthen userdb_test in preparation for user-level API keys.
The goal is eventually to have buildbuddy_server just delegate directly to userdb, which is much better tested and runs its business logic inside transactions. This also feels like better separation of concerns, since currently the business logic (auth checks, precondition checks etc.) is sort of split between buildbuddy_server and userdb without much rhyme or reason.
- Instead of the `CreateGroup` RPC calling InsertOrUpdateGroup and then AddUserToGroup, do both of these in a single transaction in userDB, in a new `CreateGroup` method.
- Move the auth check for `UpdateGroup` RPC into `InsertOrUpdateGroup` RPC.
- Add explicit auth checks to `AddUserToGroup` instead of …

Move more user/group management logic into UserDB transactions

---

enterprise/server/test/webdriver/invocation/invocation_test.go

For prod and dev targets, the builds may have cached data from previous runs

Fix webdriver test

---

app/components/banner/banner.css
app/router/router.tsx
enterprise/app/settings/settings.tsx

Add a supported URL `/settings/cli-login` that redirects to `/settings/personal/api-keys` if user-owned keys are supported, else `/settings/org/api-keys`.
---

Add UI redirect for CLI login

---

cli/plugin/plugin.go

Failed consistently with `--runs_per_test=100` before; now it passes consistently.
---

CLI: De-flake integration test

---

enterprise/server/backends/pebble_cache/pebble_cache.go

The previous function, deleteRecord, did not correctly support both inlined and stored files.

Ensure Delete() handles both kinds of stored data

---

enterprise/server/backends/userdb/userdb.go

The fixes an issue where timing profiles aren't visible for shared invocations.
---

Don't lookup user if we don't need to

---

.bazelrc
deps.bzl
go.mod
go.sum
server/testutil/webtester/webtester.go

When running bazel tests with `--config=webdriver-debug`, tests will now spawn the GUI for chrome (instead of running in `--headless` mode), so you can see what the test is doing.
If the test fails, the browser window will stay open for 3s so you can see what state the app is in when the failure happened. This duration can be extended further so you can go in and check devtools etc., by setting `--test_arg=-webdriver_end_of_test_delay=1h` (this is super rudimentary for now; there is probably a better way to do this).
Also when running under this debug config, pass `--verbose` to chromedriver, so that if chrome crashes on startup, the root cause will be logged (by default, it logs a super opaque error just saying that chrome has crashed).
Tangentially related: this PR also updates the Go …

Allow visually debugging webdriver tests locally

---

enterprise/server/backends/userdb/userdb.go
server/buildbuddy_server/buildbuddy_server.go

Persist the setting when creating or updating a group, and return the setting back to the UI.
Has no effect yet, since `--app.user_owned_keys_enabled` is not set to `true` anywhere, and this determines whether we show the setting in the UI, and the API (as of this PR) does not support creating user-level keys yet.
---

Persist the user-owned keys setting

---

server/util/log/log.go

Previously I had only added the metrics on the logging struct, not on the general util function

Fix logging metrics

---

app/service/rpc_service.ts
enterprise/app/api_keys/api_keys.tsx
enterprise/app/settings/settings.tsx
enterprise/server/backends/userdb/userdb.go
proto/api_key.proto
proto/buildbuddy_service.proto
server/buildbuddy_server/buildbuddy_server.go
server/interfaces/interfaces.go
server/role_filter/role_filter.go

* Add separate RPCs (and stub impls) for user-level API keys. The Request/Response protos are exactly the same as the corresponding group-level RPCs.
* Remove `user_id` field that was added previously, since the user API keys API will always use the authenticated user ID.
* Add 2 new UserDB methods (and stub impls): GetUserAPIKeys and CreateUserAPIKey. These operations are scoped to the authenticated user ID.
* Keep Update/Delete DB methods the same, since those operate in API key ID scope, rather than user/group scope. We use generic `perms`/`role`-based auth for those, so the logic will be exactly the same for user-owned and group-owned keys.
* Add docs to all API keys methods of UserDB.
---

Refactor user-owned keys API with user-specific endpoints

---

enterprise/server/backends/pebble_cache/pebble_cache.go
proto/raft.proto

Adds a max database version, also tracked in metadata, in case we roll back the active version.

Support min, max, and active version for clarity and better rollback support

---

cli/cmd/bb/bb.go
cli/login/BUILD
cli/login/login.go
cli/storage/BUILD
cli/storage/storage.go

* Use the new `/settings/cli-login` route (which redirects to the user-level keys page if enabled, else org API keys) instead of `/settings/org/api-keys`
* Automatically open the URL in the browser
* Store the config in `.git/config`, under `buildbuddy.api-key`, so that the API key is repo-specific.
---

CLI: improve login command

---

cli/login/login.go

Note, this is not related to https://github.com/buildbuddy-io/buildbuddy-internal/issues/2022, just coincidental.
---

CLI: Fix empty args when API key is not found in `.git/config`

---

tools/dev_qa.sh

If the loadtest flag was not set, previously this script was returning exit code 1 incorrectly

Explicitly return exit code 0 in dev QA script

---

server/build_event_protocol/target_tracker/target_tracker.go

start_time_usec is not set when the test is timeout or cancelled.

remove logging when start_time_usec is not set

---

server/backends/github/github.go
server/build_event_protocol/build_status_reporter/build_status_reporter.go

This PR is intended to help diagnose an issue where we are failing to report some statuses to GitHub, leaving certain workflow checks in a "pending" state.
* Log a warning if we fail to marshal the status payload (should never happen).
* Log a warning if we fail to create an HTTP request (should never happen).
* If GitHub returns an HTTP error (status >= 400), the HTTP client `.Do()` func treats the request as successful. Explicitly check the status code and log a warning if GitHub doesn't return a success code for whatever reason.
---

Improve error handling for GitHub status reporter

---

enterprise/server/backends/pebble_cache/pebble_cache.go
enterprise/server/backends/pebble_cache/pebble_cache_test.go
enterprise/server/raft/filestore/filestore.go

Copying happens on startup, the cache will not serve traffic until the copy is done.
External files are hard linked. 
---

Add support for copying data between partitions.

---

enterprise/server/util/ext4/ext4.go

On recent versions of Ubuntu (22.04+ on my machine and Tyler's new machine) builds with firecracker remote execution fail with errors like this:
```
2023/02/14 19:37:16.727 ERR Error running "/sbin/mke2fs -L  -N 0 -O ^64bit -m 5 -r 1 -t ext4 /tmp/iain_remote_build/fc-container-3506787005/workspacefs.ext4 220K": exit status 1 mke2fs 1.46.5 (30-Dec-2021)
Creating regular file /tmp/iain_remote_build/fc-container-3506787005/workspacefs.ext4
/tmp/iain_remote_build/fc-container-3506787005/workspacefs.ext4: Not enough space to build proposed filesystem while setting up superblock
```
This is because the minimum disk size we provide for constructing an empty ext4 filesystem for the executor is too small to hold an empty filesystem. I'm guessing this minimum size increased with a newer version of …

Increase minimum ext4 fs size from 220k to 225k

---

terraform/aws/.gitignore
terraform/aws/.terraform.lock.hcl
terraform/aws/README.md
terraform/aws/alb.tf
terraform/aws/buildbuddy-values.yaml
terraform/aws/ebs.tf
terraform/aws/eks.tf
terraform/aws/helm.tf
terraform/aws/outputs.tf
terraform/aws/terraform.tf
terraform/aws/variables.tf
terraform/aws/vpc.tf

We want to experiement with deploying BuildBuddy helm chart on AWS.
Initial approach includes using Terraform with EKS module and Helm
provider to apply the BuildBuddy chart onto a newly provisioned EKS
cluster.
We use:
- AWS's EBS CSI driver to automatically provisioning EBS volumes for
k8s Persistent Volume Claims.
- AWS's LoadBalancer controller to automatically provision ALB/ELB for
k8s' Service and/or Ingress.
Future works:
- Swapping out components in the helm chart for AWS-native components:
- S3 for object storage
- Replace K8s MySQL with RDS
- Use AWS's ClickHouse DB
- Provide additonal examples:
- Setup authentication provider
- Deploy BuildBuddy Executor
- Configure distributed cache
---

terraform: start experimenting with AWS deployment

---

enterprise/server/backends/userdb/userdb.go
enterprise/server/backends/userdb/userdb_test.go

Check that userID and subID are both non-empty (these should be set by `Authenticator.FillUser`), and add tests.
---
**Related issues**: https://github.com/buildbuddy-io/buildbuddy-internal/issues/2053

Add more validation to InsertUser and add tests

---

cli/login/login.go

An empty API key header is considered invalid, so this causes invocation auth to fail.
---

CLI: don't set empty API key header if not logged in

---

server/build_event_protocol/build_event_handler/build_event_handler.go
server/build_event_protocol/build_status_reporter/build_status_reporter.go

* Add a log message when we successfully create an invocation in the DB
* Enriches the logging context with the attempt number
* Add a log when we successfully report a GitHub status, not just when we fail to report.
---

Add more logs to help understand invocation status reporting

---

server/util/authutil/authutil.go

Users should never have a group with an empty GroupID in their `GetGroupMemberships()` list, so `authutil.AuthorizeGroupRole` should always return "You do not have access to the requested organization" today if an empty GroupID is passed in.
This PR just makes the empty group ID case a bit more explicit, to give an even stronger guarantee that we always return an error if the group ID is empty.
---

Add explicit check for empty group ID

---

enterprise/server/backends/pebble_cache/BUILD
enterprise/server/backends/pebble_cache/pebble_cache.go

Once more with feeling!
Also fixed a small race condition that jim drew my attention to:
```
unlockFn := p.locker.RLock(key.LockID())
found, err := p.iterHasKey(iter, key)
if err != nil {
return nil, err
}
if !found {
missing = append(missing, r.GetDigest())
}
unlockFn()
```
in the error case above, RLock is never unlocked

Read keys at multiple versions

---

cli/printlog/BUILD
cli/printlog/printlog.go
deps.bzl
go.mod
go.sum

Update `bb print` and `protofile.go` to use the new `protodelim` package.
---

CLI: use protodelim instead of custom code

---

enterprise/server/auth/auth.go
enterprise/server/backends/authdb/authdb.go
enterprise/server/backends/authdb/authdb_test.go
server/interfaces/interfaces.go

* Fill `user_id` field in authenticated `APIKeyGroup`, so that we can tell internally whether a key is user-owned if desired.
* Fill the `user_owned_keys_enabled` field in the authenticated user's group roles.
* Disable authentication with user-owned keys when the setting is disabled via org settings.
Note, this is tested in userdb_test in https://github.com/buildbuddy-io/buildbuddy/pull/3280. The existing functionality for group-level keys is also tested in existing integration tests which use enterprise_testauth (remote_execution_test, workflow service test, etc.)
---

Auth support for user-level keys

---

cli/plugin/plugin.go
cli/plugins/go-deps/post_bazel.py

Without this change, someone who installed bb but not bazel
encounters error when use bb to fix dependencies.

use bb instead of bazel in post_bazel.py

---

server/util/query_builder/query_builder.go
server/util/query_builder/query_builder_test.go

This way, if people write code like `.AddWhereClause("a.b = ? OR c.d = ?")` and then later `.AddWhereClause("x.y = ?")`, the query will be correctly generated as `(a.b = ? OR c.d = ?) AND (x.y = ?)`
Also add a `normalize` func to help normalize whitespace (for test assertions only), since I was going crazy trying to check the differences in all the generated queries.
---

Make QueryBuilder auto-parenthesize WHERE clauses

---

release.py

Make release.py reject version overrides that don't start with 'v'

---

enterprise/server/remote_execution/container/BUILD
enterprise/server/remote_execution/container/container.go
enterprise/server/remote_execution/containers/podman/BUILD
enterprise/server/remote_execution/containers/podman/podman.go
enterprise/server/remote_execution/runner/BUILD
enterprise/server/remote_execution/runner/runner.go
enterprise/server/tasksize/BUILD
enterprise/server/tasksize/tasksize.go
enterprise/server/usage/BUILD
enterprise/server/usage/usage.go
server/util/authutil/authutil.go
server/util/capabilities/BUILD
server/util/capabilities/capabilities.go
server/util/perms/BUILD
server/util/perms/perms.go

Context: The `perms` package was originally intended to just be utils for dealing with `perms` bits, and I added a few unrelated funcs there a while back before I understood its original purpose and before `authutil` existed. This func was one of them :)
There are a few other misplaced funcs in here like `perms.AuthenticatedUser` -- will find better homes for those in future PRs.
---

refactor: Move IsAnonymousUserError to authutil

---

enterprise/app/history/history.tsx

Currently the links on commit history just take you to a github search for the commit sha - which gives you pretty lame results.
With this change - we'll link directly to the commit or branch if it's a github repo. Otherwise we won't show the button.
We can later expand this logic to support other providers.
---

Fix up commit & branch links

---

.bazelignore

Before this PR, if one were to run something like
```
echo 'invalid_star_lark()' > website/node_modules/BUILD
```
Then `bazel build //website/...` would be broken.
This may also apply to node_modules dependencies that may contain a
`build` file and user happen to be using a file system that is case
insensitive.
Add the remaining directories under "website" from the output of
```
git status --ignored
```
to `.bazelignore` to tell Bazel about it.
---

bazelignore: add more dirs under website

---

enterprise/server/backends/pebble_cache/pebble_cache.go

By the time CommitFn runs, the disk writer Commit function has already been called and has renamed the file causing us to delete the file we just wrote.
---

Fix "metadata mismatch" errors for duplicate non-inline CAS writes.

---

cli/parser/BUILD
cli/parser/parser.go
enterprise/server/backends/migration_cache/migration_cache_test.go
enterprise/server/backends/pebble_cache/pebble_cache_test.go
enterprise/server/composable_cache/composable_cache_test.go
enterprise/server/image_converter/image_converter.go
enterprise/server/remote_execution/dirtools/dirtools.go
enterprise/server/remote_execution/dirtools/dirtools_test.go
enterprise/server/util/cacheproxy/cacheproxy_test.go
enterprise/server/util/ext4/ext4_test.go
enterprise/server/workflow/service/service.go
server/backends/disk_cache/disk_cache_test.go
server/backends/memory_cache/memory_cache_test.go
server/remote_cache/byte_stream_server/byte_stream_server.go
server/remote_cache/byte_stream_server/byte_stream_server_test.go
server/remote_cache/cachetools/cachetools.go
server/remote_cache/capabilities_server/BUILD
server/remote_cache/capabilities_server/capabilities_server.go
server/remote_cache/content_addressable_storage_server/content_addressable_storage_server.go
server/remote_cache/content_addressable_storage_server/content_addressable_storage_server_test.go
server/remote_cache/digest/digest.go
server/remote_cache/digest/digest_test.go
server/test/integration/remote_asset/remote_asset_test.go
server/testutil/testdigest/testdigest.go

Support multiple digest functions in remote cache functionality.
N.B. This does not yet add support for multiple remote execution digest functions; that's dependent on https://github.com/bazelbuild/remote-apis/pull/236 being merged and support being added to Bazel (https://github.com/bazelbuild/bazel/pull/16791).

Add support for multiple digest functions

---

enterprise/server/remote_execution/containers/sandbox/BUILD
enterprise/server/remote_execution/containers/sandbox/sandbox_test.go

`config.RegisterAndParseFlags()` has been removed since #1938 so this
test has been failing to compile for quite some times.
```
enterprise/server/remote_execution/containers/sandbox/sandbox_test.go:41:9: undefined: config.RegisterAndParseFlags
enterprise/server/remote_execution/containers/sandbox/sandbox_test.go:77:9: undefined: config.RegisterAndParseFlags
```
`//server/config` is now auto initialized on startup so let's remote the
rootDirFlag check all together.
---

sandbox_test: fix broken test

---

enterprise/server/scheduling/scheduler_server/scheduler_server.go
enterprise/server/scheduling/task_leaser/BUILD
enterprise/server/scheduling/task_leaser/task_leaser.go
proto/BUILD
proto/scheduler.proto

Previously it was possible for a task to get stuck in limbo if the executor succesfully released the lease but was not able to contact the scheduler to re-enqueue the task.
---

Have executor request re-enqueue as part of closing the lease.

---

enterprise/server/remote_execution/runner/runner.go
enterprise/server/remote_execution/vmexec_client/vmexec_client.go

In https://github.com/buildbuddy-io/buildbuddy/pull/1611, `--debug_stream_command_outputs` was repurposed to start the VM in debug mode. Debug mode streams the VM logs to the terminal, but does not actually stream any output from the commands executed (I'm not sure if this was always the case or if it broke at some point).
This PR makes 2 changes:
* Now that we have stdout/stderr streaming (in `vmexec_client.go`), `--debug_stream_command_outputs` can actually stream the command stderr/stdout (which is the original intent of the flag).
* Instead of enabling debug mode whenever `--debug_stream_command_outputs` is enabled, this PR adds a separate flag `--executor.firecracker_debug_mode` to explicitly enable debug mode. The main reason for this change is that debug mode hijacks the TTY so …

Firecracker: improve `--debug_stream_command_outputs` behavior

---

enterprise/server/remote_execution/runner/runner.go

Also remove a misleading log ("Using docker for execution") -- this is printed once on startup if docker is enabled, but does not necessarily mean that docker will actually be used.
---

Add logging when creating/reusing runners

---

enterprise/server/cmd/ci_runner/main.go

`buildEventReporter` already copies all writes to `os.Stderr` since it wraps an `invocationLog` which sets up an stderr `MultiWriter` [here](https://cs.github.com/buildbuddy-io/buildbuddy/blob/90a109254b9a39a175b0712b17cb4b7ee626b231/enterprise/server/cmd/ci_runner/main.go#L666). So by setting up `ws.log` as `io.MultiWriter(os.Stderr, buildEventReporter)`, we are effectively duplicating the writes to stderr, resulting in confusing output. This PR fixes that.
---

Fix CI runner duplicate stderr logging

---

enterprise/app/trends/drilldown_page.tsx

When a bar chart only has one entry, it means the selected and unselected data always have the same value--either the user is filtering this field (e.g., user="jdhollen") or the field isn't set at all (e.g., no hostname on executions data).

Only show aggregation bar charts when there's more than one bar.

---

server/util/db/db.go
tools/gorm/print_schema_changes.sh

A previous version of this script printed the complete migration that would take place with a Gorm auto-migration. That's probably overkill for auto-releases, as we only need to detect if there's any change at all in order to stop an auto-release

Simplify db schema changes script

---

enterprise/server/backends/authdb/BUILD
enterprise/server/backends/authdb/authdb.go
enterprise/server/backends/authdb/authdb_test.go
enterprise/server/backends/userdb/userdb.go
enterprise/server/backends/userdb/userdb_test.go
enterprise/server/cmd/server/main.go
enterprise/server/testutil/enterprise_testenv/enterprise_testenv.go
server/buildbuddy_server/buildbuddy_server.go
server/interfaces/interfaces.go
server/static/static.go

The `app.enable_user_owned_keys` flag would previously only control whether the settings UI is enabled.
This PR makes it so that the flag controls whether the API is enabled, as well as whether user-owned keys can be used to authenticate.
---

Have user-owned keys flag control key auth and API

---

server/tables/tables.go

When running the script to detect schema changes, I noticed that the mysql db was always running `ALTER TABLE `Groups` MODIFY COLUMN `user_owned_keys_enabled` tinyint(1) NOT NULL DEFAULT false`. This is because it thought that the default value type was changing from false to 0 (triggering [this](https://github.com/go-gorm/gorm/blob/master/migrator/migrator.go#L510)).
The boolean is represented as a tiny-int, so false is stored as 0 anyway

Change default type from false -> 0

---

enterprise/app/api_keys/api_keys.tsx
enterprise/server/backends/userdb/userdb.go
enterprise/server/backends/userdb/userdb_test.go
enterprise/server/test/webdriver/invocation/invocation_test.go

When admins set Read+Write capabilities in the UI, we were silently ignoring these requested capabilities and writing CAS-only to the DB. This PR fixes that.
---

Respect user key capabilities set by admins

---

enterprise/app/api_keys/api_keys.tsx

Executor keys must have CACHE_WRITE_CAPABILITY, otherwise they cannot upload AC results. So make the executor key type a radio selection rather than a checkbox attribute, to ensure that CACHE_WRITE_CAPABILITY is always applied. Also simplify the code a bunch.
---

Make executor key type a radio selection instead of checkbox

---

enterprise/server/invocation_search_service/invocation_search_service.go
enterprise/server/invocation_stat_service/invocation_stat_service.go

planning to just handle flag-guarding client-side, let me know if you feel otherwise.

make invocation and trend services use pattern filter fields when specified

---

cli/fix/typescript/BUILD
cli/fix/typescript/typescript.go
deps.bzl
go.mod
go.sum

This is a little slower than using regexes, but much less error prone (won't pick up imports in strings).
Parse time for our repo goes from ~230ms with regex to about ~350ms.
Still using regexs to find dynamic imports for now since they have a less complex syntax, and finding them via tree-sitter takes about 500ms even with manual traversal.
---

CLI: Use tree-sitter for finding toplevel ts imports

---

enterprise/server/scheduling/task_router/task_router.go

This will prevent workflows from being stuck to a set of 3 executors (causing high queue times) and allow autoscaling to work more effectively.
---

Assign third workflow probe to random executor

---

enterprise/server/remote_execution/commandutil/BUILD

This test seems flaky on macos. If this doesn't help, we can disable it on macos entirely (preferably just the UsageStats-related stuff)
---

Mark commandutil_test flaky

---

enterprise/server/remote_execution/containers/firecracker/firecracker_test.go
enterprise/server/remote_execution/snaploader/snaploader.go

Fixes "Snapshot configuration already fetched with different digest"
---

Fix recycling failures on second recycling attempt

---

docs/config-auth.md

Gitlab is a viable OIDC identity provider. We have plenty of customers who prefer to use Gitlab during early evaluation.
Let's document our learning from helping recent customers using Gitlab as an authentication option for Gitlab.
---

doc: add Gitlab to config-auth

---

server/testutil/webtester/webtester.go

I've noticed the webdriver tests can be flaky with the release workflow, probably because the github runners don't have strong connections and the rpcs may be slow. It would be nice to be able to set the max duration the tests will wait to find an element on the page

Add ability to configure implicit wait timeout for webdriver tests

---

enterprise/server/backends/gcs_cache/gcs_cache.go
enterprise/server/backends/memcache/memcache.go
enterprise/server/backends/pebble_cache/pebble_cache.go
enterprise/server/backends/redis_cache/redis_cache.go
enterprise/server/backends/s3_cache/s3_cache.go
enterprise/server/raft/cache/cache.go
enterprise/server/remote_execution/dirtools/dirtools.go
proto/cache.proto
proto/remote_execution.proto
server/backends/disk_cache/disk_cache.go
server/backends/memory_cache/memory_cache.go
server/remote_cache/action_cache_server/action_cache_server.go
server/remote_cache/byte_stream_server/byte_stream_server.go
server/remote_cache/cachetools/cachetools.go
server/remote_cache/content_addressable_storage_server/BUILD
server/remote_cache/content_addressable_storage_server/content_addressable_storage_server.go
server/remote_cache/digest/digest.go

The refactoring continues!
- Add regex support for parsing digest_function from bytestream URIs
- Move TreeCache protos to cache.proto file and store ResourceNames instead of Digests
- Bump TreeCache seed (because stored data format is changing)
- Move IsEmpty() and Validate() to the ResourceName class because they are dependent on digest function

Move Validate/Empty functions to ResourceName class

---

enterprise/server/remote_execution/containers/firecracker/firecracker.go
enterprise/server/remote_execution/filecache/filecache.go
enterprise/server/remote_execution/snaploader/BUILD
enterprise/server/remote_execution/snaploader/snaploader.go
enterprise/server/remote_execution/snaploader/snaploader_test.go
server/interfaces/interfaces.go

Today, the following scenario can happen:
- Workflows A and B run, and we store snapshots A and B respectively once the workflow runs are complete.
- Workflow A then runs several times. Each run causes something like 20-40GB of files to be added to filecache, eventually causing snapshot B to get evicted.
- Workflow B attempts to run but its snapshot was evicted. So it has to be retried, and is assigned a cold runner.
(Note, there are many other scenarios where this can happen - "workflow A" can be replaced with any combination of workflows other than B, which collectively run enough times to cause hundreds of GB of filecache churn, enough to evict B)
The fix in this PR is to manually evict base snapshots from filecache (i.e. the snapshot from the previous run of the container) as soon as …

Firecracker: proactively evict old snapshots from filecache to reduce snapshot evictions

---

enterprise/server/remote_execution/containers/firecracker/firecracker.go
enterprise/server/remote_execution/containers/firecracker/firecracker_darwin.go
enterprise/server/remote_execution/executor/executor.go
enterprise/server/remote_execution/runner/BUILD
enterprise/server/remote_execution/runner/runner.go
server/util/networking/networking.go
tools/vmstart/vmstart.go

* Add a log message when recycling is complete (runner is paused and added back to the pool)
* Add a few missing "Failed to recycle runner" logs in cases where we don't recycle due to execution errors
* Add runner descriptions to all logs
* Runner descriptions look like `abc123:paused:4:WF12345` (short random ID, runner state, number of tasks that have been assigned to the runner throughout its lifetime, workflow ID)
* Log these descriptions on any operation that changes the runner pool state: taking a runner from the pool, creating a new runner, returning a runner to the pool, evicting a runner from the pool
* Add logs when we reject a runner as a possible candidate for reuse. These will be somewhat verbose but we can remove these once we figure out the runner reuse issues.
* Pass in the …

Improve runner pool logging

---

enterprise/app/api_keys/api_keys.tsx
enterprise/server/backends/userdb/userdb.go
enterprise/server/backends/userdb/userdb_test.go

The semantics of these would be unclear (e.g. can other members of the org run builds on your user-owned executor?)
---

Disallow creating user-owned executor keys

---

app/invocation/invocation_buttons.tsx

Re-running a workflow currently fails with an auth error if you don't have access to the org that owns the invocation (e.g. you're logged out, or viewing a public workflow from another org). Instead of returning an auth error, let's not show the button.
---

Hide workflow re-run button if missing permissions

---

enterprise/server/backends/userdb/userdb.go
enterprise/server/backends/userdb/userdb_test.go
server/buildbuddy_server/buildbuddy_server.go
server/interfaces/interfaces.go

:point_right: **Recommended:** [review with whitespace diff hidden](https://github.com/buildbuddy-io/buildbuddy/pull/3517/files?diff=split&w=1). (The UserDB diff is much cleaner this way) 
* Instead of `buildbuddy_server` performing multiple separate transactions to look up the group and decide whether to auto-join by domain association or submit a request to join the org, consolidate all of this logic into a single DB transaction in `RequestToJoinOrg`, and remove the `AddUserToGroup` func in UserDB.
* Fix edge case where `addUserToGroup` would not auto-promote to admin if the group was empty and there were existing membership requests which had not been approved.
* Fix edge case where we return PermissionDenied if users try to join an org after the org has claimed domain ownership and …

Fix edge cases with org join flow

---

enterprise/server/raft/bringup/bringup.go
enterprise/server/raft/replica/replica.go
enterprise/server/raft/store/store.go
proto/raft.proto
proto/raft_service.proto

Before splitting, we start a new cluster that will become the new right side. This is unchanged from before, but because the pebble DB is already open on the new cluster we have to swap the DB with the cloned data after the replica is already running.
After the clone operation is done, we force dragonboat library to take a Raft snapshot and to compact the Raft log. This "tricks" the library into using the replica-provided snapshot data for recovery operations. This is important because the real Raft log does not contain the keys that were cloned.
---

Improve split performance by cloning the underlying pebble DB.

---

enterprise/app/BUILD.bazel
enterprise/server/cmd/executor/BUILD
enterprise/server/cmd/server/BUILD
enterprise/server/image_converter/BUILD
enterprise/server/remote_execution/vfs/BUILD
enterprise/server/tasksize/BUILD
enterprise/server/util/vfs_server/BUILD

https://github.com/buildbuddy-io/buildbuddy/commit/88b49fc88c626c7e1e9b06f3f9f33e9d11c80f19 was a little overzealous in restricting visibility and it broke buildbuddy-internal: https://app.buildbuddy.io/invocation/dc1d8c0f-0176-4881-8d53-bb9e1a15f605
This PR makes a handful of packages publicly visibly again so they can be depended on from buildbuddy-internal.

Fix the build

---

.bazelrc
WORKSPACE

This fixes a compiler warning encountered on newer machines:
```
In file included from /usr/include/string.h:535,
from external/com_google_protobuf/src/google/protobuf/stubs/port.h:39,
from external/com_google_protobuf/src/google/protobuf/stubs/common.h:48,
from external/com_google_protobuf/src/google/protobuf/message_lite.h:45,
from external/com_google_protobuf/src/google/protobuf/message_lite.cc:36:
In function 'void* memcpy(void*, const void*, size_t)',
inlined from 'uint8_t* google::protobuf::io::EpsCopyOutputStream::WriteRaw(const void*, int, uint8_t*)' at external/com_google_protobuf/src/google/protobuf/io/coded_stream.h:706:16,
inlined from 'virtual uint8_t* google::protobuf::internal::ImplicitWeakMessage::_InternalSerialize(uint8_t*, google::protobuf::io::EpsCopyOutputStream*) …
```

Upgrade com_google_protobuf to 3.22.2

---

enterprise/server/cmd/ci_runner/main.go

We can make use of this config to dogfood the remote asset API in dev/prod. This could potentially make builds faster and less flaky since we'll be fetching repos from the co-located apps instead of github / NPM etc. (but I think dogfooding is the more important benefit)
Kept the "experimental_" prefix since presumably it might be promoted to non-experimental at some point, and we'll want to have both flag variants for backwards compatibility.
---

Add a buildbuddy_remote_downloader config to ci_runner generated bazelrc

---

enterprise/server/cmd/executor/BUILD

Firecracker is in the image already but I forgot to include jailer in my last PR too.
---

Add the jailer binary to the executor image

---

deps.bzl
enterprise/vmsupport/bin/BUILD
enterprise/vmsupport/kernel/rebuild.sh

Shaves 17MB from the git repo according to `du -h` (though the file length is 35MB -- seems like maybe half of the file is empty?)
Also deletes the "linux" git submodule which seemed unused
---

Fetch vmlinux with bazel

---

enterprise/server/cmd/executor/BUILD

Firecracker does not seem to like `/usr/bin/firecracker` being a symlink (introduced in https://github.com/buildbuddy-io/buildbuddy/pull/3566). it fails to connect to the VM socket without giving any feedback as to why. Reproduced locally using the script added in https://github.com/buildbuddy-io/buildbuddy/pull/3575 and verified the fix.
---

Fix firecracker failing to start

---

enterprise/server/backends/pebble_cache/pebble_cache.go

There's a race condition between the evictor and the broken metadata scanner. If the key is already gone from the pebble DB then there's no mismatch.
---

Don't log "metadata mismatch" warning if the key doesn't exist.

---

enterprise/config/executor.local.yaml
enterprise/server/cmd/executor/BUILD
enterprise/tools/run_executor_image.sh

Created this script while attempting to debug why we timeout when attempting to connect to firecracker. It seems to repro when the executor is running via the executor_image, but not when running the go_binary target directly.
---

Add a script to run the executor_image target locally

---

release.py

This will make the script more idempotent if the auto-release workflow reruns it, and will help minimize user error if you forget to add the skip_version_bump flag.

In release.py, don't create a new release tag if there already exists a draft release

---

deps.bzl

Update soci snapshotter sha, current one is for an old version that wants a very new glibc version

---

cli/cmd/bb/BUILD
cli/cmd/bb/bb.go
cli/download/BUILD
cli/download/download.go
cli/help/help.go

usage: bb download {digest}/{size}
Downloads the blob identified by digest from the CAS and outputs its contents.
If the blob type is specified, the downloaded bytes are interpreted as a proto
of the specified type and text-marshalled before being output. Otherwise the raw
uninterpreted bytes will be output.
Example of downloading a blob and piping it to another command:
$ bb download 686f25dbadc55ac13aca8580efead40b84d2a812278900b95ce15014dfd94702/80 | sha256sum
Example of displaying an Action with a remote instance name to stdout:
$ bb download /foo/blobs/b8907c47a5c0954a440c673832f6e219e33311f577a59ea7c9de4686900140ac/234 --type=Action
Example of dumping a Command to a file:
$ bb download 0e83f9edaff969afa4d16de9f8f5c1de2778148a982e1c19c744fc11a4f96811/1321 --type=Command …

Add a download command to the CLI

---

cli/cmd/bb/BUILD
cli/cmd/bb/bb.go
cli/help/help.go
cli/upload/BUILD
cli/upload/upload.go

usage: bb upload filename
Uploads the file specified by filename to the CAS and outputs the digest.
If an input file is specified, that file will be uploaded. To upload from
stdin, set the --stdin flag.
Example of uploading a blob from stdin:
$ echo "buildbuddy" | bb upload --stdin
Example of uploading a file with a remote instance name:
$ echo -n "buildbuddy" > input_file.txt
$ bb upload input_file.txt --remote_instance_name=foo

Add CLI upload functionality as well

---

enterprise/server/remote_execution/containers/firecracker/firecracker.go
enterprise/server/remote_execution/snaploader/snaploader.go
enterprise/server/remote_execution/snaploader/snaploader_test.go

* Remove `instanceName` from constructor (instead, we'll want to change `snapshotDigest *repb.Digest` to `snapshotResourceName *rspb.ResourceName` and pass around the instance name that way)
* Add `ctx` to all interface methods, since we'll need this for a remote cache-based `Loader` implementation
* Don't store `ctx` in the loader struct
---

Small cleanup to snaploader

---

enterprise/server/remote_execution/dirtools/dirtools.go
enterprise/server/remote_execution/executor/executor.go
enterprise/server/remote_execution/runner/runner.go
enterprise/server/util/vfs_server/vfs_server.go
server/remote_cache/cachetools/cachetools.go
server/remote_cache/content_addressable_storage_server/content_addressable_storage_server.go

Tested by running a remote execution with bazel in SHA1 mode -- it completed succesfully.

Fix any stragglers

---

enterprise/server/remote_execution/workspace/workspace.go

This makes it easier to debug the root cause, i.e. out of disk space / permissions error, etc.
---

Don't swallow error message when workspace creation fails

---

enterprise/server/remote_execution/filecache/BUILD
enterprise/server/remote_execution/filecache/filecache.go
enterprise/server/remote_execution/filecache/filecache_test.go

`Filecache.Add` does not overwrite entries at a given key. This is usually not an issue,  since contents should normally match the keys (which are SHA256 digests of the content), and so any overwrites would be a NOP.
But `snaploader.FileCacheLoader` depends on being able to write entries where the key doesn't necessarily reflect the content digest, similar to AC.
This was broken and was causing problems in some unit tests that I'm adding in one of my branches, though I'm not sure yet whether this caused any problems in practice.
---

Fix filecache entries not being overwritable

---

server/backends/disk_cache/disk_cache.go
server/util/lru/lru.go
server/util/lru/lru_test.go

Fixes a small bug that overwriting an LRU element with a larger size than the existing value's size can potentially cause the LRU to exceed its max size, and that overwriting an LRU element with a smaller size than the existing key can potentially cause the LRU to have wasted capacity (and in pathological cases, could also cause the LRU to have a negative size).
---

Update LRU size when overwriting an existing LRU key with a different size

---

enterprise/app/trends/drilldown_page.tsx
enterprise/app/trends/heatmap.tsx

- Use last-hovered selection if the user drags their mouse outside of the heatmap area--this seems less surprising than just dropping the selection attempt (Maggie and Brandon both had feedback to this effect).
- Clear selection when the user clicks on a drilldown bar (otherwise, the user keeps seeing a list of invocations and bar charts even though the new heatmap doesn't show a selection).
- Clear the active selection when zoom is cleared.
- Scroll to top when a bar is selected for filtering.
---

A few more small heatmap bug fixes

---

WORKSPACE
buildpatches/protobuf.patch

After recent protobuf upgrade, some team members have experienced the
mysterious error
```
Executing genrule @com_google_protobuf//src/google/protobuf:gen_wkt_cc_sources
...
dyld[97646]: symbol not found in flat namespace '_CFRelease'
```
This seems to be caused by
`com_google_protobuf/src/google/protobuf/compiler/protoc_nowkt`
was linked with missing symbols on MacOS.  Overriding the default link
opts to add `-framework CoreFoundation` fixes the issue.
---

protobuf: patch link opts on macos

---

enterprise/server/remote_execution/containers/firecracker/firecracker.go
enterprise/server/remote_execution/containers/firecracker/firecracker_darwin.go
enterprise/server/remote_execution/snaploader/BUILD
enterprise/server/remote_execution/snaploader/snaploader.go
enterprise/server/remote_execution/snaploader/snaploader_test.go
tools/vmstart/vmstart.go

Instead of making the snapshot digest optional (`opts.ForceSnapshotDigest`) and/or stateful (`c.pausedSnapshotDigest`), always use a non-nil digest that is deterministically computed from the VM configuration hash (and runner ID, for now[^1]).
This allows us to simplify the logic around saving/loading snapshots, while also resolving one of the blockers for snapshot sharing, since snapshot sharing will require computing a deterministic snapshot digest based solely on the VM configuration required by the task, and then checking the cache (local and/or remote) to see whether a matching snapshot is available.
[^1]: In the future, we'll remove runner ID to enable snapshot sharing - but we are blocked on having a way to ensure that runners can't concurrently access the same snapshot

Use a deterministic cache key for firecracker snapshots

---

server/build_event_protocol/accumulator/accumulator.go

This is part of the refactor to consolidate Accumulator and EventParser. Before fully consolidating those two, we need to resolve any discrepancies in the way that they compute invocation fields. This PR partially resolves a discrepancy in the computation of the role field.
Currently, `EventParser` allows setting ROLE via workspace_status.sh (although we don't document this in the metadata guide), which means that the ROLE returned from workspace_status.sh will propagate to the invocation DB.
However, `Accumulator` doesn't respect ROLE in workspace_status.sh, so the ROLE set there will not be observed by build_status_reporter or target_tracker. This means that the invocation will show up in the UI with the "CI" label, but will not appear in the Test grid or in GitHub statuses.
This PR …

Allow setting role via workspace_status

---

enterprise/server/remote_execution/containers/firecracker/firecracker.go
enterprise/server/remote_execution/filecache/filecache.go
enterprise/server/remote_execution/snaploader/BUILD
enterprise/server/remote_execution/snaploader/snaploader.go
enterprise/server/remote_execution/snaploader/snaploader_test.go
enterprise/server/util/filecacheutil/BUILD
enterprise/server/util/filecacheutil/filecacheutil.go
server/interfaces/interfaces.go

The snaploader accepts a workingDirectory param which it only uses to stage temporary files for copying to/from the filecache, and the loader impl has a decent amount of complexity around managing these temp files, which are only needed so that we can read/write bytes to/from the filecache.
This PR moves this complexity out of snaploader and into a new `filecacheutil` package, which should make the snaploader code a bit easier to work with.
---

Simplify snapshot manifest file IO

---

app/invocation/invocation_model.tsx

These artifacts aren't very useful since according to the BES proto, they will never have a URI set, and also the current logic is preventing `output_group` files from being visible when `directory_output` is present.
---

Ignore directory_output in TargetComplete events

---

release.py

We may want the script to continue updating the docker images, even if we don't want to push a new git tag.

Don't fail release.py if the version already exists

---

app/invocation/invocation_action_card.tsx

Fixes a regression in the change here: https://github.com/buildbuddy-io/buildbuddy/pull/3299/files#diff-01b2f827d97e58166368c89e6233cb1f240a2b9964f79c1a676a5e6786122b30R177-R184
That change caused us to stop passing the gRPC target in the bytestream URL, but the target is required in some cases (e.g. for europe.remote.buildbuddy.io)
---

Fix remote ActionResult fetches in the invocation action page

---

enterprise/server/remote_execution/containers/podman/BUILD
enterprise/server/remote_execution/containers/podman/podman.go

This PR gets rid of the `executor.podman.image_streaming.enabled` flag in favor of a new `executor.podman.streamable_images` flag that defined a comma-separated list of images that can be streamed. This is intended to be used so we can stream some images but rely on the old pull-and-run for images that don't have a soci index stored in the container registry.

Support streaming some but not all images

---

server/util/clickhouse/BUILD
server/util/clickhouse/clickhouse.go
server/util/db/db.go

If there is a slow query that takes > 200ms, GORM will print that to stdout by default. The schema diff script assumes that we are only logging to stdout if there is a schema change, so we want to silence any other output while it's running.

Silence gorm logging during print schema script or output will interfere

---

enterprise/server/backends/kms/BUILD
enterprise/server/backends/kms/kms.go
enterprise/server/util/keystore/BUILD
enterprise/server/util/keystore/keystore_test.go
server/interfaces/interfaces.go

This makes it possible to test KMS-dependent functionality locally without depending on an external KMS.
The KMS interface gains a new FetchKey method to support fetching arbitrary keys necessary to support customer managed keys.
---

Refactor KMS manager to support serving keys from local files.

---

enterprise/app/trends/drilldown_page.tsx

Currently, if you highlight the far left/right of the heatmap and are using a "last N days" filter, refreshing the page will not restore state correctly because the bucket at the start/end of the heatmap has changed (its some small number of seconds later).
This change fixes that refresh behavior in most cases by rounding the first bucket to start at the beginning of the day and the last bucket to the end of the day.  This techincally yields slightly more than N days of data, but I think it's easier for the user to parse anyway.
---

heatmap: round before/after timestamps to local day start / end.

---

deps.bzl

This was changed because of this convo: https://buildbuddy-corp.slack.com/archives/C01D5GHRJ59/p1679927117185589
Checksum seems to have been reverted back to the original value

Revert smart-device-manager SHA256 and prefix

---

enterprise/server/test/integration/remote_execution/rbeclient/BUILD
enterprise/tools/rbeperf/BUILD
enterprise/tools/rbeperf/rbeperf.go

This represent an alternative approach to #3671
RBE is an enterprise-only feature of BuildBuddy. Our bench test tool
rbeperf has dependencies on //enterprise source code and therefore,
could not be built from FOSS version of the repo.
Because our internal repo reference this tool, there will be a short
period of time where CI in our internal repo is broken. A separate PR
will be sent to update the references in our internal repo.
---

tools/rbeperf: move under //enterprise/tools

---

enterprise/server/backends/pebble_cache/pebble_cache.go

Credit to Jim for flagging this. If the atime update channel was empty, we would spin loop on the default case and do nothing.
This changes the select to depend on `quitChan` directly. We used to need this indirection when we batched atime updates, but it's no longer necessary.
---

Fix spin loop in pebble atime update handling.

---

buildbuddy.yaml
enterprise/server/test/integration/remote_execution/bazel_rbe/bazel_rbe_test.go
enterprise/server/test/integration/remote_execution/remote_execution_test.go

Fix a set of previously skipped tests because build actions were missing
platform properties to select the executor created and registered
locally.
---

integration/remote_execution: fix darwin tests

---

tools/gorm/print_schema_changes.sh

Otherwise if the build failed, the script would continue and it would seem like there were no schema changes.

Exit schema change script upon failure

---

enterprise/app/settings/github_link.tsx

Accidentally broke this while cleaning up the PR for review :sweat_smile: 
We need to set `install=true` in the URL because the same endpoint handles plain old OAuth linking (just linking a GH token to the User) as well as the combined OAuth+Install flow.
---

Fix GitHub app install URL

---

app/root/root.css
enterprise/app/settings/BUILD
enterprise/app/settings/github_link.tsx
enterprise/app/settings/settings.css
enterprise/server/githubapp/githubapp.go
server/interfaces/interfaces.go

- Shows all installations that your linked GitHub account has access to, as well as all installations linked to your org (even if your linked GitHub account doesn't have access to the installation)
- If not yet linked to BB, show a "Link" button that calls LinkGitHubAppInstallation
- If linked to BB (any org, even ones you aren't a member of), show an unlink button
- If not linked to the currently selected org, show a warning
In a separate PR, I might add convenience links for managing each individual installation (via GitHub), but for now that can be done via the "Setup" button then selecting the installation (it's just an extra click)
https://user-images.githubusercontent.com/2414826/229212245-386b24e6-261d-4e99-bf47-89ad632c1272.mp4
---

Implement GitHub app installation management

---

proto/cache.proto

Execution metadata from ActionCache contains the timestamps for the original execution in the cache. This data can help us calculate how much time it saved per action hit.

Add execution_metadata to ScoreCard

---

enterprise/app/settings/github_link.tsx
enterprise/app/settings/settings.tsx

:point_right: review w/ whitespace diff hidden https://github.com/buildbuddy-io/buildbuddy/pull/3698/files?diff=split&w=1
Disable org-level GH account link when app is enabled and the user doesn't have an org-level account linked (in the latter case, we still show the linked account so that they can unlink it).
Also rename the personal GitHub account settings tab to "GitHub account link"
---

Hide org-level GH account link when app is enabled

---

tsconfig.json

Provides a nice performance boost for TS analysis  (20s -> 6s to run `tsc` at the repo root).
Can profile the TS compiler with
```bash
git ls-files --others --exclude-standard | grep -v tsbuildinfo | xargs --no-run-if-empty rm
rm -rf /tmp/ts_trace/* && mkdir -p /tmp/ts_trace
time node --trace-ic ./node_modules/typescript/lib/tsc.js --noEmit --generateTrace /tmp/ts_trace/ -p tsconfig.json
```
Most of the remaining time is spent parsing protos. Our protos contain tons of duplicate code because each individual `ts_proto_library` bundles all of its transitive dependencies. This seems to be a limitation of protobufjs unless I'm missing some sort of config option that lets the codegen ignore missing transitive deps when compiling. We might want to consider consolidating all the protos into a …

Ignore bazel-buildbuddy/ and website/ in tsconfig.json

---

.bazelrc
buildbuddy.yaml
enterprise/server/test/webdriver/invocation/BUILD
enterprise/server/test/webdriver/invocation/invocation_test.go

Select the group-owned API key ("Default") instead of the personal API key to ensure that the bazel builds can upload AC results to cache.
Also switch from `assert` to `require` so that the test stops executing once it fails, so we can see exactly where it failed (both w/ `--config=webdriver-debug`, and the end-of-test screenshot)
---

Fix dev webdriver QA tests

---

cli/version/BUILD
cli/version/version.go
cli/version/version_test.go

I was trying to figure out how we are installing bb CLI in Github Action lint check
when I stumbled upon this code.
Added a test for it as well.
---

cli/version: simplified w. embedsrcs

---

enterprise/server/backends/pebble_cache/pebble_cache.go

This can happen during migration as the eviction pool contains the raw key values that can change during a migration.
---

Suppress warning in sampling refresh if the key no longer exists.

---

app/invocation/invocation_suggestion_card.tsx

Keeping the build log regex-based suggestions around, since workflows still show the build logs and it could be handy to show the suggestion directly in the workflow page without needing to drill down into the invocation.
---

Hide bazel flag suggestions for workflows

---

enterprise/server/remote_execution/vmexec_client/BUILD
enterprise/server/remote_execution/vmexec_client/vmexec_client.go
enterprise/server/vmexec/vmexec_test.go

If tasks get killed rather than exiting (`exit_code == -1`), we should populate `cmdResult.Error` (otherwise we're violating the contract that exactly one of `exit_code >= 0` or `error != nil` holds).
---

Fix VM execution not reporting an error when wrapped tasks crash

---

tools/check_release_assets_uploaded.py

Failing should be reserved if something actually breaks

Don't fail the release assets script if there are assets missing

---

enterprise/server/backends/gcs_cache/gcs_cache.go

The `ctx` we pass to the gcs writer must be associated with the `cancel` function we maintain
a refernce to for calling that `cancel` to have any effect.
---

Make GCS cache writes cancelable

---

proto/BUILD
proto/soci.proto

This adds a new RPC service that has one request: Read which returns pointers to all of the SOCI artifacts required to stream the requested image. These pointers are pointers to data in the CAS, which the client will read from if it needs the data.
**Version bump**:  Minor

Add SociArtifactStore proto

---

enterprise/app/settings/settings.tsx
proto/config.proto
server/backends/github/github.go

* `IsLegacyOAuthAppEnabled` should not return true if the server-level `--github.access_token` is the only github-related flag that is set. Otherwise, we'll show broken account link functionality in the UI.
* UI should show the org-level GitHub link page if the GitHub app is enabled but the legacy OAuth app is disabled.
---

Fix some conditional logic re. github legacy OAuth-only app

---

enterprise/app/settings/github_link.tsx
enterprise/app/settings/settings.tsx
enterprise/server/githubapp/BUILD
enterprise/server/githubapp/githubapp.go
enterprise/server/webhooks/github/github.go
enterprise/server/workflow/service/service.go
server/backends/github/github.go
server/interfaces/interfaces.go
server/libmain/libmain.go

Adds all the wiring needed to listen to webhooks from GitHub, validate the webhook secret, and handle webhook events.
The app handles the following events:
* `installation.deleted` (meta-event): proactively unlinks any BB-linked installation from the `GitHubAppInstallation` table, if one exists 
* `push`, `pull_request`: same behavior as before (invoke any workflows as applicable)
A few other related changes for getting workflows working E2E:
* Sets up the plumbing so that the build status reporter can get an installation access token based on REPO_URL invocation metadata + authenticated group ID, and report statuses correctly based on that.
* Assigns a "synthetic" workflow ID to new GitRepository-based workflows so that we can reuse all the existing code that expects a `Workflow`. The …

GH app: implement webhooks/workflows

---

enterprise/server/remote_execution/containers/podman/BUILD
enterprise/server/remote_execution/containers/podman/podman.go
enterprise/server/remote_execution/containers/podman/podman_test.go

This mimics the behavior of docker.
---

If dockerUser is set to UID:GID, don't create user/group.

---

WORKSPACE

The protobuf upgrade broke `bazel query //...` due to a missing transitive dep on `com_googlesearch_re2` (protobuf depends on googletest which depends on re2). This PR pulls in the necessary transitive dep.
---

Fix missing transitive proto dep

---

enterprise/server/remote_execution/runner/runner_test.go

After investigation in https://github.com/buildbuddy-io/buildbuddy/pull/3701,
it's shown that on average, Shutdown_RunnersReturnRetriableOrNilError
could only finish 40+ trials out of 100 on Intel Mac. This is after we
have sharded the runner_test action to the exact test count (18) so that
each test func is run on it's own shard with dedicated CPU.
The root cause of the slowness is with how the test is constructed and
run. Our test would attempt to spin up 50 execution tasks asynchronously
in separate goroutines. Then in the main goroutune, wait until the task
count hit 50/2=25 and shutdown the runner pool arruptedly to check for
error. Repeat this trial 100 times and ensure that in total it took less
than 60 seconds to complete.
This works well if the test execution is provided with a …

runner_test: fix timeout on darwin

---

app/invocation/invocation.tsx
app/root/root.css
app/target/BUILD
app/target/target.tsx
app/target/target_test_coverage_card.tsx
app/util/BUILD
app/util/color.ts
app/util/lcov.ts
enterprise/app/code/BUILD
enterprise/app/code/code.css
enterprise/app/code/code.tsx

For `bazel coverage` runs, we'll now show this file level breakdown on the test target page:
If using github, and build metadata is set - clicking on these files will show you a test coverage overlay:
---

Add support for rendering `coverage` runs

---

cli/version/BUILD
deployment/BUILD
rules/flags/index.bzl

When a file referenced in embedsrcs is a generated file, Gazelle will
try it best to look up neighbor rules within the same package for "out"
and "outs" attributes that declare such file.
However, our write_flag_to_file uses "name" attribute to specify the
file name, thus trip up Gazelle at runtime.
Provide an optional "out" attribute in write_flag_to_file to avoid
Gazelle warning.
---

gazelle: fix missing file warning

---

enterprise/app/workflows/github_app_import.tsx

Navigate back to the workflows list once a repo is linked, so that the user can see that the workflow was added alongside the other workflows. (Basing this on feedback that this flow is more intuitive. Incidentally, this is also what we did for the old workflow link flow)
---

Navigate to workflows page after linking a repo

---

proto/build_event_stream.proto

This upgrade our BES proto to the latest BES from Bazel's master branch.
The latest change to BES proto in bazel.git, as of this change, is
```
commit d31dd094c56270d892040ce65586af9b76a99744
Author: Googler <wilwell@google.com>
Date:   Thu Dec 22 04:52:07 2022 -0800
Support multiplex workers in WorkerMetricsCollector.
```
This PR was generated by extracting all the changes from bazel.git with
```
$ git diff c674101d004eccd795a06e19674e317b04b1b36a..HEAD \
-- \
src/main/java/com/google/devtools/build/lib/buildeventstream/proto/build_event_stream.proto \
> bes.patch
```
The change c674101d004eccd795a06e19674e317b04b1b36a was already applied in our version of bes.proto
so I assumed that's when we last updated/copied the file.
And then apply it into buildbuddy.git with
```
$ git apply -v …
```

proto/bes: upgrade to latest BES change

---

buildbuddy.yaml

We need to dedicate some time to fixing these tests, but for now let's disable them since they almost always show up red and might hide other unexpected errors that are mac-specific.
---

Disable more flaky tests on Mac CI

---

server/tables/tables.go
server/util/clickhouse/schema/schema.go

total_cached_action_exec_usec already exists in Invocations
tables in MySQL and ClickHouse, but it's no longer populated; so I'm
just going to re-use this field.

Add total_uncached_action_exec_usec in Invocations MySQL and ClickHouse tables

---

enterprise/app/root/root.tsx

Right now you just get a blank screen if you visit https://app.buildbuddy.io/org/create while logged out.
---

Show the login screen when attempting to create an org while logged out

---

proto/BUILD
proto/soci.proto

Because it has to resolve the image name into a reference just like GetOptimizedImage, so the request may as well look the same.

Add platform and credentials to GetSociArtifacts

---

enterprise/app/filter/filter.tsx
enterprise/server/invocation_search_service/BUILD
enterprise/server/invocation_search_service/invocation_search_service.go

Allow things like `github.com/buildbuddy-io/buildbuddy` or even `buildbuddy-io/buildbuddy` to avoid confusion when filtering by repo.
---

Normalize repo URL when filtering by repo

---

enterprise/server/remote_execution/containers/firecracker/firecracker.go
server/util/disk/disk.go

We should not throw away errors here, because depending on the situation, the caller should not proceed if the removal fails.

Improve error handling in disk.DeleteLocalFileIfExists

---

enterprise/server/backends/distributed/distributed.go
enterprise/server/backends/gcs_cache/gcs_cache.go
enterprise/server/backends/memcache/memcache.go
enterprise/server/backends/migration_cache/migration_cache.go
enterprise/server/backends/migration_cache/migration_cache_test.go
enterprise/server/backends/pebble_cache/pebble_cache.go
enterprise/server/backends/pebble_cache/pebble_cache_test.go
enterprise/server/backends/redis_cache/redis_cache.go
enterprise/server/backends/s3_cache/s3_cache.go
enterprise/server/composable_cache/composable_cache.go
enterprise/server/raft/cache/cache.go
server/backends/disk_cache/disk_cache.go
server/backends/memory_cache/memory_cache.go
server/interfaces/interfaces.go

This is currently only true for pebble cache if the user is mapped to a partition that has encryption support enabled.

Add cache API to check whether encryption is supported for the user.

---

enterprise/server/backends/pebble_cache/pebble_cache_test.go
enterprise/server/crypter_service/BUILD
enterprise/server/crypter_service/crypter_service.go
enterprise/server/crypter_service/crypter_service_test.go
go.mod
server/util/retry/BUILD
server/util/retry/retry.go

Allow keys to be cached in memory for up to 10 minutes. Start trying to refresh keys after 5 minutes, if the key has been used recently. Remove key from cache if we are unable to refresh it before expiration or if it was not used recently.

Add a caching layer for encryption/decryption keys.

---

enterprise/server/remote_execution/containers/firecracker/firecracker.go

Before this PR, the firecracker implementation of `Pause()` would take the following steps:
1. Pause the VM
2. Take a VM state snapshot + memory snapshot
3. Save all snapshot artifacts to filecache (VM state, memory, disk). Importantly, the disk snapshot is not copied. Instead, we reuse the same disk image across snapshots.
4. Resume the VM
5. "Shut down" the VM (`machine.ShutDown()`)
6. Stop the VMM (`machine.StopVMM()`, which kills firecracker using SIGTERM)
7. Clean up networking
8. Remove all temp files
There are a bunch of problems with this approach:
- `machine.ShutDown()` (step 4) doesn't actually shut down the VM; instead it sends Ctrl+Alt+Del which on Linux just logs out.
- Even if we could do a clean shut down of the VM, it would be unnecessary. We've already taken a snapshot …

Firecracker: fix corruption due to resuming VM after snapshotting

---

enterprise/server/backends/pebble_cache/pebble_cache.go

We have not run into issues in the past with scanning over the keys in the database.
The current migration won't finish before the next release. 

Make pebble key migrator rate limit only apply to moves.

---

proto/BUILD
proto/runner.proto

Add protos to make the runner pool state serializable so that we can save it to a file and then reconstruct the runner pool state from the file after an executor restart.
Supporting only firecracker for now, but in theory we could also support resuming bare/podman/docker persistent workers after a restart.

Add protos for runner pool state

---

deps.bzl
enterprise/server/cmd/server/BUILD

This will be used in https://github.com/buildbuddy-io/buildbuddy/pull/3726
Longer term I would like to just call the code directly and remove this dependency, but for now this is simpler.

Add soci binary to app image

---

.github/workflows/checkstyle.yaml

When I install the latest version of `bb` and run `bb fix -mode diff` on master, it produces a non-empty diff. This is a bit of a head-scratcher since checkstyle is passing.
Adding a `bb version` step just to sanity check which version of `bb` we're using for checkstyle.

Print bb version in checkstyle

---

app/docs/BUILD
app/docs/setup.tsx
app/docs/setup_code.tsx
app/invocation/invocation_artifacts_card.tsx
app/invocation/invocation_details_card.tsx
app/invocation/invocation_raw_logs_card.tsx
app/root/BUILD.bazel
app/root/root.tsx
app/target/BUILD
app/target/action_card.tsx
app/target/target_artifacts_card.tsx
app/target/target_test_log_card.tsx
enterprise/app/root/BUILD.bazel
enterprise/app/root/root.tsx
enterprise/app/trends/trends.tsx

It's not necessary to explicitly spread `...this.state` when calling `setState()` since React will preserve existing state and update only the keys specified in the passed in state updates record.
Also clean up `this.setState({ x: this.state.x })`. It's more clear to call `forceUpdate()` in this scenario.
---

refactor: clean up `this.setState({ ...this.state, ... })`

---

app/shortcuts/shortcuts.tsx

This causes an issue clicking into sub-invocations from workflow invocations.

Don't throw an error on duplicate keyboard shortcut

---

enterprise/server/cmd/server/BUILD
enterprise/server/cmd/server/main.go

Since https://github.com/buildbuddy-io/buildbuddy/pull/3726 the apps have failed to start due to:
`ERROR 2023-04-19T20:05:17.461150912Z [resource.labels.containerName: migrate-db] /app/enterprise/buildbuddy: error while loading shared libraries: libstdc++.so.6: cannot open shared object file: No such file or directory`
Siggi and I suspect this is due to something in the soci code that we're now depending on. This PR breaks the build-time link between the app/server code and sociartifactstore so this error should stop happening, but without having to revert that entire PR (which now has a second one stacked on top).

Sever BUILD link between app and sociartifactstore

---

enterprise/server/invocation_stat_service/invocation_stat_service.go

Use time.now() for 'previous summary' time range when no updated_before filter is specified.

---

enterprise/app/history/history_invocation_card.tsx
enterprise/app/workflows/github_app_import.tsx

Our use of `setTimeout` is causing some type errors when running `tsc` because it expects the return type to be `Timeout`, which is only true for `nodejs`. This is because `@types/node` is being included in the tsc compile somewhere as a transitive dep. It doesn't affect our bazel builds, but shows up in the IDE. This PR switches us to `window.setTimeout` instead to ensure the browser types are used and fix the typing issues.
Also fixes a bug that we were using `setTimeout` instead of `setInterval` in one place.

Fix some typing issues with setTimeout

---

enterprise/server/invocation_stat_service/invocation_stat_service.go

use download_outputs_option when counting the number of builds with remote cache in summary

---

enterprise/server/api/api_server.go
enterprise/server/backends/authdb/authdb.go
enterprise/server/backends/userdb/userdb.go
enterprise/server/execution_search_service/execution_search_service.go
enterprise/server/execution_service/execution_service.go
enterprise/server/githubapp/githubapp.go
enterprise/server/hostedrunner/hostedrunner.go
enterprise/server/invocation_search_service/invocation_search_service.go
enterprise/server/invocation_stat_service/invocation_stat_service.go
enterprise/server/quota/quota_manager.go
enterprise/server/quota/quota_manager_test.go
enterprise/server/remote_execution/execution_server/execution_server.go
enterprise/server/secrets/secrets.go
enterprise/server/test/integration/invocation_webhook/invocation_webhook_test.go
enterprise/server/usage/usage.go
enterprise/server/usage/usage_test.go
enterprise/server/usage_service/usage_service.go
enterprise/server/workflow/service/service.go
server/backends/github/github.go
server/backends/invocationdb/invocationdb.go
server/backends/invocationdb/invocationdb_test.go
server/build_event_protocol/build_status_reporter/build_status_reporter.go
server/build_event_protocol/target_tracker/target_tracker.go
server/build_event_protocol/target_tracker/target_tracker_test.go
server/build_event_protocol/webhooks/webhooks.go
server/tables/tables.go
server/target/target.go
server/util/db/db.go
server/util/db/db_test.go
server/util/query_builder/query_builder_test.go

The motivation for this is that postgres does not and cannot use backticks to
indicate identifiers such as table names, so if we want to support postgres, we
need to switch to double quotes for that purpose (sql_mode="ANSI_QUOTES" in
mysql). We also need to quote table names, since we use mixed-case table names,
postgres is case sensitive, and unquoted identifiers are all converted to lower
case by postgres. This also means all strings must be specified with single
qoutes (`'`).

Use ANSI quotes for queries and quote table names

---

enterprise/server/api/api_server.go
enterprise/server/backends/authdb/authdb.go
enterprise/server/backends/userdb/userdb.go
enterprise/server/execution_search_service/execution_search_service.go
enterprise/server/execution_service/execution_service.go
enterprise/server/githubapp/githubapp.go
enterprise/server/hostedrunner/hostedrunner.go
enterprise/server/invocation_search_service/invocation_search_service.go
enterprise/server/invocation_stat_service/invocation_stat_service.go
enterprise/server/quota/quota_manager.go
enterprise/server/quota/quota_manager_test.go
enterprise/server/remote_execution/execution_server/execution_server.go
enterprise/server/secrets/secrets.go
enterprise/server/test/integration/invocation_webhook/invocation_webhook_test.go
enterprise/server/usage/usage.go
enterprise/server/usage/usage_test.go
enterprise/server/usage_service/usage_service.go
enterprise/server/workflow/service/service.go
server/backends/github/github.go
server/backends/invocationdb/invocationdb.go
server/backends/invocationdb/invocationdb_test.go
server/build_event_protocol/build_status_reporter/build_status_reporter.go
server/build_event_protocol/target_tracker/target_tracker.go
server/build_event_protocol/target_tracker/target_tracker_test.go
server/build_event_protocol/webhooks/webhooks.go
server/tables/tables.go
server/target/target.go
server/util/db/db.go
server/util/db/db_test.go
server/util/query_builder/query_builder_test.go

Reverts buildbuddy-io/buildbuddy#3832
Identical to the original PR in the first commit. The second commit corrects a mistake made with using URL vs DSN.

Revert "Revert "Use ANSI quotes for queries and quote table names""

---

enterprise/server/githubapp/githubapp.go
enterprise/server/workflow/service/service.go
server/interfaces/interfaces.go

Fixes an issue that workflows cannot be re-run when the org that owns the workflow isn't selected, even if the authenticated user has access to the workflow.
**Related issues**: Fixed https://github.com/buildbuddy-io/buildbuddy-internal/issues/2246

Fix re-running workflows for non-selected but authorized group

---

WORKSPACE

To bring it in sync w/ the internal version.

Bump protoc-gen-protobufjs to v0.0.8

---

enterprise/server/cmd/ci_runner/main.go
enterprise/server/hostedrunner/hostedrunner.go
enterprise/server/test/integration/ci_runner/ci_runner_test.go
server/testutil/testgit/testgit.go

Example situation this would fix:
1. Push a commit (C1) to a feature branch that prints "A" in a test
2. The triggered workflow will report commit=C1 and print "A"
3. Push a commit (C2) to the feature branch that prints "B"
4. Rerun the initial workflow
5. It should report commit=C1 and print "A". Currently, it will print "B" because the workflow always pulls the HEAD commit

Fix workflows not checking out the commit they are reporting for

---

enterprise/server/cmd/ci_runner/main.go

Because the ExecuteWorkflow API will only pass a branch name and not a commit sha, it will be helpful to report which commit sha the workflow is running on
**Related issues**: #3774

In ci_runner, set commit_sha metadata if it isn't passed in as an argument

---

server/build_event_protocol/build_event_handler/build_event_handler.go
server/buildbuddy_server/buildbuddy_server.go

Add the ability to retrieve an invocation's timing profile artifact from blobstore.
---

Serve timing profile artifact from blobstore

---

deps.bzl
enterprise/server/cmd/server/BUILD

This approach ended up requiring pulling a bunch of containerd stuff into the binary as well and turned out to be more effort than just inlining the index creation code, so doing that instead.
Reverts buildbuddy-io/buildbuddy#3802

Revert "Add soci binary to app image"

---

enterprise/server/scheduling/scheduler_server/scheduler_server.go

Not setting this flag to true would make BuildBuddy iterate through
the stale executors during scheduling.  With sufficient amount of
stale executors, scheduling process could be significantly slower.
Since we have set this flag to true in production for a while, let's
deprecate it by setting the default to true in up-coming release and
remove the flag entirely in a subsequent release.

scheduler_server: flip remove_stale_executors to true

---

package.json
yarn.lock

This remove the last dependency we have over the old d3-color version.
**Related issues**: Closes https://github.com/buildbuddy-io/buildbuddy/security/dependabot/71

d3-scale: upgrade to 4.0.2

---

enterprise/server/crypter_service/crypter_service.go

Actually use the fake clock in error caching :facepalm:

Fix crypter_test flakiness.

---

.github/workflows/checkstyle.yaml
WORKSPACE
deps.bzl
go.mod
go.sum
server/util/flagutil/common/BUILD
server/util/testing/flags/BUILD
server/util/testing/flags/flags.go

Also update rules_go to 0.39.1.
Adjust flags handling in testing to future-proof against new flags being added to go's testing facilities.

Update go version to 1.20

---

.github/workflows/checkstyle.yaml

The CLI install script takes a release arg that defaults to `latest`. We can pass `tags/<tag>` to request a tagged release instead

Pin bb version in checkstyle

---

app/router/router.tsx

This more closely matches the behavior of `window.location.hash` which `getTab` replaces.
This fixes an issue where if you (accidentally or intentionally) select a line on a test log, you switch tabs to a non-existent one.

Fix `getTab` to return empty string if only `#` is present in url

---

enterprise/app/trends/heatmap.tsx

react-resize-detector allows `NaN` values to fall through to the component, this masks them with reasonable default values.

Fix some ts errors in the heatmap

---

enterprise/app/trends/drilldown_page.tsx

this was previously showing two days when only one day was selected--the "before" date was (correctly) being set to midnight on the next day and then i was fastforwarding it to 11:59.

fix end date selection on drilldowns page.

---

cli/arg/arg.go
cli/arg/arg_test.go
cli/cmd/bb/bb.go

This causes the CLI to parse Bazel's subtractive patterns syntax correctly: https://bazel.build/run/build#specifying-build-targets
For example you can run:
```
bazel build -- foo/... -foo/bar/...
```
Which will build everything in `foo/...` but excludes the subdirectory `foo/bar/...`.
Also adds a test.

CLI: Support Bazel subtractive patterns properly

---

WORKSPACE

These are latest minor of the dependencies.
No breakages is expected.
Needed to unblock docusaurus upgrade under '//website/...' which require
minimum node version at v16.14.0.

Upgrade rules_nodejs to 5.8.2 and nodejs to 16.19.0

---

enterprise/server/backends/pebble_cache/pebble_cache.go
enterprise/server/raft/filestore/BUILD
enterprise/server/raft/filestore/filestore.go
enterprise/server/raft/filestore/filestore_test.go
proto/raft.proto

This format adds an optional encryption key segment for keys that refer to encrypted contents.
This version also makes the "remote instance hash" segment always be present even if the remote instance name is empty. Instead of omitting the segment, we use a "0" value. This simplifies the parsing logic as the encryption key is also optional.
Adding the encryption key ID to the key makes it simple to deal with transitions from having encryption enabled to off, or even if the encryption is turned off and on again.
For example, if a user has encryption enabled and then turns it off, we want previously written encrypted artifacts to be treated as non-existent. Without having the encryption metadata in the key, we would have to unmarshal and check every value during FindMissing calls which would …

Add new pebble key format that includes the encryption key ID.

---

enterprise/server/backends/pebble_cache/pebble_cache.go
enterprise/server/crypter_service/crypter_service.go
enterprise/server/crypter_service/crypter_service_test.go
server/interfaces/interfaces.go

I also wrapped the crypter error in a Unavaiable status so it doesn't look like a "digest not found" error to bazel/users.
Note: this builds on top of https://github.com/buildbuddy-io/buildbuddy/pull/3888

Populate encryption key segment in pebble key when encryption is on.

---

website/theme/BlogTagsListPage/index.tsx

Previously we take the first character in the key in `tags` as
the tag category.
However, `tags` is currently like this:
```
{
"/blog/tags/company": {
"allTagsPath": "/blog/tags",
"slug": "/blog/tags/company",
"name": "company",
"count": 12,
"permalink": "/blog/tags/company"
},
"/blog/tags/team": {
"allTagsPath": "/blog/tags",
"slug": "/blog/tags/team",
"name": "team",
"count": 10,
"permalink": "/blog/tags/team"
},
"/blog/tags/rules-xcodeproj": {
"allTagsPath": "/blog/tags",
"slug": "/blog/tags/rules-xcodeproj",
"name": "rules_xcodeproj",
"count": 4,
"permalink": "/blog/tags/rules-xcodeproj"
},
...
}
```
So the first character ended up being `/` and all tags ended up being in
the same category `/`.
Use tag's name initial character as category.

website: fix category in all tags page

---

.bazelrc
.gitignore

Used this recently to help with writing tests for #3800 and #3861.
Super helpful to identify code branches with missing tests.

bazelrc: support generate coverage output with lcov and genhtml

---

website/blog/whats-new-in-bazel-5-0.md
website/blog/whats-new-in-bazel-6-0.md
website/docusaurus.config.js
website/package.json
website/src/components/oss/oss.module.css
website/src/css/general.css
website/src/css/nav.css
website/src/theme/DocSidebar/index.js
website/theme/BlogListPage/index.tsx
website/theme/BlogPostItem/index.tsx
website/theme/BlogTagsListPage/index.tsx
website/theme/BlogTagsPostsPage/index.tsx
website/yarn.lock

This is a follow up of #3892.
Several changes needed to be made to accomodate for the new version:
- Deprecate colorMode.switchConfig config
- Use `className` instead of `class` in blog post's nav component.
- Several component deprecation / replacements
- BlogPostItem needed to be wrapped around by BlogPostProvider
- Tag struct in each blog post was also updated

website: upgrade docusaurus to 2.4.0

---

enterprise/server/cmd/ci_runner/main.go

We don't want these PR workflows to show up in the test grid, and build_metadata accumulates so there's no way to override this.

Don't set ROLE=CI for pull request runs

---

enterprise/app/settings/settings.tsx
enterprise/server/test/webdriver/shortcuts/BUILD
enterprise/server/test/webdriver/shortcuts/shortcuts_test.go
server/testutil/webtester/webtester.go

I tried to add a test for shift-c that copies the invocation page url, but couldn't get the banner to render remotely and actually pasting the link into a random text box elsewhere (on the settings page) interfered with the local clipboard and felt janky, but I'm open to suggestions.

Add webdriver test for keyboard shortcuts

---

enterprise/server/crypter_service/BUILD
enterprise/server/crypter_service/crypter_service.go
enterprise/server/crypter_service/crypter_service_test.go
server/tables/tables.go

If a customer has rotation enabled for their key then the key material is going to keep changing and the old key material will become unavailable. To make sure we can always decrypt the internal keys, we will periodically re-encrypt the keys using the latest available key version in the customer KMS.

Add a background process to re-encrypt existing keys.

---

enterprise/app/trends/drilldown_page.tsx

This broke with https://github.com/buildbuddy-io/buildbuddy/pull/3841. I'll work on getting coverage on this.

fix broken metric selection on drilldowns page.

---

cli/cache_proxy/BUILD
cli/cache_proxy/cache_proxy.go
cli/cmd/sidecar/sidecar.go
cli/sidecar/sidecar.go
enterprise/server/test/integration/remote_execution/rbetest/rbetest.go
server/build_event_protocol/build_event_proxy/BUILD
server/build_event_protocol/build_event_proxy/build_event_proxy.go
server/build_event_protocol/build_event_server/BUILD
server/build_event_protocol/build_event_server/build_event_server.go

When --sync=true, we will
1) pass --bes_upload_mode=wait_for_upload_complete
2) pass --synchronous_write to cache_proxy in the sidecar. When
synchronous_write flag is set, cache_proxy will not use the worker
queue to process the write requests async.
**Related issues**: 
https://github.com/buildbuddy-io/buildbuddy-internal/issues/2108

Add --sync=true flag to cli

---

enterprise/app/encryption/encryption.tsx
enterprise/app/settings/settings.tsx
enterprise/server/crypter_service/crypter_service.go
proto/config.proto
proto/encryption.proto
server/static/static.go

With the new pebble key format, content is implicitely separated by customer via the encryption key ID so there's no longer a need to require a dedicated storage partition.

Remove dedicated partition requirement for encryption.

---

proto/build_event_stream.proto

This includes the changes from latest Bazel's HEAD.
```
> git log --oneline \
--reverse \
d31dd094c56270d892040ce65586af9b76a99744..HEAD \
-- \
src/main/java/com/google/devtools/build/lib/buildeventstream/proto/build_event_stream.proto
0e1d1b6b75 Add exec_kind to RunnerCount in BEP
1acc7a843b Add option to expose package metrics via the BEP.
0ebf7bc837 Automated rollback of commit 1acc7a843bf0996c26a1e3d74bb64514395b7e7f.
284e5a3aee Add WorkerPool metrics in `blaze.invocations` table.
5f1a5709b3 Cpu timec to bep
```
Note how `1acc7a843b` was reverted by `0ebf7bc837` so those changes are
skipped.

Upgrade build_event_stream.proto to bazel.git 5f1a5709b3

---

enterprise/server/sociartifactstore/sociartifactstore.go

Vadim tells me it's not needed

Don't set instance name when writing soci artifacts to cache

---

enterprise/server/backends/pebble_cache/pebble_cache.go
enterprise/server/backends/pebble_cache/pebble_cache_test.go
enterprise/server/crypter_service/crypter_service_test.go
enterprise/server/raft/filestore/filestore.go

The same digest may exist in the cache in both unencrypted and encrypted formats.

Separate encrypted content on disk.

---

enterprise/server/backends/pebble_cache/pebble_cache_test.go
enterprise/server/crypter_service/crypter_service.go
enterprise/server/crypter_service/crypter_service_test.go

This prevents the encrypted content to be decrypted on behalf of the wrong customer (e.g. due to a bug). 
Not a problem in practice because we already use the group ID for the encrypted customer key. 

Use group ID as authenticated data for master portion of key.

---

enterprise/server/crypter_service/crypter_service.go

We were feeding 64 bytes of zeroes prior to feeding the actual keys.

Fix bug in key derivation input.

---

enterprise/server/crypter_service/crypter_service.go

This is to prevent cross-version attacks in the future if/when we need to alter the encryption format.

Include protocol version in chunk auth data.

---

deps.bzl
server/util/bazel/BUILD
server/util/bazel/defs.bzl

We are no longer running prober against Bazel 3 and 4.
Our integration test is also using Bazel 5.3 as default.
Remove Bazel 3 and 4 and simplify related configuration and
added doc.
---
This was a result of me wanting to setup some integration tests to
verify Bazel's symlink behavior in more recent versions. Those tests
will be added in future PRs.

server/util/bazel: remove old Bazel versions and simplify

---

app/invocation/invocation_breakdown_card.tsx
app/invocation/invocation_timing_card.tsx

1. use cat = "remote output download" for reporting download
outputs
2. use both name = "subprocess.run" and cat = "local action execution"
for "Executing locally"
3. Remove Objc and Swift compilation. Events with "SwiftCompile" and
"ObjcCompile" can be in two different categories "local action execution" and
"Remote execution process wall time". As a result, we are double accounting
for SwiftComiple and ObjcCompile
https://github.com/buildbuddy-io/buildbuddy-internal/issues/1831

timing profile breakdown: take into account event.cat

---

package.json
yarn.lock

This helps us upgrade the dependency @jsdoc, which in turn remove the
dependency over taffydb.
Closes https://github.com/buildbuddy-io/buildbuddy/security/dependabot/92

protobufjs-cli: upgrade to v1.1.1

---

enterprise/server/crypter_service/crypter_service.go
server/metrics/metrics.go

Unfortunately, Grafana still can't display nice legends for heat maps where the units are in microseconds.

Use milliseconds for key age metric.

---

app/root/root.css

The blue we use is the same as the one for running invocations, so it's not obvious when you select one that's running. Also updated the box shadow per Siggi's suggestion. Here's how it all looks now:
**Related issues**: https://github.com/buildbuddy-io/buildbuddy-internal/issues/2244

Mark keyboard-selected invocation with yellow instead of blue

---

server/util/filter/filter.go

a significant number of executions have a worker start timestamp *before* the queued timestamp for the task. this causes issues in clickhouse if the maximum observed queue time in usec won't fit in an int32, which apparently happens once in a blue moon.

treat negative queue times as effectively zero.

---

server/http/protolet/BUILD
server/http/protolet/protolet.go

protolet is pretty stable and well-tested so these log messages aren't needed anymore (they add lots of noise when running tests)

Clean up protolet debug message

---

enterprise/server/remote_execution/containers/firecracker/firecracker.go
enterprise/server/remote_execution/containers/firecracker/firecracker_darwin.go
enterprise/server/remote_execution/containers/firecracker/firecracker_test.go
enterprise/server/remote_execution/runner/runner.go
enterprise/server/remote_execution/snaploader/BUILD
enterprise/server/remote_execution/snaploader/snaploader.go
enterprise/server/remote_execution/snaploader/snaploader_test.go
enterprise/tools/vmstart/vmstart.go

Snapshot isolation by group_id, instance_name, and platform hash is currently implicit in the fact that only one `Runner` can use a snapshot at a time, and runners are effectively isolated by group_id, instance_name, and platform_hash.
Eventually we'd like to be able to look up snapshots from cache without needing a pre-existing `Runner` in the runner pool. So this PR is a step towards that goal by making these properties explicit rather than implicit.

Add explicit group ID, instance name, and platform hash to snapshot cache key

---

enterprise/app/trends/drilldown_page.tsx

oops, this bar is always showing right now.  hasn't made a cut yet.

fix bad falsey check for 'tags are unsupported' warning on execution drilldowns.

---

enterprise/server/cmd/ci_runner/main.go
enterprise/server/test/integration/ci_runner/BUILD
enterprise/server/test/integration/ci_runner/ci_runner_test.go

The previous code allowed the workflow invocation to cleanly terminate, which prevents it from being retried.

Ensure outer workflow invocation gets disconnected on LOCAL_ENVIRONMENTAL_ERROR

---

server/backends/blobstore/BUILD
server/backends/blobstore/aws/aws.go
server/backends/blobstore/azure/azure.go
server/backends/blobstore/blobstore.go
server/backends/blobstore/disk/BUILD
server/backends/blobstore/disk/disk.go
server/backends/blobstore/disk/disk_test.go
server/backends/blobstore/gcs/gcs.go
server/backends/blobstore/util/BUILD
server/backends/blobstore/util/util.go

Introduce PrefixBlobstore to wrap arround all existing blobstore
implementations to provide prefix support out-of-the-box.  This should
help us avoid the overhead of having to call util.BlobPath explicitly in
each blobstore implementation.
until.BlobPath is kept exported so that we could mock it during testing.
This may conflict with #3717 and require a merge conflict resolve if
this is merged after.
In which case, author could re-use this comby command for refactoring.
```bash
comby 'util.BlobPath(:[1])' ':[1]' server/backends/blobstore/**/*.go -exclude server/backends/blobstore/util/
```
---

blobstore/util: wrap all blobstore impl with prefix

---

enterprise/app/esbuild.config.mjs

When attempting to upgrade rules_nodejs for the internal repo, it seems
that the location of `node_modules` directory could be moved to be under
the Open Source repo (this repo).
Attempting to detect the usual 'node_modules' directory not being there
and switch to use the new path under 'external/'.
This fix is expected to be a no-op in the current repo and the current
internal repo.  However this should help unblock this internal PR:
https://github.com/buildbuddy-io/buildbuddy-internal/pull/2270

Fix esbuild pointing to non-existent directory

---

enterprise/app/history/BUILD
enterprise/app/history/history.tsx
enterprise/app/history/history_invocation_card.tsx

The `preventDefault()` was causing issues for keyboard navigation (pressing enter while an invocation card is focused)
The styling still looks good:

Use Link component for invocation cards

---

deps.bzl
go.mod
go.sum

Recreation of https://github.com/buildbuddy-io/buildbuddy/pull/3952/ with go_repository updated
---
Bumps [github.com/docker/distribution](https://github.com/docker/distribution) from 2.8.1+incompatible to 2.8.2+incompatible.
- [Release notes](https://github.com/docker/distribution/releases)
- [Commits](https://github.com/docker/distribution/compare/v2.8.1...v2.8.2)
---
updated-dependencies:
- dependency-name: github.com/docker/distribution
dependency-type: direct:production
...
Signed-off-by: dependabot[bot] <support@github.com>

Bump github.com/docker/distribution

---

enterprise/server/workflow/service/BUILD
enterprise/server/workflow/service/service.go
enterprise/server/workflow/service/service_test.go
server/environment/environment.go
server/libmain/libmain.go
server/real_environment/real_environment.go

(1) Process webhook requests in the background so that we can immediately respond to GitHub's HTTP request instead of potentially timing out waiting for CAS writes / Execute requests.
(2) Start workflow actions in parallel. This should reduce the overall workflow start latency in the case where a repo has many actions (rules_xcodeproj for example has 15 actions), especially in the case where there is a spike in CAS write latency / Execution service latency. For example, if CAS writes are taking 1s and there are 15 workflow actions, then starting the actions in serial means that the last action will be artificially delayed by 14s.

Make workflows more robust during CAS/Execution latency spikes

---

package.json
yarn.lock

We have replaced protobufjs-cli with https://github.com/buildbuddy-io/protoc-gen-protobufjs
---

Remove protobufjs-cli dep

---

app/invocation/invocation_cache_card.tsx
enterprise/app/history/history.tsx

Example (I've done this a million times myself on accident):

Don't render random floating `0` if there are no invocations in an org

---

app/target/target_test_cases_card.tsx

strict mode doesn't like `Boolean(foo?.bar)`, seemingly because it worries that calling `Boolean` might modify `foo` to `null`.
also, note that this one was probably fine, but i'd rather keep emitting nothing instead of `""`

coerce data to boolean in a way that makes strict mode happy.

---

app/invocation/BUILD
app/invocation/cache_requests_card.tsx
app/invocation/invocation_cache_card.tsx

more sending this out for opinions on the text and positioning of this content on the page, because there are a lot of options.  the stuff i have now is a placeholder more than anything.
It currently looks like... this: 
and... this:

render cache savings on invocations card when trends summary is enabled.

---

enterprise/server/test/integration/remote_execution/remote_execution_test.go
server/remote_cache/content_addressable_storage_server/BUILD
server/remote_cache/content_addressable_storage_server/content_addressable_storage_server.go
server/remote_cache/content_addressable_storage_server/content_addressable_storage_server_test.go

We already return MissingDigest errors for files in the tree, but were not correctly returning this error if the root of the tree is missing.

Return MissingDigestError for missing tree root as well

---

enterprise/server/scheduling/scheduler_server/scheduler_server.go

This flag has been flipped to default true in #3859.
Let's remove it entirely since turning it off would cause more problems.
**Related issues**: https://github.com/buildbuddy-io/buildbuddy-internal/pull/2278

scheduler_server: rm remove_stale_executors flag for good

---

.bazelrc

We have this config in our internal document to help with debugging.
Let's just make it part of the bazelrc.
I use this by setting my `user.bazelrc` to
```
build --remote_header=x-buildbuddy-api-key=<foo>
build:x --config=remote-mac
```
And subsequently invoke the build from M1 laptop with
`bazel test --config=x //server/backends/...`

bazelrc: provide cross remote build config

---

cli/devnull/devnull.go
server/build_event_protocol/build_event_handler/build_event_handler.go
server/build_event_protocol/build_event_handler/build_event_handler_test.go
server/build_event_protocol/build_event_server/build_event_server.go
server/interfaces/interfaces.go
server/test/integration/build_event_protocol/build_event_protocol_test.go

If Bazel doesn't receive all the ACKs that we send after finalizing the invocation, Bazel will attempt to retry the invocation starting from the last ACK'd sequence number, plus one.
In this case, we currently return an error due to a sequence number mismatch. This PR makes it so that we just re-ACK all the events that Bazel thinks it needed to re-send, without doing any additional work.
**Related issues**: #3980

Fix BES error when bazel doesn't receive all ACKs

---

cli/translate/js/js_test.go
cli/translate/js/translate.js

This allows you to concatenate lists generated with builtins like `glob()` or `select()`.
For example, something like:
```
srcs = glob([
"src/**",
"static/**",
"docs/**",
]) + [
"docusaurus.config.js",
"yarn.lock",
"sidebars.js",
"//server/cmd/buildbuddy/yaml_doc:generate_mdx",
"//server/metrics:generate_mdx",
"//enterprise/server/cmd/server/yaml_doc:generate_mdx",
"//enterprise/server/cmd/executor/yaml_doc:generate_mdx",
]
```
Could be represented as:
```
srcs: glob([
"src/**",
"static/**",
"docs/**",
]).concat([
"docusaurus.config.js",
"yarn.lock",
"sidebars.js",
"//server/cmd/buildbuddy/yaml_doc:generate_mdx",
"//server/metrics:generate_mdx",
"//enterprise/server/cmd/server/yaml_doc:generate_mdx",
"//enterprise/server/cmd/executor/yaml_doc:generate_mdx",
])
```

CLI: support `.concat()` on builtins in js BUILD files

---

enterprise/server/workflow/service/service.go

With the ExecuteWorkflow API, we do not pass in a commit sha, and only a branch name. This will let us fetch the correct workflow yaml in that case

Fetch workflow yaml with pushed branch if sha is not present

---

app/flame_chart/flame_chart.tsx
app/flame_chart/flame_chart_model.ts
app/flame_chart/profile_model.ts

1. Added a field in the LineModel to indicate the sample rate. The
sample rate for action count is every 0.2 seconds, while for other
graphs, the sample rates are every second. This should fix the issue
where some data points are not annotated for action count graphs when
hovering.
2. Fixed a bug where the first data point is not added to the LineModel.

Timeseries chart bug fixes

---

website/blog/keyboard-shortcuts.md

It's a little confusing because all Cloud customers (both free tier and paid tier) are able to use this feature.

Remove enterprise wording from blogpost

---

server/util/db/db.go

Create a DSNFormatter interface so that it is simple to create new structs for new DB drivers implementing the interface. This makes adding postgres less messy.

Refactor dsn formatting to make it easier to add new db drivers

---

enterprise/server/backends/userdb/userdb.go
enterprise/server/scheduling/scheduler_server/scheduler_server.go
server/tables/tables.go
server/util/perms/perms.go

Removes display widths of ints and removes the `tinyint` specification in order
to make all of the gorm table specifications compatible with the gorm postgres
driver.

Update table specifications to be compatible with postgres

---

enterprise/server/remote_execution/containers/firecracker/BUILD
enterprise/server/remote_execution/containers/firecracker/firecracker_test.go
server/util/networking/networking.go

This test tries to test the network connection of a firecracker VM by pinging the default route. Pinging the default route fails even when run from the executor pod itself. This may have to do with the networking setup on executors. Change the test to ping something else, because that's what the test is ultimately trying to test

Fix firecracker test that won't run on the executor

---

tools/metrics/grafana/dashboards/buildbuddy.json

- Add missing region filter to ops graphs.
- Separate estimated comaction debt to separate graph as it was dwarfing the in-progress bytes time series.

Pebble dashboard tweaks.

---

enterprise/app/history/history_invocation_card.tsx

didn't bother looking up when this happened, but i noticed that my browser tabs were hitting 100% cpu, and yeah, after a minute or something the main js thread is basically constantly spinning doing this--looks like we treated a setinterval as a settimeout by accident.

prevent exponentially multiplying setIntervals on pending build cards

---

server/remote_cache/capabilities_server/capabilities_server.go

The latest version of Remote APIs is v2.3.
Let's make sure that we follow the specification and avoid future v2.4
or v3.0 clients to try using our API before we support it.
**Related issues**: https://github.com/bazelbuild/remote-apis/issues/253

GetCapabilities: set HighApiVersion to 2.3

---

cli/plugin/plugin.go
cli/terminal/BUILD
cli/terminal/terminal.go
docs/cli-plugins.md

This avoids merging the stderr streams and stdout streams into a single stream (passed to the plugin pipeline). By merging the streams, we make it difficult for users to parse Bazel output, since Bazel normally puts all of its progress messages out-of-band (on stderr).
We could alternatively fix this by having two separate pipelines, one for stderr and one for stdout, and having two separate plugin types (handle_bazel_stderr, handle_bazel_stdout), but I think having the ability to modify stdout could be error-prone.
**Related issues**: Fixes https://github.com/buildbuddy-io/buildbuddy-internal/issues/2315

CLI: only pipe stderr through bazel output plugins

---

server/build_event_protocol/accumulator/accumulator.go
server/build_event_protocol/build_event_handler/build_event_handler.go
server/build_event_protocol/event_parser/event_parser.go
server/build_event_protocol/invocation_format/BUILD
server/build_event_protocol/invocation_format/invocation_format.go
server/build_event_protocol/invocation_format/invocation_format_test.go

This will prevent us from storing any incomplete tags.  Doesn't seem worth blocking a build to me, but I'm willing to be convinced.

Throw an error and disconnect the invocation when tag list is too long for mysql

---

enterprise/server/remote_execution/containers/podman/podman.go

If the SociArtifactStore returns an RPC error for some reason the artifacts won't be available (or may be only partially available), but the executor can still pull the image without streaming. This PR changes the executor code to fall back to the non-streaming image pull instead of returning an error in this case.

Fall back to slow image pull on SociArtifactStore.GetArtifacts RPC error

---

enterprise/app/trends/drilldown_page.tsx

This doesn't matter as much for other drilldowns, which generally are always set, but this change lets us see cases where only some builds have tags set, which can be useful.

Always show tags drilldown, even if there's only one.

---

enterprise/server/remote_execution/containers/firecracker/README.md
enterprise/server/remote_execution/containers/firecracker/containeropts.go
enterprise/server/remote_execution/containers/firecracker/firecracker.go
enterprise/server/remote_execution/runner/runner.go
enterprise/tools/vmstart/BUILD
enterprise/tools/vmstart/vmstart.go

Before, `--executor.firecracker_debug_mode=true` would only work when running the executor.
Now, it works in tests, as well as the `vmstart` util.

Make firecracker debug_mode flag work everywhere

---

enterprise/server/remote_execution/containers/podman/podman.go

Log podman pull latency too so we can see the exact number (metric just has a bucketized one)

---

proto/BUILD
proto/nbd.proto

The executor serves this `BlockDevice` service and the VM uses a little `BlockDevice` client as part of its local NBD server. The client talks to the executor to request reads/writes from a backing storage (which eventually will involve a copy-on-write mechanism implemented in the executor).

Add protos for nbd

---

server/backends/disk_cache/BUILD
server/backends/disk_cache/disk_cache_test.go
server/remote_cache/byte_stream_server/byte_stream_server_test.go
server/remote_cache/content_addressable_storage_server/content_addressable_storage_server_test.go
server/testutil/testdigest/testdigest.go

In our test code, we have a fair number of tests that contain stanzas like this:
```
d, buf := testdigest.NewRandomDigestBuf(t, size)
r := &rspb.ResourceName{
Digest:    d,
CacheType: rspb.CacheType_CAS,
}
```
This CL is the first in a series which simplifies this to simply call `testdigest.RandomCASResourceBuf` (or a variant) instead. Fixing these tests is a bit of a blocker for https://github.com/buildbuddy-io/buildbuddy/pull/4110 which otherwise would require many many test fixes that add a single field to the manually constructed ResourceName proto.

Replace some usages of testdigest.NewRandomDigestBuf with testdigest.RandomCASResourceBuf

---

enterprise/server/remote_execution/blockio/BUILD
enterprise/server/remote_execution/blockio/blockio.go
enterprise/server/remote_execution/blockio/blockio_test.go

- Add an interface for block-level storage
- Add a `File` implementation that uses `read()/write()`
- Add an `Mmap` implementation that uses `mmap()`. This is a bit experimental, but so far it seems to perform much better than `File`, with a tradeoff that it uses more memory. In a test with Bazel, the performance of nbd+Mmap is only 2% worse than our existing implementation which uses firecracker's Drive API to mount an ext4 image as a block device, compared to 20% worse for nbd+File.
In future PRs, this can be evolved to support copy-on-write (for forkable snapshots) as well as remote snapshot storage (e.g. lazily downloading blocks from cache).

Add initial block storage layer for NBD / UFFD

---

enterprise/server/backends/configsecrets/BUILD
enterprise/server/backends/configsecrets/configsecrets.go
enterprise/server/cmd/executor/BUILD
enterprise/server/cmd/executor/executor.go
enterprise/server/cmd/server/BUILD
enterprise/server/cmd/server/main.go
go.mod
go.sum
server/cmd/buildbuddy/main.go
server/config/config.go
server/interfaces/interfaces.go
server/testutil/testenv/testenv.go
server/util/flagutil/types/types_test.go
server/util/flagutil/yaml/BUILD
server/util/flagutil/yaml/yaml.go
server/util/flagutil/yaml/yaml_test.go
server/util/testing/flags/flags.go

Any flag values in format ${SECRET:foo} are loaded from the configured secret store. Initially only GCP is supported.
In this version, we perform the expansion after YAML unmarshalling so that multi-line secrets work properly.

Add secret expansion to config files (enterprise only) - try2.

---

.github/workflows/checkstyle.yaml
WORKSPACE

Several CVE related to CGO
https://github.com/golang/go/issues?q=milestone%3AGo1.20.5+label%3ACherryPickApproved

go: upgrade to 1.20.5

---

enterprise/server/cmd/goinit/main.go

We have observed that for several Workflows with larger repo, the
default max_user_watches is too low for Bazel's '--watchfs' feature to
work properly.
Let's raise the default max_user_watches according to the recommendation
in a recent Linux Kernel patch (1) where the default value should be 1%
of the memory available (which is 8GB in our case).
(1): https://lore.kernel.org/all/20201109035931.4740-1-longman@redhat.com/T/#u
Fixes https://github.com/buildbuddy-io/buildbuddy-internal/issues/2307

goinit: raise inotify.max_user_watches to 1% mem available

---

enterprise/server/backends/pebble_cache/pebble_cache.go

Keys for ANON data don't follow the normal key format so they won't be found when sampling keys with the "GR" prefix.
To make the process work for ANON keys, we make up a random pseudo group ID for anon keys that's only used when sampling group IDs. When sampling, we check if we would have hit this group ID had it really existed in the key space and if so return the ANON group as the sampled group id.

Make group ID sampling work for ANON data.

---

.github/workflows/checkstyle.yaml

After #4131, we have upgraded actions/setup-go to version 4, which
includes similar cache functionality as actions/cache. (1)
This causes the 2 cache mounting steps to collide, leading to buggy
behaviors in Github Actions (2).
Remove actions/cache as it's no longer needed.
(1): https://github.com/actions/setup-go/blob/v4.0.1/README.md#v4
(2): https://github.com/buildbuddy-io/buildbuddy/actions/runs/5206047156/jobs/9392179281#step:20:3

checkstyle: remove actions/cache

---

buildpatches/com_github_hanwen_go_fuse_v2.patch
deps.bzl
enterprise/server/cmd/goinit/BUILD
enterprise/server/cmd/goinit/main.go
enterprise/server/remote_execution/containers/firecracker/firecracker_test.go
enterprise/server/vmvfs/BUILD
enterprise/server/vmvfs/vmvfs.go
enterprise/vmsupport/bin/BUILD
enterprise/vmsupport/bin/mkinitrd.sh

This reduces the size of the initial RAM disk from 50MB -> 26MB
The go-fuse patch is required because it eagerly tries to read `/dev/null` in an `init()` func, and panics because it doesn't exist (as we haven't yet mounted devtempfs to /dev). I will see if I can upstream these changes and remove the patch in a follow-up.

Firecracker: Link vmvfs into init binary

---

server/build_event_protocol/accumulator/BUILD
server/build_event_protocol/accumulator/accumulator.go
server/build_event_protocol/build_status_reporter/build_status_reporter.go
server/build_event_protocol/target_tracker/target_tracker.go
server/build_event_protocol/target_tracker/target_tracker_test.go

Based on logging, this will cause a few metadata computations in the wild to change, but I figure it's better to consolidate this logic and help users deal with the effects of this change on a case-by-case basis, rather than having these confusing code paths for metadata computation (the confusion is that both codepaths are computing the same metadata, but one codepath would apply to GH status reporting and test grid, and the other codepath would apply to DB fields that we display in the UI).

Use EventParser logic for repo URL, commit SHA, and role

---

docs/guide-metadata.md

fixing the BUILDBUDDY_LINKS documentation to actually show the markdown format, too--looks like a docusaurus upgrade started parsing our example of how to make a link as a markdown link.

add a tiny bit of documentation about tags to metadata guide.

---

enterprise/server/backends/prom/BUILD
enterprise/server/backends/prom/prom.go

Add a redis cache in PromQuerier, and cache the prometheus json results to prevent querying prometheus too often. 

Add redis cache to promQuerier

---

docs/enterprise-api.md
enterprise/server/api/api_server.go
enterprise/server/test/integration/workflow/BUILD
enterprise/server/test/integration/workflow/workflow_test.go
enterprise/server/workflow/service/service.go
proto/api/v1/workflow.proto
proto/workflow.proto

The UI will set `async: true` so it can link to the invocation page without needing to wait for the workflow task to be dequeued. Making this opt-in to avoid a breaking change to the public API.
Also fix a bug that `waitForWorkflowInvocationCreated` failures weren't getting propagated to the `ActionStatus.status` field (discovered this while I was failing to get the test to fail when commenting out `async: true`).

Add an `async` option to ExecuteWorkflow

---

app/invocation/BUILD
app/invocation/invocation.tsx
app/invocation/invocation_in_progress.tsx
app/invocation/invocation_logs_model.tsx
app/invocation/workflow_rerun_button.tsx
app/router/router.tsx
enterprise/server/workflow/service/service.go

* When clicking the workflow re-run button, set `async: true` in the ExecuteWorkflowRequest to avoid waiting for the invocation to be created. Instead, just wait for the action to be queued, and navigate to the invocation page with `?queued=true`.
* When `queued=true` is set in the URL on the invocation page, show a page similar to the "Invocation is in progress..." screen, but with the title "Invocation is waiting for an available worker..." instead.
* Whenever we enqueue a workflow action, publish a pending status to GitHub with the message "Queued...". The status "Details" link points to an invocation URL with `queued=true`.
**Related issues**: Fixes https://github.com/buildbuddy-io/buildbuddy-internal/issues/2243

Support a "queued" invocation view and use it for queued workflows

---

cli/add/add.go
cli/translate/yaml/BUILD
cli/translate/yaml/yaml.go
cli/workspace/BUILD
cli/workspace/workspace.go

This PR adds support for the following top level blocks in the WORKSPACE.yaml file:
`deps`, `templates`, `settings`, `bazel`, 
This allows you to specify a single file to configure your whole Bazel setup, like so:
```
workspace:
name: myworkspace
bazel:
version: 6.1.1
settings:
bes_results_url: https://app.buildbuddy.io/invocation/
bes_backend: remote.buildbuddy.io
remote_cache: remote.buildbuddy.io
remote_executor: remote.buildbuddy.io
templates:
server: github/enricofoltran/simple-go-server
app: github/Kornil/simple-ts-react-app
deps:
- github/bazelbuild/rules_go
- github/bazelbuild/rules_docker
- github/bazelbuild/rules_proto
- github/bazelbuild/bazel-gazelle
- github/bazelbuild/rules_nodejs
```
As an escape hatch, you can still add things to your workspace file manually like so:
``` …
```

CLI: Add some new block types to WORKSPACE.yaml parsing

---

server/interfaces/interfaces.go

This splits the Authenticator interface into 5 separate interfaces:
- HTTPAuthenticator
- GRPCAuthenticator
- UserAuthenticator
- APIKeyAuthenticator
- InstallationAuthenticator
Each of these new, smaller interfaces has just a handful of methods, making it easier to implement.
This is a first (small) step in a series of clean-ups that I first attempted but abandoned 2 years ago with: https://github.com/buildbuddy-io/buildbuddy/pull/1008/files
This change will allow us to remove the concept of a "fallback authenticator" which the `SAMLAuthenticator` currently relies on for methods it doesn't care about (the SAMLAuthenticator only implements HTTPAuthenticator and UserAuthenticator methods and forwards the rest to the fallback).
The ultimate goal here is clean up the `SAMLAuthenticator` and …

Split the authenticator interface into separate interfaces

---

cli/add/add.go
cli/translate/yaml/yaml.go

This supports the following github repo formats for templates and deps:
- github/buildbuddy-io/buildbuddy
- github/buildbuddy-io/buildbuddy/
- github.com/buildbuddy-io/buildbuddy
- github.com/buildbuddy-io/buildbuddy/
- https://github.com/buildbuddy-io/buildbuddy
- https://github.com/buildbuddy-io/buildbuddy/

CLI: Support different github repo formats

---

enterprise/server/usage/usage.go
server/remote_cache/hit_tracker/hit_tracker.go
server/tables/tables.go

Track cpu saved time and cache write in usage table
**Related issues**: https://github.com/buildbuddy-io/buildbuddy-internal/issues/2325

Store cache upload bytes and cached execution duration in usage table.

---

enterprise/server/remote_execution/containers/firecracker/firecracker.go

Having trouble reproducing the panic due to `c.machine` being nil, but adding a nil check for now to prevent a panic. Logging an error instead of panicking should make it easier to see the order of operations in the logs.

Add nil check to pauseVM

---

enterprise/server/auth/auth.go
enterprise/server/saml/saml.go
server/http/interceptors/interceptors.go
server/interfaces/interfaces.go
server/libmain/libmain.go
server/nullauth/BUILD
server/nullauth/nullauth.go
server/testutil/testauth/testauth.go

This PR makes the HTTPAuthenticator methods `Login`, `Auth`, and `Logout` return errors rather than just immediately redirecting the browser.
This lets us reason about how each of these calls behaved when we have multiple HTTPAuthenticators.
Adds a `HandlerFunc` that converts these errors into a browser redirect.

Make `Login`, `Auth`, and `Logout` handlers return errors instead of redirecting

---

enterprise/server/backends/pebble_cache/pebble_cache.go

If there's only one group in the group list with a count of zero, the sampling will blow up.

Check total approx item count before trying to sample.

---

cli/cache_proxy/cache_proxy.go

CLI: Don't return EOF for early-exit writes in cache_proxy

---

enterprise/server/saml/BUILD
enterprise/server/saml/saml.go

Previously we checked to see if the registered auth was nullAuthenticator because we didn't want to use nullAuthenticator as a fallback.
In the new model where we don't a fallback, we don't need this check anymore.

Remove old nullAuthenticator check from old authenticator setup

---

app/flame_chart/flame_chart.tsx

`calc(60% - 14px)` causes Firefox to be unable to render timing profile events and 
y-axis misalignment under certain scenarios.
**Related issues**: 
Fixes https://github.com/buildbuddy-io/buildbuddy-internal/issues/2391
and https://github.com/buildbuddy-io/buildbuddy-internal/issues/2392

change the height of the timing event viewport

---

enterprise/server/githubapp/githubapp.go

This will make it a bit easier to view installation events, since the UI in the GH app settings doesn't have a way to search by event type.

Log GitHub app installation events

---

app/flame_chart/flame_chart.tsx

The bottom scrollbar is only partially shown after adjust the height of the top
viewport in PR https://github.com/buildbuddy-io/buildbuddy/pull/4191

timing profile: fix horizontal scrollbar

---

enterprise/app/executors/executor_card.tsx
enterprise/server/cmd/executor/BUILD
enterprise/server/cmd/executor/executor.go
enterprise/server/scheduling/scheduler_client/scheduler_client.go
enterprise/server/scheduling/scheduler_server/scheduler_server.go
enterprise/server/test/integration/remote_execution/rbetest/BUILD
enterprise/server/test/integration/remote_execution/rbetest/rbetest.go
proto/scheduler.proto

The executor no longer serves gRPC requests, so it should be safe to remove the gRPC server.
Since we're no longer depending on `grpc_server.go`, I defined a new deprecated "grpc_port" flag in executor.go to avoid breaking people who have old configs and are still setting that for whatever reason. We can remove the flag later after giving people some time to notice the deprecation warning. (I don't recall seeing any of the other flags ever being set for the executor, like `app.grpc_max_recv_msg_size_bytes`, `grpcs_port`, `internal_grpc_port` etc., but I could be mistaken)
Also update the scheduler to no longer require `port` metadata from the executor registration. After this PR is rolled out and all scheduler instances stop checking `port != 0`, we can send a follow-up to stop …

cleanup: remove executor gRPC server

---

enterprise/server/remote_execution/containers/docker/docker.go
enterprise/server/remote_execution/containers/podman/podman.go

It's dubious whether underscores are allowed / recommended in URLs (it seems to make some Java URL parsing libraries barf) and this name gets returned if you run `hostname -A`.

Use dashes instead of underscores for container names

---

enterprise/server/auth/auth.go
enterprise/server/saml/saml.go

Since the auth refactor in this case (where we have a SAML login, but the user doesn't exist yet) we return the error message from the OIDC AuthenticatedUser call (which is that no JWT is found).
This means the UI doesn't know it should attempt to create the user.
We should potentially brainstorm a better API here, but this fixes SAML user creation in the meantime.

Return the correct error when a SAML user doesn't exist yet

---

enterprise/server/backends/authdb/BUILD
enterprise/server/backends/authdb/authdb.go
enterprise/server/backends/authdb/authdb_test.go
enterprise/server/cmd/server/main.go
enterprise/server/quota/quota_manager_test.go
enterprise/server/testutil/enterprise_testenv/BUILD
enterprise/server/testutil/enterprise_testenv/enterprise_testenv.go
server/tables/tables.go

I decided to use the same column to store either the plaintext or encrypted value of the API key to simplify the schema.
There are three flags to control the behavior of the feature and to allow a gradual rollout:
- auth.api_key_encryption.key when the key is set, the auth code will look for keys matching both the unencrypted and unencrypted form of the key. Rolling out this flag first will allow encrypted keys to be recognized by all apps once they are in the database.
- auth.api_key_encryption.encrypt_new_keys when this is set, all newly created keys will be writen in an encrypted format
- auth.api_key_encryption.encrypt_old_keys on startup, any existing unencryptde keys will be encrypted

Add support for encrypting API keys.

---

enterprise/server/remote_execution/blockio/BUILD
enterprise/server/remote_execution/blockio/blockio.go
enterprise/server/remote_execution/blockio/blockio_test.go

Adds a method to split a file into fixed-size, immutable chunks, and a corresponding `Store` implementation called `COW` that implements copy-on-write when chunks are modified.
This buys us the ability to represent snapshot artifacts as manifests pointing to immutable chunks in the cache, which can be loaded as a `Store` implementation compatible with NBD/UFFD, paving the way towards shareable snapshots.
For now, all chunks are stored in a dedicated dir (the readonly chunks are stored as `${chunkByteOffset}` and the modified ones are named as `${chunkByteOffset}.dirty`). To store a COW in cache (in a later PR), we can simply add all these chunks to cache, along with a manifest proto indicating the byte offsets of each chunk. To load a COW from cache, we can read back the manifest, then …

Add initial blockio copy-on-write Store

---

cli/parser/parser.go
cli/parser/parser_test.go

**Related issues**: Fixes https://github.com/buildbuddy-io/buildbuddy-internal/issues/2427

CLI: Fix startup options parse error

---

BUILD
enterprise/server/remote_execution/execution_server/execution_server.go
server/eventlog/eventlog.go

Enable golang staticcheck analyzer S1009 (Omit redundant nil check on slices)

---

enterprise/server/remote_execution/containers/firecracker/BUILD
enterprise/server/remote_execution/containers/firecracker/firecracker.go
enterprise/tools/vmstart/vmstart.go

* Fix issue that debug mode was broken by https://github.com/buildbuddy-io/buildbuddy/pull/3797
* Split "debug mode" concept into 2 separate flags - VM log streaming, and interactive mode (which starts a terminal in the VM). Most of the time, I don't actually want the VM terminal, and occasionally it messes up my host terminal and I have to kill the whole term to fix it.

Fixes / improvements to firecracker debug mode

---

enterprise/server/test/integration/remote_execution/BUILD

**Related issues**: https://github.com/buildbuddy-io/buildbuddy-internal/issues/2379

Increase timeout on remote_execution_test

---

cli/help/BUILD
cli/help/help.go
cli/test/integration/cli/cli_test.go
server/util/lockingbuffer/lockingbuffer.go

Make it work even if the help topic is not a bazel command - not all help topics are bazel commands, such as `completion` and `target-syntax`.
**Related issues**: Fixes https://github.com/buildbuddy-io/buildbuddy-internal/issues/2448

CLI: fix 'bb help completion'

---

enterprise/server/remote_execution/container/container.go
enterprise/server/remote_execution/containers/firecracker/firecracker.go

* Fix vmstart (it was failing because `PullImageIfNecessary` expects an authenticator, but vmstart doesn't set one up. In this case, we can disable image cache auth that is based on group ID, and instead authenticate directly with the remote registry). Also, make sure to stream stdout/stderr to the terminal when the new `debug_terminal` flag is enabled, even if `debug_stream_vm_logs` is not enabled. Otherwise, we can send keyboard input to the VM but can't see the output.
* Don't set the `quiet` kernel option ever. Otherwise, we'll only see kernel logs when debug mode is enabled, but we always want kernel logs to be available (e.g. when dumping kernel logs for debugging)
* Fix up a few places that I missed in https://github.com/buildbuddy-io/buildbuddy/pull/4218 where I meant to reference …

More firecracker debugging fixes

---

enterprise/server/test/performance/cache/BUILD
enterprise/server/test/performance/cache/cache_test.go

Add Pebble Cache and Distributed Pebble Cache to benchmark cache test.
Also change the log level to error. Some warning logs make the benchmark result difficult to read. 

Add Pebble Cache to benchmark cache test

---

enterprise/server/tasksize/tasksize.go

Executors don't look super over-utilized, and we can adjust task sizing instead if this becomes an issue

Don't multiply resource requests by 0.8

---

app/auth/auth_service.ts

Fun quirk I found when working on auth stuff, if you call setInterval with larger than a 32 bit integer - you get an overflow and the setInterval function gets spammed:
https://stackoverflow.com/questions/39007056/is-there-a-maximum-delay-limit-for-window-setinterval

Don't call setInterval with larger than a day

---

proto/failure_details.proto

There has been several changes to failure_details recently with the most
interesting changes being Spawn.REMOTE_CACHE_EVICTED failure reason.

proto/failure_details: update from Bazel's latest

---

enterprise/server/oidc/BUILD
enterprise/server/oidc/oidc.go
enterprise/server/oidc/oidc_test.go
server/util/claims/BUILD
server/util/claims/claims.go
server/util/cookie/cookie.go

These methods are used in both oidc and github auth.
We pull the following methods into cookie.go:
- SetLoginCookie
- ClearLoginCookie
And the following methods into claims.go
- ClaimsFromContext
- AuthContextFromClaims

Pull some more stuff out of oidc.go into claims.go and cookie.go

---

enterprise/server/remote_execution/blockio/blockio.go
enterprise/server/remote_execution/containers/firecracker/BUILD
enterprise/server/remote_execution/containers/firecracker/firecracker.go
enterprise/server/remote_execution/containers/firecracker/firecracker_test.go
enterprise/server/remote_execution/nbd/nbdserver/nbdserver.go

:point_right: based on https://github.com/buildbuddy-io/buildbuddy/pull/4205
* Use the new `blockio.COWStore` for the NBD backing storage
* Save and load the COW as part of the snapshot
Compared to plain ext4, the `git clone && bazel build` test with NBD + COW enabled is about 6-10% slower (~62s with NBD disabled, vs. ~66-68s with NBD enabled). I haven't yet tried making the block size larger or other optimizations, so there might be some room for improvement here.

Use COW storage for firecracker VM NBDs

---

enterprise/server/backends/userdb/userdb.go
enterprise/server/backends/userdb/userdb_test.go

This allows us to create users from Github accounts without public email addresses without requesting any additional permissions.

Don't require an email address when creating an account

---

WORKSPACE
enterprise/server/remote_execution/containers/firecracker/firecracker_test.go

For more information:
https://github.com/bazelbuild/rules_go/releases/tag/v0.40.1
https://github.com/bazelbuild/rules_go/releases/tag/v0.40.0
This should help with https://github.com/buildbuddy-io/buildbuddy-internal/issues/2314
thanks to https://github.com/bazelbuild/rules_go/pull/3566

rules_go: upgrade to v0.40.1

---

WORKSPACE

We need this to verify how Executor could be built targeting Windows
platform.
**Related issues**: https://github.com/buildbuddy-io/buildbuddy-internal/issues/2314

go_sdk: add windows Go toolchains

---

enterprise/server/cmd/ci_runner/main.go

I had this fix locally but forgot to push :cry: 

Fix CI runner cred helper username

---

cli/parser/parser.go

If you apply .bazelrc options and you have `common` flags in your .bazelrc to the `bazel help` command, which may be invalid.
This causes problems until this Bazel fix is in (but will continue to cause problems on old versions):
https://github.com/bazelbuild/bazel/pull/18609

CLI: Don't apply .bazelrc when running `bazel help` to collect metadata

---

cli/sidecar/sidecar.go

Before this change, we'd unnecessarily start the sidecar if `--sync=true` is set (which it is if the CI=true environment variable is set) but BES / cache flags were not set.

CLI: Only set sync flag if we need a sidecar

---

release.py

Will also change the default behavior of the script to bump the minor version, instead of the patch version as it is doing now.
**Related Slack thread**: https://buildbuddy-corp.slack.com/archives/C01D5GHRJ59/p1687987660161869

Add option to release.py to bump the minor version vs the patch version

---

cli/log/log.go

* Set `BB_VERBOSE=1` as an env var, and respect that env var, so that child invocations run in verbose mode as well.
* As a side benefit, this also allows setting `BB_VERBOSE=1` as an env var for the top level invocation, instead of using the `--verbose=true` flag which is slightly less ergonomic in some situations.

CLI: propagate --verbose flag to child invocations

---

BUILD
cli/cache_proxy/cache_proxy.go
tools/cacheload/cacheload.go

There are several changes here:
- Disable fieldalignment completely (instead of excluding all files from
being checked).
- Remove nilness config. The analyzer was removed from an earlier change.
- Switch from including only files under `sever/` and
`enterprise/server/` to excluding all `external/` files. This will
include Go files from other directories such as `cli/`.
- Programatically replace all unix path separators with a regex that
matches both Windows and Unix separators.
- Add comment with example on how to check the rendered json config
file.
- Add missing configs for some analyzers,
effectively ignore all external dependencies during linting.

nogo: make config json consistent

---

deps.bzl
go.mod
go.sum

This includes the fix to Windows compilation for
enterprise/server/cmd/ci_runner.

creack/pty: upgrade to 1.1.18

---

server/config/config.go
server/config/config_test.go

This change returns the parse error upward when a config fails to parse, instead of early-returning no error. This fixes an issue where a malformed config results in a confusing failure to launch:
```
2023/07/07 22:32:10.053 INF BuildBuddy v2.12.49 (933606adb4ed2c807eab7a9edcc27782eb0e1d10) compiled with go1.20.5 X:nocoverageredesign
2023/07/07 22:32:10.054 INF Reading buildbuddy config from '/local/config.yaml'
2023/07/07 22:32:10.062 INF Auto-migrating DB
2023/07/07 22:32:10.078 INF Successfully configured sqlite database.
2023/07/07 22:32:10.079 WRN No authentication will be configured: rpc error: code = Internal desc = OIDC authenticator failed to configure: rpc error: code = FailedPrecondition desc = No auth providers specified in config!
2023/07/07 22:32:10.080 FTL rpc error: code = …
```

config: Propagate parse failures upward

---

cli/bazelisk/BUILD
cli/bazelisk/bazelisk.go
cli/cmd/bb/bb.go
cli/test/integration/cli/cli_test.go
cli/testutil/testcli/BUILD
cli/testutil/testcli/testcli.go
server/testutil/testbazelisk/BUILD
server/testutil/testbazelisk/testbazelisk.go

Adds a new env var `BB_USE_BAZEL_VERSION` that can be used instead of `USE_BAZEL_VERSION` when using the `.bazelversion` method for running the CLI under bazelisk. `USE_BAZEL_VERSION` doesn't work because it bypasses the CLI entirely.

CLI: allow setting bazel version w/ env var when using .bazelversion method

---

server/build_event_protocol/build_event_server/build_event_server.go

The previous behavior waits for the upload to finish, but the errors aren't propagated back to the CLI.  With this change, error output for bad API keys, messed up metadata, etc. can be printed client-side.

Wait for and print BES errors when `sync` is set on CLI runs.

---

deps.bzl
go.mod
go.sum

This one: https://github.com/buildbuddy-io/soci-snapshotter/blob/main/proto/local_keychain.proto

Upgrade version of soci-snapshotter depended on from 0.0.1 to 0.0.4 so we can use that new proto

---

deps.bzl
enterprise/server/cmd/executor/BUILD

This lets us start the store with the [local_keychain service](https://github.com/buildbuddy-io/soci-snapshotter/blob/main/service/keychain/local_keychain/local_keychain.go) enabled so we can pass credentials back and forth.
There's a bunch of crap in [buildbuddy-tools](https://console.cloud.google.com/storage/browser/buildbuddy-tools/binaries/soci-snapshotter?pageState=(%22StorageObjectListTable%22:(%22f%22:%22%255B%255D%22))&project=flame-build&prefix=&forceOnObjectsSortingFiltering=false) now (including this version), I have a reminder set to go in and clean it up (except the version we're using!) once this one looks good.

Upgrade soci-store binary to buildbuddy-io/soci-snapshotterv0.0.4

---

server/build_event_protocol/accumulator/accumulator.go
server/build_event_protocol/build_event_handler/build_event_handler.go

2 fixes to help our with our oversize build event stream issue:
- don't re-read the BES in the post-invocation handler anymore, instead track the URIs we need to copy as events are received during the invocation; do not copy more than 1K files from cache -> blobstore
- when loading oversize invocations, stop reading non-important events after 100K (The bad invocation we were looking at before had 650,000 events)

Drop events from oversize build event streams

---

enterprise/server/remote_execution/commandutil/commandutil.go
enterprise/server/vmexec/vmexec_test.go

Passes now on RBE with --runs_per_test=10000.
**Related issues**: Fixes https://github.com/buildbuddy-io/buildbuddy-internal/issues/2477

Fix panic/flakiness in vmexec_test

---

enterprise/server/remote_execution/containers/podman/BUILD
enterprise/server/remote_execution/containers/podman/podman.go
enterprise/server/remote_execution/runner/runner.go

This PR:
- Adds a new flag, `--executor.podman.enable_private_image_streaming` which controls whether images requiring authentication are streamed or not. Note that this flag only takes effect if `--executor.podman.enable_image_streaming` (which now controls streaming public images) is also true.
- Removes the unused `--executor.podman.streamable_images` flag because it was making the code more confusing than necessary.
- Refactors the image-streaming flow control a little bit so that checking state via flags and booleans is more consistent. Now, per-image streamability is controlled in the Container (which is narrowly scoped to a single podman operation) by just a boolean that is provided to the Container and has a different name than the flag (for easier searching). And image streaming …

Disable streaming private images

---

WORKSPACE

Pulls in a few minor fixes related to enum JSON representation and a few other small inconsistencies with protobufjs-cli.
https://github.com/buildbuddy-io/protoc-gen-protobufjs/compare/v0.0.8...v0.0.9

Bump protoc-gen-protobufjs to v0.0.9

---

deps.bzl
enterprise/server/remote_execution/containers/firecracker/BUILD
enterprise/server/remote_execution/containers/firecracker/firecracker.go
enterprise/server/remote_execution/containers/firecracker/firecracker_test.go
enterprise/server/remote_execution/snaploader/snaploader.go
enterprise/server/remote_execution/uffd/BUILD
enterprise/server/remote_execution/uffd/uffd.go
go.mod
go.sum

Adds some scaffolding to integrate firecracker w/ `blockio.COWStore` for managing the memory snapshot and connecting the snapshot to the VM via UFFD. The UFFD handler is just a stub that returns `Unimplemented` for now.

Add some basic scaffolding for memory COWStore

---

deps.bzl
enterprise/server/cmd/executor/BUILD
go.mod
go.sum

Bump soci-snapshotter version run as soci-store and linked into app from v0.0.4 to v0.0.5

---

enterprise/app/executors/BUILD
enterprise/app/executors/executors.css
enterprise/app/executors/executors.tsx

When helping a customer troubleshoot their executor pools,
it was not clear visually which pool was which between multiple
"Default" pools with different OS/Arch combination.
Move the OS/Arch information to their dedicated lines to better display
different attributes of a pool.

app/executors: improve OS/Arch UI

---

enterprise/server/usage/BUILD
enterprise/server/usage/usage.go
enterprise/server/usage/usage_test.go
server/tables/tables.go
server/util/db/BUILD
server/util/db/db.go

We're planning to update the Usage table schema with new Label columns (e.g. `origin={internal, external}, client={bazel, executor}`), and we might also add more labels in the future (such as `owner={bb, self_hosted}`).
These new labels effectively need to be part of the current unique index on (group_id, region, period_start_usec).
But there are a few problems with just adding these fields to the unique index:
- GORM can't migrate unique indexes for us, and doing a manual migration each time we want to add a new label is error prone. The consequence of getting this migration wrong would be potentially double-counting usage data.
- Even if GORM could migrate these unique indexes for us, our current upsert logic would be error prone. If the Create() fails, that means there is already a …

usage: remove reliance on unique index for upsert query

---

enterprise/server/remote_execution/containers/firecracker/firecracker_test.go

It seems like we are experiencing serious flake because our test would
pull image from marketplace.gcr.io which requires credentials.
Side-step the credential issue completely by pulling from GCP's mirror
of Docker's public container registry "docker.io".

firecracker_test: switch to use mirror.gcr.io

---

server/testutil/testenv/testenv.go

When set at 'debug', we have a lot of logs which make it hard to find
reason why a test fail initially.
Raise the default log level in test to reduce the noise level.
Individual tests could still override this value in their own package.

testenv: raise default log level to 'warn'

---

enterprise/server/remote_execution/filecache/BUILD
enterprise/server/remote_execution/filecache/filecache.go

We have received a report from a customer with self-hosted executor
regarding cleanup left over.
Let's start tracking if there is any failures during unlink syscall.

filecache: log potential unlink error

---

enterprise/server/backends/pebble_cache/pebble_cache.go

Extract functions:
1. to create a wrapped writer for compressing and encrypting
2. to write metadata
These two functions will be used in a following PR when I implement CDC chunking. 

Refactor: Extract methods in pebble_cache.go

---

.bazelrc
template-user.bazelrc

This config is great to help when use in combination with `--config=remote-target-linux`
As user switches between local build and remote cross-build, Bazel's analysis cache will
get dropped and needs to be rebuilt. Using Skymeld greatly speed up the total
analysis + execution time.

.bazelrc: add skymeld config

---

enterprise/server/remote_execution/containers/firecracker/firecracker_test.go

TestFirecrackerExecWithRecycledWorkspaceWithDocker flakes quite badly
because the image failed to download (possibly due to ratelimit from
docker.io). Switch the test to use the mirrored image from gcr
reduces the flake greatly.

firecracker_test: switch test to use ubuntu image from mirror

---

enterprise/app/executors/BUILD
enterprise/server/remote_execution/commandutil/BUILD
enterprise/server/remote_execution/commandutil/commandutil_test.go

This test worked fine locally due to the "exclusive" tag that prevented it from competing with stuff locally, but it runs into problems running remotely when the host is under heavier load because the timeouts are kind of tight and the resource measurement isn't 100% accurate. This change makes it pass for me locally with --runs_per_test=100, but it's not perfect.

Increase timeout and resource-measurement buffers in commandutil_test

---

enterprise/server/backends/pebble_cache/pebble_cache.go

These appear relatively safe to and should help address the large compaction backlog we see on some apps.

Tweak some pebble options

---

server/build_event_protocol/accumulator/accumulator.go

We need this event as it contains the timing profile of the build.

bep/accumulator: add BuildToolLogs as important

---

enterprise/server/backends/pebble_cache/pebble_cache.go
server/util/approxlru/approxlru.go

`evictSingleKey` is the extracted inner loop from `evict` w/o changes. 

Allow evicting more than 1 key before resampling.

---

enterprise/server/backends/pebble_cache/pebble_cache.go

Recreate iter every 1M entries to avoid holding on to old sstables for too long. 

---

enterprise/server/backends/pebble_cache/pebble_cache.go
enterprise/server/backends/pebble_cache/pebble_cache_test.go
server/util/approxlru/approxlru.go

Profiling + metrics show that eviction can be a bottleneck. A major contributor is refreshing the atime of every item in the pool on every eviction.
This CL stops doing that -- instead the approxlru will refresh an item before deleting and skip deletion if the sample's atime differs between the pool value and the live value.

Don't refresh entire eviction pool on every eviction

---

enterprise/server/cmd/goinit/main.go

In case 8.8.8.8 being unavailable, we shall first fail over to Google's
secondary DNS 8.8.4.4.  In the rare case where both fail, we fallback to
CloudFlare's DNS 1.1.1.1.
This should help us narrow down the root cause of flaky firecracker
baremetal tests such as:
```
docker:
Error response from daemon:
Get https://mirror.gcr.io/v2/: dial tcp:
lookup mirror.gcr.io on 8.8.8.8:53: read udp 192.168.241.2:42099->8.8.8.8:53: i/o timeout.
```

goinit: provide backup dns

---

deps.bzl

Most of the build directives attributes are not needed any longer with
the combination of newer Gazelle version and recent Go dependencies
upgrades.

deps.bzl: remove unused attributes

---

enterprise/server/usage/BUILD
enterprise/server/usage/usage.go
enterprise/server/usage/usage_test.go
server/tables/tables.go
server/util/db/BUILD
server/util/db/db.go

Rolling forward with some debug logging so that we can trace what happened if the manually enforced uniqueness constraint is not working properly in dev.
- Roll-forward commit (unchanged): 7acfa2ac0665306c555e2bb74a0fcd46f910a901
- Debug logging commit: d637ae1c7cb5528ac0633c86848d5fc8b9e3f51e

Roll forward "usage: remove reliance on unique index for upsert query" (#4329)

---

enterprise/app/api_keys/api_keys.css
enterprise/app/api_keys/api_keys.tsx

* Decrease font size to allow full API key to be displayed, instead of truncating w/ ellipsis
* Use unicode bullet `•` instead of `*` (looks a bit nicer)
* Reuse `<OutlinedButton>` w/ `icon-button` class for controls (had to remove `disabled` state + tweaked logic, since the default `[disabled]` styling for `<OutlinedButton>` shows a 'cancel' cursor which felt a bit weird)

Small styling tweaks for API key value

---

server/util/healthcheck/healthcheck.go

Use "_" instead of "." to avoid introducing a new debug namespace (we already have `debug_` flags)

Rename goroutine debug flag

---

deps.bzl

This reverts commit d02a2e64eec8b96ff74607668ad35174b8dbbf19. The original commit breaks the "Push dev" workflow, resulting in the following errors when trying to build smarter device manager:
```
external/com_gitlab_arm_research_smarter_device_manager/nvidia-server.go:82:39: cannot use m.server (variable of type *"gitlab.com/arm-research/smarter/smarter-device-manager/vendor/google.golang.org/grpc".Server) as *"google.golang.org/grpc".Server value in argument to pluginapi.RegisterDevicePluginServer
external/com_gitlab_arm_research_smarter_device_manager/nvidia-server.go:122:44: cannot use conn (variable of type *"gitlab.com/arm-research/smarter/smarter-device-manager/vendor/google.golang.org/grpc".ClientConn) as *"google.golang.org/grpc".ClientConn value in argument to …
```

Revert "deps.bzl: remove unused attributes (#4316)"

---

deps.bzl
tools/smarter_device_manager/BUILD

A previous change in d02a2e64eec8b96ff74607668ad35174b8dbbf19 broke the
"manual" build that depends on this Go package.
Revert the relevant buildd directive.
Add an alias for the external dep to guard our future changes against
it.
**Related issues**: replace #4388

smarter-device-manager: create an alias to validate internal build

---

enterprise/server/remote_execution/containers/docker/docker_test.go

A follow up from #4341.
This helps us avoid the rate limit from docker.io.

docker_test: use mirror.gcr.io intead of docker.io

---

server/util/db/BUILD
server/util/db/db.go
server/util/db/db_cgo.go
server/util/db/db_nocgo.go

Provide an alternative compilcation option when build without cgo on
some platforms. In particular, remove sqlite support when cgo is off.

server/util/db: allow compilation without cgo

---

enterprise/server/backends/s3_cache/s3_cache.go
server/backends/blobstore/aws/BUILD
server/backends/blobstore/aws/aws.go

When I initially committed this error handling, I had not found the way AWS SDK v2 errors were meant to be handled, so it was clumsy and inelegant.

Handle aws errors the way they're supposed to be handled

---

enterprise/server/secrets/BUILD
enterprise/server/secrets/secrets.go
server/buildbuddy_server/buildbuddy_server.go
server/interfaces/interfaces.go

- Don't use "REPLACE INTO" which is mysql-specific
- Don't include user_id in key when updating secrets since any user in the org should be able to update the same key
- Return a boolean to indicate whether it's a new secret to facilitate proper audit logging

Secret manager tweaks:

---

.github/workflows/deps.yaml

`.bazelversion` in the internal repo is at 6.0.0 but the OSS one is 6.2.1. This PR should keep these in sync automatically from now on.

Add .bazelversion to internal repo sync

---

enterprise/server/usage/usage.go
enterprise/server/usage/usage_test.go

The goal of this PR is to simplify usage data flushing, particularly since we're adding new usage label and count columns soon.
By flushing at 1 minute intervals, we no longer have a distinction between "usage periods" and "collection periods," which makes the code much simpler - each key in redis corresponds to a single row in the DB, rather than multiple "collection period" entries in redis mapping to the same "usage period" row in the DB.
One advantage of this is that we never have to run UPDATE queries when flushing - only INSERT. With updates, we have to worry about accidentally updating rows we shouldn't (causing misattribution). If we're only inserting, then the worst that happens is that we potentially don't record some label values that the current app doesn't yet support (during …

usage: flush to DB in 1 minute intervals

---

enterprise/server/githubauth/BUILD
enterprise/server/githubauth/githubauth.go
server/backends/github/BUILD
server/backends/github/github.go

This PR fixes two issues with the current Github auth setup relating to redirects:
1) This uses the standard `Redirect-Url` redirect cookie instead of the more specific `Github-Redirect-Url` so that Github logins with a redirect_url parameter set are correctly redirected after the user logs in.
2) If Github auth is enabled, and a user hits the `/auth/github/link/` endpoint but is not already logged in - redirect them to the github login flow instead of to `/`.

Fix up github auth redirects

---

enterprise/server/remote_execution/containers/podman/podman.go

**Related issues**: https://github.com/buildbuddy-io/buildbuddy-internal/issues/2523

Add a flag that logs the output of podman pull operations

---

server/metrics/metrics.go

Less buckets in <24 hour range, more buckets in 1-7 day range.

Define custom buckets for eviction histogram.

---

server/util/approxlru/BUILD
server/util/approxlru/approxlru.go
server/util/approxlru/approxlru_test.go

Adjust eviction test to check that evicted entries are older than 95% of the remaining entries rather than strictly comparing to the oldest entry.

Fill eviction sample pool when approxlru is first created.

---

enterprise/server/oidc/oidc.go
enterprise/server/remote_execution/filecache/filecache.go
server/backends/disk_cache/disk_cache.go
server/backends/memory_cache/memory_cache.go
server/interfaces/interfaces.go
server/util/claims/claims.go
server/util/lru/lru.go
server/util/lru/lru_test.go

Make use of go generic to make LRU package type-safe.
This restricts `key`'s type from `interface{} / any` to `string`, which is what we use throughout the entire code base.
It also lets us eliminate the type switch inside `keyHash()` func, further simplifying our code.

lru: use go generic

---

.github/workflows/checkstyle.yaml
buildfix.sh
enterprise/server/remote_execution/filecache/BUILD
enterprise/server/util/chunker/BUILD
server/util/lru/BUILD

buildfix.sh produces a nonempty diff today, presumably because the CLI version in checkstyle doesn't match the one in buildfix.

Use same CLI version in buildfix and checkstyle

---

enterprise/server/remote_execution/executor/BUILD
enterprise/server/remote_execution/executor/executor.go

Before this PR, there were lots of error types that we weren't properly reporting under the `buildbuddy_remote_execution_count` metric (which has an error label) - for example, failing to resume a VM, input downloads failing, or failing to publish task status updates (due to disconnecting from the app). These are all reported properly now.

Ensure execution errors are always reported in prom metrics

---

enterprise/server/tasksize/tasksize.go
enterprise/server/tasksize/tasksize_test.go

I got this number (6MB) from running `rbeperf` against dev. That tool runs a bunch of parallel remote executions that do a trivial task (running `echo`), and measures the time and (memory and CPU) usage stats reported. A sample output of the memory usage is below, but it was pretty reproducible, especially the memory component.
I checked out the CPU usage as well and it looks like our estimate of 250milliCPU is a bit high, we could probably bump it down to about 100milliCPU. One has to hack `rbeperf` a little bit to get the rate of CPU use by dividing the total CPU used by the execution time.
All of this is subject to the measurement error in `procstats`, of which there is a bit. But it's probably good enough for a first pass at least.
```
Peak memory usage:
249856 - 831078 bytes: …
```

Add a memory constraint to the minimum task size

---

enterprise/server/remote_execution/containers/docker/BUILD
enterprise/server/remote_execution/containers/docker/docker.go
enterprise/server/remote_execution/containers/docker/docker_test.go

Our previous approach was prone to race conditions between the container
starting up and our call to `ContainerLogs` API. In the case where we call
the log API before container actually started, we get no outputs.  This
resulted in flaky tests observed in our CI.
Switch to use `ContainerAttach` API to capture the container outputs as
they are streamed out to reliably obtain the logs.

docker: use ContainerAttach to capture std{out,err}

---

enterprise/server/backends/pebble_cache/pebble_cache.go

Inactive partitions may not have any AC entries and thus nothing to sample.

During sampling, don't treat lack of groups as an error.

---

enterprise/server/remote_execution/containers/firecracker/firecracker.go

There have been an increasing number of timeouts when we try to connect to the vmexec agent inside of firecracker VMs. Extend the timeout as a stopgap until we can find and resolve the underlying problem. Slack thread [here](https://buildbuddy-corp.slack.com/archives/C0495TM9UUE/p1690566102378579)

Extend firecracker vmexec timeout

---

enterprise/app/auditlogs/auditlogs.tsx
enterprise/server/backends/authdb/authdb.go
proto/api_key.proto
proto/auditlog.proto
proto/buildbuddy_service.proto
server/buildbuddy_server/buildbuddy_server.go
server/role_filter/role_filter.go

Combined with https://github.com/buildbuddy-io/buildbuddy/pull/4351 we can switch to retrieving the API key value on demand instead of as part of the list request. This will provide more useful audit logs around API key use.

Add API to lookup a single API key.

---

proto/BUILD
proto/auditlog.proto

This fixes the complaint
```
INFO: From Generating Descriptor Set proto_library //proto:auditlog_proto:
proto/auditlog.proto:5:1: warning: Import proto/acl.proto is unused.
```
from build log.

proto/auditlog: remove unused acl deps

---

enterprise/server/cmd/ci_runner/main.go
enterprise/server/remote_execution/platform/BUILD
enterprise/server/remote_execution/platform/platform.go
server/rpc/interceptors/interceptors.go

This will apply to all `executor -> app` requests (as long as the dial is done with `grpc_client.DialTarget()`). The executor will also set an env var to set the origin header for both the "outer" workflow invocation BES stream request as well as the inner one, along with any cache requests on the inner invocation.

Add gRPC origin header

---

dockerfiles/executor_image/Dockerfile

W/o an init process there's nothing to reap zombie processes.

Add a simple init process to executor image.

---

enterprise/server/remote_execution/execution_server/execution_server.go

We think that https://github.com/buildbuddy-io/buildbuddy-internal/issues/2533 is happening because the execution is missing an invocation ID. We depend on invocation ID in order to get failed action results for a particular invocation.
This will let us know whether the request metadata is missing entirely or if bazel possibly has a bug where it sets the metadata but just doesn't set the invocation ID in some cases, or if we have a bug somehow in the way that we're extracting the invocation ID.
**Related issues**: https://github.com/buildbuddy-io/buildbuddy-internal/issues/2533

Add logging for executions missing invocation ID

---

.bazelrc

It's currently part of the `cache` config which is not used by workflows. 

Enable compression for workflows.

---

app/terminal/terminal.css

The terminal is black so currently the search result count inherits it's
color from the parent.  Make the text white so it's readable.

app/terminal: make search result count white

---

deps.bzl
go.mod
go.sum
server/testutil/testgrpc/BUILD
server/testutil/testgrpc/testgrpc.go

I'm working on a small change that allows executors to retry task update streams so that tasks aren't affected as much during app rollouts. The test proxy will help us test this, because it will let us control how RPCs are routed to apps (by RPC name). Specifically, we want to make sure that the test connects to app 1 for PublishOperation streaming, then we can kill app 1 and make sure the execution still succeeds (as it should auto-reconnect to app 2).

Add a basic grpc proxy for tests

---

enterprise/server/backends/pebble_cache/BUILD
enterprise/server/backends/pebble_cache/pebble_cache.go
enterprise/server/backends/pebble_cache/pebble_cache_test.go
proto/raft.proto

When chunking is enabled, during write, we will first attempt to
chunk it, and then compress each individual chunk, and finally encrypt the chunk
if encryption is enabled.  If the data is compressed, we will first decompress it
before we chunk it.
If there is only one single chunk, we will write the chunk inline,
similar to how we write small files inline when chunking is disabled.
If there are multiple chunks, we will write a file record in Pebble. which include
all the resource names that points to the chunks. Every chunks will be
stored inline in Pebble.
Added unit tests.
This is based on Tyler's PR:
https://github.com/buildbuddy-io/buildbuddy/pull/3457

Add cdc chunking support to PebbleCache.

---

enterprise/server/backends/authdb/authdb_test.go
server/buildbuddy_server/buildbuddy_server.go

UI will start calling GetAPIKey to retrieve the value.

Stop sending API Key value in List/GetBazelConfig APIs.

---

cli/parser/parser.go
cli/test/integration/cli/cli_test.go

`bb fix -mode diff` fails with "failed to parse startup options: invalid options syntax: -mode"

Fix `bb fix -mode diff`

---

.bazelrc

This is to address release binary size.
Stripping symbols saves us 38 MB of a current 184 MB on the executor, 47 MB of a current 222 MB on the enterprise app, and 18 MB of a current 68 MB on the FOSS app.
**Related issues**: Addresses buildbuddy-io/buildbuddy-internal#2342

Strip debug symbols for release builds

---

enterprise/app/repo/repo.tsx

In the Heroku button does this: https://devcenter.heroku.com/articles/heroku-button#adding-the-heroku-button
If template isn't set, and you're being referred from a github repo - use that github repo as the template.
This allows you to create super simple "Deploy this repo" style buttons without any param fiddling.
Also adds some logic where if a repo name isn't provided, we use the last path component of the template url.

Figure out template url and repo name if not set in repo creation flow

---

app/invocation/BUILD
app/invocation/invocation_details_card.tsx
proto/invocation.proto
server/build_event_protocol/build_event_handler/build_event_handler.go
server/build_event_protocol/build_event_handler/build_event_handler_test.go

- Omit some pattern lists which are not consumed by the UI:
- Expanded event IDs which occur in the Children list of the Started event - there will be one of these per pattern
- TestSuiteExpansions
- Truncate the Expanded event to 10KB and show a banner in the UI when truncated. A real invocation with 750K events had a total pattern length of about 13MB which was causing the All / Details tabs to take 7-8s to render when clicked, and also would be slow to load on slower connections.

Omit / truncate some pattern events from invocation

---

enterprise/server/usage/usage.go
enterprise/server/usage/usage_test.go
server/tables/tables.go

Apps no longer read this field as of https://github.com/buildbuddy-io/buildbuddy/pull/4403 which has been fully rolled out.

Stop setting `final_before_usec` column in usage rows

---

server/build_event_protocol/build_event_handler/build_event_handler.go
server/util/protofile/BUILD
server/util/protofile/protofile.go
tools/replay_invocation/BUILD
tools/replay_invocation/replay_invocation.go

For a real invocation with 750K events, this PR reduces the time spent in `LookupInvocation` from 8.0s to 2.0s (serving from a local disk blobstore on SSD, with a 16-core/32-thread AMD Ryzen CPU).
The previous code would fetch blobs using multiple goroutines, but unmarshaling would be done on a single goroutine (the caller of `ReadProto`). This created a CPU bottleneck.
In this PR, the bottleneck is addressed: the goroutine responsible for fetching a single blob now also eagerly unmarshals all the proto messages in the blob, and `ReadProto` now just returns buffered messages instead of needing to unmarshal buffered raw bytes.

Improve BufferedProtoReader throughput

---

enterprise/server/remote_execution/containers/firecracker/firecracker.go
enterprise/server/remote_execution/uffd/uffd.go
enterprise/tools/vmstart/vmstart.go

Fix a race condition where the UFFD handler is still trying to access the snapshots in the background at the same time that we're trying to merge them and save them to the cache
Also inline most of the logic from SaveSnapshot() into Pause(), so it's more clear that we're doing a lot more than just saving a snapshot (i.e. we're shutting down the VM and cleaning up resources).

[UFFD] Ensure firecracker VM and UFFD handler are shut down before saving snapshots to the cache

---

enterprise/server/remote_execution/blockio/blockio.go
enterprise/server/remote_execution/containers/firecracker/firecracker.go
enterprise/server/remote_execution/uffd/uffd.go

To optimize performance of the UFFD handler, copy an entire chunk of memory when handling page faults, as opposed to just one page. This will reduce the overhead of having to make lots of copy calls for small memory ranges
A chunk size of 1000 memory pages yielded the best performance results in my testing. Some test results:
**Without UFFD:**
Initial pause: ~1s
Subsequent pauses: ~220ms
LoadSnapshot: ~420ms
Unpause: ~420ms
**UFFD loading 1 page at a time:**
Initial pause: ~2.9s
Subsequent pause: ~2.4s
Initial LoadSnapshot: ~2s
Subsequent LoadSnapshot: ~1.3s
Initial Unpause: ~2s
Subsequent Unpause: ~1.3s
**UFFD Loading 512KB chunks:**
Initial pause: ~2.7s
Subsequent pause: ~2.3s
LoadSnapshot: ~565ms
Unpause: ~565ms
**[Chosen] UFFD Loading 1000 page chunks:**
Initial pause: ~2.7s …

[UFFD] Copy entire chunks when handling page faults with uffd handler

---

config/buildbuddy.local.yaml

Ensure that the local disk cache is used when we run the FOSS server
locally with `bazel run server`.

config: fix FOSS local config not setting up cache

---

enterprise/server/remote_execution/runner/runner.go

Attempt to take (unpause) a runner from the pool up to 5 times. If unpause fails, the runner will be removed (this is already the case today). If all 5 attempts fail, fall back to creating a fresh runner.

Don't fail execution tasks when unpause fails

---

enterprise/server/backends/authdb/authdb.go
server/tables/tables.go

Adding the unique index conditionally confuses GORM auto-migrator causing it to issue a no-op alter column statement.
To get around this, backfill the nonce column for all users before the gorm migrator runs so that it can add the unique index.

Make APIKeys nonce column unique by default.

---

enterprise/server/vmexec/vmexec.go

This missing Close() probably wasn't causing any problems, just something small I noticed while poking around various networking-related firecracker things.

Add missing Close() in clearARPCache

---

enterprise/server/remote_execution/containers/firecracker/firecracker.go

From https://github.com/firecracker-microvm/firecracker/blob/main/docs/api_requests/actions.md#intel-and-amd-only-sendctrlaltdel:
```
at boot time, the Linux driver for i8042 spends a few tens of milliseconds probing the device. This can be disabled by using these kernel command line parameters:
i8042.noaux i8042.nomux i8042.nopnp i8042.dumbkbd
```

Do less fake-keyboard probing during fc boot

---

enterprise/server/quota/quota_manager.go
enterprise/server/quota/quota_manager_test.go

- Change `newQuotaManager` so that it does not return until it has successfully established the pubsub connection, otherwise quota updates that occur before the pubsub connection is established can be lost.
- Remove the `time.Sleep` and explicitly wait for the pubsub update to propagate (via a channel)
**Related issues**: Fixes https://github.com/buildbuddy-io/buildbuddy-internal/issues/2559

Deflake quota_test

---

server/remote_cache/digest/digest_test.go

```
BenchmarkDigestCompute/SHA256/1-8                2624952               455.7 ns/op
BenchmarkDigestCompute/BLAKE3/1-8                 713340              1601 ns/op
BenchmarkDigestCompute/SHA256/10-8               2636890               463.4 ns/op
BenchmarkDigestCompute/BLAKE3/10-8                812553              1558 ns/op
BenchmarkDigestCompute/SHA256/100-8              2019846               587.7 ns/op
BenchmarkDigestCompute/BLAKE3/100-8               904671              2409 ns/op
BenchmarkDigestCompute/SHA256/1000-8              515154              2291 ns/op
BenchmarkDigestCompute/BLAKE3/1000-8              546352              3174 ns/op
BenchmarkDigestCompute/SHA256/10000-8              55933             19288 ns/op
BenchmarkDigestCompute/BLAKE3/10000-8             238008 …
```

Add digest.Compute benchmark

---

enterprise/server/quota/quota_manager.go
server/testutil/pubsub/BUILD
server/testutil/pubsub/pubsub.go

Accidentally introduced this bug in the last PR: we should `defer Close()` within the goroutine, otherwise it's closed immediately.

Fix bug with quota update pubsub being closed too early

---

app/components/spinner/spinner.css
app/invocation/BUILD
app/invocation/invocation_target_group_card.tsx
app/invocation/invocation_targets.tsx
app/invocation/target_util.tsx
app/root/root.css
server/build_event_protocol/build_event_handler/build_event_handler.go
server/build_event_protocol/event_index/BUILD
server/build_event_protocol/event_index/event_index.go
server/buildbuddy_server/buildbuddy_server.go
server/target/target.go

- Render TargetGroups as cards in the UI
- Fix a few server-side bugs
- Increase the build event limit when rendering paginated invocations.
Note: this does not yet render the artifacts card or the target page. That'll be a separate PR.

Render TargetGroups in the UI

---

enterprise/server/backends/pebble_cache/pebble_cache.go

- Start compaction sooner: L0CompactionThreshold = 2
- Start parallel compactions sooner: L0CompactionConcurrency = 2
- Raise max compactions limit: MaxConcurrentCompactions = 12
- Slow down the rate at which parallel slots are added: CompactionDebtConcurrency = 10 << 30 (10GB of compaction debt per slot)

Compaction tweaks

---

server/util/redact/redact.go
server/util/redact/redact_test.go

Explicitly redacts `EXPLICIT_COMMAND_LINE` in the BuildMetadata event so it can be rendered in the UI with `<redacted>` for any command line options that should be redacted.
In all other events, it's just dropped so we don't have to deal with parsing it.
Fixes: https://github.com/buildbuddy-io/buildbuddy-internal/issues/2540

Redact `EXPLICIT_COMMAND_LINE`

---

cli/watcher/BUILD
cli/watcher/watcher.go

ibazel does this too: https://github.com/bazelbuild/bazel-watcher/blob/1f4db7637dbfd00a9e66eea6920bfb42f403ee0c/cmd/ibazel/main_unix.go#L43

Bump open file limit in CLI if `--watch` flag is used

---

enterprise/server/cmd/goinit/main.go

Keep the docker socket around when enabling docker over tcp.
Some tests use both (tcp and socket), and we don't gain much from removing the socket when this flag is set.

Keep the docker socket around when we enable docker over tcp

---

server/remote_cache/content_addressable_storage_server/content_addressable_storage_server.go

I went back and found some logs indicating that we were throwing away "incomplete" tree cache entries that were incomplete only because they lacked the empty digest, which is fine. This CL fixes that.
Sample log:
```
incomplete tree: (missing digest: "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"), allDigests: map[00a89f8681f48b389a .... etc
```

Allow the tree cache to work even if it's missing the empty digest

---

app/invocation/BUILD
app/invocation/invocation_target_group_card.tsx
app/invocation/invocation_targets.tsx
app/invocation/target_util.tsx
app/target/target.tsx
app/target/target_v2.tsx
app/util/proto.ts
server/build_event_protocol/event_index/BUILD
server/build_event_protocol/event_index/event_index.go

* Fix missing timing and rule type metadata on target page
* Tweak the `endTime` calculation to avoid rounding errors (I noticed this because the timestamp rendered in V1 is different than V2 by a millisecond, which seemed significant enough to fix).
* Don't report TestSummary events when status == 0 (NO_STATUS), otherwise these appear as failed tests which is confusing. So far, I've only seen NO_STATUS when the test is aborted due to an unrelated target in the invocation failing.
* Fix build time duration not being rendered in listing (for now, we'll just use the time between the Configured -> Completed events being published).
* Fix FAILED_TO_BUILD label in target listing card ("failed" -> "failed to build").
* Fix SKIPPED targets card not rendering (need to handle the Aborted event). …

Fix misc bugs with paginated invocations / targets

---

enterprise/server/backends/pebble_cache/pebble_cache_test.go

**Related issues**: https://github.com/buildbuddy-io/buildbuddy-internal/issues/2553
1. increase the number of attemps when we check whether unencrypted digest is
evicted in the test.
2. Add some logging
Note: I was not able to reproduce running locally with --run_per_test=1000, or
run it remotely with --run_per_test=100.

pebble_cache_test/TestSampling:increase the time when we wait for the unencrypted digest to evict.

---

enterprise/app/sidebar/sidebar.tsx

Fixes: https://github.com/buildbuddy-io/buildbuddy-internal/issues/2569

Always expand sidebar if account picker is expanded

---

server/build_event_protocol/event_index/event_index.go

Fixes these 2 little chips not showing up for Test targets (they were rendering correctly for build targets, just not test targets)

Fix missing Test target metadata in target v2 page

---

deps.bzl
enterprise/server/cmd/goinit/main.go

This seems to fix segfaulting issues in Brandon's repro script on my test setup (a c2 machine running 20.04 / 5.15 on the host and the 20.04 workflows image on the guest).
Do we want to flag guard this? probably?  It's basically as easy to roll back as it is to flag guard though, so I dunno. I'd like to wait to merge this until later this week so that it can have longer to bake, which I guess is just another reason to flag guard it.

upgrade vm kernel image to 5.15

---

enterprise/app/tap/tap.tsx

Add the missing `targetStatus` param (this is needed so we know whether to show the build or test status for the label).

Fix target v2 link from test grid

---

app/invocation/BUILD
app/invocation/invocation.tsx
app/invocation/invocation_artifacts_card.tsx
app/invocation/invocation_target_group_card.tsx
app/invocation/invocation_targets.tsx
proto/target.proto
server/target/target.go

* Search both file paths and target labels. If at least one file path is matched, only show the matched files within the target. Otherwise if only the label is matched, show all files under the label. (This is the behavior today.)
* Change the icon to "ArrowDownCircle" to match the old artifacts card.
* Slightly reduce the debounce duration from 300 -> 200 (300 felt a bit too unresponsive).

Tweaks / fixes for artifact search

---

app/invocation/BUILD
app/invocation/invocation.css
app/invocation/invocation.tsx
app/invocation/invocation_error_card.tsx
app/invocation/invocation_model.tsx
server/build_event_protocol/event_index/event_index.go

Invocation: https://app.buildbuddy.dev/invocation/936ea81e-f90e-4296-a3f7-fbeec5dfdb66
Before (we have to scroll up in the logs to see the root cause):
After:

Surface action failure details at top of invocation page

---

enterprise/server/remote_execution/containers/podman/BUILD
enterprise/server/remote_execution/containers/podman/podman.go
server/util/log/log.go

* When `podman_pull_log_level` is set, don't drop stderr from the error message returned back to bazel. This was happening in dev only. The reason this was happening is that if `stdio.Stderr` is non-nil then stderr will not be buffered in the pullResult, and instead only streamed to `stdio.Stderr`.
* Use new `CtxWriter` so we can associate the pull logs with task ID.
**Related issues**: https://github.com/buildbuddy-io/buildbuddy-internal/issues/2572

Fix podman pull error handling

---

tools/enable_local_firecracker.sh
tools/install_firecracker.sh

When running firecracker locally (i.e. not on an executor), after updating the firecracker/jailer version in `deps.bzl`, we have to copy the new `firecracker` / `jailer` binaries to `/usr/local/bin/`. This PR makes it so that `enable_local_firecracker.sh` does this automatically.
A future improvement would be to check whether the firecracker/jailer SHA256 located in PATH matches the one bundled in vmsupport, and if not, then fail the action with a loud error saying that the one in PATH needs to be updated. Otherwise, it's really easy to run the executor with an outdated firecracker/jailer version and then be unknowingly testing the wrong thing.

Copy firecracker/jailer from deps.bzl as part of enable_local_firecracker.sh

---

proto/quota.proto
proto/target.proto
proto/user.proto
server/role_filter/BUILD
server/role_filter/role_filter_test.go

Fixes a bug that GetTarget does not work in impersonation mode.
More generally, some things like role_filter / impersonation / selected group ID depend on the request context being set, so make sure we set it everywhere.
Add missing request / response context fields and a test to make sure we can't forget in the future.

Add missing request/response context fields

---

deps.bzl
go.mod
go.sum

Update fastcdc-go dep to v0.2.0-rc2 which includes some performance improvement

Update fastcdc-go dep to v0.2.0-rc2

---

enterprise/server/remote_execution/dirtools/dirtools.go

We already do this for blobs downloaded via cachetools -- this just applies the same check in dirtools/batch downloads.

Verify batch downloaded digests

---

server/endpoint_urls/build_buddy_url/build_buddy_url.go
server/util/cookie/BUILD
server/util/cookie/cookie.go
server/util/subdomain/subdomain.go
server/util/url/url.go

Set domain on cookies to allow cookies to be shared across subdomains and domain. Auth flow will happen on the domain auth endpoint and redirect back to the subdomain after auth.

Allow oauth login to work for subdomains.

---

enterprise/server/backends/pebble_cache/pebble_cache.go

We call cdcw.Close() at the start of the C[ommit function](https://github.com/buildbuddy-io/buildbuddy/blob/6f2da2755192a8e309c709947629c326745a841d/enterprise/server/backends/pebble_cache/pebble_cache.go#L1879) to wait until the chunker finished processing. However, previously we also closed the db. in cdcw.Close(). This means that we are closing the db before the file-level metadata is written. When Pebble Cache stops, it waits for the leaser to close and then close the edits channel. So in this case, we can send size updates after the edits channel closed.

Remove unused db in cdcw

---

enterprise/app/code/code.tsx
enterprise/server/hostedrunner/hostedrunner.go
proto/runner.proto

This matches the new async option in the `ExecuteWorkflowRequest` and allows clicking run button to immediately take you to the invocation page (with a queued message) instead of having a button that feels unresponsive.
Also populates the repoState.branch value which is now required.

Add async option to RunRequest

---

enterprise/server/workflow/service/service.go

This is an error case where the `WorkflowConfigured` event was not received, so we can't lump these runs together.

don't show workflow runs for empty patterns.

---

server/util/flagutil/yaml/yaml.go

Missing arg was failing to format the error string when i failed to type my yaml properly.

Make RetypeAndFilterYAMLMap properly print format string for invalid maps

---

enterprise/server/cmd/ci_runner/main.go
proto/build_event_stream.proto

This makes it so that misconfigured and unknown workflows are still logged.
We should probably rename WorkflowConfiguredEvent because the workflow isn't configured yet when this is published, but that can be done separately.

publish WorkflowConfiguredEvent a smidge sooner

---

enterprise/app/workflows/action_list.tsx
enterprise/app/workflows/workflows.css

fix width of title workflow history so that the status charts always line up.

---

enterprise/server/test/webdriver/shortcuts/BUILD
enterprise/server/test/webdriver/shortcuts/shortcuts_test.go

This PR makes a few small changes to make shortcuts_test.go not flaky anymore:
- Increases the size from small to medium because it was timing out about one time in 50.
- Adds a check that there are indeed three invocations in the test that exercises the history page navigation shortcuts, this was causing lots of failures later in the test previously, so this makes it a little bit more obvious that it's not a problem navigating between invocations but a problem that there are not as many invocations as expected.
- Sets an API key for invocations run against the test server. Without this _some_ invocations aren't correctly recorded. I didn't dig into why it only happens some times.
- And finally, removes the manual tag from the test so it can run in CI.
Here's a link with 100/100 runs …

De-flake shortcuts_test.go

---

enterprise/server/cmd/ci_runner/main.go

Disables the git credential helper for `git fetch`. It's unclear why sometimes we are getting 'invalid username or password' on certain `git fetch` commands, but this PR will let us rule out whether it's because of the cred helper.

Disable credential helper for 'git fetch'

---

tools/metrics/grafana/dashboards/buildbuddy.json

1. Fix dashboard for not found error count
2. Add a dashboard for double read hit count and percentage of important
artifacts missing.

Add more dashboards for cache migration

---

tools/metrics/grafana/dashboards/buildbuddy.json

Show the ration of double read hit to missing count for all cache request type
instead of just reader.

improve cache migration dashboard

---

server/buildbuddy_server/BUILD
server/buildbuddy_server/buildbuddy_server.go

This will make org.domain.com/join work the same as domain.com/join/org

Allow GetGroup to return group info for the current subdomain.

---

WORKSPACE
enterprise/server/gcplink/BUILD
enterprise/server/gcplink/gcplink.go
enterprise/server/oidc/BUILD
enterprise/server/oidc/oidc.go

We request the GCP scope if the `link_gcp_for_group` url param is set in the auth flow.
If this param is set, we create secrets with the account email and refresh tokens.

Allow users to optionally link a GCP account

---

server/remote_cache/content_addressable_storage_server/content_addressable_storage_server.go

Cache things with >=3 descendants instead of requiring 10 descendants.

Use tree cache more

---

enterprise/server/remote_execution/containers/firecracker/firecracker.go
enterprise/server/remote_execution/containers/firecracker/firecracker_test.go
enterprise/server/remote_execution/filecache/filecache.go
enterprise/server/remote_execution/snaploader/snaploader.go
server/interfaces/interfaces.go

This fixes a race condition with local snapshot sharing (described at https://github.com/buildbuddy-io/buildbuddy/pull/4532) and will be needed for remote snapshot sharing
It also adds unit test coverage to ensure that when UFFD is enabled, the snaploader doesn't overwrite memory snapshot files it shouldn't

[Firecracker] Add support to compute full digest of snapshot files

---

enterprise/server/backends/authdb/authdb_test.go
server/buildbuddy_server/buildbuddy_server.go
server/endpoint_urls/build_buddy_url/build_buddy_url.go
server/util/subdomain/BUILD
server/util/subdomain/subdomain.go
server/util/subdomain/subdomain_test.go
server/util/urlutil/urlutil.go

This avoids incorrectly applying subdomain checks for internal traffic (i.e. distributed cache RPCs)

Limit subdomain check to buildbuddy URL domain.

---

enterprise/server/util/cacheproxy/cacheproxy.go

If the distributed cache peer closes the stream with an error, this will return the error from the peer instead of io.EOF

Propagate error in distributed write.

---

app/invocation/BUILD
app/invocation/invocation.css
app/invocation/invocation_error_card.tsx

Before (not super useful for compilation failures):
After:

Display stderr and some additional info for failed actions

---

enterprise/server/remote_execution/blockio/blockio.go
enterprise/server/remote_execution/uffd/uffd.go

In my local testing this fixes the "possible stuck request" issue that we've seen with `firecracker_test_blockio`.

Fix UFFDIO_COPY size within last memory chunk

---

enterprise/server/remote_execution/nbd/nbdserver/nbdserver.go
server/util/grpc_server/grpc_server.go

This interceptors add too much noise to the logs and (probably) add unnecessary overhead to each I/O operation. The nbdserver is sort of an "implementation detail" of the executor and not exposed externally, so we don't get much benefit from using the common interceptors.

Don't use common interceptors for nbdserver

---

enterprise/server/remote_execution/platform/platform.go
enterprise/server/remote_execution/platform/platform_test.go

Currently we parse env-overrides request headers with `,` to separate
between different pair of variable's name and value. This approach works
for simple value string but when folks want to pass a JSON containing
commas characters within, the parse would fail.
Provide `env-overrides-base64` as a work around for more complex values.
User could encode the `k=v` pair in base64 and pass it to the new
header. Our server will attempt to decode the pair and append it to
existing overrides.

platform: allow env-overrides in base64

---

app/auth/auth_service.ts

Having the group ID in a cookie will allow group switching to work properly between subdomain and app w/o having to resort to additional hacks.

Store selected group ID in cookie instead of local storage.

---

enterprise/server/remote_execution/containers/firecracker/BUILD
enterprise/server/remote_execution/containers/firecracker/firecracker_test.go

Also de-flake `TestFirecrackerExec_Timeout_DebugOutputIsAvailable`, which was failing more often on the blockio variant of the test.

Re-enable firecracker_test_blockio on CI

---

server/api/common/common.go
server/build_event_protocol/event_index/event_index.go

If we have a TestResult event for a given label but we haven't yet gotten the TestSummary (because the test is still running), make sure we show a target status in the invocation page. This will let users see failed test results sooner, which is useful for longer running tests with multiple shards / attempts.
**Related issues**: Fixes https://github.com/buildbuddy-io/buildbuddy-internal/issues/2606

Show partial test results in the invocation page

---

deps.bzl
enterprise/server/cmd/executor/BUILD
go.mod
go.sum

This version has a few important fixes:
- https://github.com/buildbuddy-io/soci-snapshotter/pull/8
- https://github.com/buildbuddy-io/soci-snapshotter/pull/10
I'm hoping to finish up the work to run the store in-process in the executor, making this process obsolete, but I think the two fixes above are important enough to go ahead and do this upgrade without waiting for that.

Upgrade soci-store version to 0.0.6

---

app/auth/auth_service.ts
enterprise/app/org/create_org.tsx
enterprise/app/org/join_org.tsx
enterprise/app/settings/github_complete_installation.tsx
enterprise/app/sidebar/BUILD
enterprise/app/sidebar/sidebar.tsx
proto/grp.proto
server/buildbuddy_server/buildbuddy_server.go
server/util/claims/BUILD
server/util/claims/claims.go

The previous UX was not great as it made switching groups difficult.
Now the group picker works and redirects to the appropriate subdomain, if necessary.
Create org also works on subdomain and redirects to the new URL after creation.

Rework group picker behavior on subdomains.

---

deps.bzl
enterprise/server/cmd/executor/BUILD
go.mod
go.sum

Reverts buildbuddy-io/buildbuddy#4657 due to crashlooping: https://metrics.buildbuddy.dev/?orgId=1&refresh=1m&var-region=us-west1&var-window=1m&var-job=All&var-pool=executor&var-kubepool=All&var-kubenode=All&var-quantile=0.5&var-partition_id=All&viewPanel=5615

Revert "Upgrade soci-store version to 0.0.6"

---

app/router/router.tsx
server/buildbuddy_server/buildbuddy_server.go

Since we're no longer filtering groups on subdomains, we can no longer use the group list to determine whether the subdomain exists.
Instead check whether there is a selected group ID and don't set a selected group on a subdomain if the subdomain doesn't match any group user has access to.

Update subdomain existence check.

---

deps.bzl
enterprise/server/cmd/executor/BUILD
go.mod
go.sum

This version has a few important fixes:
- https://github.com/buildbuddy-io/soci-snapshotter/pull/8
- https://github.com/buildbuddy-io/soci-snapshotter/pull/10
- https://github.com/buildbuddy-io/soci-snapshotter/pull/11
I'm hoping to finish up the work to run the store in-process in the executor, making this process obsolete, but I think the two fixes above are important enough to go ahead and do this upgrade without waiting for that.
This is a second attempt at https://github.com/buildbuddy-io/buildbuddy/pull/4657
I'll manually push this to dev before submitting to test this time :-P
Related issues: N/A

Upgrade soci-store version to v0.0.7

---

enterprise/server/tasksize/tasksize.go
enterprise/server/tasksize_model/tasksize_model.go

I left these as comments in https://github.com/buildbuddy-io/buildbuddy/pull/4650 but accidentally auto-merged.

Downgrade a few recently added logs to INFO level

---

enterprise/server/remote_execution/containers/firecracker/BUILD
enterprise/server/remote_execution/containers/firecracker/firecracker.go
enterprise/server/remote_execution/containers/firecracker/firecracker_test.go
enterprise/server/remote_execution/snaploader/snaploader.go

Building off of https://github.com/buildbuddy-io/buildbuddy/pull/4532 and https://github.com/buildbuddy-io/buildbuddy/pull/4574, this PR makes it so that runners can start from snapshot without having to be matched to a runner in the runner pool.

Allow new firecracker runners to start from snapshots

---

app/components/digest/digest.tsx
app/invocation/BUILD
app/invocation/invocation.css
app/invocation/invocation_action_card.tsx
app/invocation/invocation_action_input_node.tsx
proto/buildbuddy_service.proto
proto/cache.proto
server/buildbuddy_server/BUILD
server/buildbuddy_server/buildbuddy_server.go
server/environment/environment.go
server/remote_cache/content_addressable_storage_server/BUILD
server/remote_cache/content_addressable_storage_server/content_addressable_storage_server.go
server/remote_cache/digest/digest.go
server/remote_cache/directory_size/BUILD
server/remote_cache/directory_size/directory_size.go
server/role_filter/role_filter.go

This is a little easier to parse than the current setup, which only shows the directory proto size.
The code for this is a little involved because I avoided holding the entire GetTree response in memory.  I try to clean up pending state as we finish calculating the size of directories.  Basically we just hold a few maps and then we only send a map from digest to size at the end.  This definitely saves memory because, if nothing else, we only hold the FileNode protos in memory while processing their containing directory.
Note that this sometimes shows *inflated* sizes because it will count the same file as many times as it appears (for example, the screenshot below shows `node` and `npm` in multiple places--the actual download size for this action was 150MB).  I don't think there's a great …

show input directory *total* sizes on action page

---

enterprise/server/backends/migration_cache/migration_cache.go

When we compare the bytes we read from src and dest in migration cache, it's
possible that we read the all the contents from the source but not from the
dest. This could be the case in the newChunkedReader in pebble cache, where we
pipe the chunks in a seperate go routine. 
Use io.ReadFull to read from dest cache.

Migration Cache: Ensure we read the same number of bytes from src and dest

---

enterprise/server/backends/distributed/distributed.go
enterprise/server/backends/pebble_cache/pebble_cache.go
enterprise/server/raft/cache/cache.go

This fixes an issue where GetCacheMetadata was failing because the provided ResourceName didn't have a digest hash function set.
In the future, GetCacheMetadata should be updated to explicitly provide a HashFunction, but this code still shouldn't ignore the side effects of ResourceNameFromProto.

use output from ResourceNameFromProto to fill DigestFunction in FileRecords

---

enterprise/server/cmd/ci_runner/main.go
enterprise/server/cmd/executor/BUILD
enterprise/server/cmd/executor/executor.go
enterprise/server/cmd/executor/executor_unix.go
enterprise/server/cmd/executor/executor_windows.go

Replace the os-specific syscall in ci_runner and executor by using an os-specific source file, or by switching to an alternative implementation.

ci_runner,executor: remove os-specific syscall

---

docs/secrets.md

Provide documentation for the env-overrides headers as a way to supply
ephemeral secrets to builds.

docs: document env-overrides* headers

---

WORKSPACE

Upgrade rules_go to latest commit in `master` at the moment of writing.
Unblocks Go 1.21 upgrade in #4516 by including the fixes in:
- https://github.com/bazelbuild/rules_go/pull/3660
- https://github.com/bazelbuild/rules_go/pull/3666

rules_go: upgrade to latest commit

---

enterprise/server/backends/pebble_cache/pebble_cache.go
proto/raft.proto

add a enum in FileMetadata to indicate whether an entry is for a complete file or for a chunk that is part of a larger file. 
In writeMetadata, we only record the metric if FileMetadata indicates that it's a complete file. If it consists of multiple chunks, we sum up the size of all the chunks, and use that when we record DiskCacheAddedFileSizeBytes.

record the size of artifact instead of the chunk size in DiskCacheAddedFileSizeBytes

---

enterprise/server/raft/replica/BUILD
enterprise/server/raft/replica/replica.go
enterprise/server/raft/replica/replica_test.go
enterprise/server/raft/store/BUILD
enterprise/server/raft/store/store.go
enterprise/server/raft/store/store_test.go

This makes splits simpler because data does not need to move around; only pointers need to be updated.

Use a single pebbleDB for all ranges rather than one per range

---

cli/fix/typescript/typescript.go

`import pkg` causes us to panic because we assume `import stuff from pkg` format. The panic happens because `stuff` is nil in the former case.

Fix unqualified imports in bb fix

---

enterprise/server/remote_execution/containers/podman/podman.go

We initially decided to report streamable images as cached locally because we didn't think they'd need to be pulled. This turned out to be wrong, we have to pull them to populate local layer information, though the pull is fast. I suspect that incorrectly reporting them as cached is causing us to incorrectly not run `podman pull` in circumstances where we should be doing so.
Practically, this does not matter because if the image hasn't been pulled during the executors lifetime, the cache authenticator won't know about it and will force a repull here: https://github.com/buildbuddy-io/buildbuddy/blob/cf05b786a85e65c5d6e6d482891986adb73d5488/enterprise/server/remote_execution/container/container.go#L254  but this unexpected behavior could cause a bug if anyone ever changes that logic. …

Don't report streamable images as cached

---

enterprise/server/remote_execution/containers/podman/podman.go

Without this flag, we see up to a few seconds of extra latency per action when running lots of actions concurrently. It can take up to 8 seconds to run `sleep 1` :open_mouth: to fix this, we need to set _both_ `--transient-store` and `--net=none`. This PR sets `--transient-store` on all actions, and separately we'll try to migrate users onto setting `dockerNetwork=off` in their actions.
See https://github.com/containers/podman/issues/19824

Use transient store for podman actions

---

enterprise/server/saml/BUILD
enterprise/server/saml/saml.go
server/util/cookie/cookie.go

Uses a modified version of samlsp.CookieRequestTracker that sets cookies with a domain value that allows the cookies to be visible both on app.buildbuddy.io and foo.buildbuddy.io
Wraps the samlsp.CookieSessionProvider with similiar functionality. New cookies will have domain set such that cookies will be visible on both app.buildbuddy.io and foo.buildbuddy.io. The wraper will also clear out old cookies with the old domain value.

Make SAML login work on subdomains.

---

enterprise/server/remote_execution/containers/podman/podman.go

This PR expands the image cleanup logic used to clean up podman images affected by https://github.com/containers/storage/issues/1136 to also apply to images affected by https://github.com/buildbuddy-io/buildbuddy-internal/issues/2570. This will not fix the latter bug, but it should ensure that subsequent actions have a better chance of succeeding because they'll re-pull the image and, I hope, correct the race that's causing the bug.
**Related issues**: https://github.com/buildbuddy-io/buildbuddy-internal/issues/2570q

Remove podman images that hit the input/output error bug

---

enterprise/server/remote_execution/containers/podman/podman.go

Reverts buildbuddy-io/buildbuddy#4694 because it seems to cause errors like this:
```
Error: creating container storage: parsing named reference "1b696e3c115a1a1baa7fc1554e466ff2feeadc807888722e7ce71b7bb2792cde": invalid repository name (1b696e3c115a1a1baa7fc1554e466ff2feeadc807888722e7ce71b7bb2792cde), cannot specify 64-byte hexadecimal strings
```

Revert "Remove podman images that hit the input/output error bug"

---

cli/picker/picker.go
cli/test/integration/cli/cli_test.go

In case where Bazel target patterns are provided via a flag instead of
args, don't use our picker.

cli/picker: skip using picker when some flags are provided

---

enterprise/server/remote_execution/containers/firecracker/firecracker.go
enterprise/server/remote_execution/snaploader/snaploader.go
enterprise/server/remote_execution/snaploader/snaploader_test.go

Otherwise if the disk is say 20GB, we are potentially burning through 20GB worth of digest CPU computations on every VM run even if only a few MB worth of files changed.

Avoid recomputing digests for unchanged snapshot chunks

---

enterprise/server/cmd/executor/BUILD
enterprise/tools/run_executor_image.sh

Analogue of https://github.com/buildbuddy-io/buildbuddy-internal/pull/2536/files but for the release image.
Also updates the `run_executor_image` script since `container_image` targets cannot be run directly, like `go_image` targets can.

Run the executor under tini in the release image too.

---

deps.bzl
enterprise/server/cmd/executor/BUILD
go.mod
go.sum

This includes one new change: https://github.com/buildbuddy-io/soci-snapshotter/pull/12
**Related issues**: [2570](https://github.com/buildbuddy-io/buildbuddy-internal/issues/2570)

Upgrade soci-store to v0.0.8

---

enterprise/server/backends/migration_cache/migration_cache_test.go
enterprise/server/backends/pebble_cache/pebble_cache.go

Delete the code to sort the input resources in GetMulti. This causes a race 
condition when we are migrating from one pebble cache to another.  
Also, switched to use pebble cache in migration_cache_test.

Fix a race condition in pebble cache GetMulti

---

enterprise/server/remote_execution/containers/docker/docker.go

ContainerAttach does not respect the passed context. The returned reader will not be closed if the context times out, preventing the output copying goroutine from ever finishing.

Fix timeout not working for docker actions.

---

enterprise/server/backends/pebble_cache/pebble_cache.go

There are some bad entries in pebble cache in dev when cdc is enabled where the
number of chunks in storage metadata is zero and inlineMetadata is nil.
Add logging and return error in commit function so we can catch them earlier.

return error on commit when the number of chunks in storageMetadata is smaller than 1.

---

.github/workflows/checkstyle.yaml
WORKSPACE

For more information: https://go.dev/blog/go1.21

go: upgrade to 1.21

---

docs/troubleshooting-rbe.md

This was one of the issue came up recently when a customer of ours try
to connect to us through an EC2 instance backed by AWS NAT Gateway.
It's a known issue that NAT Gateway enforce connection drop after 350
seconds idling. (1)
(1): https://docs.aws.amazon.com/vpc/latest/userguide/nat-gateway-troubleshooting.html#nat-gateway-troubleshooting-timeout

docs/troubleshooting-rbe: add TCP connection tunning

---

website/src/components/integrations/integrations.module.css
website/src/components/integrations/integrations.tsx
website/src/css/common.module.css

* Center the "BuildBuddy integrates with" heading (it looks a tad awkward left-aligned)
* Use `text-wrap: balance` so titles like "BuildBuddy is enterprise Bazel" render like "BuildBuddy is / enterprise Bazel" instead of "BuildBuddy is enterprise / Bazel" (the "Bazel" felt a tad awkward sitting on its own line)

Minor tweaks to main page headings

---

enterprise/server/invocation_stat_service/invocation_stat_service.go

I'm not seeing an appreciable difference in performance for this.  I'll fix the axis / timestamp rendering in the frontend separately (this is flag-guarded)
Before: <img width="1422" alt="Screenshot 2023-09-06 at 11 11 25 PM" src="https://github.com/buildbuddy-io/buildbuddy/assets/10570856/738c9627-7969-431a-8e90-9cb3713b7241">
After: 

add backend support for smaller time increments in drilldowns.

---

deps.bzl
go.mod
go.sum

Pulling in the changes from https://github.com/Merovius/nbd/pull/21

Update NBD lib to fix 100ms delay when unmounting workspace drive

---

enterprise/app/trends/drilldown_page.tsx
enterprise/app/trends/heatmap.tsx
enterprise/app/trends/trends.css

This  changes rendering when the feature is off a teensy bit, but it still works just fine.  Seems better to just rely on what the server sends.

Add frontend support for labeling smaller time intervals in drilldowns.

---

enterprise/server/backends/authdb/authdb.go
enterprise/server/backends/authdb/authdb_test.go

Actually persist the new API key attributes.
