- .editorconfig
Tab size is generally not an issue except for multiline raw string literals which gofmt doesn't touch.
---
> [public] Add .editorconfig file to get consistent tab size between editors & GitHub.

- deps.bzl
We use it in a test and new bazel release no longer makes files
executable by default.
---
> Mark bazel binary dependency as executable.

- enterprise/server/backends/distributed/distributed.go
- enterprise/server/backends/distributed/distributed_test.go
- enterprise/server/backends/pubsub/BUILD
- enterprise/server/backends/pubsub/pubsub.go
- enterprise/server/backends/redis_cache/BUILD
- enterprise/server/backends/redis_cache/redis_cache.go
- enterprise/server/util/redisutil/BUILD
- enterprise/server/util/redisutil/redisutil.go
- server/config/config.go
- server/environment/BUILD
- server/environment/environment.go
- server/real_environment/BUILD
- server/real_environment/real_environment.go
Separate Cache & Remote Execution Redis clients and configs.
- Introduced a new 'redis_target' config option in the
'remote_execution' config. Falls back to the cache redis target if not
set.
- Redis clients are initialized centrally and stored in the environment
instead of passing around the Redis targets.
---
**Version bump**: None 
Part of addressing buildbuddy-io/buildbuddy-internal#350
> [public] Consolidate redis client creation.

- server/build_event_protocol/target_tracker/target_tracker.go
Flush later -- waiting until workspace status ensures we have the repoURL. Be more lenient in checking target state to account for bazel event ordering: only check a target has reached atleast a certain state. Finally, only look at test target states, not all target states.
> Fix test target dashboard

- enterprise/server/backends/distributed/distributed.go
- enterprise/server/backends/distributed/distributed_test.go
- server/config/config.go
Allow setting the nodeset manually via config. Remove a healthcheck that could fail when not all nodes were already running; preventing a newly turnt-up cluster from becoming healthy.
> Allow static nodeset + remove distributed cache healthcheck

- server/config/config.go
- server/libmain/BUILD
- server/libmain/libmain.go
- server/util/log/BUILD
- server/util/log/log.go
This CL imports the zerolog library and configures it. It also makes available leveled log convenience functions in util/log -- which I intend to use to replace "log" in all our files in a followup CL.
level is configurable via config file or flag.
structured logging similarly, and should work nicely on GCS.
> Start using zerolog for logging

- enterprise/server/util/cacheproxy/BUILD
- enterprise/server/util/cacheproxy/cacheproxy.go
Don't log access to distributed cache as frequently. Use pointer to local cache if doing a remote-{read,write,contains} from same node. Disambiguate HTTP handler paths.
> Small distributed cache performance improvements.

- server/testutil/testauth/testauth.go
- server/testutil/testenv/BUILD
- server/testutil/testenv/testenv.go
* Update the test authenticator to get and set `x-buildbuddy-jwt` in the authenticated context, treating the value as just the user ID in the `testUsers` map. This is needed because the execution server directly reads the JWT using the literal string `x-buildbuddy-jwt` and stores it in the execution tasks table.
* Update the test env to use the common RPC filters, so that the x-buildbuddy-jwt in the context is automatically copied to the outgoing GRPC metadata.
---
> Update test infra to support RBE auth patterns

- server/remote_cache/cachetools/cachetools.go
We overwrote `err` from the input read with the `err` from the stream
send. At the end of the upload we would spin loop sending empty "finish
upload" requests until the server closed the stream.
---
> Fix bug in streaming uploads that caused us to flood server with empty messages.

- enterprise/server/backends/distributed/distributed.go
- enterprise/server/backends/distributed/distributed_test.go
Use http.Server.Shutdown(ctx) instead of http.Server.Close().
> Gracefully shutdown distributed disk HTTP server

- server/util/log/log.go
Part of addressing buildbuddy-io/buildbuddy-internal#396
---
> Add an API to create subloggers that have the same API as the rest of log calls.

- server/testutil/bazel/bazel.go
It was using relative paths when `mkdir -p` for the files to be created inside the workspace, which doesn't work because the test CWD is different from the workspace dir. Existing tests aren't affected by this bug because they create all files in the root of the workspace which doesn't require creating any directories.
---
> Fix bug with MakeTempWorkspace util

- server/backends/disk_cache/disk_cache.go
- server/util/disk/disk.go
The action cache does not guarantee that the digest will reflect the size of the stored data,
so our cache implementations should not use the digest to determine size.
---
> Cache should not use digest to get size of item

- enterprise/server/backends/distributed/distributed.go
The idea is to prefer local in-memory lookups to prevent HTTP traffic, and also to randomize nodes to that load is more evenly spread, even on large / popular keys.
> Randomize distributed peers and prefer localhost.

- BUILD
- buildfix.sh
- bundle.go
- enterprise/server/backends/distributed/distributed.go
- server/cmd/buildbuddy/BUILD
- server/environment/environment.go
- server/libmain/BUILD
- server/libmain/libmain.go
- server/real_environment/real_environment.go
- server/static/BUILD
- server/static/static.go
- server/version/version.go
When static file paths are set to empty string, enable serving files out of the bundle.
> Enable static file bundling in the OS server

- enterprise/server/backends/distributed/distributed.go
- enterprise/server/util/cacheproxy/BUILD
- enterprise/server/util/cacheproxy/cacheproxy.go
- enterprise/server/util/cacheproxy/cacheproxy_test.go
- proto/BUILD
- proto/distributed_cache.proto
Redid the cacheproxy code with gRPC. It ended up being clearer, less code, and faster. This also enables us to hook into prometheus metrics + jwt forwarding for 'free'.
DDisk performance numbers before and after:
GRPC
BenchmarkSet/DDisk10-12      	    4065	    321699 ns/op	   0.03 MB/s	   14683 B/op	     284 allocs/op
BenchmarkSet/DDisk100-12     	    4015	    330311 ns/op	   0.30 MB/s	   14908 B/op	     284 allocs/op
BenchmarkSet/DDisk1000-12    	    4080	    330088 ns/op	   3.03 MB/s	   17790 B/op	     284 allocs/op
BenchmarkSet/DDisk10000-12   	    3400	    365825 ns/op	  27.34 MB/s	   45561 B/op	     284 allocs/op
BenchmarkGet/DDisk10-12      	    5481	    217092 ns/op	   0.05 MB/s	   45386 B/op	     243 allocs/op
BenchmarkGet/DDisk100-12     	    5373	    219005 ns/op	   0.46 MB/s …
> Use gRPC for cacheproxy.

- .github/workflows/docs.yaml
- website/blog/buildbuddy-joins-y-combinator.md
- website/blog/buildbuddy-v1-0-6-release-notes.md
- website/blog/buildbuddy-v1-1-0-release-notes.md
- website/blog/buildbuddy-v1-2-1-release-notes.md
- website/blog/buildbuddy-v1-3-0-release-notes.md
- website/blog/buildbuddy-v1-4-0-release-notes.md
- website/blog/buildbuddy-v1-5-0-release-notes.md
- website/blog/buildbuddy-v1-8-0-release-notes.md
- website/blog/introducing-buildbuddy-v1.md
- website/blog/meet-buildbuddy.md
- website/blog/welcoming-george-li-head-of-sales.md
- website/docusaurus.config.js
This will make it easier for anyone to contribute BuildBuddy blog posts.
Things left to do after this change:
- Configure blog.buildbuddy.io ssl cert
- Figure out root domain redirection
- Some styling tweaks
- Migrate images for old posts (this can wait until we fully want to shutdown the webflow site).
- Redirect webflow blog to point at this new blog
- Configure canonical urls
---
> First pass at migrating buildbuddy blog to GitHub

- app/components/button/button.css
- enterprise/app/workflows/BUILD
- enterprise/app/workflows/github_import.tsx
- enterprise/app/workflows/workflows.css
- enterprise/app/workflows/workflows.tsx
- static/image/arrow-right.svg
- static/image/check.svg
- static/image/chevrons-down.svg
If the currently selected group has a GitHub account linked, we show the user a list of their GitHub repos (which they can import with one-click). Previously, we would make them fill out a form.
If the user doesn't see one of their GitHub repos in the list, or wants to import from BitBucket / GitLab, they can still access the form using "Import from another Git provider" at the bottom of the GitHub repo list.
Screenshot:
TODO (future PRs):
* Add a "configure" button to the workflows view that sends the user to a nice URL with a pre-configured `buildbuddy.yaml` (or just link to docs for Git providers that don't support `/new` URLs like GitHub does)
* Add a "View docs" button to the workflows view.
---
> workflows: Add GitHub import view

- server/remote_cache/cachetools/cachetools.go
Note that this code isn't used yet, but will be used starting with https://github.com/buildbuddy-io/buildbuddy-internal/pull/433 (which needs this bugfix to fix broken tests)
The bug is that after switching from `ioutil.ReadDir` to `os.ReadDir`, the call to `fileInfo.Mode()` was incorrectly migrated to `dirEntry.Type()` when checking the permission bits, which is wrong since `Type` only includes the type bits.
---
> Fix permission bits bug in UploadFiles

- server/build_event_protocol/build_status_reporter/build_status_reporter.go
- server/config/config.go
Since we'll enable workflows for both our dev environment and prod environment, and the status name is solely based on the action name, we'll need a way to tell apart which check corresponds to dev and which check corresponds to prod. The plan is to set this new config value to `(dev)` so that we'll see 2 checks in the GitHub UI -- `Test` and `Test (dev)`
---
> Add config option to append a suffix to GitHub status check names

- server/tables/tables.go
Stack from [ghstack](https://github.com/ezyang/ghstack):
* **#404 Add GroupID column to ExecutionNodes table.**
This column indicates which group owns the executor.
---
> Add GroupID column to ExecutionNodes table.

- server/http/filters/BUILD
- server/http/filters/filters.go
If people make an HTTP request with non-utf8 in the URL, it causes a panic in the Prometheus library, which checks that label values must be UTF-8. Checking valid UTF-8 fixes the panic (verified using `curl`)
---
> Check valid UTF8 on HTTP routes

- server/config/config.go
When this option is enabled, the scheduler server will start using the
EnqueueTaskReservations RPC for executors that are connected with a task
stream.
Note that this is a short-term config option and will be removed after
the feature is fully rolled out.
---
> Add config option to enable "non local" scheduling.

- .bazelrc
- buildbuddy.yaml
Workflows are enabled for OSS (via the BB app) -- customizing the config here so that we run with RBE + cache and not just BES.
---
> workflows: Customize buildbuddy.yaml config for OSS repo

- nogo_config.json
When building go code, rules_go stores temp files in some random locations:
https://github.com/bazelbuild/rules_go/issues/2172
On linux - this generally ends up under the /tmp/ directory, which is fine because we can exclude the /tmp directory.
On mac - these file can end up in some random locations like:
`/var/folders/cn/q2gg_ww95f5249g5xtfm4jp40000gn/T/rules_go_work-702856088/_cgo_gotypes.go`
This change moves from having to exclude every file/directory that you don't want go vet to analyze to just including the directories that we have go code in and have control over:
- `/server/`
- `/enterprise/server`
This fixes https://github.com/buildbuddy-io/buildbuddy/issues/435
---
> Switch from nogo excludes to manual includes

- enterprise/server/workflow/service/service_test.go
- server/build_event_protocol/build_event_handler/build_event_handler_test.go
- server/testutil/testauth/testauth.go
Makes it simple to test clients (e.g. executors) that use the standard
header.
---
> Use standard API key header in testauth.

- proto/grp.proto
- proto/scheduler.proto
- server/testutil/testauth/testauth.go
- server/util/capabilities/capabilities_test.go
Rename an older method to clarify what it's doing; new method sets JWT so that context <-> header translation in RPC interceptors works correctly.
> Add a simpler version of WithAuthenticatedUser.

- enterprise/server/util/cacheproxy/BUILD
- enterprise/server/util/cacheproxy/cacheproxy.go
- enterprise/server/util/cacheproxy/cacheproxy_test.go
Deduplicate writes by checking if digest already exists and add a test for this
> Deduplicate writes by checking if digest already exists.

- server/backends/disk_cache/disk_cache.go
The following conditions need to be true to hit this send on closed channel case:
- file must exist
- file must not be found in LRU
- WithPrefix must have been called before scanning finished 
- Channel must be closed -- meaning stuff is done being scanned but is being inserted into the LRU
In practice this means the window where this can happen is during the time between finishing scanning everything on disk, and before everything has been fully inserted into the LRU. Which explains why this is uncommon.
> Reference a single diskIsMapped var, rather than copying it.

- server/interfaces/interfaces.go
The actual interface definition for `CommandContainer` is in `container.go` in the internal repo.
---
> Remove unused interface

- enterprise/server/cmd/ci_runner/main.go
- server/util/lockingbuffer/BUILD
- server/util/lockingbuffer/lockingbuffer.go
- server/util/lockingbuffer/lockingbuffer_test.go
`flushProgress` can be called by multiple threads, but access to `ar.log` wasn't synchronized (even though we're using `lockingbuffer`, `ioutil.ReadAll` will call `Read` in a loop, meaning it is unlocked between reads), and also the progress counter was not synchronized. It also wasn't guaranteeing that progress counts would be assigned in the same order in which we called `ReadAll` on the log, so events could be reported with out-of-order event IDs.
---
> ci-runner: Fix multithreading issues with log writing

- enterprise/app/trends/trends.tsx
- enterprise/server/invocation_stat_service/BUILD
- enterprise/server/invocation_stat_service/invocation_stat_service.go
- proto/buildbuddy_service.proto
- proto/invocation.proto
- server/buildbuddy_server/buildbuddy_server.go
- server/interfaces/interfaces.go
- server/tables/BUILD
- server/tables/tables.go
- server/util/blocklist/blocklist.go
This CL fixes the unresponsive UI problem for certain big customers with 1M+ invocations by:
- splitting GetInvocationStats into two RPCs: GetInvocationStats (fully covered by index) and GetTrends (partially indexed, reads more data and duration is proportional to lookback window)
- adding a loopback window which limits the amount of data queried by GetTrends
- modifies queries slightly to remove unnecessary DISTINCT's, and do COUNT(1) instead of COUNT(invocation_id)
- unifies GetInvocationStats and GetTrendStats to only query updated_at_usec
- modifies app callsites accordingly
> Split trends/invocations rpcs & add indexes.

- enterprise/server/util/cacheproxy/cacheproxy.go
- server/remote_cache/byte_stream_server/byte_stream_server.go
This fixes an error we saw on the errors channel.
> Set buffer cap only, and check length more carefully.

- enterprise/app/executors/executors.tsx
- server/bytestream/BUILD
- Remove --executor.enable_work_streaming as it's now implied by
presence of API key in the latest docker image.
- Mount & enable docker socket so that executor can run docker-based
actions.
---
> Tweak example BYOR docker command:

- server/config/config.go
- server/http/filters/filters.go
- server/ssl/ssl.go
- Identify Google HC by User Agent instead of server-type header as
Google HCs don't support custom headers.
- Add option to set default host name for SSL cert generation as the GFE
-> Backend connection does not support SNI.
---
> Code changes to support GCP HTTPS Load Balancer:

- enterprise/server/util/fieldgetter/fieldgetter.go
- enterprise/server/util/fieldgetter/fieldgetter_test.go
Fixed cases where we would see cryptic error messages like `nil value of ""` which makes it impossible to tell which part of the GitHub webhook payload is actually missing.
---
> workflows: Fix cryptic `nil value of ""` error message

- server/build_event_protocol/build_status_reporter/build_status_reporter.go
If a build disconnects, then a status called "Test (dev) (dev)" would be reported (see screenshot below). The cause is that the disconnected status is generated from a previously reported one, which already had the suffix appended.
The fix is to only append the status suffix just before sending it out to GitHub, so we are not tempted to keep around the suffixed version and accidentally suffix it again.
---
> workflows: Fix GitHub status name suffix being appended multiple times

- enterprise/server/backends/pubsub/BUILD
- enterprise/server/backends/pubsub/pubsub.go
- enterprise/server/remote_execution/execution_server/execution_server.go
- enterprise/server/test/integration/remote_execution/remote_execution_test.go
- server/config/config.go
This will address buildbuddy-io/buildbuddy-internal#590 once it's rolled out & list-based pubsub is disabled.
---
> Add support for publishing execution status updates via a Redis stream.

- enterprise/server/webhooks/github/github.go
The list of events to listen to (`["push", "pull_request"]`) has to be passed via both the `events` param and `config.events` field, otherwise only the `push` event gets listened to (this isn't documented in GitHub API docs :cry: )
---
> workflows: Fix GitHub webhook auto-registration

- enterprise/server/remote_execution/platform/platform.go
- enterprise/server/scheduling/task_router/BUILD
- enterprise/server/scheduling/task_router/task_router.go
- enterprise/server/test/integration/task_router/BUILD
- enterprise/server/test/integration/task_router/task_router_test.go
The impl is not used anywhere yet. It will be used after https://github.com/buildbuddy-io/buildbuddy/pull/522 is submitted.
Overview:
* For a given `(cmd, ctx, remoteInstanceName)` it computes a "task key" as `task_route/${groupIDFromCtx(ctx)}/${remoteInstanceName}/${sha256(marshal(command.GetPlatform()))}`
* For each task key, it stores a list of executor IDs which previously executed tasks with the same key.
* RankNodes will place executors first from that list, and randomize the rest of the executors.
* RankNodes always returns the same executors as the ones passed via the input list, and only changes the order. So any executors in Redis which do not exist in the input list are never returned in the output list.
---
> task-router: Add task router implementation

- server/backends/disk_cache/BUILD
- server/backends/disk_cache/disk_cache.go
- server/util/monitoring/BUILD
- server/util/monitoring/monitoring.go
- server/util/statusz/BUILD
- server/util/statusz/statusz.go
This pretty much mimics a 'traditional' statusz endpoint and allows various backend services to report their own status in an easily digestible (html) format.
Screenshot, to convey the gist:
Fixes: https://github.com/buildbuddy-io/buildbuddy-internal/issues/139
> Add a simple /statusz page to help introspect running servers.

- server/backends/disk_cache/disk_cache.go
- server/backends/disk_cache/disk_cache_test.go
This should prevent the cache from ever reaching max capacity, which means that writes will not have to evict something before completing.
> Add a background janitor thread to the disk cache.

- WORKSPACE
- enterprise/server/cmd/ci_runner/main.go
- server/util/log/log.go
- tools/probers/BUILD
- tools/probers/bazelrbe/BUILD
- tools/probers/bazelrbe/bazelrbe.go
The generated workspace includes rules that generate actions that copy
their inputs to their outputs.
This PR also adds a new container image that contains the cloudprober
binary, the bazelrbe prober binary as well as the bazel binaries.
Lastly this also changes console logging to write to stderr instead of
stdout which is a common convention.
(cloudprober consumes prober stdout for any custom metrics that the
prober wants to provide.)
---
> Add prober that runs Bazel over a generated workspace.

- tools/metrics/grafana/dashboards/buildbuddy.json
Fixed "Webhook events by response code" to include only webhook requests in the query. (Noticed we were seeing a steady stream of QPS here, probably because of the /Heartbeat requests)
---
> workflows: Fix prom query for webhook requests

- app/invocation/invocation.css
- app/invocation/invocation.tsx
- app/invocation/invocation_query_graph_card.tsx
Changing the style so it feels more interactive:
* Change background to cool grey (material blue gray 50) -- not sure exactly why but the white color felt "non-interactive" to me
* Tweak height so that there's no need to scroll to see the bottom of the graph
* Adjust card padding so there's no "dead" areas around the border
* Change hover cursor to hint that the graph is interactive (not shown in screenshot -- the screenshot tool didn't capture it correctly)
---
> Slight style tweaks to graph

- server/environment/environment.go
- server/interfaces/interfaces.go
- server/real_environment/real_environment.go
This is a first step towards having an automated E2E test for workflows that doesn't depend on third party Git provider APIs. The plan is for the test to create a webhook, trigger the webhook (the fake git provider will directly return some fake webhook data in its impl of `ParseWebhookData`), then poll the invocation ID in the DB and make sure we can eventually find a completed workflow invocation.
In the future, we can consolidate all provider-specific integrations into this interface (LinkAccount, GetAccessTokenForAuthenticatedGroup, CreateStatus, ListRepos) so that a new implementation of this interface is all that's needed to get full support for the Git provider. This will also allow us to create an automated test that `CreateStatus` gets called for workflow invocations (since …
> workflows: Add git provider interface

- .github/workflows/checkstyle.yaml
* Make sure clang-format's stderr gets included in `clang-format-errors.txt` - otherwise the check always passes even if there are errors
* Print clang-format version so we can see which version GitHub's action runner is using (helpful to diagnose inconsistencies w/ `buildfix.sh`)
---
> Fixes / improvements to clang-format check

- server/util/bazel/bazel.go
For the prober we don't get any Bazel output if the probe times out and
gets killed.
Note that this will also affect tests that invoke Bazel.
---
> Update Bazel invoker to stream output to log.

- enterprise/server/backends/distributed/distributed.go
I suspsect this is where the high cache latency is coming from.
---
> Add a debug log if remote reader fails.

- server/http/protolet/BUILD
- server/http/protolet/protolet.go
- server/rpc/filters/BUILD
- server/rpc/filters/filters.go
- server/util/request_context/BUILD
- server/util/request_context/request_context.go
If we pass `RequestContext` via a plain old gRPC (bypassing protolet, as we do in some unit tests) then it doesn't get set via the protolet filter and `ProtoRequestContextFromContext` returns `nil`, causing some codepaths not to work.
This makes the `RequestContext` universally available in `ctx` by adding the extraction logic to the RPC filters as well.
This also cleans up the unnecessary usage of the "reflect" package.
---
> Make request_context available in regular gRPC requests

- tools/metrics/grafana/dashboards/buildbuddy.json
* Introduce a new `pool` var that takes on the values `executor` and `executor-workflows` to match the app label for each executor pool.
* Repeat "Remote execution" and "Runner pool" sections for each value of `pool`.
* Add `{job="buildbuddy-${pool}"}` filters on all prom queries in these sections. (Once https://github.com/buildbuddy-io/buildbuddy-internal/issues/628 is fixed we can simplify this to `label_app="${pool}"` 
---
> Split RBE grafana charts by executor pool

- enterprise/dockerfiles/ci_runner_image/Dockerfile
- enterprise/server/workflow/service/service.go
Tested our existing CI runner image with a bunch of different repos. Results are here: https://docs.google.com/document/d/1W-pdf8a_AQIiI_dqk1r6nd6W2d_NcODZ5qsPVNC7vMQ/edit#heading=h.i42bw6n4ciwh
TL;DR is that we should switch over to the same base image that we use for our default execution image (google RBE / ubuntu 16.04), as it is compatible with a lot more repos (mainly because it has Java 8 and Python3 + Pip pre-installed).
---
> workflows: Make CI runner image compatible with more repos

- enterprise/server/cmd/ci_runner/main.go
The workflow service sets `--bazel_command=""` by default, which I mistakenly figured was equivalent to not specifying the flag at all.
---
> Fix "fork/exec : no such file or directory" on CI runner in dev

- enterprise/server/remote_execution/commandutil/commandutil.go
- enterprise/server/vmexec/BUILD
- enterprise/server/vmexec/vmexec.go
- proto/BUILD
- proto/vmexec.proto
This server accepts a proto command and executes it, returning the response. I did not use the repb command proto because it includes some fields (output files, etc) that we do not support.
Big ups to @bduffany for the original implementation of this in:
- https://github.com/buildbuddy-io/buildbuddy-internal/pull/409 and
- https://github.com/buildbuddy-io/buildbuddy/pull/346
> Add vmexec server and implementation

- server/util/log/log.go
We now have services that contain the same methods (e.g. Read) and it's
useful to know which service is being called.
---
> Disambiguate ByteStream and DistributedDisk RPCs in logs.

- tools/metrics/grafana/dashboards/buildbuddy.json
I renamed the current "Remote execution" panel to "Executor pool" so I
could use the "Remote execution" name for global graphs.
---
> Add graph that shows # of execution result waiters.

- enterprise/server/backends/distributed/distributed.go
- enterprise/server/util/cacheproxy/BUILD
- enterprise/server/util/cacheproxy/cacheproxy.go
gRPC can block an RPC, regardless of its failfast settings, while the underlying connection remains in CONNECTING state which we have experienced during rollouts and node preemptions.
---
> Avoid blocking RPCs between distributed disk peers.

- buildpatches/grpc_tracing.patch
- deps.bzl
- server/rpc/filters/filters.go
- server/util/grpc_server/grpc_server.go
The instrumentation code assumes the client stream is not done until
CloseSend() is called, but that's not a strict requirement. The client
stream should also be considered done if the server stream returns
io.EOF.
Upstream function being patched: https://github.com/open-telemetry/opentelemetry-go-contrib/blob/d41f1f8fa3621b1ce3d70af48370eea4a984e3b1/instrumentation/google.golang.org/grpc/otelgrpc/interceptor.go#L152
I'll send an upstream patch shortly.
---
> Fix goroutine leak in gRPC stream interceptor and re-enable instrumentation.

- app/components/button/button.css
- app/root/root.css
- app/router/router.tsx
- enterprise/app/history/BUILD
- enterprise/app/history/history.css
- enterprise/app/history/history.tsx
- enterprise/app/root/root.tsx
- enterprise/app/workflows/workflows.tsx
- enterprise/server/invocation_search_service/invocation_search_service.go
- proto/invocation.proto
* When clicking a workflow, navigate to the existing repo history view, but append the URL param `?workflows=true` which adds the filter `role = "CI_RUNNER"` to the query. e.g. `/history/repo/buildbuddy-io/buildbuddy?workflows=true`
* Customize the workflows view with a nicer title ("Workflow runs of $repo" instead of "Builds of $repo") and empty state:
---
> workflows: Show history view when clicking a workflow

- enterprise/app/trends/trends.tsx
- enterprise/server/invocation_stat_service/invocation_stat_service.go
- proto/invocation.proto
- server/tables/tables.go
Exclude `ROLE=CI_RUNNER` from trends queries so that we don't double-count invocations (the CI runner invocation should not be counted because it just spawns Bazel invocations).
---
> workflows: Include only bazel invocations in trends view

- app/auth/auth_service.ts
- enterprise/app/sidebar/sidebar.tsx
When picking a new org, don't emit a new user -- instead, only set the selected group ID in localStorage, and let the newly selected user be naturally refreshed via the reload.
---
> Fix UI flickering when switching orgs

- enterprise/server/remote_execution/executor/executor.go
- enterprise/server/remote_execution/runner/runner.go
According to the logs, creating new containers when the executor first
starts up can take ~20 seconds though it's unclear what docker is doing
at the time.
Try to mitigate this for the default image by creating a dummy container
as part of executor start-up.
Issue: https://github.com/buildbuddy-io/buildbuddy-internal/issues/684
---
> Attempt to mitigate executor slowness on new nodes.

- enterprise/app/settings/settings.tsx
- enterprise/server/auth/auth.go
- server/backends/github/BUILD
- server/backends/github/github.go
* Set a `GitHub-Linked-Group-ID` cookie in the first step of the auth flow. The group ID comes from a URL param passed to the OAuth handler in the first step of the flow.
* When redirected back from the OAuth provider and after verifying the CSRF token, extract the group ID from the cookie and authorize group access.
* Only link the GitHub account to the authorized group.
---
> Link GitHub account per-org

- enterprise/server/remote_execution/container/container.go
- enterprise/server/remote_execution/containers/bare/bare.go
- enterprise/server/remote_execution/containers/docker/BUILD
- enterprise/server/remote_execution/containers/docker/docker.go
- enterprise/server/remote_execution/containers/docker/docker_test.go
- enterprise/server/remote_execution/runner/runner.go
Did some benchmarking -- `container.Create` + `container.Exec` is slightly faster than `container.Run`, even if we make the benchmarks more fair by removing the "pull image" and "remove container" steps inside the impl of `Run`.
```
BenchmarkRun-8                         3         440955833 ns/op
BenchmarkCreateExec-8                  4         328038006 ns/op
```
---
> cleanup: Remove container.Run codepath

- enterprise/server/auth/auth.go
- enterprise/server/cmd/goinit/main.go
- enterprise/server/remote_execution/execution_server/execution_server.go
This way, they can easily be skipped when copying files back out of the workspace fs
> Init: Name overlay root/work dirs something unmistakeably ours.

- server/util/grpc_server/BUILD
- server/util/grpc_server/grpc_server.go
Saw similar code while looking at the HTTP interceptors.
---
> Add invocation_id to RPC server span without modifying otel code.

- app/invocation/invocation_overview.tsx
- enterprise/app/history/history.tsx
- enterprise/app/history/history_invocation_card.tsx
Addressing feedback from https://github.com/buildbuddy-io/buildbuddy-internal/issues/672. Some (mild) problems with the current sentence-casing approach:
* It looks slightly odd if your username isn't just your first name (e.g. `jdoe` becomes `Jdoe`)
* It causes usernames beginning with `i` to look like they start with a lowercase `L` (though this could be mitigated by using a more readable font)
* Unix usernames are case-sensitive, so arguably this is causing the wrong data to be displayed.
---
**Related issues**: Fixes https://github.com/buildbuddy-io/buildbuddy-internal/issues/672
> Make usernames lowercase

- server/tables/tables.go
- Google's max seems to be 2048: https://developers.google.com/identity/protocols/oauth2
- Intuit is 4096: https://blogs.intuit.com/blog/2020/03/23/increased-lengths-for-oauth-2-0-fields/
- Facebook doesn't have one: https://www.quora.com/Whats-the-maximum-length-of-an-OAuth-access-token-key-secret-pair
4096 seems like a reasonable max.
---
> Increase max size of access & refresh tokens

- enterprise/server/remote_execution/execution_server/execution_server.go
- enterprise/server/scheduling/priority_task_scheduler/BUILD
- enterprise/server/scheduling/priority_task_scheduler/priority_task_scheduler.go
- enterprise/server/scheduling/priority_task_scheduler/priority_task_scheduler_test.go
- enterprise/server/scheduling/scheduler_server/scheduler_server.go
- enterprise/server/scheduling/task_router/task_router.go
- proto/scheduler.proto
- server/backends/disk_cache/disk_cache_test.go
- server/interfaces/interfaces.go
- server/metrics/metrics.go
- server/util/prefix/BUILD
- server/util/prefix/prefix.go
This PR creates a separate priority queue per group ID and then does a
round robin over the PQs to dequeue the next task.
This PR also adds a Group ID label to the remote_execution_queue_length
metric. This should not impact scaling as the metric is already
aggregated by other fields when being exposed to k8s.
---
> Add some basic task reservation balancing across groups.

- app/invocation/BUILD
- app/invocation/invocation_execution_card.tsx
- enterprise/server/execution_service/execution_service.go
- enterprise/server/remote_execution/execution_server/execution_server.go
- proto/BUILD
- proto/defs.bzl
- proto/execution_stats.proto
- server/tables/tables.go
Completed actions with gRPC errors (e.g. INTERNAL) now render like this:
Completed actions with non-zero exit code now render like this:
When sorting by status (ascending) the order is now
- Started
- Queued
- Running
- Completed
- Successful (gRPC OK, exitCode == 0)
- RBE error (gRPC != OK, sorted by gRPC code)
- Command error (gRPC == OK, exitCode != 0, sorted by exit code)
So to see failed actions first (which is our general sort order for other parts of the UI), the user just needs to sort by Status Desc, if it isn't sorted that way already.
---
**Related issues**: https://github.com/buildbuddy-io/buildbuddy-internal/issues/672
> Update style for failed actions

- enterprise/server/remote_execution/container/container.go
Otherwise all the spans are reported as coming from that function.
---
> Remove helper function from `TracedCommandContainer`.

- enterprise/server/cmd/ci_runner/main.go
- enterprise/server/test/integration/ci_runner/BUILD
- enterprise/server/test/integration/ci_runner/ci_runner_test.go
- server/testutil/testbazel/BUILD
- server/testutil/testbazel/testbazel.go
CI runner test:
* Don't use `testbazel.MakeTempWorkspace` to create the CI runner's working directory -- the CI runner creates its own bazel workspace inside the working directory (under `repo-root`).
* Fix bug that we're forwarding the `TEST_TMPDIR` env var from the test to the CI runner process, which causes Bazel to write some stuff to cache directory on the local machine (`~/.cache/bazel/...`).
* Pass `--max_idle_time_secs=5` to prevent the CI runner's spawned bazel process from sticking around forever (the default is 3 hours). Also pass `--noblock_on_lock` as a way to assert that the CI runner never gets stuck waiting for another bazel process to release the lock.
testbazel util:
* Log `bazel shutdown` duration in test cleanup phase (to help diagnose the cause of slow bazel tests) …
> Some bug fixes / improvements to bazel usage in tests

- enterprise/server/test/integration/ci_runner/BUILD
- enterprise/server/test/integration/remote_cache/BUILD
- server/test/integration/build_event_protocol/BUILD
They are flaky because `bazel shutdown` sometimes takes forever.
---
> Temporarily disable tests that invoke bazel.

- enterprise/app/root/root.tsx
Lazy loading other components seems to lead to:
```
TypeError: Cannot read property 'Timestamp' of undefined
```
https://app.buildbuddy.dev/invocation/6ae67d53-469f-4e34-9db1-a94970e889cc
which I'll need to investigate further. Potentially due to https://esbuild.github.io/api/#splitting being a work in progress.
---
> Only lazy-load the code component for now

- enterprise/server/remote_execution/containers/docker/docker.go
This fixes the issue with bazel tests taking forever to shut down. The problem is that `bazel shutdown` does not treat the server as "shut down" if it is a zombie. https://github.com/bazelbuild/bazel/pull/13656 proposes an upstream fix.
It's problematic, still, that `bazel` becomes a zombie and never gets reaped. So, by specifying the `Init` option in this PR, the top-level Docker process in the container will be a [tiny init process](https://docs.docker.com/engine/reference/run/#specify-an-init-process) that reaps zombie processes.
---
> Run docker-init in containers to reap zombie processes

- enterprise/server/remote_execution/container/container.go
- enterprise/server/remote_execution/containers/bare/bare.go
- enterprise/server/remote_execution/containers/docker/BUILD
- enterprise/server/remote_execution/containers/docker/docker.go
- enterprise/server/remote_execution/containers/docker/docker_test.go
- enterprise/server/remote_execution/runner/runner.go
This seems to make https://github.com/buildbuddy-io/buildbuddy-internal/issues/718 go away
---
> Revert `.Run()` removal and Docker Init changes

- tools/metrics/grafana/dashboards/buildbuddy.json
Ensure all queries are aggregated by `pod_name` so that only one series is created per executor, regardless of other labels (e.g. `group_id`)
---
> Fix prom queries for RBE grafana dashboards

- enterprise/app/root/root.tsx
Introducing the lazy-loaded code component cases esbuild to look for shared code between the two distinct js bundles.
These shared modules are loaded as chunks that look like:
`/app/app_bundle/chunk-abc123.js`
Where the `abc123` bit is a hash of the contents of the chunk.
This is problematic during a rollout because if hits multiple servers (behind a loadbalancer) with different chunks - the app will fail to load.
This PR comments out the code component, removing the generation of these chunks. We'll need to come up with a solution for serving these chunks during a rollout (likely by deploying the static js to a CDN) before re-enabling this component.
---
> Disable code component for next release

- enterprise/server/test/performance/cache/BUILD
- enterprise/server/test/performance/cache/cache_test.go
- go.mod
- server/backends/disk_cache/BUILD
- server/backends/disk_cache/disk_cache.go
- server/backends/disk_cache/disk_cache_test.go
- server/config/config.go
- server/libmain/libmain.go
The disk cache config has a list of partition configs consisting
of an ID and a maximum size. The ID is used to determine where on disk
the cache partition is rooted & the max size is used to instantiate the
LRU.
The config also has a list of mappings which specify when a partition
should be used. Each mapping consists of a Group ID and an remote
instance name prefix. Partition will be used if a cache request is
received with matching group ID and a remote instance name that has a
matching prefix.
Finally, a `WithRemoteInstanceName` method is introduced to allow the
instance name to be passed to the cache implementation so it can make a
decision about which partition to use.
---
> Add support for multiple "partitions" in disk cache.

- enterprise/server/backends/s3_cache/s3_cache.go
- server/backends/blobstore/blobstore.go
- server/config/config.go
This is useful for customers that are deploying offline clusters.
Based on these docs: https://docs.min.io/docs/how-to-use-aws-sdk-for-go-with-minio-server.html
---
> Add support for using MinIO as a replacement for s3

- app/invocation/BUILD
- app/invocation/invocation.css
- app/invocation/invocation.tsx
- app/invocation/invocation_action_card.tsx
- app/invocation/invocation_build_logs_card.tsx
- app/menu/BUILD
- app/menu/menu.tsx
- app/preferences/BUILD
- app/preferences/preferences.ts
- app/root/BUILD.bazel
- app/root/root.css
- app/root/root.tsx
- app/target/action_card.tsx
- app/target/target.tsx
- app/target/target_log_card.tsx
- app/target/target_test_document_card.tsx
- app/target/target_test_log_card.tsx
- enterprise/app/root/BUILD.bazel
- enterprise/app/root/root.tsx
- enterprise/app/settings/BUILD
- enterprise/app/settings/settings.css
- enterprise/app/settings/settings.tsx
- static/image/log-circle.svg
Adds support for a light terminal theme that the user can switch to in `Personal Settings`.
Does so by replacing the simple `denseMode` boolean with a simple `UserPreferences` object that manages dense mode and this new log viewer theme.
Also cleans up a few things I bumped into along the way:
- Updates invocation query style to match
- Renames ActionCardComponent => InvocationActionCardComponent (we have two components named ActionCardComponent right now).
- Cleans up some unused imports
---
> Support a light terminal theme

- buildfix.sh
- tools/prettier/prettier.sh
* Allow running `gazelle` with `-g` or `--gazelle` flags (not done by default because it is a bit slower compared to the other formatting commands).
* Run `prettier` by default (we'll want to add this to checkstyle to ensure the formatting of the frontend code is consistent, and it's quick enough assuming a cached build or pre-installed prettier binary).
* Update `prettier` to avoid dependence on `realpath` (not available on MacOS, IIUC)
---
> Make some improvements to buildfix.sh

- enterprise/server/backends/distributed/distributed.go
- enterprise/server/backends/gcs_cache/gcs_cache.go
- enterprise/server/backends/memcache/memcache.go
- enterprise/server/backends/redis_cache/redis_cache.go
- enterprise/server/backends/s3_cache/s3_cache.go
- enterprise/server/composable_cache/BUILD
- enterprise/server/composable_cache/composable_cache.go
- enterprise/server/remote_execution/execution_server/execution_server.go
- server/backends/disk_cache/disk_cache.go
- server/backends/disk_cache/disk_cache_test.go
- server/backends/memory_cache/memory_cache.go
- server/interfaces/BUILD
- server/interfaces/interfaces.go
- server/remote_asset/fetch_server/BUILD
- server/remote_asset/fetch_server/fetch_server.go
- server/remote_cache/action_cache_server/action_cache_server.go
- server/remote_cache/byte_stream_server/byte_stream_server.go
- server/remote_cache/cachetools/cachetools.go
- server/remote_cache/content_addressable_storage_server/content_addressable_storage_server.go
- server/remote_cache/namespace/namespace.go
WithIsolation is an instruction to the cache implementation to return an
accessor for the cache that isolates the data for the given cache type +
remote instance name combination from any other combination.
This method will supersede WithPrefix, which can be removed once the
distributed disk implementation has been migrated to the new method.
---
> Add WithIsolation method to the Cache interface.

- buildfix.sh
- tools/prettier/prettier.sh
Tested on Linux and Mac.
We should really just switch to Python... but then we have a dep on Python. Probably OK, but let's think about that later.
---
> Fix file arrays in buildfix scripts

- enterprise/server/remote_execution/operation/operation.go
- enterprise/server/scheduling/priority_task_scheduler/BUILD
- enterprise/server/scheduling/priority_task_scheduler/priority_task_scheduler.go
Ensure in-flight work is cancelled before the shutdown and no more messages are sent.
> Shutdown the executor gracefully on scale-down.

- server/backends/disk_cache/disk_cache.go
MST is the expected timezone placeholder.
---
> Fix timezone formatting on disk cache statusz page.

- enterprise/config/executor.local.yaml
- enterprise/server/remote_execution/containers/docker/docker.go
- enterprise/server/remote_execution/runner/runner.go
- server/config/config.go
Add a config option to inherit the uid and gid of the current user, and enable it for local development.
Before this change, when running the executor locally, all files are written with uid=0 and gid=0, causing various permissions errors.
---
> Fix filesystem permissions for local docker-based executor

- tools/enable_local_firecracker.sh
This sets up some stuff (capabilities and sudoers file) so that it's easy to run the firecracker executor locally without being root. On k8s, it's not necessary since we run as root.
> Add a script to enable running firecracker locally w/o root.

- enterprise/server/remote_execution/containers/firecracker/BUILD
- enterprise/server/remote_execution/containers/firecracker/firecracker.go
- enterprise/server/remote_execution/containers/firecracker/firecracker_test.go
- enterprise/server/util/networking/networking.go
This change runs firecracker inside of the jailer and also enables networking for VMs.
The [jailer](https://github.com/firecracker-microvm/firecracker/blob/main/docs/jailer.md) is another binary shipped with firecracker that creates a chroot + network namespace and runs the firecracker process inside. It's good for security, but also important for snapshotting + networking as it allows snapshots to have the same firecracker/vsock unix socket paths and IPs, and co-exist on the same host because they are in different chroot / namespaces.
Post this change, networking in containers works out of the box as soon as the default route is added (example:
ip route add default via 192.168.241.1). I'll send another CL after this one that makes that default route addition happen as part of init.
Want …
> Support jailer and networking

- server/build_event_protocol/build_event_server/build_event_server.go
Ran into this while trying to replay an invocation and I had a typo in the invocation ID.
---
> Fix panic in case BES stream contains no events

- app/invocation/invocation_model.tsx
`--remote_cache` defaults to the value of `--remote_executor` if it is not set. See [here](https://github.com/bazelbuild/bazel/blob/718279b6c157769f48fbaa13e0aacb94682916ef/src/main/java/com/google/devtools/build/lib/remote/RemoteModule.java#L256-L260)
---
**Related issues**: Fixes https://github.com/buildbuddy-io/buildbuddy-internal/issues/666
> Fix cache mode displayed in UI when remote_executor is set

- app/invocation/invocation_model.tsx
Updates the status logic in the invocation overview to be the same as it is for the history card, which is based on the status + success fields, and not the presence of the started / finished build events.
---
**Related issues**: Fixes https://github.com/buildbuddy-io/buildbuddy-internal/issues/662
> Fix bug that failed invocation can display as "in progress"

- app/invocation/invocation_model.tsx
- docs/guide-metadata.md
- server/build_event_protocol/event_parser/event_parser.go
This will cause the BuildKite link to take you to the correct job if the `BUILDKITE_JOB_ID` environment variable is populated.
---
> Support BuildKite job IDs

- enterprise/server/remote_execution/runner/runner.go
- enterprise/server/remote_execution/workspace/workspace.go
* Make all workspace operations mutually exclusive. In particular, make sure `Remove` waits for uploads to complete.
* After `Remove` is called, return an error from all other workspace operations.
* Parallelize all runner removals in `runner.Pool.Shutdown`, since removal is now blocked on upload completion. Otherwise, if a single workspace takes a long time to upload its outputs (while the pool is shutting down), other runners would not be removed.
---
> Fix race condition with executor shutdown

- app/invocation/invocation.tsx
- app/invocation/invocation_artifacts_card.tsx
- app/root/root.css
Some targets have a large number of outputs, which causes the UI spend a long time rendering. This change shaves about 5s off of the page load time for our infamous 13 second invocation, and also reduces the time it takes to switch between the "app" and "artifacts" tabs from O(seconds) to O(~100ms).
Since we now only partially load targets, this PR adds little indicators in the list to make it clear that we're not showing all artifacts from each target.
---
---
Also fixed artifact filtering, which was broken in a previous PR but was unnoticed.
---
**Related issues**: Fixes https://github.com/buildbuddy-io/buildbuddy-internal/issues/661
> Page artifacts by output instead of target

- .github/workflows/checkstyle.yaml
Now that prettier is included in `buildfix.sh`, we can include it in checkstyle with less hassle when there are errors. Formats the following file types: js, jsx, ts, tsx, html, css, yaml, json, md
---
> Add prettier to checkstyle workflow

- enterprise/server/scheduling/scheduler_server/BUILD
- enterprise/server/scheduling/scheduler_server/scheduler_server.go
- enterprise/server/test/integration/remote_execution/BUILD
- enterprise/server/test/integration/remote_execution/remote_execution_test.go
- proto/BUILD
- proto/scheduler.proto
- server/config/config.go
We create a hash for each executor pool. The key is the executor ID and
the value is a new RegisteredExecutionNode proto.
Additionally we create a per-group set that tracks all the available
pools.
---
> Add support for storing executor information in Redis.

- server/build_event_protocol/build_event_handler/build_event_handler.go
- server/util/redact/redact.go
This PR is a NOP for now but lays the groundwork for us to be able to factor the redaction logic out of `StreamingEventParser.ParseEvent` (and into `StreamingRedactor.RedactMetadata`) without breaking anything.
---
> Add Redactor skeleton for migrating redaction logic from event_parser

- app/invocation/invocation_filter.tsx
- enterprise/app/tap/tap.tsx
`updateParams` calls `pushState` which means every time a char is typed into the filter input, it grows the history stack by 1, meaning that the back button has to be pressed once for every keystroke that was entered in order to actually go back.
---
> Fix bug that each keystroke in invocation filter creates a new history entry

- tools/js_size_diff.sh
Example output:
```
BEFORE
size (KB)       4597
gzipped (KB)    814
AFTER
size (KB)       4746
gzipped (KB)    848
DIFF
size (KB)       148
gzipped (KB)    33
```
---
> Add tool for sanity checking JS bundle size diff

- enterprise/BUILD
- enterprise/app/BUILD.bazel
- enterprise/server/cmd/server/BUILD
- rules/sha/index.bzl
- server/libmain/libmain.go
- server/static/BUILD
- server/static/static.go
This replaces instance of `{APP_BUNDLE_HASH}` with that app bundle's hash in the `js_entry_point_path`.
We then place this as a query parameter when loading the default js bundle.
Like:
```
/app/app_bundle/app.js?hash=abc123
```
During local development, this means you should no longer have to force refresh when we make front-end changes and allows us to set aggressive cache headers.
In our production configs, this allows us to use the same variable to point do a CDN release like:
```
--js_entry_point_path=https://storage.googleapis.com/buildbuddy-static/app/{APP_BUNDLE_HASH}/app_bundle/app.js
```
or
```
--js_entry_point_path=https://static.buildbuddy.io/app/{APP_BUNDLE_HASH}/app_bundle/app.js
```
---
> Use hash of js bundle in the `js_entry_point_path`

- server/build_event_protocol/build_event_handler/build_event_handler.go
We had been only writing cache stats in FinalizeInvocation; this adds that behavior to
MarkInvocationDisconnected as well.
---
> Record cache stats on disconnect (buildbuddy/buildbuddy-internal#742)

- server/build_event_protocol/event_parser/event_parser.go
- server/build_event_protocol/event_parser/event_parser_test.go
- server/util/redact/BUILD
- server/util/redact/redact.go
- server/util/redact/redact_test.go
This PR moves most "trivial" pieces of redaction logic from the event parser to the redactor. Since we redact before calling the event parser (as of #765), this is effectively a NOP.
Will do the build metadata and env var redaction in the next PR since it's not 100% straightforward (compared to the changes in this PR).
---
> Move most basic redaction logic to StreamingRedactor

- enterprise/server/webhooks/bitbucket/test_data/BUILD
- enterprise/server/webhooks/github/test_data/BUILD
Gazelle can't understand globs, so every time we run `fix` it produces
noise about these BUILD targets. Their input files are neither overly
numerous nor frequently changing, so it makes sense to just list them.
---
> Remove globs from BUILD files for gazelle

- server/build_event_protocol/build_event_handler/BUILD
- server/build_event_protocol/build_event_handler/build_event_handler.go
- server/eventlog/BUILD
- server/eventlog/eventlog.go
- server/terminal/screen.go
- server/terminal/terminal.go
Buffer the logs so that ANSI can update the last six lines
Adds a sub-writer to the event log writer that renders ANSI text and maintains a buffer of
the last 6 lines, flushing the preceding lines to the standard witer pipeline.
---
> Buffer chunked event logs for ANSI cursor modification

- server/build_event_protocol/build_event_handler/BUILD
- server/build_event_protocol/build_event_handler/build_event_handler_test.go
- server/build_event_protocol/event_parser/event_parser.go
- server/build_event_protocol/event_parser/event_parser_test.go
- server/util/redact/BUILD
- server/util/redact/redact.go
- server/util/redact/redact_test.go
* Strip repo URL credentials from WorkspaceStatus and BuildMetadata in redactor instead of event parser
* Strip repo URL credentials more uniformly
* Beef up `build_event_handler_test` to ensure the redactor is wired up to the build event handler properly whether or not `--enable_optimized_redaction` is set. Includes tests for StructuredCommandLine redaction, which will be useful for the next PR (which moves env var redaction to the redactor as well).
---
> Move WorkspaceStatus and BuildMetadata redaction to redactor

- enterprise/server/invocation_search_service/invocation_search_service.go
The code was assuming that `time.Unix(0, 0).IsZero()` returns true, but it actually returns false. As a result, the history query would always filter to the time range `epoch_local_time <= t < epoch_local_time`, returning 0 results.
---
> Fix time range query for invocation history

- server/remote_cache/byte_stream_server/byte_stream_server.go
This should fix Bazel errors that look like:
```
(Exit 34): io.grpc.StatusRuntimeException: RESOURCE_EXHAUSTED: gRPC message exceeds maximum size 4194304: 4194305
```
---
> Lower read buffer size to avoid bazel error

- server/eventlog/eventlog.go
- server/terminal/screen.go
- Prevent screen.y from ever becoming negative
- Increase lines to retain for event log ANSI cursor buffer
First, we guard against the possibility of `s.y` dropping below 0 by forcing more lines to be retained than requested when that would flush the current line the ANSI cursor is on out of the buffer. Second, as we saw an error where `s.y` went out of range by `2`, we increase the number of lines buffered by the `ANSICursorBufferWriter` in `eventlog.go` from 6 to 10, as we would prefer to anticipate the number of lines bazel will attempt to edit to maintain the log as an exact replica of the command line output. Finally, we add warnings to let us know if we are failing to edit the buffer as bazel intended.
---
> Fix panic in `screen.go` where `s.y` can be negative

- enterprise/server/util/cacheproxy/cacheproxy.go
- enterprise/server/util/cacheproxy/cacheproxy_test.go
AC items may be re-written and we want to allow this -- so check that the isolation type is == CAS before deduping cache writes.
Also, clean up the tests slightly.
> Dedupe writes differently depending on isolation type.

- enterprise/server/testutil/testredis/BUILD
- enterprise/server/testutil/testredis/testredis.go
* Add a startup healthcheck before allowing the test to use the server instance, to ensure that the server is ready to accept connections.
* Use a Unix socket instead of a random free TCP port to avoid race conditions where the port gets taken after the port is determined but before the server actually listens on it.
Tested locally with `--runs_per_test=2000` (12K total test funcs)
---
**Related issues**: Fixes https://github.com/buildbuddy-io/buildbuddy-internal/issues/767
> Fix redis connection refused errors in tests

- rules/release/index.bzl
This will enable us to keep the master `dev.apply` rule that will deploy both the GCS bucket and then apply our k8s configs.
I'm working on adding a `.diff` action to the gcs deploy (in a separate PR) so we can keep the diff functionality.
There is prior art: https://github.com/atlassian/bazel-tools/tree/master/multirun
---
> Add a release bazel rule

- app/invocation/invocation.css
- app/invocation/invocation.tsx
- app/invocation/invocation_build_logs_card.tsx
- app/invocation/invocation_logs_model.tsx
- server/eventlog/eventlog.go
* Fetch the first chunk in parallel with the invocation, instead of making 2 requests in serial (GetInvocationRequest followed by GetEventLogChunkRequest)
* Update server so that if chunking is not enabled for an invocation, we return EOF instead of an error. This allows us to make the requests in parallel, because we can now always fetch event log chunks even if we don't know whether chunking is enabled (the enabled bit is present in the GetInvocationResponse).
* Show a loading state while the chunk is loading, if it has not loaded by the time the GetInvocationResponse comes back. For non-chunked invocations, we never show this loading state, since we have a separate full-page loading state until the InvocationModel is created and the InvocationModel contains the logs. For chunked …
> Improve loading sequence for chunked event logs

- app/invocation/invocation.tsx
The logs model was meant to be initialized only once. This PR initializes them in `componentWillMount` instead of `fetchInvocation` (which is called at an interval).
---
> Fix logs initialization

- app/invocation/invocation_logs_model.tsx
The number of function arguments that can be passed to a function has a relatively small limit, so `String.fromCharCode(...buffer)` results in a RangeError.
Try running this in the JS console: `console.log(...new Array(1000000))`
---
> Fix `RangeError` for large chunk buffers

- server/eventlog/BUILD
- server/eventlog/eventlog.go
Took the tried and true [`blobQueue`](https://github.com/buildbuddy-io/buildbuddy/blob/c61f7d5e62fef4b17c553cfc0ee1d19b18a84710/server/util/protofile/protofile.go#L124-L189) from `protofile.go` and adapted it for chunkstore reads.
---
**Related issues**: Fixes https://github.com/buildbuddy-io/buildbuddy-internal/issues/774
> Parallelize chunkstore reads

- app/target/target_test_document_card.tsx
This fixes the issue where switching between test shards where some have and some don't have test.xml files leads to stale data.
---
> Clear test.xml file if one is not found

- enterprise/config/executor.local.yaml
- enterprise/server/remote_execution/containers/firecracker/firecracker.go
- enterprise/server/remote_execution/runner/runner.go
- enterprise/server/util/container/container.go
Firecracker will use the estimated task sizes for execution. Also; do all container and image caching inside the working directory rather than on the root filesystem.
> Do work on the root filesystem; tasksize fc tasks

- enterprise/server/remote_execution/containers/firecracker/BUILD
- enterprise/server/remote_execution/containers/firecracker/firecracker_darwin.go
Looks like I messed up this function signature when splitting darwin/linux firecracker packages.
---
> Fix darwin executor build

- enterprise/server/remote_execution/containers/firecracker/firecracker.go
- enterprise/server/util/container/container.go
This removes the jailer directories so they don't pile up on disk. Also cleans up the snapshot impl a little bit by cleanly removing and restoring things between snapshots (all state lives in the snapshot).
Finally, it no longer does any container caching using the user's cache directory -- everything lives inside the root executor working directory (which is important as it means everything will be on SSD).
> Cleanup jailer dir after execution.

- enterprise/server/remote_execution/runner/BUILD
- enterprise/server/remote_execution/runner/runner.go
This warms up firecracker as well as docker; both need to pull the default image in different ways.
> Warmup all configured containers.

- app/invocation/invocation_action_card.tsx
Notifies user that empty action page with no error means it was removed from CAS
> Explains emtpy action page

- enterprise/server/invocation_stat_service/invocation_stat_service.go
- server/tables/tables.go
The proto already allows filtering by role, but the actual filtering wasn't implemented. This adds the SQL wiring and index necessary to make the query complete in a reasonable amount of time.
See performance details here https://github.com/buildbuddy-io/buildbuddy-internal/issues/617
---
**Related issues**: https://github.com/buildbuddy-io/buildbuddy-internal/issues/617
> Add role filtering support for invocation stats query

- proto/invocation.proto
Since the client's notion of "status" is really derived from 2 fields (`invocation_status` and `success`) it makes sense to define a new enum that represents this derived status, so that we can specify a list of statuses to fetch (which will be driven by the new global filtering UI).
In upcoming PRs, will update the client to always send all possible status filter values (by default -- this will later be controlled by the filtering UI), and then update the server to handle this new field appropriately.
Confirmed that status filtering does not make queries significantly slower for group IDs with the largest number of invocations (tried history, stats, and trends queries) -- even when combined with `role` filtering.
--- …
> Add status filter field to invocation query protos

- app/router/router.tsx
The existing logic wasn't preserving the `#users`, `#repos`, etc. part of the URL
---
> Get status filter working on history aggregate pages

- enterprise/server/invocation_search_service/invocation_search_service.go
- enterprise/server/invocation_stat_service/invocation_stat_service.go
- proto/invocation.proto
* Implement status filtering for `SearchInvocationRequest`, `GetInvocationStatRequest`, `GetTrendRequest`
* Change the documentated semantics for the `status` filter -- rather than requiring all desired statuses to be specified, it is more natural (and also backwards-compatible) to select all statuses by default, and for each filter to map one-to-one with an OR clause in SQL. It is also more natural for the user to build up a list of statuses they want to see (starting from an empty list, meaning "all statuses"), rather than subtract the ones they don't want to see.
* Update `GetTrendRequest` to allow filtering by the new timestamp fields instead of the `lookback_window`. Will remove the `lookback_window` support in another PR (once clients are using the new timestamp fields).
--- …
> Implement server-side invocation history status filtering and trends filtering

- enterprise/app/filter/filter.css
- enterprise/app/filter/filter.tsx
- enterprise/app/filter/filter_util.tsx
- enterprise/server/invocation_search_service/invocation_search_service.go
- enterprise/server/invocation_stat_service/invocation_stat_service.go
- proto/invocation.proto
Instead of radio buttons, now using checkboxes.
Required an API change to allow selecting any combination of roles. The API change is backwards-compatible.
---
> Make role filters work the same way as status filters

- bundle.go
We call `fs.ReadFile(bundleFS, "sha.sum")` to get the sha of the app js bundle.
`ReadFile`'s documentation reads:
> If fs implements ReadFileFS, ReadFile calls fs.ReadFile. Otherwise ReadFile calls fs.Open and uses Read and Close on the returned file.
Because we were embedding `embed.FS` into `aliasFS`, we were implementing `ReadFileFS` which would not take our aliasing into account.
This only turned out to be a problem for builds built with `-c opt` that didn't specify an `app_directory`. Unfortunately this included the open source docker image builds between versions `2.3.3` and `2.4.9`.
Enterprise docker images and builds run with `bazel run` where not affected.
---
> Fix ReadFile calls when using bundle filesystem

- enterprise/server/remote_execution/executor/executor.go
This makes it easier to see why executions are failing, which shortens the time it takes us to debug weird remote exec problems. I think the extra debug-level noise is worth it.
> Debug log stdout/stderr of execution failures.

- server/util/query_builder/BUILD
- server/util/query_builder/query_builder.go
- server/util/query_builder/query_builder_test.go
There's a few places in the code where we rely on `query_builder.OrClauses` returning an empty string when there are no clauses present, but it feels a bit brittle since that function could just as easily return `" "` which still seems like a valid result (especially since the current impl pads the returned string with whitespace in the non-empty case). Adding a unit test to enforce this expected behavior and avoid accidentally breaking stuff in the future.
---
> Add some unit tests for query_builder.OrClauses

- rules/release/index.bzl
From the `genrule` [documentation](https://docs.bazel.build/versions/main/be/general.html#genrule.tools) for `exec_tools`:
> A list of tool dependencies for this rule. This behaves exactly like the tools attribute, except that these dependencies will be configured for the rule's execution platform instead of the host configuration. This means that dependencies in exec_tools are not subject to the same limitations as dependencies in tools. In particular, they are not required to use the host configuration for their own transitive dependencies. See tools for further details.
>The Bazel team is migrating all uses of tools to use exec_tools semantics. Users are encouraged to prefer exec_tools to tools where this does not cause any issues. After the functional migration is complete, we may …
> Fix release rule

- enterprise/server/backends/distributed/distributed_test.go
- enterprise/server/util/cacheproxy/cacheproxy.go
- enterprise/server/util/cacheproxy/cacheproxy_test.go
- server/backends/disk_cache/disk_cache_test.go
- server/remote_cache/byte_stream_server/byte_stream_server.go
- server/remote_cache/byte_stream_server/byte_stream_server_test.go
The fix is the 3 line change in `byte_stream_server.go`, but this PR also adds tests for this scenario in:
- distributed_test.go
- cacheproxy_test.go
- disk_cache_test.go
- byte_stream_server_test.go
---
> Handle bytestream /Read requests where read_offset == digest size

- app/errors/BUILD
- app/errors/error_service.ts
- app/root/BUILD.bazel
- app/root/root.tsx
- app/util/errors.ts
- enterprise/app/root/BUILD.bazel
- enterprise/app/root/root.tsx
This uses the same BuildBuddyError parsing logic that will properly display golang-style errors.
Here's what this looks like:
---
> Display errors passed through the `?error=` url query param using the error service

- app/auth/BUILD
- app/auth/auth_service.ts
- app/util/errors.ts
- enterprise/server/auth/auth.go
- enterprise/server/remote_execution/runner/runner.go
- server/buildbuddy_server/buildbuddy_server.go
- server/nullauth/nullauth.go
- server/testutil/testauth/testauth.go
- server/util/capabilities/BUILD
- server/util/capabilities/capabilities.go
- server/util/status/status_test.go
Right now we only console log errors from CreateUser / GetUser (we don't display them to the user).
This is because some of the errors are benign - specifically "User not found" from GetUser and "No user token available to fill user" from CreateUser.
This is mostly fine, but when we get real errors from CreateUser (like the auth token not containing an email address) - we just console log these errors which effectively swallows them.
This change clearly marks all of the server side errors that the client auth flow depends on and switches them to UNAUTHENTICATED errors. From the [status code docs](https://github.com/googleapis/googleapis/blob/master/google/rpc/code.proto#L86):
>   // The caller does not have permission to execute the specified
// operation. `PERMISSION_DENIED` must not be …
> Display (real) errors coming from CreateUser or GetUser using the ErrorService

- enterprise/server/scheduling/scheduler_server/scheduler_server.go
- enterprise/server/test/integration/remote_execution/remote_execution_test.go
Sharing the state across schedulers will give us better scheduling
during upscaling.
We use a sorted set per executor pool to track unclaimed tasks.
This is a roll-forward of
https://github.com/buildbuddy-io/buildbuddy/pull/748.
This time around we don't rely on the availability of the ZRANDMEMBER
command which requires Redis 6.2
Instead we fetch the entire set of task IDs and do our own sampling.
The task ID set has a relatively small upper bound (10k) and in practice should be much smaller than that.
---
> Track unclaimed tasks in Redis.

- server/build_event_protocol/target_tracker/target_tracker.go
The main goal of this PR is to move status tracking from the TestSummary event to the Finished event to support invocations that use the `--test_tag_filters=` flag.
This PR also:
- Pulls permissions logic out into its own function so we have a better idea of which errors should be warnings and which should be debug
- Add more logging and include invocation ID for better debugging
- Cleans up switch statement by breaking the cases out into their own functions
---
> Clean up target tracking

- app/errors/error_service.ts
- app/invocation/invocation_logs_model.tsx
Currently for invocations that we have error pages for, we also pop an errorService alert modal.
Example for not found: https://app.buildbuddy.io/invocation/dfldksfjlsfa
This PR fixes that.
---
> Don't show error alerts on invocations page for errors we already have pages for

- app/BUILD.bazel
- app/components/spinner/BUILD
- app/components/spinner/spinner.css
- app/components/spinner/spinner.tsx
- enterprise/app/history/BUILD
- enterprise/app/history/history.css
- enterprise/app/history/history.tsx
- enterprise/app/history/history_invocation_card.tsx
- enterprise/app/history/history_invocation_stat_card.tsx
Makes the experience less janky when loading the page and when changing the global filter, mainly when the stats response takes longer than the SearchInvocation response.
* Add a `<Spinner>` component which we can also use in a few other places, rather than using `<div className="loading" />` with brittle style overrides (will do the cleanup in follow-up PRs)
* Fix bugs where `this.setState({ ...this.state })` was called, preventing multiple calls to `setState` in the same async task
* Fix typing issues in history component and sub-components
https://user-images.githubusercontent.com/2414826/130646332-7867e1c1-f161-4b3d-b515-0dbdd67648f6.mp4
---
> Add spinner for summary stats in history view

- enterprise/app/history/history.tsx
* Fix bug that we would sometimes call certain RPCs unnecessarily. For example, we would always fetch invocations when looking at aggregate pages, and wait for the invocations to come back before displaying the aggregate stats, even though the invocations aren't needed in order to show aggregate stats. Now we always fetch _either_ invocations and summary stats, _or_ aggregated stats.
* Fix bug that we'd fetch summary stats when scoped to a user, repo, etc. but not actually display the stats.
* Fix bug that navigating to the users view would show "No users found" while the users are being fetched (can repro this easily in prod by going to the Users tab in the probers org)
* Fix bug that stale RPC data could be displayed (now we cancel all RPCs properly).
* Commented, renamed, and updated …
> Simplify and fix bugs with history component

- enterprise/app/history/history.tsx
- enterprise/app/history/history_invocation_stat_card.tsx
Fixes a bug that if the only fetched stat card doesn't have a name (e.g. user="", repo="", etc.), then we just show a blank view instead of the zero state (can see this in the "branches" tab of the BB probers org).
---
> Fix zero state display for history aggregate views

- tools/metrics/grafana/dashboards/buildbuddy.json
It had an override that was showing only the last 1 minute of data.
---
> Fix "redis clients" graph.

- tools/metrics/grafana/dashboards/buildbuddy.json
* Use `${window}` config var for averaging windows instead of 1m
* Apply area fills to stacked metrics more consistently, so it's clear that they are stacked
* Remove area fills from other charts
* Set min axis values to 0
---
> Tweak redis charts

- tools/metrics/grafana/dashboards/buildbuddy.json
- tools/metrics/run.sh
Good news: no unexpected events in dev :)
Also fix grafana startup URL so it takes us to the editable view by default.
Query is
```promql
sum by (name) (rate(buildbuddy_unexpected_event[${window}]))
```
---
> Add unexpected events chart

- buildpatches/com_github_hanwen_go_fuse_v2
- deps.bzl
- enterprise/server/cmd/goinit/main.go
We delay the splice package init() call until the FUSE server is
instantiated.
---
> FUSE lib hack to avoid accessing /dev/null before it's available.

- enterprise/server/remote_execution/containers/firecracker/firecracker.go
The image path is only set in `PullImage` which is not called if
`IsImageCached` returns true.
Since this function can have side-effects perhaps it could use a better
name like `CheckCachedImage` or `FindCachedImage`?
---
> Fix image caching related bug in Firecracker impl.

- app/root/root.css
Looks like Safari applies a 2px margin to `<button>` elements by default.
Clicked around the UI and made sure this didn't break anything else.
---
> Fix global filer alignment in Safari

- enterprise/server/remote_execution/dirtools/dirtools.go
- enterprise/server/remote_execution/platform/platform.go
- enterprise/server/remote_execution/runner/runner.go
- enterprise/server/remote_execution/workspace/BUILD
- enterprise/server/remote_execution/workspace/workspace.go
- enterprise/server/remote_execution/workspace/workspace_test.go
Add `clean-workspace-inputs` platform argument that allows users to specify how workspace inputs are cleaned up when preserving workspaces.
- If unset or empty, the current behavior will be preserved where we only overwrite inputs that have changed between actions.
- If set to `*`, all old inputs that are not used in the current action are cleaned up.
- If set to another value, we split on commas and clean up any inputs glob matching those strings
- For example  `clean-workspace-inputs: **.framework/**,**.h ` will clean up any old inputs that end in `.h` or contain `.framework/`.
This fixes: https://github.com/buildbuddy-io/buildbuddy-internal/issues/852
---
> Add `clean-workspace-inputs` platform argument that allows users to specify how workspace inputs are cleaned up when preserving workspaces

- enterprise/server/cmd/goinit/main.go
- enterprise/server/remote_execution/containers/firecracker/firecracker.go
- enterprise/server/remote_execution/containers/firecracker/firecracker_test.go
- tools/vmstart/vmstart.go
This CL:
- Continually restarts getty so if you ctrl-D in a VM started by vmstart, it'll no longer leave you hanging forever
- Cleanly "Wait()"s and handles the exit of VMs resumed from a snapshot, where before it would hang forever
- Logs some more errors at level=ERROR
- Fixes the firecracker tests to be compatible with the new ImageCacheAuthenticator
> Allow vmstart to exit cleanly even after starting from snapshot.

- deps.bzl
- enterprise/server/cmd/executor/BUILD
- enterprise/server/cmd/executor/executor.go
- enterprise/server/remote_execution/platform/BUILD
- enterprise/server/remote_execution/platform/platform.go
- enterprise/server/remote_execution/platform/platform_test.go
- enterprise/server/remote_execution/runner/runner.go
- go.mod
- go.sum
- server/environment/environment.go
- server/interfaces/interfaces.go
- server/real_environment/real_environment.go
- server/xcode/BUILD
- server/xcode/xcode.go
- server/xcode/xcode_darwin.go
This removes the need to have hardcoded XCode paths in our code (and for folks running executors to place XCode at those paths), and also allows us to support XCode versions more precise than two components (i.e. 12.5.1 or 12.5.1.12E507).
Xcode location logic is losely based on Bazel's XCode locator: https://github.com/bazelbuild/bazel/blob/master/tools/osx/xcode_locator.m
This removes the need for enableXcodeOverride.
---
> Implement a real Xcode locator

- enterprise/server/test/performance/cache/BUILD
- enterprise/server/test/performance/cache/cache_test.go
Distributed disk cache requires isolation params to be set.
---
> Fix cache perf test.

- enterprise/server/remote_execution/containers/firecracker/firecracker.go
- enterprise/server/vmexec/BUILD
- enterprise/server/vmexec/vmexec.go
- proto/vmexec.proto
When a snapshotted VM is resumed we need to clear the ARP cache for networking to fully work, otherwise packets may go to the wrong place until the old ARP cache entry expires.
This CL adds an "Initialize" RPC to the vmexec server which clears the ARP cache and also sets the VM's system time. When a snapshot is resumed, this method is called once.
More context (from https://github.com/firecracker-microvm/firecracker/blob/main/docs/snapshotting/network-for-clones.md):
To make sure the guest also adjusts to the new environment, you can explicitly clear the ARP/neighbour table in the guest:
ip -family inet neigh flush any
ip -family inet6 neigh flush any
Otherwise, packets originating from the guest might be using old Link Layer Address for up to arp cache timeout seconds. After said timeout …
> Clear arp cache (and set time) after resuming from snapshot

- enterprise/server/remote_execution/dirtools/dirtools.go
- enterprise/server/remote_execution/workspace/workspace.go
The input cleaning logic currently keeps any files that were "skipped" when downloading inputs.
This mostly works - however if an input file has changed, we do not "skip" it but instead we download the new file.
This means that when we go to clean up the files that were not "skipped", we'll accidentally clean up changed input files.
This change moves from tracking "skips" to tracking "exists", which are files that already existed when we went to download them.
This accurately maps to the overlap in input files between actions, and prevents us from incorrectly deleting files that changed.
---
> Don't clean up changed workspace inputs

- app/flame_chart/flame_chart.tsx
Argument lists in JS have a size limit. Using an array and reducing with `Math.max` fixes the problem.
```tsx
let arr = new Array(1000000).fill(0);
Math.max(...arr) // error: 'Uncaught RangeError: Maximum call stack size exceeded'
arr.reduce((a, b) => Math.max(a, b)) // 0
```
---
**Related issues**: Fixes https://github.com/buildbuddy-io/buildbuddy/issues/997
> Fix 'Maximum call stack size exceeded' in flame chart

- .bazelrc
- .github/workflows/release-m1.yaml
- BUILD
- WORKSPACE
- enterprise/BUILD
- server/version/BUILD
- server/version/version.go
- workspace_status.sh
This PR enables a darwin-arm64 executor release for m1 macs.
This only enabled the executor build for now, since much more work is needed to release m1 mac builds (we'll probably need to upgrade to rules_nodejs 4.0 which is an involved upgrade).
While doing this release, I discovered that the executor currently bundles the js app. This is because of the dependency chain executor => scheduler_client => version => bundle => app_bundle => js.
This PR breaks the chain by pulling the executor version number from a stamp rather than the version file in the bundle for release builds.
There are enough tweaks to the workflow needed that it's cleaner as a separate workflow. Once we're able to build apps, it will be pretty straightforward to combine these workflows and use the release matrix.
The …
> m1 release

- app/auth/auth_service.ts
- enterprise/app/login/login.tsx
- proto/grp.proto
- server/buildbuddy_server/buildbuddy_server.go
When a user visits a "join organization" page and they're not logged in and the organization has SSO enabled, clicking the big login / signup button behaves the same as clicking the "Login with SSO" button.
Also prioritizes groups with a url slug over groups without one when picking a "default group" (so users in their user group and an SSO organization without an associated domain default to their SSO organization rather than their personal group).
---
> If a group has sso enabled, use that as the default login mechanism on their join page

- proto/grp.proto
Adding `role` directly to `Group`, rather than creating a new `UserGroup` proto and then migrating the `GetUserResponse` from `repeated UserGroup` to `repeated Group`. Figured this would have little benefit since we only ever return `Group` protos for a particular user, so this proto already implicitly represents a user-group membership.
---
**Related issues**: https://github.com/buildbuddy-io/buildbuddy-internal/issues/868
> Add role field to group proto

- app/capabilities/capabilities.tsx
- app/components/button/BUILD
- app/components/button/button.css
- app/components/button/checkbox_button.tsx
- enterprise/app/org/BUILD
- enterprise/app/org/org.css
- enterprise/app/org/org_members.tsx
- enterprise/app/settings/settings.tsx
- proto/config.proto
- server/config/config.go
- server/static/static.go
Behind the config option `app.user_management_enabled`, show the "Members" tab in the settings page. It shows a list of group members. It also includes "Edit role" and "Remove" buttons, which don't do anything yet. The plan for "Edit role" is to show a modal dialog that shows the role selector as well as an explanation of each role. The plan for "Remove" is to show a modal with a confirm button. In both cases (edit role and remove) we'll show an extra warning if the changes will affect the current user (to protect against accidentally removing yourself or demoting yourself).
https://user-images.githubusercontent.com/2414826/133817736-ee7cbdeb-e63f-416a-877d-5d8b15deb42d.mp4
In a future PR, we should also consolidate the membership requests into this page.
---
> Add initial user management list view

- server/backends/memory_cache/memory_cache.go
- server/backends/memory_cache/memory_cache_test.go
> Remove remoteInstanceName from memory_cache CAS key (other cache types still tbd)

- enterprise/server/cmd/smash/BUILD
- enterprise/server/cmd/smash/smash.go
- server/backends/disk_cache/disk_cache.go
- server/backends/disk_cache/disk_cache_test.go
WIP
- Remove the concept of "prefix" as one big string and instead pass around remoteInstanceName (string) and cacheType (int).
- Add the concept of fileKey, a struct containing the pieces necessary to construct a full path to a file
- Add FromPartitionAndPath, which reconstructs a fileKey struct from a v1 or v2 file path on disk
- Add internString, which takes a string, hashes it, and if it's been seen before returns a reference to the initial string, else inserts it in a map and returns a reference to it. This should reduce the number of unique strings kept in memory. Intern both the remoteInstanceName and groupID prefix strings.
Before:
After:
> Reduce disk cache space usage further

- server/backends/disk_cache/disk_cache.go
- server/backends/disk_cache/disk_cache_test.go
- Fix a race condition around string interning
- Fix a correctness issue around determining file paths
- Fix a race issue around waiting for the disk to finish scanning files
> Fix disk_cache filepaths and de-flake disk test

- enterprise/server/cmd/server/BUILD
- enterprise/server/cmd/server/main.go
- enterprise/server/usage/BUILD
- enterprise/server/usage/usage.go
- enterprise/server/usage/usage_test.go
- enterprise/server/util/redisutil/BUILD
- enterprise/server/util/redisutil/redisutil.go
- server/interfaces/interfaces.go
* Fix the `final_before_usec` update condition; we want to update the usage row only if it is finalized up to the _start_ of the current collection period, not the end
* Improve the concurrent access tests to disable Redlock, so we can test that concurrent flushing is safe even if Redis fails. Also assert that the result is correct rather than just asserting that there was no error (this is what caught the bug above).
---
> Fix bugs with usage flush logic and improve concurrency tests

- enterprise/server/cmd/server/main.go
- enterprise/server/usage/usage.go
- enterprise/server/usage/usage_test.go
We don't set the redis_cache target in dev which makes the server fail to start when usage_tracking_enabled is configured as `true`.
Separately we'll think about whether it makes sense to define a new Redis target just for the usage tracker, and I can make that change afterwards. Just want to unbork dev.
---
> Use different redis client for usage tracker

- enterprise/server/remote_execution/casfs/BUILD
- enterprise/server/remote_execution/casfs/casfs.go
- enterprise/server/util/vfs_server/vfs_server.go
- enterprise/server/vmcasfs/vmcasfs.go
- proto/vfs.proto
- Cache node attributes. `getattr` OPs are frequent so it helps to
avoid extra RPCs.
- When opening small files for reading, return the file contents inline
to avoid the overhead of additional read RPCs.
- Bring back `CopyFileRange` which got dropped in the vfs server
transition.
- Don't lock on read requests as FUSE can fire off multiple read requests in parallel. 
- Bump write buffer size to maximum supported by kernel
Other:
- Instrument FUSE ops so we can know how much time is spent in the user
space code broken down by each OP type.
---
> FUSE optimizations

- app/capabilities/BUILD
- app/capabilities/capabilities.tsx
- app/preferences/BUILD
- app/preferences/preferences.ts
- app/root/root.tsx
- enterprise/app/root/root.tsx
- proto/BUILD
- proto/config.proto
- server/static/BUILD
- server/static/static.go
- static/index.html
This will allow us to use structured protos in the FrontendConfig (planning on using this for the per-role permissions config, which is a relatively small proto that doesn't seem worth adding an extra RPC for).
It's also nice to have the config available as a proto because we no longer need to extract individual fields from the proto and set them on the capabilities class.
---
> Use jsonpb for capabilities config

- app/auth/auth_service.ts
- app/service/rpc_service.ts
- proto/BUILD
- proto/user.proto
- server/buildbuddy_server/buildbuddy_server.go
This will allow us to expand `GetUserResponse` with the list of resources (API endpoints) that are accessible to the user within their currently selected group.
Replicating the exact logic that we use on the client to determine the "fallback" selected group when a preference is not set or the user no longer has access to the selected group.
---
> Move selected group logic to the server

- enterprise/app/org/org_members.tsx
If the role dropdown was not changed from the default selection, then we were passing a role of `undefined` in the RPC, which is effectively a NOP.
---
> Fix role applied when dropdown selection is unchanged from its initial value

- docs/enterprise-config.md
- enterprise/config/buildbuddy.local.yaml
- enterprise/server/cmd/server/main.go
- enterprise/server/usage/usage.go
- enterprise/server/usage/usage_test.go
- server/config/config.go
- server/environment/environment.go
- server/real_environment/real_environment.go
- Add default redis target and use it
- Use default redis target in local enterprise config
Defines a new redis target `app.default_redis_target` to use for usage tracking, metrics collection,
and event log caching. Falls back to the remote execution redis target if unspecified for migration reasons.
Acts as a fallback for the remote execution target if it is unspecified for intentional design reasons.
---
> Add default redis target

- enterprise/server/backends/userdb/userdb.go
- server/tables/tables.go
This has been replaced with the API keys table.
GORM doesn't delete old columns for us, so I added a migration to explicitly remove the column. I am OK with removing this though if we don't think it's worth the added migration code and/or the risk of losing data permanently due to incorrect migration logic. (I figure since this column hasn't been in use for such a long time, the risk is minimal)
---
> Clean up `Groups.api_key` column

- enterprise/server/cmd/server/main.go
- enterprise/server/usage/BUILD
- enterprise/server/usage/usage.go
- enterprise/server/usage/usage_test.go
- server/config/config.go
- server/tables/tables.go
Adding `region` to the composite key for the usage table, so that flushes from Redis -> DB in each region only finalize the current collection period + group's data for the current region, rather than all regions.
As a bonus, this will make it easy to allow users to segment usage by region in the UI (if that's something they're interested in).
---
> Support usage tracking across regions

- server/util/grpc_server/BUILD
- server/util/grpc_server/grpc_server.go
Default is 5 min: https://pkg.go.dev/google.golang.org/grpc/keepalive#EnforcementPolicy
We set it to 10s to avoid sending: 
```
error code: ENHANCE_YOUR_CALM Received Goaway too_many_pings
```
---
> Set a keep-alive enforcement policy

- enterprise/server/util/redisutil/BUILD
- enterprise/server/util/redisutil/redisutil.go
- enterprise/server/util/redisutil/redisutil_test.go
This will be used to help reduce load on Redis; counter values will be collected via this buffer and periodically flushed to Redis at regular intervals.
This util on its own does not actually flush the values to Redis; the caller will be responsible for that.
The plan to integrate this with the app looks like this:
* Create one of these buffers and set them on the env
* In `main`, call `Flush` every 1s or so (will experiment in dev using some artificial invocations that generate a lot of INCRBY commands to see what a good value is for this)
* Update `RedisMetricsCollector` and `UsageTracker` to go through this buffer instead of writing directly to Redis
* In the build event handler, wait a few seconds at the end of the invocation (in the background) before writing invocation stats to the …
> Add a primitive buffer for Redis counter values

- server/backends/memory_metrics_collector/memory_metrics_collector.go
- server/backends/redis_metrics_collector/redis_metrics_collector.go
- server/interfaces/interfaces.go
- server/remote_cache/hit_tracker/BUILD
- server/remote_cache/hit_tracker/hit_tracker.go
Once we add Redis buffering, `MetricsCollector.IncrementCount` will no longer be able to return the count after incrementing, because the Redis command is only issued when flushing, which happens periodically in the background.
We could get around this by issuing a `GET` immediately after the `INCRBY` but this sort of defeats the purpose of buffering.
Instead, we can just remove the readback capability from the `Increment` function and update consumers to no longer depend on this readback capability.
The only place where we depend on this readback is in `hit_tracker.go` where we do throughput calculations. Luckily we can replace this with an equivalent calculation that doesn't rely on the readback. See this demo which shows that throughput calculations are the same: …
> Remove readback from `MetricsCollector.IncrementCount` API

- app/auth/auth_service.ts
- app/invocation/invocation_not_found.tsx
- enterprise/app/login/login.tsx
- enterprise/app/root/root.tsx
The interstitial page doesn't support SSO, and keeping the two login pages in sync is probably not worth the hassle.
---
> Redirect to main login page (with SSO) instead of using interstitial invocation login page

- enterprise/server/remote_execution/casfs/BUILD
- enterprise/server/remote_execution/casfs/casfs.go
- enterprise/server/remote_execution/containers/firecracker/firecracker.go
- enterprise/server/remote_execution/executor/executor.go
- enterprise/server/remote_execution/runner/runner.go
- enterprise/server/util/vfs_server/BUILD
- enterprise/server/util/vfs_server/vfs_server.go
- enterprise/server/util/vfs_server/vfs_server_test.go
- enterprise/server/vmcasfs/BUILD
- enterprise/server/vmcasfs/vmcasfs.go
- proto/vfs.proto
- proto/vmcasfs.proto
- tools/vmstart/vmstart.go
This change removes the need to propagate the same layout information
directly to both the vfs server and the fuse filesystem.
Additionally, the VFS server now takes existing files into account when
creating the layout to make it possible to reuse workspaces.
---
> Have the vfs file system retrieve layout from the vfs server.

- server/util/git/git.go
- server/util/git/git_test.go
Should fix some issues with repo parsing we're seeing in prod
---
> Trim whitespace before normalizing/parsing repo urls

- server/backends/invocationdb/BUILD
- server/backends/invocationdb/invocationdb.go
Verified that Bazel does a retry in case we return an error here, so this should not negatively affect any existing cases where we return an error for whatever reason (e.g. due to context deadline exceeded).
---
> Improve error handling for InsertOrUpdateInvocation

- server/build_event_protocol/build_event_server/build_event_server.go
This fixes at least one possible cause of the AlreadyExists error (https://github.com/buildbuddy-io/buildbuddy-internal/issues/951), although there may be others (still looking into it).
---
> Fix bug that we finalize invocations twice in some cases

- server/build_event_protocol/build_event_handler/build_event_handler.go
- server/build_event_protocol/build_event_handler/build_event_handler_test.go
- server/build_event_protocol/build_event_server/BUILD
- server/build_event_protocol/build_event_server/build_event_server.go
- server/interfaces/interfaces.go
It's possible that once we call `beValues.AddEvent(BuildFinished)`, we encounter an error, which would cause the invocation to terminate early and be finalized. However, because we saw the `BuildFinished` event, we'd mark the invocation with COMPLETED status, which would cause AlreadyExists to be returned on the subsequent retry.
Instead of switching on whether we saw the BuildFinished event, we now pass the status directly, basing the status on whether we're invoking FinalizeInvocation as the result of `disconnectWithErr` or as the result of successfully receiving all build events from Bazel.
Future work: Should we only mark the invocation COMPLETED after sending back all of the ACKs to Bazel? (Will Bazel attempt to retry if we don't ACK everything?)
--- …
> Fix another source of AlreadyExists errors

- server/test/webdriver/invocation/invocation_test.go
Adding `--show_progress=0` prevents the logs from being as variable in length for invocations that happen to take longer to run (so we can do assertions more reliably on what is shown in the logs viewport).
---
> Fix flaky invocation page test

- server/backends/invocationdb/invocationdb.go
- server/build_event_protocol/build_event_handler/build_event_handler.go
- server/interfaces/interfaces.go
This should provide a stronger guarantee that the usage count does not exceed the number of rows inserted into the DB (modulo the possibility of deleting invocations via the UI).
---
> Only increment invocation usage after inserting a new invocation row

- enterprise/server/hostedrunner/hostedrunner.go
10GB is not enough to build all of buildbuddy repo.
---
> Bump hosted bazel disk space to 20GB.

- server/util/prefix/BUILD
- server/util/prefix/prefix.go
Currently if you do a write authenticated as a user - it will write to the cache with a user prefix (rather than a group prefix).
We don't ever want to write to the cache with a user prefix (we want to write it as the group).
This currently isn't an issue, but became an issue when we started writing patch files while authenticating as a user in the web UI.
---
> Always use group id as cache prefix

- enterprise/app/code/code.tsx
Git seems to strip the first directory from filenames when git applying (likely because `git diff` uses `a/filename` and `b/filename` when rendering diffs.
---
> Add prefixes to match git apply's filename expectations

- BUILD
- bundle.go
- enterprise/BUILD
- enterprise/bundle.go
- enterprise/server/cmd/ci_runner/BUILD
- enterprise/server/cmd/executor/BUILD
- enterprise/server/cmd/executor/executor.go
- enterprise/server/cmd/server/BUILD
- enterprise/server/cmd/server/main.go
- enterprise/server/hostedrunner/BUILD
- enterprise/server/hostedrunner/hostedrunner.go
- enterprise/server/remote_execution/containers/firecracker/BUILD
- enterprise/server/remote_execution/containers/firecracker/firecracker.go
- server/environment/environment.go
- server/libmain/BUILD
- server/libmain/libmain.go
- server/real_environment/real_environment.go
- server/util/fileresolver/BUILD
- server/util/fileresolver/fileresolver.go
- server/util/fileresolver/fileresolver_test.go
- server/util/fileresolver/test_data/BUILD
- server/util/fileresolver/test_data/bundle.go
- server/util/fileresolver/test_data/embedded_file.txt
Also use the fileresolver in a few places:
* firecracker.go (simplifies the logic for resolving paths to vmlinux, etc.)
* hostedrunner.go (fixes a bug that the server fails to start because we don't have runfiles available when running the enterprise app as a standalone binary)
This will also be useful for https://github.com/buildbuddy-io/buildbuddy/pull/1193
---
> Add a fileresolver util to locate bundled files with runfiles fallback

- enterprise/server/util/container/container.go
The regular unpack command generates some extra data that is only
necessary for creating new layers which we don't need.
Verified that the Docker executor image we are building already pull the
latest version of umoci.
This is about 30% faster for the buildbuddy image.
---
> Use "raw unpack" when generating Firecracker container fs.

- app/terminal/terminal.tsx
Add a lightweight regex to strip ANSI styles, since they render as raw ANSI codes unless viewing the logs with `cat` or `less -r` (most people will probably use their editor or the default text viewer on their system)
---
> Strip ANSI sequences when downloading logs

- enterprise/server/remote_execution/commandutil/commandutil.go
- enterprise/server/remote_execution/containers/docker/docker.go
`docker_debug_stream_command_outputs` allows sending stdout / stderr of Docker commands directly to the terminal. This PR renames the flag to a more generic `debug_stream_command_outputs` and gets it working for bare executors too.
Using this for debugging Mac workflows.
---
> Implement debug stream command outputs flag for bare executors

- enterprise/server/cmd/ci_runner/main.go
This fixes an issue with Mac workflows that the osxkeychain credential helper shows an interactive dialog which blocks the `git fetch` until the dialog is clicked through.
---
> Don't use a git credential helper for the workflow repo

- enterprise/server/remote_execution/platform/platform.go
- enterprise/server/test/integration/workflow/workflow_test.go
- enterprise/server/workflow/config/config.go
- enterprise/server/workflow/service/service.go
Also, don't set `container-image` unless the OS is `linux`.
This requires us to read the workflow config when calling `ExecuteWorkflow`, so a little bit of refactoring was needed. `executeWorkflow` now requires the `workflowAction` config from `buildbuddy.yaml`. Since we have that object, we no longer need to pass `--action_name=...` as an extra CI runner arg, and can always set it based on the passed in `workflowAction`.
Note that this does not make any changes to `pool` - that'll be a separate PR.
---
> Allow configuring the OS for workflows in buildbuddy.yaml

- app/invocation/invocation.tsx
- app/invocation/invocation_model.tsx
- app/invocation/scorecard_card.tsx
- app/root/root.css
- proto/cache.proto
- proto/invocation.proto
- proto/remote_execution.proto
- server/build_event_protocol/build_event_handler/build_event_handler.go
- server/interfaces/interfaces.go
- server/remote_cache/hit_tracker/hit_tracker.go
This CL adds support for an ActionCache miss scorecard, basically a list of targets and their associated action ids that were cache misses during a build. The data is collected using deferred counters in redis|memory, and finalized to blobstore at the same time the cache stats are finalized.
This adds a card to the cache tab that shows the items that were missing from the action cache, like this:
Future improvements (maybe someone more UI handy than me can help with):
- pagination, in case the scorecard is large (it can be)
- linking to a card to display the action, rather than downloading it, so users can debug a cache miss entirely in the UI
> Add better cache miss debugging

- enterprise/server/workflow/config/config.go
- enterprise/server/workflow/service/service.go
This lets us support M1 Macs (by setting `os: darwin, arch: arm64`)
---
> Allow specifying CPU architecture in workflow config

- app/invocation/invocation_action_card.tsx
- app/invocation/scorecard_card.tsx
- app/root/root.css
* Implement client-side paging (the same way we do for artifacts)
* Link to action results page
* Add action mnemonic to links
* Make the styling consistent with the test artifacts list
TODO in future PRs:
- Don't hard-code the action digest size as 141: either don't require a size to be able to view the action page, or find a way to use the actual digest size
- If the action is not found, show a help message with the list of potential reasons: `--noremote_upload_local_results` was set; a read-only API key was used; action expired or was manually deleted from CAS; ...?
---
> Add paging for cache scorecard and link to action results

- app/root/root.css
- app/terminal/terminal.tsx
Tested in Chrome (both Linux and macOS) and Safari.
Test log (light / non-dense)
Build log (dark / dense)
---
> More CSS fixes for build logs

- server/build_event_protocol/webhooks/webhooks.go
The infamous `Groups` table quoting issue strikes once again. This is a problem in MySQL 8 but not 5.7
---
> Fix MySQL 8 syntax for BEP webhooks

- deps.bzl
- enterprise/server/cmd/ci_runner/BUILD
- enterprise/server/cmd/ci_runner/main.go
- server/util/bazelisk/BUILD
- server/util/bazelisk/bazelisk.go
Increases the size of the standalone CI runner binary by about 5MB (bringing the total size to 25MB).
---
> Embed bazelisk into the CI runner to simplify Mac workflow executor provisioning

- enterprise/app/login/login.tsx
- enterprise/app/sidebar/sidebar.tsx
- enterprise/server/test/webdriver/BUILD
- enterprise/server/test/webdriver/invocation/BUILD
- enterprise/server/test/webdriver/invocation/invocation_test.go
- enterprise/server/testutil/buildbuddy_enterprise/buildbuddy_enterprise.go
- server/testutil/webtester/webtester.go
Uses the new self-auth to log in to the app, gets the bazelrc contents (including the API key) from the setup page, then runs a bazel invocation using those recommended bazelrc flags. Asserts that we can view the invocation if we're still logged in, and that if we're logged out, we see the login page instead.
---
> Add a webdriver test for authenticated invocations (via self-auth)

- enterprise/server/remote_execution/runner/runner.go
This was added in #1237 which is not in prod yet so it's safe to revert. Occasionally, it causes workflow_test to fail.
---
> Temporarily revert bazel cleanup logic causing workflow_test to be flaky

- enterprise/server/remote_execution/runner/runner.go
- enterprise/server/test/integration/remote_execution/rbetest/rbetest.go
The root cause is that we weren't properly waiting for all executors to shut down before removing the test root workspace containing the data for all the executors.
---
> Fix workflow_test flakiness and re-enable bare workflow runner shutdown logic

- app/alert/BUILD
- app/alert/alert.tsx
- app/invocation/BUILD
- app/invocation/invocation_error_card.tsx
- app/invocation/invocation_filter.tsx
- app/invocation/invocation_model.tsx
- app/invocation/invocation_overview.tsx
- app/root/root.css
- enterprise/app/api_keys/BUILD
- enterprise/app/api_keys/api_keys.css
- enterprise/app/api_keys/api_keys.tsx
- enterprise/app/filter/BUILD
- enterprise/app/filter/filter.tsx
- enterprise/app/history/BUILD
- enterprise/app/history/history.tsx
- enterprise/app/history/history_invocation_card.tsx
- enterprise/app/history/history_invocation_stat_card.tsx
- enterprise/app/sidebar/BUILD
- enterprise/app/sidebar/sidebar.css
- enterprise/app/sidebar/sidebar.tsx
- package.json
- yarn.lock
Before:
https://user-images.githubusercontent.com/2414826/143095274-c7eb8c8d-e651-4dc7-a8f5-534539a3d785.mp4
After:
https://user-images.githubusercontent.com/2414826/143095288-b6d295da-a034-4932-8f27-dbf58813ab28.mp4
We currently serve SVGs uncached which results in a waterfall of requests while the app is loading, causing jank and network congestion (each SVG request uses up a connection from the client's connection pool and has a fixed overhead due to HTTP headers etc.).
Rather than trying to cache these SVGs, the fix in this PR is to use icons as code (from the `lucide-react` package) rather than using `img` elements, where possible, effectively embedding them in the app bundle / chunks.
This approach has a few advantages compared to `img src`:
* No need to further slow down / …
> Fix jankiness / network waterfall while loading SVGs during initial page load

- tools/metrics/grafana/dashboards/buildbuddy.json
Handled gRPC requests per second by status is not used on either executors or workflow executors.
> Remove unused grafana dashboards

- server/backends/disk_cache/BUILD
- server/backends/disk_cache/disk_cache.go
- server/metrics/metrics.go
Keep a prom counter with the last evicted item's age (in usec), per partition, and update it when items are evicted.
> Record the last evicted item age so we can monitor cachet eviction

- tools/metrics/grafana/dashboards/buildbuddy.json
Graph the avg last evicted item age.
Looks like this on dev:
> Graph the avg last evicted item age

- enterprise/server/remote_execution/container/container.go
This allows quickly testing local image builds without needing to push to a remote registry.
---
> Add flag to allow using local images during development

- app/components/button/button.css
- app/invocation/invocation_menu.tsx
- app/invocation/invocation_share_button.tsx
- enterprise/app/api_keys/BUILD
- enterprise/app/api_keys/api_keys.tsx
- enterprise/app/workflows/BUILD
- enterprise/app/workflows/workflows.tsx
The `<div className="loading" />` would take up the full width of the `<DialogFooterButtons>`, and since `.outlined-button` was recently updated to have `flex-shrink: 1;`, the outlined button would get squished by the loading div. Fixed by using the `<Spinner />` component instead, which does not try to render at 100% width.
---
> Fix button wrapping issue in dialog footer

- tools/metrics/grafana/dashboards/buildbuddy.json
We currently query the metrics that are explicitly defined per pool.
Moving to the generic metrics will fix discrepancies in the prod data due
to counting custom customer executor pools in the default pool graphs.
After this rolls out we can also remove the custom pool scrape config
from Prometheus.
---
> Switch executor pool metrics to use the 'generic' metrics.

- server/eventlog/BUILD
- server/eventlog/eventlog.go
In EventLogWriter, do not write to key value store if the chunk value
hasn't been changed.
> Avoid writing duplicate entries to key value store

- enterprise/server/auth/auth.go
This fixes the issue where Okta users registered through OIDC will be logged out every 60 minutes.
Without this scope, Okta does not send a refresh_token with the authorize response.
Google auth does not support this scope, but instead uses a url parameter `access_type=offline` which we already set thanks to oauth2.AccessTypeOffline on line 91 of auth.go:
https://github.com/coreos/go-oidc/blob/v2.2.1/oidc.go#L30
---
> Request `offline_access` scope from non-Google OIDC providers in order to retrieve refresh token

- server/build_event_protocol/build_event_proxy/build_event_proxy.go
Found out that when using proxy some streams were not complete. It's
because the build event server to which traffic was proxied was sending
ACKs messages along the way, but buildbuddy was not retrieving it,
so those were accumulated till some buffers were filled up.
---
> Retrieve ACKs from build event proxy

- app/root/root.css
- enterprise/app/executors/executor_card.tsx
- enterprise/app/executors/executors.css
- enterprise/app/executors/executors.tsx
- enterprise/app/org/org.css
- enterprise/app/org/org_form.tsx
- enterprise/app/root/root.tsx
- enterprise/server/remote_execution/platform/platform.go
- enterprise/server/scheduling/scheduler_server/BUILD
- enterprise/server/scheduling/scheduler_server/scheduler_server.go
- enterprise/server/test/integration/remote_execution/rbetest/rbetest.go
- proto/config.proto
- proto/scheduler.proto
- server/static/static.go
* Always show all connected executors, even if "use self-owned Linux executors" is not enabled in settings. This fixes https://github.com/buildbuddy-io/buildbuddy-internal/issues/980.
* To avoid confusion while also simplifying the UX in the case where you have Linux executors registered, but haven't enabled "use self-owned Linux executors", show an explicit callout in this case to go to the settings page and enable self-hosted executors.
* The page was starting to get noisy and crowded showing both the full executors list and full setup instructions below it -- so this PR also splits the page into separate "Status" and "Setup" tabs. The tabbed UX should not result in any unnecessary extra clicks in most cases, since we default to the "setup" tab if no executors are currently registered. …
> Show group-owned connected executors even if "use self-owned Linux executors" is not enabled

- .github/workflows/release-mac.yaml
- .github/workflows/release.yaml
This will allow us to re-run mac workflows without creating a new release each time.
Also pins Xcode version.
---
> Split out mac release workflow (to enable re-running independently) and pin xcode version

- enterprise/server/cmd/executor/executor.go
- server/xcode/xcode.go
- server/xcode/xcode_darwin.go
Return error for NewXCodeLocator when Xcode cannot be found.
If NewXCodeLocator returns an error log.Fatal
> Avoid panic when Xcode is not installed

- enterprise/server/remote_execution/container/container.go
- enterprise/server/remote_execution/containers/docker/docker.go
- enterprise/server/remote_execution/dirtools/dirtools.go
- enterprise/server/remote_execution/platform/platform.go
- enterprise/server/remote_execution/runner/runner.go
- enterprise/server/remote_execution/workspace/workspace.go
Decided to go with an alternate approach of specifying a platform prop that controls directory permissions directly.
---
> Revert "Add `dockerUser` platform prop to control Docker user ID and output dir permissions (#1294)"

- app/root/root.css
- enterprise/app/root/root.css
- enterprise/app/sidebar/sidebar.css
- enterprise/app/sidebar/sidebar.tsx
Fixes:
* Fix bottom spacing between profile picker (at bottom) and the bottom edge of the sidebar, which was reproducible in dense mode only
* Fix issue that icons in the group picker become squished when the group name is too long
Refactor:
* Avoid specifying margins where possible and instead use the `gap` property which now has full support in all major browsers: https://caniuse.com/gap. The gap property is cleaner than margins because it allows setting a single CSS property on the parent, rather than having to awkwardly apply margins to all children except the last child.
* Avoid specifying negative margins where possible.
* Avoid non-symmetric padding and margins where possible -- make it so that the top padding almost always matches the bottom padding and left padding almost always …
> Fix some sidebar styling issues and clean up sidebar styles

- enterprise/server/auth/BUILD
- enterprise/server/auth/auth.go
- enterprise/server/auth/auth_test.go
- enterprise/server/backends/authdb/authdb.go
- enterprise/server/saml/saml.go
- server/build_event_protocol/build_event_handler/build_event_handler.go
- server/interfaces/interfaces.go
- server/nullauth/nullauth.go
- server/testutil/testauth/testauth.go
1. change ParseAPIKeyFromString to return a string pointer instead of
a string; and thus allow us to distinguish between when the key is
not set (i.e. 'x-buildbuddy-api-key=' is not present) vs empty key
(i.e. the header is present)
2. also print quotes for "Invalid API Key" message, to make it more
readable when the key is empty.
> Distinguish between key not set and empty key

- app/components/digest/digest.css
- app/components/digest/digest.tsx
- app/invocation/invocation.css
- app/invocation/invocation_action_card.tsx
- app/invocation/scorecard_card.tsx
- app/service/rpc_service.ts
* Don't show an incorrect digest size in the UI / URL if we don't know the digest size (last outstanding issue from buildbuddy-io/buildbuddy-internal#982)
* Don't show `Input files: 0` and instead show "None found" -- in some cases there were input files but we just don't have them available on our side, particularly when not using RBE.
* Misc
* Make the DigestComponent size optional since we don't know it in some cases
* Simplify DigestComponent border-radius to encompass the outer component
* Refactor so that the DigestComponent doesn't specify its own external margins, which makes it less composable; instead specify margin via parents
---
**Related issues**: Fixes https://github.com/buildbuddy-io/buildbuddy-internal/issues/982
> Misc tweaks for cache misses card and action page

- app/auth/auth_service.ts
- app/auth/user.ts
- app/menu/menu.tsx
- enterprise/app/code/code.tsx
- enterprise/app/settings/settings.tsx
- proto/grp.proto
- proto/user.proto
- server/backends/github/github.go
- server/buildbuddy_server/buildbuddy_server.go
- server/tables/tables.go
This allows the user to link a user-specific Github token for use in the Code UI instead of using the org-wide one.
---
> Add user-specific github token

- tools/metrics/grafana/dashboards/buildbuddy.json
My last PR unintentionally changed the dashboard to show only the first
pool by default when you first open the dashboard.
---
> Show all pools by default.

- tools/metrics/docker-compose.grafana.yml
- tools/metrics/grafana/provisioning/deploy/datasources/datasources.yml
- tools/metrics/grafana/provisioning/local/datasources/datasources.yml
- tools/metrics/run.sh
This will allow us to switch our charts over to the new "Time series" charts in Grafana which are based on the [uPlot](https://github.com/leeoniya/uPlot) libary, and are significantly more performant when viewing more than a few minutes of data. From my experience trying it out against dev, the new charts load much more quickly when a time range of 3+ hours is selected, and moving the mouse around the charts is a much smoother experience.
The high-performance charts are available starting from v7.4, but I found v7.4 to have a few small but very annoying bugs (the graph tooltip would rapidly flicker in some cases). v8.3 includes fixes for those bugs.
Confirmed that v8.3 is able to read our existing dashboard JSON, but the next time we make dashboard changes, it may export some JSON which …
> Upgrade Grafana to v8.3

- tools/metrics/grafana/dashboards/buildbuddy.json
- Set proper unit for RBE Prober Latency graph.
- Fix pod regex for the ready metric to match wider range of pod names
---
> Grafana fixes.

- proto/execution_stats.proto
When an action succeeds, action result digest is the same as action
digest; but when an action fails, action result digest contains
result details, but action digest doesn't.
> Add action_result_digest to Execution proto

- enterprise/server/execution_service/BUILD
- enterprise/server/execution_service/execution_service.go
- enterprise/server/remote_execution/executor/executor.go
- server/remote_cache/digest/digest.go
1. When remote execution fails, compute action result digest based on
the original action digest and the invocation id. When if succeeds,
action result digest is the same as action digest. Upload the action
result digest
2. When we convert Execution row from db to proto, set action result
cache using the same logic as above.
> Set ActionResultCache in execution proto

- enterprise/server/test/integration/remote_execution/rbetest/BUILD
- enterprise/server/test/integration/remote_execution/rbetest/rbetest.go
- enterprise/server/test/integration/remote_execution/remote_execution_test.go
- server/testutil/testenv/testenv.go
1. Pass the runtime os and arch to Command.Platform.Properties
2. Set XcodeLocator in test env
3. set default_xcode_version in executor test config
> Make remote_Execution_test pass on darwin arm64

- server/xcode/xcode_darwin.go
The current way made it look the like the ProductBuildVersion was part of the ShortVersionString.
> Adjust Xcode version info output

- enterprise/server/remote_execution/platform/platform.go
- enterprise/server/remote_execution/platform/platform_test.go
- server/interfaces/interfaces.go
- server/xcode/xcode.go
- server/xcode/xcode_darwin.go
We now store a map of sdk -> sdkPath (e.g. `iPhoneSimulator15.2` -> `Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator15.2.sdk`, `MacOSX.sdk` -> `SDKs/MacOSX.sdk`). We now also return an error if we can't find the desired SDK in the desired Xcode version, which is more correct than falling back to a version-less SDK.
This change is more performant, with a map lookup instead of iterating over an array. But more importantly, it is needed for a future change to support using the Xcode Command Line Tools as the default "Xcode" version.
---
> Refactor SDKROOT calculation

- app/invocation/invocation.css
- app/invocation/invocation_build_logs_card.tsx
- app/root/root.css
- app/target/action_card.tsx
- app/target/target_log_card.tsx
- app/target/target_test_log_card.tsx
- app/terminal/terminal.tsx
Updates the terminal component to be more self-contained so that it can render in places other than `.card`.
* Remove external negative margins to avoid unexpected layout shifts
* Give it ownership of the title and subtitle, so that it can manage the layout more directly, without relying on negative margins
* Add a placeholder div which is empty but has the same dimensions as the search bar, so that the title and actions are laid out more naturally and wrap properly on different screen sizes.
Before (layout is shifted upwards, top bar does not have the correct BG color, wrap/download icons are not visible):
After (different invocation, so output is not expected to be the same):
The terminal could use a bit of padding in this screenshot, but I think that should be managed by a separate …
> Make terminal component more self-contained so it can be used to show action outputs

- app/invocation/invocation.css
- app/root/root.css
- app/terminal/terminal.tsx
Just adding padding and border-radius to the `.terminal-container`. Moved the background color to `.terminal-container` instead of `.terminal` so that the padding gets the color as well.
---
> Add styles for invocation action card terminal

- app/invocation/invocation.tsx
- app/invocation/invocation_artifacts_card.tsx
- app/invocation/invocation_model.tsx
- app/target/target.tsx
This prepares us for the impending flip of the `--legacy_important_outputs` flag in future bazel versions: https://github.com/bazelbuild/bazel/pull/14353
---
> Add support for displaying artifacts populated via namedSetOfFiles

- .gitignore
- proto/.gitignore
This new pattern matches `enterprise/server/test/integration/remote_execution/proto/**/*.pb.go`
---
> gitignore generated protos under all dirs, not just /proto

- enterprise/server/api/api_server.go
- enterprise/server/cmd/ci_runner/main.go
- enterprise/server/cmd/smash/smash.go
- enterprise/server/execution_service/execution_service.go
- enterprise/server/remote_execution/dirtools/dirtools.go
- enterprise/server/remote_execution/execution_server/execution_server.go
- enterprise/server/remote_execution/executor/executor.go
- enterprise/server/remote_execution/operation/operation.go
- enterprise/server/test/integration/remote_execution/rbeclient/rbeclient.go
- enterprise/server/test/integration/remote_execution/rbetest/rbetest.go
- enterprise/server/test/integration/remote_execution/remote_execution_test.go
- server/bytestream/bytestream.go
- server/remote_cache/byte_stream_server/byte_stream_server.go
- server/remote_cache/byte_stream_server/byte_stream_server_test.go
- server/remote_cache/cachetools/cachetools.go
- server/remote_cache/digest/BUILD
- server/remote_cache/digest/digest.go
- server/remote_cache/digest/digest_test.go
- tools/vmstart/vmstart.go
Allows the bytestream server to parse upload and download resource names for zstd-compressed blobs:
- Upload resource names follow the pattern `{instance_name}/uploads/{uuid}/compressed-blobs/{compressor}/{uncompressed_hash}/{uncompressed_size}{/optional_metadata}`
- Download resource names follow the pattern `{instance_name}/compressed-blobs/{compressor}/{uncompressed_hash}/{uncompressed_size}`
Changes:
* Expand `InstanceNameDigest` to include the blob compression type (either identity or zstd for now)
* Rename `InstanceNameDigest` to `ResourceName`
* Update string parsing methods to return `*ResourceName, error` instead of `string, *repb.Digest, error` and update regex matchers to recognize `compressed-blobs/zstd`
* Add tests
The only functional difference expected to be introduced by …
> Allow parsing resource names referring to zstd-compressed blobs

- deps.bzl
- go.mod
- go.sum
Not really sure why this only causes an issue in the internal repo, but I believe it has something to do with: https://github.com/bazelbuild/bazel-gazelle/issues/619 and/or https://github.com/bazelbuild/bazel-gazelle/issues/680
The problem is we can't easily add this directive to the internal WORKSPACE file because deps.bzl is in a different repo (the external one):
```
```
---
> Add cloud.google.com/go/iam dependency to fix internal build

- app/target/target_test_cases_card.tsx
- app/target/target_test_document_card.tsx
This fixes https://github.com/buildbuddy-io/buildbuddy/issues/231
---
> Render node's textContent rather than innerHTML when rendering test logs

- docs/rbe-setup.md
All configuration options should be H3 instead of H2
---
> RBE Setup doc: Fix incorrect heading

- server/libmain/libmain.go
- server/remote_cache/capabilities_server/capabilities_server.go
To be pushed in a subsequent release after the `--cache.zstd_transcoding_enabled` flag is live on all servers.
---
> Expose zstd capabilities

- server/remote_cache/byte_stream_server/byte_stream_server.go
- server/remote_cache/byte_stream_server/byte_stream_server_test.go
When Bazel actually completes the upload (as opposed to the upload immediately returning because the digest already exists) -- it will check whether the committed_size matches the _raw_ size of the stream written. The previous impl of committed_size returned the number of _uncompressed_ bytes written.
---
> Fix impl of WriteResponse.committed_size field

- enterprise/server/remote_execution/execution_server/execution_server.go
- enterprise/server/usage/usage.go
- enterprise/server/usage/usage_test.go
- server/tables/tables.go
Also add tests that make it ~impossible to forget to update the usage tracker when new UsageCounts fields are added.
---
**Related issues**: https://github.com/buildbuddy-io/buildbuddy-internal/issues/1063
> Add per-OS execution duration to usage table

- enterprise/server/backends/gcs_cache/BUILD
- enterprise/server/backends/gcs_cache/gcs_cache.go
- enterprise/server/backends/s3_cache/BUILD
- enterprise/server/backends/s3_cache/s3_cache.go
Adds tracing for GCS and S3 caches. For reading from GCS with a reader, we depend on the tracing code
already present in google's GCS libs. An alternative strategy (that I am happy to switch to if it is 
desired) would be to wrap the returned reader with a bundled context so we can start a span on each
call to Read.
---
> Add tracing around s3 and gcs cache network activity

- server/remote_cache/byte_stream_server/byte_stream_server.go
> Ensure zstd decompressor is always closed, even if clients do not send a FinishWrite request

- server/build_event_protocol/build_event_handler/BUILD
- server/build_event_protocol/build_event_handler/build_event_handler.go
- server/eventlog/eventlog.go
Approximates flag parsing by shlex splitting and assuming no options have values of `--curses`
or `--ui_actions_shown`. Actually correct parsing would require reproducing the entirety of all
possible bazel flags in go, which is too much. If we decide correctly parsed options are necessary,
we can instead buffer events until the OptionsParsed event arrives and use the values in that, but
that, too, is cumbersome.
---
> Use `ui_actions_shown` to determine number of log lines to buffer for ANSI

- enterprise/server/hostedrunner/hostedrunner.go
- enterprise/server/remote_execution/platform/platform.go
- enterprise/server/remote_execution/runner/runner.go
- enterprise/server/remote_execution/runner/runner_test.go
- proto/runner.proto
- tools/remotebazel/remotebazel.go
This allows clients to specify preference as to which Bazel instance
their requests get routed.
---
> Add support for specifying an "session affinity key" in the Run API.

- app/invocation/invocation_model.tsx
Previously we were parsing these client side, which is error prone and led to a mismatch in parsing behavior between client and server.
---
> Use invocation proto as source of truth for `repo` `commitSHA` and `branchName`

- server/target/target.go
ts.start_time_usec is the time when the test is first ran. If a test is
cached; then it would be earlier than the created_at_usec.
> Use ts.created_at_usec instead of ts.start_time_usec

- website/blog/buildBuddy-achieves-soc-2-certification.md
- website/blog/buildbuddy-joins-y-combinator.md
- website/blog/buildbuddy-v1-1-0-release-notes.md
- website/blog/buildbuddy-v1-2-1-release-notes.md
- website/blog/buildbuddy-v1-3-0-release-notes.md
- website/blog/buildbuddy-v1-4-0-release-notes.md
- website/blog/buildbuddy-v1-5-0-release-notes.md
- website/blog/buildbuddy-v1-8-0-release-notes.md
- website/blog/buildbuddy-v2-5-0-release-notes.md
- website/blog/buildbuddy-v2-7-0-release-notes.md
Some of the release notes blog post file names / contents got jumbled in the old blog migration.
---
> Update blog posts to point to new images and fix a few jumbled release notes

- server/remote_cache/byte_stream_server/BUILD
- server/remote_cache/byte_stream_server/byte_stream_server.go
* For very small blobs, fix an issue that we often issue multiple separate responses unnecessarily when the fully compressed blob could have been sent in a single response.
* More generally, for streaming compression responses, each Read() from the compressor returns some number of bytes that is very different from our desired 1MB read buffer size. Since we directly pipe the compressor to the stream writer, this means we'll write smaller buffers with varying sizes depending on compression ratio as well as the compressor's window size, which determines how often it flushes. We can fix this by staging through an intermediate buffer that we only flush when it reaches 1MB. But the small fix in this PR should fix this issue for 99+% of blobs, and we will still want to keep this optimization …
> Fix a few minor compression issues

- server/xcode/xcode_darwin.go
If the following Xcode versions are installed:
- 12.0.0.12A7209
- 12.1.0.12A7403
- 12.1.1.12A7605b
- 12.2.0.12B45b
Then we map these input versions to these output versions:
- 12 - > 12.2.0.12B45b
- 12.0 -> 12.0.0.12A7209
- 12.0.0 -> 12.0.0.12A7209
- 12.0.0.12A7209 -> 12.0.0.12A7209
- 12.1 -> 12.1.1.12A7605b
- 12.1.0 -> 12.1.0.12A7403
- 12.1.0.12A7403 -> 12.1.0.12A7403
- 12.1.1 -> 12.1.1.12A7605b
- 12.1.1.12A7605b -> 12.1.1.12A7605b
- 12.2 -> 12.2.0.12B45b
- 12.2.0 -> 12.2.0.12B45b
- 12.2.0.12B45b -> 12.2.0.12B45b
To summarize, we map a less percise version to the highest available version it could match. This is good.
We _also_ currently take a fully qualified version, such as  12.5.0.12E262 and if it doesn't match one of the inputs available above, we make it less percise until it …
> Make Xcode matching more percise

- enterprise/server/cmd/executor/executor.go
- enterprise/server/test/integration/remote_execution/rbetest/rbetest.go
- server/xcode/xcode.go
- server/xcode/xcode_darwin.go
I forgot to make this change when adding support for the Command Line Tools. Technically it's not an error to not have any Xcodes installed, but we will still warn when this happens.
---
> Allow running executor without any Xcode installed

- enterprise/server/test/integration/ci_runner/BUILD
- enterprise/server/test/integration/workflow/BUILD
This ensures that the `ci_runner`, when invoked in these tests, runs in the same environment that it would in production. In particular, this ensures it is using the same version of `git` that we use in prod.
---
> Run ci_runner_test and workflow_test using CI runner image

- enterprise/server/remote_execution/containers/firecracker/BUILD
- enterprise/server/remote_execution/containers/firecracker/firecracker_test.go
- server/testutil/testenv/BUILD
- server/testutil/testenv/testenv.go
* Disable sandboxing
* Fix error caused by HOME dir not being defined
---
> Make firecracker_test work with `bazel test`

- enterprise/app/executors/executor_card.tsx
- enterprise/app/executors/executors.tsx
- enterprise/app/org/org_form.tsx
- enterprise/server/remote_execution/execution_server/execution_server.go
- enterprise/server/remote_execution/platform/platform.go
- enterprise/server/scheduling/scheduler_server/BUILD
- enterprise/server/scheduling/scheduler_server/scheduler_server.go
- enterprise/server/scheduling/scheduler_server/scheduler_server_test.go
- proto/scheduler.proto
- server/interfaces/interfaces.go
This PR enables users to choose whether or not to use self-hosted executors at the action level.
It does so by introducing a new platform property called `use-self-hosted-executors`.
For folks that only want to use self-hosted executors, there is still an organization-level switch that defaults all invocations to self-hosted executors, and disallows the use of cloud-hosted executors.
The wording of this switch updated slightly to `Use self-hosted executors ` => `Default to self-hosted executors` but the functionality effectively remains the same for existing users.
Also updated the "Enabled" language for executors to "Default" to match this behavior.
---
> Allow mixing of self-hosted and cloud-hosted executors

- server/testutil/testenv/BUILD
- server/testutil/testenv/testenv.go
- server/util/uuid/uuid.go
For some reason, HOME and XDG_CONFIG_HOME don't seem to be defined when running `bazel test //...` locally, but they _are_ defined when running remotely, at least on my machine. So `os.UserConfigDir` returns an error. Fixed by detecting TEST_TMPDIR and using that instead.
---
> Fix error returned by uuid.GetHostID when running some tests locally

- app/root/root.css
- app/target/action_card.tsx
- app/target/target_log_card.tsx
- app/target/target_test_document_card.tsx
- app/target/target_test_log_card.tsx
- app/terminal/terminal.tsx
They're not really compatible with the way we render the terminal search box.
On small screens they would wrap and overlap with terminal content.
This PR removes/combines useless subtitles and breaks out useful ones into their own card.
---
> Remove terminal subtitles

- enterprise/server/remote_execution/runner/runner.go
The fix for https://github.com/buildbuddy-io/buildbuddy-internal/issues/1076 involves two parts:
1. Update our recommended command to the following:
```diff
docker run \
+    --volume /tmp/buildbuddy:/buildbuddy \
--mount type=bind,source=/var/run/docker.sock,target=/var/run/docker.sock \
gcr.io/flame-public/buildbuddy-executor-enterprise:latest \
+    --executor.host_executor_root_directory=/tmp/buildbuddy \
--executor.docker_socket=/var/run/docker.sock \
--executor.app_target=grpcs://remote.buildbuddy.dev \
--executor.api_key=XXXX
```
2. (This PR) Respect the `host_executor_root_directory` flag in environments other than k8s. The current behavior of only supporting this flag on k8s is most likely arbitrary (reviewers can correct me if I am wrong :sweat_smile: )
---
**Version bump**: …
> Respect executor host root dir flag when not running on k8s

- enterprise/app/executors/executors.tsx
- enterprise/server/remote_execution/runner/runner.go
- server/config/config.go
Also rename `executor.host_executor_root_directory` to `executor.host_root_directory` while we still can (it's unlikely that anyone is using this flag yet, since we haven't documented it anywhere, and it previously wasn't working as intended -- see https://github.com/buildbuddy-io/buildbuddy/pull/1445)
---
> Fix docker command for running the executor

- enterprise/dockerfiles/ci_runner_image/Dockerfile
- enterprise/server/cmd/ci_runner/main.go
- enterprise/server/cmd/ci_runner/run_local.sh
- enterprise/server/test/integration/ci_runner/BUILD
- enterprise/server/test/integration/workflow/BUILD
- enterprise/server/workflow/service/service.go
Use "partial clones" to speed up git checkouts.
The partial clone feature allows delaying fetching relevant blobs until they are
actually needed (e.g. when checking out a branch).
This is particularly useful for cold Hosted Bazel instances.
---
> Use "partial clones" to speed up git checkouts.

- deps.bzl
- enterprise/server/cmd/ci_runner/BUILD
- enterprise/server/cmd/ci_runner/main.go
- enterprise/server/test/integration/ci_runner/ci_runner_test.go
- go.mod
- go.sum
- tools/remotebazel/remotebazel.go
This allows us to show interactive git & bazel progress without hacks.
---
> Allocate pseudo-tty in CI runner when executing commands.

- app/invocation/child_invocation_card.tsx
- app/invocation/child_invocations.tsx
- app/invocation/invocation.tsx
- app/invocation/invocation_model.tsx
- app/invocation/invocation_overview.tsx
- app/invocation/invocation_tabs.tsx
- enterprise/app/history/history_invocation_card.tsx
- enterprise/server/cmd/ci_runner/main.go
- proto/build_event_stream.proto
The runner will report child invocation information via the new
`ChildInvocationsConfigured` and `ChildInvocationCompleted` events that
can be used for both workflows & hosted bazel invocations.
Invocation history:
Invocation details:
---
> Have Hosted Bazel runs be displayed more naturally in the UI.

- server/build_event_protocol/build_event_handler/build_event_handler.go
- server/build_event_protocol/target_tracker/target_tracker.go
- server/tables/tables.go
1. Remove Invocation PK column from Invocations and
TargetStatuses
2. DB Migration:
- For MySQL, use ALTER TABLE DROP PRIMARY KEY, ADD PRIMARY KEY
statement
- For SQLite, rename the old TargetStatuses table before auto
migration; therefore, gorm will create TargetStatuses table
from the new schema; In post migration, use INSERT to backfill
the data
> Drop invocation pk column

- .gitignore
Otherwise we can't have blog posts files start with `bazel-`.
---
> Make `bazel-*` exclude more specific

- proto/config.proto
- server/config/config.go
- server/static/static.go
Define a server flag that decides whether to enable the new V2 test grid query and pipe it up to the client.
---
> Add config flag for test grid v2

- dockerfiles/default_execution_image/Dockerfile
According to https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#run
* It's always recommended to run `rm -rf /var/lib/apt/lists/*` (shaves off about 100MB)
* The official Ubuntu/Debian images should run `apt-get clean` automatically, but I found that there are things in the apt cache that could be cleaned (shaving off around another 100 MB). The explicit `apt-get clean` might be needed because we are on an older ubuntu version (16.04) or because Google's RBE image doesn't do this automatically for some reason.
---
> Clean apt cache after installing deps in default RBE image

- enterprise/server/remote_execution/platform/platform.go
The new image version has `docker-ce` installed. Compressed size is about 90MB increased from the previous image (8.6%)
---
> Bump default execution image version

- enterprise/server/cmd/ci_runner/main.go
- enterprise/server/test/integration/ci_runner/ci_runner_test.go
This makes the synthetic hosted bazel invocation look more like a
regular invocation in the UI.
---
> Normalize hosted bazel args in runner.

- server/build_event_protocol/build_event_handler/build_event_handler.go
- server/build_event_protocol/target_tracker/target_tracker.go
- server/tables/tables.go
Revert "Fix TargetStatuses Insert Statement"
This reverts commit bfe6dfd9273cc778984e0e68e96d4a51f37e2b22.
Revert "address comments"
This reverts commit 106ef207090913079d9aa25f6cb327e593ab7a52.
Revert "Use INPLACE and LOCK=NONE"
This reverts commit 67f6c59b4cc3c23f595ed1afae113932753ee666.
Revert "Drop Invocation PK Column"
This reverts commit c488d640e201dcab982476adb60f776c31af99ec.
> Revert Primary Key Migration

- enterprise/server/remote_execution/containers/firecracker/firecracker.go
When testing docker-in-firecracker in dev, I found that dockerd takes a bit longer to init than it did when testing locally, causing the VM exec server connection timeout to be consistently hit (since we block on dockerd being available before starting the VM exec server). Fixed by bumping the timeout from 3s to 10s.
Also make the errors a bit more verbose, so we get a bit more visibility into where these "context deadline exceeded" errors are coming from in the future (it took me a bit of searching to pinpoint it to the VM exec startup timeout).
---
> Firecracker: Fix context deadline exceeded errors with docker-in-fc actions

- server/remote_cache/byte_stream_server/byte_stream_server.go
- server/remote_cache/byte_stream_server/byte_stream_server_test.go
Context: https://github.com/bazelbuild/bazel/issues/14654
---
> Add workaround for Bazel committed_size check when uploading compressed blobs

- cli/cmd/bb/bb.go
- cli/cmd/sidecar/sidecar.go
[Longstanding bug, felt like a distraction last night so added this] 5 mins (configurable) after recieving the last RPC, the sidecar will gracefully terminate itself
> CLI: Add a timeout to sidecar

- .github/workflows/checkstyle.yaml
- buildfix.sh
This makes sure that `deps.bzl` is up to date before running Gazelle, which updates BUILD files that can reference the repositories in `deps.bzl`.
The checkstyle change isn't strictly needed, but this applies the same ordering there just to keep things consistent.
---
> Move go deps fix before gazelle

- enterprise/app/history/history.tsx
- enterprise/app/root/root.css
> Make repo and commit links more obviously clickable

- .github/workflows/release-m1.yaml
We already do this for the x86_64 build.
---
**Version bump**: Patch.
> Pin arm64 executor build to Xcode 12.4 as well

- server/util/compression/compression.go
The problem is that the pool waits for decoders to be garbage collected before calling `Close`, but decoders can't be garbage collected until `Close` is called (circular logic).
Fixed by adding a lightweight reference around the decoder that can be garbage collected before the decoder can (since it doesn't start any goroutines itself), and when finalized it closes the underlying decoder.
Before (running a bazel build in a loop that uploads a bunch of compressed artifacts to cache, clearing the local cache in between runs and uploading via a new remote instance name):
After (same scenario as above):
Also, save even more memory by setting `WithDecoderConcurrency(1)` -- we don't need the default concurrency of GOMAXPROCS because we don't use these decoders concurrently (yet at least). Each …
> Fix goroutine leak in zstd decoder pool

- docs/workflows-config.md
- enterprise/server/cmd/ci_runner/main.go
- enterprise/server/workflow/config/config.go
- enterprise/server/workflow/service/service.go
Makes the config story consistent between default and non-default (i.e. `buildbuddy.yaml`-configured) workflows, and makes the command line rendered in the UI for the default workflow a bit less messy.
---
**Related issues**: Fixes https://github.com/buildbuddy-io/buildbuddy-internal/issues/835
> Move default workflow args to /etc/bazel.bazelrc

- enterprise/server/cmd/ci_runner/run_local.sh
- Pass a fake `workflow_id` arg so that workflow testing works again.
- Add a `PERSISTENT` option for easier testing of repo sync behavior (rather than fresh clone), while still allowing the locally built CI runner to be swapped into the persistent container. This avoids needing to re-clone the repo each time the CI runner is changed
- Forward `BUILDBUDDY_API_KEY` env var to the CI runner
---
> Improve/fix CI runner development script

- .github/workflows/release-m1.yaml
This Xcode 12.4 was installed to a different path.
---
**Version bump**: None.
> Use correct path in release-m1.yaml

- tools/fix_go_deps.sh
It appears that grep sometimes fails because `head -n 2` is closing the read end of the pipe before `grep` has a chance to write all of its output to the pipe.
Demo:
```bash
for i in $(seq 20); do
(
set -euo pipefail
grep -E '(^require \(|// indirect)' go.mod | head -n 2
) &>/dev/null || echo "pipefail on attempt $i"
done
pipefail on attempt 2
pipefail on attempt 6
pipefail on attempt 8
pipefail on attempt 13
pipefail on attempt 15
```
The fix is to change `grep ...` to `(grep ... || true)` so that the overall command doesn't fail if grep tries to write to a closed pipe.
```bash
for i in $(seq 1000); do
(
set -euo pipefail
( grep -E '(^require \(|// indirect)' go.mod || true ) | head -n 2
) &>/dev/null || echo "pipefail on attempt $i"
done
```
---
> Fix occasional pipe failure in fix_go_deps.sh

- enterprise/server/remote_execution/containers/firecracker/firecracker.go
It looks like as of firecracker v0.25, passing more than one `--` to bootArgs is not allowed, even if `--` is used as a prefix rather than a standalone arg. It causes the error
```
Internal: Failed starting machine: [PUT /actions][400] createSyncActionBadRequest  &{FaultMessage:Invalid kernel command line: Too many `--` in kernel cmdline.}
```
Was able to repro the error locally after upgrading from v0.24 -> v0.25, and verified that passing the args with a single `-` instead of `--` fixes the issue.
---
> Firecracker: Fix error when passing more than one init flag

- enterprise/server/tasksize/BUILD
- enterprise/server/tasksize/tasksize.go
- enterprise/server/tasksize/tasksize_test.go
- Account for firecracker VM memory overhead in memory estimate. Experimentally, I found that firecracker needs at least 104 MB of memory to be able to run a trivial task (`pwd`). This PR sets the overhead to 150MB to give us some wiggle room. I think this might depend on the size of `initrd.cpio` + `vmlinux` since those get loaded into memory (?) so in the future we might want to calculate the sizes of those files at build time and derive the estimate from those sizes.
- Increase memory and disk estimates when using docker-in-firecracker. I found that running a `mysql:8.0` image inside a test requires at least 400MB additional memory (on top of the default estimate for a `small` test) and about 4GB additional disk space. I derived the estimate values by multiplying those by 2x and 3x, …
> Firecracker: Improve default task sizing

- enterprise/server/raft/api/BUILD
- enterprise/server/raft/api/api.go
- enterprise/server/raft/bringup/bringup.go
- enterprise/server/raft/cache/BUILD
- enterprise/server/raft/cache/cache.go
- enterprise/server/raft/cache/cache_test.go
- enterprise/server/raft/client/client.go
- enterprise/server/raft/constants/constants.go
- enterprise/server/raft/keys/keys.go
- enterprise/server/raft/replica/BUILD
- enterprise/server/raft/replica/replica.go
- enterprise/server/raft/replica/replica_test.go
- enterprise/server/raft/sender/sender.go
- enterprise/server/raft/store/BUILD
- enterprise/server/raft/store/store.go
- proto/raft.proto
- server/gossip/gossip.go
This CL fixes multi-range lookup, cleans up some interfaces, and adds tests for most of the raft operations performed by each replica. It also moves Read to store so that it correctly respects range leases, preventing a problem where a node could read stale or missing data from a replica that was restarted and is still catching up.
> Add tests for replica

- enterprise/server/remote_execution/runner/BUILD
- enterprise/server/remote_execution/runner/runner.go
- enterprise/server/remote_execution/runner/runner_test.go
* Fix "unexpected runner state" errors in both Run and Add when the pool is shutdown mid-task
* Fix NPE due to unsynchronized concurrent access to `p.runners` when the pool is shutdown mid-task
---
**Related issues**: Fixes https://github.com/buildbuddy-io/buildbuddy-internal/issues/1158
> Fix some runner pool shutdown issues

- enterprise/server/cmd/smash/BUILD
- enterprise/server/cmd/smash/smash.go
- enterprise/server/raft/client/client.go
- enterprise/server/raft/rangelease/rangelease.go
- enterprise/server/raft/sender/sender.go
- enterprise/server/raft/store/BUILD
- enterprise/server/raft/store/store.go
- Stop monitoring smash
- Smarter logic around cache/uncaching a replica
- Dedupe containsMetaRange function
- Ensure default context is set before interacting with nodehost.
> raft: cleanup / small fixes

- proto/build_event_stream.proto
- server/build_event_protocol/target_tracker/target_tracker.go
- server/target/target.go
1. Parse Aborted events and set appropriate test statues for the target
statuses.
2. Write the target statuses when we process the last messages instead
of when we receive the Finished event. Otherwise, we will skip many Aborted events.
https://github.com/buildbuddy-io/buildbuddy-internal/issues/1160
> Parse Aborted build events

- enterprise/server/webhooks/github/github.go
If a non-HTTP error is returned, then the response might be nil.
---
> Fix NPE in github.go

- app/format/format.tsx
- app/format/format_test.ts
- enterprise/app/trends/cache_chart.tsx
- enterprise/app/trends/trends.tsx
- enterprise/app/trends/trends_chart.tsx
* More natural time formatting (1m 15s instead of 1.25m)
* Fix y-axis precision in trends charts. Sometimes, two Y-axis ticks would have the same formatted values (see screenshot) since they weren't being rendered with high enough precision.
* Prevent y-axis in trends charts from showing fractional values for whole-number charts, such as users, branches, etc, to prevent showing ticks representing "1.5 users" etc.
BEFORE (History card shows 1.31m)
AFTER
BEFORE (2M is shown twice in trends chart y-axis)
AFTER
BEFORE (each tick in trends chart y-axis represents 0.75 branches -- nonsensical)
AFTER
---
**Related issues**: https://github.com/buildbuddy-io/buildbuddy-internal/issues/1100
> Misc number formatting fixes

- enterprise/app/root/root.css
- enterprise/app/root/root.tsx
- enterprise/app/tap/tap.css
- enterprise/app/tap/tap.tsx
- Make test labels stick to the left of the screen
- Make the top header stick to the top of the screen
- Move the x-axis "load more" button to the top header
This change affects the current test grid, not just V2.
https://user-images.githubusercontent.com/2414826/153301613-7bf965e0-ba04-4642-a0d2-6d5082bdbe11.mp4
---
> Improve test grid layout

- enterprise/server/cmd/ci_runner/main.go
- enterprise/server/test/integration/ci_runner/ci_runner_test.go
`/etc/bazel.bazelrc` is not writable when running the test locally in the bazel sandbox, so the CI runner encounters a fatal error.
The fix in this PR is to disable writing this file only in tests. This is not ideal because then this logic won't be exercised. But the other options I considered seem worse:
- Revert the /etc/bazel.bazelrc behavior. Not a good option IMO because the benefits of this approach outweigh the downsides in terms of testability.
- Make failed writes to /etc/bazel.bazelrc non-fatal: this is not great because the test would then behave differently locally vs. on CI (where it is run inside a docker container with /etc writable), making it difficult to debug.
- If /etc is not writable, write ~/.bazelrc instead: this is also not great because ~/.bazelrc overrides the …
> Fix local ci_runner_test

- app/components/select/select.css
- enterprise/app/tap/BUILD
- enterprise/app/tap/tap.css
- enterprise/app/tap/tap.tsx
- Add repo picker pinned just to the right edge of the page title
- Another option was to place it with the other dropdowns, but this placement prevents it from jumping around when switching between empty and nonempty repos
- Repo picker selection defaults to the value in the URL, or the last selected repo (stored in localStorage)
- When the page loads, fetch the list of repos in the background, in parallel with test targets.
- If no repo is selected, wait for the repos to be fetched before fetching targets so that we have some repo to filter by.
https://user-images.githubusercontent.com/2414826/153500304-4c3a4f3e-9697-45ad-88c7-2418e14b3e17.mp4
---
> Add repo picker for test grid V2

- rules/yarn/index.bzl
- website/BUILD.bazel
- website/README.md
Adds a really dumb Yarn rule that runs a yarn command or bundles the `build` directory into a tar.
Updated website README to document the 3 workflows:
- Development with live reload
- Previewing production build locally
- Bundling static tar
---
> Add BUILD file to the marketing website so it can be built and developed with Bazel

- server/build_event_protocol/target_tracker/BUILD
- server/build_event_protocol/target_tracker/target_tracker.go
- server/util/timeutil/BUILD
- server/util/timeutil/timeutil.go
1. only use deprecated fields as a fallback
2. remove result struct -- it's set but not used. As a result,
deprecated fields: test_attempt_start_millis_epoch and
test_attempt_duration_millis are removed
> Use first_start_time and total_run_duration

- .bazelrc
- buildbuddy.yaml
- enterprise/server/remote_execution/containers/docker/BUILD
- enterprise/server/remote_execution/containers/docker/docker_test.go
Using the new docker-in-firecracker support to run `docker_test` on CI.
WIP: Blocked on https://github.com/buildbuddy-io/buildbuddy-internal/issues/1151
---
> Get docker_test running in CI

- app/format/format.tsx
- app/util/BUILD
- app/util/proto.ts
- proto/BUILD
Usage:
- Instead of `format.formatDateMillis(someProto.someTimestampMillis)`, call `format.formatDate(proto.timestampToDateWithFallback(someProto.someTimestamp, someProto.someTimestampMillis))`
- Instead of `format.durationMillis(someProto.someDurationMillis)`, call `format.durationMillis(proto.durationToMillisWithFallback(someProto.duration, someProto.durationMillis))`
---
> Add some utils to help with bazel 5 proto timestamp/duration migration

- buildbuddy.yaml
Can be re-enabled once docker-in-firecracker works in prod
---
> Disable docker test workflow

- proto/build_event_stream.proto
For consistency with the latest BEP protos.
> Deprecate millis in BB-specific build events

- enterprise/server/test/integration/build_logs/BUILD
- enterprise/server/test/integration/build_logs/build_logs_test.go
- server/build_event_protocol/accumulator/BUILD
- server/build_event_protocol/accumulator/accumulator.go
- server/build_event_protocol/event_parser/BUILD
- server/build_event_protocol/event_parser/event_parser.go
- server/build_event_protocol/event_parser/event_parser_test.go
Migrate finish_time_millis and start_time_millis from event_parser, and
build_logs_test
> Migrate finish_time_millis and start_time_millis

- enterprise/server/test/integration/workflow/workflow_test.go
- enterprise/server/workflow/service/service.go
- server/config/config.go
Same issue as https://github.com/buildbuddy-io/buildbuddy/pull/1563 -- the fix is the same as well (setting `--write_system_bazelrc=false` on the CI runner).
---
> Fix local workflow integration test

- enterprise/server/cmd/ci_runner/main.go
- enterprise/server/workflow/service/service.go
This will allow us to run dev workflows against dev and prod workflows against prod, by adding the following to our .bazelrc:
```
build:workflows --config=buildbuddy_bes_backend
build:workflows --config=buildbuddy_bes_results_url
build:workflows --config=buildbuddy_remote_cache
build:workflows --config=buildbuddy_remote_executor
```
---
> Add workflow systemrc configs for env-specific endpoints

- app/compare/BUILD
- app/compare/diff_preprocessing.tsx
- delete first_started_ms and last_ended_ms in
BuildMetrics.ActionSummary.ActionData
- delete BuildStarted.StartTime and BuildFinished.FinishTime
> remove new timing fields when comparing invocations

- .bazelrc
This causes problems for BB code, which wants to use the `buildbuddy-ci-runner` image for the RBE image (so that the target platform matches the host platform), but the CI runner image doesn't (yet?) have Docker installed.
Example failure:
https://app.buildbuddy.dev/invocation/0255ebea-bafb-43fe-b0e2-fea27ec6d6fd?actionDigest=1fa103e9af0da4afabefe962260b88007243a10a1cf96d01489d423fda36703e/284&actionResultDigest=d020edebebf3c2ca9a0d4531a76cad4ec7526f443a0fbd14df49146c7e85a4f1/284#
---
> Don't build docker tests by default

- app/invocation/invocation_details_card.tsx
- app/invocation/invocation_overview.tsx
This field is deprecated and no longer set.
> Remove usages of TargetsLoaded

- .bazelrc
- buildbuddy.yaml
This will allow us to re-enable workflows in dev, with dev CI runner actions pointing at dev BB endpoints.
Here are the new systemrc configs in action (screenshot from the command line displayed in the UI):
---
**Related issues**: https://github.com/buildbuddy-io/buildbuddy-internal/issues/1140
> Re-enable systemrc for workflows

- enterprise/server/remote_execution/runner/runner.go
This will allow seeing the firecracker VM output without having to make a code change.
---
> Firecracker: Enable debug mode when --debug_stream_command_outputs is set

- server/build_event_protocol/build_event_handler/build_event_handler.go
Attempt at fixing the error: `"Failed to write cache stats: stats recorder task buffer is full"`, which we believe is happening when all stats recorder workers have returned.
Also replace some `log.Errorf` occurrences with `alert.UnexpectedEvent` so we can be alerted of this more quickly in the future.
---
> Don't return from stats recorder goroutine when invocations are retried

- enterprise/server/cmd/goinit/main.go
- server/util/rlimit/rlimit.go
The current limit (4096) is not sufficient for large Bazel builds.
The default process hard limit in the kernel is 4096, but it is modifiable by any
privileged process. The system hard limit is much higher.
---
> Raise open file descriptor limit for VMs.

- enterprise/server/cmd/server/main.go
Log an error and fail to start when run with an unsupported configuration.
> Log an error and fail to start when run with an unsupported configuration.

- server/build_event_protocol/build_event_handler/build_event_handler.go
- server/metrics/metrics.go
* Refactor workers so that it's more obvious that they should run forever, so we don't accidentally terminate them.
* Add metrics so we can monitor/alert on the status of these finalizers.
* Use more than one invocation lookup worker for webhook notifications (previously all webhook notifications were blocked on a single worker looking up invocations in serial).
---
> Refactor invocation finalization workers and add prometheus metrics

- enterprise/server/remote_execution/containers/firecracker/BUILD
- enterprise/server/remote_execution/containers/firecracker/firecracker.go
- server/config/config.go
Mounting the filesystem file directly is significantly faster.
This is behind a flag for now because it doesn't work well locally due
to needing root. I tried using `udisksctl` to get around this
requirement but ran into the following issues:
1) On local Ubuntu, at least on my
installation, something automatically mounts the filesystem as soon as I
set up the loop device even before I call "mount".
2) On a deployed image, we would need to have DBus & udisk daemons
installed and running for this to work.
---
> Add option to mount workspace ext4 fs instead of extracting contents.

- tools/metrics/prometheus/prometheus.yml
The grafana `pool` variable values are determined using the `executor*` regex, so update the local job name to match this regex.
---
> Fix prometheus scrape configs for local executor

- server/build_event_protocol/build_event_handler/build_event_handler.go
Some invocations still indicate that the cursor is trying to move 1 line above the top of the
screen, so let's add 1 more line. I think this may be trying to erase a newline at the end of
the first line outside the buffer and not actually affecting the output display, since I
haven't seen malformed logs since we last incremented the ANSI buffer, but this should
silence complaints in the log.
---
> Add one more line to ansi buffer

- enterprise/server/backends/pubsub/BUILD
- enterprise/server/backends/pubsub/pubsub.go
- enterprise/server/backends/pubsub/pubsub_test.go
- enterprise/server/cmd/server/main.go
- enterprise/server/remote_execution/execution_server/BUILD
- enterprise/server/remote_execution/execution_server/execution_server.go
- enterprise/server/scheduling/scheduler_server/BUILD
- enterprise/server/scheduling/scheduler_server/scheduler_server.go
- enterprise/server/test/integration/remote_execution/BUILD
- enterprise/server/test/integration/remote_execution/remote_execution_test.go
- enterprise/server/util/rbeutil/BUILD
- enterprise/server/util/rbeutil/rbeutil.go
This PR adds the ability to detect if execution related data has disappeared
because Redis restarted and lost data or because a Redis shard went
away. The detection is built into the PubSub subscription. The PubSub
subscriber monitors the state of the PubSub stream in the background
and publishes an error to the subscription client if the PubSub stream
disappears.
If we detect that a PubSub stream has gone away, we generate a synthetic
operation failure message to Bazel and rely on Bazel to retry execution
of the action.
---
> Redis unavailability handling.

- enterprise/app/tap/tap.css
This way, the horizontal scrollbar renders at the bottom of the page instead of awkwardly in the middle.
---
> Make test grid extend to fill remainder of viewport vertically

- tools/fix_go_deps.sh
When grep terminates early (due to "head -n2") it occasionally prints "grep: broken pipe" for some reason. Silence this output to prevent it from showing up in the diff.
I can't repro this locally, so this PR is just an attempt to fix.
---
> Fix another source of 'broken pipe' errors in fix_go_deps

- server/util/redact/redact.go
- server/util/redact/redact_test.go
The URL secret regex was redacting `--flag_name=@repo//some/package` since it matches `--flag_name=@`. The fix is to split this up into two parts (flag name and flag value), so that the flag value `@repo//some/package` is redacted on its own -- the regex does not match this.
---
**Related issues**: Fixes https://github.com/buildbuddy-io/buildbuddy-internal/issues/1197
> Prevent flag names in combined form from getting stripped out

- app/auth/BUILD
- app/auth/auth_service.ts
- enterprise/server/auth/auth.go
- enterprise/server/auth/auth_test.go
- enterprise/server/saml/saml.go
This should greatly reduce the frequency that users with {no refresh token, short-lived refresh tokens, SAML auth} see the login screen. It should now only ever be shown if they manually log out or if access is revoked on the auth provider side.
On the client side: 
- Attempt to refresh the token if we get a "session expired" error message on the initial page load
- If token refresh fails, try to auto-relogin once by redirecting to the /login/ page
On the server side:
- Return a "session expired" error message:
- if we are attempting to refresh the OIDC token, and the refresh fails
- if the slug cookie is set, but we don't have a valid SAML session
- Only force the OIDC consent screen to be showed if a session ID isn't set (i.e. the user has logged out).
- Fallback to cookies for issuer / …
> Attempt to auto-relogin when sessions expire

- enterprise/server/remote_execution/containers/firecracker/firecracker.go
- enterprise/server/remote_execution/containers/firecracker/firecracker_test.go
This is for 2 reasons:
- When adding a container to the runner pool, if `Pause` fails, then the pool will call `Remove`. Since `FirecrackerContainer.Pause` internally calls `FirecrackerContainer.Remove`, `Remove` winds up getting called twice.
- When tests fail between `Create` and `Remove`, the networks are left hanging around on the machine, causing the next test execution to fail. Now, we can register `Remove` as a cleanup func just after calling `Create`, without worrying about whether the test has already called `Pause` or `Remove` by the end of the test.
---
> Firecracker: Ensure containers are only removed once

- enterprise/server/remote_execution/containers/podman/podman.go
Once we mounted /var/lib/containers, we don't need to use /fuse/overlay
mount program.
> Remove storage global options for podman

- app/invocation/invocation_details_card.tsx
For workflows, these wind up just showing `bazel`.
At some point we might want to show the CI runner command line, but that will require a few BES changes, so for now just hide these.
Review is easier with whitespace diff disabled: https://github.com/buildbuddy-io/buildbuddy/pull/1667/files?diff=split&w=1
---
> Hide explicit + effective command lines for workflow invocations

- enterprise/server/cmd/goinit/main.go
- enterprise/server/remote_execution/containers/firecracker/BUILD
- enterprise/server/remote_execution/containers/firecracker/firecracker.go
- enterprise/server/remote_execution/containers/firecracker/firecracker_test.go
- enterprise/server/remote_execution/snaploader/snaploader.go
- enterprise/server/util/ext4/ext4.go
- enterprise/server/vmexec/vmexec.go
- Split the mounted RW drive into 2 drives: `scratchfs` (persists across container reuse, not hot-swapped for now) and `workspacefs` (hot-swappable)
- Add a `SyncWorkspace` function to allow hot-swapping the workspace device
The `SyncWorkspace` function is not actually called yet because it would wind up doing unnecessary extra work in the hosted bazel case, since hosted bazel actions have no explicit inputs or outputs that they care about. Specifically, we'd unnecessarily nuke the workspace and then re-create an ext4 image with the same contents. Workspaces can be rather large since they can contain an entire git repo, so this would likely slow down hosted bazel too much.
PRs to follow:
* Update the CI runner to write its contents to the scratch disk (at `/root`) instead of the workspace …
> Firecracker: Add support for hot-swapping workspaces

- enterprise/server/remote_execution/containers/podman/podman.go
Use the default network mode: bridge for podman
Tested with a sh_test that curl www.google.com
> Enable network for podman

- enterprise/server/remote_execution/containers/podman/BUILD
- enterprise/server/remote_execution/containers/podman/podman.go
- enterprise/server/remote_execution/containers/podman/podman_test.go
Also remove two global options "--events-backend=file", "--cgroup-manager=cgroupfs". They are no longer needed in podman 3.4.
> Implement podman lifecycle methods

- enterprise/server/remote_execution/containers/firecracker/firecracker.go
- enterprise/server/remote_execution/containers/firecracker/firecracker_test.go
- enterprise/server/remote_execution/snaploader/snaploader.go
Fixes:
* Fix VM exec server timeout due to forgetting to close the gRPC client connection from a previous VM run. This was introduced in #1672. I suspect that gRPC was trying to reuse the previous connection, which was broken since the VM was paused.
* Fix incorrect `workspaceFSPath` introduced in #1672. Except when getting the initial firecracker config, the workspace FS path should always point to the path in the chroot dir. That PR introduced a change where `workspaceFSPath` pointed to the path under the temp dir `fc-container-*`, which caused a few issues related to cleanup, copying outputs, etc.
Cleanup:
* Clean up some unnecessary/error-prone state related to paths -- workspace FS path in chroot can be computed from `c.getChroot()` and `c.workspaceGeneration`, and scratch FS path …
> Firecracker: Fix some issues with runner recycling

- enterprise/server/remote_execution/filecache/BUILD
- enterprise/server/remote_execution/filecache/filecache.go
- server/metrics/metrics.go
This will help us monitor the health of the filecache as we roll out firecracker, which adds large artifacts to the filecache and depends on the filecache for restoring VMs from snapshot.
---
**Related issues**: https://github.com/buildbuddy-io/buildbuddy-internal/issues/1214
> Add filecache last evicted age metric

- enterprise/server/remote_execution/filecache/BUILD
- enterprise/server/remote_execution/filecache/filecache.go
- server/metrics/metrics.go
This will provide a straightforward way to observe the filecache hit rate.
---
**Related issues**: https://github.com/buildbuddy-io/buildbuddy-internal/issues/1214
> Add file cache request count metric

- enterprise/server/remote_execution/filecache/filecache.go
- server/metrics/metrics.go
This will allow us to understand whether an unhealthy file cache is due to a large amount of small/moderately sized files being added, vs. a small/moderate amount of very large files.
---
> Add filecache file size metric

- cli/cmd/sidecar/sidecar.go
- enterprise/server/cmd/executor/executor.go
- enterprise/server/cmd/server/main.go
- enterprise/server/remote_execution/containers/bare/BUILD
- enterprise/server/remote_execution/containers/bare/bare_test.go
- enterprise/server/test/integration/remote_execution/rbetest/BUILD
- enterprise/server/test/integration/remote_execution/rbetest/rbetest.go
- enterprise/server/test/integration/workflow/workflow_test.go
- server/cmd/buildbuddy/main.go
- server/config/config.go
- server/testutil/testenv/testenv.go
- server/util/capabilities/capabilities_test.go
- server/util/testing/flags/BUILD
- server/util/testing/flags/flags.go
- server/util/url/url_test.go
- app changes for moving config into flags defined in code
- update tests for change to flag handling
`config.go` now registers only missing flags, and thus can no longer register them in its `init` function,
as not all flags can be guaranteed to be defined when config is imported. The code which was pointing
the default FlagSet at the `sharedGeneralConfig` has been repurposed to allow us to define missing flags
or define flags whose values point to a given `generalConfig` for ease of assignment to and from the
default flags. Explicitly defined flags take precedence over explicitly defined config values, which
in turn take precedence over default flag values. On the initial flag parse, the explicitly set flags
are saved so that they may be referenced for that precedence later. The string …
> Refactor flag handling to allow config flags to be explicitly defined in code

- tools/metrics/grafana/dashboards/buildbuddy.json
- Charts are added under the "executor pool" panel
- Hit rate is averaged over the configured time window and aggregated across all executors
- Last eviction age shows the per-executor gauge value
- Added file size shows p50, p90, p99, p99.99 across all executors
---
**Related issues**: Fixes https://github.com/buildbuddy-io/buildbuddy-internal/issues/1214
> Add filecache grafana charts

- enterprise/server/auth/auth.go
At this point the JWT has already been validated.
We undergo the extra step of making sure the token's at_hash matches - but the at_hash parameter is optional and not set by all auth providers: https://openid.net/specs/openid-connect-core-1_0.html#CodeIDToken
The go-oidc library mentions: "It is the caller's responsibility to ensure that the optional access token hash is present for the ID token before calling this method":
https://github.com/coreos/go-oidc/blob/d42db69c79f2fa664fd4156e939bf27bba0d2f68/oidc/oidc.go#L371
Also improves error logging to help debug situations like these in the future.
---
> Don't fail if a valid JWT doesn't contain (optional) at_hash

- enterprise/server/remote_execution/containers/firecracker/containeropts.go
- enterprise/server/remote_execution/containers/firecracker/firecracker.go
- enterprise/server/remote_execution/containers/firecracker/firecracker_test.go
- enterprise/server/remote_execution/platform/platform.go
- enterprise/server/remote_execution/runner/runner.go
- enterprise/server/util/ext4/ext4.go
- tools/vmstart/vmstart.go
Instead of hard-coding the scratch disk size as 2GB, hard-code the workspace size as 2GB and allocate the EstimatedFreeDiskBytes to scratch space instead. This makes sense both for hosted bazel (once we move its working directory to the scratch disk) and for docker-in-firecracker tests (which need most of the disk space for cached image layers).
---
**Related issues**: https://github.com/buildbuddy-io/buildbuddy-internal/issues/1188
> Firecracker: Move slack space allocation to scratch disk

- enterprise/server/cmd/ci_runner/main.go
- enterprise/server/hostedrunner/hostedrunner.go
Depends on https://github.com/buildbuddy-io/buildbuddy/pull/1680
---
**Related issues**: https://github.com/buildbuddy-io/buildbuddy-internal/issues/1188
> Firecracker: Move hosted bazel working dir to scratch disk

- enterprise/server/remote_execution/containers/firecracker/firecracker.go
- enterprise/server/remote_execution/containers/firecracker/firecracker_test.go
- enterprise/server/remote_execution/runner/runner.go
This allows firecracker actions that deal with inputs/outputs to work properly when using runner recyling.
---
**Related issues**: Fixes https://github.com/buildbuddy-io/buildbuddy-internal/issues/1188
> Firecracker: Sync workspace after downloading inputs

- app/invocation/invocation_details_card.tsx
Before, this would link to something like:
[https://github.com/buildbuddy-io/buildbuddy.git/commit/6c69b8c55cbd6ff2518c877611d2c993f236c444](https://github.com/buildbuddy-io/buildbuddy.git/commit/6c69b8c55cbd6ff2518c877611d2c993f236c444)
This link doesn't work -- stripping the `.git` suffix fixes it:
https://github.com/buildbuddy-io/buildbuddy/commit/6c69b8c55cbd6ff2518c877611d2c993f236c444
---
> Fix broken github commit URL

- enterprise/server/auth/auth.go
Should decouple max execution duration from --remote_timeout when using --experimental_remote_execution_keepalive
---
> Lower internal jwt lifespan from 24h=>6h and always use that

- enterprise/server/remote_execution/commandutil/commandutil.go
- enterprise/server/remote_execution/containers/docker/docker.go
- enterprise/server/remote_execution/executor/BUILD
- enterprise/server/remote_execution/executor/executor.go
This fixes one of the causes for workflows not being retried when the executor shuts down. Workflow actions go through the `Exec` code path (due to runner recycling), and the `ContainerExecInspect` API returns a clean exit code (137) when killed as part of `Remove()`, which is called when the executor shuts down.
The fix is to translate this exit condition to `ErrSIGKILL` and explicitly retry `ErrSIGKILL` errors.
Future work: look into ensuring that all commands are retried whenever they receive SIGKILL (due to OOM), as well as ensure that the `Run()` codepath is well-behaved as well.
---
**Related issues**: https://github.com/buildbuddy-io/buildbuddy-internal/issues/1183
> Ensure docker exec commands are retried during executor shut down

- app/service/rpc_service.ts
- server/http/protolet/BUILD
- server/http/protolet/protolet.go
- server/libmain/libmain.go
This CL allows appending "debug=1" or "debug=true" to a URL in the UI to request the backend to force tracing.
My intent with this CL is to make it easier to debug performance issues in prod: currently it's very difficult to see why queries are slow for a particular page load without setting up a mirror environment and running the same request with debug logging on. After this change, it should only require loading the page with debug=1 and then fishing around in jaeger.
The app enables this functionality by setting an HTTP header in requests to the backend when the debug=1 flag is present in the URL. For simplicity, the header is only set on RPC (via protolet) requests.
The backend protolet previously did not set any gRPC metadata before calling handler implementations -- now it does. …
> Enable web tracing

- server/config/BUILD
- server/config/config.go
This was accidentally broken in
https://github.com/buildbuddy-io/buildbuddy/pull/1671.
Our docker BYOR instructions don't pass a config file.
---
> Allow executor to be started w/o a config file.

- server/tables/tables.go
- server/target/target.go
Add command to the index. 
Need to use prefix indices on VARCHAR(255) 
columns on Mysql, otherwise it returns an error with "Specified key was too long;
max key length is 3072 bytes"
Unfortunately, prefix indexes are not supported on SQLite. Therefore, the index are different based on the dialect. 
Fixes https://github.com/buildbuddy-io/buildbuddy-internal/issues/1212
> Add command to test grid query

- enterprise/server/cmd/ci_runner/main.go
- server/build_event_protocol/accumulator/accumulator.go
- server/build_event_protocol/build_status_reporter/build_status_reporter.go
- server/build_event_protocol/target_tracker/target_tracker_test.go
This prevents the `bazel test //...` statuses from showing up, which are redundant with the action statuses (e.g. "Test all") and can be easily clobbered if multiple actions execute the same bazel command (e.g. "Test all" and "Test all (Mac)" which both run `bazel test //...`).
Tested locally.
---
**Related issues**: Fixes https://github.com/buildbuddy-io/buildbuddy-internal/issues/1229
> Don't report commit statuses for inner workflow invocations

- cli/download/BUILD
- cli/download/download.go
- deps.bzl
- enterprise/server/webhooks/github/BUILD
- enterprise/server/webhooks/github/github.go
- enterprise/server/workflow/service/BUILD
- enterprise/server/workflow/service/service.go
- go.mod
- go.sum
The upgrade gives us access to some generated getters that aren't available in our current version, particularly `PullRequestReview.GetAuthorAssociation()` used in https://github.com/buildbuddy-io/buildbuddy/pull/1704
---
> Upgrade go-github to v43

- enterprise/server/build_event_publisher/BUILD
- enterprise/server/build_event_publisher/build_event_publisher.go
- enterprise/server/cmd/ci_runner/main.go
- enterprise/server/test/integration/build_logs/build_logs_test.go
This fixes an issue that a workflow invocation can be disconnected if the build event stream client is connected to a BB app that is shut down while the stream is in progress and the workflow invocation takes longer than the grace period.
Tested locally.
---
**Related issues**: https://github.com/buildbuddy-io/buildbuddy-internal/issues/1183
> Retry failed workflow invocation streams

- app/docs/setup_code.tsx
- enterprise/app/api_keys/api_keys.css
- enterprise/app/api_keys/api_keys.tsx
- enterprise/server/backends/userdb/BUILD
- enterprise/server/backends/userdb/userdb.go
- proto/api_key.proto
- server/buildbuddy_server/buildbuddy_server.go
- server/interfaces/interfaces.go
- server/tables/tables.go
This allows admins to choose whether or not individual API keys are visible to developers when creating / updating keys.
All existing API keys will only be visible to Admins.
Admin:
User:
> When creating / editing API keys allow admins to chose whether they're visible to developers

- server/tables/tables.go
- server/target/target.go
Commit containing just the fixes (tested locally): https://github.com/buildbuddy-io/buildbuddy/pull/1719/commits/38bea110281ff7d4373fb7de9b062f063bb7671e
* Fix erroneous reference to "TargetStatuses" instead of "Invocations"
* Fix sqlite migration bug that occurs because we check existence of the index pre-migration but defer the drop statement execution until post-automigration. The deferred DROP INDEX fails because the index gets dropped automatically as part of GORM auto-migration (more accurately, GORM recreates the entire table from scratch, copying values from the old table). This behavior only appears to happen for sqlite and not mysql.
---
> Roll forward #1696: Add command to test grid query

- enterprise/server/remote_execution/commandutil/BUILD
- enterprise/server/remote_execution/commandutil/commandutil_test.go
- enterprise/server/test/integration/remote_execution/remote_execution_test.go
I plan on changing some of the error handling logic in RBE so that we can retry errors caused by failing to unpause runners, and make sure we don't return runners back to the pool.
The purpose of this PR is to add some tests to demonstrate and solidify the current behavior of the system, so that it will be more clear what behavior is changing as part of this upcoming error handling PR.
---
> Add some tests for RBE signal handling

- .github/workflows/checkstyle.yaml
Stats from current checkstyle workflows
```
dates   2022-03-15T17:24:28Z - 2022-03-16T17:08:14Z
n       30
min     0:01:49
max     0:07:12
mean    0:03:56
std     0:01:44
p10     0:02:08
p25     0:02:37
p50     0:02:59
p75     0:05:54
p90     0:06:30
```
Will re-evaluate in a few days to see whether things have improved, but results are looking good so far (seeing runs ~1m30s which is faster than all of the runs from this sample)
---
> Mount go cache to speed up checkstyle

- app/BUILD.bazel
- app/components/link/BUILD
- app/components/link/link.css
- app/components/link/link.tsx
Also add an inline `TextLink` component that works exactly like `<a>` but has underline styling:
---
> Add a router-aware Link component

- app/components/link/link.tsx
- enterprise/app/workflows/BUILD
- enterprise/app/workflows/github_import.tsx
- enterprise/server/workflow/service/service.go
Instead of crashing the app, show this error instead:
---
**Related issues**: Fixes https://github.com/buildbuddy-io/buildbuddy-internal/issues/1234
> Fix error handling for github import page

- enterprise/server/backends/userdb/userdb.go
- enterprise/server/workflow/service/service.go
- proto/github.proto
- server/buildbuddy_server/buildbuddy_server.go
- server/interfaces/interfaces.go
* Clear `Group.github_token`
* Delete workflows registered with the GitHub token, and report any issues unregistering webhooks as warnings
This does not actually revoke app access, but just clears our references to the access token. We instead advise the user to revoke access via GitHub's UI.
---
> Implement UnlinkGitHubAccount

- enterprise/server/cmd/ci_runner/main.go
- enterprise/server/workflow/config/BUILD
- enterprise/server/workflow/config/config.go
- enterprise/server/workflow/config/config_test.go
- enterprise/server/workflow/service/service.go
Support a simple wildcard character ( `*` ) to match any branch. Not supporting full regex or glob for now to avoid having to worry about performance.
This wildcard support also lets us simplify the default workflow config. Now, it can be fully static, instead of depending on the base branch.
---
**Related issues**: Fixes https://github.com/buildbuddy-io/buildbuddy-internal/issues/1235
> Support a simple wildcard specifier in workflow config to match any branch

- enterprise/server/workflow/config/config.go
Deleting a line added in https://github.com/buildbuddy-io/buildbuddy/pull/1742/files#diff-c616e5fe98c2a3744d73f798d03567de0daebc665a72adef67300c334560d748R67 because I remembered the reason why we didn't have a `PullRequest` trigger in the default config (it causes workflow actions to be triggered twice on each push to a PR branch). Reverted the change and added an explanatory comment
---
> Revert change to default workflow config

- enterprise/app/settings/github_link.tsx
For some reason, this library fails to build with `Parameter 'e' implicitly has an 'any' type.`, but only when building from the internal repo. Need to dig into why this is happening, but in the meantime this fixes the internal build.
---
> Fix implicit any error for internal build

- enterprise/server/backends/userdb/userdb.go
- server/buildbuddy_server/buildbuddy_server.go
- server/interfaces/interfaces.go
Fixes issue where developers can't view timing profiles.
---
> Don't check visibility when pulling any available api key for invocation

- app/docs/setup_code.tsx
- app/invocation/dense/dense_invocation_overview.tsx
- app/invocation/invocation_cache_card.tsx
- app/invocation/invocation_details_card.tsx
- app/invocation/invocation_error_card.tsx
- app/invocation/invocation_execution_card.tsx
- app/invocation/invocation_fetch_card.tsx
- app/invocation/invocation_filter.tsx
- app/invocation/invocation_in_progress.tsx
- app/invocation/invocation_not_found.tsx
- app/invocation/invocation_overview.tsx
- app/invocation/invocation_raw_logs_card.tsx
- app/invocation/invocation_targets.tsx
- app/invocation/invocation_timing_card.tsx
- app/menu/menu.tsx
- app/target/action_card.tsx
- app/target/target.tsx
- app/target/target_artifacts_card.tsx
- app/target/target_log_card.tsx
- app/target/target_test_cases_card.tsx
- app/target/target_test_document_card.tsx
- app/target/target_test_log_card.tsx
- enterprise/app/code/code.tsx
- enterprise/app/history/history_tabs.tsx
- enterprise/app/login/login.tsx
- enterprise/app/sidebar/sidebar.tsx
- enterprise/app/trends/cache_chart.tsx
- enterprise/app/trends/trends.tsx
- enterprise/app/trends/trends_chart.tsx
Motivation:
* Specifying `props: Props` instead of `React.Component<Props>` prevents the compiler from understanding the expected types of `shouldComponentUpdate` and other lifecycle methods, which can be helpful for catching certain types of bugs. See https://codesandbox.io/s/withered-fog-pq8o3x?file=/src/App.tsx
* Specifying `props: Props` is also incompatible with TS `strict` mode, which would be nice to enable at some point (for better null-safety, etc.)
* When not using type parameters for `State`, the compiler is unable to detect issues with `this.setState`. See https://codesandbox.io/s/dazzling-taussig-0r4s1y?file=/src/App.tsx:0-339
This PR refactors
```
class Foo extends React.Component {
props: Props;
state: State = { ... };
}
```
to
```
class Foo extends React.Component<Props, …
```
> Use type parameters for component props and state

- server/build_event_protocol/target_tracker/target_tracker.go
- server/target/target.go
These NO_STATUS rows are stored when running a test with `--test_tag_filters` and test targets are matched by the pattern (e.g. `//...`) but excluded by the tag filters. For example, when running our "Docker tests" workflow we see that a NO_STATUS gets reported for all targets which aren't tagged with `docker`.
---
**Related issues**: Fixes https://github.com/buildbuddy-io/buildbuddy-internal/issues/1244
> Don't return NO_STATUS rows from TargetStatuses table

- cli/remotebazel/BUILD
- cli/remotebazel/remotebazel.go
We were redrawing log chunks using the physical number of lines which
did not account for any wrapping that occurrs on the local terminal.
---
> Fix log redraw issues when lines are longer than the terminal width.

- enterprise/server/workflow/service/service.go
This allows workflow actions to use different build configurations (e.g. `--define` flags) without discarding the analysis cache for other workflow actions. It also allows actions to run `bazel clean` as the first `bazel_command` without affecting the bazel cache from other actions.
---
**Related issues**: Fixes https://github.com/buildbuddy-io/buildbuddy-internal/issues/1251
> Include workflow action name in runner routing key

- app/invocation/invocation_model.tsx
Use `toFixed(3)` for test times to be consistent with build times, and so that the decimal points line up and times can be more easily compared.
Before:
After:
---
> Fix number formatting of test durations

- buildbuddy.yaml
- enterprise/server/usage/BUILD
- server/testutil/testmysql/BUILD
- server/testutil/testmysql/testmysql.go
This gets `usage_test_mysql` running on CI in about ~6.6s total (for warm runs)
---
> Reuse MySQL server instances across tests

- docs/rbe-microvms.md
I submitted 2 docs site changes at the same time and the new firecracker page isn't showing up.
Making an NOP change to try and redeploy, since re-running the actions didn't work.
---
> NOP change to redeploy docs site

- server/config/config.go
Now that struct slice flags work, `auth.oauth_providers` is a valid flag as long as we give its
fields json tags, as done in this PR.
---
> Enable `auth.oauth_providers` flag

- cli/remotebazel/remotebazel.go
- enterprise/server/cmd/ci_runner/main.go
- enterprise/server/hostedrunner/hostedrunner.go
ci_runner arg changes:
--target_commit_sha can be specified instead of --target_branch to
checkout the target at a specific commit
--push_repo_* args can be omitted
---
> Speed up remote bazel checkouts when base commit doesn't change.

- server/http/protolet/BUILD
- server/http/protolet/protolet.go
- server/util/db/BUILD
- server/util/db/db.go
- server/util/tracing/tracing.go
Example traces look like this:
> Bring back dapper sql tracing; sans the gorm upgrade.

- enterprise/server/remote_execution/executor/executor.go
- enterprise/server/remote_execution/filecache/filecache.go
- server/remote_cache/action_cache_server/action_cache_server.go
- server/util/uuid/uuid.go
Several customers now have bumped into this when attempting to run BuildBuddy in very-locked-down environments (no write perms for config dir) or in unusual configurations (no config dir set?).
This prevent an error in that case, at the cost of generating a less sticky ID.
> Support HostID usecases when we have no permissions

- .github/workflows/release-m1.yaml
This reverts commit ff5607cda7fe417baffbeda0a09f172880c8ce78.
Both paths are currently valid, but we want to standardize on the GitHub runner standard naming.
---
**Version bump**: None.
> Revert "Use correct path in release-m1.yaml"

- enterprise/server/webhooks/github/github.go
- enterprise/server/workflow/service/service.go
Run workflows as trusted whenever the PR author is a trusted member of the organization, even if the repo is a fork.
---
**Related issues**: Fixes https://github.com/buildbuddy-io/buildbuddy-internal/issues/1232
> Run trusted workflows on events from trusted forks

- server/util/consistent_hash/consistent_hash.go
Before:
goos: linux
goarch: amd64
cpu: AMD Ryzen 9 5950X 16-Core Processor
BenchmarkGetAllReplicas-32    	   32829	     31928 ns/op
PASS
After:
goos: linux
goarch: amd64
cpu: AMD Ryzen 9 5950X 16-Core Processor
BenchmarkGetAllReplicas-32    	  129259	      8693 ns/op
PASS
(so roughly a 4x improvement)
> Faster find replicas.

- enterprise/server/api/api_server.go
- enterprise/server/api/api_server_test.go
Currently if you make a `GetAction` API request with a target_id specified, we (incorrectly) return all targets.
This PR fixes that target id filtering logic and adds a test to verify this behavior. 
---
> Fix GetAction API target filtering

- enterprise/server/raft/store/store.go
- server/gossip/gossip.go
- server/gossip/gossip_test.go
Because currently setting tags is synchronous (waits for gossip to broadcast the tag before returning) this makes setting multiple tags much faster (which we do a lot in our store tests).
> Gossip: Set multiple tags at once by default

- enterprise/server/remote_execution/executor/executor.go
- enterprise/server/test/integration/remote_execution/bazel_rbe/BUILD
- enterprise/server/test/integration/remote_execution/bazel_rbe/bazel_rbe_test.go
- enterprise/server/test/integration/remote_execution/rbetest/BUILD
- enterprise/server/test/integration/remote_execution/rbetest/rbetest.go
- server/metrics/metrics.go
- server/testutil/testmetrics/testmetrics.go
Motivation: This will give us greater confidence that any proposed changes to address https://github.com/buildbuddy-io/buildbuddy-internal/issues/1279 won't break the existing retry behavior.
This also buys us test coverage for the following Bazel <-> RBE integrations:
* Bazel's retry behavior based on the error codes that we are returning
* Bazel's stdout/stderr output displayed to the user based on the status codes that we return
Since these two behaviors are directly visible when using bazel with BB RBE, it seems worthwhile to have integration tests in place to enforce that these are working as intended.
---
> Add bazel RBE integration tests

- server/util/rangemap/rangemap.go
- server/util/rangemap/rangemap_test.go
This fixes the panic in https://app.buildbuddy.io/invocation/b1b8a961-c498-4127-b0d0-90ee51d6eb9c?target=%2F%2Fenterprise%2Fserver%2Fraft%2Fstore%3Astore_test and adds a tests for this case.
> Fix panic in rangemap.GetOverlapping

- enterprise/server/remote_execution/executor/executor.go
In the firecracker case, an unclean execution can mean that the VM can be in an unexpected state when we next try to resume it (e.g. if we failed to pause the VM, then there's a good chance unpausing will fail). So for now we can avoid these scenarios by avoid adding containers to the pool if there was an error.
It's difficult to test this codepath with our current setup, so in a separate PR I'm planning on defining interfaces for `runner.Pool` and `runner.CommandRunner` so that we can have `runner.Run()` directly return an error like `InternalError`, which can't be easily triggered otherwise.
---
> Don't return runners to the pool after unclean execution

- enterprise/server/remote_execution/runner/runner.go
- enterprise/server/remote_execution/runner/runner_test.go
Mac workflow executors were only allowing up to 2 workspaces in the pool at once. Since rules_xcodeproj has 3 workflow actions, this was causing a new workspace to be created on every workflow run, resulting in slow workflows.
Instead of using the task size estimate to get pooled runner memory usage (8GB for workflow tasks), use the baseline mem estimate (2.6GB). Assuming 16GB memory, this increases the memory-based max pool count from 2 to 6. In practice, I was seeing bazel resident memory at about 1.2GB (after building buildbuddy enterprise server) and 1.8GB (after building bazel itself), so this 2.6GB estimate seems much more reasonable than 8GB.
---
**Related issues**: https://github.com/buildbuddy-io/buildbuddy-internal/issues/1277
> Tune runner pool for Mac workflow workspace reuse

- enterprise/server/cmd/ci_runner/main.go
- enterprise/server/remote_execution/runner/runner.go
- enterprise/server/remote_execution/runner/runner_test.go
This allows the bazel output base to get cleaned up along with the workspace to prevent it from being "orphaned" when the executor restarts or if runners are evicted from the pool.
See https://github.com/buildbuddy-io/buildbuddy-internal/issues/1277#issuecomment-1087604511
---
**Related issues**: https://github.com/buildbuddy-io/buildbuddy-internal/issues/1277
> Write bazel output base under CI runner workspace dir

- tools/cas/BUILD
- tools/cas/cas.go
This is useful for fetching objects not associated with an invocation, for example workflows that failed to start, or when replaying actions in dev.
I've had this sitting in a branch for a while and have found a few uses for it, and a few other ppl have used it as well. Figured it's worth checking in at this point
---
> Add a CLI tool to fetch objects from cache and print their text representation

- enterprise/server/remote_execution/commandutil/BUILD
- enterprise/server/remote_execution/commandutil/commandutil.go
- enterprise/server/remote_execution/commandutil/commandutil_test.go
- enterprise/server/remote_execution/commandutil/test_binary/BUILD
- enterprise/server/remote_execution/commandutil/test_binary/test_binary.go
- enterprise/server/remote_execution/containers/firecracker/firecracker.go
- enterprise/server/vmexec/vmexec.go
- go.mod
- go.sum
- server/testutil/testfs/BUILD
- server/testutil/testfs/testfs.go
* We fail to collect stdout/stderr from certain bazel tests because the bazel `test-setup.sh` script runs the test child process as its own process group leader. So, [the fix in the last PR to kill processes by pgid](https://github.com/buildbuddy-io/buildbuddy/pull/1822/files#diff-ce918767a53b70309881b30d88900177b4791e488cee8d4449e1c1a01cab920aR113) was not sufficient. Fix this by explicitly killing the process tree by recursively inspecting child pids of the root command process. This fix also benefits the bare runner impl, not just firecracker.
* Move the action timeout calculation closer to when we actually send the exec request (after dialing the exec server), since dialing the exec server can eat up a significant amount of the timeout that would otherwise be allocated to collecting …
> More fixes for firecracker timeout handling

- enterprise/server/workflow/service/BUILD
- enterprise/server/workflow/service/service.go
- server/util/bazel_request/BUILD
- server/util/bazel_request/bazel_request.go
It's a slightly odd link since the invocation is created by the
ci_runner, but it does give us an easy way to find the ci_runner
execution linked to a workflow run.
---
> Associate ci_runner execution with the invocation it's creating.

- enterprise/server/webhooks/github/github.go
- enterprise/server/webhooks/github/github_test.go
Accidentally reverted this logic in another PR. Fixed and updated the test
---
**Related issues**: Fixes https://github.com/buildbuddy-io/buildbuddy-internal/issues/1228
> Set IsTargetRepoPublic field for PR events

- enterprise/server/raft/cache/BUILD
- enterprise/server/raft/cache/cache.go
- enterprise/server/raft/constants/constants.go
- enterprise/server/raft/driver/BUILD
- enterprise/server/raft/driver/driver.go
- enterprise/server/raft/rangecache/rangecache_test.go
- enterprise/server/raft/store/BUILD
- enterprise/server/raft/store/store.go
- enterprise/server/raft/store/store_test.go
- proto/raft.proto
This also removes some of the old FindNodes code that lived in driver.go and associated tests.
> Add initial framework for driver (read-only to start)

- proto/BUILD
- proto/ping_service.proto
- server/rpc/filters/BUILD
- server/rpc/filters/filters_test.go
What I am seeing is that with client/server interceptors enabled (and logging at ERROR level), a simple server and client do 60% more allocations than a bare server.
goos: linux
goarch: amd64
cpu: AMD Ryzen 9 5950X 16-Core Processor
BenchmarkBare-32            	    9894	    102119 ns/op	    8681 B/op	     172 allocs/op
...
BenchmarkInstrumented-32    	    8373	    142681 ns/op	   15834 B/op	     277 allocs/op
PASS
> Benchmark interceptors

- release.py
* Only support python3 (I tested today with python3 and it works, so let's just stick with one python version so we don't have to worry about multiple)
* Stream live command output
* Update messaging at the end of the script
---
> Small release script improvements

- enterprise/server/test/integration/remote_execution/bazel_rbe/BUILD
- enterprise/server/test/integration/remote_execution/bazel_rbe/bazel_rbe_test.go
- enterprise/server/test/integration/remote_execution/rbetest/BUILD
- enterprise/server/test/integration/remote_execution/rbetest/rbetest.go
:point_right: This depends on the runner refactoring in https://github.com/buildbuddy-io/buildbuddy/pull/1877 since we need to be able to stub in a test runner impl that returns arbitrary error results.
---
Add more RBE error handling tests now that we have more flexibility on how we inject errors.
This is in preparation for implementing the changes described here: https://docs.google.com/document/d/1fIC4gt4sZBH89-NkcQn6EEGRhU2rMwV6d0QiJpLw7d8/edit#heading=h.6u7iifm7d5cn
Some of the test assertions added in this PR demonstrate some of the issues that should be corrected as part of these changes.
---
> Add more executor error handling tests

- enterprise/server/remote_execution/containers/docker/BUILD
- enterprise/server/remote_execution/containers/docker/docker.go
- enterprise/server/remote_execution/containers/podman/BUILD
- enterprise/server/remote_execution/containers/podman/podman.go
- enterprise/server/remote_execution/runner/runner.go
- server/config/config.go
This change introduces the capability to pass devices from host machine to execution containers, which are being spawned by the build-buddy.
The rationale: adding support for `/dev/fuse` or any other host-bound devices during Bazel RBE execution.
---
> Allow specifying--dev flag for exec containers

- app/BUILD.bazel
- enterprise/app/BUILD.bazel
- server/static/static.go
- static/index.html
This makes it so that `style.css` is cached in dev/prod, and also so that `style.css` caching is fixed during local development, so that we no longer need "Disable cache" ticked in devtools.
This should speed up initial page load time significantly, since there's a ~100ms gap where we aren't doing anything due to `style.css` being loaded:
* Include styles in app bundle hash
* Append hash param to `style.css`
---
> Make style.css cacheable

- proto/BUILD
- proto/buildbuddy_service.proto
- proto/cache.proto
- proto/pagination.proto
- server/buildbuddy_server/BUILD
- server/buildbuddy_server/buildbuddy_server.go
- server/role_filter/role_filter.go
Expanding the cache scorecard result message with more details, and adding a new field `result` which will contain a flat results list. This flattened list is easiest for the client to slice and dice.
Might need to iterate on this in subsequent PRs if we see that this approach doesn't scale well, but this flat list works well for development purposes. The plan is to only populate the new fields behind a flag.
---
> Expand cache scorecard proto and add dedicated RPC for cache scorecard

- enterprise/server/remote_execution/containers/podman/podman.go
When we detect that podman failed with the storage corruption warning
and readlink no such file error, we will remove the image and set the
command result to unavailable error to trigger a retry.
> workround for podman readlink error

- enterprise/server/backends/redis_metrics_collector/BUILD
- enterprise/server/backends/redis_metrics_collector/redis_metrics_collector.go
- enterprise/server/backends/redis_metrics_collector/redis_metrics_collector_test.go
- server/backends/memory_metrics_collector/BUILD
- server/backends/memory_metrics_collector/memory_metrics_collector.go
- server/backends/memory_metrics_collector/memory_metrics_collector_test.go
- server/interfaces/interfaces.go
These will be used for the new cache scorecard. `GetAll` is used instead of individual `Get` operations for better performance in the Redis case.
---
> Add SetMembers, Set, and GetAll methods to MetricsCollector

- tools/smarter_device_manager/BUILD
rules_docker is using a base image that is out of date and has vulnerabilities, so we explicitly set the base image.
also adds container_push target to ease deployment of images.
---
> use base image explicitly for smarter-device-manager

- enterprise/server/test/integration/remote_execution/remote_execution_test.go
In the failing cases seen so far, it takes Bazel more than 10 seconds to
send any remote execution requests causing us to fail to find the remote
execution task information.
Fixes https://github.com/buildbuddy-io/buildbuddy-internal/issues/1324
---
> Bump timeout in TestRedisRestart test.

- app/components/link/link.tsx
- app/invocation/invocation_overview.tsx
- app/root/root.css
- enterprise/server/cmd/ci_runner/main.go
* Add PARENT_INVOCATION_ID and WORKFLOW_ID as build metadata to child invocations, so that we know the parent invocation ID as well as whether it's a workflow (vs hosted bazel)
* Show "Workflow <workflow_invocation_id>" in the breadcrumb (or "Bazel invocation <hostedbazel_invocation_id>" for hosted bazel)
Wraps more or less as expected:
---
> Link workflow invocation from inner invocations

- deps.bzl
- enterprise/tools/cpio/BUILD
- enterprise/tools/cpio/cpio.go
- enterprise/vmsupport/bin/BUILD
- enterprise/vmsupport/bin/mkinitrd.sh
- go.mod
- go.sum
This keeps initrd.cpio in sync with its transitive deps, and avoids adding 40MB to the repo history on each update.
---
> Add initrd.cpio to build using pure Go cpio lib

- enterprise/server/remote_execution/containers/sandbox/BUILD
- enterprise/server/remote_execution/containers/sandbox/sandbox.go
- enterprise/server/remote_execution/containers/sandbox/sandbox_test.go
- enterprise/server/remote_execution/platform/platform.go
- enterprise/server/remote_execution/runner/BUILD
- enterprise/server/remote_execution/runner/runner.go
- server/config/config.go
This CL adds macOS sandboxing support for remotely executed actions by generating a sandbox-config file per-action and then executing the action using sandbox-exec.
A generated sandbox config looks like this:
```
(version 1)
(debug deny)
(allow default)
(allow process-exec (with no-sandbox) (literal "/bin/ps"))
(deny file-read*
(subpath "/tmp/remote_build")
)
(allow file-read*
(subpath "/tmp/remote_build/9d054f1d-26bd-4ba0-a203-e2925869b279")
)
(deny file-write*)
(allow file-write*
(subpath "/Users/tylerw/Library/Caches")
(subpath "/Users/tylerw/Library/Developer")
(subpath "/Users/tylerw/Library/Logs")
(subpath "/dev")
(subpath "/private/tmp")
(subpath "/private/var/folders/2f/wy_q59s572b5fsv3tryx38d00000gn/C")
(subpath "/private/var/folders/2f/wy_q59s572b5fsv3tryx38d00000gn/T")
(subpath …
```
> Add basic support for macOS sandboxing.

- cli/autoconfig/autoconfig.go
- cli/cmd/bb/bb.go
- cli/commandline/commandline.go
- cli/remotebazel/BUILD
- cli/remotebazel/remotebazel.go
- enterprise/server/cmd/ci_runner/main.go
If the user executes `bazel run //target -- --foo=bar`, we need to pass
`--foo=bar` to the downloaded binar.
When parsing the command line args, we split them into regular &
passthrough slices (stored in `BazelArgs` struct). 
This also fixes a missing `defer` in the ci_runner (introduced in the
last PR).
---
> Pass through extra args to `bazel run` to the downloaded binary.

- rules/sha/index.bzl
I'm running into trouble upgrading rules_nodejs, so using `grep -v _metadata.json` to avoid including the generated metadata.json files in the SHA for now.
---
> Patch sha rule to not depend on config paths

- enterprise/server/cmd/ci_runner/main.go
This is to support replaying workflows against a particular env, without affecting the env in which the workflow was originally created.
---
> Add CI runner option to override bazel args

- enterprise/server/remote_execution/snaploader/snaploader.go
Make sure these errors are retryable. (We used to convert all runner errors to Unavailable errors, but now we respect the returned error codes, so this error is no longer retried.)
---
> Fix error code returned when snaploader artifacts expire

- enterprise/server/workflow/service/service.go
- server/config/config.go
Make the config separate for Linux vs Mac, so that we can bump the BCUs for Linux workflows without affecting Mac workflows.
Also bump the current default value from 2 -> 3 (3 CPU cores + 7.5GB RAM), to reduce the chance of hitting OOM errors.
---
> Make workflows compute units configurable

- enterprise/server/remote_execution/containers/podman/BUILD
- enterprise/server/remote_execution/containers/podman/podman.go
1. avoid parallel downlownding the same image
2. use server context for pull image to prevent the pull process gets
cancelled when the context get cancelled.
Workaround for https://github.com/buildbuddy-io/buildbuddy-internal/issues/1322
> Optimize podman pull

- .bazelrc
- buildbuddy.yaml
Building only with remote cache for now since I ran into toolchain issues with RBE. Also just building specific targets, since building `//...` also resulted in toolchain issues, even without RBE. I would like to revisit the RBE build at some point, but this should at least make sure we can build our binaries on Mac, to avoid blocking releases.
---
> Add Mac build to workflows

- cli/cmd/bb/BUILD
- cli/cmd/bb/bb.go
- cli/cmd/sidecar/BUILD
- cli/cmd/sidecar/sidecar.go
- proto/BUILD
- proto/sidecar.proto
We lean on the sidecar in remote bazel for caching artifacts but the
sidecar can terminate due to inactivity during a long remote bazel
build.
This PR avoids this by continuously pinging the sidecar while the CLI is
running.
---
> Keep sidecar alive while CLI is running.

- cli/commandline/commandline.go
- cli/remotebazel/BUILD
- cli/remotebazel/remotebazel.go
- enterprise/server/cmd/ci_runner/BUILD
- enterprise/server/cmd/ci_runner/main.go
- enterprise/server/remote_execution/dirtools/dirtools.go
- enterprise/server/remote_execution/dirtools/dirtools_test.go
- enterprise/server/remote_execution/workspace/workspace.go
- enterprise/server/test/integration/remote_execution/rbeclient/rbeclient.go
- enterprise/server/test/integration/remote_execution/rbetest/rbetest.go
- proto/build_event_stream.proto
- server/remote_cache/cachetools/BUILD
- server/remote_cache/cachetools/cachetools.go
runner: all symlinked runfile directories are uploaded and returned as
Tree objects via BES.
cli: download and plant all trees referenced in the BES event.
---
> remote bazel: handle runfile directory dependencies.

- enterprise/server/remote_execution/executor/executor.go
We pull images in `PrepareForTask`, which is called after recording the worker start timestamp and before the input fetch start timestamp. So this will let us accurately monitor how long actions are spending pulling images.
---
> Add pull_image to action stage durations histogram

- tools/metrics/grafana/dashboards/buildbuddy.json
Allows selecting quantiles (includes quartiles 0.25, 0.5, 0.75 as well as common long-tail values: 0.9, 0.95, 0.99, 0.999, 0.9999) for histogram charts, rather than always showing p50 or a range of preset quantiles.
Currently only applies to "Action stage durations", but we can add this to other charts as we see fit.
---
> Add quantile dropdown to grafana dashboard

- enterprise/server/remote_execution/runner/runner.go
- server/config/config.go
s/--docker_devices/--executor.docker_devices/
The old code had all the options unprefixed, this one instance must have been missed.
Also, added some hints about the right format. Took me an insane amount of time to figure out, so I hope it will help others.
---
-->
> Fixup option name broken on refactor

- enterprise/server/remote_execution/containers/podman/podman.go
h/t @bduffany 
Address error:
```
runtime error: invalid memory address or nil pointer dereference [signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x1129c17]
at go.opentelemetry.io/otel/sdk/trace.(*recordingSpan).End·dwrap·11 ( [external/io_opentelemetry_go_otel_sdk/trace/span.go:244](https://console.cloud.google.com/debug?referrer=fromlog&file=external%2Fio_opentelemetry_go_otel_sdk%2Ftrace%2Fspan.go&line=244&project=flame-build) )
at go.opentelemetry.io/otel/sdk/trace.(*recordingSpan).End ( [external/io_opentelemetry_go_otel_sdk/trace/span.go:283](https://console.cloud.google.com/debug?referrer=fromlog&file=external%2Fio_opentelemetry_go_otel_sdk%2Ftrace%2Fspan.go&line=283&project=flame-build) )
at github.com/buildbuddy-io/buildbuddy/enterprise/server/remote_execution/conta …
```
> Check err != nil before using

- server/target/target.go
When we have a problem parsing commit_shas and there are tons of
invocations with empty commit_shas. The test grid performance will
degrade since the limit clause on the commit inner-query doesn't really
prune the number of invocations down.
> Remove empty commit_shas from test grid query

- release.py
Group all the `update_latest_tag` builds together, since those all have the same `--define` flags. (Changing `--define` flags invalidates the Bazel analysis cache, causing the builds to be much slower)
---
> Speed up image building in release.py

- enterprise/server/cmd/ci_runner/main.go
- enterprise/server/test/integration/build_logs/build_logs_test.go
- server/build_event_protocol/build_event_handler/build_event_handler.go
- server/build_event_protocol/build_event_handler/build_event_handler_test.go
> For command types that don't populate OptionsDescription on the Started event (query, fetch), use OptionsParsed instead

- cli/cmd/sidecar/sidecar.go
- enterprise/server/auth/auth.go
- enterprise/server/cmd/executor/executor.go
- enterprise/server/cmd/server/main.go
- server/cmd/buildbuddy/main.go
- server/config/BUILD
- server/config/config.go
- server/environment/BUILD
- server/environment/environment.go
- server/libmain/BUILD
- server/libmain/libmain.go
- server/real_environment/BUILD
- server/real_environment/real_environment.go
- server/testutil/testenv/testenv.go
- server/util/url/url_test.go
- tools/vmstart/BUILD
- tools/vmstart/vmstart.go
Removes the configurator entirely, as it is no longer a relevant structure. `flags.Parse`
can now be called safely directly from a main function without "registering" flags first.
We now only need to populate the flags from a given YAML config, as opposed to reconciling,
and the new flagutils way of populating the flags means that we don't need to externally
keep track of which flags were set initially via the command line.
---
> Switch over fully to flag-based configuration

- app/invocation/invocation_cache_card.tsx
- proto/cache.proto
- server/build_event_protocol/build_event_handler/build_event_handler.go
- server/remote_cache/hit_tracker/hit_tracker.go
- server/remote_cache/hit_tracker/hit_tracker_test.go
- server/tables/tables.go
Rename "compressed size" to "transferred size" and include IDENTITY requests in the total transferred size (e.g. AC requests) so that the total bytes transferred shown in the UI is more accurate. For example, if we have 1 AC request uncompressed @ 100KB and 1 CAS request @ 10KB compressed, 30KB uncompressed, we want to show it in the UI as 130KB downloaded (110KB w/ compression). But before this PR we'd show 130KB downloaded (10KB w/ compression) which is inaccurate and makes the compression ratio seem higher than it is.
---
> Store transferred size in invocation table instead of only compressed sizes

- app/invocation/cache_requests_card.tsx
- app/invocation/invocation.css
* Show compressed size when not filtering to AC (AC requests results are always uncompressed so it's useless when filtering to AC)
* Hide waterfall chart when screen is too small
* Allocate more of the table width to the "name" column (target and/or action mnemonic)
---
> Show more data in the scorecard

- enterprise/server/remote_execution/execution_server/execution_server.go
- enterprise/server/scheduling/priority_task_scheduler/BUILD
- enterprise/server/scheduling/priority_task_scheduler/priority_task_scheduler.go
- proto/remote_execution.proto
Forward the complete request metadata proto with requests from executor -> cache, not just the invocation ID metadata.
This fixes an issue that the scorecard is missing the target ID, action ID, and action mnemonic for RBE requests.
---
> Add full request metadata to executor cache requests

- dockerfiles/executor_image/Dockerfile
The repo updated podman and skopeo very often. This might cause podman
to be upgraded in the production without enough testing.
> Pin podman and Skopeo versions in Dockerfile

- app/invocation/invocation.tsx
- app/invocation/invocation_suggestion_card.tsx
- app/invocation/invocation_tabs.tsx
- app/root/root.css
- app/router/router.tsx
* Add a suggestions tab if there is at least one suggestion
* In the overview page, link to "See {n} more suggestions" and also hide the suggestion reason to make it a bit more compact. The suggestion reason is now only visible in the suggestions tab.
* Support INFO-level suggestions instead of just errors.
* Remove red background and use a red icon instead, to make the styling more consistent for INFO-level suggestions.
---
Overview:
---
Suggestions tab:
---
> Add suggestions tab with support for multiple suggestions

- tools/edit_instance_template/edit_instance_template.go
This was basically a clean rewrite of this script attempting to make it a bit safer and more intuitive to use. It's probably easier to review as that rather than in diff mode.
It is safe to run multiple times -- it will do nothing once modifications have been made.
It supports a dry run mode so you can see what changes will be made.
It uses a smarter template naming approach to better support changes in the future.
It modifies all instance groups in the region, not just one at a time.
TODO: I might still want to delete the old instance templates, I only delete the old groups now. WDYT?
> Better / safer edit instance template script.

- enterprise/server/remote_execution/containers/docker/docker.go
By default, docker returns a container's ID when calling `hostname`.
---
> Use default docker hostname behavior

- app/BUILD.bazel
- enterprise/app/BUILD.bazel
Reverts buildbuddy-io/buildbuddy#2003
It's breaking static file uploads to GCS.
> Revert "Re-enable code splitting"

- enterprise/server/remote_execution/execution_server/execution_server.go
Executions can complete quickly before the ScheduleTask() call returns
causing us to not properly clean up the pending execution metadata.
---
> Record pending execution before scheduling.

- enterprise/server/backends/redis_metrics_collector/redis_metrics_collector.go
- enterprise/server/util/redisutil/redisutil.go
- enterprise/server/util/redisutil/redisutil_test.go
- server/backends/memory_metrics_collector/memory_metrics_collector.go
- server/backends/memory_metrics_collector/memory_metrics_collector_test.go
- server/interfaces/interfaces.go
- server/remote_cache/hit_tracker/BUILD
- server/remote_cache/hit_tracker/hit_tracker.go
:point_right: depends on https://github.com/buildbuddy-io/buildbuddy/pull/2027
* Switch to using a list to store results, to simplify retrieval and cleanup
* Delete the list in `CleanupCacheStats`
* Set a 3h expiration for the list in case we fail to clean up for whatever reason. The expiration is reset on each list push, so as long as an invocation makes cache requests at least once every few hours, we should still be able to handle long running invocations.
---
> Clean up detailed stats after reading

- cli/autoconfig/autoconfig.go
- server/util/networking/networking.go
1. Rename findDevice to findRoute. In addition to device name, also return
the gateway, which will be used when set up ip rules and routing for
second network.
2. Move DefaultIP function to networking.go; and re-use the code to find
the ip for a device.
> Find IP for a device and gateway of a route

- app/invocation/invocation_suggestion_card.tsx
- app/root/root.css
- ~~Suggest using `--incompatible_strict_action_env` if not set~~ -- removed this one, since Brentley pointed out it's not desirable for iOS builds, and there may be other cases I'm not aware of.
- Suggest adding `COMMIT_SHA` and `REPO_URL` metadata if this is a CI test and those pieces of metadata are missing
- Polish up a few other suggestions (add flag links, make wording more consistent)
---
**Related issues**: https://github.com/buildbuddy-io/buildbuddy-internal/issues/1357
> Add more invocation suggestions (round 2)

- .bazelrc
This will give us some experience using these flags, since we are recommending them with the suggestions cards.
- Enable `--experimental_remote_cache_compression` when running with `--config=remote` or `--config=cache` (does not apply to workflows since it's likely to be detrimental, and not to github CI either since it's unclear whether the network is a bottleneck there)
- Enable `--experimental_remote_cache_async` and `--incompatible_remote_build_event_upload_respect_no_cache` unconditionally
---
> Update bazelrc with some bazel 5.0 cache flags

- enterprise/server/cmd/ci_runner/main.go
This should make the test grid "just work" when using BB workflows or the bb CLI.
---
> Set git repo metadata in CI runner bazelrc

- app/invocation/cache_requests_card.tsx
- proto/cache.proto
- server/build_event_protocol/build_event_handler/build_event_handler.go
- server/remote_cache/scorecard/BUILD
- server/remote_cache/scorecard/scorecard.go
Instead of showing "bes-upload" for all of these names, show the actual file name by cross-referencing File metadata that we have readily available in the BEP.
Computing these on the server side rather than client side, and storing them in the scorecard proto so that they are searchable.
The server side implementation extracts file metadata from the buffered BES events that we already have in memory during FinalizeInvocation. The downside is that this metadata sits in memory for 500ms for each invocation while we wait for stats buffers across apps to be flushed. This will slightly increase memory usage, but to a very small degree. Also, the alternatives seemed a bit overkill (either storing this metadata in Redis or re-reading the full invocation in the stats recorder just to get file …
> Show file names for BES uploads in cache scorecard

- server/tables/tables.go
Delete unique index target_id on Targets. This allows one target to show
up on multiple orgs' test grid.
> add unique index (target_id, group_id) on Targets

- enterprise/server/backends/distributed/distributed.go
- enterprise/server/backends/distributed/distributed_test.go
- enterprise/server/backends/gcs_cache/gcs_cache.go
- enterprise/server/backends/memcache/memcache.go
- enterprise/server/backends/redis_cache/redis_cache.go
- enterprise/server/backends/s3_cache/s3_cache.go
- enterprise/server/composable_cache/composable_cache.go
- enterprise/server/raft/cache/cache.go
- enterprise/server/raft/store/store.go
- enterprise/server/util/cacheproxy/cacheproxy.go
- enterprise/server/util/cacheproxy/cacheproxy_test.go
- proto/distributed_cache.proto
- proto/raft.proto
- server/backends/disk_cache/disk_cache.go
- server/backends/disk_cache/disk_cache_test.go
- server/backends/memory_cache/BUILD
- server/backends/memory_cache/memory_cache.go
- server/backends/memory_cache/memory_cache_test.go
- server/interfaces/interfaces.go
- server/remote_cache/byte_stream_server/byte_stream_server.go
Used to serve container layer ranges.
---
> Support partial reads in ByteStream API.

- server/util/networking/networking.go
vmIdx is mapped the following ip range:
* `192.168.{vmIdx/30}.{(vmIdx%30) * 8) + 5}/30` on the host
* `192.168.{vmIdx/30}.{(vmIdx%30) * 8) + 6}/30` in the namespace
* `192.168.{vmIdx/30}.{(vmIdx%30) * 8) + 3}` as the host IP
We are not going to assign ip's in range `192.168.241.0/29` (tap addresses/vm addresses)
Fixes https://github.com/buildbuddy-io/buildbuddy-internal/issues/1379
> Use a different range for firecracker host interfaces

- enterprise/server/scheduling/priority_task_scheduler/priority_task_scheduler.go
- server/resources/resources.go
Reverts buildbuddy-io/buildbuddy#2030
Going to modify this to not be based on load avg.
> Revert "Add a simple cpu cutoff"

- enterprise/server/remote_execution/runner/runner.go
- enterprise/server/remote_execution/runner/runner_test.go
Adding even more locking to the runner pool (to protect `r.state`, `r.PlatformProperties`, and `r.task`) ... we can remove the need for locking once we have a proper fix for https://github.com/buildbuddy-io/buildbuddy-internal/issues/1159 (e.g., canceling the context on shutdown, instead of doing a concurrent call to `r.Remove()` while the task is executing)
I chose to lock around the runner pool's lock, rather than introducing per-runner locks, for (a) simplicity, and (b) to avoid introducing the possibility of deadlocks (i.e., having to worry about acquiring `p.mu` and `r.mu` in a consistent order)
---
> Fix data races in runner_test

- server/util/healthcheck/healthcheck.go
The checker still picks up a race even though we have a lock around the map, because we are still using an unprotected ref to the map: https://app.buildbuddy.io/invocation/8ccdc88f-f820-43fc-9d79-7fd06985f202?target=%2F%2Fenterprise%2Fserver%2Fusage%3Ausage_test_mysql
Fixed by making a copy of the map.
---
> Fix data race in healthchecker

- enterprise/server/remote_execution/runner/BUILD
- enterprise/server/remote_execution/runner/runner.go
During the protobuf migration we switched from `buffer.EncodeMessage` to just `proto.Marshal`, which inadvertently dropped length-delimiting. This PR adds back the length delimiter, by mimicking the old implementation of `EncodeMessage` as closely as possible.
Tests to follow.
---
> Remote persistent workers: Fix work request encoding

- enterprise/server/remote_execution/runner/BUILD
- enterprise/server/remote_execution/runner/runner_test.go
- enterprise/server/remote_execution/runner/testworker/BUILD
- enterprise/server/remote_execution/runner/testworker/testworker.go
Beef up the existing tests by using a worker binary which actively decodes incoming requests according to the persistent worker protocol.
---
> Test persistent worker proto encoding

- enterprise/server/test/integration/workflow/workflow_test.go
- enterprise/server/workflow/service/service_test.go
- server/endpoint_urls/build_buddy_url/BUILD
- server/endpoint_urls/build_buddy_url/build_buddy_url.go
- server/endpoint_urls/cache_api_url/BUILD
- server/endpoint_urls/cache_api_url/cache_api_url.go
- server/endpoint_urls/events_api_url/BUILD
- server/endpoint_urls/events_api_url/events_api_url.go
- server/endpoint_urls/remote_exec_api_url/BUILD
- server/endpoint_urls/remote_exec_api_url/remote_exec_api_url.go
- server/testutil/testhttp/testhttp.go
- server/util/flagutil/flagutil.go
- server/util/flagutil/flagutil_test.go
- server/util/url/BUILD
- server/util/url/url_test.go
The motivation for this is mainly to stop having to re-parse a URL over and over again, as well
as to remove the associated error handling code, which was needlessly complicating.
---
> Change URLFlag so that its underlying type is URL, not string

- enterprise/server/cmd/executor/yaml_doc/BUILD
- enterprise/server/cmd/executor/yaml_doc/main.go
- enterprise/server/cmd/server/yaml_doc/BUILD
- enterprise/server/cmd/server/yaml_doc/main.go
- server/cmd/buildbuddy/BUILD
- server/cmd/buildbuddy/yaml_doc/BUILD
- server/cmd/buildbuddy/yaml_doc/main.go
- server/util/flagutil/flagutil.go
- server/util/flagutil/flagutil_test.go
Add functionality to `flagutil` that allows us to auto-generate documented YAML files
from the flag definitions.
- Refactor the way we generate types from flags to allow for code reuse in generating YAML from flags
* Generate map structure for YAML from flag names
* Use a function that has been passed in as a parameter to generate value to be stored in the YAML map for a given flag, don't store anything if nil
* Use filter functions that have been passed in to determine if a given flag should be ignored when generating YAML
* Recursively remove all empty maps from the YAML
- Add ability to generate documented YAML node from flag definition
- Separate "structured" and "unstructured" settings for readability purposes
- Update tests to reflect changes to yaml type map generation
- Add …
> Auto-generate YAML docs

- app/invocation/invocation_details_card.tsx
Currently these render without spaces, i.e.
```
bazel build targetonetargettwotargetthree --config=local
```
With this change we join the pattern components with spaces, i.e.
```
bazel build targetone targettwo targetthree --config=local
```
---
> Fix explicit/effective command lines with multiple pattern components

- server/remote_cache/byte_stream_server/byte_stream_server_test.go
- server/remote_cache/content_addressable_storage_server/content_addressable_storage_server_test.go
- server/remote_cache/hit_tracker/hit_tracker.go
These are most likely from older executors that aren't setting executor host ID.
---
> Fix empty rows in cache requests card

- enterprise/server/remote_execution/runner/BUILD
- enterprise/server/remote_execution/runner/runner.go
- enterprise/server/remote_execution/runner/runner_test.go
:point_right: Highly recommend disabling whitespace diff when reviewing: https://github.com/buildbuddy-io/buildbuddy/pull/2088/files?diff=split&w=1
The worker was getting killed after the first task it executed, due to the task context being canceled. The fix is to use the server context for the persistent worker instead of the task context.
Also fixed that the worker could stick around forever, since we were only ever canceling the worker context in the first task execution.
---
> Fix persistent worker lifecycle

- enterprise/server/cmd/smash/smash.go
- server/backends/disk_cache/disk_cache.go
This permits substantially more QPS on the FindMissing endpoint by reducing contention.
In my local testing this increased /FindMissingBlobs QPS (where each batch contained 100 digests) from ~3K to ~12K.
> A little locking goes a long way: prefer Rlock for contains checks.

- enterprise/server/cmd/smash/smash.go
- server/backends/disk_cache/disk_cache.go
Reverts buildbuddy-io/buildbuddy#2103
fixing. a. race. condition.
> Revert "A little locking goes a long way: prefer Rlock for contains checks."

- server/backends/disk_cache/disk_cache.go
Reverts buildbuddy-io/buildbuddy#2105
Unfortunately this still triggers a data race.
==================
WARNING: DATA RACE
Read at 0x00c0014ce0f8 by goroutine 183:
container/list.(*List).move()
GOROOT/src/container/list/list.go:122 +0x1b8
container/list.(*List).MoveToFront()
GOROOT/src/container/list/list.go:185 +0x175
github.com/buildbuddy-io/buildbuddy/server/util/lru.(*LRU).Contains()
server/util/lru/lru.go:170 +0x10f
github.com/buildbuddy-io/buildbuddy/server/backends/disk_cache.(*partition).contains()
server/backends/disk_cache/disk_cache.go:723 +0x17a
github.com/buildbuddy-io/buildbuddy/server/backends/disk_cache.(*partition).findMissing.func1.1()
server/backends/disk_cache/disk_cache.go:771 +0xbe
golang.org/x/sync/errgroup.(*Group).Go.func1() …
> Revert "RLock"

- .github/workflows/checkstyle.yaml
It warns that `--global` is deprecated in favor of `--location=global`, causing checkstyle to fail.
---
> Fix NPM warnings in checkstyle

- .github/workflows/checkstyle.yaml
This might fix the recent NPM woes (complaining about libpng-dev not being installed) and is also consistent with our local development workflow (using yarn to manage NPM deps).
---
> Switch prettier checkstyle from npm to yarn

- enterprise/server/remote_execution/commandutil/BUILD
- enterprise/server/remote_execution/commandutil/commandutil.go
- enterprise/server/remote_execution/commandutil/commandutil_test.go
- enterprise/server/remote_execution/container/container.go
- enterprise/server/remote_execution/container/container_test.go
- enterprise/server/remote_execution/containers/bare/bare.go
- enterprise/server/remote_execution/containers/docker/docker.go
- enterprise/server/remote_execution/containers/docker/docker_test.go
- enterprise/server/remote_execution/containers/firecracker/firecracker.go
- enterprise/server/remote_execution/containers/firecracker/firecracker_darwin.go
- enterprise/server/remote_execution/containers/podman/podman.go
- enterprise/server/remote_execution/containers/podman/podman_test.go
- enterprise/server/remote_execution/containers/sandbox/sandbox.go
- enterprise/server/remote_execution/runner/runner.go
This will let us read stderr from the persistent worker process and expose errors from the worker in command error messages, rather than the vague error `io: read/write on closed pipe`.
---
> Allow passing an stderr reader to container.Exec

- enterprise/server/cmd/ci_runner/main.go
- enterprise/server/test/integration/ci_runner/BUILD
- enterprise/server/test/integration/ci_runner/ci_runner_test.go
Properly handle the argument separator ("--") in `bazel run` commands.
---
> Workflows: Fix argument handling for `bazel run` commands

- deps.bzl
- go.mod
- go.sum
According https://github.com/prometheus/client_golang/pull/955, the
newer version uses a more efficient API to get data from the go runtime.
---
> Bump github.com/prometheus/client_golang to latest version.

- enterprise/server/backends/pebble_cache/pebble_cache_test.go
- enterprise/server/raft/constants/constants.go
This segments AC files by remote_instance_name when it is set. The original remote_instance_name value is preserved in the file metadata (in pebble) but the file is stored under a subpath made from a hash of the remote_instance_name.
> Ensure remote_instance_name is respected in action cache

- enterprise/server/remote_execution/container/container.go
- enterprise/server/remote_execution/containers/podman/BUILD
- enterprise/server/remote_execution/containers/podman/podman.go
- enterprise/server/remote_execution/containers/podman/podman_test.go
- server/interfaces/interfaces.go
Adds an option `EnableStats` to the podman API that periodically collects CPU usage (nanos) and mem usage (bytes) while the container is running, and reports these in the `CommandResult` (both for `Run` and `Exec`). It also allows the `Stats()` func to work properly, which is used for runner pool resource management.
The implementation is based on polling the cgroupfs. Locally, each cgroupfs read takes ~10 microseconds, so we should be able to sample these stats at a fairly high rate.
Alternatives considered:
* Using the `getrusage` system call - I found this to be unreliable. In particular, `maxrss` only reports the max resident set size amongst all child processes individually, as in `max(child1_maxrss, ..., childN_maxrss)` and doesn't represent the max total memory usage across all …
> Task sizing: Add an option to enable cgroup-based podman stats

- server/backends/chunkstore/chunkstore.go
- server/backends/chunkstore/chunkstore_test.go
The actual bug was that the volatile tail would get wiped out by last chunk id
checks sometimes, but while debugging I also noticed we were calling the
writeHook way more often than we should be, so I also fixed that.
---
> Fix for lag in build logs

- enterprise/server/testutil/testredis/testredis.go
- server/util/dsingleflight/BUILD
- server/util/dsingleflight/dsingleflight.go
- server/util/dsingleflight/dsingleflight_test.go
Every client for a given work key will try to obtain a lock in Redis.
The first client to get the lock will perform the work and publish the
result to a stream. If the owner does not refresh the lock within 5
seconds, another worker will have a chance to claim the lock and do the
work.
---
> Utility to dedupe expensive work across servers.

- enterprise/server/registry/BUILD
- enterprise/server/registry/registry.go
This will allow us to run multiple replicas of the registry.
---
> Dedupe image conversions across registry instances.

- enterprise/server/cmd/server/BUILD
- enterprise/server/cmd/server/main.go
- enterprise/server/remote_execution/execution_server/BUILD
- enterprise/server/remote_execution/execution_server/execution_server.go
- enterprise/server/tasksize/BUILD
- enterprise/server/tasksize/tasksize.go
- enterprise/server/test/integration/remote_execution/rbetest/rbetest.go
- server/environment/environment.go
- server/interfaces/interfaces.go
- server/real_environment/real_environment.go
This will let us fail at server startup (in `Register()`) if no Redis client is configured in the env. It also generally makes sense to make an interface that has the same look and feel as TaskRouter, since the usage of those two things is very similar (they both will use Redis, and they both will be called after each task execution in MarkComplete).
* Add task sizer interface definition
* Add env plumbing
* Use the new `Estimate()` method in `ExecutionServer` (just passes through to the existing impl)
---
> Task sizing: Define sizer interface

- app/root/root.css
* Add 3 more log lines worth of height (60px)
* Trim bottom padding from 32px -> 16px. The top padding is still at 32px so this introduces an asymmetry, but it's not really noticeable in practice because we add a blank line to the end of the logs. Tested in dense mode; no change because the bottom padding for dense mode is already 16px.
Before/after:
---
**Related issues**: https://github.com/buildbuddy-io/buildbuddy-internal/issues/1452
> Slightly increase build log height

- enterprise/server/backends/s3_cache/s3_cache.go
This fixes an issue where (when using an s3 backing cache) we get a SHA mismatch if the context is cancelled during a large download.
---
> Fix s3 range reads

- server/tables/tables.go
QuotaBucket is to define the sustained rate and max burst.
QuotaGroup is to define the relationship between group ID / IP and the
QuotaBucket.
Note:
To save the space, for each namespace, we will define a default bucket. If a group id / ip is not in the QuotaGroup table, then quota manager will apply the default bucket.
> add schema for quota configs

- server/libmain/libmain.go
Add an --exit_when_ready flag that can be used to kill the app after running migrations.
This will allow us to run other migrations as well as the DB ones (like, for instance, a disk cache migration). Currently setting --auto_migrate_db_and_exit causes the app to die before a disk migration would ever run.
> Add exit when ready flag

- enterprise/server/backends/pebble_cache/pebble_cache.go
- enterprise/server/raft/filestore/filestore.go
Look at the stored metadata when deleting files rather than blindly constructing their filepaths assuming they are stored in the blobs dir. This allows deleting migrated files.
Also log when files are evicted in order to better debug missing files.
> Allow evicting migrated files too.

- server/buildbuddy_server/buildbuddy_server.go
- server/interfaces/BUILD
- server/interfaces/interfaces.go
- server/quota/BUILD
- server/quota/quota_manager.go
- server/quota/quota_manager_test.go
Note: this PR doesn't include pubsub change. i.e. when the db changes,
quota manager doesn't fetch the updated change from db. This will be
implemented in the following PR.
> Implement Quota APIs to change quota

- server/util/consistent_hash/consistent_hash.go
- server/util/consistent_hash/consistent_hash_test.go
- Measure allocs
- Reduce cpu usage by doing less duplicate work
Before:
tylerw@lunchbox:~/buildbuddy$ blaze run server/util/consistent_hash:consistent_hash_test -- -test.bench=.
-----------------------------------------------------------------------------
goos: linux
goarch: amd64
cpu: AMD Ryzen 9 5950X 16-Core Processor
BenchmarkGetAllReplicas-32    	  143203	      8215 ns/op	    1249 B/op	       2 allocs/op
PASS
After:
tylerw@lunchbox:~/buildbuddy$ blaze run server/util/consistent_hash:consistent_hash_test -- -test.bench=.
-----------------------------------------------------------------------------
goos: linux
goarch: amd64
cpu: AMD Ryzen 9 5950X 16-Core Processor
BenchmarkGetAllReplicas-32    	  452287	      2711 ns/op	     224 B/op	       2 allocs/op
PASS …
> old friend

- enterprise/server/tasksize/tasksize.go
- enterprise/server/tasksize/tasksize_test.go
* Don't use measured task sizes for Firecracker tasks (yet)
* Don't use a 1.10x multiplier for mem estimates, since the mem size estimate is just a soft limit and we have some wiggle room anyway (20% of the executor's memory is reserved in case we go over)
---
> Task sizing: Support only soft task size limits for now

- enterprise/server/remote_execution/containers/podman/podman.go
This appears to avoid the failures seen in TF builds, though it's hard
to say with 100% certainty.
We can try turning image streaming again in dev after tomorrow's
release.
---
> Disable stargzstore background fetching.

- enterprise/server/backends/pebble_cache/pebble_cache.go
I went for something simple to start with.
The difference, when running locally:
```
2022/06/30 15:41:08.627 INF Pebble Cache: Initialized cache partition "default" AC: 15331, CAS: 1732768, Size: 7012901198 [bytes] in 424.877198ms
2022/06/30 15:41:29.414 INF Pebble Cache: Initialized cache partition "default" AC: 15508, CAS: 1732784, Size: 7013263634 [bytes] in 2.488654371s
```
> Scan inter + intra partition in parallel

- enterprise/server/auth/auth.go
Before https://github.com/buildbuddy-io/buildbuddy/pull/2165, we would set `SkipExpiryCheck = true` in the preceding call to `verifyTokenAndExtractUser(ctx, jwt, false /*=checkExpiry*/)`, which mutated the `oidcConfig`, and `checkAccessToken` was implicitly relying on that mutation. Now, we explicitly set `SkipExpiryCheck`, again making a copy to avoid data races across requests.
---
**Related issues**: Fixes https://github.com/buildbuddy-io/buildbuddy-internal/issues/1489
> Skip expiry check in checkAccessToken

- enterprise/server/remote_execution/workspace/workspace.go
- enterprise/server/remote_execution/workspace/workspace_test.go
If we fail to delete a workspace directory, fall back to force-removal (golang equivalent of `chmod -R +w workspace && rm -rf workspace`.
---
> Executor: Force-remove workspace directories

- enterprise/server/backends/pebble_cache/pebble_cache.go
- server/metrics/metrics.go
- Include metadata in cache size; faster startup; better statusz
- Store a histogram of time since last access
> Add a histogram metric with time-since-last-access

- enterprise/server/cmd/executor/BUILD
- enterprise/server/cmd/executor/executor.go
- enterprise/server/remote_execution/container/container.go
- enterprise/server/remote_execution/containers/podman/podman.go
- enterprise/server/tasksize/BUILD
- enterprise/server/tasksize/tasksize.go
- server/metrics/metrics.go
- tools/metrics/grafana/dashboards/buildbuddy.json
- Add a "1s CPU" gauge (gives a more "realtime" metric than what we can get from the counter metric -- our scrape interval is 1m so we can only get a 1m average using the counter)
- Add a "peak mem" metric (should track the estimated memory metric more closely)
- Add task sizer read/write metrics
- Add charts for CPU + task sizer reads/writes, + add peak mem to existing memory usage chart
These metrics uncovered a surprising amount of read errors -- based on logs it seems like we're failing to deserialize some of the protos stored in Redis. Need to dig in and figure out what's going on here.
---
> Task sizing: Improve metrics

- enterprise/server/backends/pebble_cache/pebble_cache.go
- enterprise/server/backends/pebble_cache/pebble_cache_test.go
Previously we were skipping some records when scanning the AC ranges on startup.
> Fix startup scan

- enterprise/server/remote_execution/commandutil/commandutil.go
- enterprise/server/remote_execution/commandutil/commandutil_test.go
- enterprise/server/remote_execution/container/container.go
- enterprise/server/remote_execution/container/container_test.go
- enterprise/server/remote_execution/containers/bare/bare.go
- enterprise/server/remote_execution/containers/docker/docker.go
- enterprise/server/remote_execution/containers/docker/docker_test.go
- enterprise/server/remote_execution/containers/firecracker/firecracker.go
- enterprise/server/remote_execution/containers/firecracker/firecracker_darwin.go
- enterprise/server/remote_execution/containers/podman/podman.go
- enterprise/server/remote_execution/containers/podman/podman_test.go
- enterprise/server/remote_execution/containers/sandbox/sandbox.go
- enterprise/server/remote_execution/runner/runner.go
The original intent was just to hold 3 input/output streams, and this rename makes the intent more clear and will prevent more options creeping into this struct.
---
> Rename ExecOpts to Stdio

- enterprise/server/backends/pebble_cache/pebble_cache.go
- server/util/flagutil/types/types.go
- server/util/flagutil/types/types_test.go
Now if someone wants to use the Alias function to access a flag in a place that it isn't defined, they are no longer forced to declare a new alias for the flag.
---
> Allow Alias to do a no-op to the flags

- enterprise/server/quota/quota_manager.go
Don't return error when the default bucket is not defined in the namespace. In
this case, quota manager will always allow the traffic.
Also, check that the bucket name is not empty in the request.
> Allow nil default bucket in the namespace

- server/build_event_protocol/build_event_handler/build_event_handler.go
- server/remote_cache/scorecard/scorecard.go
Fixes buildbuddy-io/buildbuddy-internal#1287
> Write cache scorecard under attempt-specific directory

- server/metrics/metrics.go
- server/rpc/filters/BUILD
- server/rpc/filters/filters.go
This allows us to figure out a sensible default quota.
Add rpc intercepters to record the metrics.
> Define metrics for GRPC by group id.

- enterprise/server/scheduling/scheduler_server/scheduler_server.go
`GetNodes()` returns a reference to `np.connectedExecutors` which is then read in `enqueueTaskReservations` (e.g. `toNodeInterfaces(nodes)`. `RemoveConnectedExecutor()` can concurrently mutate that slice though in order to remove an executor. The fix is to remove executors by creating a new slice, rather than mutating its contents.
---
> Fix data race in RemoveConnectedExecutor

- server/metrics/metrics.go
- server/rpc/filters/filters.go
In the rpc interceptor, when quota manager is set, call Allow method.
Currently, quota is not forced; but the metrics will be recorded.
> Use quota manager in rpc interceptor

- enterprise/server/vmexec/vmexec.go
- proto/BUILD
- proto/vmexec.proto
This will be useful for:
- Stats (immediate use case): allows us to stream stats and live-update prometheus metrics while the task is running.
- Stdio: allows us to stream stdin and stdout/stderr, so we no longer have to worry about grpc max size restricting the amount of stdout/stderr we can receive.
- Persistent workers: firecracker-based persistent workers require stdin streaming, since we need to stream tasks one-by-one as each task comes in.
---
> Add protos for stream-based Firecracker execution

- app/invocation/invocation_model.tsx
- enterprise/app/api_keys/api_keys.css
- enterprise/app/api_keys/api_keys.tsx
- enterprise/server/auth/auth.go
- enterprise/server/test/integration/remote_cache/remote_cache_test.go
- proto/api_key.proto
- server/remote_cache/byte_stream_server/byte_stream_server.go
- server/remote_cache/content_addressable_storage_server/content_addressable_storage_server.go
- server/testutil/testauth/testauth.go
This API key type allows users of this key to upload to the CAS, but not the Action Cache.
This allows users to use an API key that restricts them from poisoning / tampering with the remote cache via the Action Cache, but allows them to still upload timing profiles and test logs. CAS uploading is less prone to issues because we validate the SHAs of the content on upload, and artifacts are stored keyed on their SHA.
This also pairs nicely with remote execution, where users can upload inputs to the CAS (where again their SHAs are validated) - but only the trusted remote executors can populate the AC. 
---
> Add support for CAS-only API keys

- enterprise/server/tasksize/tasksize.go
- server/metrics/metrics.go
This will let us split the sizer charts by isolation type, so we can see how many of the hits/misses are coming from Mac vs Linux executors.
---
> Task sizing: Add isolation type label to sizer metrics

- enterprise/server/registry/registry.go
Authenticator is always being passed as nil to checkAccess.
---
> Fix authenticator shadowing.

- tools/metrics/grafana/dashboards/buildbuddy.json
Add new graphs for duplicate writes, file size added, and seconds since last access for remote cache disk cache. Used heat maps for the bucketed data.
---
> Add new disk cache graphs for remote cache to grafana

- server/rpc/filters/filters.go
Rename record metrics interceptor to quota b/c we are also checking
quota in that interceptor.
Put the quota interceptor after the auth one.
> Fix get group id for quota interceptor

- package.json
- yarn.lock
Update the bazelisk version in node_modules to one that supports M1 Macs.
---
> Update NPM bazelisk to v1.12.0

- server/remote_cache/byte_stream_server/byte_stream_server.go
> Move QueryWriteStatus short-circuiting before the cache lookup

- enterprise/server/backends/pebble_cache/BUILD
- enterprise/server/backends/pebble_cache/pebble_cache.go
- enterprise/server/backends/pebble_cache/pebble_cache_test.go
Add code to pebble_cache which will scan and delete files from the blobDir which do not have corresponding records in the pebble DB. This is to remove corrupted data which is effectively invisible and taking up space on the partition but not being used.
> Scan and delete

- enterprise/server/backends/pebble_cache/pebble_cache.go
- enterprise/server/backends/pebble_cache/pebble_cache_test.go
Based on logs, it seems we're orphaning files when the apps restart. I disabled the orphan deletion already, but this disables the scan as well because it hammers the disk and the logs for no real reason.
> Disable orphan file scan by default

- enterprise/server/scheduling/scheduler_server/scheduler_server.go
Tested by running two executors locally, where the first one had the default resource limits and the second had `--executor.millicpu=50` (so small that it can't fit any task). Before this change, the second executor would get tasks enqueued, but never be able to dequeue. After the change, only the first executor (with the default resource limits) would get the task enqueued.
---
**Related issues**: Fixes https://github.com/buildbuddy-io/buildbuddy-internal/issues/1467
> Send probes only to nodes that can fit a task

- proto/scheduler.proto
This PR is just adding new fields / comments as a proposal for addressing a scheduling issue with task sizing.
With the current task sizing implementation, there's an issue in which, after an executor has executed a task, the task may no longer be schedulable on that executor due to the measured task size exceeding the executor's resource limits. This is not an intended outcome at least with this first iteration of task sizing, since it breaks a lot of tasks that currently schedule and execute just fine.
The proposed fix is to never use measured task sizes for scheduler -> executor probing, and instead always use the "original" task size estimate (either the one from platform props, or the one based on our heuristics). Then, on the executor, we can use the measured_task_size, but capped …
> Update task sizing semantics in scheduling API

- app/target/target_test_log_card.tsx
* Use nanos portion of timestamp for higher accuracy
* Show the execution strategy in the title so that users can distinguish between locally and remotely executed tests
Before:
After:
---
**Related issues**: Fixes https://github.com/buildbuddy-io/buildbuddy-internal/issues/1535
> Improve test title rendering

- enterprise/server/remote_execution/execution_server/execution_server.go
- Fix inaccurate "could not update task router" logging since the error wasn't necessarily with the task router.
- Add more logging when `updateUsage` fails due to a nil timestamp. I suspect it's because the ExecuteResponse has an error, but this logging will let us confirm.
---
**Related issues**: https://github.com/buildbuddy-io/buildbuddy-internal/issues/1508
> Improve error logging in markTaskComplete

- enterprise/server/remote_execution/execution_server/BUILD
- enterprise/server/remote_execution/execution_server/execution_server.go
- enterprise/server/scheduling/scheduler_server/scheduler_server.go
- enterprise/server/tasksize/tasksize.go
- enterprise/server/tasksize/tasksize_test.go
- proto/scheduler.proto
- server/interfaces/interfaces.go
- tools/tasksize_stress/tasksize_stress_test.go
The scheduler will now apply task size measurements just before enqueueing a task onto an executor, limiting the task size to the executor's resource limits. This means that task sizing should no longer affect schedulability at all.
This approach is different than the original proposal in https://github.com/buildbuddy-io/buildbuddy/pull/2315, which was to have executors apply task size measurements locally. I found that it was cleaner to have the scheduler apply the task size measurements just before enqueueing a task onto the executor, because there were 3 different places where the executor was looking at the task_size field and we'd have to be careful to apply the measured task size in all 3 places as well as any future places. By having the scheduler apply the size adjustment, we …
> Task sizing: Fix measurements causing tasks to become unschedulable

- enterprise/server/execution_service/execution_service.go
- enterprise/server/remote_execution/execution_server/execution_server.go
- enterprise/server/remote_execution/executor/executor.go
- proto/remote_execution.proto
- server/tables/tables.go
We were checking the conditions `ExitCode != 0 || Status != OK` to determine whether to use the invocationID-hashed action digest, but we also need `|| DoNotCache` since we add the invocation ID to the action result hash in that case as well.
---
> Allow viewing action results for actions marked with do_not_cache

- server/remote_cache/hit_tracker/hit_tracker.go
Scorecard metadata is sometimes missing or incomplete -- adding some debug logs to get a sense of how often this is happening in dev and to see if we can find any patterns.
---
> Add some debug logs for missing scorecard request metadata

- enterprise/server/remote_execution/vmexec_client/BUILD
- enterprise/server/remote_execution/vmexec_client/vmexec_client.go
- enterprise/server/vmexec/BUILD
- enterprise/server/vmexec/vmexec.go
- enterprise/server/vmexec/vmexec_test.go
- Implement `ExecStreamed` RPC in `vmexec.go`
- Add a client library that correctly implements the client streaming protocol.
- A subsequent PR will replace our existing usage of `Exec()` in `firecracker.go` with `ExecStreamed()`.
---
> Task sizing: Add initial impl of streaming vmexec API

- enterprise/server/scheduling/scheduler_server/scheduler_server.go
This will produce better debugging information in the logs.
We had an issue yesterday with a task that was never executed, but it
kept being reused due to action merging. I suspect this means this task
actually existed (since we check during merging) but was somehow marked
as claimed.
---
> Differentiate missing task & already claimed task during claim attempt.

- enterprise/server/scheduling/scheduler_server/scheduler_server.go
The executor already knows/logs the task ID when a claim does not
succeed so there's no need to repeat it in the error message. This makes
it easier to see the error message in the log line.
---
> Simplify task claim error messages.

- app/terminal/BUILD
- app/terminal/ansi.tsx
- app/terminal/row.tsx
- app/terminal/text.tsx
- app/terminal/text_test.ts
* Fix bug that we were only expanding at most 1 tab to the equivalent spacing, causing a crash due to incorrect wrapping calculations if a line has multiple tabs.
* Add a safeguard to render a blank line instead of crashing if wrapping calculations are off for any other reason in the future.
* Properly handle tabs by converting each tab to the number of spaces required to reach the next tab stop position.
---
> Terminal V2: Fix handling of tab characters

- app/terminal/row.tsx
When copying and pasting text, lines would be concatenated together in a single line. The fix is to append a newline to the last row in each wrapped line. (These newlines are lost when we split by `\n` originally)
---
> Terminal V2: Fix missing newlines in copied-and-pasted text

- tools/metrics/grafana/dashboards/buildbuddy.json
Metric name changed to `buildbuddy_remote_cache_disk_cache_usec_since_last_access_bucket` (and units changed to usec), so update histogram to reflect that. Also tweak graph settings so they look nicer and are easier to understand.
---
> Update disk access by time with new metric name, add pretty visuals

- server/util/log/log.go
How do people feel about printing stack traces for all errors?
When debugging locally, I find stack traces helpful, even for common errors.
For example if a local service is unavailable or resource is exhausted,
it's helpful to have more information about where exactly it's failing.
> Print stack trace for all errors

- server/metrics/metrics.go
* For most metrics, change the buckets from `(min=1us, max=30d, factor=2)` (~37 buckets) to `(min=1us, max=1h, factor=10)` (~10 buckets)
* For some metrics, use a custom bucket range, with reasonable cardinality.
---
> Reduce bucket granularity for duration metrics

- enterprise/server/cmd/ci_runner/main.go
The original intent was to remove all untracked and ignored files and directories. The new implementation does this properly, while the old implementation did not properly delete ignored directories.
Test with:
```
#!/usr/bin/env bash
set -euo pipefail
cd $(mktemp -d)
git init
echo '
ignored_dir/
ignored_file.txt
' > .gitignore
git add .
git commit -m "Initial commit with .gitignore"
touch untracked_file.txt
mkdir untracked_dir
touch untracked_dir/file.txt
mkdir ignored_dir
touch ignored_dir/file.txt
touch ignored_file.txt
git clean -X --force
git clean -d --force
echo "Paths remaining after clean (excluding .git/*):"
find . | grep -v './.git/'
```
Output before (with `git clean -X --force && git clean -d --force`); note `ignored_dir` is not removed (bug):
```
Paths remaining after clean …
```
> CI runner: Fix git clean to remove ignored directories

- enterprise/server/cmd/ci_runner/main.go
- enterprise/server/test/integration/ci_runner/ci_runner_test.go
- enterprise/server/workflow/config/config.go
- enterprise/server/workflow/service/service.go
Adds a new `git_clean_exclude` list to the workflow action config, which will be passed as extra `-e` flags to `git clean`.
Context: This is needed for `rules_xcodeproj` which needs a bazel output base that is in-repo. (Creating a symlink to the existing output base will not work.) This dir will be added to `.gitignore` so it will be cleaned by our usual `git clean` logic, so we need a way to explicitly exclude it from `git clean`.
---
> Workflows: Allow excluding paths from git clean

- enterprise/server/backends/pebble_cache/pebble_cache.go
Use math.big to evenly divide the CAS and AC keyspace and scan the CAS keyspace with more goroutines (160) than before (16).
> Use math.big to evenly scan ranges on startup with more goroutines

- enterprise/server/backends/pebble_cache/BUILD
- enterprise/server/backends/pebble_cache/pebble_cache.go
- enterprise/server/backends/pebble_cache/pebble_cache_test.go
This cleanup CL just removes the old atimes map since now we are relying on an atime written in the record.
> Remove in-memory atimes map, which is not used

- enterprise/server/backends/pebble_cache/pebble_cache.go
This is to prevent potential panics / race conditions.
Also, compute some simple summary stats across all partitions by summing the cas, ac, and bytes totals and showing them in /Statusz. (I find myself adding these often when debugging things, so I figured I'd let a computer do it)
> Make partition evictor use db leases too

- server/util/flagutil/BUILD
- server/util/flagutil/common/common.go
- server/util/flagutil/flagutil.go
- server/util/flagutil/types/autoflags/BUILD
- server/util/flagutil/types/autoflags/autoflags.go
- server/util/flagutil/types/autoflags/autoflags_test.go
- server/util/flagutil/types/types.go
- server/util/flagutil/types/types_test.go
- server/util/flagutil/yaml/yaml.go
- server/util/flagutil/yaml/yaml_test.go
This introduces `autoflags`, which greatly simplifies the use of `DeprecatedFlag`s. It also allows us to disambiguate the special case of string-based slice flags from the general JSON-based slice flags, which were previously fairly muddled together, while still not requiring the user of the library to make the distinction themselves. Finally, it allows for easy extension of our flag types. `autoflags.New` and `autoflags.Deprecated` can be used anywhere a normal `flag`-style flag declaration, like `flag.Bool` is used, and `autoflags.Var` and `autoflags.DeprecatedVar` can be used anywhere a `flag`-style `Var` flag declaration is used, like `flag.BoolVar`.
---
> Add flag type registry

- enterprise/server/backends/gcs_cache/gcs_cache.go
- enterprise/server/backends/memcache/memcache.go
- server/backends/disk_cache/disk_cache.go
- server/backends/memory_cache/memory_cache.go
Standardize error type, so that it can be caught and ignored
> Standardize cache delete method by returning NotFoundError for files that don't exist

- enterprise/server/testutil/buildbuddy_enterprise/buildbuddy_enterprise.go
I noticed in some of the tests that timeout there is a gap that seems to be due to telemetry client timeout:
```
2022/08/10 16:15:05.538 INF                        healthcheck.go:204 > HealthChecker transitioning from ready: false => ready: true
2022/08/10 16:15:22.643 DBG                   telemetry_client.go:129 > Error posting telemetry data: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 34.82.173.239:443: i/o timeout"
```
(source: https://app.buildbuddy.io/invocation/08ae1234-9397-4da8-8dba-ac9df2a98839?target=%2F%2Fenterprise%2Fserver%2Ftest%2Fintegration%2Fremote_cache%3Aremote_cache_test)
> Disable telemetry when running buildbuddy_enterprise in tests

- server/util/peerset/peerset.go
- server/util/peerset/peerset_test.go
Prior to this change, the number of fallback peers we attempted to use
was equal to the number of failed preferred peers. In the most common
case of 1 failed peer, we would only try one fallback peer. If that peer
was also down, we would give up and this would typically lead to a
failed write.
This change returns up to 3 fallback peers before giving up.
---
> Increase the number of fallback peers we attempt to use for handoff.

- enterprise/server/backends/pebble_cache/pebble_cache.go
- enterprise/server/backends/pebble_cache/pebble_cache_test.go
- Bug was causing items to be evicted prematurely
- Fix flaky unit tests due to truncating floats instead of rounding up. Was also causing items to be evicted prematurely, causing test failures
- Fix TestingWaitForGC. If the cache held exactly the max number of bytes, the test would wait forever and timeout
> Fix double JanitorCutoffThreshold multiplication in pebble cache

- server/util/db/db.go
Useful for batch tools that interact with the DB directly with more expensive queries, and don't want the console to be spammed with slow query warnings.
---
> Make SQL slow query threshold configurable

- enterprise/server/backends/s3_cache/s3_cache.go
Leads to unnecessary copying of S3 objects
> Don't try to  bump TTL of S3 objects if no TTL set

- enterprise/server/backends/gcs_cache/gcs_cache.go
- enterprise/server/backends/memcache/memcache.go
- enterprise/server/backends/redis_cache/redis_cache.go
- enterprise/server/backends/s3_cache/s3_cache.go
- server/backends/memory_cache/memory_cache.go
buildbuddy-io/buildbuddy-internal#1485
Some cache types automatically expose last access / modify time. Add this lowhanging fruit to the metadata API.
For those that don't, a little more work will be required to buffer access time updates, so add in a separate PR
> Add metadata timestamps for cache types that already expose it

- enterprise/server/raft/replica/replica.go
- proto/raft.proto
The split point should be a single key, otherwise there will be a gap in
the ranges.
---
> Fix raft split point logic.

- app/invocation/cache_requests_card.tsx
Before, if an optional field did not exist, a `0` would be printed on the cache requests card.
> Fix formatting of optional fields on cache requests card

- enterprise/server/cmd/smash/smash.go
- server/remote_cache/digest/digest.go
- server/testutil/testdigest/testdigest.go
Once in a while I need to generate random digests in a one-off testing
tool and it'd be nice to have this functionality easily accessible.
---
> Make random digest generator usable outside of tests.

- server/util/dsingleflight/BUILD
- server/util/dsingleflight/dsingleflight.go
- server/util/dsingleflight/dsingleflight_test.go
We were not propagating the error from the work function. If a worker
got the result from the redis stream, they would see the correct error
but the worker that owns the work could incorrectly return a nil error.
---
> Fix error propagation in dsingleflight util.

- enterprise/server/raft/client/client.go
- enterprise/server/raft/store/store.go
- proto/raft_service.proto
When attempting to write to peers, send the first request and wait for a
response from the peer to indicate whether it has accepted the write. If
the write fails (for example due to stale range information), we can
retry with fresh information.
---
> Handle stale write attempts.

- enterprise/server/raft/filestore/BUILD
- enterprise/server/raft/filestore/filestore.go
- enterprise/server/raft/replica/replica.go
- enterprise/server/raft/store/BUILD
- enterprise/server/raft/store/store.go
This keeps ownership of the DB inside the replica.
[It's also a prerequisite for tests (coming in another CL) that test file writes to the replica.]
> Move Reader, Writer, and FindMissing to the replica

- server/util/rangemap/rangemap.go
- server/util/rangemap/rangemap_test.go
Since the right end is exclusive, it should not be considered
overlapping if a different range has it as it as its left.
---
> Fix range overlap check.

- enterprise/server/scheduling/priority_task_scheduler/priority_task_scheduler.go
- enterprise/server/tasksize/tasksize.go
- enterprise/server/test/integration/remote_execution/BUILD
- enterprise/server/test/integration/remote_execution/remote_execution_test.go
This fixes two problems:
- (main issue) the 10ms polling was causing constant CPU usage of a few % even while the executor was idle. In dev, the executor always consumes around 4.5% CPU. Locally, the CPU usage is always around 1.7% and this change brings it to 0%.
- (minor issue) the 10ms poll rate was artificially throttling the queue draw-down rate to one task per 10ms.
---
> Remove polling from task scheduling loop

- server/util/rangemap/rangemap.go
- server/util/rangemap/rangemap_test.go
For the right index, we find the first range that does *not* overlap the
range being tested. If the right index is 0 then it means there are no
ranges that overlap.
---
> Fix overlap check.

- enterprise/tools/tensorflow/BUILD.lib.bzl
- enterprise/tools/tensorflow/Dockerfile
- enterprise/tools/tensorflow/WORKSPACE
- enterprise/tools/tensorflow/deps.bzl
- enterprise/tools/tensorflow/generate_repository.sh
Adds a script `enterprise/tools/tensorflow/generate_repository.sh` that can be run to generate a Bazel-compatible Tensorflow repo. The generated repo contains only the files needed to build the Go bindings:
* The original go sources from the `tensorflow/go` subdirectory in TF proper
* Gazelle-generated BUILD files (with `-proto=disable` since it gets confused when trying to generate the protos). The `tensorflow/go/BUILD` file is modified to properly link against `libtensorflow`
* The generated code produced via `(cd tensorflow/go/op && go generate)`, which generates Go protos among other things
* The C headers under `tensorflow/c/` (these are taken from the release archive, rather than the original repo, since we link against the release shared object)
* A `deps.bzl` file containing an …
> Add tooling for generating a Bazel repository with minimal Tensorflow Go bindings

- enterprise/server/raft/cache/cache.go
- enterprise/server/raft/filestore/filestore.go
- enterprise/server/raft/replica/BUILD
- enterprise/server/raft/replica/replica.go
- enterprise/server/raft/replica/replica_test.go
- enterprise/server/raft/store/store.go
- enterprise/server/raft/store/store_test.go
- Simplify replica construction by only requiring a single dir, rootDir, in New().
- Clean up replica tests to use the replica Writer directly.
- Add a DeleteStoredData method to fileStorer
- Add a function to delete stored files based on k/v ranges, and call it from split().
> Delete unused files after splitting

- deps.bzl
To add the cgo deps without breaking the internal repo, we need to first add the TF go_repository to deps.bzl, then let the repo auto-sync complete, then import the cgo deps from the go_repository within the internal repo WORKSPACE. Then, we can use tensorflow safely in the OSS repo without the internal repo breaking.
---
> Add go-tensorflow to deps.bzl

- enterprise/tools/tensorflow/BUILD.lib.bzl
- enterprise/tools/tensorflow/Dockerfile
TF doesn't work unless `libstdc++.so.6` and `libgcc_s.so.1` are available at runtime. I didn't catch this until trying to run BB as a Docker container (which is based on the distroless image), since when running as a regular go_binary, my system copies of these libs were used.
We could also switch to the `distroless/cc-debian11` base image (instead of `distroless/debian11`) but I figured it's more portable to include the libs in the generated repo.
Generated repo diff: https://github.com/bduffany/go-tensorflow/commit/35855b13822d37e8e9e77ec74bf8582e5d656d90
---
> Update generated TF repo with required c++ libs

- enterprise/server/raft/replica/replica.go
- enterprise/server/raft/replica/replica_test.go
- enterprise/server/raft/store/store.go
Although we already validate the generation in the store, the generation
in the replica might change due to a concurrent split so we need to
revalidate the generation after split lock is acquired to make sure the
generation hasn't changed.
---
> Check range generation in replica.

- proto/health.proto
I don't think anyone was using this yet, but lmk if you know of any.
The path / service name are both configurable in AWS so this is just as simple to use as before and now is at a more widely known path.
Related to https://github.com/buildbuddy-io/buildbuddy-internal/issues/1606
> Make gRPC health check appear at grpc.health.v1.Health

- enterprise/server/test/integration/invocation_webhook/BUILD
- enterprise/server/test/integration/invocation_webhook/invocation_webhook_test.go
- server/build_event_protocol/build_event_handler/BUILD
- server/build_event_protocol/build_event_handler/build_event_handler.go
- server/remote_cache/hit_tracker/hit_tracker.go
- server/testutil/buildbuddy/buildbuddy.go
After enabling detailed stats, we no longer populate the `score_card` field in invocation webhook payloads. This PR restores that functionality and also adds an integration test for invocation webhooks.
---
> Populate scorecard field in invocation webhook payload with action cache misses

- enterprise/server/remote_execution/container/container.go
- enterprise/server/remote_execution/executor/executor.go
- enterprise/server/scheduling/scheduler_client/scheduler_client.go
- enterprise/server/scheduling/scheduler_server/scheduler_server.go
* Audit all usages of `time.Ticker` and make sure we `defer ticker.Stop()`.
* Some exceptions are made in cases where we create a ticker in a func like `foo.Start()` and then destroy it in a symmetric call to `foo.Stop()`. Note, it is safe to call `ticker.Stop()` twice.
* In any cases where we call `defer ticker.Stop()`, make sure the `defer` is not inside a `for` loop. Otherwise, the ticker will be kept running until the for loop terminates (potentially never, in some cases), incurring high CPU load. (Note, a ticker will run even if nobody is receiving from ticker.C)
---
> Fix usages of time.Ticker

- enterprise/server/raft/replica/replica.go
- enterprise/server/raft/replica/replica_test.go
On a new node, the keys for existing files won't be present because the
file writes are not part of the raft log.
---
> Fetch file from peer if key is missing on write.

- enterprise/server/invocation_stat_service/invocation_stat_service.go
- server/build_event_protocol/build_event_handler/build_event_handler.go
So that we can enable double write first; then enable reading from
clickhouse after the data is backfilled.
> add seperate flags for reading and writing from clickhouse

- enterprise/server/raft/rangelease/rangelease.go
I saw this happen once during some testing:
```
12:49:48 app3 | panic: runtime error: invalid memory address or nil pointer dereference
12:49:48 app3 | [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xf92fb8]
12:49:48 app3 | goroutine 197358 [running]:
12:49:48 app3 | github.com/buildbuddy-io/buildbuddy/proto/raft.(*RangeLeaseRecord).Reset(0x1f912a0?)
12:49:48 app3 | 	bazel-out/k8-fastbuild/bin/proto/raft_go_proto_/github.com/buildbuddy-io/buildbuddy/proto/raft/raft.pb.go:2209 +0x18
12:49:48 app3 | google.golang.org/protobuf/proto.Reset({0x7145ac0, 0x0})
12:49:48 app3 | 	external/org_golang_google_protobuf/proto/reset.go:18 +0x3e
12:49:48 app3 | google.golang.org/protobuf/proto.UnmarshalOptions.unmarshal({{}, 0x0, 0x0, 0x0, {0x7152788, 0xc0000fac60}}, {0xc0003a5220, 0x1d, …
```
> Fix a potential panic

- enterprise/server/raft/replica/replica.go
Try to fix a weird panic I saw during testing:
```
15:21:27 app4 | panic: runtime error: invalid memory address or nil pointer dereference
15:21:27 app4 | [signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x196d185]
15:21:27 app4 | goroutine 1004 [running]:
15:21:27 app4 | github.com/buildbuddy-io/buildbuddy/enterprise/server/raft/replica.(*Replica).Close(0xc0001519e0)
15:21:27 app4 | 	enterprise/server/raft/replica/replica.go:1578 +0x25
15:21:27 app4 | github.com/lni/dragonboat/v3/internal/rsm.(*OnDiskStateMachine).Close(0x0?)
15:21:27 app4 | 	external/com_github_lni_dragonboat_v3/internal/rsm/adapter.go:343 +0x25
15:21:27 app4 | github.com/lni/dragonboat/v3/internal/rsm.(*NativeSM).Close(0xc005a7ed00)
15:21:27 app4 | …
```
> Fix a potential panic in Close

- enterprise/server/raft/store/store_test.go
Previously these tests were writing files in a very weird way.
> Correct store tests so they immitate SyncWriter

- server/backends/invocationdb/BUILD
- server/backends/invocationdb/invocationdb.go
- server/build_event_protocol/build_event_handler/build_event_handler.go
- server/util/capabilities/BUILD
- server/util/capabilities/capabilities.go
- server/util/perms/perms.go
Fixes buildbuddy-io/buildbuddy-internal#1589
When we create an invocation, we are setting the permissions based on the context (https://github.com/buildbuddy-io/buildbuddy/blob/master/server/backends/invocationdb/invocationdb.go#L91). These are
being overwritten for workflows for public repos. This may
incorrectly restrict the invocation, if we had previously set additional permissions on it
> For public invocations, add (as opposed to replace) others_read permissions

- cli/autoconfig/autoconfig.go
- cli/cache_proxy/cache_proxy.go
- cli/sidecar/sidecar.go
- enterprise/server/backends/distributed/distributed.go
- enterprise/server/backends/gcs_cache/gcs_cache.go
- enterprise/server/remote_execution/containers/docker/docker.go
- enterprise/server/remote_execution/containers/docker/docker_test.go
- enterprise/server/remote_execution/containers/firecracker/firecracker_test.go
- enterprise/server/remote_execution/containers/podman/podman_test.go
- enterprise/server/remote_execution/dirtools/dirtools.go
- enterprise/server/remote_execution/filecache/filecache_test.go
- enterprise/server/remote_execution/workspace/workspace_test.go
- enterprise/server/webhooks/bitbucket/bitbucket.go
- enterprise/server/webhooks/github/github.go
- enterprise/server/workflow/config/config.go
- server/backends/blobstore/blobstore.go
- server/backends/github/github.go
- server/http/filters/filters.go
- server/http/protolet/protolet.go
- server/remote_asset/fetch_server/fetch_server.go
- server/ssl/ssl.go
- server/telemetry/telemetry_client.go
- server/testutil/testbazel/testbazel.go
- server/testutil/testserver/testserver.go
- server/util/compression/compression.go
- server/util/devnull/devnull.go
- server/util/disk/disk.go
- Replace usages of ioutil.ReadDir with os.ReadDir
- Replace usages of ioutil.ReadFile with os.ReadFile
- Replace usages of ioutil.ReadAll with io.ReadAll
- Replace usages of ioutil.WriteFile with os.WriteFile
- Replace ioutil.TempFile, ioutil.Discard with non-deprecated equivalents
> Remove usages of deprecated ioutil

- docs/config-flags.md
- docs/prometheus-metrics.mdx
Added a line noting the path and port that Prometheus metrics are configured with. Also documented the `--monitoring_port` config flag.
> Document Prometheus metrics path and port

- server/util/flagutil/yaml/yaml.go
- Fixes a bug where an instance of the type of the type, as opposed to the type, was being default-constructed for pointers.
- Adds indentation to allow uncommenting the examples to work properly with sub-examples.
- Changes `AppendTypeToLineComment` to not pass through so it doesn't double (or triple, or quadruple, etc) up types at the end of lines.
---
> Make yaml autodocs give examples for null fields

- enterprise/server/remote_execution/container/container.go
The `.Add()` method for a Prometheus counter metric panics if called with a negative value (:cry:)
I am only seeing this on Mac executors, and very rarely (once every few days). Presumably it's some issue with the system clock, or some imprecision with the process stats API being used.
---
> Fix rare panic in ContainerMetrics.Observe

- enterprise/server/cmd/executor/executor.go
- enterprise/server/remote_execution/container/container.go
- enterprise/server/remote_execution/containers/bare/bare.go
- enterprise/server/remote_execution/containers/firecracker/firecracker.go
- enterprise/server/remote_execution/containers/podman/podman.go
- enterprise/server/remote_execution/containers/sandbox/sandbox.go
- enterprise/server/remote_execution/runner/BUILD
- enterprise/server/remote_execution/runner/runner.go
- enterprise/server/remote_execution/runner/runner_test.go
- enterprise/server/test/integration/remote_execution/rbetest/rbetest.go
- Update the runner pool logic and `container.Stats()` API to allow returning 0 as a valid memory usage value, and to allow returning `nil` to represent "not implemented, use an estimate instead"
- Update all container implementations so that only Firecracker returns 0 memory from `Stats()`, and all the other impls which don't yet implement `Stats()` (or have it disabled) return `nil` instead.
---
> Remove runner pool memory restrictions for Firecracker

- tools/metrics/grafana/dashboards/buildbuddy.json
These charts show up in the "kubernetes nodes" section but only work for Macs -- for kube nodes the charts will be empty since we don't explicitly scrape mem metrics (yet?)
Swap usage is also interesting, but for some reason it always shows 0 (for both current and total). Looking into this separately.
---
> Add Mac memory usage charts to Grafana

- tools/metrics/grafana/dashboards/buildbuddy.json
- tools/metrics/process_dashboard.py
- tools/metrics/run.sh
Some changes to prevent unnecessary diffs and make it less painful to deal with concurrent changes to the dashboard JSON across multiple branches:
- Remove null values (I see these show up in diffs sometimes, not sure why, but the dashboard seems to work the same with or without these)
- Prevent accidentally modifying the refresh interval (happens to me all the time, since locally I find a short refresh interval like 5s more useful)
- Prevent accidentally updating the "collapsed" bit, leaving panels expanded unnecessarily (also happens often)
- Remove "iteration" key which is unnecessary versioning info
---
> Improve dashboard JSON normalization

- tools/metrics/grafana/dashboards/buildbuddy.json
This will let us quickly verify whether any nodes are under high memory pressure.
Also fix negative values on CPU charts.
---
> Add charts for node swap rate

- docs/workflows-config.md
- Update `pull_request` trigger so that workflows trigger on stacked PRs (e.g. when pushing `frontend` in the chain `main <- backend <- frontend`)
- Remove `--build_metadata=ROLE=CI` since we apply this by default.
- Remove unnecessary `grpcs://` prefix
- Rename "M1" -> "Apple silicon (ARM-based)"
---
> Tweak Mac workflows starter config

- enterprise/server/raft/rbuilder/rbuilder.go
- enterprise/server/raft/replica/replica.go
- enterprise/server/raft/replica/replica_test.go
- enterprise/server/util/pebbleutil/pebbleutil.go
- proto/raft.proto
These two new raft commands allow acquiring/extending a split lease and releasing it. While locked for splitting, a DB cannot be leased, and instead an error is returned.
> Add splitlease support

- app/auth/auth_service.ts
- enterprise/server/auth/auth.go
- enterprise/server/saml/saml.go
Improvements that make our auth library work better with a wider variety of auth providers.
- Don't assume auth token refresh interval on the front-end (different providers issue access tokens with a 5 minute lifespan). Instead set a cookie that the frontend can read when we set the login cookies.
- Don't assume all auth providers support `consent=prompt` (some don't) and put this behind a flag.
- If an auth provider gives us a new refresh token in the token refresh response, update the session so we use that one going forward (some auth providers will "roll" the refresh token, so old tokens become invalid once they're used once).
- Don't assume that refresh tokens contain an "id_token" (some providers don't set this). If they don't, preserve the original id token.
---
**Version bump**: …
> Support wider range of auth providers

- enterprise/server/backends/pebble_cache/BUILD
- enterprise/server/backends/pebble_cache/pebble_cache.go
- server/metrics/metrics.go
While we could theoretically get filesystem information via the node metrics, it's in a format that's more difficult to work with for our needs.
---
> Export filesystem usage information from pebble cache.

- server/role_filter/role_filter.go
Previously this would output the confusing message `Could not determine authenticated group ID from request`, when in fact the server admin group was simply not defined.
---
> Fix error message when attempting to use a server-admin only endpoint with no server-admin group ID defined

- enterprise/server/raft/bringup/bringup.go
- enterprise/server/raft/replica/replica.go
- enterprise/server/raft/store/store.go
- Log spurious reqs received during split
- Check SyncPropose error
- Remove spurious log
> Small raft cleanup

- tools/metrics/grafana/dashboards/clickhouse.json
The dashboard is adapted from https://github.com/Altinity/clickhouse-operator/blob/master/grafana-dashboard/Altinity_ClickHouse_Operator_dashboard.json
Changes: Removed the graph referencing an unsupported plugin: "grafana-piechart-panel"
Screenshot:
> Add a clickhouse grafana dashboard

- cli/cmd/bb/BUILD
- cli/cmd/bb/bb.go
- cli/remotebazel/BUILD
- cli/sidecar/BUILD
- cli/sidecar/sidecar.go
- cli/sidecar_bundle/BUILD
- cli/sidecar_bundle/sidecar_bundle.go
Really basic -- just in the spirit of making things build again. This bundles the sidecar into the CLI rather than trying to do anything fancy like downloading it.
Tested: it works.
> Bundle the sidecar instead of downloading it

- tools/enable_local_firecracker.sh
In Ubuntu 20.04.1, cgroup2 is mounted on `/sys/fs/cgroup/unified`, not `/sys/fs/cgroup`. Update the script to read the cgroup2 path using `mount | grep cgroup2`. Also delete the old cgroup v1 stuff (cpuset), and fix a few shellcheck lints.
---
> Fix tools/enable_local_firecracker.sh to allow cgroup2 mounted on /sys/fs/cgroup/unified

- enterprise/server/remote_execution/runner/runner.go
If folks want to run docker and connect to it over tcp, they will now be able to by setting
```
executor.docker_host=tcp://localhost:2375
```
in their config. Existing configs which set a file path should still have "unix://" prefixed to them and be unaffected.
> Allow a lil docker tcp socket as a treat

- enterprise/server/remote_execution/commandutil/commandutil.go
- enterprise/server/remote_execution/containers/firecracker/containeropts.go
- enterprise/server/remote_execution/containers/firecracker/firecracker.go
- enterprise/server/remote_execution/containers/firecracker/firecracker_test.go
- enterprise/server/remote_execution/runner/runner.go
- enterprise/server/remote_execution/vmexec_client/vmexec_client.go
- enterprise/server/vmexec/vmexec.go
- enterprise/server/vmexec/vmexec_test.go
- proto/vmexec.proto
Can be specified as `USER[:GROUP]`, where both USER and GROUP can be either names or IDs (same as Docker).
To be consistent with Docker, we do not create the user automatically. Instead the user is expected to be provisioned as part of the Docker image.
---
**Related issues**: https://github.com/buildbuddy-io/buildbuddy-internal/issues/1643
> Support dockerUser platform prop for firecracker

- enterprise/server/raft/store/store.go
I think the following is happening during moves:
A replica is removed from a range.  Other apps still have that replica in the cached range descriptor so they keep sending requests to that node. Since the node returns NotFound errors, the clients never refresh their range descriptors.
---
> Return OutOfRangeError if replica is not found.

- enterprise/server/cmd/executor/BUILD
- enterprise/server/cmd/executor/executor.go
- server/util/monitoring/BUILD
- server/util/monitoring/monitoring.go
When `--monitoring.ssl_port` >= 0, use the SSL config to serve the monitoring handler with HTTPS on that port.
---
> Allow SSL to be used for monitoring endpoint on executor

- app/router/router.tsx
- enterprise/app/filter/filter.tsx
- enterprise/app/filter/filter_util.tsx
- enterprise/app/history/history.tsx
- enterprise/app/trends/trends.tsx
- enterprise/server/invocation_search_service/invocation_search_service.go
- enterprise/server/invocation_stat_service/invocation_stat_service.go
- proto/invocation.proto
- server/util/clickhouse/clickhouse.go
This column doesn't (yet) have an index, but this is under advanced filter - so we can worry about that if we get any negative performance feedback. 
Not sure if there's anything I need to do on the clickhouse side of things of whether this will "just work". cc @luluz66 
I can verify clickhouse compatibility when this goes to dev.
---
> Add bazel "command" as an advanced filter

- cli/autoconfig/autoconfig.go
* Fix indentation (bazel fails to build w/ the current indentation)
* Import http_archive if not already imported
---
> Fix CLI RBE autoconfig

- enterprise/dockerfiles/ci_runner_image/Dockerfile
- enterprise/server/cmd/ci_runner/run_local.sh
- enterprise/server/remote_execution/platform/platform.go
- enterprise/server/test/integration/ci_runner/BUILD
- enterprise/server/test/integration/workflow/BUILD
- enterprise/server/workflow/config/config.go
- enterprise/server/workflow/service/service.go
* Add a `buildbuddy` user to the CI runner image
* Allow setting `user:` in the workflow config, which directly sets the `dockerUser` platform prop. For now, we will only support the "buildbuddy" user (users can explicitly specify "root" if they want, but this will have no effect). This way we're consistent with how users are provisioned for Docker/Podman -- we expect them to be provisioned in the Dockerfile, rather than creating them ourselves.
---
**Related issues**: https://github.com/buildbuddy-io/buildbuddy-internal/issues/1643
> Allow running workflows as a non-root user

- deps.bzl
- go.mod
- go.sum
- server/util/clickhouse/BUILD
- server/util/clickhouse/clickhouse.go
- server/util/clickhouse/clickhouse_test.go
It's difficult to migrate additional existing columns to clickhouse after initial migration.
In this PR,
- add all the columns from Invocation to clickhouse if i think there is
a slight possibility in the future we need it in clickhouse.
- add a method "ExcludedFields", where we need to explicitly call out
the fields we don't want to store in clickhouse.
- add tests to catch future bugs where we forget to add a field in
clickhouse when we add them in Invocation.
> Add more fields to clickhouse.Invocation

- enterprise/server/backends/pebble_cache/pebble_cache.go
* Can no longer make assumptions that the naming structure is
partition_id/<ac/cas>/hash, because now the structure can look like
partition_id/group_id/<ac/cas>/hash
* We can scan the cache synchronously to compute cache size, as opposed to in parallel,
bc we are now caching the metadata, so this computation will occur much less and it's ok
if it's slow
> Small fixes to support adding group ID in directory structure in pebble cache

- cli/bazelisk/BUILD
- cli/bazelisk/bazelisk.go
Since we invoke bazelisk ourselves, bazelisk will just re-invoke us if we're invoked via .bazelversion, causing an infinite recursion of `bazelisk -> bb -> bazelisk -> bb -> ...`.
Break this loop by setting USE_BAZEL_VERSION to the second line in .bazelversion if it exists, or "latest" otherwise.
---
> CLI: fix infinite loop when run via .bazelversion

- .github/workflows/buildbuddy-foss.yaml
- .github/workflows/checkstyle.yaml
- .github/workflows/deps.yaml
- .github/workflows/helm.yaml
- .github/workflows/main.yaml
- .github/workflows/pr.yaml
- .github/workflows/release-m1.yaml
- .github/workflows/release-mac.yaml
- .github/workflows/release.yaml
- .github/workflows/website-pr.yaml
- .github/workflows/website.yaml
- docs/rbe-github-actions.md
I'm running into some weird issues like "reference is not a tree" with checkout v1, which appears to be fixed in v3 ([issue](https://github.com/actions/checkout/issues/23)).
Upgrading all actions to checkout v3 so that we get this fix everywhere, and also because I noticed some issues on m1 which were only fixed by clearing out the _work dir on the runner. I suspect this might be due to some incompatibility between v1 and v3 across different action runs. Either way, upgrading everything to v3 shouldn't hurt, and will rule out version incompatibility as an issue.
---
> Upgrade all checkout actions to v3

- .github/workflows/release-cli.yaml
Adds a workflow that creates a new CLI release over in the `buildbuddy-io/bazel` repo whenever we push a tag `cli-v{VERSION}` to this repo.
---
> Add release workflow for CLI

- cli/install.sh
Adapted from https://github.com/buildbuddy-io/buildbuddy-cli/tree/master/install.sh but works with the new releases over in https://github.com/buildbuddy-io/bazel/releases
Tested linux-amd64 and darwin-arm64
---
> Add install script for CLI

- cli/logging/logging.go
- cli/parser/BUILD
- cli/parser/parser.go
This is based on logic that currently lives here, but will be removed:
https://github.com/buildbuddy-io/buildbuddy/blob/master/cli/cmd/bb/bb.go#L61
Also makes logging non-verbose by default.
---
> Add method that parses .bazelrc files to a list of effective args

- cli/cmd/bb/BUILD
- cli/cmd/bb/bb.go
- cli/cmd/sidecar/BUILD
- cli/cmd/sidecar/sidecar.go
- cli/logging/logging.go
- cli/remotebazel/BUILD
- cli/remotebazel/remotebazel.go
- cli/sidecar/BUILD
- cli/sidecar/sidecar.go
- cli/tooltag/BUILD
- cli/tooltag/tooltag.go
- cli/version/BUILD
- cli/version/version.go
This makes the main of CLI only responsible for manipulating args.
- Moves sidecar configuration into sidecar
- Moves remote bazel configuration into remotebazel
- Pulls `bazel version` handling into its own package
- Pulls tooltag setting into its own package
This drops any RBE / remote cache / BES autoconfiguration, which I think we should think about more carefully before adding back.
Will delete code that this makes obsolete in a separate PR.
---
> Clean up CLI main

- cli/bazelisk/BUILD
- cli/bazelisk/bazelisk.go
- cli/plugin/BUILD
- cli/plugin/plugin.go
- cli/workspace/BUILD
- cli/workspace/workspace.go
First approximation of a plugin API:
- To add a plugin, just add to your buildbuddy.yaml:
```yaml
plugins:
- repo: "owner/repo@abc123" # optional; use current bazel workspace if empty
path: "subdir/within/repo" # optional, behaves like "." by default
```
- The repo + path tells us where to find `pre_bazel.sh` and/or `post_bazel.sh`
- Adds functions to execute those hooks and get their output, if they exist.
- pre_bazel takes the current bazel args, and can output new args, one per line.
- post_bazel gets a path to the combined bazel output (stderr + stdout), and can do whatever it likes.
---
> CLI: Add basic plugin API

- cli/bazelisk/BUILD
- cli/bazelisk/bazelisk.go
- cli/cmd/sidecar/BUILD
- cli/cmd/sidecar/sidecar.go
- cli/log/BUILD
- cli/log/log.go
- cli/logging/BUILD
- cli/parser/BUILD
- cli/parser/parser.go
- cli/remotebazel/BUILD
- cli/remotebazel/remotebazel.go
- cli/sidecar/BUILD
- cli/sidecar/sidecar.go
Rename logging => log so we don't have to use bblog everywhere.
Differentiate between debug logs (that don't get printed unless verbose) and non-debug logs.
---
> Clean up logging in CLI

- cli/plugin/BUILD
- cli/plugin/plugin.go
Support the "repo" parameter in the plugin spec.
Repos are cloned to the storage dir, under `~/.cache/buildbuddy/`, then under `plugins/HOST/OWNER/REPO`, then in a ref-specific subdir: either `latest` if no ref is specified or `ref/REF` if `@<branch,sha,etc>` is specified (the `ref/` is needed so that we can distinguish between "latest commit from the default branch" and "an actual branch named 'latest'")
Also fix a few bugs found when testing.
---
> CLI: Add support for remote plugins

- cli/BUILD
Lets us build/run the CLI with `bazel run cli` instead of `bazel run cli/cmd/bb`. Similar to how we can run the server with `bazel run server`.
---
> Add //cli build target alias

- cli/cmd/bb/bb.go
- cli/log/log.go
For now, this has to come before any other args i.e.
```
bb --verbose build foo
```
---
> Fix `--verbose` flag

- enterprise/server/util/cacheproxy/cacheproxy.go
Fixes buildbuddy-io/buildbuddy-internal#1646
> Add metadata fields to cacheproxy

- enterprise/server/raft/replica/replica.go
- enterprise/server/raft/replica/replica_test.go
This change makes the splitting more flexible: any splittable point in a range is valid. The algorithm searches through the entire range for a split point, and determines the best split point by how closely it approximates splitting the range into two even halves.
If a split point cannot be found for some reason, the range's keys are printed (so we can debug better).
We can tweak it if we want so it only ever splits in the middle third or something, but figured I'd start here. Open to feedback!
> Be more flexible about choosing a split point; add tests

- .github/workflows/release-cli.yaml
- .github/workflows/release-m1.yaml
The GitHub Actions workspace dir doesn't seem to get properly cleaned up before/after workflows on our self-hosted M1 runner. (I noticed that the cloned BB repo as well as the built executor binary from the `release-m1` workflow was present in the workspace during the `release-cli` workflow.)
Temporarily fix this by explicitly cleaning up before running workflows. Do the same on the release-m1 workflow so we always run from a clean workspace on the M1 runner. Longer term, we should figure out why this is happening, but I couldn't find any obvious reasons after searching online and inspecting the permissions on the workspace files.
---
> Fix recursive cloning issue with CLI release

- .github/workflows/release-cli.yaml
I don't think this actually fixes the output of `bb version`, but it at least prevents an undefined variable reference in the workflow.
---
> Fix version definition in CLI release

- enterprise/server/backends/distributed/distributed.go
- enterprise/server/backends/distributed/distributed_test.go
- enterprise/server/backends/gcs_cache/gcs_cache.go
- enterprise/server/backends/memcache/memcache.go
- enterprise/server/backends/migration_cache/migration_cache.go
- enterprise/server/backends/migration_cache/migration_cache_test.go
- enterprise/server/backends/pebble_cache/pebble_cache.go
- enterprise/server/backends/pebble_cache/pebble_cache_test.go
- enterprise/server/backends/redis_cache/redis_cache.go
- enterprise/server/backends/s3_cache/s3_cache.go
- enterprise/server/composable_cache/composable_cache.go
- enterprise/server/raft/cache/cache.go
- server/backends/disk_cache/disk_cache.go
- server/backends/disk_cache/disk_cache_test.go
- server/backends/memory_cache/memory_cache.go
- server/backends/memory_cache/memory_cache_test.go
- server/interfaces/interfaces.go
- server/remote_cache/byte_stream_server/byte_stream_server.go
More details about ResourceName refactor in #2389 
Plan is to create a new Contains method that takes a ResourceName instead of a digest (Ex. https://github.com/buildbuddy-io/buildbuddy/pull/2638)
> Rename Contains to ContainsDeprecated to prepare for ResourceName refactor

- cli/login/login.go
This error was being printed every time since I haven't run bb login yet - log it as a debug msg instead
---
> Use log.Debug for missing API key file error

- cli/bazelisk/bazelisk.go
- cli/cmd/bb/BUILD
- cli/cmd/bb/bb.go
- cli/log/log.go
- cli/plugin/plugin.go
- cli/terminal/BUILD
- cli/terminal/terminal.go
Actually load plugins in `main()` and run their pre/post-bazel plugin hooks.
Tested with both pre- and post-bazel hooks, with both local and remote plugins.
(Note, I haven't made the change to the pre-bazel API yet so that it operates on a single file passed as $1; will do that in a follow-up PR)
---
> CLI: Wire up plugins in `main`

- buildbuddy.yaml
- cli/example_plugins/go_highlight/README.md
- cli/example_plugins/go_highlight/post_bazel.sh
- cli/plugin/plugin.go
This example plugin looks for go source lines and outputs them at the end of the build with the file names highlighted, like this:
I have been using my own Bazel wrapper for a while which does something similar (it highlights the errors inline, instead of at the end of the build). I've found it useful for more quickly spotting errors in Go code, since Go's errors are in plain text and hard to distinguish from other output lines.
---
> Add example "go_highlight" plugin

- server/remote_asset/fetch_server/fetch_server.go
Bug fixes:
* If the remote URI returns an HTTP error status, return an error instead of reading the response body. This can cause empty responses to be returned.
* If we fail to fetch a particular URI, continue to the next URI instead of returning `Aborted`.
* Make sure we call `Close()` on the response body (documentation says the caller is responsible for calling `Close()`).
Improvements:
* Record the last fetch error and return it in the status message, in addition to logging. (We still return a gRPC code of NotFound so this should functionally be a NOP, but improve debuggability.)
* Make sure all logged error messages include the URI.
* Do a checksum on our side (since it's simple enough to do) so that we don't store useless blobs into the cache and so that the client doesn't have to …
> Bug fixes / improvements for FetchBlob

- server/test/integration/remote_asset/BUILD
- server/test/integration/remote_asset/remote_asset_test.go
Verified that 2 of the tests fail without the changes from https://github.com/buildbuddy-io/buildbuddy/pull/2672
---
> Add bazel integration test for remote asset API

- enterprise/server/remote_execution/dirtools/dirtools.go
- enterprise/server/remote_execution/dirtools/dirtools_test.go
Symlinks were being created relative to the executor's working directory rather than relative to the parent `Directory` containing the `SymlinkNode`.
---
> Fix symlink paths

- server/util/clickhouse/clickhouse.go
RowsAffected is always zero in this case.
The data is still writing to clickhouse.
> Remove check one RowsAffected

- app/invocation/BUILD
- app/invocation/cache_requests_card.tsx
- proto/BUILD
- proto/resource.proto
See motivation for this change here:
https://github.com/buildbuddy-io/buildbuddy/pull/2649#discussion_r987289928
> Switch the ordering of the resource.proto CacheType enum

- server/util/fastcopy/fastcopy_darwin.go
Documentation of `C.CString`:
```
// Go string to C string
// The C string is allocated in the C heap using malloc.
// It is the caller's responsibility to arrange for it to be
// freed, such as by calling C.free (be sure to include stdlib.h
// if C.free is needed).
func C.CString(string) *C.char
```
Verified locally using a bazel build that runs a nop sh_test, with `--runs_per_test=100000`. Before, the executor's memory would start at 27MB then climb steadily up to 80 MB or so. After, the executor's memory usage stays at 27MB while the tests are executing.
Interestingly, there's a lot of code in the wild that creates a `C.CString` without freeing it - seems like a Go static analyzer would be able to catch this: https://cs.github.com/?scopeName=All+repos&scope=&q=%22%2C+C.CString%22
--- …
> Fix memory leak in fastcopy_darwin

- enterprise/server/backends/pebble_cache/pebble_cache.go
Part of this refactor: https://github.com/buildbuddy-io/buildbuddy/pull/2389
> Refactor pebble cache to use resourceName when generating file record keys

- enterprise/server/backends/migration_cache/migration_cache_test.go
- server/backends/disk_cache/disk_cache.go
- server/backends/disk_cache/disk_cache_test.go
Using the file size underestimates the real usage since each file is stored as multiples of the filesystem block size.
---
> Update disk cache usage to be calculated based on block size.

- buildbuddy.yaml
- cli/cmd/bb/bb.go
- cli/example_plugins/go_deps/post_bazel.py
- cli/example_plugins/go_deps/post_bazel.sh
- cli/plugin/plugin.go
Looks for go deps issues in the bazel output (post-bazel run) and runs Gazelle on the parent directories of the source files parsed from the errors.
Example run:
https://asciinema.org/a/acoLS4xdiUGURLH9FWKg7Frf9
---
> CLI: Add plugin to run Gazelle on "missing strict dependencies" errors

- buildbuddy.yaml
- cli/bazelisk/BUILD
- cli/bazelisk/bazelisk.go
- cli/cmd/bb/BUILD
- cli/cmd/bb/bb.go
- cli/example_plugins/open_invocation/README.md
- cli/example_plugins/open_invocation/post_bazel.sh
- cli/example_plugins/open_invocation/pre_bazel.py
- cli/example_plugins/open_invocation/pre_bazel.sh
- cli/plugin/plugin.go
Adds a plugin which accepts the flag `--open`. When set, it automatically opens the invocation in the browser, if `bes_results_url` is also set.
This plugin needs to pass data between `pre_bazel.sh` and `post_bazel.sh`, so we now provision a temp dir for each plugin where they can write whatever data they want. The dir path is available via the `PLUGIN_TEMPDIR` env var.
---
> CLI: Add `--open` plugin

- buildbuddy.yaml
On macOS, we ran into an issue that bazelisk output is not properly getting line-buffered, so there is a long delay between when bazelisk prints a line of output and when we see it in the terminal.
The issue is that when we are using bazel output handler plugins, bazelisk no longer thinks that it's writing to a terminal, since we are using `io.Pipe()` to pass output to the bazel output handler pipeline. On macOS, line buffering apparently gets disabled when not writing to a terminal (this behavior doesn't seem to happen on Linux).
To fix this properly, we need to pipe via a `pty` so that bazelisk thinks it's writing to a terminal. But this is looking like a somewhat involved fix, so while the fix is in progress, I'm disabling the bazel output handler plugins that we have active in the BB …
> CLI: Temporarily disable bazel output handler plugins

- buildbuddy.yaml
- cli/plugin/BUILD
- cli/plugin/plugin.go
This fixes the bazel output buffering issue since it tricks plugins into thinking they are writing to a terminal.
Tested on macOS and Linux.
---
> CLI: Write plugin pipeline outputs to a pty

- .github/workflows/release-cli.yaml
- cli/version/BUILD
- cli/version/defs.bzl
- cli/version/version.go
Adds a build flag `--//cli/version:cli_version` that lets us specify the CLI version, and sets this based on the git tag in the release workflow.
---
**Related issues**: Fixes https://github.com/buildbuddy-io/buildbuddy-internal/issues/1746
> CLI: Fix version command

- cli/cmd/bb/bb.go
- cli/log/BUILD
- cli/log/log.go
- Remove call to `flag.Parse()`
- Make `--verbose` a manually parsed flag. For now it has to be set to either `--verbose=1` or `--verbose=true`.
- TODO in future PR: Need to figure out an alternate flag parsing strategy so that we can still use the standard Go `flag` library for anything that depends on it. We might want to consider something like requiring all bb flags to be prefixed with `bb`, then call `flag.Parse()` only with those prefixed flags (by temporarily overriding `os.Args`). We could alternatively require startup flags to be passed via `--startup_flag=--foo=bar` but that would break compatibility with `bazel` -- not sure if we want to do that.
---
> CLI: Make bazel startup flags work

- enterprise/server/raft/client/client.go
Proposing something via raft requires a deadline. Previously this was hardcoded to 1 second, which can cause issues if the raft command being applied takes longer than that.
I noticed this when debugging a split issue -- acquiring the split lock requires waiting for existing reads/writes to finish, and this can take longer than a second.
> Require a deadline; use it

- enterprise/server/remote_execution/execution_server/execution_server.go
- enterprise/server/scheduling/scheduler_server/scheduler_server.go
- server/rpc/filters/BUILD
- server/rpc/filters/filters.go
- server/util/log/BUILD
- server/util/log/log.go
- server/util/uuid/BUILD
- server/util/uuid/uuid.go
Instead of extracting a hardcoded set of IDs at log time, allow identifiers to be added to the context.
This will enable us to enrich log events with execution_id, raft replica id, etc.
---
> Change the way IDs (invocation, request) are propagated to the logger.

- cli/bazelisk/bazelisk.go
- cli/cmd/bb/bb.go
- cli/plugin/plugin.go
---
**Related issues**: Fixes https://github.com/buildbuddy-io/buildbuddy-internal/issues/1747
> CLI: Fix Ctrl+C not working when bazel output handlers are active

- cli/bazelisk/bazelisk.go
USE_BAZEL_VERSION=5.0.0 wasn't working because our current logic would always set USE_BAZEL_VERSION=latest if `.bazelversion` doesn't point to `buildbuddy-io/`. This PR fixes that, so that we stay compatible with bazelisk.
---
> CLI: Respect USE_BAZEL_VERSION env var

- cli/bazelisk/BUILD
- cli/bazelisk/bazelisk.go
- cli/cmd/bb/bb.go
- Don't run bazel output handlers on the output of the `bazel run` binary
- Run post-bazel plugins after the bazel build and before the run
---
**Related issues**: Fixes https://github.com/buildbuddy-io/buildbuddy-internal/issues/1748
> CLI: Only run plugins on the `build` step in `bazel run` invocations

- server/backends/disk_cache/disk_cache.go
- server/backends/disk_cache/disk_cache_test.go
The disk cache tests have been really flaky for me due to a race condition where temp files are being deleted by the initialization function at the same time as when we're trying to [set data in unit tests](https://github.com/buildbuddy-io/buildbuddy/blob/master/server/util/disk/disk.go#L81)
> Prevent disk cache race condition when cleaning up temp files

- app/router/router.tsx
`getUnavailableMessage()` was looking at the pathname of the target URL, but `capabilities.canNavigateToPath()` was looking at the whole URL including params, which caused it to incorrectly return `false` in some cases.
This PR updates the logic so that we only pass in the matched `Path` string to both functions.
---
> Fix "unavailable" alert logic for target URLs containing params

- cli/bazelisk/bazelisk.go
- cli/cmd/bb/BUILD
- cli/cmd/bb/bb.go
- cli/watcher/BUILD
- cli/watcher/watcher.go
- deps.bzl
- go.mod
- go.sum
Using [godemon](https://github.com/bduffany/godemon) as the file watcher for now since it embeds easily in Go. We might consider switching to [ibazel](https://github.com/bazelbuild/bazel-watcher) in the future, but we might want to either fork or contribute some upstream patches since it has some undesired behavior, e.g. https://github.com/bazelbuild/bazel-watcher/issues/305. We'd also need to figure out how to embed it in our app, since the Go API currently isn't visible externally.
---
> CLI: Support interactive rebuilding with `-w` or `--watch` flag.

- enterprise/server/backends/migration_cache/migration_cache.go
- enterprise/server/backends/migration_cache/migration_cache_test.go
* Fix bug where we'd log a FindMissing discrepancy even when we weren't double reading, so the destination cache array was always empty
* Add metrics to track how many double reads are successful to get a better sense of what % of reads are unsuccessful
> Only log migration FindMissing discrepancies if we are double reading

- cli/example_plugins/go_deps/post_bazel.py
* Pass `exist_ok` to `makedirs` (unlike `mkdir -p` it returns an error if the dir already exists :confused:)
* Make sure stdout is a tty before showing prompts, otherwise if the bb output is being redirected to a file then the command might hang and it won't be clear why
---
> CLI: More fixes for go deps plugin

- cli/bazelisk/bazelisk.go
- cli/cmd/bb/bb.go
- cli/watcher/BUILD
- cli/watcher/watcher.go
- deps.bzl
- go.mod
- go.sum
* Fix run script being deleted before it has a chance to run (since it was written to the cleaned up tempdir)
* Upgrade godemon to get better `.gitignore` behavior (it now respects `.gitignore` files anywhere in the repo, including nested dirs)
* Watch all files under the workspace root, not just the current directory (in the case where BB is invoked from a subdir in the bazel workspace)
---
> CLI: Fix some issues with watch mode

- cli/arg/arg.go
- cli/cmd/bb/BUILD
- cli/cmd/bb/bb.go
- cli/help/BUILD
- cli/help/help.go
- cli/version/version.go
* Running `bb` without subcommand: shows top-level help
* Running `bb help <command>` or `bb <command>` with `-h` or `--help` appearing anywhere in the args: shows help for `<command>`
* Supports `--short` and `--long` options that bazel supports
* Replaces occurrences of `bazel` with `bb` in a few cases
* Shows CLI version info above Bazel version info
Example output
<details>
<summary>bb help</summary>
```
[bb release unknown]
[bazel release 5.3.1]
Usage: bb <command> <options> ...
Available commands:
analyze-profile     Analyzes build profile data.
aquery              Analyzes the given targets and queries the action graph.
build               Builds the specified targets.
canonicalize-flags  Canonicalizes a list of bazel options.
clean               Removes output files and optionally …
```
> CLI: Make help commands and flags work

- enterprise/server/backends/migration_cache/migration_cache.go
- enterprise/server/backends/migration_cache/migration_cache_test.go
Some implementations of FindMissing sort the input slice, which can cause a race condition if both the src and dest cache try to sort at the same time
> Fix race condition in migration cache FindMissing

- server/build_event_protocol/build_event_handler/build_event_handler.go
- server/build_event_protocol/build_event_server/build_event_server.go
- server/remote_cache/hit_tracker/hit_tracker.go
- server/rpc/filters/filters.go
- server/util/log/log.go
1. Add CtxInfo and CtxWarning
2. Add invocation_id to the context and use log.Ctx*** for logging.
3. Add additional logging after we successfully enqueue stats recorder task.
> Improve FinalizeInvocation logging
