enterprise/server/scheduling/priority_task_scheduler/priority_task_scheduler.go

**Related issues**: https://github.com/buildbuddy-io/buildbuddy-internal/issues/2485

Remove verbose logging in priority task scheduler

---

enterprise/server/auditlog/auditlog.go
proto/auditlog.proto
server/interfaces/interfaces.go
server/util/clickhouse/schema/schema.go

Replace method string with a simplified proto enum.

---

app/flame_chart/profile_model.ts

https://github.com/buildbuddy-io/buildbuddy-internal/issues/2499

Support network usage in timing profile

---

enterprise/server/auditlog/auditlog.go
server/buildbuddy_server/buildbuddy_server.go

- Add paging
- Clear out some redundant fields from requests

Audit logging tweaks to support UI:

---

enterprise/server/backends/pebble_cache/pebble_cache.go

Remove unused arg partID in encryptionEnabled

---

server/buildbuddy_server/buildbuddy_server.go

Remove server deps on group_id field outside of request_context.

---

enterprise/server/backends/pebble_cache/pebble_cache.go

remove unused writeCloser in pebble_cache.go

---

enterprise/server/remote_execution/operation/operation.go
enterprise/server/scheduling/priority_task_scheduler/priority_task_scheduler.go

Improve PublishOperation error logging

---

go.mod
server/libmain/BUILD
server/libmain/libmain.go

Hack to make go mod tidy happy when generated protos are symlinked in the source tree.

---

deps.bzl
go.mod
go.sum

Downgrade redsync

---

server/testutil/testenv/testenv.go

Reverts buildbuddy-io/buildbuddy#4344

Revert "testenv: raise default log level to 'warn'"

---

enterprise/server/backends/pebble_cache/BUILD
enterprise/server/backends/pebble_cache/pebble_cache.go

Add some basic tracing to pebble around reading and writing metadata.

Trace pebble reads and writes

---

enterprise/server/backends/pebble_cache/pebble_cache.go

Lower concurrent compactions.

---

enterprise/server/backends/pebble_cache/pebble_cache.go
server/metrics/metrics.go
server/util/approxlru/BUILD
server/util/approxlru/approxlru.go

Instrument pebble cache eviction loop.

---

enterprise/app/api_keys/BUILD
enterprise/app/api_keys/api_keys.css
enterprise/app/api_keys/api_keys.tsx
enterprise/server/test/webdriver/invocation/invocation_test.go

api_keys: make the key hidden by default and provide a copy button

---

enterprise/server/cmd/executor/BUILD
enterprise/server/cmd/executor/executor.go
enterprise/server/cmd/executor/executor_linux.go
enterprise/server/cmd/executor/executor_notlinux.go

Package `server/util/networking` only works on Linux.

cmd/executor: make network config linux exclusive

---

enterprise/server/tasksize/tasksize.go
enterprise/server/tasksize/tasksize_test.go

Set a minimum task size

---

deps.bzl
enterprise/server/cmd/executor/BUILD

UFFD patch: https://github.com/firecracker-microvm/firecracker/compare/main...maggie-lou:firecracker:uffd_user_mode

Upgrade firecracker to v1.4.0 and add patch for uffd

---

enterprise/server/workflow/config/config.go
enterprise/server/workflow/config/config_test.go

Context: https://itbit.slack.com/archives/C04KPGQV0HH/p1690301873856329?thread_ts=1690297248.107469&cid=C04KPGQV0HH

Allow BB Workflows to be triggered by GitHub merge queues

---

enterprise/server/test/webdriver/invocation/invocation_test.go

Fix dev webdriver test

---

server/buildbuddy_server/buildbuddy_server.go

Audit log invocation updates.

---

enterprise/app/auditlogs/auditlogs.tsx
enterprise/server/auditlog/auditlog.go
enterprise/server/backends/userdb/userdb.go
proto/auditlog.proto
server/buildbuddy_server/buildbuddy_server.go
server/interfaces/interfaces.go
server/testutil/testauditlog/testauditlog.go

Enrich some IDs in audit logs with names.

---

enterprise/app/auditlogs/auditlogs.tsx
proto/BUILD
proto/auditlog.proto
server/buildbuddy_server/buildbuddy_server.go

Audit logs for workflow events.

---

proto/BUILD
proto/auditlog.proto
server/buildbuddy_server/buildbuddy_server.go

Audit log user secret changes.

---

BUILD
buildbuddy.yaml

Add a workflow that uses a private version of the RBE ubuntu 20.04 image

---

enterprise/server/remote_execution/containers/podman/podman.go

Also, rename `executor.podman.run_soci_snapshotter` to `executor.podman.run_soci_store` to match and be more accurate. This flag isn't set in dev or prod and I'm pretty sure I'm the only one using it.
**Related issues**: [2523](https://github.com/buildbuddy-io/buildbuddy-internal/issues/2523)

Add a flag that controls the log-level of soci-store

---

enterprise/server/backends/pebble_cache/pebble_cache.go

Raise default eviction rate limit to 300qps.

---

enterprise/app/auditlogs/auditlogs.css
enterprise/app/auditlogs/auditlogs.tsx
enterprise/app/root/root.tsx
enterprise/app/sidebar/sidebar.tsx

Minor audit logs styling tweaks

---

enterprise/server/remote_execution/execution_server/execution_server.go
enterprise/server/scheduling/priority_task_scheduler/priority_task_scheduler.go

Add more logging to diagnose cancelled executions

---

enterprise/tools/rbeperf/rbeperf.go

**Related issues**: https://github.com/buildbuddy-io/buildbuddy-internal/issues/2516

Make rbeperf output remote memory (peak) & CPU usage

---

enterprise/server/backends/pebble_cache/pebble_cache.go
server/metrics/metrics.go
server/remote_cache/hit_tracker/hit_tracker.go

Add metric to track compression broken down by group ID.

---

enterprise/server/remote_execution/blockio/blockio.go
enterprise/server/remote_execution/containers/firecracker/firecracker.go

Fix race condition when merging diff snapshots with uffd enabled

---

enterprise/server/remote_execution/containers/firecracker/BUILD
enterprise/server/remote_execution/uffd/BUILD
enterprise/server/remote_execution/uffd/README.md
enterprise/server/remote_execution/uffd/uffd.go

Implement uffd handler to load memory for a firecracker vm

---

deps.bzl
enterprise/app/auditlogs/BUILD
go.mod
go.sum
server/util/db/BUILD
server/util/db/db.go
server/util/db/db_cgo.go

**Related issues**: Addresses buildbuddy-io/buildbuddy#4349

Recognize postgres duplicate key and deadlock erors

---

enterprise/tools/rbeperf/rbeperf.go

Check if UsageStats is nil before referencing in rbeperf

---

enterprise/server/backends/pebble_cache/pebble_cache.go
enterprise/server/raft/filestore/filestore.go

We need to use the stored anon group ID when doing sample, not the logical "ANON" group ID.

Fix anon group sampling.

---

enterprise/server/backends/pebble_cache/pebble_cache.go

- find missing should check all the chunks
- use findMissing in contains

Make FindMissing chunk aware

---

server/util/clickhouse/schema/schema.go
server/util/clickhouse/schema/schema_test.go

Remove audit log schema flag.

---

enterprise/app/BUILD.bazel
enterprise/app/repo/BUILD
enterprise/app/repo/repo.css
enterprise/app/repo/repo.tsx
enterprise/app/root/BUILD.bazel
enterprise/app/root/root.tsx
server/libmain/libmain.go

There are lots of ways we can make this better, want to just get something in as a starting point.
Screenshots of 3 states below:
State 1: Logged out
State 2: Creation
State 3: Created

Add a basic repo creation UI

---

enterprise/server/backends/pebble_cache/pebble_cache.go

Remove anon group ID workaround and bump min version for AC eviction to 4.

---

app/format/format.tsx
enterprise/app/auditlogs/auditlogs.css
enterprise/app/auditlogs/auditlogs.tsx

* Fix sizing / border issues
* Fix "Last 1 days" in date picker (should say "Today")
**Related issues**: Fixes https://github.com/buildbuddy-io/buildbuddy-internal/issues/2539

Audit log styling fixes

---

server/util/approxlru/approxlru.go

Move eviction rate limiter to the correct place.

---

server/util/healthcheck/healthcheck.go

Add flag to force app to report not ready.

---

enterprise/app/auditlogs/auditlogs.css

Prevent super long "Request" columns from squishing the other columns.
https://github.com/buildbuddy-io/buildbuddy/assets/2414826/036b8be7-c94e-459d-9421-709ce5f2da88

More audit log CSS fixes

---

app/invocation/invocation_execution_table.tsx

The link was wrong :neutral_face: 
**Related issues**: Fixes https://github.com/buildbuddy-io/buildbuddy-internal/issues/2533

Fix action results not showing up in action page

---

server/remote_cache/content_addressable_storage_server/content_addressable_storage_server.go

Downgrade incomplete tree logs to debug.

---

enterprise/server/backends/pebble_cache/pebble_cache.go

Fix pebble cache "metadata mismatch" handling.

---

enterprise/server/backends/pebble_cache/pebble_cache.go

Add flag to disable missing file scan.

---

enterprise/server/cmd/goinit/main.go
enterprise/server/remote_execution/containers/firecracker/firecracker.go
enterprise/server/remote_execution/containers/firecracker/firecracker_test.go
enterprise/server/remote_execution/platform/platform.go
enterprise/server/remote_execution/runner/runner.go
proto/firecracker.proto

Add support for communicating with firecracker dockerd over tcp

---

deps.bzl

pull in the external workspace name for fastcdc patch

---

docs/cli.md
website/src/pages/cli.tsx

CLI: bump version in docs to 5.0.21

---

website/src/pages/remote-cache.tsx

website/remote-cache: update PoP count

---

enterprise/server/backends/authdb/authdb.go
enterprise/server/backends/authdb/authdb_test.go
enterprise/server/backends/userdb/userdb.go
enterprise/server/oidc/oidc.go
enterprise/server/test/webdriver/invocation/invocation_test.go
server/interfaces/interfaces.go

Remove unused write_token auth.

---

.github/workflows/checkstyle.yaml
buildfix.sh
enterprise/server/backends/authdb/BUILD
enterprise/server/backends/userdb/BUILD

Pull in `bb fix -mode diff` fix in checkstyle / buildfix

---

enterprise/app/secrets/BUILD
enterprise/app/secrets/secret_util.ts
enterprise/app/secrets/update_secret.tsx

This allows the logic to be used in other places, like deployment configuration.

Pull libsodium encryption & secret updating into a util library

---

enterprise/app/repo/repo.tsx

Show pending invocation page in repo flow if workflow not created yet

---

enterprise/server/test/webdriver/shortcuts/BUILD

Disable shortcuts_test

---

enterprise/server/backends/pebble_cache/pebble_cache.go
server/metrics/metrics.go

Add metric to track number of applied atime updates.

---

server/util/protofile/protofile.go

Instead of keeping a slice of channels and manually advancing through the slice, use a more conventional model based on a channel of requests (where each request has a response channel).

Refactor protofile fetching logic

---

server/buildbuddy_server/buildbuddy_server.go

Clear out secret value in audit log.

---

enterprise/server/backends/authdb/authdb.go
enterprise/server/backends/authdb/authdb_test.go

Decrypt API key value, if necessary, in GetAPIKey API.

---

proto/remote_execution.proto
server/remote_cache/content_addressable_storage_server/content_addressable_storage_server.go

seems like this became dead in https://github.com/buildbuddy-io/buildbuddy/pull/390

remove unused code i stumbled on while messing with executions code.

---

enterprise/app/auditlogs/auditlogs.tsx
enterprise/server/auditlog/auditlog.go
enterprise/server/backends/authdb/authdb.go
server/interfaces/interfaces.go
server/testutil/testauth/testauth.go
server/util/claims/claims.go

Audit log requests authenticated using API Keys.

---

enterprise/server/usage/usage.go
enterprise/server/usage/usage_test.go
server/tables/tables.go

Add more logging for usage data

---

enterprise/app/repo/repo.tsx

Don't show deployment configuration block if no configuration is requested

---

app/docs/setup_code.tsx
app/invocation/invocation_timing_card.tsx
app/target/action_card.tsx

Before:
After:
After (with cache enabled):

Fix setup code instructions when cache is not configured.

---

server/tables/tables.go

This will avoid having the UPDATE statement flagged as a schema change.

Skip nonce backfill update if nothing to backfill.

---

enterprise/server/remote_execution/execution_server/BUILD
enterprise/server/remote_execution/execution_server/execution_server.go
enterprise/server/usage/usage.go
enterprise/server/usage/usage_test.go
server/build_event_protocol/build_event_handler/BUILD
server/build_event_protocol/build_event_handler/build_event_handler.go
server/build_event_protocol/build_event_handler/build_event_handler_test.go
server/interfaces/interfaces.go
server/remote_cache/hit_tracker/BUILD
server/remote_cache/hit_tracker/hit_tracker.go
server/remote_cache/hit_tracker/hit_tracker_test.go
server/tables/tables.go
server/util/usageutil/BUILD
server/util/usageutil/usageutil.go
tools/cacheload/BUILD
tools/cacheload/cacheload.go

Roll forward #4400: Add support for usage labels

---

enterprise/server/remote_execution/runner/runner.go

Record hit/miss counts based on the end result of `takeWithRetry()`, not each `take()` attempt.

Fix runner pool hit/miss metrics to account for retry

---

enterprise/server/cmd/goinit/main.go
server/util/retry/retry.go

Fix dockerd init timeout

---

app/invocation/BUILD
app/invocation/invocation_artifacts_card.tsx
app/invocation/invocation_target_group_card.tsx
proto/target.proto
server/target/target.go

Render paginated target artifacts card

---

buildpatches/org_google_golang_grpc.patch
deps.bzl
server/util/grpc_client/BUILD
server/util/grpc_client/grpc_client.go

Add logging whenever gRPC sends a keepalive ping

---

app/invocation/BUILD
app/invocation/dense/dense_invocation_overview.tsx
app/invocation/invocation_details_card.tsx
app/invocation/invocation_model.tsx
app/invocation/invocation_overview.tsx
proto/invocation.proto
server/build_event_protocol/event_index/event_index.go
server/buildbuddy_server/buildbuddy_server.go

Fix some target counts displayed in UI when pagination is enabled

---

enterprise/server/backends/pebble_cache/pebble_cache.go

Address feedback in https://github.com/buildbuddy-io/buildbuddy/pull/4527

account for key size in sampling

---

enterprise/server/backends/prom/prom.go

Fix Typo in source metrics in prom.go

---

enterprise/server/backends/pebble_cache/pebble_cache.go

include_metadata_size should default to false

---

server/remote_cache/content_addressable_storage_server/content_addressable_storage_server.go

Downgrade treeCache log to Info.

---

tools/enable_local_firecracker.sh

Set vm.unprivileged_userfaultfd=1 in enable_local_firecracker.sh

---

server/target/target.go

Fix rendering of skipped target listing

---

enterprise/server/backends/prom/prom.go

Fix another typo in prom.go

---

enterprise/app/repo/repo.tsx

Don't render `0` in repo UI if no deployment config is requested

---

enterprise/app/repo/repo.css
enterprise/app/repo/repo.tsx

Add a button to repo flow that takes you to code UI

---

enterprise/app/code/code.tsx

Currently we assume the (sometimes incorrect) default branch name.

Support repo default branch names in code editor

---

enterprise/app/repo/repo.tsx

Remember your most recently selected git scope in repo flow

---

enterprise/app/code/code.tsx

Remove editor call-outs

---

server/target/target.go

e.g. [this link](https://app.buildbuddy.io/invocation/d0ff7f9a-64e8-4035-bb37-4c5f50e552e4?target=%2F%2Fenterprise%2Fserver%2Fbackends%2Fpebble_cache%3Apebble_cache_test) (posted in one of our internal issues) fails with 'status is required when fetching a single target label'. This PR fixes that.

Fix old target links that didn't have the targetStatus param

---

server/util/subdomain/BUILD
server/util/subdomain/subdomain.go
server/util/subdomain/subdomain_test.go

Fix subdomain logic.

---

enterprise/server/util/vsock/vsock.go

Add a timeout when waiting for 'OK' from firecracker guest over vsock.

---

server/buildbuddy_server/buildbuddy_server.go

Paginate invocations by default

---

enterprise/server/backends/pebble_cache/pebble_cache.go

To fix dev migration error unexpected EOF

Use compression.NewZstdDecompressor to decompress when cdc is enabled

---

server/util/bazel_request/bazel_request.go
server/util/usageutil/BUILD
server/util/usageutil/usageutil.go
server/util/usageutil/usageutil_test.go

To be merged after this week's release, to avoid changing too much at once (this week's release also contains https://github.com/buildbuddy-io/buildbuddy/pull/4521)

Start populating usage label columns

---

tools/metrics/grafana/dashboards/buildbuddy.json

Add graphs for
- bytes copied per second
- blobs copied per second
- copy queue size

Add a grafana dashboard for remote cache migration

---

proto/github.proto

These protos contain just the minimal set of request / response data necessary to render the UI. 
This is not an attempt to recreate the entire Github API an all of its functionality, its just the bits that we actually need.

Add protos for GitHub requests we currently make

---

enterprise/server/invocation_stat_service/invocation_stat_service.go

Make sure query is not nil.

---

enterprise/server/githubapp/githubapp.go
proto/buildbuddy_service.proto
server/buildbuddy_server/buildbuddy_server.go
server/interfaces/interfaces.go
server/role_filter/role_filter.go

These just translate back and forth from our minimal protos to actual GitHub API requests.

Implement new Github endpoints on server

---

enterprise/server/oidc/BUILD
enterprise/server/oidc/oidc.go
enterprise/server/remote_execution/execution_server/execution_server.go
enterprise/server/scheduling/scheduler_server/scheduler_server.go
enterprise/server/tasksize/tasksize.go
enterprise/server/usage/usage.go
server/interfaces/interfaces.go
server/nullauth/nullauth.go
server/static/static.go
server/util/capabilities/capabilities.go
server/util/perms/perms.go
server/util/prefix/prefix.go

Don't allow anon access on subdomains.

---

app/auth/auth_service.ts
app/auth/user.ts
enterprise/app/code/code.tsx
enterprise/app/repo/repo.tsx
enterprise/app/settings/user_github_link.tsx
enterprise/app/workflows/github_app_import.tsx
proto/user.proto
server/buildbuddy_server/buildbuddy_server.go

Replace `githubToken` with `githubLinked` boolean

---

enterprise/app/repo/BUILD
enterprise/app/repo/repo.css
enterprise/app/repo/repo.tsx

Depends on https://github.com/buildbuddy-io/buildbuddy/pull/4614

Add GCP link button to repo flow

---

enterprise/app/repo/repo.tsx
enterprise/server/gcplink/gcplink.go

Remove `CLOUDSDK_AUTH_ACCOUNT` as it's not strictly required

---

README.md
app/docs/setup.tsx
app/footer/footer.tsx
app/menu/menu.tsx
docs/contributing.md
docs/enterprise-config.md
docs/enterprise-helm.md
docs/guides.md
docs/introduction.md
docs/troubleshooting.md
website/blog/bazel-remote-cache-debugging.md
website/blog/buildbuddy-v1-2-1-release-notes.md
website/blog/buildbuddy-v1-3-0-release-notes.md
website/blog/buildbuddy-v1-4-0-release-notes.md
website/blog/buildbuddy-v1-5-0-release-notes.md
website/blog/buildbuddy-v1-8-0-release-notes.md
website/blog/buildbuddy-v2-5-0-release-notes.md
website/blog/buildbuddy-v2-7-0-release-notes.md
website/blog/clickhouse-build-trends.md
website/blog/customer-managed-encryption-keys.md
website/blog/introducing-buildbuddy-v2.md
website/blog/keyboard-shortcuts.md
website/blog/postgres-support.md
website/docusaurus.config.js
website/src/pages/contact.tsx
website/src/pages/pricing.tsx

Update community url

---

enterprise/server/gcplink/gcplink.go
enterprise/server/oidc/oidc.go

Also removes now unused email from the method signature

Never store empty refresh token

---

enterprise/server/util/cacheproxy/cacheproxy.go

Fix error handling in cacheproxy.Read

---

enterprise/server/backends/pebble_cache/pebble_cache.go
enterprise/server/backends/pebble_cache/pebble_cache_test.go

Don't use digest size passed from client for decryptor.

---

enterprise/server/backends/userdb/BUILD
enterprise/server/backends/userdb/userdb.go
server/buildbuddy_server/BUILD
server/buildbuddy_server/buildbuddy_server.go
server/util/subdomain/subdomain.go

Don't allow using subdomains in default subdomains list.

---

app/auth/auth_service.ts
app/auth/user.ts
app/router/router.tsx
enterprise/app/org/BUILD
enterprise/app/org/org_access_denied.tsx
enterprise/app/root/BUILD.bazel
enterprise/app/root/root.tsx
proto/config.proto
proto/user.proto
server/buildbuddy_server/buildbuddy_server.go
server/static/BUILD
server/static/static.go
server/util/claims/BUILD
server/util/claims/claims.go

Restrict visible groups when accessing customer subdomain.

---

server/http/interceptors/interceptors.go

Monitor route '/api/v1/metrics' 

---

server/buildbuddy_server/buildbuddy_server.go

Perform the selection logic after filtering the list of groups.

Fix default group selection for subdomains.

---

tools/metrics/grafana/dashboards/buildbuddy.json

Also close the remote migration graphs by default

add dashboard for app versions

---

enterprise/server/raft/bringup/bringup.go
enterprise/server/raft/cache/BUILD
enterprise/server/raft/cache/cache_test.go
enterprise/server/raft/store/store.go
server/util/healthcheck/healthcheck.go

- Fix some race conditions
- Remove boilerplate in raft/cache_test.go
- Run 5 shards

De-flake and re-enable the raft/cache tests

---

server/backends/disk_cache/disk_cache.go

The "could not retrieve filesystem stats" message would keep getting logged while tests are running because we delete the disk cache root dir after each test case. Example: https://app.buildbuddy.io/invocation/480cc8bd-fd25-4d9f-ae0b-b516d44bbe75?target=%2F%2Fenterprise%2Fserver%2Fremote_execution%2Fcontainers%2Ffirecracker%3Afirecracker_test_blockio&targetStatus=6
This PR fixes that.

Fix noisy disk cache logs in tests

---

enterprise/server/raft/cache/cache_test.go

Fix and re-enable TestDistributedRanges

---

package.json
yarn.lock

Remove some unused frontend deps

---

enterprise/app/org/org.css

Small padding tweaks to org subdomain input

---

app/docs/BUILD
app/docs/setup.tsx
app/root/root.tsx
enterprise/app/root/root.tsx

Fix example invocation URL shown on quickstart page.

---

enterprise/server/remote_execution/execution_server/execution_server.go
enterprise/server/remote_execution/platform/BUILD
enterprise/server/remote_execution/platform/platform.go
enterprise/server/remote_execution/platform/platform_test.go
enterprise/server/remote_execution/runner/runner.go
enterprise/server/tasksize/tasksize.go
enterprise/server/tasksize_model/tasksize_model.go

This is a follow up from #4575.

platform: make ParseProperties return error

---

enterprise/server/usage/usage.go
server/tables/tables.go

Switch to table-level locking for writing usage rows, since only one app should be writing to the table at a time anyway.
The SELECT FOR UPDATE does not cause the non-existent row to be locked in postgres, and in mysql it happens to work but I don't know why. Locking non-existent rows generally seems like a bad idea - https://stackoverflow.com/questions/17068686/how-do-i-lock-on-an-innodb-row-that-doesnt-exist-yet

Deflake usage_test_postgres

---

app/router/router.tsx

A person can have access to an invocation w/o having access to the group.

Skip subdomain org access check for invocations.

---

enterprise/app/root/root.tsx

Hide sidebar if user does not have access to subdomain group.

---

enterprise/server/cmd/executor/BUILD
enterprise/server/cmd/executor/executor.go
enterprise/server/remote_execution/platform/BUILD
enterprise/server/remote_execution/platform/platform.go
enterprise/server/scheduling/priority_task_scheduler/BUILD
enterprise/server/scheduling/priority_task_scheduler/priority_task_scheduler.go
server/build_event_protocol/build_event_handler/build_event_handler.go
server/libmain/BUILD
server/libmain/libmain.go
server/rpc/interceptors/interceptors.go
server/util/usageutil/BUILD
server/util/usageutil/usageutil.go
server/util/usageutil/usageutil_test.go

Add client label header

---

app/invocation/child_invocations.tsx

Hide "Bazel commands" list on workflow invocation page if empty

---

server/static/static.go

enable workflow history ui everywhere

---

server/remote_cache/directory_size/directory_size.go

default cache.directory_sizes_enabled to false while i debug stuff.

---

enterprise/server/cmd/ci_runner/main.go

This was probably causing the "invalid username or password" errors.

Fix workflows using stale GitHub app tokens

---

server/build_event_protocol/build_event_handler/build_event_handler.go

fix ctx binding

---

enterprise/server/backends/migration_cache/migration_cache.go

Don't compare number of bytes read from src and dest cache when there are some
errors occur during reading from source cache.

migration cache: only log num of bytes different when src reader is successful

---

enterprise/server/saml/saml.go

Add missing lock around saml provider map.

---

.bazelrc

Use subdomain for buildbuddy builds.

---

server/util/claims/claims.go

Set encryption bit from selected group when authenticating by sub

---

server/remote_cache/content_addressable_storage_server/content_addressable_storage_server.go

Log a more informative message if tree caching ran into a time limit.

---

enterprise/server/remote_execution/execution_server/execution_server.go
enterprise/server/usage/usage.go
server/tables/tables.go

Track CPU nanos in usage

---

server/build_event_protocol/build_event_server/BUILD
server/build_event_protocol/build_event_server/build_event_server.go
server/build_event_protocol/build_event_server/build_event_server_test.go

Fix panic when channel is nil

---

enterprise/server/raft/replica/replica.go
enterprise/server/util/pebble/pebble.go

- Include the `BatchReader` API in our pebble wrapper
- Start and Stop async processing in the replica's `Open()` and `Close()` methods
- Don't update replica in-memory state until the batch has been successfully committed
- Group replica in-memory state functions under a new `loadReplicaState()` function and use this function
- Rename BatchCmd* -> Batch*

Cleanup replica state machinery

---

enterprise/server/backends/pebble_cache/pebble_cache.go

log copy and close error in GetMulti in pebble_cache.go

---

enterprise/server/remote_execution/runner/runner.go

Looks like this err was not being checked, so check it.

Catch error when creating new workspace

---

cli/picker/picker.go
cli/test/integration/cli/cli_test.go

cli/picker: validate flag with HasPrefix instead of Contains

---

enterprise/server/remote_execution/snaploader/BUILD
enterprise/server/remote_execution/snaploader/snaploader.go
server/metrics/metrics.go

[Remote Snapshot Sharing] Add metric for ratio of dirty chunks in a copy-on-write snapshot

---

enterprise/server/cmd/goinit/main.go
enterprise/server/remote_execution/containers/firecracker/firecracker_test.go

Add temporary workaround for NBD stuck request issue

---

dockerfiles/executor_image/Dockerfile

Upgrade to latest available version on Debian 11 repositories.

dockerfile/executor: upgrade podman and skopeo

---

enterprise/server/raft/cache/cache.go
enterprise/server/raft/rbuilder/rbuilder.go
enterprise/server/raft/replica/BUILD
enterprise/server/raft/replica/replica.go
enterprise/server/raft/replica/replica_test.go
enterprise/server/raft/store/BUILD
enterprise/server/raft/store/store.go
enterprise/server/raft/store/store_test.go
proto/raft.proto

Make splits happen via raft command.

Make splits happen via raft command

---

website/src/pages/contact.module.css

Fix horizontal centering of 'request quote' page

---

enterprise/server/invocation_stat_service/invocation_stat_service.go
proto/stats.proto

remove the very-deprecated lookback_window_days

---

enterprise/server/remote_execution/uffd/uffd.go

Fix uffd.Stop() hanging when firecracker initialization fails

---

enterprise/server/backends/authdb/authdb.go

Fix invalid int/bool comparison in impersonation predicates

---

WORKSPACE
cli/test/integration/cli/BUILD
enterprise/server/test/integration/ci_runner/BUILD
enterprise/server/test/integration/workflow/BUILD

Upgrade bb toolchain to get `dockerNetwork=off`

---

app/auth/auth_service.ts

This applies to both the group picker and for creating new orgs.

Start redirecting users to subdomain even on the main site.

---

app/router/router.tsx
enterprise/app/root/root.tsx

Allow access to /join URL even if user does not have access to group.

---

deps.bzl
enterprise/server/cmd/executor/BUILD
enterprise/server/remote_execution/containers/podman/podman.go

**Related issues**: [2570](https://github.com/buildbuddy-io/buildbuddy-internal/issues/2570)

Support specifying which soci-store to run via a flag

---

enterprise/server/remote_execution/containers/firecracker/firecracker.go

Make the firecracker workspace disk size configurable

---

enterprise/server/gcplink/BUILD
enterprise/server/gcplink/gcplink.go
enterprise/server/remote_execution/execution_server/BUILD
enterprise/server/remote_execution/execution_server/execution_server.go

Convert refresh tokens into access tokens for workflow runs when gcp is linked

---

enterprise/server/gcplink/gcplink.go

Correctly parse access_token from refresh response JSON

---

enterprise/server/backends/migration_cache/migration_cache.go

use Info/Warning when no arguments are passed

---

enterprise/server/backends/pebble_cache/pebble_cache.go
server/metrics/metrics.go

Add metrics to track the number of chunks in pebble cache when cdc is enabled

---

enterprise/server/remote_execution/containers/firecracker/BUILD
enterprise/server/remote_execution/containers/firecracker/firecracker_test.go
server/util/networking/networking.go

Using this to try and repro some of the NBD issues with firecracker. For now I am just manually editing the `const` config options, but later we can make these flags and/or structs to make it easier to test various scenarios.

Add a stress test for firecracker

---

cli/picker/picker.go
cli/test/integration/cli/cli_test.go

cli: fix target_pattern_file arg handling for tests too

---

enterprise/server/util/pebble/BUILD
enterprise/server/util/pebble/pebble.go

Alert when pebble db handle leaks

---

enterprise/server/raft/config/config.go
enterprise/server/raft/listener/BUILD
enterprise/server/raft/listener/listener.go
enterprise/server/raft/store/store.go

We had a workaround for this that's no longer necessary.

Wait for shard ready in library

---

enterprise/server/raft/bringup/bringup.go
enterprise/server/raft/driver/driver.go
enterprise/server/raft/replica/replica.go
enterprise/server/raft/store/store.go
enterprise/server/raft/store/store_test.go
proto/raft.proto
proto/raft_service.proto

- More raft renaming
- Remove some unused proto messages
- Rename Add and Remove functions
- Rename SplitCluster to SplitRange
- Rename ListCluster to ListRange

More raft renaming

---

enterprise/server/remote_execution/blockio/blockio.go
enterprise/server/remote_execution/blockio/blockio_test.go

Adds a `Resize()` function which allows right-padding the COWStore with zeroes. This will let us merge the containerfs and scratchfs into a single disk - instead of layering an empty scratchfs onto the containerfs, we can just resize the containerfs.
The right-padding is implemented by just updating a single int (the totalSize), so that the right-padding is purely virtual / lazy. It avoids accessing any of the underlying chunks, which means we preserve our current copy-on-write behavior while also not needing to eagerly fetch any chunks from cache (particularly the last chunk).

Add a resize function to COWStore

---

enterprise/server/raft/bringup/bringup.go
enterprise/server/raft/rangecache/rangecache.go
enterprise/server/raft/rangecache/rangecache_test.go
enterprise/server/raft/rangelease/rangelease.go
enterprise/server/raft/rangelease/rangelease_test.go
enterprise/server/raft/replica/replica.go
enterprise/server/raft/replica/replica_test.go
enterprise/server/raft/sender/sender.go
enterprise/server/raft/store/store.go
enterprise/server/raft/store/store_test.go
proto/raft.proto
server/util/rangemap/rangemap.go

- Make AddPeer call StartShard instead of duplicating that logic
- Rename left->start and right->end

Rename {left,right} -> {start,end} and tiny refactor

---

proto/stats.proto

Proto changes for sub-day trends charts.

---

app/auth/auth_service.ts

This likely explains https://github.com/buildbuddy-io/buildbuddy-internal/issues/2627

Set path on selected group cookie.

---

enterprise/server/remote_execution/blockio/blockio.go
enterprise/server/remote_execution/blockio/blockio_test.go
enterprise/server/remote_execution/nbd/nbdserver/nbdserver_test.go

Also remove the `File` store which is unused.

Add bounds checking for COWStore

---

enterprise/server/backends/migration_cache/migration_cache.go

don't compare num of bytes when double read is off

---

enterprise/server/cmd/goinit/main.go
enterprise/server/remote_execution/nbd/nbdclient/nbdclient.go

Add a flag to goinit to allow mounting a single rootfs disk.

---

enterprise/server/invocation_stat_service/invocation_stat_service.go
server/interfaces/interfaces.go
server/testutil/testolapdb/testolapdb.go
server/util/clickhouse/clickhouse.go
server/util/query_builder/query_builder.go

server-side support for sub-day trends intervals

---

enterprise/server/remote_execution/containers/podman/podman.go
enterprise/server/remote_execution/platform/platform.go

Remove dead platform property podman-enable-image-streaming

---

enterprise/app/trends/common.ts

Floor seconds and milliseconds when computing trend buckets.

---

enterprise/app/trends/BUILD
enterprise/app/trends/common.ts
proto/stats.proto

Stick to even-numbered local hour steps even when dst goes by

---

enterprise/server/invocation_stat_service/invocation_stat_service.go

more intervals means better granularity on more queries.

---

enterprise/app/filter/filter_util.tsx

Just mailing this on its own because it makes it very clear that there is no change to existing behavior.

Parse date URL params as numbers if they're numbers.

---

template-user.bazelrc

Fix API key config in bazelrc template.

---

enterprise/server/githubapp/githubapp.go

Allow template subdirectory paths to contain dashes and underscores

---

enterprise/server/backends/pebble_cache/pebble_cache_test.go
enterprise/server/util/chunker/chunker.go

Address a comment missed in https://github.com/buildbuddy-io/buildbuddy/pull/4784

CloseWithErr on cancelation

---

enterprise/server/raft/driver/driver.go
enterprise/server/raft/driver/driver_test.go
enterprise/server/raft/store/store.go
proto/raft.proto

Remove some clumsy protos and simplify things.

Remove RangeUsage and NodeReplica protos; simplify usage tracking

---

enterprise/server/raft/driver/driver.go
enterprise/server/raft/driver/driver_test.go
enterprise/server/raft/store/store.go
proto/raft.proto

Record last observation timestamp in driver

---

app/format/format.tsx
enterprise/app/filter/filter.tsx
enterprise/app/filter/filter_util.tsx

support rendering (but not picking) sub-day ranges in date picker

---

enterprise/app/auditlogs/auditlogs.tsx
enterprise/app/sidebar/sidebar.tsx

fix audit log page title and sidebar hover title to match other pages

---

enterprise/server/backends/migration_cache/migration_cache.go

do not log double writer

---

enterprise/server/backends/pebble_cache/pebble_cache.go
enterprise/server/util/chunker/BUILD
enterprise/server/util/chunker/chunker.go

Adding more context to returned error in chunker and pebble cache

---

tools/metrics/grafana/dashboards/buildbuddy.json

Actually filter Disk Cache Avg Last Evicted Age by cache name

---

enterprise/server/backends/pebble_cache/pebble_cache.go

commit then close

---

enterprise/server/clientidentity/BUILD
enterprise/server/clientidentity/clientidentity.go
enterprise/server/clientidentity/clientidentity_test.go
enterprise/server/cmd/executor/BUILD
enterprise/server/cmd/executor/executor.go
enterprise/server/cmd/server/BUILD
enterprise/server/cmd/server/main.go
enterprise/server/iprules/iprules.go
server/environment/environment.go
server/interfaces/interfaces.go
server/real_environment/real_environment.go
server/rpc/interceptors/interceptors.go

Add service to sign & verify client identity for trusted services.

---

app/router/router.tsx
enterprise/app/trends/BUILD
enterprise/app/trends/cache_chart.tsx
enterprise/app/trends/percentile_chart.tsx
enterprise/app/trends/simple_trends_tab.tsx
enterprise/app/trends/trends.css
enterprise/app/trends/trends.tsx
enterprise/app/trends/trends_chart.tsx
enterprise/app/trends/trends_model.ts
proto/config.proto
server/static/static.go

Again, fairly big, fairly repetitive, but hopefully with a (hopefully evident) minimal blast radius.
Also fixing some small things i missed in the "new" trends UI that i now regret starting before going down this rabbit hole.

allow selecting date ranges by clicking and dragging on trends charts.

---

app/router/router.tsx
enterprise/app/trends/simple_trends_tab.tsx
enterprise/app/trends/trends.css
enterprise/app/trends/trends.tsx

No meaningful behavior change here because the dates take precedence.  It was just annoying me.

blow away "days" url param when zooming

---

enterprise/server/sociartifactstore/sociartifactstore.go

**Related issues**: https://github.com/buildbuddy-io/buildbuddy-internal/issues/2673

Log some more stuff about https://github.com/buildbuddy-io/buildbuddy-internal/issues/2673

---

app/components/popup/popup.css
app/root/root.css
enterprise/app/trends/trends.css
enterprise/app/trends/trends.tsx

use a scrim for loading state on trends page

---

tools/metrics/grafana/dashboards/buildbuddy.json

filter pebble op rate latency graph with cache_name

---

tools/metrics/grafana/dashboards/mac.json

Add mac specific grafana dashboard.

---

.bazelrc

Use BLAKE3 function internally

---

tools/metrics/grafana/dashboards/buildbuddy.json
tools/metrics/grafana/dashboards/mac.json

- Fix Node Overview labels
- Fix pool graphs

Mac dashboard fixes.

---

enterprise/server/cmd/executor/BUILD
enterprise/server/cmd/executor/executor.go
enterprise/server/remote_execution/runner/runner.go

Add a flag to clear the build root dir on startup

---

enterprise/server/remote_execution/containers/firecracker/README.md

Add notes on firecracker VM SSH access

---

enterprise/app/trends/common.ts

simplify some calls to round off dates

---

enterprise/app/iprules/iprules.css
enterprise/app/iprules/iprules.tsx

Add "bulk add" dialog for ip rules.

---

enterprise/server/backends/migration_cache/config.go
enterprise/server/backends/migration_cache/migration_cache.go
enterprise/server/backends/migration_cache/migration_cache_test.go

Add an option in migration config to allow for multiple workers to copy in parallel

---

server/util/claims/claims.go

Make jwt duration configurable.

---

enterprise/server/remote_execution/vbd/BUILD
enterprise/server/remote_execution/vbd/vbd.go
enterprise/server/remote_execution/vbd/vbd_test.go

Add FUSE-based Virtual Block Device package

---

enterprise/server/remote_execution/containers/firecracker/firecracker.go

firecracker: clean up unused externalJailerCmd

---

app/invocation/invocation_model.tsx

remove toolLogs, we already have buildToolLogs

---

enterprise/server/backends/pebble_cache/pebble_cache.go

Don't write the chunk in the cache if it already exists.

don't write the chunk to the cache if it already exists

---

enterprise/server/backends/pebble_cache/pebble_cache.go

There are a few places I missed in https://github.com/buildbuddy-io/buildbuddy/pull/4460

Create Iterator after Lock

---

enterprise/server/backends/pubsub/pubsub.go
enterprise/server/remote_execution/execution_server/execution_server.go

Expire pubsub streams sooner after actions are done.

---

enterprise/server/sociartifactstore/sociartifactstore.go

**Related issues**: https://github.com/buildbuddy-io/buildbuddy-internal/issues/2673

Don't keep a reference to cache in sociartifactstore.go, grab it from env instead

---

enterprise/server/remote_execution/containers/firecracker/firecracker.go

It seems error prone to continue with cleanup if firecracker has not yet exited - it may still be using some of the resources we are trying to clean up (networking etc.)

Wait for firecracker process to exit after calling StopVMM

---

docs/workflows-config.md

Also add docs for merge queue support.

workflows: add website docs for new `merge_with_base` option

---

enterprise/server/sociartifactstore/sociartifactstore.go

Don't single-flight-dedupe reading soci artifacts from cache

---

tools/cas/cas.go

cas tool: preserve digest function from digest arg

---

tools/metrics/grafana/dashboards/buildbuddy.json
tools/metrics/grafana/dashboards/workflow.json

**Related issues**: Add grafana workflow dashboard configmap:  https://github.com/buildbuddy-io/buildbuddy-internal/pull/2720/files
* Think I need to merge this PR first

[Remote Snapshot] Add workflow-related graphs to grafana

---

app/invocation/invocation_action_card.tsx
app/invocation/invocation_model.tsx
server/bytestream/bytestream.go
server/remote_cache/digest/digest.go
server/remote_cache/digest/digest_test.go

This makes blake3 action results viewable and all files downloadable.

Ensure client sets the digest type when necessary

---

app/service/rpc_service.ts

Include cookies when communicating with regional server

---

app/auth/auth_service.ts

Preserve path/query params when switching subdomains for impersonation.

---

enterprise/server/raft/driver/driver.go

Fixes: https://github.com/buildbuddy-io/buildbuddy-internal/issues/2709

Fix data race

---

enterprise/server/remote_execution/containers/firecracker/firecracker_test.go
enterprise/server/remote_execution/uffd/uffd.go

To reduce the number of round trips, when the UFFD handler receives a page fault and fetches a chunk from the store to serve the page fault, we copy the entire chunk as opposed to just 1 page.
We had a bug where sometimes a chunk would map to addresses that fell out of the memory range allocated to the VM. The handler would get errno(2) and fail.
Ex. Let's say the VM's entire memory range is 100B from addresses 0 - 99. The uffd object will be registered for addresses 0-99. If one chunk is 200B, there will be an error when we try to copy to addresses 100-200.

[UFFD] Fix bug where we try to map an address outside of the VM's memory range

---

proto/BUILD
proto/execution_graph.proto

mirror over bazel protos for execution graph.

---

server/http/interceptors/interceptors.go
server/rpc/interceptors/interceptors.go
server/util/clientip/clientip.go

Needed to handle the UI requests that go through the LB (subdomains).

Check X-Forwarded-For header in http requests.

---

enterprise/server/raft/client/client.go
enterprise/server/raft/nodeliveness/nodeliveness.go
enterprise/server/raft/rangelease/BUILD
enterprise/server/raft/rangelease/rangelease.go
enterprise/server/raft/rangelease/rangelease_test.go
proto/raft.proto

Publish node liveness updates on a channel (and correct a find/replace error)

---

app/invocation/invocation_suggestion_card.tsx

New mnemonic that we want to adjust.

Add `AppleLipo` to `IOS_EXECUTION_FILTER`

---

.bazelrc
template-user.bazelrc

This reverts commit fd496a108534616525a730d38a5268a510116bf2.

Revert "bazelrc: support windows specific configs (#4902)"

---

enterprise/tools/rbeperf/rbeperf.go

Support using custom container images in rbeperf

---

enterprise/server/remote_execution/containers/firecracker/firecracker_test.go

Fix TestSnapshotAndResume unmounting in-use VBD device

---

enterprise/server/remote_execution/containers/firecracker/firecracker.go

[FC] Add additional networking cleanup failure log

---

server/resources/resources.go

Use total RAM instead of free RAM for resource estimation limits

---

enterprise/server/remote_execution/runner/runner.go
enterprise/server/scheduling/priority_task_scheduler/BUILD
enterprise/server/scheduling/priority_task_scheduler/priority_task_scheduler.go

This is now the default, and we don't explicitly enable it anymore.

Clean up context_based_shutdown flag

---

enterprise/server/remote_execution/runner/runner.go

In some of our configs, we're relying on the value 0 to mean "use the default value." But we have a bug where we're actually treating 0 literally as the memory limit, meaning that any runners where we measured memory > 0 cannot be pooled. This PR fixes that.

Fix `max_runner_memory_usage_bytes` flag default logic

---

enterprise/server/remote_execution/containers/docker/docker_test.go

Deflake docker_test even more

---

app/invocation/invocation.tsx

s/ == / === /g
Expect this to be no-op, but help with consistency in the long run.

app/invocation: ensure we are comparing values

---

enterprise/server/backends/pebble_cache/BUILD
enterprise/server/backends/pebble_cache/pebble_cache.go

delete unused var and method in pebble cache

---

enterprise/server/gcplink/BUILD
enterprise/server/gcplink/gcplink.go
proto/BUILD
proto/buildbuddy_service.proto
proto/gcp.proto
server/buildbuddy_server/BUILD
server/buildbuddy_server/buildbuddy_server.go
server/role_filter/role_filter.go

This will allow the user to pick which project they'd like to deploy into

Add an endpoint for fetching projects for linked gcp account

---

.github/workflows/checkstyle.yaml
WORKSPACE

See
https://github.com/golang/go/issues?q=milestone%3AGo1.21.2+label%3ACherryPickApproved
for more information.

Upgrade go sdk to 1.21.2

---

.github/workflows/checkstyle.yaml
WORKSPACE

upgrade Go sdk to 1.21.3

---

proto/BUILD
proto/scheduler.proto

Proto changes for lease retry

---

enterprise/server/remote_execution/containers/firecracker/firecracker.go

Fix race condition in monitorVMContext

---

enterprise/server/remote_execution/copy_on_write/copy_on_write.go

Missed this in: https://github.com/buildbuddy-io/buildbuddy/pull/4920

[VBD] Fix missing lock in COWStore

---

enterprise/server/cmd/ci_runner/main.go
enterprise/server/remote_execution/platform/BUILD
enterprise/server/remote_execution/platform/platform.go
server/interfaces/interfaces.go

Add client identity to workflows.

---

enterprise/server/sociartifactstore/sociartifactstore.go

**Related issues**: https://github.com/buildbuddy-io/buildbuddy-internal/issues/2673

Remove debugging logs added for go/b/2673

---

enterprise/server/clientidentity/BUILD
enterprise/server/clientidentity/clientidentity.go

Sshhhhh, it's a secret.

---

enterprise/server/backends/pebble_cache/pebble_cache.go
enterprise/server/backends/pebble_cache/pebble_cache_test.go

Add active_key_version as a pebble option.

---

enterprise/server/cmd/ci_runner/BUILD
enterprise/server/cmd/ci_runner/main.go

Set client identity header for workflow outer invocation too.

---

enterprise/server/remote_execution/snaploader/snaploader.go

Add a few logs for remote snapshot fetching

---

enterprise/server/remote_execution/containers/podman/podman.go

This allows using `podman.enable_stats` (to measure task size) on Ubuntu 22.04+ (e.g. locally), since podman uses cgroup v2.

podman: support cgroup v2 for `podman.enable_stats`

---

enterprise/server/remote_execution/snaploader/snaploader.go

This is a little more convenient than Grafana for now, esp. during testing. We can remove these later once we've got things more optimal.

Add debug logs for bytes/chunks dirtied

---

enterprise/server/usage/usage.go
enterprise/server/usage/usage_test.go
server/tables/tables.go

**Related issues**: https://github.com/buildbuddy-io/buildbuddy-internal/issues/2740

Add UsageID field and start populating it

---

enterprise/server/scheduling/scheduler_server/scheduler_server.go
server/remote_cache/byte_stream_server/byte_stream_server.go

Clean up minInt implementations in favor of builtin min

---

enterprise/server/cmd/server/BUILD
enterprise/server/cmd/server/main.go
enterprise/server/server_notification/BUILD
enterprise/server/server_notification/server_notification.go
enterprise/server/server_notification/server_notification_test.go
proto/BUILD
proto/server_notification.proto
server/environment/environment.go
server/interfaces/interfaces.go
server/real_environment/real_environment.go

The initial use case will be to refresh cached IP rules whenever they are updated.
I'm not in love with the name of the package/service, naming suggestions are welcome.

Add service for broadcasting messages to other apps.

---

enterprise/app/iprules/iprules.css
enterprise/app/iprules/iprules.tsx
enterprise/server/iprules/BUILD
enterprise/server/iprules/iprules.go

Refresh cached IP rules whenever changes are made in the UI.

---

enterprise/app/iprules/iprules.css

Vertically center IP rules label

---

enterprise/server/backends/pebble_cache/pebble_cache.go
enterprise/server/backends/pebble_cache/pebble_cache_test.go
server/metrics/metrics.go

Revive Tyler's PR https://github.com/buildbuddy-io/buildbuddy/pull/4533/.
On top of that, generate samples in a seperate go routine.

Pebble Cache: sample in a queue

---

enterprise/server/backends/userdb/BUILD

Fix recycling key for userdb_test_postgres

---

enterprise/server/remote_execution/commandutil/BUILD
enterprise/server/remote_execution/commandutil/commandutil.go
enterprise/server/remote_execution/commandutil/commandutil_test.go
enterprise/server/remote_execution/commandutil/commandutil_unix_test.go
enterprise/server/remote_execution/commandutil/commandutil_windows_test.go
enterprise/server/remote_execution/container/BUILD
enterprise/server/remote_execution/container/container.go
enterprise/server/remote_execution/container/container_test.go
enterprise/server/remote_execution/containers/bare/bare.go
enterprise/server/remote_execution/containers/docker/BUILD
enterprise/server/remote_execution/containers/docker/docker.go
enterprise/server/remote_execution/containers/docker/docker_test.go
enterprise/server/remote_execution/containers/firecracker/BUILD
enterprise/server/remote_execution/containers/firecracker/firecracker.go
enterprise/server/remote_execution/containers/firecracker/firecracker_test.go
enterprise/server/remote_execution/containers/podman/BUILD
enterprise/server/remote_execution/containers/podman/podman.go
enterprise/server/remote_execution/containers/podman/podman_test.go
enterprise/server/remote_execution/containers/sandbox/sandbox.go
enterprise/server/remote_execution/runner/runner.go
enterprise/server/remote_execution/vmexec_client/BUILD
enterprise/server/remote_execution/vmexec_client/vmexec_client.go
enterprise/server/vmexec/BUILD
enterprise/server/vmexec/vmexec_test.go

Makes more sense to me, LMK if you disagree

Move Stdio from container.go to commandutil.go

---

website/src/components/rbe/rbe.module.css

Fix jumpy numbers when counting up on small screen

---

enterprise/server/remote_execution/snaploader/snaploader.go

This behavior was accidentally removed in #4809. We should probably reinstate it before snapshot sharing is officially enabled, because it's causing greater load on the executors

[SS] If snapshot sharing is disabled, don't compute full digests for artifacts to save computation

---

server/util/claims/BUILD
server/util/claims/claims.go
server/util/claims/claims_test.go

Add support for JWT key rotation.

---

enterprise/server/remote_execution/containers/podman/podman.go

These exit codes happen when the requested command is not executable / found within the podman container, one cause of which is if the image isn't streamed correctly.

Add a log statement when podman exits with code 126/127

---

enterprise/server/remote_execution/containers/firecracker/firecracker.go

Fix error handling in masquerading init logic

---

enterprise/server/remote_execution/container/container.go
enterprise/server/remote_execution/container/container_test.go
enterprise/server/remote_execution/runner/runner.go

Remove unused function parameter in GetPullCredentials()

---

enterprise/server/cmd/smash/BUILD
enterprise/server/cmd/smash/smash.go

Stream writes when the blob size is big.

---

enterprise/server/raft/client/client.go
enterprise/server/raft/replica/replica.go

Fixes: https://github.com/buildbuddy-io/buildbuddy-internal/issues/2801
//enterprise/server/raft/store:store_test                                PASSED in 19.3s
Stats over 800 runs: max = 19.3s, min = 0.3s, avg = 1.1s, dev = 1.9s

Fix raft race condition and check before closing nil channel

---

app/invocation/invocation_query_graph_card.tsx

Don't render `\n` in graph summary

---

tools/metrics/grafana/dashboards/buildbuddy.json

Add resample, evict, bytes deleted per sec graph for cache

---

tools/metrics/grafana/dashboards/buildbuddy.json
tools/metrics/grafana/dashboards/nodes.json

Move per-node dashboards out of main bb dashboard.

move per-node dashboards out of main bb dashboard

---

enterprise/server/remote_execution/containers/firecracker/BUILD

Fix firecracker blockio build target

---

enterprise/server/backends/migration_cache/config.go
enterprise/server/backends/migration_cache/migration_cache.go

add active key version to migration config

---

enterprise/server/backends/pebble_cache/pebble_cache.go

let generateSampleForEviction sleep for some time if the partition is not that full

---

enterprise/dockerfiles/ci_runner_image/Dockerfile
enterprise/server/remote_execution/platform/platform.go
enterprise/server/workflow/service/service.go

Run firecracker workflows with `init-dockerd: true`

---

enterprise/app/usage/usage.tsx

Add cached execution duration to usage page

---

enterprise/server/cmd/ci_runner/main.go

Expose convenience env vars in CI runner

---

enterprise/server/util/vfs_server/vfs_server_test.go

Disable vfs_server TestGetLayout

---

enterprise/server/backends/pebble_cache/pebble_cache.go

Don't apply migration rate limiter to stale keys.

---

proto/firecracker.proto
proto/scheduler.proto

Proto changes for git ref-based snapshot matching

---

enterprise/server/cmd/ci_runner/main.go

Send client identity header in BES stream too.

---

deps.bzl

Want to let this run for at least a week with the race detector.

Upgrade soci-store to v0.0.11 (with background fetching)

---

buildbuddy.yaml
tools/checkstyle/BUILD
tools/checkstyle/checkstyle.sh
tools/prettier/prettier.sh

Not removing these from GH actions or adding this to branch protection rules yet - want to make sure we iron out any bugs first.

Add initial checkstyle workflow with gofmt, go deps, and prettier

---

buildbuddy.yaml
deps.bzl
tools/checkstyle/BUILD
tools/checkstyle/checkstyle.sh
tools/clang-format/BUILD
tools/clang-format/build_static.sh
tools/clang-format/clang-format.sh

Also makes the output format a little nicer, and speeds up checks by running them all in parallel.

Add bb fix and clang-format to checkstyle workflow

---

enterprise/server/backends/pebble_cache/pebble_cache.go
enterprise/server/raft/filestore/filestore.go

Add temporary debug logs to help root cause missing file errors.

---

app/invocation/BUILD
app/invocation/invocation_action_card.tsx
app/invocation/invocation_model.tsx

Send digest function to server when requesting directory sizes

---

enterprise/server/backends/pebble_cache/pebble_cache.go

During migrations we will have two instances of pebble cache running. Adding the
name to the logs make it easier to debug.

add cache name in logs

---

enterprise/server/scheduling/scheduler_server/scheduler_server.go

Today we only enforce it when there's some activity on the stream.

Enforce lease expiration on the server.

---

enterprise/server/backends/pebble_cache/pebble_cache.go

Remove dev pebble debug logs.

---

enterprise/server/backends/distributed/distributed.go

Don't hold lock while processing handoffs.

---

enterprise/server/util/cacheproxy/cacheproxy.go
server/util/ioutil/ioutil.go

Simplification of CacheProxy.Read func.

---

tools/metrics/grafana/dashboards/buildbuddy.json

Don't sum redis connection count.

---

enterprise/server/remote_execution/snaputil/snaputil.go

Set compressor in snaputil.GetArtifact

---

website/src/pages/privacy.md

This is needed for scope approval.

Add Google APIs section to privacy policy

---

enterprise/server/backends/distributed/distributed.go
server/util/log/log.go

This will make it easy to correlate all the logs for a single request.

Use context logs in distributed cache.

---

enterprise/server/backends/pebble_cache/pebble_cache.go

add a db flush right after wait group finished

---

enterprise/app/repo/repo.css
enterprise/app/repo/repo.tsx

Repo flow styling tweaks

---

enterprise/tools/vmstart/vmstart.go

`log.Fatalf` is preventing `Remove()` from getting called, leaving trash everywhere.

vmstart: fix error handling

---

enterprise/server/tasksize/tasksize.go
enterprise/server/tasksize/tasksize_test.go

**Related issues**: Fixes https://github.com/buildbuddy-io/buildbuddy-internal/issues/2861

Use bazel's test size values as minimum test task size

---

enterprise/server/backends/migration_cache/migration_cache.go

Otherwise, Close() will wait forever for decompression to be done.

Don't create decompressor if destReader returns an error.

---

enterprise/server/workflow/service/service.go

* Reduce noise (don't log "polling" msg every 1s)
* Add execution ID and invocation ID to context

Improve ExecuteWorkflow logs

---

enterprise/server/backends/pebble_cache/pebble_cache_test.go
server/remote_cache/byte_stream_server/byte_stream_server_test.go
server/testutil/testdigest/testdigest.go

Move compressibleBlobOfSize into testdigest to make it re-usable.

refactor - move compressibleBlobOfSize into testdigest

---

.bazelrc
buildbuddy.yaml

Move workflow tag metadata into .bazelrc

---

enterprise/server/remote_execution/snaploader/snaploader.go

Add a log when we successfully upload a snapshot

---

server/remote_cache/byte_stream_server/byte_stream_server.go

Simplify ByteStream Read loop.

---

enterprise/server/vmexec/vmexec.go

Credit to @jdhollen for noticing this

Fix missing error handling in ExecStreamed

---

.github/workflows/checkstyle.yaml
WORKSPACE

Fixed a few Windows path/filepath CVEs
References:
https://github.com/golang/go/issues?q=milestone%3AGo1.21.4+label%3ACherryPickApproved

go_sdk: upgrade to 1.21.4

---

enterprise/server/remote_execution/containers/podman/podman.go

Fix NPE accessing podmanVersion when secondary network is enabled

---

tools/checkstyle/checkstyle.sh

Last thing needed before we can get rid of the GH action.

Add ./buildfix.sh tip at end of checkstyle

---

docs/config-auth.md

Clean up SAML docs

---

server/util/db/BUILD
server/util/db/db.go

Fixes the issue that GORM logs are logged to stderr unstructured.

Use zerolog for GORM logging

---

enterprise/server/remote_execution/containers/podman/BUILD
enterprise/server/remote_execution/containers/podman/podman.go

This reverts commit 07a7a868a22d18a60bf1ad05ca756501a4a17859.

Revert "Optimize podman IsImageCached (#5128)"

---

enterprise/server/remote_execution/filecache/filecache.go

This improves performance for both hardlinks and clones.
```
tylerw@lunchbox:~/buildbuddy$ blaze run enterprise/tools/reflinker:reflinker -- -n 1000 -dir /home/tylerw/refcountestmount/work/ -n 10000 --executor.enable_fastcopy_reflinking=false -auth=false
2023/11/08 12:13:48.466 INF Finished 10000 loops in 113.825685ms
tylerw@lunchbox:~/buildbuddy$ blaze run enterprise/tools/reflinker:reflinker -- -n 1000 -dir /home/tylerw/refcountestmount/work/ -n 10000 --executor.enable_fastcopy_reflinking=true -auth=false
2023/11/08 12:13:57.287 INF Finished 10000 loops in 260.090144ms
tylerw@lunchbox:~/buildbuddy$
tylerw@lunchbox:~/buildbuddy$ blaze run enterprise/tools/reflinker:reflinker -- -n 1000 -dir /home/tylerw/refcountestmount/work/ -n 10000 --executor.enable_fastcopy_reflinking=false …
```

Be judicious about filecache locking

---

enterprise/server/remote_execution/containers/podman/BUILD
enterprise/server/remote_execution/containers/podman/podman.go

This reverts commit 67210ffd3136b01304a7126afbdfe0a42e3fbfd9.
Commit 9df3fd247da3fe26efcb9af2752d68908a472ca4 contains just the changes compared to the original PR.

Roll-forward "Optimize podman IsImageCached (#5128)"

---

docs/config-auth.md

More SAML config cleanup

---

app/invocation/invocation_breakdown_card.tsx

Add `Action dependency checking` to execution breakdown

---

cli/cache_proxy/cache_proxy.go
enterprise/server/cmd/executor/BUILD
enterprise/server/cmd/executor/executor.go
enterprise/server/raft/client/BUILD
enterprise/server/raft/client/client.go
enterprise/server/remote_execution/containers/podman/BUILD
enterprise/server/remote_execution/containers/podman/podman.go
enterprise/server/scheduling/scheduler_server/BUILD
enterprise/server/scheduling/scheduler_server/scheduler_server.go
enterprise/server/test/integration/remote_execution/remote_execution_test.go
enterprise/server/util/cacheproxy/cacheproxy.go
server/testutil/testgrpc/testgrpc.go
server/util/grpc_client/BUILD
server/util/grpc_client/grpc_client.go
server/util/healthcheck/BUILD
server/util/healthcheck/healthcheck.go

Create multiple gRPC connections by default when dialing targets.

---

enterprise/server/raft/leasekeeper/leasekeeper.go
enterprise/server/raft/listener/BUILD
enterprise/server/raft/listener/listener.go
enterprise/server/raft/rangelease/rangelease.go
enterprise/server/raft/rangelease/rangelease_test.go
enterprise/server/raft/store/store.go

- Use the provided logger
- Blocking channel
- Pass logger when creating leasekeeper
- BF

Use the named sub logger in more places

---

docs/cli.md
website/src/pages/cli.tsx

doc: document bb cli 5.0.23 release

---

enterprise/app/login/login.tsx

With this change:
- If the user visits `app.buildbuddy.io`, the user will see the current login screen.
- If the user visits `acme.buildbuddy.io` or `app.buildbuddy.io/join/acme`:
- If acme has SSO enabled, they'll only see the SSO button with the slug pre-filled.
- If acme doesn't have SSO enabled, they'll only see the non-SSO buttons.

Streamline login flow for subdomains

---

enterprise/server/scheduling/task_router/task_router.go
enterprise/server/test/integration/task_router/task_router_test.go

When snapshot sharing is enabled, we want workflows to be matched to snapshots that recently ran the workflow associated with the workflow's git branch. GIT_BRANCH is part of env vars, not platform, so we need a change to add that in to the routing key.

Add GIT_BRANCH to workflow task routing key

---

server/remote_cache/content_addressable_storage_server/BUILD
server/remote_cache/content_addressable_storage_server/content_addressable_storage_server.go
server/remote_cache/content_addressable_storage_server/content_addressable_storage_server_test.go

Fix nil panic in CAS server if an empty digest is in the batch.

---

enterprise/server/raft/client/client.go
enterprise/server/raft/rbuilder/rbuilder.go
enterprise/server/raft/replica/replica.go
proto/raft.proto

Add support for post-commit hooks

---

enterprise/server/remote_execution/commandutil/commandutil_unix.go

Fixes a bug that the `docker` group was not effective when running as the "buildbuddy" user in the CI runner image, so the `buildbuddy` user could not run `docker login`.
Before: `id` command shows `uid=1000(buildbuddy) gid=1000(buildbuddy) groups=1000(buildbuddy)`
After: `id` command shows `uid=1000(buildbuddy) gid=1000(buildbuddy) groups=1000(buildbuddy),27(sudo),999(docker)`
This makes firecracker match the behavior of docker/podman when setting `--user` without explicitly setting the `gid` part of the user, i.e. `--user=buildbuddy` rather than `--user=buildbuddy:buildbuddy`
Also verified that the permissions issue with `docker login` is resolved.

Fix supplementary unix group IDs not being applied in SetCredential

---

enterprise/server/remote_execution/containers/podman/podman.go

`podman version` can output a warning message when it's first run:
```
$ podman run --rm -it --privileged --entrypoint bash \
gcr.io/flame-public/buildbuddy-executor-enterprise:enterprise-v2.29.2 \
-c 'podman version --format="{{.Client.Version}}"'
ERRO[0000] Failed to built-in GetDriver graph btrfs /var/lib/containers/storage 
4.6.2
```
This message is being printed to stderr:
```
$ podman run --rm -it --privileged --entrypoint bash \
gcr.io/flame-public/buildbuddy-executor-enterprise:enterprise-v2.29.2 \
-c 'podman version --format="{{.Client.Version}}" 2>/dev/null'
4.6.2
```
So, this PR makes sure we only try to parse the version from stdout.

Fix podman version parsing

---

enterprise/server/remote_execution/containers/firecracker/BUILD

firecracker: improve linux-only setup

---

enterprise/server/scheduling/scheduler_server/scheduler_server.go

In the follow up release we can start sending lease_id as reconnect token to executors and stop storing reconnect token.

Accept lease ID as reconnect token.

---

enterprise/server/remote_execution/snaploader/snaploader.go
server/metrics/metrics.go

[SS] Fix snapshot chunk source metric

---

app/auth/auth_service.ts

Fixes https://github.com/buildbuddy-io/buildbuddy-internal/issues/2862

Include fragment in impersonation redirect.

---

server/util/canary/canary.go
server/util/grpc_client/BUILD
server/util/grpc_client/grpc_client.go

Warn about slow streaming RPC setup.

---

docs/cli.md
website/src/pages/cli.tsx

Includes the `common` parsing fix

cli: update docs for v5.0.25

---

app/invocation/invocation_action_card.tsx
app/invocation/invocation_action_input_node.tsx
proto/cache.proto
server/remote_cache/directory_size/directory_size.go

show total file count on directories in invocation action card.

---

enterprise/tools/replay_action/replay_action.go

- use source API key if target API key is not set (as per documentation)
- specify the digest function

replay_action fixes

---

enterprise/tools/replay_action/replay_action.go

 Require target_api_key if source_api_key is set.

---

enterprise/server/remote_execution/copy_on_write/BUILD
enterprise/server/remote_execution/copy_on_write/copy_on_write.go
server/metrics/metrics.go

This should help us figure out whether we're properly unmapping chunks.

Add gauge metric for currently memory-mapped bytes

---

app/format/format.tsx
app/invocation/BUILD
app/invocation/invocation_action_input_node.tsx
app/invocation/invocation_artifacts_card.tsx
app/invocation/invocation_cache_card.tsx
app/invocation/invocation_details_card.tsx
app/invocation/invocation_execution_card.tsx
app/invocation/invocation_execution_table.tsx
app/invocation/invocation_overview.tsx
app/invocation/invocation_raw_logs_card.tsx
app/invocation/invocation_target_group_card.tsx
app/invocation/invocation_targets_card.tsx

Adds comma rendering to a bunch of counts all over our UI.

Commas everywhere

---

app/invocation/invocation_cache_card.tsx
enterprise/app/history/history_invocation_stat_card.tsx

Missed a couple, and fix up some whitespace.

More commas

---

server/remote_cache/cachetools/cachetools.go

Remove unused opts and return value from cachetools.GetBlob

---

enterprise/server/raft/nodeliveness/nodeliveness.go
enterprise/server/raft/store/BUILD
enterprise/server/raft/store/store.go

Pretty much what it says on the tin: do this so things don't get broken if splits half-fail.

Use 2PC for splits to ensure consistency

---

enterprise/server/cmd/server/BUILD
enterprise/server/cmd/server/main.go
enterprise/server/scim/BUILD
enterprise/server/scim/scim.go
enterprise/server/scim/scim_test.go
server/environment/environment.go
server/interfaces/interfaces.go
server/libmain/libmain.go
server/real_environment/real_environment.go

Just adds the http handlers & service. No implementations yet.

SCIM scaffolding

---

server/remote_cache/cachetools/BUILD
server/remote_cache/cachetools/cachetools.go
server/util/retry/BUILD
server/util/retry/retry.go
server/util/rpcutil/BUILD
server/util/rpcutil/rpcutil.go

Fixes https://github.com/buildbuddy-io/buildbuddy-internal/issues/2916

Add timeouts and retries for CAS/AC operations.

---

website/blog/whats-new-in-bazel-5-0.md
website/blog/whats-new-in-bazel-6-0.md

|Before|After|
|---|---|
| ![Before](https://github.com/buildbuddy-io/buildbuddy/assets/158658/cf0b0445-5eab-4c02-9c9d-e3913ae17a2e) | ![After](https://github.com/buildbuddy-io/buildbuddy/assets/158658/e1c1312a-521a-4440-9f46-f8190dcee342) |

Improve how changes are linked in “What New in Bazel” blog posts

---

server/util/retry/retry.go
server/util/retry/retry_test.go

Actually check for non-retryable errors.

---

enterprise/server/util/execution/execution.go
proto/remote_execution.proto
server/util/clickhouse/clickhouse.go

(so that we can use them in drilldowns)
(for buildbuddy-io/buildbuddy-internal#2923)

synchronize exit code and execution status to clickhouse 

---

enterprise/server/remote_execution/containers/firecracker/firecracker.go
server/metrics/metrics.go

Add vmexec dial duration metric

---

enterprise/server/remote_execution/copy_on_write/copy_on_write.go
enterprise/server/remote_execution/uffd/uffd.go

[SS] Unmap chunks after memory has been copied by uffd to reduce memory usage

---

enterprise/server/remote_execution/copy_on_write/copy_on_write.go

* Use `Ctx` logging functions so the logs are associated with task ID
* Fix `err != nil` check (I think the intent was to check the ctx error? I noticed some "rate limiter failed" errors that were because of some expected context cancellations, and this fixed it)
* `defer eg.Wait()` to simplify things.

Small improvements to eager fetch error handling

---

enterprise/server/remote_execution/copy_on_write/copy_on_write.go

Good news - using a single exclusive lock in each chunk doesn't have any major performance impact on the COWStore and is simpler and more readable. This is likely because most (if not all) concurrent operations are on different chunks so there isn't much contention
On master (with two locks) the perf test took: 25m24.355207734s.
On this branch the perf test took: 25m1.941984613s

[SS] Simplify locking in COWStore

---

server/util/compression/compression.go

remove unused CompressFlate and DecompressFlate

---

enterprise/server/remote_execution/containers/firecracker/firecracker.go
enterprise/server/remote_execution/copy_on_write/copy_on_write.go
enterprise/server/remote_execution/snaploader/snaploader.go

[SS] When saving snapshots, unmap chunks eagerly to reduce memory usage

---

app/invocation/invocation_cache_card.tsx

Fix UI bug

---

app/invocation/invocation_cache_card.tsx

Fix UI - try 2

---

enterprise/server/remote_execution/containers/firecracker/firecracker.go

When merging the diff snapshot, the buffer that we use to copy the data over is smaller than the chunk size, so we may write to each COWStore chunk multiple times. We want to make sure not to unmap the chunk until all those writes have finished, or we'll do a lot of unnecessary maps and unmaps

[SS] Fix unmapping chunk too early when merging diff snapshot

---

enterprise/server/backends/distributed/distributed.go

Reverts buildbuddy-io/buildbuddy#5321

Revert "Reduce findmissing fanout"

---

enterprise/server/raft/constants/constants.go
enterprise/server/raft/store/store.go

Use 2PC for metarange edits

---

dockerfiles/executor_image/Dockerfile
enterprise/server/remote_execution/containers/podman/podman.go
enterprise/server/test/integration/podman/BUILD

Reverts buildbuddy-io/buildbuddy#5431

Revert "Upgrade executors to podman 4.8.0"

---

enterprise/server/raft/client/client.go
enterprise/server/raft/replica/replica.go
enterprise/server/raft/store/store.go

The transaction was being rolled back correctly but no error was being returned which was confusing.
Also: remove dead flag, and set rangeID field in replicaUsage proto.

Return any prepare errors encoutered during txn

---

enterprise/server/remote_execution/copy_on_write/BUILD
enterprise/server/remote_execution/copy_on_write/copy_on_write.go
server/metrics/metrics.go

We're seeing an unexpected number of mmapped bytes - this will help us figure out which files are responsible.

Add filename label to mmapped bytes metric

---

enterprise/server/cmd/ci_runner/main.go

workflows: rewrite github ssh URLs to https

---

enterprise/server/util/cacheproxy/BUILD
enterprise/server/util/cacheproxy/cacheproxy.go
server/util/grpc_client/grpc_client.go

Enable connection pool for distributed cache.

---

enterprise/server/remote_execution/containers/firecracker/firecracker.go

Fix initial rootfs snapshot being created directly under chroot

---

enterprise/server/raft/leasekeeper/leasekeeper.go
enterprise/server/raft/replica/replica.go
enterprise/server/raft/store/store.go
enterprise/server/raft/usagetracker/BUILD
enterprise/server/raft/usagetracker/usagetracker.go

Clean up some code and fix gossiped usage data.

Drive usage based on events queue

---

dockerfiles/executor_image/Dockerfile

Revert podman to 4.7.2. due to sqlite locking issue

---

enterprise/server/remote_execution/copy_on_write/copy_on_write.go

Add nil check in UnmapChunk

---

enterprise/tools/pgo/collect_profiles.sh

pgo: make sure app 0 does not feel left out

---

enterprise/server/remote_execution/containers/firecracker/firecracker_test.go

Update TestMergeDiffSnapshot to test base snapshot files with holes

---

enterprise/tools/check_metrics/check_metrics.go

Make check metric script log more readable

---

enterprise/server/hostedrunner/hostedrunner.go
enterprise/server/remote_execution/containers/firecracker/firecracker.go
enterprise/server/remote_execution/containers/firecracker/firecracker_performance_test.go
enterprise/server/remote_execution/containers/firecracker/firecracker_test.go
enterprise/server/remote_execution/executor/BUILD
enterprise/server/remote_execution/executor/executor.go
enterprise/server/remote_execution/platform/platform.go
enterprise/server/scheduling/task_router/task_router.go
enterprise/server/test/integration/task_router/task_router_test.go

[RB] Support remote snapshot sharing for remote bazel

---

go.mod
server/rpc/interceptors/BUILD
server/rpc/interceptors/interceptors.go
server/util/grpc_server/BUILD
server/util/grpc_server/grpc_server.go

use no-op meters in otel grpc

---

server/backends/blobstore/aws/aws.go
server/backends/blobstore/azure/azure.go
server/backends/blobstore/disk/BUILD
server/backends/blobstore/disk/disk.go
server/backends/blobstore/gcs/gcs.go
server/backends/blobstore/util/BUILD
server/backends/blobstore/util/util.go
server/util/ioutil/ioutil.go

Revert "Optimize blobstore ReadBlobs"

---

rules/yarn/index.bzl

An alternative to #5351.
Move the command templates out to constants to render multi-lines
correctly.
For the executable template, make sure that we set PATH before
running yarn so the correct NodeJS is picked up.

website: use Bazel's node toolchain with 'start' and 'serve'

---

WORKSPACE

Multiple security fixes https://github.com/golang/go/issues?q=milestone%3AGo1.21.5+label%3ACherryPickApproved

go_sdk: upgrade to 1.21.5

---

server/backends/github/github.go

The cookie library correctly sets `domain`, which fixes GitHub login from org-specific subdomains.
Fixes: https://github.com/buildbuddy-io/buildbuddy-internal/issues/2958

Use cookie library for GitHub cookies

---

enterprise/server/remote_execution/commandutil/commandutil_unix_test.go

Relax memory threshold for commandutil test.

---

enterprise/server/api/BUILD
enterprise/server/api/api_server.go
enterprise/server/testutil/enterprise_testenv/BUILD
enterprise/server/testutil/enterprise_testenv/enterprise_testenv.go
server/build_event_protocol/build_event_handler/BUILD
server/build_event_protocol/build_event_handler/build_event_handler.go
server/buildbuddy_server/BUILD
server/buildbuddy_server/buildbuddy_server.go
server/environment/environment.go
server/interfaces/BUILD
server/interfaces/interfaces.go
server/libmain/BUILD
server/libmain/libmain.go
server/real_environment/real_environment.go
server/remote_cache/byte_stream_client/BUILD
server/remote_cache/byte_stream_client/byte_stream_client.go
server/remote_cache/byte_stream_client/byte_stream_client_test.go
server/testutil/testenv/BUILD
server/testutil/testenv/testenv.go
server/util/grpc_client/grpc_client.go

make byte_stream_client an object

---

enterprise/app/BUILD.bazel
enterprise/app/org_picker/BUILD
enterprise/app/org_picker/org_picker.css
enterprise/app/org_picker/org_picker.tsx
enterprise/app/repo/BUILD
enterprise/app/repo/repo.tsx
enterprise/app/root/root.css
enterprise/app/sidebar/BUILD
enterprise/app/sidebar/sidebar.css
enterprise/app/sidebar/sidebar.tsx
server/testutil/webtester/webtester.go

Pull the org picker into its own component and add it to the repo page

---

app/auth/auth_service.ts
enterprise/app/org_picker/org_picker.css

Right now when you switch orgs, you lose your place in the UI.

Preserve location when switching orgs and fix css

---

enterprise/app/org_picker/org_picker.css

Org picker CSS tweak

---

enterprise/tools/replay_action/replay_action.go

- Should recommend `bazel` over `blaze` for most users
- The tool moved when it became OSS
- Gives an example of using `blake3`, since it might not be clear otherwise

Improve comment for `replay_action` command

---

enterprise/tools/replay_action/replay_action.go

Support different digest funcs in replay_action.

---

enterprise/app/tap/tap.tsx

Add support for sorting test grid by flake percentage

---

enterprise/server/raft/store/store.go

Stop this goroutine when store stops.

Exit on stop

---

enterprise/server/util/cacheproxy/cacheproxy_test.go
server/testutil/testdigest/BUILD
server/testutil/testdigest/testdigest.go

Add a benchmark for distributed read

---

enterprise/server/backends/prom/generate_docs/generate_docs.go

Right now we show "**" around the metric name.

fix prometheus docs for cloud

---

enterprise/server/raft/store/BUILD
enterprise/server/raft/store/store.go
enterprise/server/raft/store/store_test.go

- Kill zombie nodes
- Use a ticker instead of time.After
- Add a test

zombiekill

---

enterprise/server/crypter_service/crypter_service.go

There was a race condition between the key refresh goroutine and the test advancing the timer. Prior to this change, there was no guarantee that the refresh goroutine was waiting on the timer at the time the test advanced the time which would lead to the test waiting indefinitely.
Fixes https://github.com/buildbuddy-io/buildbuddy-internal/issues/2967

Fix flakiness in TestKeyReencryption.

---

server/util/bazel_request/bazel_request.go
server/util/bazel_request/bazel_request_test.go
server/util/grpc_server/grpc_server.go

Add `action_id` tag to tracing

---

.github/workflows/website.yaml

add the directory for exported metrics to update website workflow

---

enterprise/server/backends/distributed/distributed.go
enterprise/server/raft/store/store.go
enterprise/server/util/cacheproxy/cacheproxy.go
server/resources/resources.go

This is to reduce some logspam.

Simplify resources.GetZone

---

app/target/target_v2.tsx

Default to the first non-passing test attempt / shard / run

---

app/invocation/BUILD
app/invocation/invocation_compare_button.tsx
app/invocation/invocation_comparison_service.ts

i'll use this to share fetching of an invocation + show "compare" buttons in random little corners of the UI.

extract logic for saving comparison invocation into a service

---

enterprise/server/remote_execution/copy_on_write/copy_on_write.go
server/util/lockmap/lockmap.go

Clean up lockmap gc goroutines

---

app/service/rpc_service.ts
app/target/target_artifacts_card.tsx
enterprise/app/code/code.tsx

show zip file contents in code ui

---

server/rpc/interceptors/BUILD
server/rpc/interceptors/interceptors.go

Add group_id and user_id to logs.

---

enterprise/server/remote_execution/execution_server/execution_server.go

Demote noisy execution server logs to warnings

---

enterprise/server/remote_execution/runner/BUILD
enterprise/server/remote_execution/runner/runner.go
enterprise/server/remote_execution/runner/runner_darwin.go
enterprise/server/remote_execution/runner/runner_linux.go
enterprise/server/remote_execution/runner/runner_windows.go

Fix linux-support-only firecracker import on mac/windows builds

---

enterprise/server/backends/authdb/authdb.go
enterprise/server/crypter_service/crypter_service.go
server/build_event_protocol/target_tracker/target_tracker.go
server/util/db/db.go

Convert a couple of call sites to use ScanAll.

---

enterprise/server/workflow/service/service.go
server/interfaces/interfaces.go
server/util/db/db.go

Remove DBHandle method used in a single place.

---

app/invocation/invocation_timing_card.tsx
app/service/rpc_service.ts
enterprise/app/code/code.tsx

this really didn't touch much and i should have just done it.  oh well.

merge init param into bytestream fetch options

---

.github/workflows/release-m1.yaml
.github/workflows/release-mac.yaml
.github/workflows/release.yaml

Add support to manually trigger uploading release artifacts

---

.github/workflows/maggie-test-m1.yaml

Test workflow to debug mac version not being set

---

.github/workflows/maggie-test-m1.yaml

Test fetching tags to populate version tag

---

.github/workflows/maggie-test-m1.yaml

Reverts buildbuddy-io/buildbuddy#5546

Revert "Test add more logging"

---

enterprise/server/backends/migration_cache/migration_cache_test.go

This test cannot possibly succeed (except if goroutine scheduling is lucky) because when shutting down the migration cache, we discard copy instructions. The change to do that was [this one](https://github.com/buildbuddy-io/buildbuddy/pull/5135).

[DEFLAKE] Remove flaky migration cache test

---

enterprise/app/code/code.tsx

show single bytestream files even w/o a linked github account

---

enterprise/server/raft/rangelease/rangelease.go

Surfaced here: https://buildbuddy.buildbuddy.dev/invocation/50a846d0-3fcb-42f5-8aa8-44b3956b1528?target=%2F%2Fenterprise%2Fserver%2Fraft%2Fcache%3Acache_test&targetStatus=11#1@398

[DEFLAKE] Fix a lil race in rangelease code

---

enterprise/server/remote_execution/execution_server/execution_server.go

I also renamed "execute_result" to "execution_result" but LMK if you'd like to keep the same key for those.
**Related issues**: [2997](https://github.com/buildbuddy-io/buildbuddy-internal/issues/2997)

Add execution_id to trace spans

---

enterprise/server/backends/pebble_cache/pebble_cache.go

Pebble Optimization: create FileMetadata outside of for loop

---

enterprise/server/remote_execution/containers/podman/podman.go

Log stderr from podman run in secondary network setup

---

enterprise/tools/vmstart/BUILD
enterprise/tools/vmstart/vmstart.go

vmstart: fix LRU configuration

---

enterprise/server/cmd/executor/BUILD
enterprise/server/cmd/executor/executor.go
server/libmain/BUILD
server/libmain/libmain.go
server/testutil/testenv/BUILD
server/testutil/testenv/testenv.go
server/util/vtprotocodec/BUILD
server/util/vtprotocodec/vtprotocodec.go

Use vtproto Marshal/Unmarshal functions in grpc

---

app/service/rpc_service.ts

Don't double-call rpcs if streaming is enabled

---

proto/BUILD

clean up unused vtproto deps in cache proto

---

enterprise/server/invocation_search_service/invocation_search_service.go
server/buildbuddy_server/buildbuddy_server_test.go
server/interfaces/interfaces.go
server/libmain/libmain.go

Remove `DB(ctx)` method from DBHandle interface.

---

server/build_event_protocol/webhooks/webhooks.go
server/interfaces/interfaces.go
server/testutil/testolapdb/testolapdb.go
server/util/clickhouse/clickhouse.go
server/util/db/db.go

Remove name options and provide NewQuery method with opts.

Misc DB cleanup.

---

enterprise/server/remote_execution/snaputil/snaputil.go

This does not have a noticeable performance impact on `LoadSnapshot` duration when fetching a large number of chunks remotely - just something small I noticed that should simplify things slightly and help reduce memory pressure.

snaputil: stream chunks directly to file instead of buffering

---

server/util/clickhouse/clickhouse.go
server/util/db/db.go

db.Scan* funcs need to work for both types of handles.

---

cli/download/BUILD
cli/download/download.go
cli/printlog/BUILD
cli/printlog/printlog.go

No behavior change. Only proto.Message is used in the changed files.

use //server/util/proto in cli

---

enterprise/server/githubapp/BUILD
enterprise/server/githubapp/githubapp.go
proto/buildbuddy_service.proto
proto/github.proto
server/buildbuddy_server/buildbuddy_server.go
server/interfaces/interfaces.go
server/role_filter/role_filter.go

Will add caching in a follow-up since it adds complexity - and this is already a decently sized PR.
Open to any feedback / suggestions to make this simpler or less complex.
I think most of the complexity comes from doing the two searches in parallel, and then doing all of the metadata fetching in parallel.

Add backend support for fetching pull requests from github

---

app/format/format.tsx
app/router/router.tsx
enterprise/app/BUILD.bazel
enterprise/app/review/BUILD
enterprise/app/review/review.css
enterprise/app/review/review.tsx
enterprise/app/root/BUILD.bazel
enterprise/app/root/root.tsx
enterprise/app/sidebar/sidebar.tsx
proto/config.proto
server/static/static.go

Depends on server side here: https://github.com/buildbuddy-io/buildbuddy/pull/5599 (will probably fail to build until that's submitted).
Nostalgic screenshot:

Add nostalgia-inducing code review dashboard

---

enterprise/server/remote_execution/dirtools/BUILD
enterprise/server/remote_execution/dirtools/dirtools.go

benchmark results for Directory can be found at https://github.com/buildbuddy-io/buildbuddy/pull/5571

vtproto: use server/util/proto in dirtools

---

server/util/proto/proto.go

Add a few more proto method alias in server/util/proto

---

enterprise/server/githubapp/githubapp.go

Open to ideas on how to do this differently, or go style feedback - I suck at golang lol.

Add redis caching to pull request github requests

---

enterprise/app/review/BUILD
enterprise/app/review/review.css
enterprise/app/review/review.tsx
server/libmain/libmain.go

- Support hitting the URL directly
- Add an empty state
- Add a loading state
- Show `Unresolved` if changes are requested

Review dashboard tweaks

---

enterprise/app/review/review.css
enterprise/app/review/review.tsx

Review tweaks

---

enterprise/server/githubapp/githubapp.go

If you spam refresh with no cached result (before a result returns and is cached), you might hit a github rate limit error.
In that case, we want to avoid casting nil into whatever type we're expecting - so we check the error first.

Fix nil casting error

---

app/util/BUILD
app/util/react.tsx
enterprise/app/review/BUILD
enterprise/app/review/review.tsx

Fix array reduce issue

---

server/util/proto/proto.go
tools/edit_instance_template/BUILD
tools/edit_instance_template/edit_instance_template.go

add new methods in proto.go and use server/util/proto in tools/edit_instance_template

---

enterprise/server/raft/bringup/BUILD
enterprise/server/raft/bringup/bringup.go
enterprise/server/raft/client/BUILD
enterprise/server/raft/client/client.go
enterprise/server/raft/driver/BUILD
enterprise/server/raft/driver/driver.go
enterprise/server/raft/nodeliveness/BUILD
enterprise/server/raft/nodeliveness/nodeliveness.go
enterprise/server/raft/rangecache/BUILD
enterprise/server/raft/rangecache/rangecache.go
enterprise/server/raft/rangelease/BUILD
enterprise/server/raft/rangelease/rangelease.go
enterprise/server/raft/rbuilder/BUILD
enterprise/server/raft/rbuilder/rbuilder.go
enterprise/server/raft/registry/BUILD
enterprise/server/raft/registry/registry.go
enterprise/server/raft/replica/BUILD
enterprise/server/raft/replica/replica.go
enterprise/server/raft/sender/BUILD
enterprise/server/raft/sender/sender.go
enterprise/server/raft/store/BUILD
enterprise/server/raft/store/store.go
enterprise/server/raft/usagetracker/BUILD
enterprise/server/raft/usagetracker/usagetracker.go

Note: Used MarshalOld for rfpb.BatchCmdResponse because MarshalVT() is slower due to this message has google.rpc.Status in a repeated field.

use server/util/proto in raft

---

website/src/components/apply/apply.tsx

If there's something strange
In your Slack channel
Who you gonna call
Ghostbusters!
An invisible candidate
And we can't reach them
Who you gonna call
Ghostbusters!
I ain't hirin' no ghost
I ain't hirin' no ghost
If you're seeing Slacks
And they are empty
Who can you call?
(Ghostbusters)
An invisible candidate
Lookin' for a job
Ow, who you gonna call?
(Ghostbusters)

Ghostbusters: Don't send empty job applications to Slack

---

.github/workflows/release-cli.yaml

Following the example from https://github.com/buildbuddy-io/buildbuddy/pull/5616

Fix CLI mac build for bazel 7 too

---

.github/workflows/website.yaml

Temporarily use bazel 6.4.0 for website build to fix breakage

---

app/format/format.tsx
enterprise/app/review/review.tsx

Change "Last action" to "Updated" and shorten "December 21st" -> "Dec 21"

Make 'Last action' column more compact

---

cli/plugins/go-deps/post_bazel.py

The source path changed from something like `/.../execroot/...` to `/tmp/bazel-working-directory/buildbuddy/...`
Seems it's coming from [here](https://github.com/bazelbuild/bazel/blob/d9dc4fde4c8d06498f39b54a81d4e7fa1e5b5b30/src/main/java/com/google/devtools/build/lib/sandbox/LinuxSandboxedSpawnRunner.java#L71)

Fix CLI go-deps (auto-run gazelle) plugin

---

enterprise/server/testutil/testredis/testredis.go

- If Redis crashes, proactively fail the test.
- After the current test case completes, kill the Redis server. Otherwise a bunch of Redis servers will be kept in memory until the test process exits.

Improve lifecycle management of test redis servers

---

enterprise/server/scheduling/scheduler_server/scheduler_server.go
enterprise/server/scheduling/task_leaser/task_leaser.go
proto/scheduler.proto

Start sending lease_id as reconnect token.

---

.github/workflows/release.yaml

Run Linux release build on 16-core runner

---

enterprise/app/review/BUILD
enterprise/app/review/review.css
enterprise/app/review/review.tsx

Tidy up reviews page and fix horizontal scrolling

---

server/http/interceptors/BUILD
server/http/interceptors/interceptors.go

Missed one file before the break.

replace proto library in http interceptors

---

enterprise/server/githubapp/githubapp.go
proto/buildbuddy_service.proto
proto/github.proto
server/buildbuddy_server/buildbuddy_server.go
server/interfaces/interfaces.go
server/role_filter/role_filter.go

I'm piling up a bunch of RPCs here.  I think getting the experience right and trying it out is a little more important than the most efficient request/response pairs but it's alright if you want to smack me down on this.

server-side code for viewing a single PR.

---

app/invocation/BUILD
app/invocation/invocation.css
app/invocation/invocation_action_card.tsx

Render status field from ExecuteResponse

---

enterprise/app/review/BUILD
enterprise/app/review/review.css
enterprise/app/review/review.tsx
enterprise/app/review/review_list.tsx
enterprise/app/review/view_pull_request.tsx
enterprise/app/root/root.tsx

I don't use graphite, so I'm just blasting this out as a change that includes the server changes in #5653
I'll merge that first and bring this one up to it
It looks like this:

a code review ui that may look familiar to some

---

enterprise/server/backends/userdb/userdb.go
enterprise/server/backends/userdb/userdb_test.go
server/interfaces/interfaces.go

This will be used by the SCIM API to lookup an existing user corresponding to a user in the external system.

Add userdb method to lookup user by e-mail.

---

enterprise/app/workflows/workflows.tsx
server/static/static.go

stop checking workflow_history_enabled, it's launched

---

enterprise/server/backends/redis_kvstore/redis_kvstore.go
enterprise/server/backends/redis_metrics_collector/redis_metrics_collector.go

Limit invocation cache counters and log TTLs in redis to 1 day

---

enterprise/app/review/review_list.tsx
enterprise/app/review/view_pull_request.tsx

fix reviews page titles

---

docs/workflows-config.md

Document workflow artifacts dir

---

enterprise/server/backends/distributed/distributed.go

Improve multiWriter logging.

---

proto/build_event_stream.proto
proto/execution_graph.proto

Mirroring changes from these 2 commits
- https://github.com/bazelbuild/bazel/commit/564a3993a5ae54e87c239da2bd12d05299cc14cf
- https://github.com/bazelbuild/bazel/commit/c0b09960847bed4a3f49b8e467b1f5d6b23bc244

proto: update build_event_stream and execution_graph proto

---

.github/workflows/release-m1.yaml
.github/workflows/release-mac.yaml

Use macos-13 GitHub runners

---

.github/workflows/release-m1.yaml

Use correct label for GitHub arm64 Mac runner

---

release.py

Simplify version type flags in release.py

---

.bazelrc

Build macOS executors with a macOS 12 minimum requirement

---

website/blog/whats-new-in-bazel-5-0.md
website/blog/whats-new-in-bazel-6-0.md

Fix broken commit links in “What’s New in Bazel {5,6}.0” blog posts

---

enterprise/server/backends/userdb/userdb.go
enterprise/server/oidc/oidc.go
enterprise/server/scim/BUILD
enterprise/server/scim/scim.go
enterprise/server/scim/scim_test.go
enterprise/server/testutil/enterprise_testauth/enterprise_testauth.go
proto/api_key.proto
server/interfaces/interfaces.go
server/libmain/libmain.go
server/util/claims/claims.go

SCIM (external user management API) user lookup & user creation.

---

.github/workflows/create-github-release.yaml

Fix typo in github release workflow

---

enterprise/server/oidc/oidc.go

This is the way Okta sends API key when using Header auth in SCIM.

Accept API key as Bearer token.

---

enterprise/server/raft/store/store_test.go

Use 1 replica per test instead of 3 in store tests

---

enterprise/server/raft/store/store.go

manual (test) splits were conflicting with autosplitting

Deflake TestManySplits test

---

enterprise/app/review/BUILD
enterprise/app/review/review.tsx
enterprise/app/review/review_list.tsx
enterprise/app/review/view_pull_request.tsx
enterprise/app/root/root.tsx
enterprise/server/githubapp/githubapp.go
proto/github.proto

gonna use this to make sure i make your view not ugly in #5691 

add a `user/<username>` route for reviews

---

app/invocation/invocation_card.tsx

Made this change locally in the last PR but didn't save/commit it.

Fix invocation card classname

---

enterprise/app/api_keys/api_keys.tsx
proto/config.proto
server/static/static.go

Support for creating SCIM API keys.

---

enterprise/server/remote_execution/runner/runner.go

Got branches crossed and accidentally committed this rather than stashing in 
https://github.com…/buildbuddy-io/buildbuddy/pull/5702/files#diff-76b77e78fb5efa6662a1eac6abead695c329e3bb2002609676a9430dd6dd0228

Revert runner.go change I accidentally included in previous PR

---

enterprise/app/tap/tap.tsx

Before we'd just show the latest commit status.
This is nice, but the stats get a little wonky (since they're per-invocation) and this doesn't give you the full story of flaky tests or flaky builds if they were retries.
Here's an example of what a commit looks like that failed on the first invocation and passed on the second (check out the third square):
It'll show up to 4 stacked invocations per commit, after which you'd have to click on the commit circle to see more. (We can improve this experience if it ends up being common).

Show multiple test grid invocations per commit

---

server/util/filter/filter.go

Don't assume m is non-nil

---

enterprise/app/tap/tap.css
enterprise/app/tap/tap.tsx

Forgot these in my previous PR.

CSS changes for test grid

---

WORKSPACE

Changes: https://github.com/golang/go/issues?q=milestone%3AGo1.21.6+label%3ACherryPickApproved

go_sdk: upgrade to 1.21.6

---

dockerfiles/executor_image/Dockerfile

Upgrade podman to 4.9

---

proto/BUILD
proto/buildbuddy_service.proto
proto/codesearch_service.proto
proto/config.proto
proto/index.proto
proto/search.proto

Moved to main because it makes things easier. Also added request and response context.

Add codesearch protos

---

app/router/router.tsx
enterprise/app/BUILD.bazel
enterprise/app/codesearch/BUILD
enterprise/app/codesearch/codesearch.css
enterprise/app/codesearch/codesearch.tsx
enterprise/app/root/BUILD.bazel
enterprise/app/root/root.tsx
enterprise/app/sidebar/sidebar.tsx
server/libmain/libmain.go

It's behind a flag!
Looks like this:

Add enterprise/app codesearch bits (behind flag)

---

enterprise/server/backends/authdb/authdb.go
enterprise/server/backends/userdb/userdb.go
enterprise/server/scheduling/scheduler_server/scheduler_server.go
server/buildbuddy_server/buildbuddy_server.go
server/tables/tables.go

This is a bit of a historical wart.

Make UseGroupOwnedExecutors a non-pointer field.

---

enterprise/server/backends/authdb/authdb_test.go
enterprise/server/backends/userdb/userdb.go
enterprise/server/backends/userdb/userdb_test.go
enterprise/server/iprules/iprules_test.go
enterprise/server/oidc/oidc.go
enterprise/server/saml/saml.go
enterprise/server/scim/scim.go
enterprise/server/scim/scim_test.go
enterprise/server/testutil/enterprise_testauth/enterprise_testauth.go
server/buildbuddy_server/buildbuddy_server.go
server/tables/tables.go
server/util/claims/claims.go
server/util/subdomain/subdomain.go

Make URLIdentifier a non-pointer field.

---

enterprise/server/saml/saml.go
enterprise/server/scim/scim.go
enterprise/server/scim/scim_test.go
server/buildbuddy_server/buildbuddy_server.go
server/tables/tables.go

Make SAMl IDP URL a non-pointer field for simplicity.

---

enterprise/server/remote_execution/vbd/vbd.go

Use CtxErrorf for VBD reads

---

buildpatches/com_github_hanwen_go_fuse_v2.patch
deps.bzl
go.mod
go.sum

Revert "Upgrade go-fuse and remove patch (#5763)"

---

enterprise/server/scim/scim.go

Azure AD does not appreciate it.

SCIM: don't send null resource list

---

enterprise/server/hostedrunner/hostedrunner.go

For the hosted remote bazel runner, we [set api key on the outgoing context](https://github.com/buildbuddy-io/buildbuddy/blob/master/enterprise/server/hostedrunner/hostedrunner.go#L230). The execution server then tries [to parse remote header overrides](https://github.com/buildbuddy-io/buildbuddy/blob/master/enterprise/server/remote_execution/execution_server/execution_server.go#L494) from the [incoming context](https://github.com/buildbuddy-io/buildbuddy/blob/master/enterprise/server/remote_execution/platform/platform.go#L297). Because the hosted runner code is calling the execution server directly via function call, the context does not switch from outgoing -> incoming context, and the the header is not parsed correctly. This PR changes the code to make a self-RPC to the execution …

[RB] Fix parsing remote header overrides for remote bazel

---

enterprise/server/remote_execution/copy_on_write/copy_on_write.go

Fix noisy COWStore rate limiter logs

---

app/target/BUILD
app/target/target_artifacts_card.tsx
app/util/BUILD
app/util/cache.tsx
app/util/cache_test.ts

Fix target artifacts card rendering empty/0 digests

---

enterprise/server/backends/pebble_cache/pebble_cache.go

time.Sleep is annoying because it means tests have to wait out this sleep even if the cache is already shutting down. Instead, wait on a ticker channel, or exit early if the context was cancelled.
Partially addresses https://github.com/buildbuddy-io/buildbuddy-internal/issues/3035

Don't sleep quite so hard

---

server/remote_cache/cachetools/cachetools.go

This PR fixes a minor goroutine leak in the case where RecvWithTimeoutCause returns a non-EOF error.

Ensure zstd decompressor is closed

---

enterprise/config/buildbuddy.local.yaml

Enable user owned keys locally

---

enterprise/server/cmd/executor/executor.go
server/libmain/libmain.go

call vtprotocodec.Register() in init

---

tools/clickhouse

https://github.com/buildbuddy-io/buildbuddy-internal/issues/2905

use clickhouse version 23.8 locally

---

enterprise/server/backends/pebble_cache/pebble_cache.go

L0CompactionConcurrency 4 => 2

---

enterprise/server/githubapp/githubapp.go

This is less error prone, since it prevents you from being able to create a `newInstallationClient` without calling `authorizeUserInstallationAccess`.

Move `authorizeUserInstallationAccess` into `newInstallationClient`

---

tools/metrics/grafana/dashboards/buildbuddy.json

Break out compaction debt by pod.

---

enterprise/server/cmd/ci_runner/main.go
enterprise/server/test/integration/ci_runner/ci_runner_test.go

Make sure we upload artifacts before returning from the function due to the bazel error.

Fix jvm.out upload

---

enterprise/server/cmd/ci_runner/main.go

Add `--heap_dump_on_oom` flag to our generated bazelrc and upload the heapdump.hprof file as a workflow artifact if it exists.
The test I tried adding was super flaky (it was really slow/heavyweight, and couldn't get Bazel to consistently OOM and generate the heap profile), so I just left the test as-is for now. When the heap profile was generated though, it was uploaded successfully.

Upload bazel heap dump on OOM

---

enterprise/server/remote_execution/containers/firecracker/firecracker.go

Fix panic if VMMetadata is missing (for older snapshots)

---

docs/prometheus-metrics-for-cloud.mdx
enterprise/server/backends/prom/prom.go

update docs for exported prometheus metrics

---

enterprise/server/scim/scim.go

Extract out SCIM request handling code that can be re-used for groups.

---

enterprise/server/scim/scim.go
enterprise/server/scim/scim_test.go

SCIM group JSON schemas.

---

server/build_event_protocol/event_index/event_index.go

Sort root-cause targets first in target listings

---

docs/enterprise-api.md

Add docs for passing env vars to ExecuteWorkflow api

---

tools/metrics/grafana/dashboards/buildbuddy.json

Use pod name as legend for pebble debt graph.

---

server/testutil/testauth/BUILD
server/testutil/testauth/testauth.go

Just use the real Claims struct.

Simplify testauth.TestUser

---

enterprise/tools/replay_action/replay_action.go

Fix replay action if you want to replay on the same executor but under a different group api key

---

enterprise/app/org/org_members.tsx
proto/grp.proto

**Related issues**: https://github.com/buildbuddy-io/buildbuddy-internal/issues/3091

Add new roles to role proto

---

deps.bzl
server/util/bazelisk/BUILD
server/util/bazelisk/bazelisk.go

This reverts commit c454fd9ddb94d364a8d9709f32121bf2ed46c7ee.

Revert "reapply: build bazelisk from source (#5826)"

---

docs/workflows-config.md
enterprise/server/remote_execution/containers/firecracker/firecracker.go
enterprise/server/workflow/config/config.go
enterprise/server/workflow/service/service.go

**Related issues**: Fixes https://github.com/buildbuddy-io/buildbuddy-internal/issues/3043

Add timeout field for workflows

---

cli/remotebazel/remotebazel.go
enterprise/server/hostedrunner/BUILD
enterprise/server/hostedrunner/hostedrunner.go
proto/runner.proto

**Related issues**: https://github.com/buildbuddy-io/buildbuddy/pull/5846

[RB] Add timeout field for remote bazel

---

cli/plugins/go-deps/post_bazel.py

Fix go-deps plugin

---

website/src/pages/security-vulnerability-report.md

Added security@buildbuddy.io as the contact email

Update "Report a Security Vulnerability" page with contact email

---

enterprise/app/repo/repo.tsx

Add a mode to the repo flow that kicks you straight into the code UI

---

enterprise/server/backends/userdb/BUILD
enterprise/server/backends/userdb/userdb.go
enterprise/server/backends/userdb/userdb_test.go

Update capabilities when changing role

---

enterprise/server/scim/scim.go
enterprise/server/scim/scim_test.go

SCIM: support user deletion via DELETE as well

---

enterprise/server/scim/scim.go
enterprise/server/scim/scim_test.go

It was previously being unnecessarily URL-encoded

SCIM: fix user SubID

---

server/buildbuddy_server/buildbuddy_server.go
server/capabilities_filter/BUILD
server/capabilities_filter/capabilities_filter.go
server/capabilities_filter/capabilities_filter_test.go
server/util/capabilities/capabilities.go

Update allowed RPCs to be based on capabilities instead of role

---

enterprise/app/api_keys/api_keys.tsx
proto/config.proto
server/static/static.go

Rename org admin API key flag.

---

enterprise/config/buildbuddy.raft.yaml

Enable self auth when running raft locally

---

cli/parser/parser_test.go
cli/remotebazel/remotebazel.go
enterprise/server/cmd/ci_runner/main.go

Fixes buildbuddy-io/buildbuddy-internal#2979

[RB] Add unit test for importing user.bazelrc and print an update so it doesn't seem like cli is hanging when unpausing a snapshot

---

enterprise/server/remote_execution/uffd/uffd.go

**Related issues**: buildbuddy-io/buildbuddy-internal#3092

[SS] Add debug logging in uffd

---

enterprise/server/remote_execution/containers/firecracker/firecracker.go

Overprovision Firecracker VMs by up to 3 CPU cores (configurable via `--executor.firecracker_overprivision_cpus`)

Overprovision VM CPUs

---

enterprise/server/scim/scim.go
enterprise/server/scim/scim_test.go

SCIM: SubID needs to be updated if the username is updated.

---

app/components/link/link.css

Make text link color blue

---

dockerfiles/executor_image/Dockerfile

upgrade podman 4.9.0 -> 4.9.1

---

enterprise/server/scim/scim.go
enterprise/server/scim/scim_test.go

SCIM: support username changes for Okta folks too (via PUT)

---

enterprise/server/raft/rangecache/rangecache.go

Call GetOverlapping only once in updateRange.
Also add some comments to exported methods in range cache.

range cache: call GetOverlapping once in updateRange

---

website/docusaurus.config.js
website/src/css/nav.css

Left some TODOs in there for marketing pages we should create.
Before:
After:

Marketing website navigation tweaks

---

enterprise/server/raft/registry/registry.go
enterprise/server/raft/replica/replica.go
enterprise/server/raft/store/store.go

Add comments to raft store, replica and registry

---

enterprise/server/auditlog/BUILD
enterprise/server/auditlog/auditlog.go
enterprise/server/backends/authdb/BUILD
enterprise/server/backends/authdb/authdb.go
enterprise/server/backends/userdb/userdb.go
enterprise/server/githubapp/BUILD
enterprise/server/githubapp/githubapp.go
enterprise/server/iprules/BUILD
enterprise/server/iprules/iprules.go
enterprise/server/workflow/service/BUILD
enterprise/server/workflow/service/service.go
server/backends/github/BUILD
server/backends/github/github.go
server/buildbuddy_server/buildbuddy_server.go
server/util/authutil/BUILD
server/util/authutil/authutil.go

Remove AuthorizeGroupRole and check capabilities instead

---

enterprise/server/raft/cache/cache.go

Add health check for RaftCache

---

enterprise/app/org_picker/org_picker.tsx
enterprise/app/sidebar/sidebar.tsx

I think I broke this when I extracted the org picker out into its own component.

Fix org picker / collapsed side bar interaction

---

BUILD
enterprise/server/raft/client/client.go
enterprise/server/raft/nodeliveness/nodeliveness.go
enterprise/server/raft/rangelease/rangelease.go
enterprise/server/remote_execution/executor/executor.go
enterprise/server/scheduling/priority_task_scheduler/priority_task_scheduler.go
server/remote_asset/fetch_server/fetch_server.go
server/util/background/background.go
server/util/grpc_server/grpc_server.go

Enable golang static check analyzer S1024: 'Replace x.Sub(time.Now()) with time.Until(x)'

---

enterprise/server/scim/BUILD
enterprise/server/scim/scim.go
enterprise/server/scim/scim_test.go
server/util/role/BUILD
server/util/role/role.go
server/util/role/role_test.go

Support reader/writer roles in SCIM

---

enterprise/server/raft/driver/driver.go

raft/driver debugf -> debug

---

enterprise/server/remote_execution/uffd/uffd.go

If there is a page fault in one process on a multi-core machine, that process will be paused while the page fault is handled, but the other processes will not (https://stackoverflow.com/questions/15886938/can-other-processes-run-during-memory-paging). So if multiple processes on the machine access the same memory location at the same time, they can trigger duplicate page fault notifications for the same address.
(In debug logging I noticed that there were multiple page fault notifications for the exact same GuestFaultingAddr. So it was not an issue related to address math. The page fault handler was literally trying to allocate the same memory address twice.)
Also remove debug logging if we map the same chunk twice, because there are valid cases for this if Firecracker assigns multiple …

[SS] Ignore uffd errors due to mapping the same page multiple times

---

enterprise/app/api_keys/api_keys.tsx

**Related issues**: Fixes https://github.com/buildbuddy-io/buildbuddy-internal/issues/3127

Fix personal API key button visibility

---

enterprise/app/api_keys/api_keys.tsx
enterprise/server/backends/authdb/authdb.go

Update presentation of keys with non-admin visibility

---

enterprise/app/code/code.tsx

Makes working with this code a little easier.
There are two instances of `any` left, but that's part of the actual signature of the `JSON.stringify` replacer and `JSON.parse` reviver functions.

Remove the use of `any` type in the code editor

---

enterprise/app/code/code.tsx

Other file extensions should already be handled by monaco's built-in language types.

Use python syntax highlighting for Bazel files

---

website/src/css/nav.css

I broke this with my recent nav tweaks

Fix marketing website navbar on small screens

---

cli/parser/parser.go
cli/parser/parser_test.go

**Related issues**: fixes https://github.com/buildbuddy-io/buildbuddy-internal/issues/3128

cli: fix starlark flags not expanding from common configs

---

app/format/format.tsx
enterprise/app/BUILD.bazel
enterprise/app/code/BUILD
enterprise/app/code/code.css
enterprise/app/code/code.tsx
enterprise/app/sidekick/module/BUILD
enterprise/app/sidekick/module/module.css
enterprise/app/sidekick/module/module.tsx

A sidekick is a panel that opens up in the code editor when a specific file type is opened.
The first sidekick which I'm introducing here opens when you visit a `MODULE` or `MODULE.bazel` file and helps you add/remove/upgrade dependencies.

Introduce the concept of a "sidekick" to the code editor

---

enterprise/app/sidekick/module/module.tsx

This handles 3 cases when adding a new module via the module sidekick:
1) The user has selected some text in the editor. In this case, the selected text is replaced. 
2) The cursor is on an empty line. In this case, the module is added to this empty line.
3) The cursor is on a non-empty line. In this case, the module is added on the next line. If the next line does not exist, it is created with a "\n".

Tweak new module insertion

---

app/target/target_test_document_card.tsx

Attempt to reconstruct ANSI sequences from test XML

---

enterprise/app/BUILD.bazel
enterprise/app/code/BUILD
enterprise/app/code/code.tsx
enterprise/app/sidekick/bazelversion/BUILD
enterprise/app/sidekick/bazelversion/bazelversion.css
enterprise/app/sidekick/bazelversion/bazelversion.tsx

Let's you pick your bazel version with a dropdown.

Add .bazelversion sidekick

---

deps.bzl
enterprise/server/githubapp/BUILD
enterprise/server/githubapp/githubapp.go
enterprise/server/webhooks/github/BUILD
enterprise/server/webhooks/github/github.go
enterprise/server/workflow/service/BUILD
enterprise/server/workflow/service/service.go
go.mod
go.sum
server/backends/github/BUILD
server/backends/github/github.go
server/interfaces/BUILD
server/interfaces/interfaces.go

Needed to experiment with some new-ish workflow APIs.

Upgrade go-github to v59

---

enterprise/server/remote_execution/uffd/uffd.go

I noticed that we were still seeing errno(17) in the logs after the release, and realized there was a bug in this logic

[SS] Fix UFFD error handling

---

docs/guide-auth.md

Update docs for new user roles

---

enterprise/app/BUILD.bazel
enterprise/app/code/BUILD
enterprise/app/code/code.tsx
enterprise/app/sidekick/bazelrc/BUILD
enterprise/app/sidekick/bazelrc/bazelrc.css
enterprise/app/sidekick/bazelrc/bazelrc.tsx

Add bazelrc sidekick

---

enterprise/server/raft/replica/replica.go

hoping we can jus throw this in for now in case we see that issue again.

Do some logging on startup

---

enterprise/app/code/BUILD
enterprise/app/code/code.css
enterprise/app/code/code.tsx
enterprise/app/code/code_sidebar_node.tsx

Didn't change the new file / delete implementations much, just created context menu and added them there.
Will fix up the implementations and add more methods separately.

Move new file and delete actions to context menu

---

enterprise/server/raft/client/client.go
enterprise/server/raft/constants/constants.go
enterprise/server/raft/store/store.go

To fix the error message, `Error gettting membership for shard 10: specified
timeout value is too small`

ensure that the timeout value we set is > 0

---

enterprise/app/code/code.tsx
enterprise/app/code/code_pull_request.ts
enterprise/server/githubapp/githubapp.go

Implement delete in code editor

---

proto/usage.proto

**Related issues**: https://github.com/buildbuddy-io/buildbuddy-internal/issues/3139

Proto changes to fetch less usage data

---

enterprise/server/raft/leasekeeper/leasekeeper.go

fix some nits in leasekeeper

---

enterprise/server/raft/listener/BUILD
enterprise/server/raft/listener/listener.go

Add debug logging when leader is changed and updated some comments

---

enterprise/server/remote_execution/runner/runner.go

Should help us debug the podman failed to remove issue.

Log runner ID when we fail to remove

---

cli/remotebazel/remotebazel.go
cli/remotebazel/remotebazel_test.go

[RB] Fix remote bazel parsing if a flag is passed multiple times

---

enterprise/config/buildbuddy.workflow.yaml
enterprise/config/executor.workflow.yaml

Add configs to run workflows/remote bazel locally

---

enterprise/server/raft/rangelease/rangelease.go

[Raft] Errorf -> Error in rangelease

---

enterprise/server/raft/client/client.go

don't call raft API when the deadline has approached

---

tools/metrics/grafana/dashboards/workflow.json

[SS] Add a grafana dashboard for vm exec server dial time

---

tools/metrics/grafana/dashboards/buildbuddy.json

Make remote execution charts more clear

---

.github/workflows/remote-bazel-build.yaml

In remote bazel workflow, don't build from source every time bc it's slow

---

enterprise/app/code/code.css
enterprise/app/code/code.tsx

Add basic tabs to editor

---

enterprise/app/code/code.tsx

Don't show tabs in single file view & remove completed todo

---

enterprise/app/code/code.css
enterprise/app/code/monaco.css

Fixes issue where search highlight is off by two lines.
Also makes UI with no tabs look a little cleaner.

Editor css tweaks

---

enterprise/server/remote_execution/containers/firecracker/firecracker.go
enterprise/server/remote_execution/executor/BUILD
enterprise/server/remote_execution/executor/executor.go

Add more logging to help debug stuck VM executions

---

enterprise/app/code/code.tsx

Allows linking from a file like https://github.com/buildbuddy-io/buildbuddy/blob/master/tools/cas/cas.go instead of just from the top level repo
Since these links can contain branch information, I also made some improvements to the handling of branches:
- Add branch to the local storage cache key 
- Add a url parameter for branch
- Show this branch in the breadcrumbs, and collapse branch + commit sha breadcrumbs if they're the same
Also fixes a few places where I was calling setState instead of updateState (which doesn't persist state to local storage).
Addresses part of: https://github.com/buildbuddy-io/buildbuddy-internal/issues/1176

Allow deep-linking from files on github to code editor

---

enterprise/server/usage_service/BUILD
enterprise/server/usage_service/usage_service.go
enterprise/server/usage_service/usage_service_test.go

usage: return only the period specified in the request

---

enterprise/server/githubapp/githubapp.go

Instead of having dev and prod both be labeled "buildbuddy" and using an additional "dev" label to differentiate dev from prod, just use a single label, which we'll set to "buildbuddy-dev". After thinking through it, the `matchesRunnerLabels` logic won't work if we want to run dev and prod workflows at the same time - it's fixable but unnecessarily complicated.

Simplify actions runner labels

---

enterprise/tools/replay_action/replay_action.go

This is useful to replay an action targeting the same VM snapshot but with a different command so that we can run debug commands within the VM.

Update replay_action to allow overriding the command

---

enterprise/server/hostedrunner/hostedrunner.go

**Related issues**: Fixes https://github.com/buildbuddy-io/buildbuddy-internal/issues/2978

[RB] Fix async requests

---

enterprise/server/raft/store/store.go

During some local testing, I noticed that sometimes grpcServer.Serve is occasionally called around
4 - 6 seconds after the registry update is pushed, sometimes even after other apps have received the registry update events.  
This change makes grpcServer.Serve kick in earlier. When tested locally,
grpcServer.Server is called within 30ms - 60ms after the
registry update is pushed and before other apps received the updates.

[Raft] start grpcServer.Serve earlier

---

enterprise/app/code/code.tsx

Seeing some GLIBC issues in my testing.

Update code UI to use ubuntu20 image for remote execution

---

enterprise/app/code/monaco.css

Add color for selected text

---

enterprise/app/code/code.tsx

If you right click on a file and then click new file / new folder - we want to create that new file or new folder in that file's parent directory.

Support new file / new folder when clicked on file

---

server/metrics/metrics.go

[SS] Add buckets for metrics

---

enterprise/app/code/code.tsx

I think this does more harm than good, and the .bazelrc is a better tool for this (with suggestions from the .bazlerc sidekick).

Don't tack any additional flags onto bazel command

---

enterprise/server/usage/usage.go

Add more logs to diagnose slow usage flushing

---

enterprise/server/usage/usage.go

Return an error earlier if usage counts are empty

---

tools/metrics/grafana/dashboards/buildbuddy.json

Improve SQL charts and add RBE-specific SQL latency chart

---

enterprise/app/usage/BUILD
enterprise/app/usage/usage.tsx

Fixes buildbuddy-io/buildbuddy-internal#3139

use new usage rpc fields in client

---

.github/workflows/remote-bazel-build.yaml
cli/remotebazel/remotebazel.go

**Related issues**: Fixes https://github.com/buildbuddy-io/buildbuddy-internal/issues/3141

[RB] Try to base remote runs off current branch if possible

---

enterprise/app/code/code.tsx

Makes the deep linking experience even better

Preserve focused line number when redirecting from github

---

enterprise/app/code/monaco.css

It's currently busted (due monaco version upgrade).

Fix up find-replace styling

---

app/invocation/invocation.css
app/invocation/invocation_error_card.tsx

Probably needs some minor CSS tweaks, but looks good enough for now, IMO. Screenshot in https://github.com/buildbuddy-io/buildbuddy-internal/issues/3155
**Related issues**: https://github.com/buildbuddy-io/buildbuddy-internal/issues/3155

Render action stderr in terminal

---

enterprise/server/remote_execution/platform/platform.go
enterprise/server/scheduling/scheduler_server/scheduler_server.go

Allow routing a task to a specific executor ID for debugging

---

tools/metrics/grafana/dashboards/workflow.json

[SS] Add grafana dashboards for new performance metrics

---

enterprise/server/remote_execution/execution_server/execution_server.go

This reverts commit ab822707ab6dfe13b8a11d9d84314283f7d617e4.

Revert "Only perform the select to determine if there is no related execution row after attempting an update (#6002)"

---

docs/config-auth.md

I will send another PR for Okta.

Add SCIM instructions for Entra.

---

docs/config-auth.md

The `Azure AD SAML Toolkit` application does not support SCIM.

Update Entra SAML instructions to use a custom application.

---

enterprise/server/raft/replica/replica.go

Right now we cannot update atime properly b/c we pass nil key in sender.Run.
Use sender.RunMultiKey instead.

[Raft] Fix atime update

---

docs/config-auth.md

Add instructions for configuring SCIM for Okta.

---

.github/workflows/release-cli.yaml
cli/release.py

Automatically upgrade the cli when merging changes to cli/**

---

enterprise/server/remote_execution/containers/firecracker/firecracker.go

Disable output copying in vmstart

---

enterprise/server/remote_execution/execution_server/BUILD
enterprise/server/remote_execution/execution_server/execution_server.go
enterprise/server/remote_execution/execution_server/execution_server_test.go

Fixed the execution update change and added tests

---

enterprise/server/remote_execution/containers/firecracker/firecracker.go
enterprise/server/remote_execution/containers/firecracker/firecracker_test.go
enterprise/server/vmexec/BUILD
enterprise/server/vmexec/vmexec.go

Add more logging to vmexec server

---

app/invocation/invocation_action_card.tsx

Fix issue where "resumed from" link breaks inside the same invocation

---

tools/metrics/grafana/dashboards/buildbuddy.json

Add tree cache hit rate graph

---

deps.bzl

Reverts buildbuddy-io/buildbuddy#6093

Revert "Upgrade soci-store to v0.0.13 (with some new log statements)."

---

server/util/rangemap/rangemap.go
server/util/rangemap/rangemap_test.go

Fixes https://github.com/buildbuddy-io/buildbuddy-internal/issues/3165

Ensure Range.String() outputs utf8 valid string

---

enterprise/server/backends/distributed/distributed.go

Log all read errors.

---

enterprise/server/raft/usagetracker/usagetracker.go

**Related issues**: https://github.com/buildbuddy-io/buildbuddy-internal/issues/3174

[raft] fix concurrent map iteration and map write

---

enterprise/server/remote_execution/execution_server/execution_server.go

Fix exec duration metric

---

app/components/link/link.tsx
app/router/router.tsx
enterprise/app/workflows/action_list.tsx
enterprise/app/workflows/workflows.tsx

blow away previous state when clicking links on workflows

---

enterprise/server/remote_execution/containers/firecracker/firecracker.go
enterprise/server/remote_execution/copy_on_write/copy_on_write.go
enterprise/server/remote_execution/snaploader/snaploader.go
enterprise/server/remote_execution/uffd/uffd.go
server/metrics/metrics.go

Also remove some labels and reduce number of buckets to reduce cardinality of metrics

[SS] Clean up some noisy prometheus metrics

---

enterprise/server/raft/usagetracker/usagetracker.go

**Related issues**: https://github.com/buildbuddy-io/buildbuddy-internal/issues/3180

[raft] log and return error if total count is negative

---

.github/workflows/release-cli.yaml

Fix release cli workflow

---

deps.bzl
enterprise/server/githubapp/BUILD
enterprise/server/githubapp/githubapp.go
go.mod
go.sum
proto/buildbuddy_service.proto
proto/github.proto
server/buildbuddy_server/buildbuddy_server.go
server/capabilities_filter/capabilities_filter.go
server/interfaces/interfaces.go

- fetch PR data via graphql so that we can make threads and properly identify comments for updates by _id_ 
- add relevant mutate RPCs for comments

server changes to support commenting on reviews

---

proto/build_event_stream.proto
proto/failure_details.proto
proto/option_filters.proto

Including changes from the following commits
- build_event_stream.proto
https://github.com/bazelbuild/bazel/commit/7923669e5b76417ce9e0d2587b19c063cdd24af1
https://github.com/bazelbuild/bazel/commit/8a413983fc1c053d1f24b09cb72697d24397ba59
- failure_details.proto
https://github.com/bazelbuild/bazel/commit/a03388ac74cad22efe27ad75ad41130af83c8f3c
https://github.com/bazelbuild/bazel/commit/940b80fe9f6eb8497b19b373c1a533e50ff76ac6
https://github.com/bazelbuild/bazel/commit/d48734859744474dd469570b80d86bef4a519435
https://github.com/bazelbuild/bazel/commit/4042fd6e6eaff5014aad9d22bdf6c1fb74a78a88
https://github.com/bazelbuild/bazel/commit/8e0343c189c1decaca7efaf148a79adff78187f3
https://github.com/bazelbuild/bazel/commit/9f0f23211293589d812cb9ea4aaaead52486c52e …

proto: update bazel protos

---

deps.bzl

With https://github.com/buildbuddy-io/soci-snapshotter/pull/18

Upgrade to soci-store v0.0.14

---

enterprise/server/raft/cache/BUILD
enterprise/server/raft/cache/cache.go

[raft] remove sync read from healthcheck

---

website/blog/how-to-migrate-an-ios-app-to-bazel.md

Fix a typo

---

tools/metrics/grafana/dashboards/buildbuddy.json

Add chart for tree cache hits/misses by directory level

---

enterprise/server/backends/distributed/distributed.go
enterprise/server/remote_execution/executor/executor.go
enterprise/server/scheduling/priority_task_scheduler/priority_task_scheduler.go
server/remote_cache/content_addressable_storage_server/content_addressable_storage_server.go
server/util/approxlru/approxlru.go

Your price is way too high, you need to cut it
Cut it, cut it, cut it, cut it
Cut it, cut it, cut it, cut it

Reduce log volume

---

rules/gcs/index.bzl

fix random lint error that popped up when i ran buildfix -a

---

BUILD
buildbuddy.yaml
rules/gcs/index.bzl

**Related issues**: [2282](https://github.com/buildbuddy-io/buildbuddy-internal/issues/2282)

Add a workflow that uses an image with a bunch of layers, for testing image streaming

---

enterprise/server/remote_execution/soci_store/soci_store_linux.go

**Related issues**: [2901](https://github.com/buildbuddy-io/buildbuddy-internal/issues/2901)

Set pdgid=true for soci-store subprocess

---

enterprise/server/remote_execution/containers/firecracker/firecracker.go

Nothing should be accessing the VBD file handles since we've stopped the VM and the firecracker process should have exited, and firecracker should be the only process accessing VBD files. But closing the VBD mounts explicitly before saving COWStore contents to cache just gives us a little more peace of mind.

Unmount VBD devices before calling saveSnapshot

---

server/remote_cache/directory_size/BUILD
server/remote_cache/directory_size/directory_size.go

this will hopefully help diagnose what the heck is going wrong for some users.

slap in a bit of extra logging on directory size RPCs

---

website/blog/how-to-migrate-an-ios-app-to-bazel.md

Add filepaths to examples in “How to migrate an iOS app to Bazel” blog post

---

server/tables/tables.go

Guessing this was unintentional but lmk if not :)

Remove debug print

---

enterprise/server/githubapp/githubapp.go

Fixes buildbuddy-io/buildbuddy-internal#3189
There's a better fix for this involving a preview API, but this seems good enough for now.

Check if change is approved before marking it as submittable.

---

enterprise/app/review/view_pull_request.tsx
enterprise/server/githubapp/githubapp.go
proto/github.proto

For those of us who just smash approve

Fix approvals on changes when the user has no draft comments

---

enterprise/app/review/view_pull_request.tsx

Fixes buildbuddy-io/buildbuddy-internal#3199

fix infinite loop when rendering diffs

---

enterprise/server/scheduling/task_router/task_router.go
enterprise/server/scheduling/task_router/task_router_test.go

Rename default branch routing flag

---

enterprise/app/review/view_pull_request.tsx
enterprise/server/githubapp/githubapp.go
proto/github.proto

add submit button, for submitting

---

enterprise/tools/replay_action/replay_action.go

Fix missing instance_name/digest in replay_action

---

website/blog/bazels-remote-caching-and-remote-execution-explained.md
website/blog/how-to-migrate-an-ios-app-to-bazel.md

Add captions to some blog post images

---

enterprise/app/review/view_pull_request.tsx
enterprise/server/githubapp/githubapp.go
proto/github.proto

Show check state in analysis list, fix pending / done states

---

enterprise/app/code/code.tsx
enterprise/app/history/BUILD
enterprise/app/history/history.css
enterprise/app/history/history_invocation_stat_card.tsx

Also fixes state hydration when navigating to and from code editor without a full page reload.

Show links to editor from repo page if editor is enabled

---

enterprise/app/code/BUILD
enterprise/app/code/code.tsx
enterprise/app/org_picker/org_picker.css
enterprise/app/org_picker/org_picker.tsx

Add an org picker to code editor

---

enterprise/app/code/BUILD
enterprise/app/code/code.css
enterprise/app/code/code.tsx
enterprise/app/code/code_empty.tsx

The current empty state pretty janky / broken. This change gives us a nice & simple starting point.

Fix up code editor empty state

---

enterprise/server/githubapp/githubapp.go

Auto-init new github repos if they're not created from a template

---

enterprise/app/code/code.css
enterprise/app/code/code_empty.tsx

Found these issues when testing in dev
- Limits the repo results to 5
- Fixes css

Fix new editor empty state

---

enterprise/app/code/BUILD
enterprise/app/code/code.tsx

Link to review UI (if enabled) from editor

---

deps.bzl
go.mod
go.sum

This version includes a patch where we log the hostnames if they changed.

[raft] use dragonboat 4.0.0-pre1.2

---

enterprise/server/raft/logger/logger.go
enterprise/server/raft/replica/replica.go
enterprise/server/raft/store/store.go

Add more logs to debug what happened when we rejoin clusters during startup.

[raft] more logs

---

enterprise/app/code/code.tsx

Make bgithub url work for pull requests

---

enterprise/server/remote_execution/containers/firecracker/firecracker.go
enterprise/server/remote_execution/containers/firecracker/firecracker_test.go
enterprise/server/remote_execution/executor/executor.go
enterprise/server/vmexec/vmexec.go
proto/vmexec.proto
server/interfaces/interfaces.go

Don't recycle VM if workspace device is still busy after unmounting

---

enterprise/server/tasksize/tasksize.go

Downgrade disk space warning to info.

---

enterprise/server/cmd/executor/executor_linux.go
enterprise/server/remote_execution/containers/podman/podman.go
server/util/networking/networking.go

Add executor option to blackhole traffic to private ranges.

---

enterprise/server/githubapp/githubapp.go

send file comment counts to client

---

docs/workflows-config.md

A frequently asked question is "how do I run bash scripts in workflows?" This PR adds a docs section explaining how to do this using Bazel commands.

Add docs for running shell scripts as bazel commands

---

app/components/button/checkbox_button.tsx
enterprise/app/review/BUILD
enterprise/app/review/review.css
enterprise/app/review/review_thread.tsx
enterprise/app/review/view_pull_request.tsx
enterprise/server/githubapp/githubapp.go
proto/github.proto

pop up a little dialog when replying to a pr

---

enterprise/server/hostedrunner/hostedrunner.go

The attached remote bazel error only occurs in prod. Add more descriptive error logging to zone in on the problem
**Related issues**: https://github.com/buildbuddy-io/buildbuddy-internal/issues/3263

[RB] Add more descriptive error messages

---

BUILD
server/xcode/xcode_darwin.go

Reverts buildbuddy-io/buildbuddy#6269

Revert "nogo: enable SA1024"

---

enterprise/app/review/review.css
enterprise/app/review/view_pull_request.tsx

Just a light-weight first pass. If there's anything you hate, lmk
Before:
After:

Review styling tweaks

---

enterprise/app/review/review.css

Hoping to satisfy @tylerwilliams's nostalgia a bit better here

Make the reply button red

---

server/metrics/metrics.go

Use finer-grained buckets for MySQL latency

---

release.py

Add a bit more logging to release.py

---

enterprise/server/raft/sender/sender.go

[raft] actually write shardStatementMap

---

proto/build_event_stream.proto
proto/failure_details.proto

Including changes from:
- https://github.com/bazelbuild/bazel/commit/12de6fb460436aa7f873da203b8803d2190e965b
- https://github.com/bazelbuild/bazel/commit/f4050eeddda520c8503eb1874bfd1ae08427cc8f

Update bazel proto

---

enterprise/server/test/integration/podman/podman_test.go

Fix auth issue in podman integration test

---

enterprise/app/usage/usage.tsx
enterprise/server/usage_service/usage_service.go
enterprise/server/usage_service/usage_service_test.go
proto/usage.proto

make GetUsageResponse.usage optional instead of repeated

---

website/src/pages/team.tsx

Remove old emails

---

docs/rbe-setup.md

Remove extra `=` from java toolchain docs

---

docs/prometheus-metrics-for-cloud.mdx

Add missing `:` to scrape config docs

---

cli/remotebazel/remotebazel.go

Reverts buildbuddy-io/buildbuddy#6283
This PR makes a [remote git fetch](https://github.com/buildbuddy-io/buildbuddy/blob/master/cli/remotebazel/remotebazel.go#L340). We are currently only [initializing access to the local git repo](https://github.com/buildbuddy-io/buildbuddy/blob/master/cli/remotebazel/remotebazel.go#L263) in the cli, so this remote git fetch will fail for private repos ([Thread](https://buildbuddy-corp.slack.com/archives/C04S4M5U3BK/p1712877290612589?thread_ts=1710888921.160789&cid=C04S4M5U3BK))
If we want the cli to have remote git access, we need to either [grant it access to use the local SSH agent](https://stackoverflow.com/questions/75510923/in-go-git-how-to-authenticate-using-the-ssh-agent) or use some other mechanism
Given that fetching the default branch is just …

Revert "workflows/remote-bazel: fix default branch not found"

---

enterprise/server/remote_execution/vmexec_client/vmexec_client.go

Don't log nil err

---

cli/remotebazel/BUILD
cli/remotebazel/remotebazel.go

**Related issues**: Fixes https://github.com/buildbuddy-io/buildbuddy-internal/issues/3226#issuecomment-2008324628

[RB] Use auth from bb login if set

---

enterprise/server/backends/distributed/distributed.go

remove unused variable that manages to trick go

---

app/terminal/ansi.tsx
app/terminal/row.tsx
app/terminal/text.tsx

Make terminal links clickable

---

app/router/router.tsx
enterprise/app/review/BUILD
enterprise/app/review/file_content.tsx
enterprise/app/review/pull_request_header.tsx
enterprise/app/review/review.css
enterprise/app/review/review.tsx
enterprise/app/review/review_controller.ts
enterprise/app/review/review_model.ts
enterprise/app/review/review_thread.tsx
enterprise/app/review/view_pull_request.tsx

add a view for a single file (kinda hacked up ui-wise)

---

release.py

Always skip latest tag when building arch-specific images

---

enterprise/server/githubapp/githubapp.go
enterprise/server/workflow/service/service.go
server/tables/tables.go

**Related issues**: https://github.com/buildbuddy-io/buildbuddy-internal/issues/3286

Start setting and respecting new `default_non_root_runner` column

---

cli/printlog/BUILD
cli/printlog/compact/BUILD
cli/printlog/compact/compact.go
cli/printlog/printlog.go

Preparation for up-coming stable sort support.

printlog: move exec log logic to new package

---

app/BUILD.bazel
enterprise/app/BUILD.bazel

re-disable splitting, still busted.

---

enterprise/app/code/code.css
enterprise/app/code/code.tsx
enterprise/app/code/code_build_button.tsx

- Make empty tabs look nice.
- Replace stray `setState` with `updateState`
- Syntax highlight based on file extension when loading from state
- Try different icon for build button

Small cosmetic editor tweaks

---

enterprise/app/review/review.css
enterprise/app/review/review_list.tsx
enterprise/server/githubapp/githubapp.go
proto/github.proto

Show PRs that dont require review as 'Mergeable' in reviews list.

---

server/util/rpcutil/BUILD
server/util/rpcutil/rpcutil.go
server/util/rpcutil/rpcutil_test.go

Fix rpcutil not respecting context cause arg

---

enterprise/server/githubapp/githubapp.go
proto/github.proto

remove some unused stuff on the pr search request

---

server/libmain/libmain.go

Found this when I was shamelessly copying this code.

Remove unnecessary err check in libmain.go

---

codesearch/searcher/BUILD
codesearch/searcher/searcher.go
codesearch/types/types.go
deps.bzl
go.mod
go.sum

Adds the searcher, which takes text queries, parses them, and queries the index for matching source files.

Add searcher implementation

---

.bazelrc

**Related issues**: https://github.com/buildbuddy-io/buildbuddy-internal/issues/3325

Turn off repo fetching worker

---

enterprise/server/remote_execution/executor/executor.go

Decrease default timeout to 8h and maximum allowed user-configurable timeout to 24h. Both are configurable as an executor flag.

Decrease default task timeout and maximum allowed timeout

---

server/tables/tables.go

mysql: explicitly set ALGORITHM=INPLACE, LOCK=NONE when creating new indexes

---

enterprise/app/review/file_content_monaco.tsx
enterprise/app/review/review.css
enterprise/app/review/review_model.ts
enterprise/app/review/review_thread.tsx
enterprise/app/review/view_pull_request.tsx

make comment creation interaction, like, good.

---

app/components/button/button.css
enterprise/app/review/review.css
enterprise/app/review/view_pull_request.tsx

Add expand all button to reviews page

---

enterprise/app/review/file_content_monaco.tsx

show comments in folded areas--still a little weird, but better than not

---

codesearch/query/BUILD
codesearch/query/regexp_query.go
codesearch/searcher/BUILD
codesearch/searcher/searcher.go
codesearch/types/types.go

This is all the same code but slightly re-arranged to separate concerns a bit.
These interfaces match my rough recollection of lucene / solr stuff from a long time ago so I think they generally make sense.

Break up searcher into query, scorer, and highlighter 

---

enterprise/app/code/BUILD
enterprise/app/code/code.tsx
enterprise/app/monaco/BUILD
enterprise/app/monaco/monaco.ts
enterprise/app/review/BUILD
enterprise/app/review/file_content_monaco.tsx

share logic for python-ish syntax highlighting between code and reviews ui

---

enterprise/server/raft/replica/replica_test.go

[raft] reduce repeated setup code in replica_test

---

enterprise/server/cmd/ci_runner/main.go

This will allow the server to start a ci_runner with a custom (kythe) action.

Allow ci_runner to execute a serialized action passed by flag

---

enterprise/server/raft/client/client.go
enterprise/server/raft/rangelease/rangelease_test.go
enterprise/server/raft/registry/registry_test.go
enterprise/server/raft/replica/replica.go
enterprise/server/raft/replica/replica_test.go
enterprise/server/raft/store/store.go
enterprise/server/raft/store/store_test.go

Remove dead code in raft.
Also moved GetMembership to store_test.go b/c it's only used in the test.

Remove dead code in raft

---

enterprise/app/review/BUILD
enterprise/app/review/file_content_monaco.tsx
enterprise/app/review/file_content_service.ts

will use this in a follow-up to preload the first few files in a PR, too.

Reuse monaco models via convenience function.

---

enterprise/server/cmd/cache_proxy/cache_proxy.go

Check if SSL service is enabled before trying to start gRPC services

---

enterprise/server/certgenerator/BUILD
enterprise/server/certgenerator/certgenerator.go

Make library visible to the internal repo for deployment.

Add http and monitoring ports for cert generator.

---

docs/workflows-config.md

Update buildbuddy.yaml docs

---

enterprise/server/workflow/service/service.go
proto/api/v1/workflow.proto
proto/workflow.proto
server/buildbuddy_server/buildbuddy_server.go

Clean up post https://github.com/buildbuddy-io/buildbuddy/pull/6308

Deprecate ExecuteWorkflowRequest.Clean field

---

app/invocation/invocation_timing_card.tsx

- **Reapply "timing_card: get profile from structured flag" (#6495)**
- **timing_card: fix filename detection**

timing_card: roll forward profile detection

---

tools/metrics/grafana/provisioning/deploy/datasources/datasources.yml

Update VictoriaMetrics datasource to use global server

---

app/invocation/invocation_action_card.tsx

Make the action timeline look more like a trace view.

action_card: make timeline offset base on start time

---

enterprise/server/cmd/ci_runner/main.go
enterprise/server/test/integration/ci_runner/ci_runner_test.go
enterprise/server/workflow/service/service.go

Also support not passing a target_repo_url

[ci_runner] Support only passing a commit sha and not a branch

---

enterprise/server/raft/leasekeeper/leasekeeper.go

raft: removed unused quit in leasekeeper

---

enterprise/server/raft/usagetracker/usagetracker.go

raft: remove unused const in usagetracker

---

enterprise/app/review/BUILD
enterprise/app/review/view_pull_request.tsx

making slow but steady progress on optimizing ui lag on load, so this is still slow, but it's at least better than it was before.

prefetch first 3 files in a review.
