server/version/BUILD
server/version/version.go

The commit and version keep getting set to UNKNOWN in version.go, ruining our app version metric. There seems to be a bug where x_defs does not consistently embed the data during releases.
In this commit we try another approach where we use a genrule that explicitly sets stamp = 1 and directly reads from bazel-out/stable-status.txt (described here: https://github.com/bazelbuild/bazel/issues/4942#issuecomment-1506315647)
There's some additional context at the bottom of this thread: https://buildbuddy-corp.slack.com/archives/C01D5GHRJ59/p1694026279817119

[Release] Fix version tag and commit not getting embedded correctly

---

deps.bzl

Which includes https://github.com/buildbuddy-io/soci-snapshotter/pull/14
**Related issues**: https://github.com/buildbuddy-io/buildbuddy-internal/issues/2570

Update soci-store versions to 0.0.10

---

WORKSPACE
cli/test/integration/cli/BUILD
enterprise/server/test/integration/ci_runner/BUILD
enterprise/server/test/integration/workflow/BUILD

Reverts buildbuddy-io/buildbuddy#4735
It might breaker the server/testutil/webtester/webtester.go
https://app.buildbuddy.io/invocation/e629172c-a4dc-4ff1-b0a0-8928771b16ac

Revert "Upgrade bb toolchain to get `dockerNetwork=off`"

---

enterprise/server/backends/pebble_cache/pebble_cache.go
server/metrics/metrics.go

When we turn on migration cache, we want to be able to seperate metrics from src
and dest pebble cache.

add cache name label to pebble cache metrics

---

enterprise/server/backends/authdb/authdb.go
server/role_filter/role_filter.go

The API will be called after impersonation is already in effect in which case we can't rely on checking admin group membership.
Instead check the impersonation bit, which can only be set for authenticated admins.

Modify impersonation api key permission check.

---

enterprise/server/remote_execution/nbd/nbdclient/nbdclient.go

atime will cause file metadata to be updated whenever files are read from, which will cause lots of unnecessary writes.

Disable atime for NBD mounted filesystems

---

BUILD
buildbuddy.yaml

Have seen a 4xx error in a little bit. Will re-add if it crops up again.
**Related issues**: https://github.com/buildbuddy-io/buildbuddy-internal/issues/2357

Remove private image workflow

---

cli/ask/ask.go

Changes the flag location from
```
~/.cache/last_bb_{name}_{workspaceHash}.txt
```
to
```
~/.cache/buildbuddy/last_flag_values/{workspaceHash}/{name}.txt
```
this makes it easier to clear the CLI cache - just `rm -rf ~/.cache/buildbuddy`

Save last CLI flag value under buildbuddy subdir

---

enterprise/server/backends/authdb/authdb.go
enterprise/server/backends/userdb/userdb.go
enterprise/server/cmd/server/BUILD
enterprise/server/cmd/server/main.go
enterprise/server/iprules/BUILD
enterprise/server/iprules/iprules.go
enterprise/server/iprules/iprules_test.go
enterprise/server/testutil/enterprise_testauth/enterprise_testauth.go
proto/BUILD
proto/iprules.proto
server/environment/environment.go
server/interfaces/interfaces.go
server/real_environment/real_environment.go
server/tables/tables.go
server/testutil/testauth/testauth.go
server/util/claims/claims.go

There's a new group-level settings that determines whether IP rules are applied.
Currently, IP rules are a simple unordered list of allowed IP ranges.
IP rules are cached to avoid having to load them for every request.
Next PR hooks up the service for enforcement.

Add IP rules service for manipulating and checking IP rules.

---

tools/metrics/grafana/dashboards/buildbuddy.json

Used vim to check metrics without region filters. We only have some
raft-related metrics without the region filter, plus "Disk Cache Duplicate Writes"
(which we don't populate the metrics anymore)
Add region filters to raft-related metrics
Delete "Disk Cache Duplicate Writes" graph
Delete another unused graph (RPCs by Quota Key) while I'm at it.

Add region filter and delete unused graphs

---

enterprise/app/trends/BUILD
enterprise/app/trends/cache_chart.tsx
enterprise/app/trends/percentile_chart.tsx
enterprise/app/trends/simple_trends_tab.tsx
enterprise/app/trends/trends.tsx
enterprise/app/trends/trends_chart.tsx
enterprise/app/trends/trends_model.ts
package.json

this is prep work for making the trends charts all support sub-day entries.  i'm using a slightly-but-not-too-clever trick to make date strings keep working (so that we can keep supporting non-clickhouse without much headache)

use timestamps instead of strings in trends fe code

---

enterprise/app/repo/repo.tsx
enterprise/server/githubapp/BUILD
enterprise/server/githubapp/githubapp.go
proto/repo.proto

Also squashes template commit history into a single commit, so as not to clutter the git history of the newly created repo.

Support subdirectory templates in repo flow

---

enterprise/app/trends/BUILD
enterprise/app/trends/cache_chart.tsx
enterprise/app/trends/common.ts
enterprise/app/trends/new_trends.tsx
enterprise/app/trends/percentile_chart.tsx
enterprise/app/trends/simple_trends_tab.tsx
enterprise/app/trends/trends.tsx
enterprise/app/trends/trends_chart.tsx
enterprise/app/trends/trends_model.ts

Still some changes to make clicks work for sub-day values, etc., but despite all appearances this is intended to have no visible effect in prod.

frontend code for sub-day trends intervals.

---

go.mod
go.sum

We have it in WORKSPACE already, but set it to 1.21 in go.mod so that we can start using the new language features without editor warnings.

Set go 1.21 in go.mod

---

cli/add/add.go
cli/translate/yaml/yaml.go

Previously bb add would always just fetch the latest version of a dependency

Support specifying version numbers when using `bb add`

---

cli/fix/BUILD
cli/fix/golang/BUILD
cli/fix/golang/golang.go
cli/fix/language.go

This interface includes extra methods for gazelle languages that can be used to automatically generate WORKSPACE / MODULE files for the language.
Included in this PR is an implementation of this interface for gazelle's built-in golang language implementation.

Add Language interface used for WORKSPACE generation

---

WORKSPACE
cli/test/integration/cli/BUILD
enterprise/server/test/integration/ci_runner/BUILD
enterprise/server/test/integration/workflow/BUILD
enterprise/server/test/webdriver/invocation/BUILD
rules/webdriver/index.bzl

Added `test.dockerNetwork=bridge` to the webdriver test to fix it. Also change `dockerNetwork` => `test.dockerNetwork` so that only the test actions get networking, not the actions that build the tests.

Roll-forward "Upgrade bb toolchain to get `dockerNetwork=off`"

---

enterprise/server/iprules/BUILD
enterprise/server/iprules/iprules.go
server/http/interceptors/interceptors.go
server/http/protolet/protolet.go
server/interfaces/interfaces.go
server/libmain/libmain.go
server/metrics/metrics.go
server/role_filter/role_filter.go
server/rpc/interceptors/interceptors.go

- For HTTP, check all requests except GetUser which will be used to inform the frontend as to whether user has access to the target group.
I removed the HTTP Path prefix stripping from the interceptors so that it's always possible for interceptors to know the requested URI.
- For gRPC all requests are checked.

Incorporate IP access check into interceptors.

---

app/auth/BUILD
app/auth/auth_service.ts
app/auth/user.ts
app/router/BUILD
app/router/router.tsx
enterprise/app/org/BUILD
enterprise/app/org/org_access_denied.tsx
enterprise/app/root/root.tsx
enterprise/app/sidebar/BUILD
enterprise/app/sidebar/sidebar.tsx
proto/user.proto
server/buildbuddy_server/buildbuddy_server.go

Use it to communicate if the user has selected a group that they have access to but cannot access due to IP rules. Also use the same mechanism for communicating subdomain access issues.
Update UI to show a minimal sidebar if user doesn't have access to the selceted group so that the user still has access to the group switcher.

Use GetUser to communicate if user can't access selected group.

---

enterprise/server/remote_execution/blockio/BUILD
enterprise/server/remote_execution/blockio/blockio.go
enterprise/server/remote_execution/blockio/blockio_test.go
enterprise/server/remote_execution/containers/firecracker/firecracker.go
enterprise/server/remote_execution/nbd/nbdserver/nbdserver.go
enterprise/server/remote_execution/nbd/nbdserver/nbdserver_test.go
enterprise/server/remote_execution/snaploader/BUILD
enterprise/server/remote_execution/snaploader/snaploader.go
enterprise/server/remote_execution/snaploader/snaploader_test.go
server/interfaces/interfaces.go

Given that we are only using the COW store for one use case, remove the various interfaces and nested structs for simplicity

[Remote Snapshot] Simplify structure of snaploader and cow code

---

enterprise/server/remote_execution/containers/firecracker/BUILD
enterprise/server/remote_execution/containers/firecracker/firecracker.go
enterprise/server/remote_execution/copy_on_write/BUILD
enterprise/server/remote_execution/copy_on_write/copy_on_write.go
enterprise/server/remote_execution/copy_on_write/copy_on_write_test.go
enterprise/server/remote_execution/nbd/nbdserver/BUILD
enterprise/server/remote_execution/nbd/nbdserver/nbdserver.go
enterprise/server/remote_execution/nbd/nbdserver/nbdserver_test.go
enterprise/server/remote_execution/snaploader/BUILD
enterprise/server/remote_execution/snaploader/snaploader.go
enterprise/server/remote_execution/snaploader/snaploader_test.go
enterprise/server/remote_execution/uffd/BUILD
enterprise/server/remote_execution/uffd/uffd.go

Now that this package only has structs dealing with copy-on-write, rename it to reflect that. Also change ordering of the file so that the COWStruct is defined at the top (preference thing where I find it easier to read a file if the main struct is defined first).

[Remote Snapshot] Rename copy on write package

---

enterprise/server/remote_execution/containers/podman/podman.go

If `executor.podman.transient_store` is false then don't pass the flag to podman at all. This makes it so that if an older podman version is installed, the executor can still run (I hit this issue on a GCP VM today).

Fix `--transient-store=false` flag breaking older podman versions

---

enterprise/server/remote_execution/platform/platform.go

When the `default_isolation_type` flag is unspecified, it currently defaults to the first of `docker, firecracker, podman, none`.
This PR changes the ordering to be `docker, podman, firecracker, none`, swapping podman and firecracker. This way, we don't have to explicitly set `default_isolation_type=podman` when both podman and firecracker are enabled. It also intuitively makes more sense this way since docker and podman are the same "class" of isolation (OCI container).
I hit this while trying to run a local executor within a GCP VM while trying to reproduce an issue, and had both podman and firecracker enabled. I was surprised to see that build actions were trying to use firecracker by default.

Swap order of podman and firecracker in default isolation type list

---

enterprise/server/cmd/goinit/main.go
enterprise/server/remote_execution/nbd/nbdclient/nbdclient.go
enterprise/server/vmexec/vmexec.go

This will prevent other goroutines in the init / vmexec binaries from deadlocking with the NBD handler (due to the binary + handler contending for the same OS thread resource). This should reduce the occurrence of these occasional "possible stuck request" bugs.

Run NBD clients in dedicated processes

---

enterprise/server/remote_execution/containers/firecracker/firecracker.go
enterprise/server/remote_execution/nbd/nbdserver/nbdserver.go

Not sure if this was actually happening or was causing problems, but before saving snapshots we should ensure that any in-progress writes to disk COWStores are complete, by calling `GracefulStop()` (which waits for RPCs to complete, vs. `Stop()` which just cancels contexts).
We already do something similar for the UFFD handler, so it makes sense to do it for the NBD server too.

Guard against possible data race with NBD server + snapshotting

---

WORKSPACE
deps.bzl
tools/fix_go_deps.sh
tools/update_deps.sh

This change:
1) Allows us to have different functions for different language ecosystems (i.e. install_package_json_dependencies, etc)
2) Makes it easier for automated tooling to generate this function name (i.e `install_%s_dependencies` where %s is the name of the file where the dependencies came from). 
I have a separate change do to the same in the internal repo.

Rename `install_buildbuddy_dependencies` => `install_go_mod_dependencies`

---

WORKSPACE

Right now we're just lucky this gets imported transitively by one of our other dependencies.
We use it here, but never explicitly import it:
https://github.com/buildbuddy-io/buildbuddy/blob/master/proto/BUILD#L1

Add explicit `rules_proto` dependency to WORKSPACE

---

dockerfiles/executor_image/Dockerfile

Since `docker-credential-gcr` is installed, I figure installing the cred helper for AWS ECR would be good too.
I tried to test this but I wasn't able to pull from gcr.io/cloud-marketplace. Even after changing to docker:11 though, I ran into an error installing docker-ce.

Install amazon-ecr-credential-helper in executor

---

enterprise/server/backends/pebble_cache/pebble_cache.go
enterprise/server/backends/pebble_cache/pebble_cache_test.go
enterprise/server/util/chunker/chunker.go

Run the server locally with --@io_bazel_rules_go//go/config:race, turn on
cdc with pebble cache, and then run a build (e.g. //app/...)  against the local 
bb server triggers DATA RACE and 0 chunk errors
I added a test where we cancel the context before writing any data. It can reproduce both the data race and 0 chunk error. 
- Add mutex in `cdcWriter` to protect writtenChunks and numChunks.
- In commit, instead of calling `cdcw.Close()` we call `cdcw.chunker.Close()`. In `cdcw.Close()` we ignore the error from `cdcw.chunker.Close()`. It causes us to attempt to write 0 chunks if we cancel the context before any data is written. Returning `cdcw.chunker.Close()` in `cdcw.Close()` doesn't work because we call cdcw.Close() twice: once in CommitFn and once when we close …

Fix 0 chunk error

---

enterprise/server/backends/migration_cache/config.go
enterprise/server/backends/migration_cache/migration_cache.go
enterprise/server/backends/pebble_cache/pebble_cache.go

Need to delete the cdc cache to restart migration in prod/dev

add a flag in migration cache to clear pebble cache on start up

---

enterprise/server/githubapp/BUILD
enterprise/server/githubapp/githubapp.go

In https://github.com/buildbuddy-io/buildbuddy/pull/4779 the default branch was unintentionally switched to `master`.

Create new repos with `main` as the default branch

---

enterprise/server/backends/migration_cache/migration_cache.go

Right now we extend the deadline when we enqueue the copy. But by the time we dequeue it and process it, the timeout might be close to be expired. This will lead to copy error warning.

extend deadline when we actually process copy

---

server/backends/memory_metrics_collector/memory_metrics_collector.go

We received a crash report with
```
fatal error: concurrent map iteration and map write
goroutine 1779257345 [running]:
github.com/buildbuddy-io/buildbuddy/server/remote_cache/hit_tracker.ScoreCard({0x23e6608, 0xc0bae78f00}, {0x2405988?, 0xc000895680?}, {0xc0cf58aed0, 0x24})
server/remote_cache/hit_tracker/hit_tracker.go:564 +0x2b1
github.com/buildbuddy-io/buildbuddy/server/build_event_protocol/build_event_handler.LookupInvocation.func1()
server/build_event_protocol/build_event_handler/build_event_handler.go:1235 +0x6b
...
```
so let's ensure that we do not return the map directly from LRU but a
copy of it to avoid race conditions.

mem_metrics_collector: return a copy of the map on ReadCounts

---

enterprise/server/githubapp/githubapp.go

We don't have permission to create this directory (since we don't ask for workflow permissions).

Remove .github/workflows directory when creating repo from template

---

enterprise/server/remote_execution/containers/firecracker/firecracker.go
enterprise/server/remote_execution/snaploader/BUILD
enterprise/server/remote_execution/snaploader/snaploader.go
enterprise/server/remote_execution/snaploader/snaploader_test.go
proto/firecracker.proto

For remote snapshot sharing, we will need to represent snapshot metadata as an ActionResult in order to save it to the action cache.
When fetching action results, our existing architecture will validate that all referenced digests have not been evicted from the cache. We can take advantage of this to validate that our snapshots are valid and all necessary artifacts are still in the cache
Also remove the DeleteSnapshot function. When we are storing snapshot artifacts remotely, we can rely on the remote cache to evict LRU elements. Snapshot chunks can be reused by other snapshots, so we won't want to delete all associated artifacts

[Remote Snapshot] Refactor snaploader to represent snapshot metadata using an ActionResult

---

enterprise/server/saml/BUILD
enterprise/server/saml/saml.go

This handling was broken by: https://github.com/buildbuddy-io/buildbuddy/commit/4e1c317d3d8d33b5316d9f1f96c573607d5164cf

Handle ErrNoSession errors correctly in SAML flow

---

enterprise/server/backends/pebble_cache/pebble_cache.go
enterprise/server/raft/replica/replica_test.go
enterprise/server/raft/store/store.go
enterprise/server/util/pebble/pebble.go
enterprise/server/util/pebble/pebble_test.go
server/metrics/metrics.go

During cache migration, it's helpful to see the pebble op metrics separated by
cache names.

seperate pebble op metrics by different instances

---

app/format/format.tsx
enterprise/app/filter/filter_util.tsx
enterprise/app/trends/summary_card.tsx
enterprise/app/trends/trends.css

This fixes it so that we show "6 hours" instead of "1 day" if you only have 6 hours selected, etc.  Really, this UI should probably change a bit when the ranges are so small but that's talk for later.

Fix summary text for sub-day time ranges.

---

enterprise/server/backends/migration_cache/config.go
enterprise/server/backends/migration_cache/migration_cache.go

In early stages of migration while we are backfilling from source cache, we need
the ability to rate limit writes to destination cache to avoid overwhelming the
destination cache which causes Write latency goes up and compaction debt goes up
for example.
Also in this PR, I used mc.Writer() to implement Set() method to make the logic
simpler and also allow us to write data in background in the Set() method.

Add an option to rate limit writes in migration cache

---

enterprise/server/cmd/ci_runner/main.go
enterprise/server/test/integration/ci_runner/ci_runner_test.go
enterprise/server/workflow/config/config.go

This PR allows users to disable the default "merge-with-base" behavior in workflows by setting `merge_with_base: false` in the `pull_request` config:
```yaml
actions:
- name: Test
triggers:
pull_request:
branches: [ "*" ]
merge_with_base: false  # New option; defaults to true (for now) if not configured explicitly.
bazel_commands:
- ...
```

workflows: add an option to disable merging with base branch

---

app/format/format.tsx
enterprise/app/trends/cache_chart.tsx
enterprise/app/trends/percentile_chart.tsx
enterprise/app/trends/trends_chart.tsx

- Let "overflowed" reference areas render as a workaround for a really weird recharts bug (it sometimes thinks that the last cell in the chart is outside of the y axis for very specific combinations of window width + number of bars in the chart, seemingly a floating point error)
- Fix date range rendering in an edge case: show "Sep 18" instead of "Sep 18-19" when the selected time range is Midnight Sep 18 - Midnight Sep 19

two date range selection bug fixes

---

app/router/router.tsx
enterprise/app/trends/cache_chart.tsx
enterprise/app/trends/percentile_chart.tsx
enterprise/app/trends/simple_trends_tab.tsx
enterprise/app/trends/trends.tsx
enterprise/app/trends/trends_chart.tsx

currently, these clicks do worse than nothing--if the date range doesnt change, they just push an extra entry onto the history stack for the user to back up through.
this makes these bars go straight to the build history page, which is maybe not the *most* intuitive thing, but it's definitely better than what we've got now.

make clicks on smallest-possible buckets go directly to build history

---

enterprise/app/trends/trends.tsx

We should be showing the summary in the vast majority of cases in prod at this point (i.e., the user needs to choose a 6-month date range and refresh the page or something like that), so this seems like a better default than the opposite.

Add a bogus trendsSummary for initial loading to keep layout steady

---

enterprise/server/backends/prom/prom.go
enterprise/server/usage/BUILD
enterprise/server/usage/usage.go
server/metrics/metrics.go
server/remote_cache/hit_tracker/hit_tracker.go

This covers Action cache hits, CAS hits, total bytes downloaded from cache,
total bytes uploaded to cache.
Add new counter metrics instead of using the existing histogram since I need to add group id label and don't want to increase cardinality.

Export Cache Usage data to consumers via prometheus

---

enterprise/app/trends/drilldown_page.tsx
enterprise/app/trends/trends.tsx

- don't round heatmap start date to start-of-day.  this is obsolete now that we've changed "last 30 days" to "midnight 30 days ago".  all it does now is make the heatmap look weird when the user picks "14:05-14:10" and it shows "00:00-14:10" instead.
- use `navigateTo` when switching trends tabs so that drilldown params get blown away--this prevents weirdness when going back and forth between charts + heatmap (e.g., if you switch the date selection on the charts page, the "selected" area might "not include builds" anymore).

two minor interaction improvements for the drilldowns page.

---

.bazelrc

This flag changes the name of output directories under `bazel-out/*` to
contain the platform information. This means that if a user were to
switch between a local build and a remote build
using `--config=remote-target-linux`, they would be able to retain the
output from both configs.
Also disabling `experimental_repo_remote_exec`. This flag is meant to
allow repository rules, when marked with `remotable = True` to be
executed remotely with RBE. The main purpose of this is to allow
toolchains to probe remote execution platforms information to setup
appropriate toolchains and paths. We do not use this effect in our
repository anywhere, however it will make us re-run all repository rules
when toggle between `--config=remote-target-linux` build and local build.

bazelrc: remote-target-linux use platform in output dir, stop repo RE

---

buildpatches/com_github_firecracker_microvm_firecracker_go_sdk_jailer.patch
deps.bzl
enterprise/server/remote_execution/containers/firecracker/firecracker.go

Instead of having firecracker-go-sdk hardlink files into the chroot for us, we now create the files directly in the chroot. This is required in order to use FUSE for the disk image files, since the SDK's hardlink attempt would fail as it crosses filesystem boundaries. It also results in simpler code - the current `tempDir` approach was purely working around the SDK's hardlinking behavior.
This requires patching the go SDK to skip hardlinking in the case where the file is already inside the chroot. I have sent https://github.com/firecracker-microvm/firecracker-go-sdk/pull/510 to upstream the patch.

firecracker: simplify chroot provisioning

---

enterprise/server/remote_execution/containers/podman/podman.go

When re-using podman containers, we shouldn't set the `--network` flag because the `podman exec` command doesn't take the flag like `podman run` does (`podman create` does instead).

Don't set `--network` flag on podman exec

---

tsconfig.json

In #4769, we make it so that `--config=target-linux` would store outputs
in a new dir with name includes the platform information.
Include this new dir schema in tsconfig.

tsconfig: update rootdirs for target-linux

---

app/root/root.css
enterprise/app/root/root.css
enterprise/app/root/root.tsx

* Enable flex-wrap
* Make it less verbose on mobile and hide the API key button (it's probably impractical to actually use an API key on mobile)
Screenshot (simulating `iPhone 12 Pro` screen dimensions)

Fix impersonation bar styling

---

enterprise/server/remote_execution/containers/firecracker/BUILD
enterprise/server/remote_execution/containers/firecracker/README.md
enterprise/server/remote_execution/containers/firecracker/bench.sh
enterprise/server/remote_execution/containers/firecracker/test.sh
tools/buildozer.sh

Testing requires `mount()` privileges once we enable VBD. Add some scripts to make this slightly less painful.

Add scripts to test/bench firecracker locally

---

server/util/networking/networking.go

This isn't actually a bug because `route` is an empty `route{}` rather than `nil` but the existing code just seemed error prone.

Improve error handling in EnableMasquerading

---

enterprise/server/util/ext4/ext4.go

`du -k` uses 1K = 1024 bytes (IEC), not 1000 bytes (SI).
This fixes an issue that `alpine` fails to be converted to ext4.

Fix disk size calculation in `DirectoryToImageAutoSize`

---

server/util/uuid/uuid.go

Fixes: https://github.com/buildbuddy-io/buildbuddy-internal/issues/2728

Allow executor host_id to be manually specified via config option / flag

---

enterprise/server/backends/pebble_cache/pebble_cache.go
enterprise/server/backends/pebble_cache/pebble_cache_test.go
enterprise/server/util/chunker/chunker.go

Close pr instead of pw in the chunker on context cancellation.
pw.Write() returns "io: read/write on closed pipe" if pw is already closed.
However, if we close the pr with ctx.Err(), then pw.Write() will return the
given error. 
We also need to let Chunker.Close() return an error if the context
is cancelled, so that Commit() in pebble cache will return early and not writing
0 chunk to pebble.

Close pr on cancel in chunker

---

enterprise/server/auth/BUILD
enterprise/server/auth/auth.go

Right now we are only returning the first error for all the
authenticator errors. However, since we always configure OIDC
authenticator, only OIDC authenticator error is returned.
This is fine from user perspective, but from the sysadmin / operation
perspective, we have no way to verify whether the issue is coming from
SAML or Github authenticator to troubleshoot.
Log out the errors to help aid troubleshooting.

auth: log auth errors

---

WORKSPACE
docs/rbe-github-actions.md
docs/rbe-setup.md

Update our toolchain in docs according to the one we are using in
WORKSPACE.

docs/rbe-setup: update buildbuddy-toolchain

---

enterprise/server/iprules/iprules.go
enterprise/server/iprules/iprules_test.go

- Don't enforce IP rules for GetGroup API as it's now used for impersonation.
- AuthorizeGroup should check the impersonation bit, like Authorize does.

IP rule impersonation fixes.

---

enterprise/tools/replay_action/BUILD
enterprise/tools/replay_action/replay_action.go

Improvements:
* Migrate off of deprecated `github.com/golang/protobuf/proto` package.
* Add `-n` and `-jobs` flags to allow replaying the action several times, optionally in parallel.
* Print action stdout and stderr (only when `n=1`, to avoid spamming the console)
* Instead of traversing the input directory tree using chained RPCs, use `GetTree`.
* Instead of having to pass `-skip_copy_files` on replay attempts after the first attempt, use `FindMissingBlobs` to check whether blobs need to be re-uploaded. Adds a `FindMissingBatcher` to transparently batch the digest existence checks.

Move replay_action to OSS, with some improvements

---

enterprise/server/test/integration/remote_execution/rbetest/rbetest.go
server/remote_cache/cachetools/cachetools.go

This should fix `tools/cas` not being able to fetch blake3 action results.

Fix a few more AC requests missing DigestFunction

---

enterprise/server/remote_execution/containers/firecracker/firecracker.go
enterprise/server/remote_execution/uffd/uffd.go

Before this PR, when we encountered a UFFD failure, we'd wait for several seconds trying to dial the VM, then eventually time out with "deadline exceeded", and the UFFD error would be logged to the console instead of getting surfaced as the root cause of the dial error.
Now, UFFD failures immediately cause any pending VM operations to be cancelled and the UFFD errors are surfaced directly.
* If the UFFD handler fails to handle a page fault, cancel the VM context immediately, setting the cancel cause to the UFFD error.
* Update `Exec`, `Pause`, and `Unpause` to make their `ctx` track the VM context, so that as soon as the VM ctx is cancelled, their ctx gets cancelled too (with the same cause as the VM ctx cancellation).

Immediately propagate UFFD errors instead of waiting for timeout

---

enterprise/server/remote_execution/containers/docker/BUILD
enterprise/server/remote_execution/containers/docker/docker_test.go

Instead of hoping the docker action will complete within 1 second, wait for an explicit signal that the action is done (specifically, wait for output.txt to be created). Also give a little bit of time for the stdout/stderr written by the action to be flushed to docker logs and for us to collect the output from the logs.

Deflake docker_test

---

app/capabilities/capabilities.tsx
app/service/BUILD.bazel
app/service/rpc_service.ts
enterprise/app/executors/executors.tsx
proto/config.proto
server/http/interceptors/BUILD
server/http/interceptors/interceptors.go
server/static/BUILD
server/static/static.go
server/util/region/BUILD
server/util/region/region.go

Decided to just fetch executors in parallel from each region and display them for now. We can add a dropdown once the number of regions gets higher.
Probably still need to set a CORS header that includes these regions, but that's tough to test locally.

Support fetching executors from multiple regions

---

enterprise/server/backends/pebble_cache/pebble_cache.go
enterprise/server/util/cacheproxy/cacheproxy.go
server/remote_cache/byte_stream_server/byte_stream_server.go
server/util/bytebufferpool/bytebufferpool.go
server/util/bytebufferpool/bytebufferpool_test.go

When buffers are returned, look at the capacity instead of the length to make sure the buffers are returned to the right bucket. There's at least one codepath where the buffer is returned with a smaller length.
Since we're now looking at the capacity instead of the length, we can automatically return buffers of the correct length instead of asking callers to do it.

Make bytebufferpool less error-prone.

---

enterprise/server/remote_execution/uffd/uffd.go

We call Wait in a background thread in firecracker to check if the handler has shut down early due to an error. We call Stop() when we are explicitly telling the handler to shut down, for example if we are pausing the VM. There is a race condition where Stop might try to set handleDoneChan=nil at the same time that the background Wait thread is trying to read it.

Fix UFFD race condition between Wait and Stop

---

enterprise/server/backends/pebble_cache/pebble_cache.go
enterprise/server/backends/pebble_cache/pebble_cache_test.go
enterprise/server/raft/filestore/filestore.go

Only scan AC keys if "fix missing files" is not enabled. Make "fix missing files" off by default.

Scan less keys in background repair.

---

server/build_event_protocol/accumulator/accumulator.go
server/build_event_protocol/build_event_handler/build_event_handler.go

No client behavior change in this one (i.e., we're still just kind of assuming that the first entry with a uri in BuildToolLogs is the profile, which does seem to work but doesn't seem to be guaranteed in the protocol.)

Store all files from BuildToolLogs events

---

app/service/rpc_service.ts
server/http/interceptors/BUILD
server/http/interceptors/interceptors.go

Execution graph debug info (`--experimental_execution_graph_log`) writes out a zstd-compressed file, which we want to get to the client, but browsers can't handle zstd over the wire... yet.  Doing this server-side, where we already have support for it, seems way better than taking some weird js dep.

add "zstd" option for X-Stored-Encoding-Hint

---

enterprise/server/sociartifactstore/BUILD
enterprise/server/sociartifactstore/sociartifactstore.go
enterprise/server/sociartifactstore/sociartifactstore_test.go

This PR changes the format of the image-to-SOCI-index that's stored in the ActionCache. Previously, a cache entry was written using the rehashed, salted image's config hash as the key and the serialized digest of the SOCI index as the value. However, this had a few drawbacks including increased difficulty debugging the ActionCache entries using the ActionCacheServer APIs and requiring multiple trips to the cache to unpack a SOCI index. This PR changes the image-to-index mapping to be stored as an ActionResult with all of the SOCI artifacts (index and ZToCs) stored as OutputFiles with a NodeProperty denoting their type. This should address both shortcomings mentioned previously.

Store the image-to-SOCI-index mapping as an ActionResult

---

server/util/region/BUILD
server/util/region/region.go
server/util/region/region_test.go

Currently CORS works correctly when making a request from https://app.buildbuddy.io to https://app.europe.buildbuddy.io
This adds support for making requests from https://my-org.buildbuddy.io to https://app.europe.buildbuddy.io

Support CORS for org subdomains

---

enterprise/server/remote_execution/containers/firecracker/BUILD

There are some problems with the blockio setup (UFFD + VBD enabled) that are causing the tests to run forever. This is causing the bare executor pool to have a huge queue. Disable the tests for now as we fix things.

Disable firecracker blockio tests

---

enterprise/server/backends/pebble_cache/pebble_cache.go
enterprise/server/raft/filestore/BUILD
enterprise/server/raft/filestore/filestore.go
enterprise/server/raft/filestore/filestore_test.go

The reason for introducing this key format change is to simplify key eviction for AC entries.
All keys would look like:
```
//"PTFOO/9c1385f58c3caf4a21a2626217c86303a9d157603d95eb6799811abb12ebce6b/1/cas/v5"
//"PTFOO/647c5961cba680d5deeba0169a64c8913d6b5b77495a1ee21c808ac6a514f309/9/ac/v5"
//"PTFOO/9c1385f58c3caf4a21a2626217c86303a9d157603d95eb6799811abb12ebce6b/9/cas/EK123/v5"
//"PTFOO/647c5961cba680d5deeba0169a64c8913d6b5b77495a1ee21c808ac6a514f309/1/ac/EK123/v5"
```

Add support for v5 keys

---

server/rpc/interceptors/interceptors.go

This interceptor shouldn't be able to override context values set by other interceptors.

Move "copy headers" interceptor earlier in the order.

---

enterprise/server/raft/cache/cache.go
enterprise/server/raft/rangecache/BUILD
enterprise/server/raft/rangecache/rangecache.go
enterprise/server/raft/rangecache/rangecache_test.go
enterprise/server/raft/sender/sender.go
enterprise/server/raft/store/store.go
enterprise/server/raft/store/store_test.go

Explicitly disable event quiescing so there's no delay when advertising the metarange.

Send metarange via user event

---

enterprise/server/remote_execution/containers/firecracker/firecracker.go

Networking cleanup failures are preventing us from recycling runners and customers are seeing slow workflows. See [thread](https://buildbuddy-corp.slack.com/archives/C0495TM9UUE/p1695740849246189) for more info.
I realized that because we are returning the lastErr in cleanupNetworking, it's not guaranteed that DeleteRuleIfSecondaryNetworkEnabled is actually the culprit. I added more debug logging to clarify which rule the context is being canceled for.
Also dump the vm logs on failure to see if there's any useful debug info
I also checked to make sure that VM setup won't break if we fail to clean up networking. 
* The opposite of `DeleteRuleIfSecondaryNetworkEnabled` is `ip rule add from cloneIP lookup routingTableName` - this is idempotent and can be rerun multiple times, even if the …

[FC] Don't prevent runner recycling if networking cleanup fails

---

enterprise/server/remote_execution/containers/podman/podman.go

Podman **always** uses the additional layer stores specified in storage.conf, so writing this means that running the executor with `--executor.podman.enable_image_streaming=true` and `--executor.podman.enable_private_image_streaming=false` will cause podman to hit the additional layer store for all images (including private ones), generating a bunch of not found logs in the soci-store.

Remove the additionallayerstore argument from storage.conf so per-image streaming works correctly.

---

enterprise/server/raft/listener/BUILD
enterprise/server/raft/listener/listener.go
enterprise/server/raft/store/store.go

this is pt1 of 2, the second part actually makes uses of the channels to update rangeleases as soon as leadership changes.

Use channel instead of callback to communicate leadership changes

---

.bazelrc
template-user.bazelrc

Also ensure that C++17 is passed to compiler for all configurations:
exec(host_cxxopt) and others(cxxopt).

bazelrc: support windows specific configs

---

cli/parser/parser.go

Since we do a custom parse of the `.bazelrc`, we need to handle the `--enable_platform_specific_config` specially, as it is supposed to be equivalent to `--config=<os>`. This PR substitutes the last instance of this flag, if it is set to true, with the appropriate `--config` option immediately before we do `--config` substitution.

Fix cli to work with `--enable_platform_specific_config`

---

enterprise/server/remote_execution/containers/firecracker/firecracker.go

Networking cleanup failures are preventing us from recycling runners and customers are seeing slow workflows. Based on logs so far, the errors come from trying to delete ip routes that don't exist.
Related: #4924

[FC] Don't fail firecracker cleanup if networking route doesn't exist

---

enterprise/server/backends/pebble_cache/pebble_cache.go
server/metrics/metrics.go

Right now these metrics are only available in statusz page, and it's difficult
to monitor the trend.

Add pebble write stall metrics to prom

---

enterprise/server/backends/pebble_cache/pebble_cache.go

Store chunks outside of pebble if they are bigger than maxInlineFileSizeBytes. 
When tested locally, the eviction latency doesn't spike, the eviction rate don't
plateaued and can get to about the same as the current rate in production, no
compaction debt accumulated.

Store chunks outside of pebble

---

enterprise/server/remote_execution/containers/firecracker/firecracker.go

Revert silently ignoring networking cleanup errors so we don't un-intentionally start leaving a lot of trash behind on the executors.
Based on logs in dev, networking cleanup errors come from trying to delete ip routes that don't exist. This should fix that: #4937
**Related issues**: #4924

[FC] Propogate networking cleanup errors

---

.bazelrc
BUILD
WORKSPACE
buildpatches/com_github_awslabs_soci_snapshotter.patch
cli/testutil/testcli/testcli.go
deps.bzl
enterprise/server/cmd/goinit/BUILD
enterprise/server/remote_execution/containers/firecracker/firecracker_test.go
enterprise/server/test/integration/ci_runner/ci_runner_test.go
go.mod

Adds `hermetic_cc_toolchain` as the new toolchain for C and C++ compilation. Patches `soci-snapshotter` to depend on `zlib`. Adds build options to `.bazelrc` to perform static linking and an [ASLR-able binary](https://stackoverflow.com/questions/61553723/whats-the-difference-between-statically-linked-and-not-a-dynamic-executable).
Edits: Does not work on Mac. Could not build PIE-able code without crashing the race detector during analysis, so no ASLR.

Use hermetic_cc_toolchain to statically link against musl

---

enterprise/server/remote_execution/containers/firecracker/firecracker.go
enterprise/server/remote_execution/snaploader/snaploader.go
server/metrics/metrics.go

We'd expect to see fewer dirty chunks with recycled VMs. Without this field, it's harder to interpret the data.

[Remote Snapshot] Add recycled runner status to dirty chunk metrics

---

enterprise/server/remote_execution/container/container.go
enterprise/server/remote_execution/runner/runner.go
enterprise/server/remote_execution/runner/runner_test.go

Ensure that we can't call `container.Remove()` while other operations are in progress, and also make operations fail immediately after the container is already removed.
This will likely fix https://github.com/buildbuddy-io/buildbuddy-internal/issues/2554, and at minimum it should give us better information as to whether a container operation is failing because of `Remove()` having already been called (on executor shutdown).

Prevent container.Remove() being called while other operations are in progress

---

enterprise/server/remote_execution/containers/firecracker/firecracker.go

Firecracker logs show lots of errors that we are failing to cleanup networking due to context canceled errors. In these cases, we still want to ensure the cleanup happens.
Related: https://github.com/buildbuddy-io/buildbuddy/pull/4924

[FC] Extend the context for networking cleanup

---

enterprise/server/remote_execution/containers/firecracker/BUILD

This will make it easier to continue testing with the target even if we still don't want it automatically enabled on CI

Mark fc blockio test as manual, instead of commenting out

---

enterprise/server/raft/cache/cache.go
enterprise/server/raft/listener/listener.go
enterprise/server/raft/store/store.go
enterprise/server/raft/store/store_test.go

This causes bugs in another CL i'm working on because the same listener is reused in tests when it shouldn't be.

Remove default listener

---

app/invocation/invocation.css
app/invocation/invocation_execution_table.tsx

A simple solution to hold us over until https://github.com/buildbuddy-io/buildbuddy-internal/issues/2774 is implemented - just render the status message from the Executions table which is already available in the UI.
Looks like this: 
The action page doesn't currently have access to the Execution row, so it's simplest to render this in the table for now (rather than awkwardly passing it to the action page via URL params or something like that)

Render execution status message in executions table

---

app/invocation/invocation_timing_card.tsx

`GetBazelConfigRequest` requests show up in the audit log, so we don't want to make these requests unnecessarily.
Currently the `SetupCodeComponent` is briefly shown when the component is rendered but before the timing profile request is made. This causes an api key viewed audit log entry to be created any time you visit the timing profile.
Separately we should change the UX of the `SetupCodeComponent` to require a click instead of automatically making a request that triggers an audit log entry.

Don't make `GetBazelConfigRequest` any time you visit timing profile

---

enterprise/server/remote_execution/containers/podman/podman.go

This has the effect of preserving the soci-store data across executor container restarts which should address the Input/output bug streaming public images we observed last week.

Update soci-store data paths to be under /var/lib/containers

---

app/service/rpc_service.ts

Set the `request_context` param for _all_ `/file/download` requests, not just bytestream requests.
**Related issues**: Fixes https://github.com/buildbuddy-io/buildbuddy-internal/issues/2777

Fix impersonation not working for artifact downloads

---

docs/config-auth.md

Add a dedicated SAML section for authentication configuration, separated
from OIDC. Added examples for Azure AD / Entra.

docs/config-auth: add a dedicated SAML section

---

enterprise/server/scheduling/scheduler_client/scheduler_client.go

When the executor gets disconnected from the app, there's a ton of errors and warnings printed to the executor logs. This is part 1 of a series of PRs which will attempt to denoise the logs a bit.

Don't double-log warning when scheduler client disconnects from app

---

enterprise/server/remote_execution/executor/executor.go
enterprise/server/remote_execution/operation/BUILD
enterprise/server/remote_execution/operation/operation.go
enterprise/server/scheduling/priority_task_scheduler/BUILD
enterprise/server/scheduling/priority_task_scheduler/priority_task_scheduler.go
enterprise/server/test/integration/remote_execution/BUILD
enterprise/server/test/integration/remote_execution/rbeclient/BUILD
enterprise/server/test/integration/remote_execution/rbeclient/rbeclient.go
enterprise/server/test/integration/remote_execution/rbetest/rbetest.go
enterprise/server/test/integration/remote_execution/remote_execution_test.go
server/resources/resources.go
server/util/healthcheck/healthcheck.go

The executor currently has 2 streams to the app that it maintains for each task, each of which can be broken when the apps roll out and cause a task retry:
- LeaseTask
- PublishOperation
This PR allows us to transparently retry PublishOperation, which should roughly cut in half the number of times that a task has to be retried because of an app rollout / disconnect.
In a later PR we can retry LeaseTask as well, though this is more complex.
---
Description of the changes in this PR:
- There are two stream methods in a `PublishOperation` stream client: `Send()` publishes a status update, and `CloseAndRecv()` terminates the stream and waits for the server to ack that it has received all messages.
- Note, `Send()` does not guarantee that the server has ack'd the message. So if `Send()` fails, …

Transparently retry PublishOperation streams

---

enterprise/server/scheduling/scheduler_client/scheduler_client.go

https://github.com/buildbuddy-io/buildbuddy/pull/4978 added a new `schedulerErr` channel. When sending on that channel and the context is cancelled, it's possible the goroutine which is supposed to receive from that channel has already exited ([here](https://github.com/buildbuddy-io/buildbuddy/blob/aa2d5443698a9544a389f7a43b3929f6a7bcf554/enterprise/server/scheduling/scheduler_client/scheduler_client.go#L109))
The fix in this PR is to use a channel buffer size of 1 so that the error will just go into the buffer in this case, then the channel will be garbage collected.

Fix potential goroutine leak

---

server/rpc/interceptors/BUILD
server/rpc/interceptors/interceptors.go
server/util/clientip/BUILD
server/util/clientip/clientip.go
server/util/clientip/clientip_test.go

- Support single-IP format used by NGINX.
- Don't trust X-Forwarded-For header unless explicitly enabled by flag.
- Fall back to peer IP for RPCs if header is absent/not trusted.

Extend X-Forwarded-For parsing.

---

app/auth/auth_service.ts
app/errors/error_service.ts
app/util/popup.ts

This prevents plugins like [React Developer Tools](https://chrome.google.com/webstore/detail/react-developer-tools/fmkadmapgofadopljbjfkapdkoienihi/related) from unintentionally posting window messages that interfere with the flow.

Filter out any window messages that aren't from buildbuddy

---

enterprise/server/backends/distributed/distributed.go

When replication factor is higher than the actual peer count, such as
running 1 pod with replication factor set to 3, we would run into:
```
panic: runtime error: slice bounds out of range [:3] with capacity 0
```
To avoid this, let's make sure that we only sub-slicing when the
replication factor was set correctly.
Also adjust the default replication factor to be inline with our
documentation "Must be >=1".

distributed: fix potential panic

---

cli/download/download.go
cli/upload/upload.go

cli: avoid setting empty API key header in upload/download commands

---

enterprise/server/backends/authdb/authdb.go
enterprise/server/scheduling/scheduler_server/scheduler_server.go
enterprise/server/workflow/service/service.go
server/backends/invocationdb/invocationdb.go
server/util/perms/perms.go

UserInfo is an interface so there's no need for the extra level of indirection. (I wrote this when I just started learning Go and didn't have much intuition about interfaces yet.)

cleanup: have AuthorizeRead accept UserInfo instead of *UserInfo

---

app/invocation/invocation_timing_card.tsx
app/service/rpc_service.ts

This is in preparation for switching the timing profile to use a streaming HTTP request for loading and parsing the JSON profile. XHR supports streaming but it's very ugly.
* Switch from XHR to Fetch
* Remove `storedEncoding` as a method param (since it's pretty niche), and instead pass the stored-encoding header directly via the standard `RequestInit` object
* Improve type safety of fetch() method - instead of `Promise<any>`, returns `Promise<ArrayBuffer>` when setting request type to `arraybuffer`, `Promise<string>` when setting request type to `"text"`, etc.

Switch from XHR to Fetch API

---

app/auth/auth_service.ts
enterprise/app/org/org_access_denied.tsx

The navigateTo call was going through the access check which tried to manipulate the URL prior to impersonation. Instead, redirect directly to the target URL.
Fixes https://github.com/buildbuddy-io/buildbuddy-internal/issues/2780

Fix URL weirdness when entering impersonation.

---

enterprise/app/repo/BUILD
enterprise/app/repo/repo.css
enterprise/app/repo/repo.tsx
enterprise/server/gcplink/gcplink.go
server/backends/github/github.go

This is still a bit of a work in progress, but this state is definitely better than what's currently live in dev.
This PR does a few things, happy to break it up if it's a pain to review:
- Switches to using popups instead of redirects for all linking / auth
- This allows us to remove like 3 or 4 buttons that were needed for all sorts of edge cases
- Moves the edge case handling to when either the create repo button is clicked or the deploy button is clicked
-  Adds some query parameters which allows us to render a nice title with an image if present
- Adds a cookie with the last github app installation id so we can automatically select it if it was just installed
Screenshot:

Update repo flow to use popups

---

enterprise/server/raft/cache/cache.go
enterprise/server/raft/client/client.go
enterprise/server/raft/rbuilder/rbuilder.go
enterprise/server/raft/replica/BUILD
enterprise/server/raft/replica/replica.go
enterprise/server/raft/replica/replica_test.go
enterprise/server/raft/store/BUILD
enterprise/server/raft/store/store.go
enterprise/server/raft/store/store_test.go
enterprise/server/raft/usagetracker/usagetracker.go
proto/raft.proto
proto/raft_service.proto

Make all reads and writes linearizable so we're not fighting the library. Basically just means rather than going around the raft locks when reading and writing stuff, we run the requests through the statemachine as raftgod intended.
There's a small performance impact for writes and seemingly none for reads. Will come back and fix that once other stuff is solid.

Make reads and writes linearizable

---

WORKSPACE

Main highlights for v24
https://github.com/protocolbuffers/protobuf/releases/tag/v24.0

protobuf: upgrade to 24.4

---

app/auth/auth_service.ts
enterprise/server/backends/userdb/userdb.go
proto/buildbuddy_service.proto
proto/user.proto
server/buildbuddy_server/buildbuddy_server.go
server/role_filter/role_filter.go
server/util/claims/BUILD
server/util/claims/claims.go

If the user is impersonating group X, but tries to access subdomain for group Y then don't enable impersonation on requests for subdomain Y so that subdomain Y can be accessed normally.
This PR slightly changes the semantics of how the frontend communicates impersonation information to the backend. Prior to this change, the frontend would set an impersonation target and would assume that impersonation was in effect. Now, the frontend still sets the impersonation target but now the backend informs the frontend whether impersonation is actually in effect via the GetUser response.
Fixes https://github.com/buildbuddy-io/buildbuddy-internal/issues/2779

Make impersonation play nice with subdomains.

---

enterprise/server/raft/cache/cache.go
enterprise/server/raft/client/client.go
enterprise/server/raft/rangelease/rangelease_test.go
enterprise/server/raft/sender/sender.go
enterprise/server/raft/store/store.go
proto/raft.proto

Allow clients to specify if they want a full raft read (fast) or a stale read (fastest).

Allow configuring stale reads

---

server/rpc/interceptors/interceptors.go

The remote execution client was registered before the identity service which meant the header was never added for execution requests. This change makes the registration order irrelevant.

Move identity service check inside interceptor function.

---

enterprise/server/remote_execution/platform/platform.go

The platform override happens on the executor which means it can only be set within shared executors.

Remove todo that's not even true.

---

app/invocation/invocation.css
app/invocation/invocation_timing_card.tsx
app/trace/BUILD
app/trace/trace_events.ts
app/trace/trace_events_test.ts

Use streaming JSON parse for timing profile to work around V8 string size limit

---

app/BUILD.bazel
app/picker/BUILD
app/picker/picker.css
app/picker/picker.tsx
app/picker/picker_service.ts
enterprise/app/repo/BUILD
enterprise/app/repo/repo.tsx
enterprise/app/root/BUILD.bazel
enterprise/app/root/root.tsx

Add a gcp project picker to the repo flow

---

enterprise/server/raft/replica/replica.go
enterprise/server/raft/replica/replica_test.go
enterprise/server/raft/store/store.go
server/gossip/gossip.go

This avoids there being any read/write slowdown when callbacks are run.
Previously a series of callbacks would be called which eventually triggered a gossip notification push -- this stuff was all blocking and would slow down every 1000th write request or something. Fix it.

Publish replica usage updates via channel

---

app/invocation/invocation_tabs.tsx

"action" tab is a child tab that could be accessed via either "Cache"
tab (by clicking on the mnemonic of Cache Request), or via "Execution"
tab.
Let's default it to highlight the Execution tab while viewing "action"
details. If no RBE is enabled, highlight "Cache" tab instead.

app/invocation_tabs: highlight Execution while viewing action

---

app/capabilities/capabilities.tsx
enterprise/app/settings/settings.tsx
proto/config.proto
server/static/static.go

This has been set to true by default for a while now.
Let's clean it up.

deprecate app.user_management_enabled flag

---

enterprise/server/clientidentity/BUILD
enterprise/server/clientidentity/clientidentity.go
enterprise/server/clientidentity/clientidentity_test.go

Bazel appears to send the header twice when --experimental_remote_downloader is enabled. We'll continue to treat other cases of multiple headers as an error as that would indicate a real problem.

Allow duplicate client identity headers.

---

enterprise/server/scheduling/priority_task_scheduler/priority_task_scheduler.go
enterprise/server/scheduling/scheduler_server/BUILD
enterprise/server/scheduling/scheduler_server/scheduler_server.go
enterprise/server/scheduling/task_leaser/BUILD
enterprise/server/scheduling/task_leaser/task_leaser.go
enterprise/server/test/integration/remote_execution/remote_execution_test.go
proto/scheduler.proto

Implements the reconnection changes described in the proto docs added here: https://github.com/buildbuddy-io/buildbuddy/pull/4983
The executor changes are behind the flag `executor.enable_lease_reconnect` which is set to true by default. The app's behavior is gated by the client's reported value of this flag, as well as the app flag `remote_execution.lease_reconnect_grace_period` being greater than 0 (defaults to 1s)

Retry LeaseTask on app shutdown

---

proto/firecracker.proto

Adds the following fields to the VMConfiguration proto (which affects the snapshot key):
* **kernel_version**: if we upgrade the kernel to fix bugs / pull in security improvements etc. we want old snapshots to be invalidated. For now, this can be a SHA256 of the vmlinux binary.
* **firecracker_version**: make sure we don't have to worry about snapshot backwards/forwards compatibility - we'll only ever support loading snapshots that were created by the locally available firecracker version.
* **goinit_version**: if we make changes to goinit, we want those to be reflected immediately rather than having to wait indefinitely for the snapshots to pick up the new binary version. For now, we can manually maintain a version number, since the SHA256 is very likely to change with each executor …

Add more versioning fields to snapshot key

---

enterprise/server/remote_execution/containers/firecracker/firecracker.go
enterprise/server/remote_execution/uffd/uffd.go

LoadSnapshot was calling `monitorVMContext` then passing the returned context to the UFFD / VBD handlers. However, this context is cancelled at the end of LoadSnapshot, so if UFFD / VBD need to do any remote chunk fetches they would fail with "context cancelled."
This PR moves the `monitorVMContext` after the UFFD / VBD setup so that their context can outlive the LoadSnapshot call.
The RemoteSnapshot test is failing because of this, but we didn't catch this because it's disabled currently.

Fix UFFD / VBD context being cancelled too early

---

enterprise/server/remote_execution/vbd/vbd.go
enterprise/server/remote_execution/vbd/vbd_test.go

I occasionally would see firecracker logging errors due to `fsync` failing on the block device backing file. I'm not 100% sure whether the errors were fatal, but we may as well implement `fsync` to avoid the errors.

vbd: fix fsync "operation not supported" error

---

enterprise/server/scheduling/scheduler_server/scheduler_server.go

When the client is sending its lease finalization request (`finalize=true`) and the app is shutting down, we shouldn't return a shutdown error. This is for 2 reasons:
1. There is no need for the client to retry the lease at that point, because we finalized the lease successfully. A well-behaved client should immediately close the stream after we return the success message, so in practice we don't need to worry too much about the open client stream delaying shutdown for much longer.
2. (Worse) if the client does retry, it will fail, because the server won't be able to find the task. This is because in the previous attempt which set `finalize=true`, we called `deleteClaimedTask`.

Don't return shutdown error after lease has been finalized

---

enterprise/server/remote_execution/runner/runner.go

This "runner recycling is not supported for anonymous builds" error adds a lot of friction when testing firecracker / runner recycling locally, especially when developing remotely on a GCP VM where it's a hassle to log in via the UI and get an API key.
Add a debug flag to bypass this behavior for development only.

Add a development-only flag to allow anonymous runner recycling

---

enterprise/server/cmd/executor/executor_linux.go
enterprise/server/remote_execution/containers/firecracker/firecracker_test.go
enterprise/server/remote_execution/vbd/vbd.go
enterprise/server/remote_execution/vbd/vbd_test.go

Use file-locking to avoid trying to clean up VBD mounts that are currently in use by other executor / test processes.
This fixes one of the blockers for running `firecracker_test` concurrently / with sharding.
The implementation uses `flock` for locking - see `man 2 flock`.

vbd: don't try to clean up in-use mounts

---

enterprise/server/remote_execution/containers/docker/docker_test.go

We don't need the 10 second timeout - we really just want to wait for the container to create `output.txt` which we're already doing via an explicit poll on that file. The 10 second timeout will just cause the test to be flaky if the machine is under high load.

Remove unnecessary timeout causing flakes in docker test

---

enterprise/server/remote_execution/containers/firecracker/test.sh
tools/buildozer.sh

Otherwise, the test script will silently fail to pass input arguments to the test command.

Make firecracker test script explicitly fail if buildozer is not installed

---

enterprise/server/remote_execution/containers/firecracker/firecracker.go
server/util/background/background.go

COW IO can happen outside of the task ctx scope, so make sure we use vmCtx for COW cache requests.

Use vmCtx for COW cache requests

---

enterprise/server/remote_execution/containers/firecracker/firecracker.go

If `copyOutputsToWorkspace` fails, we'd previously swallow the error if `ResumeVM` also fails, resulting in a confusing error message. `ResumeVM` will fail in particular if the context deadline is exceeded, which is more often because of a vsock timeout in `copyOutputsToWorkspace`.
This results in a small change in behavior: we won't call `ResumeVM` if we fail to copy workspace outputs, whereas before we would. However, it's unnecessary to resume the VM in this scenario, since we treat the copyOutputs error as fatal and Remove() the VM anyway.

Simplify/fix error handling in copyOutputsToWorkspace

---

enterprise/server/remote_execution/containers/docker/docker_test.go
server/util/disk/disk.go

Remove another unnecessary timeout causing docker_test to be flaky

---

enterprise/app/repo/repo.tsx

There are two flows / issues that this fixes.
The first is if you'd previously linked an Oauth (non-app) Github integration, when we first fetch available installations we get an error which was previously shown to the user. With this PR, we no longer show that error to the user, since in this scenario we'll link the Github app when they click "Create repository".
The second is the flow where you have accepted some permissions, but not the new updated permissions. In this case we weren't returning the promise form the permissions popup, so we weren't waiting on the permissions change to continue in the flow. This change fixes that by returning the promise. It also attempts to continue if the popup is closed, since Github doesn't always seem to perform a redirect in the permissions update …

Fix repo flow RBODs and permissions flow

---

server/util/claims/claims.go

All apps must be aware of the new key before it can be used for signing.

Continue to sign new JWTs using old key.

---

tools/firecracker_clean_networking.sh

Leftover VMs that weren't properly cleaned up can interfere when trying to run additional VMs

[FC] Clean up any firecracker processes in the clean networking script

---

enterprise/server/remote_execution/executor/executor.go

Add logging to diagnose whether input download is stalled

---

enterprise/server/iprules/BUILD
enterprise/server/iprules/iprules.go
enterprise/server/iprules/iprules_test.go
server/build_event_protocol/build_event_handler/build_event_handler.go
server/testutil/testauth/testauth.go

Don't return error in IP rules service if auth failed for any reason.
Add separate IP auth check in BES handler.

Fix BES ip rule handling.

---

enterprise/server/githubapp/githubapp.go
server/backends/github/github.go

Can be configured by setting `github.enterprise_host` to your Github Enterprise Server hostname (not including https:// and no trailing slash).

Add support for Github Enterprise Server

---

enterprise/server/remote_execution/containers/firecracker/firecracker_test.go

Results: (Includes #5027)
(remote_snapshot_sharing=true) Bazel build on a clean runner took  1m7.718469349s.
(remote_snapshot_sharing=true) Bazel build on a recycled runner (100% locally cached) took 2.162489981s.
(remote_snapshot_sharing=true) Bazel build (30% locally cached) took 1m5.167310881s. 70% artifacts fetched remotely.
(remote_snapshot_sharing=true) Bazel build (0% locally cached) took 1m13.816709152s. 100% artifacts fetched remotely.
(remote_snapshot_sharing=false) Bazel build on a clean runner took 1m23.309983265s.
(remote_snapshot_sharing=false) Bazel build on a recycled runner (100% locally cached) took 1.996104061s.
(remote_snapshot_sharing=false) Bazel build (30% locally cached) took 1m18.716916804s. Could not start from snapshot, had to prepare clean runner. …

[RSS] Add manual performance tests that run git clone + bazel for more realistic results

---

tools/metrics/grafana/dashboards/buildbuddy.json

1. Remove unused kubenode global variable.
2. add (grp-)? to the regex for kubepool
3. fix Network graph by using "(ens|eth)" as the device filter.
4. Also add (grp-)? to nodename filter so that cpu, memory graph also shows up
for executor pool.

Fix Node Overview dashboard

---

enterprise/server/backends/pebble_cache/pebble_cache.go
enterprise/server/raft/usagetracker/usagetracker.go
server/metrics/metrics.go
server/util/approxlru/approxlru.go
server/util/approxlru/approxlru_test.go

combine onRefresh and onEvict in approxlru.go
In pebble cache, onEvict will put the sample on a queue; and we delete the
entry in background. Before we delete from pebble, we will check the last access
time and only delete if it's not recently read.

Pebble Cache: delete in a queue

---

deps.bzl
go.mod
go.sum

Change log: https://github.com/klauspost/compress/compare/v1.16.6...v1.17.2
Includes https://github.com/klauspost/compress/pull/876 which fixes a corruption bug in v1.16.4 forward.

klauspost/compress: upgrade to v1.17.2

---

.bazelrc
BUILD
WORKSPACE
toolchains/BUILD

Register our toolchains inside WORKSPACE.
Then enable automatic cc toolchain resolution for auto selection based
on platform compatibility.
This let us get rid of the manual toolchain declaration when building with
`--config=remote`. Subsequently, we won't need to specify `--cpu` and
`--host_cpu` to aid cc_toolchain_suite detection.

Move toolchain registration into WORKSPACE

---

enterprise/server/raft/cache/cache.go
enterprise/server/raft/nodeliveness/BUILD
enterprise/server/raft/nodeliveness/nodeliveness_test.go
enterprise/server/raft/rangelease/rangelease_test.go
enterprise/server/raft/replica/replica.go
enterprise/server/raft/sender/sender.go
enterprise/server/raft/store/store.go
proto/raft.proto

This gives the performance of STALE reads with the consistency guarantees of a LINEARIZABLE raft read.

Support RANGELEASE consistency

---

server/util/fastcopy/BUILD
server/util/fastcopy/fastcopy_linux.go
server/util/fastcopy/fastcopy_test.go

* Add a test that mounts an XFS image and tests that a reflinked file modification doesn't affect the original
* defer close `destFile` (it would have been closed on GC so this is not a big deal)

Add test for reflink

---

server/endpoint_urls/events_api_url/BUILD
server/endpoint_urls/events_api_url/events_api_url.go
server/endpoint_urls/remote_exec_api_url/BUILD
server/endpoint_urls/remote_exec_api_url/remote_exec_api_url.go
server/util/flag/BUILD
server/util/flag/flag.go
server/util/flagutil/common/common.go
server/util/flagutil/common/common_test.go
server/util/flagutil/flagutil.go
server/util/flagutil/types/autoflags/BUILD
server/util/flagutil/types/autoflags/autoflags.go
server/util/flagutil/types/autoflags/autoflags_test.go
server/util/flagutil/types/types.go
server/util/flagutil/types/types_test.go
server/util/flagutil/yaml/yaml.go
server/util/flagutil/yaml/yaml_test.go

I'm attempting to write a `bb execute` command that runs an arbitrary command as a remote execution request, but noticed that I can't add a multi-valued `remote_header` flag matching Bazel's flag, because the StringSlice() func only works on the default flag set.
This PR updates the flag utils to explicitly plumb through the FlagSet everywhere instead of referencing DefaultFlagSet. The top-level utils such as `flag.StringSlice()` still use the default flag set (flag.CommandLine).

Allow flag utils to work with CLI subcommands

---

tools/metrics/grafana/dashboards/buildbuddy.json

use $window instead of $__interval in resample/evict latency graph

Fix resample/evict latency graphs

---

tools/metrics/grafana/dashboards/buildbuddy.json
tools/metrics/grafana/dashboards/cache.json

It's difficult to examine the graph when we show two queries for all different
combo pod_name and partition_id in the same graph. It's better to move them to
per partition graph in remote cache dashboard.

move bytes deleted to remote cache dashboard

---

enterprise/server/remote_execution/runner/runner.go

The current behavior is fine from an auth perspective but makes it trickier to identify misconfigured per-action credentials for self-hosted executors, since it would take 15 minutes for the warmup cache token to expire, and only then would we start actually returning an error for the misconfigured per-action credentials.

Don't cache image pull auth result during initial warmup

---

enterprise/server/remote_execution/execution_server/execution_server.go

Instead, explicitely log if client disconnected.

Remove confusing PubSub log message.

---

enterprise/server/raft/cache/cache.go
enterprise/server/raft/driver/BUILD
enterprise/server/raft/driver/driver.go
enterprise/server/raft/driver/driver_test.go
enterprise/server/raft/events/BUILD
enterprise/server/raft/events/events.go
enterprise/server/raft/leasekeeper/BUILD
enterprise/server/raft/leasekeeper/leasekeeper.go
enterprise/server/raft/listener/BUILD
enterprise/server/raft/replica/BUILD
enterprise/server/raft/replica/replica.go
enterprise/server/raft/store/BUILD
enterprise/server/raft/store/store.go

Previously there were various components that could update or depend on cluster state and each required a different set of information. That led to a multiplicative number of types / channels. Instead, use a single events channel and allow various components (leasekeeper, store, usagetracker, driver) to read and write what they need from the channel.

Broadcast range messages on events channel

---

enterprise/server/backends/pebble_cache/pebble_cache.go
enterprise/server/util/cacheproxy/cacheproxy.go
server/remote_cache/byte_stream_server/byte_stream_server.go
server/remote_cache/cachetools/cachetools.go
server/util/bytebufferpool/bytebufferpool.go
server/util/bytebufferpool/bytebufferpool_test.go

It essentially already existed (safeSyncPool) but was private to the package.
Removed use of generics since we were ever using it with a single type.

Add type-safe fixed-size byte buffer pool option to `bytebufferpool` package.

---

.bazelrc
BUILD
WORKSPACE
toolchains/BUILD

This reverts commit 164737127a175c494c7f5a06fc44241014e0ad05.
We previously introduced this in 5070 but reverted due to
incompatibilities with internal repo. Will couple this PR with another
internal PR to ensure compatibility between the 2.

    Revert "Revert "Move toolchain registration into WORKSPACE (#5070)""

---

proto/BUILD
proto/action_cache.proto
proto/build_event_stream.proto
proto/failure_details.proto
proto/option_filters.proto

These proto files are taken from commit
https://github.com/bazelbuild/bazel/commit/76117b4a43b552c681dcf841704fedfd60d3e37b
Highlight:
- Inclusion of ActionCacheStatistics in build_event_stream
https://github.com/bazelbuild/bazel/pull/17615
- Explicit Execution phase timing (in prepare for Skymeld)
https://github.com/bazelbuild/bazel/commit/be63eeefa9736d66f4b773bf6043958575eb02d7
- If `--noallow_analysis_cache_discard` is set, BuildFinished may
contains FailureDetails -> CONFIGURATION_DISCARDED_ANALYSIS_CACHE.
https://github.com/bazelbuild/bazel/pull/16805/
- ExecRequest event is included for `bazel run`
https://github.com/bazelbuild/bazel/commit/9a047de5f6cd5c2f1204b2389746d5a9862f10c8
- TestProgress event is included for TestRunner action …

proto: update proto from Bazel upstream

---

enterprise/server/cmd/ci_runner/main.go
enterprise/server/workflow/service/service.go
proto/scheduler.proto

* Removes `RemoteSnapshotOptions` - after offline discussion we decided to use env instead.
* Set `GIT_BRANCH`, `GIT_BASE_BRANCH`, `GIT_REPO_DEFAULT_BRANCH` in env, which are all useful for snapshot matching.

workflows: set env vars needed for snapshot matching

---

enterprise/server/backends/pebble_cache/pebble_cache.go

It's flagging already-broken keys which is too noisy.

Remove atime update alert.

---

app/trace/trace_viewer.css
app/trace/trace_viewer.tsx

* Update panel to be absolutely positioned within its container to fix jitter when zoom animation is running.
* Apply a max zoom level to prevent the inner scrollable div's width from exceeding the apparent max width that browsers are capable of handling (once we get above this threshold, various weird things start happening)

Fix zooming issues with trace viewer

---

cli/execute/execute.go
enterprise/server/remote_execution/execution_server/execution_server.go
enterprise/server/scheduling/scheduler_server/scheduler_server.go

* Add a few spans to better understand scheduling overhead
* Have `bb execute` report time from each stage (when running with `--verbose=1`)
**Related issues**: https://github.com/buildbuddy-io/buildbuddy-internal/issues/2844

Improve execution tracing

---

enterprise/server/remote_execution/containers/podman/BUILD
enterprise/server/remote_execution/containers/podman/podman.go

`IsImageCached` consistently adds at least 20ms of action overhead locally (10% of total execution time for a local NOP action) and around 30ms of overhead remotely. Optimize it by caching its result when returns true, since we don't expect podman images to disappear.
Also use `podman image exists` which appears to run a few ms faster than `podman image inspect` and is also more straightforward.
**Related issues**: https://github.com/buildbuddy-io/buildbuddy-internal/issues/2844

Optimize podman IsImageCached

---

enterprise/server/backends/migration_cache/migration_cache.go
enterprise/server/backends/pebble_cache/pebble_cache.go

Don't do expensive work like eviction or copying while draining queue, b/c this
can cause pebble cache not properly shut down and we have inconsistencies
between pebble keys and blobs on disk.

Do nothing while draining queue

---

cli/fix/BUILD
cli/fix/fix.go
cli/test/integration/cli/cli_test.go
tools/checkstyle/checkstyle.sh

`bb fix -mode=diff` used to work in 5.0.21 (the version used in our current checkstyle GH action), but broke somewhere along the way. This PR fixes it, but uses an explicit `--diff` flag instead of forwarding `-mode=diff` to gazelle (because `bb fix` now does more than just call gazelle, and we can't safely forward the same args to all commands). Also supports buildifier diffs.

Fix broken `diff` mode in bb fix

---

enterprise/server/cmd/goinit/BUILD
enterprise/server/remote_execution/containers/firecracker/BUILD
enterprise/server/remote_execution/containers/firecracker/containeropts.go
enterprise/server/remote_execution/containers/firecracker/firecracker.go
enterprise/server/remote_execution/containers/firecracker/firecracker_test.go
enterprise/server/remote_execution/platform/platform.go
enterprise/server/remote_execution/runner/runner_linux.go
enterprise/server/vmexec/BUILD
enterprise/tools/vmstart/vmstart.go
proto/firecracker.proto
server/remote_cache/digest/digest.go

Once we enable snapshot sharing (either local or remote), this will be required in order to start running VMs on newer software versions (firecracker, kernel, or goinit binary). Otherwise, actions can get stuck on old snapshots for as long as the snapshot remains in remote cache, which can be ~forever. Newer executor versions will potentially be incompatible with older snapshot versions, which can result in various classes of bugs (resume failures, unexpected VM states or execution results, etc.).
The goinit binary version is especially important since changes to this binary are unlikely to be backwards compatible (e.g. adding a new goinit flag is not a backwards compatible change, so we need to bump the goinit version when adding a new flag).

Include versioning info in firecracker snapshot key

---

enterprise/server/remote_execution/containers/firecracker/firecracker.go
enterprise/server/remote_execution/containers/firecracker/firecracker_test.go

Forgot to bump this before merging my healthcheck PR :sweat_smile: 

Bump GuestAPIVersion to fix firecracker_test

---

enterprise/server/cmd/ci_runner/main.go

This will make it a little easier to see how long things are taking, until we support proper timing metrics for the CI runner.

Add timestamps to CI runner logs

---

enterprise/server/remote_execution/containers/firecracker/firecracker.go
enterprise/server/remote_execution/containers/firecracker/firecracker_test.go

This should help diagnose disconnected workflows - if the last observed memory usage is close to 100%, it's more evidence that we're OOM-ing.

Report last observed VM stats after crash

---

enterprise/server/workflow/service/service.go

This breaks `docker login` when running as a non-root user.
This is a partial revert of https://github.com/buildbuddy-io/buildbuddy/pull/5099

Temporarily disable init-dockerd in CI runner image

---

template-user.bazelrc

We have removed target-linux in #5088 in favor of `--config=remote`
working out of the box.

template-user.bazelrc: remote reference to target-linux

---

enterprise/server/scheduling/scheduler_server/scheduler_server.go

A reconnect does not begin a new execution attempt, so we shouldn't increment the attempt count.
This is causing some workflow actions to fail after not being retried the full 5 times.

Do not increment attempt count on lease reconnect

---

server/backends/blobstore/aws/aws.go

When configure AWS S3 blobstore, we first call HeadBucket to check
whether if the bucket exists. Upon a NotFound error, we should be
attempting to create a new bucket. For any other errors, such as
credential error or SigningError, we want to surface that logic
back to the user.
Flip the return statement between NotFound and other error types when
calling HeadBucket.

blobstore/aws: fix NotFound error handling

---

enterprise/server/remote_execution/snaploader/snaploader.go

The group ID makes it difficult to fetch and debug remote snapshots using the `vmstart` tool - we'd have to set up a fake authenticator and insert a fake group ID into the ctx. It's easier if we can just plug in an API key, and have the remote cache handle group ID partitioning.

Remove group ID from remote snapshot key

---

enterprise/server/remote_execution/snaploader/BUILD
enterprise/server/remote_execution/snaploader/snaploader.go

This will make it easier to track errors across particular snapshot keys, as well as let us pull and inspect them locally.

Add remote snapshot manifest key to logs

---

server/libmain/libmain.go

Add flags that allow configuring the runtime MutexProfileFraction and BlockProfileRate. Will send a flag change to set these to 1/100 in dev.

Flags to enable more profiling

---

enterprise/server/scheduling/task_router/task_router.go
enterprise/server/test/integration/task_router/task_router_test.go

**Related issues**: [222](https://github.com/buildbuddy-io/buildbuddy-internal/issues/222)

Enable affinity routing unconditionally, with an shutoff flag in case of emergency.

---

enterprise/server/remote_execution/snaploader/snaploader.go
enterprise/server/remote_execution/snaputil/snaputil.go

We want `tools/vmstart` to be able to read snapshots from remote cache (for debugging purposes), but not overwrite them.

Add a flag to enable readonly remote snapshot sharing

---

enterprise/server/remote_execution/containers/firecracker/firecracker.go

Adds a lock around data that is accessed in two concurrent goroutines.

Fix data race condition that is detected when we build with musl

---

enterprise/server/remote_execution/containers/firecracker/firecracker_test.go

This ensures we always set the path and that we only do it once, in `init`.

Only set the path once in firecracker_test

---

enterprise/tools/vmstart/BUILD
enterprise/tools/vmstart/vmstart.go

Adds several improvements to `enterprise/tools/vmstart`:
* Allow loading remote snapshots.
* Add a "repl" mode to allow entering commands into the VM using a super basic Bash REPL. The VM debug terminal can't be used when starting from remote snapshots, because the tty flags need to be set via boot args.
* Call vm.Remove() when pressing Ctrl+C instead of doing nothing.
* Run networking cleanup before doing anything to prevent random network errors.

Allow vmstart to load remote snapshots

---

WORKSPACE

In Go 1.21, Go SDK starts to include `go.env` file at the root of the
toolchain with GOPROXY set to default values. With this changes, Go
toolings start to fail when the `go.env` file is not found and the proxy
is unset.
We actually don't get this problem when using Linux RBE because our
action execution image has Go pre-installed and there seems to be some
magic fall back somewhere. However when attempting to build using MacOS
RBE, the error occurred on GoToolchainBinaryBuild actions.
Luckily, this was reported in Bazel slack and fixed in (1).
This PR upgrade our rules_go to that exact fixed commit.
(1): https://github.com/bazelbuild/rules_go/pull/3722

rules_go: fix GOPROXY unset

---

enterprise/server/remote_execution/containers/firecracker/firecracker.go

The default timeout for `ResumeVM` is 500ms, which is not enough time when we have to resolve page faults remotely (confirmed via logging that `ResumeVM` is actually triggering page faults). This PR increases it to 30s so that we have more time.
Note, this timeout is also capped to the task ctx deadline. So things like executor shutdown will still result in proper ctx cancellation.

Increase firecracker go sdk request timeout

---

enterprise/server/remote_execution/copy_on_write/BUILD
enterprise/server/remote_execution/copy_on_write/copy_on_write.go
enterprise/server/remote_execution/copy_on_write/copy_on_write_test.go
enterprise/server/remote_execution/snaploader/snaploader.go
enterprise/server/remote_execution/snaputil/snaputil.go
enterprise/server/remote_execution/snaputil/snaputil_test.go
server/metrics/metrics.go

Add an initialization source to each snapshot chunk. If the chunk was fetched from the cache, we don't need to re-cache it. Even though the cache has short-circuiting behavior if we try to re-upload a chunk that is already cached, a good amount of data could've already been streamed by the time that it exits. 
Also add some metrics to validate our hypothesis that most chunks should be cached locally.

[SS] Don't re-cache snapshot chunks that are already cached

---

enterprise/server/remote_execution/copy_on_write/BUILD
enterprise/server/remote_execution/copy_on_write/copy_on_write.go

If we access a snapshot chunk, use a background queue to eagerly fetch the next X contiguous chunks, anticipating that they will also be accessed.
**Some performance results:**
The performance tests build the buildbuddy repo from a snapshot that is cached in the remote cache, but nothing is cached locally in filecache. Every testing scenario was run 6 times. 
Baseline: (45.8s - 50.6s)
Best config - 8 concurrent threads, max 1000 fetches per sec: (24.9s - 27.2s)
**Some additional sample tests for context:**
4 concurrent threads, max 1000 fetches per sec: (25.7s - 27.6s)
4 concurrent threads, max 500 fetches per sec: (28.5 - 29.5s)
8 concurrent threads, max 100 fetches per sec: (37.5s - 40.2)
-  Additional threads not that helpful, because rate limiter is so low
4 concurrent threads, max …

[FC] Eagerly fetch chunks in the cow store

---

enterprise/server/remote_execution/runner/BUILD
enterprise/server/remote_execution/runner/runner.go
enterprise/server/remote_execution/snaploader/snaploader.go
server/metrics/metrics.go

The motivation for the runner pool is that state is saved on the runner during an initial task, which can be reused for future workloads.
If snapshot sharing is enabled, a firecracker VM can be cloned from the cache and does not rely on previous state set on the runner, so we can circumvent the runner pool. In fact we *should* circumvent the runner pool and create a new runner with data from the incoming task, which can be used to find a better snapshot match than a runner created for a stale task
(Ex. If runner A was created for branch `feature_one` and an incoming workload is for branch `feature_two`, we should create a new runner intended for `feature_two`, rather than reuse the runner for branch `feature_one`, which would be more stale)
We need to do this because of how the Container …

[SS] Skip the runner pool for snapshot-sharing-enabled runners

---

enterprise/server/remote_execution/copy_on_write/copy_on_write.go

The accessed chunk will be accessed in the foreground, so we can start eager fetching at the following chunk. This makes the `eagerFetchNextChunks` parameter a little more intuitive

[SS] Start eager fetching at the chunk following the one that is accessed

---

server/version/BUILD

Fixes a bug that lots of cache invalidations are happening on every commit.
Credit to @sluongng for finding this bug.

Don't include version info when using `-c fastbuild`

---

enterprise/server/auth/BUILD
enterprise/server/auth/auth.go
enterprise/server/githubauth/BUILD
enterprise/server/githubauth/githubauth.go
server/backends/github/github.go
server/static/BUILD
server/static/static.go

The check basis is actually using the JwtKey on the github package.
Use it instead.

githubauth: move enable check to server/backends/github

---

enterprise/server/raft/replica/replica.go
server/util/qps/qps.go
tools/cacheload/cacheload.go

The QPS counter has a bug where if the QPS has actually dropped to zero, the reported QPS appears to stay stuck at the same value for up to a minute, and even appears to increase after a while, then suddenly drops to 0.
This is because the counter only averages buckets that have a value of 0. So if the QPS is actually zero then only the other buckets are counted (and are weighted higher in the average).
This PR fixes the bug by having a separate notion of "valid" and "zero". All buckets are valid except when the counter is first initialized, and after the averaging window first elapses, all buckets are considered valid.
Other improvements:
* Use `time.Ticker` instead of `time.Sleep` to avoid drift under CPU load.
* Make time window configurable, and set it to 5s in cacheload (for more …

Fix QPS counter

---

BUILD
enterprise/server/backends/distributed/distributed.go
enterprise/server/backends/migration_cache/migration_cache.go
enterprise/server/backends/pebble_cache/pebble_cache.go
enterprise/server/raft/registry/registry.go
enterprise/server/remote_execution/copy_on_write/copy_on_write.go
enterprise/server/remote_execution/runner/runner.go
enterprise/server/remote_execution/uffd/uffd.go
enterprise/server/util/chunker/chunker.go
server/backends/slack/slack.go
server/util/redact/redact.go

* S1019:  Simplify make call by omitting redundant arguments.
* S1023: Omit redundant control flow.
* S1025: Don’t use fmt.Sprintf(%s, x) unnecessarily.

Enable golang static checks S1019, S1023, and S1025

---

enterprise/server/raft/constants/constants.go
enterprise/server/raft/rbuilder/rbuilder.go
enterprise/server/raft/replica/replica.go
enterprise/server/raft/replica/replica_test.go
proto/raft.proto

Sometimes, like during a split or merge, you want to make changes that apply to multiple ranges and those changes should apply as a unit.
To support this, add a transaction_id that batches a request in-memory and locks the keys in that batch. This allows us to implement 2PC so we can Prepare a bunch of changes against different ranges and then Commit them or Roll them back together.

2PC: allow setting a txn id

---

app/invocation/BUILD
app/invocation/invocation_model.tsx
app/invocation/suggestion_button.tsx
app/util/BUILD
app/util/exit_codes.ts
enterprise/app/history/BUILD
enterprise/app/history/history.tsx
enterprise/app/history/history_invocation_card.tsx
server/test/webdriver/invocation/invocation_test.go

Shows more granular test statuses in the UI based off of Bazel exit code.
Also makes the "NO_TESTS_FOUND" exit code display as more of a neutral status rather than a hard failure.

More granular invocation statuses

---

enterprise/server/remote_execution/copy_on_write/copy_on_write.go

There were two bugs related to copying unmapped chunks: 
1) There could be a race condition where thread A) is initializing a chunk in the background and setting the source field (to something like RemoteCache) and thread B) is copying an unmapped chunk to be dirtied and reading the source field (Unmapped) to copy it over to the new chunk
2) When we copy an unmapped chunk, we create a clone of the chunk (So the new chunk is also unmapped). When we try to copy over the source data using newChunk.Write(bufCopiedFromSrc) (pseudocode), it tries to initialize the new chunk from the cache because it's unmapped. We don't need to do this, because we're overwriting the chunk's data with the contents of the source chunk.
Both these problems can be fixed by just initializing the source chunk before …

[SS] Fix race condition / bug when copying an unmapped chunk

---

enterprise/server/remote_execution/platform/platform.go
enterprise/server/remote_execution/runner/runner.go
enterprise/server/remote_execution/runner/runner_darwin.go
enterprise/server/remote_execution/runner/runner_linux.go
enterprise/server/remote_execution/runner/runner_windows.go

Before this PR, we would call `podman.NewProvider()` regardless of whether podman was enabled (same for docker, bare, and sandbox). This is causing problems for https://github.com/buildbuddy-io/buildbuddy/pull/5207, which attempts to run the `podman` command within the `NewProvider()` func. If podman is not available (e.g. in tests), we'll fail to run podman to detect the version.

Don't register container providers that are not enabled

---

.bazelignore

Turn out, if you just tail Bazel java log, it just scans everything.
Removing .git directory from scanning helps speed things up slightly.

.bazelignore: add .git

---

deps.bzl

This fix: https://github.com/buildbuddy-io/soci-snapshotter/pull/16
**Related issues**: [2282](https://github.com/buildbuddy-io/buildbuddy-internal/issues/2282)

Upgrade soci-store to 0.0.12 (with the go-fuse fix)

---

enterprise/server/remote_execution/containers/firecracker/firecracker.go

This caused an error where we'd clean up the contents of the memory store before stopping the uffd handler, causing errors when the uffd handler tried to access the memory store.
This only happened on executor shut downs because in a typical case we'd call Pause() on the container first, which stops the uffd handler. During executor shut downs, we only call Remove(), so the uffd handler was still running when we clear chroot

[FC] Fix early chroot cleanup in firecracker.Remove()

---

enterprise/server/remote_execution/containers/firecracker/firecracker.go
enterprise/server/remote_execution/containers/firecracker/firecracker_test.go
enterprise/server/remote_execution/copy_on_write/copy_on_write.go
enterprise/server/remote_execution/copy_on_write/copy_on_write_test.go
enterprise/server/remote_execution/snaploader/snaploader.go
enterprise/server/remote_execution/snaploader/snaploader_test.go
enterprise/server/remote_execution/snaputil/BUILD
enterprise/server/remote_execution/snaputil/snaputil.go
enterprise/server/remote_execution/snaputil/snaputil_test.go

Limit non-workflow actions that try to use runner recycling to local-only snapshot sharing, because it would be too expensive for large builds to upload a full snapshot per action.

[SS] Limit non-workflow actions to local-only snapshot sharing

---

enterprise/server/remote_execution/containers/firecracker/firecracker.go
enterprise/server/remote_execution/containers/firecracker/firecracker_test.go

Bumping version to pick up https://github.com/buildbuddy-io/buildbuddy/pull/5216 and updating the hash to fix the test.
(The test failed on that PR, but had auto-merge enabled :sweat_smile: )

Bump GuestAPIVersion

---

enterprise/server/raft/client/client.go
enterprise/server/raft/rbuilder/BUILD
enterprise/server/raft/rbuilder/rbuilder.go
enterprise/server/raft/replica/replica_test.go
enterprise/server/raft/sender/sender.go

The txn runner can be used to apply statements that cross shard boundaries. Example usage:
```
txn := rbuilder.NewTxn().AddStatement(shardID, leftBatch)
txn = txn.AddStatement(newShardID, rightBatch)
txn = txn.AddStatement(metaRangeShardID, metaBatch)
if err := client.RunTxn(ctx, s.nodeHost, txnReq); err != nil {
return nil, err
}
```

Add a 2PC txn runner

---

tools/checkstyle/checkstyle.sh

Makes `bazel run tools/checkstyle` work at least somewhat on Mac locally. The `clang-format` binary isn't yet set up properly for Mac so that part still fails.

Fix checkstyle date command on mac

---

enterprise/server/scheduling/scheduler_server/scheduler_server.go
enterprise/server/scheduling/task_leaser/task_leaser.go

We are seeing the new server-side lease timeout getting triggered for some workflow actions in dev. This PR adds a little bit of debug logging to try and diagnose the issue.

Add temp debug logging for server-side lease timeout issue

---

.bazelrc
buildbuddy.yaml

These should maximize benchmark performance and give us more realistic results. Should also prevent the benchmarks from timing out as much.
Also disables the race detector for checkstyle since this slows it down unnecessarily.

Disable race detector for benchmark workflow and set -c opt

---

enterprise/server/remote_execution/containers/podman/podman.go

This is useful for folks that need their executors to connect to internal DNS servers.

Add a flag to configure podman DNS settings

---

app/invocation/invocation_model.tsx
enterprise/app/history/history_invocation_card.tsx

This change https://github.com/buildbuddy-io/buildbuddy/pull/5170 broke workflow status rendering because workflows don't report a bazel exit code so they hit this case in the switch statement: https://github.com/buildbuddy-io/buildbuddy/pull/5170/files#diff-d02509013b3d6d63733e2a920b9661f301cb4e1f154fbb778735705b4657ce20R40
This change fixes that by checking the invocation status first.

Correctly show successful workflows as "Succeeded"

---

enterprise/server/remote_execution/containers/firecracker/firecracker.go
enterprise/server/remote_execution/containers/firecracker/firecracker_performance_test.go
enterprise/server/remote_execution/containers/firecracker/firecracker_test.go
enterprise/server/remote_execution/snaploader/BUILD
enterprise/server/remote_execution/snaploader/snaploader.go
enterprise/server/remote_execution/snaploader/snaploader_test.go
proto/firecracker.proto

:arrow_right: depends on https://github.com/buildbuddy-io/buildbuddy/pull/5115
* Use main git ref (pushed branch name) for reading and writing
* Use fallback git refs for reading only (PR base branch and repo default branch, if different from PR base branch)

executor: use git refs for snapshot read/write

---

app/router/router_params.ts
enterprise/app/filter/filter.tsx

This PR:
* Renders the little "X" button when non-default sort parameters are selected, so the user can clear them.
* Marks the default sort options with a "(Default)" label and selects their radio buttons when they're active, even if no URL parameters are set.
* Hides the UI label and clears URL parameters when the default sort options are selected, even if other sort options were previously selected.
**Related issues**: [1954](https://github.com/buildbuddy-io/buildbuddy-internal/issues/1954)

Sort menu tweaks

---

enterprise/server/invocation_stat_service/BUILD
enterprise/server/invocation_stat_service/invocation_stat_service.go

Noticed while trying to filter for `github.com/buildbuddy-io/buildbuddy` that the results turn up empty.

Normalize repo URL in trends queries

---

enterprise/server/cmd/server/BUILD
enterprise/server/cmd/server/main.go
enterprise/server/gcplink/gcplink.go
enterprise/server/oidc/oidc.go
server/buildbuddy_server/BUILD
server/buildbuddy_server/buildbuddy_server.go
server/environment/environment.go
server/interfaces/BUILD
server/interfaces/interfaces.go
server/real_environment/real_environment.go

Introduce a GCPService interface to help decouple GCPLink logic.
This helps us remove a direct link between buildbuddy_server and
//enterprise package.

gcplink: move exported funcs to GCPService interface

---

server/metrics/generate_docs.py
server/metrics/metrics.go

buildbuddy_*_exported metrics are created as intermediate metrics so that we can 
export to cloud customers prometheus metrics. Cloud customers are supposed to 
use exported_buildbuddy_* metrics for monitoring. I think exposing the
intermediate metrics in docs create more confusion.
I plan to write a seperate doc for prometheus exporters for cloud runners.
Also, moved a metric definition after "Example" comment in metrics.go

remove intermediate prom metrics from docs

---

buildpatches/org_golang_google_grpc_remove_drain_panic.patch
deps.bzl

Patch out panic from gRPC Drain when handling grpc-over-http requests.

---

enterprise/server/remote_execution/dirtools/dirtools.go
enterprise/server/remote_execution/dirtools/dirtools_test.go

If a symlink exists with the correct target; use it, and if the target is incorrect, attempt to remove it and recreate.

Handle already-existing symlinks without error

---

enterprise/dockerfiles/ci_runner_image/Dockerfile
enterprise/dockerfiles/rbe-ubuntu20-04-workflows/Dockerfile
enterprise/server/remote_execution/platform/platform.go
enterprise/server/workflow/service/service.go

There were two issues:
* The `buildbuddy` user was not part of the `docker` group (fixed in this PR)
* Supplementary group memberships (such as `docker`) were not taking effect when running commands - fixed in https://github.com/buildbuddy-io/buildbuddy/pull/5273/files

Fix and re-enable `init-dockerd` in workflow tasks

---

app/invocation/invocation_model.tsx
app/invocation/invocation_suggestion_card.tsx

In Bazel 7.0 `experimental_remote_cache_compression` and `experimental_remote_build_event_upload` will lose their `experimental_` prefix (though they'll still be accepted with prefix).
Let's not show the flag suggestions if we see the flags set without the `experimental_` prefix (which I think Bazel automatically strips when normalizing flags).

Don't show experimental flag suggestions in Bazel 7.0

---

server/remote_cache/content_addressable_storage_server/content_addressable_storage_server.go
server/remote_cache/digest/digest.go

Roughly 6% of allocs are happening in a single method `ResourceNameFromProto ` called in a loop for every input digest*action. Reduce the allocs that need to happen in this loop.

Use ResourceNameFromProto less to reduce allocs

---

enterprise/server/remote_execution/container/container.go
enterprise/server/remote_execution/runner/runner.go
enterprise/server/remote_execution/snaploader/BUILD
enterprise/server/remote_execution/snaploader/snaploader.go
enterprise/tools/vmstart/vmstart.go

- Issue 1: It fails with an "Unimplemented" error in `groupId()` because auth is not enabled. Fixed by setting `-debug_enable_anonymous_runner_recycling` and updated that flag to also apply to local snapshot sharing, not just runner pool recycling.
- Issue 2: After adding trace_fraction=1, it now fails unless you also pass in trace_jaeger_collector. Just removed the trace_fraction flag for now. So to trace, we need to pass both app.trace_jaeger_collector and app.trace_fraction=1
- Issue 3: The default image (busybox) doesn't have `bash`. Change `-repl` mode to start an `sh` session which is more widely available. Also switch to `mirror.gcr.io` since it doesn't have as much rate limiting as docker.io does.

Fix vmstart when trying to run a local VM from scratch

---

enterprise/server/backends/distributed/distributed.go
enterprise/server/oidc/oidc.go
server/remote_cache/digest/digest.go
server/rpc/interceptors/interceptors.go
server/util/tracing/tracing.go

Reduce allocations (~6%) by extracting just the value we need from grpc metadata, rather than copying all of it.

Do not copy metadata proto when extracting headers

---

enterprise/server/remote_execution/runner/runner.go

**Related issues**: [2881](https://github.com/buildbuddy-io/buildbuddy-internal/issues/2881)

Add flag --executor.warmup_additional_images specifying a list of container images to warm up, in addition to the default images.

---

enterprise/server/remote_execution/containers/firecracker/firecracker.go
enterprise/server/remote_execution/containers/firecracker/firecracker_test.go
enterprise/server/vmexec/BUILD
enterprise/server/vmexec/vmexec.go
enterprise/server/vmexec/vmexec_test.go
go.mod

This PR makes sure we report VM CPU / memory usage, not just the usage from the top level task. In particular, make sure we report CPU / memory from docker-in-firecracker containers.
This will make it easier to diagnose OOMs, and also let us gather more accurate usage numbers.
Verified using the vmstart tool:
* Added some temp logging in `vmexec` to print the current cpu/memory
* To verify CPU usage, ran `while true; do : ; done` and observed that CPU was steadily increasing by roughly 1000 CPU-ms per second.
* To verify memory usage, ran `VAL=$(cat /dev/random | head -c 500000); while true; do STR="$STR:$VAL" ; done` and verified that mem usage was steadily increasing by several MB per second.

Report usage stats from the whole VM, not just the exec'd process tree

---

server/util/grpc_client/grpc_client.go
server/util/grpc_server/grpc_server.go

Allocs before (3 runs of smash.go):
Allocs after (also 3 runs of smash.go):
This claims ~40% reduction in allocations (2G vs 3.7G) for bytestream reads (and about a 80% decrease in allocations on the actual path that allocates the recv buffer in this toy harness), and doesn't seem to have a meaningful impact on request latency, so hopefully it will help with GC pressure.

make grpc use RecvBufferPools

---

cli/add/add.go
cli/fix/fix.go
cli/fix/golang/golang.go
cli/translate/yaml/yaml.go
cli/workspace/workspace.go
docs/cli-plugins.md
server/util/bazel/bazel.go

This adds support for MODULE.bazel files in the CLI in a few places:
- When trying to find the workspace root when there is no WORKSPACE file present
- When auto-generating a MODULE.bazel file in Bazel 6.4 or later when bootstrapping a non-bazel repository
- When running `bb add` for example `bb add rules_go` when a MODULE.bazel file exists
- When converting from a MODULE.yaml => MODULE.bazel file

[CLI ] Add support for MODULE.bazel files

---

server/util/grpc_client/grpc_client.go

Before:
After:
Delta: (718713265-123938889)/718713265 = 82% fewer allocs?

Share write buffers (to reduce allocs)

---

tools/metrics/grafana/dashboards/buildbuddy.json
tools/metrics/grafana/dashboards/cache.json
tools/metrics/grafana/dashboards/clickhouse.json
tools/metrics/grafana/dashboards/mac.json
tools/metrics/grafana/dashboards/nodes.json
tools/metrics/grafana/dashboards/rbeperf.json
tools/metrics/grafana/dashboards/workflow.json
tools/metrics/grafana/grafana.go
tools/metrics/process_dashboard.py

Store the filename as a "file:" tag rather than slug. The slug apparently gets overwritten by grafana when re-saving the dashboard, while the tags remain stable.

Fix grafana dashboards saving as unexpected file name

---

.bazelrc
WORKSPACE
rules/yarn/index.bzl

Some minor changes that remove incompatible attributes and flags that
are going away in Bazel 7.
`rules_webtesting` was also upgraded to latest version with some
bug fixes in removing `browser_overrides` attributes in
`wrap_web_test_suite`.

bazel: prepare for bazel 7

---

enterprise/server/remote_execution/containers/firecracker/firecracker_performance_test.go
enterprise/server/remote_execution/containers/firecracker/firecracker_test.go

Some of our recent changes have broken the remote snapshot sharing related tests: 
1. NewContainer now mutates the opts to set executor config fields. If you try to use the original opts to load a snapshot, the digests won't match
2. You must have a workflow ID set to enable remote SS

[SS] Fix firecracker tests

---

enterprise/app/repo/repo.tsx
enterprise/server/gcplink/BUILD
enterprise/server/gcplink/gcplink.go
enterprise/server/oidc/BUILD
enterprise/server/oidc/oidc.go
server/backends/github/github.go
server/interfaces/interfaces.go
server/libmain/libmain.go

Adds a new endpoint `/auth/gcp/link/` that sends folks through the Google Cloud scope acceptance flow (rather than hijacking the `/login/` and `/auth/` flow).
This also fixes the issue where we'd use a different gcp client for linking vs exchanging auth tokens.

Separate `gplink` from `oidc.go`

---

app/picker/picker.tsx
app/picker/picker_service.ts
enterprise/app/repo/repo.css
enterprise/app/repo/repo.tsx

Shows this if the user doesn't have any GCP projects:
And this at the bottom if the user does have projects:

Gracefully handle case where the user doesn't have any GCP projects

---

app/footer/footer.tsx

Allows you to quickly see release notes for the current release by clicking this guy:

Make version number in footer link to Github release

---

enterprise/server/auditlog/auditlog.go
server/buildbuddy_server/BUILD
server/buildbuddy_server/buildbuddy_server.go
server/interfaces/interfaces.go
server/testutil/testauditlog/testauditlog.go

This allows us to build //server/buildbuddy_server with one fewer
//enterprise dependency.

auditlog: move helper functions to server/auditlog_util

---

server/backends/blobstore/gcs/gcs.go

I was really impressed with GCS upload time until I realized because of the defer, we're only recording how long it takes to write to a pipe; not to actually complete the write on GCS.
Fix that.

Include writer.Close() time in gcs tracing

---

server/rpc/interceptors/interceptors.go
server/util/bazel_request/BUILD
server/util/bazel_request/bazel_request.go
server/util/usageutil/BUILD
server/util/usageutil/usageutil.go

just by doing a normal build I see this has a significant impact in reducing allocations because we're not re-extracting that metadata proto over and over again.

Reduce allocations when extracting invocation ID

---

enterprise/server/backends/distributed/distributed.go

We discussed over lunch the idea of reducing FindMissing fanout. This change limits the number of nodes contacted for each digest in a FindMissing call to 1 at the risk of returning false-positive responses in FindMissing (basically: saying something is missing when really we have it).
We don't believe this should cause issues because the cases where digests are not on the correct replica are rare and if they are encountered we'll possibly trigger an extra write

Reduce findmissing fanout

---

enterprise/server/remote_execution/snaploader/snaploader.go

This is causing about 2-3 seconds of delay for every firecracker action w/ COW enabled and also lots of disk I/O.

Fix UnpackContainerImage always converting image to COW

---

enterprise/server/remote_execution/containers/firecracker/firecracker.go
enterprise/server/remote_execution/snaploader/snaploader.go

`loader.GetSnapshot` is used by `UnpackContainerImage` so we're incorrectly recording runner hits/misses when calling that `UnpackContainerImage`. We want the hit rate to apply to the whole VM snapshot, not the containerfs snapshot.
Side note, a containerfs hit/miss is not a huge deal since we can just chunk up the local containerfs on disk into a COW which only takes a few seconds. So we probably don't need a separate metric for this for now.

Fix workflow hit rate metric

---

enterprise/server/scheduling/scheduler_server/BUILD
enterprise/server/util/vsock/BUILD

These are no longer needed now that //server could be built
independently from //enterprise.
There are still some part of //cli that depend on //enterprise directly,
but we could address it separately.

chore: cleanup TODOs related to package visibility

---

enterprise/server/remote_execution/cgroup/BUILD
enterprise/server/remote_execution/cgroup/cgroup.go
enterprise/server/remote_execution/containers/podman/BUILD
enterprise/server/remote_execution/containers/podman/podman.go

* Move all the cgroup stuff from `podman.go` to a new package `cgroup.go` since it's growing a bit, and we also want to use this for Docker.
* Instead of requiring the cgroup flags, walk the /sys/fs/cgroup tree, searching for the cid in the path, and determine mem/cpu paths from that.
* The dir scanning approach is used because there are several different variables that determine what the paths will actually be - whether systemd is used or not, whether we're on cgroup v1 or v2, whether podman is running rootless or not... maybe other stuff (that may possibly change in the future?) I figured it was too complicated and error-prone to try and take all of these things into account.
* In terms of performance, it takes 8ms to scan the cgroupfs tree (tested on a GCP VM). It succeeds very quickly …

podman: determine cgroup paths automatically

---

.bazelrc
app/trace/BUILD
app/trace/trace_viewer.tsx

With this change, clicking on an event with a target label takes you to the target page.
Some changes on the way to the target page to make this more useful.

Make trace events with target label clickable

---

tools/metrics/grafana/dashboards/workflow.json

* Add chart for new memory-mapped bytes gauge
* Slight cleanup / styling tweaks on runner reuse rate chart (set min/max to [0,1], use filled line chart instead of bar chart)
* Update dirty byte chart to show a rate instead of cumulative counter value, and use human readable axis units

Small improvements/additions to workflow dashboard

---

app/invocation/invocation_action_card.tsx
app/invocation/invocation_model.tsx

This will allow us to use it outside of the action card.

Move `getCacheAddress` to invocation_model

---

platforms/BUILD

We should not be setting Arch=amd64 when we want to target arm64.

platforms: fix macos arch exec_properties

---

enterprise/server/remote_execution/copy_on_write/BUILD
enterprise/server/remote_execution/copy_on_write/copy_on_write.go

In the COWStore, we need locking to prevent concurrent access of maps, and also to synchronize simultaneous actions on a chunk - in particular when we're copying a chunk. We copy chunks when they are written to. When copying, we first initialize an empty chunk, and then copy over the original data to it. We need to make sure concurrent goroutines don't try to read from the empty new chunk, or write to the outdated old chunk for example.
Our hypothesis (validated below) is that locking in this second case hurts performance, because it's wrapped around a large and slow chunk of code that includes copying the data over. This PR adds a finer grained lock in this case, so we can just lock access to that chunk and not the entire store.
Testing PR: #5334 
For an incremental build on gazelle …

[SS] Use finer-grained locking in COWStore

---

app/invocation/BUILD
app/invocation/invocation_artifacts_card.tsx
app/invocation/invocation_target_group_card.tsx
app/target/BUILD
app/target/target_artifacts_card.tsx

This makes it easier to compare the digests & sizes against cache requests / other invocations, etc.

Add little digest widgets next to artifacts

---

app/invocation/invocation.tsx
app/target/BUILD
app/target/target_v2.tsx

This makes the target page much more useful, as it links the target to the action(s) that it spawns, as well as the CAS artifacts that it uploads.
It also means that in conjunction with the clickable timing profile, we now have a way to link the timing profile, the target page, and remote cache requests / executions.
This change also makes the target card load even if the target wasn't mentioned in the BES, since it might be a dependency that is not announced that we still have cache request / timing profile entries for.

Add a target scoped cache requests card to the target page

---

app/router/router.tsx
enterprise/app/org/create_org.tsx
enterprise/app/org/org.css

With this change, it will show this page instead:

Don't show `Access denied` page if the user isn't a member of any orgs

---

proto/action_cache.proto
proto/build_event_stream.proto
proto/failure_details.proto

Quick recap:
```bash
> export OLD_COMMIT=76117b4a43b552c681dcf841704fedfd60d3e37b
> export LATEST_COMMIT=5ee3ddce8653263d8280ce0163062cb7f5f9d8d4
> git log --stat --oneline "$OLD_COMMIT...$LATEST_COMMIT" -- **/*.proto
5ee3ddce86 Log WorkerMetrics of killed workers in the BEP and why they were killed. Also include the number of actions executed of each worker process.
src/main/java/com/google/devtools/build/lib/buildeventstream/proto/build_event_stream.proto | 32 +++++++++++++++++++++++++++++++-
1 file changed, 31 insertions(+), 1 deletion(-)
6fb551f04e Add load time of action cache to statistics.
src/main/protobuf/action_cache.proto | 6 +++++-
1 file changed, 5 insertions(+), 1 deletion(-)
4b7c808ec9 Forbid simultaneously requesting both a JSON and binary execution log. …
```

proto: sync from Bazel @ 5ee3ddce

---

app/trace/constants.ts
app/trace/trace_viewer.tsx
app/trace/trace_viewer_panel.ts

- Use a slightly off black for text to make it a little less harsh
- Reduce horizontal whitespace between to half a pixel to reduce empty whitespace a bit
- Slightly reduce font size of labels by 1px
- Fix hovering of events without args (which I borked a bit in my previous PR)
- Make events less than 1px wide render as 1px wide if they don't have a rendered event starting less than 1px before it
- Bump hover target for events less than 1px wide up to 1px 
If you hate any of these changes, let me know and I'll revert them (this is your baby and I defer to you). If we end up not liking some of these changes in dev / or prod, we can always roll them back.
Before dense:
After dense:
Before remote threads:
After remote threads:

Trace viewer tweaks

---

server/util/retry/retry.go
server/util/retry/retry_test.go

Also fixes inconsequential timer leak in retry.Next

retry.Do should return context error if context is done on 1st attempt.

---

server/util/retry/BUILD
server/util/retry/retry_test.go

Whether the timer or context done channel is selected is non-deterministic so it's not guaranteed that the function is not run.
Have the test function return an error and verify that an error is always returned, regardless of whether the function is run or not.

Fix retry test flakiness.

---

enterprise/server/remote_execution/executor/executor.go

We are seeing a bunch of firecracker processes taking up lots of memory while they are pausing. This resource usage is untracked by the priority_task_scheduler, which is likely contributing to overscheduling and executor restarts. So we should make sure to keep the resource claims held until the pause is complete.
One small consideration here: because priority_task_scheduler is currently responsible for keeping the lease, this means we're unnecessarily keeping the lease held while we're pausing. This increases the chances slightly of retrying the task unnecessarily. This would be mostly solved by our recent discussions around having LeaseTask + PublishOperation be the same stream, so that a task can't be re-leased if we've already published the COMPLETED operation on the stream. We could …

Keep runners' local resource claims held while pausing

---

enterprise/server/remote_execution/containers/firecracker/firecracker_performance_test.go

The remote snapshot sharing flag affects the setup of the firecracker container, so must be set first.

[SS] Fix performance tests

---

enterprise/server/backends/pebble_cache/pebble_cache.go

io.Copy() perform better than io.ReadAll when reading big inputs:
Here is the benchmark for PebbleCache.Get (cdc disabled)
```
goos: linux
goarch: amd64
│ /home/lulu/baseline_readall_nocdc.log │ /home/lulu/benchmark_copy_nocdc.log │
│                sec/op                 │    sec/op     vs base               │
Get/Pebble/size=10-24                                    8.290µ ± 5%   9.132µ ±  3%  +10.16% (p=0.002 n=6)
Get/Pebble/size=100-24                                   8.753µ ± 4%   9.545µ ±  5%   +9.05% (p=0.004 n=6)
Get/Pebble/size=1000-24                                  8.889µ ± 4%   9.777µ ±  6%  +10.00% (p=0.002 n=6)
Get/Pebble/size=10000-24                                 16.22µ ± 4%   17.14µ ±  8%   +5.68% (p=0.026 n=6) …
```

use Copy instead of ReadAll in pebble_cache.Get()

---

enterprise/server/backends/pebble_cache/pebble_cache.go

Optimize newChunkedReader to directly copy data to piped writer instead of using
a temporary bytes.Buffer in (Get()).
Below is the benchmark result. Note CDC was enabled when the size is 0.5MB. 
```
goos: linux
goarch: amd64
│ /home/lulu/baseline-cdc-get.log │  /home/lulu/benchmark-cdc-get.log  │
│             sec/op              │   sec/op     vs base               │
Get/Pebble/size=10-24                             9.088µ ±  8%   9.072µ ± 7%        ~ (p=0.699 n=6)
Get/Pebble/size=100-24                            9.603µ ±  6%   9.567µ ± 2%        ~ (p=0.485 n=6)
Get/Pebble/size=1000-24                           9.840µ ±  5%   9.914µ ± 2%        ~ (p=0.420 n=6)
Get/Pebble/size=10000-24                          17.06µ ±  6%   17.06µ ± …
```

CDC Optimization: Don't use Get in newChunkedReader

---

dockerfiles/executor_image/Dockerfile

4.6.2 was removed from the repo we're using.
Tested in dev. Sanity-checked perf, running `podman run --rm --net=none --transient-store ubuntu:22.04 true` still takes around 170ms.

Upgrade podman to 4.7.2

---

enterprise/server/remote_execution/copy_on_write/copy_on_write.go
enterprise/server/remote_execution/copy_on_write/copy_on_write_test.go

* Add a concurrency-safe `Unmap` function to allow safely unmapping chunks at any time. The plan is to call this from an LRU `OnEvict` callback, which will unmap the least recently used chunk in order to save memory.
* Add a concurrency-safe `Fetch` function and call this function when eager-fetching, instead of calling `initMap`. This makes sure that we don't `mmap` unless the chunk is actually needed, since `mmap` incurs extra memory usage and causes extra churn on the LRU if the chunk is not actually used.
* Now that `Unmap` can be called at any time, fix a concurrency issue in certain mmap operations where we momentarily releasing the lock after calling `initMap`. During this time that we're not holding the lock, it is valid for `Unmap` to be called, which would result in a panic when …

Update mmap to support memory limit changes

---

server/backends/blobstore/disk/BUILD
server/backends/blobstore/disk/disk_test.go
server/backends/blobstore/util/util.go

1. Add a benchmark test for ReadBlob and WriteBlob
2. use io.Copy in util.Decompress
3. use buf.Bytes instead of io.ReadAll in util.Compress
Our current blob write size is the median is 5K, 95% is 800K. Here's the benchmark result after the change:
```
│ /home/lulu/benchmark-rw-baseline.log │  /home/lulu/benchmark-rw-after.log  │
│                sec/op                │    sec/op     vs base               │
ReadBlob/size=10-24                                 22.81µ ± 11%   21.72µ ± 14%        ~ (p=0.180 n=6)
ReadBlob/size=1000-24                               28.10µ ± 14%   27.44µ ±  2%        ~ (p=0.065 n=6)
ReadBlob/size=10000-24                              75.63µ ±  1%   71.12µ ±  6%   -5.97% (p=0.002 n=6)
ReadBlob/size=100000-24 …
```

Optimize ReadBlob and WriteBlob

---

enterprise/tools/replay_action/replay_action.go

This is a bit more convenient, especially when SSH'd into a GCP VM where setting up auth is a pain.

replay_action: log warning instead of failing when target_api_key is unset

---

enterprise/server/scheduling/task_leaser/task_leaser.go

These add a lot of noise, and the logs being added in https://github.com/buildbuddy-io/buildbuddy/pull/5284 are probably more actionable.

Revert task_leaser debug logs

---

enterprise/server/remote_execution/containers/firecracker/firecracker.go
enterprise/server/remote_execution/snaploader/snaploader.go

* `GetSnapshot()` logs hits/misses for the containerfs snapshot which is confusing because without more context, it looks like the hit/miss is referring to the whole VM snapshot. This PR makes it so we only log for the whole VM snapshot.
* The hit rate metric has an issue that I introduced when attempting to fix a different issue - if `createFromSnapshot` is false then we won't call `LoadSnapshot()` and record the miss. So I think we'll effectively always report a 100% hit rate. Fixed in this PR

Fix confusing snapshot logging and hit rate metric

---

app/invocation/invocation.css
app/trace/BUILD
app/trace/constants.ts
app/trace/trace_viewer.css
app/trace/trace_viewer.tsx
app/trace/trace_viewer_panel.ts

This allows you to search the timing profile by event name, target, mnemonic, category, or output name.
Event that match will be shown in color, while all other events will be greyed out.
Example:

Add a filter to the timing profile

---

enterprise/server/raft/leasekeeper/leasekeeper.go
enterprise/server/raft/nodeliveness/BUILD
enterprise/server/raft/nodeliveness/nodeliveness.go
enterprise/server/raft/store/store.go

rangelease acquisition is driven by raft leadership changes, ranges being added or removed, or node liveness state changes. Race conditions were possible in the previous code because multiple differing requests could simultaneously be pending to update a lease.
this change fixes those race conditions by running a single goroutine per rangelease, and only allowing it to process one range lease instruction at a time.

One thread per rangelease

---

enterprise/server/raft/constants/constants.go
enterprise/server/raft/nodeliveness/BUILD
enterprise/server/raft/nodeliveness/nodeliveness.go
enterprise/server/raft/nodeliveness/nodeliveness_test.go
enterprise/server/raft/rangelease/rangelease_test.go
enterprise/server/raft/store/store.go

Reverts buildbuddy-io/buildbuddy#5406
I was too hasty; this works great in tests but not in real usage. Will fix in a different way.

Revert "Nodeliveness needs only nodehost; not sender"

---

enterprise/server/remote_execution/containers/firecracker/firecracker.go

When running from a completely cold cache (e.g. during autoscaling), we've exceeded the 30s timeouts when attempting to unpause and exec, because it can take longer than this timeout value to fetch all of the necessary UFFD / disk chunks.
Bump to 60s to reduce the rate at which we hit these timeouts.
Also, clean up an unused timeout const.

Increase VM timeouts

---

server/build_event_protocol/build_status_reporter/build_status_reporter.go

Doesn't really feel like it should be a failure (we do a weird hack internally where we create a dummy //:pass test to work around this currently).

Don't return a failure to github if no tests were found

---

app/invocation/invocation_model.tsx
server/build_event_protocol/event_parser/BUILD
server/build_event_protocol/event_parser/event_parser.go
server/build_event_protocol/event_parser/event_parser_test.go

Bazel sends multiple command line events to the BES server:
- `original`
- `canonical`
Where the `canonical` event is the effective one while the `original`
event is algamation of command line flags and `.bazelrc` configs.
Additionally, users may specify `--experimental_tool_command_line` to
send the command line from layers of Bazel wrappers.
Let's filter for `canonical` command line event to parse since it's the
most accurate one. The other 2 events are still available via raw bep
JSON and could be inspected accordingly from our UI (if they are not
empty).
References:
- https://cs.opensource.google/bazel/bazel/+/master:src/main/java/com/google/devtools/build/lib/runtime/CommandLineEvent.java;drc=dab6383ecef2d3996a67b2b1e4760369abc08de7

event parsing: only use 'canonical' StructuredCommandLine event

---

buildfix.sh

Gofmt will sometimes fail on proto symlink errors. Don't fail the rest of the buildfix script in these cases.

Don't fail buildfix on gofmt errors

---

enterprise/server/remote_execution/copy_on_write/copy_on_write.go

The first time a firecracker VM is paused, it's very slow because it has to translate the memory snapshot to a COW store. Add multiple goroutines to speed up that conversion. This should hopefully make the tests faster too, because we're doing a lot of COW conversions.
For a clean VM with 10_000MB memory, ConvertFileToCOW() time in the performance tests decreased 6s from 15 - 9s with 8 goroutines. Overall Pause time decreased from 50s - 44s. Most of the time in Pause was spent in `c.machine.CreateSnapshot` (~35s). Local testing might not be the most accurate way to test this though, because Pause is much faster in dev, probably due to faster disks.

[SS] Convert file to COW with multiple goroutines

---

enterprise/server/raft/rangelease/rangelease.go
enterprise/server/raft/store/store.go
enterprise/server/raft/store/store_test.go

These changes have made the store tests more reliable:
```
tylerw@lunchbox:~/buildbuddy$ blaze test enterprise/server/raft/store:store_test  --cache_test_results=false  --config=remote --runs_per_test=100
INFO: Invocation ID: 34cf5647-2c2c-4935-a405-0577b5879a8d
INFO: Streaming build results to: https://buildbuddy.buildbuddy.io/invocation/34cf5647-2c2c-4935-a405-0577b5879a8d
INFO: Analyzed target //enterprise/server/raft/store:store_test (0 packages loaded, 0 targets configured).
INFO: Found 1 test target...
Target //enterprise/server/raft/store:store_test up-to-date:
bazel-bin/enterprise/server/raft/store/store_test_/store_test
INFO: Elapsed time: 53.755s, Critical Path: 39.96s
INFO: 806 processes: 1 internal, 805 remote.
//enterprise/server/raft/store:store_test …
```

Wait for leases when testing

---

dockerfiles/executor_image/Dockerfile
enterprise/server/remote_execution/containers/podman/podman.go
enterprise/server/test/integration/podman/BUILD

The issue was a combination of: inconsistent selection of the storage-driver between our code and the podman code between the `podman version` (which has an empty storage driver) call and the first `podman image exists` call (which uses the overlayfs storage driver in dev), and a [bug](https://github.com/containers/podman/issues/20731) in the new sqlite database they're using. I expect this will be fixed in 4.8.1 or 4.8.2, but it's probably wise to explicitly specify the storage driver for all podman commands anyways.
I have aspirations to refactor our podman command-running logic and add some tests, but will save those for another PR.
**Related issues**: https://github.com/buildbuddy-io/buildbuddy-internal/issues/2932

Upgrade executors to podman 4.8.0

---

enterprise/server/remote_execution/containers/firecracker/firecracker.go
server/metrics/metrics.go

Oops! The previous buckets were (in minutes):  {0.0016, 0.016, 0.16, 1.6, 16.6, 166.6}, which explains why the graphs made workflows seem suspiciously slow and all taking around 16 min.
Add more granularity into the buckets, and also a reminder to the help section that the values in the graphs don't represent the actual durations, but upper bounds of buckets. 
Open to suggestions for better buckets. I'm assuming there will be a lot of variation in the duration of workflows between different customers.

[SS] Fix buckets for firecracker stage metrics

---

cli/remotebazel/BUILD
cli/remotebazel/remotebazel.go
enterprise/server/hostedrunner/hostedrunner.go
proto/runner.proto

Seeing `GLIBC_2.28' not found` build errors on the 18.04 image

[BR] Upgrade bazel remote runner to use ubuntu 20.04 image

---

enterprise/server/test/integration/podman/podman_test.go

Agree that this isn't awesome, but it's nice to have the test coverage IMO.

Give podman commands 5 seconds to run and make some output in the timeout tests

---

dockerfiles/executor_image/Dockerfile
enterprise/server/remote_execution/containers/podman/podman.go
enterprise/server/test/integration/podman/BUILD

The previous attempt (https://github.com/buildbuddy-io/buildbuddy/pull/5431) had the wrong default storage driver name ("overlayfs" instead of "overlay"): https://cloudlogging.app.goo.gl/hDFLo8hJBYnDC4do6
**Related issues**: https://github.com/buildbuddy-io/buildbuddy-internal/issues/2932

Upgrade executor podman version to v4.8.0

---

server/backends/blobstore/aws/aws.go
server/backends/blobstore/azure/azure.go
server/backends/blobstore/disk/BUILD
server/backends/blobstore/disk/disk.go
server/backends/blobstore/gcs/gcs.go
server/backends/blobstore/util/BUILD
server/backends/blobstore/util/util.go
server/util/ioutil/ioutil.go

Refactor util.Decompress() so that it takes in a reader instead of bytes.
Currently, in ReadBlobs we call io.ReadAll(..) and then in util.Decompress(..)
we construct a bytes.Buffer as a reader to pass in NewCompressReader. All of
these seem unnecessary to me.
The benchmark showed smaller allocations for disk blob store. The result is as follows:
```
│ /home/lulu/benchmark-read-baseline.log │ /home/lulu/benchmark-read-opt.log │
│                 sec/op                 │   sec/op     vs base              │
ReadBlob/size=10-24                                    22.52µ ± 3%   23.11µ ± 4%  +2.62% (p=0.004 n=6)
ReadBlob/size=1000-24                                  27.66µ ± 9%   28.28µ ± 3%  +2.24% (p=0.041 n=6)
ReadBlob/size=10000-24 …
```

Optimize blobstore ReadBlobs

---

enterprise/server/remote_execution/containers/firecracker/firecracker.go
enterprise/server/remote_execution/copy_on_write/copy_on_write.go

The number of mmapped bytes was spiking in MergeDiffSnapshot, because there were some edge cases where we missed unmapping chunks we'd finished processing. Ex. We seek across holes in the data. If we seek to an offset in a new chunk, we should unmap the previous chunk we were in.
Passes this more robust unit test: https://github.com/buildbuddy-io/buildbuddy/commit/9fb18cca4685d7edf8ac81523eb8b81912b76e0e

[SS] Fix not unmapping chunks in MergeDiffSnapshot if we seek across chunk boundaries

---

buildfix.sh
tools/fix_go_deps.sh

Upgrade our `bb` CLI used in ./buildfix.sh to latest version.
Also ensure that the `bazel run //:gazelle` does not show up as a
separate PR check in CI..

style check tooling: minor fixes

---

docs/rbe-platforms.md

Categorized and document relevant `exec_properties` keys for users to
reference.
This does not include some properties that are specific to BuildBuddy
Workflows or debug properties that are used to assist development.
Also omit no-op properties such as `affinity-routing`.

rbe-platforms: document exec_properties

---

enterprise/server/oidc/oidc.go

The error message we return to the client doesn't contain the actual error.

Add debug log for auth token exchange

---

enterprise/server/remote_execution/container/container.go
enterprise/server/remote_execution/runner/BUILD
enterprise/server/remote_execution/runner/runner.go
enterprise/server/remote_execution/runner/runner_test.go

Problem:
- [Here](https://github.com/buildbuddy-io/buildbuddy/blob/2fc2e2243e8a619474564995de6319341cd32fab/enterprise/server/remote_execution/runner/runner.go#L360-L365) `runner.Run()` calls `Create()`, then transitions the runner from `s.initial` => `s.ready` state _only if Create succeeds_
- When `Create()` fails, we wind up calling `TryRecycle` which should call `finalize()` then `Remove()` [here](https://github.com/buildbuddy-io/buildbuddy/blob/2fc2e2243e8a619474564995de6319341cd32fab/enterprise/server/remote_execution/runner/runner.go#L1347) since the task did not finish cleanly
- But [here](https://github.com/buildbuddy-io/buildbuddy/blob/2fc2e2243e8a619474564995de6319341cd32fab/enterprise/server/remote_execution/runner/runner.go#L427) we explicitly don't call `Remove()` if the …

Fix VM not being removed if Unpause fails during Create

---

enterprise/server/remote_execution/platform/platform.go
enterprise/server/remote_execution/platform/platform_test.go
enterprise/server/scheduling/scheduler_server/scheduler_server.go
enterprise/server/scheduling/scheduler_server/scheduler_server_test.go
enterprise/server/scheduling/task_router/task_router.go
enterprise/server/test/integration/remote_execution/remote_execution_test.go
enterprise/server/test/integration/task_router/task_router_test.go
server/interfaces/interfaces.go

This is a customer feature request. I took the opportunity to refactor the `enqueueTaskReservations` function in `scheduler_server.go` and would appreciate a careful review!

Add a platform property that lets the user delay execution of tasks scheduled on non-preferred nodes.

---

enterprise/server/remote_execution/containers/firecracker/firecracker.go
enterprise/tools/vmstart/vmstart.go

- Add a flag to make it easier to test remote snapshotting with ad-hoc actions (I've been having to hard-code `supportsRemoteSnapshots` to true, because now we check arg0 == ./buildbuddy_ci_runner instead of checking workflow ID - with workflow ID I could fake it a bit more easily)
- Set this flag to true in `vmstart` to fix remote snapshot fetching.

Fix vmstart remote snapshot fetching

---

enterprise/server/util/cacheproxy/cacheproxy.go
enterprise/server/util/cacheproxy/cacheproxy_test.go
proto/distributed_cache.proto

When doing a new CAS write today, we're running 6 find-missing calls beforehand: 3 in bytestream (which calls cache.FindMissing) and 3 in cache_proxy, which does the same for CAS objects.
This CL removes the extra FindMissing calls happening in cacheproxy, and instead swallows the error if the server returns `ALREADY_EXISTS` for a CAS blob.
At the time I originally wrote this, I did not fully appreciate how many small writes we get, and thought preventing a large write was a good tradeoff. I no longer believe that: the extra cost of so many extra FindMissing calls is harmful, especially given the number of small writes we handle.

Short circuit distributed writes without calling FindMissing.

---

enterprise/app/login/login.tsx

This fixes an issue where we can't post messages between pages on different subdomains when doing a GitHub login from an org-specific subdomain. We already do this for non-GitHub logins.

Redirect to current URL after Github login

---

enterprise/server/test/integration/remote_execution/BUILD
enterprise/server/test/integration/remote_execution/remote_execution_test.go

Add a runner-recycling-max-wait to the two runner recycling tests in remote_execution_test to reduce flakiness a bit

---

enterprise/server/util/cacheproxy/cacheproxy.go

Streams are async so the Send in Write might not return an EOF even tho an ALREADY_EXISTS error has been returned. 
In that case the EOF can be hit in Commit(), so if that happens, attempt to call CloseAndRecv to check for an ALREADY_EXISTS before returning any error.

Handle grpc stream EOFs correctly

---

enterprise/server/remote_execution/containers/firecracker/firecracker.go

This is mostly to make the logs a bit less confusing, but is also a minor optimization. I found it surprising/confusing that we were pulling the base containerfs snapshot when resuming from a rootfs snapshot, which should have the full disk contents that we need.

Don't pull image when resuming from rootfs snapshot

---

cli/cmd/bb/BUILD
cli/cmd/bb/bb.go
cli/watcher/BUILD
cli/watcher/watcher.go

Previously we only bump open file limit for `bb watch`.
Let's apply it to every commands.
Close #5465.

cli: bump open file limit for all commands

---

enterprise/server/remote_execution/containers/firecracker/firecracker.go
enterprise/server/remote_execution/containers/firecracker/firecracker_test.go
enterprise/server/vmexec/vmexec.go

Collect stats when the command terminates. This does two things:
* Guarantees that we report stats at least once for each command.
* Ensures that the last reported stats are accurate. Otherwise, we are potentially not accounting for the last several ms of command execution.
* The stats collection is polling based - it starts with a 10ms poll rate then exponentially backs off up to 250ms - so in the worst case we are ignoring the last 250ms of command execution

Collect VM stats when command terminates

---

enterprise/server/scheduling/task_router/task_router.go
enterprise/server/test/integration/task_router/task_router_test.go
enterprise/server/workflow/service/service.go

With 2 equally preferred nodes, we can potentially hit a situation where workflows are "bouncing" back and forth between the 2 preferred nodes.
To make things a bit easier to reason about, only use 1 preferred workflow node and add a small scheduling delay to increase the chances that we will use that node, so that instead of "bouncing" we just choose a new node which then becomes the preferred node.

Make workflow load balancing a bit more sane

---

enterprise/server/raft/store/store.go

Avoid spinning in the case there are no shards on a node.

Fix hot loop

---

server/http/interceptors/interceptors.go
server/http/protolet/BUILD
server/http/protolet/protolet.go
server/libmain/libmain.go

This adds support for server-side streaming (and paves the way for client side streaming with websockets in the future if we want it).
If we end up using this for a bit and liking it, we could delete all of the gnarly reflection protolet.go and simplify that code a ton.
The concepts used here are losely based on https://github.com/improbable-eng/grpc-web/blob/master/go/grpcweb/wrapper.go - so they've been tested in a production environment, but have been greatly simplified.
**Overview** 
Here's how it works:
- If the client sets the `application/grpc+proto` content type, we forward requests to the grpc server's `ServeHTTP` method.
- In order to support local development, we spoof HTTP2 requests by setting ProtoMajor and ProtoMinor. This is what the improbable library does too, so there's …

Add server support for `application/grpc+proto` over http

---

enterprise/server/remote_execution/runner/runner.go

Use CtxError for runner_maxed_out log

---

enterprise/server/remote_execution/runner/runner.go

By default, our disks are 20GB for workflow VMs. If we cap them at 90%, there's still 2GB of space leftover, which is a good amount of headroom. Bump up to a 99% cap for 0.2GB headroom.

[SS] Increase max recyclable resource utilization

---

enterprise/server/scheduling/scheduler_server/scheduler_server.go
enterprise/server/scheduling/scheduler_server/scheduler_server_test.go
enterprise/server/test/integration/remote_execution/remote_execution_test.go

https://github.com/buildbuddy-io/buildbuddy/pull/5344 was making `TestAppShutdownDuringExecution_LeaseTaskRetried` in remote_execution_test.go flaky for unexplained reason. The revert isn't clean, but there weren't any changes to `scheduler_server.go`, so I just reverted that file, fixed the one build failure, re-enabled `TestAppShutdownDuringExecution_LeaseTaskRetried`, and re-implemented the non-preferred scheduling delay in the reverted code. I'll pursue the refactor independently, as `enqueueTaskReservations()` is quite a mess now.
**Related issues**: https://github.com/buildbuddy-io/buildbuddy-internal/issues/2968

Revert scheduler_server.go refactor and reimplement delay functionality in reverted code

---

enterprise/tools/replay_action/replay_action.go

Can be useful to have once we have `action_id` tagging (#5515), as another way to group and compare tracing results.

Send `action_id` with `replay_action`

---

app/service/rpc_service.ts
proto/config.proto
server/static/static.go

Client side support for server-side grpc streaming over http.
This is behind a `app.streaming_http_enabled` flag.
If that flag is enabled, we'll do three things: 
- We'll change our content-type from `application/proto` to `application/grpc+proto`
- We'll send proto messages as `Length-Prefixed-Message`s (see https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-HTTP2.md)
- We'll read the response as a stream rather than just a single arraybuffer.
There is a TODO in there to support messages that come across chunks. This should be relatively straightforward to implement, but I haven't run into it in my testing - and would like to run into it before fixing.
Depends on: https://github.com/buildbuddy-io/buildbuddy/pull/5505

Client side support for http streaming

---

enterprise/server/backends/pebble_cache/BUILD
enterprise/server/backends/pebble_cache/pebble_cache_test.go

1. add different sizes to benchmark tests
2. remove Contain benchmark test (Contain is calling FindMissing)
3. increase log levels in benchmark tests

Refactor pebble cache benchmark test

---

tools/metrics/grafana/dashboards/buildbuddy.json
tools/metrics/grafana/dashboards/cache.json

This PR changes how we display the legends for Grafana cache usage and disk cache
filesystem usage graph. It show labels with their last non-null values directly 
in table mode.
I find it difficult to figure out which apps uses >90% cache when all the lines
are clustered together when I hover over the graph. The table mode allows me to
sort by values and make it easier to identify the hot apps.
Also, there are times when the partition usage > 100%; and we are not showing them on the graph.

Make cache usage graph more readable

---

enterprise/server/remote_execution/runner/BUILD
enterprise/server/remote_execution/runner/runner.go
server/metrics/metrics.go

Having an alert per event is too noisy. Add a custom metric instead. 
PR to alert on the new metric: https://github.com/buildbuddy-io/buildbuddy-internal/pull/2973

[SS] Emit a custom metric instead of an alert if a runner won't get recycled due to max resource utilization

---

enterprise/server/backends/pebble_cache/pebble_cache.go

This is not strictly necessary in practice since we only have one lockmap per app instance, but it's nice to clean up the lockmap for testing purposes.

Clean up lockmap gc goroutine in PebbleCache

---

proto/execution_stats.proto

This PR adds the proto changes needed to show `ExecuteResponse` in the action page instead of `ActionResult`. Showing `ExecuteResponse` has two advantages:
* It means we'll show the actual `ExecuteResponse` for the execution ID, rather than the latest `ActionResult` associated with the action digest. The latter is inaccurate/incorrect and often confusing.
* The `ExecuteResponse` contains a superset of info, such as:
* The `status` field (execution error details when the task either fails to start, or terminates abnormally), which is not representable by an ActionResult.
* An optional `server_logs` field which allows attaching arbitrary logs. We can use this for attaching firecracker VM logs.
Note, this does **NOT** take any steps towards addressing …

Proto changes for showing ExecuteResponse in the UI

---

.github/workflows/release-m1.yaml
.github/workflows/release-mac.yaml
.github/workflows/release.yaml

This will fix populating the version tag when we manually trigger the github release upload. [(Slack thread)
](https://buildbuddy-corp.slack.com/archives/C0495TM9UUE/p1702561546424619)

Fix populating the version tag in github release workflows

---

app/service/rpc_service.ts
server/http/protolet/protolet.go

This makes a bit more sense because the client is not really sending a grpc request. It's sending a `Length-Prefixed-Proto` request. The fact that we're passing this to the grpc server behind the scenes is more of just a server-side implementation detail that the client shouldn't need to know about.
This also avoids other systems (and other parts of our system) from trying to interpret and route these requests as if they were real grpc requests (for example this code https://github.com/buildbuddy-io/buildbuddy/blob/master/server/util/grpc_server/grpc_server.go#L268).

Use `application/proto+prefixed` content type

---

enterprise/server/remote_execution/execution_server/execution_server.go

**Related issues**: [2997](https://github.com/buildbuddy-io/buildbuddy-internal/issues/2997)

Add trace span annotation showing result of execution_server.execute()

---

enterprise/server/backends/pebble_cache/pebble_cache_test.go

```
INFO: Elapsed time: 6.113s, Critical Path: 3.47s
INFO: 401 processes: 1 internal, 400 linux-sandbox.
//enterprise/server/backends/pebble_cache:pebble_cache_test              PASSED in 3.5s
Stats over 400 runs: max = 3.5s, min = 0.0s, avg = 0.3s, dev = 0.6s
```

[DEFLAKE] Loosen up version restriction in version test

---

tools/metrics/grafana/dashboards/jaeger.json
tools/metrics/prometheus/prometheus.yml

Add the dashboard from https://github.com/jaegertracing/jaeger/blob/main/monitoring/jaeger-mixin/dashboard-for-grafana.json (internal PR to follow). This is for monitoring Jaeger itself, and should (hopefully) help us see whether it's keeping up with the incoming trace volume.
Tested it locally and saw some data showing up in the dashboard when running some requests with `x-buildbuddy-trace=force`
Screenshot (there are more dashboards if we scroll down, these are just a few)
**Related issues**: https://github.com/buildbuddy-io/buildbuddy-internal/issues/2998

Add Jaeger dashboard

---

tools/metrics/grafana/dashboards/jaeger.json

See https://github.com/jaegertracing/jaeger/issues/5007
It seems like either the Grafana dashboards are wrong, or jaeger isn't exporting the correct metric names.
For now, just update the Grafana dashboard queries to match the actual metrics that are exported.

Drop 'collector' prefix from jaeger dashboard queries

---

enterprise/server/scheduling/scheduler_server/BUILD
enterprise/server/scheduling/scheduler_server/scheduler_server.go
enterprise/server/scheduling/scheduler_server/scheduler_server_test.go

This issue was that the code in enqueueTaskReservations() was always overriding the Delay field, with either the calculated delay, or to reset it, so client-specified delays were discarded. In the lease-test in remote_execution_test, the scheduler receives a bunch of requests with a short delay specified, and without this bug fix it would just try to run them all at once, causing there to be more tasks started and breaking the check on line 1889 to fail: https://github.com/buildbuddy-io/buildbuddy/blob/9f701d8970267212b8b9c194734fb2c43c72048f/enterprise/server/test/integration/remote_execution/remote_execution_test.go#L1889

Roll forward enqueueTaskReservations refactor with a fix for the bug that was causing remote_execution_test to be flaky and a unit test for that bug.

---

app/service/rpc_service.ts

I managed to reproduce the case where the server flushes a proto response without the full proto message.
This seems to happen when a single proto message is larger than ~4kb.
This PR handles this on the client side (and completes the TODO) by:
- Reading the length-prefix at the beginning of the `Length-Prefixed-Message`
- If we get a stream read that is smaller than length of the message, create a Uint8Array that we can use to buffer the message until we've got the full thing
- Append to that buffer until we've got a full message
- Call the callback with the full buffer, and reset the buffer

Support partial client-side stream reads

---

server/metrics/metrics.go
tools/metrics/grafana/dashboards/workflow.json

Without `increase` our graphs were showing a cumulative value over time as opposed to real-time insights

[SS] Fix histograms

---

server/util/proto/BUILD
server/util/proto/proto.go
server/util/proto/proto_test.go
server/util/protoutil/protoutil.go

The intention is to replace "google.golang.org/protobuf/proto" with our own
proto package.

Rename protoutil to proto

---

enterprise/server/tasksize/BUILD
enterprise/server/tasksize/tasksize.go

Marshal for repb.Command is 47.21% faster
Marshal for scpb.TaskSize is 34.05% faster
Unmarshal for scpb.TaskSize is 47.21% faster
```
benchstat -col /name ~/benchmark-proto-taskSize.log.                                                                                                                                                                                         15s
goos: linux
goarch: amd64
│      Old      │                 New                 │
│    sec/op     │   sec/op     vs base                │
Marshal/pbName=TaskSize-24      287.8n ± 44%   189.8n ± 6%        ~ (p=0.239 n=10)
Marshal/pbName=Command-24      13.129µ ±  3%   6.931µ ± 2%  -47.21% (p=0.000 n=10)
Unmarshal/pbName=TaskSize-24    371.3n ±  9%   243.9n ± 6%  -34.30% …
```

Use vtproto in tasksize

---

server/util/paging/BUILD
server/util/paging/paging.go

Benchmark:
```
goos: linux
goarch: amd64
│     Old      │                 New                  │
│    sec/op    │    sec/op     vs base                │
Marshal/pbName=OffsetLimit-24     282.5n ± 17%   190.7n ±  4%  -32.48% (p=0.001 n=10)
Unmarshal/pbName=OffsetLimit-24   377.2n ± 15%   252.5n ± 30%  -33.07% (p=0.001 n=10)
geomean                           326.4n         219.4n        -32.78%
│      Old      │                  New                  │
│      B/s      │      B/s       vs base                │
Marshal/pbName=OffsetLimit-24     13.50Mi ± 21%   20.01Mi ±  4%  +48.20% (p=0.001 n=10)
Unmarshal/pbName=OffsetLimit-24   10.11Mi ± 18%   15.11Mi ± 23%  +49.36% (p=0.001 n=10)
geomean                           11.69Mi         17.39Mi …
```

use vtproto (un)marshal in paging

---

server/util/bazel_request/BUILD
server/util/bazel_request/bazel_request.go

**Related issues**: 
Benchmark result shows vtproto is faster and no extra memory allocation.
```
goos: linux
goarch: amd64
│     Old     │                 New                  │
│   sec/op    │    sec/op     vs base                │
Marshal/pbName=RequestMetadata-24     692.8n ± 8%   431.4n ±  3%  -37.72% (p=0.002 n=10)
Unmarshal/pbName=RequestMetadata-24   1.373µ ± 5%   1.083µ ± 16%  -21.16% (p=0.000 n=10)
geomean                               975.3n        683.4n        -29.93%
│     Old      │                  New                  │
│     B/s      │      B/s       vs base                │
Marshal/pbName=RequestMetadata-24     341.4Mi ± 9%   548.2Mi ±  3%  +60.56% (p=0.002 n=10)
Unmarshal/pbName=RequestMetadata-24   172.2Mi ± 5% …
```

use vtproto in bazel_request.go

---

.bazelrc

Mirror the change made in https://github.com/buildbuddy-io/buildbuddy-internal/pull/3009/files
We do not build container image directly from this repo, but it's good
to have the flag here for consistency and avoid potential cache misses.

bazelrc: disable rules_docker transition

---

enterprise/server/remote_execution/copy_on_write/copy_on_write.go

`Unpause` is a bottleneck for workflow performance - p90 Unpause time is about 25s according to metrics. For users, this means that 1 in 10 workflows spend about 25s in the "Invocation is waiting for available worker" state in the UI before they even start executing.
This PR reduces this latency by tuning the eager fetching parameters. Tested on some production snapshots - this reduces the LoadSnapshot duration from ~20-27s (~1.8 Gbps peak RX throughput, measured with `iftop`) to about 10.4s (~5 Gbps peak throughput).

Tune eager fetching to speed up LoadSnapshot

---

enterprise/server/backends/prom/BUILD
enterprise/server/backends/prom/prom.go
server/util/proto/proto.go

Add a few method alias in proto.go
Use MarshalOld instead of Marshal b/c MarshalVT() is slower and uses more memory than standard Marshal for mdb.Metrics
```
goos: linux
goarch: amd64
│     Old     │                 New                 │
│   sec/op    │   sec/op     vs base                │
Marshal/pbName=Metrics-24     4.853m ± 4%   5.904m ± 1%  +21.67% (p=0.000 n=10)
Unmarshal/pbName=Metrics-24   8.796m ± 2%   8.705m ± 2%        ~ (p=0.218 n=10)
geomean                       6.533m        7.169m        +9.74%
│     Old      │                 New                  │
│     B/s      │     B/s       vs base                │
Marshal/pbName=Metrics-24     476.8Mi ± 4%   391.8Mi ± 1%  -17.81% (p=0.000 n=10) …
```

use server/util/proto library in prom.go

---

app/invocation/invocation.css
app/root/root.css

Based on the advice here: https://twitter.com/pixeljanitor/status/1735758919509684360
Our current shadows have always felt a little dull and amorphous.
With this change, they become a bit more crisp and defined - but remain subtle.
Before:
After:

Nicer looking CSS shadows

---

.github/workflows/release-mac.yaml

Use Bazel 6.4.0 for non-m1 mac release for now.

---

cli/ask/ask.go
cli/fix/fix.go
cli/version/version_test.go

With the cli refactor, we no longer need to pass the command name to the handler because we parse it upfront in bb.go

Fix double passing bb cli commands to handlers 

---

.github/workflows/release-mac.yaml

It seems like the older versions are not compatible with Bazel 7.
Use of `XCODE_VERSION` instead of `DEVELOPER_DIR` for accurate
autoxcode_config result.

mac-release: fix Bazel 7 compatibility

---

.github/workflows/release.yaml

The `action-automatic-releases` action had some implicit behavior if the workflow was triggered by pushing a git tag. Now that we support manually running the workflow, we'll have to explicitly set `automatic_release_tag`.

Fix release workflow for manual triggers

---

proto/jaeger/BUILD
proto/jaeger/model.proto
proto/jaeger/query.proto
tools/jaegerquery/BUILD
tools/jaegerquery/jaegerquery.go

A small tool to help us measure remote execution performance by printing aggregated trace stats instead of having to view individual traces and/or add prometheus metrics in a ton of places just to get finer-grained metrics.
Example usage:
```
$ IID=$(uuidgen | tee /dev/stderr)
eddea668-aa9e-4d89-9473-858578d364cc
$ for _ in $(seq 100); do
bb execute --invocation_id=$IID \
--remote_header=x-buildbuddy-trace=force \
--exec_properties=dockerNetwork=off \
--remote_executor=grpcs://remote.buildbuddy.dev \
-- \
true
done
$ kubectl port-forward --namespace=monitor-dev statefulset/jaeger 16685:16685
$ bazel run -- tools/jaegerquery \
--service=app --tag=invocation_id=$IID --operation=build.bazel.remote.execution.v2.Execution/Execute
...
AVG_MS  OP
722.61  scheduler.Scheduler/LeaseTask
696.73 …
```

Add a basic tool to fetch and print jaeger trace stats.

---

enterprise/server/remote_execution/copy_on_write/BUILD
enterprise/server/remote_execution/copy_on_write/copy_on_write_test.go
enterprise/server/remote_execution/copy_on_write/cow_cgo_testutil/BUILD
enterprise/server/remote_execution/copy_on_write/cow_cgo_testutil/cow_cgo_testutil.go

* Add a `StoreTester` which allows reading and writing random ranges concurrently and also validates byte contents (rather than just checking whether the race detector is triggered)
* Use byte-range locking to avoid concurrent writes of overlapping byte ranges. In practice, the guest's block device driver will avoid doing these types of writes, because block device files do not guarantee atomicity for `read()` or `write()`. If we can assume that overlapping byte writes will never happen concurrently, we can acquire finer-grained locks (e.g. writes can lock per-chunk instead of locking the whole store)

Expand COW concurrency tests

---

enterprise/server/remote_execution/containers/podman/podman.go

Per my most recent comment in https://github.com/buildbuddy-io/buildbuddy-internal/issues/2844 we can lose some time in `podman.PullImage` due to the locking behavior. This span should measure when we start and for how long we're actually pulling the image, as opposed to messing around with locks, which will be basically the difference between `podman.PullImage` and `podman.pullImage`.
**Related issues**: https://github.com/buildbuddy-io/buildbuddy-internal/issues/2844

Add trace span in podman.pullImage()

---

.github/workflows/release-m1.yaml
.github/workflows/release-mac.yaml
.github/workflows/release.yaml

I realized that GITHUB_REF is always set, even if the workflow was not triggered by a push event.

Fix release workflows

---

.bazelrc

Bazel keeps trying to generate `MODULE.bazel` and `MODULE.bazel.lock` when I run certain commands. This seems to fix it.

Prevent bazel from generating MODULE.bazel file

---

rules/yarn/index.bzl
tsconfig.json
website/docusaurus.config.js

We were previously relying on `bazel` to create the `bazel-bin` dir for us, which is unsound because `bazel-bin` is only created after bazel successfully runs once. This means that `bazel clean && bazel build website` fails currently.
This PR adds a webpack resolver plugin to translate `bazel-bin` references to the real action input paths in the execroot. Basically, we want to do the same thing that we do in /tsconfig.json (listing out all the possible bazel-out/ paths), except docusaurus doesn't have a way to customize the tsconfig it uses, so instead we use a webpack plugin.

Fix bazel-bin references in docusaurus builds

---

enterprise/server/remote_execution/containers/firecracker/firecracker.go

I'm not really sure if old snapshots (non-shareable) and new snapshots (shareable) are compatible, but don't want to have to spend any time testing it - so when snapshot sharing is enabled, just ignore old persisted snapshots.

Firecracker: ignore old-style persisted snapshots when snapshot sharing is enabled

---

enterprise/server/remote_execution/copy_on_write/BUILD
enterprise/server/remote_execution/copy_on_write/copy_on_write.go
enterprise/server/remote_execution/copy_on_write/copy_on_write_test.go
server/util/boundedstack/BUILD
server/util/boundedstack/boundedstack.go
server/util/boundedstack/boundedstack_test.go

My hypothesis that motivated this PR was that when the `eagerFetchChan` is saturated we'll spend less time fetching newer/more important chunks and more time fetching older/less important chunks.
This PR changes the data structure for the eager fetch list from a buffered `chan` to a new `BoundedStack` data structure, so that new chunks can always be added to the list of chunks to be eagerly fetched, evicting the oldest chunk when the stack's capacity is exceeded. Under the hood, the `BoundedStack` is backed by a ring buffer, and it also exposes a channel that receives a value whenever an item is pushed (so that the eager fetch goroutines can be notified whenever it's safe to `pop`).
Did some testing, comparing `master` to this PR branch (`eager-fetch-prio`). Alternated between the two …

Improve chunk prioritization for eager fetching

---

enterprise/server/cmd/goinit/main.go
enterprise/server/remote_execution/containers/firecracker/firecracker.go
enterprise/server/remote_execution/containers/firecracker/firecracker_test.go

`Create()` and `Unpause()` both call `setupVFSServer` unconditionally, but it should be conditioned on whether VFS (experimental FUSE filesystem) is enabled.
Also, the VM unconditionally spawns the `vmvfs` binary, which isn't needed when VFS is not enabled.

Firecracker: don't setup VFS if not enabled

---

.gitignore

Ignore MODULE.bazel because bazel 7 is auto-generating one

---

enterprise/server/test/integration/remote_execution/rbetest/rbetest.go

`cmd.Wait()` times out when the executors are under high load. Increase the timeout to reduce flakes.

Increase rbetest command wait timeout

---

enterprise/server/scheduling/scheduler_server/BUILD
enterprise/server/scheduling/scheduler_server/scheduler_server.go
enterprise/server/scheduling/scheduler_server/scheduler_server_test.go

Causes https://buildbuddy-corp.slack.com/archives/C01D5GHRJ59/p1704318477269539 due to not refreshing nodes upon fully circling the nodering

Revert scheduler_server refactor

---

enterprise/server/remote_execution/containers/firecracker/firecracker_test.go
enterprise/server/remote_execution/dirtools/dirtools_test.go
enterprise/server/remote_execution/execution_server/execution_server_test.go
enterprise/server/remote_execution/snaploader/snaploader_test.go
enterprise/server/remote_execution/snaputil/snaputil_test.go
enterprise/server/scheduling/scheduler_server/scheduler_server_test.go
enterprise/server/workflow/service/service_test.go
server/build_event_protocol/build_event_server/build_event_server_test.go
server/remote_cache/byte_stream_server/byte_stream_server_test.go
server/remote_cache/content_addressable_storage_server/content_addressable_storage_server_test.go
server/testutil/testcache/testcache.go
server/testutil/testenv/testenv.go

TLDR don't call `testenv.LocalGRPCServer` in `testcache.Setup` - `testenv.LocalGRPCServer` is designed to be called at most once, and `testenv.LocalGRPCConn` is supposed to connect to the one server that was created. So, don't "hog" the server registration in `testcache.Setup` since the test setup code may want to register other services too. (Also, make it an error to call `LocalGRPCServer` more than once).
---
I ran into the following issue while adding a test case to `execution_server_test.go`:
- I needed to run an in-process gRPC server and register the ExecutionServer to it, so that I could make a real PublishOperation RPC in the test.
- Normally I would just call the RPC method handler directly, but this is a pain for streaming RPCs - it's easier to invoke the method as an actual …

Don't call `testenv.LocalGRPCServer` in `testcache.Setup`

---

enterprise/server/test/integration/remote_execution/remote_execution_test.go

Per https://buildbuddy-corp.slack.com/archives/C0694U6QC30/p1704394946753449 if the executor is added before the app proxy, it may register with app 1 and then be removed from the node pool when app 1 is shut down, causing the commands to fail. By registering it after the app proxy is installed, it always registers with app 2.
**Related issues**: [3004](https://github.com/buildbuddy-io/buildbuddy-internal/issues/3004)

Deflake TestAppShutdownDuringExecution_LeaseTaskRetried

---

server/util/proto/proto.go
server/util/proto/proto_test.go
server/util/vtprotocodec/vtprotocodec.go

Make proto.Marshal / Unmarshal signature the same as google's proto lib. 
It's going to be safer since it's going to return a compiler time error instead
of a runtime error when we try to marshal something other than a proto message.

use proto.Message instead of interface in Marshal/Unmarshal

---

app/invocation/BUILD
app/invocation/invocation.css
app/invocation/invocation_action_card.tsx
app/terminal/terminal.css
app/terminal/terminal.tsx

Now that we render `ExecuteResponse` instead of `ActionResult`, we can show `server_logs`. https://github.com/buildbuddy-io/buildbuddy/pull/5647 adds the VM log tail to `server_logs`.

Render server_logs field from ExecuteResponse

---

proto/BUILD
server/util/proto/BUILD
server/util/proto/proto.go
server/util/proto/proto_test.go

This change will update all current uses of proto.Clone to use vtproto generated
Clone method. vtproto generated Clone method is faster in general, except for `ScoreCard`, which I suspect shares the same cause as in https://github.com/buildbuddy-io/buildbuddy-internal/issues/3018.
Here is the benchmark:
```
goos: linux
goarch: amd64
│      Old      │                 New                  │
│    sec/op     │    sec/op     vs base                │
Clone/pbName=FileMetadata-24   14.708µ ± 18%   7.804µ ± 16%  -46.94% (p=0.000 n=10)
Clone/pbName=ScoreCard-24       1.268m ±  3%   1.299m ±  3%        ~ (p=0.063 n=10)
Clone/pbName=TreeCache-24       45.61m ±  1%   38.13m ±  2%  -16.39% (p=0.000 n=10)
Clone/pbName=ReadResponse-24    222.7n ± 41% …
```

Use VTproto generated clone method

---

app/invocation/invocation.tsx
app/invocation/invocation_tabs.tsx
enterprise/server/bes_artifacts/bes_artifacts.go

Render any artifacts which the user wrote to `BUILDBUDDY_ARTIFACTS_DIRECTORY`, such as the gRPC log.
Also fix a small issue that we weren't setting the digest/length metadata on the file, so the digest component appeared blank.

Render workflow artifacts in the UI

---

app/invocation/invocation_model.tsx

* Workflow actions don't publish a `canonical` command line event. Update the logic from https://github.com/buildbuddy-io/buildbuddy/pull/5362 to prefer the canonical command line if present but fall back to the original command line otherwise. 
* We could alternatively update workflows to send a `canonical` command line rather than an `original` one, but this approach feels more forgiving to BES clients in general.
* Fix `getCacheAddress()` incorrectly returning `address + instanceName` which results in bytestream URLs containing the instance name twice, like `grpc://remote.buildbuddy.io/instance-name/instance-name/...`

Fix workflow action result not being displayed in action page

---

.bazelrc

Since we are now using Bazel 7, we could replace the usage of
experimental_remote_build_event_upload with remote_build_event_upload.
The recent changes in the local MacOS LLVM toolchain made it so that the
compiler would be a lot noisier when the duplicate flag is given.
In our case, we see this in the form of 2 warnings below:
```bash
ld: warning: ignoring duplicate libraries: '-lm'
ld: warning: ignoring duplicate libraries: '-lm', '-lpthread'
```
For GoLink, our action currently looks like this:
```bash
bazel-out/.../builder
-param=bazel-out/.../vet_actual_/vet_actual-0.params
--
-extld
external/local_config_cc/cc_wrapper.sh
-buildid=redacted
-s
-w
-extldflags
-mmacos-version-min=10.11 -no-canonical-prefixes -fobjc-link-runtime -headerpad_max_install_names -Wl,-dead_strip -lm
```
where …

bazelrc: silence invalid warnings

---

.bazelrc

Reverts buildbuddy-io/buildbuddy#5663
We are not yet ready for the new xcode

Revert "bazelrc: silence invalid warnings"

---

tools/clickhouse

Add a script that starts a clickhouse server using docker, then prints the flags needed to connect to it.
Example usage: `bazel run enterprise/server -- $(tools/clickhouse)`

Add development script for local clickhouse

---

enterprise/server/raft/leasekeeper/leasekeeper.go
enterprise/server/raft/replica/replica.go
enterprise/server/raft/replica/replica_test.go
enterprise/server/raft/sender/BUILD
enterprise/server/raft/sender/sender.go

Scan was broken because we we're including a suffix on keys.
This made them appear lexicagraphically AFTER a key. For example:
start:         "\x02\x04\x00"
appeared before "\x02\x04-c0001n0001"
when in fact it should not include the suffix and "\x02\x04\x00" should come *after* "\x02\x04". 
This change fixes this issue by instead making the range-specific-ident a prefix.

Fix an issue with range-specific-key suffixing

---

enterprise/server/raft/bringup/bringup.go
enterprise/server/raft/store/BUILD
enterprise/server/raft/store/store_test.go

When running with real data and shards moving between nodes, I noticed that split transactions would fail after a while. This happened because the transaction being run to update range descriptors was taking place on nodes that did not hold the metarange. This meant that the SyncProposeLocal would fail, because that range was not held locally.
Working on a fix but wanted to add a failing test first.

Add a test that illustrates failing cross-cluster txn issue.

---

WORKSPACE
cli/fix/BUILD

https://github.com/bazelbuild/rules_go/releases/tag/v0.44.2
https://github.com/bazelbuild/bazel-gazelle/releases/tag/v0.35.0

Upgrade rules_go and gazelle

---

BUILD
enterprise/server/test/integration/remote_execution/proto/BUILD
proto/BUILD
proto/api/v1/BUILD
proto/jaeger/BUILD

In https://github.com/bazelbuild/rules_go/pull/3761, rules_go started deprecating away
the usage of https://github.com/golang/protobuf in favor of a combination of
https://github.com/protocolbuffers/protobuf-go and https://github.com/grpc/grpc-go/blob/master/cmd/protoc-gen-go-grpc.
This results in `go_proto_library` requiring these 2 new compilers.
As an convinience, a `go_grpc_library` macro was introduced to wrap around `go_proto_library`
to ensure that these 2 compilers are set by default.
Effectively, in our `go_proto_library` targets, switch our usage of the old compiler to the new pair of compilers.
We are not using `go_grpc_library` yet because Gazelle has yet to support it. https://github.com/bazelbuild/bazel-gazelle/pull/1711

proto: handle go proto library deprecation

---

app/invocation/invocation_model.tsx
app/invocation/invocation_overview.tsx

We already have the BES info needed to render it, so just show the detail chip.
**Related issues**: https://github.com/buildbuddy-io/buildbuddy-internal/issues/3042

Show OS/Arch in workflow overview

---

.bazelrc
.github/workflows/release-m1.yaml
.github/workflows/release-mac.yaml

As of Bazel 7.0 we aren’t using the apple_support cc_toolchain. Only `/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk` is included in `builtin_include_directories`. If we have `DEVELOPER_DIR` set to something else we can see errors like following:
```
ERROR: /private/var/tmp/_bazel_brentley/7e5d3aaeb704234ad9b80179b286c374/external/com_google_absl/absl/base/BUILD.bazel:95:11: Compiling absl/base/internal/spinlock_wait.cc [for tool] failed: absolute path inclusion(s) found in rule '@@com_google_absl//absl/base:spinlock_wait':
the source file 'absl/base/internal/spinlock_wait.cc' includes the following non-builtin files with absolute paths (if these are builtin files, make sure these paths are in your toolchain):
'/Applications/Xcode-15.1.0-Release.Candidate.app/Contents/Developer/Platfo …
```

Use the Xcode command-line tools instead of Xcode in Mac release workflows

---

.bazelrc

This is a follow-up of #5663.
A binary is linked for toolchains, it will be using
`--host_linkopt` instead of `--linkopt`.
This results in the following being left over from previous PR.
```bash
INFO: From GoLink external/io_bazel_rules_webtesting/go/metadata/main/main_darwin_arm64 [for tool]:
ld: warning: ignoring duplicate libraries: '-lm'
INFO: From GoLink enterprise/server/backends/prom/generate_docs/generate_docs_/generate_docs [for tool]:
ld: warning: ignoring duplicate libraries: '-lm'
INFO: From GoLink enterprise/server/cmd/executor/yaml_doc/yaml_doc_/yaml_doc [for tool]:
ld: warning: ignoring duplicate libraries: '-lm'
INFO: From GoLink server/cmd/buildbuddy/yaml_doc/yaml_doc_/yaml_doc [for tool]:
ld: warning: ignoring duplicate libraries: '-lm'
INFO: From GoLink …
```

.bazelrc: ignore duplicate flags cont.

---

.bazelrc
platform_mapping

In a previous change, we introduced --linkopt unconditionally on MacOS.
This cause remote builds with `--config=remote` to include those linker
flags in our Linux actions. And `ld.gold` did not like these Xcode 15
only flags.
Fix this by making sure that the linker flags are only applied when this
combination happen:
- We are building on MacOS. This is done by using the `common:macos`
profile that is automatically included by Bazel's
`--enable_platform_specific_config` flag.
- We are targeting the local MacOS platform. The local platform is
`@local_config_platform//:host`. We leverage Bazel's platform_mapping
feature to achieve this.

macos: make --config=remote work again

---

deps.bzl

This is a follow-up for #5662.
Turn out our external dependencies also need some proto love
```bash
WARNING: /private/var/tmp/_bazel_sluongng/06e573a93bc2d6a9cad4ad41f00b4310/external/com_github_buildbuddy_io_tensorflow_proto/tensorflow_serving/apis/BUILD.bazel:27:17:
in go_proto_library rule @@com_github_buildbuddy_io_tensorflow_proto//tensorflow_serving/apis:apis_go_proto:
target '@@com_github_buildbuddy_io_tensorflow_proto//tensorflow_serving/apis:apis_go_proto'
depends on deprecated target '@@io_bazel_rules_go//proto:go_grpc':
Migrate to //proto:go_grpc_v2 compiler (which you'll get automatically if you use the go_grpc_library() rule).
```
Ensure that when Gazelle is run on external dependencies, the proper
directive is also applied so that the newer compilers are used.

deps.bzl: ensure external proto use latest compiler

---

.bazelrc
platform_mapping

This change is incompatible with XCode 14 and lower.
Let's roll this back for now to unblock rollout.

macos: rollback linkopt flag

---

release.py

The release.py script starts by pulling the latest version tag, and plans to bump it for the new release. Previously, if that version tag didn't correspond to a published github release however, we'd reuse that version tag instead of bumping it. This logic was originally added so that if rerun release.py (Ex. if we fail to upload some docker images for example and someone reruns the release workflow) it won’t bump the version tag again. This behavior is confuisng and error-prone though. If the latest tag doesn't correspond to a published release, we should fail the script because it indicates something fishy going on. You can force it to still run by passing the --force flag. Or you can pass the --skip_version_bump flag explicitly.

Remove confusing logic in release.py

---

app/invocation/invocation_model.tsx

The UI cannot handle zstd-compressed blobs, so always fetch using the `.../blobs/...` bytestream URL rather than `.../compressed-blobs/zstd/...`

Don't fetch zstd artifacts from cache download endpoint in the UI

---

app/invocation/invocation_action_card.tsx

Use the `parseActionDigest` func which allows the `/size` suffix to be omitted (size is optional for AC)

Fix blank action page when navigating from cache requests card

---

app/invocation/invocation_model.tsx

The UI was not correctly parsing the blake3 option and as a result it was incorrectly trying to fetching some artifacts using sha256 bytestream URLs.

Fix digest_function option parsing

---

enterprise/server/backends/userdb/userdb.go
enterprise/server/scim/BUILD
enterprise/server/scim/scim.go
enterprise/server/scim/scim_test.go
server/interfaces/interfaces.go

For now, we support the minimum required by Okta:
- PATCH is only used for de-activation requests
- PUT is used for de-activation and other attribute updates (next PR)

SCIM user deletion support.

---

enterprise/server/remote_execution/executor/BUILD
enterprise/server/remote_execution/executor/executor.go
enterprise/server/scheduling/priority_task_scheduler/priority_task_scheduler.go
enterprise/server/scheduling/scheduler_server/scheduler_server.go
proto/scheduler.proto
server/metrics/metrics.go

I'm planning to take a look at how this fares in dev for a little while, compared to the current autoscaler metric of queued tasks, and then explore autoscaling off this instead.

Add two new metrics for tracking estimated RAM/CPU usage queued or executing

---

.github/workflows/create-github-release.yaml

Grrr github does not make writing these yamls easy...
From the github docs:
Because default environment variables are set by GitHub and not defined in a workflow, they are not accessible through the env context. However, most of the default variables have a corresponding, and similarly named, context property. For example, the value of the GITHUB_REF variable can be read during workflow processing using the ${{ github.ref }} context property.

Fix more typos in github release workflow

---

enterprise/server/githubapp/BUILD
enterprise/server/githubapp/githubapp.go
proto/repo.proto

New features:
- Adds the ability to find & replace variables in templates
- Adds the ability to specify a destination directory that the template should be copied into in the new repo
- Adds the option to skip GitHub repo creation, allowing you to copy templates into existing repos
- Adds the option to skip workflow linking
I can break this out into 3-4 PRs if that's easier, but I don't think the changes are too crazy.

New features for repo flow

---

enterprise/server/remote_execution/container/BUILD
enterprise/server/remote_execution/container/container.go
enterprise/server/remote_execution/container/container_test.go
enterprise/server/remote_execution/containers/bare/bare.go
enterprise/server/remote_execution/containers/docker/docker.go
enterprise/server/remote_execution/containers/firecracker/firecracker.go
enterprise/server/remote_execution/containers/podman/podman.go
enterprise/server/remote_execution/containers/sandbox/sandbox.go
enterprise/server/remote_execution/runner/runner.go
enterprise/server/util/ociconv/ociconv.go
server/util/hash/hash.go
server/util/hash/hash_test.go

This should fix the serial-image-pulling bug described [here](https://github.com/buildbuddy-io/buildbuddy-internal/issues/2844#issuecomment-1868007914). This is kinda gross, but a more correct fix that simplifies locking in container implementations and moves some of the auth-checking logic into container.go is quite a bit more involved, so I figured this was a good first step.
**Related issues**: [2844](https://github.com/buildbuddy-io/buildbuddy-internal/issues/2844#issuecomment-1868007914)

Serialize the existence check and image pull in PullImageIfNecessary

---

enterprise/server/scim/scim.go

The owned domain value is currently tied to automatically adding users by domain which users may want to disable.
This means that SCIM API could be used to create a user with any e-mail, but this is fine because:
- The user Sub ID will be tied to the SAML login for the org so the created user won't be usable outside that org
- The user will only belong to the group being administered

Remove domain restriction from SCIM user creation.

---

enterprise/server/githubapp/githubapp.go

i imagine this was done because it shows reviews with no reviewers? if so, i can try to address that separately, but this state is more annoying imo.

show outgoing reviews that havent received a review yet

---

enterprise/server/test/webdriver/invocation/BUILD
enterprise/server/test/webdriver/invocation/invocation_test.go
server/testutil/webtester/webtester.go

For now, the test just navigates to the executions tab and makes sure an execution row shows up.
The execution row is currently in a weird state because there are no executors registered. In a later PR we can register a real executor and make sure the action gets executed.

Add a minimal webdriver test for the executions listing

---

enterprise/server/remote_execution/filecache/filecache.go

With this flag, an executor can set `--executor.local_cache_always_clone=true` to force the executor to always use clone files from the filecache into the execution root.

Add flag to always force cloning from filecache

---

server/target/target.go

The pagination token should the last item in the following sql query:
```
SELECT commit_sha, max(invocation_start_time_usec)
as latest_created_at_usec FROM "TestTargetStatuses"
WHERE group_id = '[group_id]'
AND repo_url = '[repo_url]
AND commit_sha != ''
GROUP BY commit_sha
ORDER BY latest_created_at_usec DESC, commit_sha asc)
```
To repo the bug locally, I run a test from 25 commits, and then open the test grid.
**Before this change,** there are only 20 commits shown, and 5 commits were missing. 
**After this change**, all 25 commits were shown.
Fixes
https://github.com/buildbuddy-io/buildbuddy-internal/issues/3058

Test Grid: fix a bug when computing pagination tokens

---

enterprise/app/repo/repo.css
enterprise/app/repo/repo.tsx
enterprise/server/githubapp/githubapp.go

- Add UI support for template variables
- Minor styling tweaks
- Switch from `GCP_PROJECT` environment variable to `CLOUDSDK_CORE_PROJECT` which the gcloud CLI uses without the need for any special handling from us https://cloud.google.com/compute/docs/gcloud-compute#default_project
- Add UI support for destination directories
- Remove unused repository hook permission check
- Fix commit message when not initializing a new repo
- Fix use of wrong path when copying a template to a new repo

Repo flow tweaks

---

enterprise/server/raft/client/BUILD
enterprise/server/raft/client/client.go
enterprise/server/raft/constants/constants.go
enterprise/server/raft/replica/replica.go
enterprise/server/raft/sender/sender.go

Don't return an error from SyncPropose (my bad, I forgot); it will result in a panic. SyncRead is fine tho.
Because header is not blindly copied from request -> batch in SyncPropose, ensure that it's being set if it's not set already, in the client. And ensure that it will be updated if it happens to change between subsequent retries.

no err returned

---

dockerfiles/run_script/BUILD

This is resulting in a failure when trying to run `target-determinator`.

Fix tag_file reference on run_script target

---

enterprise/app/tap/tap.tsx

Without this the no-status blocks aren't sized correctly.

Wrap tap no-status blocks in `tap-commit-container`

---

.bazelrc

By default, go_test would not run the test binary with `-test.v`.
This effectively creates a relatively empty XML output, with only the
target as the top level "testsuite".
```xml
<testsuites>
<testsuite errors="0" failures="0" skipped="0" tests="0" time="0.004" name="github.com/buildbuddy-io/buildbuddy/cli/arg">
</testsuite>
</testsuites>
```
This behavior could be overriden as stated in (1) so that the XML output
is decorated with smaller testcase, each representing a Go test func.
```xml
<testsuites>
<testsuite errors="0" failures="0" skipped="0" tests="2" time="10.834" name="enterprise/server/test/integration/ci_runner/ci_runner_test">
<testcase classname="ci_runner_test" name="TestCIRunner_Push_WorkspaceWithCustomConfig_RunsAndUploadsResultsToBES" time="3.020">
</testcase>
<testcase …
```

.bazelrc: test go tests to be more verbose

---

deps.bzl
server/util/bazelisk/BUILD
server/util/bazelisk/bazelisk.go

This is needed to support patterns like `USE_BAZEL_VERSION=6.x`

Upgrade bazelisk version bundled with CI runner

---

app/invocation/invocation_suggestion_card.tsx

`CppLink` was split in two, so we need to include `CppArchive` as well.

Add `CppArchive` to `IOS_EXECUTION_FILTER`

---

enterprise/server/remote_execution/containers/firecracker/BUILD
enterprise/server/remote_execution/containers/firecracker/firecracker.go
enterprise/server/remote_execution/containers/firecracker/firecracker_test.go
enterprise/server/remote_execution/snaploader/snaploader.go

**Related issues**: Fixes https://github.com/buildbuddy-io/buildbuddy-internal/issues/3069

Fix snapshot reuse when base image chunks expire from cache

---

deps.bzl

Also formatted the file with
```bash
> buildifier -type workspace deps.bzl
```
to have a consistent ordering of repository rules attributes.

deps.bzl: make soci_snapshotter use the new grpc compiler

---

.bazelrc
.github/workflows/build-windows-github-release-artifacts.yaml
.github/workflows/create-github-release.yaml
tools/check_release_assets_uploaded.py

This should help us to start releasing Windows executor artifacts to our Github Release.

.github: add windows release workflow for executor

---

enterprise/server/githubapp/githubapp.go
server/backends/github/BUILD
server/backends/github/github.go
server/interfaces/BUILD
server/interfaces/interfaces.go

If an invocation takes longer than an hour, the GitHub installation token can expire. Respect the expiration time and re-fetch if the token is nearly expired.

Respect GitHub token expiration when publishing statuses

---

docs/rbe-setup.md

The old toolchain flags are old and have became no-ops in recent Bazel
versions.
Let's replace them with the new flags.
Keep the old flags around in a dedicated section for older Bazel
versions.

docs/rbe-setup.md: use new Java toolchain flags

---

enterprise/server/remote_execution/vbd/BUILD
enterprise/server/remote_execution/vbd/vbd_test.go

Applying some learnings from hackathon :)
This makes it so that `bazel test //enterprise/server/remote_execution/vbd:vbd_test` no longer requires root to run it locally. It does this by using a `TestMain()` function which executes the test as a new child process in a "pseudo-root" container. The container gets its own mount namespace and user namespace, with the host uid/gid mapped to 0:0 (root). See `man 7 namespaces` for more info on namespaces.
We can likely also use this trick to run `firecracker_test` as non-root, and get rid of the `test.sh` script. Will try that in a separate PR

Use Linux namespaces to allow vbd_test to run as non-root user

---

app/root/root.css

Makes underscores more clearly visible. Also makes things feel more cozy/legible (the underline no longer intersects with the descenders, e.g. the tail of the `y` / `p`).
Before:
After:

Set text-underline-offset on links

---

server/util/proto/proto.go
server/util/proto/proto_test.go

Currently, there are no use cases to use Google Proto Library's Unmarshal. Remove the exported alias.

remove proto.UnmarshalOld

---

.github/workflows/website.yaml

When we upgraded to Bazel 7.0.0 in the past, we encountered problem with
directly depending on `bazel-bin` convienience symlink created by Bazel.
In #5626, we introduced a custom Docusaurus plugin to customize how the
`bazel-bin` path is resolved and fixed this problem.
Let's make sure our workflows stay on the same Bazel version.

website: remove Bazel 6.4.0 usage in workflows

---

enterprise/server/backends/userdb/userdb.go

If you make a no-op update via the UI, it currently displays a "Group not found" error.

Don't treat no-op group update as error.

---

enterprise/server/backends/prom/prom.go
enterprise/server/usage/BUILD
enterprise/server/usage/usage.go
server/metrics/metrics.go

Customers want to monitor and/or alert on their remote build usage. 
This PR created a new metric in metrics.go to capture the linux and mac remote
execution duration; and added a new exported metric in prom.go

Export remote build duration to customers

---

enterprise/server/backends/pebble_cache/pebble_cache.go
enterprise/server/backends/pebble_cache/pebble_cache_test.go

JanitorCheckPeriod is not even referenced anymore in pebble_cache.go.
Partially addresses https://github.com/buildbuddy-io/buildbuddy-internal/issues/3035

Remove superfluous sleeps

---

enterprise/server/backends/pebble_cache/pebble_cache_test.go

Remove some duplicate test cases and ship a little less data around.
Is faster:
```
//enterprise/server/backends/pebble_cache:pebble_cache_test              PASSED in 7.6s
Stats over 8 runs: max = 7.6s, min = 1.5s, avg = 3.7s, dev = 1.9s
```
Fixes https://github.com/buildbuddy-io/buildbuddy-internal/issues/3035.

Less coffee time for Lulu

---

.bazelrc

This should be windows only and was added from a bad merge

bazelrc: fix wrong instance name for release config

---

.github/workflows/release-cli.yaml

The github runner has Bazelisk preinstalled, so we could get rid of our
custom Bazelisk installation step as well.

release-cli: use Github M1 runner instead of our "m1"

---

tools/clickhouse

Create a clickhouse data dir in /tmp. When we stop the docker clickhouse
container and start a new container, the data can be persisted. This will be
helpful when we are testing newer clickhouse versions locally.

Persist clickhouse data dir when running tools/clickhouse

---

enterprise/server/remote_execution/execution_server/execution_server.go
enterprise/server/remote_execution/execution_server/execution_server_test.go
enterprise/server/secrets/secrets.go
enterprise/server/workflow/service/service.go
server/backends/invocationdb/BUILD
server/backends/invocationdb/invocationdb_test.go
server/build_event_protocol/build_event_handler/build_event_handler_test.go
server/build_event_protocol/target_tracker/target_tracker.go
server/util/perms/perms.go

This PR change the GroupAuthPermissions to take in interfaces.UserInfo instead
of groupID, and renamed it to DefaultPermissions. When a personal key is used, the user_id will be the real user ID; and empty otherwise.
As a result, we will associate user_id with invocations, executions, git repositories 
Added tests in invocationdb_test.go, execution_server_test.go and build_handler_event_test.go to make sure user_id is set.
I reserve the current implementation of perms.GroupAuthPermissions and name it perms.GroupPermissionsDeprecated. This currently is used in CreateWorkflow in enterprise/server/workflow/service/service.go. Since Workflow table is to be replaced with GitRepositories, I didn't bother to change the code to use the new DefaultPermissions.

use userID instead of groupID in userGroupPerm

---

enterprise/server/remote_execution/containers/firecracker/BUILD
enterprise/server/remote_execution/containers/firecracker/firecracker.go
go.mod
go.sum

This PR sets the kernel boot option `lapic=notscdeadline` on AMD host CPUs only. I don't fully understand what this does but it allows `TestFirecrackerStressIO` to pass on my AMD machine if I set `maxRunsPerVM = 20`.
I read that LAPIC TSC deadline is meant to improve performance, so disabling it could potentially be bad - but I haven't noticed any performance degradation e.g. when trying a Python app that does 4 hot-loops in separate CPU cores using `multiprocessing`. But anyway, we're only disabling it on AMD which for now only affects local development. I'd rather have the tests pass with some slight performance degradation, than have it be flaky on our dev machines.
I left a TODO for us to remove this flag if the Firecracker folks sort out the root cause of the freezing.
**Related …

Add workaround for VMs freezing after resuming from snapshot on AMD CPUs

---

buildpatches/com_github_awslabs_soci_snapshotter.patch
buildpatches/vtprotobuf.patch

These fixes are backport from #5792. Expect no-ops.
soci_snapshotter should not need the MODULE.bazel and WORKSPACE.bzlmod
file to build under bzlmod. Removing the hunks to simplify the patch.
Fix space identation in vtprotobuf patch.

buildpatches: minor fixes to patch files

---

enterprise/server/backends/pebble_cache/pebble_cache_test.go

- Use a clock
- Ensure that avg evicted age is >> avg kept age
- Ensure that >= 80% of evictions are correct (compared to a perfect LRU)
```
INFO: Build completed successfully, 1814 total actions
//enterprise/server/backends/pebble_cache:pebble_cache_test              PASSED in 18.7s
Stats over 160 runs: max = 18.7s, min = 0.3s, avg = 1.8s, dev = 3.3s
```
Fixes https://github.com/buildbuddy-io/buildbuddy-internal/issues/3098

Deflake TestLRU

---

WORKSPACE
buildpatches/googleapis.patch
deps.bzl
enterprise/server/raft/client/BUILD
enterprise/server/raft/nodeliveness/BUILD
enterprise/server/raft/replica/BUILD
enterprise/server/telemetry/BUILD
enterprise/server/util/dsingleflight/BUILD
enterprise/server/util/execution/BUILD
proto/BUILD
proto/api/v1/BUILD
server/remote_asset/fetch_server/BUILD
server/remote_cache/content_addressable_storage_server/BUILD
server/remote_cache/hit_tracker/BUILD
server/remote_cache/scorecard/BUILD

Instead of maintaining our own status_go_proto, let's patch the
existing target inside googleapis and use it.
This let us remove custom Gazelle directives in our go_repository.

googleapis: build status_go_proto with vtprotobuf compiler

---

enterprise/server/cmd/ci_runner/main.go

my suggestion [here](https://github.com/buildbuddy-io/buildbuddy/pull/5806#discussion_r1476859302) was wrong lol
(Also, removed the logging in the success case, because we already have a log message for each file that's uploaded, which displays at the end of the workflow run)

Fix jvm.out error logging

---

buildpatches/buildifier.patch
deps.bzl
go.mod
go.sum

This fix is backported from #5792
Upgrade buildtools to latest version and ensure our patch have the right
indentation (Go uses tabs instead of spaces).

buildifier: upgrade to latest version

---

.github/workflows/build-linux-github-release-artifacts.yaml
.github/workflows/build-mac-intel-github-release-artifacts.yaml
.github/workflows/build-mac-m1-github-release-artifacts.yaml
.github/workflows/build-windows-github-release-artifacts.yaml
.github/workflows/main.yaml
.github/workflows/pr.yaml

The github runners images come with Bazelisk by default and is more
up-to-date than our self-managed 'Install bazelisk' job.
Switch to the pre-installed bazelisk to simplify our pipeline.

.github/workflows: use the pre-installed bazelisk

---

deps.bzl
server/util/bazelisk/BUILD
server/util/bazelisk/bazelisk.go

Getting this error when running workflows in firecracker locally:
/root/workspace/bazelisk: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /root/workspace/bazelisk)
The error goes away with the revert applied.
The bazelisk we were previously using was statically linked. Based on the error, it looks like it's no longer getting statically linked when building from source, so we run into glibc versioning issues :/

Revert "bazelisk: use Bazelisk built from source (#5748)"

---

deps.bzl
server/util/bazelisk/BUILD
server/util/bazelisk/bazelisk.go

Same approach as before, but ensure we use the release binary target instead of the default target.
This helps apply the needed transitions on top of the binary to force Pure Go (no CGO) compilation and avoid depending on GLIBC.

reapply: build bazelisk from source

---

enterprise/app/workflows/workflows.tsx

Without this param, we see the "not found" page instead of the "invocation is waiting for available worker" page.

Add `queued=true` URL param to workflows run via the "Run workflow" button

---

enterprise/server/api/api_server.go
enterprise/server/cmd/ci_runner/main.go
enterprise/server/workflow/service/service.go
proto/api/v1/workflow.proto
proto/workflow.proto

Customers were requesting this in the context of passing short-lived aws tokens to workflows. 
As a follow up, I plan on adding support for setting env vars to remote bazel

Add option to set env vars to ExecuteWorkflow api

---

enterprise/server/remote_execution/snaploader/snaploader.go
enterprise/tools/upload_local_snapshot/upload_local_snapshot.go

It seems wrong that we search for the chunked file tree in the remote cache, even for local-only snapshots 
(As a reminder, in order to translate a chunked file into an action cache result, we create a *repb.Tree object representing each chunked file. In the action cache result we store the digests of the *repb.Trees, and then we also cache each *repb.Tree in the CAS, which contains the list of chunks.)

[SS] Fix hard coded remote enabled value

---

enterprise/server/scim/scim.go
enterprise/server/scim/scim_test.go

Azure AD changes the username when de-activating a user.
Fixes https://github.com/buildbuddy-io/buildbuddy-internal/issues/3093

SCIM: allow changing username (email)

---

.bazelrc

I have this config in my `user.bazelrc` but it will be helpful to have a common config that we can mention in "flaky test" bug reports instead of having to list out all the bazel flags we're using.
e.g. "I can no longer repro the flakiness with `bazel test //target --config=deflake-go` so I'm closing this bug"

Add .bazelrc config for deflaking tests

---

enterprise/server/backends/pebble_cache/pebble_cache.go
enterprise/server/backends/pebble_cache/pebble_cache_test.go

Per Lulu's comment [here](https://github.com/buildbuddy-io/buildbuddy-internal/issues/3098#issuecomment-1930896750), the TestSampling flakiness can reproduced reliably by sleeping for 10ms instead of 100ms.
Just remove the termination condition on the loop and wait as long as it takes for the eviction to happen. If it takes too long then the test will just timeout.

Deflake pebble_cache_test TestSampling

---

enterprise/server/remote_execution/dirtools/dirtools.go
enterprise/server/remote_execution/dirtools/dirtools_test.go

If uploading a file like /foo/bar/baz/file.txt, don't upload directory entries for 'baz', 'bar', and 'foo', only upload 'file.txt'.

Upload fewer dirs

---

.gitignore

I find myself wasting a lot of time setting the same config options when doing local testing. Add a user-configs dir to .gitignore, so I can maintain a set of configs that I like to use.

Add user config files to .gitignore

---

cli/cmd/bb/bb.go
cli/test/integration/cli/cli_test.go

Fix --target_pattern_file handling when expanded via bazelrc

---

enterprise/app/org/BUILD
enterprise/app/org/org.css
enterprise/app/org/org_members.tsx
proto/config.proto
server/static/static.go

* Add new roles to dropdown (behind `--app.reader_writer_roles_enabled`)
* Attempt to communicate the permissions differences a little better using a table (see screen recording)
https://github.com/buildbuddy-io/buildbuddy/assets/2414826/12874b08-c873-41c8-a868-10b9153cc327

Add new roles to UI (behind flag)

---

proto/grp.proto

Go lets us easily convert between a `role.Role` and the proto enum value (`grpb.Group_*_ROLE`). Having the values be different seems like an accident waiting to happen, so update the proto enums to have them match the Go enum. (Note, the reader/writer roles are not stored anywhere yet, so it should be OK to update them)
(Note: a better fix is to use the Role proto everywhere and get rid of the Go enum. Will do that in a later PR)

Update Role proto enum values to match Go `role.Role` enum values

---

enterprise/server/backends/pebble_cache/pebble_cache.go

In Metadata function(), we currently create the iterator before we lock, which
can cause race condition described in https://github.com/buildbuddy-io/buildbuddy/pull/4460
In deleteMetadataOnly(), I added a comment stating the the key should be locked prior to calling this function. 
For FindMissing, I addressed the issue in https://github.com/buildbuddy-io/buildbuddy/pull/5851

create iterator after lock in pebble cache

---

app/invocation/invocation_suggestion_card.tsx

As of Bazel 7 the BwtB issues are fixed, but the default is also now what we would suggest.

Remove unused and no longer needed `--remote_download_minimal` suggestion

---

app/invocation/invocation_suggestion_card.tsx

This is now the default in Bazel 7, and can be confusing to users if we suggest setting it.

Stop suggesting `--remote_build_event_upload=minimal` on Bazel 7+

---

proto/BUILD
proto/grp.proto

Currently, the "Personal API keys" UI allows admin users to assign arbitrary capabilities to their API keys, and developers always get CAS_WRITE keys (they cannot customize the capabilities). This logic is hard-coded in the frontend code, and the server validates the capabilities requested via the API.
However, now that we've defined a concrete role => capabilities mapping, the server can send up the explicit list of capabilities that the user is allowed to assign. This will make it so that the frontend does not have to duplicate the role => capabilities mapping that we already have on the server, which will make the code simpler and easier to maintain now that we're adding new roles.
**Related issues**: https://github.com/buildbuddy-io/buildbuddy-internal/issues/3091

Proto changes for new role-based user API key capabilities

---

cli/parser/parser.go
cli/parser/parser_test.go

Here's sample output from `bazel help build`, which we use to determine what flags are valid:
--propeller_optimize_absolute_ld_profile (a string; default: see description)
--remote_download_all
--remote_download_minimal
--remote_download_outputs (all, minimal or toplevel; default: "toplevel")
--remote_download_symlink_template (a string; default: "")

[RB] Fix parsing flags that do not require a value to be set in cli

---

enterprise/server/backends/pebble_cache/pebble_cache.go
enterprise/server/util/pebble/pebble.go

This PR created a new method pebble.GetProto; which uses db.Get to get the bytes
and then unmarshal it to proto.
I used GetProto inside the lookupMetadataAndVersion method. It is faster and
uses less alloc per op. Also, we no longer need to worry about the order of
iterator creation and locking the key. 
Here is the benchmark test results:
```
│ /home/lulu/benchmark-pebble-master.log │ /home/lulu/benchmark-pebble-get-proto.log │
│                 sec/op                 │     sec/op      vs base                   │
GetMulti/size=1000B-24                                 1.344m ± 2%      1.296m ± 1%   -3.52% (p=0.000 n=80)
GetMulti/size=2KiB-24                                  2.610m ± 1%      2.424m ± 0%   -7.11% (n=80)
FindMissing/size=1000B-24 …
```

Use db.Get when look up metadata in pebble

---

enterprise/server/backends/pebble_cache/pebble_cache_test.go

**Related issues**: https://github.com/buildbuddy-io/buildbuddy-internal/issues/3098
In TestWriteCancelBeforeCommit, we currently expect that commit return a context
cancel error. However, sometimes, it returns nil when chunker.Close is called
before the chunker receives the ctx.Done(). 
I think in these cases, it's ok for wc.Commit() to return nil; when 
all the goroutines have already finished writing chunks. The original intention of this
test is to make sure during context cancellation there is no data race and zero
chunk error.

deflake TestWriteCancelBeforeCommit in pebble cache test

---

enterprise/server/backends/authdb/authdb.go
enterprise/server/backends/userdb/userdb.go
enterprise/server/backends/userdb/userdb_test.go
server/util/capabilities/capabilities.go

Instead of allowing only admins to assign CACHE_WRITE capabilities (and restricting everyone else to just CAS_WRITE), allow any user to assign any capabilities as long as the capabilities are a subset of their authenticated User+Group capabilities
Concretely:
- Org admins can assign either CACHE_WRITE or CAS_WRITE (like they can today), because their effective capabilities are a subset of these (CACHE_WRITE|CAS_WRITE).
- Writers can assign either CACHE_WRITE or CAS_WRITE, too.
- Developers can only assign CAS_WRITE, since their role-based capabilities are limited to just CAS_WRITE.
- Readers cannot assign any capabilities, since their role-based capabilities are empty.
Note, we still do not allow REGISTER_EXECUTOR or ORG_ADMIN capabilities to be assigned to user-owned keys for now. …

Allow assigning finer-grained capabilities to user API keys

---

app/components/button/button.css

Outline thickness is one of those CSS properties that doesn't get smoothly animated. Set a default 2px transparent outline so that when the focus outline does come in, it just fades in smoothly instead of jankily expanding. Note that this 2px area is not hoverable, so it shouldn't change behavior.

Remove janky focus outline transition

---

server/util/db/db.go

By default, gorm wraps every call in a transaction. Since we don't use gorm to do more than a single query at a time, this is unnecessary and adds bloat to our qps.
fixes buildbuddy-io/buildbuddy-internal#3083

disable gorm default transactions

---

enterprise/server/raft/client/client.go
enterprise/server/raft/replica/replica.go
enterprise/server/raft/store/store.go

Previously this method was happening via SyncPropose, which blocks the state machine from handling other writes. Because FindSplitPoint needs to scan the entire range, this can be slow. Instead, handle this method via SyncRead, which does not block the statemachine.

FindSplitPoint does not need to block state machine

---

app/root/root.css
enterprise/app/history/history.tsx
enterprise/app/tap/tap.css
enterprise/app/tap/tap.tsx

Makes buttons look a bit more clickable. Couldn't figure out how to add color without it being too obnoxious.
Before:
After:

Some empty state tweaks

---

enterprise/server/workflow/service/service.go
server/util/perms/perms.go

Inline it at the callsite so we can remove it.
Note: this code is not be getting called anymore anyway, since we've enabled the new GitHub App-based workflows. The last time we created a legacy Workflow row in the DB was in April of 2023.

Remove perms.DeprecatedGroupPermissions

---

enterprise/server/raft/replica/replica.go

Not that we generate vtproto for grpc status, BatchCmdResponse is 21% faster with MarshalVT.

use proto.Marshal instead of proto.MarshalOld for BatchCmdResponse

---

server/util/rangemap/rangemap.go
server/util/rangemap/rangemap_test.go

In TestAddOrdering, check the order of range.Start instead of range.Val, since we are ordering by the interval instead of value. 
In TestGet, add test cases where only one of start and end matches.

Add comments for exported methods in RangeMap, and update some tests

---

dockerfiles/executor_image/Dockerfile
dockerfiles/executor_image/create_podman_bundle.sh

This PR removes our dependency on the third-party apt repo during deployment.
- Add a script to pre-package podman deps in a ZIP archive.
- All dependencies from the third-party apt repo (alvistack) are included as `.deb` archives within the ZIP.
- All other deps (i.e. available in the standard apt repos) are just listed in deps.txt within the ZIP.
- The ZIP file also contains an installer that first installs prereqs from deps.txt, then installs the deb packages.
- The Dockerfile now just downloads the ZIP from GCS and just runs the install script, instead of trying to install from apt.
This script is pretty hacky and there is probably a better way to do this, but this should at least hold us over until we can build from source, or until we're prepared to switch the executor to a …

Install podman from pre-downloaded deb archives

---

enterprise/server/api/api_server.go
enterprise/server/backends/pebble_cache/pebble_cache.go
enterprise/server/backends/userdb/userdb.go
enterprise/server/raft/cache/cache.go
enterprise/server/remote_execution/execution_server/execution_server.go
enterprise/server/saml/saml.go
enterprise/server/scheduling/scheduler_server/scheduler_server.go
enterprise/server/workflow/service/service.go
server/backends/disk_cache/disk_cache.go
server/backends/github/github.go
server/build_event_protocol/build_event_handler/build_event_handler.go
server/build_event_protocol/target_tracker/target_tracker.go
server/buildbuddy_server/buildbuddy_server.go
server/libmain/libmain.go
server/remote_cache/capabilities_server/BUILD
server/remote_cache/capabilities_server/capabilities_server.go
server/rpc/interceptors/interceptors.go
server/target/target.go
server/telemetry/BUILD
server/telemetry/telemetry_client.go
server/util/capabilities/capabilities.go
server/util/perms/perms.go

Follow-up from https://github.com/buildbuddy-io/buildbuddy/pull/5899#pullrequestreview-1878738508
The app binds a `NullAuthenticator` instance if auth is disabled, otherwise it binds a "real" authenticator, so `env.GetAuthenticator()` will never return `nil`. As a result, we can simplify any code that checks whether the authenticator is nil.
Also, some of our existing code was already not doing the nil checks, so if anything, this PR makes the nil checking consistent by removing it everywhere.

Clean up nil checks on `env.GetAuthenticator()`

---

enterprise/server/usage/BUILD
enterprise/server/usage/usage.go
enterprise/server/workflow/service/service.go
server/util/authutil/authutil.go
server/util/perms/BUILD
server/util/perms/perms.go

A while back, we updated the implementations of `interfaces.UserInfo.GetGroupID()` so that it always returns the correct value of the user's authenticated selected group ID (either the group ID from the API key in the gRPC auth case, or the authenticated selected group ID from the proto request context sent by the UI). So these util funcs are no longer needed; we can just call `GetGroupID` directly now.

Remove Group ID utils from perms package

---

BUILD
enterprise/server/test/integration/ci_runner/ci_runner_test.go

Enable golang static check analyzer S1031: 'Omit redundant nil check around loop'

---

BUILD
enterprise/tools/check_metrics/check_metrics.go

Enable golang static check analyzer S1028: 'Simplify error construction with fmt.Errorf'

---

cli/execute/execute.go

This is useful to be able to debug the action afterwards (e.g. fetch the full ActionResult from AC using `tools/cas`).

Log action resource name in bb execute debug logs

---

enterprise/server/raft/replica/replica.go
enterprise/server/raft/replica/replica_test.go

We were saving the raw `[]byte txid` in sm.lockedKeys, but then we were opening ourselves up to it changing because the caller still had a reference to it. Copy `txid` to prevent this, and add a test that fails without this fix.

Fix a transaction locking issue. Pointers!

---

enterprise/server/backends/authdb/authdb.go
enterprise/server/backends/userdb/userdb.go
enterprise/server/quota/quota_manager.go
enterprise/server/workflow/service/service.go
server/build_event_protocol/target_tracker/target_tracker.go
server/target/BUILD
server/target/target.go

Non-locking reads have no effects to rollback and do not lock rows during the transaction, so there is no need to wrap them in a transaction.

remove transactions surrounding exclusively non-locking reads

---

enterprise/server/raft/registry/registry.go
enterprise/server/raft/registry/registry_test.go

Currently, we call `LoadOrStore` when we call `AddNode`. If the target's raft or
gRPC addresses change, we don't store the new addresses. 
This PR 
- changes `LoarOrStore` to `Store`.
- adds a registry test where we add the same target twice with different addresses.
- in `registry_test.go`, use `require.NoError` and `require.ErrorIs` for error assertion. 
Tested locally by running smash against a raft cluster. Bring down a raft node, 
change its grpc port and bring it back. 
https://github.com/buildbuddy-io/buildbuddy-internal/issues/3125

[Raft] When addresses change, update the registry

---

enterprise/server/remote_execution/containers/firecracker/firecracker.go

I realized that u.String() will always return the same value, when I intended for it to generate a new value.
I will refactor vmID and snapshotID in a follow up, so it's more clear that snapshotID is a unique per-run value, and vmID should only be generated at the beginning of a VM's lifecycle.

Fix invalid usage of uuid in firecracker code

---

enterprise/server/remote_execution/containers/firecracker/firecracker.go
enterprise/server/remote_execution/vbd/vbd.go
enterprise/server/remote_execution/vbd/vbd_test.go

Instead of `context.TODO()`, use the VM context so we get proper cancellation and log labels.

Use VM ctx for VBD mount

---

server/interfaces/interfaces.go
server/util/claims/claims.go
server/util/perms/perms.go

This "admin" group is no longer used since we added proper impersonation. Checked in the DB, and no users are a member of the "admin" group ID according to the UserGroups table.

Remove global admin group logic

---

enterprise/app/code/code.tsx
package.json
yarn.lock

Requires a monaco editor upgrade.
Addresses bullet 4 from https://github.com/buildbuddy-io/buildbuddy-internal/issues/1176

Make Ctrl+F target editor even if not focused

---

enterprise/app/code/BUILD
enterprise/app/code/code.tsx
enterprise/app/code/code_pull_request.ts

- Reset review request state in case of a backend error, and print the error message
- Reset update pr state in case of a backend error, and print the error message
- Update fetch latest content after merging a PR
- Only count merge conflicts if file contents are different than editor file contents
- If on a PR branch and you update the default branch and have no changes - switch back to the default branch (this likely means the PR was merged outside of the code editor UI)
- If on a PR branch, show the PR branch in the breadcrumbs
- Fix branch ref when updating PR branch

Clean up pull request flow

---

.bazelrc
.github/workflows/remote-bazel-build.yaml
buildbuddy.yaml

Add a CI workflow using remote bazel so we can test it out more and compare it performance-wise to bb workflows. Run the same test command we have in our workflows config.

[RB] Add a CI workflow using remote bazel

---

tools/cacheload/BUILD
tools/cacheload/cacheload.go

Drive cacheload QPS based on ticker. The intent is to make the QPS applied to target less dependent on target handling latency.
In the previous version, because there were a fixed number of worker goroutines, I believe when a couple requests got slow it would prevent the tool from hitting its QPS target.

Drive cacheload read and write QPS based on ticker

---

enterprise/server/raft/store/store.go

The listener is passed to nodehost config and to the lease keeper, but we never
call store.listener.

remove listener from raft store

---

enterprise/server/remote_execution/platform/platform.go
enterprise/server/remote_execution/platform/platform_test.go
enterprise/server/tasksize/tasksize.go

We tried to set EstimatedComputeUnits to 0.8 today, but it was being treated as 0.

Parse EstimatedComputeUnits as a float

---

.github/workflows/remote-bazel-build.yaml
cli/remotebazel/BUILD
cli/remotebazel/remotebazel.go

I noticed that in a github workflow using remote bazel, the snapshots were never recycled. There is no guarantee that workflows will be run on stable machines with stable node IDs and dir structure. The SessionAffinityKey is set as a platform prop, which is hashed for the snapshot key, so the changing value was causing snapshot misses.
**Related issues**: buildbuddy-io/buildbuddy-internal#3140

[RB] Remove session affinity key because it prevents snapshot sharing

---

enterprise/server/remote_execution/commandutil/BUILD
enterprise/server/remote_execution/commandutil/commandutil.go
enterprise/server/remote_execution/commandutil/commandutil_unix.go
enterprise/server/remote_execution/commandutil/commandutil_windows.go

For bare runners (e.g. macos), instead of only relying on our polling goroutine which monitors stats from procfs stats, use `Rusage` as a secondary signal for CPU usage, and report whichever one is higher.
For most "normal" actions (which don't spawn a bunch of child processes) this fixes an issue where the last 1 second of CPU usage potentially goes unreported. More specifically, we use a backoff for polling that starts at 25ms and backs off to 1000ms. The amount of CPU usage that goes unreported depends on how long the action has run (i.e. how much backoff we've applied so far).
Tested with a C program that burns almost exactly 1000ms of CPU time by running ~3 billion NOP operations in a for-loop (found this value through a bunch of trial and error). Before this PR, when running this …

Improve accuracy of CPU measurement on bare runner

---

enterprise/app/code/code.css
enterprise/app/code/code.tsx
enterprise/app/code/code_sidebar_node.tsx

- Shows edited / deleted / new status change drawer
- Shows new files and hides deleted files in sidebar
- Adds "New folder" context menu option
- Adds "Rename" context menu option
- Updates "New file" implementation to vscode-style inline input filename
Things not yet supported in this PR (shows a toast when attempted in UI):
- Renaming directories
- Deleting directories
I could probably split this up into a few PRs if it's overwhelming.

Support more file operations

---

enterprise/server/backends/authdb/authdb.go
enterprise/server/backends/userdb/userdb.go
enterprise/server/githubapp/githubapp.go
enterprise/server/quota/quota_manager.go
enterprise/server/remote_execution/execution_server/execution_server.go
enterprise/server/telemetry/telemetry_server.go
server/backends/invocationdb/invocationdb.go
server/build_event_protocol/target_tracker/target_tracker.go

Non-locking reads have no effects to rollback and do not lock rows for future queries, and thus are superfluous to include at the beginning of a transaction.
This reduces some transactions to single queries, which means those transactions can be removed in a future PR, but that is outside of the scope of this PR.

shrink transactions with initial non-locking reads and single terminating writes

---

enterprise/server/backends/authdb/authdb.go
enterprise/server/backends/userdb/userdb.go
enterprise/server/remote_execution/execution_server/execution_server.go
enterprise/server/telemetry/telemetry_server.go
enterprise/server/workflow/service/service.go
server/backends/invocationdb/invocationdb.go
server/build_event_protocol/target_tracker/BUILD
server/build_event_protocol/target_tracker/target_tracker.go

If a single query fails, it does not need to be rolled back, so there is no reason to surround it with a transaction.

remove transactions surrounding single queries

---

buildbuddy.yaml

They have been timing out and we don't have a super strong need to run these on macOS as part of CI (Linux should be enough)

Disable integration tests on mac workflows

---

enterprise/server/remote_execution/execution_server/execution_server.go

This makes our most-common codepath only use one query instead of two

Only perform the select to determine if there is no related execution row after attempting an update

---

enterprise/server/remote_execution/containers/firecracker/firecracker.go
enterprise/server/remote_execution/copy_on_write/BUILD
enterprise/server/remote_execution/copy_on_write/copy_on_write.go
enterprise/server/remote_execution/snaploader/snaploader.go
enterprise/server/remote_execution/uffd/BUILD
enterprise/server/remote_execution/uffd/uffd.go
server/metrics/metrics.go

The goal of this PR is to better understand performance bottlenecks when initializing a firecracker VM (i.e. before we can execute a command). So for now, only emitting these metrics before `SendExecRequestToGuest`. Because exec requests can take very different amounts of time, it feels less helpful to emit metrics for them.
* Add metrics for time spent on various COWStore operations
* Add metrics for page fault handling
As added context, [p95 to dial the vm exec server ](https://metrics.buildbuddy.dev/d/KI6NxDWSk/workflow-snapshotting?orgId=1&refresh=1m&viewPanel=19)frequently spikes to 20s. I want to better understand what part of the VM initialization is so spiky/slow

[SS] Add performance metrics for snapshotted VM startup time

---

enterprise/server/raft/client/client.go
enterprise/server/raft/sender/sender.go

Borrowed from `buildbuddy/enterprise/server/util/cacheproxy
/cacheproxy.go`
Fail fast when there are no ready connections from the connection pool and we
can try another replica.

[raft] return Unavailable error when there is no ready connection in the pool

---

enterprise/server/githubapp/BUILD
enterprise/server/githubapp/githubapp.go

Set an API key on GH actions runner executions.
This worked without an API key when I was testing locally because I was running the executor with `--debug_enable_anonymous_runner_recycling`, but in dev I got an error because runner recycling requires auth.

Fix GH actions auth

---

enterprise/app/BUILD.bazel
enterprise/app/code/BUILD
enterprise/app/code/code.tsx
enterprise/app/sidekick/buildfile/BUILD
enterprise/app/sidekick/buildfile/buildfile.css
enterprise/app/sidekick/buildfile/buildfile.tsx

Adds a little sidekick that allows you to quickly build/run/test any target in the BUILD files.
This could get a lot fancier, but just want to start simple.

Add a simple BUILD file sidekick

---

.github/workflows/buildbuddy-actions-runner-pr.yaml

Once we merge https://github.com/buildbuddy-io/buildbuddy-internal/pull/3148 then re-push this branch, we should be able to see the initial results right in this PR :)

Add initial GitHub actions workflow using `runs-on: buildbuddy`

---

.github/workflows/buildbuddy-actions-runner-pr.yaml

Accidentally broke this while cleaning up some debug prints just before merging

Fix GitHub Actions runner workflow

---

enterprise/server/usage/usage.go

Let's say we have the following usage data in Redis that we want to flush to the DB:
| Key | Value |
| --- | --- |
| usage/collections/{period1} | Set{ "group_id=GR1", "group_id=GR2&origin=internal" } |
| usage/counts/{period1}/group_id=GR1 | Hash{ "invocations": "1" } |
| usage/counts/{period1}/group_id=GR2&origin=internal |  Hash{ "invocations": "2" } |
Currently, our flush procedure looks like this:
- Flush GR1 counts to the DB
- Delete GR1 counts
- Flush GR2 counts to the DB
- Delete GR2 counts
- Delete the collections set containing GR1 and GR2
This has a problem though: if we flush GR1 successfully, but then the flush for GR2 times out, the collections set entry will still contain GR1 on the next flush. So, the next time we try to flush, we'll try to flush the GR1 collection again, …

Fix bug in redis cleanup logic

---

enterprise/app/org/BUILD
enterprise/app/org/org.css
enterprise/app/org/org_members.tsx
enterprise/server/backends/userdb/userdb.go
proto/user_id.proto
server/tables/tables.go

This helps distinguish between Google / Github accounts and SAML accounts when migrating org auth provides.
This makes it easy to identify remove any members not using a preferred auth method.
Without these icons, it's impossible to distinguish between two accounts with the same email address from different providers in the UI.
Example:

Show account type icons next to emails in members list

---

enterprise/app/code/code.tsx

I added this a couple of PRs ago, but turns out it was a mistake.
We don't always know the branch, leading to pulling the wrong state in those cases.
We'll have to handle switching between branches in another way once we add that functionality.

Don't put branch in cache key

---

enterprise/server/raft/replica/BUILD
enterprise/server/raft/replica/replica.go
enterprise/server/util/pebble/pebble.go

https://github.com/buildbuddy-io/buildbuddy-internal/issues/3153

[Raft] flush the batch more frequently when recovering from snapshot

---

enterprise/app/code/BUILD
enterprise/app/code/code.tsx

This allows us to push from the UI if you configure the correct environment variables.

Set platform props in code ui

---

enterprise/tools/upload_local_snapshot/BUILD

This lets us `scp` it to the node without hitting a GLIBC error

Make upload_local_snapshot statically linked

---

.github/workflows/remote-bazel-build.yaml

** PENDING: Need to upgrade cli after I merge #6031 , before I can merge this
**Related issues**: https://github.com/buildbuddy-io/buildbuddy-internal/issues/3141

[RB] Clean up having to checkout default branch in remote bazel workflow

---

proto/remote_execution.proto

This should provide a little more insight into input fetch times in the case where 0 files are downloaded from remote cache.
**Related issues**: https://github.com/buildbuddy-io/buildbuddy-internal/issues/3142

Add filecache metrics to IOStats proto

---

enterprise/server/backends/prom/prom.go

Change the exported metric types from gauge to counter; and also add a label "pod_name" to exported metrics.
Currently, the exported metric is the sum of all counters from the all the apps. During the rollout, the metrics from one app will reset to zero one by one. As a result, the aggregation never reset to zero.

change exported metrics from gauge to counter

---

enterprise/server/remote_execution/containers/firecracker/firecracker.go
enterprise/tools/upload_local_snapshot/BUILD
enterprise/tools/upload_local_snapshot/upload_local_snapshot.go
enterprise/tools/vmstart/BUILD
enterprise/tools/vmstart/vmstart.go

* Disable workspace sync when using vmstart to start a snapshot (use the workspace from the snapshot instead of a local empty dir). This will let us debug the snapshotted workspace contents.
* In upload_local_snapshot, make it harder to forget setting executor_id in the `--file_cache_dir` flag (I got stuck on this for a few min because I only saw the default flag definition and not the comment that mentions setting host_id)
* Upload artifacts in parallel using errgroup, and clean up temp files created by uploads. Also allow pressing Ctrl+C to cancel the script (healthchecker prevents this from happening - use NewBatchEnv instead).
* Fix auth error due to missing authenticator in env

Debugging improvements for local snapshots

---

enterprise/server/remote_execution/action_merger/BUILD
enterprise/server/remote_execution/action_merger/action_merger.go
enterprise/server/remote_execution/execution_server/BUILD
enterprise/server/remote_execution/execution_server/execution_server.go
enterprise/server/scheduling/scheduler_server/BUILD
enterprise/server/scheduling/scheduler_server/scheduler_server.go
enterprise/server/test/integration/remote_execution/BUILD
enterprise/server/test/integration/remote_execution/rbetest/BUILD
enterprise/server/test/integration/remote_execution/rbetest/rbetest.go
enterprise/server/test/integration/remote_execution/remote_execution_test.go
server/testutil/testgrpc/testgrpc.go

The current implementation of action merging:
1. Checks Redis for a pending execution ID for a given action digest when an Execute request is received, reusing the pending execution ID if one is found, or
2. Writes two entries in Redis bidirectionally mapping action IDs to/from execution IDs with an 8 hour TTL for scheduled executions, and finally
3. Deletes this bidirectional map when the execution completes.
This is not resilient to unexpected failures in the app during execution, or cases where all of the executors simultaneously exit unhealthily. If either of these things happen, the action-merging entries written in step 2 can persist, because step 3 never happens. These "stuck" action merging entries block subsequent execution requests for that action, as alluded to in the linked …

Make action-merging more resilient to dying apps/executors

---

enterprise/server/raft/cache/cache.go
enterprise/server/raft/sender/sender.go

sender.Run -> sender.run since apart from the usage in raft/cache, we don't use 
sender.Run outside sender any more, and instead we shall use sender.SyncRead or
sender.SyncPropose.

[Raft] use sender.SyncRead directly instead of sender.Run

---

enterprise/server/oidc/oidc.go
server/util/claims/claims.go

It looks like [this change](https://github.com/buildbuddy-io/buildbuddy/commit/216dfe89879b04d356e8ffd800763c2b3571addc#diff-f9a06e832e7e443d9e2956af68a414f014011678f50c8859d8c4221936c87731R911) (need to click "load diff" on `auth.go`) changed the logic from `a.parseClaims()` which uses the `ClaimsCache`, to `claims.ParseClaims` which parses the claims unconditionally. This seems like it could have been unintentional but please let me know if it wasn't!
This should save about ~3-4% CPU in prod.

Bring back `ClaimsCache` to reduce JWT parsing work

---

enterprise/server/oidc/oidc.go

The PR https://github.com/buildbuddy-io/buildbuddy/pull/6066 changed the logic so that we fall through in the case where a JWT is missing, returning `"gRPC request is missing credentials"` instead of `authutil.UserNotFoundMsg` like we were before. This seems OK, but the logic in `auth.AuthenticatedUser` [here](https://github.com/buildbuddy-io/buildbuddy/blob/a8703506971adab680d4b0711f2fe1fcb483532b/enterprise/server/auth/auth.go#L163) depends on the error containing the string `authutil.UserNotFoundMsg` to know whether to short-circuit, or to move on to the next authenticator in the chain. This PR brings back that old logic to return `UserNotFoundMsg` just to ensure that we short-circuit like we were doing before (although I think the lack of short-circuiting is probably fine, I didn't …

Fix short-circuit logic

---

enterprise/server/oidc/oidc.go
server/util/claims/claims.go

Reverts #6074 and #6066 - will roll forward with a better approach (addressing the TODO in `ClaimsFromContext`).

Revert ClaimsCache changes

---

enterprise/server/backends/pebble_cache/pebble_cache.go
server/metrics/metrics.go

On write, in pebble cache, record the compressed size and uncompressed size of blobs.
Having both counters separately should allow us to track overall compression ratio in a more accurate way.

Attempt to track compression ratio in a more accurate way

---

enterprise/server/remote_execution/containers/docker/docker.go
enterprise/server/remote_execution/containers/podman/podman.go

For docker you an enable access to all GPUs with:
```
--executor.docker_gpus=all
```
For podman, you can do the same with:
```
--executor.podman.gpus=all
```

Add support for GPUs to docker / podman executors

---

enterprise/server/cmd/ci_runner/main.go
enterprise/server/test/integration/ci_runner/ci_runner_test.go

This will make it easier to add flags to this script in the future.
Right now, if you pass an undefined flag to this script, the script will immediately fail when `flag.Parse` encounters the unexpected flag. This will make it challenging to ever iterate on this script and add new flags, especially because customers with self-hosted executors may rarely update their executors to pull in new changes to this script. The workflow service / our schedulers don't know what version of this script will be on an executor, so it won't be able to tell whether it's safe to send a new flag.

Ignore invalid flags in the ci_runner script

---

enterprise/server/backends/distributed/distributed.go
enterprise/server/backends/distributed/distributed_test.go

Rather than having "extra_nodes" add nodes to the primary peer set, rename the value to "new_nodes" and make it an entirely independent set. This more flexible API would allow for shrinking the node set in the future if desired.
Also make the test more stringent.

Make extra_nodes an independent set

---

deps.bzl

**Related issues**: https://github.com/buildbuddy-io/buildbuddy-internal/issues/2282

Upgrade soci-store to v0.0.13 (with some new log statements).

---

enterprise/server/raft/replica/replica.go

**Related issues**: https://github.com/buildbuddy-io/buildbuddy-internal/issues/3166
Add range not current error message when updating atime failed range check, so
that sender can retry this error with a different replica.

Retry updating atime

---

enterprise/server/raft/replica/replica.go

Raft libraries calls replica.Update in goroutines; and it can panic if Update
returns error, e.g. https://github.com/buildbuddy-io/buildbuddy-internal/issues/3165
Adding some context in the error message can make it easier to debug.

add more context in error message to make debugging easier

---

enterprise/server/remote_execution/containers/podman/podman.go

That setting in containers.conf controls how many layers podman will pull/push concurrently, system-wide. Without setting it, the default is 6. I'd like to set it higher in dev to try and exacerbate https://github.com/buildbuddy-io/buildbuddy-internal/issues/2282 which I suspect will happen more frequently if there's more parallelism hitting soci-store.
Orthogonally, it would be nice to be able to tweak this value in dev/prod to see how it affects image pull performance.
**Related issues**: https://github.com/buildbuddy-io/buildbuddy-internal/issues/2933

Add a flag that controls the podman's engine.image_parallel_copies

---

server/util/consistent_hash/consistent_hash.go
server/util/consistent_hash/consistent_hash_test.go

* Use "vnodes" instead of "replicas" to refer to the copies of each node placed around the ring
* Continue using "items" or "replicas" to refer to the nodes themselves
Context: https://github.com/buildbuddy-io/buildbuddy/pull/6091#discussion_r1516296223

Rename replicas => vnodes

---

enterprise/server/remote_execution/containers/firecracker/firecracker.go

I noticed in the metrics that we have files named "rootfs" and "rootfs.ext4". We pull the store name from the path, and I realized we are naming the path different things at different points. This pr consolidates the path names.
This wasn't causing issues because the different names were used when we create a new store from scratch, vs when we're unpausing a snapshot. As long as we were consistent within each case, there was no problem

[SS] Fix rootfs file path and name

---

enterprise/server/backends/pebble_cache/pebble_cache.go
server/metrics/metrics.go

Will use this to get a rough idea of what % of digests are read "often" (i.e., inside the 3-hour atime update threshold) vs. not, as well as P(any read|not read in k days).  This might give some ideas for how to optimize a smaller cache across all apps.

Add a histogram for the delta between atime and current time for cache reads

---

enterprise/config/buildbuddy.raft.yaml
enterprise/server/raft/replica/replica.go

fix a bug in updating atime: need to create the batch in the function that
passes into RunMultiKey. 
Also, set split range and atime_update_threshold smaller locally

Fix raft atime update bug

---

enterprise/app/api_keys/api_keys.tsx

The API key value is no longer populated in the api list response.

Remove API key value from delete dialog.

---

tools/dev_qa.py

* Disable bzlmod on builds (and remove `bazel` repo build because it's been fully migrated to bzlmod, and we haven't done enough testing to guarantee our toolchain work well with bzlmod)
* Fail script if a QA build fails
* Add API key to builds
* Update to the latest buildbuddy toolchain
**Related issues**: Fixes https://github.com/buildbuddy-io/buildbuddy-internal/issues/3167

Fix dev QA script

---

.github/workflows/remote-bazel-build.yaml
cli/remotebazel/remotebazel.go
enterprise/server/cmd/ci_runner/main.go
enterprise/server/hostedrunner/hostedrunner.go
enterprise/server/workflow/service/service.go

The snapshot key is based off the git branch. If we do not have a snapshot for a branch, we support falling back to snapshots for default branches, as specified in the `GIT_REPO_DEFAULT_BRANCH` and `GIT_BASE_BRANCH` env vars.
This change will enable more snapshot hits.

[RB] Try to set default branch env var for better snapshot matching

---

app/invocation/invocation_share_button.tsx

The UI was only looking at whether or not a user id was present on an invocation to determine whether or not to disable the visibility modal.
After this change https://github.com/buildbuddy-io/buildbuddy/pull/5778/files we don't set a user id if an organization-level API key is used.
This makes the visibility dropdown disabled in some cases where it shouldn't be.
This PR updates the UI to check for a group id as well when trying to determine if the invocation is an authenticated build.

Fix visibility modal in the UI

---

enterprise/server/remote_execution/containers/firecracker/firecracker.go
enterprise/server/remote_execution/containers/firecracker/firecracker_test.go
enterprise/server/vmexec/vmexec.go

Also log the first 1K bytes of the executable (I realized that if there is corruption, just knowing the digest of the corrupted contents will not be super helpful)

Fix executable diagnostics

---

rules/gcs/index.bzl

I'm using the rule to upload bare metal boot configs and I don't want them to be cached.

Add GCS rule option to disable caching.

---

enterprise/server/raft/events/events.go
enterprise/server/raft/store/store.go
enterprise/server/raft/usagetracker/usagetracker.go

We are dropping range usage events, and this might cause total count to be
negative. increase the event channel size to 100.
Also add more details to the logs when we drop the range usage event.

[raft] increase the event channel size

---

app/router/router.tsx

This makes the redirect_url url param work for SAML & GitHub logins

Respect `redirect_url` even for non-OIDC logins

---

server/remote_cache/content_addressable_storage_server/content_addressable_storage_server.go

The idea here is that we can reduce the amount of TreeCache AC lookups by respecting `minTreeCacheLevel` not only for cache writes but for cache reads as well.
Here is the intuition for this change: directories usually appear at the same "level" across builds. If we have a directory nested 3 levels deep under the root dir ("L3"), usually we won't see those exact directory contents re-appear at a higher level in a different build (specifically, at L0 or L1). For example, most inputs in the build will appear under `/bazel-out/{config}` or `/external/{repo_name}`, and it's unlikely that we'd see a directory like `/external/bazel_tools/blah` reappear as `/blah` in a subsequent build. So, we are likely spending a lot of time doing TreeCache lookups for levels which will almost always result in …

GetTree: skip TreeCache lookups for levels that aren't cached

---

enterprise/server/remote_execution/vbd/vbd.go
enterprise/server/remote_execution/vfs/vfs_unix.go

See https://github.com/hanwen/go-fuse/issues/506
If direct mounting fails, don't fall back to `fusermount`, since it can cause deadlocks. Direct-mounting should work in most cases without needing to fall back to `fusermount` since we run the executor as root. The `fusermount` fallback mostly seems needed for cases where the user is not root and direct mounting doesn't work.
This may or may not be the root cause of the VBD deadlocks we are seeing. If VBD mounts occasionally fail in prod, then they would fall back to using `fusermount` ([regardless of error code](https://github.com/hanwen/go-fuse/blob/e9e7c22af17af4611b5783a16458647088cc8dec/fuse/mount_linux.go#L142-L150)), which can potentially deadlock. However, we don't know if this fallback is actually happening or not, because it …

Set DirectMountStrict in VBD/VFS to prevent deadlocks

---

enterprise/server/remote_execution/soci_store/soci_store_linux.go

It's nil by default because it's a pointer not an embedded struct.
**Related issues**: [2901](https://github.com/buildbuddy-io/buildbuddy-internal/issues/2901)

Set cmd.SysProcAttr before using

---

enterprise/server/scheduling/task_router/task_router.go
enterprise/server/scheduling/task_router/task_router_test.go

To improve local filecache hit rates when snapshot sharing, we want workflows to be routed to the executor that recently ran a similar workflow. In addition to trying to route on GIT_BRANCH, also route on the default git branch and base branch as fallbacks, to ensure higher routing hit rates for new pr branches that won't have been run before.

[SS] When routing workflows, support adding git default branch to routing key as a fallback

---

cli/fix/fix.go

Also make the diff output slightly nicer and silence warning about missing `-diff_command`

Have `bb fix` check and format .bzl files

---

.github/workflows/release-cli.yaml

Test run at this PR branch (this created v5.0.36): https://github.com/buildbuddy-io/buildbuddy/actions/runs/8288445823

Fix CLI release missing GH token

---

enterprise/server/backends/pebble_cache/pebble_cache.go
server/metrics/metrics.go

sigh.  races between apps to update atime made me think this was working right in dev, but i somehow missed a short circuit right before the channel _write_ (we short circuit updating atime in two places)

actually log access time delta for case where atime wont be updated

---

WORKSPACE
deps.bzl
go.mod
go.sum

Upgrade the related protobuf dependencies.
Resolve https://pkg.go.dev/vuln/GO-2024-2611

Upgrade protobuf deps

---

website/src/css/markdown.css
website/theme/BlogPostItem/styles.module.css

The old one got mangled in the release processes css obfuscation.
Also add a nice little improvement for wrapping blog post titles.

Use a more stable selector for code blocks

---

website/docusaurus.config.js
website/src/css/general.css
website/theme/BlogListPage/index.tsx
website/theme/BlogPostItem/index.tsx
website/theme/BlogPostItem/styles.module.css

Make blog post list page a little nicer

---

server/backends/invocationdb/invocationdb.go

If the initial insert fails when registering an invocation attempt, nothing is or needs to be locked, and the insert has had no effects to roll back. If the insert succeeds, however the transaction ends. Thus, it does not to be included in the transaction.

initial insert when registering invocation attempt doesn't need to be in a transaction

---

enterprise/server/cmd/ci_runner/main.go

Simpler impl in this PR makes this flag unncessary: https://github.com/buildbuddy-io/buildbuddy/pull/6085

Clean up unnecessary env_overrides flag

---

enterprise/server/remote_execution/containers/firecracker/firecracker.go
enterprise/server/remote_execution/vbd/vbd.go

Error: https://buildbuddy-corp.slack.com/files/USLACKBOT/F06QSAARCAU/new_error_in_flame-build_executor_executor-54df5bd945-dkck9
We unmount vbd in the background, which [sets f.server=nil when it's complete](https://github.com/buildbuddy-io/buildbuddy/blob/master/enterprise/server/remote_execution/vbd/vbd.go#L146). We also may [return early from the Unmount call if the context is cancelled](https://github.com/buildbuddy-io/buildbuddy/blob/master/enterprise/server/remote_execution/vbd/vbd.go#L137), and we don't wait for the background unmount process to complete. If we don't set the vbd=nil, when we're cleaning up the VM we might try to unmount again, which will cause a nil pointer ref

Fix nil pointer ref in vbd

---

enterprise/app/review/view_pull_request.tsx

at least dont crash when loading diffs for binary files

---

enterprise/server/remote_execution/overlayfs/overlayfs_linux.go

The overlayfs tests were failing locally for me (on Debian bookworm), and this was the change suggested by dmesg.

Add `userxattr` to overlayfs mount to support more kernels

---

deps.bzl
go.mod
go.sum
server/libmain/BUILD
server/libmain/libmain.go
tools/deps/deps.go
tools/smarter_device_manager/BUILD

This is a change backported from #5792.
Under bzlmod, there will be no `deps.bzl` file.
The `go_repository` repos are automatically generated with gazelle's
`go_deps` extension parsing `go.mod` and `go.sum` files.
This let us consolidate go dependency management to a single source of
truth that is consistent with our editor experience.
The downside of this approach is that we should not be adding
`go_repository` declarations manually, but instead, adding them to
`go.mod` file by calling `go mod tidy -e`.
Create a dummy Go source file that imports all the Go tools dependencies
and guard it with a Go build directive that will not be used.

go.mod: add dependencies for go tooling

---

deps.bzl
server/util/bazel/BUILD

I'll remove the old versions once probers are updated.
**Related issues**: [3209](https://github.com/buildbuddy-io/buildbuddy-internal/issues/3209)

Add bazel-6.5.0 and bazel-7.1.0 to //server/util/bazel:bazel_binaries.tar

---

enterprise/server/remote_execution/containers/firecracker/firecracker.go
enterprise/server/remote_execution/containers/firecracker/firecracker_test.go

We're seeing some suspicious warnings like "Disk size 15319603456 is not a multiple of sector size 512; the remainder will not be visible to the guest." Align the disks to ensure there's no unpredictable behavior around this.

[SS] Align disks to page size

---

enterprise/server/remote_execution/containers/firecracker/BUILD
enterprise/server/remote_execution/containers/firecracker/firecracker.go

This was a missed during the earlier migration.
Ensure runfiles are used when accessing initrd.cpio and vmlinux

firecracker: ensure runfiles lib is used

---

.bazelrc
WORKSPACE

Upgrade Zig toolchain to the latest release to start trying out other toolchains with a fixed version of glibc included.

Upgrade zig toolchain to 3.0.1

---

app/invocation/invocation.tsx

Useful for debugging remote bazel invocations

Show executions tab in the UI for hosted bazel runs

---

cli/remotebazel/BUILD
cli/remotebazel/remotebazel.go

`strings.Contains()` can have false positives - not a big deal but gives a little more peace of mind

Use normalized repo URL for token check

---

enterprise/server/backends/authdb/BUILD
enterprise/server/backends/authdb/authdb.go

Rather than first performing a select to determine if we should insert or update, we can attempt an insert which does nothing on conflict and then update if the query executes without error but affects no rows.

Removes unnecessary select and fixes potential time-of-check, time-of-use problem

---

enterprise/server/githubapp/githubapp.go

We don't have the `workflow` permission right now, and I don't want to spam users with it for nothing, so we'll just settle for this right now.  If we request the permission, we'll be able to show the GH workflow name ("PR", "Check Style", etc.) instead.

just show a single analysis chip with the app name for checksuites 

---

WORKSPACE

Switch from the default
```
GOPROXY=https://proxy.golang.org,direct
```
to use `|` separator so that we fall back on `direct` download when
`proxy.golang.org` has issues (TLS handshake or 500 error).

gazelle: add GOPROXY

---

server/build_event_protocol/build_event_handler/BUILD
server/build_event_protocol/build_event_handler/build_event_handler.go
server/metrics/metrics.go

Add prometheus metric tracking client Bazel versions

---

enterprise/server/backends/prom/prom.go

add podName to buildbuddy_remote_execution_duration_usec_exported

---

enterprise/server/remote_execution/containers/firecracker/BUILD
enterprise/server/remote_execution/containers/firecracker/firecracker.go
go.mod
go.sum

Fixes errors concerning `rcu_sched detected stalls`. 
More context in this [doc](https://docs.google.com/document/d/1vyIpf093zKjz-nJdYJeL944pRT5LpsxsjyypuYdbXK0/edit) and this [thread](https://buildbuddy-corp.slack.com/archives/C01D5GHRJ59/p1711413814105089).

[SS] Always set boot arg lapic=notscdeadline in firecracker to prevent stalling

---

tools/metrics/grafana/dashboards/buildbuddy.json

it's currently showing all tasks for all executor types.

make tasks running chart only show tasks for the pool being viewed

---

enterprise/server/remote_execution/containers/firecracker/firecracker.go

Make more firecracker errors retryable

---

enterprise/app/trends/trends.tsx
enterprise/server/invocation_stat_service/invocation_stat_service.go
proto/stats.proto

will add chart to usage page separately.
we could extract and add platform info (or really just OS) to the executions table + use that to display mac vs linux minutes, which would be better, but we have the data in this PR for (effectively) all time, so it's a good starting point.

add a RBE build minutes chart to the trends page

---

enterprise/server/raft/logger/logger.go
enterprise/server/raft/replica/replica.go
enterprise/server/raft/store/store.go

When rejoining configured clusters in `NewWithArgs`, `StartOnDiskReplica` often hangs when there are more than ranges.
This happens because we didn't started processing LeaderUpdated events when we call `StartOnDiskReplica`, and when the channel for leader updated listener channel is full (after 10 occurences), it blocks LeaderUpdated API ([code](https://github.com/buildbuddy-io/buildbuddy/blob/41c76e7bb3c336e72e44450449f1a44b4e1212bf/enterprise/server/raft/listener/listener.go#L44)). Raft uses the same worker for handling system events and the leader updated queue,  (see [code](https://github.com/lni/dragonboat/blob/1d6e2d76cd5754dd27e83a8fac2600143a4b4fdc/nodehost.go#L1853)). As a result, when LeaderUpdated API is blocked, it causes the leader updated queue …

[Raft] Fix store NewWithArgs hanging when there are >50 ranges

---

enterprise/app/repo/repo.tsx
enterprise/server/githubapp/githubapp.go
proto/repo.proto

We used to implicitly rely on the presence of the `organization` string to determine if a repo should live under an organization or not (because this is how the golang github library we're using did it).
This means we didn't have owner information when creating non-organization repos, causing workflow linking to fail.
This PR fixes that by making the API explicit about whether or not the repo is being created under an organization, and always taking an `owner` field instead of an `organization` field.

Fix creating repos under non-organizations

---

enterprise/server/cmd/server/main.go
enterprise/server/test/integration/workflow/BUILD
enterprise/server/test/integration/workflow/workflow_test.go
enterprise/server/webhooks/bitbucket/bitbucket.go
enterprise/server/webhooks/github/BUILD
enterprise/server/webhooks/github/github.go
enterprise/server/webhooks/github/github_test.go
enterprise/server/workflow/config/config_test.go
enterprise/server/workflow/service/service.go
server/interfaces/interfaces.go
server/testutil/testgit/testgit.go

Example (the details link just goes to https://buildbuddy.io/docs/workflows-config for now. Later we could do something fancier, like link to a YAML editor in the Code UI, with some type of schema validation)
Also fix logging to use `CtxErrorf` when we fail to start the workflow.
**Related issues**: https://github.com/buildbuddy-io/buildbuddy-internal/issues/3115

Publish an error status when buildbuddy.yaml is invalid

---

deps.bzl
enterprise/server/cmd/executor/BUILD
enterprise/server/remote_execution/containers/firecracker/firecracker.go

* Upgrade to v1.7.0 (latest release)
* Refactor so that we only have to update `deps.bzl` when upgrading and not the genrule targets as well. (Some tweaking here was also necessary because they introduced a new top-level `release-*` directory in the tar archive which contains the firecracker/jailer binaries, rather than the binaries just being in the top-level of the archive)
* Remove `UffdPrivileged` (not supported by upstream firecracker, and seems to not be needed anymore. The tests pass, at least)
* Note: this will invalidate all cached snapshots since `firecracker_version` is part of the VmConfiguration for now, which is part of the snapshot cache key.
The baremetal tests aren't exercising the new version yet because they use the firecracker binary from the currently deployed …

Upgrade firecracker to v1.7.0

---

BUILD
server/xcode/xcode_darwin.go

This helps us identify `strings.TrimLeft` and `strings.TrimRight` miss
uses.
Reference: https://staticcheck.io/docs/checks/#SA1024

nogo: enable SA1024

---

app/components/popup/popup.css
app/root/root.css
enterprise/app/code/code.tsx
enterprise/app/code/code_build_button.tsx

Some tweaks to the code editor build button based on my experience using it:
1) Fix z-indexes that clash with monaco
2) Move the command state out of the button and into the editor component - this makes it so if you trigger a build through other means (like a sidekick), the command still gets added to your command history so it's easy to run again
3) Adds a button to edit the current command, instead of always having to create a new one
4) Adds the option to set a default config (this makes things like the sidekick more useful when you need to always add a config like --config=remote)
Included a couple of small unrelated changes that I'm happy to break out if you'd like:
1) Add a 8px more padding to the bottom of the build logs card to match the top
2) Fix new file / new folder when not …

Code editor build button tweaks

---

enterprise/server/remote_execution/containers/firecracker/firecracker.go
enterprise/server/remote_execution/platform/platform.go
proto/firecracker.proto

This will ensure that if we change boot args, we invalidate old snapshots and start using the new boot args immediately. There are pros and cons to this, but I think it would make our lives easier and save a lot of debugging time / confusion if boot args were to propagate immediately.

Add bootArgs to VMConfiguration

---

enterprise/server/remote_execution/execution_server/execution_server.go
enterprise/server/scheduling/scheduler_server/scheduler_server.go
enterprise/server/scheduling/task_router/BUILD
enterprise/server/scheduling/task_router/task_router.go
enterprise/server/scheduling/task_router/task_router_test.go
enterprise/server/test/integration/remote_execution/rbeclient/rbeclient.go
enterprise/server/test/integration/remote_execution/rbetest/rbetest.go
enterprise/server/test/integration/remote_execution/remote_execution_test.go
enterprise/tools/rbeperf/rbeperf.go
server/interfaces/interfaces.go

Depends on:
- https://github.com/buildbuddy-io/buildbuddy/pull/6156
When executors restart, all task routing info is effectively lost because we route by `executor_id`, which is set to a new UUID when the executor restarts. This PR makes it so we route by `executor_host_id` instead, which is preserved across restarts.

Use executor host ID for task routing

---

app/picker/picker.tsx
enterprise/app/code/code.tsx
enterprise/app/org_picker/org_picker.css

Tweaks from playing around with quick picker with search in dev
1. Set input text before firing off search query for more responsive input bar
2. Prefix query with `filepath:` so we only search filenames
3. Fix a little z-index issue I found

Editor tweaks

---

BUILD
enterprise/server/backends/distributed/distributed.go
enterprise/server/raft/sender/sender.go
enterprise/server/secrets/secrets_test.go
server/gossip/gossip_test.go

this result of append is never used, except maybe in other appends

nogo: enable SA4010

---

enterprise/server/gcplink/gcplink.go
enterprise/server/remote_execution/execution_server/execution_server.go

Right now we only include these in workflows runs.
This means you can't deploy from a remote bazel run, which is useful for development.

Include gcp tokens in hosted bazel runs too

---

cli/add/BUILD
cli/add/add.go
cli/bazelisk/bazelisk.go
cli/bzlmod/BUILD
cli/bzlmod/bzlmod.go
cli/fix/BUILD
cli/fix/fix.go
cli/workspace/BUILD
cli/workspace/workspace.go

Ensure that bzlmod is correctly detected.
In case bzlmod is used, we need to query for the location of
```
@@gazelle~override~go_deps~bazel_gazelle_go_repository_config//:WORKSPACE
```
so that we could feed it to Gazelle to generate BUILD files with correct
import.

cli/fix: support bzlmod

---

enterprise/server/cmd/ci_runner/main.go

In a previous change, we managed to detect when the credential helper
was invoked by `git` with the `get` operation and provide a special
espcape hatch for it.
However, `get` is not the only operation that `git` will call us with.
The other operations include `store` and `erase` in the current
git-credentials spec.
Adjust the credential helper detection when parsing flags to make sure
we don't run into infinite loop with `store` and `erase` operations
(or future new operations).

ci_main: fix cred helper handle 'store'

---

cli/bzlmod/bzlmod.go

Accidentally introduced a bug when I failed to stack different PRs.
Fix the static analysis error to turn CI green.

fix SA1024

---

enterprise/server/test/integration/podman/BUILD
enterprise/server/test/integration/podman/podman_test.go

`podman_test` was not being run on CI because the target label was not referenced explicitly in the `Baremetal tests` workflow but the target is marked with `bare` and `manual` tags. Fix errors and get it running on CI.
**Related issues**: Fixes https://github.com/buildbuddy-io/buildbuddy-internal/issues/2944

Fix podman integration test and get it running on CI

---

.github/workflows/test-executor-linux-arm64.yaml
deps.bzl
enterprise/server/test/integration/podman/BUILD
enterprise/server/test/integration/podman/podman_test.go
enterprise/server/test/integration/remote_execution/remote_execution_test.go
enterprise/server/testutil/testredis/BUILD
enterprise/server/testutil/testredis/testredis.go
platforms/configs/BUILD
server/util/bazel/defs.bzl

Adds a GitHub workflow that runs applicable RBE tests on linux-arm64 runners.

Run RBE tests on linux-arm64

---

cli/storage/BUILD
cli/storage/storage.go

Instead of detecting for WORKSPACE and check for `.git` directory,
leverage `git` to detect the root of the repo.
This location should be ideal to read/write git config to local config
file.
Closes #6282.

cli/storage: fix login with git-worktree

---

.github/workflows/build-linux-amd64-github-release-artifacts.yaml
.github/workflows/build-linux-arm64-github-release-artifacts.yaml
.github/workflows/create-github-release.yaml
tools/check_release_assets_uploaded.py

Test build (tested everything except the `gh release upload` command): https://github.com/buildbuddy-io/buildbuddy/actions/runs/7993652037/job/21829927623?pr=5960.
I ran `which gh` to sanity check that `gh` was installed. Looks like it is not yet installed by default on the arm64 runners, so I added an installation step for that.
We probably also should add docker image builds - can do that in a separate PR.

Add linux-arm64 release binaries

---

enterprise/app/review/review_list.tsx
enterprise/server/githubapp/githubapp.go
proto/github.proto

- greatly reduce quota used (120 requests for siggi's dashboard -> 2 requests with "cost" equivalent to 3 each, that is, effectively 6 requests of quota)
- speeds things up a bit (not really measured)

switch to graphql for review list page

---

.github/workflows/remote-bazel-build.yaml
cli/remotebazel/remotebazel.go

Listing all local branches to find the default branch could yield unreliable results.
For example, in Github Action, there is no local `refs/heads/{master,main}` written by the `actions/checkout` plugin.
It's also interesting how `refs/remote/origin/HEAD` symbolic ref is not written, so trying to use the symbolic ref might not work.
`refs/remote/origin/master` is written conditionally based on whether `fetch-depth: 0` is configured in the `actions/checkout` plugin or not.
Employ 2 strategies to detect the default branch: `local` and `remote`.
For `local` strategy, we attempt to read `refs/heads/{master,main}`, each, from 2 places: in the `.git/refs` directory and the `.git/packed-refs` file.
For `remote` strategy, run `git ls-remote origin` and see if either `refs/heads/{master,main}` …

workflows/remote-bazel: fix default branch not found

---

BUILD
server/xcode/BUILD
server/xcode/xcode_darwin.go
server/xcode/xcode_darwin_test.go

The previous usage of TrimLeft yielded an unexpected result, so to
compensate for it, we added a "/" prefix to the result developerDirPath.
Change this to TrimPrefix requires us from removing that forward-slash
compenstation.
Provide a test to demonstrate the issue.

xcode: fix TrimLeft to TrimPrefix

---

enterprise/server/raft/replica/replica.go
enterprise/server/raft/store/store.go

Fix https://github.com/buildbuddy-io/buildbuddy-internal/issues/3266. Right now,
everytime we call `AddRange` we launch a goroutine to update tags. Each updateTags
call will grab `gm.mu`. This causes `gossipManager.AddListener` to be blocked in
`NewWithArgs`, because `AddListener` needs to wait for `gm.mu` to be unlocked. 
In this PR, I created a worker to handle updateTags tasks, and will skip
updateTags if the task createdAt is before the lastExecutedAt. When I tested in
dev, we skipped update tags 813 times and only ran updateTags for 17 times.
`NewWithArgs` finished in 11 seconds.

[raft] create a worker to handle update tags tasks and skip update tags when necessary

---

buildbuddy.yaml
server/testutil/app/app.go
server/testutil/testenv/testenv.go

`sqlite3://:memory:` has some gotchas which I think were causing the issues with flaky webdriver tests in which tables were suddenly disappearing in the middle of the test.
I randomly stumbled across this HN comment which mentioned the same symptom we were seeing (tables randomly disappearing): https://news.ycombinator.com/item?id=39956165
Also see the linked FAQ here: https://github.com/mattn/go-sqlite3?tab=readme-ov-file#faq
Specifically
> Why I'm getting no such table error?
> Why is it racy if I use a sql.Open("sqlite3", ":memory:") database?
> Each connection to ":memory:" opens a brand new in-memory sql database, so if the stdlib's sql engine happens to open another connection and you've only specified ":memory:", that connection will see a brand new database. …

Don't use `sqlite3://:memory:`

---

dockerfiles/executor_image/Dockerfile

I think I accidentally removed this while resolving a merge conflict. This is causing the baremetal tests to fail in dev, because it is unable to convert OCI images to EXT4 which requires skopeo.

Add skopeo back to executor image

---

enterprise/server/cmd/executor/BUILD
enterprise/server/remote_execution/container/BUILD
enterprise/server/remote_execution/container/container.go
enterprise/server/remote_execution/containers/firecracker/BUILD
enterprise/server/remote_execution/containers/firecracker/firecracker.go
enterprise/server/remote_execution/platform/platform.go
enterprise/server/remote_execution/runner/BUILD
enterprise/server/remote_execution/runner/runner_linux.go
enterprise/server/remote_execution/runner/runner_linux_amd64.go
enterprise/server/remote_execution/runner/runner_linux_notamd64.go
enterprise/server/remote_execution/soci_store/soci_store_linux.go

We'll need arm64 builds of soci-snapshotter as well as vmlinux and firecracker/jailer before we can enable these. Would also be good to have CI tests for these to avoid breakage. Since this seems like significant work, disable these for now and avoid building / shipping them as part of the go binary / docker image.

Disable Firecracker and soci-snapshotter on arm64 for now

---

.github/workflows/test-executor-linux-arm64.yaml
enterprise/server/remote_execution/commandutil/BUILD
enterprise/server/test/integration/remote_execution/BUILD

Increase local CPU resources to 4 and set size="enormous" (which IIUC just increases memory to 800MB) on some tests to prevent too many expensive local test actions from running concurrently on the arm64 runner, which was causing OOMs. Also disable benchmark tests which can consume an inordinate amount of resources.

Deflake arm64 RBE tests

---

app/util/popup.ts

On Linux, a scrollbar is rendered inside the window which consumes 15px, so the window winds up being effectively 385px wide, and it looks squished. Add a little more width so that the window doesn't need to scroll, and looks good on both Linux and macOS.

Make the auth popup a little wider

---

server/util/background/BUILD
server/util/background/background.go
server/util/background/background_test.go

If the parent context has the default action timeout (7 days) and gets canceled (either before or after calling ExtendContextForFinalization), then the context returned by ExtendContextForFinalization will have a deadline that is 7 days + 15s in the future, rather than 15s starting from the time of cancellation like we would expect.
This PR changes the implementation to match the expected behavior in this case, which is to apply a deadline that is `<whenever the parent context gets canceled, either via deadline or manual cancel>` + 15s.

Have ExtendContextForFinalization respect the parent context's cancelation

---

enterprise/server/githubapp/githubapp.go
proto/github.proto

this makes it a little easier to write code that cares about the review id, thread id, final comment position, "real" comment id, yada yada.

echo comment info from github back when creating new comments.

---

app/format/BUILD
app/format/format.tsx
app/invocation/invocation_action_card.tsx

Also tidy up action details.
Before:
After:
- Moved "cacheable" towards the end since it's less interesting than inputs and causes a visual break between the 2 digest components
- Removed output node properties since these are always unset from what I've seen and also have been removed from the upstream proto (if there are some old bazel versions where this is useful, we can always add it back, but it seems unlikely)

Render action timeout in action page

---

.bazelrc
cli/printlog/printlog.go

Fixed an issue in `reconstructDir()` where the filesInDir slice was
initiated with nil entries.
Rename the compact log file to have the right extension.

cli/printlog: improve compact exec log

---

tools/firecracker_clean_networking.sh

- Kill firecracker processes first (before removing network resources that may be in use)
- Kill with SIGKILL so firecracker exits immediately
- Don't fail if there are no firecracker processes
- Don't fail if there are no net namespaces to clean up
- Get rid of iptables clean up (pretty sure this is not needed - our networking cleanup in Go code doesn't do this)
- Rename to `firecracker_clean` since it cleans processes too (not just networking)

Small tweaks to firecracker cleanup script

---

enterprise/server/remote_execution/snaploader/snaploader.go

If we have to rollback https://github.com/buildbuddy-io/buildbuddy/pull/6341/files, any snapshots written in the meantime will break, because there will be two auxiliary metadata entries (the vm config + the new vm metadata). Add this first to make rollouts safer.
I'll cherry pick and deploy this before #6341 goes out.

Make snaploader code more rollout safe before my proto change

---

server/util/background/BUILD
server/util/background/background.go

These debug logs are turning out too noisy and making the logs less usable.

Disable debug logs in disconnectedContext.Deadline()

---

enterprise/server/raft/replica/replica.go
enterprise/server/raft/replica/replica_test.go

Clear replica states after we apply remote snapshot to recover

---

server/remote_cache/byte_stream_server/BUILD
server/remote_cache/byte_stream_server/byte_stream_server.go
server/remote_cache/byte_stream_server/byte_stream_server_test.go

When writes are small, traces look like this:
small writes (which are most writes) should get a 75% drop in latency, and current AlreadyExists rates imply this shouldn't increase load.

Add flag to skip Contains() check in bytestream.Write if file is small.

---

server/remote_cache/hit_tracker/hit_tracker.go

This removes a return that prevents us cleaning up counters when detailed stats are enabled (as they are in prod).

Don't skip deleting counters when detailed stats are enabled

---

enterprise/tools/vmexec/BUILD
enterprise/tools/vmexec/vmexec.go

- Make it statically linked so we can easily copy it to the executor pod
- Add comments about how to use it to debug a live executor pod
- Shorten the name to `vmexec` - feels a bit more convenient when running it at the command line
- Improve arg parsing to allow running shell scripts

Tweaks to vmexec client tool

---

server/tables/tables.go

**Related issues**: https://github.com/buildbuddy-io/buildbuddy-internal/issues/3286

Update DB schema for workflows non-root migration

---

enterprise/server/remote_execution/dirtools/dirtools.go

On Windows Executor, the path separator is backslash `\`.
The action result that we currently creating and consumed by Bazel would
look like this:
```
"outputFiles": [
{
"path": "bazel-out\\k8-fastbuild\\bin\\b.txt",
"digest": {
"hash": "..."
}
}
],
```
and Bazel would err with
```
remote spawn failed: Invalid action cache entry ...: expected output b.txt does not exist.
```
Ensure that ActionResult always use posix path so it would look like
this instead:
```
"outputFiles": [
{
"path": "bazel-out/x64_windows-fastbuild/bin/b.txt",
"digest": {
"hash": "..."
}
}
],
```

dirtools: ensure ActionResult ouputs are posix

---

enterprise/server/remote_execution/vmexec_client/BUILD
enterprise/server/remote_execution/vmexec_client/vmexec_client.go

Make sure we return Unavailable in more places, and make sure to wrap errors in a few places so that we have more context.
Also add a temporary info-level log message in the case where the error returned is from the vmexec server (to help with debugging).

Improve vmexec RPC error handling

---

enterprise/server/remote_execution/runner/runner.go

#6345 fixed a bug where in many cases, ExtendContextForFinalization would extend the context deadline ~indefinitely (7 days, to be specific). Now that it's fixed, certain code paths are failing because the finalization deadlines we'd set are too short
P99 to pause a firecracker VM takes 1.5min. Setting the deadline to 3min to be safe (P95 frequently reaches 1.5min as well)

Extend finalization deadline for pausing firecracker VMs

---

enterprise/server/remote_execution/containers/firecracker/firecracker.go

There was one codepath where we weren't closing the `execDone` channel, so the message would get logged even if there was an error returned that would short-circuit execution.

Fix a case where we incorrectly log 'execution possibly stuck'

---

server/util/networking/BUILD
server/util/networking/networking.go
server/util/networking/networking_test.go

This just locks IP ranges within a single executor process for now - a future improvement would be to lock across executors as well so that we can run VM networking tests in parallel.

Lock VM host network IP ranges while in use

---

enterprise/server/hostedrunner/hostedrunner.go
server/remote_cache/cachetools/cachetools.go

The ci runner bundle has gotten too large, so we were seeing errors like `ResourceExhausted desc = grpc: received message larger than max (50464990 vs. 50000000)` when trying to upload it to the cache. Use a bytestream write instead to handle large blobs.
Customers have previously reported similar errors, so hopefully this helps there too: https://buildbuddy-corp.slack.com/archives/C057TAUAQ7P/p1701803746816029?thread_ts=1701800129.129309&cid=C057TAUAQ7P
This PR also changes the hosted runner to use blake3 to generate digests. Hopefully this will help performance with these huge blobs
**Related issues**:  Fixes https://github.com/buildbuddy-io/buildbuddy-internal/issues/3263

[RB] Stream large writes to prevent grpc errors

---

enterprise/server/remote_execution/containers/firecracker/firecracker_test.go
enterprise/server/remote_execution/filecache/filecache.go
enterprise/server/remote_execution/filecache/filecache_test.go
server/remote_cache/digest/digest.go
server/util/disk/disk_unix.go
server/util/disk/disk_windows.go

When calling `AddFile`, stat the file to get the number of blocks consumed by the file, and compute the size based on the number of blocks consumed, rather than the content stored in the blocks. The extra `stat()` syscall does not significantly affect performance according to benchmarks:
```
goos: linux
goarch: amd64
cpu: AMD Ryzen 9 7950X 16-Core Processor            
│ /tmp/bench_false.txt │        /tmp/bench_true.txt         │
│        sec/op        │   sec/op     vs base               │
FilecacheLink/100%Link/0%Add/1K-32            15.52m ± 1%   15.57m ± 1%       ~ (p=0.631 n=10)
FilecacheLink/95%Link/5%Add/1K-32             14.77m ± 2%   14.75m ± 3%       ~ (p=0.436 n=10)
geomean                                       15.14m        15.15m       +0.07%
```
A future improvement could be …

Use block-based size for filecache entry size

---

enterprise/server/raft/rbuilder/rbuilder.go
enterprise/server/raft/replica/replica.go
proto/raft.proto

DirectDelete is used to delete keys in meta range. The current Delete method
only allows us to delete file records. We need this methods to maintain
transaction records.

[Raft] Add a direct delete request

---

enterprise/server/remote_execution/containers/firecracker/firecracker.go
enterprise/server/remote_execution/containers/firecracker/firecracker_test.go
enterprise/server/util/ext4/BUILD
enterprise/server/util/ext4/ext4.go
enterprise/server/util/ext4/ext4_test.go
enterprise/server/util/ociconv/BUILD
enterprise/server/util/ociconv/ociconv_test.go

We currently fail to convert `alpine` to ext4 since it has a large amount of symlinks compared to other images, which are reported by `du` as requiring 0 bytes. (More specifically, all of the standard tools like `/usr/bin/du` are symlinks to `/bin/busybox`).
`du` does not seem to have a way to incorporate metadata into file size calculations, so the fix in this PR is to add a manual `WalkDir` procedure that estimates the metadata size as 1 block per `DirEntry`.

Fix ext4 DirectoryToImageAutoSize not working for some images

---

enterprise/app/code/code.tsx
enterprise/app/sidekick/bazelrc/bazelrc.tsx
enterprise/app/sidekick/module/module.tsx

This prevents these listeners from clobbering each other.
Also makes sure to call `document.removeEventListener` in `componentWillUnmount`.

Replace instances of `document.onkeydown = ` with `document.addEventListener`

---

enterprise/app/code/BUILD
enterprise/app/code/code.css
enterprise/app/code/code.tsx

Makes breadcrumbs look a little less broken, and adds a `Continue with GitHub` button instead of a blank screen.

Make editor a little nicer when GitHub isn't linked yet

---

app/terminal/ansi.tsx

We can relax this later, but the current regex is a bit too lenient and is rendering links all over the place.

Require `http(s)://` prefix to render links

---

enterprise/server/remote_execution/execution_server/execution_server.go

Truncate the `Execution` table `status_message` column with ellipsis (it currently looks a little awkward when rendered in the UI).

Use "..." for truncated execution status messages

---

enterprise/server/raft/store/BUILD
enterprise/server/raft/store/store.go
enterprise/server/raft/store/store_test.go

Move db, leaser creation out of NewWithArgs, so in tests we are able to write stuff to pebble. 
also flush the db and close the leaser on stop()

[raft] refactor: move pass db and leaser into NewWithArgs

---

enterprise/server/workflow/service/service.go

This allows workflow users to link to these invocations in other systems.

Add `BUILDBUDDY_INVOCATION_ID` environment variable to workflows

---

server/build_event_protocol/build_event_server/build_event_server.go

Small refactor primarily to try to improve readability.
- Added some logging.
- Did a small refactor to not attempt to process an empty channel.
- Removed an error case that cannot occur (there is no way that we can return `AlreadyExistsError` from `HandleEvent`).

Small clean-up of build event handler logic

---

app/target/target_test_cases_card.tsx

If not populated, fallback to the overall test time like we currently do.

Display `testSuite` time when parsing `test.xml` if populated

---

enterprise/app/org/org_members.tsx
enterprise/app/org_picker/org_picker.tsx
enterprise/app/settings/settings.tsx

Makes it a little easier to figure out what email address you're logged in with.
Also adds a little `(You)` call-out in the org members list.

Show logged-in user's email when hovering over name

---

enterprise/server/remote_execution/containers/firecracker/firecracker.go
enterprise/server/remote_execution/containers/firecracker/firecracker_test.go
enterprise/server/util/ext4/BUILD
enterprise/server/util/ext4/ext4.go
enterprise/server/util/ext4/ext4_test.go
enterprise/server/util/ociconv/BUILD
enterprise/server/util/ociconv/ociconv_test.go

Original PR https://github.com/buildbuddy-io/buildbuddy/pull/6380
The fixes are in [this commit](https://github.com/buildbuddy-io/buildbuddy/commit/rollforward-disksize)
* Use `lstat` instead of `stat` since `stat` can fail on "dangling" symlinks (symlink with a target that does not exist)
* Fix a bug which existed before the original PR: in `DirectoryToImageAutoSize`, `if err != nil { return nil }` should be `if err != nil { return err }`
* Make sure `ext4_test` runs on CI and add regression tests for both of the above issues
* Increase minimum disk size to fix the alpine image conversion test

Roll-forward "Fix ext4 DirectoryToImageAutoSize not working for some images (#6380)"

---

app/invocation/invocation_action_card.tsx
enterprise/server/remote_execution/snaploader/snaploader.go
proto/remote_execution.proto

**Related issues**: https://github.com/buildbuddy-io/buildbuddy/pull/6341

Clean up deprecated remote_execution.VMMetadata field

---

app/invocation/BUILD
app/invocation/invocation_error_card.tsx
app/invocation/invocation_model.tsx

* Structure errors as a list rather than trying to pick out a single error from the build
* Support rendering more types of errors
* Fetch failed action stdout (not just stderr) - e.g. TypeScript actions put their errors on stdout. So now we show typecheck errors directly in this card
---
Before:
After:
---
Before:
After:
**Related issues**: Fixes https://github.com/buildbuddy-io/buildbuddy/issues/6404

Rework invocation error card and render more types of errors

---

enterprise/server/remote_execution/filecache/BUILD
enterprise/server/remote_execution/filecache/filecache.go
enterprise/server/remote_execution/filecache/filecache_test.go

Fixes a bug that a file being deleted concurrently with the directory scan will cause the directory scan to short-circuit, resulting in the remaining files not being added to the cache.

Fix filecache concurrent scan and remove

---

deployment/BUILD
enterprise/deployment/BUILD
release.py

The `container_push` rule from `rules_docker` seems to have a bug where it builds some (but not all) image layers with mediaType `application/vnd.oci.image.layer.v1.tar` rather than `application/vnd.docker.image.rootfs.diff.tar.gzip`, even though we're setting `format = "Docker"`. (This only seems to happen on arm64 for some reason, but it could possibly just be because the linux arm64 runners are on ubuntu 22.04 and might have a newer version of dockerd). containerd and podman do not seem to support the `oci` format, or at least they don't support mixing both types of image layers in the same manifest.
I didn't see a straightforward way to customize the mediaType in any of the `rules_docker` rules, so the fix in this PR is to build the image via the `container_image` target but then push …

Fix incorrect mediaType in arm64 executor image layers

---

server/remote_asset/fetch_server/BUILD
server/remote_asset/fetch_server/fetch_server.go
server/remote_asset/fetch_server/fetch_server_test.go

Implement support for digest function in FetchBlobRequest as well as
usage of Blake3 as a digest func.

fetch_server: support digest function and blake3

---

enterprise/app/history/history.tsx

preserve filter state when going to trends page from history page

---

enterprise/server/remote_execution/vmexec_client/BUILD
enterprise/server/remote_execution/vmexec_client/vmexec_client.go

If we stop receiving messages on the vmexec stream, it means we somehow got into a bad state, because we should be sending status updates once every 250ms during normal operation.
This PR adds a timeout to detect when the stream is stuck - conservatively just set to 1 minute for now because we don't have the data as to how high the recv interval is in practice.

Apply timeout to vmexec stream recv

---

enterprise/server/remote_execution/containers/firecracker/firecracker.go

Mount/unmount should be relatively fast, so if these RPCs take longer than 1 minute then the vmexec server is likely stuck and the mount/unmount will likely never complete. Return an error in this case rather than allowing the RPC to hang.

Add timeout to guest mount/unmount RPCs

---

enterprise/server/cmd/server/BUILD
server/BUILD
server/cmd/buildbuddy/BUILD

https://github.com/buildbuddy-io/buildbuddy/pull/6416 changed the behavior of `release.py` to build the docker images with `bazel run` but then push them with the `docker` CLI, rather than using the `container_push` targets.
When calling `bazel run` on the BuildBuddy server `go_image` targets though, it actually runs the server image after building it. This differs from `container_image` which just builds and tags the image. This behavior causes `release.py` to get stuck running the server.
To fix this issue, this PR changes the `buildbuddy_image` server targets (OSS and enterprise) to be `container_image` targets rather than `go_image` targets.

Fix release.py running docker images instead of just building

---

enterprise/server/workflow/service/service.go

The workflow config schema supports an "env" section for passing arbitrary env vars but it was only being set for individual bazel commands. This PR makes it so we set the env at the action level, which allows passing env vars e.g. to git, like `GIT_TRACE2=1` or `GIT_CURL_VERBOSE=1`.

Apply workflow action env to CI runner env, not just bazel commands

---

release.py

When we derive the image tag from the target name (as rules_docker does), we need to use the non-aliased target name since rules_docker doesn't know about our aliasing.

Use non-aliased target for image push

---

BUILD
enterprise/server/raft/bringup/bringup.go

Enable golang static check analyzer SA9001: Defers in range loops may not run when you expect them to

---

server/libmain/libmain.go
server/util/grpc_server/grpc_server.go
server/util/monitoring/monitoring.go

Clean up code flow for gRPC server setup and server registration

---

enterprise/server/action_cache_server_proxy/BUILD
enterprise/server/action_cache_server_proxy/action_cache_server_proxy.go
enterprise/server/byte_stream_server_proxy/BUILD
enterprise/server/byte_stream_server_proxy/byte_stream_server_proxy.go
enterprise/server/capabilities_server_proxy/BUILD
enterprise/server/capabilities_server_proxy/capabilities_server_proxy.go
enterprise/server/cmd/cache_proxy/BUILD
enterprise/server/cmd/cache_proxy/cache_proxy.go
enterprise/server/content_addressable_storage_server_proxy/BUILD
enterprise/server/content_addressable_storage_server_proxy/content_addressable_storage_server_proxy.go
server/libmain/libmain.go
server/util/grpc_server/grpc_server.go

This PR introduces a new cache_proxy server (`//enterprise/server/cmd/cache_proxy`) that proxies the ActionCache, ByteStream, Capabilities, and ContentAddressableStorage services to the specified backend server. It authenticates with the backing cache by forwarding the provided API Key along. This server is currently running in dev at `grpcs://proxy.buildbudd.dev`, you can build against it by running something like:
```
bazel clean && bazel build --config=remote-dev --remote_cache=grpcs://proxy.buildbuddy.dev --remote_header=x-buildbuddy-api-key=[REDACTED] //server/util/status
```
Next steps are to add a local cache, better auth, and then try routing executor-to-app traffic through the proxy.
I went back and forth over whether to switch the gRPC server configuration to use the Builder …

Basic CacheProxy Server

---

app/invocation/BUILD
app/invocation/invocation.css
app/invocation/invocation.tsx
app/invocation/invocation_exec_log_card.tsx
app/invocation/invocation_execution_card.tsx
app/invocation/invocation_model.tsx
app/invocation/invocation_timing_card.tsx
package.json
proto/BUILD
yarn.lock

Renders the compact execution log on the `Executions` tab if the following Bazel flags are set:
```
--experimental_execution_log_compact_file
--remote_build_event_upload=all
```
Also adds a download button to the card title so users can easily download the file for their own analysis.
Kept the rendering basic to start. Currently renders most of the spawn details we get in a list, and each links to its corresponding action details card.
Added filtering by mnemonic and runner type, sorting by total duration asc / desc, and text filtering by target label, args, and digest.
I explicitly didn't touch any input / output file rendering / diffing / linking / graph creation - even though I think that's probably the most valuable thing we can do with this information. Just want to get something …

Add some basic rendering for the execution log in the UI

---

cli/plugins/go-deps/post_bazel.py

Fixes https://buildbuddy.slack.com/archives/CUHBFVATU/p1714155129601919
Reproduced locally (had to run a bb build with `--enable_bzlmod --noincompatible_sandbox_hermetic_tmp`) and verified the fix.

go-deps: resolve _main to workspace dir

---

enterprise/app/review/review.css
enterprise/app/review/review_thread.tsx

I don't think this is an *exact* match to the "familiar" behavior, but it seems close enough.
I'll be adding text to the file list about the number of unaddressed comments (when the author is viewing) + draft comments (everyone) in a separate PR.
Fixes buildbuddy-io/buildbuddy-internal/issues/3324 (this is the last issue i'll address as part of that bug, let's file individual bugs from now on, i'll add a tag)

shade comments lighter when the current user has already replied

---

enterprise/server/githubapp/githubapp.go
proto/github.proto

add server-side support for identifying moved files.

---

WORKSPACE
WORKSPACE.bzlmod
docs/rbe-github-actions.md
docs/rbe-setup.md

Includes our new Windows cc toolchain and several cleanups.
Should be a no-ops for us, but users will get docs with up-to-date
commit and SHA.

buildbuddy-toolchain: upgrade to the latest version

---

enterprise/server/remote_execution/containers/firecracker/firecracker.go
server/util/networking/BUILD
server/util/networking/networking.go
server/util/networking/networking_test.go

Instead of using `vmIdx` for the clone IP, we want to use the `netIdx` which we have locked. The `netIdx` is different from the `vmIdx` in the case where the `vmIdx` is already in use.
This also restructures the cleanup work that needs to be done after calling `SetupVethPair`. Because the clone IP depends on the `netIdx` and not the `vmIdx`, some of the current cleanup work that is done in `firecracker.go` would now need to know about the `netIdx`. But this feels a bit like implementation details leaking out. So, in order to avoid exposing the `netIdx` and having to plumb it around, this PR makes it so that the cleanup func already returned by `SetupVethPair` now also does this cleanup work. This makes the networking API a bit simpler since more of the cleanup work is done automatically. …

Fix VM network clone IP calculation and consolidate cleanup

---

app/invocation/invocation_exec_log_card.tsx
app/invocation/invocation_model.tsx

Let users download the compact execution log with the correct file
extension. This way users could immediately tell how to consume the
downloaded file.
Also support the new file name that was proposed in (1).
(1): https://github.com/bazelbuild/bazel/pull/22172

exec_log_card: download execution log with ext

---

.bazelrc
.gitignore

In a shared environment, the file under `/tmp` could be written by
another user, thus cause a permission conflict.
Let's write it to user's local repo to avoid this issue.

bazelrc: write exec log to local repo

---

app/invocation/invocation_timing_card.tsx

Currently we are assuming that the BuildToolLogs event will have
relatively small amount of files that are uploaded via bytestream API.
Using that assumption, we guessed that the build timing profile must be
one of the 2 files referenced in this event, and differentiate them
based on their file name.
Detect the actual timing profile name by searching through canonical
command line for a `--profile=` flag. If the user does not specify a
custom profile name, assume the default `command.profile.gz` name.

timing_card: get profile from structured flag

---

enterprise/server/cmd/ci_runner/main.go
enterprise/server/test/integration/ci_runner/ci_runner_test.go
enterprise/server/workflow/config/BUILD
enterprise/server/workflow/config/config.go
enterprise/server/workflow/config/config_test.go
enterprise/server/workflow/service/service.go

* Instead of `git clone`, do a `git init` which doesn't fetch anything.
* Allow customizing the `git fetch` via two new workflow config options `git_fetch_filters` and `git_fetch_depth`. `git_fetch_filters` defaults to `["blob:none"]` to match what we have today, and `git_fetch_depth` defaults to `0` (equivalent to not being set).

workflows: allow customizing git fetch

---

tools/metrics/BUILD
tools/metrics/docker-compose.grafana.yml
tools/metrics/docker-compose.victoria-metrics.yml
tools/metrics/grafana/BUILD
tools/metrics/grafana/dashboards-vm/BUILD
tools/metrics/grafana/dashboards.bzl
tools/metrics/grafana/grafana.go
tools/metrics/grafana/provisioning/deploy/datasources/datasources.yml
tools/metrics/grafana/provisioning/local/datasources/datasources.yml
tools/metrics/process_dashboard.py
tools/metrics/victoria-metrics/scrape.yml

* Add a `--vm` arg to `tools/metrics/grafana` to use VictoriaMetrics as the datasource
* Auto-generate VictoriaMetrics versions of our current prometheus grafana dashboards
**Related issues**: https://github.com/buildbuddy-io/buildbuddy-internal/issues/3294

Update Grafana setup for VictoriaMetrics
