buildbuddy-io/buildbuddy

enterprise/server/raft/bringup/bringup.go
enterprise/server/raft/rangelease/rangelease_test.go
enterprise/server/raft/replica/replica.go
enterprise/server/raft/replica/replica_test.go
enterprise/server/raft/store/store.go
enterprise/server/raft/store/store_test.go
proto/raft.proto

Store the nhid in ReplicaDesciptor. This enables us to tell which store has
a particular range by looking at the rangeDescriptor which contains a list of 
ReplicaDescriptors.

Add NHID to replica descriptor

---

enterprise/server/certgenerator/BUILD
enterprise/server/certgenerator/certgenerator.go
proto/BUILD
proto/certgenerator.proto
server/http/interceptors/interceptors.go
server/rpc/interceptors/interceptors.go
server/ssl/ssl.go

The initial use case is for SSH certificates.
The user will present an OIDC token and a public key. After validating the token, the server will sign the public key and return the signed key back to the user.

Add service for generating short-lived user certificates.

---

enterprise/server/workflow/config/BUILD
enterprise/server/workflow/config/config.go
enterprise/server/workflow/service/BUILD
enterprise/server/workflow/service/service.go

If enabled, automatically insert a custom workflow which will effectively run:
```bash
blaze build --override_repository kythe_release=$KYTHE_DIR --bazelrc=$KYTHE_DIR/extractors.bazelrc //...
```
only when the default branch is Pushed.

Run a kythe workflow if codesearch is enabled

---

enterprise/server/remote_execution/containers/podman/BUILD

`tar` is trying to preserve the file permissions on the original artifact stored in GH actions but this is causing some issues for some workflows: https://buildbuddy.buildbuddy.dev/invocation/9727fbf8-e397-4a4c-a15f-4a3ec519231a?role=CI_RUNNER&days=7&branch=master
We don't need to preserve the exact owner from the release archive so just set `--no-same-owner` as a fix for now.

Fix uid/gid errors from podman tar command

---

enterprise/server/cmd/ci_runner/main.go

Fixes the error
```
/root/workspace/buildbuddy_ci_runner --credential_helper store: 1: /root/workspace/buildbuddy_ci_runner: not found
```
e.g. from this invocation: https://buildbuddy.buildbuddy.dev/invocation/9727fbf8-e397-4a4c-a15f-4a3ec519231a?actionDigest=6f58d2073848230084b1eedb848c1d1c593187c13f5457a41a1814245b4885d0%2F141&executeResponseDigest=c09bb1611a6ccc9e18ba4d038b0515d8926ab476f0305428e03c76929b781d31%2F184&role=CI_RUNNER&days=7&branch=master
The buildbuddy_ci_runner binary is stored in `/workspace`, but we change to `/root/workspace` before running workflows so that the workflow outputs don't wind up in the action working dir (to avoid expensive workspace syncing). We need to compute the CI runner's absolute path before changing to this dir.
I'm not sure how this ever …

Fix incorrect credential helper path

---

app/invocation/invocation_timing_card.tsx

Suspected to break timing profiles for invocations with `--profile`.
Reverts buildbuddy-io/buildbuddy#6465

Revert "timing_card: get profile from structured flag"

---

docs/rbe-platforms.md

Confusingly, using `./name` as the link target will refer to the subpath under the current URL, instead of under the current directory.

Fix some broken links in platforms docs

---

.bazelrc

These flags are enabled by default in Bazel 7.

Remove Bazel flags enabled by default

---

.bazelrc

Fixes warnings such as:
```
WARNING: /private/var/tmp/_bazel_fmeum/412888b82b4f18156bc415025cb8faa1/external/npm_fast-glob-3.2.7/BUILD.bazel:6:10: input 'extract_tmp/package' to @@npm_fast-glob-3.2.7//:_npm_fast-glob-3.2.7 is a directory; dependency checking of directories is unsound
```

Fix non-hermeticity with rules_nodejs' directory inputs

---

enterprise/server/raft/store/store.go

Also remove calculating totalBytesUsed in the replicas.Range loop since it was overwritten later by diskEstimateBytes

set total bytes free in store.Usage

---

enterprise/server/remote_execution/containers/bare/BUILD
enterprise/server/remote_execution/containers/bare/bare.go
enterprise/server/remote_execution/containers/bare/bare_test.go

With `podman` we can run `podman logs` to see the output from a running container so we can debug it if it's stuck. This PR adds a similar capability to `bare` runners by writing command logs to a file while they are running (behind a flag).
Planning to enable these on mac workflow executors so that we can debug stuck workflow tasks.

Add flag to write bare runner output to temp log files for debugging

---

enterprise/server/cmd/ci_runner/main.go

Disable git credential helpers for all setup commands, including `git checkout` -- not just the `git fetch` command. `git checkout` can result in a fetch so we need to clear out the credential helper here too.

Disable git credential helpers for all setup commands

---

app/invocation/BUILD
app/invocation/invocation_action_card.tsx
app/invocation/invocation_action_tree_node.tsx

Refactor InputNodeComponent:
- Rename to TreeNodeComponent in prepare for later reuse in the Output tree.
- Add support for SymlinkNode. <img width="1501" alt="image" src="https://github.com/buildbuddy-io/buildbuddy/assets/26684313/25757475-3d79-4fb0-b442-85958c75f7e2">

Rename InputNodeComponent to NodeComponent

---

tools/bbcert/BUILD
tools/bbcert/bbcert.go

Obtains an OIDC token from gcloud, sends it to the remote server along with the SSH public key to be signed.
Once the cert is obtained, it's written to a location that ssh expects to find it.

Add command line tool for obtaining a SSH cert.

---

enterprise/server/raft/store/store.go

When a new store is created without any ranges. It is not known to other stores
by store_usage tag; and thus in my placement driver prototype, https://github.com/buildbuddy-io/buildbuddy/pull/6515,
the new store was not detected by other stores as a valid replication target.

queue update usage tags task at the end of new with args

---

enterprise/app/trends/BUILD
enterprise/app/trends/heatmap.tsx

A small itch I've wanted to scratch for a while. I find this a bit easier to use because it means I don't have to keep my mouse perfectly within the chart bounds while making a selection (this gets more difficult when the selection is close to the edge of the chart), but lmk if you think the old behavior is better and I'd be fine closing this
Screenshot (shows current behavior first, then new behavior)
https://github.com/buildbuddy-io/buildbuddy/assets/2414826/1a733863-62bd-4430-9440-ad746f0eb83d

Allow moving mouse outside heatmap while making selection

---

enterprise/server/raft/rangelease/rangelease.go
enterprise/server/raft/replica/replica.go
enterprise/server/raft/store/store.go

In replica.Replica, rename member var ShardID -> shardID and ReplicaID ->
replicaID.
In placement driver [PR](https://github.com/buildbuddy-io/buildbuddy/pull/6515),  I need to get access to shard id and replica id through interface
functions; and golang doesn't allow me to create ShardID() when there is
a ShardID member variable.
Also, changing it to private variables make it impossible for other
classes to accidentally change shard id and replica id.

[raft] Add methods in replica.Replica to get IDs and range descriptor.

---

enterprise/server/raft/store/store.go

nodehost.Close() might invoke some tasks that require the db such as save
snapshot. close db before nodehost.Close can cause panic.

close db and leaser after nodehost.Close() is called

---

enterprise/server/raft/store/store.go
enterprise/server/raft/store/store_test.go

When we are up-replicating meta range, we only want to add 1 statement instead
of 2 in AddReplica. 
Also, Add some contexts when returning error in AddReplica.

raft: fix a bug in AddReplica when we want to up-replicate meta range

---

cli/add/add.go
cli/fix/fix.go

- Support searching for `bazel_deps` that contain repo_name (like ours do) ex:
```
bazel_dep(name = "rules_go", version = "0.47.1", repo_name = "io_bazel_rules_go")
```
- Add repo_root flag to gazelle invocations with bzlmod enabled (because gazelle has a hard time locating this repo root)
---
Still trying to understand / figure out a better solution for this gnarliness https://github.com/buildbuddy-io/buildbuddy/blob/master/cli/fix/fix.go#L76 which doesn't seem to work for me. But these two changes are nice to have regardless.

CLI fix fixes

---

proto/remote_execution.proto

The motivation for this PR is that when running a workflow we just show "Invocation is waiting for an available worker." This message is sort of misleading - often, the workflow action will be dequeued quickly, but then most of the time is spent booting or resuming the workflow VM.
But today, we don't really have a good way to display a more accurate message about what the task is currently doing. We do have ExecutionStage, but it only has "QUEUED" and "EXECUTING" stages, which are pretty coarse grained. If we were to use this data, we'd likely be in a similar position that we're in today, just showing "Invocation is executing" instead of "Invocation is waiting for an available worker", which doesn't feel much better.
This PR proposes a general way to communicate finer-grained progress …

Add protos for fine-grained execution progress

---

docs/enterprise-api.md
enterprise/server/api/api_server.go
proto/api/v1/workflow.proto

**Related issues**: This PR must be rolled out first: https://github.com/buildbuddy-io/buildbuddy/pull/6519

Support passing a commit sha in the ExecuteWorkflow API

---

enterprise/app/review/file_content_monaco.tsx
enterprise/app/review/review.css

- Don't re-render when size hasn't changed.
- Debounce resize events instead of relying on Monaco to do it.
- Dispose editor when component is unmounted (preventing attempts to re-render)
- Corresponding hacks and nonsense to make things work clean.
- A random bug fix where zones were being accounted to the wrong editor.

some performance improvements to diff rendering--not perfect but way better

---

app/invocation/invocation.css
app/invocation/invocation_action_card.tsx

Also fixed Command.environmentVariables and platform properties to
render as `None` when emptied.

invocation_action_card: render output symlinks

---

enterprise/server/webhooks/webhook_data/webhook_data.go
enterprise/server/workflow/config/config.go
enterprise/server/workflow/service/BUILD
enterprise/server/workflow/service/service.go
enterprise/server/workflow/service/service_test.go

Currently, the kythe workflow action is only running for the ExecuteWorkflow API and not when a webhook triggers the workflow service. My understanding is the opposite should be happening
Consolidate the code where we match workflow actions to prevent this from happening in the future.

Fix kythe workflow action

---

server/util/grpc_server/grpc_server.go

We've been running with this in production for a long while now, and it simplifies on-prem setup as well (only DNS entry / load balancer endpoint needed).

Enable grpc over http by default

---

enterprise/server/remote_execution/executor/executor.go
enterprise/server/test/integration/remote_execution/remote_execution_test.go

This is causing some errors to not be retried even though they should be.
I think this logic is actually not needed. The protocol says:
```
// * `FAILED_PRECONDITION`: One or more errors occurred in setting up the
//   action requested, such as a missing input or command or no worker being
//   available. The client may be able to fix the errors and retry.
```
I think by "missing [...] command" they mean that the `Command` proto is missing or expired from cache, given the context clues of the sentence. The `Action` consists of `input_root_digest` and `command_digest`, which are both downloaded from cache. I think that's what they meant here, not the command's executable (arg0) not being found on disk after we successfully downloaded the inputs and command.

Remove FailedPrecondition error logic

---

cli/printlog/printlog.go

We do show the flag in the example but no doc currently.

cli: add --sort to help msg

---

app/invocation/invocation.css
app/invocation/invocation_action_card.tsx
app/invocation/invocation_action_tree_node.tsx

Render the output directories as expandable trees so that users could
explore their contents.
This PR is based on #6525 so we should only merge this PR after.

action_card: display output dirs as trees

---

enterprise/server/remote_execution/dirtools/BUILD
enterprise/server/remote_execution/dirtools/dirtools.go
enterprise/server/remote_execution/dirtools/dirtools_test.go

Switch from `dirHelper.IsOutputPath` to `dirHelper.ShouldUploadFile` to detect cases where the symlink was not explicitly declared as a command output, but a parent directory was.
Move this check outside of the `if` clause as we need to do this regardless of REAPI protocol version.
Use only the symlink file name instead of the full path as when we add the symlink to its parent directory.
Closes https://github.com/buildbuddy-io/buildbuddy-internal/issues/3347

dirtools: fix handling symlink inside output dir

---

app/invocation/invocation_timing_card.tsx

Windows support both backward and forward slash as valid separator.
Fix detecting the wrong name for the timing profile.

invocation_timing_card: add windows alt separator

---

.github/workflows/test-executor-linux-arm64.yaml
enterprise/server/test/integration/remote_execution/BUILD

* Reduce the effective `--local_test_jobs` from 16 to 8 - seems like remote_execution_test keeps crashing due to running too many jobs locally. We're already setting `size = "enormous"` so I'm not sure there's anything else we can do to reduce the local test concurrency, short of setting `tags = ["exclusive"]` which we don't really want since the individual test shards take kind of a long time :/
* Increase flaky_test_attempts from 2 to 3
* Remove `cpu:4` tag - I found this on stackoverflow or something a while back, but when testing it out it doesn't seem like it actually does anything in this case. In the timing profile, I was seeing 16 test actions running concurrently which wouldn't make sense if this actually worked, since the arm64 runner only has 16 cores.

Another attempt to deflake arm64 tests

---

WORKSPACE
WORKSPACE.bzlmod
deps.bzl

Added streaming codegen support in https://github.com/buildbuddy-io/protoc-gen-protobufjs/commit/51f3bb3b644b7306bb1c670a0089ee65c2f07154
(Also, feel free to leave comments on that commit if you don't like the generated API - will be happy to address them)

Upgrade protoc-gen-protobufjs to get server-streaming support

---

enterprise/server/execution_service/BUILD
enterprise/server/execution_service/execution_service.go
proto/BUILD
proto/buildbuddy_service.proto
proto/execution_stats.proto
server/buildbuddy_server/BUILD
server/buildbuddy_server/buildbuddy_server.go
server/capabilities_filter/BUILD
server/capabilities_filter/capabilities_filter.go
server/capabilities_filter/capabilities_filter_test.go
server/interfaces/interfaces.go

This will allow us to show live execution progress which is especially nice for workflow executions, where we'd like to show progress like "Resuming VM", "Executing" etc.
The RPC is purely a passthrough to the `Execution.WaitExecution` RPC.

Add WaitExecution to BuildBuddyService

---

cli/execute/execute.go
enterprise/server/remote_execution/executor/executor.go
enterprise/server/remote_execution/operation/BUILD
enterprise/server/remote_execution/operation/operation.go
enterprise/server/scheduling/priority_task_scheduler/priority_task_scheduler.go
enterprise/server/test/integration/remote_execution/BUILD
enterprise/server/test/integration/remote_execution/rbeclient/BUILD
enterprise/server/test/integration/remote_execution/rbeclient/rbeclient.go
enterprise/server/test/integration/remote_execution/remote_execution_test.go
proto/remote_execution.proto
server/util/rexec/BUILD
server/util/rexec/rexec.go

* Adds a `Publisher` interface that lets us publish the new progress updates concurrently with other progress updates. We need this because there's a loop in `ExecuteTaskAndStreamResults` which periodically publishes progress updates while the task is executing, but we also want to publish fine-grained progress events while this loop is ongoing.
* Publish the basic progress updates: pulling image, downloading inputs, executing, uploading outputs.
* Update `bb execute` to log debug messages with these progress updates.
* Some small refactoring in the `rexec` / `operation` packages.
TODO in future PRs:
* Publish progress for VM boot / snapshot resume.
* Don't publish "pulling image" status if we're not actually pulling an image.
Screenshot showing it in action (with `bb execute` for now as …

Add initial execution progress streaming impl

---

app/service/rpc_service.ts
deps.bzl
enterprise/app/api_keys/api_keys.tsx

Allows defining server-streaming RPC methods, and calling them like this:
```typescript
const stream = rpc_service.service.waitExecution(
// First argument: provide the request message object or fields (same as calling a unary RPC)
{ executionId },
// Second argument (new): provide stream handlers.
// All handlers are required
{
// Handle response message
next: (response) => { /* handle response */ },
// Handle error
// In most cases, we should check for network errors here and retry the stream w/ exponential backoff,
// in case of app restarts or a flaky network connection. In a later PR we can probably add some utils
// to make this easier.
error: (e) => { /* ... */ },
// Handle EOF (no more data on stream).
complete: () => { /* ... */ },
},
);
// ... later, e.g. componentWillUnmount(): …
```

Update RPC service to support server-streaming RPCs

---

enterprise/server/backends/redis_metrics_collector/BUILD
enterprise/server/backends/redis_metrics_collector/redis_metrics_collector.go
server/cache/config/config.go
server/remote_cache/hit_tracker/hit_tracker.go

The current default expiration times for the metrics collector are extremely generous, and can result in us getting alerts about redis cache usage. This happens especially when users are running a lot of invocations that only use us as the cache without sending us build events, as we can't manage the lifetime of those scorecards and counts in any way other than by allowing them to expire when they hit their ttl, since we have no idea when the related invocation is over.

Add flags to make metrics collector expiries configurable

---

server/remote_cache/hit_tracker/hit_tracker.go

We also create `/misses` counts in the cache if we aren't using detailed stats, so clean those up as well.

Also delete cache misses on cache stat clean-up

---

enterprise/server/cmd/ci_runner/main.go
enterprise/server/test/integration/ci_runner/ci_runner_test.go
enterprise/server/workflow/service/service.go

**Related issues**: Fixes https://github.com/buildbuddy-io/buildbuddy-internal/issues/3332#event-12660456383

Handle timeouts with ExecuteWorkflow API better

---

server/config/BUILD
server/config/config.go
server/util/flag/BUILD
server/util/flag/flag.go
server/util/flagutil/common/common.go
server/util/flagutil/flagutil.go
server/util/flagutil/types/BUILD
server/util/flagutil/types/autoflags/BUILD
server/util/flagutil/types/autoflags/autoflags.go
server/util/flagutil/types/autoflags/autoflags_test.go
server/util/flagutil/types/autoflags/tags/BUILD
server/util/flagutil/types/autoflags/tags/tags.go
server/util/flagutil/types/types.go
server/util/flagutil/types/types_test.go

Make tags extensible without needing to special-case each new tag type that needs to modify methods.
Go `flag.Value`s need to be able to produce accurate string forms of their zero values even when the instance is nil because of how they are used in `flagset.Usage`:
https://cs.opensource.google/go/go/+/refs/tags/go1.22.1:src/flag/flag.go;l=642-644
This means if we are wrapping a value, we need to capture the type of the value in a type parameter of the wrapping type. Unfortunately, that means that if we want the `Tag` function of a tag we pass in to the `New` or `Var` functions would need to have a type parameter as well if we needed them to wrap the flag value themselves, resulting in the awkward and repetitive:
```go
var foo = autoflags.New(flag.CommandLine, "foo", Foo{}, …
```

Rework flag tags to allow for easier extensibility

---

app/invocation/invocation_action_card.tsx

The queue timestamp could be after the initialization timestamp when the
Executor experience local clock drift vs the scheduler.
For this reason, some of our action timeline duration has been showing
up as negative value when we take the difference between 2 phases
timestamps that were taken on 2 different machines.
With the negative duration, our rendering would try to create elements
with this CSS.
```javascript
style: {
flex: `${negativeValue} 0 0`,
backgroundColor: "rgba(0, 0, 0, .1)"
}
```
which is an invalid initial value for `flex`. Because of this, React
rendered the element without `flex`, which result in wrong offset being
shown in the Action's timeline.
Ensure that duration values never goes negative to avoid this rendering
issue.
Closes …

action card: fix negative timeline duration

---

app/invocation/BUILD
app/invocation/execution_status.tsx
app/invocation/invocation.tsx
app/invocation/invocation_action_card.tsx
app/invocation/invocation_execution_card.tsx
app/invocation/invocation_execution_table.tsx
app/invocation/invocation_execution_util.tsx

Starting with the action page mostly as a proof of concept because it's easier to test than workflows and is maybe somewhat useful for larger actions. It will be more interesting to show this info on the queued invocation page (for workflow / remote bazel invocations).
Screen recording of an execution with an artificial 8s delay at the beginning of ExecuteTaskAndStreamResults + 750ms delay when transitioning between each execution state (otherwise the updates go by too quickly...) (also the "Unknown" execution status should probably be "Queued", need to fix that separately)
https://github.com/buildbuddy-io/buildbuddy/assets/2414826/d76dd269-d966-48a9-b51e-e30696f142be

Stream execution progress to the action page

---

app/invocation/cache_requests_card.tsx

Right now we show AC Misses by default, which is cool - but often empty.
For the uninitiated, this often leads folks to believe there were no cache requests for the invocation.
With this change, we'll show all requests by default, and let users scope them down to AC misses or CAS reads or whatever they're interested in looking at.

Default cache requests card to showing all

---

enterprise/server/remote_execution/executor/BUILD
enterprise/server/remote_execution/executor/executor.go
server/util/metricsutil/BUILD
server/util/metricsutil/metricsutil.go

The "Action stage durations" chart cardinality is too high and makes it slow to load. A single query loads over 300K individual timeseries from the DB.
Restricting to just prober group IDs should fix this (we want to split out prober latency to keep the prober latency chart working). If we need to query by other group IDs, we can use Clickhouse instead.

Restrict group_id label cardinality

---

enterprise/server/remote_execution/runner/runner.go

**Related issues**: https://buildbuddy-corp.slack.com/archives/C0495TM9UUE/p1715892089321979

Increase runner recycle timeout, so we can save snapshots with large resource requests

---

enterprise/server/scheduling/task_leaser/task_leaser.go

This is a follow-up from https://github.com/buildbuddy-io/buildbuddy/pull/6507 which was closed.
There was no race condition in that original PR because we were holding a mutex before sending anything on the stream. However, there is a separate issue where `pingServer` could potentially try to send a message on the stream after `Close()` was called. In practice, this likely just adds noise to logs, but I figured it would be nice to fix.
Also fix a small bug that the short-circuiting check in `Close()` was not actually short-circuiting, though in practice we never actually hit this codepath because we only Close once.

Avoid sending task keepalive ping after stream is closed

---

app/invocation/invocation.css
app/invocation/invocation_action_card.tsx

Render the command's expected outputs so that users can compare them
against the actual outputs in the ActionResult.
Base on https://github.com/buildbuddy-io/buildbuddy/pull/6545

invocation_action_card: render expected outputs

---

enterprise/app/trends/cache_chart.tsx
enterprise/app/trends/drilldown_page.tsx
enterprise/app/trends/percentile_chart.tsx
enterprise/app/trends/trends_chart.tsx
package.json
yarn.lock

Updates deps so that we can use a secure version of `semver`
**Related issues**: https://github.com/buildbuddy-io/buildbuddy/security/dependabot/127

Update deps for dependabot

---

app/invocation/invocation_action_card.tsx

In #6576, we made sure that all duration in the Timeline phases are
non-negative when time drift happens.
However, because the total duration is still being calculated by taking
the difference between the first event and last event, which is
inaccurate because the first event timestamp could be after the second
event timestamp due to drift. As the total duration is shorter than it
should be, it's possible for the `offset% + event%` value to be
higher than the actual total duration (100%). This causes the last bar of
the timeline, which is calculated with `100% - (offset% + event%)`, to
have a negative value. This prevents `flex` from not being rendered in
the div's style due to invalid initial value, causing strange offset.
Apply several fixes to mitigate the issue:
- Fix total duration …

action card timing: ensure the min css value

---

enterprise/server/hostedrunner/hostedrunner.go

You can set it like this: `bb remote --env=REPO_TOKEN=XXX test //...`
This would let us support gitlab with remote bazel: https://buildbuddy-corp.slack.com/archives/C0495TM9UUE/p1715880018594729

[RB] Read repo access token from env if set

---

app/compare/BUILD
app/compare/compare.css
app/compare/compare_invocations.tsx
app/root/root.css
app/root/root.tsx
enterprise/app/root/root.tsx

Adds tabs to the comparison view (starting with just invocation details and flags).
Will add tabs execution log in a follow-up.
Also fixes up some minor issues I found while testing in dev.

Add tabs to comparison view

---

enterprise/server/remote_execution/container/BUILD
enterprise/server/remote_execution/container/container.go
enterprise/server/remote_execution/containers/bare/BUILD
enterprise/server/remote_execution/containers/bare/bare.go
enterprise/server/remote_execution/containers/docker/docker.go
enterprise/server/remote_execution/containers/firecracker/firecracker.go
enterprise/server/remote_execution/containers/podman/BUILD
enterprise/server/remote_execution/containers/podman/podman.go
enterprise/server/remote_execution/containers/podman/podman_test.go
enterprise/server/remote_execution/containers/sandbox/BUILD
enterprise/server/remote_execution/containers/sandbox/sandbox.go
enterprise/server/remote_execution/runner/BUILD
enterprise/server/remote_execution/runner/runner.go
enterprise/server/remote_execution/runner/runner_test.go
enterprise/server/test/integration/podman/podman_test.go

Refactor container provider args so that we can add new optional params without every container implementation having to handle the new params. (I want to add `*operation.Publisher` to these args, but only Firecracker will be using it). 
These args are all truly optional so a struct seems better than using required positional args here (which force callers to consider the new args). For example, the Bare container implementation doesn't look at any of these struct fields.

Refactor container provider args

---

app/invocation/invocation.css
app/invocation/invocation_target_group_card.tsx
app/root/root.css

This changes adds a "load all" button to the targets card.
It also improves copy targets behavior in two ways:
1. It shows a confirmation checkbox icon when copy is complete
2. It calls "load all" before initiating the copy so all targets are copied (not just the ones visible on the first page).

Add "load all" targets button and fix up copy behavior 

---

enterprise/server/raft/store/store.go
enterprise/server/raft/store/store_test.go

When we decide whether a node is a zombie or not in raft store, currently we
only check whether this node is a member of the cluster and whether there is
a range on the store. 
It misses a case where when a replica is removed from raft
cluster when the store is offline; so when the store restarted, the range
descriptor it loaded from the store is out of date and it cannot get the udpated
info from raft cluster because it's not longer a member of the cluster. 
In order to clean up this type of zombie nodes, we need to consult meta range 
through the sender; and if range descriptor from the meta range doesn't contain 
the replica, we will then clean it up.
Added a unit test to test the zombie node is cleaned up for the above scenario.

[raft] check meta range when determine whether a node is a zombie

---

enterprise/server/raft/store/store.go

**Related issues**: https://github.com/buildbuddy-io/buildbuddy-internal/issues/3409

[raft] skip the cache to get the up-to-data meta range when determine if a node is a zombie

---

enterprise/server/raft/driver/driver.go
enterprise/server/raft/store/store.go

Occasionally, driverQueue.Start() is called after we call driverQueue.Stop().
When this happens, store.Stop() hangs s.eg.Wait() because driver.Start() doesn't
return. For example: https://buildbuddy.buildbuddy.io/invocation/a0dd0b7c-29f1-47ee-be81-dab38c3ac26c

[raft] fix occasional timeout in store_test

---

app/format/format.tsx
app/format/format_test.ts

This should help avoid things being rendered as `0.543KB`.

format: render 0.100KB as 100B

---

enterprise/server/raft/store/BUILD

**Related issues**: https://github.com/buildbuddy-io/buildbuddy-internal/issues/3415
This fixed the "bind: address already in use" issue.

[raft] add block-network tag to raft/store_test

---

enterprise/server/composable_cache/BUILD
enterprise/server/composable_cache/composable_cache_test.go
enterprise/server/raft/store/BUILD
enterprise/server/raft/store/store_test.go
enterprise/server/remote_execution/platform/BUILD
enterprise/server/remote_execution/platform/platform_test.go

**Related issues**: https://github.com/buildbuddy-io/buildbuddy-internal/issues/3415
flag.Set doesn't restore the value to default while flags.Set does during
cleanup phase.

use flags.Set(t,...) instead of flag.Set in tests

---

enterprise/server/raft/store/store_test.go

1. NewStore only needs to return TestingStore, we can access nodehost
through TestingStore
2. add a function to makeNodeGRPCAddressMap to make it easier to create
the map when we bring up shards.
3. use require.NoError instead of t.Fatalf when appropriate

[raft] refactor store test

---

enterprise/server/raft/store/BUILD
enterprise/server/raft/store/store.go
enterprise/server/raft/store/store_test.go
enterprise/server/raft/txn/txn_test.go

We set the zombie scan interval to 100ms when testing zombie clean up logic.
This can cause the test to be flaky because the zombie detector comes along when
we are in the middle of starting the shards in the test.

[raft] pass fake clock in test

---

enterprise/server/usage/usage.go
server/tables/tables.go

Went with GB-usec as the units which will let us represent 2.5 million GB-hours for each usage row, which seems plenty.

Add usage column for memory usage

---

enterprise/server/raft/store/store.go

If zombie detector runs in the middle of bringup.StartShard(..) it can
incorrectly delete a shard. To avoid this problem, we only delete the node if it
is dead for a certain period of time.

[raft] check whether a node is zombie again after a minute before removal

---

server/util/rlimit/rlimit.go

This gets logged every time I run `bb` and feels a bit unnecessary.

Remove rlimit log message

---

enterprise/server/hostedrunner/hostedrunner.go
proto/runner.proto

This will make it easier to add support to the remote runner API for new flags that are added to the ci_runner (Ex. `git_fetch_depth` or `git_fetch_depth`). Currently, we have been adding an explicit field to the RunnerRequest for each field

[ci_runner] Add support to pass flags directly to the runner

---

server/util/flag/flag.go
server/util/flagutil/common/common.go
server/util/flagutil/types/autoflags/BUILD
server/util/flagutil/types/autoflags/autoflags_test.go
server/util/flagutil/types/autoflags/tags/BUILD
server/util/flagutil/types/autoflags/tags/tags.go
server/util/flagutil/types/autoflags/tags/tags_test.go
server/util/flagutil/yaml/yaml.go

Added a `Hidden` tag for flags, allowing us to specify flags that will not show up in docs or usage for our internal use only.
As the way we handle the `Hidden` tag closely mirrors the `Secret` tag, it made sense to change both of them to be easier to use (specifically, handling unwrapping within the TaggedFlagValue instead of wherever we want to test to see if a flag value is secret or hidden.
Added tests.
The tests revealed that empty maps caused problems with the yaml marshalling (specifically, we could end up with a pair of empty curly braces). This made the `Hidden` tests fail, so adjusted how we handle empty maps in `yaml.go`.
**Related issues**: Fixes buildbuddy-io/buildbuddy-internal#2804

Add hidden tag for flags

---

app/invocation/invocation_action_card.tsx

If we don't have `lastOperation` (the last live-streamed update) but we do have an ExecuteResponse (the final response fetched from cache) then we can safely say that the execution is "Completed" rather than "Unknown."

Fix displayed execution status when we have an execute response but not a live-streamed update

---

cli/cmd/bb/bb.go

**Related issues**: Fixes https://github.com/buildbuddy-io/buildbuddy-internal/issues/3428

cli: don't show picker when there are args after '--'

---

cli/fix/fix.go
cli/fix/golang/BUILD
cli/fix/golang/golang.go
cli/fix/language.go

Right now only populates it if it doesn't exist in the MODULE.bazel file already. In the future we can improve this to merge with existing `use_repo` rules.

Populate `use_repo` in MODULE.bazel with `bb fix`

---

enterprise/server/raft/store/store_test.go

When using t.Failf, it's hard to locate the failure message in test log.

[raft] store_test: use require.Failf instead of t.Fatalf

---

enterprise/server/cmd/ci_runner/main.go

Currently, we only configure the git repo when initializing a clean runner. This means if we change the default config, users will have to invalidate their snapshots to pull in the changes. This PR changes the runner to always explicitly configure the repo at the beginning of the run

[ci_runner] Always configure the git repo

---

cli/tooltag/tooltag.go

This would let us know which version of BB was used via BES and help
troubleshooting issues easier.

cli: add version to tool_tag

---

enterprise/server/workflow/service/service.go

The "target repo" terminology doesn't make sense for the ExecuteWorkflow API or remote bazel, so I removed it from the ExecuteWorkflow API. I forgot to update these references to use the pushed repo URL instead

[ci_runner] Fix using incorrect url to report github statuses for

---

enterprise/server/cmd/ci_runner/main.go
enterprise/server/test/integration/ci_runner/ci_runner_test.go

The `--depth` option is sticky across fetching the same branch. So if I fetch `master` in one snapshot run with `--depth=1`, in a future snapshot run I'll have to explicitly set `--unshallow` if I want it to fetch the whole git history. *shakes fist at git* 

[ci_runner] Explicitly pass --unshallow flag when attempting to fetch full git history

---

enterprise/server/remote_execution/containers/sandbox/BUILD
enterprise/server/remote_execution/containers/sandbox/sandbox.go

The mac builds are failing : https://buildbuddy.buildbuddy.io/invocation/54310d19-fbf3-416b-9405-8b419fb7eeab

Fix build errors from unused import

---

enterprise/server/cmd/server/BUILD
enterprise/server/cmd/server/main.go
enterprise/server/registry/BUILD
enterprise/server/registry/registry_server.go

Disabled by default.
For now, this simply proxies requests to the BCR.

Add simple bzlmod registry server

---

enterprise/server/raft/bringup/bringup.go
enterprise/server/raft/client/client.go
enterprise/server/raft/leasekeeper/leasekeeper.go
enterprise/server/raft/rangelease/rangelease_test.go
enterprise/server/raft/store/store.go
enterprise/server/raft/testutil/testutil.go
proto/raft.proto

**Related issues**: https://github.com/buildbuddy-io/buildbuddy-internal/issues/3452
Store CreatedAt instead of ExpiredAt in Session. This allows more flexibility when we want to change the TTL of the session.
Also use *sessionLifetime directly instead of pass it into client session to make creation methods simpler.

[raft] store createdAt instead of expiredAt in Session

---

enterprise/server/raft/bringup/bringup.go
enterprise/server/raft/client/client.go
enterprise/server/raft/leasekeeper/leasekeeper.go
enterprise/server/raft/rangelease/rangelease_test.go
enterprise/server/raft/rbuilder/rbuilder.go
enterprise/server/raft/replica/replica.go
enterprise/server/raft/replica/replica_test.go
enterprise/server/raft/store/store.go
enterprise/server/raft/testutil/testutil.go
proto/raft.proto

**Related issues**: https://github.com/buildbuddy-io/buildbuddy-internal/issues/3452
Add DeleteSessions Request to delete all sessions created before a timestamp.
raft.Store can send a sync propose at an interval to delete sessions created
before a timestamp. 
We can achieve the same thing by using a scan + direct
delete, but the downside is that scanRsp can potentially return a lot of
entries; and there is one more round trip.

[raft] Add DeleteSessions raft command

---

enterprise/server/cmd/ci_runner/main.go

I realized I was using a logger that logs to the executor, but is not shown in the UI

[ci_runner] Fix using wrong log

---

enterprise/server/backends/pubsub/pubsub.go

When logging errors, ignore `context.Canceled` which also matches the error checks later on in the file.

Don't log stream error if context is canceled

---

enterprise/server/cmd/ci_runner/main.go

Publish the workspace status sooner, but only if `commit_sha` is known. Otherwise, wait until we sync the repo (to get the resolved HEAD commit SHA), but log a warning.
The warning focuses on the reproducibility benefits (making sure the build happens at an exact commit SHA), even though this PR is focused on the UX benefit of showing results in the UI sooner. I figured the reproducibility benefit might be a better selling point for getting people to set the commit_sha.
---
(Original context from https://github.com/buildbuddy-io/buildbuddy/pull/6529)
WorkspaceStatus is one of the events that prevents us from writing the Invocation row to the DB (due to the code [here](https://github.com/buildbuddy-io/buildbuddy/blob/a5f5c0be34c89dbaa82a913977f5dec8feee0898/server/build_event_protocol/build …

Publish workflow invocation workspace status event sooner (take 2)

---

tools/metrics/docker-compose.grafana.yml
tools/metrics/grafana/grafana.go
tools/metrics/grafana/provisioning/local/datasources/datasources.yml

When passing `-kube` we need to target VictoriaMetrics, not prometheus.
Also fix a few other small issues:
- Don't generate `dashboards.bzl` if there is an error processing dashboards (otherwise the file names list may be incomplete)
- Make VM the default datasource in the datasources config

Fix local grafana dashboard k8s mode

---

proto/scheduler.proto

Allow differentiating between user-reserved memory/CPU vs. resources that we determined using our automatic task sizer.

Annotate explicitly requested resources in task size proto

---

app/invocation/BUILD
app/invocation/invocation_action_card.tsx
app/util/BUILD
app/util/rpc.ts
enterprise/server/backends/pubsub/pubsub.go
proto/BUILD
server/util/status/BUILD
server/util/status/status.go

If an execution stream no longer exists (e.g. if the execution happened a long time ago), then `WaitExecution` returns a pubsub error saying that the stream is not found. Check for this error in the UI and just ignore it, displaying an "Unknown" execution status instead (or the status from the cached ExecuteResponse if it hasn't expired from cache yet).
**Related issues**: Fixes https://github.com/buildbuddy-io/buildbuddy-internal/issues/3473

Don't show error in the UI when execution stream is not found

---

server/build_event_protocol/build_event_handler/build_event_handler.go

In-progress workflow invocations are rendering with a blank invocation title (i.e. missing the workflow action name) because we don't explicitly mark WorkflowConfigured as one of the required "starting" build events before writing the invocation metadata row to the DB. This PR fixes that.
This bug was introduced by https://github.com/buildbuddy-io/buildbuddy/pull/6691 which moved the WorkspaceStatus event earlier in the build event stream. Turns out we are unintentionally depending on WorkspaceStatus to be published after the WorkflowConfigured event.

Fix missing workflow action name for in-progress workflows

---

buildbuddy.yaml

**Related issues**: https://github.com/buildbuddy-io/buildbuddy-internal/issues/3480

disable raft/txn:txn_test on mac CI

---

enterprise/server/remote_execution/dirtools/dirtools.go
enterprise/server/remote_execution/dirtools/dirtools_test.go
enterprise/server/remote_execution/workspace/workspace.go

While looking at `NewDirHelper` constructor, it took me a while to figure out that the `outputDirectories` and `outputPaths` parameters are not just direct passthroughs from `command.GetOutputDirectories()` and `command.GetOutputPaths()` respectively.
Instead, every caller of `NewDirHelper` is expected to write some boilerplate code to adapt the old-style `output_directories`/`output_files` into a new-style `output_paths` input.
It took me a while to realize this, and I spent a lot of time confused about why we only needed to call `IsOutputPath` in order to determine whether a directory needed to be uploaded, rather than `IsOutputPath || IsOutputDirectory || IsOutputFile`.
So, instead of having the caller adapt these fields, do it internally. To me, this is a lot more clear, since it …

Move output_paths migration boilerplate to NewDirHelper, instead of its caller

---

WORKSPACE
WORKSPACE.bzlmod

This bundle is a superset of the previous bundle with CA certs that expire far into the future.

Switch to new AWS RDS CA bundle.

---

MODULE.bazel
WORKSPACE

go1.22.4 (released 2024-06-04) includes security fixes to the archive/zip and net/netip packages, as well as bug fixes to the compiler, the go command, the linker, the runtime, and the os package. See the [Go 1.22.4 milestone](https://github.com/golang/go/issues?q=milestone%3AGo1.22.4+label%3ACherryPickApproved) on our issue tracker for details.

gosdk: upgrade to 1.22.4

---

enterprise/server/raft/client/BUILD
enterprise/server/raft/client/client.go
enterprise/server/raft/client/client_test.go
enterprise/server/raft/replica/replica.go
enterprise/server/raft/replica/replica_test.go
enterprise/server/raft/store/store_test.go

**Related issues**: https://github.com/buildbuddy-io/buildbuddy-internal/issues/3452
write tests for session, and fix a few things:
- Before -> After when check whether to refresh
- stockSession.index + 1 == reqSession.index is too strong a condition. When a session is shared by multiple ranges, this cannot be guaranteed. Relax this check
- Relax the mutex in SyncProposeLocal. We only need to make sure that one SyncProposeLocal is run per range per session at the same time; instead of one SyncProposeLocal globally. Performance improvement goes from 347409 ns / op -> 210624 ns/op

[raft] write some tests; fix some bugs

---

enterprise/server/raft/client/BUILD
enterprise/server/raft/client/client.go
enterprise/server/raft/client/client_test.go
enterprise/server/raft/leasekeeper/leasekeeper.go
enterprise/server/raft/replica/replica.go
enterprise/server/raft/replica/replica_test.go
enterprise/server/raft/store/BUILD
enterprise/server/raft/store/store.go
enterprise/server/raft/store/store_test.go
enterprise/server/raft/testutil/BUILD
enterprise/server/raft/testutil/testutil.go
enterprise/server/raft/testutil/testutil_test.go
enterprise/server/raft/txn/txn_test.go

**Related issues**: buildbuddy-io/buildbuddy-internal#3452
Initiate cleanup sessions in raft/store.
Use the current goroutine that scans the leased replica, and queue tasks to
delete sessions.
Use a rate limiter to make sure we are not delete sessions for all replicas at
once.
Record the time when we last delete the sessions and skip if we deleted the
sessions within SessionLifetime().

[raft] clean up expired sessions

---

deps.bzl
server/util/bazel/BUILD

These were use for old probers that I deleted a while ago.

Remove Bazel 6.0.0 binaries from deps.bzl

---

enterprise/server/registry/BUILD
enterprise/server/registry/github_registry.go
enterprise/server/registry/registry_server.go

This allows you to use a github repo directly as a module provided it has a `MODULE.bazel` file (we could even lift that restriction, but keeping it simple for now).
Depending on the BuildBuddy repo at a commit sha (recommended, since the others can get stale):
```
bazel_dep(name = "buildbuddy", version = "github.buildbuddy-io+3b0abcc3d478b7a29ee7550eab36271076fff40c")
```
Depending on a tag:
```
bazel_dep(name = "buildbuddy", version = "github.buildbuddy-io+v1.0.0")
```
Depending on a branch:
```
bazel_dep(name = "buildbuddy", version = "github.buildbuddy-io+release_123")
```
Depending on head:
```
bazel_dep(name = "buildbuddy", version = "github.buildbuddy-io")
```

Support using github as a module backend

---

enterprise/server/registry/BUILD
enterprise/server/registry/npm_registry.go
enterprise/server/registry/registry_server.go

This allows you to use a npm package directly as a module.
Depending on an unscoped npm package at a version:
```
bazel_dep(name = "docusaurus", version = "npm+1.14.7")
```
Depending on a scoped npm package at a version:
```
bazel_dep(name = "docusaurus_core", version = "npm.docusaurus+3.4.0")
```

Support using npm as a module backend

---

codesearch/cmd/cli/cli.go
codesearch/index/BUILD
codesearch/index/token.go
codesearch/server/server.go

- Perf: Use sparse set for trigrams and smaller buffers for lang/mimetype detection
- Tweak max file length down

Minor tweaks to improve codesearch indexing performance a lot

---

server/buildbuddy_server/buildbuddy_server.go

Siggi this is for you primarily -- if you set auth appropriately you can shove whatever you want into namespace.

Allow clients to use a custom namespace within their grp

---

enterprise/server/cmd/ci_runner/main.go

This seems to be causing `git gc --auto` to run in the background, which prevents us from running `rm -rf .git` in the case where we fail to sync the repository and need to sync from scratch.
If we need to run `git gc` in the future, we can run it manually after all actions complete.
Separately, https://github.com/buildbuddy-io/buildbuddy/pull/6756 should help us debug why the sync is failing in the first place.

Disable git automatic gc

---

cli/remotebazel/BUILD
cli/remotebazel/remotebazel.go
enterprise/server/test/integration/remote_bazel/remote_bazel_test.go

Processing bazelrcs and running plugins should happen on the remote runner, not locally

[RB] Stop explicitly expanding bazelrcs and running plugins

---

enterprise/server/remote_execution/containers/ociruntime/BUILD
enterprise/server/remote_execution/containers/ociruntime/ociruntime.go
enterprise/server/remote_execution/containers/ociruntime/ociruntime_test.go

Wire up `interfaces.Stdio` with the option of discarding all output, which is prevents hanging in `create` as `sleep` never closes its inherited stdout/stderr.

[ociruntime] Fix stderr/stdout/stdin handling

---

tools/prettier/prettier.sh

I use zsh as a shell, and it does not have the mapfile command 

Fix prettier for zsh

---

enterprise/server/cmd/ci_runner/main.go

The env var KYTHE_DIR was not being set if kythe was already checked out. Whoops!

Always set KYTHE_DIR env var

---

app/invocation/workflow_rerun_button.tsx

Invalidating workflow snapshots was broken by this [PR](https://github.com/buildbuddy-io/buildbuddy/pull/6687/files)
Also add more info on how to invalidate all workflow snapshots
**Related issues**: https://github.com/buildbuddy-io/buildbuddy-internal/issues/3481#event-13051953877

Improve error message for failures when invalidating a workflow snapshot

---

enterprise/server/remote_execution/dirtools/dirtools.go

While reading this code, I found the fileToUpload struct to be confusing because it can represent either a file or a directory. 
This PR adds a separate dirToUpload struct and simplifies the code by removing the conditional logic checking whether a fileToUpload is a file or directory.

Split fileToUpload struct into separate file and dir structs

---

enterprise/server/raft/store/store.go

1. Use s.log instead of log
2. Add a log line when we start to shut down. This helps debugging debugging
stuck liveness.Release()

[raft] logging in store.Stop()

---

enterprise/server/raft/driver/driver.go
enterprise/server/raft/leasekeeper/leasekeeper.go
enterprise/server/raft/nodeliveness/nodeliveness.go
enterprise/server/raft/nodeliveness/nodeliveness_test.go
enterprise/server/raft/rangelease/rangelease.go
enterprise/server/raft/rangelease/rangelease_test.go
enterprise/server/raft/store/store.go
enterprise/server/raft/store/store_test.go

**Related issues**: https://github.com/buildbuddy-io/buildbuddy-internal/issues/3496
Sometimes liveliness.ensureValidLease got stuck, and as a result it makes
liveliness.Release stuck waiting for ensureValidLease release the lock

[raft] pass context into nodeliveness.ensureValidLease()

---

codesearch/cmd/cli/cli.go
codesearch/query/regexp_query.go
codesearch/server/server.go
codesearch/types/types.go

Adds a configurable CustomSnippet method and uses it in the server (but not the cli) to return more context (1 line in either direction) around match snippets.

Make the snippets a little longer

---

app/invocation/BUILD
app/invocation/invocation.tsx
app/invocation/invocation_coverage_card.tsx
app/invocation/invocation_model.tsx
app/invocation/invocation_tabs.tsx

We can get fancier with the rendering later.
Screenshot:

Add simple invocation-level coverage tab / report

---

enterprise/server/raft/nodeliveness/nodeliveness.go
enterprise/server/raft/nodeliveness/nodeliveness_test.go
enterprise/server/raft/rangelease/rangelease_test.go
enterprise/server/raft/store/store.go

**Related issues**: https://github.com/buildbuddy-io/buildbuddy-internal/issues/3496
On shutdown, liveness.Release() got stuck because liveness.ensureValidLease()
kept the lock and stuck in the renew loop; but ensureValidLease() could not
finish b/c two other stores are already shut down.

[raft] stop liveness.renewLease() on context cancel

---

server/util/db/db.go

Turns out it was the MySQL driver that was falling back to prepared statements, not GORM.
If the MySQL driver received a query with arguments, it forced the caller to use a prepare/execute combination which requires two round trips. MySQL has an option called 'interpolateParams' that does the interpolation client side in the driver instead of relying on the server. 

Enable mysql query interpolation.

---

app/compare/BUILD
enterprise/app/code/code.css
enterprise/app/code/code.tsx

Right now the loading state and a lot of error states for the code viewer just show the "Welcome to BuildBuddy Code" message.
This PR improves that by showing a loading spinner during bytestream fetches and handles some error cases better by showing red toast.
Pulls coverage handling into a showLcov function to make it more similar to `showBytestreamCompare` and `showBytestreamFile`.
Also improves viewing coverage view without a GitHub link (prompts you to link GitHub).

Better loading state for code viewer

---

enterprise/app/codesearch/codesearch.css
enterprise/app/codesearch/codesearch.tsx

- stop showing the annoying error when no results are found
- show a placeholder if query is empty with some example searches
- show a chill no results found page if no results are found
- stop updating the q param on every keypress; only set it on search

Better empty states in codesearch UI

---

app/root/root.css

Oops - had meant to include this in https://github.com/buildbuddy-io/buildbuddy/pull/6774 but forgot to commit it before merging 
This is what the color of the pill looks like, but it would be for remote bazel

[RB] Change color of pill

---

enterprise/app/code/code.tsx

If you leave the page mid-loading, you don't want that loading state to be popped out of local storage the next time you visit the page.

Don't revive loading state from storage

---

app/invocation/invocation_overview.tsx

Right now when you view an invocation that's the child of a workflow, you breadcrumb looks like this:
`BuildBuddy > Builds > Workflow X > Invocation Y`
When you click on `Workflow X` you're taken to a workflow page that looks like this:
`BuildBuddy > Builds > Invocation X`
With this change, you'll get taken to a workflow page that looks like this instead:
`BuildBuddy > Builds > Workflow X`

Show invocation type in breadcrumb

---

app/invocation/suggestion_button.tsx

We currently show it for passing & failing workflows (because there's no bazel exit code) and the results aren't very good.

Don't show "Ask Buddy" for workflow invocations

---

enterprise/server/cmd/server/main.go
enterprise/server/registry/BUILD
enterprise/server/registry/registry_server.go
server/environment/environment.go
server/interfaces/interfaces.go
server/libmain/libmain.go
server/real_environment/real_environment.go

This makes things easier, because if we don't run it on its own port - we can use use the same endpoints we use for all of our other services instead of having to set up a new ingress, etc just for this.

Move registry server to our standard http mux

---

BUILD
buildfix.sh
tools/fix_go_deps.sh

This switch our script to use buildifier managed by Bazel instead of
relying on users to install buildifier on their host machine.

buildfix.sh: use buildifier managed by Bazel

---

enterprise/server/remote_execution/snaploader/snaploader.go
enterprise/server/remote_execution/snaploader/snaploader_test.go
proto/firecracker.proto

For snapshot-specific keys, _only_ include the snapshot ID in the key, leaving all other fields blank. This will make it possible to have a `--snapshot_id` arg to vmstart, which we can easily copy-paste from the UI, instead of needing to dig through executor logs.

Use a simpler key for snapshot-specific AC entries

---

buildbuddy.yaml

The linked bug https://github.com/buildbuddy-io/buildbuddy-internal/issues/958 seems to have gone away on its own, maybe due to a bazel fix.
**Related issues**: https://github.com/buildbuddy-io/buildbuddy-internal/issues/958

Remove --remote_download=toplevel from webdriver test invocation

---

app/invocation/BUILD
app/invocation/invocation_logs_model.tsx
config/buildbuddy.local.yaml
enterprise/config/buildbuddy.local.yaml
enterprise/config/test/buildbuddy.noauth.yaml
enterprise/config/test/buildbuddy.selfauth.yaml
enterprise/server/cmd/server/BUILD
enterprise/server/cmd/server/main.go
proto/buildbuddy_service.proto
proto/config.proto
server/build_event_protocol/build_event_handler/build_event_handler.go
server/buildbuddy_server/BUILD
server/buildbuddy_server/buildbuddy_server.go
server/capabilities_filter/capabilities_filter.go
server/environment/environment.go
server/eventlog/eventlog.go
server/real_environment/real_environment.go
server/static/static.go

- Publish a message on a pubsub channel (in Redis) whenever logs are updated
- Have clients read logs using the same 3s polling logic as today, except the polling happens on the server-side, and the server also subscribes to the pubsub channel (if available) to eagerly re-fetch the tail as soon as it is updated. The pubsub channel should be available except on OSS (for now) and possibly also during Redis restarts.
Demo (local terminal on right, BuildBuddy invocation page on left - note how the UI updates ~immediately)
https://github.com/buildbuddy-io/buildbuddy/assets/2414826/85056461-dcfb-43e0-b7c9-344531227076

Live-stream invocation logs

---

cli/remotebazel/remotebazel.go

Currently for remote `run`s, the generated binary will not be executed remotely, and will be fetched and run locally (See here for [implementation](https://github.com/buildbuddy-io/buildbuddy/blob/master/enterprise/server/cmd/ci_runner/main.go#L157)). Add a configurable flag, because for CI people may want it to be executed remotely

[RB] Support configuring whether to run targets on the local vs remote runner

---

enterprise/app/code/code.css
enterprise/app/code/code.tsx

Highlights query from url parameter.
Adds support for `commit` query parameter.
Makes the editor read only if url param is set. (We could change this later, or add an edit button to switch to edit mode).
Hides some unnecessary UI if query is set - like changes view & open PR button.

Add query support to code editor

---

.bazelrc
BUILD
MODULE.bazel
WORKSPACE
enterprise/server/remote_execution/containers/firecracker/BUILD
platforms/BUILD
toolchains/BUILD

The new toolchain produces binaries statically linked against musl.
Tested on `//cli` and `//enterprise/server/cmd/executor` from macOS.

bazel: Add a musl cross toolchain targetting Linux amd64/arm64

---

.github/workflows/release-cli.yaml

The current name looks like a workflow job ID rather than a workflow name, which had me confused for a second

Tweak CLI release workflow name

---

enterprise/server/scheduling/scheduler_server/scheduler_server.go
enterprise/server/scheduling/scheduler_server/scheduler_server_test.go
enterprise/server/scheduling/task_router/task_router.go
enterprise/server/scheduling/task_router/task_router_test.go
enterprise/server/test/integration/remote_execution/remote_execution_test.go
server/interfaces/interfaces.go

We'll be adding `CustomResources` in https://github.com/buildbuddy-io/buildbuddy/pull/6820 which should be a bit simpler to plumb through after this refactor is done.

Simplify executionNode by storing the whole ExecutionNode proto

---

enterprise/server/remote_execution/runner/runner.go
enterprise/server/test/integration/workflow/workflow_test.go
enterprise/server/workflow/service/BUILD
enterprise/server/workflow/service/service.go

This will make it easier to ship ci_runner changes to customers with self-hosted executors

[ci_runner] Modify Linux workflows to download the binary from the cache, rather than using the binary provisioned on the executors

---

enterprise/server/cmd/ci_runner/BUILD
enterprise/server/cmd/ci_runner/main.go

After running the action (and publishing the success/failure status for the outer invocation), attempt to save disk space by running `git gc` if disk usage exceeds 90%.

ci runner: try to reclaim disk space when usage is high

---

enterprise/server/cmd/ci_runner/BUILD
enterprise/server/cmd/ci_runner/main.go

Instead of gosigar, use `disk.DirUsage` which supports multiple platforms

Roll forward "ci runner: try to reclaim disk space when usage is high"

---

enterprise/server/raft/store/store.go
proto/raft.proto

When we are adding a new replica, we first add it as a non-voter, and when the
node catches up with other replcias, we promote it as a voter.

[raft] When adding a replica, add the node as a non voter first

---

server/build_event_protocol/build_event_handler/build_event_handler.go

This is a saner default for folks with large Bazel build logs.
In some cases, it will prevent OOM in self-hosted OSS BuildBuddy.
Also fixed a minor typo in the next line.

build_event_handler: chunk event log by default

---

deps.bzl

This new version of soci-store contains a couple of commits that I hope will address [ino reuse in newInodeWithID](https://github.com/containerd/stargz-snapshotter/issues/1594)
- go-fuse: [Add inode.Initialized() for checking if an inode has been initialized](https://github.com/hanwen/go-fuse/commit/dfe6a153c480d3f50af926ff9305ab34b123573c)
- soci-snapshotter: [Only reuse inos for nodes that are forgotten and initialized (actually).] (https://github.com/buildbuddy-io/soci-snapshotter/commit/a09a8130be41fc0d56b9a86bf69c8d850c2b2e59)

Bump soci-store binary version dependency to 0.0.15

---

proto/buildbuddy_service.proto
proto/config.proto
proto/target.proto
server/buildbuddy_server/buildbuddy_server.go
server/capabilities_filter/capabilities_filter.go
server/static/static.go
server/target/target.go

- add a time series query for target flake stats
- remove pagination from target stats query (just not worth it for now since the query already sorts)
- add repo param so that two repos can have the same targets without us getting crossed up.
- add a few extra pieces of info to flake samples.

update flake-related target queries to what we actually need.

---

enterprise/server/cmd/ci_runner/main.go

The CI runner image doesn't have a recent enough version of `git`: https://buildbuddy.buildbuddy.dev/invocation/3e19735b-975c-4436-9129-cd009d836dc2?role=CI_RUNNER&days=7&branch=master

Use `git gc --auto` instead of `git maintenance`

---

app/invocation/BUILD
app/invocation/invocation.css
app/invocation/invocation_artifacts_card.tsx
app/invocation/invocation_target_group_card.tsx
app/invocation/invocation_targets.tsx
app/root/root.css
app/target/BUILD
app/target/flaky_target_chip.tsx
app/target/target_flaky_test_card.tsx
app/target/target_test_cases_card.tsx
app/target/target_test_suite.tsx
app/target/target_v2.tsx
enterprise/app/root/root.tsx
enterprise/app/tap/BUILD
enterprise/app/tap/flakes.tsx
enterprise/app/tap/grid.tsx
enterprise/app/tap/grid_common.ts
enterprise/app/tap/grid_sort_controls.tsx
enterprise/app/tap/tap.css
enterprise/app/tap/tap.tsx
enterprise/app/tap/tap_empty_state.tsx
enterprise/app/trends/trends.css
enterprise/app/trends/trends_chart.tsx

- a page over by the test grid ui to see a table of flaky targets from the last 7 days.
- a click-through to a specific target to see sample flakes for that target
- a link on the target page to see recent flakes of a failing tests.
- a link on the invocation page to see recent flakes of any failing tests that are recently flaky
styles need a bit of love but geez this change is big and i'd rather get it on in dev before fixing it up.

UI for finding example flakes, flake history, etc.

---

app/invocation/invocation_logs_model.tsx

In some special cases, the server could send response without
next_chunk_id field set and cause our UI to trigger an infinite
recursion loop.
Handle the base case to break the loop early.

invocation_logs_model: handle fetchTail base case

---

enterprise/server/cmd/goinit/main.go
enterprise/server/remote_execution/containers/firecracker/firecracker.go
enterprise/server/remote_execution/containers/firecracker/firecracker_test.go
proto/firecracker.proto

`crun` doesn't appear to be fully compatible with a "hybrid" cgroup setup (v1+v2) - when running the OCI runtime tests on Firecracker, I'm getting the error `cgroups in hybrid mode not supported` ([invocation link](https://buildbuddy.buildbuddy.io/invocation/a3f929c0-f756-4cf0-89a7-ddb9e37b6407?target=%2F%2Fenterprise%2Fserver%2Fremote_execution%2Fcontainers%2Fociruntime%3Aociruntime_test&targetStatus=6)) which comes from the code [here](https://github.com/containers/crun/blob/f44da38333321335611d45638401e99f5f9548f2/src/libcrun/cgroup.c#L314-L326)
This PR adds a flag to only enable cgroup2 within the guest. Since modern distros have ditched the hybrid setup in favor of v2-only, I would like to enable this everywhere after some testing in dev with docker-in-firecracker, so I went with an …

firecracker: mount only cgroup v2 in the guest instead of hybrid v1+v2

---

enterprise/server/raft/rbuilder/rbuilder.go
enterprise/server/raft/sender/sender.go
enterprise/server/raft/store/store.go
enterprise/server/raft/txn/BUILD
enterprise/server/raft/txn/txn.go
enterprise/server/raft/txn/txn_test.go
proto/raft.proto

**Related issues**: https://github.com/buildbuddy-io/buildbuddy-internal/issues/3537
1. Pass RangeDescriptor instead of ReplicaDescriptor in txn statement. This allows us to try different replicas in txn.
2. Expose TryReplicas from sender, but allow the caller to specify how to make the header. In sender, we pass the range info into the header but in txn we just need to pass the replica.
3. Un-expose FinalizeTxn and DeleteTxn: they are only used internally.

[raft] try replicas in txn

---

enterprise/server/remote_execution/containers/ociruntime/BUILD
enterprise/server/remote_execution/containers/ociruntime/ociruntime.go
enterprise/server/remote_execution/containers/ociruntime/ociruntime_test.go
enterprise/server/util/oci/BUILD
enterprise/server/util/oci/oci.go

* Pull and extract image layers with `go-containerregistry`
* Pull concurrently with up to 8 goroutines
* For now, use `tar` to extract, using `--no-same-user` to avoid permissions issues
* Set up rootfs as an overlayfs mount

Add basic image support to OCI runtime isolation

---

server/util/clickhouse/clickhouse.go

Currently our main DB would leave a log like this after successfully
configured:
```
Successfully configured sqlite database
```
Provide the same for OLAP DB

enterprise/server: log OLAPDB is used

---

enterprise/server/remote_execution/containers/podman/podman.go

Looks like these "database is locked" can surface through multiple different podman exit codes.
This PR adds support for two more that we've witnessed in the wild, 125 and 127 (we previously only retried 126).

Add support for retrying locked database errors for more exit codes

---

server/target/target.go

there will probably still be quirks involving missing logs but wanted to do this first.
See buildbuddy-io/buildbuddy-internal/issues/3543

filter samples by the right set of statuses.

---

enterprise/server/auth_service/BUILD
enterprise/server/auth_service/auth_service.go
enterprise/server/auth_service/auth_service_test.go

For the period where we're just running the cache-proxy within our own GCP deployment or other deployments that we're comfortable sharing the JWT key with, we can use this to support remotely authenticating. At some point we will probably want to sign these differently, probably using RSA public/private keys, but I'll address that later.

Fill out the JWT field in AuthenticateResponse

---

enterprise/server/remote_execution/snaploader/snaploader.go

We probably should remove `instance_name` from the snapshot key proto, since the key is basically the "digest" part of the resource name, and the instance name is normally separate from the digest. But that will be a pretty big refactor, so just add the instance name back to the snapshot-specific key to hold us over until then.

Add instance name back to snapshot-specific key

---

enterprise/server/raft/driver/BUILD
enterprise/server/raft/driver/driver.go
enterprise/server/raft/driver/driver_test.go
enterprise/server/raft/storemap/storemap.go

It's difficult to set up different scenerios in store_test to test
driver logic. Therefore, we will use store_test to test the interaction
between the store and the queue, and basic placement logic.
Since it's complicated to choose and compare candidates, it's worthwhile
to test these logic seperately.
1. export storemap.CreateStoresWithStats
2. create two versions of compare functions: compare by score and
compare by score and id. We will use compareByStoreAndID when
sorting. In rebalancing, we need compareByScore.
3. change the return type of compare to int instead of float64 to make
things easier
4. add test to compare method and findNodeForAllocation and fix a bug in
compare method

[raft] driver: add tests to choose and compare candidates, and fix a bug in compare

---

enterprise/server/cmd/ci_runner/main.go

Should prevent the progress output from getting truncated unnecessarily.

Increase CI runner default PTY size

---

server/util/networking/BUILD
server/util/networking/networking.go

I need to make some additional changes to firecracker setup and it'll be much easier without having to extend the string parsing code.

Use netlink for retrieving route information instead of string parsing.

---

server/tables/tables.go
server/util/clickhouse/schema/schema.go

default value is false (i.e., not cached), which is effectively a no-op with prod.  there isn't a reasonable backfill path.

schema changes to store whether or not a test target was cached

---

enterprise/server/raft/driver/BUILD
enterprise/server/raft/driver/driver.go
enterprise/server/raft/driver/driver_test.go
enterprise/server/raft/storemap/storemap.go

**Related issues**: 
1. Add an interface IStoreMap, so I can fake it in the test for removal.
2. fix bugs in TestCandidateComparison
3. Fix bugs in compare method: 
- candidate with full disk is worse not better than candidate w/o full disk; should return negative number. 
- when the diff is relatively small compared to range count, return a positive/negative number instead of 0.
4. fix a bug when handling brand new replica id

[raft] driver test: add tests for finding replicas to remove

---

enterprise/server/remote_execution/containers/ociruntime/BUILD
enterprise/server/remote_execution/containers/ociruntime/ociruntime.go
enterprise/server/remote_execution/containers/ociruntime/ociruntime_test.go

Adds the usual optimizations to avoid excessive requests to the remote image registry:
* Implement `IsImageCached` so that `container.PullImageIfNecessary` can skip the call to `Pull` most of the time
* Dedupe pulls for the same image ref, since the executor would otherwise be making an excessive amount of requests to the registry when assigned several actions that need the same image within a short duration

OCI runtime: add standard image pull optimizations

---

enterprise/server/webhooks/github/github.go
server/interfaces/interfaces.go

Fixes an issue that we'd attempt to trigger workflows for forked repos that we can't access.

Handle repo not existing in GetFileContents

---

.github/workflows/deps.yaml

I don't think this has any actual impact / benefit in this case, but it's considered a best practice:
https://securitylab.github.com/research/github-actions-untrusted-input/#remediation

Store github workflow inputs in intermediate environment variables

---

enterprise/server/remote_execution/platform/platform.go
enterprise/server/remote_execution/runner/BUILD
enterprise/server/remote_execution/runner/runner.go
enterprise/server/remote_execution/runner/runner_linux.go

* Support `workload-isolation-type: oci`, behind flag `--executor.oci_enabled`
* For now, fall back to podman or docker if the action requires networking (`dockerNetwork != "off"`), since we don't yet have networking implemented. Once we implement networking, we can remove this fallback
* Was able to build the BB repo (after some small bugfixes, to come in a follow-up PR). It's very fast :fire: 

Wire up OCI runtime to executor

---

server/target/target.go

- only look at uncached test runs
- pre-filter to only success, flaky, failed, and timed out runs (i.e., ignore tool failures, skipped tests, etc. completely) when querying for "likely flakes".

couple of tweaks to speed up flakes queries a bunch.

---

tools/metrics/docker-compose.victoria-metrics.yml

Instead of logging an error every time scraping fails, only log once every minute. This way the logs are not as noisy, but we still get feedback as to whether VictoriaMetrics thinks the scrape targets are up or not.

Suppress scrape errors when not running certain scrape targets locally

---

enterprise/server/backends/pebble_cache/pebble_cache.go
server/metrics/metrics.go

We are running into issues where zombie table size gets huge. This can make
monitoring this metric easier.

[pebble cache] export zombie table count and size to prometheus

---

codesearch/cmd/cli/cli.go
codesearch/query/regexp_query.go
codesearch/server/server.go
codesearch/types/types.go

Prevent displaying the same line twice.

Dedupe region matches by line number

---

server/build_event_protocol/target_tracker/BUILD
server/build_event_protocol/target_tracker/target_tracker.go
server/build_event_protocol/target_tracker/target_tracker_test.go

this map is getting created no matter what--we can get the target from all the events we care about.

look up target objects for tracking by label instead of using parent event

---

codesearch/query/regexp_query.go
codesearch/searcher/searcher.go
codesearch/types/types.go

Ensure that there are snippets present, even for filter-only queries like `[lang:go]`. Also, make scoring of these queries faster by not doing wasted work.

Better support for filter-only queries

---

enterprise/server/workspace/BUILD
enterprise/server/workspace/workspace_service.go

Implemented it with a `workspace.use_blobstore` flag that allows you to chose if you want to use blobstore or the cache as a backend to prove (to both you and myself) that the API works with either backend.
My ideal longer term set up is:
- Workspace proto and current set of just workspace changes in blobstore
- Unchanged files from cache (with fallback to GitHub if not present in cache)
I looked into adding support for a TTL for the blobstore backend, but would need to make some blobstore API changes there - so added it as a TODO.

Implement workspace service backend

---

codesearch/cmd/cli/cli.go
codesearch/query/regexp_query.go
codesearch/searcher/searcher.go

- don't display filename field matches in the CLI, it shows lots of duplicates
- don't insert a fake region match unless the content part of the query was empty
- limit results correctly even if scoring is a no-op

Filter q and non-q results correctly

---

server/remote_cache/digest/digest.go
server/remote_cache/digest/digest_test.go

As the pre-content supporting sha384/sha512 remote_asset.
Related https://github.com/buildbuddy-io/buildbuddy/pull/6911

Add sha384/sha512 digest function

---

codesearch/query/regexp.go
codesearch/query/regexp_query.go
codesearch/query/regexp_query_test.go

Previously we were not expanding case (I broke this in a refactor). Fix this, and ensure it's tested.
Also, it was confusing that only "case:y" was a supported query atom but not "case:n" (the default). So if "case:(n|no)" is passed, handle that correctly, and add a test for this.
Also, remove some old debug logs.

Handle case:n and fix case expansion

---

enterprise/app/codesearch/codesearch.tsx

The parsedQuery field returned from the server contains the flags set on the regex. Because the regex formats are different between go and js, remove the go flags (since we set the js ones manually).

remove regex flags

---

cli/printlog/compact/BUILD
cli/printlog/compact/compact.go
cli/printlog/printlog.go

Bazel team has commented that the compact log file format could be
unoptimized for `bazel test //...` where test targets could introduce a
lot of files which cannot be deduplicated.
Provide a flag to inspect the raw content of the compact exec log
to help aid development of this log format.

cli/printlog: provide a --raw flag to print compact exec log

---

server/remote_cache/content_addressable_storage_server/content_addressable_storage_server.go
server/remote_cache/content_addressable_storage_server/content_addressable_storage_server_test.go

Writes are far more expensive than reads. They happen consistently (r=3), require a fsync, etc. For some workloads, we believe we're doing a lot of writes that are then wasted (never or rarely read).
Attempt to fix that by only doing writes with probability 1 in 10. If cached entries are requested a lot, they will soon be cached, and if not, we may avoid caching them at all.

Make tree cache writes probabalistic

---

.bazelrc

This was previously disabled on Windows because we were writing it to
`/tmp` and on Windows, there is not a fixed tmp path.
We have since switched the log path to our workspace and thus,
compatible with Windows.
Also changed the log to use the correct ZSTD extension, which is `.zst`.

.bazelrc: write exec log on Windows

---

server/remote_asset/fetch_server/fetch_server_test.go

As a follow up from #6911, provide a test to demonstrate cache misses on
subsequent FetchBlob requests where the digestFunc and the checksum
qualifier differ.
When this is fixed in the future, we should be able to flip the flag
accordingly.

fetch_server_test: demonstrate cache misses

---

server/tables/tables.go

This column was used to guarantee that we don't double-count when accumulating multiple usage collection periods (1 minute) into a single usage period row (1 hour). Since we want to go back to 1h usage periods, we need to bring back this column.

Bring back final_before_usec usage column

---

.gitignore

The file extension was changed in https://github.com/buildbuddy-io/buildbuddy/pull/6937/files

Fix .zst file extension in gitignore

---

server/remote_cache/content_addressable_storage_server/content_addressable_storage_server.go

We did this originally because there were bad trees cached. I've verified that we don't see any metrics with invalid_entry, so this seems safe to remove now, and will save some CPU being spent on proto serialization.

Don't re-verify cached trees at read time

---

enterprise/server/cmd/cache_proxy/cache_proxy.go
server/rpc/interceptors/BUILD
server/rpc/interceptors/interceptors.go
server/util/grpc_server/grpc_server.go

https://github.com/buildbuddy-io/buildbuddy/pull/6788 adds a new authenticator that remotely authenticates gRPC requests. But that relies on the auth headers being present in the outgoing RPC context at the time that the authenticator is invoked, which is not the case with the way this code is currently written. This PR re-shuffles the extra-interceptors installation so that these interceptors are run before the auth interceptor. It also adds a JWT-propagating interceptor so that executors can remotely authenticate using the remote authenticator.
Ultimately, we should probably switch this to something fancier like a builder, but for now this should suffice.

Install API-Key propagating interceptor prior to auth interceptor

---

server/rpc/interceptors/interceptors.go

Metadata can be large so copying the full thing can be costly. If we only need one key, we can just look for that key.

Don't make a full copy of metadata to extract a single key

---

codesearch/query/regexp_query.go
codesearch/query/regexp_query_test.go
codesearch/searcher/searcher.go

If you query for [Hello World case:y], we want to match docs that contain both "Hello" and "World".
If you query for ["Hello World" case:y], we want to match docs that contain the string "Hello World".

And query terms

---

codesearch/cmd/cli/cli.go
codesearch/index/index.go
codesearch/index/index_test.go

Before this CL,  a query which triggered the (:all) squery like [s3] would not return matches. This is because while the docs were returned, they had no field matches, so were not scored.
This CL fixes that.

Return all fields for (:all)

---

cli/download/download.go

Without this fix, we may try to seek on stdout, which is not allowed.

Fix seek /dev/stdout: illegal seek error

---

enterprise/server/cmd/executor/BUILD
enterprise/server/remote_execution/containers/podman/BUILD

The action is poisoned by the creation date of the files on disk.
Fix this by adding `--mtime` to the `tar` packaging command.
Unfortunately this flag is only available on linux version of `tar`, so
restrict the target to only be executed on Linux.
Also ensure that the subsequent image layers are only built lazily to
avoid any extra downloads on our workflows runner.

podman: make podman-static archive deterministic

---

server/remote_asset/fetch_server/fetch_server.go
server/test/integration/remote_asset/remote_asset_test.go

As we start to set
```golang
&http.Transport{
...
Proxy: http.ProxyFromEnvironment,
}
```
It's worth to note that http.ProxyFromEnvironment is initialized only
once and store the proxy result in the package level without a way to
reset it.
So testing this in fetch_server_test.go was not possible, unless we
write our test func at the very top of the file, or shard the test
enough so that each test func gets their own shard.
Instead, implement the test in our integration test setup.
Closes #6966

fetch_server: support http proxy

---

enterprise/server/certgenerator/certgenerator.go

In order to setup auto push for the bare metal cluster, GitHub actions need to be able to access the kubernetes cluster using service account credentials.
This change allows listed service accounts to obtain credentials and makes the SSH certificate generation optional if not requested.

Enable certificate generation for service accounts.

---

enterprise/server/remote_execution/execution_server/execution_server.go

**Related issues**: https://github.com/buildbuddy-io/buildbuddy-internal/issues/3588
Currently, we are allocating time.Timer in the for loop in loopAfterTimeout.

use time.Ticker in loopAfterTimeout in execution_server

---

enterprise/server/remote_execution/runner/runner.go

https://github.com/buildbuddy-io/buildbuddy/pull/6968 caused failures in `//enterprise/server/test/integration/workflow:workflow_test` due to the fact that the `String()` function of runner does an unprotected read of `runner.state` which may race with one of the function that writes that field.

Remove runner.state from runner.String()

---

dockerfiles/test_images/ociruntime_test/env_test_image/Dockerfile
enterprise/server/remote_execution/commandutil/commandutil.go
enterprise/server/remote_execution/containers/ociruntime/ociruntime.go
enterprise/server/remote_execution/containers/ociruntime/ociruntime_test.go

- Respect image env (e.g. `ENV` directives in Dockerfile)
- Change the `ImageStore` to represent images as a struct including both the layers and the image config (which includes the env), instead of just a list of layers
- Fix Action env variables not being respected by `Exec()`

OCI runtime: fix env not being respected in some cases

---

MODULE.bazel
WORKSPACE
go.mod

https://github.com/golang/go/issues?q=milestone%3AGo1.22.5+label%3ACherryPickApproved
Also remove an outdated replace directive in go.mod for
`github.com/go-redsync/redsync/v4`. This dependency was removed
in #4362.

go sdk: upgrade to 1.22.5

---

proto/remote_execution.proto

The immediate use case for these metrics is to expose them in the UI to make it easier for users to see whether a task is slow due to thrashing (for each resource type: CPU, memory, and disk).
It may also be useful to incorporate this information into task sizing somehow. For example, we can consider a task size measurement to be unreliable if there was a lot of thrashing while the measurement was taken, and avoid storing it in Redis. Another idea is that we could apply a small percent penalty to counteract the negative feedback loop that can happen when a task runs during high pressure conditions.

Add PSI metrics to UsageStats proto

---

enterprise/server/remoteauth/remoteauth_test.go

Add missing 't' argument to testenv.RegisterLocalGRPCServer

---

enterprise/server/remote_execution/cgroup/BUILD
enterprise/server/remote_execution/cgroup/cgroup.go
enterprise/server/remote_execution/cgroup/cgroup_test.go
enterprise/server/remote_execution/container/BUILD
enterprise/server/remote_execution/container/container.go
enterprise/server/remote_execution/container/container_test.go
enterprise/server/remote_execution/containers/podman/podman.go

* Read PSI metrics from cgroup2 fs
* Refactor path templates a bit - instead of having a separate path template for each cgroup file we want to read, just keep track of the cgroup dir. All of the cgroup accounting files should be direct children of this dir.
* Also remove deprecated path template flags - we aren't setting these anywhere and they are no longer needed.
* Update `UsageStats` util to allow tracking relative increases in pressure stall time (in the runner recycling case), similar to what we do for CPU time
* Add tests for `UsageStats` util, which also caught some bugs in the current implementation :grimacing: 

Add PSI stats implementation

---

deps.bzl

Reverts buildbuddy-io/buildbuddy#7016
Dev probers are down - seeing a lot of "context deadline exceeded in the logs", "IP-Config: Unable to set interface netmask (-22)" in one kernel log

Revert "Upgrade firecracker to v1.8.0"

---

enterprise/server/remote_execution/action_merger/action_merger.go
enterprise/server/remote_execution/execution_server/execution_server.go
enterprise/server/test/integration/remote_execution/remote_execution_test.go

This PR adds a flag, `remote_execution.action_merging_hedge_count` that causes the execution server to execute actions additionally in the background when new execution requests are received and merged against pending executions, up to a limited number of total in-fight executions. This is done by tracking the number of in-flight executions per action in Redis alongside the other action-merging data, and making the execution server spawn additional executions in the background when actions are hedge-able. A few notes:
- When hedging is enabled, there will be 1 execution spawned per execution request up to `remote_execution.action_merging_hedge_count+1`.
- When hedge executions are run, the ExecutionServer will still return the merged-against execution ID to the client. If that execution …

Support hedging merged actions

---

.bazelrc
app/invocation/invocation_suggestion_card.tsx

Reported in https://github.com/bazelbuild/bazel/issues/18997.
Using ZSTD often increases blob size when the blob is smaller than
100 bytes.
Suggest our users to set the threshold to 100 bytes when compression
is enabled.
This flag is only available since 7.1 so refactor getBazelMajorVersion
to emit minor version as well.

invocation suggestion: add compression threshold

---

buildbuddy.yaml

There isn't much reason to have a separate `Browser tests` workflow anymore since it now runs with the same Bazel flags as the normal `Test` workflow, and also it is no longer an optional check.

Make browser tests run as part of the normal Test workflow action

---

codesearch/cmd/cli/cli.go
codesearch/index/BUILD
codesearch/index/index.go
codesearch/index/index_test.go
codesearch/posting/posting.go
codesearch/posting/posting_test.go
codesearch/query/regexp_query.go
codesearch/searcher/searcher.go
codesearch/types/types.go

Return a slice of DocumentMatch interfaces from IndexReader RawQuery.
Each DocumentMatch tells you the docID that was matched, which fields match, and (eventually) the posting with offsets for the matches. This allows for much faster scoring.

Improve "matched docs" interface (returning maps stinks)

---

enterprise/server/tasksize/tasksize.go
enterprise/server/tasksize/tasksize_test.go

When a task is fully-stalled on a resource according to cgroup PSI metrics, the task is trying to use that resource, but can't due to contention. This winds up increasing the execution duration, which decreases the calculated milli-CPU, since the execution duration is in the denominator in the milli-CPU calculation: `milliCPU = (cpuNanos / 1e6) / execDurationMicros`. This is not ideal, because it means that contention will cause us to size tasks smaller, which results in even more contention (a negative feedback cycle).
So, in order to improve the accuracy of our reported duration, we can subtract the full stall duration (wall time, in usec) from the denominator in the average milliCPU calculation (CPU-milliseconds used per second of execution wall time). More specifically, we subtract …

Subtract full-stall duration from exec wall time in milliCPU calculation

---

enterprise/server/remote_execution/commandutil/BUILD
enterprise/server/remote_execution/commandutil/commandutil.go
enterprise/server/remote_execution/commandutil/commandutil_unix_test.go
enterprise/server/remote_execution/containers/podman/podman.go
enterprise/server/test/integration/podman/BUILD
enterprise/server/test/integration/podman/podman_test.go

Make sure that the reported CPU time includes the CPU time spent in the `podman run` command itself, and not just the child processes in the spawned container. On my local machine this adds about 60ms of additional reported CPU time for each command. This should significantly improve the task sizing accuracy for commands where podman itself accounts for most of the runtime.

Report podman overhead in execution stats

---

enterprise/server/scheduling/task_leaser/task_leaser.go
enterprise/server/usage/usage.go
enterprise/server/util/heartbeat/heartbeat.go
enterprise/server/util/redisutil/redisutil.go
server/util/approxlru/approxlru.go
server/util/healthcheck/healthcheck.go

**Related issues**: https://github.com/buildbuddy-io/buildbuddy-internal/issues/3588
to avoid unnecessary time.Timer allocations in background.

use time.Ticker instead of time.After in a loop

---

enterprise/server/backends/distributed/distributed.go

I noticed io.ReadAll in a heap trace and I think it's possible that we're over-allocating when reading a Reader into a []byte buf in the cache.Get call.
[io.ReadAll](https://cs.opensource.google/go/go/+/master:src/io/io.go;l=710?q=io.ReadAll) internally allocates a 512 byte buffer for performing the copy
[byte.Buffer](https://cs.opensource.google/go/go/+/master:src/bytes/buffer.go;l=16?q=bytes.Buffer) internally allocates a 64 byte buffer and grows it as needed. I believe that for small blobs, this should be more efficient.

Don't use io.ReadAll in distributed.go

---

enterprise/server/raft/store/store.go

Currently we call GetNodeHostInfo to get all the shard info a nodeHost has, and
then iterate over this list. The rate we iterate is one per 10 second. This
means that by the time we process this shard, it could be deleted by the driver.
As a result, the raft calls will failed with ShardNotFound.
I added a new membershipStatus for ShardNotFound; so isZombieNode can return
false immediately.

[raft] cleanup zombie: handle shard-not-found error

---

enterprise/server/raft/client/client.go

In order to understand what's going on with RunNodeHostFn, sometimes it's useful
to know what previous errors we encountered.

[raft] collect error from previous runs in RunNodeHostFn

---

codesearch/index/index.go
codesearch/posting/BUILD
codesearch/posting/posting.go
codesearch/posting/posting_test.go

Replace `[]uint64` with `[]Posting` throughout -- this allows tracking positions alongside docids. The value is:
1. we can avoid scoring docs with few positions, they wont rank higher than docs with many positions
2. we can limit the amount of bytes that need to be run through a regex, which is a bottleneck today

Use postings throughout

---

server/util/networking/BUILD
server/util/networking/networking.go
server/util/networking/networking_test.go

* Ensure that the veth pair is deleted synchronously. We were previously relying on it to be cleaned up as part of `RemoveNetNamespace`, but it turns out that `ip netns delete` only deletes the namespace itself synchronously - the resources in the namespace are cleaned up in the background.
* For the namespaced end of the veth pair, use `netIdx` (the locked index) instead of `vmIdx`. The comment `// Can be anything because it's in a namespace` was inaccurate - the IP address of the namespaced side of the veth pair is reachable from the host, so it must also be unique on the host. This can be verified by hard-coding `vmIdx` to 0 which causes the test to fail.
* In a follow-up PR I would like to get rid of `vmIdx` entirely - it's not really needed now that we have the separate `netIdx` …

Fix some bugs with VM network setup

---

app/router/router.tsx
enterprise/app/sidebar/sidebar.tsx
enterprise/app/workflows/workflows.tsx

- Render workflows page in the sidebar for all users, not just admins (if workflows are enabled)
- In the workflow listing, show the "Run workflow" button for developers but hide the 3-dot menu (which allows unlinking the repo / invalidating all snaphots for the repo)
Note, role-based capabilities are already set up for this to work - users can already view the workflow listing + workflow history, as well as run workflows.
Also note, the zero-state page already had some logic to show "Contact your administrator to set up workflows" instead of the setup button, so no changes were needed there.
**Related issues**: Fixes https://github.com/buildbuddy-io/buildbuddy-internal/issues/3628

Allow Developer role to view and execute workflows

---

dockerfiles/executor_image/README.md

- Switch to ssh-based repo, since (I think) most of us use keys to communicate with github
- `git apply` is for applying patch files; switch to `git cherry-pick` to cherry-pick a commit
- the first positional argument of `git push` is the remote repository, then all subsequent arguments are the refs to push. Switch to `git push origin <tag>`

Update instructions for podman-static releases

---

server/util/urlutil/BUILD
server/util/urlutil/urlutil.go
server/util/urlutil/urlutil_test.go

I am testing subdomains locally by setting up some entries in my `/etc/hosts` file like `app.localhost.io`, `customer.localhost.io` etc. and hit an issue where subdomain matching wasn't working properly - so directly navigating to `customer.localhost.io` via the address bar wouldn't navigate to the `customer` group.
The root issue was that the check [here](https://github.com/buildbuddy-io/buildbuddy/blob/2f35de7d46427aaa70a6aa5f91f904578d67f5c4/server/util/subdomain/subdomain.go#L35) was comparing `"localhost.io:8080"` (computed from `req.Host`) to `"localhost.io"` (computed from the `Hostname()` of the configured BB URL). `Hostname()` strips the port while `req.Host` includes the port, but `urlutil.GetDomain()` preserves the port, resulting in different domains being compared.
The fix in …

Handle port numbers in `GetDomain`

---

server/remote_cache/content_addressable_storage_server/BUILD
server/remote_cache/content_addressable_storage_server/content_addressable_storage_server_test.go
server/testutil/cas/BUILD
server/testutil/cas/cas.go

Planning to use these in another, new test in an upcoming PR

Move makeTree and readTree functions out of CAS test to testutil

---

enterprise/server/workspace/workspace_service.go
proto/workspace.proto

Enabled fetching of "original" file that doesn't contain any changes from this workspace.
This is useful for showing file diff views, generating patch files, etc.
Also adds metadata for tracking merge conflicts when syncing a workspace to a newer base commit.
Finally, returns a Node instead of just bytes from GetWorkspaceFileResponse so we can retrieve this additional metadata.

Tweaks to workspace proto

---

enterprise/server/raft/header/BUILD
enterprise/server/raft/header/header.go
enterprise/server/raft/sender/BUILD
enterprise/server/raft/sender/sender.go
enterprise/server/raft/store/BUILD
enterprise/server/raft/store/store.go
enterprise/server/raft/txn/BUILD
enterprise/server/raft/txn/txn.go

also, set the correct replica when we are getting local applied index in GetReplicaStates. (I don't think it changes behavior: currently, we only use the shard id from the replica in the header)

[raft] move makeHeader function out from sender/store/txn.

---

dockerfiles/rbe-ubuntu20-04/Dockerfile
enterprise/dockerfiles/rbe-ubuntu20-04-workflows/Dockerfile
enterprise/server/remote_execution/platform/platform.go

This seems to fix git-lfs hanging issues. Also makes sure that the git version in this image is at least as new as the one in the 18.04 workflows image (previously, the 18.04 image had a newer git version than the ubuntu 20.04 image).

Upgrade git version in ubuntu 20.04 image

---

enterprise/server/backends/pebble_cache/pebble_cache.go
enterprise/server/util/pebble/BUILD
enterprise/server/util/pebble/pebble.go

It's kinda tough to get a read on how much of a difference this makes in a real-ish environment.
I ran a little test harness where I hacked up cacheload to:
- write a few million 500-1000 byte entries to the pebble cache
- call findmissing with random (i.e., near-certain miss) digests as fast as possible
CPU profiles showed table read CPU decreasing by ~33% on FindMissing misses (so, disk reads and table loads decreased) in exchange for essentially-zero (<.1%) CPU hit on checking bloom filters.
qps perf, on the other hand, was pretty variable. i won't pretend to have a meaningful read on it; in both cases my load test environment came up with something like 30-40k read qps (single process requesting + receiving).  Performance across runs wasn't consistent enough to pretend i'm not being …

pebble cache: add a flag to enable bloom filter creation.

---

enterprise/app/tap/flakes.tsx

the `value` in the `<select>` element didn't match the pseudo-enum value.  

fix silly issue with sort select in flakes ui

---

enterprise/server/cmd/server/main.go
server/cmd/buildbuddy/main.go
server/libmain/libmain.go

This can allows us to grab go profiles during server start-up.

start monitoring handler earlier during server startup

---

enterprise/server/remote_execution/action_merger/BUILD
enterprise/server/remote_execution/action_merger/action_merger.go
enterprise/server/remote_execution/execution_server/execution_server.go
server/metrics/metrics.go

This PR adds two new metrics that track action-merging performance:
- `buildbuddy_remote_execution_merged_actions_per_execution`: a distribution tracking the number of merged actions per execution.
- `buildbuddy_remote_execution_merged_action_submit_time_offset_usec`: a distribution tracking the "submit time offset" for merged actions. The "submit time offset" is the wall time at which an action that is merged was submitted to the execution server minus the wall time at which the original execution it was merged against was submitted to the execution server. In a [previous PR](https://github.com/buildbuddy-io/buildbuddy/pull/6630) I called this the "time saved" due to action merging, but that's not really correct.
I'd like to add these as prometheus metrics because Siggi suggested that …

Add a couple of new action-merging metrics

---

enterprise/server/cmd/cache_proxy/BUILD
enterprise/server/cmd/cache_proxy/cache_proxy.go
server/environment/environment.go
server/real_environment/real_environment.go
server/testutil/testenv/testenv.go

This PR includes / is based off https://github.com/buildbuddy-io/buildbuddy/pull/7048. Please review that one first.

In Cache Proxy, start a local CASServer on the internal gRPC port

---

enterprise/server/tasksize/tasksize.go
enterprise/server/tasksize_model/tasksize_model.go

* Have the TF model limit its CPU predictions to 8 CPU cores. Since the model is not super accurate, CPU estimates higher than 8 CPU cores aren't really warranted.
* When we compute a milliCPU estimate that exceeds 16 CPU cores, log an info message that should help us understand why the computed value is so high, so we know what tweaks to make.

Add diagnostics and safeguards for high CPU estimates

---

server/build_event_protocol/accumulator/accumulator.go
server/build_event_protocol/build_event_handler/build_event_handler.go
server/build_event_protocol/build_event_handler/build_event_handler_test.go
server/build_event_protocol/build_status_reporter/build_status_reporter.go
server/build_event_protocol/target_tracker/target_tracker_test.go

In https://github.com/buildbuddy-io/buildbuddy-internal/issues/3579 we were reporting incorrect statuses to GitHub after a seemingly harmless change to change the order of build events.
The root issue was that the build status reporter was only reporting a status once the WorkspaceStatus event was loaded, instead of waiting for _all_ declared metadata events.
The "quick fix" was to simply change the order of events so that we publish WorkspaceStatus last. This PR implements a more comprehensive fix, which is to improve how we check whether metadata is fully loaded. Specifically, this PR refactors the build status reporter to use the same logic that we use in the build event handler to decide whether the invocation metadata is ready to be flushed to the DB. This refactor involved moving …

Consolidate invocation metadata logic

---

enterprise/server/test/integration/remote_execution/remote_execution_test.go

This test was written to rely on interaction between several concurrent remote executions of the same bash command. This required using `sleep` quite liberally and probing the remote system state to ensure remote executions of this script had proceeded to certain points in the command. This PR simplifies the flaky command to either finish immediately or block basically indefinitely, and introduces a second control script that unblocks subsequent executions of the first script. This makes it possible to `.Wait()` on the control script so the test can know when hedged executions will finish ~immediately, allowing us to remove most of the sleeping and remote-executor system-state probing from the test.
Here's an invocation with 1,000/1,000 green runs: …

Deflake TestActionMerging_Hedging

---

enterprise/server/remote_execution/execution_server/execution_server.go

all credit to @jdhollen and @bduffany for identifying this -- this is old code that we still have hanging around but isn't really doing anything useful anymore (and is causing unnecessary load on the database).
Write once the first time through the loop to set stage = executing, and then let everything else work the way it was before.

Don't write to mysql so much

---

enterprise/server/remote_execution/containers/firecracker/firecracker.go
server/util/networking/networking.go
server/util/networking/networking_test.go

* Remove `vmIdx` parameter of `SetupVethPair` - it is only used to keep track of the next host IP that we should try to reserve. This can instead be an internal implementation detail of `HostNetAllocator`, instead of relying on the caller to "hint" at what the next "likely free" index will be.
* Remove TAP device configuration from `CreateVethPair` and into a separate function (more context/discussion to follow in Slack)

Refactor `SetupVethPair` to prepare for reuse with OCI containers

---

server/remote_cache/byte_stream_server/BUILD
server/remote_cache/byte_stream_server/byte_stream_server.go
server/util/bazel_deprecation/BUILD
server/util/bazel_deprecation/bazel_deprecation.go

Big ups @fmeum for the help :)
Allow for publishing a deprecation warning in the bazel console when a request uses some feature that we're planning to drop. Do this by returning an error in the bytestream.Write call of the profile -- but still let that upload succeed so we don't impact profile uploads.

Support deprecation warnings in the console

---

enterprise/server/raft/client/client.go

Fix a regression introduced in
https://github.com/buildbuddy-io/buildbuddy/pull/7032, as a result, we are not retrying OutOfRange errors from SyncPropose.
This caused RemoveDeadReplica test to be flaky.

[raft] fix a regression when aggregating errors

---

enterprise/server/raft/cache/cache.go
enterprise/server/raft/store/store.go

**Related issues**: https://github.com/buildbuddy-io/buildbuddy-internal/issues/3625
Added a health check in raft to check whether replicas that started from disk on
ready to serve.
1. Before we call StartOnDiskReplica, we will mark them "started". Note that,
replicas created by AddReplica or Split won't have this status.
2. The first time when the store received AddRange from the replica with a non-empty range, we 
will initiate a goroutine to start wait for the replica to catch up. 
3. For some zombie shards that were created by a failed attempt to split, we
will wait up to maxWaitTimeForReplicaRange.
Also add the init status to statuz to make debugging easier.

[raft] wait till the replicas are loaded and caught up.

---

docs/config-olap-databases.md
website/sidebars.js

Our OLAP configuration doc was hidden from the world because it was not
added to the sidebars. Only keen users could find it from our doc search
results.
Remove the app.* flags as they have all been defaulted to true.
Users who setup clickhouse will get those features immediately.
Adjust the wording to highlight that ClickHouse is completely optional.
Also provided separate configuration example for clickhouse singleton vs
cluster deployment.

docs: update olap docs

---

enterprise/server/remote_execution/containers/ociruntime/ociruntime.go

Not having `/dev/shm/` mounted was causing webdriver tests to fail. When run with `--verbose` mode, Chromium reports failures relating to `/dev/shm`. Confirmed that tests pass on a local executor after enabling this mount.

Mount /dev/shm in OCI containers

---

deps.bzl
enterprise/server/remote_execution/containers/ociruntime/BUILD
enterprise/server/remote_execution/containers/ociruntime/ociruntime.go
enterprise/server/remote_execution/containers/ociruntime/ociruntime_test.go
tools/build_busybox.sh

It was getting stuck because it spawns a background process, and the unset `WaitDelay` param was causing us to have to wait for the background process to terminate.
Also make sure this test runs on CI by ensuring that `busybox` is available in `PATH`. (I built busybox for amd64 and arm64 and uploaded it to our GCS bucket so that it gets provisioned with Bazel).

Fix ociruntime pause/unpause test getting stuck

---

deps.bzl
enterprise/vmsupport/kernel/microvm-kernel-x86_64.config

Fix the OCI tests. They run in firecracker containers, and after the kernel config update, started failing with errors like ` create container: {"msg":"prctl: Invalid argument","level":"error","time":"2024-07-26T01:55:10.449777Z"}`. Setting the `CONFIG_SECCOMP=y` kernel option makes them run successfully again.

[FC] Fix OCI tests by enabling SECCOMP

---

enterprise/server/backends/distributed/BUILD

The block-network tag forces each test to run in its own network namespace so there's no issue with port collisions across concurrently running tests.
Part of fixing https://github.com/buildbuddy-io/buildbuddy-internal/issues/3114

Fix distributed_test port race flag when running test locally.

---

enterprise/server/remote_execution/container/container.go
enterprise/server/remote_execution/container/container_test.go
enterprise/server/remote_execution/containers/ociruntime/BUILD
enterprise/server/remote_execution/containers/ociruntime/ociruntime.go
enterprise/server/remote_execution/containers/ociruntime/ociruntime_test.go
enterprise/server/remote_execution/containers/podman/podman.go

The current call to `Reset()` sets the stats baseline to the last observed value, but if a runner has background processes running, then the last observed value won't account for any usage from background processes since the last call to `Exec()` finished.
There is some evidence that this is causing task sizes to be inflated - some tasks with runner recycling enabled have very high pressure stall times which are close to or exceed the task's execution duration, which doesn't make much sense. But this could be explained by the fact that the current `Reset()` implementation ignores any resource usage since the previous task finished its `Exec()` call (e.g. while it was uploading outputs).

Fix container stats baseline for recycled runners

---

dockerfiles/test_images/net_tools/Dockerfile
enterprise/server/remote_execution/containers/ociruntime/BUILD
enterprise/server/remote_execution/containers/ociruntime/ociruntime.go
enterprise/server/remote_execution/containers/ociruntime/ociruntime_test.go
enterprise/server/remote_execution/runner/runner.go
server/testutil/testnetworking/BUILD
server/testutil/testnetworking/testnetworking.go
server/util/networking/BUILD
server/util/networking/networking.go
server/util/networking/networking_test.go

Not much interesting new code is being added here except a new `iptables` rule in `SetupVethPair` to prevent traffic between containers. Everything else is mostly plumbing / tests.
**Related issues**: https://github.com/buildbuddy-io/buildbuddy/pull/7093

Implement networking for OCI runtime

---

enterprise/server/remote_execution/containers/ociruntime/ociruntime.go

Mount /dev/pts for additional docker/podman compatibility.
Also rename the "source" name of the /dev/shm mount from "tmpfs" to "shm." (This just reduces some unnecessary diff in the `mount` output between oci and podman - it shouldn't actually matter what this name is unless people are grepping the 'mount' output and looking for it)

Mount /dev/pts in OCI containers

---

enterprise/server/remote_execution/containers/ociruntime/ociruntime.go

argh, in https://github.com/buildbuddy-io/buildbuddy/pull/7104 I meant to rename `/dev/shm` to `shm`, but accidentally renamed `/dev` to `shm`.

Update names of /dev and /dev/shm

---

enterprise/server/iprules/iprules.go

When copying and pasting my IP from Google, it included a space on the left, and I got an error that the IP was invalid

Trim space from IP rule input

---

enterprise/server/remote_execution/containers/ociruntime/ociruntime.go
enterprise/server/remote_execution/containers/ociruntime/ociruntime_test.go

- `Hostname` field in the OCI config gets set to either `--hostname` if set, or the container name, which defaults to `cid[:12]` if a container name is not set explicitly. We don't allow passing `--hostname` or setting a container name explicitly so just set it to `cid[:12]`.
- `/etc/hostname` just contains `localhost` unless `--hostname` flag is passed, which we don't allow passing. So hard-code this file to `localhost`.
- `$HOSTNAME` env var should match the contents of `/etc/hostname`; hard-code this to `localhost` as well.

OCI runtime: make hostname logic more compatible

---

codesearch/index/index.go
codesearch/query/regexp.go
codesearch/query/regexp_query_test.go
codesearch/query/regexp_test.go
codesearch/sparse/BUILD
codesearch/sparse/set.go
codesearch/token/BUILD
codesearch/token/token.go
codesearch/token/token_test.go

The sparse ngrams are longer than trigrams so I don't want to do case expansion on them (casE, caSe, cAse, Case, caSE...).

Only index lowercase ngrams (still use case in regex match tho).

---

enterprise/server/raft/replica/replica.go
enterprise/server/raft/replica/replica_test.go
enterprise/server/raft/store/store_test.go
enterprise/server/raft/testutil/testutil.go

**Related issues**: https://github.com/buildbuddy-io/buildbuddy-internal/issues/3606
Use EstimatedDiskUsage() as a way to calculate the size of a shard; instead of
partition metadata. It's expensive to calculate the accurate size of a partition
in a range post split, because we have to iterate all the keys.

use EstimateDiskUsage in Usage()

---

codesearch/cmd/cli/cli.go
codesearch/index/index.go
codesearch/token/token.go
codesearch/token/token_test.go
codesearch/types/types.go

This roughly halves the amount of space allocated (from 12G -> 7G) during an indexing run of the kernel.

Don't mint token objects just to discard them

---

enterprise/server/remote_execution/containers/ociruntime/ociruntime.go
enterprise/server/remote_execution/containers/ociruntime/ociruntime_test.go

* Fix peak memory getting reported as 0
* Port https://github.com/buildbuddy-io/buildbuddy/pull/7021 to OCI runtime so that we account for the runtime process stats

Fix OCI runtime stats

---

enterprise/server/remote_execution/containers/ociruntime/ociruntime.go
enterprise/server/remote_execution/containers/ociruntime/ociruntime_test.go

We don't need to manually mount /dev/null, /dev/zero etc. - this happens automatically.

Clean up how devices are mounted in OCI containers

---

enterprise/server/remote_execution/containers/ociruntime/ociruntime.go

In our current podman implementation, we are granting fewer capabilities than what's currently in the hard-coded list.

Reduce OCI capabilities set

---

app/invocation/invocation_cache_card.tsx

The previous version was confusing because it shows up in the cache tab, so folks automatically assume it's talking about remote cache misses. 
In reality, this data comes directly from Bazel (via the BES) and explains why actions missed Bazel's local action cache - but may still hit the remote cache.

Improve cache miss reason wording

---

enterprise/server/remote_execution/containers/ociruntime/ociruntime.go

Set `resources.pids.limit` to 2048 by default and make it configurable (for parity with podman).

Set OCI pid limit

---

tools/metrics/grafana/dashboards/buildbuddy.json

Before this change, the move graph doesn't show the number of moves, and the hit graph shows the value is 100%, but the graph shows movement of the metric
After this change, we can see the number of moves and also the an accurate value in hit graph.

[raft] fix move graph and range cache hit graph

---

dockerfiles/test_images/net_tools/Dockerfile
enterprise/server/remote_execution/containers/ociruntime/BUILD
enterprise/server/remote_execution/containers/ociruntime/ociruntime.go
enterprise/server/remote_execution/containers/ociruntime/ociruntime_test.go
server/testutil/testnetworking/testnetworking.go
server/util/networking/BUILD
server/util/networking/networking_test.go

We need the sysctl `net.ipv4.ping_group_range="0 0"` in order for ICMP requests to work without needing `CAP_NET_RAW` capability.

Fix ping not working in OCI runtime

---

enterprise/server/scheduling/scheduler_server/scheduler_server.go
server/metrics/metrics.go

Wound up just doing it per-probe since `adjustTaskSize` incorporates each node's total size, and the adjusted task size is the source of truth for the task size.

Add histograms for enqueued task sizes

---

tools/bulkredis/BUILD
tools/bulkredis/bulkredis.go

Starting with just bulk scan + bulk delete for now. This could be useful for other things like computing the size of keys, so eventually it'd be cool to split this up into more unix-like tools like `bulkredis scan 'taskSize/*' | bulkredis delete` or something like that.
Credit to @vadimberezniker for the initial version of this tool in https://github.com/buildbuddy-io/buildbuddy/commit/b5d27e70d545925f3db3d5129fff87bf2d7a8e52

Add tool to bulk-delete keys from Redis

---

server/util/grpc_server/grpc_server.go

compare: https://github.com/grpc-ecosystem/go-grpc-middleware/blob/62b7de50cda5a5d633f1013bfbe50e0f38db34ef/providers/prometheus/server_options.go#L37-L48 , which bottoms out at .005s
(`var DefBuckets = []float64{.005, .01, .025, .05, .1, .25, .5, 1, 2.5, 5, 10}`)

add a few more grpc latency buckets for more precise measurement.

---

enterprise/server/remote_execution/container/container.go
enterprise/server/remote_execution/containers/podman/podman.go

If the CPU usage between Unpause() and Exec() is high relative to the exec duration, then this could cause the milli_cpu estimate that we store in Redis to be disproportionately large relative to the task's actual CPU usage. This is because the exec duration only accounts for the time spent in Exec(), not the time between Unpause() and Exec(). So if there is a BG process in the runner and (input_download+pull_image) duration is relatively high, the BG process can be racking up CPU usage which will be misattributed to the exec_duration and inflate the calculated average milli-CPU.
This PR just adds some debug logging to help test this hypothesis, and should not affect scheduling behavior.

Add logging for CPU usage between Unpause() and Exec()

---

enterprise/server/remote_execution/action_merger/action_merger.go
enterprise/server/remote_execution/execution_server/execution_server.go
server/metrics/metrics.go

This PR adds a flag, `remote_execution.action_merging_hedge_delay` which causes the execution server to employ a linear backoff strategy for running hedged executions. IOW, the execution server will run a hedged execution for each client-submitted action that arrives at least `remote_execution.action_merging_hedge_delay` after the last execution (original or hedged), up to `remote_execution.action_merging_hedge_count` times.
It also adds a prometheus counter that counts hedged executions.

Support linear backoff for hedged executions

---

enterprise/server/byte_stream_server_proxy/BUILD
enterprise/server/byte_stream_server_proxy/byte_stream_server_proxy.go
enterprise/server/byte_stream_server_proxy/byte_stream_server_proxy_test.go

This PR contains the changes in https://github.com/buildbuddy-io/buildbuddy/pull/7048 -- review that one first.
This PR makes `byte_stream_server_proxy` use the `byte_stream_server` installed in the environment by `cache_proxy` in https://github.com/buildbuddy-io/buildbuddy/pull/7048 for caching data locally. It attempts to serve reads out of the local bytestreamserver, when the data is available, and writes data that's read through the proxy to the local bytestreamserver. There is a bit of a hack that converts downloaded resource names into uploaded resource names, but otherwise it's mostly just manipulating gRPC streams.
Note that the test is largely copied from `server/remote_cache/byte_stream_server/byte_stream_server_test.go` because that test has pretty good coverage of compression …

Enable local caching in byte_stream_server_proxy

---

server/remote_cache/digest/digest.go
server/remote_cache/digest/digest_test.go

The current implementation of `digest.Diff` uses pointer equality for testing digest equality. This means that it will incorrectly declare two digests to be different if they are pointers to different versions of the same digest, rather than checking their values to determine they are the same.
This is only used in the migration cache and has likely resulted in over-migrating data during the double read phase. From reading the code, it appears the new, correct behavior is desired as it's reading digests from two different backends, so the current implementation will always declare them all to be different, as they'll be pointers into different allocated protos in memory.
I added a new test that demonstrates the bug.

Fix a bug in digest.Diff() by making it use value equality instead of pointer equality.

---

enterprise/server/test/integration/ci_runner/BUILD

In `ci_runner_test > TestArtifactUploads_JVMLog`, Bazel occasionally throws an unexpected "NoClassDefFoundError" instead of the expected "OutOfMemoryError," but only when run inside the OCI runner.
I think we should treat this as a blocker for launching the OCI runner to prod, because it seems likely that whatever's causing this flakiness could also cause some customer actions to flake. But I would like to turn on OCI by default in dev so that we can start testing it much more seriously, so in the meantime this PR should let us do that without the dev tests constantly being flaky.

Temporarily require podman isolation for ci_runner_test

---

enterprise/server/remote_execution/containers/podman/podman.go

argh, I forgot that this information is also needed in order to tell whether https://github.com/buildbuddy-io/buildbuddy/pull/7126 will fix our task sizing problems.

Add full stall durations to podman debug logs

---

enterprise/server/raft/replica/replica.go
enterprise/server/raft/sender/sender.go
proto/raft.proto

**Related issues**: https://github.com/buildbuddy-io/buildbuddy-internal/issues/3626

[raft] only return one kv when we look up range descriptor

---

MODULE.bazel
WORKSPACE
WORKSPACE.bzlmod

Switch to use googleapis module instead of our own.

bzlmod: use googleapis module

---

MODULE.bazel
WORKSPACE
WORKSPACE.bzlmod
buildpatches/build_bazel_rules_nodejs.patch
rules/sha/index.bzl
rules/typescript/index.bzl

This PR attempts to change all the forced-local actions to remote-able actions.
It should improve our Build without the Bytes setup and reduce the amount of artifacts downloaded locally.
After this is applied, we still download a few data from each build:
- Stderr / stdout of each action (including tests)
- Directory tree metadata (no blob)
The remaining data could still be significant in some cases, such as a change that invalidates a lot of tests with large logs.
The fix for these most likely will have to come from Bazel upstream.

CI: no local actions

---

server/util/networking/networking.go

On my system (ubuntu 22.04), traffic in the FORWARD chain is dropped by default, so I need explicit ACCEPT rules for container networking traffic to be forwarded to/from the host interface. We have the ACCEPT rule in place for forwarding veth => host traffic, but we're missing the rule for the reverse direction (host => veth). This PR fixes that.
I noticed this while trying to run `ping` on my local machine from within an OCI container - no idea why, but this used to work for me before, but stopped working today. (My best guess is that a software update caused it somehow.)
I confirmed with `iptables -L -n -v` that the default-drop policy is what was causing these packets to be dropped, and that adding the ACCEPT rule fixed it.

Allow traffic from default interface to host veth

---

dockerfiles/test_images/ociruntime_test/env_test_image/Dockerfile
enterprise/server/remote_execution/containers/ociruntime/ociruntime.go
enterprise/server/remote_execution/containers/ociruntime/ociruntime_test.go

- Mount `lowerdir` in the correct order
- Respect whiteout files (deleted files/dirs)

OCI runtime: fix some overlayfs bugs

---

enterprise/server/remote_execution/execution_server/BUILD
enterprise/server/remote_execution/execution_server/execution_server.go
enterprise/server/scheduling/scheduler_server/scheduler_server.go
server/interfaces/interfaces.go

This will allow testing riskier changes without impacting real workloads.
It turned out to be just a tad hacky, but it should suffice for near term testing. I didn't see a cleaner way to fit this into the current architecture.

Add support for "teeing" shared executor pool work to a separate pool.

---

app/invocation/invocation_exec_log_card.tsx

While working on #7166, I discovered that clicking on `local` actions in
the execution log card would crash our UI.
This is because local spawn entry does not have `digest` and thus,
render the entries in the card with `href=/invocation/<uuid>$#action`,
and clicking on it would cause our browser to crash.
Don't render the invalid URL here.

invocation_exec_log_card: fix invalid href local runner entries

---

enterprise/server/raft/listener/listener.go

When leasekeeper receive quitAll, RemoveLeaderUpdatedListener() can be blocked
waiting for the mutex. The mutex is held by LeaderUpdated(), but itself was
blocked by sending the message to the channel.

[raft] do not block leader updates

---

enterprise/server/test/webdriver/invocation/invocation_test.go

We believe it's causing the section to re-render and cause problems with the test. All should already be the default so this should be unnecessary.

Dont try to select "all" filter.

---

.bazelrc
server/testutil/webtester/webtester.go

- Split out `webdriver_debug` flag into 2 separate flags, `webdriver_headless` and `webdriver_verbose`
- Don't set `webdriver_verbose` when running with `--config=webdriver-debug` since the logs are pretty obnoxious. We can enable these for dev QA though, since it helps piece together what happened during the test.

Rework webdriver debug flags

---

enterprise/server/remote_execution/containers/ociruntime/BUILD
enterprise/server/remote_execution/containers/ociruntime/ociruntime.go
enterprise/server/remote_execution/containers/ociruntime/ociruntime_test.go
enterprise/server/remote_execution/persistentworker/persistentworker.go
enterprise/server/remote_execution/runner/testworker/BUILD

- Use `CommandContext` for all OCI runtime commands so that they are killed on shutdown.
- Close persistent worker stdin pipe when stopping the persistent worker, otherwise the crun exec command's `cmd.Run()` call never returns, even though the process has been killed.

OCI runtime: fix persistent workers getting stuck on shutdown

---

enterprise/server/remote_execution/containers/firecracker/firecracker.go

The corresponding bug has been fix in firecracker v1.8 🎉 
As a note, I'm planning to release each of these firecracker config changes independently and with some time between so it will be easier to debug if there are problems

[FC] Remove lapic=notscdeadline bootarg

---

enterprise/server/raft/listener/listener.go

When there are 200+ ranges, leaderUpdates chan needs to be bigger; otherwise,
the leader update will be dropped when the server started; and it can cause
decrease range cache hit rate and increased write latency.

[raft] make leader updated chan size configurable

---

.github/workflows/test-executor-linux-arm64.yaml

Exclude
//enterprise/server/test/integration/remote_execution:remote_execution_test
from running locally on ARM64.
This constantly fail on ARM64 and create false signals.

github/workflows: exclude flaky test

---

app/invocation/invocation_exec_log_card.tsx

This was using the same name as the radio buttons for the remote
executions card.
Changing sort direction when both 4 radio buttons are available cause
the checked status to not render correctly.
Rename the radio inputs of exec log.
Also tighten the onChange handler to not rely on the input name to
determine the state.
Fixes https://github.com/buildbuddy-io/buildbuddy-internal/issues/3587

invocation_exec_log_card: fix sort direction radio group

---

enterprise/server/raft/replica/replica.go
enterprise/server/raft/replica/replica_test.go

**Related issues**: https://github.com/buildbuddy-io/buildbuddy-internal/issues/3681
We still need to set usage.Partitions.

[raft] set partition usage in usage

---

enterprise/server/remote_execution/commandutil/commandutil.go
enterprise/server/remote_execution/containers/ociruntime/BUILD
enterprise/server/remote_execution/containers/ociruntime/ociruntime.go
enterprise/server/remote_execution/containers/ociruntime/ociruntime_test.go

Yet another case of `cmd.Run()` getting stuck after the process has terminated.
This is fixed by placing `crun run` inside its own pid namespace, since killing pid 1 in the namespace causes all other processes in the namespace to be killed as well. Before this PR, `crun run` was in the same pid namespace as the executor (and the containerized child processes were in their own namespace). Adding an additional level of pid namespacing simplifies cleanup and ensures that child processes are immediately cleaned up when `crun run` is killed.
I'm not sure why this issue doesn't happen with `crun exec`, but am investigating separately. I tried looking for differences in the output of `ps -eo pid,ppid,pidns,cmd`, but it shows similar output for both `run` and `exec` in terms of the ps tree …

OCI runtime: fix `run` not respecting context cancellation

---

MODULE.bazel
buildbuddy.yaml

This fixes running `bazel mod tidy --enable_bzlmod` in the repo.
Since we do not reference any repos generated by the `switched_rules` extension (otherwise CI would have caught the mistake), we can also drop the `use_repo`.
**Related PRs**: #7205

Fix `googleapis` module extension usage

---

deps.bzl
enterprise/server/cmd/executor/BUILD

This reverts commit 63c2d0da3a414f92e4fb3f2593e8c6982ae3e11d.

Revert "Update `soci-snapshotter` version in executor image (#7186)"

---

codesearch/dfa/BUILD
codesearch/dfa/copy.go
codesearch/dfa/dfa.go
codesearch/dfa/regexp.go
codesearch/dfa/utf.go
codesearch/query/BUILD
codesearch/query/regexp_query.go

for a search like [lang:c failed] on the linux kernel sources, this is about 3x faster.
DFA: 	2024/08/12 19:18:56.695 INF Scoring 12438 docs took 326.02845ms name=searcher
STDLIB: 2024/08/12 19:19:03.823 INF Scoring 12438 docs took 947.251817ms name=searcher
More context on go's relatively slow regex performance here: https://github.com/golang/go/issues/26623

Use the rsc/codesearch DFA for speed

---

enterprise/server/cmd/ci_runner/main.go

Running
`git config --global url.https://github.com/.insteadOf <original>`
multiple times will replace the previous config value with the new value
of each call.
Instead of doing that, run the very first attempt with `--replace-all`
to wipe all existing values with our new value.  For subsequent runs,
use `--add` to append the new values to existing config.

ci_runner: avoid url.*.insteadOf clobbering

---

app/invocation/invocation_action_card.tsx
app/util/cache.tsx

If user try to navigate to a url such as
`http://app.buildbuddy.io/invocation/<uuid>#action` today, their UI
would crash and unable to recover.
Fix this by returning an alert on the screen instead.
With this, users still see the invocation UI and can navigate away.

invocation_action_card: handle exception parsing action digest

---

enterprise/server/cmd/ci_runner/main.go
enterprise/server/test/integration/ci_runner/BUILD
enterprise/server/test/integration/ci_runner/ci_runner_test.go

If the workspace lock is still held at the end of the workflow, create the file ".BUILDBUDDY_DO_NOT_RECYCLE" in the action working dir to prevent recycling.
This should fix an issue where workflows can get stuck with the error message `Another command (pid=XXX) is running. Waiting for it to complete on the server (server_pid=XXX)...`

Don't recycle workflow VM if workspace lock is still held

---

enterprise/server/cmd/ci_runner/main.go
enterprise/server/remote_execution/runner/runner.go

- In `ci_runner`, make sure logs are sent on the BES stream so that they appear in the workflow invocation logs
- In the executor, log a message when we don't reycle because of the DO_NOT_RECYCLE file

Improve DoNotRecycle logging

---

deps.bzl
enterprise/server/cmd/executor/BUILD

Fixed the panic; soci changed where they added default values from where they were used to when they were parsed, so corrected to the new config loading function:
https://github.com/buildbuddy-io/soci-snapshotter/commit/15935fa304085232215608325765d80c3d4e0a5a

Update `soci-snapshotter` version in executor image

---

codesearch/cmd/cli/BUILD
codesearch/cmd/cli/cli.go
codesearch/cmd/server/server.go
codesearch/index/BUILD
codesearch/index/index.go
codesearch/index/index_test.go
codesearch/kythe/server/BUILD
codesearch/kythe/server/server.go
codesearch/performance/BUILD
codesearch/performance/performance.go
codesearch/query/regexp_query.go
codesearch/query/regexp_query_test.go
codesearch/searcher/BUILD
codesearch/searcher/searcher.go
codesearch/server/BUILD
codesearch/server/server.go
codesearch/types/types.go

looks about the same as before but now there's more useful data and it can be returned to the client.
```
2024/08/13 12:05:05.257 INF raw query: [(FailedPrecondition|Unknown)Error] name=regexp-query
2024/08/13 12:05:05.257 INF parsed query: [(?mi)((FailedPrecondition|Unknown)Error)] name=regexp-query
2024/08/13 12:05:05.257 INF squery: "(:and (:and (:eq content \"err\") (:eq content \"rror\")) (:or  (:and (:eq content \"cond\") (:eq content \"diti\") (:eq content \"edpr\") (:eq content \"fail\") (:eq content \"iled\") (:eq content \"ion\") (:eq content \"ndi\") (:eq content \"pre\") (:eq content \"reco\") (:eq content \"tio\")) (:and (:eq content \"nkno\") (:eq content \"now\") (:eq content \"own\") (:eq content \"unk\"))) (:or (:eq content \"oner\") (:eq content \"wner\")))" …
```

Track index read performance

---

app/components/button/button.css

[This PR](https://github.com/buildbuddy-io/buildbuddy/pull/7170/files) started a battle that `.outlined-button-group` wasn't prepared to fight.
This PR gives `.outlined-button-group` the specificity ammunition to win that battle.
Before:
After:

Sprinkle in some more specificity

---

enterprise/server/tasksize/tasksize.go
enterprise/server/tasksize/tasksize_test.go

Adds a knob to control the fraction of pressure stall time that we apply as a correction to the execution duration, and adjusts the effective value of the knob from 100% to 75%. This is needed because (for reasons that are still not 100% clear) the PSI stall time is occasionally reported to be very close to the execution duration, resulting in a high computed value for the average milliCPU usage.
Based on analysis of logs, using only 75% of the reported pressure stall time instead of 100% would have fixed all problematic tasks from the last 24h (>16 CPU), putting them under the 30 CPU mark. For non-problematic tasks, this should not affecting task sizes by too much, and preserve enough backpressure to prevent negative feedback loops, since we are still preserving most (75%) of the PSI …

Use a configurable fraction of stall time in PSI-adjusted duration

---

codesearch/cmd/server/server.go

This way I can grab remote heap dumps.

Enable the monitoring handler in the codesearch binary

---

app/components/button/button.css

Otherwise the borders come back once they're hovered

Get the hover states too

---

codesearch/server/server.go
proto/search.proto

```
performance_metrics {
metrics {
name: "INDEX_BYTES_READ"
value: 225999
}
metrics {
name: "INDEX_KEYS_SCANNED"
value: 18
}
metrics {
name: "DOC_BYTES_READ"
value: 4573186
}
metrics {
name: "DOC_KEYS_SCANNED"
value: 3452
}
metrics {
name: "POSTING_LIST_QUERY_DURATION"
value: 2463906
}
metrics {
name: "POSTING_LIST_COUNT"
value: 18
}
metrics {
name: "POSTING_LIST_DOCIDS_COUNT"
value: 23702
}
metrics {
name: "REMOVE_DELETED_DOCS_DURATION"
value: 5850
}
metrics {
name: "TOTAL_SCORING_DURATION"
value: 7923278
}
metrics {
name: "TOTAL_DOCS_SCORED_COUNT"
value: 160
}
metrics {
name: "TOTAL_SEARCH_DURATION"
value: 10467454
}
}
```

Return performance metrics to client

---

enterprise/server/cmd/ci_runner/main.go

**Related issues**: Fixes https://github.com/buildbuddy-io/buildbuddy-internal/issues/3695#event-13912334818

[ci_runner] Stop buffering bash output in memory

---

cli/plugins/go-deps/post_bazel.py

I've been getting
```
/home/zoey/src/bb/buildbuddy/cli/plugins/go-deps/./post_bazel.py:29: SyntaxWarning: invalid escape sequence '\s'
f'^\s*(?P<prefix>.*/execroot/|/tmp/bazel-working-directory/)(({workspace_basename}|_main)/)?(?P<src_path>.*?\.go): import of "(?P<import_url>.*?)"',
/home/zoey/src/bb/buildbuddy/cli/plugins/go-deps/./post_bazel.py:29: SyntaxWarning: invalid escape sequence '\.'
f'^\s*(?P<prefix>.*/execroot/|/tmp/bazel-working-directory/)(({workspace_basename}|_main)/)?(?P<src_path>.*?\.go): import of "(?P<import_url>.*?)"',
```
on every build since updating python. This should fix it.

Fix bad escape sequences in `post_bazel.py`

---

WORKSPACE

Adds platform `ppc64le`, which was necessary for upgrading `rules_go`

Update `bazelbuild/platforms` from 0.0.6 -> 0.0.10

---

codesearch/index/index.go
codesearch/query/regexp_query.go

// Skip redundant outer list wrapping
((:and blah)) -> (:and blah)
// Simplify expressions
(:and (expr)) -> (expr)
// Remove redundant subexpressions from :and expressions 
(:and (:all) (expr1) (expr2)) -> (:and (expr1) (expr2))

Simplify redundant squeries (which can be slower than necessary)

---

codesearch/server/server.go

This is so I can add a "repo:" atom.

Split repo and owner fields

---

proto/BUILD
proto/build_event_stream.proto
proto/failure_details.proto
proto/invocation_policy.proto
proto/option_filters.proto
proto/spawn.proto
proto/strategy_policy.proto

This PR update the protos from bazel.git to the latest version from
```
> git log -1
commit 5f66ae8032ef84103b34e214153975495f7f5c48 (HEAD -> master, origin/master, origin/HEAD)
Author: Googler <jingwen@google.com>
Date:   Fri Aug 2 07:43:28 2024 -0700
Add experimental active_directories field to PROJECT.scl.
.. to support sharding a project's active_directories by name.
PiperOrigin-RevId: 658787465
Change-Id: I9685780adef1accafe89a76298d28acdbca6787d
```
https://github.com/bazelbuild/bazel/commit/5f66ae8032ef84103b34e214153975495f7f5c48
This should fix our UI crashing when Bazel fail to write the new compact execution log
with the new Error Code 15.
Some manual adjustment was needed around BUILD configuration for invocation_policy.proto 
and it's newly imported, strategy_policy.proto. …

Update Bazel protos

---

enterprise/server/cmd/cache_proxy/cache_proxy.go

Forgot to add this in https://github.com/buildbuddy-io/buildbuddy/pull/7076

Set local CAS client in cache_proxy initialization so it doesn't crash.

---

dockerfiles/executor_image/Dockerfile

This has the side effect of uninstalling `docker-credential-ecr-login`

Don't uninstall ca-certificates package

---

enterprise/server/tasksize/tasksize.go
enterprise/server/tasksize/tasksize_test.go

Since we changed the max computed CPU to 7500, we can revert the other hack which sets the PSI correction factor to 0.75. I kept around this flag in case we want to disable it (e.g. by setting it to zero) or if we find there's a need to dial it down in the future.

Set PSI correction factor back to 1

---

dockerfiles/executor_image/Dockerfile

this way, we'll only remove these packages if none of the other stuff we install depends on it--better to explicitly list all the things we manually installed for this purpose.

mark packages we used to configure the executor image as auto-installed

---

deps.bzl
enterprise/server/util/redisutil/redisutil_test.go
go.mod
go.sum
server/backends/chunkstore/chunkstore.go
server/remote_cache/byte_stream_client/byte_stream_client_test.go
tools/metrics/grafana/grafana.go

Upgrade our staticcheck from v0.3.1 to v0.5.1 in prepare for Go 1.23.
Also fixed an issue with printf being used without a string format.

go.mod: upgrade staticcheck version

---

server/util/redact/redact.go
server/util/redact/redact_test.go

We have received some report about our redact logic wrongly remove regex
flag values that contain an `@` character in side. Although I am not
sure if we could make our regex any narrower without reducing the
effectiveness of it, I think it's a confusing experience for our user to
pass some regex via CLI just to get a different regex via our UI.
Instead of silently replace the matched value with an empty string,
effectively yanking out the redaction, replace it using a static
placeholder instead.

redact: replace with placeholder

---

cli/remotebazel/remotebazel.go

[Here](https://github.com/buildbuddy-io/buildbuddy/blob/master/cli/remotebazel/remotebazel.go#L880) is where we add the executable args if running the target locally

[RB] Pass executable args to remote bazel command

---

enterprise/server/remote_execution/containers/podman/podman.go

In https://github.com/buildbuddy-io/buildbuddy/pull/7261/files we added this for the `Exec()` path. This PR adds it to the `Run()` path as well.

Handle podman SIGKILL / SIGTERM in Run() path

---

enterprise/server/remote_execution/executor/executor.go
server/metrics/metrics.go

The high cardinality of this metric seems to be hurting scrape performance.

Reduce cardinality of PSI metrics

---

app/invocation/invocation_model.tsx
cli/remotebazel/BUILD
cli/remotebazel/remotebazel.go
enterprise/server/cmd/ci_runner/main.go
enterprise/server/test/integration/remote_bazel/BUILD
enterprise/server/test/integration/remote_bazel/remote_bazel_test.go
proto/build_event_stream.proto
server/build_event_protocol/build_event_handler/build_event_handler.go

Reverts buildbuddy-io/buildbuddy#7061
There is a regression from https://github.com/buildbuddy-io/buildbuddy/pull/7138.
We're seeing weird behavior on certain [workflows](https://app.buildbuddy.dev/invocation/536a0418-b197-447c-b73b-14a1fc544e60) where it will link multiple redundant child invocations. I think it may be because the ci_runner execution was disrupted due to an executor restart, so we rescheduled it but we didn't clean up parent_invocation_id on the previous child invocations that were spawned
I will revert 7138 as well

Revert "[ci_runner] Populate child invocation cards in UI for bazel commands in bash"

---

enterprise/server/remote_execution/runner/runner.go

After investigation, there is strong evidence of a bug somewhere in the kernel [code](https://github.com/torvalds/linux/blob/5be63fc19fcaa4c236b307420483578a56986a37/kernel/sched/psi.c) responsible for reporting PSI durations. I reported a bug here (with more details + small repro program): https://bugzilla.kernel.org/show_bug.cgi?id=219194
If we look at [logs](http://go/bad-cpu-stall) from the last 7d of nonsensical task sizes, almost all of the CPU stall durations for these tasks seem to be about 4.2s, i.e. the suspicious UINT32_MAX nanoseconds number mentioned in the bug report.
At some point, it would be nice to diagnose / fix this bug upstream, but I think it makes sense to add a mitigation for this bug in our code, since any upstream fix would likely to take a long time to develop, …

Add mitigation for kernel bug in PSI calculation

---

app/invocation/BUILD
app/invocation/child_invocation_card.tsx
app/invocation/child_invocations.tsx
app/invocation/invocation.tsx
enterprise/server/cmd/ci_runner/main.go

Reverts buildbuddy-io/buildbuddy#7138
There is a regression from https://github.com/buildbuddy-io/buildbuddy/pull/7138.
We're seeing weird behavior on certain [workflows](https://app.buildbuddy.dev/invocation/536a0418-b197-447c-b73b-14a1fc544e60) where it will link multiple redundant child invocations. I think it may be because the ci_runner execution was disrupted due to an executor restart, so we rescheduled it but we didn't clean up parent_invocation_id on the previous child invocations that were spawned

Revert "[ci_runner] Fetch child invocations from the db instead of BES events"

---

buildpatches/com_github_mattn_go_sqlite3.patch
deps.bzl
go.mod
go.sum

Reduced the patch to minimally needed for building and maintenance.

upgrade go-sqlite3 to 1.14.22

---

BUILD

stdversion is part of `go vet` starting from 1.23.
I discorvered unusedwrite while browsing x/tools and it seems like a
useful check now that variables in a loop are now copies.

nogo: add stdversion and unusedwrite

---

codesearch/server/server.go
enterprise/app/codesearch/result.tsx
proto/search.proto

Return owner + repo in search results, and use both when constructing the link to the code editor.

Fix owner/repo linking

---

enterprise/server/remote_execution/containers/firecracker/firecracker.go

We've had this enabled in prod for a while now.

Enable guest cgroup2 flag by default

---

enterprise/server/remote_execution/container/container.go
enterprise/server/remote_execution/containers/bare/BUILD
enterprise/server/remote_execution/containers/bare/bare.go
enterprise/server/remote_execution/runner/runner.go

Add some temporary debug logging to help debug a customer issue where there is a 3 min delay between when the executor claims to be executing a task and the command starts executing: https://buildbuddy-corp.slack.com/archives/C019DS52XAR/p1724833048078539?thread_ts=1710341219.838939&cid=C019DS52XAR

Add debug logging to runner

---

enterprise/server/content_addressable_storage_server_proxy/BUILD
enterprise/server/content_addressable_storage_server_proxy/content_addressable_storage_server_proxy.go
enterprise/server/content_addressable_storage_server_proxy/content_addressable_storage_server_proxy_test.go
enterprise/server/remote_execution/dirtools/BUILD
enterprise/server/remote_execution/dirtools/dirtools.go
server/remote_cache/cachetools/cachetools.go
server/remote_cache/content_addressable_storage_server/BUILD
server/remote_cache/content_addressable_storage_server/content_addressable_storage_server.go
server/util/rpcutil/rpcutil.go

This is a pretty simple implementation of GetTree. I looked into trying to reuse the implementation in content_addressable_storage_server, but I think that adding support for locally writing remotely read directories will add enough complexity that it's not warranted, at least for now.
I also refactored the three instances of `gRPCMaxSize` out into `rpcutil`, using the lower of the two values defined in the code, rather than adding a fourth redundant definition of this constant.

Serve GetTree requests out of the local cache via BatchReadBlobs

---

enterprise/server/cmd/ci_runner/main.go
proto/invocation.proto
server/backends/invocationdb/invocationdb.go
server/build_event_protocol/build_event_handler/build_event_handler.go
server/build_event_protocol/event_parser/event_parser.go
server/buildbuddy_server/buildbuddy_server.go
server/interfaces/interfaces.go
server/tables/tables.go
server/util/clickhouse/schema/schema.go

This PR adds the concept of a "run ID" - a unique identifier for each invocation retry attempt - so that we can fetch children invocations for only the current retry attempt
We should not fetch children invocations using the parent's invocation ID, because if the parent has been retried, we will fetch children from all retry attempts

Add run ID to invocations to link parent invocation attempts with children

---

cli/remotebazel/remotebazel.go

While debugging remote bazel, it can sometimes be easier to recommend customers use the Run RPC instead of the CLI. Log the JSON payload so that it's easier to use 

[RB] Log the run request

---

enterprise/server/backends/authdb/authdb_test.go
enterprise/server/backends/pebble_cache/pebble_cache_test.go
enterprise/server/crypter_service/crypter_service_test.go
enterprise/server/remote_execution/containers/firecracker/firecracker_performance_test.go
enterprise/server/remote_execution/copy_on_write/copy_on_write_test.go
enterprise/server/remote_execution/runner/runner_test.go
enterprise/server/scheduling/task_router/task_router_test.go
enterprise/server/test/integration/remote_execution/rbetest/rbetest.go
enterprise/server/test/webdriver/invocation/invocation_test.go
enterprise/server/util/dsingleflight/dsingleflight_test.go
enterprise/tools/rbeperf/rbeperf.go
enterprise/tools/vmstart/vmstart.go
server/remote_cache/scorecard/scorecard_test.go
server/util/consistent_hash/consistent_hash_test.go
server/util/lockingbuffer/lockingbuffer_test.go
server/util/random/random.go
tools/probers/bazelrbe/bazelrbe.go

See https://pkg.go.dev/math/rand#Seed for more info
```
If Seed is not called, the generator is seeded randomly at program startup.
Prior to Go 1.20, the generator was seeded like Seed(1) at program startup. To
force the old behavior, call Seed(1) at program startup. Alternately, set
GODEBUG=randautoseed=0 in the environment before making any calls to functions in
this package.
Deprecated: As of Go 1.20 there is no reason to call Seed with a random value.
Programs that call Seed with a known value to get a specific sequence of results
should use New(NewSource(seed)) to obtain a local random generator.
```
Since we don't use `rand.Seed()` to generate deterministic randomized value, there
is no need too replace it with `Rand.Seed()`.
Remove all `rand.Seed()` calls.

remove usage of rand.Seed()

---

enterprise/server/backends/distributed/distributed.go

Comment looks like it was copied from another redis flag.

Fix `cache.distributed_cache.redis_target` comment

---

.bazelrc
buildbuddy.yaml

This has been fixed to be compatible with blake3.

Workflows: re-enable remote downloader

---

deps.bzl
enterprise/server/remote_execution/containers/podman/BUILD
enterprise/server/remote_execution/containers/podman/podman.go
enterprise/server/remote_execution/containers/podman/podman_test.go
enterprise/server/test/integration/podman/BUILD
enterprise/server/test/integration/podman/podman_test.go

This PR should fix the memory corruption bug ("corrupted size vs. prev_size") mentioned in https://github.com/buildbuddy-io/buildbuddy-internal/issues/3631
It turns out that `podman-static` includes its own versions of `crun` and `runc` under `/usr/local/bin`, which has higher precedence in PATH than the ones we provision under /usr/bin. So when upgrading to the latest `podman-static` release, we inadvertently upgraded `crun` to version 1.16.1, which has a [double-free bug](https://github.com/containers/crun/issues/1537). This was causing the "corrupted size vs. prev_size" errors we were seeing in some teed actions.
The double-free bug won't be fixed until 1.16.2, so this PR effectively just downgrades us to 1.15 until 1.16.2 is available. …

Don't use container runtimes bundled with podman-static release

---

server/test/integration/build_event_protocol/BUILD

We have 6 tests funcs under the target.
Let's try running each one in a separate shard to avoid any concurrency
issue.

integration/bep: bump test shard to 6

---

server/build_event_protocol/build_event_handler/build_event_handler.go

When Bazel drop the grpc connection, ignore the log write error.

Build Event Handler: don't log error when context is canceled

---

server/metrics/metrics.go
server/remote_cache/content_addressable_storage_server/content_addressable_storage_server.go

Store tree cache blobs separately from pointers.
The blobs themselves are flattened lists of a directory and all it's children: these are stored in the cache. Separately, a pointer based only on the directory name and a seed is stored in the action cache: this points to the blob.
Also, update the tree cache seed.

2layer treecache

---

enterprise/server/cmd/ci_runner/main.go

Currently workflows don't log the git cleanup command to the UI, so it's difficult to determine how long it took to run and the actual end time of the execution 
How it will look after this change (Currently it only has the top "Running git maintenance..." line)

[ci_runner] Log end time of the script execution

---

tools/metrics/grafana/dashboards/buildbuddy.json
tools/metrics/grafana/dashboards/raft.json

1. Add heap size graph for raft dashboard
2. in main dashboard, group the heap size by namespace to seperate out
buildbuddy-dev and raft-dev metrics.

[raft] add heap size graph in raft dashboard

---

server/remote_asset/fetch_server/fetch_server.go

There is a pebble_db_handle_leak alert this morning indicating Reader() is not
properly closed.

close reader in fetch server

---

app/invocation/BUILD
app/invocation/child_invocation_card.tsx
app/invocation/child_invocations.tsx
app/invocation/invocation.tsx
app/invocation/invocation_model.tsx
cli/remotebazel/BUILD
cli/remotebazel/remotebazel.go
enterprise/server/cmd/ci_runner/main.go
enterprise/server/test/integration/remote_bazel/BUILD
enterprise/server/test/integration/remote_bazel/remote_bazel_test.go
proto/build_event_stream.proto
server/build_event_protocol/build_event_handler/build_event_handler.go

This PR re-enables two PRs that support showing child invocations in the UI for workflows with bash commands
- Revert "Revert "[ci_runner] Fetch child invocations from the db instead of BES events" (#7305)"
- Revert "Revert "[ci_runner] Populate child invocation cards in UI for bazel commands in bash" (#7298)"

Fetch child invocations by run ID to account for retries

---

enterprise/server/remote_execution/execution_server/execution_server.go
enterprise/server/scheduling/priority_queue/priority_queue.go
enterprise/server/scheduling/priority_task_scheduler/priority_task_scheduler_test.go
proto/scheduler.proto

Allow users to pass `--remote_execution_priority` to set relative action priorities within their group. Per the remote API spec, a higher priority value means that the action should be executed later. For now, we limit values to be between -1000 and 1000.

Allow groups to set action priorities within their own queues

---

enterprise/server/backends/pebble_cache/pebble_cache_test.go
enterprise/server/selfauth/selfauth.go
enterprise/tools/rbeperf/rbeperf.go
tools/probers/bazelrbe/bazelrbe.go

For more info: https://pkg.go.dev/math/rand#Read
```
Deprecated: For almost all use cases, crypto/rand.Read is more appropriate.
If a deterministic source is required, use math/rand/v2.ChaCha8.Read.
```
Replace it with crypto/rand.

math/rand: replace rand.Read with crypto/rand

---

enterprise/server/remote_execution/filecache/filecache_test.go

Passes with `--runs_per_test=1000` now.

Deflake TestFilecache

---

server/test/integration/build_event_protocol/BUILD

build_event_protocol_test has been flaky on macOS - increase the test size + timeout to try and deflake.

Increase size+timeout of BEP test

---

server/metrics/metrics.go
server/remote_cache/content_addressable_storage_server/BUILD
server/remote_cache/content_addressable_storage_server/content_addressable_storage_server.go

by my read, we are basically always killing the trecache write content via a direct `defer cancelFunc()` call (we never actually make it to the block of code where we wait on the cache write error group)
this change should make it so that we return the rpc but hang onto the context for up to a second to finish cache writes.

actually wait for treecache writes to finish.

---

tools/metrics/grafana/dashboards/buildbuddy.json
tools/metrics/grafana/dashboards/raft.json

Remove raft eviction graphs from main dashboard in dev.
Add raft eviction graphs in Raft dashboard.

add eviction graph to raft dashboard

---

enterprise/server/remote_execution/containers/ociruntime/ociruntime.go
enterprise/server/remote_execution/containers/ociruntime/ociruntime_test.go
server/util/networking/BUILD
server/util/networking/networking.go
server/util/networking/networking_test.go

* Adds a `ContainerNetworkPool` object that allows pooling networks for OCI containers only (*)
* When adding networks to the pool, we unassign the IP so it does not immediately get reused. This also deletes the default route.
* When taking networks from the pool, we assign a new IP as well as a new default route.
* When the executor shuts down, all pooled networks are cleaned up, and new networks may not be added to the pool.
Tested performance by running 1000 actions via 32 concurrently running `bb execute` commands, where each action just runs `ping -c1 8.8.8.8`
Results:
- Pooling disabled: 53s
- Pooling enabled: 6.9s
(*) It should be possible to also do this for VM networks, but it will take a bit of refactoring to do in a clean way, since Firecracker's setup and cleanup logic is very …

Implement container network pooling

---

server/remote_cache/content_addressable_storage_server/content_addressable_storage_server.go

improve debug logging a bit, too

properly detect when treecache finalization context exceeds deadline

---

.gitignore
rules/yarn/index.bzl

This change allows us to do
```
cd website && bazel run //website:start
```
instead of having to run the target from the workspace root dir.
Also tell git to ignore the left over exec log.

website: add support to run from within the directory

---

server/backends/invocationdb/invocationdb.go
server/build_event_protocol/build_event_handler/build_event_handler.go
server/tables/tables.go
server/util/clickhouse/clickhouse.go
server/util/clickhouse/schema/BUILD
server/util/clickhouse/schema/schema.go
server/util/clickhouse/schema/schema_test.go

This was originally added so that we could fetch child invocations for a parent invocation. However it didn't work well if the parent invocation was retried. Went with this approach instead: https://github.com/buildbuddy-io/buildbuddy/pull/7333

Clean up ParentInvocationID column

---

enterprise/server/remote_execution/containers/ociruntime/ociruntime.go

Planning to enable OCI in prod tomorrow, but we haven't tested network pooling thoroughly yet with teed traffic, so disable it for now.

Turn OCI net pooling off by default

---

server/xcode/xcode_darwin.go

Today when we provision and start up mac executors we do a bunch of stuff to install the OS and Xcode and simulators, and then start up the executor on the machine. However, if any of the prerequisite steps, like installing the OS or Xcodes, fail then we just skip 'em and then the running executor won't be able to serve some RBE requests because it doesn't have all of the correct dependencies. This PR is the first of two that'll make starting the executor fail if any of the desired Xcodes aren't present on the host machine, which is better than quietly starting up and failing to serve RBE requests. It adds a new flag, `--executor.required_xcode_versions` that specifies a comma-delimited list of Xcode versions that must be present on the host system for the executor to come up healthy. …

Don't start executor if expected Xcode versions are not present

---

app/invocation/invocation.tsx

Now that live-streaming invocation logs is enabled, we are constantly triggering `componentDidUpdate` which calls `scheduleRefetch`. That keeps calling `clearTimeout`, so `timeoutRef` the function to fetch the invocation never gets called
I noticed this because workflows should refetch their child invocations to display on the UI and I noticed they weren't updating

Fix refetching invocation with live-streaming invocation logs

---

enterprise/server/raft/store/store.go

[raft] close the db and stop replicaInitStatusWaiter when we close the store

---

enterprise/server/backends/pebble_cache/pebble_cache.go

pebble-cache: remove unused accesses from partitionEvictor

---

enterprise/server/raft/store/store.go
enterprise/server/raft/testutil/BUILD
enterprise/server/raft/testutil/testutil.go

In raft/store, use the clock from the environment. This will allow me to share
a fake clock between raft_cache and raft_store without adding a new argument to
store.New.

[raft] use clock from the env

---

.gitignore
rules/yarn/index.bzl

This appears to be breaking dev autopush: https://github.com/buildbuddy-io/buildbuddy-internal/actions/runs/10798433205/job/29951922712
```
/bin/bash: line 6: cd: $BUILD_WORKSPACE_DIRECTORY/website: No such file or directory
```

Revert "website: add support to run from within the directory (#7399)"

---

enterprise/server/raft/replica/replica.go
proto/raft.proto

In order to move atime update to raftCache from replica, we need to know know
last access time in findMissing because when we send atime update we want to
check if last access time is older than a threshold.

[raft] set last access time in find response

---

enterprise/server/atime_updater/BUILD
enterprise/server/atime_updater/atime_updater.go
enterprise/server/atime_updater/atime_updater_test.go
enterprise/server/byte_stream_server_proxy/BUILD
enterprise/server/byte_stream_server_proxy/byte_stream_server_proxy.go
enterprise/server/byte_stream_server_proxy/byte_stream_server_proxy_test.go
enterprise/server/cmd/cache_proxy/BUILD
enterprise/server/cmd/cache_proxy/cache_proxy.go
enterprise/server/content_addressable_storage_server_proxy/BUILD
enterprise/server/content_addressable_storage_server_proxy/content_addressable_storage_server_proxy.go
enterprise/server/content_addressable_storage_server_proxy/content_addressable_storage_server_proxy_test.go
server/environment/environment.go
server/interfaces/interfaces.go
server/real_environment/real_environment.go

Whoops, this PR turned out a bit bigger than I expected. Most of it's tests, though, so hopefully it's still palatable but let me know if not.
This PR adds an `AtimeUpdater` interface and implementation that exposes functions for enqueueing atime updates to be written to the remote cache. This is intended to address the issue that artifacts served out of the Cache Proxy's local cache won't have their remote atimes updated and thus may expire prematurely. The `AtimeUpdater` is best effort and will drop requested updates if the number of pending updates exceeds flag-configured thresholds. Internally, it maintains a set of "updates" (effectively FindMissingBlobsRequests) per group, with one update per instance-name/digest-type per group. It flushes these to the remote cache in a round robin …

Cache Proxy: Update remote-cache-atime of locally-accessed cache entries

---

enterprise/server/remote_execution/containers/firecracker/firecracker.go
server/util/networking/BUILD
server/util/networking/networking.go
server/util/networking/networking_test.go

This PR is a precursor to creating a `VMNetwork` struct to consolidate the setup/cleanup logic for firecracker VM networks so that it matches the new `ContainerNetwork` struct more closely. Having a `VMNetwork` struct will make it a little bit cleaner to introduce pooling logic for both types of networks, since they'll expose similar interfaces. It should also just make the code more consistent, since the firecracker networking logic has lots of details that are unnecessarily exposed to `firecracker.go`, while the OCI `ContainerNetwork` API is much more minimal. Having a `VMNetwork` struct with a minimal interface should help remove some of the complexity from `firecracker.go`.
---
* Refactor net namespaces so that they are represented as a struct:
* When passing around the net namespaces …

Minor cleanup/refactor of namespaces + veth pair names

---

app/invocation/invocation.tsx

Also remove the subtitle - this subtitle also makes it sound more "technical" than it is

Remove 'advanced' label from runner output heading

---

deps.bzl
dockerfiles/executor_image/Dockerfile
enterprise/server/cmd/executor/BUILD

- **update docker, docker buildx, and containerd in executor dockerfile**
- **don't have to paste over `containerd` anymore, yay**
Still waiting for a `buildx-plugin` release to fix the last instance of the recent `CRITICAL` CVE, and when `runc` finally releases 1.2.0 we'll want to update `podman-static` again to pick up all the fixes when they [finally upgrade](https://github.com/containers/podman/issues/19795).
Other than that, we have the obvious problem of `docker-credential-gcr` never being updated again. We should probably address that at some point.

Update docker in the executor to pick up recent security fixes

---

enterprise/server/cmd/ci_runner/main.go
enterprise/server/remote_execution/commandutil/commandutil.go
enterprise/server/remote_execution/container/container.go
enterprise/server/remote_execution/containers/bare/BUILD
enterprise/server/remote_execution/containers/bare/bare.go
enterprise/server/remote_execution/runner/runner.go

This PR reverts 2 debug logging PRs, as we have narrowed in on the source of the problem.
The third commit includes some changes from those PRs I would like to maintain.
- Revert "[ci_runner] Add more debug logs (#7379)"
- Revert "Add debug logging to runner (#7324)"

Clean up ci_runner debug logs

---

server/metrics/generate_docs.py

Fixes a warning about invalid escape sequence `\s`. This is supposed to be interpreted as the whitespace wildcard by the regex implementation, not as a special character by the python interpreter, so we just make it a raw string.

Add missing `r` to would-be python raw string for regex

---

enterprise/server/raft/store/store.go

[raft] When stop the store, usage tracker should also be stopped

---

WORKSPACE
WORKSPACE.bzlmod

It seems like AWS has updated their cert bundle.
Let's also update ours.

workspace: upgrade aws cert bundle sha

---

website/package.json
website/theme/BlogTagsPostsPage/index.tsx
website/yarn.lock

Docusaurus v3.0.0 locks us into a vulnerable version of `path-to-regexp'

Update docusaurus to unblock buildbuddy-io/buildbuddy/security/dependabot/170

---

server/remote_cache/digest/BUILD
server/remote_cache/digest/digest.go

We saw `Digest <nil> not found` internally and I also saw this while looking at some customer executions.
Specifically the error I saw was `"rpc error: code = FailedPrecondition desc = Digest <nil> not found"`
Based on this error message I think this happens when a nil digest is passed to `MissingDigestError()`. Log a stack trace when this happens so we can find the misbehaving caller.

Log stack trace to debug nil digest error

---

enterprise/server/backends/distributed/distributed.go
enterprise/server/backends/pebble_cache/pebble_cache.go

The default of `cache.distributed_cache.lookaside_cache_ttl` is 15 minutes, and
it's supposed to be << `atime_update_threshold`. but the default of 
`cache.pebble.atime_update_threshold` is 10 minutes.

change default lookaside_cache_ttl to 1 minute

---

docs/rbe-setup.md

BAZEL_DO_NOT_DETECT_CPP_TOOLCHAIN is used in a repository rule so
setting it in --action_env will have no effect.
Use --repo_env instead and add documentation for it
Properly document --action_env and --test_env as well while we are at
it.

docs/rbe-setup: fix wrong usage of action_env

---

server/remote_asset/fetch_server/fetch_server.go
server/remote_asset/fetch_server/fetch_server_test.go

In addition to the checksum.sri qualifier from remote api spec,
Bazel includes it's own set of qualifiers to each FetchBlob requests.
https://cs.opensource.google/bazel/bazel/+/master:src/main/java/com/google/devtools/build/lib/remote/downloader/GrpcRemoteDownloader.java;l=76-85;drc=618c0abbfe518f4e29de523a2e63ca9179050e94
This change adds initial support for the http_header qualifier as well
as acknoledge the existence of bazel.canonical_id header (without
actually using it). Relevant tests were also added to demonstrate the
current behavior.
In a future patch, we may start rejecting unknown qualifiers as
recommended by the Remote Asset API spec and thus, flip the assertions
in the test. See https://github.com/bazelbuild/remote-apis/issues/301
for more info.
Another change to consider in …

fetch_server: add support for bazel qualifiers

---

enterprise/server/remote_execution/containers/ociruntime/ociruntime.go
enterprise/server/remote_execution/containers/ociruntime/ociruntime_test.go

- Add `--executor.oci.image_cache_root` flag which sets the directory where image layers are cached.
- Make the image cache versioned - store layers under a `v1/` subdirectory so that if we make backwards-incompatible changes to the storage format, we can migrate more smoothly.

Make OCI image cache directory versioned and configurable

---

enterprise/server/remote_execution/containers/ociruntime/ociruntime.go
enterprise/server/remote_execution/containers/ociruntime/ociruntime_test.go

Move the overlayfs temp directories (workdir, upperdir) into the OCI bundle directory so that they get cleaned up during `Remove()`.

Ensure overlay tmp dirs get cleaned up

---

enterprise/server/backends/pebble_cache/pebble_cache.go
server/util/approxlru/BUILD
server/util/approxlru/approxlru.go

When we test LRU, we usually create a fake clock; but it was not passed into
approxLRU, so the reported age in the logs are confusing since it was calculated
based on the real clock.

add clock to approxlru

---

enterprise/server/raft/cache/BUILD
enterprise/server/raft/cache/cache.go

Before the server stopped, we wanted to flush the atime. We need a little extra
time otherwise the last flush will fail with context canceled.

[raft] extend deadline when updating atime

---

MODULE.bazel
WORKSPACE
WORKSPACE.bzlmod
buildpatches/com_google_protobuf_18241.patch
buildpatches/com_google_protobuf_18242.patch
buildpatches/com_google_protobuf_18243.patch

~Need to confirm this builds on all of our production platforms; 27.3 did not and blocked release last week.~
All warnings are removed; builds both with and without bazelmod.

Update protobuf from 26.0 -> 28.1 and absl to latest lts

---

enterprise/server/backends/authdb/authdb.go

@bduffany pointed out that this was a better way to do `LEFT JOIN`s. Should make it more clear what's happening in the query and remove the possibility of actual empty fields being mistaken for missing rows (even though that's very unlikely here).

Use pointer instead of struct for left joined tables

---

enterprise/server/remote_execution/containers/firecracker/firecracker.go

Set firecracker default CPU overprovisioning to max

---

enterprise/server/tasksize/tasksize.go

- For firecracker tasks, the task sizer now returns CPU estimates based on the last recorded size, but sets the memory estimate to 0.
- The scheduler server handles this properly [here](https://github.com/buildbuddy-io/buildbuddy/blob/6d565dbb90a895d525ea79e1018108f0d870ce54/enterprise/server/scheduling/scheduler_server/scheduler_server.go#L425-L462) - it checks EstimatedCPU and EstimatedMemory separately on both the recorded size + modeled size, and ignores them if they are 0, using the statically estimated size instead.
- The tensorflow model is still completely disabled for Firecracker tasks ([here](https://github.com/buildbuddy-io/buildbuddy/blob/6d565dbb90a895d525ea79e1018108f0d870ce54/enterprise/server/tasksize_model/tasksize_model.go#L209-L213))
- We're already storing task sizes …

Enable task sizer for Firecracker CPU

---

MODULE.bazel
codesearch/posting/BUILD
codesearch/posting/posting.go
codesearch/posting/posting_test.go
deps.bzl
go.mod
go.sum

StreamVByte custom:
BenchmarkListSerializationPosting
BenchmarkListSerializationPosting-24      	     100	  13748341 ns/op	 7682248 B/op	       4 allocs/op
BenchmarkListDeserializationPosting
BenchmarkListDeserializationPosting-24    	     442	   2313002 ns/op	 9644653 B/op	       5 allocs/op
Roaring (w/ ToArray())
BenchmarkListSerializationPosting
BenchmarkListSerializationPosting-24      	     160	   7717982 ns/op	 5730012 B/op	     525 allocs/op
BenchmarkListDeserializationPosting
BenchmarkListDeserializationPosting-24    	     446	   2603957 ns/op	 6942231 B/op	     149 allocs/op
Roaring (no ToArray()):
BenchmarkListSerializationPosting
BenchmarkListSerializationPosting-24      	     158	   7183902 ns/op	 5730642 B/op	     525 allocs/op
BenchmarkListDeserializationPosting …

With consecutive doc IDs, bring back roaring bitsets

---

enterprise/server/byte_stream_server_proxy/BUILD
enterprise/server/byte_stream_server_proxy/byte_stream_server_proxy.go
enterprise/server/byte_stream_server_proxy/byte_stream_server_proxy_test.go

The current strategy of just smashing "/uploads/00000000-0000-0000-0000-000000000000" on the front breaks instance names, as illustrated in the expanded byte_stream_server_proxy_test.

Fix ByteStreamProxyServer resource name rewriting

---

tools/metrics/grafana/dashboards/raft.json

- Latency for grpcs like SyncPropose, SyncRead
- Partition Usage for the cache
- Last eviction age, and eviction age per partition

Add more graphs for raft

---

enterprise/server/content_addressable_storage_server_proxy/content_addressable_storage_server_proxy.go

context.Background() doesn't have creds so these writes were always failing in dev. Whoops!

Use the correct context for local CAS proxy writes.

---

MODULE.bazel
codesearch/index/index.go
codesearch/posting/posting.go
codesearch/token/BUILD
codesearch/token/token.go
deps.bzl
go.mod
go.sum

- Don't allocate giant sparse sets in the tokenizer
- Don't copy between []uint64 and posting lists
- Use less memory by encoding directly into the pebble batch without additional allocs

Codesearch: use less memory when indexing

---

enterprise/server/backends/pebble_cache/pebble_cache.go
enterprise/server/util/pebble/BUILD
enterprise/server/util/pebble/pebble.go

This allows us to reuse this struct in raft.
Also pebble.EventListener is already claimed so I renamed to
pebble.MetricsCollector

move pebble_cache.pebbleEventListener to pebble.MetricsCollector

---

WORKSPACE.bzlmod

this is already a bazel module declared in MODULE.bazel file

bzlmod: remove duplicated platforms archive

---

enterprise/server/remote_execution/containers/firecracker/BUILD
enterprise/server/remote_execution/containers/firecracker/firecracker_test.go
server/testutil/testnetworking/BUILD
server/testutil/testnetworking/testnetworking.go
server/util/networking/networking.go

Follow-up from https://github.com/buildbuddy-io/buildbuddy/pull/7429
* Add optional `flock`-based IP range locking to prevent concurrent test shards from trying to use the same IP range concurrently.
* This is useful for firecracker tests, as well as running multiple firecracker executors locally. 
* Don't try to clean up network namespaces in tests, because they might be in use.
* I don't expect that too many of these will accumulate, but if it does happen, we can find a way to clean up "orphaned" namespaces, maybe by associating them with lockfiles.
* Don't try to clean up the shared executor root directory in tests either, to prevent converted ext4 image files from disappearing mid-test.
* Added a TODO to provision these images as data deps of the test instead of converting during the …

Allow multiple firecracker test shards to run concurrently on a single machine

---

enterprise/server/backends/authdb/authdb.go
enterprise/server/backends/userdb/userdb_test.go
proto/api_key.proto
server/buildbuddy_server/buildbuddy_server.go
server/interfaces/interfaces.go

- Allow assigning API key capabilities when creating a key for a user other than the authenticated user (ORG_ADMIN keys only)
- Allow listing keys for users other than the authenticated user (ORG_ADMIN keys only)

Allow a few more operations with user key management

---

enterprise/server/util/cacheproxy/cacheproxy.go
server/util/bytebufferpool/bytebufferpool.go

To prevent heap from possibly growing out of control -- use variable sized write buffers in cacheproxy.

Pool bufio.Writers of different sizes

---

enterprise/server/remote_execution/containers/ociruntime/ociruntime.go
enterprise/server/remote_execution/containers/ociruntime/ociruntime_test.go

We can use this to set an upper bound on CPUs so that the CPU count looks uniform regardless of the underlying hardware.
https://github.com/buildbuddy-io/buildbuddy-internal/issues/3853

Add optional CPU limit to OCI runtime.

---

MODULE.bazel
WORKSPACE
WORKSPACE.bzlmod

Cleanup usage of gnu_cpio, we rewrote it in Go a while ago.
Remove the protobuf deps in WORKSPACE.bzlmod, they should be
automatically pulled by bzlmod from bcr.
Move nogo-analyzer from WORKSPACE.bzlmod to MODULE.bazel as a POC for
using repo rules inside the MODULE.bazel file.

WORKSPACE: cleanup and use http_archive in MODULE.bazel

---

app/util/BUILD
app/util/remote_runner.tsx
enterprise/server/cmd/ci_runner/main.go

In the ci_runner, we generate a bazelrc that points to the correct BES backend. However our .bazelrc (in the buildbuddy repo) contains
```
common --bes_results_url=https://app.buildbuddy.io/invocation/
common --bes_backend=grpcs://remote.buildbuddy.io
```
which overrides that and always points to prod. We prioritize the workspace bazelrc over the ci_runner generated one. Explicitly add the bes flags to point to the correct server in dev and other envs
Also set fallback branch keys on the remote requests 

[RB] Target correct BES backend and add fallback keys to remote bazel buttons

---

tools/fix_go_deps.sh

The previous version caused an error if the CI env var was unset.

Fix checkstyle take 3

---

enterprise/server/remoteauth/remoteauth.go

Protect accesses to the remote authenticator's JWT cache with a mutex

---

MODULE.bazel
WORKSPACE
WORKSPACE.bzlmod
buildpatches/bzlmod_rules_nodejs.patch
rules/typescript/index.bzl

Upgrade swc to the latest version so that we are not stuck with the
older aspect transitive dependencies such as their aspect_bazel_lib.
This should unlock us from experimenting with other aspect rules such as
rules_oci.

Aspect_rules_swc: upgrade to v2.0.0

---

cli/parser/parser.go
cli/test/integration/cli/BUILD
cli/test/integration/cli/cli_test.go

Run `bazel help` in its own `output_base` so that we don't kill any running bazel server instance in the current workspace.

CLI: prevent option schema parsing from killing existing server

---

tools/metrics/grafana/dashboards/buildbuddy.json

This PR adds a graph displaying these two metrics, which track performance of the async remote atime updater: https://github.com/buildbuddy-io/buildbuddy/blob/456426d2e0193f062162a681ec2ae414b0f20bf6/server/metrics/metrics.go#L2789-L2809

Cache Proxy: add grafana graph tracking atime_updater performance

---

enterprise/app/code/code_v2.tsx

This prevents the line number from getting lost during navigation.

Preserve window hash when navigating in editor

---

server/cache_proxy/cache_proxy.go

Fixes a small regression from https://github.com/buildbuddy-io/buildbuddy/pull/7563
The PR restructured some things so that we can use `log.Ctx*` to get more helpful logs. But it introduced a bug - the previous code was correctly propagating _all_ gRPC metadata to the remote cache (i.e. all `--remote_header` values) but that PR made it so that we only propagate the metadata allowed by the RPC interceptors (API key, bazel requestmetadata, etc.)

Fix --remote_header propagation in CLI local cache proxy

---

cli/cmd/bb/bb.go
cli/sidecar/sidecar.go
server/build_event_protocol/build_event_server/build_event_server.go
server/cache_proxy/cache_proxy.go

- Log slow write warnings periodically instead of just once
- Add some info-level logs for BES proxying lifecycle
- Dump all logs on failure, not just warning/info

Add more diagnostics for CLI BES timeouts

---

enterprise/server/raft/store/BUILD
enterprise/server/raft/store/store.go
enterprise/server/raft/usagetracker/BUILD
enterprise/server/raft/usagetracker/usagetracker.go

1. DiskCachePartitionUsage should report local usage instead of global usage.
Right now per-pod partition usage is the same. It's less useful to monitor.
We can sum them together if we want to know the global partition usage.
2. when we calculate store usage, use file system free and used instead of
parition size.

[raft] size

---

app/invocation/cache_requests_card.tsx
app/target/target_v2.tsx
app/util/BUILD
app/util/remote_runner.tsx
enterprise/server/cmd/ci_runner/main.go

* Add a missing space in a command
* Only add bazel flags to bazel commands
* Support platform properties
* For the bb explain button, use commit shas rather than branches when comparing 2 invocations

[RB] Fix a couple bazel button bugs

---

enterprise/server/invocation_search_service/invocation_search_service.go
proto/BUILD
proto/invocation.proto
proto/stat_filter.proto
server/util/filter/BUILD
server/util/filter/filter.go
server/util/filter/filter_test.go

this is partially done, but there's not really a need to flag-guard it.
leaving some todos to add remaining filter types as they're a little different from the primary ones in this pr.

server-side changes for supporting generic filters in invocation search 

---

enterprise/app/review/review_list.tsx

For browsing PRs, I prefer our review listing over GitHub's, so I use the reviews page heavily. But after clicking a review, I always click the little GitHub icon to go to the pull requests page, because I find the GitHub review page easier to use.
This change makes it so that clicking a review with Ctrl+Shift+Click goes straight to the GitHub PR page (in a new tab), to save a little bit of time.

reviews: add shortcut to go straight to GitHub PR page

---

enterprise/server/remote_execution/containers/firecracker/firecracker.go

theoretically this should help keep snapshot size down because we'll wipe freed memory back to zeroes (to help with squishing down pages / compression)
@tylerwilliams flagged this, i'm just mailing it

enable init_on_alloc and init_on_free in firecracker vms

---

app/invocation/invocation_model.tsx

Context: https://buildbuddy-corp.slack.com/archives/C03JL0YT6G5/p1727292745614949

Fix artifact downloads in UI when remote_bytestream_uri_prefix is set

---

app/invocation/invocation_model.tsx

In the last PR I switched to `new URL()` for parsing the bytestream URI prefix, thinking it'd be cleaner than manually parsing... but when testing that approach, I think I was somehow using stale JS :skull: `new URL()` totally fails to parse `"localhost:1985"` or even `"grpc://localhost:1985"`

Fix bytestream_uri_prefix parsing

---

.bazelrc

This should make our Go tests executions a bit more parallelized.

bazelrc: run validation action as aspect

---

enterprise/server/cmd/executor/BUILD
enterprise/server/cmd/executor/executor.go
server/resources/resources.go

If firecracker is disabled but firecracker snapshot sharing is enabled, then the current code will unnecessarily reserve 10GB of the executor's schedulable memory for mmapped chunks.
This is not an issue today, but would cause problems once we enable CoW by default, which is something we want to do eventually.

Fix mmap resource allocation logic

---

server/remote_cache/content_addressable_storage_server/content_addressable_storage_server.go
server/remote_cache/directory_size/directory_size.go

this waste currently accounts for more than half of the cpu used by treesplitting.

don't pointlessly recompute digests when splitting treecache trees

---

enterprise/server/raft/leasekeeper/leasekeeper.go

Reverts buildbuddy-io/buildbuddy#7538
This causes Write to slow down significantly, and uses a lot of CPUs.

Revert "[raft] only buffer one update per lease agent"

---

enterprise/server/remote_execution/platform/platform.go
enterprise/server/remote_execution/platform/platform_test.go

All occurrences of  `{{region}}` in the provided container image name will be replaced with the value of `--executor.container_registry_region` in the executor that runs the task.

Add support for {{region}} template string in container image names

---

enterprise/server/remote_execution/execution_server/execution_server.go
enterprise/server/remote_execution/executor/executor.go
enterprise/server/remote_execution/operation/operation.go
enterprise/server/test/integration/remote_execution/rbetest/rbetest.go
enterprise/server/test/integration/remote_execution/remote_execution_test.go

This allows us to show information like the executor host ID when the executor fails due to some transient issue.
**Related issues**: http://go/b/937
Originally, I was going to use the Operation.metadata field for this, but I think it's clunky, and with a few small changes, it seems safe to return an Operation.result even when the execution failed.
The executions tab used to look like 
Now it looks like 
Note that the executor host ID is filled in.

Return execution metadata even when execution fails

---

enterprise/server/cmd/cache_proxy/cache_proxy.go

Cache Proxy: connect to proxied services via DialInternal instead of DialSimple

---

enterprise/server/workflow/config/config.go

Build: https://app.buildbuddy.io/invocation/99450de4-855d-4cff-8c29-4668e9f08823
Command: `blaze build --config=static --config=release --config=remote --@io_bazel_rules_go//go/config:static kythe/release:release`

Switch from kythe-v0.0.67d to kythe-v0.0.67f

---

enterprise/server/content_addressable_storage_server_proxy/BUILD
enterprise/server/content_addressable_storage_server_proxy/content_addressable_storage_server_proxy.go
enterprise/server/content_addressable_storage_server_proxy/content_addressable_storage_server_proxy_test.go

This is just conditionally reverting https://github.com/buildbuddy-io/buildbuddy/pull/7319/files behind a flag. The idea here is that `GetTree` is especially susceptible to cross-zone latency because every level of the tree that isn't cached incurs an addition roundtrip latency.

Cache Proxy: add a flag that makes Cache Proxy always serve GetTree requests from the remote, authoritative cache.

---

server/http/interceptors/interceptors.go
server/static/static.go

Go's `http` package automatically sets `Content-Type` based on file extensions (and possibly content, but only as a fallback), so we only need to set the header manually when not going through `http` methods.

server: Set `X-Content-Type-Options: nosniff`

---

enterprise/server/remote_execution/copy_on_write/copy_on_write_test.go

https://github.com/buildbuddy-io/buildbuddy-internal/issues/3918

Update copy_on_write test to avoid failures on baremetal executors

---

enterprise/server/test/integration/podman/BUILD

unfortunately this one sometimes butts up on a minute, so just doing `moderate` for now--300s instead of 900s

make podman_test timeout a little bit shorter

---

enterprise/server/raft/usagetracker/usagetracker.go

The current condition is localSize <= 0.2 * part.MaxBytes which is wrong, since
part.MaxBytes is the global maximum; instead of the maximum per server.
**Related issues**: https://github.com/buildbuddy-io/buildbuddy-internal/issues/3747

[raft] fix should sleep calculation.

---

app/app.tsx
app/root/root.css
server/http/csp/BUILD.bazel
server/http/csp/csp.go
server/http/interceptors/BUILD
server/http/interceptors/interceptors.go
server/libmain/BUILD
server/libmain/libmain.go
server/static/BUILD
server/static/static.go
static/index.html

The CSP allows at most the current origin (and subdomains) as well as a few inline scripts pinned by hashes.

server: Use a strict CSP for all pages

---

cli/remotebazel/remotebazel.go

* Fix a bug where we'd return an error if an API key wasn't set in .git/config
* Add some debug logging to clarify login logic

[RB] Improve login flow

---

enterprise/server/raft/usagetracker/usagetracker.go

should not overwrite OutOfRange error with Internal Error. This prevent
RunMultiKey retrying.
https://github.com/buildbuddy-io/buildbuddy-internal/issues/3747

[raft] fix eviction

---

enterprise/server/remote_execution/execution_server/execution_server.go
enterprise/server/remote_execution/execution_server/execution_server_test.go
enterprise/server/remote_execution/platform/platform.go
enterprise/server/scheduling/scheduler_server/scheduler_server.go
enterprise/server/scheduling/scheduler_server/scheduler_server_test.go
server/interfaces/interfaces.go

Context: https://buildbuddy-corp.slack.com/archives/C05GZM1EGM8/p1727895825533649
Our expectation (as well as one of our users' expectations) was that setting `use-self-hosted-executors=false` would override the org-level "Default to self-hosted executors" setting, but it turns out that this override behavior only works in one direction (i.e. when setting `use-self-hosted-executors=true`).
This PR makes it work as expected by updating the logic to consider whether `use-self-hosted-executors` was set explicitly or not.

Make use-self-hosted-executors=false work as expected

---

app/format/format.tsx
enterprise/app/auditlogs/auditlogs.tsx
enterprise/app/filter/filter.tsx
enterprise/app/filter/filter_util.tsx
enterprise/app/trends/summary_card.tsx

right now, if you pick, say, sep 10-15 in the date picker, the filter text winds up saying "sep 10-14".  it's been like this for a while.

fix incorrect date date range rendering in filters ui.

---

enterprise/server/test/integration/podman/podman_test.go

The unstable version has some weird behavior that affect how signal is
handled and failed our TestSignal test consistently.
Let's downgrade our image from latest to stable and pin it with a
SHA256.

integration/podman: pin busybox image to stable

---

WORKSPACE
buildpatches/protobuf.js_inquire.patch
server/http/interceptors/interceptors.go
static/index.html

* Allow dynamic loading of scripts such as Monaco via strict-dynamic
* Allow more image sources
* Add directives required by libsodium.js
* Patch out an unnecessary use of `eval`

server: Add more sources to the CSP

---

enterprise/server/invocation_stat_service/invocation_stat_service.go

don't count negative execution times in trends ui.

---

enterprise/server/remote_execution/executor/executor.go

As of github.com/buildbuddy-io/buildbuddy/pull/7596, when executions fail due to an error (and not the action failing), worker_start_timestamp is set, but worker_finish_timestamp is 0, which results in large negative durations.
Always set the completed time to at least the start time, and possibly some larger value. This will start counting usage for errored executions.

Ensure that worker_completed_timestamp is set

---

codesearch/cmd/server/BUILD
codesearch/cmd/server/server.go

This will allow for authed requests to the app (we need to read files from the cache) and let me remove that namespace hack from the buildbuddy app (can do it in codesearch directly instead).

Use remote authenticator in codesearch service

---

enterprise/server/remote_execution/containers/firecracker/firecracker.go
enterprise/server/remote_execution/execution_server/execution_server.go
enterprise/server/remote_execution/executor/executor.go
enterprise/server/remote_execution/platform/platform.go
enterprise/server/remote_execution/runner/runner.go
enterprise/server/remote_execution/snaploader/BUILD
enterprise/server/remote_execution/snaploader/snaploader.go
enterprise/server/remote_execution/workspace/workspace.go
enterprise/server/scheduling/scheduler_server/scheduler_server.go
enterprise/server/scheduling/scheduler_server/scheduler_server_test.go
enterprise/server/scheduling/task_router/task_router.go
enterprise/server/scheduling/task_router/task_router_test.go
enterprise/server/tasksize_model/tasksize_model.go
enterprise/server/test/integration/remote_execution/rbeclient/rbeclient.go
enterprise/server/test/integration/remote_execution/remote_execution_test.go
server/interfaces/interfaces.go

In REAPI v2.2, the usage of platform in Command was deprecated over in Action. Although most of the older REAPI clients, such as Bazel, are setting it in both, newer clients such as Buck2 would only set it in Action message.
This change replace most of existing command.GetPlatform() calls with action.GetPlatform() while using the command value as fallback.
This was heavily inspired by https://github.com/buildbuddy-io/buildbuddy/pull/7550, but with a few more changes.
I tried a simpler approach where we overwrite command.platform with action.platform, but because we read the original protos by digest in ExecutionServer.markTaskComplete, this doesn't work.
Closes buildbuddy-io/buildbuddy-internal#3863

reapi: favor platform set in Action over Command

---

enterprise/server/backends/authdb/authdb.go
enterprise/server/backends/userdb/userdb_test.go

**Related issues**: https://github.com/buildbuddy-io/buildbuddy-internal/issues/3907

Allow ORG_ADMIN keys to retrieve user API key values within the org

---

MODULE.bazel
WORKSPACE
WORKSPACE.bzlmod
deps.bzl
toolchains/BUILD

Introduce an extension which wrap around our install_static_dependencies
macro so that we can load all those deps from MODULE.bazel file.
Moved the remaining standalone http_archive and http_file to
MODULE.bazel.
Moved register_toolchains call to MODULE.bazel.
Remove unused all_content variable in both WORKSPACE file.
Remove sh_toolchain. We needed a custom sh_toolchain for rbe due to the issue reported in https://github.com/aspect-build/rules_swc/issues/20.
Now that we have upgraded rules_swc, we should be able to build without an explicit sh_toolchain registered.
Note: merge https://github.com/buildbuddy-io/buildbuddy-internal/pull/3922 first.

bzlmod: move things from WORKSPACE.bzlmod to MODULE.bazel

---

server/xcode/xcode_darwin.go

The current implementation where the executor fails to start if any of the required Xcode versions aren't configured makes it difficult to upgrade Xcode versions on the host system :-/

Change 'required_xcode_versions' to 'desired_xcode_versions' and make it log.Warning

---

enterprise/server/raft/txn/txn.go
enterprise/server/raft/txn/txn_test.go
proto/raft.proto

https://github.com/buildbuddy-io/buildbuddy-internal/issues/3932

[raft] rollback all statements when there is preparation error

---

enterprise/server/remote_execution/operation/operation.go

We don't have to check the type of `op.result` because `op.GetResponse` will return nil if the oneof is not a response (in other words, it's an unset or the error field variation is set)

Simplify operation.ExtractExecuteResponse

---

tools/metrics/grafana/dashboards/buildbuddy.json

In the executor pool panels, add charts showing the CPU usage of all of the pods' host nodes for all executor pods in each pool. This is useful for seeing the node CPU usage corresponding to a particular pod.

Add charts for executor node CPU usage by pod

---

codesearch/index/index.go
codesearch/server/server.go

Move log.Printf -> log.Infof
Remove some unnecessary logs

Clean up some logs in codesearch

---

proto/build_event_stream.proto
proto/failure_details.proto
proto/spawn.proto

Update all relevant Bazel protos.
Skip on the deprecations removal in spawn.proto as it would break our
existing code, which supports the older compact exec log format.

proto: update Bazel protos

---

MODULE.bazel
WORKSPACE
go.mod

Reference: https://github.com/golang/go/issues?q=milestone%3AGo1.23.2+label%3ACherryPickApproved

gosdk: upgrade to 1.23.2

---

WORKSPACE

In recent version of rules_go, `go_register_nogo` was changed to a macro
wrapper which apply a sane default for `includes` and `excludes`
packages to run nogo over. However, the `go_register_nogo` inside
`go_register_toolchains` that we are currently using was not the new
macro wrapper, but the original repository rule. As a result, we are
running nogo validation actions over external packages and made our
build slower, especially when using local execution.
Register nogo separately using the macro wrapper so we don't need to
validate nogo for external `go_repository` targets.
Upstream discussion: https://github.com/bazelbuild/rules_go/issues/4137

workspace: register nogo separately

---

server/config/config.go
server/util/flagutil/common/common.go

Some third-party flags don't support being set back to their string representation.

Don't try to set flag after expansion if value hasn't changed.

---

enterprise/server/raft/listener/BUILD
enterprise/server/raft/listener/listener.go
enterprise/server/raft/usagetracker/usagetracker.go
server/metrics/metrics.go

https://github.com/buildbuddy-io/buildbuddy-internal/issues/3963,
https://github.com/buildbuddy-io/buildbuddy-internal/issues/3962, https://github.com/buildbuddy-io/buildbuddy-internal/issues/3964
Also increase the default chan size for leader update and node ready.

[raft] monitor dropped listener events and eviction error

---

enterprise/server/cmd/cache_proxy/BUILD
enterprise/server/cmd/cache_proxy/cache_proxy.go

This is the simplest way to support peering between Cache Proxy servers.

Cache Proxy: make the local cache a distributed cache wrapping a pebble cache.

---

enterprise/server/backends/authdb/authdb.go
enterprise/server/backends/userdb/userdb.go
enterprise/server/backends/userdb/userdb_test.go
server/interfaces/interfaces.go
server/tables/tables.go
server/util/claims/claims.go

Groups are considered related if they have the same SAML Metadata URL.
Only keys for groups marked as 'parent' are allowed access to related groups.

Allow admin API keys for a 'parent' group to affect child groups.

---

enterprise/server/remote_execution/containers/firecracker/firecracker.go

This results in flakiness when running a lot of docker-in-firecracker actions concurrently.
Here's a run of `usage_test_mysql` with overprovisioning set to max (the current default): https://buildbuddy.buildbuddy.dev/invocation/59d2f757-f994-4c53-af0d-d9bde3a49614?target=%2F%2Fenterprise%2Fserver%2Fusage%3Ausage_test_mysql&targetStatus=7#470
And here's a run with overprovisioning set to 3 like we had before: https://buildbuddy.buildbuddy.dev/invocation/b11e9a45-f7b0-4b41-9cda-39de0659a93b?target=%2F%2Fenterprise%2Fserver%2Fusage%3Ausage_test_mysql&targetStatus=5
Opened https://github.com/buildbuddy-io/buildbuddy-internal/issues/3965 to remove this overprovisioning altogether, but I didn't want to make too drastic of a change just yet, so for now this PR is just setting the …

Set firecracker CPU overprovisioning back to 3 for now

---

tools/cacheload/cacheload.go

cacheload in raft-dev got fatal error "too many concurrent timer firings"

cacheload: use ticker instead of after

---

enterprise/server/backends/userdb/userdb.go
enterprise/server/buildbuddy_server/BUILD
enterprise/server/buildbuddy_server/buildbuddy_server_test.go
server/buildbuddy_server/buildbuddy_server.go

The new groups will inherit the SAML IDP Metadata URL of the original group.

Allow an Admin API key for a 'parent' group to create new groups.

---

.prettierrc
package.json
tools/checkstyle/checkstyle.sh
yarn.lock

Ran into this on ubuntu 2204 when trying get buildbuddy building on arm.
`jsxBracketSameLine` is deprecated, now just `bracketSameLine`: https://prettier.io/blog/2021/09/09/2.4.0.html#:~:text=This%20release%20renames%20the%20jsxBracketSameLine,such%20as%20class%20static%20blocks
`--loglevel` was renamed to `--log-level`

Upgrade prettier since the old one is incompatible with newer libc versions

---

server/util/disk/disk.go

This stat call isn't necessary, since os.MkDirAll first does a stat by itself.
This change does affect behavior a bit. Previously, if the path was a file, the function would return nil. Now it returns an error. As far as I can tell, this shouldn't matter in practice.
I don't think this will improve performance in dev or prod, since creating directories seems to be rare. But when running a local server without any directories, this doubles up the number of stat calls, and each one occupies a thread, making it more likely that the process dies because it tries to create more than 10k threads.

Remove os.Stat from disk.EnsureDirectoryExists

---

dockerfiles/rbe-ubuntu22-04/Dockerfile

Docker version > 24 currently can create images with mixed media types in the layers, which containerd does not handle gracefully and thus which do not work in GCP.

Pin docker version to 24 in RBE ubuntu 22.04

---

dockerfiles/rbe-ubuntu22-04/Dockerfile

This is a port of https://github.com/buildbuddy-io/buildbuddy/pull/7704/files which was merged while this 22.04 image was WIP.

Install en_US.UTF-8 locale in rbe-ubuntu22-04

---

.github/pull_request_template.md

This PR template results in `git log` being cluttered, since we enabled the GitHub setting to use the PR description as the commit message for PR squash+merge commits.

Remove PR template

---

MODULE.bazel
WORKSPACE
go.mod

Reverts buildbuddy-io/buildbuddy#7718 due to a newly introduced panic: https://go-review.googlesource.com/c/go/+/611496

Revert "gosdk: upgrade to 1.23.2"

---

proto/remote_execution.proto

Understanding the distribution of CPU usage (as opposed to just the average) may help us improve our task sizing model, and is also useful information to present to users in order to understand how effectively their actions are utilizing available resources.

Add CPU timeline to UsageStats proto

---

MODULE.bazel
WORKSPACE
enterprise/server/remote_execution/containers/ociruntime/BUILD
enterprise/server/remote_execution/containers/ociruntime/ociruntime.go
enterprise/server/remote_execution/containers/ociruntime/ociruntime_test.go

When the action required an image with more than 20 layers, our mount
will fail with
```
create OCI bundle: create rootfs: mount overlayfs: no such file or directory
```
After some digging, it seems like 20 is the current limit of the number
of lowerdir allowed in each mount call.
Add special logic to break down images with more than 20 layers into
groups of 20. For each group, create an overlayfs mount called
"merged<group-id>" in the same bundle dir. The final overlayfs will then
be composed of these "merged" groups as lowerdirs.

ociruntime: handle images with high layer count

---

enterprise/server/atime_updater/atime_updater.go

This metrics currently has values like "0" and "5." This PR switches to using the human-readable gRPC code as the value, e.g. "OK" or "NOT_FOUND," similar to the other gRPC graphs.

[Cache Proxy]: record human-readable gRPC response codes in atime-updater gRPC metric

---

app/invocation/BUILD
app/invocation/child_invocation_card.tsx
app/invocation/invocation_model.tsx
cli/remotebazel/remotebazel.go
enterprise/server/cmd/ci_runner/main.go
server/backends/invocationdb/invocationdb.go
server/build_event_protocol/build_event_handler/build_event_handler.go
server/buildbuddy_server/BUILD
server/buildbuddy_server/buildbuddy_server.go
server/interfaces/interfaces.go

Currently, the UI will only show the command and the pattern - i.e. `build //...`. Show the full explicit command line to include all flags specified by the user. This will bring the UI closer to how it looked before the bash steps refactor
Note that this won't apply automatically for workflows - some more refactoring is required to consolidate the deprecated `BazelCommand` syntax with the new `Steps` syntax
Before this PR:
After:

[RB] Show full child command in UI

---

enterprise/tools/get_executions/BUILD
enterprise/tools/get_executions/get_executions.go
enterprise/tools/replay_action/replay_action.go

* Add a tool `get_executions` which just calls the `BuildBuddyService/GetExecution` API
* Update the `replay_action` tool to allow replaying more than one execution. Also allow executions to be specified as `execution_id` instead of action digest + instance name. It's more convenient to use `execution_id` anyway, because we can just copy-paste it from the action page, vs copying both the action digest (which doesn't have a copy button yet) and the remote instance name (which is located in a separate invocation details tab)
* An alternative implementation would be to call `replay_action` once per execution, but this is not ideal because the concurrency limit would apply to each tool run rather than to all executions. Also, `replay_action` is able to dedupe CAS uploads using this approach, …

Allow replaying all executions from an invocation

---

enterprise/server/hostedrunner/hostedrunner.go

This will change the default from 2CPU 5GB memory => 3CPU, 7.5GB memory which feels like a more reasonable default

[RB] Default runners to have more memory and CPU by default

---

app/docs/setup.tsx
app/footer/footer.tsx
app/menu/menu.tsx
config/buildbuddy.local.yaml
proto/config.proto
server/static/static.go

Provide a flag for some deployments to not display our community Slack
on the UI.

static: provide a flag to turn off community link

---

enterprise/server/cmd/cache_proxy/cache_proxy.go
enterprise/server/cmd/executor/BUILD
enterprise/server/cmd/executor/executor.go
enterprise/server/cmd/server/main.go
enterprise/server/scheduling/scheduler_client/scheduler_client.go
server/cmd/buildbuddy/main.go
server/static/static.go
server/telemetry/telemetry_client.go
server/util/statusz/statusz.go
server/version/version.go

* Print version info in the executor, not just the apps
* Print the actual binary name rather than just "BuildBuddy" so we can distinguish between binaries more easily in logs
* Rename `AppVersion` to `Tag`

Version log improvements

---

enterprise/server/execution_search_service/execution_search_service.go
enterprise/server/invocation_search_service/invocation_search_service.go
enterprise/server/invocation_stat_service/invocation_stat_service.go
server/util/filter/filter.go
server/util/filter/filter_test.go

this cleans up some freaky string concats in query code that i've never really liked much--these callsites were all being used correctly, but a messed up call could theoretically lead to injection.
doesn't seem to me that we actually need `i.` on the search service queries, and that was the only place this was being used.

refactor: get rid of unneeded prefixing logic for queries

---

enterprise/server/remote_execution/containers/ociruntime/ociruntime.go
enterprise/server/remote_execution/containers/ociruntime/ociruntime_test.go
enterprise/server/remote_execution/runner/runner_linux.go

Move cached ext4 images under `{executor.local_cache_directory}/{host_id}/images/oci` so that we can run the executor with `--executor.delete_build_root_directory_on_startup` without clearing the oci image cache.
See also https://github.com/buildbuddy-io/buildbuddy/pull/7763

Move oci image cache under executor.local_cache_directory

---

server/util/db/db.go

this makes it explicitly `YYYY-MM-DD`, which matches the format given in clickhouse and the implicit string extraction from mysql.

postgres: make DateFromUsecTimestamp match other engines

---

enterprise/server/remote_execution/dirtools/BUILD
enterprise/server/remote_execution/dirtools/dirtools.go
server/metrics/metrics.go

In local and dev experiments, this prevents the upload of about 30% of bytes, and makes the output_upload stage about 40% faster. The speed increase isn't really meaningful, since the output_upload stage only takes 13ms on average.
Some things I'm not sure about:
1. Instead of creating a new metric, should I add a dimension to an existing metric, like `buildbuddy_remote_execution_file_upload_size_bytes`? I'm leaning towards creating this new metric because we don't need a histogram for skipped bytes.
2. Instead of adding a new metric, should I just report the reduced amount to `buildbuddy_remote_execution_file_upload_size_bytes`? If I did that, it would be harder to know how many bytes were skipped, and I think it's still useful to know how many bytes would be uploaded without the …

After executing, don't upload outputs that already exist remotely

---

server/build_event_protocol/build_event_proxy/BUILD
server/build_event_protocol/build_event_proxy/build_event_proxy.go

In `synchronous` mode, Bazel will retry the request if it fails, so don't log a warning internally (Bazel will log the warning if all retry attempts fail).

Return PublishLifecycleEvent errors instead of logging in sync mode

---

enterprise/server/atime_updater/atime_updater.go
enterprise/server/content_addressable_storage_server_proxy/content_addressable_storage_server_proxy_test.go

This test became flaky after https://github.com/buildbuddy-io/buildbuddy/pull/7783 because it assumes the atime-update interval is 30 seconds. Changed the test to explicitly set a value and use that in the test instead of relying on the default value.
Here's 1000/1000 green runs: https://buildbuddy.buildbuddy.io/invocation/0f73573a-a98a-4dc3-8570-181218774d4f

Fix flaky CASProxyTest

---

deps.bzl
go.mod
go.sum

Since #7769, which updated `otelhttp`, the following line is logged many times per second:
```
2024/10/25 12:52:58 http: superfluous response.WriteHeader call from go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp/internal/request.(*RespWriterWrapper).writeHeader (resp_writer_wrapper.go:78)
```
This is caused by a regression in the module, which has been fixed in https://github.com/open-telemetry/opentelemetry-go-contrib/commit/54d69164e7e6e337b3da441573cfea85279c2a3b.

server: Fix logspam caused by regression in otelhttp

---

server/features/BUILD.bazel
server/features/features.go
server/http/interceptors/BUILD
server/http/interceptors/interceptors.go
server/static/BUILD
server/static/static.go

Monaco is highly incompatible with a CSP that forbids inline styles.

server: Allow inline styles when code editor is enabled

---

cli/explain/compactgraph/BUILD.bazel
cli/explain/compactgraph/compactgraph.go

Small execlog (Bazel@HEAD vs Bazel@HEAD~30):
```
Time (mean ± σ):     139.3 ms ±   3.3 ms    [User: 445.7 ms, System: 69.8 ms]
Range (min … max):   133.4 ms … 146.2 ms    21 runs
Time (mean ± σ):     103.2 ms ±   1.8 ms    [User: 482.2 ms, System: 59.3 ms]
Range (min … max):    99.4 ms … 106.3 ms    28 runs
```
Large execlog (~250MB compressed):
```
Time (mean ± σ):      5.260 s ±  0.060 s    [User: 12.502 s, System: 0.619 s]
Range (min … max):    5.173 s …  5.351 s    10 runs
Time (mean ± σ):      3.331 s ±  0.062 s    [User: 12.379 s, System: 0.760 s]
Range (min … max):    3.256 s …  3.436 s    10 runs
```

explain: Parallelize parsing and graph construction

---

cli/cmd/bb/bb.go

Currently we print sidecar logs in any failure that's not a simple test failure.
With this change, we scope that down to just Bazel exit codes that are BES related.

Limit automatic sidecar log printing to BES-related errors

---

enterprise/server/api/api_server.go

There is more than one case where we return `NotFound`, so the current logic is causing us to return a misleading error in some cases.

Fix workflow error message

---

enterprise/server/remote_execution/workspace/workspace.go
proto/remote_execution.proto
server/cache/dirtools/dirtools.go
server/cache/dirtools/dirtools_test.go
server/remote_cache/cachetools/cachetools.go

Now the `file_upload_count` and `file_upload_size_bytes` metrics will include these files and bytes.
Also addresses the last comment from buildbuddy-io/buildbuddy/pull/7788

Include stdout, stderr, and auxiliary logs in file upload metrics

---

cli/remotebazel/remotebazel.go
enterprise/server/cmd/ci_runner/main.go
enterprise/server/test/integration/remote_bazel/remote_bazel_test.go

We have a remote bazel feature that builds the target remotely and runs the executable locally. This happens automatically in the CLI, as opposed to building the target remotely, and then the user manually running the executable that was fetched locally (here's the [PR](https://github.com/buildbuddy-io/buildbuddy/commit/fa9409e55400bd34c19b7e7282d4468999c056fc) where the behavior was introduced). This PR adds support in the new Steps syntax - this is the last missing feature before feature parity with BazelCommands

[ci_runner] Support build remotely and running locally via bash command

---

enterprise/server/remote_execution/container/container.go
enterprise/server/remote_execution/containers/podman/podman.go

This is no longer useful because we aren't actively running podman in prod.

Clean up some debug logging in podman

---

server/remote_cache/byte_stream_server/byte_stream_server.go

The `decompressorCloser` that's opened on [lines 307/315 of byte_stream_server.go](https://github.com/buildbuddy-io/buildbuddy/blob/6733ce557e5c064e278e8dd3f018cc8068df11d7/server/remote_cache/byte_stream_server/byte_stream_server.go#L303-L322) is only closed if [writeState.Flush](https://github.com/buildbuddy-io/buildbuddy/blob/6733ce557e5c064e278e8dd3f018cc8068df11d7/server/remote_cache/byte_stream_server/byte_stream_server.go#L333) is called, which only happens on [receiving the final frame of the ByteStream.Write](https://github.com/buildbuddy-io/buildbuddy/blob/6733ce557e5c064e278e8dd3f018cc8068df11d7/server/remote_cache/byte_stream_server/byte_stream_server.go#L425-L430). If that Write() loop exits early, then the decompressorCloser leaks, including goroutines from the zstd library …

Always close the writeState's decompressorCloser in ByteStreamServer.Write()

---

enterprise/server/remote_execution/containers/ociruntime/BUILD
enterprise/server/remote_execution/containers/ociruntime/ociruntime.go
enterprise/server/remote_execution/containers/ociruntime/ociruntime_test.go

Behind a flag, sets cgroup2 `cpu.weight` so that when the executor doesn't have spare CPU capacity, it throttles the CPU usage of each OCI container proportionally to estimated task size. This (roughly) guarantees that each action gets _at least_ the amount of CPU specified in the task size.
The behavior today is that `cpu.weight` is effectively set to `100` (the default value) for every task. So if the executor is fully loaded and all containers are CPU-constrained, each container will get equal CPU time, regardless of task size. This is not ideal because it means that tasks which are properly sized are unfairly throttled.
The OCI specification uses the "shares" naming (and unit scaling) instead of "weight" because that's what it was called in cgroup v1, and presumably the name "shares" …

oci runtime: set CPU weight according to task size

---

enterprise/server/remote_execution/execution_server/execution_server.go
proto/remote_execution.proto
server/util/clickhouse/clickhouse.go
server/util/clickhouse/schema/schema.go

Each Execution is often corresponding to a Bazel's Action, but end users
don't often think of Execution or Action because Bazel's build rules
system often abstract that away from them.
Instead, folks often think of Bazel build targets.
Each targets uses a build rule, in combination with a build
configuration, to create multiple actions. Usually each of these actions
are created with a unique mnemonic to help identify them a bit easier
(note that this is not always the case).
Capture the target label from Executor's RequestMetadata when record the
Execution into OLAPDB. We will evaluate adding mnemonic and
configuration at a later stage.

Add target to Execution

---

enterprise/server/cmd/executor/BUILD
enterprise/server/cmd/executor/executor_linux.go
enterprise/server/remote_execution/runner/runner.go
enterprise/server/remote_execution/runner/runner_darwin.go
enterprise/server/remote_execution/runner/runner_linux.go
enterprise/server/remote_execution/runner/runner_windows.go

If podman is not enabled then don't run the warmup container (which ensures the correct rule ordering) but do continue to run the other networking setup.

Don't run podman network setup container if podman isn't enabled

---

enterprise/server/raft/leasekeeper/leasekeeper.go
enterprise/server/raft/rangelease/rangelease.go
enterprise/server/raft/sender/sender.go
enterprise/server/raft/store/store.go
enterprise/server/raft/store/store_test.go

1. stop liveness before leasekeeper. Previously, after we shutdown leasekeeper, liveness keepLeaseAlive which will send cas requests to the store. The leasekeeper will then continue queuing instructions causing leaseAgent.runloop unable to finish in time.
2. When we stop leaseagent, we will also stop the keepLeaseAlive. 
3. In lease.ensureValidLease, check if the context deadline is reached.

[raft] fix shutdown order

---

server/http/csp/csp.go
server/http/interceptors/interceptors.go

* Reports are now filtered (rudimentarily) to remove noise such as reports triggered by browser extensions.
* Reports are logged as raw JSON so that they are easier to discover via the GCP Log Explorer.
* Allow `data:` sources for images as that's very low risk and Monaco appears to require it, although it's unclear why.
* Allow workers when Monaco is enabled.
Work towards https://github.com/buildbuddy-io/buildbuddy-internal/issues/3911

server: More CSP fixes and cleaner reports

---

enterprise/server/remote_execution/workspace/workspace.go
proto/remote_execution.proto
server/cache/dirtools/BUILD
server/cache/dirtools/dirtools.go
server/cache/dirtools/dirtools_test.go
server/metrics/metrics.go
server/remote_cache/cachetools/cachetools.go

- **Revert "Include stdout, stderr, and auxiliary logs in file upload metrics (#7799)"**
- **Revert "After executing, don't upload outputs that already exist remotely (#7788)"**

Revert #7788 and #7799

---

enterprise/server/raft/txn/txn.go

We stop preparing for the statements when there is an error; with the current code, we can return not found error during rollback. 
log the operation when there is an error for finalization.

[raft] txn: do not return NotFound error when rollback

---

enterprise/server/testutil/buildbuddy_enterprise/buildbuddy_enterprise.go
server/http/csp/csp.go
server/http/interceptors/interceptors.go

There haven't been any CSP reports in dev since the latest fix. The flag is only enabled in dev, but any violations reported after this point should be reported in a release-blocking fashion.
Also enables the flag in webdriver tests.

server: Enforce CSP with `--app.strict_csp_enabled`

---

server/remote_cache/cachetools/cachetools.go

When `cachetools.BatchReadBlobs` returns an error for an individual blob, we forget to set `Digest` in the `BlobResponse` which results in a `Digest <nil> not found` error being logged.

Fix nil digest error logged when calling BatchReadBlobs

---

MODULE.bazel
buildpatches/com_github_firecracker_microvm_firecracker_go_sdk_cgroup.patch
deps.bzl
enterprise/server/remote_execution/containers/firecracker/containeropts.go
enterprise/server/remote_execution/containers/firecracker/firecracker.go

Because of CPU overprovisioning, VMs can unfairly eat into each other's CPU allocation. Setting `cpu.weight` as a cgroup option (via the jailer) fixes this by providing a better CPU guarantee for VMs when the machine is under load.
Test:
* VM A (accurately sized): EstimatedCPU=31, run 31x CPU-bound processes for a fixed number of cycles.
* VM B (poorly sized): EstimatedCPU=1, run 32x CPU-bound processes for a fixed number of cycles.
In this test, VM B should get throttled to 1000m CPU usage, from its overprovisioned maximum of 4000m. When enabling `cpu.weight` I could see using `top` that it was indeed getting throttled as expected, whereas without CPU weight it was allowed to use 400% CPU, unfairly eating into VM A's CPU allocation. Enabling `cpu.weight` also reduces the exec duration of …

firecracker: set jailer cgroup CPU weight according to task size

---

enterprise/server/remote_execution/containers/firecracker/BUILD
enterprise/server/remote_execution/containers/firecracker/firecracker.go
enterprise/server/util/ociconv/BUILD
enterprise/server/util/ociconv/ociconv.go
enterprise/server/util/ociconv/ociconv_test.go

This complicates migrating away from skopeo / umoci and is unused, so remove it.

Remove unused dockerclient optional functionality from firecracker image pull path

---

proto/remote_execution.proto

- Add cgroup IO stats (`io.stat` file)
- Add timelines for memory and IO

Add more fields to usage stats protos

---

server/target/target.go

The current page size is very small and makes repeatedly clicking "Load more" very tedious

Increase test grid page size

---

dockerfiles/rbe-ubuntu22-04/Dockerfile

Our guest kernel config is not properly set up for nftables, so the newer `iptables` doesn't work. This prevents `dockerd` from starting. Switch to `iptables-legacy` for now.

Use iptables-legacy in ubuntu 22.04 RBE image

---

MODULE.bazel
WORKSPACE
go.mod

Reference: https://github.com/golang/go/issues?q=milestone%3AGo1.23.3+label%3ACherryPickApproved

gosdk: upgrade to 1.23.3

---

buildpatches/com_github_firecracker_microvm_firecracker_go_sdk_cgroup.patch
deps.bzl
enterprise/server/remote_execution/containers/firecracker/firecracker.go
enterprise/server/remote_execution/containers/ociruntime/ociruntime.go
enterprise/server/util/oci/oci.go

1. Ensure that VM cgroups are siblings of OCI container cgroups, which is required for proper CPU weighting. Currently, each VM's cgroup is a child of the "firecracker" parent cgroup `/sys/fs/cgroup/firecracker/<vm_id>` which means they are not siblings of the OCI container cgroups, which live in `/sys/fs/cgroup/<container_id>`. This PR sets `--parent-cgroup` on the jailer command to move the VM cgroups directly under `/sys/fs/cgroup` rather than in a subdirectory, which ensures they are siblings of the OCI container cgroups.
2. Fix the units used for CPU weighting. We were effectively using different mappings from milliCPU -> `cpu.weight` across firecracker and OCI, which means we were weighting inconsistently.
Tested by running the following tasks in parallel:
- One "properly sized" …

Fix relative CPU weighting between firecracker VMs and OCI containers

---

enterprise/server/remote_execution/containers/firecracker/firecracker.go

The cgroups created by jailer aren't deleted automatically. From the [jailer docs](https://github.com/firecracker-microvm/firecracker/blob/main/docs/jailer.md#observations):
> It’s up to the user to handle cleanup after running the jailer. One way to do this involves registering handlers with the cgroup notify_on_release mechanism, while being wary about potential race conditions (the instance crashing before the subscription process is complete, for example).
Rather than using `notify_on_release`, this PR just deletes the cgroup after the firecracker process exits, since the cgroup should no longer have any pids present at that point.
Fixes https://github.com/buildbuddy-io/buildbuddy-internal/issues/4101

Clean up firecracker cgroups manually

---

enterprise/server/raft/bringup/bringup.go
enterprise/server/raft/rangelease/BUILD
enterprise/server/raft/rangelease/rangelease.go
enterprise/server/raft/rangelease/rangelease_test.go
enterprise/server/raft/replica/replica_test.go
enterprise/server/raft/store/store_test.go

https://github.com/buildbuddy-io/buildbuddy-internal/issues/4100
Also add a test for ContainsMetaRange

[raft] change the start key of meta range from \x00 to \x02

---

enterprise/server/remote_execution/executor/executor.go
server/metrics/metrics.go
tools/metrics/grafana/dashboards/buildbuddy.json

Currently, it's hard to interpret the stall time histogram because it's reporting absolute duration. High stall durations might be fine if the task ran for a relatively long time. So report stall durations as a fraction of execution duration instead.

Report PSI prom metrics as a fraction of exec duration

---

enterprise/server/remote_execution/copy_on_write/copy_on_write.go

The background lru eviction channel is not keeping up, because we are locking the LRU when unmapping chunks. This means that the unmaps are happening serially. Unmapping is slow, and we do not need the LRU to be locked while different chunks are being unmapped
This situation will now be possible: 
```
evict m1
> m1.mu.Lock()
> lru.Lock()
> lru.Unlock()
> blocks before we unmap and unlock m1
// Another goroutine
evict m2
> m2.mu.Lock()
> lru.Lock() <- This is a safe operation, because we are only taking the lock to see if the lru contains the m2 key. There is no reason we need to wait for m1 to finish unmapping beforehand
... 
```
Fixes https://buildbuddy-corp.slack.com/archives/C0154UFBCJ2/p1731014993153979

[COW] Do not lock the lru when unmapping

---

enterprise/server/backends/authdb/authdb.go
enterprise/server/backends/userdb/userdb_test.go

Modify authdb.go so that credentials with admin capability
can Update and Delete user's api keys.

authdb: allow admin cap to update+delete user api key

---

enterprise/server/remote_execution/cgroup/cgroup.go

In some cases, the `io.stat` file has some `(unknown)` devices instead of the expected `MAJOR:MINOR` device number format. Ignore these for now while we dig deeper into what these mean.

Ignore unknown device numbers in io.stat

---

enterprise/app/workflows/BUILD
enterprise/app/workflows/workflows.tsx

Let user decide which action to run from our web UI.
The field accepts multiple action names separated by comma (`,`).
Custom input could be provided via environment variables.
The environment variables should be specified in comma-separated key-value pairs.
For example: `VAR1=value1,VAR2=value2`.

workflows: add Action Names and Env to Run Workflow button

---

enterprise/server/remote_execution/workspace/workspace.go
proto/remote_execution.proto
server/cache/dirtools/BUILD
server/cache/dirtools/dirtools.go
server/cache/dirtools/dirtools_test.go
server/metrics/metrics.go
server/remote_cache/cachetools/cachetools.go

Reverts buildbuddy-io/buildbuddy#7851
This rolls forward
- Include stdout, stderr, and auxiliary logs in file upload metrics (https://github.com/buildbuddy-io/buildbuddy/pull/7799)
- After executing, don't upload outputs that already exist remotely (https://github.com/buildbuddy-io/buildbuddy/pull/7788)

Revert "Revert #7788 and #7799"

---

enterprise/server/remote_execution/filecache/filecache.go
enterprise/server/remote_execution/filecache/filecache_test.go

This should be backwards compatible with the existing filecache format.

Prefix filecache digest paths with first 4 of digest

---

app/invocation/invocation_action_card.tsx
enterprise/server/remote_execution/block_io/BUILD
enterprise/server/remote_execution/block_io/block_io_unix.go
enterprise/server/remote_execution/block_io/block_io_windows.go
enterprise/server/remote_execution/cgroup/BUILD
enterprise/server/remote_execution/cgroup/cgroup.go
enterprise/server/remote_execution/container/BUILD
enterprise/server/remote_execution/container/container.go
enterprise/server/remote_execution/container/container_test.go
enterprise/server/remote_execution/containers/ociruntime/BUILD
enterprise/server/remote_execution/containers/ociruntime/ociruntime.go
enterprise/server/remote_execution/containers/podman/BUILD
enterprise/server/remote_execution/containers/podman/podman.go
enterprise/server/remote_execution/runner/BUILD
enterprise/server/remote_execution/runner/runner.go
proto/remote_execution.proto

Also show the IO stats in the UI - this was useful for E2E testing locally; figured it's a small enough change to include with this PR.
Here's the results from an sh_test that ran `head -c 10000000000 > /tmp/file.txt ; sync`

Record IO stats only for build_root device

---

server/build_event_protocol/build_event_handler/build_event_handler.go

Without an options event, we don't know anything useful about the build - so there's no point in trying to finalize (it will fail because we never wrote the invocation row in the first place).
In the future we could write some special tombstone row in the invocation here which we could render as an unknown build in the UI - but I'm not convinced that behavior is much better than this behavior "Not found".
This fixes an issue where if you do a build with an invalid flag with bes enabled:
```
bazel build //... --not_a_real_flag_name
```
Bazel will retry 4 times and fail each time with the error `Attempt %d of invocation %s pre-empted by more recent attempt, invocation not finalized.` because we never get an options event. 
This causes the command to appear to hang for a few seconds (while …

Don't try to finalize invocation we never get an options event for

---

enterprise/tools/replay_action/BUILD
enterprise/tools/replay_action/replay_action.go

I tried chaining with get_executions but I ran into problems with bash arg limits and being able to control parallelism due to separate instances of replay_action.

Allow replay_action to lookup invocation executions directly.

---

enterprise/server/cmd/ci_runner/main.go
enterprise/server/test/integration/ci_runner/BUILD
enterprise/server/test/integration/ci_runner/ci_runner_test.go

This flag was originally added so that remote bazel could specify the command to run. Now that we're always sending the commands in --serialized_action, we can remove it
Should be merged after https://github.com/buildbuddy-io/buildbuddy/pull/7835 has been deployed

[ci_runner] Clean up bazel_sub_command flag

---

proto/scheduler.proto

The `SchedulingMetadata.task_size` field is both lossy (since it is supposed to contain the "default" task size, but gets overwritten) and redundant (the executor allegedly uses this for scheduling but in practice it actually uses EnqueueTaskReservationRequest.task_size).
Deprecate this field and add clearer, not-lossy alternatives. (We'll keep setting it for some time, probably, because we do have some places in the code where it's unfortunately used - e.g. ExecutedActionMetadata.task_size gets set to this value, but probably should be getting set to the task_size from EnqueueTaskReservationRequest, which represents its "final" size for local scheduling

Deprecate ambiguous SchedulingMetadata.task_size field

---

proto/scheduler.proto

Adds a proto representing all of the cgroup2 options that we can set per-task: https://docs.kernel.org/admin-guide/cgroup-v2.html
This will allow the app's task sizer to control resource limits in addition to task sizes. Executor implementation to follow.

Add a proto for cgroup settings

---

enterprise/server/remote_execution/action_merger/action_merger.go

These are in non-exported functions.

Remove unused args in action_merger

---

enterprise/server/remote_execution/execution_server/execution_server.go
enterprise/server/remote_execution/runner/runner.go
enterprise/server/tasksize/BUILD
enterprise/server/tasksize/tasksize.go
enterprise/server/tasksize/tasksize_test.go

This is working towards fixing buildbuddy-io/buildbuddy-internal#4108

Store request and default sizes in SchedulingMetadata

---

enterprise/server/remote_execution/filecache/BUILD
enterprise/server/remote_execution/filecache/filecache.go
enterprise/server/remote_execution/filecache/filecache_test.go

During the initial filecache scan, we repeatedly call `AddFile()` on each scanned file.
The current implementation of `AddFile()` is:
1. Evict any existing entry. If an entry does exist, unlink it from the destination path, via the OnEvict callback.
2. Hardlink the file from the source path to its dest path.
For the filecache scan specifically, this logic is not ideal for two reasons:
* At best, it's unnecessary. Passing the same argument to `os.Link()` twice is always an error: either `EEXIST` (file already exists) or `ENOENT` (no such file or directory). So we're performing a bunch of syscalls which are guaranteed to return errors, which we then ignore. This is a bunch of unnecessary work.
* At worst, an action can race with the filecache background scan to update a cache key (e.g. …

Fix filecache scan deleting entries added by concurrent actions

---

enterprise/server/remote_execution/containers/firecracker/BUILD
enterprise/server/remote_execution/containers/firecracker/firecracker_test.go
enterprise/server/remote_execution/containers/firecracker/test.sh
enterprise/server/remote_execution/uffd/uffd.go
proto/firecracker.proto

Make firecracker CoW tests run on CI

---

enterprise/server/scheduling/priority_task_scheduler/priority_task_scheduler.go
enterprise/server/scheduling/scheduler_client/scheduler_client.go
enterprise/server/scheduling/scheduler_server/scheduler_server.go
enterprise/server/test/integration/remote_execution/rbetest/rbetest.go
proto/scheduler.proto

Work today is enqueued on executors in two ways:
1) When an Execute() request comes in, work is pushed to already running executors
2) When new executors come online, if there is unclaimed work, some of it may be enqueued on them
This CL introduces a third mechanism, which is that when an executor has excess capacity, it can request more work from the scheduler. The scheduler may enqueue unclaimed work on the executor if any exists, or if not, it will tell the executor to back off before asking again.
The exponential backoff period starts at 5 seconds of inactivity and maxes out at 60 seconds, so the min / max additional QPS we'd expect to see with say 10K executors is between (10K/5 - 10K/60) == 2000QPS max, 166QPS Min. All of these requests are messages on the existing stream, not new …

Request more work when executor is idle

---

tools/dev_qa.py

We're testing the bb repo on an old commit that still runs the ci_runner_test with `workload-isolation-type=podman` against dev.

Update dev QA script to remove podman dependency in dev

---

enterprise/server/cmd/executor/executor.go
enterprise/server/cmd/executor/executor_linux.go
enterprise/server/cmd/executor/executor_notlinux.go
enterprise/server/remote_execution/cgroup/cgroup.go

Add a flag to allow the executor to create child cgroups for the executor and action processes.
This should fix several issues:
- The current cpu weight for action processes is being applied relative to cgroup siblings in the cgroup root on the host node. This is not desired - CPU resources should be distributed _within_ the executor container cgroup, so that we respect quota/limits etc. and ensure that we don't mess with the relative weights between other pods on the node.
- Placing the executor within a sibling cgroup of action cgroups allows us to assign CPU weight to the executor process itself, which gets weighted against all action cgroups.
- k8s pod metrics should now work properly (assuming those metrics are driven by scraping the cgroup metrics from the container cgroup)
- On k8s …

Add executor flag to create child cgroups for executor and actions

---

enterprise/server/remote_execution/containers/firecracker/BUILD

Should help reduce the chance of timeouts which can result in networking garbage being left over on the machine: https://buildbuddy-corp.slack.com/archives/C01D5GHRJ59/p1732555141310049?thread_ts=1732553501.715329&cid=C01D5GHRJ59

Increase size of firecracker_test

---

enterprise/server/remote_execution/block_io/block_io_unix.go
enterprise/server/remote_execution/runner/runner.go

Use the `dev` field from `stat_t` to get the device numbers from the path, instead of trying to look up the associated block device special file under `/dev/` and using the `rdev` field from that.
Fixes 2 issues:
- The `/dev/*` device may not be mounted inside the executor container, so `stat` will fail.
- On macOS, `/proc/mounts` isn't a thing, so we can't look up the `/dev/*` device path from it.

Fix block device detection logic

---

enterprise/server/remote_execution/executor/executor.go
enterprise/server/remote_execution/workspace/BUILD
enterprise/server/remote_execution/workspace/workspace.go

Attempt to limit os.RemoveAll parallelism a little bit because it can swamp filesystems on very large machines (lol)

Limit workspace Remove() parallelism

---

enterprise/server/remote_execution/containers/firecracker/firecracker.go
enterprise/server/remote_execution/copy_on_write/copy_on_write.go
enterprise/server/remote_execution/vbd/vbd.go

Since the workspace VBD now exposes the workspace block device contents as a plain old file (via FUSE), we can directly pass that file path to `ImageToDirectory()`, rather than first creating a full copy of the workspace contents. (This resolves the TODO here - this wasn't easily doable with NBD before, but is now possible with VBD)

Don't copy the workspace VBD contents during workspace sync

---

cli/execute/execute.go

Useful for ad-hoc testing of action input/output handling.

Add output_path flag to bb execute

---

enterprise/server/remote_execution/copy_on_write/BUILD
enterprise/server/remote_execution/uffd/BUILD
enterprise/server/remote_execution/uffd/uffd.go

The window build is broken because certain syscalls are not supported on windows: https://github.com/buildbuddy-io/buildbuddy/actions/runs/12037002728/job/33560293374

[COW] Don't build on windows

---

enterprise/server/test/integration/remote_bazel/remote_bazel_test.go

I realized there is a small mistake in this test. During a `bazel run` on the remote runner, the execution output is always in the outer parent invocation, not the child invocation. So this test would always succeed, even if something is broken

[RB] Fix test

---

enterprise/server/backends/redis_client/redis_client.go
enterprise/server/util/redisutil/redisutil.go

Provide a set of flags that would enable TLS when connecting to Redis
using Go Redis client (false by default).
note: In the future, we might want to add support for custom certificate
as well with flags pointing to custom cert+key files.

redis_client: provide flags to enable TLS

---

enterprise/server/remote_execution/containers/podman/podman.go
server/util/networking/networking.go

Since we no longer enable the podman isolation, we can configure this entirely in the veth pair setup.
I'm making the task IP range configurable to support running multiple executors and only applying the policy for the range of the current executor doesn't make much sense.

Move private range blackholing to veth pair setup and enable it by default.

---

server/util/claims/BUILD
server/util/claims/claims.go

Could not repro this locally, so adding some diagnostic logs.
Related: https://github.com/buildbuddy-io/buildbuddy-internal/issues/4191

Add some diagnostic logs for missing group_id

---

enterprise/server/execution_service/execution_service.go
enterprise/server/remote_execution/execution_server/execution_server_test.go
enterprise/server/remote_execution/executor/executor.go
enterprise/server/test/integration/remote_execution/BUILD
enterprise/server/test/integration/remote_execution/rbetest/BUILD
enterprise/server/test/integration/remote_execution/rbetest/rbetest.go
enterprise/server/test/integration/remote_execution/remote_execution_test.go
enterprise/server/util/execution/BUILD
enterprise/server/util/execution/execution.go
server/remote_cache/digest/digest.go
tools/cas/cas.go

Nothing is reading this, since now executions are stored as ExecuteResponses for all actions (passed or failed).

Stop writing failed actions with the invocation ID as part of their key

---

enterprise/server/raft/driver/BUILD
enterprise/server/raft/driver/driver.go
enterprise/server/raft/store/store.go

To prepare the driver for rebalancing lease counts, the driver needs to be
stopped at the start of the store.Stop() method before we try to drop all the
leases held.

[raft] refactor driver start and stop code

---

app/trace/trace_events.ts
enterprise/server/execution_service/execution_service.go
enterprise/server/remote_execution/container/container.go
enterprise/server/remote_execution/container/container_test.go
proto/remote_execution.proto

Example:
This screenshot is from running this python script as a test action. It repeatedly doubles the length of a string, starting from a string of length 1, sleeping for a bit before each doubling operation. It runs this whole procedure for 3 total iterations, sleeping a bit between each run.
```python
import gc
import time
for _ in range(3):
s = "A"
while len(s) < 100e6:
s += s
gc.collect()
time.sleep(0.25)
time.sleep(1)
gc.collect()
```

Add memory usage timelines

---

website/yarn.lock

Address https://github.com/buildbuddy-io/buildbuddy/pull/7969
Submitted as a separate PR since right now dependabot's forks don't run in our CI correctly.

Address https://github.com/buildbuddy-io/buildbuddy/security/dependabot/181

---

docs/troubleshooting-rbe.md

Add a doc explaining 'missing digest error' and the recommended path to
troubleshoot it.

troubleshooting-rbe: document Missing Digest

---

MODULE.bazel
WORKSPACE
go.mod

https://github.com/golang/go/issues?q=milestone%3AGo1.23.4+label%3ACherryPickApproved

gosdk: upgrade to 1.23.4

---

cli/remotebazel/BUILD
cli/remotebazel/remotebazel.go
cli/remotebazel/remotebazel_test.go
enterprise/server/test/integration/remote_bazel/remote_bazel_test.go

Our usage of go-git in the remote bazel CLI doesn't handle a series of edge cases and has resulted in some performance problems. This PR is a continuation of https://github.com/buildbuddy-io/buildbuddy/pull/7933
Also:
* Fixes an assumption that the default branch had to be named `main` or `master`
* Tries to minimize slow remote git calls by making one `git ls-remote --symref origin` call at the beginning, and passing the output to helper function
* Fixes a bug where the flags weren't parsed when we were trying to use them
Fixes https://github.com/buildbuddy-io/buildbuddy/issues/7896
Fixes https://github.com/buildbuddy-io/buildbuddy-internal/issues/3717

[RB] Finish refactoring out go-git from CLI

---

enterprise/server/raft/leasekeeper/leasekeeper.go
enterprise/server/raft/sender/sender.go
enterprise/server/raft/store/store.go

Ctx log can associate the log with the request_id, this can help us to
understand some of the sender debug logs better.

[raft] use ctx log

---

website/src/css/common.module.css

This aligns headers flush with nav bar logo for larger screen sizes (which looks nice).
Before
After

Tweak website alignment

---

server/buildbuddy_server/BUILD
server/buildbuddy_server/buildbuddy_server.go

Right now we only support downloading JSON with the `raw_json` parameter because it's nice and human readable.
This change adds support for downloading via var-int size delimited protos (https://pkg.go.dev/google.golang.org/protobuf/encoding/protodelim#MarshalOptions) as well using the `raw_proto` parameter.

Support proto-encoded BEP download through `/file/download` endpoint

---

template-user.bazelrc

Now that 7.4 includes a GC for local disk cache, enabling it should help
speed up local builds by quite a lot.
I have enabled this for weeks in my $HOME/.bazelrc file without any
issue.
We should dogfood this before recommending it to our users.

template-user.bazelrc: recommend disk_cache for local usage

---

cli/remotebazel/remotebazel.go
cli/remotebazel/remotebazel_test.go

I introduced a bug in this commit: https://github.com/buildbuddy-io/buildbuddy/pull/7989
If your local branch does not exist remotely, we want to fallback to using the master branch. In the previous incorrect version, we'd use the remote master head commit. If this commit didn't exist locally, there'd be errors when we tried to diff against it to generate the diff patchsets

[RB] Fix an incorrect reference to remote branch vs local branch

---

cli/remotebazel/remotebazel.go

Fixes https://buildbuddy-corp.slack.com/archives/C07GMM2VBLY/p1733333761499139?thread_ts=1731949897.755029&cid=C07GMM2VBLY
The CLI sometimes reports the wrong exit code (0, even when the remote run failed). This is because there can be a slight delay between when the remote runner execution finishes, and when the execution is successfully updated in the DB with the final exit code. Make sure to check that the execution is complete before using the exit code.

[RB] Fix race condition with fetching completed execution data

---

enterprise/server/util/execution/execution.go
proto/remote_execution.proto
server/util/clickhouse/clickhouse.go

Each boolean field is about 0.1% of our clickhouse write throughput. This is based on the success field.

Write do_not_cache and cached_result to clickhouse

---

server/cache/dirtools/dirtools.go
server/cache/dirtools/dirtools_test.go

A symlink in an output directory should not be reported as an `output_{,directory,file}_symlink` unless it has been explicitly requested via `output_paths`. This matches the logic for REAPI < v2.1 using `output_directories` and `output_files`.
This fixes a failure in Bazel with `(Exit 34): /build/execroot/_main/bazel-out/darwin_arm64-fastbuild/bin/foo/... (File exists)`.

Don't report symlinks in output directory separately with `output_paths`

---

enterprise/server/backends/redis_client/redis_client.go
enterprise/server/util/redisutil/redisutil.go

Effectively revert https://github.com/buildbuddy-io/buildbuddy/pull/7978
as user could already enable TLS by using "rediss://" url scheme.
This would not work in case of a Shared Redis setup using Ring Client,
so ensure that we use the first shard address to setup the Ring Client
options. If the first shard address uses "rediss://", TLS will be
enabled and if it uses "redis://", TLS will be disabled.

redis: respect rediss://

---

enterprise/server/raft/store/store.go

buildbuddy-io/buildbuddy-internal#4211
nodehost.startShard can return AlreadyExists error in two cases:
- 1. the shard exists, but for a different replica id
- 2. the shard with specified replica id exists.
In AddReplica, we can ignore the 2nd case, but not the 1st case.

[raft] discern already exists error

---

MODULE.bazel
deps.bzl
server/util/bazelisk/BUILD
server/util/bazelisk/bazelisk.go

Confirmed that `v1.19.0` respects .bazelversion when MODULE.bazel is present, and that `v1.17.0` does not.

Update ci_runner bundled bazelisk version

---

proto/api/v1/remote_runner.proto

`google/rpc/status.proto` is unused in `proto/api/v1/remote_runner.proto`, which causes a logged warning during build.

Remove unused import in `remote_runner.proto`

---

enterprise/server/remote_execution/uffd/BUILD
enterprise/server/remote_execution/uffd/uffd.go

We don't need the go build constraint because the BUILD file contains a `target_compatible_with` platform. This makes it easier to edit the file with an IDE, even on non-linux platforms
This was originally added here https://github.com/buildbuddy-io/buildbuddy/pull/7965, then reverted due to the separate changes in that PR

Remove linux go build constraint for uffd

---

enterprise/server/raft/client/client.go
enterprise/server/raft/driver/BUILD
enterprise/server/raft/driver/driver.go
enterprise/server/raft/store/store.go
enterprise/server/raft/store/store_test.go

Also fix RemoveNodeFromCluster test. Sometimes test fail with shardNotFound when
we call removeReplica on the store where c2n4 resides.
Seperate RemoveData from RemoveReplica so that we can call try removeReplica on
different replicas (in following PRs)
https://github.com/buildbuddy-io/buildbuddy-internal/issues/4220

[raft] move remove data out of removeReplica

---

enterprise/server/util/ociconv/BUILD
enterprise/server/util/ociconv/ociconv.go

OLD     --- PASS: TestOciconv/image=mirror.gcr.io/ubuntu:22.04 (4.10s)
NEW    --- PASS: TestOciconv/image=mirror.gcr.io/ubuntu:22.04 (2.57s)
Images are the same size (125MB) and contain the same number of files and dirs.

Remove need to call umoci, use crane tools

---

enterprise/app/sidekick/module/module.tsx

Previously we'd just replace the full module snippet with the example snippet from the docs.
This could be destructive if either the example snippet includes weird stuff (like comments), or if usage is non-standard (i.e. has some extra args).
With this change, we just touch the version argument and bump it to the latest version when update is clicked.

Only touch version number when updating bazel module version via sidekick

---

enterprise/server/raft/store/store.go
proto/raft.proto

Allow RemoveRequest to take a request without range. If we are removing zombies,
that means the replica is not in the descriptor, so we don't need the range
descriptor in that case. But we still want to check that the server is the lease
holder of that range. 
Known issue: the Cleanup Zombie test can become flaky if we are removing
a leader. I will address it in a follow up PR when I refactor the zombie code.

[raft] RemoveReplica

---

app/invocation/invocation_action_card.tsx

This lets us get all the metadata that is stored in the ExecutedResult, but isn't sent on wait operation.

Fetch ExecuteResult when WaitExecution is done

---

enterprise/app/login/login.tsx
proto/config.proto
server/static/static.go

This enables configuring the login page buttons to use a specific organization slug with the `app.default_login_slug` flag / config option.
Particularly useful for installations that don't use customer-specific subdomains.

Allow specifying a default login slug

---

enterprise/server/remote_execution/containers/ociruntime/BUILD
enterprise/server/remote_execution/containers/ociruntime/ociruntime.go
enterprise/server/remote_execution/containers/ociruntime/ociruntime_test.go

This change include a few small changes inside:
- Reapply "ociruntime: replace tar extraction subprocess with in-process (#7589)" (#8019)
- Add a basic image pull test and guard it with a separate, manual Bazel test target to help verifying common images.
- Fix issues with the previous implementation.
Ensure that parent directory is created for file tar entries.
Ignore unknown tar entry types (i.e. devices).

ociruntime: reapply tar unpack

---

enterprise/server/cmd/executor/executor.go
enterprise/server/remote_execution/container/BUILD
enterprise/server/remote_execution/container/container.go
enterprise/server/remote_execution/containers/bare/bare.go
enterprise/server/remote_execution/containers/firecracker/firecracker.go
enterprise/server/remote_execution/containers/ociruntime/ociruntime.go
enterprise/server/remote_execution/containers/podman/podman.go
server/metrics/metrics.go

This PR cleans up some stats logic in preparation for tracking firecracker stats using cgroups, instead of tracking stats using the guest vmexec server. The current logic is somewhat tangled up which would make the integration with firecracker a bit more messy than it needs to be.
* Remove the logic to record prometheus metrics for running containers, which manually totals the results of `c.Stats()`. This logic is complex and its value is pretty questionable.
* On Linux, a better way to do this would be to poll the stats from the action parent cgroup once `executor.child_cgroups_enabled` is rolled out.
* On macOS we could probably just live with the node metrics instead of trying to separate the executor metrics and task metrics. The accuracy of the task metrics on macOS is especially …

Simplify stats polling logic

---

website/package.json
website/yarn.lock

Fixes all peer deps except for `@cmfcmf/docusaurus-search-local`, which will need to at some point be replaced (likely with `@easyops-cn/docusaurus-search-local`) since it does not support docusaurus 3.

Fix peer deps for `//website`

---

enterprise/server/remote_execution/containers/firecracker/BUILD
enterprise/server/remote_execution/containers/firecracker/firecracker.go

We aren't actively using this code. The `debugfs` codepath is probably "fast enough" since we updated it to only copy output paths in https://github.com/buildbuddy-io/buildbuddy/pull/7959, and also this code is likely to be supplanted by FUSE anyway. If we do want to try this code again in the future, we can always bring it back, but should test thoroughly in dev first because we hit some issues with the loopback device approach last time.

Remove workspacefs loopback mount code

---

website/yarn.lock

Addresses https://github.com/buildbuddy-io/buildbuddy/security/dependabot/183

Upgrade `nanoid` to `3.3.8` for dependabot

---

enterprise/server/remote_execution/runner/runner_linux.go
enterprise/server/remote_execution/vfs/vfs_unix.go

- Use log.Ctx for verbose logging instead of adding a custom prefix which makes the logs easier to read.
- Add optional per-file FUSE operation stats.
- Add support for Passthrough.
- Add flags for controlling various debugging options.

Various VFS client side changes

---

enterprise/server/cmd/goinit/main.go
enterprise/server/remote_execution/containers/firecracker/firecracker.go
enterprise/server/remote_execution/containers/firecracker/firecracker_test.go
enterprise/server/remote_execution/snaploader/snaploader.go
proto/firecracker.proto

It's not necessary to use COW+VBD for the workspace drive or store it as part of the VM snapshot, because we never wind up reading from the snapshotted workspace - instead, we wind up just throwing it away after unpausing, since we create a new workspace ext4 image from the action workspace on the host for every action.
So, instead of snapshotting the workspace, we can stub out the workspace drive with an empty file (`empty.bin` relative to the chroot) just before saving the snapshot, so that the snapshotted state does not contain any references to the workspace. Firecracker will expect this file to exist when resuming the snapshot, so we just need to manually create this file before resuming.
In addition, there is some extra related cleanup in this PR: when initially creating the VM, we …

Don't use COW for workspaces or store them in snapshots

---

enterprise/server/content_addressable_storage_server_proxy/content_addressable_storage_server_proxy.go
enterprise/server/content_addressable_storage_server_proxy/content_addressable_storage_server_proxy_test.go

This should address a cache-inconsistency bug that's possible when artifacts in the proxy outlive those in the backing cache and are reported as found by the executor logic that checks for the presence of artifacts before uploading them.

[Cache Proxy] always proxy FindMissingBlobs RPCs

---

tools/metrics/grafana/dashboards/clickhouse.json

The metrics are already exported by the clickhouse operator, so I added two panels, one for totals size per table, and one for write throughput per table.

Add visualizations of per table stats to the clickhouse dashboard

---

enterprise/app/org/org_form.tsx
server/tables/tables.go

Invocations shared publicly also provide access to the artifacts they reference, which organizations may rightly be cautious about. Allowing developers access to this features should require a conscious decision.

Disable "allow making builds public" by default and improve explanation

---

server/cache_proxy/cache_proxy.go

This is the CLI sidecar version of https://github.com/buildbuddy-io/buildbuddy/pull/8073
Consulting the local CAS leads to two issues:
1. We don't bump the TTL on remote cache objects that exist locally
2. If for whatever reason an action output is missing, bazel will never recover by re-uploading the missing artifact (if the artifact exists in the local CAS)
We already handle `GetActionResult`, `UpdateActionResult`, `BatchUpdateBlobs`, and `BatchReadBlobs` similarly.

[CLI] Don't consult local CAS for findMissing

---

enterprise/server/raft/store/store.go
enterprise/server/raft/txn/txn.go

I need a isLeader function that only checks the state on raft. 
while removing zombies, I need to check if the zombie node is the leader in
raft. In that case, the replica probably is not loaded.

raft: refactor isLeader

---

enterprise/server/remote_execution/execution_server/execution_server.go
enterprise/server/tasksize/tasksize.go
enterprise/server/tasksize/tasksize_test.go
server/interfaces/interfaces.go

I guess I missed this one as well.

Use action.platform instead of command.platform in one more place

---

enterprise/server/remote_execution/platform/platform.go

Currently, we can't tell the difference between the user not requesting an isolation type and requesting an invalid one. This change fixes that.

Allow empty string in platform.CoerceContainerType

---

enterprise/server/tasksize/tasksize.go
enterprise/server/tasksize/tasksize_test.go

I introduced this in https://github.com/buildbuddy-io/buildbuddy/pull/7920 and found it using the new clickhouse fields.
If the user only  sets CPU, it takes no affect. If the user only sets RAM, it sets CPU to 0, which later gets overridden  to 600 from the default.
I fixed this and added tests.

fix a bug in tasksize.Requested

---

dockerfiles/executor_image/Dockerfile
enterprise/server/remote_execution/containers/ociruntime/ociruntime.go

On certain nodes we've had issues with actions auto-sizing themselves to use way too many CPUs because they were not cgroup-aware. This should address that issue by faking out the common ways processes detect the number of CPUs available.

Add lxcfs support to fake cpuinfo for containers

---

enterprise/server/remote_execution/containers/firecracker/firecracker.go

I'd like to understand if these slow interrupt warnings are correlated with higher action failure rates. By logging these we can get a rough frequency chart from GCP then compare that to the action failure metrics in Grafana.

Surface slow interrupt warnings in the executor logs

---

server/buildbuddy_server/buildbuddy_server.go

Since we're no longer authenticating using API key auth, we need the JWT.

Fix HTTP file download auth

---

dockerfiles/executor_image/Dockerfile

Bumping the base image we use in the executor `Dockerfile` to the latest `debian:stable` tag in the docker registry.

Update executor image to pick up fixes for vulnerabilities

---

WORKSPACE
WORKSPACE.bzlmod

Just bumping to the latest `gcr.io/distroless/cc-debian12` image.

Update app image to pick up fixes for vulnerabilities

---

enterprise/server/remote_execution/execution_server/execution_server.go
enterprise/server/remote_execution/execution_server/execution_server_test.go
proto/remote_execution.proto
server/util/clickhouse/clickhouse.go
server/util/clickhouse/schema/schema.go

I expect this to add less than 1% to write throughput.

Add action mnemonic to clickhouse

---

cli/remotebazel/remotebazel.go

WaitExecution will sometimes set the error on the rsp object, which we were previously failing to check for
Because the default value of an int is 0, if the execute response result was unset, we would sometimes incorrectly return the default value which looks like a success code
Fixes #1 from this thread: https://buildbuddy-corp.slack.com/archives/C07GMM2VBLY/p1734595606837269

[RB] Fix error handling

---

enterprise/server/test/integration/remote_execution/remote_execution_test.go
enterprise/server/test/webdriver/invocation/BUILD
enterprise/server/test/webdriver/invocation/invocation_test.go
enterprise/server/testutil/testexecutor/BUILD
enterprise/server/testutil/testexecutor/testexecutor.go
server/testutil/webtester/webtester.go

The action page breaks often because the `/file/download` logic is pretty complex as well as the logic in `invocation_action_card.tsx`. So, it seems worth expanding the existing webdriver test to not just check the executions listing for the test build, but also click through to the action page.
To make this change, we need to update the current test to actually execute the build on an executor. Currently when the test build runs, it fails because there are no registered executors. The current test just asserts that the failed execution is displayed in the UI. By running an executor in the test, we can successfully run the execution and click through to the action page to see the action result.
This PR only tests a single auth scenario: the invocation is authenticated, and the user is …

Add webdriver test for action page

---

enterprise/server/remote_execution/copy_on_write/BUILD
enterprise/server/remote_execution/copy_on_write/copy_on_write.go

The `mmap` call will happily succeed if we provide a `sizeBytes` that is larger than the actual file size, but a subsequent out-of-bounds read will fail with an "unexpected fault address" error and crash the executor.
Add some temporary debug logic to check whether this is causing the fault errors that we see occasionally.

Add debug logic for fault error

---

enterprise/server/remote_execution/copy_on_write/copy_on_write.go

This is a little more convenient, since it's not obvious how these returned errors get logged.

Surface mmap validation errors with UnexpectedEvent

---

enterprise/server/raft/store/store.go
proto/raft.proto

Background: https://docs.google.com/document/d/1Vk5TqjFYykkmgtXTOmygtN9HI0fP0zYd6WHd8wOa6bo/edit?tab=t.0

[raft] mark replicas as removed in range descriptor before we remove from raft

---

app/target/target_test_cases_card.tsx
app/target/target_test_suite.tsx

(I mucked up the history for #8131, so am starting over).
Addressing a customer issue: https://github.com/buildbuddy-io/buildbuddy-internal/issues/4272
Previously, if a successful test case had any child content (including text content), we would not render an individual card for the test case. Successful test cases with Playwright attachments, for example, would not show up.
@jdhollen suggested handling `<system-out>` and `<system-err>` specially instead of trying to peek into the `<![CDATA[`.

display individual test cases even if they have `<system-out>` or `<system-err>` children

---

server/testutil/webtester/webtester.go

We are hitting this "session deleted because of page crash" issue: https://stackoverflow.com/questions/53902507/unknown-error-session-deleted-because-of-page-crash-from-unknown-error-cannot/53970825#53970825
`/dev/shm` inside ociruntime is limited to 64MB (we chose this size to match podman). Chrome sometimes crashes because this isn't enough memory.
Passing `--disable-dev-shm-usage` to Chrome makes it stop depending on `/dev/shm`, which fixes this specific issue.

Fix page crash error during webdriver tests

---

enterprise/server/scheduling/scheduler_server/scheduler_server.go

It's enabled everywhere now, except locally and for on-prem apps. This shouldn't affect on-prem apps much, since only firecracker and oci isolation types support it, and those aren't commonly used on-prem as far as we know.

Turn on app-controlled cgroup settings by default

---

proto/remote_execution.proto
server/util/clickhouse/clickhouse.go
server/util/clickhouse/schema/schema.go

Not populating them yet, just adding to the schema.

Add region and self-hosted columns to Executions table

---

app/invocation/cache_requests_card.tsx

Bazel attaches a number of special action IDs to cache requests, such as `prefetcher` when it downloads the inputs for an action that is executed locally. Such actions were frequently rendered as a broken link that treated the special action IDs as digests.
This PR ensures that only actual digests are stylized as links and adds a ` (for local execution)` suffix to prefetcher downloads.

Improve action ID rendering in Cache tab

---

enterprise/server/util/cpuset/BUILD
enterprise/server/util/cpuset/cpuset.go
enterprise/server/util/cpuset/cpuset_test.go
enterprise/server/util/cpuset/numcpu_darwin.go
enterprise/server/util/cpuset/numcpu_linux.go
enterprise/server/util/cpuset/numcpu_windows.go

Make the CPU Leaser numa aware (on linux).
The leaser will prefer to assign a set of processors from the least loaded numa node. It will never return processors from multiple numa nodes in the same lease -- if more processors are requested than are available on a single node, it will return all the processors from the least loaded node.
Obligatory https://www.youtube.com/watch?v=Cqd1Gvq-RBY

Make cpuleaser numa-aware

---

app/errors/error_service.ts
server/testutil/webtester/BUILD
server/testutil/webtester/webtester.go

We generally want to avoid showing error banners to the user. So, we should fail webdriver tests if the error banner is displayed at any point during the test.
This is a follow-up from https://github.com/buildbuddy-io/buildbuddy/pull/8117 - I verified that the new test logic fails with that commit reverted.
We show a "Logged out!" banner when logging out, so a few tests are opted out of this assertion currently. Removing that banner requires some minor auth changes so I split it into a separate PR.

Fail webdriver tests if error banner is displayed

---

enterprise/server/raft/rbuilder/rbuilder.go
enterprise/server/raft/replica/replica.go
enterprise/server/raft/replica/replica_test.go
enterprise/server/raft/sender/sender.go
proto/raft.proto

In sender, use fetchRanges when we fetch active replicas and also fetch
multiple range descriptors at once. The latter is needed in zombie
cleanup in following PRs.
Currently, we use scan to fetch multiple ranges. However, scan returns all range
replicas and the client filter them out. Assuming we have M machines and
N ranges, the client only needs 3N/M ranges on average. So filtering out at the
replica level can save the data transferred on the network.

[raft] Implement a raft command to fetch multiple range descriptors at once

---

server/testutil/webtester/webtester.go

This opt-out check is going away in https://github.com/buildbuddy-io/buildbuddy/pull/8140 but there are a few lingering issues with that PR. Update the test names for a short-term fix.

Fix error banner opt-out check

---

tools/metrics/grafana/dashboards/buildbuddy.json

- Fix broken executor pool CPU usage query by using the node metrics instead of the custom executor metrics (which no longer exist)
- Don't join with `node_uname_info` to get nodename - no longer needed since the node label is applied to all node-exporter metrics now
- Consistently use `1 - idle_time` for CPU usage instead of `user_time + system_time`

Fix and simplify node CPU metrics

---

enterprise/server/util/ociconv/ociconv.go

`os.Getuid` has no failure mode, whereas `user.Current` can fail even though the uid was successfully retrieved. Since we don't care about any part of the user except for the uid, retrieving the other user info is extraneous work and complicates error handling unnecessarily, reporting a warning and short-cicuiting the `isRoot` logic even though we have the uid.

Use `os.Getuid()` instead of `user.Current()` if we only want the uid

---

enterprise/server/remote_execution/containers/firecracker/firecracker.go

Since switching to the host cgroup for memory usage reporting, we've gotten a few user reports where the UI shows the VM's memory usage exceeding the available memory. Switch back to guest stats for now.

Use guest VM stats for peak memory reporting

---

enterprise/server/hostedrunner/hostedrunner.go
enterprise/server/workflow/service/service.go

This will allow us to more easily distinguish between workflows, remote bazel, and "normal" bazel actions when looking at executions in clickhouse.

Set action mnemonic for workflows and remote bazel

---

enterprise/server/remote_execution/execution_server/execution_server.go
enterprise/server/remote_execution/execution_server/execution_server_test.go
enterprise/server/scheduling/priority_task_scheduler/BUILD
enterprise/server/scheduling/priority_task_scheduler/priority_task_scheduler.go
enterprise/server/scheduling/scheduler_server/scheduler_server.go
server/interfaces/interfaces.go

Tested locally with self-hosted executors and shared executors, and also checked the region column.

Populate self-hosted and region fields in ClickHouse

---

enterprise/server/remote_execution/containers/firecracker/firecracker.go

Missed this in https://github.com/buildbuddy-io/buildbuddy/pull/8175

Get last observed memory value from guest too

---

tools/metrics/grafana/dashboards/raft.json

1. Add graphs for zombie counts and errors
2. Add graphs for grpc qps. Use this to monitor qps imbalances across pods.
3. Add rows to organize the graphs.

[raft] graph

---

enterprise/server/test/integration/remote_execution/BUILD

We have a few tests that follow this pattern:
```
for i := 0; i < 10; i++ {
...
cmds = append(cmds, cmd)
}
...
for _, cmd := range cmds {
cmd := cmd
eg.Go(func() error {
...
}
}
eg.Wait()
```
so let's make sure that we have at least 5 CPU to run these commands in
parallel.
Disabled verbose logging as we start to get warnings like this from Bazel
```
stdout (/.../bazel-out/_tmp/actions/stdout-8) 9609824 exceeds maximum size of --experimental_ui_max_stdouterr_bytes=1048576 bytes; skipping
```

integration/remote_execution_test: increase compute unit

---

enterprise/tools/get_executions/BUILD
enterprise/tools/get_executions/get_executions.go

* Allow replacing the `worker` field with the executor hostnames instead of host IDs. This is done by looking up the shared executor listing using the GetExecutionNodes API.
* Allow inlining the execute response (just adds a flag that sets `inline_execute_response=true` in the request).

Add a few convenience features to get_executions

---

.bazelrc
tools/checkstyle/BUILD
tools/checkstyle/checkstyle.sh
tools/prettier/BUILD
tools/prettier/prettier.sh

It's not necessary (and in many cases less hermetic due to binaries looking for data in the output base, not their runfiles directory) to `readlink` runfiles paths, they just need to be made absolute before cd'ing.
Also have the `prettier` wrapper look up `prettier` from runfiles without a nested Bazel invocation and fix its runfiles path to work with `--nolegacy_external_runfiles`.

Clean up runfiles access in checkstyle

---

enterprise/server/raft/store/store.go
server/metrics/metrics.go

When we detect raft zombies, we queries node host with log info which contains
all replicas that have been started in the history. This means that zombies that
have been successfully deleted in the past will always be in the list. 
This PR creates a map to track removed zombies; so that we don't look up for
range descriptors of removed zombies.
Also track the number of zombies deleted successfully.

[raft] don't do extra work on removed zombies

---

.bazelrc
tools/checkstyle/BUILD
tools/checkstyle/checkstyle.sh
tools/prettier/BUILD
tools/prettier/prettier.sh

This reverts commit 347a145b15a11f51d1fb6966c3a5d8defd0f95ac.
I think this change broke prettier and checkstyle https://buildbuddy.buildbuddy.io/invocation/145575c5-93af-4353-91ae-fa00349281c1#@146

Revert "Clean up runfiles access in checkstyle (#8204)"

---

app/invocation/invocation_action_card.tsx

Removes this "0" rendered between output symlinks and stderr:

Fix '0' rendered in action page

---

.bazelrc
MODULE.bazel
buildfix.sh
deps.bzl
tools/checkstyle/BUILD
tools/checkstyle/checkstyle.sh
tools/clang-format/BUILD
tools/prettier/BUILD
tools/prettier/prettier.sh

Reverts the revert https://github.com/buildbuddy-io/buildbuddy/commit/d9d19f0c4bdc195611bf02638b4723abdf159246 with the following additional fixes:
* Use `bazel run` for everything in `buildfix.sh`.
* Always use a hermetic `clang-format` 15 binary (reusing the binaries from the Angular project).
* Fix runfiles handling in prettier wrapper, which is called from `//tools/checkstyle` after `cd`ing into a different directory.

Reland checkstyle/buildfix runfiles changes

---

app/invocation/invocation_exec_log_card.tsx

The span made this render as (note the extra space):
```
Remotely executed actions ( 16 in progress, 2,411 completed)
```

Fix spacing in exec log card header

---

buildfix.sh

After #8198, `buildfix.sh` pointed to a non-existent `//:goimports.sh` target. Point it to the right one!

Fix `buildfix.sh`

---

enterprise/server/cmd/ci_runner/main.go

Ensure gc finishes before snapshotting, which saves disk space.

ci_runner: Disable git gc auto detach

---

app/invocation/cache_requests_card.tsx

In https://github.com/bazelbuild/bazel/commit/998e7624093422bee06e65965f8a575d05d57c27, Bazel started to distinguish between files prefetched as inputs to locally executions and those that are explicitly requested outputs (e.g. of top-level targets with `--remote_download_toplevel`).
This commit recognizes these two cases and no attaches any special meaning to the `prefetcher` action ID, which could be misleading as it was also assigned to action outputs that are never consumed by a local execution.

Adapt handling of special action IDs to Bazel changes

---

WORKSPACE

1ea92ac7ddee2be12f1f58fc04e8f041161d2ba1 made it so that the definition of the `com_google_protobuf` repo in our WORKSPACE file wasn't honored since a previous dep macro already brought in a different version. This is prevented by moving all `http_archive`s for core rules to the top of WORKSPACE.

Ensure that specified versions of core Bazel deps are picked

---

tools/goimports/BUILD
tools/goimports/goimports.sh
tools/prettier/BUILD
tools/prettier/prettier.sh

Use a runfiles library to automatically map the "friendly" (apparent) repo names to the resolved (canonical) runfiles directories.
Tested by adding `common --enable_bzlmod` to `user.bazelrc` and running `./buildfix.sh -a`.

Fix `buildfix.sh` with Bzlmod

---

server/build_event_protocol/build_event_server/BUILD
server/build_event_protocol/build_event_server/build_event_server.go
server/metrics/metrics.go

Unfortunately it doesn't look like the grpc metrics already have a metric like "RPCs currently being handled" - add a new metric for tracking the number of build event stream RPCs in-flight.

Add gauge metric for open invocation streams

---

codesearch/kythestorage/BUILD
codesearch/kythestorage/kythestorage.go

I was stupidly returning the value from pebble.Get directly, forgetting that it's lifetime is only valid until closer.Close() is called. This meant that in the rare case we got two simultaneous requests, the bytes would get invalidated before being read and we'd hit a NPE.
The fix is to copy the bytes before returning them.
One small other fix -- I used ClaimsFromContext to get the groupID to avoid reparsing a jwt.

Don't panic in kythe

---

enterprise/server/remote_execution/containers/firecracker/firecracker.go
enterprise/server/remote_execution/platform/BUILD
enterprise/server/remote_execution/platform/platform.go
enterprise/server/remote_execution/platform/platform_test.go
enterprise/server/remote_execution/snaploader/snaploader.go

BE support so that we can use remote bazel to start from a specific snapshot key

[FC] Add a platform property to specify a snapshot key to start from

---

enterprise/server/remote_execution/execution_server/execution_server.go

This will correctly set the `self_hosted` field in clickhouse without forcing clients to update their executors.
I also slightly improved the log statement when the aux meta is missing.

Assume the executor is self hosted when it doesn't send aux meta

---

server/metrics/metrics.go

The prober latency chart isn't super useful because these buckets are too coarse-grained.
We made these coarse-grained a while back due to issues with high cardinality, but I think we can probably handle higher cardinality now that we're on victoriametrics and we've also restricted the group_id label to a hard-coded list.

Use finer-grained buckets for execution durations

---

enterprise/server/backends/openai/openai.go

This allows you to easily use any openai-compatible endpoint.
Also bumps the default model from `gpt-3.5-turbo` to `gpt-4o`.
Finally, bumps debug log to warning (since it's only logged in an actual error case).

Allow configuration of openai endpoint via flag

---

tools/replay_invocation/BUILD
tools/replay_invocation/replay_invocation.go

Read the logs chunk-by-chunk instead of 4096 bytes at a time. This fixes an issue where a read into the buffer stops before a UTF-8 sequence has terminated, resulting in an invalid UTF-8 string which proto fails to marshal.

Fix invalid UTF-8 when replaying invocation logs

---

enterprise/server/util/oci/BUILD
enterprise/server/util/oci/oci.go
enterprise/server/util/oci/oci_test.go

The ECR credential helper stopped working for one of our on-prem users after they switched from podman to OCI. This is because `oci.Resolve()` doesn't respect credential helpers.
This PR enables the default keychain in `oci.Resolve()` (behind a flag) so that credential helpers will work. The default keychain respects commonly used container auth config files, including `.docker/config.json` and podman's `$XDG_RUNTIME_DIR/containers/auth.json`.
The customer was specifically trying to use `~/.config/containers/auth.json` which doesn't quite work after this PR, but will work if we either patch https://github.com/google/go-containerregistry/pull/2052 or if the customer switches to `~/.docker/config.json` instead (that file is generally the least common denominator and is supported by docker, …

Use default keychain to resolve OCI credentials

---

enterprise/server/remote_execution/containers/firecracker/BUILD
enterprise/server/remote_execution/containers/firecracker/firecracker.go

This will save a tiny bit of time, but that's not the main reason I'm making the change.
Currently, the FirecrackerExecDialDurationUsec metric records the time for 3 dials per action. The first dial is much slower, but the 2nd and 3rd one drive down the average for the metric, so it seems that the par action dial is faster than it really is.

Reuse vmexec connections in firecracker.go

---

app/target/target_test_cases_card.tsx

@fzakaria noticed that failing test cases would show on both the failure card and the success card. Turns out our filtering logic was not looking for `<failure>`, `<skipped>`, or `<error>` child nodes in all cases! This change fixes that filtering logic.

test case successful only if it has no error/failure/skipped child nodes

---

enterprise/server/oidc/oidc.go

We have a use case where we need to be able to filter out users on login by LDAP groups. Our OIDC provider is currently unable to do a group search on LDAP because the OAuth scopes baked into Buildbuddy do not include `groups`. This PR would allow users to add custom OAuth scopes if additional permissions are needed.

Provide config options to add additional OAuth scopes for OIDC

---

enterprise/server/remote_execution/containers/firecracker/BUILD
enterprise/server/remote_execution/containers/firecracker/firecracker.go

I added the `pull_image` and `remove` stages, and I split `init` into `create` and `unpause`.

Add stages to the firecracker_stage_duration_usec metric

---

enterprise/server/remote_execution/containers/firecracker/firecracker_test.go

Instead of using sleeps, use a named pipe to synchronize between processes. This reduces flakiness in this test method from 24/100 to 0/100.

Fix flakiness in TestFirecrackerRun_ReapOrphanedZombieProcess

---

cli/explain/BUILD
cli/explain/compactgraph/compactgraph.go
cli/explain/compactgraph/compactgraph_test.go
cli/explain/explain.go
cli/storage/storage.go
proto/spawn.proto
proto/spawn_diff.proto

The invocation ID is stored in the exec logs as of Bazel 7.5.0 and 8.1.0. The `--bes_results_url` is obtained from the flags parsed from the last build-like command, if available.

explain: Print invocation URLs if available

---

tools/probers/bazelrbe/BUILD
tools/probers/bazelrbe/bazelrbe.go

- Default the bazel binary to "bazel" so that we don't have to pass `--bazel_binary=bazel`
- Don't use `bazel.Invoke()` - it uses a new HOME directory for every invocation which means bazel is re-downloaded and re-installed on each run, which takes a while. Instead, use the system HOME directory so that bazel is installed to `~/.cache` but point `--output_base` into the temp dir so that nothing from the build is persisted.

Make prober script easier to run locally

---

app/invocation/cache_requests_card.tsx
docs/remote-bazel-introduction.md
enterprise/app/code/code_v2.tsx
enterprise/app/codesearch/codesearch.css
enterprise/app/codesearch/codesearch.tsx
enterprise/app/tap/flakes.tsx
tools/prettier/prettier.sh

`prettier.sh` has been broken since 260b7e71f37 - the bash syntax `[[ -z "${paths[*]+}" ]]` for checking whether an array is empty doesn't seem to work.

Fix prettier.sh

---

tools/prettier/prettier.sh

Now getting `/root/workspace/output-base/execroot/buildbuddy/bazel-out/platform_linux_x86_64-fastbuild/bin/tools/checkstyle/checkstyle.runfiles/buildbuddy/tools/prettier/prettier.sh: line 80: paths: unbound variable`
Desperately need to rewrite this in Go

Fix prettier.sh again

---

enterprise/server/backends/distributed/distributed.go
enterprise/server/backends/distributed/distributed_test.go
enterprise/server/byte_stream_server_proxy/BUILD
enterprise/server/byte_stream_server_proxy/byte_stream_server_proxy.go
enterprise/server/content_addressable_storage_server_proxy/content_addressable_storage_server_proxy.go
server/metrics/metrics.go

I thought that I would be able to measure this using the prometheus gRPC metrics, but I couldn't find one tracking bytes. This will require updating the dashboards because I changed some of the metric names, will follow-up with that. I tried this out in dev for a couple of hours and it looks like we're proxying a lot of bytes there!

Add bytes-proxied metrics to BSProxy and CASProxy servers
