buildbuddy-io/buildbuddy

enterprise/app/review/file_content_monaco.tsx

fix issue where you can't create new comments on left hand side of review

---

enterprise/server/remote_execution/containers/podman/podman.go

Enable podman stats by default

---

server/tables/tables.go

Update server/tables/tables.go

Default: 0

---

enterprise/server/remote_execution/containers/podman/podman.go

Add podman `pids-limit` flag

---

cli/plugin/plugin.go

Instead of downloading the git repo to an intermediate temp directory under /tmp, download it as a `.tmp`-suffixed sibling dir next to the final path where it will be cloned. This ensures it will live on the same device so that it can be safely renamed afterwards.
Also fix a minor issue that we fail to parse `buildbuddy.yaml` when it is completely empty (i.e. initialized with `touch ~/buildbuddy.yaml`).
Reproduced and verified with:
```
unshare -mr sh -ec '
mount -t tmpfs -o size=1G none /tmp
mount -t tmpfs -o size=1G none ~/.cache/buildbuddy
bb install --user bduffany/go-highlight
'
```
**Related issues**: Fixes https://github.com/buildbuddy-io/buildbuddy/issues/6567

cli: fix 'invalid cross-device link' when installing plugins

---

server/util/grpc_client/grpc_client.go

When a gRPC target is missing a protocol like `grpc://` or `grpcs://`, Bazel assumes `grpcs://`. Update our target parsing so that our various tools parse targets the same way that Bazel does, to make our tools more ergonomic / bazel-compatible.

Make grpc_client's target parsing match bazel's

---

server/util/flagutil/flagutil.go

Accidentally only had this change locally when I merged #6246

Small change that should have been in #6246

---

enterprise/server/remote_execution/containers/podman/podman.go

Retry podman 'database is locked' errors

---

enterprise/server/raft/store/store.go
proto/raft.proto
server/util/proto/proto.go

[raft] record last replica id and added timestamp in range descriptor

---

cli/remotebazel/BUILD
cli/remotebazel/remotebazel.go
cli/remotebazel/remotebazel_test.go

**Related issues**: Fixes https://github.com/buildbuddy-io/buildbuddy-internal/issues/3338

Fix remote bazel if local commit has not been pushed yet

---

app/invocation/cache_requests_card.tsx
app/invocation/invocation.css

Fixes https://github.com/buildbuddy-io/buildbuddy-internal/issues/3381

cache requests card: separate button for downloading vs. navigating

---

enterprise/server/raft/client/client.go

specified timeout is too small is not helpful in debugging, because it's usually
a symptom where there are multiple failures.

raft: return more meaningful error than timeout too small

---

enterprise/server/workflow/service/service.go

Set a timeout on workflow actions

---

app/invocation/BUILD
app/invocation/execution_status.tsx
app/service/rpc_service.ts
app/util/BUILD
app/util/rpc.ts

Add utility function to call a streaming RPC with retry

---

enterprise/server/remote_execution/execution_server/execution_server.go

In practice, we were publishing UNKNOWN as the initial status instead of QUEUED. Publish QUEUED instead.

Don't publish UNKNOWN ExecutionStage

---

enterprise/app/code/code.tsx

This will allow us to easily show diffs input files that changed in the UI.

Add support for diffing bytestream files in editor

---

app/invocation/invocation.tsx

Hide runner execution streaming behind flag

---

enterprise/server/raft/store/store_test.go

[raft] fix race condition in tests

---

enterprise/server/raft/driver/driver.go

[raft] fix race conditions in driver

---

enterprise/server/raft/store/store.go

[raft] make RemoveData op best effort in RemoveReplica

---

server/build_event_protocol/event_parser/BUILD
server/build_event_protocol/event_parser/event_parser.go
server/build_event_protocol/event_parser/event_parser_test.go

allow setting tags via workspace_status_command

---

app/invocation/invocation_model.tsx

try to get BUILDBUDDY_LINKS from workspaceStatus if not in buildMetadata

---

enterprise/server/raft/store/store.go

[raft] remove debug logging and uses s.log 

---

enterprise/server/raft/driver/BUILD
enterprise/server/raft/driver/driver.go
enterprise/server/raft/store/store.go
enterprise/server/raft/storemap/storemap.go

[raft] placement driver: implement logic to down-replicate

---

enterprise/server/raft/store/store.go

Right now we only update usage tags in gossip when we add/remove a range but not
when the range usage is updated. Placement driver relies on store_usage tag to 
understands the usage for the stores in raft clusters.

[raft] update usage tags when range usage updated

---

enterprise/server/raft/store/store.go

[raft] another race condition

---

proto/BUILD
proto/auth.proto

Add an AuthService for remote authentication

---

enterprise/server/raft/driver/driver.go

[raft] another race condition in driver

---

enterprise/app/review/view_pull_request.tsx

fix issue where review id wasn't being updated properly on reply

---

cli/login/login.go

Update bb login usage string for --allow_existing flag

---

app/invocation/cache_requests_card.tsx
app/invocation/invocation_action_card.tsx
app/service/rpc_service.ts
proto/config.proto
server/util/region/region.go

action results are a little more involved, so i'll do them separately.

use regional service for metadata and tree lookups

---

enterprise/server/auth_service/BUILD
enterprise/server/auth_service/auth_service.go
enterprise/server/auth_service/auth_service_test.go
enterprise/server/cmd/server/BUILD
enterprise/server/cmd/server/main.go
proto/BUILD
proto/auth.proto
server/environment/environment.go
server/interfaces/BUILD
server/interfaces/interfaces.go
server/libmain/BUILD
server/libmain/libmain.go
server/real_environment/real_environment.go

Depends on: https://github.com/buildbuddy-io/buildbuddy/pull/6622

Skeleton implementation of the Auth API added in #6622

---

server/build_event_protocol/target_tracker/target_tracker.go

We can just attempt an update and then return an error if no rows are affected.

Remove unnecessary select statement when updating targets

---

enterprise/server/githubapp/githubapp.go
proto/github.proto

use FileSummary instead of File when fetching commit diffs.

---

enterprise/app/workflows/action_list.tsx
enterprise/server/workflow/service/service.go

Show history from all branches if a workflow never runs on main/master

---

enterprise/server/remote_execution/filecache/filecache.go
enterprise/tools/mount_temp_xfs.sh

Context: https://buildbuddy-corp.slack.com/archives/C05GZM1EGM8/p1705093049089379
Also add a little tool to make it easier to test with XFS locally.

Fix files not being cloned when initially adding to filecache

---

app/invocation/execution_status.tsx
app/invocation/invocation.tsx
app/invocation/invocation_action_card.tsx
app/service/rpc_service.ts

use regional service to stream execution data.

---

enterprise/server/remote_execution/executor/BUILD
enterprise/server/remote_execution/executor/executor.go
enterprise/server/remote_execution/platform/platform.go
enterprise/server/remote_execution/platform/platform_test.go

Allow setting a timeout on build actions

---

proto/api/v1/action.proto
server/api/common/common.go

Expose shard/run/attempt in API for test actions

---

app/components/select/select.css
app/components/select/select.tsx
enterprise/app/review/BUILD
enterprise/app/review/review.css
enterprise/app/review/review_model.ts
enterprise/app/review/view_pull_request.tsx
enterprise/server/githubapp/githubapp.go
proto/github.proto

show revision picker on review page

---

enterprise/server/quota/BUILD
enterprise/server/quota/quota_manager.go
enterprise/server/quota/quota_manager_test.go

Switching to a JOIN here means we no longer need a transaction and we issue fewer queries to the database.

Use `JOIN` for quota fetch

---

enterprise/server/secrets/secrets.go

Just a comment explaining this function; added it for easy reference and readability.

Add doc comment for `UpdateSecrets`

---

server/build_event_protocol/build_event_handler/build_event_handler.go
server/util/redact/BUILD
server/util/redact/redact.go
server/util/redact/redact_test.go

**Related issues**: Fixes https://github.com/buildbuddy-io/buildbuddy-internal/issues/3398

[ci_runner] Redact bazel sub command

---

enterprise/server/remote_execution/containers/podman/podman.go

Make 'database is locked' regex more broad

---

enterprise/server/cmd/ci_runner/main.go

[ci_runner] Disable checks for force updates during git fetch

---

server/tables/tables.go

fix index creation: CREATE INDEX doesn't support specifying both ALGORITHM and LOCK

---

enterprise/server/cmd/ci_runner/main.go
enterprise/server/test/integration/ci_runner/ci_runner_test.go
enterprise/server/workflow/config/config.go
enterprise/server/workflow/service/service.go

[ci_runner] Default to fetch depth=1 if possible to improve fetch performance

---

app/invocation/workflow_rerun_button.tsx

**Related issues**: Fixes https://github.com/buildbuddy-io/buildbuddy-internal/issues/3455#event-12987646000

Fix re-run from clean button for non-firecracker workflows

---

app/invocation/cache_requests_card.tsx
app/invocation/invocation.css

Fix download button layout when text overflows

---

app/service/rpc_service.ts
app/util/async.ts
app/util/async_test.ts

Make fetchBytestreamFile cancelable

---

enterprise/server/remote_execution/containers/podman/podman.go

Loosen 'database is locked' regex again

---

proto/raft.proto

**Related issues**: https://github.com/buildbuddy-io/buildbuddy-internal/issues/3452

[raft]  Add a session proto message for idempotency support

---

server/buildbuddy_server/buildbuddy_server.go

- Return "Not found" message if the blob is not found in blobstore, instead of "Internal server error" (for easier debugging)
- Don't try to fetch `actioncache://` blobs from blobstore, since only CAS entries get persisted

Small fixes for bytestream download endpoint

---

proto/BUILD

Add vtproto compiler for auth_go_proto

---

enterprise/server/workflow/config/config.go
enterprise/server/workflow/service/service.go

[ci_runner] Turn off merge commit sha usage by default

---

enterprise/server/hostedrunner/hostedrunner.go

[Remote Bazel] By default, use non-root user

---

cli/remotebazel/remotebazel.go
cli/remotebazel/remotebazel_test.go

**Related issues**: Fixes https://github.com/buildbuddy-io/buildbuddy-internal/issues/3160

[Remote Bazel] Fix applying binary patches

---

enterprise/server/cmd/ci_runner/main.go

Disable git interactive prompts in ci_runner

---

enterprise/server/cmd/server/BUILD
enterprise/server/cmd/server/main.go
enterprise/server/util/redisutil/redisutil.go

Noticed some non-structured log output in the logs while testing out some pubsub stuff.

Configure go-redis to use zerolog

---

enterprise/server/remote_execution/dirtools/dirtools.go

This PR attempts to make some improvements that I think would help when trying to grok this code:
* Rename `treesToUpload` to `outputDirectoryPaths`, since it's a list of output paths that correspond to `ActionResult.output_directories`, not a list of `Trees`.
* Use more consistent naming for all variables that refer to paths: always start with an unambiguous qualifier like `parent` or `child`, and consistently use `FullPath` to refer to an absolute path rather than less obvious alternatives like `fqfn` (it's an acronym that not everyone may get) and `dir` (can be confused with `Directory` proto)
* Rename `uploadFileFn` and `uploadDirFn` to `visitFile` and `visitDir` since these don't upload anything; they just collect things to upload.
* Rename `trees` to `outputDirectoryTrees` to make …

Rename some variables and add comments in UploadTree to help with readability

---

enterprise/server/workflow/config/config.go
enterprise/server/workflow/config/config_test.go

Make wildcard matching in workflow branch patterns more flexible

---

buildbuddy.yaml

Run required checks when release branch is pushed

---

.bazelrc

https://github.com/actions/runner-images/issues/10004

Attempt to work around Windows failure

---

enterprise/server/raft/driver/driver.go

[raft] fix a race condition in driver

---

proto/BUILD
proto/runner.proto

fix a random extra dep warning that i saw in the windows build logs

---

codesearch/server/server.go
proto/search.proto

This is useful for linking to the file.

Index document sha too

---

codesearch/cmd/server/BUILD
codesearch/server/server.go
proto/index.proto
proto/search.proto

App does auth. Add server_image target so we can check in deployment files.

Add namespace param and image target

---

codesearch/server/BUILD
codesearch/server/server.go

Ensure scratch dir exists before use

---

enterprise/server/raft/rangelease/rangelease.go

**Related issues**: https://github.com/buildbuddy-io/buildbuddy-internal/issues/3415
`TestSplitNonMetaRange` sometimes timed out because `ensureValidLease()` is stuck in the renew loop. This can happen when `renewLease` skipped to send cas request when the `newValue` and `expectedValue` are the same, but the `replica.GetRangeLease()` is different from the `expectedValue`, so the following `verifyLease` fails.  
With this change, the number of  `TestSplitNonMetaRange` timeout is reduced to ~15 from ~30, when `--runs_per_test=100`

[raft] fix a timeout issue in store_test

---

enterprise/server/cmd/ci_runner/BUILD
enterprise/server/cmd/ci_runner/main.go
server/util/redact/redact.go

[RB] Redact commands before displaying in UI

---

enterprise/server/oidc/BUILD
enterprise/server/oidc/oidc.go
enterprise/server/oidc/oidc_test.go
server/build_event_protocol/build_event_handler/BUILD
server/build_event_protocol/build_event_handler/build_event_handler.go
server/interfaces/interfaces.go
server/nullauth/nullauth.go
server/testutil/testauth/testauth.go
server/util/authutil/BUILD
server/util/authutil/authutil.go
server/util/authutil/authutil_test.go

Move ParseApiKeyFromString out of Authenticator interface and into authutil.

---

enterprise/server/cmd/ci_runner/main.go

Log git sync errors to BES log

---

enterprise/server/raft/testutil/testutil.go

So if cannot gracefully stop in 10 seconds, we will hard stop grpc server.

[raft] Add a deadline when stop store in test

---

enterprise/server/raft/cache/cache.go
enterprise/server/raft/cache/cache_test.go

[raft] pass context to cache.Stop()

---

enterprise/server/hostedrunner/BUILD
enterprise/server/hostedrunner/hostedrunner.go

[RB] Add missing RBE flag

---

enterprise/server/certgenerator/certgenerator.go

Needed for forwarding through management server.

Allow port forwarding when using SSH certs.

---

app/format/format.tsx
app/root/root.css
cli/remotebazel/remotebazel.go
enterprise/app/filter/filter.tsx
enterprise/server/cmd/ci_runner/main.go
enterprise/server/hostedrunner/hostedrunner.go

This is what the UI looks like
**Related issues**: Fixes https://github.com/buildbuddy-io/buildbuddy-internal/issues/3430

[RB] Set the build user and add a remote bazel role

---

enterprise/server/raft/leasekeeper/leasekeeper.go
enterprise/server/raft/listener/listener.go

**Related issues**: https://github.com/buildbuddy-io/buildbuddy-internal/issues/3496
During store shutdown, nodehost.Close() sometimes hangs on Publish, because raft
listener leaderUpdated got stuck when leasekeeper shutdown and no one process
leader update events.
This PR adds a method to remove listener. When watchLease() received quitAll
signal, it removes the listener.

[raft] remove listener when we quit leasekeeper

---

app/invocation/invocation_coverage_card.tsx
app/root/root.css

Add sorting and totals to coverage

---

deps.bzl
enterprise/server/remote_execution/containers/ociruntime/BUILD
enterprise/server/remote_execution/containers/ociruntime/ociruntime.go
enterprise/server/remote_execution/containers/ociruntime/ociruntime_test.go

Provision test OCI runtime binary with bazel

---

.github/workflows/test-executor-linux-arm64.yaml

One more try at deflaking arm64 tests

---

enterprise/server/raft/store/store.go

need the ability to disable txn cleanup in tests.

[raft] add a flag to enable txn cleanup.

---

enterprise/server/certgenerator/certgenerator.go
proto/certgenerator.proto
server/ssl/ssl.go
tools/bbcert/BUILD
tools/bbcert/bbcert.go

Add support for k8s cert generation.

---

tools/bbcert/bbcert.go

Support EdDSA keys in bbcert.

---

enterprise/app/codesearch/result.tsx

- Link each line to that line in the code editor.
- Link each file to that file at that sha in the editor.
- Include pq param so we can highlight in the editor.

Link to code editor from search results

---

tools/bbcert/bbcert.go

Add missing break.

---

proto/scheduler.proto

**Related issues**: https://github.com/buildbuddy-io/buildbuddy-internal/issues/3491

Add proto for custom resources

---

enterprise/server/raft/driver/driver.go
enterprise/server/raft/txn/txn.go

[raft] remove go func() from txn coordinator and driverQueue Start()

---

enterprise/server/raft/store/store.go
enterprise/server/raft/store/store_test.go

[raft] add test for upreplicate

---

server/build_event_protocol/invocation_format/invocation_format.go
server/build_event_protocol/invocation_format/invocation_format_test.go

allow TAGS to be up to 255 chars long.

---

enterprise/server/raft/store/store_test.go

[raft] add a test for down replicate

---

enterprise/app/codesearch/codesearch.css

This just makes it a little easier to look at / want to click on.

Mellow highlight color and add on-hover events

---

.github/workflows/release-cli.yaml

The build "just works" with the new arm64 runner image distributed by ARM Limited.
https://github.com/buildbuddy-io/buildbuddy/actions/runs/9500724839/job/26184480216?pr=6814

Add CLI linux/arm64 build to release

---

enterprise/server/raft/driver/BUILD
enterprise/server/raft/driver/driver.go
enterprise/server/raft/store/store.go
enterprise/server/raft/storemap/BUILD
enterprise/server/raft/storemap/storemap.go

[raft] add clock to driver and storemap

---

enterprise/server/raft/driver/BUILD
enterprise/server/raft/driver/driver.go
enterprise/server/raft/store/store.go
enterprise/server/raft/store/store_test.go
enterprise/server/raft/storemap/BUILD
enterprise/server/raft/storemap/storemap.go
enterprise/server/raft/testutil/testutil.go

Also add a Stop() method to TestingStore where it leave and shutdown gossip
manager.

[raft] add a test for replace dead replicas

---

.github/workflows/release-cli.yaml

**Related issues**: https://github.com/buildbuddy-io/buildbuddy/issues/6813

Fix arch suffix for CLI on linux/arm64

---

enterprise/server/raft/driver/driver.go
enterprise/server/raft/store/store.go

1. pass nhlog into driver, so that when debugging test, we can tell where the
log is from
2. fix context.TODO()

[raft] driver misc

---

enterprise/app/code/code.tsx

Adds a edit button to the code editor if being viewed as a search result.
In search result mode, hides any notion of any active changes that may be ongoing.

Add edit button to code editor search result

---

enterprise/server/cmd/ci_runner/BUILD
enterprise/server/cmd/ci_runner/main.go

I think this broke the mac build: https://buildbuddy.buildbuddy.io/invocation/c990ff08-52b8-435e-b5a5-ee4ae4a3dc61

Revert "ci runner: try to reclaim disk space when usage is high"

---

enterprise/server/backends/pubsub/pubsub.go
enterprise/server/backends/pubsub/pubsub_test.go

Fix pubsub channels not getting closed

---

enterprise/server/backends/userdb/userdb.go

Get user's group memberships in the same query as the user

---

server/util/db/db.go

**Related issues**: Fixes https://github.com/buildbuddy-io/buildbuddy/issues/6846

Log parameterized queries

---

cli/login/login.go

Fix bb login when using org-level keys

---

WORKSPACE
WORKSPACE.bzlmod

We are using toolchains_musl instead.

Remove zig toolchain repo

---

enterprise/app/root/root.tsx

oops, fix flipped dark theme bit on flakes terminal

---

app/service/rpc_service.ts
proto/config.proto
proto/context.proto
server/static/static.go

send app bundle hash in request context

---

enterprise/server/raft/store/store.go

[raft] remove debugging log

---

.bazelrc

The upstream issue was resolved.
No RCA though.

Windows: remove workaround

---

enterprise/server/cmd/ci_runner/main.go

Send du output to BES logs

---

enterprise/server/workflow/service/service.go

**Related issues**: Partial revert of https://github.com/buildbuddy-io/buildbuddy/pull/6684

[ci_runner] Fix rerunning worklows triggered by pull request

---

enterprise/server/workflow/service/service.go

We currently have a weird approach where the workflow service will read the workflow action from the buildbuddy.yaml and pass some - but not all - of the data as flags to the ci_runner. The ci_runner then must re-read the buildbuddy.yaml to get the rest of the data. Instead the workflow service should just serialize the action and pass it to the ci_runner, and the ci_runner can read all of the data from there. This should make things simpler, and will make it easier to add new fields to the workflow config.
Another benefit is that the ci_runner won't be able to read the buildbuddy.yaml until it checks out a branch. But it sometimes needs the info in the config to determine how to checkout the branch (i.e. if merge-with-base is enabled)

[ci_runner] Always send the serialized action to the ci_runner

---

server/build_event_protocol/target_tracker/BUILD
server/build_event_protocol/target_tracker/target_tracker.go
server/build_event_protocol/target_tracker/target_tracker_test.go

write out test target cached-ness to db

---

buildpatches/io_kythe.patch
codesearch/cmd/server/BUILD
codesearch/cmd/server/server.go
codesearch/kythe/server/BUILD
codesearch/kythe/server/server.go
codesearch/server/BUILD
codesearch/server/server.go
go.mod
go.sum

Pretty basic, just exposes the RPCs on the server port and serves data from a pebble database.
Next steps will be figuring out how to get data into this thing.

Add a simple kythe RPC service

---

proto/workspace.proto

Changes from last proposal:
- changes is now a list instead of a map
- consolidated Node / Change into a single `Node` message
- simpler `Repo` message that doesn't include fields that we don't need

Add workspace proto

---

enterprise/server/remote_execution/containers/ociruntime/ociruntime.go

* Don't mount empty layers - if an image has multiple empty layers, then the overlay mount will fail, due to the same directory appearing twice in `lowerdir` (which is apparently invalid)
* Fix `layerDigests` logic - we were previously relying on `PullImage` to always be called, which sets `c.layerDigests`. But `PullImage` can be skipped if the image is already cached. Instead, compute the layer digests on the fly, using `imageStore.CachedLayers`

Fix some bugs with OCI image handling

---

enterprise/server/backends/prom/prom.go

To make debugging slightly easier.

add group id to prom log

---

tools/cacheload/cacheload.go

cacheload: fix panic when read_qps=0

---

enterprise/server/backends/pebble_cache/pebble_cache.go

Right now when e.samples channel is full, the iter can stay open full for a long
time.

[pebble cache] close the iter when e.samples is blocked

---

enterprise/app/tap/flakes.tsx

fix up loading state on flakes page a bunch.

---

app/target/target_flaky_test_card.tsx
enterprise/app/tap/flakes.tsx

render errors in addition to failures on flake sample card.

---

enterprise/server/backends/userdb/userdb.go

getUser is now a single select, so we do not need to maintain READ REPEATABLE isolation when calling it unless we are planning to do more reads.

We no longer need to wrap getUser in a transaction

---

enterprise/server/cmd/server/BUILD
enterprise/server/cmd/server/main.go
enterprise/server/workspace/BUILD
enterprise/server/workspace/workspace_service.go
proto/BUILD
proto/buildbuddy_service.proto
server/buildbuddy_server/BUILD
server/buildbuddy_server/buildbuddy_server.go
server/capabilities_filter/capabilities_filter.go
server/environment/environment.go
server/interfaces/BUILD
server/interfaces/interfaces.go
server/real_environment/real_environment.go

This is pretty much all boilerplate, endpoints just return:
```
status.UnimplementedError("Not implemented")
```

Add workspace service boilerplate

---

enterprise/server/remote_execution/containers/podman/podman.go

Add database retry for another exit code (255)

---

.github/workflows/build-executor-win.yaml

Make BES auth optional for windows executor CI

---

codesearch/cmd/cli/cli.go

This is more useful for debugging.

Print squery results in a more useful way

---

enterprise/server/raft/driver/BUILD
enterprise/server/raft/driver/driver.go
enterprise/server/raft/driver/driver_test.go
enterprise/server/raft/store/store_test.go

[raft] rebalance based on replica count.

---

enterprise/server/raft/driver/driver.go

[raft] flip replica id and shard id in logs

---

enterprise/server/raft/driver/driver.go

This allows me to check how a range is moved between nodes.

[raft] add debug log for rebalance

---

enterprise/server/remote_execution/containers/ociruntime/ociruntime.go
enterprise/server/remote_execution/containers/ociruntime/ociruntime_test.go

OCI runtime: implement pause and unpause

---

app/terminal/BUILD
app/terminal/terminal.tsx

Screenshot:
And full-screen view:

Add full-screen button to terminal 

---

buildbuddy.yaml
enterprise/server/cmd/ci_runner/main.go
enterprise/server/test/integration/ci_runner/ci_runner_test.go
enterprise/server/workflow/config/config.go

[ci_runner] Support arbitrary commands in workflows

---

server/remote_cache/content_addressable_storage_server/content_addressable_storage_server.go

Context in https://github.com/buildbuddy-io/buildbuddy-internal/issues/3175#issuecomment-1985787901

Fix min_level comparison

---

app/shortcuts/shortcuts.tsx
enterprise/app/codesearch/BUILD
enterprise/app/codesearch/codesearch.tsx

Code seach: make '/' select the search box

---

enterprise/server/remote_execution/container/container.go
enterprise/server/remote_execution/containers/podman/podman.go

These will be useful for the OCI runtime implementation which will also use cgroup polling for stats.

Move podman cgroup stats tracking utils into a shared location

---

enterprise/server/cmd/ci_runner/main.go

I noticed that our github statuses were only being posted when workflows were "Queued" and "Finished", and were not updated when they were "Running". 
This was a regression from https://github.com/buildbuddy-io/buildbuddy/commit/861d44ea3b35fe6e29b5d583d565738edbe3096b where we started publishing the WorkspaceStatus event before the BuildMetadata event. We need the BuildMetadata event to be published first, because the [status reporter checks the role of the invocation](https://github.com/buildbuddy-io/buildbuddy/blob/master/server/build_event_protocol/build_status_reporter/build_status_reporter.go#L73).

[ci_runner] Fix github running statuses not being reported

---

codesearch/query/regexp_query.go

This makes it so you can AND terms by putting them in quotes, otherwise everything is ORd.
Inspired by @luluz66's bad query "go file"

Handle quoted term query strings

---

enterprise/app/codesearch/BUILD
enterprise/app/codesearch/codesearch.css
enterprise/app/codesearch/result.tsx
enterprise/server/backends/pebble_cache/pebble_cache.go

Add an expand button to search results to show all snippets.

Allow expanding search results

---

enterprise/app/codesearch/codesearch.css
enterprise/app/codesearch/result.tsx

- Removes use of OutlineButton
- Adds icon
- Renders "matches" or "match" depending on how many additional matches there are

Code search more button tweaks

---

enterprise/app/codesearch/codesearch.tsx

The only important part is switching from:
```
router.setQueryParam("q", this.query);
```
to:
```
router.updateParams({ q: this.inputText });
```
The former uses [replaceState](https://developer.mozilla.org/en-US/docs/Web/API/History/replaceState) while the later uses [pushState](https://developer.mozilla.org/en-US/docs/Web/API/History/pushState).
The rest of the PR is making the url parameter the source of truth rather than just an afterthought. This means if you change the url parameter (either manually, programmatically, or via browser back navigation) - the component will render the results for the new query.

Support history navigation for search results

---

enterprise/server/util/pebble/pebble.go

Tested locally. Manually added a sleep in generateSamplesForEviction, and then grab a profile.

add profile for open/close pebble iterator

---

enterprise/server/cmd/ci_runner/main.go

Fix 'bazel' status reported for each workflow

---

server/tables/tables.go

This is causing issues for sqlite

Remove NOT NULL constraint on Usage final_before_usec

---

enterprise/server/action_cache_server_proxy/BUILD
enterprise/server/action_cache_server_proxy/action_cache_server_proxy.go
enterprise/server/action_cache_server_proxy/action_cache_server_proxy_test.go

Add a test for action_cache_server_proxy

---

enterprise/server/cmd/executor/executor.go

Let the executor use different cache and app targets

---

codesearch/index/index.go

BAD BAD BAD
2024/07/01 15:26:51.905 INF LOOP[0], list is 499 long name=reader-tylerw
2024/07/01 15:26:51.905 INF LOOP[1], list is 570 long name=reader-tylerw
2024/07/01 15:26:51.905 INF LOOP[2], list is 641 long name=reader-tylerw
2024/07/01 15:26:51.905 INF LOOP[3], list is 938 long name=reader-tylerw
2024/07/01 15:26:51.905 INF LOOP[4], list is 641 long name=reader-tylerw
2024/07/01 15:26:51.905 INF LOOP[5], list is 325 long name=reader-tylerw
2024/07/01 15:26:51.905 INF LOOP[6], list is 2 long name=reader-tylerw
2024/07/01 15:26:51.905 INF LOOP[7], list is 2 long name=reader-tylerw
GOOD GOOD GOOD
2024/07/01 15:25:57.812 INF LOOP[0], list is 499 long name=reader-tylerw
2024/07/01 15:25:57.813 INF LOOP[1], list is 495 long name=reader-tylerw
2024/07/01 15:25:57.813 INF LOOP[2], list is …

Fix anding of posting lists

---

codesearch/cmd/cli/cli.go
codesearch/query/regexp_query.go

- Don't show blank lines before the match
- Dont insert a fake snippet if there is already a content match snippet
- Use snippets in the CLI too for consistency / easier debugging

nicer snippets

---

enterprise/app/codesearch/codesearch.tsx

Change search input text when query param changes

---

enterprise/server/backends/pebble_cache/BUILD
enterprise/server/backends/pebble_cache/pebble_cache.go
enterprise/server/backends/pebble_cache/pebble_cache_test.go
server/util/timeutil/BUILD
server/util/timeutil/timeutil.go

recreate iterator every X minutes in sampler

---

server/remote_cache/content_addressable_storage_server/content_addressable_storage_server.go

Flip tree_cache_min_level back to 2

---

app/target/target_v2.tsx

only show target history button for test targets.

---

server/static/static.go

static: flip "app.trends_range_selection" to true

---

app/BUILD.bazel
app/components/search_bar/BUILD
app/components/search_bar/search_bar.css
app/components/search_bar/search_bar.tsx
enterprise/app/code/BUILD
enterprise/app/code/code.css
enterprise/app/code/code.tsx
enterprise/app/org_picker/org_picker.css
static/image/user-regular.svg

Also made some general styling tweaks and hid "sidekicks" and some noisy breadcrumbs in search mode.
There are some niceties I'd like to add, but it's relatively usable in its current state.

Add a search bar to code editor in search mode

---

codesearch/posting/BUILD
codesearch/posting/posting.go

to make scoring faster i'm gonna encode term positions in the posting list. To do that we need to change how posting lists are structured and encoded. This is the first step of that. Code is unused (but it passes all tests when enabled).

Introduce a posting set

---

app/invocation/invocation_suggestion_card.tsx

See https://buildbuddy.slack.com/archives/CUHBFVATU/p1720210335904999?thread_ts=1720199583.543539&cid=CUHBFVATU for context.

Don't include `- ` in front of resource_request suggestions

---

enterprise/server/cmd/ci_runner/BUILD
enterprise/server/cmd/ci_runner/main.go

Fixes https://buildbuddy-corp.slack.com/archives/C04S4M5U3BK/p1720047175177259

[ci_runner] Set default merge_with_base=true for the execute workflow API too

---

enterprise/app/code/code.tsx

I messed this up a bit in https://github.com/buildbuddy-io/buildbuddy/pull/6987

Fix picker-based code editor navigation

---

tools/bbcert/BUILD
tools/bbcert/bbcert.go

Skip ssh certificate generation if no ssh keys are found.

---

enterprise/app/tap/flakes.tsx

- show loading state below already-loaded samples
- show link to flaky/failed invocation even if the logs fail to load/parse.

fix up loading state for flake samples.

---

server/remote_asset/fetch_server/fetch_server.go
server/remote_asset/fetch_server/fetch_server_test.go

Originally suggested by @hunshcn in #6911.
In each FetchBlobRequest, there are 2 digest functions:
a. One digest function to verify the content of the downloaded blob.
This is usually set by the Bazel repository rules calling
`repository_ctx.download` and `repository_ctx.download_and_extract` API.
Usually, this is set by http_archive rules to SHA256, but in recent
community rules, such as rules_js and rules_proto, SHA512 and SHA384 are
also used.
b. One digest function to store the blob in cache for the client to
subsequently downloaded. This is usually set to either SHA1, SHA256, or
Blake3, which are the digest functions Bazel support in `startup
--digest_function`. The default is SHA256.
If the Bazel client is also configured with
`--experimental_remote_downloader` pointing to …

fetch_server: support storing blob using checksum digest func

---

enterprise/server/raft/driver/driver.go

The mutex need to protect both pq and pqItemMap. Increase the scope of the
mutex, to avoid race conditions that cause unexpected
"unexpected_pq_item_not_found" in test.

[raft] fix race condition in driver

---

enterprise/server/cmd/ci_runner/main.go

**Related issues**: This will help make this PR https://github.com/buildbuddy-io/buildbuddy/pull/6961 simpler

[ci_runner] Refactor ci_runner to add custom flags to .bazelrc rather than manually parsing into the command

---

enterprise/server/raft/store/store.go
enterprise/server/raft/store/store_test.go

StopReplica doesn't involve membership change.
Remove TestCleanupZombieShards test because we cannot remove the only
replica for a shard
**Related issues**: https://github.com/buildbuddy-io/buildbuddy-internal/issues/3570

[raft] request membership change when clenup zombie nodes

---

app/invocation/invocation_action_card.tsx

Render pressure stall durations

---

deps.bzl

Upgrade firecracker to v1.8.0

---

app/invocation/invocation_overview.tsx
app/router/router.tsx

Make all invocation details right-clickable

---

deps.bzl
enterprise/server/remote_execution/containers/firecracker/firecracker.go

**Related issues**: More context at https://buildbuddy-corp.slack.com/archives/C01D5GHRJ59/p1721075695733979

Upgrade firecracker to v1.8.0 - disable ACPI

---

enterprise/server/raft/registry/registry.go
enterprise/server/raft/store/store.go

-fix typos in logging
-adding the request to logs when split failed
-change cluster/node logging to make it easy to search logs

[raft] add/modify some logging

---

app/components/search_bar/search_bar.css
enterprise/app/code/code.css
enterprise/app/org_picker/org_picker.css

Code editor styling tweaks

---

cli/fix/fix.go
deps.bzl
tools/update_deps.sh

Adding -prune to scripts and docs that need it.

go deps.bzl: make sure to add -prune when update-repos

---

enterprise/server/remote_execution/execution_server/execution_server.go

Populate self-hosted usage fields

---

app/invocation/invocation_overview.tsx

getting [object Object] right now

fix tag links

---

server/remote_cache/byte_stream_server/BUILD
server/remote_cache/byte_stream_server/byte_stream_server_test.go
server/testutil/byte_stream/BUILD
server/testutil/byte_stream/byte_stream.go

Move some test code out of byte_stream_server_test for future sharing.

---

deps.bzl
enterprise/server/cmd/executor/BUILD
enterprise/server/remote_execution/containers/ociruntime/BUILD

Add crun to executor image

---

enterprise/server/raft/store/store.go

Create function GetRemoteLastAppliedIndices. This function will also be used in
a seperate PR: we need to wait for the replica to catch up in startup.
Rename getLastAppliedIndex -> getLocalLastAppliedIndex, to clarify that this
function only get the last applied index from the local replica on the store.

[raft] refactor: extract out the functionality of querying remote stores of last applied index

---

codesearch/index/index.go
codesearch/posting/BUILD
codesearch/posting/posting.go
codesearch/posting/posting_test.go

Reverts buildbuddy-io/buildbuddy#7034
Going with a different approach.

Revert "Use postings throughout"

---

docs/workflows-introduction.md

Following up from https://buildbuddy-corp.slack.com/archives/C0777L0C2UW/p1721706669016319?thread_ts=1721691994.752379&cid=C0777L0C2UW

Revamp workflows introduction docs

---

enterprise/server/remote_execution/execution_server/execution_server.go
enterprise/server/test/integration/remote_execution/remote_execution_test.go

This fixes a bug in the hedging implementation where hedged executions would mess with the action-merging state stored in redis. I expanded the hedging test to exercise this bug.

Don't overwrite action-merging state when running hedged executions

---

enterprise/server/raft/store/store.go

[raft] if a range doesn't have bound, mark it as a zombie

---

app/invocation/invocation_action_card.tsx

dont use compact duration format for execution durations

---

server/static/static.go

default code editor v2 to off, oooops

---

enterprise/server/raft/store/store.go
enterprise/server/raft/txn/txn.go

**Related issues**: https://github.com/buildbuddy-io/buildbuddy-internal/issues/3650

[raft] update meta range immediately if we receive an AddRange for meta range

---

enterprise/server/remote_execution/execution_server/execution_server.go
enterprise/server/tasksize/tasksize.go
enterprise/server/tasksize_model/tasksize_model.go
server/static/static.go

Pull cherry-picks into latest release branch

---

cli/install.sh

Fix arch detection in CLI install script

---

enterprise/server/remote_execution/containers/firecracker/firecracker_test.go

The current networking setup is designed to ensure that networking can still work after resuming from snapshot, following this guide: https://github.com/firecracker-microvm/firecracker/blob/main/docs%2Fsnapshotting%2Fnetwork-for-clones.md
This PR adds a dedicated test to make sure we're testing networking after resuming from snapshot.

Add a firecracker test with networking after resuming from snapshot

---

server/util/networking/networking.go
server/util/networking/networking_test.go

Currently our IP setup looks like this (assuming `netIdx` is 0 for this example):
- `veth1` (on host) has addr `192.168.0.5/30` (`hostNet.String()`).
- `veth0` (in namespace) has addr `192.168.0.6/30` (`cloneEndpointNet`)
- The VM TAP device (in namespace) always has a fixed IP - `192.168.241.1`.  We set up NAT within the namespace to translate the VM TAP's IP to `192.168.0.3` (`hostNet.CloneIP()`)
- This part is a little funky, I think. `192.168.0.3` is not a member of the same /30 network that the host and namespaced ends of the veth pair are a part of. So we have to set up an additional routing rule so that the host knows how to route packets back to veth0 in the namespace: `ip route add 192.168.0.3 via 192.168.0.6/30`.
This extra routing rule can be removed if we just configure the …

Simplify routing configuration of veth pair

---

docs/rbe-platforms.md

Fix exec properties link

---

enterprise/server/remote_execution/containers/ociruntime/ociruntime.go

Set rlimits to match podman

---

app/auth/auth_service.ts

Tested locally (by messing with my `/etc/hosts` file to make subdomains work)
**Related issues**: Fixes https://github.com/buildbuddy-io/buildbuddy-internal/issues/3079

Use sessionStorage for impersonation again

---

enterprise/server/remote_execution/containers/ociruntime/ociruntime.go

Mount /etc/resolv.conf in OCI containers

---

enterprise/server/remote_execution/container/container.go
enterprise/server/remote_execution/container/container_test.go
enterprise/server/remote_execution/containers/ociruntime/ociruntime.go
enterprise/server/remote_execution/containers/podman/podman.go

Revert "Fix container stats baseline for recycled runners (#7080)"

---

BUILD
buildbuddy.yaml

Discussed with Iain, and this workflow is ready to be deleted.
**Related issues**: buildbuddy-io/buildbuddy-internal#2282

Remove `Image streaming test` workflow

---

cli/execute/BUILD
cli/execute/execute.go

bb execute: log execution metadata

---

enterprise/server/remote_execution/execution_server/execution_server.go

Fixes an issue that the call to `taskSizer.Update(ctx)` doesn't have the execution_id in the context, making debugging more difficult.

Add execution_id to logging context in PublishOperation

---

enterprise/server/remote_execution/containers/firecracker/firecracker.go
enterprise/server/remote_execution/containers/firecracker/firecracker_test.go
enterprise/server/vmexec/vmexec.go

**Related issues**: Fixes https://github.com/buildbuddy-io/buildbuddy-internal/issues/3664

Fix Firecracker CPU stats

---

server/metrics/metrics.go
server/version/version.go

Add commit SHA to version metric

---

enterprise/server/raft/driver/driver.go

1. fix typo
2. only compute ReplicaByStatus when necessary

[raft] minor fixes in driver

---

tools/metrics/grafana/dashboards/buildbuddy.json

We were showing the aggregated percentile since the pod was up.

Fix some percentile graphs.

---

codesearch/index/index.go
codesearch/token/token.go
codesearch/token/token_test.go

It works -- just still a little slower than I'd like. Gonna fix in a followup.

Make the sparse ngram tokenizer better

---

enterprise/app/tap/flakes.tsx

fix a bit of whitespace in flakes error ui

---

server/build_event_protocol/target_tracker/target_tracker.go
server/build_event_protocol/target_tracker/target_tracker_test.go

Also, set things up so that we _could_ track aspects if we ever wanted to..
Fixes https://github.com/buildbuddy-io/buildbuddy-internal/issues/3603

don't cross up aspect events with primary build events

---

server/build_event_protocol/target_tracker/target_tracker.go

fix var name, auto merge let me down

---

enterprise/server/remote_execution/containers/ociruntime/ociruntime.go
enterprise/server/remote_execution/containers/ociruntime/ociruntime_test.go
server/util/networking/networking.go
server/util/networking/networking_test.go

`ping $(hostname)` should work regardless of whether networking is enabled or not, but currently doesn't. This is at least part of the reason that `remote_execution_test` is failing - the logs show that we're trying (and failing) to dial addresses like `abc123:PORT` where `abc123` is the container name.
This PR does the following:
* When networking is disabled, create a net namespace anyway (with a loopback device) so that we can still reach `$(hostname)`.
* Adds an `/etc/hosts` entry so that the container hostname can be resolved. If networking is disabled, resolve it to the loopback device (127.0.0.1). If networking is enabled, resolve it to the namespaced veth IP. 

Fix OCI container hostname resolution

---

codesearch/token/token.go

Decode runes directly into the interned slice of runes.

Don't waste memory

---

codesearch/cmd/cli/cli.go
codesearch/index/index.go
codesearch/server/server.go
codesearch/token/token.go

- delete dead code
- fix key parsing to handle ngrams that contain the separator character
- stop iterating when we hit another ngram (iterator UpperBound code was wrong)

Make postingList function sparse ngram compatible

---

enterprise/server/raft/config/config.go
enterprise/server/raft/driver/BUILD
enterprise/server/raft/driver/driver.go
enterprise/server/raft/replica/replica_test.go
enterprise/server/raft/store/BUILD
enterprise/server/raft/store/store.go
enterprise/server/raft/store/store_test.go

https://github.com/buildbuddy-io/buildbuddy-internal/issues/3637

[raft] ensure that split and other placement actions don't happen simultaneously

---

enterprise/server/raft/rangelease/rangelease.go

There are warnings of "HaveLease range: 1 valid: false, should have lease: true"
every 10 seconds. It turned out that ensureValidLease in keepLeaseAlive didn't
actually renew the lease. renewLease() always return context cancelled error.

[raft] fix the context when keeping lease alive

---

enterprise/server/raft/replica/replica.go

**Related issues**: https://github.com/buildbuddy-io/buildbuddy-internal/issues/3666
Adding leaseMu to replica to protect rangelease to prevent deadlock.

[raft] fix deadlock

---

app/components/button/button.css
app/target/BUILD
app/target/flaky_target_chip.tsx

fix up loading state for flaky test link

---

app/root/root.css

fix icon margin on flaky target chip on targets tab.

---

tools/kube_foreach/BUILD
tools/kube_foreach/kube_foreach.go

Add kube_foreach tool

---

enterprise/server/remote_execution/containers/podman/podman.go
server/util/networking/networking.go

For reasons I can't understand, IP routing rules seem to affect ARP resolution. If the blackhole IP routing rules are present, podmain containers are unable to resolve the gateway IP address because no ARP reply is ever received.
Addresses https://github.com/buildbuddy-io/buildbuddy-internal/issues/3671

Rework private range blackholing to use iptables.

---

enterprise/app/tap/BUILD
enterprise/app/tap/flakes.tsx
proto/target.proto
server/target/target.go

add average runtime per flake to flakes data

---

deps.bzl

Update `containerd` version in executor image

---

enterprise/server/remote_execution/containers/ociruntime/BUILD
server/util/networking/BUILD

Tag tests as "docker" so that they don't run locally with //... pattern.

---

deps.bzl

Update `podman-static` version in executor image

---

deps.bzl
enterprise/server/cmd/executor/BUILD

Update `soci-snapshotter` version in executor image

---

app/invocation/invocation.css

(maybe there's a better way to do this, if so lmk)

Make font sizes match on cache scorecard page

---

MODULE.bazel

Fix singleflight dep on MODULE.bazel

---

enterprise/server/raft/store/store.go

[raft] remove less useful logs

---

enterprise/server/raft/leasekeeper/leasekeeper.go

**Related issues**: https://github.com/buildbuddy-io/buildbuddy-internal/issues/3666

[raft] only execute the last item in the queue

---

server/util/log/log.go

add a flag so we have the option to not emitting gRPC request log even with log level = debug

---

enterprise/server/scheduling/priority_task_scheduler/BUILD
enterprise/server/scheduling/priority_task_scheduler/priority_task_scheduler.go

Add invocation ID & group IDs to executor logs, if they are available.

---

buildfix.sh
tools/fix_go_deps.sh
tools/update_deps.sh

Add bazel mod tidy to checkstyle + buildfix

---

enterprise/server/raft/bringup/bringup.go
enterprise/server/raft/client/client.go
enterprise/server/raft/client/client_test.go
enterprise/server/raft/config/config.go
enterprise/server/raft/constants/constants.go
enterprise/server/raft/driver/driver.go
enterprise/server/raft/driver/driver_test.go
enterprise/server/raft/leasekeeper/leasekeeper.go
enterprise/server/raft/rangecache/rangecache.go
enterprise/server/raft/rangecache/rangecache_test.go
enterprise/server/raft/rangelease/rangelease.go
enterprise/server/raft/rangelease/rangelease_test.go
enterprise/server/raft/registry/registry.go
enterprise/server/raft/registry/registry_test.go
enterprise/server/raft/replica/replica.go
enterprise/server/raft/store/store.go
enterprise/server/raft/store/store_test.go
enterprise/server/raft/testutil/testutil.go
enterprise/server/raft/txn/txn.go
proto/raft.proto

**Related issues**: https://github.com/buildbuddy-io/buildbuddy-internal/issues/3675
- Replace shard ID with range ID.
- Remove constants.InitialShardID.
- Remove LastShardIDKey
- Simplify code in store.lookupRange

[raft] shard ID -> range ID

---

tools/metrics/grafana/dashboards.bzl
tools/metrics/grafana/dashboards/buildbuddy.json
tools/metrics/grafana/dashboards/raft.json

move raft graphs to a separate dashboard

---

enterprise/server/raft/store/store.go
enterprise/server/raft/usagetracker/BUILD
enterprise/server/raft/usagetracker/usagetracker.go

Report Filesystem usage and partition usage for raft cache

[raft] report partition size and file system size

---

tools/metrics/grafana/dashboards/raft.json

fix raft grafana region variable

---

server/metrics/metrics.go

Thanks @jdhollen for finding this issue - if min <= 0 then this function will loop until it OOMs.

Add guardrails to exponentialBucketRange

---

codesearch/query/BUILD
codesearch/query/regexp.go
codesearch/query/regexp_query.go
codesearch/query/regexp_test.go
codesearch/token/token.go
codesearch/token/token_test.go

Pass tokenizer options into the regex machine, and down to the tokenizer.

Unify options

---

enterprise/server/cmd/ci_runner/main.go
enterprise/server/test/integration/ci_runner/ci_runner_test.go

`buildbuddy.yaml` supports a `bazel_workspace_dir` option for testing repos that contain more than one bazel workspace (e.g. rules_xcodeproj contains multiple workspaces to run various integration tests).
We weren't taking this into account when computing the bazel args used to apply our custom bazelrc, meaning we'd treat the workspace bazelrc with lower precedence than we should have.

Fix .bazelrc logic when bazel_workspace_dir is set

---

enterprise/server/remote_execution/executor/executor.go
server/metrics/metrics.go

Add prometheus histogram for PSI metrics

---

deps.bzl

Fix typo in docker-credential-gcr arm64 target

---

enterprise/app/tap/flakes.tsx
enterprise/app/tap/tap.css

add a little summary of flakes data to the top of the flakes table.

---

rules/go/index.bzl

Stop using some attributes that are going away.

Fix rules/go/index.bzl to account for rules_go changes

---

enterprise/server/remote_execution/dirtools/BUILD
enterprise/server/remote_execution/dirtools/dirtools.go
enterprise/server/remote_execution/workspace/workspace.go

In my tests, it increases performance by more than 5x.

Add some parallelism to file cache linking.

---

codesearch/server/server.go

This will allow indexing private repos as well.

Use auth token

---

enterprise/server/remote_execution/dirtools/dirtools.go

If there are a sufficient number of cache misses, the fetch channel can get full and block new goroutines from being created, preventing the link for loop from ever finishing.

Move the link loop to a goroutine.

---

server/util/networking/networking.go

Reject packets to private IP ranges instead of dropping them.

---

codesearch/server/server.go

This should fix the private repo indexing.

Use github API url to fetch private repos

---

codesearch/cmd/cli/cli.go
codesearch/query/regexp_query.go
codesearch/query/regexp_query_test.go
codesearch/searcher/searcher.go
codesearch/server/server.go
codesearch/types/types.go
proto/search.proto

Support search result pagination via offset param

---

enterprise/server/remote_execution/containers/docker/docker.go
enterprise/server/remote_execution/containers/podman/podman.go

Handle SIGTERM in the same way as SIGKILL

---

enterprise/server/tasksize/tasksize.go
enterprise/server/tasksize/tasksize_test.go

Add configurable limit to computed task milliCPU

---

enterprise/server/content_addressable_storage_server_proxy/BUILD
enterprise/server/content_addressable_storage_server_proxy/content_addressable_storage_server_proxy.go
enterprise/server/content_addressable_storage_server_proxy/content_addressable_storage_server_proxy_test.go

Locally cache unary requests in content_addressable_storage_server_proxy

---

enterprise/server/cmd/ci_runner/main.go

[ci_runner] Don't disable credential helpers when using system git credentials

---

tools/metrics/grafana/dashboards/buildbuddy.json

Add two graphs for tracking action merging performance to the Remote execution collection of graphs.

---

app/components/button/button.css
app/components/input/input.css
app/components/select/select.css

Fix some styling inconsistencies in `TextInput`, `Button`, `OutlinedButton`, and `Select`

Update component styles to be more consistent

---

tools/metrics/grafana/dashboards/buildbuddy.json

Add graph of rate of hedged executions to the action-merging rate graph

---

WORKSPACE.bzlmod

anotha day anotha hash

---

tools/metrics/grafana/dashboards/buildbuddy.json

Add task PSI histogram charts

---

app/root/root.css

Changing from the teal color -> blue color. Think it looks a little nicer
Blue 900 from https://materialui.co/colors

Change pill color for remote bazel

---

tools/dev_qa.py

update dev-qa bb repo commit

---

enterprise/server/cmd/ci_runner/main.go
enterprise/server/workflow/config/BUILD
enterprise/server/workflow/config/config.go
enterprise/server/workflow/service/service.go

Use the new bash steps to simplify this codepath.

[ci_runner] Move custom kythe code out of binary

---

tools/dev_qa.py

Need to upgrade bazel after https://github.com/buildbuddy-io/buildbuddy/pull/7301

upgrade bazel version in dev-qa

---

MODULE.bazel
WORKSPACE
WORKSPACE.bzlmod

Update `protobuf` from 26.0 -> 27.3

---

MODULE.bazel
WORKSPACE
WORKSPACE.bzlmod

Update `abseil` to new lts

---

enterprise/server/remote_execution/containers/ociruntime/ociruntime_test.go

Adds a sanity check to ensure that we correctly set up the container fs so that we can read inputs / outputs.
We test this indirectly in a few other test cases but this just adds some more explicit test logic for it.

OCI runtime: test action inputs/outputs

---

enterprise/server/workflow/config/config.go

And change the url to use a new version I just pushed.
```
tylerw@lunchbox:~/buildbuddy$ gsutil ls -lh gs://buildbuddy-tools/archives/
0 B  2024-05-01T02:05:01Z  gs://buildbuddy-tools/archives/
320.36 MiB  2024-05-01T02:05:50Z  gs://buildbuddy-tools/archives/kythe-v0.0.67.tar.gz
245.53 MiB  2024-08-28T19:20:02Z  gs://buildbuddy-tools/archives/kythe-v0.0.67a.tar.gz
TOTAL: 3 objects, 593376170 bytes (565.89 MiB)
tylerw@lunchbox:~/buildbuddy$
```

Allow switching kythe versions by just changing the URL

---

server/util/bazel_deprecation/bazel_deprecation.go

Make deprecation notices more visible

---

enterprise/tools/replay_action/replay_action.go

- Make log output less noisy and more useful - switch some logs to `debug` level and add `run=i/N` context to all execution logs
- Log stdout+stderr if `--jobs=1`, not just when `--n=1`.
- Bring back `--skip_copy_files` - even though we're using batched FindMissing requests to reduce the amount of work, it can still take a long time to make all the FindMissing requests.

Small improvements to replay_action

---

enterprise/server/hostedrunner/BUILD
enterprise/server/hostedrunner/hostedrunner.go
enterprise/server/hostedrunner/hostedrunner_test.go

**Related issues**: https://buildbuddy-corp.slack.com/archives/C04S4M5U3BK/p1724965618085339?thread_ts=1723069446.908899&cid=C04S4M5U3BK

[RB] Fix normalization of platform properties

---

docs/rbe-platforms.md

Document action timeout props

---

enterprise/server/remote_execution/runner/runner.go

Don't warmup bare/sandbox isolation types

---

server/util/networking/networking.go

Make sure to unlock the IP range _after_ deleting the veth pair, since the IPs in this range are still attached to the veth interfaces when we delete it (we don't have an explicit cleanup func to un-assign the IP that is registered in `attachAddressToVeth`, because deleting the interface does this cleanup automatically).

Fix order of veth interface cleanup

---

enterprise/server/raft/replica/replica.go

add replica name to error message

---

enterprise/server/test/integration/remote_bazel/BUILD
enterprise/server/test/integration/remote_bazel/remote_bazel_test.go

**Related issues**: Fixes https://github.com/buildbuddy-io/buildbuddy-internal/issues/3689#event-13866491179

Fix flaky remote bazel test

---

enterprise/server/byte_stream_server_proxy/BUILD
enterprise/server/byte_stream_server_proxy/byte_stream_server_proxy.go
enterprise/server/content_addressable_storage_server_proxy/BUILD
enterprise/server/content_addressable_storage_server_proxy/content_addressable_storage_server_proxy.go
server/metrics/metrics.go

Add some basic hit/miss metrics to cache proxy servers that do stuff.

---

enterprise/server/raft/driver/driver.go

[raft] lower the priority of split

---

enterprise/server/raft/driver/driver.go

[raft] don't split if there is a node in suspect state

---

server/build_event_protocol/build_event_handler/build_event_handler.go

Move build logs errors to warning level

---

enterprise/server/cmd/ci_runner/main.go

If you want the ci_runner to write to the output that is visible to customers, you must use workspace.log. We frequently confused this with the logger that only writes to the backend executor logs

[ci_runner] Rename the log that writes only to the executor logs to reduce ambiguity

---

enterprise/server/backends/authdb/authdb.go
enterprise/server/backends/userdb/BUILD
enterprise/server/backends/userdb/userdb_test.go
proto/api_key.proto
server/buildbuddy_server/buildbuddy_server.go
server/interfaces/interfaces.go

Allow admins to provision user API keys for other group users

---

enterprise/server/cmd/ci_runner/main.go
enterprise/server/remote_execution/commandutil/commandutil.go

Continue trying to narrow in on a suspicious delay in starting the ci_runner
**Related issues**: https://buildbuddy-corp.slack.com/archives/C019DS52XAR/p1725545996356349?thread_ts=1710341219.838939&cid=C019DS52XAR

[ci_runner] Add more debug logs

---

proto/cache.proto
server/remote_cache/content_addressable_storage_server/BUILD
server/remote_cache/content_addressable_storage_server/content_addressable_storage_server.go
server/remote_cache/content_addressable_storage_server/content_addressable_storage_server_test.go
server/remote_cache/directory_size/directory_size.go

split node_modules dirs into their own child treecaches

---

server/metrics/metrics.go
server/remote_cache/content_addressable_storage_server/content_addressable_storage_server.go

add some very basic metrics for tree splitting

---

enterprise/server/cmd/ci_runner/main.go

Revert "ci_runner: fix insteadOf replacement (#7342)"

---

enterprise/server/raft/usagetracker/usagetracker.go

[raft] add eviction related metrics

---

server/tables/tables.go

Just copying from sqlite sqliteDialect for now.

tables: add missing postgres index

---

server/remote_cache/content_addressable_storage_server/content_addressable_storage_server.go

even more treecache debug logging.

---

enterprise/server/cmd/goinit/main.go
enterprise/server/remote_execution/containers/firecracker/firecracker.go
enterprise/server/remote_execution/containers/firecracker/firecracker_test.go
enterprise/server/remote_execution/containers/ociruntime/ociruntime_test.go

Clean up more cgroup2-related code

---

.bazelrc

Add prober org specific configs

---

cli/ask/ask.go
cli/storage/storage.go

Fix 'bb login' returning an error when using `--allow_existing` and API key is unset

---

server/metrics/metrics.go

Conservatively bumping the multiplier from 5x to 2x since this metric is already relatively high in cardinality.

Add more action stage duration buckets

---

enterprise/server/raft/cache/cache_test.go

This can allow us to pass a fake clock in StartNNodes.

[raft] extract creating test env logic out of startNNode

---

enterprise/server/cmd/ci_runner/main.go
enterprise/server/test/integration/ci_runner/ci_runner_test.go
server/util/redact/redact.go
server/util/redact/redact_test.go

**Related issues**: https://buildbuddy-corp.slack.com/archives/C019DS52XAR/p1725982537416079?thread_ts=1710341219.838939&cid=C019DS52XAR

[ci_runner] Redact all logs

---

docs/rbe-setup.md

To be merged after https://github.com/buildbuddy-io/buildbuddy/pull/7372 goes out

Add docs for remote_execution_priority

---

enterprise/server/cmd/ci_runner/main.go
enterprise/server/test/integration/ci_runner/ci_runner_test.go

[ci_runner] Upload artifacts for bazel commands in bash

---

app/invocation/child_invocations.tsx

**Related issues**: https://buildbuddy-corp.slack.com/archives/C05GBMP463D/p1726066806425789

Rename child invocation section

---

app/invocation/invocation.tsx

Fix async invocation fetch on invocation page

---

app/root/root.css

Fix specificity in flaky target icon styling

---

enterprise/server/atime_updater/BUILD
enterprise/server/atime_updater/atime_updater.go
server/metrics/metrics.go

Cache Proxy: Add a couple of metrics tracking atime_updater performance

---

enterprise/server/cmd/ci_runner/main.go
proto/build_event_stream.proto

[ci_runner] Rename WorkflowCommandCompleted build event to be more generic

---

enterprise/server/backends/pebble_cache/pebble_cache.go

bump JanitorCutoffThreshold back to .9

---

codesearch/searcher/BUILD
codesearch/searcher/searcher_test.go
codesearch/types/types.go

Gonna change the truncate method -- wanted to add a test first.

Add a simple searcher test

---

server/xcode/BUILD
server/xcode/xcode_darwin.go

Use flag.Slice for --executor.required_xcode_versions

---

enterprise/server/backends/pebble_cache/pebble_cache_test.go
server/remote_cache/byte_stream_server/byte_stream_server_test.go
server/testutil/testdigest/testdigest.go

fix testdigest's random seed

---

server/util/networking/networking.go

Add executor flag to restrict nat source ports.

---

codesearch/index/BUILD
codesearch/index/index.go
codesearch/index/index_test.go
codesearch/types/BUILD
codesearch/types/types.go

(it will come back as an external unique field in a followup)

Remove internal DocID completely

---

.github/workflows/test-executor-linux-arm64.yaml

context: https://buildbuddy-corp.slack.com/archives/C01D5GHRJ59/p1726523041819279

Add auth to arm64/linux build

---

tools/dev_qa.py

Update sha in dev_qa.py too (whoops)

---

server/testutil/webtester/webtester.go

possibly fix flaky remote webdriver test.

---

server/remote_asset/fetch_server/fetch_server.go
server/remote_asset/fetch_server/fetch_server_test.go

This allows Bazel to propagate credentials from netrc or cred helpers
to fetch external dependencies from BuildBuddy.

fetch_server: support uri-specific header qualifier

---

enterprise/server/backends/pebble_cache/pebble_cache.go

forget to remove this in https://github.com/buildbuddy-io/buildbuddy/pull/7407

one more access in partitionEvictor

---

enterprise/server/raft/store/store.go

Fixes: https://github.com/buildbuddy-io/buildbuddy-internal/issues/3765

Attempt to stop replicas we can't delete

---

enterprise/server/raft/replica/BUILD
enterprise/server/raft/replica/replica.go

remove Sender() in replica

---

enterprise/server/raft/replica/replica.go
server/metrics/metrics.go

Add metrics to monitor replica.Update.
Remove unused raft eviction metrics

[raft] replica.Update metrics

---

enterprise/server/raft/client/client.go

[raft] correctly identify request rejected err

---

enterprise/server/raft/driver/BUILD
enterprise/server/raft/driver/driver.go
enterprise/server/raft/store/store.go
server/metrics/metrics.go

[raft] add some metrics to monitor splits

---

enterprise/server/raft/usagetracker/usagetracker.go

[raft] fix panic

---

enterprise/server/raft/store/store.go

otherwise we will try to auto bring up all the time.

[raft] increment configuredClusters on startup

---

cli/upload/upload.go
enterprise/server/remote_execution/snaputil/BUILD
enterprise/server/remote_execution/snaputil/snaputil.go
enterprise/tools/replay_action/replay_action.go
enterprise/tools/upload_local_snapshot/upload_local_snapshot.go
server/buildbuddy_server/buildbuddy_server_test.go
server/cache_proxy/cache_proxy.go
server/metrics/metrics.go
server/remote_asset/fetch_server/fetch_server.go
server/remote_cache/byte_stream_server/byte_stream_server_test.go
server/remote_cache/cachetools/cachetools.go
tools/cacheload/cacheload.go

track uploaded snapshot bytes.

---

enterprise/server/raft/store/store.go
enterprise/server/raft/store/store_test.go
enterprise/server/raft/testutil/testutil.go

[raft] add a test for ConfiguredClusters in the store

---

enterprise/server/raft/usagetracker/usagetracker.go

[raft] fix eviction metrics

---

enterprise/server/raft/driver/driver.go

[raft] track split errors in metrics for real

---

enterprise/server/raft/store/store.go

We need to start to listen to meta range before we query for active replicas.
Otherwise the query will fail because RangeCache cannot find meta range.

[raft] move queryMetaRange before initializing replica

---

tools/metrics/grafana/dashboards/raft.json

[raft] add system up/ready graph

---

enterprise/server/raft/constants/constants.go
enterprise/server/raft/usagetracker/usagetracker.go

[raft] move cache name to constants

---

enterprise/server/tasksize/tasksize.go
tools/metrics/grafana/dashboards/buildbuddy.json
tools/metrics/grafana/dashboards/raft.json

Revert "Enable task sizer for Firecracker CPU (#7487)"

---

tools/metrics/grafana/dashboards/buildbuddy.json
tools/metrics/grafana/dashboards/raft.json

Revert accidental dashboard changes

---

tools/metrics/grafana/dashboards/buildbuddy.json

Has just a few metrics to show how much data we're shipping around, as well as storage size. We could add more metrics later as needed.

Add a basic VictoriaMetrics monitoring dashboard

---

enterprise/server/raft/store/store.go

[raft] collect pebble metrics in raft

---

tools/metrics/grafana/dashboards/buildbuddy.json
tools/metrics/grafana/dashboards/mac.json

Auto-generate grafana graphs for cache-proxy as well as app & executor

---

MODULE.bazel
WORKSPACE

This helps slim down our bzlmod config a little bit.

Upgrade protobuf to 28.2

---

WORKSPACE
WORKSPACE.bzlmod

WORKSPACE: remove unused rules_foreign_cc

---

tools/metrics/grafana/dashboards/raft.json

[raft] fix instances graph

---

enterprise/server/raft/store/store.go
enterprise/server/raft/usagetracker/usagetracker.go

[raft] don't start eviction when we are still initializing replicas

---

tools/fix_go_deps.sh

**Related issues**: Fixes https://github.com/buildbuddy-io/buildbuddy-internal/issues/3854

Fix dev checkstyle workflow

---

enterprise/server/raft/store/store.go
enterprise/server/raft/testutil/testutil.go

[raft] fix metricsCollector in raft

---

enterprise/server/raft/store/store.go

[raft] add replica init progress logs during startup

---

enterprise/server/remote_execution/execution_server/execution_server.go

We have a few places where Action.command_digest is apparently nil. Add the execution ID to ctx sooner in one of these cases to help debug further (the execution ID has the action_digest, so we'll be able to see whether the command_digest was actually nil, or if we have some bug).

Add execution ID to ctx sooner

---

enterprise/server/raft/store/store.go

[raft] increase the num of go routines waiting for init status

---

enterprise/server/remote_execution/containers/firecracker/firecracker.go

Cap firecracker CPUs at firecracker limit.

---

enterprise/server/raft/leasekeeper/leasekeeper.go

Right now we can block the leader updates when we cannot keep up with the lease
instructions. Since we only need the last update, we can drop all previous
instructions.

[raft] only buffer one update per lease agent

---

enterprise/server/raft/store/store.go

nodehost.GetNodeHostInfo will lock the nodehost.

don't call IsLeader in checkIfReplicaCaughtUp

---

.github/workflows/pr.yaml

Set API key in pr.yaml Bazel commands

---

enterprise/server/workflow/config/config.go

- Fix bash quotes
- Export a serving SSTable that can be ingested directly by the kythe server

Export a kythe serving sstable

---

enterprise/server/raft/listener/listener.go
enterprise/server/raft/store/store.go

**Related issues**: https://github.com/buildbuddy-io/buildbuddy-internal/issues/3871

[raft] Use NodeReady callback to determine whether a replica is ready

---

enterprise/server/raft/store/store.go

[raft] start replica in parallel

---

enterprise/server/raft/config/config.go

**Related issues**: https://github.com/buildbuddy-io/buildbuddy-internal/issues/3870

[raft] enable SnapshotCompression and EntryCompression

---

enterprise/server/raft/driver/driver.go
enterprise/server/raft/store/store_test.go

[raft] increase the number of replicas for meta range

---

tools/metrics/grafana/dashboards/buildbuddy.json

Cache Proxy: put graphs back in the correct row.

---

enterprise/server/raft/store/BUILD
enterprise/server/raft/store/store.go
enterprise/server/raft/store/store_test.go
proto/raft.proto

**Related issues**: https://github.com/buildbuddy-io/buildbuddy-internal/issues/3869

[raft] delete data from pebble in RemoveData

---

enterprise/server/remote_execution/containers/ociruntime/ociruntime.go

Avoid handling gzip decompression via `tar` command.
Replace it with `layer.Uncompressed()` from go-containerregistry which
supports both gzip and zstd format.

ociruntime: decompress using go-containerregistry

---

server/build_event_protocol/build_event_server/build_event_server.go

When in `synchronous` mode (e.g. when `CI=true`) we should not throw away the `PublishBuildToolEventStream` error, and instead surface it to the client.

cli: surface BES forwarding RPC errors when in synchronous mode

---

enterprise/server/cmd/cache_proxy/cache_proxy.go

Cache Proxy: configure tracing during server startup.

---

enterprise/server/raft/driver/driver.go

[raft] fix bug for up replicate

---

tools/metrics/grafana/dashboards/raft.json

[raft] add some pebble compaction/level graphs

---

enterprise/server/byte_stream_server_proxy/BUILD
enterprise/server/byte_stream_server_proxy/byte_stream_server_proxy.go
enterprise/server/content_addressable_storage_server_proxy/BUILD
enterprise/server/content_addressable_storage_server_proxy/content_addressable_storage_server_proxy.go
enterprise/server/remoteauth/BUILD
enterprise/server/remoteauth/remoteauth.go

Cache Proxy: add trace spans to gRPC server entrypoints

---

enterprise/server/raft/client/BUILD
enterprise/server/raft/client/client.go
enterprise/server/raft/sender/BUILD
enterprise/server/raft/sender/sender.go

[raft] add some tracing span

---

enterprise/server/raft/client/client.go

[raft] more detailed span in SyncProposeLocal

---

tools/metrics/grafana/dashboards/raft.json

[raft] adjust partition size graph

---

enterprise/server/action_cache_server_proxy/BUILD
enterprise/server/action_cache_server_proxy/action_cache_server_proxy.go

Cache Proxy: remove unused localCache from ActionCacheProxyServer

---

enterprise/server/workflow/config/config.go

- Use remoteex and shrink kythe workflow image temporarily
- BF

small with remotex

---

MODULE.bazel
WORKSPACE
WORKSPACE.bzlmod
codesearch/cmd/server/BUILD
deployment/BUILD
enterprise/server/cmd/cache_proxy/BUILD
enterprise/server/cmd/server/BUILD
enterprise/tools/rbeperf/BUILD
tools/cacheload/BUILD
tools/probers/BUILD
tools/smarter_device_manager/BUILD
tools/tcpproxy/BUILD

This reverts commit 5430f7ae0e637548449ee9234f66522edfd9a26a.
Break current release flow.

Revert "Add rules_oci (#7568)"

---

enterprise/server/workflow/config/config.go

This reverts commit 0367c820dd980fb273919cf349672be85671ccbb.

Revert "small with remotex (#7600)"

---

enterprise/server/raft/usagetracker/usagetracker.go

[raft] log global size update

---

enterprise/server/raft/config/config.go

[raft] try a smaller compaction overhead

---

enterprise/server/raft/store/store.go

[raft] add some logs for debugging shutdown

---

enterprise/server/raft/leasekeeper/BUILD
enterprise/server/raft/leasekeeper/leasekeeper.go
enterprise/server/raft/nodeliveness/BUILD
enterprise/server/raft/nodeliveness/nodeliveness.go
enterprise/server/raft/store/store.go

Also remove some debug logs
https://github.com/buildbuddy-io/buildbuddy-internal/issues/3910

[raft] wait until lease agent, lease keeper, liveness stopped fully

---

enterprise/server/raft/usagetracker/usagetracker.go

also don't prune old data. stale data is better than no data.

[raft] fix idle timer: we are not sending forced node partition usage

---

enterprise/server/raft/usagetracker/usagetracker.go

With previous formula, after each eviction, each node's partition usage is
decreased by ~5 * sample.sizeBytes. This causes the eviction to stop
prematurely.
In approxlru, globalSize becomes (globalSize - sample.Sizebytes* globalSize/localSize). I changed the calculation so that when each node's partition usage is summed, it's aligned with the formula in approxlru.

[raft] change how we speculate other stores' usage

---

enterprise/server/raft/usagetracker/usagetracker.go

https://github.com/buildbuddy-io/buildbuddy-internal/issues/3747

[raft] reset idleTimer

---

server/http/csp/csp.go

Avoids potential log spam in prod.

server: Demote CSP logs to debug level

---

enterprise/app/filter/date_picker_button.tsx

fix date range rendering that got missed in merge/rebase

---

server/http/interceptors/interceptors.go

server: Allow Monaco's font loading in the CSP

---

enterprise/server/api/api_server.go
proto/api/v1/BUILD
proto/api/v1/remote_runner.proto
proto/api/v1/service.proto
server/capabilities_filter/capabilities_filter.go

[RB] Add public API

---

enterprise/server/raft/config/config.go

decrease snapshot entries

---

cli/remotebazel/remotebazel.go

[RB] Support running from a specific GitHub ref if you want to disable local git sync

---

enterprise/server/test/integration/remote_execution/remote_execution_test.go

In the previous version, it was possible for the 2 slow executions to be accepted and in the executing state, but not actually check for the existence of fname before the unlock command ran.
Now, there is synchronization between the scripts, so unlock will only run after the first 2 executions checked for the existence of fname.

Remove flakiness in remote_execution_test.TestActionMerging_Hedging

---

server/build_event_protocol/build_event_handler/build_event_handler.go

Rename invocationJWT to invocationInfo

---

proto/api_key.proto
proto/bazel_config.proto

Related: https://github.com/buildbuddy-io/buildbuddy-internal/issues/3907

Proto changes to return certs as part of ApiKey APIs

---

docs/enterprise-api.md
docs/remote-bazel-introduction.md
website/sidebars.js

Add Remote Bazel docs

---

enterprise/server/raft/replica/replica.go
enterprise/server/raft/txn/txn.go

[raft] add more logs for txn

---

server/buildbuddy_server/buildbuddy_server.go

Depends on proto changes in https://github.com/buildbuddy-io/buildbuddy/pull/7622/files
Related issues: https://github.com/buildbuddy-io/buildbuddy-internal/issues/3907

Populate cert if requested in GetApiKey

---

server/http/interceptors/interceptors.go
server/static/static.go

server: Gate CSP behind `--app.strict_csp_enabled`

---

enterprise/server/raft/store/store_test.go

[raft] de-flake TestAddNodeToCluster

---

enterprise/server/raft/nodeliveness/nodeliveness.go

[raft] fix a data-race

---

enterprise/app/history/history.tsx
enterprise/app/trends/drilldown_page.tsx
enterprise/app/trends/trends.tsx
enterprise/app/trends/trends_requests.ts
enterprise/server/execution_search_service/BUILD
enterprise/server/execution_search_service/execution_search_service.go
enterprise/server/invocation_stat_service/invocation_stat_service.go
proto/execution_stats.proto
proto/invocation.proto
proto/stats.proto

add missing dimension filters to stats request on the client side, too.  oops.

use generic filters on all requests that should reasonably support them.

---

proto/invocation.proto
server/build_event_protocol/event_parser/event_parser.go

**Related issues**: I realized I missed some references in this cleanup PR https://github.com/buildbuddy-io/buildbuddy/pull/7389

Clean up some leftover references to parent invocation ID

---

docs/remote-bazel-introduction.md

**Related issues**: Changes from PR https://github.com/buildbuddy-io/buildbuddy/pull/7659/files

[RB] Add docs to run from specific GH ref

---

server/http/interceptors/interceptors.go

Also add more domains for Google Analytics.

server: Allow connections to region servers in the CSP

---

enterprise/server/raft/usagetracker/usagetracker.go

[raft] remove debug log

---

enterprise/server/remote_execution/execution_server/execution_server.go

When execution is completed, we used to call operation.ExtractExecuteResponse 3 times. Now it's called once.
Maybe this has some performance benefit, but I mostly made the change because I found it confusing that we are unpacking 3 times.

Remove some AnyPB unwrapping in ExecutionServer.PublishOperation

---

enterprise/server/raft/driver/driver.go
enterprise/server/raft/store/store.go
server/metrics/metrics.go

[raft] track range move success/failure in metrics

---

docs/remote-bazel-introduction.md

Make some minor Remote Bazel doc edits

---

server/config/config.go
server/config/config_test.go

Expand flag secrets even if no config file is loaded.

---

tools/metrics/grafana/dashboards/raft.json

1. for Raft moves, group by move_type and status
2. simplify the legends

[raft] Grafana changes

---

enterprise/app/filter/filter.tsx

restore apply button in filters menu, yikes

---

enterprise/server/raft/client/BUILD
enterprise/server/raft/client/client.go

[raft] add range_id to locker.Lock span

---

dockerfiles/rbe-ubuntu20-04/Dockerfile

Java compilation actions unconditionally use this locale.

docker: Install en_US.UTF-8 locale in rbe-ubuntu20-04

---

enterprise/server/remote_execution/dirtools/dirtools.go
server/remote_cache/digest/digest.go

Fix a panic when res.Digest is nil

Fix panic in debug logging

---

enterprise/server/raft/store/store.go

[raft] have a seperate session for txn

---

enterprise/server/raft/store/store.go

[raft] use seperate sessions for eviction and startShard

---

codesearch/server/server.go

Reference shared field names from schema

---

codesearch/server/server.go
enterprise/server/backends/codesearch/codesearch.go
proto/codesearch_service.proto
proto/index.proto
server/build_event_protocol/build_event_handler/build_event_handler.go
server/interfaces/interfaces.go

s/IngestKytheTable/IngestAnnotations/g

Correct a poorly named RPC

---

enterprise/server/remote_execution/containers/firecracker/firecracker.go
enterprise/server/remote_execution/containers/firecracker/firecracker_test.go
enterprise/server/remote_execution/snaploader/snaploader.go
enterprise/server/remote_execution/snaploader/snaploader_test.go
proto/firecracker.proto

**Related issues**: Fixes https://buildbuddy.slack.com/archives/CUY16GNK1/p1728328827179879?thread_ts=1726242879.319709&cid=CUY16GNK1

[CI] Add better snapshot fallback behavior for merge queues

---

enterprise/server/raft/store/store.go

GetNodeHostInfo will lock on raft side.

[raft] use GetLeaderID to determine if a range is leader or not

---

enterprise/server/raft/events/events.go
enterprise/server/raft/leasekeeper/leasekeeper.go
enterprise/server/raft/store/store.go

[raft] stop standing range events, we are not using them

---

enterprise/server/raft/events/events.go
enterprise/server/raft/leasekeeper/leasekeeper.go
enterprise/server/raft/rangelease/rangelease.go
enterprise/server/raft/store/store.go

[raft] set the deadline after the lock

---

server/util/networking/networking.go

Fix pooled network cleanup

---

cli/remotebazel/remotebazel.go

Slack: https://buildbuddy-corp.slack.com/archives/C07GMM2VBLY/p1729518562819779?thread_ts=1729512952.020239&cid=C07GMM2VBLY

[RB] Fix incorrect error exit code

---

enterprise/server/remote_execution/filecache/filecache.go

The filecache has a `_tmp` dir which we should not scan, and we are also considering moving OCI + firecracker images to this cache directory, to prevent `executor.delete_build_root_on_startup` from wiping cached images.

filecache: restrict initial scan to group-specific dirs

---

MODULE.bazel
deps.bzl
server/util/bazelisk/BUILD

Context: https://buildbuddy-corp.slack.com/archives/C075SCSB2BE/p1729550163140139?thread_ts=1729547224.837649&cid=C075SCSB2BE

Fix bazelisk binary bundled with arm64 ci_runner

---

enterprise/tools/replay_action/replay_action.go

When replaying multiple actions, it's useful to be able to look at the Execute response in a structured way, e.g. processing the ExecuteResponse as JSON with `jq` to look at failure rates / usage stats etc.
This PR writes the artifacts associated with each execution to its own directory. The directory is structured like this:
```
- {outDir}/
- {actionDigestHash}/
- {attemptNumber}/ # numbered 1..n, where n is the `-n` flag value
- stdout
- stderr
- execute_response.json
```

Write replay_action results to disk for easier analysis

---

app/invocation/invocation_spawn_card.tsx

Updated invocation_spawn_card.tsx

Fixed spelling of "Mnemonic" in the dropdown menu of the spawns tab

---

server/build_event_protocol/event_index/event_index.go

I noticed we were seeing duplicate build events for a given label, and realized that one of them had an `Aspect` ID (For example, you can see in this [invocation](https://buildbuddy.buildbuddy.io/invocation/1bd24aa9-0d79-47bc-8366-4347cae84ece#artifacts) we render the build artifact twice). I believe the aspect, named "ValidateTarget" is run because we set `--experimental_use_validation_aspect=true`

Handle duplicate aspect-related build events in the event index

---

enterprise/server/atime_updater/atime_updater.go
enterprise/server/atime_updater/atime_updater_test.go

The current atime-update behavior is that it keeps a queue of atime-updates to deliever per group ID, with one update per instance-name & digest function. If a single update exceeds `cache_proxy.remote_atime_max_digests_per_update` digests, additional digests are ignored until the update is flushed. In practice, this doesn't work too well because there's one really large pending update and a lot of digests dropped from that update. This change makes it so that an individual update can grow larger than `cache_proxy.remote_atime_max_digests_per_update` but introduces a second cap, `cache_proxy.remote_atime_max_digests_per_group` limiting the total number of digests-to-update per group. This change also moves the batching of digests into requests to dequeue time instead of doing it at …

[Cache Proxy] Let the atime updater accumulate more than 10,000 queued digests-to-update per instance-name / digest function

---

enterprise/server/raft/store/store.go

https://github.com/buildbuddy-io/buildbuddy-internal/issues/3982

let all stores instead of just leader report range size

---

enterprise/server/test/integration/ci_runner/ci_runner_test.go

Per https://patchwork.kernel.org/project/git/patch/20181217221625.1523-1-avarab@gmail.com/#22387021, newer versions of `git` no longer support the (previously default) behavior of refusing to fetch non-HEAD refs. Thus, we cannot rely on that behavior in our tests as they will fail on newer distros (e. g. debian13, ununtu22).

Update `ci_runner_test` to work with newer versions of `git`

---

enterprise/server/raft/cache/cache.go

http://github.com/buildbuddy-io/buildbuddy-internal/issues/3982

[raft] add a flag to delete cache data from previous run

---

docs/config-rbe.md
server/resources/BUILD
server/resources/resources.go
server/resources/resources_test.go
server/testutil/testenviron/BUILD
server/testutil/testenviron/testenviron.go

Fixes https://github.com/buildbuddy-io/buildbuddy-internal/issues/4063

Add SYS_CPU env var to supersede SYS_MILLICPU

---

server/http/csp/csp.go

Auto-merge got in the way of removing them in https://github.com/buildbuddy-io/buildbuddy/pull/7845.

server: Remove redundant conditions

---

docs/enterprise-api.md
enterprise/server/api/BUILD
enterprise/server/api/api_server.go
proto/api/v1/invocation.proto

https://buildbuddy-corp.slack.com/archives/C04S4M5U3BK/p1730321133924089?thread_ts=1730318886.632589&cid=C04S4M5U3BK

Set bazel exit code for disconnected invocations in GetInvocation

---

enterprise/server/remote_execution/containers/firecracker/firecracker.go

https://github.com/buildbuddy-io/buildbuddy-internal/issues/4087

Randomize jailer NUMA node setting

---

enterprise/server/remote_execution/vbd/vbd.go

Even after this [change](https://github.com/buildbuddy-io/buildbuddy/pull/7780), we are still seeing error logs "Failed to unmount VBD: context canceled". However the [unmount happens in a goroutine, and continues even if the context is canceled.](https://github.com/buildbuddy-io/buildbuddy/blob/master/enterprise/server/remote_execution/vbd/vbd.go#L132)
Add some more logging so we can see if we are eventually unmounting these VBDs, or if there is a goroutine leak and something is permanently blocking them from being unmounted. In prod, where most of these errors occur, we only have info-level logging. In the more limited cases I saw in dev, there were debug logs that the VBD was eventually getting unmounted. So I don't think this is an actual problem, but the logging should make it more …

[FC] Add more logging to tell if VBD was unmounted in the background

---

proto/stat_filter.proto
server/util/filter/filter_test.go

add "string contains" filter

---

enterprise/server/raft/replica/replica.go
enterprise/server/raft/store/store.go
enterprise/server/raft/store/store_test.go

https://github.com/buildbuddy-io/buildbuddy-internal/issues/4100

[raft] when remove data also remove local range

---

tools/dev_qa.py

Needs to match https://github.com/buildbuddy-io/buildbuddy-internal/pull/4115/files

Use the same commit as internal

---

enterprise/server/raft/store/store.go

https://github.com/buildbuddy-io/buildbuddy-internal/issues/4077

[raft] Check membership when adding replica

---

docs/rbe-platforms.md

I think this was the intended meaning of the docs.

Clarify docs for execution properties

---

enterprise/server/raft/store/store.go
enterprise/server/raft/store/store_test.go

1. AddReplica can fail to promote to voter in some rare cases with request
rejected. When one attempt of `SyncRequestAddReplica` went through in raft
system, but raft returned a temp "system is busy" error; the next attempt will
fail with "request rejected". Therefore, when we receive request rejected error,
instead of returning error directly, we can check the membership to see if the
replica has been promoted to voter.
2. getMembership in DownReplicate can fail with shard not found between getting 
the store with range lease and getting the membership, the replica was removed.
In this case, the test should try again to find another store with range lease
and see the number of replicas on that store.
3. In DownReplicate, sometimes when we check the pebble to see if the keys are
deleted, …

[raft] fix flaky tests

---

.bazelrc
MODULE.bazel
WORKSPACE
WORKSPACE.bzlmod
docs/rbe-github-actions.md
docs/rbe-setup.md
toolchains/BUILD
tsconfig.json
website/docusaurus.config.js

- **update some toolchain and platform stuff**
- **add necessary rootDirs for new platform names**

Update to new `buildbuddy-toolchain`

---

enterprise/server/remote_execution/cgroup/BUILD
enterprise/server/remote_execution/cgroup/cgroup.go
enterprise/server/remote_execution/cgroup/cgroup_test.go
server/util/proto/proto.go

The plan is to use this function to configure the cgroups for firecracker+ociruntime.

Add function to apply cgroup settings

---

enterprise/server/remote_execution/containers/firecracker/BUILD
enterprise/server/remote_execution/containers/firecracker/containeropts.go

Clean up unused firecracker docker client opt

---

enterprise/server/remote_execution/filecache/filecache.go
enterprise/server/remote_execution/filecache/filecache_test.go

Reverts buildbuddy-io/buildbuddy#7906

Revert "Prefix filecache digest paths with first 4 of digest"

---

enterprise/server/cmd/executor/BUILD
enterprise/server/cmd/executor/executor.go
enterprise/server/cmd/executor/executor_linux.go
enterprise/server/cmd/executor/executor_notlinux.go
enterprise/server/remote_execution/cgroup/cgroup.go
enterprise/server/remote_execution/runner/runner.go

Fixes https://github.com/buildbuddy-io/buildbuddy-internal/issues/4140

Ensure action cgroups are placed under the k8s container cgroup

---

enterprise/server/raft/replica/replica.go
enterprise/server/raft/replica/replica_test.go

https://github.com/buildbuddy-io/buildbuddy-internal/issues/4142
Added a unit test to replicate the bug.

[raft] delete data before apply snapshot

---

enterprise/server/raft/replica/replica.go
enterprise/server/raft/replica/replica_test.go
proto/raft.proto

Add entry index in session proto to aid debugging.
Also add a error log if lastAppliedIndex going backward.

[raft] add entry index in session proto

---

tools/metrics/grafana/dashboards/raft.json

To make the cpu graph easier to read.

[raft] add a node <> pod mapping table on raft grafana

---

proto/BUILD
proto/bazel_query.proto
proto/build_event_stream.proto
proto/failure_details.proto
proto/stardoc_output.proto

Update protos according to the latest files from Bazel.git.

protos: update Bazel's protos

---

enterprise/server/backends/userdb/userdb.go

Under certain conditions, we could be adding users to the default group
twice and got this error as the result:
```
Error 1062 (23000): Duplicate entry 'US16246136860140428328-GR0000000000000000000' for key 'UserGroups.PRIMARY'
```
Ensure that all ids in groupids is unique by using a map instead of a
slice.

userdb: deduplicate groupids when create user

---

server/cache/dirtools/dirtools.go

Pipe the operations through a global queue with a fixed number of workers.

Limit total input tree setup parallelism across all actions.

---

cli/remotebazel/BUILD
cli/remotebazel/remotebazel.go
docs/remote-bazel-introduction.md
enterprise/server/test/integration/remote_bazel/remote_bazel_test.go
server/util/shlex/BUILD
server/util/shlex/shlex.go
server/util/shlex/shlex_test.go

Based off @bduffany 's PR https://github.com/buildbuddy-io/buildbuddy/pull/7766
Properly quote commands to prevent shell parsing errors (or abuses)

[RB] Improve shell token handling

---

enterprise/server/remote_execution/executor/executor.go
enterprise/server/test/integration/remote_execution/remote_execution_test.go

Actions can't access files outside of their workspaces (due to isolation) but ban `".."` in output paths as an additional safeguard.
This is a pre-requisite for https://github.com/buildbuddy-io/buildbuddy/pull/7959 which is adding some code that doesn't guard against these types of paths, but probably shouldn't be responsible for doing so.

Add additional safeguard against parent paths

---

cli/remotebazel/remotebazel.go
cli/remotebazel/remotebazel_test.go

Our usage of go-git in the remote bazel CLI doesn't handle a series of edge cases and has resulted in some performance problems
To make these changes easier to review, I'll refactor out go-git in a series of PRs
This PR also adds some debug logging to the CLI for how long each git command takes, as customers often wonder where time is spent by the CLI
Related issues:
https://github.com/buildbuddy-io/buildbuddy/issues/7896
https://github.com/buildbuddy-io/buildbuddy-internal/issues/3717
https://github.com/buildbuddy-io/buildbuddy-internal/issues/1682
https://buildbuddy-corp.slack.com/archives/C04S4M5U3BK/p1731617106465189

[RB] Refactor CLI to not use go-git when determining the remote

---

enterprise/server/remote_execution/execution_server/execution_server.go
enterprise/server/remote_execution/execution_server/execution_server_test.go
enterprise/server/remote_execution/operation/operation.go

This is more flexible and I need it for me next change.

Expose the internal version of operation.Assemble

---

docs/remote-bazel-introduction.md
enterprise/server/remote_execution/platform/platform.go

https://buildbuddy-corp.slack.com/archives/C0495TM9UUE/p1730709914819379

Improve documentation and error message for custom docker images

---

proto/scheduler.proto

I forgot to commit my clarification before merging.

Finish doc of ScheduledTask.serialized_task

---

cli/execute/execute.go

Allow writing the `ExecuteResponse` to a path specified by `-response_json_file`. This makes it possible to access metadata, outputs, etc.

bb execute: add response JSON file flag

---

enterprise/server/remote_execution/containers/ociruntime/ociruntime.go

This reverts commit 559a71d64e5610d443b4d8f60b709e760f9c8cfb.

Revert "ociruntime: replace tar extraction subprocess with in-process (#7589)"

---

app/trace/trace_events.ts
enterprise/server/execution_service/execution_service.go
enterprise/server/remote_execution/container/container.go

Screenshot from an action that generates a 5GB file using `head -c 5000000000 /dev/zero > /tmp/zeros.bin`, then creates a copy of it with `cp /tmp/zeros.bin /tmp/zeros_copy.bin`

Add disk IO usage timelines

---

enterprise/server/backends/authdb/authdb.go
enterprise/server/backends/userdb/userdb_test.go

In a few different places, we call `GetAPIKeyForInternalUseOnly` to retrieve an "arbitrary" API key for a group. However, some things break if the arbitrary key happens to be a readonly key.
This PR makes it so that we retrieve the key with the highest cache capabilities.
I opted to do ranking instead of filtering, because it seems less risky. e.g. if an org only has CAS-write or readonly keys, we don't want to break those orgs.

Prefer keys with cache write caps

---

enterprise/server/raft/store/store.go
proto/raft.proto
proto/raft_service.proto

https://github.com/buildbuddy-io/buildbuddy-internal/issues/4214

[raft] add a debug endpoint

---

server/cache/dirtools/dirtools.go

I forgot to remove this in https://github.com/buildbuddy-io/buildbuddy/pull/7799

Remove unused field from dirtools.UploadTree

---

enterprise/server/raft/store/store.go

https://github.com/buildbuddy-io/buildbuddy-internal/issues/4211

[raft] SyncRequestDeleteReplica should not ignore ErrShardClosed

---

enterprise/server/raft/client/client.go
enterprise/server/raft/replica/replica.go

Add some logging for debugging

[raft] log session

---

enterprise/server/raft/store/store.go
enterprise/server/raft/store/store_test.go

https://github.com/buildbuddy-io/buildbuddy-internal/issues/4220

[raft] when removing zombie, try different replicas to remove the replica

---

enterprise/server/remote_execution/execution_server/execution_server.go

I missed this in https://github.com/buildbuddy-io/buildbuddy/pull/7661

Prefer action.platform over command.platform in one more place

---

tools/metrics/grafana/dashboards/buildbuddy.json

Add a few metrics from this guide: https://docs.victoriametrics.com/guides/understand-your-setup-size/#terminology
- Active timeseries
- Churn rate (new timeseries creation rate)
- Ingestion rate (rows inserted per second)
See the last 3 panels in this screenshot:

Add more vmstorage metrics

---

website/src/components/rbe/rbe.tsx
website/src/pages/team.tsx

Fix teams page alignment & tweak compute minutes wording

Website tweaks

---

enterprise/server/remote_execution/cgroup/cgroup.go
enterprise/server/remote_execution/containers/firecracker/firecracker.go

Get all Firecracker stats from the cgroup on the host, except for the filesystem usage stats which come from the filesystem mounted in the guest. This makes the usage timelines work for Firecracker, and also lets us get pressure stall metrics for Firecracker.

Get firecracker stats from host cgroup

---

app/invocation/invocation_action_card.tsx

In #8051 we added an extra execution request which races with another request, which gets canceled. This PR reorders some logic to avoid concurrent requests. We'll now call `WaitExecution` to live-stream the execution only if we first try and fail to fetch the cached `ExecuteResponse`.

Fix error banner on action page

---

docs/rbe-platforms.md
enterprise/server/remote_execution/containers/firecracker/firecracker_test.go
enterprise/server/remote_execution/platform/platform.go
enterprise/server/remote_execution/runner/runner.go
enterprise/server/remote_execution/workspace/workspace.go
enterprise/server/test/integration/remote_execution/remote_execution_test.go
server/cache/dirtools/dirtools.go

Context: https://github.com/buildbuddy-io/buildbuddy-toolchain/pull/40
Discussion in https://buildbuddy-corp.slack.com/archives/C0694U6QC30/p1734718629659079

Remove nonroot-workspace property

---

enterprise/server/raft/driver/driver.go
enterprise/server/raft/driver/driver_test.go
enterprise/server/raft/store/store.go

also do not add a replica onto a node where a removal is taking in
place.

[raft] do not split if there is a replica in the middle of removal

---

enterprise/server/raft/store/store.go

When AddReplica fails before the replica descriptor is added to the range
descriptor, RemoveReplica won't mark this replica for removal since it was not
on the range descriptor in the first place. 
In this case, we still want to remove the data from raft, but we don't need to
remove the data from pebble, there is no raft command in StartShard.

[raft] in RemoveData, treat replica not marked for removal as a valid case

---

tools/dev_qa.py

https://github.com/buildbuddy-io/buildbuddy/commit/bc3ad577b6fcec1429f73437079ab8aea4e00bde

bump bb repo commit sha in dev_qa.py to current head

---

enterprise/server/raft/store/store.go

https://docs.google.com/document/d/1Vk5TqjFYykkmgtXTOmygtN9HI0fP0zYd6WHd8wOa6bo/edit?tab=t.0

[raft] refactor zombie clean up code

---

enterprise/server/raft/store/store.go

https://github.com/buildbuddy-io/buildbuddy/pull/8169

[raft] forget this place when addressing feedback earlier

---

enterprise/server/raft/store/store.go

When we are not able to process all zombies before the scan, we don't want
to add duplicate entries into the zombie. This can make the length of queue
metric I am adding in the following PR less representive of the number of
zombies in the system.
Also, if there are any errors happening in removeZombie, add them back to the
queue.

[raft] don't queue zombie tasks when they are already in queue

---

enterprise/server/raft/store/store.go

Also, include the error when failing to get the range descriptor

[raft] Remove data, allow remove data when only range_id is available

---

enterprise/server/util/vfs_server/vfs_server.go

We were using the fuse context instead of the task context.

Fix context used for accessing CAS artifacts.

---

tools/metrics/grafana/dashboards.bzl
tools/metrics/grafana/dashboards/globalstatus.json

We can tweak this but I wanted to try putting something together that showed everything on one page (incl macs, bare metal, europe, etc)

Rough draft of a global dashboard

---

enterprise/server/raft/driver/driver.go
enterprise/server/raft/store/store.go

added logging to track how range descriptor changes in driver.

[raft] fix removeDataReq in removeZombie and also add some logging

---

server/backends/blobstore/BUILD
server/backends/blobstore/blobstore.go
server/libmain/libmain.go
server/telemetry/BUILD
server/telemetry/telemetry_client.go
server/testutil/testenv/testenv.go
tools/replay_invocation/replay_invocation.go

I'd like to use blobstore for a mystery hackathon project and having it require an env is a little inconvenient.

Allow creating blobstore without env

---

docs/troubleshooting-rbe.md

Used this command
```
tail -45 docs/troubleshooting-rbe.md |\
llm -m gemini-2.0-flash-exp 'Fix grammar errors. Try to keep the original tone and format. New version:\n'
```
with some small manual style edits.

docs/troubleshooting-rbe: improve docs with llm

---

enterprise/app/code/BUILD
enterprise/app/code/code_v2.tsx
tools/goreman/procfiles/Procfile.codesearch

- **Add a kythe stub to fetch proto annotations**
- **key that makes sense**

kythe annotations stub

---

codesearch/searcher/searcher.go

Just to prevent bogus queries from using too much CPU.

Stop scoring after 100K docs

---

enterprise/server/cmd/ci_runner/main.go

Add some logging to help diagnose an issue where an artifact wasn't uploaded when we expected it to be.

Add more logging around workflow artifact uploading

---

enterprise/server/suggestion/suggestion.go
proto/suggestion.proto

This makes it possible to use the suggestion service for any prompting needs that the frontend has.

Allow overriding of default prompt when requesting suggestions

---

enterprise/server/cmd/ci_runner/main.go
enterprise/server/test/integration/ci_runner/BUILD
enterprise/server/test/integration/ci_runner/ci_runner_test.go

If `.gitmodules` exists after checking out the desired commit, we'll now automatically run `git submodule update --init --recursive`.

workflows: support git submodules

---

cli/explain/explain.go

Make the API target configurable.

cli: Make explain's invocation fetching usable in workflows 

---

enterprise/server/cmd/executor/executor.go
enterprise/server/remote_execution/containers/firecracker/BUILD
enterprise/server/remote_execution/containers/firecracker/firecracker.go
enterprise/server/remote_execution/containers/firecracker/firecracker_test.go
enterprise/server/remote_execution/runner/runner.go
enterprise/server/remote_execution/snaploader/snaploader.go
enterprise/server/remote_execution/snaputil/snaputil.go
enterprise/server/remote_execution/uffd/uffd.go

Reverts buildbuddy-io/buildbuddy#8327

Revert "[SS] Cleanup flags and debug data"

---

enterprise/server/cmd/ci_runner/main.go
enterprise/server/test/integration/ci_runner/BUILD
enterprise/server/test/integration/ci_runner/ci_runner_test.go

Revert "workflows: support git submodules (#8311)"

---

cli/explain/explain.go

More generally, state transitions are now handled independently of the new state.

explain: Print "old only" info when there is no "new only" info

---

enterprise/server/scheduling/priority_task_scheduler/priority_task_scheduler.go

Context: https://buildbuddy-corp.slack.com/archives/C05GZM1EGM8/p1739816255111619

Initialize queue length metric to 0 on startup

---

enterprise/server/scheduling/scheduler_client/scheduler_client.go
enterprise/server/scheduling/scheduler_server/scheduler_server.go
proto/scheduler.proto

Don't think its worth the maintenance cost.
https://github.com/buildbuddy-io/buildbuddy-internal/issues/4404

Revert "registration ack timeout" change.

---

enterprise/server/remote_execution/filecache/filecache.go

This improves AddFile performance by about 5%.
```
goos: linux
goarch: amd64
│ /tmp/nopathinvalue │       /tmp/nopathinvalue-rl        │
│       sec/op       │   sec/op     vs base               │
ContainsAdd/1K/10G-24          619.8µ ± 2%   616.4µ ± 2%       ~ (p=0.199 n=50)
ContainsAdd/1K/1M-24           14.51m ± 2%   13.72m ± 1%  -5.46% (p=0.000 n=50)
geomean                        2.999m        2.908m       -3.04%
│ /tmp/nopathinvalue │        /tmp/nopathinvalue-rl         │
│   retained-heap    │ retained-heap  vs base               │
ContainsAdd/1K/10G-24         229.9k ±  3%    233.8k ±  3%       ~ (p=0.336 n=50)
ContainsAdd/1K/1M-24          65.66k ± 10%    67.69k ± 10%       ~ (p=0.809 n=50)
geomean                       122.8k …
```

Reduce locked region in  filecache.AddFile

---

enterprise/server/remote_execution/filecache/filecache.go

Refactor so that we only lock/defer unlock once, which simplifies the control flow a bit so that the code section on line 372 (in the original file) is only locked from a single place rather than either the if or the else branch (having the lock inside a conditional felt slightly error prone)
(Was leaving this as a comment, but was too slow :P)

Refactor locking control flow in addFileToGroup

---

enterprise/server/cmd/ci_runner/main.go

[ci_runner] Add more clear timestamps to log

---

enterprise/server/raft/sender/BUILD
enterprise/server/raft/sender/sender.go
enterprise/server/raft/store/store.go
enterprise/server/raft/txn/txn.go

1. Add ctx as argument for runFunc passed into TryReplicas
2. Add child span for fn

[raft] fix TryReplicas tracing

---

enterprise/server/raft/leasekeeper/leasekeeper.go

Update leasekeeper.go to skip redundant work

---

app/format/format.tsx
enterprise/app/trends/cache_chart.tsx
enterprise/app/trends/common.ts
enterprise/app/trends/trends.tsx

Showing totals where it makes sense.

Show totals in trends charts legend

---

enterprise/server/raft/rangelease/rangelease.go

1. when ensureLeaseValid is used in doSingleInstruction, we already check
whether the lease is valid before calling this function.
2. When keepLeaseAlive is using it, it needs to renewLease no matter whether the
current lease is valid or not, so we don't need to check whether the lease is
valid or not

[raft] remove verifyLease from ensureLeaseValid

---

enterprise/server/raft/rangelease/BUILD
enterprise/server/raft/rangelease/rangelease.go

for debugging repeated timeout lease acquisition

[raft] add spn for rangelease.Lease

---

enterprise/server/util/ext4/BUILD
enterprise/server/util/ext4/ext4.go

I'm curious to see if this is CPU bound

Record CPU time of creating ext4 image in span attributes

---

enterprise/server/raft/registry/registry.go
enterprise/server/raft/store/store.go
enterprise/server/raft/store/store_test.go
proto/raft.proto
proto/raft_service.proto

During rollout, we spent quite a lot of time on query peers. 
https://github.com/buildbuddy-io/buildbuddy-internal/issues/3745

[raft] pre-load registry

---

website/package.json
website/yarn.lock

Fixes https://github.com/buildbuddy-io/buildbuddy/security/dependabot/191

Address https://github.com/buildbuddy-io/buildbuddy/security/dependabot/191

---

cli/parser/parser.go

`Option` will be used for options that have been parsed from the args, so we rename this struct to `OptionSchema` to free up the name.

Rename `Option` -> `OptionSchema` in the CLI

---

enterprise/app/tap/flakes.tsx

will investigate more next week.

drop time per flake entirely--the data doesn't look right

---

tools/metrics/grafana/dashboards/raft.json

fix error count graph for raft

---

server/testutil/mockgcs/BUILD
server/testutil/mockgcs/mockgcs.go

- **Add a mock GCS implementation**
- **Buildfix**

Add a simple mock gcs implementation

---

enterprise/server/cmd/metadata_server/BUILD
enterprise/server/cmd/metadata_server/main.go

Renamed (from MDS) for clarity.

Add metadata_server executable

---

enterprise/server/raft/store/store.go
enterprise/server/raft/store/store_test.go

https://github.com/buildbuddy-io/buildbuddy-internal/issues/4526
also added a test

[raft] fix an issue where we cannot remove replica when range descriptor is not in the meta range

---

enterprise/server/remote_execution/platform/platform.go
enterprise/server/scheduling/scheduler_server/scheduler_server.go
server/scheduling/scheduler_server/config/config.go

Mirroring what we are doing with MacOS

scheduler_server: force user-owned executor if Windows

---

server/janitor/janitor.go

Don't think we use this in prod, it seems unnecessary now.

Remove old janitor flag guarding warning logs

---

enterprise/server/remote_execution/containers/firecracker/BUILD
enterprise/server/remote_execution/containers/firecracker/firecracker.go
enterprise/server/remote_execution/executor/BUILD
enterprise/server/remote_execution/executor/executor.go
enterprise/server/remote_execution/snaploader/snaploader.go
enterprise/server/util/ext4/ext4.go

My main motivation is to make it easier to find and understand workflow executions.

Add a bit more tracing in the executor

---

enterprise/server/ociregistry/ociregistry.go

Forgot to hit `git push` with this fix on #8510.

Check that `Content-Length` header value from upstream registry is positive

---

enterprise/server/backends/pebble_cache/pebble_cache.go

I believe these are all safe to make the default, and I plan to remove these from the config once they are the default.

Update some pebble default flag values

---

enterprise/server/action_cache_server_proxy/BUILD
enterprise/server/action_cache_server_proxy/action_cache_server_proxy.go
enterprise/server/capabilities_server_proxy/BUILD
enterprise/server/capabilities_server_proxy/capabilities_server_proxy.go
server/metrics/metrics.go

These numbers should hopefully be insignificant, but it'll be nice to actually have them.

[Cache Proxy] track requests and bytes proxied through ActionCache and Capabilities proxy servers

---

enterprise/server/raft/store/store.go

If we have called RemoveData on a node, this node won't show up in
GetNodeHostInfo even when we set skipLogInfo = false. This means that if
we successfully removed a replica from the driver or cleaned up
a zombie, it should not appear in GetNodeHostInfo, therefore won't be
started during server startup.
https://github.com/buildbuddy-io/buildbuddy-internal/issues/4508

Don't make lookup active replicas during server startup

---

tools/metrics/grafana/dashboards/raft.json

To seperate metrics between raft-dev and metadata-server-dev

[raft] add namespace variable to raft dashboard

---

enterprise/server/workflow/config/config.go

https://github.com/buildbuddy-io/kythe/compare/v0.0.73...v0.0.74-buildbuddy

workflow/config: Update Kythe to v0.0.74

---

tools/metrics/grafana/dashboards/cache-proxy.json

[Cache Proxy] add more graphs tracking proxy servers performance

---

enterprise/server/raft/store/store.go

We added this map because in the past we have seen the replica janitor keep
removing zombies that have been removed when `RemoveData` was done with best
effort.
Now that we want to enforce `RemoveData` being called as the last step in zombie
cleanup. This map can potentially hide errors.

[raft] remove removedZombies map

---

enterprise/server/filestore/BUILD
enterprise/server/filestore/filestore.go

Add some logging to help debug GCS issue, and fix a missing context val.

debug missing gcs files

---

.github/workflows/coverage.yaml

Will give us some example coverage runs for demos and testing

Run daily coverage workflow

---

enterprise/server/remote_execution/filecache/filecache.go
enterprise/server/remote_execution/filecache/filecache_test.go

fixes https://github.com/buildbuddy-io/buildbuddy-internal/issues/4463

vfs: respect executable bit when writing files to filecache

---

.github/workflows/build-mac-intel-github-release-artifacts.yaml
.github/workflows/build-mac-m1-github-release-artifacts.yaml

https://github.com/buildbuddy-io/buildbuddy/actions/runs/13935372579/job/39002068961

Fix homedir in github mac workflows

---

cli/parser/parser.go
cli/parser/parser_test.go

In order to simplify parsing, we make just one set of `OptionDefintion`s and store them in the `Parser` alongside the set of known bazel commands. Before, we separated them out by command to cater to `CommandLineSchema`, which was designed for use with the usage-based help parsing; now, however, we have access to all the flag definitions, and they store within them which commands they support, so we can just check if options support commands after retrieving the `OptionDefiniton`.
Also did away with the `All` field in the parser, as it was never read and made modification of the Parser confusing when testing with options that would need to be deleted.

Make one `Parser` with all the `OptionDefinitions`

---

enterprise/app/tap/BUILD
enterprise/app/tap/tap.tsx

Otherwise old / junk repos accumulate in this picker and never go away.

Make test grid repos dropdown respect date range

---

enterprise/server/remote_execution/vfs/vfs_test.go
enterprise/server/remote_execution/vfs/vfs_unix.go

fixes https://github.com/buildbuddy-io/buildbuddy-internal/issues/4642

vfs: fix attrs returned in setattr

---

server/util/grpc_client/grpc_client.go

https://github.com/buildbuddy-io/buildbuddy-internal/issues/4645

Log connection pool state if unhealthy

---

enterprise/server/backends/distributed/BUILD
enterprise/server/backends/distributed/distributed.go
enterprise/server/util/distributed_client/BUILD
enterprise/server/util/distributed_client/distributed_client.go
enterprise/server/util/distributed_client/distributed_client_test.go

Save some poor future souls a grep headache

Rename ye olde CacheProxy to make way for new one

---

enterprise/server/remote_execution/vfs/vfs_test.go
enterprise/server/remote_execution/vfs/vfs_unix.go
enterprise/server/util/vfs_server/vfs_server.go
proto/vfs.proto

fixes https://github.com/buildbuddy-io/buildbuddy-internal/issues/4647

vfs: add extended attribute support

---

server/build_event_protocol/build_event_handler/build_event_handler.go

Also check that ordered_build_event exists before handleEvent

event_handler: ensure all proto fields are accessed through getter

---

enterprise/server/remote_execution/containers/firecracker/firecracker.go
enterprise/server/remote_execution/vfs/vfs_test.go
enterprise/server/remote_execution/vfs/vfs_unix.go
enterprise/server/remote_execution/workspace/workspace.go
enterprise/server/util/vfs_server/vfs_server.go
enterprise/server/util/vfs_server/vfs_server_test.go
enterprise/server/util/vfs_server/vfs_server_unsupported.go
enterprise/tools/mount_vfs/mount_vfs.go
proto/vfs.proto

fixes https://github.com/buildbuddy-io/buildbuddy-internal/issues/4648

vfs: add a basic statfs implementation.

---

server/backends/chunkstore/chunkstore.go
server/eventlog/eventlog.go

Add comments to this file to improve clarity / readability, as we are currently investigating an issue that appears to be related.

Add comments to `eventlog.go`

---

enterprise/server/experiments/BUILD
enterprise/server/experiments/experiments.go

This was very confusing -- but we need to use WIthHost and WithPort to specify where we are connecting to.

Fix flagd dialing code

---

enterprise/server/workflow/config/config.go

This reverts commit 6142348f16a5cb8583801a5c792de73f9e219871.
Currently does not work due to missing exec platform information on
Kythe actions.
Need to find a better way to handle this.
Disable RBE for now.

Revert "kythe: use rbe instead of local exec (#8581)"

---

deps.bzl

https://github.com/firecracker-microvm/firecracker/releases/tag/v1.11.0

Upgrade firecracker to version v1.11

---

enterprise/server/raft/store/store.go

This can cause data race in tests

[raft] don't use flag values in go routines

---

enterprise/app/repo/repo.tsx
enterprise/app/settings/github_complete_installation.tsx
enterprise/app/settings/github_link.tsx
enterprise/app/workflows/github_app_import.tsx
enterprise/server/githubapp/BUILD
enterprise/server/githubapp/githubapp.go
enterprise/server/githubauth/githubauth.go
enterprise/server/hostedrunner/hostedrunner.go
enterprise/server/test/integration/remote_bazel/remote_bazel_test.go
enterprise/server/workflow/service/service.go
enterprise/server/workspace/workspace_service.go
proto/github.proto
server/backends/github/github.go
server/buildbuddy_server/buildbuddy_server.go
server/environment/environment.go
server/interfaces/interfaces.go
server/libmain/libmain.go
server/real_environment/real_environment.go
server/static/static.go
server/tables/tables.go
server/testutil/testgit/testgit.go

This reverts commit 3cf4d90f4b5b41e866d9b95247cf0706d673c556.

Revert "Refactor github logic to prepare for supporting 2 github apps (#8611)"

---

enterprise/server/raft/store/store.go

address comments in https://github.com/buildbuddy-io/buildbuddy/pull/8777

address feedback in previous PR

---

cli/printlog/printlog.go

Protodelim default is 4MB: https://go.googlesource.com/protobuf/+/master/encoding/protodelim/protodelim.go#61
Also adds the flag `--max_entry_size_mb` so it can be bumped further if needed.

Bump cli's print log max message size to 40 MB

---

enterprise/server/scim/scim.go

https://github.com/buildbuddy-io/buildbuddy-internal/issues/4703

Log more information for SCIM requests to make debugging easier.

---

enterprise/server/scim/scim.go
enterprise/server/scim/scim_test.go

Treat them the same as 'replace' updates.
fixes https://github.com/buildbuddy-io/buildbuddy-internal/issues/4703

SCIM: support PATCH updates with 'add' operations.

---

enterprise/server/raft/events/events.go
enterprise/server/raft/store/store.go

remove unused event type
remove unused sendRangeEvent in store

[raft] clean up raft/events

---

enterprise/tools/replay_action/replay_action.go

Fixes lots of large, duplicate file uploads when uploading inputs for a replayed execution.

replay_action: fix deduping in copyTree

---

enterprise/server/raft/store/store.go

introduced in https://github.com/buildbuddy-io/buildbuddy/pull/8886

[raft] fix a bug in drop leadership

---

enterprise/server/remote_execution/runner/runner.go

Context: https://github.com/buildbuddy-io/buildbuddy-internal/issues/4789
If we sample runner disk usage with, say, 10% probability instead of 100%, then this should free up somewhere between 250m and 1000m CPU capacity on each of the macs mentioned in the linked issue when the executor is under high load.

Allow sampling runner disk usage to reduce CPU

---

enterprise/server/raft/driver/driver.go
enterprise/server/raft/store/store.go

https://github.com/buildbuddy-io/buildbuddy-internal/issues/4802

[raft] add an action in driver to removeData

---

server/remote_cache/digest/digest.go

This was using a regexp just to check the length, and that all the characters were lower case hex. In prod this is using roughly 2% of the CPU of pebble_cache.FindMissing
This speeds up pebble read benchmarks by another 3%-14%:
```
goos: linux
goarch: amd64
│     base     │               simple                │
│    sec/op    │    sec/op     vs base               │
GetMulti/size=1KiB-24                    1.525m ±  2%   1.468m ±  1%   -3.74% (p=0.001 n=7)
GetMulti/size=1MiB-24                    65.23m ±  1%   63.26m ±  2%   -3.02% (p=0.002 n=7)
GetMulti/size=10MiB-24                   908.5m ±  2%   882.0m ±  4%   -2.91% (p=0.017 n=7)
FindMissing/size=1KiB/insert=false-24    351.1µ ±  4%   298.9µ ±  4%  -14.85% (p=0.001 n=7) …
```

Optimize digest.ResourceName.Validate

---

server/util/redact/redact_test.go

This change introduces the following test functions (and moves test cases into those functions):
* `TestRedactEntireSections`
* `TestRedactRemoteHeaders`
* `TestRemoveRepoURLCredentials`
This change neither increases nor decreases test coverage. I am starting to see spots where we could be more exhaustive.

Group more (but not all) redaction tests by kind of secret

---

enterprise/server/raft/store/store.go
enterprise/server/raft/store/store_test.go

[raft] fix flaky test: always stop replica before remove data

---

server/config/config_test.go
server/util/flagutil/types/types.go

Fixes https://github.com/buildbuddy-io/buildbuddy-internal/issues/4672

Fix multiline secret expansion inside struct flag.

---

enterprise/server/atime_updater/atime_updater.go

I'm trying to address the TODO on line 146 of the code before this change:
```
// TODO(iain): this locking may be a bit overzealous. Hopefully not though.
```
This PR makes the next diff a big easier to understand.

In atime_updater, factor out the pending-update-searching logic into a function

---

server/util/watchdog/watchdog.go
server/util/watchdog/watchdog_test.go

Address https://github.com/buildbuddy-io/buildbuddy/pull/8952#discussion_r2044676472

Add some comments (and a lock) on watchdog package

---

enterprise/server/atime_updater/atime_updater.go

This PR addresses the TODO on line 167:
```
// TODO(iain): this locking may be a bit overzealous. Hopefully not though.
```
I added a little benchmark that tests the performance of `atime_updater.Enqueue(...)`:
```
// setup...
instances := []string{"instance-1", "instance-2", "instance-3", "instance-4", "instance-5", "instance-6", "instance-7", "instance-8", "instance-9", "instance-10"}
digests := []*repb.Digest{aDigest, bDigest, cDigest, dDigest, eDigest, fDigest, gDigest, hDigest, iDigest, jDigest}
start := time.Now()
for i := 0; i < 10; i++ {
wg := sync.WaitGroup{}
// This runs 1,000 * 10 * 10 = 100,000 times
for i := 0; i < 1_000; i++ {
for _, instance := range instances {
for _, digest := range digests {
req := repb.FindMissingBlobsRequest{
InstanceName:   instance,
BlobDigests: …
```

Lock more judiciously in atime_updater.go

---

.github/workflows/build-linux-amd64-github-release-artifacts.yaml
.github/workflows/release-cli.yaml

Github has depcreated the ubuntu 20.04 runner

Bump github linux amd64 runner version

---

enterprise/server/remote_execution/vfs/vfs_unix.go

The existing test should have surfaced this issue but the firecracker kernel doesn't support passthrough and our non-passthrough implementation was automatically invalidating the cache after every write. I removed the invalidation so that the non-passthrough and passthrough behaviors are the same.

Mark inode as opened in Create as well.

---

enterprise/server/remote_execution/containers/bare/bare.go
enterprise/server/remote_execution/containers/bare/bare_test.go

The executor's root directory can be set to a relative path. This causes $TMPDIR to point to a non-existent directory path.

Ensure TMPDIR path is absolute

---

enterprise/server/remote_execution/platform/platform.go
enterprise/server/remote_execution/platform/platform_test.go

When setting `--executor.extra_env_vars=NAME` (omitting the `=VALUE` part), inherit the env var's value from the executor process. This is similar to bazel's `--action_env` which has the same syntax and semantics.

Allow inheriting process env vars

---

enterprise/server/atime_updater/atime_updater_test.go

This is basically what I was using for https://github.com/buildbuddy-io/buildbuddy/pull/8991, so figured it'd be wise to check it in.

Add a benchmark for atime_updater.Enqueue()

---

MODULE.bazel
WORKSPACE
WORKSPACE.bzlmod
buildbuddy.yaml
buildpatches/rules_docker.patch

Reverts buildbuddy-io/buildbuddy#8924

Revert "bzlmod: use our own forks of rules_{docker,k8s}"

---

enterprise/server/scheduling/priority_task_scheduler/priority_task_scheduler.go

Context: https://buildbuddy-corp.slack.com/archives/C0495TM9UUE/p1745349300729789?thread_ts=1745347202.204039&cid=C0495TM9UUE

Log CloseAndRecv error

---

tools/metrics/grafana/dashboards/mac.json

Add an "executor performance summary" panel, with the ability to filter by inventory_hostname_pattern.

Improve mac dashboard

---

enterprise/server/byte_stream_server_proxy/byte_stream_server_proxy_test.go
server/testutil/testenv/testenv.go

https://github.com/buildbuddy-io/buildbuddy-internal/issues/4782

Add benchmarks for byte_stream_server_proxy Read and Write RPCs

---

enterprise/server/scheduling/priority_task_scheduler/priority_task_scheduler_test.go

Fix race in priority_task_scheduler_test

---

server/backends/github/github.go
server/build_event_protocol/build_status_reporter/build_status_reporter.go

https://buildbuddy.slack.com/archives/CUY16GNK1/p1744983438830069
Fixes https://github.com/buildbuddy-io/buildbuddy/issues/9010#event-17321236767

Always report github statuses if a hard coded reporting token was set

---

shared.bazelrc

Reverts buildbuddy-io/buildbuddy#9048
welp

Revert "Enable VFS on our workflows."

---

enterprise/server/content_addressable_storage_server_proxy/content_addressable_storage_server_proxy_test.go
server/testutil/cas/cas.go

https://github.com/buildbuddy-io/buildbuddy-internal/issues/4782

Add benchmarks for content_addressable_storage_server_proxy RPCs

---

shared.bazelrc

Reverts buildbuddy-io/buildbuddy#9056

Rererererererereererevert "Enable VFS on our workflows.""

---

enterprise/server/raft/replica/replica.go

[raft] add a bg ctx to replica

---

tools/metrics/grafana/dashboards/buildbuddy.json

add "HTTP client bytes read per request" to HTTP section

---

enterprise/server/backends/pubsub/pubsub.go

I found this while trying to figure out why some tasks have way more goroutines than others. I don't think this is the cause, and it's no that severe, but might as well fix it.
Right now, if the context expires while the monitoring goroutine is calling `checkMonitoredChannelExists`, then `msgChan` will get closed, and the third (merge) goroutine will exit, so nothing will be listening t `monChan`.
If fixed this by putting each error send in a select with a `<-ctx.Done()`.

Fix a goroutine leak in pubsub.Subscribe

---

cli/printlog/compact/compact.go

Updates the execution log parser to recognize and prioritize
new fields for referencing inputs and outputs.
Uses `input_ids` in `Set` and `output_id` in `Output` which
are present in newer versions of the execution log format.
This allows the parser to correctly identify inputs and outputs
referenced by these new IDs (files, directories, symlinks).
Deprecated fields (`file_ids`, `directory_ids`, `unresolved_
symlink_ids`, `transitive_set_ids`) are now handled as a
fallback.
Also adds stub handling (with TODOs) for new top-level entry
types: SymlinkAction, SymlinkEntrySet, and RunfilesTree.

printlog: Use new exec log input/output IDs

---

enterprise/server/util/vfs_server/vfs_server.go

We try to refresh attributes when a file is closed but the backing file won't be there if unlink is called first.

vfs: fix some log spam if an fd is closed after unlinking

---

enterprise/server/raft/rbuilder/rbuilder.go
enterprise/server/raft/replica/replica.go
enterprise/server/raft/store/BUILD
enterprise/server/raft/store/store.go
enterprise/server/raft/testutil/testutil.go
enterprise/server/raft/txn/BUILD
enterprise/server/raft/txn/txn.go
proto/raft.proto

https://github.com/buildbuddy-io/buildbuddy-internal/issues/4843

[raft] start the shard in post commit hook for split

---

enterprise/server/test/integration/ci_runner/ci_runner_test.go

I'm seeing 
``` testserver.go:73: binary failed to start within 30s: /readyz err: Get "http://localhost:37693/readyz?server-type=buildbuddy-server": dial tcp 127.0.0.1:37693: connect: connection refused```
on multiple failing tests in this suite. Let's start by calling `t.Run(...)` on each test case.

call t.Run on ci_runner_test test cases

---

shared.bazelrc

also, run flaky tests when we use deflake config.

add a debug config where we can run flaky tests

---

enterprise/server/remote_execution/snaploader/snaploader.go

[A customer's snapshot writes have been timing out after our default 10min runner recycle timeout](https://buildbuddy.slack.com/archives/CUHBFVATU/p1745620488310219). We don't release workflows' requested resources until after the snapshot has been saved anyway, so we should use the allocated cores to save the snapshots faster

[SS] Scale snapshot write concurrency with the number of requested CPUs

---

enterprise/server/ociregistry/README.md

README that captures cache organization.

[oci registry] README

---

enterprise/server/remote_execution/snaploader/snaploader.go

Also log how many chunks were uploaded before an error, and remove one layer of nested goroutine. We're currently simultaneously uploading memory + disk snapshots. We rate limit the number of concurrent goroutines writing chunks anyway, so we might as well just write each snapshot one at a time. If we fail to write one snapshot, we shouldn't bother trying to write the other

[SS] Exit early if there's an error saving one snapshot chunk

---

enterprise/server/remote_execution/operation/operation.go

We saw this error, which isn't currently being retried: `Error closing execution status update stream: rpc error: code = Unavailable desc = unexpected HTTP status code received from server: 502 (Bad Gateway); transport: received unexpected content-type "text/html; charset=UTF-8"`

Retry more errors in PublishOperation

---

enterprise/server/raft/driver/driver.go
enterprise/server/raft/header/header.go
enterprise/server/raft/sender/sender.go
enterprise/server/raft/store/store.go
enterprise/server/raft/store/store_test.go

make the header function take in replicaDescriptor instead of index

[raft] refactor header function

---

shared.bazelrc

Reverts buildbuddy-io/buildbuddy#9060

Revert "Enable VFS on our workflows."""

---

enterprise/server/remote_execution/containers/firecracker/firecracker.go
enterprise/server/remote_execution/containers/firecracker/firecracker_test.go
enterprise/server/remote_execution/snaploader/snaploader.go

Apply changes from https://github.com/buildbuddy-io/buildbuddy/pull/9153

[SS] Only cache multiple snapshots on the same branch locally

---

enterprise/server/scheduling/scheduler_server/scheduler_server.go
enterprise/server/scheduling/scheduler_server/scheduler_server_test.go

The `debug-executor-id` platform property is helpful in debugging execution on a specific executor, and can be used to route remote runner requests to a specific executor with a local snapshot present. Work stealing makes it unreliable, so have the scheduler always respect it.

Respect debug-executor-id when work stealing

---

enterprise/server/workflow/service/BUILD

Attempt to fix timeouts by splitting up the test so each individual test has a longer time to run.

Shard workflow service test

---

tools/metrics/docker-compose.node-exporter.yml
tools/metrics/grafana/dashboards.bzl
tools/metrics/grafana/dashboards/node-exporter-full.json
tools/metrics/grafana/grafana.go
tools/metrics/victoria-metrics/scrape.yml

Importing the dashboard here: https://grafana.com/grafana/dashboards/1860-node-exporter-full/
And also adding a local node-exporter to the docker-compose setup.

Add grafana node exporter dashboard

---

enterprise/server/backends/redis_execution_collector/redis_execution_collector.go

Split out from https://github.com/buildbuddy-io/buildbuddy/pull/9211

Document execution collector redis keys

---

app/invocation/BUILD
app/invocation/invocation_exec_log_card.tsx
enterprise/server/execution_service/BUILD
enterprise/server/execution_service/execution_service.go
enterprise/server/execution_service/execution_service_test.go

Also surface the error more obviously in the UI, and add tests.

Fix auth check when reading clickhouse executions for anonymous user

---

MODULE.bazel
WORKSPACE
go.mod

https://github.com/golang/go/issues?q=milestone%3AGo1.24.3+label%3ACherryPickApproved

gosdk: upgrade to 1.24.3

---

enterprise/server/ociregistry/ociregistry.go

Not going to merge this until #9044 is out and good.

[oci registry] fetch manifest from AC instead of CAS

---

shared.bazelrc

I think this is the time it finally sticks...?

Enable VFS on our workflows.

---

app/invocation/BUILD
app/invocation/invocation_coverage_card.tsx
app/root/root.css
app/target/target_test_coverage_card.tsx

Also clean up a bit of CSS that I missed in the last PR.

Use TextLink for coverage listing in one more place

---

enterprise/server/ociregistry/ociregistry.go

Reverts buildbuddy-io/buildbuddy#9268

Revert "Revert "[oci registry] fetch manifest from AC instead of CAS""

---

app/invocation/BUILD
app/invocation/invocation.css
app/invocation/invocation_execution_table.tsx
app/invocation/invocation_execution_util.tsx
enterprise/server/util/execution/execution.go

Show target labels if we have them, and implement a few misc UI improvements.
Before:
After:

Show target labels in execution table if we have them

---

enterprise/server/ociregistry/ociregistry.go

This change is a mechanical change to separate all functions that interact with the AC and CAS from the rest of the OCI registry mirror code.
A later change will move these cache functions to `oci.go` and make them public.
That later change will then create a dependency from `ociregistry` on `oci`.
This is all setup for caching (potentially) private OCI images in `oci.Resolver.Resolve(...)`.

[oci registry] separate functions that read from or write to AC or CAS

---

server/util/compression/compression.go

We suspect this is triggering a panic. See https://buildbuddy-corp.slack.com/archives/C06N9AHA4JX/p1746725758528329

Don't use io.Pipe in compression.NewZstdCompressingReader

---

enterprise/server/auditlog/BUILD
enterprise/server/auditlog/auditlog.go
enterprise/server/auditlog/auditlog_test.go
proto/api_key.proto
server/capabilities_filter/capabilities_filter.go

Adding the new capability to the UI is a separate PR.

Add new capability for querying audit logs.

---

enterprise/server/remote_execution/snaputil/snaputil.go

Fixes [error](https://buildbuddy-corp.slack.com/archives/C0154UFBCJ2/p1746559254308709)

[SS] Cleanup paths after failed fetches

---

cli/remotebazel/BUILD
cli/remotebazel/remotebazel.go
enterprise/server/hostedrunner/hostedrunner.go
enterprise/server/remote_execution/containers/firecracker/BUILD
enterprise/server/remote_execution/containers/firecracker/firecracker.go
enterprise/server/scheduling/scheduler_server/BUILD
enterprise/server/scheduling/scheduler_server/scheduler_server.go
server/util/error_util/BUILD
server/util/error_util/error_util.go

Before it would look like:
Now it will look like:

[RB] Cleaner error handling for expected errors in CLI

---

enterprise/server/raft/store/store_test.go

https://app.buildbuddy.io/invocation/5a58ae84-b7ba-4f74-8be3-94b6105daa41
https://app.buildbuddy.io/invocation/0dd626e5-9c9a-4504-94b2-8e672e9a82e6
https://app.buildbuddy.io/invocation/38a27f90-ac34-49b3-91eb-aabb8cee3491

[raft] unquarantine TestSplitNonMetaRange

---

enterprise/server/hit_tracker_service/BUILD
enterprise/server/hit_tracker_service/hit_tracker_service.go

Check for invalid data in hit tracker service

---

enterprise/server/raft/store/store_test.go

runs:
https://app.buildbuddy.io/invocation/b58b04e5-5082-4ce2-bfcd-90db510852c1
https://app.buildbuddy.io/invocation/1a62f4f0-9837-4cec-a84b-d97fa7e8b310

[raft] unquarantine TestPostFactoSplit

---

enterprise/server/raft/store/store_test.go

2 500 runs
https://app.buildbuddy.io/invocation/19a28347-5c7b-4136-99ee-641d0f5432d4
https://app.buildbuddy.io/invocation/8b9a6caf-bf8b-4059-b8bd-2d54183ac406

[raft] unquarantine TestSplitAcross

---

release.py

Something weird is going on with the release.

Log output of git status.

---

cli/parser/parser.go

These were moved to `bazelrc.go`.

Remove `getBazelOS` and `getPhases` from `parser.go`

---

codesearch/index/index.go

This does change the `DeleteDocument` semantics slightly - instead of being applied immediately the index, they are now added to the current batch (consistent with `AddDocument` and `UpdateDocument`). We're not currently calling it from anywhere outside of `index.go`, so this should be safe.
Note that the `lookupDocId` helper function isn't attached to `Writer` because it will also be used from `Reader` in an imminent follow on change.

Factor common CS doc update/delete functionality 

---

enterprise/server/test/performance/cache/cache_test.go

This mostly doesn't affect the actual benchmark results. There's 2 improvements:
1. Instead of using unique digests in Set benchmarks to circumvent caches which first call FindMissing, use AC entries, since those have to be written.
2.  Use b.Loop() instead of b.N. This lets the benchmark function run fewer times. See https://go.dev/blog/testing-b-loop
A nice side benefit of #1 is that now we also benchmark the AC path for writes, in case other things are different about it.
This make the whole benchmark finish in about 4.5 minutes, and use less than 5GB of memory when running remotely.

Speed up cache benchmarks and make them use less RAM

---

server/tables/tables.go

The UI renders that value [here](https://github.com/buildbuddy-io/buildbuddy/blob/master/enterprise/app/org/org_members.tsx#L253)
Fixes [this](https://buildbuddy-corp.slack.com/archives/C0495TM9UUE/p1747423662459899)

Use the github username as the name, if no name is set.

---

server/remote_cache/digest/BUILD
server/remote_cache/digest/digest_test.go

Related issues: https://github.com/buildbuddy-io/buildbuddy-internal/issues/5015

Expand test coverage of digest parsing

---

codesearch/index/index.go
codesearch/index/index_test.go
codesearch/server/server.go

- Log the correct commit when finishing incremental vs full updates
- Handle updating the same file more than once within a single batch
- Fix GetRepoStatus to use the correct schema (server tests have been added to the TODO list...)

Fix multiple codesearch bugs

---

enterprise/server/raft/store/store_test.go

https://app.buildbuddy.io/invocation/460f918d-9d1f-4994-a0b4-c8f7898795dc
https://app.buildbuddy.io/invocation/189f717c-1f62-4fd5-822e-e3d8c6f544ba

[raft] unquarantine TestManySplits

---

server/remote_cache/digest/digest_test.go

Mostly around missing the leading '/'

Add a few more test cases for digest.go

---

server/remote_cache/cachetools/cachetools.go
server/remote_cache/cachetools/cachetools_test.go

For writing OCI image layers to the CAS, I'll need zstd support, so I went ahead and added it. This change also includes tests for using zstd with `UploadWriter`.
`UploadWriter` keeps a `cbuf` for writing compressed bytes. `CompressZstd` may allocate an additional buffer if `cbuf` is not large enough for the compressed output. However, I do not want `UploadWriter` to take ownership of that buffer: I want to keep a reference to the same `cbuf` so I can return it to the pool on `Close`.

[cachetools] add support for zstd to UploadWriter

---

tools/metrics/grafana/dashboards/buildbuddy.json
tools/metrics/grafana/dashboards/cache-proxy.json

I accidentally left it open in https://github.com/buildbuddy-io/buildbuddy/pull/9433.

[dash] Collapse the "Distributed Cache" section by default

---

enterprise/app/settings/BUILD
enterprise/app/settings/github_link.tsx
enterprise/app/settings/settings.css
enterprise/server/githubapp/githubapp.go
proto/buildbuddy_service.proto
proto/github.proto
server/buildbuddy_server/buildbuddy_server.go
server/capabilities_filter/capabilities_filter.go
server/interfaces/interfaces.go

Add UI toggle to set ReportCommitStatusesForCiBuilds

---

app/invocation/invocation_execution_table.tsx

https://buildbuddy-corp.slack.com/archives/C03JL0YT6G5/p1747967889709579

Don't repeat failed exit codes in the execution rows

---

enterprise/server/raft/metadata/metadata_test.go

[raft] unquarantine TestAutoBringup

---

enterprise/server/workflow/config/config.go

Try newer ubuntu to get a compatible glibc version

Fix codesearch workflow action

---

cli/parser/options/options.go

Guessing this was not intentional

Remove printf from flag parsing logic

---

proto/remote_execution.proto

Adds protos to support collecting network usage stats from executions.

Proto changes for network usage

---

enterprise/server/workflow/config/config.go

Temporary workaround until https://github.com/buildbuddy-io/buildbuddy-internal/issues/5060 is fixed

Explicitly install bb for codesearch workflow action

---

enterprise/server/backends/pebble_cache/pebble_cache.go

`NewZstdCompressor` gets a compression buffer from the pool.
We must make sure to give that same buffer back to the pool on close.
Since `CompressZstd` can allocate a new buffer, we have to track the buffer we got from the pool separately in order to correctly put it back.

[pebble cache] fix potential buffer leak

---

enterprise/server/raft/metadata/metadata.go
enterprise/server/raft/metadata/metadata_test.go
enterprise/server/raft/replica/replica.go
enterprise/server/raft/store/store.go
enterprise/server/raft/usagetracker/usagetracker.go

Runs successfully 3 * 1000 times. 
https://app.buildbuddy.io/invocation/2283e499-9041-44c1-b6a2-bef776a2a34c
https://app.buildbuddy.io/invocation/fccdc19e-7a4c-472c-8180-cb26141376d6
https://app.buildbuddy.io/invocation/7abf5ae7-8b8a-4a1f-921f-d8328fe8a67d

[raft] fix TestLRU in metadata_test

---

enterprise/server/util/distributed_client/distributed_client.go

This was added in https://github.com/buildbuddy-io/buildbuddy/pull/9503 because I thought it might fix our memory leak, but it wasn't related.
Also, it does prevent the active RPC count from continuously going up, but it causes it to continuously go down, though at a slower rate. 
I suspect that the prometheus metrics interceptor is incrementing the `handled` count every time `CloseAndRecv` is called, so I just added a `CloseAndRecv` call in `Close`, if it hasn't been called already. Cancelling the stream context should be sufficient to close the stream, but this way, `distributed_client.RemoteWriter` doesn't rely on that, and as long as `Close` is called, the stream will be closed.

Remove CloseAndRecv in runtime.Cleanup

---

server/gossip/BUILD
server/gossip/gossip.go
server/gossip/gossip_test.go

UserQuery:
https://app.buildbuddy.io/invocation/c30c5e78-8483-4aee-9118-e7476db7f0da
https://app.buildbuddy.io/invocation/d9c4e5a7-6b5c-4b9d-8ea2-3d8e8d1bd9b2
UserEvents:
https://app.buildbuddy.io/invocation/9478b501-5207-4e59-bbe2-a41080c167a3
https://app.buildbuddy.io/invocation/b028b85b-1baf-4aa7-ad30-52822f1ed5a8

add --gossip.retransmit_mult and set it to 10 in gossip_test

---

enterprise/server/raft/leasekeeper/leasekeeper.go

This can prevent races on la.eg.

[raft] start la.runLoop in newLeaseAgent

---

enterprise/server/backends/migration_cache/migration_cache.go

`io.Writer` says that
> Implementations must not retain p (the buffer passed to Write)
The `asyncWriter` I introduced definitely violates this. In practice, this worked for us, because the buffer comes from proto parsing code, which doesn't reuse the buffer. Still, I don't feel comfortable keeping this foot-gun around.
I've change the implementation to be pretty similar to how it was before my optimization, but it uses a single `sync.WaitGroup`, instead of creating a new `errgroup.Group` for every call. Performance wise, this new version ends up being roughly half way between the original version and the `asyncWriter`.
It's also a lot simpler.
```
│  original   │         broken-optimization         │          new-optimization          │
│   sec/op    │   sec/op     vs …
```

Partially undo my optimization of migration_cache.Writer

---

enterprise/server/util/oci/BUILD
enterprise/server/util/oci/oci.go
enterprise/server/util/oci/oci_test.go

[oci resolver] add read_layers_from_cache flag (disabled by default)

---

enterprise/server/backends/migration_cache/migration_cache.go

I forgot to push before merging.

Fix log statements from https://github.com/buildbuddy-io/buildbuddy/pull/9604

---

enterprise/server/workflow/config/config.go

This picks up the go vnames config fix

Bump to kythe 0.0.76

---

enterprise/server/raft/store/store.go

introduced in https://github.com/buildbuddy-io/buildbuddy/pull/9654

[raft] fix a bug

---

server/cache/dirtools/dirtools.go

File cache stores executable and non-executable entries separately, even for the same hash due to the fact that attributes are shared when hardlinking.
To simplify handling of the executable bit during input downloads, treat executable and non-executable inputs as different artifacts.

Include executable bit in input tree fetch key.

---

enterprise/server/backends/pebble_cache/pebble_cache.go
proto/storage.proto
server/metrics/metrics.go

Reverts buildbuddy-io/buildbuddy#9633

Revert "sample pebble partition size by group, throttled a bit"

---

enterprise/app/code/code.css
enterprise/app/code/code_v2.tsx

Incorporate kythe annotations into v2 code browser

---

server/util/lib/seq/seq.go
server/util/lib/seq/seq_test.go

Adds a `Drop` function as the counterpart to `Truncate`.

Add `seq.Drop` function

---

enterprise/server/raft/constants/constants.go
enterprise/server/raft/driver/driver.go
enterprise/server/raft/replica/replica.go
enterprise/server/raft/sender/sender.go
enterprise/server/raft/store/store.go
enterprise/server/raft/store/store_test.go

also retries when there is conflict on key.

[raft] lock the left range when we split

---

MODULE.bazel
WORKSPACE

Updates the base image for our app image to pick up security fixes.

Update app image

---

enterprise/server/usage/usage.go
enterprise/server/usage/usage_test.go
server/tables/tables.go
server/util/usageutil/usageutil.go

see #9592 for the actual changes to use the new field

schema changes for a server field in the usage table. 

---

enterprise/server/backends/pebble_cache/pebble_cache.go

In all but one case, we need both versions. Getting them together slightly speeds up some operations.
```
│     base     │               minmax               │
│    sec/op    │   sec/op     vs base               │
Set/LocalPebble10/AC-24             10.53µ ±  3%   10.55µ ± 2%       ~ (p=0.606 n=11)
Set/LocalPebble10/CAS-24            8.877µ ±  4%   8.697µ ± 2%       ~ (p=0.058 n=11)
Set/LocalPebble100/AC-24            15.43µ ±  4%   15.32µ ± 2%       ~ (p=0.898 n=11)
Set/LocalPebble100/CAS-24           14.09µ ±  6%   13.24µ ± 3%  -6.01% (p=0.004 n=11)
Set/LocalPebble1000/AC-24           25.77µ ± 12%   23.58µ ± 3%       ~ (p=0.056 n=11)
Set/LocalPebble1000/CAS-24          21.77µ ±  5%   21.52µ ± 5%       ~ (p=0.606 n=11)
Set/LocalPebble10000/AC-24          143.3µ ±  5% …
```

Get maximum and minimum pebble db version with a single lock call

---

enterprise/server/remote_execution/filecache/filecache.go
server/cache/dirtools/BUILD
server/cache/dirtools/dirtools.go
server/metrics/metrics.go

I'm making some changes around the file cache that could affect performance and want more visibility into the effects.

Add some additional executor latency metrics.

---

enterprise/server/atime_updater/atime_updater_test.go

With this change, https://github.com/buildbuddy-io/buildbuddy/pull/9809 makes the benchmark run about 16% faster:
```
goos: linux
goarch: amd64
│ /home/iain/old.txt │         /home/iain/new.txt          │
│       sec/op       │   sec/op     vs base                │
Enqueue-16          244.5m ± 0%   205.4m ± 1%  -15.99% (p=0.000 n=20)
│ /home/iain/old.txt │          /home/iain/new.txt          │
│        B/op        │     B/op      vs base                │
Enqueue-16         196.8Mi ± 0%   263.7Mi ± 0%  +34.01% (p=0.000 n=20)
│ /home/iain/old.txt │         /home/iain/new.txt          │
│     allocs/op      │  allocs/op   vs base                │
Enqueue-16          5.130M ± 0%   6.030M ± 0%  +17.54% (p=0.000 n=20)
```

Use multiple user contexts in atime_updater benchmark

---

enterprise/server/backends/migration_cache/migration_cache.go

- Use log.Ctx... methods so it's easier to spot failures just for one group ID
- For read methods, only start a destination read if the source succeeded. This means we only log misses when we expect hits and we only increment hit and miss metrics when we expect a hit. This makes it much easier to tell what percentage or requests were hit in the source but missing in the destination. Finally, this means that we don't enqueue copies when the source doesn't contain the resource.

Improve logging and metrics in the migration cache

---

docs/rbe-platforms.md

To be merged after https://github.com/buildbuddy-io/buildbuddy/pull/9777/files is rolled out

Update persistent worker docs

---

enterprise/server/raft/store/store.go
enterprise/server/raft/store/store_test.go

https://github.com/buildbuddy-io/buildbuddy-internal/issues/4913

[raft] reduce responsibilities of zombie janitor

---

enterprise/server/raft/store/store.go
enterprise/server/raft/store/store_test.go

https://github.com/buildbuddy-io/buildbuddy-internal/issues/4913

[raft] remove NonVoterZombieJanitor

---

enterprise/server/raft/store/BUILD
enterprise/server/raft/store/store.go
enterprise/server/raft/store/store_test.go

I don't think this scanario is not realistic given the introduction of
staging and removed replicas. Still, I want to make zombie janitor can
handle this case if we ended up here.

[raft] fix this ZombieInRangeDescriptor test and that uncovered a bug.

---

enterprise/server/raft/driver/driver.go
enterprise/server/raft/store/store.go
server/metrics/metrics.go

https://github.com/buildbuddy-io/buildbuddy-internal/issues/4913

[raft] add more metrics to monitor driver and intermediate replica states

---

enterprise/server/backends/distributed/distributed.go
enterprise/server/backends/distributed/distributed_test.go

I also added more context to the assertions.

Deflake distributed_test even more 

---

server/util/authutil/authutil.go

The cache proxy directly calls internal local grpc servers, instead of going through a grpc client ([Example](https://github.com/buildbuddy-io/buildbuddy/blob/master/enterprise/server/byte_stream_server_proxy/byte_stream_server_proxy.go#L317)). Values from the outgoing context are therefore never translated to the incoming context, where this function expects to find them. Without this, I was seeing `Unexpected event "No auth headers found in context, did you remember to call authutil.StoreAuthHeadersInContext?"`

Fix auth context propagation in the proxy to internal grpc servers

---

tools/dev_qa.py

The previous script works with my local python version, but seeing an error in CI
https://github.com/buildbuddy-io/buildbuddy-internal/actions/runs/16328076055/job/46132295626

Fix dev_qa.py again

---

enterprise/server/raft/store/store.go

also add a column for isLeader which differs from HaveLease

add num staging and removed replicas into statusz

---

enterprise/server/raft/store/store.go

[raft] fix metrics bug with intermediate replicas

---

enterprise/app/executors/executor_card.tsx

render custom resource configuration on executors page

---

enterprise/server/backends/pebble_cache/pebble_cache.go
enterprise/server/cmd/ci_runner/main.go
enterprise/server/hostedrunner/BUILD
enterprise/server/hostedrunner/hostedrunner.go
enterprise/server/remote_execution/snaputil/snaputil.go
enterprise/server/workflow/service/BUILD
enterprise/server/workflow/service/service.go

[Example config](https://github.com/buildbuddy-io/buildbuddy-internal/pull/5408)

[SS] Support caching snapshots in a dedicated partition

---

enterprise/server/hostedrunner/hostedrunner.go
enterprise/server/workflow/service/service.go

To prepare for assigning certain group IDs to the baremetal workflow executor pool

[RB/WF] Read pool override from experiment service

---

enterprise/server/raft/store/BUILD
enterprise/server/raft/store/store.go
enterprise/server/raft/txn/txn.go
enterprise/server/raft/txn/txn_test.go

https://github.com/buildbuddy-io/buildbuddy-internal/issues/5402

[raft] make zombie janitor skip ranges in in-progress txn records

---

enterprise/server/raft/sender/sender.go

https://github.com/buildbuddy-io/buildbuddy-internal/issues/5441

[raft] set preferred replica in run multi key

---

server/util/clickhouse/clickhouse.go
server/util/db/BUILD
server/util/db/db.go
server/util/gormutil/BUILD
server/util/gormutil/gormutil.go

Move `sqlLogger` to gormutil and use it for ClickHouse.

Add clickhouse GORM logger to match primary DB logger

---

dockerfiles/rbe-ubuntu20-04/Dockerfile

Adds `parallel` command line utility to the image we use for workflows.

Add parallel to workflows image

---

cli/remotebazel/remotebazel.go

Context: https://buildbuddy-corp.slack.com/archives/C094HBMGR9P/p1754403502644819

Add invocation_id_file option to remote bazel

---

enterprise/server/remote_execution/container/container.go
enterprise/server/remote_execution/runner/runner.go
enterprise/server/remote_execution/runner/runner_test.go
enterprise/server/util/oci/BUILD
enterprise/server/util/oci/oci.go
go.mod
go_deps.MODULE.bazel

Reverts buildbuddy-io/buildbuddy#9974

Revert "[remote exec] resolve container image property to registry/repository@digest"

---

website/yarn.lock

Addresses https://github.com/buildbuddy-io/buildbuddy/security/dependabot/221

Update `compression` to update `on-headers` for dependabot

---

app/format/format.tsx
enterprise/app/executors/BUILD
enterprise/app/executors/executor_card.tsx
enterprise/app/executors/executors.tsx
enterprise/server/scheduling/priority_task_scheduler/priority_task_scheduler.go
enterprise/server/scheduling/scheduler_client/BUILD
enterprise/server/scheduling/scheduler_client/scheduler_client.go
enterprise/server/scheduling/scheduler_server/scheduler_server.go
proto/scheduler.proto

Add last check-in time and queue length to executors page

---

app/compare/BUILD
app/compare/compare_invocations.tsx
app/util/BUILD
app/util/diff.tsx

This will make it easier to use similar diff logic / views for action diffing as well

Pull some diff logic out into a util

---

app/format/format.tsx
enterprise/app/trends/trends_chart.tsx
enterprise/app/usage/usage.css
enterprise/app/usage/usage.tsx
enterprise/server/usage_service/BUILD
enterprise/server/usage_service/usage_service.go
proto/usage.proto

usage data broken down by category, eg:
usage charts with breakdowns, eg:

define a bunch of new fields for reporting usage.

---

enterprise/app/usage/usage.tsx

fix numbers that should be bools in react conditions

---

docs/enterprise-mac-rbe.md

https://buildbuddy-corp.slack.com/archives/C04S4M5U3BK/p1754958239428579

Clarify mac executor architecture download in docs

---

enterprise/tools/clickhouse_cluster/BUILD
enterprise/tools/clickhouse_cluster/clickhouse_cluster.go

Useful for messing around with risky ClickHouse stuff without worrying about wiping the dev DB.

Add tool for running clickhouse cluster locally

---

enterprise/server/workflow/config/config.go
enterprise/server/workflow/config/config_test.go

Context: https://buildbuddy-corp.slack.com/archives/C04S4M5U3BK/p1753921426820069

Support negation syntax for workflow branch triggers

---

enterprise/server/util/distributed_client/distributed_client.go
server/util/grpc_client/grpc_client.go

This is a safer version of https://github.com/buildbuddy-io/buildbuddy/pull/10076.

Decrease the pool size for distributed clients to 2

---

server/util/bazel/BUILD

Need the binaries to probe the probes!

add bazel 6.2.1, 8.2.1 to binaries tar (and base image)

---

enterprise/app/code/code_v2.tsx

Also use a click handler rather than a javascript: url since our xss policy doesn't like those

Show current path for single files if the url doesn't have a filename param

---

enterprise/server/raft/driver/BUILD
enterprise/server/raft/driver/driver.go
enterprise/server/raft/driver/driver_test.go
enterprise/server/raft/store/BUILD
enterprise/server/raft/store/store.go
enterprise/server/raft/store/store_test.go
enterprise/server/raft/testutil/testutil.go

- Add partition setup goroutine to store
- Add partition-level task support to driver
- add ReserveIDs to driver.IStore
- add a method to find nodes for allocation
- add InitializeShardsForPartition to store and driver interface
https://github.com/buildbuddy-io/buildbuddy-internal/issues/3607

[raft] initialize partitions in driver

---

enterprise/server/scheduling/priority_task_scheduler/priority_task_scheduler.go

Split out from https://github.com/buildbuddy-io/buildbuddy/pull/10109/files - wrapping up the resource counts as a collection (and defining some functions like Add / Clone etc.) makes some of the scheduling logic a bit simpler. This should purely be a refactor with no behavior change.

refactor: extract resourceCounts struct

---

enterprise/server/cmd/executor/executor.go
server/util/grpc_client/grpc_client.go

- Move info log before dialing
- Add debug logs after dial is complete
- Add debug logs around NewDefaultCredentials()

Add more logging around cache dialing

---

enterprise/server/remote_execution/commandutil/commandutil_unix.go
enterprise/server/remote_execution/containers/firecracker/firecracker_test.go

This command works with OCI isolation type:
```
$ bb execute --exec_properties=dockerUser=1001 -- id
uid=1001 gid=0(root) groups=0(root)
```
As expected, this matches the behavior of `docker run`:
```
$ docker run --user=1001 gcr.io/flame-public/rbe-ubuntu22-04 id
uid=1001 gid=0(root) groups=0(root)
```
However on firecracker, it unexpectedly results in a uid lookup error:
```
$ bb execute --exec_properties=dockerUser=1001 --exec_properties=workload-isolation-type=firecracker --remote_header=x-buildbuddy-api-key=${BB_API_KEY?} -- id
failed to receive from stream: uid lookup failed: user: unknown userid 1001
```
This is unexpected because we mostly want firecracker to be a drop-in replacement for docker/podman/OCI isolation types.
I ran into this trying to set a numeric `dockerUser` on a …

Fix firecracker not respecting numeric dockerUser

---

enterprise/server/scheduling/scheduler_server/scheduler_server.go

Currently, the `clients` map uses non-pointer values, so `client.lastAccess = time.Now()` doesn't change any values in the map. This means, that every iteration inside `startExpirer` expires every connection.
Change the values to pointers instead.

Don't expire every scheduler client every minute

---

tools/metrics/grafana/provisioning/deploy/datasources/datasources.yml

- Don't hard-code "dev"
- Remove tracing config from main DB (this is only needed for the OTEL DB)

Fix clickhouse grafana datasource

---

.github/actions/cache-save/action.yml
enterprise/app/esbuild.config.mjs
tools/lint/lint.go
website/blog/whats-new-in-bazel-7-0.mdx

Add .mjs, .mts (JS/TS modules) .cjs, .cts (commonjs / TS), .yml (YAML), .mdx (JSX markdown)

Add a few more file extensions to be formatted by prettier

---

enterprise/server/util/oci/oci.go
enterprise/server/util/oci/oci_test.go

Now that these are fully rolled out, hard-code the logic as if they are set to true, but keep them defined (will clean up the YAML configs after this change rolls out)
Work towards https://github.com/buildbuddy-io/buildbuddy/pull/10199/files (I'm hitting some test failures - this should make the tests a little easier to debug)

Clean up individual OCI cache flags

---

app/invocation/BUILD
app/invocation/action_compare_button.tsx
app/invocation/invocation.css
app/invocation/invocation_execution_table.tsx
app/invocation/invocation_spawn_card.tsx

Added this to invocations, adding it to executions table too:
Also added it to spawns list.

Add mini compare button to executions table

---

enterprise/server/raft/bringup/bringup.go
enterprise/server/raft/sender/sender.go
enterprise/server/raft/store/store.go
enterprise/server/raft/store/store_test.go
server/util/disk/disk.go

- add soft_deleted to disk.Partition
- When the configured partition is soft deleted, marked the partition descriptor
as soft deleted

[raft] soft delete for partitions

---

enterprise/server/backends/migration_cache/migration_cache.go

Currently, we spend a bunch 4% of CPU time decompressing and compressing these copies.

Make migration background copies read/write compressed data

---

enterprise/server/raft/store/store.go
enterprise/server/raft/store/store_test.go

add retry loops in tests to handle lease invalid error.

[raft] check HaveLease in SplitRange, AddReplica and RemoveReplica

---

enterprise/server/backends/authdb/BUILD
enterprise/server/backends/userdb/userdb.go
enterprise/server/backends/userdb/userdb_test.go
server/interfaces/interfaces.go
server/tables/BUILD
server/tables/tables.go
server/util/db/db_cgo.go

User lists are simple collections of users that may be made members of an organization with an associated role.

Schema for "user lists" (aka groups).

---

enterprise/server/raft/store/store.go
proto/raft.proto
proto/raft_service.proto

These are to be used to fix range descriptor / partition descriptors.

[raft] Add RPCs to update range and partition descriptors

---

app/invocation/invocation.css
app/invocation/invocation_spawn_card.tsx

Add platform property filtering to `Spawns` tab

---

.github/workflows/release-cli.yaml

Also adds `--compilation_mode=opt`

Build cli statically

---

enterprise/tools/replay_action/replay_action.go

In particular, make sure we respect the `x-buildbuddy-experiment.group_id` header since the `group_id` in the experiment context affects the cache partition.
This fixes a bug where `replay_action` would appear to successfully upload an input, but then the executor would fail to download the input (because the uploaded partition and downloaded partition don't match)

Fix copyTree not respecting target_headers flag

---

enterprise/server/test/integration/remote_execution/docker_rbe/BUILD
enterprise/server/test/integration/remote_execution/docker_rbe/docker_rbe_test.go

This hit an auth error when trying to pull busybox.

Deflake docker_rbe_test

---

enterprise/server/backends/userdb/userdb.go

This is the same as https://github.com/buildbuddy-io/buildbuddy/pull/10265
I'm consolidating the two queries and sending this out to minimize unrelated diffs.

Simplify query in userdb.getUser

---

enterprise/server/crypter_key_cache/BUILD
enterprise/server/crypter_key_cache/crypter_key_cache.go
enterprise/server/crypter_key_cache/crypter_key_cache_test.go
enterprise/server/crypter_service/BUILD
enterprise/server/crypter_service/crypter_service.go
enterprise/server/crypter_service/crypter_service_test.go

Related Issues: https://github.com/buildbuddy-io/buildbuddy-internal/issues/4758

Pull local encryption key caching logic out of crypter_service for reuse

---

WORKSPACE
deps/toolchains.MODULE.bazel

Reverts buildbuddy-io/buildbuddy#10419

Revert "Upgrade node to 20"

---

enterprise/server/cmd/executor/BUILD
enterprise/server/cmd/server/BUILD
rules/utils.bzl
server/cmd/buildbuddy/BUILD

It differs depending on the main repo.

Don't incorrectly hardcode the runfiles directory name

---

tools/metrics/grafana/dashboards/buildbuddy.json

This was introduced in https://github.com/buildbuddy-io/buildbuddy/pull/10402

Fix typo in dashboard graph query

---

enterprise/server/raft/bringup/bringup.go
enterprise/server/raft/driver/driver.go
enterprise/server/raft/metadata/metadata.go
enterprise/server/raft/nodeliveness/nodeliveness.go
enterprise/server/raft/rangelease/rangelease.go
enterprise/server/raft/replica/replica.go
enterprise/server/raft/sender/sender.go
enterprise/server/raft/store/store.go
enterprise/server/raft/txn/txn.go
enterprise/server/raft/usagetracker/usagetracker.go

This is to prepare for the following PRs where I will use errors.Is check
instead of "==" or strings.Contains to check errors.
https://github.com/buildbuddy-io/buildbuddy-internal/issues/5752

preserve errors.Is check when we wrap or create errors in raft.

---

deps/toolchains.MODULE.bazel
go.mod

https://github.com/golang/go/issues?q=milestone%3AGo1.25.1+label%3ACherryPickApproved
https://github.com/golang/go/issues?q=milestone%3AGo1.25.2+label%3ACherryPickApproved

gosdk: upgrade to 1.25.2
