buildbuddy-io/buildbuddy

tools/metrics/grafana/dashboards/cache-proxy.json

This updates the dashboard to reference the new metric names from https://github.com/buildbuddy-io/buildbuddy/pull/8293 and adds new graphs for proxied digests and proxied bytes.

Update Cache Proxy dashboard to include graphs for proxied byte metrics

---

enterprise/app/history/history.tsx
enterprise/app/org/org.css
enterprise/app/org/org_join_requests.tsx
enterprise/app/settings/BUILD
enterprise/app/settings/settings.tsx

We currently only show org join requests on the Users page, which is a common source of confusion.
With this change, they will also appear on the Org members page on the settings tab.

Show org join requests on member page

---

cli/cmd/sidecar/sidecar.go
server/util/grpc_server/grpc_server.go

The go default value is [5 min](https://github.com/grpc/grpc-go/blob/v1.70.0/keepalive/keepalive.go#L94) - but we often recommend users configure Bazel's --[grpc_keepalive_time](https://bazel.build/reference/command-line-reference#flag--grpc_keepalive_time)=30s flag.
Our servers already set this to 10s, but this change updates the cli's sidecar to also use 10s.

Configure grpc keepalive enforcement policy for the cli sidecar

---

MODULE.bazel
WORKSPACE
go.mod

> go1.23.5 (released 2025-01-16) includes security fixes to the crypto/x509 and
> net/http packages, as well as bug fixes to the compiler, the runtime, and the
> net package. See the Go 1.23.5 milestone on our issue tracker for details.
https://github.com/golang/go/issues?q=milestone%3AGo1.23.5+label%3ACherryPickApproved
> go1.23.6 (released 2025-02-04) includes security fixes to the crypto/elliptic
> package, as well as bug fixes to the compiler and the go command. See the Go
> 1.23.6 milestone on our issue tracker for details.
https://github.com/golang/go/issues?q=milestone%3AGo1.23.6+label%3ACherryPickApproved

chore: Update Go SDK to 1.23.6

---

enterprise/server/cmd/ci_runner/main.go

This ensures "git gc --auto" runs in the foreground, preventing
snapshots of the microvm while it's running and avoiding potential
interference.

ci_runner: set git gc.autoDetach to false

---

enterprise/server/remote_execution/containers/firecracker/firecracker_test.go

All of these are specified in the test target

Remove unnecessary flags from firecracker_test.go

---

enterprise/server/remote_execution/containers/firecracker/firecracker.go
server/metrics/metrics.go

Dialing is significantly faster when loading a snapshot, so this will make that difference more clear.

Add a "from_snapshot" dimension to the exec_dial_duration metric

---

enterprise/server/ociregistry/BUILD
enterprise/server/util/oci/BUILD
enterprise/server/util/oci/oci.go
enterprise/server/util/oci/oci_test.go

The OCI registry mirror under `enterprise/server/ociregistry` can only serve manifests and pulls for public registries. Mirroring private registries is not supported.
Configuring a mirror works at the domain level. So, for example, mirroring `gcr.io` will cause all requests that would to go `gcr.io` to go to the mirror. While rolling out the OCI registry mirror, I do not want to break image pulls from an entire domain!
So, this change causes `oci.Resolve()` to fall back to the original registry domain if the mirror returns a non-2XX HTTP status code. I've added a test to make sure `oci.Resolve()` does indeed fall back.

Fall back to original registry if mirror cannot serve request

---

enterprise/server/cmd/goinit/main.go
enterprise/server/remote_execution/containers/firecracker/firecracker_test.go

This will help me understand why goinit takes a few hundred milliseconds to start up.

Add a few more debug logs in goinit

---

enterprise/server/remote_execution/containers/firecracker/BUILD
enterprise/server/remote_execution/containers/firecracker/README.md

The old flag doesn't exist any more, and these are useful for understanding what broke in a failing test.

Update debug logging flags in firecracker/README

---

enterprise/server/scheduling/priority_task_scheduler/BUILD
enterprise/server/scheduling/priority_task_scheduler/priority_task_scheduler.go
enterprise/server/scheduling/scheduler_server/scheduler_server.go
enterprise/server/scheduling/scheduler_server/scheduler_server_test.go
proto/scheduler.proto
server/interfaces/interfaces.go

currently, we don't prune tasks from executor queues until we're actually taking on new work.  when we're under load, this means some executors can have artificially long "queues" of tasks that have already been finished by other executors.
this change works around this case by periodically checking if the frontmost entry in the task queue has already been finished by another worker (indicated by the record not existing in redis anymore).  when such an entry is found, the worker will continue picking entries off the front of the queue until it's either empty or finds a task that hasn't been completed yet.  this should help us scale up more efficiently.
as a toy example: if we have an average queue length of 20, scale up when the average queue length is >5, and all of our tasks take 20 …

periodically trim already-finished tasks from front of the executor queue.

---

enterprise/server/scheduling/priority_task_scheduler/priority_task_scheduler.go

This doesn't actually change the correctness afaict, just lets us avoid an extra TaskExistsRequest

Fix typo in trimQueue

---

cli/remotebazel/remotebazel.go
docs/remote-bazel-introduction.md

Extracted CLI code from https://github.com/buildbuddy-io/buildbuddy/pull/8172
This PR disables automatic retries when using the remote bazel CLI. The CLI then implements retry behavior itself so it can detect when a retry is happening
This fixes a bug where if the remote run fails due to a transient error, the CLI will report a failure. However the scheduler may retry the run in the background and it may eventually succeed. When users go to the invocation link, they'll see that it succeeded despite expecting a failure
Slack thread (Issue 2): https://buildbuddy-corp.slack.com/archives/C07GMM2VBLY/p1734595804049229?thread_ts=1734595606.837269&cid=C07GMM2VBLY
Should be merged after https://github.com/buildbuddy-io/buildbuddy/pull/8172 is rolled out

[RB] Handle retries in the CLI rather than server-side

---

enterprise/server/remote_execution/containers/firecracker/firecracker_performance_test.go

Also set `--bazelrc=/dev/null` so that incompatible flags aren't used.

Update bazel version in firecracker_performance_test

---

enterprise/server/remote_execution/containers/ociruntime/ociruntime.go
enterprise/server/remote_execution/containers/ociruntime/ociruntime_test.go

Also return a non-retryable error.

Add tests for layer entry path validation

---

enterprise/server/cmd/executor/executor.go
enterprise/server/remote_execution/containers/firecracker/BUILD
enterprise/server/remote_execution/containers/firecracker/firecracker.go
enterprise/server/remote_execution/containers/firecracker/firecracker_test.go
enterprise/server/remote_execution/runner/runner.go
enterprise/server/remote_execution/snaploader/snaploader.go
enterprise/server/remote_execution/snaputil/snaputil.go
enterprise/server/remote_execution/uffd/uffd.go

Many of these features only work in tandem, so eliminate some of the snapshot related flags. Only keep `enable_remote_snapshot_sharing` and `enable_local_snapshot_sharing`.
Also cleanup some debug logging in uffd.go

[SS] Cleanup flags and debug data

---

server/util/networking/BUILD
server/util/networking/networking.go
server/util/networking/networking_test.go

Context: https://buildbuddy-corp.slack.com/archives/C01D5GHRJ59/p1739204423929709?thread_ts=1738948035.930359&cid=C01D5GHRJ59
The new INPUT rule breaks testing connections between actions and locally running servers.

Add flag to allow a subset of private IPs

---

enterprise/server/workflow/config/config.go
enterprise/server/workflow/service/service.go

Allow setting workflow action priorities, using the same semantics as the `--remote_execution_priority` flag in bazel (priority only applies within an org, not across orgs)

Add priority field to workflow action config

---

enterprise/server/remote_execution/executor/executor.go

I copied the error message `DEADLINE_EXCEEDED: deadline exceeeded` from the UI and couldn't find any results, later realized it was because of the three `e` in `exceeeded`.

fix: error log typo

---

enterprise/server/raft/replica/BUILD
enterprise/server/raft/replica/replica.go
enterprise/server/raft/replica/replica_test.go

This should preventing raft panicking when there is an update error.
https://github.com/buildbuddy-io/buildbuddy-internal/issues/4141

[raft] set error in Entry instead of returning it directly

---

enterprise/server/scheduling/scheduler_client/scheduler_client.go
enterprise/server/scheduling/scheduler_server/scheduler_server.go
proto/scheduler.proto

When enabled, the executor will ask the scheduler to send a message back whenever it receives a registration request. If the executor does not hear back within the specified deadline then the executor will establish a new registration stream.
https://github.com/buildbuddy-io/buildbuddy-internal/issues/4404

Add a mechanism for executors to detect registration issues.

---

proto/BUILD
proto/storage.proto

I plan to split up the raft.proto before introducing some metadata-only messages.

Refactor(rfpb): Copy non-raft messages to storage proto

---

app/invocation/BUILD
app/invocation/cache_requests_card.tsx

This avoids unnecessary Bazel invocations if the builds had the execution log uploaded.

ui: Use existing exec logs for "compare" Bazel button

---

enterprise/server/remote_execution/containers/firecracker/BUILD
enterprise/server/remote_execution/containers/firecracker/firecracker_test.go

I'm targeting the `dockerd`-running-in-Firecracker path as the best starting place for the caching OCI registry mirror. Before rolling out the OCI registry mirror to dev and prod, I want to make sure that path works!
This change tests 3 cases:
1. Pulling an image name that includes the registry mirror address.
2. Pulling the vanilla image name.
3. Having the registry mirror respond 404 to requests for the manifest, forcing `docker` to fall back to Docker Hub.
To build confidence that the tests actually pull from the mirror, I count the requests that go to the mirror. It would be fantastic if the OCI image itself could tell you where the bytes come from, but I have not found a way of doing that. Suggestions welcome!

Test pulling from OCI registry mirror using `docker` in Firecracker VM

---

enterprise/server/remote_execution/containers/firecracker/firecracker.go

This is similar to https://github.com/buildbuddy-io/buildbuddy/pull/8296, but also works when loading from a snapshot, and not just when creating a new machine. It seems that the Initialize() call can be delayed without breaking anything.

Delay dialing the vm exec server when we load a snapshot

---

enterprise/server/remote_execution/snaploader/snaploader.go
enterprise/server/remote_execution/snaputil/BUILD
enterprise/server/remote_execution/snaputil/snaputil.go
enterprise/server/remote_execution/snaputil/snaputil_test.go
server/metrics/metrics.go

This [graph](https://metrics.buildbuddy.io/d/KI6NxDWSk/workflow-snapshotting?orgId=1&refresh=1m&viewPanel=14) provides a misleading view of how much snapshot data we're writing to the remote cache, because it tracks non-compressed data and doesn't account for data that already exists in the cache.
Add file name to the metric that tracks compressed data that is actually written to the cache

[SS] Add file name to metric for compressed bytes uploaded for snapshots

---

server/remote_asset/fetch_server/fetch_server.go
server/remote_asset/fetch_server/fetch_server_test.go

While not strictly required for interoperability with Bazel, this improves our spec compliance.

remote_asset: Always set `uri` and `digest_function` fields

---

enterprise/config/executor.workflow.yaml

When running RBE locally, this allows remote bazel to hit the locally running app.

Set task_allowed_private_ips=default in executor.workflow.yaml

---

cli/explain/explain.go
cli/storage/BUILD
cli/storage/storage.go
cli/storage/storage_test.go

This is based on extending `storage` to persist an arbitrary number of values per flag.
Example:
```shell
$ bb build //cli --config=remote
$ # modify cli/storage/storage.go
$ bb build //cli --config=remote
$ bb explain
RunNogo //cli/storage:storage (bazel-out/platform_linux_x86_64-fastbuild/bin/cli/storage/storage.facts)
inputs changed:
cli/storage/storage.go: content changed
GoCompilePkg //cli/storage:storage (bazel-out/platform_linux_x86_64-fastbuild/bin/cli/storage/storage.a)
inputs changed:
cli/storage/storage.go: content changed
transitively invalidated:
10 GoCompilePkg
10 RunNogo
1 GoLink
```

explain: Let `--old` default to the build before the last one

---

enterprise/server/remote_execution/containers/firecracker/firecracker.go
enterprise/tools/vmstart/BUILD
enterprise/tools/vmstart/vmstart.go

Also add a `--debug_disable_cgroup` flag since we don't support cgroup v1 and the GCP VMs we're using for testing have a weird hybrid cgroup setup

Fix vmstart

---

enterprise/server/scheduling/scheduler_server/scheduler_server.go

We can treat these enqueues as best-effort. 
This also applies to newly connected executors being assigned the initial batch of work. 
https://github.com/buildbuddy-io/buildbuddy-internal/issues/4404

Don't wait for enqueue response when enqueing extra work on idle executors.

---

enterprise/server/scheduling/scheduler_server/scheduler_server.go
enterprise/server/test/integration/remote_execution/BUILD
enterprise/server/test/integration/remote_execution/rbetest/rbetest.go
enterprise/server/test/integration/remote_execution/remote_execution_test.go

Custom resource requests were being dropped if a measured or predicted size is available.

Fix custom resources not being respected

---

app/invocation/invocation.css
enterprise/app/org/join_org.tsx
enterprise/app/org/org_access_denied.tsx

Currently if you get served the "Access denied page" because you visited an invocation you don't have access to, it's very unclear what options you have / what next step you should take.
This change makes your options clearer / more actionable by adding two buttons:
- Request to join organization
- Switch accounts
Which allows users to either request access to the organization (pending admin approval) or switch accounts where they can login to a different account that may have access to this invocation.

Add join and switch accounts buttons to the access denied page

---

cli/remotebazel/remotebazel.go

By default, when specifying a snapshot key to start from, we don't save changes back to that snapshot to avoid changing it.
If users do want to save new changes to that snapshot key, they can pass `--runner_exec_properties=recycle-runner=true`. This PR fixes a bug to enable that behavior

[RB] When starting from a snapshot key, allow users to save to the snapshot

---

enterprise/server/raft/client/client.go
enterprise/server/raft/driver/driver.go
enterprise/server/raft/replica/replica.go
enterprise/server/raft/sender/sender.go
server/gossip/gossip.go

- Fully remove the debugging logs for investigating session mismatch index
- Remove EventMemberUpdate serf log
- Add range id into "should not queue" messages
- In sender.TryReplicas, only log when TryReplicas failed.  Log all debugging
messages at once so we can have a better idea of what's going on.

[raft] clean up some logs

---

server/remote_cache/byte_stream_client/byte_stream_client.go

When bytestream dialing is restricted, we'll only dial our own endpoints which are always grpcs.

Don't fallback to grpc if bytestream dialing is restricted

---

enterprise/server/raft/client/BUILD
enterprise/server/raft/client/client.go
enterprise/server/raft/replica/replica.go
server/gossip/gossip.go

1. remove some serf logs that I never looked at during debugging
2. remove canary call on node.SyncPropose and replica.Update now that we report
metrics on the latency.

[raft] remove some logs

---

MODULE.bazel
WORKSPACE
WORKSPACE.bzlmod
deps.bzl
go.mod
go.sum
rules/webdriver/index.bzl
server/testutil/webtester/BUILD

Upgrade rules_webtesting to latest commit.
The repo has been updated to be bzlmod compatible so we have to rename
it to remove the io_bazel_ prefix. Moved the setup from WORKSPACE.bzlmod
into MODULE.bazel.
Upgrade our browser repository from 0.3.3 to 0.3.4.

rules_webtesting: upgrade to latest commit

---

buildfix.sh

No that we have goimports, gofmt is redundant

refactor: Remove gofmt from buildfix.sh

---

enterprise/server/cmd/goinit/main.go
enterprise/server/remote_execution/containers/firecracker/BUILD
enterprise/server/remote_execution/containers/firecracker/firecracker.go
enterprise/server/remote_execution/containers/firecracker/firecracker_test.go

We'd like to be able to have `dockerd` running inside a Firecracker VM be able to pull images from registry mirrors (and, for tests, be able to pull from insecure registries).
This change introduces `executor.firecracker_vm_docker_mirrors` and `executor.firecracker_vm_docker_insecure_registries` flags. When either is set, the host machine writes their values as JSON and passes that JSON to the VM over the [microVM Metadata Service](https://github.com/firecracker-microvm/firecracker/blob/main/docs/mmds/mmds-user-guide.md), also known as the Firecracker Metadata API or MMDS.
This change bumps the Firecracker guest API version. I'm not sure if that bump is strictly necessary or warranted.

pass docker registry mirror info from executor to guest vm via MMDS

---

enterprise/server/remote_execution/platform/platform.go
enterprise/server/remote_execution/runner/runner.go

Proper recycling support is not yet implemented and firecracker performance is not good enough yet.

Disable VFS for unsupported configurations.

---

enterprise/server/remote_execution/cgroup/cgroup.go
enterprise/server/remote_execution/containers/ociruntime/BUILD
enterprise/server/remote_execution/containers/ociruntime/ociruntime.go
enterprise/server/remote_execution/containers/ociruntime/ociruntime_test.go
enterprise/server/tasksize/tasksize.go
enterprise/server/tasksize/tasksize_test.go

Partially addresses https://github.com/buildbuddy-io/buildbuddy-internal/issues/4435
Before, if a subprocess within a test is OOM-killed, the test may continue execution and possibly fail with a non-zero exit code + OK gRPC status.
This behavior is not ideal for a few different reasons:
- It results in confusing errors - the user has to dig through test logs and look for possible hints that there may have been an OOM such as a "signal: killed" error, and even then it's not obvious whether the SIGKILL came from the OOM killer or something else on the system.
- It wastes time - the test may chug along running other test cases, only to then fail because of the OOM kill in an earlier test case.
- It causes unnecessary failures - if the OOM error was really our fault (because of …

Return a retryable error and short-circuit execution when any subprocess is OOM-killed

---

enterprise/server/scheduling/scheduler_server/BUILD
enterprise/server/scheduling/scheduler_server/scheduler_server.go
enterprise/server/scheduling/scheduler_server/scheduler_server_test.go

Fixes an issue where `assignWorkToNode` results in indefinite queue buildup if a task can't fit on some executors in the pool.
Context: https://buildbuddy-corp.slack.com/archives/C06DBLTGC2V/p1739598075814869

Filter sampled tasks to ones that fit on the node

---

enterprise/server/remote_execution/uffd/uffd.go

To make my balloon PR easier to review, refactor the UFFD code to prepare for balloon-related changes. The major change in this PR is that rather than {read page fault event, resolve page fault event} in a loop, we will {read all available page fault events, resolve all page faults} in a loop. This behavior is required to handle balloon events (comments coming in a future PR) but should be a no-op for now

[SS] Refactor UFFD to prepare for balloon

---

.bazelrc

The platform definition in //platforms was removed in an earlier PR.
Replace it with Bazel's default platform

bazelrc: fix config=local exec platform

---

enterprise/server/scheduling/priority_task_scheduler/priority_task_scheduler.go

Fixes a busy loop issue when `executor.queue_trim_interval` is enabled (>0), since `trimQueue` returns false when nothing was trimmed, which is the case most of the time.
Reproduced the busy loop issue locally and confirmed that this fixes it.

Fix queue pruning loop condition

---

enterprise/server/backends/distributed/distributed.go
enterprise/server/remote_execution/copy_on_write/copy_on_write.go
enterprise/server/remote_execution/filecache/filecache.go
server/backends/disk_cache/disk_cache.go
server/interfaces/interfaces.go
server/util/lru/lru.go
server/util/lru/lru_test.go

This will allow the filecache LRU to have smaller values.
I also removed the LRU.Purge method, since it's never used.

Make the LRU OnEvict callback accept the key as well.

---

enterprise/server/remote_execution/containers/firecracker/firecracker.go

Initial attempt at fixing the `network_cleanup_failed` errors. A lot of these are failing with "deadline exceeded," so try extending the deadline by a few seconds.
We are also seeing some of the `iptables` commands fail with `signal: killed` but I'm not sure if this is the same error (because `CommandContext` is implemented by sending SIGKILL when the context deadline expires) or if this is an OOM-kill. Will look into this separately.

Extend deadline for networking cleanup

---

enterprise/server/scheduling/priority_task_scheduler/priority_task_scheduler.go
enterprise/server/scheduling/priority_task_scheduler/priority_task_scheduler_test.go

While working on a different issue, I noticed locally that while an executor was eagerly requesting work during idle periods, the queue length kept going up. This was surprising because I had enqueued a fixed set of 100 tasks, but the queue length climbed to over 200.
The issue was that although the executor was under the `excess_capacity_threshold` on CPU and RAM, it was fully utilized on custom resources (`gpu`), because all of the tasks in the queue were requesting 100% of `gpu` resources. So the executor kept requesting more work, and because we don't dedupe tasks, this drove up the queue length. To address this specific case, we could incorporate custom resources into the excess capacity threshold.
But I think the queue can still build up with duplicate tasks in other cases, too. For …

Dedupe task reservations

---

enterprise/server/remote_execution/filecache/filecache.go
enterprise/server/remote_execution/filecache/filecache_test.go

Since the LRU now has string keys, we can use those to get the filecache paths, instead of storing the path in the LRU value.
I also simplified the benchmark and made it monitor retained memory usage.
This reduces memory usage by 25% compared to the previous version of the LRU (with hashed keys), and by 33% compared to the current LRU (with string keys). It also speeds it up a bit and reduces allocations.
```
goos: linux
goarch: amd64
│ /tmp/baseline │          /tmp/simplekeys           │         /tmp/nopathinvalue         │
│    sec/op     │   sec/op     vs base               │   sec/op     vs base               │
ContainsAdd/1K/10G-24     642.8µ ± 2%   616.4µ ± 3%  -4.11% (p=0.000 n=50)   605.5µ ± 2%  -5.80% (p=0.000 n=50)
ContainsAdd/1K/1M-24 …
```

Reduce memory usage of the filecache 

---

enterprise/server/cmd/executor/executor_linux.go
enterprise/server/remote_execution/cgroup/cgroup.go
enterprise/server/remote_execution/containers/ociruntime/ociruntime.go

Fix lxcfs cpuinfo not respecting cpuset when `executor.child_cgroups_enabled` is set.
On initialization, lxcfs looks up the current cgroup for pid 1 (in the current pid namespace) and makes an assumption that this cgroup's controllers will be the same controllers that are enabled for all child cgroups: https://github.com/lxc/lxcfs/blob/42b57f265a31261a0b69dc1f040cbcfe58a9c6a1/src/cgroups/cgfsng.c#L1036-L1054
So to make lxcfs happy, we need to enable cgroup controllers in the executor cgroup before starting lxcfs.
The fact that we aren't explicitly enabling cgroup controllers in the child cgroups made me wonder whether cgroups were working at all. After some experimentation, it seems that these cgroup controllers are only getting enabled because crun automatically enables them for us …

Fix lxcfs cpuinfo

---

.github/workflows/main.yaml

Our go_repository repos are download by @bazel_gazelle//cmd/fetch_repo
which does not use Bazel's repo cache but a local temporary directory.
Setting the variable GO_REPOSITORY_USE_HOST_CACHE=1 tells go_repository
downloads to respect either GOPATH or GOMODCACHE (usually a sub dir of
GOPATH) environment variables to cache the download contents.
Set the cache key to files which may invalidate the cache to make sure
we always use a fresh download cache when updating external
dependencies.

github/workflows: cache go module downloads

---

enterprise/server/raft/leasekeeper/leasekeeper.go
server/metrics/metrics.go

To make it easy to spot abnomalies when acquire leases. For example, there is an
instance where it took 16s to acquire lease while I was examining logs.

[raft] add metrics for lease action latency

---

cli/remotebazel/remotebazel.go
enterprise/server/remote_execution/containers/firecracker/firecracker.go

There have been cases where I want to start from a snapshot and make some changes, but not change the original snapshot if I ever need to go back and reference it. It would still be nice to save the changed snapshot though

[RB] When starting from a snapshot, write to a different snapshot ID

---

enterprise/server/atime_updater/BUILD
enterprise/server/atime_updater/atime_updater.go
enterprise/server/atime_updater/atime_updater_test.go
enterprise/server/byte_stream_server_proxy/BUILD
enterprise/server/byte_stream_server_proxy/byte_stream_server_proxy_test.go
enterprise/server/content_addressable_storage_server_proxy/BUILD
enterprise/server/content_addressable_storage_server_proxy/content_addressable_storage_server_proxy_test.go

Without this, async atime updates are rejected for organizations with IP rules enabled.

[Cache Proxy] preserve client-identity header in async atime updates

---

enterprise/server/cmd/goinit/main.go
enterprise/server/remote_execution/containers/firecracker/firecracker_test.go

VM exec server will wait for dockerd to be started either way, but this lets VM exec start a bit earlier, which could reduce the latency for dialing VM exec from the host.

In goinit, start dockerd in parallel with vmexec server

---

deps.bzl

The executors need to first be running the patched version of firecracker, or the balloon-related tests from this [PR](https://github.com/buildbuddy-io/buildbuddy/pull/8460/files) will all fail when it is merged. To keep CI happy, upgrade firecracker first

[SS] Use patched version of FC to support balloon

---

enterprise/server/cmd/executor/executor.go

pre-work for switching to a different way of mounting /dev/kvm in containers

check that /dev/kvm exists when firecracker is enabled

---

enterprise/server/raft/replica/BUILD
enterprise/server/raft/replica/replica.go
server/util/qps/BUILD
server/util/qps/qps.go
server/util/qps/qps_test.go
tools/cacheload/BUILD
tools/cacheload/cacheload.go

I would like to use a similar time-binning ring buffer to track error rates for performing failover in a new gRPC client. This is the first step towards extracting the time-binning logic into a different place where it can be reused.

Add a test for qps.go

---

server/gossip/BUILD
server/gossip/gossip.go
server/util/log/log.go

Serf Logs are noisy. When I am testing raft, I have main log level set to debug,
but I want to have serf logs at warning levels.
Created a new flag gossip.log_level to control serf log level.
Added a Level() call to log.Logger

Have a seperate log level for serf log

---

cli/remotebazel/remotebazel.go
enterprise/server/scheduling/scheduler_server/scheduler_server.go

Fixes https://github.com/buildbuddy-io/buildbuddy-internal/issues/4494#event-16433445516
Also remove `Not re-enqueuing.` message from the error returned by the scheduler, because it can be confusing when the CLI does retry the run

[RB] Fix retry behavior in CLI

---

enterprise/server/remote_execution/vfs/vfs_test.go
enterprise/server/util/vfs_server/vfs_server.go

The backing path is used to indicate whether the vfs node is backed by a real directory/file in the scratch directory.
When creating parent directories, we were only setting the backing path for the immediate parent even if we created multiple levels of directories.

Set "backing path" for all parent directories.

---

enterprise/server/raft/client/BUILD
enterprise/server/raft/client/client.go

One trace during rollout shows that "TryReplica: fn" started 3.2 seconds after "TryReplica" started indicating `client.GetForReplica` is slow.

[raft] add spn for getForClient

---

enterprise/server/raft/client/client.go
enterprise/server/raft/registry/registry.go
enterprise/server/raft/registry/registry_test.go
enterprise/server/raft/store/store.go
enterprise/server/raft/store/store_test.go

prepare for the following PR to add trace into registry
We see traces where GetForReplica is slow, indicating queryPeers are slow.

[raft] refactor: add context to registry

---

enterprise/server/remote_execution/containers/firecracker/firecracker.go

I'm pretty sure this fixes the goroutine leak, since Remove is called even when Pause isn't. I thought about moving it to just inside Remove(), but there are situations where Pause can fail and Remove is never run

Close the vmexec connection in Remove as well

---

deps.bzl
go.mod
go.sum

Change log:
https://github.com/cockroachdb/pebble/compare/v1.1.1...v1.1.4
Relatively small and short upgrade.
Should help us some-what when we want to upgrade to 2.x

go.mod: Update cockroachdb/pebble to v1.1.4

---

enterprise/server/remote_execution/containers/firecracker/firecracker.go

The balloon won't allocate memory from the page cache, so explicitly drop the cache before trying to reclaim memory with the balloon ([verified that behavior in this thread](https://lore.kernel.org/all/CAJuQAmpDUyve2S+oxp9tLUhuRcnddXnNztC5PmYOOCpY6c68xg@mail.gmail.com/))
Also: 
* pull available memory from the balloon stats, instead of trying to parse it from bash output
* loosen early exit logic for balloon inflation. In my testing there were some cases where there might be a slight delay in balloon inflation, but then it speeds up
From my testing, dropping the page cache didn't seem to have a significant impact on workflow execution performance. In my tests, I: 
A) Ran a build on a clean VM. This filled up the page cache
B) Started from the snapshot (with the page cache) and ran a fully …

[SS] Drop the page cache before inflating the balloon

---

server/metrics/metrics.go
server/util/networking/BUILD
server/util/networking/networking.go

Add duration and CPU usage metrics for networking commands

---

enterprise/server/remote_execution/containers/firecracker/BUILD
enterprise/server/remote_execution/containers/firecracker/firecracker.go

After understanding this code a bit more, I don't think we need to worry about concurrent callers to vmExecConn().
With the existing code, the race detector complains because `singleflight.Do` creates a goroutine which will write to `c.vmExec.conn`, while `c.Remove` might read from that field. The race detector has no way of proving that `Remove()` won't be called until `vmExecConn()` returns. Getting rid of singleflight actually removes this "race".
This was only [failing in tests](https://buildbuddy.buildbuddy.dev/invocation/3d08e9e7-de8b-4983-bdf3-6f507ac77ce1?target=%2F%2Fenterprise%2Fserver%2Fremote_execution%2Fcontainers%2Ffirecracker%3Afirecracker_test&targetStatus=6#@95).
I couldn't reproduce it, even with `bazel test //enterprise/server/remote_execution/containers/firecracker:fire …

Fix test data race from closing vm exec server

---

.bazelrc

When a top-level artifact was produced by a BwoB build, Bazel will download it even with `--remote_download_minimal` after the period specified by `--experimental_remote_cache_ttl` has passed (assuming that the Bazel server is still running). This is unexpected as only the metadata should be refreshed (i.e., a find missing blobs request should be sent).
While we wait for the Bazel fix (https://github.com/bazelbuild/bazel/pull/25398), set this to a high value to work around the issue. This could negatively impact the handling of remote cache evictions.

Speculative fix for top-level artifact downloads despite BwoB

---

enterprise/server/backends/pebble_cache/pebble_cache.go
enterprise/server/util/pebble/BUILD
enterprise/server/util/pebble/pebble.go
enterprise/server/util/pebble/pebble_test.go

PebbleDB comes with multiple on-disk format versions(0). If we don't
specify a FormatMajorVersion inside pebble.Options when we initialize
the DB, the default format is FormatMostCompatible, the second-oldest
version available.
To prepare for a future upgrade to PebbleV2(1), we want to upgrade all
DBs to the latest on-disk format available.  By setting
`FormatMostCompatible: FormatNewest`, the `pebble.Open()` func will
automatically migrate the on-disk format to the latest version.
The migrations are done in a backward-compatible manner (2).  If there
are any errors during the migration, the existing DB should not be
affected.  Despite that, safeguard the migration with a feature flag,
disabled by default, so that we can test this in dev first.
Add a test to verify the expected behavior …

pebble_cache: add a flag to enable auto rachet

---

enterprise/server/backends/pebble_cache/pebble_cache.go

We have been running with bloom filter enabled in production since
August 2024. Let's flip the default to true so that we can retire the
flag in deployment config.

pebble_cache: flip table bloom filter to true

---

enterprise/server/remote_execution/containers/firecracker/firecracker.go

Based on these [logs](https://console.cloud.google.com/logs/query;query=resource.type%3D%22k8s_container%22%0Aresource.labels.project_id%3D%22flame-build%22%0Aresource.labels.location%3D%22us-west1%22%0Aresource.labels.cluster_name%3D%22dev-nv8eh%22%0Aresource.labels.namespace_name%3D%22executor-dev%22%0A--%20labels.k8s-pod%2Fapp%3D%22executor%22%0A--%20severity%3D%2528WARNING%20OR%20ERROR%20OR%20CRITICAL%20OR%20ALERT%20OR%20EMERGENCY%2529%0A%22balloon%22;summaryFields=:true:32:end;cursorTimestamp=2025-02-27T22:20:32.032991606Z;startTime=2025-02-27T22:07:19.191Z;endTime=2025-02-27T22:22:19.191Z?project=flame-build&pageState=(%22savedViews%22:(%22i%22:%220c6fd25fd59f4d32b822b9bbf52ac66b%22,%22c%22:%5B%22gke%2Fus-west1%2Fprod-hs6in%22%5D,%22n%22:%5B%5D))&pli=1), we're not giving the balloon …

[SS] Give balloon more time to inflate

---

enterprise/server/remote_execution/containers/firecracker/firecracker.go
enterprise/server/remote_execution/containers/firecracker/firecracker_test.go

A balloon can only be added to a new VM. Invalidate existing snapshots so that they all new VMs startup with a balloon

[SS] Integrate balloon into all firecracker VMs

---

enterprise/server/filestore/BUILD
enterprise/server/filestore/filestore.go
server/backends/blobstore/gcs/gcs.go

Make just the methods we're using in pebble into an interface that can be mocked out; also remove GCS specific constructs from the API so it's easier to do so.

Make GCS stuff an interface so it's easier to test

---

enterprise/server/ociregistry/BUILD
enterprise/server/ociregistry/ociregistry.go
enterprise/server/ociregistry/ociregistry_test.go

The `ociregistry` is now an OCI registry mirror that supports HEAD and GET requests to retrieve manifests and blobs. It makes requests to an upstream registry (`index.docker.io` by default). It does nothing else.
The tests come from [01_pull_test.go](https://github.com/opencontainers/distribution-spec/blob/main/conformance/01_pull_test.go) in the OCI distribution spec.
`ociregistry_test` previously relied on `oci.Resolve`. That was a mistake. Testing the HTTP interface directly gives me more confidence that this registry will work for different clients out in the wild.
TODO:
1. Cache manifests and blobs in the CAS. See #8510.
2. Remove `X-Forwarded-Host` header from `oci.Resolve`. Unnecessary and not in any spec.

OCI registry mirror that passes through HTTP requests to upstream registry

---

cli/explain/BUILD
cli/explain/compactgraph/BUILD.bazel
cli/explain/compactgraph/compactgraph.go
cli/explain/compactgraph/input.go
cli/explain/explain.go
codesearch/index/BUILD
codesearch/index/index.go
codesearch/performance/BUILD
codesearch/performance/performance.go
enterprise/server/remote_execution/copy_on_write/BUILD
enterprise/server/remote_execution/copy_on_write/copy_on_write.go
server/remote_cache/cachetools/BUILD
server/remote_cache/cachetools/cachetools.go
server/util/consistent_hash/BUILD
server/util/consistent_hash/consistent_hash_test.go
server/util/rexec/BUILD
server/util/rexec/rexec.go
tools/jaegerquery/BUILD
tools/jaegerquery/jaegerquery.go

In exp/maps the Keys() and Values() return a slice, but in maps package, they
return iter.Seq instead.

Replace experimental maps package with maps in standard library

---

enterprise/server/raft/bringup/bringup.go

When the order is not deterministic, the retry can fail with inconsistent
target.

[raft] sort nodeGrpcAddr when making bootstrapInfo

---

enterprise/server/raft/driver/driver.go

https://github.com/buildbuddy-io/buildbuddy-internal/issues/4527

[raft] add logs in driver when we are not considering rebalancing leases

---

enterprise/server/raft/client/client.go
server/metrics/metrics.go

This metric can help us understand the health at the dragonboat library. For
example, if we get a lot of timeout errors, we know that dragonboat is
overloaded. This can be helpful in understanding latency/performance issues.
https://github.com/buildbuddy-io/buildbuddy-internal/issues/3745

[raft] add metrics for nodehost.SyncPropose errors

---

enterprise/server/raft/nodeliveness/BUILD
enterprise/server/raft/nodeliveness/nodeliveness.go
enterprise/server/raft/rangelease/rangelease.go

https://github.com/buildbuddy-io/buildbuddy-internal/issues/4528
Add more traces in the Lease flow, in particular capture errors returned by
verifyLease.

[raft] add traces around nodeliveness

---

enterprise/server/remote_execution/copy_on_write/copy_on_write.go
enterprise/server/remote_execution/copy_on_write/copy_on_write_test.go

This method is used when unpacking container images and when saving the initial memory snapshot. The latter is on the critical path of the firecracker `pause` stage.
By using io.Copy with 2 files, we allow it to use the `copy_file_range` system call. This avoids copying memory between kernel and user space. Then we don't need a buffer in Go, which also allows copying bigger ranges instead of just one block at a time. This is where most of the improvement comes from.
Passing chunk starts through a channel instead of starting a new goroutine for every chunk gives another 1-2% improvement.
All together, this is about 36% faster on 100MB files without holes. Benchmark results:
```
goos: linux
goarch: amd64
│     base      │              optimized …
```

Optimize copy_on_write.ConvertFileToCOW

---

.bazelrc

Move the download minimal flags to a separate config.
Make sure that our workflow and prober configs benefit from the TTL flag

bazelrc: Corrected remote_download_minimal config

---

MODULE.bazel
WORKSPACE
go.mod

This contains a fix that broke our build previously on 1.24.0
References:
- https://tip.golang.org/doc/go1.24
- https://github.com/golang/go/issues?q=milestone%3AGo1.24.1+label%3ACherryPickApproved

    gosdk: upgrade to 1.24.1

---

enterprise/server/remote_execution/containers/firecracker/firecracker.go

This delete is on the critical path of the pause stage, and often takes over 150ms. Also, if it fails, I don't think we need to fail the action.

After converting a file to a COWStore, delete it async

---

enterprise/server/raft/store/store.go
enterprise/server/raft/testutil/testutil.go

Example failure: https://buildbuddy.buildbuddy.io/invocation/1ea34ada-e298-4e8a-98f6-2aebc76fdb4a?target=%2F%2Fenterprise%2Fserver%2Fraft%2Fstore%3Astore_test&targetStatus=6#@31
I also added checks for errors in TestingStore.Close()

Fix race condition in //enterprise/server/raft/store:store_test

---

enterprise/server/raft/constants/constants.go
enterprise/server/raft/replica/replica.go
enterprise/server/raft/replica/replica_test.go
enterprise/server/raft/store/store_test.go

because the session key uses system prefix instead of local prefix

[raft] rename LocalSessionPrefix to SessionPrefix

---

cli/bazelisk/bazelisk.go

Fixes a race condition that occurred when passing a buffer to replace stderr in `bazelisk.Run`. Previously, both the goroutine that redirected stderr and the `goLog` had access to the (non-threadsafe) underlying writer and could attempt to write to it in two separate threads. This PR replaces the bare pointer to the writer being passed to `goLog` with the `PipeWriter` we put in front of it, preventing the race condition.

Fix race condition in `bazelisk.Run`

---

enterprise/server/remote_execution/snaploader/BUILD
enterprise/server/remote_execution/snaploader/snaploader.go

When looking at traces, this will make it easy to tell if the memory or disk COWStore took longer to save.
I suspect that the disk one always takes longer. If that's the case, we could start it before we create or merge the memory one.

Add the COW name and size to the tracing span in snaploader.cacheCOW

---

enterprise/server/remote_execution/containers/firecracker/firecracker.go

Prior to enabling the balloon, there were consistently `failed to sync workspace: failed to connect to VM: context deadline exceeded` errors in [executor-workflow](https://console.cloud.google.com/logs/query;query=%22failed%20to%20connect%20to%20VM:%20context%20deadline%20exceeded%22%0Alabels.%22k8s-pod%2Fapp%22%3D%22executor-workflows%22%0Aresource.labels.namespace_name%3D%22executor-prod%22;summaryFields=:false:32:beginning;lfeCustomFields=resource%252Flabels%252Fzone,jsonPayload%252Fkubernetes%252Flabels%252Fapp;cursorTimestamp=2025-03-06T21:26:22.498634932Z;duration=P7D?project=flame-build), but not in `executor` in both [cloud](https://console.cloud.google.com/logs/query;query=%22failed%20to%20connect%20to%20VM:%20context%20deadline%20exceeded%22%0Alabels.%22k8s-pod%2Fapp%22%3D%22exec …

[SS] Disable balloon for non-workflows

---

enterprise/server/remote_execution/containers/firecracker/firecracker.go
enterprise/server/remote_execution/containers/firecracker/firecracker_test.go

This should resolve the snapshot loading issues in SJC

Bump firecracker.GuestAPIVersion to invalidate snapshots

---

enterprise/server/remote_execution/filecache/filecache.go
server/metrics/metrics.go

so that we can tell how much _more_ disk we're using when we enable storing treecache data in the filecache.
the current metric is just a bucketed histogram and is kind of a pain to read.  if you'd rather that we just have the one metric, i can make do.

add a counter metric for filecache writes

---

server/backends/blobstore/disk/disk.go

It can lead to a problem where all blobs are deleted. See https://github.com/buildbuddy-io/buildbuddy/issues/8583 for details.

Don't attempt to delete the emptyBlob

---

enterprise/server/backends/pebble_cache/pebble_cache.go
enterprise/server/backends/pebble_cache/pebble_cache_test.go
enterprise/server/util/pebble/pebble_test.go

s/rachet/ratchet/g
Add a test to help us validate the ability for us to open a ratcheted DB
after a deployment rollback.

pebble: add test to validate revert after ratchet

---

enterprise/server/ociregistry/BUILD
enterprise/server/ociregistry/ociregistry.go
enterprise/server/ociregistry/ociregistry_test.go
proto/BUILD
proto/ociregistry.proto
server/testutil/testregistry/testregistry.go

This change adds caching to the OCI registry mirror. It depends on #8468. Please review #8468 first!
When a client makes a GET request _by digest_ for a blob (layer) or manifest, the registry mirror will
1. see if the payload exists in the CAS and return it if it does;
2. otherwise, fetch the payload from an upstream registry and
3. store payload in the CAS if successfully found in the upstream registry.
If there is an error reading from or writing to the CAS, the request will fail.
People typically fetch manifests by tag (i.e., `latest`). The mapping from tag to OCI image can change. For example, `latest` changes every time people upload a new version of an image. Therefore I do not cache OCI image manifests by tag nor do I cache the mapping from tag to digest.
This means that `docker …

Store OCI image layers and manifests in the CAS

---

enterprise/server/remote_execution/containers/firecracker/firecracker.go

Did not mean to write `.` here - we don't use `.` for the other firecracker flags

Fix firecracker net pool flag name

---

enterprise/server/remote_execution/filecache/filecache.go

When `--executor.include_subdir_prefix` is enabled, this used to return paths with double slashes, because `filepath.Split("foo/bar")` returns `["foo/", "bar"]`. It didn't break anything since `//` is treated the same as `/` pretty much everywhere, but it did make error logs more confusing.
I also added a log for empty group IDs, since that can potentially result in very different paths.

Fix small bug in filecache.filecachePath

---

enterprise/server/raft/bringup/bringup.go
enterprise/server/raft/constants/constants.go
enterprise/server/raft/store/store.go
enterprise/server/raft/store/store_test.go

https://github.com/buildbuddy-io/buildbuddy-internal/issues/4546
Also, make it so that we don't skip range 3.

[raft] store last replica id per range

---

enterprise/server/raft/replica/replica.go
enterprise/server/raft/replica/replica_test.go

https://github.com/buildbuddy-io/buildbuddy-internal/issues/4540
We don't need to worry about overflowing after removing the zero paddings.

[raft] remove zero paddings from replica name

---

dockerfiles/executor_image/Dockerfile
dockerfiles/run_script/Dockerfile
dockerfiles/test_images/net_tools/Dockerfile
dockerfiles/test_images/nonroot_user_image/Dockerfile
dockerfiles/test_images/ociruntime_test/image_config_test_image/Dockerfile
dockerfiles/test_images/xfsprogs_image/Dockerfile

This should help us when the Docker Hub rate limit comes online.

dockerfiles: Use mirror.gcr.io for base images

---

enterprise/server/remote_execution/containers/firecracker/firecracker.go
enterprise/server/remote_execution/copy_on_write/copy_on_write.go
enterprise/server/remote_execution/uffd/uffd.go

Also emit the metrics for stages that fail.
Previously, we only got these metrics up to the point where the balloon is inflated.

Emit COW and UFFD metrics for stages other than init

---

server/metrics/metrics.go

This increases bucket count from 9 to 11, but it adds a lot more precision between 1s and 10min.
The previous buckets were
```
0 = 1µs
1 = 10µs
2 = 100µs
3 = 1ms
4 = 10ms
5 = 100ms
6 = 1s
7 = 10s
8 = 1m40s
9 = inf
```
Now they are
```
0 = 100ms
1 = 229.999ms
2 = 528.999ms
3 = 1.216699s
4 = 2.798409s
5 = 6.436342s
6 = 14.803588s
7 = 34.048254s
8 = 1m18.310985s
9 = 3m0.115266s
10 = 6m54.265112s
11 = inf
```

Improve histogram buckets for 2 firecracker metrics

---

enterprise/server/raft/bringup/bringup.go
enterprise/server/raft/client/client.go
enterprise/server/raft/store/store.go
enterprise/server/raft/store/store_test.go

https://github.com/buildbuddy-io/buildbuddy-internal/issues/4571
1. added a new zombie clean up action: stopReplica.
2. In the case where getMembership returns shard is not ready; we stopReplica
and call RemoveData
3. Added a test case

[raft] clean up zombies where the initial members were not set up properly

---

enterprise/server/api/BUILD
enterprise/server/api/api_server_test.go
server/api/common/common.go

When an invocation failed because of a non-test(aka build) action, the
TargetCompleted event will not contains the relevant output files.
Relevant stderr/stdout of the failed action can be found in the
ActionCompleted event instead.
Enhance the GetAction rpc logic by only handling successful
TargetCompleted events. For the failed cases, add additional logic to
create Action entries from ActionCompleted events.
Refactor FillActionFromBuildEvent to switch on event id instead of event
payload.

api/GetAction: add handling for failed build action

---

enterprise/server/vmexec/BUILD

`vmexec_test` runs `sync` which is very slow if the host FS is under a lot of contention, since it causes all pending writes to be flushed to disk and then waits for those writes to complete.

Run vmexec_test in a VM

---

server/metrics/metrics.go

Previously, this metric had 57 buckets, which made it very slow to query. This change makes it have 12 buckets.

Reduce the number of buckets for firecracker_exec_dial_duration_usec

---

enterprise/server/remote_execution/vbd/vbd.go

Previously, we logged `Unmounted %s in the background, even after the context was canceled`, even if the `f.server.Unmount()` call failed.
Also, there was a logging only race, where the context wouldn't be expired in the child goroutine, so it wouldn't log anything, and then it would be expired in the parent goroutine, which would indicate that we might unmount in the background.

Log the error from umount when it fails in the background

---

enterprise/server/raft/store/store.go
enterprise/server/raft/store/store_test.go

1. should not ignore ShardNotFound when requesting delete replica. When
this happens, the replica membership was not changed
2. always stop replica before removing data. There are some cases where
after requesting delete replica, the node is not deleted or unloaded.
3. fix a bug where we will always return an error when we are supposed
to ignore ErrRejected.
also, rename a zombie test to make it more descriptive since we have
three zombie tests now.
https://github.com/buildbuddy-io/buildbuddy-internal/issues/4577

[raft] fixing some bugs in zombie cleanup

---

enterprise/server/remote_execution/containers/firecracker/firecracker.go
enterprise/server/remote_execution/vbd/vbd.go

This gets rid of duplicate logging when the context expired. It also adds warning logs when calling from Pause(), as opposed to error logs when called from Remove().

Clean up logging from vbd.Unmount calls

---

.bazelrc
.github/workflows/build-executor-win.yaml
.github/workflows/build-windows-github-release-artifacts.yaml

Cache external dependencies downloads to speed up these workflows.

workflows/windows: Enable Bazel and Go download cache

---

server/http/interceptors/interceptors.go
server/libmain/libmain.go

Count requests to the OCI mirror registry by HTTP status code, HTTP method, whether it's a cache hit, and whether you're fetching a blob or manifest.
Measure request latency for successful GET requests of blobs or manifests.

Count requests to OCI registry mirror (plus latency for fetching blobs and manifests)

---

app/invocation/cache_requests_card.tsx
cli/README.md
docs/cli.md
website/src/pages/cli.tsx

Thanks to @skeggse for pointing out `curl` implicitly goes to port 80 unless you specify `https://`!
context: https://buildbuddy-corp.slack.com/archives/C057TAUAQ7P/p1741901313234809

tell people to install CLI over HTTPS

---

enterprise/server/remote_execution/snaploader/snaploader.go

uncompressed_bytes isn't really clear. Is it byte sent remotely, locally, or what? cow_size_bytes makes it clear that it's the size of the COWStore, including non-dirty and all zero chunks.

Rename a span attribute in snaploader.cacheCOW

---

enterprise/server/raft/logger/BUILD
enterprise/server/raft/logger/logger.go

rsm info logs constains membership operations and there are less noisy than other packages. There are useful in debugging driver/split/zombie issues in general.
also removed nullLogger and used zerolog.Level(Disabled) instead. This allows us to control the log levels of dragonboat library easily.

[raft] log rsm info logs for dragonboat library

---

cli/remotebazel/remotebazel.go
cli/remotebazel/remotebazel_test.go

The remote bazel CLI selects a GitHub branch and commit to fetch on the remote runner.
There's an edge case where (1) the remote branch has a commit that the local branch does not and (2) the local commit does not exist remotely. Previously we would use the head commit from the remote branch. This would cause issues in the CLI, because we'd try to run `git diff` operations against a commit that didn't exist locally

[RB] Fix bug when remote commit doesn't exist locally

---

app/invocation/workflow_rerun_button.tsx
buildbuddy.yaml

If you execute a workflow from the API, you can override any env vars that were set in your workflow config. We weren't correctly applying these in the workflow retry button
Fixes https://github.com/buildbuddy-io/buildbuddy/issues/8557

Apply env overrides when retrying manually dispatched workflows

---

cli/parser/parser.go

To avoid naming collisions when introducing the `Option` struct as a parsed form of an option from the command line, make all of the naming in `parser.go` consistent.

Rename variables, fields, and functions named `Option` to `OptionDefinition` as appropriate in cli parser

---

enterprise/app/filter/filter_util.tsx

This commit reduces the default value for the filter from 30 to 7,
which is a more sensible default for our users.

enterprise/app: Changed default filter to 7 days

---

.bazelrc
.github/actions/cache-restore/action.yml
.github/actions/cache-save/action.yml
.github/workflows/build-executor-win.yaml
.github/workflows/build-linux-amd64-github-release-artifacts.yaml
.github/workflows/build-linux-arm64-github-release-artifacts.yaml
.github/workflows/build-mac-intel-github-release-artifacts.yaml
.github/workflows/build-mac-m1-github-release-artifacts.yaml
.github/workflows/build-windows-github-release-artifacts.yaml
.github/workflows/main.yaml
.github/workflows/pr.yaml
.github/workflows/release-cli.yaml
.github/workflows/test-executor-linux-arm64.yaml
.github/workflows/website-pr.yaml
.github/workflows/website.yaml

Follow up of reviews from https://github.com/buildbuddy-io/buildbuddy/pull/8608
Introduce 2 new composite actions
- .github/actions/cache-restore
- .github/actions/cache-save
which handle restoring and saving external dependencies download for
subsequent builds to re-use. This is currently limitted to Bazel's
downloads, go_repository downloads and our yarn_install downloads.
Add these composite actions to all existing workflows that invoke
`bazelisk`.

github/workflows: Improve caching in CI workflow

---

app/router/router.tsx

Workaround for Slack's URL parsing does not accomodate for trailing
periods.

router: apply additional encoding for period character

---

app/trace/constants.ts
app/trace/trace_events.ts

Sort threads using thread id to show the events in a more consistent
order.
Increase the default height of line plots panel to 400 to accomodate for
Bazel 8 flipping --experimental_collect_system_network_usage to true and
added 2 lanes for network upload/download.

Timing profile: update thread sort and metrics

---

.bazelrc

These flags are set with default values as of Bazel 8.1
https://bazel.build/versions/8.1.0/reference/command-line-reference
Clean them up.

bazelrc: remove flags with default values

---

enterprise/server/remote_execution/container/BUILD
enterprise/server/remote_execution/container/container.go
enterprise/server/remote_execution/executor_auth/BUILD
enterprise/server/remote_execution/executor_auth/executor_auth.go
enterprise/server/remote_execution/runner/runner.go
enterprise/server/remote_execution/snaploader/snaploader.go
enterprise/server/scheduling/scheduler_client/BUILD
enterprise/server/scheduling/scheduler_client/scheduler_client.go
enterprise/server/scheduling/task_leaser/BUILD
enterprise/server/scheduling/task_leaser/task_leaser.go
enterprise/server/test/integration/remote_execution/bazel_rbe/BUILD
enterprise/server/test/integration/remote_execution/bazel_rbe/bazel_rbe_test.go

The `--debug_enable_anonymous_runner_recycling` flag is needed to enable runner recycling for anonymous executions. This adds a bit of unnecessary configuration complexity for local development, and possibly also some on-prem scenarios where executors are run without auth. If `--executor.api_key` is unset, then we're already running as part of an anonymous auth setup, so anonymous runner recycling should be allowed.

Enable anonymous recycling when API key is unset

---

enterprise/server/remote_execution/containers/ociruntime/ociruntime.go

These logs are pretty noisy and in practice only `/dev/` paths are logged, which is expected.

Move 'unsupported tar header' logs to debug-level

---

.bazelrc

group all common remote cache flags into a cache-shared config
move remote-shared --remote_upload_local_results flag to cache-shared

bazelrc: clean up duplicated cache flags

---

enterprise/server/workflow/config/config.go

Switch to use `--config=remote-minimal` with a regex to download all
kzip files to help save local resources.

kythe: use rbe instead of local exec

---

.github/workflows/release-cli.yaml

release-cli workflow is a bit special where it operates on multiple
repos instead of just one
```
.github/workflows/release-cli.yaml
19:        uses: actions/checkout@v3
20-        with:
21-          # We need to fetch git tags to obtain the latest cli version tag.
22-          fetch-depth: 0
--
44:        uses: actions/checkout@v3
45-        with:
46-          repository: buildbuddy-io/bazel
47-          path: bazel-fork
--
81:        uses: actions/checkout@v3
82-        with:
83-          path: buildbuddy
84-
--
86:        uses: actions/checkout@v3
87-        with:
88-          repository: buildbuddy-io/plugins
89-          path: plugins
--
156:        uses: actions/checkout@v3
157-        with:
158-          path: buildbuddy
159-
```
Adjust the paths which we load our composite action …

github/workflows: fix release-cli cache loads

---

cli/parser/parser.go
cli/parser/parser_test.go

Fixed a bug where the execArgs were not being re-attached after canonicalizing the startup args.
Also modified a test to confirm the new behavior.

Fix bug in `CanonicalizeStartupArgs`

---

tools/gce-startup-script.sh

Running the BuildBuddy app or an executor on a Linux VM requires certain packages to be installed.
This script installs those packages.
After the script completes, you need to run `sudo ./tools/enable_local_firecracker.sh` to install Firecracker.
As of today (2025-03-17), I can verify that running this script at machine creation time lets you run the app and an executor with the OCI runtime and Firecracker enabled.
```
gcloud compute instances create $YOUR_VM_NAME \
--zone=$A_HANDY_GCE_ZONE_SUCH_AS_us-central1-a \
--machine-type=n2-standard-16 \
--enable-nested-virtualization \
--boot-disk-size=200GB \
--metadata-from-file startup-script=tools/gce-startup-script.sh
```

script for setting up a GCE VM to build and run app, executor

---

app/trace/trace_events.ts
app/trace/trace_viewer_model.ts
app/trace/trace_viewer_panel.ts

Some time series lanes, such as "Memory usage" and "Network usage"
lanes can display a wide range of metric values that made it hard for
users to "guess" the unit being recorded.
Override the event name in Bazel profile with our own display name with
a unit attached to make it easier to read these metrics.

timing profile: add unit to some time series lanes

---

.github/workflows/release-cli.yaml

Follow up from #8679
```
Error
the `uses' attribute must be a path, a Docker image, or owner/repo@ref
```

github/workflows: fix path syntax in release-cli

---

cli/parser/parser.go

We rename `OptionDefinitionSet` to `Parser` in preparation for instanitiating it as a singleton containing the only set of `OptionDefinition`s as well as the set of supported bazel commands, and also because it has the parsing methods as its member methods.
In addition to it being a more descriptive name, it is also much shorter, which is generally preferable.

Rename `OptionDefinitionSet` to `Parser`

---

.github/workflows/build-mac-intel-github-release-artifacts.yaml

https://github.com/buildbuddy-io/buildbuddy/actions/runs/13928825454

Remove empty 'env' from workflow

---

enterprise/server/raft/constants/constants.go
enterprise/server/raft/sender/sender.go

We return range-not-present error when the range is not present in openRanges.
The intention of this error is if we hit the wrong machine, then we don't want
to try all replicas. However, openRanges is not appropriate for this check; it
didn't represent all replicas that should be on this machine; but what was
currently open; during rollout or shutting down, this is only a subset of all
the ranges that should be on the machine.

[raft] try other replicas with range-not-present error

---

.github/workflows/build-mac-intel-github-release-artifacts.yaml
.github/workflows/build-mac-m1-github-release-artifacts.yaml

For some reasons, `$HOME` was evaluated to `/home/runner` in these MacOS
release pipelines instead of `/Users/runner`.
Hard code the paths to `/Users/runner` instead.

github/workflows: fix cache dir for mac releases

---

cli/parser/parser.go

With the exception of `watch_fs`, which is included as a `startup` option intentionally so that it can output a message regarding its deprecation, this change corrects some oversights regarding the classifications of some bazel flags in the flag collection proto, and accompanies them with a comment including their corresponding github issue.

Correct behavior of some flags that bazel does not correctly report

---

buildbuddy.yaml

bazel_commands is deprecated
also address http://go/b/1249

buildbuddy.yaml: migrate to steps

---

enterprise/server/raft/client/BUILD
enterprise/server/raft/constants/constants.go
enterprise/server/raft/store/store.go

When we preload registry, we compute the address from serf address which
was a IP address instead of a hostname. As a result, we are storing two
clients under different names in APIClient.

[raft] add grpc address tag to gossip

---

enterprise/server/util/execution/execution.go
proto/remote_execution.proto
server/remote_cache/action_cache_server/action_cache_server.go

we set `statsPollInterval` to 50ms in `enterprise/server/remote_execution/container/container.go`, and we track 7 stats, so we end up recording 140 bytes per second of execution time.
sending this back to the client when it looks up actionresults adds up quickly--if an action took a minute, we'll send 8k of data!  i think this is having a big impact on data transfer for CI runs, where lots and lots of cached actions are fetched for slow tests.

only send timeline data with ActionResults when it is explicitly requested.

---

enterprise/app/sidebar/sidebar.tsx

These are our most hidden, but also some of our most valuable pages.
This change puts them in the sidebar (if enabled) to make them more easily accessible.

Make drilldowns and flakes top level sidebar items

---

enterprise/server/ociregistry/ociregistry.go
enterprise/server/ociregistry/ociregistry_test.go

OCI clients can fetch OCI image manifests by tag (for example, `latest`) or digest. The mapping from tag to manifest can change (and often does for `latest`), so the mirror only caches manifests by digest.
This means that every time an OCI client makes a GET request for a manifest tag, the mirror makes an upstream GET request  to Docker Hub. [This GET request counts as a "pull"](https://docs.docker.com/docker-hub/usage/pulls/). Starting March 31, 2025, Docker Hub will enforce a 10 pulls per hour rate limit for unauthenticated users.
"Version checks" do not count as pulls. I _think_ that a version check is a HEAD request.
This change has the mirror make a HEAD request to find the digest for a manifest tag. The mirror can then use the digest to look up the manifest in the cache. On the …

[OCI mirror] Resolve manifest digests to be able to read manifests from cache

---

enterprise/server/api/api_server.go

500 usually means we hit some sort of internal server error
In this case, we just couldn't find the file - so we should return 404

Return 404 instead 500 for missing GetFile api endpoint

---

.bazelrc

Remove flags with default values in Bazel 8.
Hide cached test result by default in the test summary as they can make
the terminal output quite large and harder to parse.

bazelrc: remove obsolete flags and hide cached tests

---

server/remote_cache/action_cache_server/action_cache_server.go
server/remote_cache/action_cache_server/action_cache_server_test.go

i've changed the meaning of this metric; i'd be happy to rename it if you want.  instead of tracking the size of the first requested file, the function now tracks the actual size of all files that are sent on the response.

track inlined bytes for all getactionresultrequest files.

---

enterprise/server/cmd/executor/BUILD
enterprise/server/cmd/executor/executor.go

Also use `disk.ForceRemove()` instead of `os.RemoveAll()` - this func is sometimes needed to work around permissions issues, which historically have been more problematic on macOS.

Add logging for delete_build_root_on_startup

---

server/util/disk/disk.go

Use 777 instead of 770 perms. The permissions should be as wide as possible to maximize the chances of removing stubborn entries.

Widen perms in ForceRemove

---

enterprise/app/tap/grid.tsx
enterprise/app/tap/grid_common.ts
enterprise/app/tap/grid_sort_controls.tsx
enterprise/app/tap/tap.css
enterprise/app/workflows/action_list.tsx

Cached test runs are rendered with 50% opacity.
Also shows percentage cached in test summary stats, and allows sorting by cache percentage ascending / descending.
Uses an (imperfect) heuristic to tell whether or not a test was cached (if the tests's start time was before the invocation's start time). This can lead to some false negatives, but should be alright for this use-case.

Differentiate between cached and uncached tests in test grid

---

app/target/target_artifacts_card.tsx

Fix for this warning
```
INFO: From Splitting Javascript ../../../app/app.tsx [esbuild]:
▲ [WARNING] The "&&" operator here will always return the right operand [suspicious-logical-operator]
app/target/target_artifacts_card.js:37:90:
37 │ ....props.files.find((file)=>true && file.name === TargetArtifacts...
╵                                   ~~
The "=>" symbol creates an arrow function expression in JavaScript. Did you mean to use the greater-than-or-equal-to operator ">=" here instead?
app/target/target_artifacts_card.js:37:83:
37 │ ... = this.props.files.find((file)=>true && file.name === TargetAr...
│                                   ~~
╵                                   >=
INFO: From Splitting Javascript ../../../enterprise/app/app.tsx [esbuild]:
▲ [WARNING] The "&&" operator here …
```

app/target: remove redundant boolean clause

---

enterprise/server/remote_execution/execution_server/execution_server.go

This used to be the behavior before I broke it in https://github.com/buildbuddy-io/buildbuddy/pull/8036, because I moved the `recordExecution` call out of `updateExecution`.
Also, fix a possible panic when platform.ParseProperties fails. All subsequent code assumes that the return platform is non-nil.

Log to clickhouse in execution_server.MarkExecutionFailed

---

enterprise/server/execution_service/execution_service.go

This step may not include image download on Executor using "bare"
sandbox.
Instead, it's a combination of:
- Action Cache check
- Runner recycling
+ Runner cleanup
+ Prepare output directories
- Download container image
Rename this to "prepare runner" to better describe the span.

execution_service: rename trace span for step before input download

---

enterprise/server/remote_execution/platform/platform.go

This is no longer used as of #8188

remote_execution/platform: remove GithubActionsImage

---

server/backends/chunkstore/BUILD
server/backends/chunkstore/chunkstore.go
server/backends/chunkstore/chunkstore_test.go

Fixes a bug where the chunkstore would write a chunk with the invalid index, which ought to be impossible. Adds a test confirming this behavior.

Don't write to the invalid index in the chunkstore

---

enterprise/server/cmd/executor/executor.go
enterprise/server/remote_execution/execution_server/execution_server.go
enterprise/server/remote_execution/executor/executor.go
enterprise/server/test/integration/remote_execution/rbetest/rbetest.go
proto/execution_stats.proto
proto/remote_execution.proto
server/util/clickhouse/clickhouse.go
server/util/clickhouse/schema/schema.go

This will allow evaluating experiments where we want a feature to be on/off on a whole machine.
Initially, I want to evaluate https://github.com/buildbuddy-io/buildbuddy/pull/8655.

Store the executor hostname in clickhouse

---

enterprise/server/cmd/server/BUILD
enterprise/server/cmd/server/main.go
enterprise/server/hit_tracker_service/BUILD
enterprise/server/hit_tracker_service/hit_tracker_service.go
enterprise/server/hit_tracker_service/hit_tracker_service_test.go
proto/BUILD
proto/hit_tracker.proto
server/environment/BUILD
server/environment/environment.go
server/libmain/BUILD
server/libmain/libmain.go
server/real_environment/BUILD
server/real_environment/real_environment.go

This is https://github.com/buildbuddy-io/buildbuddy/pull/8726/files but without any changes to the hit tracker implementation.
I also removed the `source` field from `TrackRequest` as it's not needed at this time (but would be nice to have in the future).

Add a no-op hit-tracking RPC service in the app

---

.github/workflows/release-cli.yaml

As Github Action set $HOME on MacOS to Linux path `/home/runner`, we get
no cache hit on MacOS as that path does not exist.
Use separate setup cache restore/save steps for MacOS and Linux based on
matrix os value.

workflows/release-cli: use separate cache dir for Mac and Linux

---

cli/bazelisk/bazelisk.go
cli/help/BUILD
cli/help/help.go

This fixes a race condition `bazelisk.Run` where if both the out and err buffers were the same, two pipes pointing to the same buffer were created with accompanying goroutines, and the buffer could thus be accessed in two different goroutines. This solves the problem by checking to see if the buffer is the same between both out and err, and then creating only one pipe if it is. This was previously sidestepped in `cli/help/help.go` by passing a `lockingbuffer`, but that requirement is undocumented, and it seems that removing the possibility of the race condition is likely better than documenting such a requirement for future ease of use.

Fix race condition in `bazelisk.Run` when redirecting both stderr and stdout to the same buffer

---

enterprise/server/remote_execution/execution_server/execution_server.go
enterprise/server/remote_execution/execution_server/execution_server_test.go

If the invocation ID is missing from the execution request metadata, we'll keep appending executions to the "exec" key and refreshing the expiration on that key.
Context: https://buildbuddy-corp.slack.com/archives/C06N9AHA4JX/p1742936173184879?thread_ts=1742926682.004709&cid=C06N9AHA4JX

Fix memory leak in "exec" redis key

---

cli/execute/execute.go
cli/explain/explain.go
cli/upload/upload.go
enterprise/server/atime_updater/atime_updater_test.go
enterprise/server/backends/distributed/distributed.go
enterprise/server/bes_artifacts/bes_artifacts.go
enterprise/server/byte_stream_server_proxy/byte_stream_server_proxy.go
enterprise/server/byte_stream_server_proxy/byte_stream_server_proxy_test.go
enterprise/server/cmd/ci_runner/main.go
enterprise/server/cmd/smash/smash.go
enterprise/server/hostedrunner/hostedrunner.go
enterprise/server/remote_execution/action_merger/action_merger.go
enterprise/server/remote_execution/execution_server/execution_server.go
enterprise/tools/replay_action/replay_action.go
server/remote_cache/cachetools/cachetools.go
server/remote_cache/cachetools/cachetools_test.go
server/remote_cache/digest/digest.go
server/testutil/byte_stream/byte_stream.go

These functions always return `nil` errors since https://github.com/buildbuddy-io/buildbuddy/pull/8761.

Remove `error` return value of typed `ResourceName` `*String` functions

---

MODULE.bazel
WORKSPACE
docs/rbe-github-actions.md
docs/rbe-setup.md
tools/dev_qa.py

Fix issues with dev_qa.py while running on 22.04:
- Use the latest BB toolchain version.
- Ensure our toolchains are registered with Bazel
- Trim some flags that are not relevant to toolchain-platform resolution
- Exclude "local" targets in Gazelle, which may cause incompatibility
On the last point: we are still doing RBE on 20.04 image, so some of the CC/CGO compilation are incompatible with a 22.04 host. Gazelle has some `go_bazel_test` targets which are tagged with "local" and "exclusive". These will use CC/CGO deps, which are compiled remotely, to link the final binary locally, which can cause issues. Excluding them for now since the purpose here is to verify RBE of dev deployment.

sync buildbuddy toolchain in dev_qa.py

---

enterprise/app/repo/repo.tsx
enterprise/app/settings/github_complete_installation.tsx
enterprise/app/settings/github_link.tsx
enterprise/app/workflows/github_app_import.tsx
enterprise/server/githubapp/BUILD
enterprise/server/githubapp/githubapp.go
enterprise/server/githubauth/githubauth.go
enterprise/server/hostedrunner/hostedrunner.go
enterprise/server/test/integration/remote_bazel/BUILD
enterprise/server/test/integration/remote_bazel/remote_bazel_test.go
enterprise/server/workflow/service/service.go
enterprise/server/workspace/workspace_service.go
proto/github.proto
server/backends/github/github.go
server/buildbuddy_server/buildbuddy_server.go
server/environment/environment.go
server/interfaces/interfaces.go
server/libmain/libmain.go
server/real_environment/real_environment.go
server/static/static.go
server/tables/tables.go
server/testutil/testgit/testgit.go

TODO: Backfill appID in database for `GitRepository` and `GitHubAppInstallation`
This PR adds a wrapper for every place we use GithubApp. Now that we'll support 2 different versions of the app, we need to reference the appropriate one

Refactor github logic to prepare for supporting 2 github apps

---

enterprise/server/remote_execution/execution_server/execution_server.go
enterprise/server/remote_execution/execution_server/execution_server_test.go
enterprise/server/remote_execution/executor/executor.go
enterprise/server/remote_execution/operation/operation.go
server/remote_cache/cachetools/cachetools.go
server/remote_cache/digest/digest.go

Addresses the comments in https://github.com/buildbuddy-io/buildbuddy/pull/8761#pullrequestreview-2715109056 by:
* Refactor `Metadata` functions to accept digests, which avoids unwrapping `CASResourceName`s.
* Inline a confusing wrapper method.

Make typed resource names more ergonomic

---

enterprise/server/scheduling/priority_task_scheduler/priority_task_scheduler.go
enterprise/server/util/cpuset/cpuset.go
server/util/priority_queue/priority_queue.go
server/util/priority_queue/priority_queue_test.go

driver.priorityQueue and priority_queue.innerPQ share almost the same code.
The main difference is that 
- in driver, we want to be able to remove the item with the min priority when the
queue is full. 
- in driver, we want to update the priority, when we push the task with the same
range id instead of adding a new item onto the queue.

Consolidate driver.priorityQueue and priorityQueue.innerPQ

---

enterprise/server/raft/driver/BUILD
enterprise/server/raft/driver/driver.go
enterprise/server/raft/driver/driver_test.go

1. refactor - added a baseQueue layer to put the queue related logic; so
that when I test the retry logic I don't need to set up replicas and
stores.
2. added an attemptRecord in pqItem. When the nextAttemptTime hasn't
become current, we don't execute the task, and instead we will put
the same task back onto the queue.
https://github.com/buildbuddy-io/buildbuddy-internal/issues/3933

[raft] Add exponential backoff when we retry the same action for the same replica

---

enterprise/server/raft/store/store.go
enterprise/server/raft/store/store_test.go

1. refactor: create a class replicaWorker that encapsulate common replica task queue
operation such as Enqueue(), Start(). So deleteSessionsWorker and the
new worker to clean up non voters can share the code
2. Implement a worker to remove zombie non voters. For replicas where we hold
the leases, we will get the membership info from dragonboat, and if there is
a replica stayed as a non-voter for an hour, we will call RemoveReplica on
it.
3. getMembership -> GetMembership, so I can use it in the test.

[raft] clean up zombie non-voter

---

enterprise/server/cmd/executor/executor.go

This is the hostname that is sent to the scheduler when the executor registers itself. This only matters if the MY_HOSTNAME env variable is set.

Make the hostname sent to PublishOperation use the resources package

---

enterprise/server/atime_updater/atime_updater.go

I've noticed some occasional RPC timeouts and dropped digests from the atime updater over the past couple of weeks. Given the Cache Proxy's memory usage is quite low, it seems fine to buffer more of these in memory and give the RPC a bit longer to finish.

[Cache Proxy] tweak default values for atime_updater flags

---

enterprise/server/raft/store/store.go

https://github.com/buildbuddy-io/buildbuddy-internal/issues/4573
When we start the shard in AddReplica, dragonboat will call registry.Add on our
behalf so we don't need to call it. Sometimes, a non-voter can be a zombie, and the shard is never started. If we don't call registry.Add here, we don't need to clean up.
The node info is either added during preload Registry; or through RegistryPush
gossip requests.

[raft] remove registry.Add call when we add non-voting replicas

---

enterprise/server/raft/registry/BUILD
enterprise/server/raft/registry/registry.go
enterprise/server/raft/registry/registry_test.go
enterprise/server/raft/store/store.go
enterprise/server/raft/store/store_test.go
enterprise/server/raft/testutil/BUILD
enterprise/server/raft/testutil/testutil.go

https://github.com/buildbuddy-io/buildbuddy-internal/issues/4573
dragonboat calls Remove/RemoveShard when it applies RemoveNode
membership change.
I changed the nodeTargets to a regular map, added a new map to keep track of all replicas for a single shard. These two maps are protected by a mutex since they need to be in sync. 
Also fix the test. Previously in testutil, we share a single registry among different stores created StoreFactory and this can cause test to fail now we are removing entries from registries.

[raft] implement registry.Remove/RemoveShard

---

enterprise/server/filestore/BUILD
enterprise/server/filestore/filestore.go

This ensures that even in the presence of concurrent writes for the same blob, only one writer will write to a single blob path.

Write blobs under unique paths

---

enterprise/server/raft/leasekeeper/leasekeeper.go
enterprise/server/raft/replica/replica.go
enterprise/server/raft/store/store.go
server/metrics/metrics.go

https://github.com/buildbuddy-io/buildbuddy-internal/issues/3602
increased event size to 1000. We have ~180 ranges per machine. When replica and
leasekeeper broadcasting events at the same time, we will drop events.
add monitoring to monitor the size of the broadcast chan and the num of dropped
events

[raft] increase events chan size and add monitoring

---

server/util/log/log.go

Example usage:
```
l := log.NamedSubLogger("test").EveryN(3)
for i := range 10 {
l.Infof("i is %d", i)
}
```
Will print:
```
2025/03/31 16:24:09.097 INF i is 0 name=test
2025/03/31 16:24:09.398 INF i is 3 name=test
2025/03/31 16:24:09.699 INF i is 6 name=test
2025/03/31 16:24:10.000 INF i is 9 name=test
```
And
```
l2 := log.NamedSubLogger("test").EveryDuration(time.Millisecond * 300)
for i := range 10 {
l2.Warningf("l2: i is %d", i)
time.Sleep(100 * time.Millisecond)
}
```
Will print:
```
2025/03/31 16:24:09.097 WRN l2: i is 0 name=test
2025/03/31 16:24:09.398 WRN l2: i is 3 name=test
2025/03/31 16:24:09.699 WRN l2: i is 6 name=test
2025/03/31 16:24:10.000 WRN l2: i is 9 name=test
```

Add simple log filters to reduce frequency

---

enterprise/server/raft/registry/registry.go

After we removed registry.Add and registry.AddNode call from addNonVoting in https://github.com/buildbuddy-io/buildbuddy/pull/8796,  it causes issues when we try up-replicate meta-range from 3 replicas to 5 replicas.
The issue is that the target:raft_address:grpc_address were not propagated to other nodes as expected through gossip; and as a result, registry.Resolve can't resolve the raft address for the new replica c1n4 or c1n5 even though registry have info for these two replicas.

[raft] pushUpdate registry event should not be coalesced

---

enterprise/server/atime_updater/BUILD
enterprise/server/atime_updater/atime_updater.go
server/util/authutil/BUILD
server/util/authutil/authutil.go

I'd like to reuse this logic in the hit-tracker-client implementation.

Factor the auth-header preservation out of atime_updater

---

website/yarn.lock

https://github.com/buildbuddy-io/buildbuddy/security/dependabot/204

Update `tar-fs` to `v2.1.2` and `v3.0.8` for dependabot

---

package.json

https://github.com/buildbuddy-io/buildbuddy/security/dependabot/202

Update `@babel/runtime` to `v7.26.10` for dependabot

---

enterprise/server/action_cache_server_proxy/action_cache_server_proxy.go
enterprise/server/action_cache_server_proxy/action_cache_server_proxy_test.go

Previously, if we requested a proxy-cached ActionResult and the remote server has a _different_ ActionResult, we would use a modified GetActionResultRequest that included cached_action_result_digest as a key when saving the ActionResult to the cacheproxy cache.  This meant that the cacheproxy-cached ActionResult was never getting overwritten!
This change computes the AC key for the request prior to setting cached_action_result_digest.

cache proxy: dont include cached digest key when hashing GetActionResultRequest

---

app/invocation/invocation_error_card.tsx

cquery would always include the --nobuild flag automatically.
This causes Bazel to generate a handful of aborted events despite the
user running a valid query.
Silence the error card by excluding this particular case.

invocation/error_card: don't show NO_BUILD abort events with cquery

---

enterprise/app/history/history.tsx
enterprise/server/invocation_search_service/invocation_search_service.go
enterprise/server/invocation_stat_service/invocation_stat_service.go
proto/invocation.proto

Was trying to filter the UI to show only prober invocations > 1 minute and noticed the invocation list was being updated but not the summary at the top which shows the total invocation count / duration etc. This PR fixes that.
Also simplify some of the server-side query logic and fix some TS type issues (we were using the `InvocationQuery` message for the `GetInvocationStatRequest.query` field but should be using `InvocationStatQuery`).

Respect min/max duration filters in invocation aggregate/summary queries

---

tools/metrics/grafana/dashboards/cache-proxy.json

This generated a bunch of extra diffs because I also made the "Proxy Servers" graphs collapsed by default (they are currently expanded at http://go/cpm). New row looks like this:

[Cache Proxy] add Grafana graphs tracking the performance of the remote hit-tracker

---

enterprise/server/cmd/server/BUILD

Enable runfiles on pkg_tar. We depend on it critically.
Fix entrypoint path to mirror our existing rules_docker path.
Add an oci_load rule to help with loading the image into docker daemon.

ent/cmd/server: fix oci_image setup

---

.bazelrc
.github/workflows/deps.yaml
shared.bazelrc

Split most of common bazelrc flags into a shared file so that we can
sync and reuse it with our internal repo.
Intentionally exclude most of environment-specific configs as they can
be a bit cummbersome to untangle in this change.
One important change in this PR is the removal of the default flag
`--noremote_upload_local_results`. The reasoning is that uploading AC
should be relatively cheap vs CAS so we don't really have a strong
reason to skip it. The flag is no-op unless a `--remote_cache` or
`--remote_executor` is set, and we do enable it inside `cache-shared`
unconditionally. This should bring our config more in sync with
internal's bazelrc.

.bazelrc: introduce shared.bazelrc

---

enterprise/server/raft/leasekeeper/leasekeeper.go
enterprise/server/raft/listener/listener.go
enterprise/server/raft/rangelease/rangelease.go
enterprise/server/raft/store/store_test.go

- add a test to reproduce the issue where when a replica is removed from
a nodehost, and then we add a new replica of the same range, and then when the
leadership is transfered to the new replica, we cannot acquire lease.
https://github.com/buildbuddy-io/buildbuddy-internal/issues/4528
- add the replica name when rangeLease does not match replica's in-memory
rangelease.
To fix the issue:
- store replica id in lease agent
- use a regular map to store lease agents in leasekeeper, and protect it by the
existing mu in leasekeeper. 
- in AddRange, we will check if the store lease agent matches the r.ReplicaID.
If not, we will create a new lease agent and store it. 
- In raft/listener, implement Add(Remove)NodeUnloadedListener; so that
leasekeeper can listen on it.
- When leasekeeper receives …

[raft] fix the issue where we use the lease agent for the removed replica instead of the newly added one

---

enterprise/server/remote_execution/execution_server/execution_server.go
server/olapdbconfig/olapdbconfig.go

It's always set to true in our configs. If someone is self-hosting, using clickhouse, and they don't want every execution written when they update buildbuddy, they can still turn the flag off.

Default --app.enable_write_executions_to_olap_db to true

---

tools/metrics/docker-compose.grafana.yml
tools/metrics/grafana/grafana.go
tools/metrics/grafana/provisioning/local/datasources/datasources.yml

It can connect to either a locally running clickhouse, or a port-forwarded dev/prod instance.
I also made a few minor improvements to grafana.go:
- if `docker-compose` isn't available, then `docker compose` is used
- Log when port forwarding fails. Since we don't use `exec.CommandContext` for the docker command, it keeps running and logging, so `eg.Wait()` doesn't return which makes it hard to tell that anything went wrong.
- Cancel the context when docker exits cleanly. This cancels all the other goroutines and lets the program exit instead of continuously logging `Failed to list grafana dashboards...`

Allow local grafana to connect to clickhouse

---

tools/metrics/grafana/provisioning/deploy/datasources/datasources.yml

Using the "grafana" uid seems to collide with the builtin grafana data source, making this not work. Either way, I wanted to call this "clickhouse" instead.

Fix the uid of the clickhouse datasource in grafana

---

enterprise/server/hit_tracker_client/hit_tracker_client.go

Without this PR, the hit-tracker-factory is nil if the flag is missing, which causes panics in the cache code that tries to use it. This change registers a no-op hit tracker factory if the flag is missing.

[Cache Proxy] allow empty values of cache_proxy.remote_hit_tracker.target

---

tools/metrics/grafana/dashboards/buildbuddy.json

Makes it more obvious when the hit rate being low is due to autoscaling.

Add quartiles to filecache hit rate chart

---

shared.bazelrc

our parser does not work correctly with this flag when it does not come
with a value attached.
workaround by adding a value explicitly.

shared.bazelrc: workaround bb cli parser

---

cli/parser/parser.go

when we detect this special flag and see that the value starts with "-",
assume that the value is another bazel flag and this flag has no value.

cli: fix enablePlatformSpecificConfigFlag

---

enterprise/server/saml/saml.go
enterprise/server/scim/BUILD
enterprise/server/scim/scim.go
enterprise/server/scim/scim_test.go

From the perspective of an external system, a user does not exist if it's not a member of the SCIM-managed group. We do not return such users via the query APIs.
If a user is manually removed via the UI, but is still mapped in the external system then the external system will send a "create user" request to bring the systems in sync. Prior to this fix, this would fail since the internal create call would fail due to the existence of a user with the same SubID.

SCIM: fix user creation if user exists but not in SCIM group

---

enterprise/server/backends/distributed/distributed.go
enterprise/server/backends/distributed/distributed_test.go

When using a lookaside cache, if some of the digests weren't found in the lookaside cache, we would fail to return all the ones that *were* found.

Fix a bug in distributed.Cache.remoteGetMulti 

---

enterprise/server/cmd/executor/executor.go
enterprise/server/remote_execution/containers/firecracker/firecracker_test.go
enterprise/server/remote_execution/containers/ociruntime/ociruntime_test.go
enterprise/server/util/cpuset/cpuset.go
enterprise/server/util/cpuset/cpuset_test.go
enterprise/server/util/cpuset/numcpu_darwin.go
enterprise/server/util/cpuset/numcpu_linux.go
enterprise/server/util/cpuset/numcpu_windows.go
enterprise/tools/vmstart/vmstart.go

- Don't require NUMA node to be specified when setting the CPU ranges flag; instead allow passing only CPU ranges and infer the NUMA node automatically. See https://github.com/buildbuddy-io/buildbuddy-internal/pull/4558#discussion_r1989994829
- If the NUMA node is specified (e.g. if we want to make the config more explicit / make it clearer which nodes we're using) then validate that the nodes actually correspond to the provided CPUs.
- Don't ignore errors in GetCPUs.
- Make parsing slightly more intuitive: split the `NODE:CPUS` strings on `:` first then `-`, instead of the other way around.
- Improve error messaging when we fail to parse the cpuset flag.

Improve cpuset configuration

---

enterprise/server/backends/migration_cache/config.go
enterprise/server/backends/migration_cache/migration_cache.go
enterprise/server/backends/pebble_cache/pebble_cache.go
enterprise/server/backends/pebble_cache/pebble_cache_test.go

Add this option which we set in some cells so that migrations can proceed with it set.

Add ratchet option to migration config

---

app/invocation/invocation_suggestion_card.tsx

https://github.com/bazelbuild/bazel/commit/241c21da0739ad2d5b0642690190c14b96dcbae2
flips this to false by default starting from 8.0.

invocation/suggestion: skip legacy_important_outputs for 8.0

---

enterprise/server/remote_execution/execution_server/execution_server_test.go
enterprise/server/util/execution/execution.go
server/util/clickhouse/clickhouse.go

This is a blocker for migrating from MySQL => ClickHouse for the Executions page, since we currently render this column on that page.

Populate status_message column in ClickHouse

---

WORKSPACE
WORKSPACE.bzlmod

Upgrade to the latest commit in master branch of rules_docker.
The 2 years worth of diff could be found here
https://github.com/bazelbuild/rules_docker/compare/v0.25.0...b44cc958e61c3192c57fed7aef78c8567d757a70
In a future PR, we will attempt to use a fork of rules_docker which
enable bzlmod support. This should help lifting to that version a bit
easier.

rules_docker: upgrade to latest master

---

enterprise/server/remote_execution/execution_server/execution_server_test.go
enterprise/server/util/execution/execution.go
proto/remote_execution.proto
server/util/clickhouse/clickhouse.go
server/util/clickhouse/schema/schema.go

This is a blocker for MySQL => ClickHouse migration since we currently show this data in the UI and it's driven by the command_snippet field that we store in MySQL but not ClickHouse.
Longer-term we discussed using `output_paths[0]` instead of command snippet for display in the UI, but I think we should decouple that from the MySQL => ClickHouse migration. If we switch to `output_paths[0]` later, we can always come back and delete this `command_snippet` column.

Store command_snippet in ClickHouse

---

enterprise/server/test/webdriver/shortcuts/shortcuts_test.go
server/testutil/webtester/webtester.go

The `<body>` element isn't particularly special compared to other elements, so it seems confusing/redundant for it to have its own special `Find` method exposed in the low-level WebTester API. Replace `FindBody()` with `Find("body")`.

cleanup: remove FindBody from WebTester API

---

server/util/redact/redact.go
server/util/redact/redact_test.go

https://github.com/buildbuddy-io/buildbuddy-internal/issues/4729

avoid redacting bazel targets that look like api keys

---

enterprise/server/raft/client/client.go
enterprise/server/raft/driver/driver.go
enterprise/server/raft/nodeliveness/nodeliveness.go
enterprise/server/raft/registry/BUILD
enterprise/server/raft/registry/registry.go
enterprise/server/raft/registry/registry_test.go
enterprise/server/raft/store/store.go
enterprise/server/raft/store/store_test.go
proto/raft.proto

https://github.com/buildbuddy-io/buildbuddy-internal/issues/3336
- Remove unused ResolveNHID in registry.
- Change ResolveGRPC to take in NHID instead of (shard_id, replica_id).
- Allow us to query peers by NHID.

[raft] change ResolveGRPC to take in nhid

---

server/util/terminal/terminal.go

This "fixes" the annoying bug where bazel progress lines get scrolled up above the line where curses believes them to be, effectively freezing those lines in time and then beginning the progress lines below. I discovered that what was happening was that particulary long lines (>100 characters) would wrap in the ANSI state machine we use, which would cause any lines above it to move up. That means any lines above that line would no longer be where curses believed them to be, so the lines above the window curses modifies would never be changed again, resulting in the behavior we were seeing.
I increased the number of columns in the state machine from 160 to 256 via the `SetSize` function, which at least makes this much less common. I am open to suggestions as to what this value ought to be; …

Fix for line-wrap bug

---

server/util/redact/BUILD
server/util/redact/redact_test.go

This change groups the tests for redacting passwords in URLs into a single test function with multiple test cases. It also uses the `protocmp` and `go-cmp` packages to compare BuildEvents.
In general, I'd like one test function per _kind_ of secret we're redacting (such as passwords in URLs, non-allowed environment variables, or repo credentials) with one test case per _place_ where a secret could appear.
This way, if we find we're failing to redact a particular _kind_ of secret, we can add or modify the test cases for that _kind_ of secret and know we've covered it. Same goes for cases where we're over-redacting.
If people approve of this approach, I'll keep going!

Test redacting passwords in URLs in a single function

---

app/errors/error_service.ts
app/invocation/invocation.tsx
app/invocation/invocation_action_card.tsx
app/invocation/invocation_not_found.tsx
enterprise/app/trends/heatmap.tsx
enterprise/server/test/webdriver/executions_clickhouse/BUILD
enterprise/server/test/webdriver/executions_clickhouse/executions_clickhouse_test.go
server/build_event_protocol/build_event_handler/BUILD
server/build_event_protocol/build_event_handler/build_event_handler.go
server/eventlog/BUILD
server/eventlog/eventlog.go

Both the UI state and backend state for executions is very complex (especially for in-progress executions), and the UI/backend have complex interactions (streaming w/ retries, special loading state, periodic refreshing). So it seems like a basic webdriver test exercising the real code can help us catch lots of bugs here.
While writing the test I hit various test failures/flakes due to how we're handling certain types of errors (mostly NotFound errors), which seem like legitimate issues - e.g. we're directly returning the "record not found" DB-level error to the UI, instead of returning a gRPC NotFound status. Fixed those bugs in this PR as well.

Add E2E webdriver test for executions + clickhouse

---

enterprise/server/backends/distributed/distributed.go
server/remote_cache/digest/digest.go

Currently, it spends most of its time creating errors that are never returned or logged: 
There's no benchmarks that currently use this code, and I could add them, but these changes are trivial so I think it's safe to assume they won't make things slower.

Optimize distributed.Cache.getLookasideEntry

---

WORKSPACE
WORKSPACE.bzlmod

Upgrade rules_k8s to latest commit on master branch.
Prepatory change for bzlmod and oci support in the future.

rules_k8s: upgrade to latest commit on master

---

app/docs/setup_code.tsx
docs/rbe-setup.md
docs/troubleshooting-rbe.md

This has been a recurring theme for a while now that Bazel can wait for
an action for a full hour before issuing a retry.
Let's recommend a moderate timeout value of 10 minutes (600 seconds)
instead. This does mean that larger blob transfers may fail in slow
network conditions. But that's relatively rarer and easier to
troubleshoot.

docs: recommend 600 seconds timeout

---

enterprise/server/scheduling/scheduler_server/scheduler_server.go
enterprise/server/scheduling/scheduler_server/scheduler_server_test.go
enterprise/server/test/integration/remote_execution/remote_execution_test.go

Setting flags that are read in goroutines often causes race condition failures like https://buildbuddy.buildbuddy.dev/invocation/230df744-1163-4fa7-9be2-4b55a0bd090e?target=%2F%2Fenterprise%2Fserver%2Ftest%2Fintegration%2Fremote_execution%3Aremote_execution_test&targetStatus=6#10@10

Fix a race condition in remote_execution_test

---

enterprise/server/remote_execution/platform/platform.go
enterprise/server/scheduling/scheduler_server/scheduler_server.go

This skips most of modifyTaskForExperiments for OCI actions, and it will make it a bit easier to analyze the experiment.

Only set skip-resaving-action-snapshots on firecracker actions

---

enterprise/server/ociregistry/ociregistry.go

To track metrics (and block requests to non-allowed IPs), use the `httpclient` instead of `http.DefaultClient`.

use httpclient for /v2/ requests

---

enterprise/server/raft/store/store.go

To prevent machine cpu goes to 90% when there is a bug in zombie removal code.
also, actually use rateLimiter in the janitor.

[raft] add some backoff when retry zombie failed

---

enterprise/server/experiments/experiments.go
enterprise/server/scheduling/scheduler_server/BUILD
enterprise/server/scheduling/scheduler_server/scheduler_server.go
server/util/bazel_request/bazel_request.go

The previous version of this didn't work because `GetRequestMetadata` in `experiments.FlagProvider.getEvaluationContext` would return nil. This is because the server interceptor calls ParseRequestMetadataOnce, it doesn't find the metadata bytes, but it puts a nil proto in the context.
Instead, just allow override the parsed RequestMetadata.

Fix how the scheduler overrides RequestMetadata for experiments

---

enterprise/server/execution_search_service/execution_search_service.go
enterprise/server/util/execution/execution.go

I had already written this `ExecutionListingColumns()` function for a different WIP PR; figured the recent issue with the `experiments` column was a good excuse to send this out as a smaller PR :P

drilldown: select only needed execution fields

---

MODULE.bazel
WORKSPACE
go.mod

Includes some security fixes to net/http and some compiler+runtime
fixes.
https://github.com/golang/go/milestone/390?closed=1

gosdk: upgrade to 1.24.2

---

MODULE.bazel
WORKSPACE

Cleanup MODULE.bazel file to prepare for eventual migration.
The most important change here is that we are explicitly registering our
bb toolchains to override the default auto-registering order, which put
rules_cc local toolchain up top based on the bazel_dep loading order.
In the future we might need to apply the same manual registration to
select the exact Go toolchains that we want to use.
Upgraded googleapis, platforms, rules_python to latest release on central
registry. This let us get rid of the deprecated switched_rules
extensions call.

bzlmod: prepare deps for migration

---

deps.bzl

Upgrade protoc-gen-protobufjs to v0.0.13 and
update the integrity checksum.
Include this change that should help aid bzlmod migration.
https://github.com/buildbuddy-io/protoc-gen-protobufjs/pull/3

deps: upgrade protobufjs (#8922)

---

enterprise/server/hostedrunner/BUILD
enterprise/server/hostedrunner/hostedrunner.go
enterprise/server/hostedrunner/hostedrunner_test.go
server/util/rexec/BUILD
server/util/rexec/rexec.go
server/util/rexec/rexec_test.go

Functionally, this is just a small aesthetic change - makes it easier to compare actions in the UI, since currently the env vars get shuffled around when looking at different remote bazel invocations. It's also good practice though since the REAPI spec says we "MUST" normalize env vars

Normalize remote bazel env vars

---

app/invocation/invocation_error_card.tsx

Ignore all nobuild and noanalyze aborted events during error tracking.

invocation_error_card: ignore nobuild and noanalyze

---

cli/cmd/sidecar/BUILD
cli/cmd/sidecar/sidecar.go
cli/config/config.go
cli/sidecar/sidecar.go

Switch from searching the os args to try to remove a flag indicating the sidecar, if it exists, to using an environment variable. This avoids having to modify os args without parsing them, which is brittle, as well as parsing the os args, which we would prefer not to do if we are not the sidecar.

Use environment variable to identify if the bb binary is running as the sidecar

---

enterprise/server/backends/distributed/distributed.go
enterprise/server/test/performance/cache/cache_test.go
enterprise/server/util/distributed_client/distributed_client.go

Implement an io.WriterTo instead of using io.Pipe., which is pretty much the same strategy as https://github.com/buildbuddy-io/buildbuddy/pull/8887.
I renamed the distributed benchmarks so it's easier to just run them with `-test.bench=Benchmark/Dist`.
Reduces CPU usage by 1%-7% and memory allocations by 5%-20%:
```
goos: linux
goarch: amd64
│     base     │            writetocopy             │
│    sec/op    │   sec/op     vs base               │
Get/DistDisk10-24              98.92µ ± 3%   91.90µ ± 2%  -7.10% (p=0.000 n=11)
Get/DistDisk100-24             98.39µ ± 2%   92.34µ ± 3%  -6.14% (p=0.000 n=11)
Get/DistDisk1000-24           100.29µ ± 1%   95.15µ ± 1%  -5.13% (p=0.000 n=11)
Get/DistDisk10000-24           111.1µ ± 1%   104.4µ ± 1%  -6.01% …
```

Optimize distributed.Cache.Get

---

.bazelrc
shared.bazelrc

Moved most configs that our internal repo does not use into the shared
file. Since they are not used, this move is unlikely to break anything.
Removed some redudant --remote_cache flag as it's used right next to
--remote_executor flag targeting the same grpc endpoint.
Moved all testing related flags into a dedicated section in our shared
file. We don't do any testing in our internal repo so this should be
safe.
Cleaned up the remaining file:
- Removed redudant flag to disable disk_cache
- Moved remote_timeout to cache-shared so cache-related configs would
also benefit from it.
- Moved some of the remaining flags to the top of the file to better
highlight the default values.

.bazelrc: move unique configs into shared.bazelrc

---

server/tables/tables.go

After merging, I plan to backfill both of these fields to true for all current customers
PRs where these are used (still WIP):
https://github.com/buildbuddy-io/buildbuddy/pull/8930
https://github.com/buildbuddy-io/buildbuddy/pull/8914

[WF] Add db columns to support disabling automatic workflow functionality

---

server/util/consistent_hash/BUILD
server/util/consistent_hash/consistent_hash.go
server/util/consistent_hash/consistent_hash_test.go

In benchmarks, this makes distributed FindMissing ~10% faster. GetAllReplicas is also 2.6% of our app CPU, so this will nearly eliminate that.
Benchmark results from `//server/util/consistent_hash:consistent_hash_test`:
```
│    50base     │            50finalnomod2            │
│    sec/op     │   sec/op     vs base                │
GetAllReplicas/CRC32/100_vnodes-24      23560.0n ± 1%   579.5n ± 3%  -97.54% (p=0.000 n=11)
GetAllReplicas/SHA256/10000_vnodes-24   17076.0n ± 3%   759.3n ± 1%  -95.55% (p=0.000 n=11)
geomean                                   20.06µ        663.3n       -96.69%
│   50base   │            50finalnomod2            │
│    B/op    │    B/op     vs base                 │
GetAllReplicas/CRC32/100_vnodes-24      960.0 ± 0%   960.0 ± 0%       ~ (p=1.000 n=11) ¹ …
```

Make consistent_hash.GetAllReplicas 20 times faster

---

enterprise/server/backends/pebble_cache/pebble_cache.go
enterprise/server/backends/pebble_cache/pebble_cache_test.go
enterprise/server/util/pebble/pebble.go
server/util/compression/compression.go

The changes to compression.NewZstdDecompressingReader get most of the benefit here, making small reads in benchmarks 20% faster. This is because io.Pipe() causes every read and write to block on a channel, and it requires creating another goroutine.
Using io.ReadFull instead of io.Copy is mostly about reducing allocations and memory copying. This improves performance by 2-4%.
I'm not sure if real world impact of these changes will be as high, since the pebble parts of the code seem relatively more heavy weight in the real world profiles compared to benchmark profiles.
Here are the benchmarks from `//enterprise/server/backends/pebble_cache:pebble_cache_test`:
```
goos: linux
goarch: amd64
│ /tmp/getmulti/base │      /tmp/getmulti/zstdreader       │ …
```

Optimize pebble reads

---

go.mod
go_deps.MODULE.bazel
server/util/monitoring/BUILD
server/util/monitoring/monitoring.go

https://github.com/buildbuddy-io/buildbuddy-internal/issues/4736
Export metrics registered with VictoriaMetrics in metrics endpoint too.
Dragonboat library's metrics are registered with VM.
Note: my change dropped support for zstd compression that was supported
in promhttp.Handler(). However, Both [VM's prometheus scraper](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/2f4680d8f39f5e84069dcdabb71c72bc3234c69f/lib/promscrape/client.go#L144) and prometheus's own
[scraper](https://github.com/prometheus/prometheus/blob/main/scrape/scrape.go#L812) only set gzip header. 
I pushed this change to raft-dev, and verified /metrics endpoint works and the 
dragonboat metrics were picked by vm scraper.

Export VM metrics in /metrics endpoint

---

enterprise/server/remote_execution/vfs/vfs_unix.go

There are different types of locks (POSIX/OFD) with different semantics and the fuse implementation does not have enough information to know which one is being used (!).
Thankfully if locking is not enabled in the FUSE implementation it is handled entirely by the kernel which is able to properly handle different lock types.
I'll rip out the rest of the locking code after I'm satisfied that it won't be needed anymore.

Disable locking in VFS implementation.

---

server/util/healthcheck/BUILD
server/util/healthcheck/healthcheck.go
server/util/watchdog/BUILD
server/util/watchdog/watchdog.go
server/util/watchdog/watchdog_test.go

This does not change the default behavior, except to add a new TTL counter in the statusz page.
If the --max_unready_duration flag is set, and the app is unready for longer than 30 seconds, then it will exit.

Wire a watchdog timer into healthcheck, configurable via flag

---

enterprise/server/hit_tracker_client/hit_tracker_client.go
enterprise/server/hit_tracker_client/hit_tracker_client_test.go

This should let us enqueue more updates and flush them without these RPCs getting huge (and potentially slow).

[Cache Proxy] support splitting hit-tracker RPCs

---

enterprise/server/cmd/executor/BUILD
enterprise/server/cmd/executor/executor.go
server/util/disk/disk.go
server/util/healthcheck/healthcheck.go

This adds a disk fullness healthchecker (disabled by default) and statusz page.
By enabling the disk fullness health check in conjunction with max_unready_duration, you can force executors to restart themselves if their disk is full.
Example:
```
--executor.maximum_disk_fullness=.95 --max_unready_duration=30s
```

Add a disk fullness healthchecker + statusz widget and add it to the executor

---

tools/metrics/grafana/dashboards/raft.json

https://github.com/buildbuddy-io/buildbuddy-internal/issues/4212
Added a graph for 
1. total number of ranges without range leases/leaders
2. dragonboat proposal dropped
3. dragonboat failed message connections
4. dragonboat received message dropped
5. dragonboat message send failure rate

[raft] more graphs

---

enterprise/server/remote_execution/containers/bare/BUILD
enterprise/server/remote_execution/containers/bare/bare.go
enterprise/server/remote_execution/containers/bare/bare_test.go
server/util/rexec/rexec.go

Some actions on macOS are creating temporary files in system temporary directories, which we don't clean up, causing disk usage to increase over time. Setting TMPDIR to a path that the executor cleans up should solve this.
Context: https://buildbuddy-corp.slack.com/archives/C03JL0YT6G5/p1744654261022149?thread_ts=1744401999.823709&cid=C03JL0YT6G5

Allow setting TMPDIR for bare executions

---

enterprise/server/raft/store/store.go
enterprise/server/raft/store/store_test.go

This test sometimes failed with the "the shard is not ready".
Upon investigation, this happens with the step in StartShard when we try to call
sync propose the batch request because we only set up one replica of the shard
when there are three initial members.
I removed the batch request from the StartShardRequest because this is not 
necessary for the test.
Also add more context in the returned errors in StartShard.

[raft] fix TestCleanupZombieInitialMemberNotSetUp

---

enterprise/server/util/oci/oci.go
server/http/httpclient/httpclient.go
server/remote_asset/fetch_server/fetch_server.go

Rely solely on context for timeouts.

Remove timeout parameter from httpclient.

---

enterprise/server/hit_tracker_client/hit_tracker_client.go
enterprise/server/hit_tracker_client/hit_tracker_client_test.go

I added a small benchmark in the test that enqueues 1,000,000 hits (all for the same group) asynchronously in batches of 100,000, waiting for each enqueue() call in a batch to return before proceeding to the next batch. Before this change, that took 7.26 seconds, with this change it takes 2.67 seconds (63% faster) with `--config=race --config=remote`. With `-c opt` it took 3.1 seconds before this change and about 500ms after. Interestingly, I implemented the channel approach we discussed a week or so ago and that took about the same amount of time, so there may be some other resource contention in the benchmark that's limiting further speedup in the benchmark. For now, this is at least a fair bit faster than the old approach.

Lock less aggressively in hit-tracker-client

---

enterprise/app/tap/tap.tsx

These are now separate pages in the sidebar, so the tabs are redundant (and taking up valuable real estate in the test grid, since the header is sticky).
Also tweak the page titles.

Remove tabs from Tests/Flakes pages

---

enterprise/server/action_cache_server_proxy/action_cache_server_proxy.go
server/remote_cache/action_cache_server/action_cache_server.go
server/remote_cache/action_cache_server/action_cache_server_test.go

this is admittedly a little weird.  there are two options here that i see:
1. track size in the cache proxy when the value is in the cache proxy's cache, track size in the apps when it's there instead.  this is a little weird, because we don't know if the value will match until we've actually read it, at which point we've already initialized a tracker in the app server, yada yada.
2. do what's in this pr: never track download for ac requests in the cache proxy.  this is also a little weird, but the net result is that we run no risk of double-tracking hits.  i considered this more reasonable because we literally always perform the reads in the apps under the current implementation--we _never_ put ac entries in the lookaside cache, and cut around the hit-tracking service implementations …

track full response size in action_cache_server even for client-side cache hits.

---

enterprise/server/raft/sender/sender.go
enterprise/server/raft/txn/BUILD
enterprise/server/raft/txn/txn.go

This will be re-used in a follow up PR; where I need to call SyncPropose when
setting up a new shard.

[raft] move txnCoordinator.syncPropose to sender

---

enterprise/server/raft/bringup/BUILD
enterprise/server/raft/bringup/bringup.go
enterprise/server/raft/sender/sender.go
enterprise/server/raft/store/store.go
enterprise/server/raft/store/store_test.go
enterprise/server/raft/testutil/testutil.go
enterprise/server/raft/txn/BUILD
enterprise/server/raft/txn/txn.go
proto/raft.proto

https://github.com/buildbuddy-io/buildbuddy-internal/issues/4832
Refactor to reduce the number of arguments passed into some functions in bringup
code.
Call SyncPropose after the startShard requests finished.

[raft] call sync propose to set up the new shard in a separate call

---

.bazelrc
shared.bazelrc

Consolidate bes+cache+remote configs to a new section in the shared
file.
Also moved the XCode flags into the shared file.

.bazelrc: move cache+remote configs to shared file

---

docs/config.md
docs/on-prem.md

This burned me as I spent time figuring out why the Prometheus metrics `/metrics` wasn't loading. Because monitoring is enabled by default, I believe it should work out of the box.

Add port mapping for Prometheus metrics to docs

---

enterprise/server/util/oci/BUILD
enterprise/server/util/oci/oci.go
go.mod
go_deps.MODULE.bazel

Replace docker/distribution/reference with a newer version of that
package at distribution/reference.
This helps us avoid potential compilcation error spotted while migrating
to bzlmod:
```
external/gazelle++go_deps+com_github_docker_distribution/reference/reference_deprecated.go:122:19: undefined: reference.SplitHostname
compilepkg: error running subcommand external/rules_go++go_sdk+buildbuddy__download_0/pkg/tool/darwin_arm64/compile: exit status 2
```
Example invocation:
https://buildbuddy.buildbuddy.io/invocation/708b4308-2da8-4cec-8132-c2eb9a038889#@45
`SplitHostname` was deprecated and yanked in the latest version of distribution/reference.
https://pkg.go.dev/github.com/docker/distribution/reference#SplitHostname
https://github.com/distribution/reference/commit/4894124079e525c3c3c5c8 …

oci: update distribution reference (#8931)

---

enterprise/server/raft/store/store_test.go

Add more stores when we set up the tests.
Also remove the assertion on GetRange and GetReplica. This can cause test to
flake because when the rd changes, RemoveRange will be called. If the assertion
runs between RemoveRange and AddRange, it will fail.

[raft] fix flakiness in a zombie test

---

enterprise/server/raft/store/store_test.go

This reduces timeout error in tests: https://github.com/buildbuddy-io/buildbuddy-internal/issues/4192

[raft] use more stores in CleanupZombieNonVoter

---

enterprise/server/raft/store/store.go
enterprise/server/raft/store/store_test.go

The current code can sometimes causes one zombie stuck in the transfer
leadership step when we remove zombies that are not in the meta range.
This is because, when we determine the target replica id for leader transfer, we
are using task.shardInfo.Replicas, which can be stale when we are removing three
zombies simultaneously on 3 machines.
If we really want to make this work, we probably need to call get membership to
get the current replicas to find a target. This can make the code more
complicated and I don't think explicit leadership transfer is a necessary step 
anyway.
Also, explicitly disable driver in some zombie test. And set up three stores instead of 2 to reduce timeout errors.

[raft] remove transfer leadership step from removeZombie

---

MODULE.bazel
buildpatches/rules_webtesting.patch
go_deps.MODULE.bazel

rules_webtesting does not have a valid git tag for Go modules, so the
version we are using in go.mod and the actual version would mismatch
each others.
This mismatch would result in several warning in the past, which we have
ignored. However, we do want to elevate this class of issue to error so
that we can catch mismatched Go dependencies earlier.
Patch the bzlmod version of rules_webtesting to be consistent with the
go.mod version. Increase the strictness of go_dep extension to fail when
transitive go deps use a different version than the one in our go.mod.
Ref: https://github.com/bazelbuild/rules_webtesting/issues/452

bzlmod: patch rules_webtesting and force stricter go_dep

---

dockerfiles/rbe-ubuntu24-04/Dockerfile
enterprise/server/remote_execution/platform/platform.go
enterprise/server/workflow/service/service.go

Was mostly able to copy the 22.04 image and it "just works." The only thing different is that it's using a newer version of docker, since v24 no longer exists in the repositories for ubuntu 24.04. I pushed and tested the image and made sure docker-in-firecracker still works (using `bb execute --exec_properties=container-image=docker://gcr.io/flame-public/rbe-ubuntu24-04:latest --exec_properties=workload-isolation-type=firecracker --exec_properties=init-dockerd=true -- docker run --rm busybox echo Hello`)

Add rbe-ubuntu24-04 image

---

shared.bazelrc

- When testing with `--config=remote`, allow running tests tagged with `docker` or `bare`, since these tests work fine on RBE. (Note, these tests only work when running with _authenticated_ RBE, which should be the case since we're targeting the `buildbuddy` subdomain. If running against _unauthenticated_ RBE, bare execution does not work since the `bare` pool requires being authenticated to the BB org, and most docker-tagged tests won't work since recycle-runner is not supported for anon executions)
- Exclude "performance" test tag (benchmarks) by default when running with `--config=remote` to discourage running benchmarks remotely. RBE doesn't provide a good environment for benchmark testing (yet?)

Make test_tag_filters more sane when running remotely

---

enterprise/server/hit_tracker_service/BUILD
enterprise/server/hit_tracker_service/hit_tracker_service.go
enterprise/server/hit_tracker_service/hit_tracker_service_test.go
proto/BUILD
proto/hit_tracker.proto

To prepare for tracking local AC requests in the proxy when we skip the remote cache

Support tracking AC and upload requests in hit tracker service

---

enterprise/server/remote_execution/execution_server/execution_server.go

Since we added finer-grained updates in WaitExecution (PULLING_CONTAINER_IMAGE, DOWNLOADING_INPUTS etc.) we're doing a lot more "WaitExecution" logs which add a lot of noise. This PR attempts to denoise the logs a bit.

Reduce noise from WaitExecution logs

---

tools/populate_tests.sh

Makes a temp bazel workspace and repeatedly adds git commits with new tests, running a bazel build with each commit. Each commit is made in a feature branch, to allow testing branch filtering.

Add a little script to populate test history locally

---

enterprise/app/tap/BUILD
enterprise/app/tap/flakes.tsx
enterprise/app/tap/grid.tsx
enterprise/app/tap/tap.tsx
proto/target.proto
server/build_event_protocol/target_tracker/target_tracker_test.go
server/target/target.go
server/target/target_test.go
server/util/clickhouse/clickhouse.go

We already store branch name in the DB but don't allow filtering on it. This PR allows us to filter by branch.
Queries with branch filters enabled should be roughly as fast as what we've got today since we're scanning the same number of rows. We could speed these up in the future by adding a data-skipping index on branch name.
https://github.com/user-attachments/assets/14cc4c42-2b6e-42e2-9f8a-0ffaecc71a28

Allow filtering tests and flakes by branch name

---

app/invocation/invocation.css
app/invocation/invocation.tsx
app/invocation/invocation_artifacts_card.tsx
app/invocation/invocation_exec_log_card.tsx
app/invocation/invocation_targets.tsx

The `.loading` class includes `height: 100%` - use `loading-slim` for a few places where we don't want this.

Use inline loading components for invocation tabs

---

enterprise/server/hit_tracker_client/hit_tracker_client_test.go
server/testutil/testenv/testenv.go

Also remove hand-rolled `require.Eventually` function.

Add a benchmark for hit_tracker_client.Enqueue

---

cli/parser/BUILD
cli/parser/options/BUILD
cli/parser/options/options.go
cli/parser/parser.go

This moves the `Option` and `Definition` struct definitions and accompanying functions out of the `parser.go` file, which is already quite large, and into their own file. It also abstracts the `Definition` somewhat, preventing most access to the definition fields post-creation and allowing easy access to those accessor functions via the Option. These changes are in preparation for making the `Option` `struct` an `interface` instead, which will allow differentiation of `Option`s, and move a lot of the logic identifying types of options out of the parsing logic and into formalized types that confirm to the `Option` interface.
Most of the line changes are just moving code or renaming.

Move cli `Option` and `Definition` into their own file

---

.bazelrc
enterprise/server/test/integration/remote_bazel/BUILD

The compile and link actions should not need access to BuildBuddy Secret
values. It's an execution time dependency.
Shift the tag exclusion from build -> test.

integration/remote_bazel: only include secrets in test actions

---

shared.bazelrc

* `--test_arg=-test.failfast` can be achieved in a more language-agnostic way by passing `--test_runner_fail_fast` instead (thanks @fmeum for pointing this out)
* Seems OK to set `--config=race` even when deflaking non-go tests (which I think is just the TypeScript tests - we have very few of these, and they're usually not flaky) - so, just remove the `--config=deflake-go` config and have a single `--config=deflake`

Make deflake config language-agnostic

---

.github/workflows/build-linux-arm64-github-release-artifacts.yaml
shared.bazelrc

The executor arm64 release binaries are being built for x86; this should fix that.

Remove RBE config from --config=release

---

enterprise/server/remote_execution/snaploader/BUILD
enterprise/server/remote_execution/snaploader/snaploader_test.go
enterprise/server/remote_execution/snaputil/snaputil.go
enterprise/server/remote_execution/snaputil/snaputil_test.go

Previously, there was no way to disable local snapshot sharing, which required more setup for tests and has caused some issues testing locally for me when fast copy performance is not good

[SS] Respect enable_local_snapshot_sharing flag

---

.bazelrc
shared.bazelrc

Rename the default platform config to indicate that it's specific
to WORKSPACE setup. Move the actual flag back to <repo>/.bazelrc so that
we can migrate each repo to bzlmod independently from each others.

bazelrc: rename platform configs

---

enterprise/server/cmd/ci_runner/main.go

If we encounter a retryable error, log a message that we're retrying, and also give a little bit more time for logs to flush so that we can see why the retry is happening. Context: https://buildbuddy-corp.slack.com/archives/C04KPGQV0HH/p1745272715570709?thread_ts=1745247080.715669&cid=C04KPGQV0HH

ci_runner: flush logs before retrying errors

---

enterprise/server/auth/auth.go
enterprise/server/githubauth/githubauth.go
enterprise/server/oidc/oidc.go
enterprise/server/saml/saml.go
server/http/interceptors/interceptors.go
server/libmain/libmain.go
server/testutil/webtester/webtester.go

When clicking "Logout" we show an error banner to the user. This is a tad confusing because we logged out successfully. It also means that we have to opt out some of our webdriver tests (which test the logout behavior) from a [new assertion](https://github.com/buildbuddy-io/buildbuddy/pull/8128) that makes sure we don't display error banners during tests.
This PR fixes the logout handler to stop returning an error, so that we will no longer show the error banner. Instead, we'll just redirect to the login page. I considered showing a "success" banner in this case but I don't think it's really necessary since it's pretty clear the user is logged out, as they're now seeing the login page.

Don't show an error banner after successfully logging out

---

enterprise/server/remote_execution/execution_server/execution_server.go
enterprise/server/remote_execution/execution_server/execution_server_test.go

The timeline data adds a lot of noise when using tools like `replay_action` which print out the ExecutedActionMetadata. The timeline data can also be somewhat big, and bazel doesn't care about it, so it's adding unnecesary network transfer.

Trim usage timelines from cached ActionResults

---

cli/test/integration/cli/cli_test.go
cli/testutil/testcli/testcli.go

Introduce a new BazelCommand wrapper around existing Command func so
that we can inject the 2 --nosystem_rc and --nohome_rc flags.
This enable us to run these tests locally on MacOS while having a
$HOME/.bazelrc file setup.

testcli: Ignore system and home rc files

---

server/target/target.go

We fetch target statuses commit-by-commit, but the returned target statuses within each commit aren't sorted in a stable way which causes the tests to be flaky (I added `label` in a previous PR which partly addressed this; this PR also adds sorting on `start_time_usec`).
I don't believe this should have any impact on query performance since it's applying the ordering to the final results from the inner query (which is filtering on commit_sha and not these other fields) but it would be great if someone could double-check my understanding on this :D

Deflake target_test

---

enterprise/server/cmd/ci_runner/main.go

The initial branch name doesn't really matter since we always fetch git refs from upstream, but git prints a verbose warning if we don't set one explicitly, which is a little annoying.

Suppress git init branch name warning

---

cli/parser/BUILD
cli/parser/arguments/BUILD
cli/parser/arguments/arguments.go
cli/parser/options/BUILD
cli/parser/options/options.go
cli/parser/parser.go

Abstracts out the `Option` type from a struct to an interface so that we can make custom option types that handle the logic for the calls surfaced by the `Option` interface individually.

Abstract the option type in the CLI

---

server/util/healthcheck/BUILD
server/util/healthcheck/healthcheck.go

- Switch from `fmt.Println()` to `log.Infof()` so that shutdown logs are handled consistently, using structured logging if enabled. There is a comment about the log output being wonky due to being called in a signal handler, but using `log.Infof` seems to work just fine when I tested locally, and don't see why the log output would be wonky since the signal handler is just a regular goroutine, but lmk if I'm missing something.
- When running in a terminal, print a newline when receiving a signal to work around the `^C` echoed to the terminal from causing extra indentation and making the logs harder to read. (I suspect the "wonky" comment might have been referring to this echoing behavior, but the same problem happens with `log.Infof` so I'm not sure.)
- If the user presses Ctrl+C several …

Improve signal handling/logging in healthchecker

---

enterprise/server/raft/rbuilder/rbuilder.go
enterprise/server/raft/replica/replica.go
enterprise/server/raft/replica/replica_test.go
proto/raft.proto

https://github.com/buildbuddy-io/buildbuddy-internal/issues/4843
I added a boolean in BatchCmdRequest to indicate if the entire mapped range should be locked. This is because we don't need to lock the entire range when we prepare every transaction; we only need to do that for the left range during the split transaction.

[raft] allow the replica to lock the entire range

---

enterprise/server/workflow/service/service.go

Saw a warning log about this. Context: https://github.com/bazelbuild/remote-apis/blob/main/build/bazel/remote/execution/v2/remote_execution.proto#L551

Set platform in Action as well as command for workflow actions

---

server/remote_asset/fetch_server/fetch_server.go
server/remote_cache/cachetools/cachetools.go

We used to (configurably) apply upload compression only to `UploadFile`, not e.g. `UploadBlob`. Make this more principled by enabling compression on more code paths, but only if the file size is large enough to be worth it (see the linked Bazel discussion).
Always enable compression for the remote asset API as files fetched from the internet are overwhelmingly likely to be larger than 100 bytes anyway.

Compress uploads more consistently

---

enterprise/server/ociregistry/ociregistry.go
enterprise/server/ociregistry/ociregistry_test.go
server/testutil/testregistry/testregistry.go

Docker Hub does not (or does not always) return a Docker-Content-Digest header for layers.
That's fine, you have to know a layer's digest to even request it.
However, writing layers to the cache depend on the Docker-Content-Digest header appearing in the response from the upstream registry.
This change makes sure the test registry does not return Docker-Content-Digest for blobs (layers), and patches the caching code to not rely on this header.

[oci registry] do not rely on Docker-Content-Digest header for caching layers

---

enterprise/server/remote_execution/containers/firecracker/BUILD
enterprise/server/remote_execution/containers/firecracker/firecracker_test.go
enterprise/server/remote_execution/snaploader/BUILD
enterprise/server/remote_execution/snaploader/snaploader.go
enterprise/server/remote_execution/snaputil/BUILD
enterprise/server/remote_execution/snaputil/snaputil.go

Reverts buildbuddy-io/buildbuddy#9000
When looking at the metrics, I was surprised to see "local-only" requests already being made. This was only intended for snapshots, but is currently being applied to FC RBE actions run on proxies. I'll re-apply the PR to only add the header for workflows / remote bazel

Revert "[SS] Skip accessing the remote cache when proxy is enabled"

---

.bazelrc

I could not get a local build to work with this flag set. `--config=local` is only enabling BES/cache, so I think we don't need to set  up platforms/toolchains.

Remove platform setting from --config=local

---

cli/remotebazel/remotebazel.go

Follow up from https://github.com/buildbuddy-io/buildbuddy/pull/9037

[RB] Automatically set GIT_BASE_BRANCH for github action runners running remote bazel

---

enterprise/server/remote_execution/vfs/BUILD
enterprise/server/remote_execution/vfs/vfs_test.go
enterprise/server/remote_execution/vfs/vfs_unix.go
enterprise/server/util/vfs_server/vfs_server.go
proto/vfs.proto

overlayfs uses Mknod to create regular files and character files for "whiteouts". It also uses the rename flag RENAME_WHITEOUT to leave a whiteout marker on renames.

vfs: add some stuff neededed by overlayfs

---

enterprise/server/action_cache_server_proxy/action_cache_server_proxy.go
enterprise/server/action_cache_server_proxy/action_cache_server_proxy_test.go
enterprise/server/cmd/cache_proxy/cache_proxy.go
enterprise/server/content_addressable_storage_server_proxy/content_addressable_storage_server_proxy.go
enterprise/server/content_addressable_storage_server_proxy/content_addressable_storage_server_proxy_test.go
server/environment/environment.go
server/real_environment/real_environment.go

Benchmark results on my local machine (from `benchstat`):
```
goos: linux
goarch: amd64
│   old.txt   │               new.txt               │
│   sec/op    │   sec/op     vs base                │
FindMissingBlobs-16   313.4µ ± 8%   301.1µ ± 9%        ~ (p=0.280 n=10)
BatchReadBlobs-16     377.9µ ± 4%   236.6µ ± 7%  -37.39% (p=0.000 n=10)
BatchUpdateBlobs-16   601.8µ ± 6%   461.1µ ± 6%  -23.38% (p=0.000 n=10)
GetTree-16            744.4µ ± 7%   256.3µ ± 6%  -65.56% (p=0.000 n=10)
geomean               479.9µ        302.9µ       -36.88%
│    old.txt    │               new.txt                │
│     B/op      │     B/op      vs base                │
FindMissingBlobs-16    46.50Ki ± 0%   46.52Ki ± 0%        ~ (p=0.590 n=10) …
```

[Cache Proxy] Use AC/CAS RPC server interfaces directly instead of invoking client interfaces via self RPC

---

enterprise/server/remote_execution/workspace/workspace.go
server/cache/dirtools/dirtools.go
server/cache/dirtools/dirtools_test.go

This fixes some log spam since these adds can never succeed.

vfs: don't try to add files to filecache when vfs is enabled

---

enterprise/server/hit_tracker_client/BUILD
enterprise/server/hit_tracker_client/hit_tracker_client.go
enterprise/server/hit_tracker_client/hit_tracker_client_test.go

DNM until https://github.com/buildbuddy-io/buildbuddy/pull/9001 is released

Add hit tracking for local-only AC requests in the cacheproxy

---

tools/metrics/grafana/dashboards/cache-proxy.json

Update cache proxy graphs to include proxy request type label

---

enterprise/server/raft/cache/BUILD
enterprise/server/raft/cache/cache_test.go
enterprise/server/raft/store/BUILD
enterprise/server/raft/store/store_test.go
server/testutil/quarantine/BUILD
server/testutil/quarantine/quarantine.go

By default, we want to skip running flakey tests locally and in CI, while preserving the option to choose to run them.
This change introduces `SkipQuarantinedTest`, which will skip the current test unless `RUN_QUARANTINED_TESTS` environment variable is set to `true`.
If people are comfortable with this change and approach, I will quarantine other flakey tests. From that point on, we will have zero tolerance for flakes: either fix them or delete them.

Introduce SkipQuarantinedTest; quarantine 1 cache_test test and 4 store_test tests

---

enterprise/server/test/integration/remote_bazel/BUILD
enterprise/server/test/integration/remote_bazel/remote_bazel_test.go

The flakiness occurs because we redirect stdout when invoking bazelisk in the CLI, and simultaneously the health check from the local server also tries to write to stdout. Run the local server the CLI in separate processes to prevent this

Fix flakiness in remote bazel test

---

enterprise/server/raft/cache/cache_test.go

This change quarantines 4 additional tests in cache_test.
In total, 5 out of 6 tests in this suite will be quarantined.
Tests are selected for quarantine if they
* appear at least twice in [the past 30 days of flakes for the cache_test suite](https://app.buildbuddy.io/tests/?target=%2F%2Fenterprise%2Fserver%2Fraft%2Fcache%3Acache_test&days=30#flakes), or
* fail or timeout once during a run of bazel  test //enterprise/server/raft/cache:cache_test --config=remote --config=race --nocache_test_results --runs_per_test=16.

Quarantine cache_test tests

---

cli/parser/parser.go

To speed up remote bazel, let's swap back to using a static list of bazel commands until / unless we can get `bazel help` output without ever starting a bazel server (which seems unnecessary).

Use static list of bazel commands

---

enterprise/server/test/integration/ci_runner/BUILD
server/testutil/testserver/testserver.go

This change
* gives the `ci_runner_test` suite 3 compute units
* bumps the size to medium (meaning more RAM and a default timeout of 5 minutes)
Either change made alone still produces flakes with
```
bazel test //enterprise/server/test/integration/ci_runner:ci_runner_test --config=remote --config=race --nocache_test_results --runs_per_test=16
```

reduce ci_runner_test flakes

---

cli/parser/parser.go

Move the conditional that governs early return when attempting to canonicalize non-bazel args earlier, to before the parser is potentially generated.

Skip potential parser generation when attempting to canonicalize non-bazel commaneds (e.g. `remote`)

---

enterprise/server/remote_execution/cgroup/cgroup.go
enterprise/server/remote_execution/cgroup/cgroup_test.go
enterprise/server/remote_execution/containers/ociruntime/BUILD
enterprise/server/remote_execution/containers/ociruntime/ociruntime.go
enterprise/server/remote_execution/containers/ociruntime/ociruntime_test.go

- Recursively enable ancestor cgroup controllers if they are not already enabled. `crun` effectively does this already, but only after our first failed attempt to enable the controllers. This results in warnings being printed to the logs on executor startup (when it runs the warmup container). Fixes https://github.com/buildbuddy-io/buildbuddy-internal/issues/4842
- Use `--keep` to prevent the runtime from immediately deleting the container cgroup when the task completes. This removes the need for the parent/child setup and also is a prerequisite for being able to detect when the `pids.max` limit exceeded, since pid events are only reported to the child cgroup which currently is being cleaned up before we have the chance to read from it. This should also let us get more accurate resource …

Simplify and improve ociruntime cgroup setup

---

tools/metrics/grafana/dashboards/cache-proxy.json

This change gets rid of the `kubepool` template variable and replaces it with a `node` template variable which is populated by querying `kube_pod_info` and extracting the node name for nodes running pods called `cache-proxy.*`. This new variable is used in a single row of per-node metrics, defaulting to all nodes. This approach works for GKE, EKS, and SJC.
Before:
After:
Related issues: https://github.com/buildbuddy-io/buildbuddy-internal/issues/4851

[Cache Proxy] fix node graphs in dashboard

---

enterprise/server/remote_execution/containers/ociruntime/BUILD
enterprise/server/remote_execution/containers/ociruntime/ociruntime_test.go

I'm a little hesitant on this one, since this is such a critical path.
TestSignal has a clear race condition -- both Signal() and Run() touch c.cid. If we expect to be able to call those functions from separate goroutines, we need to synchronize access.

quarantine ociruntime_test

---

enterprise/server/test/integration/remote_bazel/remote_bazel_test.go

This will make debugging failures easier

Print the logs from the remote bazel run in the remote bazel integration tests

---

enterprise/server/remote_execution/execution_server/execution_server.go
enterprise/server/remote_execution/execution_server/execution_server_test.go
enterprise/server/test/integration/remote_execution/rbeclient/rbeclient.go
enterprise/server/test/integration/remote_execution/rbetest/rbetest.go
enterprise/server/test/integration/remote_execution/remote_execution_test.go
enterprise/tools/rbeperf/rbeperf.go
server/interfaces/interfaces.go

`skip_cache_lookup` should not prevent action merging (it currently does), but `do_not_cache` should (it currently doesn't). The former is used by Bazel when an action result is discovered to be invalid, but that can't have happened while the merged execution is still executing. The latter powers `--runs_per_test` and thus won't be useful to detect flakes if action merging is used.
Since `--runs_per_test` sets both fields to `true`, we did correctly disable action merging for it, but for the wrong reason. Other code paths may not do this though.
See https://github.com/bazelbuild/remote-apis/commit/cfe8e540cbb424e3ebc649ddcbc91190f70e23a6 for the intended semantics.

Fix action merging handling of `do_not_cache` and `skip_cache_lookup`

---

server/util/urlutil/urlutil.go
server/util/urlutil/urlutil_test.go

It's currently 0.5% of app CPU.
```
goos: linux
goarch: amd64
│  domainbase   │            domainindex             │
│    sec/op     │   sec/op     vs base               │
GetDomain/buildbuddy.io-24           68.030n ± 21%   6.869n ± 1%  -89.90% (p=0.000 n=9)
GetDomain/app.buildbuddy.io-24       83.770n ± 14%   6.023n ± 3%  -92.81% (p=0.000 n=9)
GetDomain/foo.app.buildbuddy.io-24   89.880n ± 30%   5.944n ± 3%  -93.39% (p=0.000 n=9)
GetDomain/app.localhost.io:8080-24   57.740n ± 28%   8.331n ± 3%  -85.57% (p=0.000 n=9)
geomean                               73.74n         6.728n       -90.88%
│ domainbase │              domainindex              │
│    B/op    │   B/op     vs base                    │
GetDomain/buildbuddy.io-24 …
```

Make urlutil.Domain 10x faster

---

server/remote_cache/byte_stream_server/byte_stream_server.go

The idea here is to move as much of the business logic of handling ByteStream writes as possible into the `WriteState` struct in `byte_stream_server.go`, making the actual `Write()` function only responsible for pulling frames off of the write stream, and sending them to the `WriteState`. This way, the `WriteState` can be used directly in `byte_stream_server_proxy` without loss of functionality. See https://github.com/buildbuddy-io/buildbuddy/pull/9106 for how this will be used.
The alternative to this is to do the splitting at the gRPC level, but that ends up being a little more complicated IMO due to the async nature of the streams.
Related issues: https://github.com/buildbuddy-io/buildbuddy-internal/issues/4782

Refactor ByteStreamServer.Write() to make it easier to use directly in ByteStreamServerProxy

---

enterprise/server/scheduling/priority_task_scheduler/BUILD
enterprise/server/scheduling/priority_task_scheduler/priority_task_scheduler.go
enterprise/server/scheduling/scheduler_server/BUILD
enterprise/server/scheduling/scheduler_server/scheduler_server.go
proto/scheduler.proto

This allows the executor to set the JWT on outgoing RPCs. Having this on the LeaseTask RPC is necessary to get experiments to trigger by group ID.

Send JWT in EnqueueTaskReservationRequest

---

enterprise/server/ociregistry/ociregistry.go
server/metrics/metrics.go

Each time the OCI registry fetches a manifest or layer from the cache, it can perform up to three fetches:
1. Fetch an ActionResult from the AC
2. Fetch metadata from the CAS
3. (Only needed for serving GET requests) Fetch contents from the CAS
When the OCI registry uploads a manifest or layer to the cache, it always performs three uploads:
1. Upload metadata to CAS
2. Upload contents to CAS
3. Upload an ActionResult to AC
This change counts hits, misses, and uploads for all AC and CAS fetches and uploads.

[oci registry] track AC and CAS hits, misses, and uploads

---

enterprise/server/raft/leasekeeper/leasekeeper.go

This can cause test-flakiness.
In tests, we often want to find the store with the range leases. There are small
windows of time where two stores both hold leases, with one of them should not
have it hold. In these cases, if we grab the store which should hold the lease,
it can cause the test to fail.

[raft] haveLease should return false when it shoudn't have lease

---

enterprise/server/raft/store/BUILD

store_test sometimes failed with shard is not ready. When I turned on the logs for dragonboat, there are LocalTicks warnings that indicates that nodes are overloaded. The execution page showed high IO pressure stall duration.

[raft] use firecracker for store_test

---

proto/execution_stats.proto

target_label will be used immediately (in a WIP PR); planning to use executor_hostname in a short followup.

Add target_label and executor_hostname to client execution proto

---

server/environment/environment.go
server/interfaces/BUILD
server/interfaces/interfaces.go
server/real_environment/real_environment.go
server/remote_cache/byte_stream_server/byte_stream_server.go

This is just some cleanup to try and make https://github.com/buildbuddy-io/buildbuddy/pull/9106 a bit smaller and easier to digest.
I also realized I moved the big ole comment about `Write()` to the wrong place in https://github.com/buildbuddy-io/buildbuddy/pull/9105, so fixed that here.

Make ByteStream WriteHandler an interface and put in Environment

---

enterprise/server/scheduling/task_leaser/task_leaser.go

We saw an instance of `Error updating lease for task: "TASK_ID": rpc error: code = Internal desc = stream terminated by RST_STREAM with error code: INTERNAL_ERROR`. Make sure to retry these. Also, elevate these errors to ERROR level to make them stand out more in the logs, since these errors are the root cause if a task is canceled.

Retry internal errors on task lease stream

---

cli/arg/arg.go
cli/cmd/bb/bb.go
cli/flaghistory/BUILD
cli/flaghistory/flaghistory.go
cli/login/login.go
cli/runscript/runscript.go
cli/sidecar/sidecar.go
cli/tooltag/tooltag.go

Switch to using `arg.Append` instead of `append(args, ...)` to append to bazel args. This helps protect us from cases where there may be a `--` in the args we are appending to, and also abstracts the call so we can use real parsing in the future to do appending.
Also enforces `JoinExecutableArgs` not adding an additional `--` if one already exists.

Use `arg.Append` to append to cli bazel args

---

enterprise/server/scheduling/task_leaser/task_leaser.go

Whenever I see this error in the logs, I always have to check the source to see what it means :face_with_spiral_eyes:

Clarify task lease error

---

enterprise/server/raft/store/store_test.go

- add one more store to avoid split brain
- When we check the number of members, we don't want to check the store where
the replica is removed. Most of time this won't happen because
- we call remove the replica on the store with the lease
- we don't remove the replica that's the leader
In some cases, however we did end up remove the leader replica (when there is
a leader transfer after we call RemoveReplica) and when we try to verify the
membership, the store we get is the one with the removed replica and the
getmembership will return 0 instead of 2.  
- Remove the test from quarantine. 
I ran this test twice with --runs_per_test=500
https://app.buildbuddy.io/invocation/df9817b1-09f6-4d6c-b171-bd63dc3ba506
https://app.buildbuddy.io/invocation/8d842a5c-5d10-437b-87c5-60a40353e0b7

[raft] TestRemoveNodeFromCluster: add one more node

---

enterprise/server/remote_execution/containers/firecracker/firecracker.go
enterprise/server/remote_execution/snaploader/snaploader.go
server/metrics/metrics.go

Before applying the [change to only cache multiple snapshots on the same branch locally](https://github.com/buildbuddy-io/buildbuddy/pull/9084), add some logging and metrics to evaluate if this would be impactful, or if any modifications to the logic are necessary
The implemented logic is:
* If a given branch does not have a remote snapshot, we will write one remotely
* If it already has a remote snapshot, we will only write subsequent snapshots locally
* For the default/master snapshot, we will always write remotely

[SS] Add logs to test reducing remote snapshot writes

---

enterprise/server/remote_execution/containers/firecracker/BUILD
enterprise/server/remote_execution/containers/firecracker/firecracker_test.go
enterprise/server/remote_execution/snaploader/BUILD
enterprise/server/remote_execution/snaploader/snaploader.go
enterprise/server/remote_execution/snaputil/BUILD
enterprise/server/remote_execution/snaputil/snaputil.go

This reverts commit fd32eb407b14cdeb56dad1b004965b52ccb51958.
Last week, I noticed in the metrics we had some SkipRemote requests recorded in the cacheproxy. I only expected to see SkipRemote requests coming from workflows, which are currently not running with the proxy, so I reverted the PR out of caution.
After looking into it more, I think those are coming from requests for the snapshot version. Firecracker RBE actions only save snapshots locally, but they still request version data from the remote cache.
The first commit in this PR is the change that was reverted. In the second commit, I remove SkipRemote from requests for the snapshot version, so we'll always save that in the remote cache. This will guarantee that any version invalidations are applied universally

Reinstate "[SS] Skip accessing the remote cache when proxy is enabled" (#9072)

---

enterprise/server/byte_stream_server_proxy/BUILD
enterprise/server/byte_stream_server_proxy/byte_stream_server_proxy.go
enterprise/server/byte_stream_server_proxy/byte_stream_server_proxy_test.go
enterprise/server/cmd/cache_proxy/cache_proxy.go
enterprise/server/content_addressable_storage_server_proxy/content_addressable_storage_server_proxy_test.go
enterprise/server/remote_execution/containers/firecracker/firecracker_test.go
server/environment/environment.go
server/real_environment/real_environment.go

This changes the ByteStreamServerProxy to use the `Read()`, `BeginWrite()`, and `WriteState.Write()` functions directly, the latter two of which were introduced in https://github.com/buildbuddy-io/buildbuddy/pull/9105.
```
goos: linux
goarch: amd64
│ /home/iain/old.txt │         /home/iain/new.txt          │
│       sec/op       │   sec/op     vs base                │
Read-16          404.2µ ±  7%   226.6µ ± 5%  -43.94% (p=0.000 n=25)
Write-16         665.7µ ± 10%   477.9µ ± 6%  -28.22% (p=0.000 n=25)
geomean          518.8µ         329.1µ       -36.56%
│ /home/iain/old.txt │          /home/iain/new.txt          │
│        B/op        │     B/op      vs base                │
Read-16          149.2Ki ± 0%   104.7Ki ± …
```

Make ByteStreamServerProxy call ByteStreamServer directly

---

tools/metrics/grafana/dashboards/buildbuddy.json

The HTTP graphs escaped their row at some point (see screenshot). This puts them back where they belong.

Put HTTP graphs back in their row by default

---

app/invocation/cache_requests_card.tsx
app/invocation/invocation.css

For some invocations recently I've noticed that when changing the scorecard query, there is a significant delay before the results are updated, with no loading indicator shown. This PR fixes that.
https://github.com/user-attachments/assets/7fdc5cb1-4ac8-43b3-b369-85e0ddf91d84

Add loader when changing scorecard query

---

enterprise/server/byte_stream_server_proxy/byte_stream_server_proxy.go

Addressing Brandon's comments on https://github.com/buildbuddy-io/buildbuddy/pull/9106

ByteStreamServerProxy: handle EOF errors and separate reading and stats-recording logic in Read()

---

server/util/compression/BUILD
server/util/compression/compression_test.go

This change adds a test that takes all the publicly available zstd compressors (`CompressZstd` and `NewZstdCompressingReader`) and zstd decompressors (`DecompressZstd`, `NewZstdDecompressor`, `NewZstdDecompressingReader`) and makes sure that compressing and decompressing through each pair produces the same string.
This change also removes `Test_NewZstdDecompressingReader`, as `TestLossless` is a superset of that test.
I'm about to introduce `NewZstdCompressingWriter` in another change, and I want to be able to test that it too is lossless.

Test that zstd compression and decompression is lossless

---

enterprise/server/test/integration/remote_execution/remote_execution_test.go

Under load, the default max-wait of 5s isn't enough to guarantee affinity routing.

Deflake affinity routing tests

---

cli/cmd/bb/bb.go
cli/parser/BUILD
cli/parser/arguments/arguments.go
cli/parser/options/options.go
cli/parser/parsed/BUILD
cli/parser/parsed/parsed.go
cli/parser/parser.go
cli/parser/parser_test.go
cli/setup/setup.go

This PR primarily adds types to manage parsed args. It additionally removes the need for separating canonicalization of startup args from canonicalization of other args. Many of the methods added are intended for use once we begin passing `ParsedArgs` types around instead of `[]arg` slices. Finally, it adds the `common` and `always` "commands" to non-startup options to make config expansion more straightforward.

Add and use new parsed args types within the `parser` package

---

enterprise/server/raft/driver/driver.go
enterprise/server/raft/replica/replica.go
enterprise/server/raft/replica/replica_test.go
enterprise/server/raft/store/store.go
enterprise/server/raft/store/store_test.go

repl.RangeDescriptor requires a Clone() which is not as efficient as
store.GetRange().
The downside of using store.GetRange() is that between RemoveRange() and
AddRange() there is a gap where GetRange() can return nil. This is not addressed
in this PR.

[raft] use store.GetRange instead of repl.RangeDescriptor()

---

enterprise/server/raft/sender/sender.go
enterprise/server/raft/store/store.go
enterprise/server/raft/store/store_test.go
proto/raft.proto

https://github.com/buildbuddy-io/buildbuddy-internal/issues/4910
Added a staging field in range descriptor.
When we add a replica, we will 
1. add to the staging field in range descriptor
2. start the shard as a non-voter, catch up, promote to voter
3. move the replica descriptor from staging to regular replica descriptors
In the sender, when we try replicas, we will also try staging replicas, so that 
we won't ended up fail the writes with no lease found for replicas when the
leader is moved to the newly added replica before the range descriptor is
updated.
Also, fixed some issues with AddNodeToCluster tests:
- disable driver
- add s3 to the candidate stores when we try to get the store with range lease.
The AddNodeToCluster tested succeeded with 2 500 runs: …

[raft] Add staging replica descriptors in range descriptor

---

enterprise/server/backends/pebble_cache/pebble_cache.go
enterprise/server/backends/pebble_cache/pebble_cache_test.go

A common cause of flake in `pebble_cache_test` is "LRU not making progress" errors.
This change removes the hardcoded 3-second limit on making progress on each partition in favor of a cancelable context.

[pebble cache] pass timeout to TestingWaitForGC

---

server/util/redact/redact.go
server/util/redact/redact_test.go

Fixes [internal issue 4912](https://github.com/buildbuddy-io/buildbuddy-internal/issues/4912)

redact sensitive env vars from action_env

---

enterprise/app/settings/user_github_link.tsx
proto/buildbuddy_service.proto
proto/github.proto
server/buildbuddy_server/buildbuddy_server.go
server/capabilities_filter/capabilities_filter.go

The current RPC requires `Admin` role (since it can unlink the account that is linked to the org), which prevents `Developer` users from unlinking their GitHub account. Add a new RPC that only requires an authenticated user to call (since it only affects the User entity).

Add separate RPC to unlink user-level GH token

---

enterprise/server/remote_execution/vfs/vfs_unix.go

I don't know how to write a simple test for this. There doesn't seem to be a way for user space code to exercise Lookup w/o also calling GetAttr.
overlayfs is likely able to do it because it's running in the kernel and is able to use lower-level APIs. Perhaps the only option is to add an overlayfs test to vfs_test?

vfs: refresh attrs in Lookup if needed

---

enterprise/server/hostedrunner/hostedrunner.go

Context: https://buildbuddy-corp.slack.com/archives/C04S4M5U3BK/p1746470513290689?thread_ts=1746470374.153659&cid=C04S4M5U3BK

Set dockerInit=true on remote bazel commands that don't use firecracker

---

cli/parser/options/options.go
cli/parser/parser_test.go

This was just falling through to a `BoolOrEnumOption`, which works in most cases, but not all.

Actually use the `starlarkOption` type

---

enterprise/server/byte_stream_server_proxy/byte_stream_server_proxy.go
enterprise/server/byte_stream_server_proxy/byte_stream_server_proxy_test.go
enterprise/server/cmd/cache_proxy/cache_proxy.go
enterprise/server/content_addressable_storage_server_proxy/content_addressable_storage_server_proxy_test.go
enterprise/server/remote_execution/containers/firecracker/firecracker_test.go
server/environment/environment.go
server/real_environment/real_environment.go

This PR reverts: https://github.com/buildbuddy-io/buildbuddy/pull/9169 and https://github.com/buildbuddy-io/buildbuddy/pull/9106 due to suspected EOF errors writing snapshots from workflows in dev.

Revert changes to make ByteStreamServerProxy call ByteStreamServer directly

---

server/util/perms/BUILD
server/util/perms/perms_test.go

Add tests for `perms.go` with extensive coverage of `AuthorizeRead` / `AuthorizeWrite` as a prerequisite to changing the behavior to allow unauthenticated users to be granted permission if OTHERS perms bits are set.

Add perms tests

---

enterprise/server/raft/store/store_test.go

This PR https://github.com/buildbuddy-io/buildbuddy/pull/8941 changed the driver
so that remove replica as an raft cluster member and remove data becomes two
driver action. This introduced the flakiness in the test; because some times,
when we verify whether the data is removed, the remove data action has not been
run.
The test passes with --runs_per_test=500 on top of the change to decrease raft disk usage in test:
https://app.buildbuddy.io/invocation/1ab84174-781d-4709-927d-83f9ff233d7b
https://app.buildbuddy.io/invocation/fc3d6700-8f4d-4530-aedb-a133184069ae

[raft] fix TestDownReplicate

---

enterprise/server/remote_execution/action_merger/action_merger.go
enterprise/server/remote_execution/execution_server/execution_server.go

Speculative fix for a number of cases in which action merging keys went stale because their original execution's context got canceled during the cleanup routine.

Complete action merging cleanup even with a canceled parent context

---

tools/metrics/grafana/dashboards/buildbuddy.json

This PR introduces two new template variables: `appnode` and `executornode` that contains the names of all nodes running `buildbuddy-app-.*` or `executor-.*` pods respectively, and adds rows plotting the per-node metrics for those nodes. It also moves the existing "Node Overview" repeated rows to be called "GKE Nodepool Overview". They are still useful because the new node row doesn't work for cluster with lots of nodes.
Example (US-SJC):
Related Issues: https://github.com/buildbuddy-io/buildbuddy-internal/issues/4851

Add app/executor Node Overview rows that work outside of GCP to main Grafana dashboard

---

enterprise/server/byte_stream_server_proxy/byte_stream_server_proxy.go
enterprise/server/byte_stream_server_proxy/byte_stream_server_proxy_test.go
enterprise/server/cmd/cache_proxy/cache_proxy.go
enterprise/server/content_addressable_storage_server_proxy/content_addressable_storage_server_proxy_test.go
enterprise/server/remote_execution/containers/firecracker/firecracker_test.go
server/environment/environment.go
server/real_environment/real_environment.go

This PR rolls forward https://github.com/,buildbuddy-io/buildbuddy/pull/9106 and https://github.com/buildbuddy-io/buildbuddy/pull/9169 which, together were reverted in https://github.com/buildbuddy-io/buildbuddy/pull/9208 and fixes a case where we mistakenly propagated EOF errors from the remote to the caller.
Specifically, the bug was that this previous logic: https://github.com/buildbuddy-io/buildbuddy/blob/afcfc41037a4daccb031d576a013234fd2a3f186/enterprise/server/byte_stream_server_proxy/byte_stream_server_proxy.go#L324-L332 would handle EOF errors from the remote write stream by causing a `SendAndClose()` call on the client stream. This was broken in the two PRs I mentioned at the top, here: https://github.com/buildbuddy-io/buildbuddy/blob/90173e817f5c63b3da1bf296c3a5263fb3b849a2/ente …

Roll-forward: Make ByteStreamServerProxy call ByteStreamServer directly

---

server/testutil/testserver/BUILD
server/testutil/testserver/testserver.go

We're still seeing
```
testserver.go:73: binary failed to start within 30s: /readyz err: Get "http://localhost:38589/readyz?server-type=buildbuddy-server": dial tcp 127.0.0.1:38589: connect: connection refused
```
in tests, causing them to flake.
This change logs the time at which `waitForReady` starts waiting for the server to respond to `/readyz`. It also clearly marks the testserver stdout and stderr.

[testserver] add logging

---

server/build_event_protocol/target_tracker/BUILD

This is essnetially the same as target_tracker_test target since the
change in 8506d9c5af5.

test: Remove target_tracker_test_clickhouse

---

app/terminal/ansi.tsx

Context: https://buildbuddy-corp.slack.com/archives/C01D5GHRJ59/p1746566444199369?thread_ts=1746546618.860849&cid=C01D5GHRJ59

Don't render 0x16 bytes from go test logs

---

enterprise/server/remote_execution/snaploader/snaploader.go

In an effort to re-push #9221 , break out some of the changes to make them less risky and easier to review.
With #9221, we will write fewer remote snapshots and should try to use a local snapshot instead. This PR should have no effect until #9221 is merged, because workflows won't write local manifests so we'll always fall back to reading the remote manifest

[SS] Always look for a local manifest before remote manifest

---

server/util/compression/compression.go

See https://go.dev/blog/cleanups-and-weak#cleanups for the benefits, but in short:
- AddCleanup is less error prone.
- AddCleanup will allow the reference to be collected 1 GC cycle earlier.

Use runtime.AddCleanup instead of SetFinalizer

---

enterprise/app/trends/drilldown_page.tsx
enterprise/server/invocation_stat_service/invocation_stat_service.go

- Fix sorting instability due to sorting NaN values, where comparisons always return false (except for `!=` which always returns true) 
- Fix rendering "NaN%" in the UI

drilldown: fix a few NaN / divide-by-zero issues

---

enterprise/server/remote_execution/snaploader/snaploader.go
enterprise/server/remote_execution/snaploader/snaploader_test.go

I had to rollback #9084 because it made an assumption that if a snapshot was cached locally, all the chunks existed locally as well. This assumption does not hold true, because we lazily load snapshot chunks. So the following situation is possible:
1. [Executor A] Write snapshot chunks { 0 1 2 3 4 } to the remote cache
2. [Executor B] Fetch the remote snapshot. Only lazily load { 2 4 }. Now only { 2 4} will be cached locally, but the local manifest will still reference all chunks { 0 1 2 3 4}
3. [Executor B] Try to start from the local snapshot from # 2. We fail to use the local snapshot, because `checkAllArtifactsExist` reports that we don't have chunks {0 1 3} in the local filecache. 
After this PR, in # 3 we will allow you to start from the local snapshot, fetching {2 4} from the local …

[SS] Support starting from a local manifest but fetching chunks remotely

---

enterprise/server/util/oci/BUILD
enterprise/server/util/oci/oci_test.go
server/testutil/testregistry/testregistry.go

As I add read-through caching to `oci.Resolver.Resolve(...)`, the grid of test cases will expand:
* nothing for the image is cached
* image index is cached, individual manifest is not, layers may or may not be
* image index is cached, individual manifest is cached, layers may or may not be
* ...
* everything is cached
I'd like to enumerate specific inputs and outputs, and then make sure we get the expected outputs under all paths. This change enumerates specific inputs and outputs. It also tests resolving a manifest directly and through an index for each input/output combination.
It also uses the `executor.container_registry_allowed_private_ips` in favor of `http.client.allow_localhost`, since the `executor.container_registry_allowed_private_ips` is part of the public interface of the …

[oci] explicitly lay out oci.Resolver.Resolve(...) test cases

---

app/invocation/invocation.tsx
app/service/rpc_service.ts

All RPCs and bytestream file downloads that are issued when viewing an invocation should have the `requestContext.groupId` match the invocation owner group ID, so that cache artifact fetches work properly. This PR makes it happen.

Update request context to match invocation owner group ID

---

enterprise/server/content_addressable_storage_server_proxy/BUILD
enterprise/server/content_addressable_storage_server_proxy/content_addressable_storage_server_proxy.go
enterprise/server/content_addressable_storage_server_proxy/content_addressable_storage_server_proxy_test.go

[Workflows now call CASServer::FindMissing](https://github.com/buildbuddy-io/buildbuddy/pull/9232), so support SkipRemote in the proxy

Support SkipRemote in FindMissing for CAS proxy

---

enterprise/server/raft/replica/replica.go
enterprise/server/raft/store/store.go
enterprise/server/raft/store/store_test.go
enterprise/server/raft/testutil/testutil.go

Fix flaky test for AddRangeBack
-- add retries for remove replica and remove data call. Occasionally,
these tests fail with timeout while updating range descriptors b/c
there are no leaders elected.
-- add retries for transfer leader because it's a best effort only
call.
-- GetReplica call can fail with OutOfRangeError from the test when it is
called between RemoveRange and AddRange.
Also remove the quarantine on AddRangeBackTest:
https://app.buildbuddy.io/invocation/ce1949ab-259e-4d29-a0ad-1a2a8082b858
https://app.buildbuddy.io/invocation/63e7524a-7414-4184-91b1-b2c199e76a98

[raft] Update instead of Remove/Add Range

---

enterprise/server/raft/store/store_test.go

buildbuddy-io/buildbuddy-internal#4192
Sometimes GetRange will return empty start and end for range 2 in the test.
Added a for loop to make sure we get an non empty range.
https://app.buildbuddy.io/invocation/0d435d29-5e59-49a6-ac12-a83390265b8d

[raft] fix TestCleanupZombieRangeDescriptorNotInMetaRange

---

app/invocation/invocation_coverage_card.tsx
app/util/lcov.ts

Sorting was not working properly if there are files with zero lines
found. That caused a divided-by-zero bug, which is now shortcuted by a
zero check.
Also added proper typing for lcov entries parsed from the coverage
report file.

coverage_card: fix sorting logic

---

enterprise/server/remote_execution/snaploader/snaploader.go
server/metrics/metrics.go

If we don't write data to the remote cache, `compressedBytesWrittenRemotely` is 0. Track `dirtyBytes` instead, as a proxy for how much data we would've written (though it's the uncompressed value).

[SS] Fix skipped bytes metric

---

enterprise/server/remote_execution/containers/ociruntime/BUILD
enterprise/server/remote_execution/containers/ociruntime/ociruntime.go
enterprise/server/remote_execution/containers/ociruntime/ociruntime_test.go

Allows specifying arbitrary additional mounts using the OCI `Mount` spec (for maximum flexibility). Needed for migrating self-hosted executors from `podman` to `oci` for users relying on the equivalent podman flag.
Example usage:
```yaml
executor:
oci:
mounts:
- source: /host/foo
destination: /mnt/foo
type: bind
options: [ bind, ro ]
```

Add mounts flag to ociruntime

---

codesearch/index/index.go
codesearch/schema/BUILD
codesearch/schema/schema.go
codesearch/schema/schema_test.go
codesearch/types/types.go

Tokenizers are not threadsafe. In this change, Tokenizers are now created on-demand and cached on Writer instances. This avoids reuse of a single tokenizer instance across multiple Writers. Writers themselves are not shared across threads currently. This crash was introduced in #9255.
Note that there is a larger issue here around updating the same document concurrently with multiple writers, but this change is intended to get us back to a non-crashing state before addressing this larger issue.

Fix crash due to thread-unsafe usage of tokenizers in codesearch

---

enterprise/server/backends/migration_cache/migration_cache.go
enterprise/server/test/performance/cache/BUILD
enterprise/server/test/performance/cache/cache_test.go
server/nullauth/nullauth.go
server/remote_cache/digest/digest.go
server/testutil/testdigest/testdigest.go
server/util/compression/compression.go

The Get, GetMulti, FindMissing, and Contains methods all follow a similar pattern. Instead of using an errgroup and waiting for the results of both caches, do the destination read completely async. The Reader method is more complicated so I ignored it for now.
Writer is more interesting. The key here is not creating a goroutine for every `Writer.Write` call. Instead, create a single goroutine for the destination writer which handles all writes, comitts, and closes. Also, creating the source and destination writer in parallel actually makes things slower. I guess the errgroup overhead is large enough and creating a pebble Writer is fast enough.
The Get methods are up to 50% faster. FindMissing is up to 10% faster. Set (which uses Writer) is up to 20% faster.
```
goos: …
```

Optimize the migration cache

---

server/util/compression/compression_test.go

Tests I wrote to exercise #9170, focusing on:
* different buffer sizes
* holding onto errors until the CompressingReader has exhausted successfully-read bytes.

test NewZstdCompressingReader with different buffer sizes

---

server/remote_cache/cachetools/cachetools.go

This prevents sending small batches to ByteStream.Write when the reader has more data.

Use ReadTryFillBuffer in cachetools.uploadFromReader

---

codesearch/query/BUILD
codesearch/query/regexp.go
codesearch/query/regexp_query.go
codesearch/query/regexp_query_test.go
codesearch/searcher/searcher.go
codesearch/searcher/searcher_test.go

This change fixes a bug in codesearch where, in certain circumstances, docs that shouldn't match were returned. This happened most often when short tokens were included in the query.
There are 2 relevant phases in a query:
1. Find docs that match according to the n-gram index
2. Post filter and rank (score) these documents
In phase 1, we sometimes over-retrieve documents, because n-gram indices are incapable of filtering on tokens < 3 characters long. For example, searching for "foo ba" will return all documents that have "foo", but will not filter at all on "ba". This also shows up in cases like "foo.ba", where `.` is treated as single-char wildcard. In these cases, post-filtering is needed to trim out all the non-matches.
In phase 2, we score all the documents. Prior to this change, we …

Bugfix: Prevent codesearch from returning matches that don't fully match

---

enterprise/server/remote_execution/runner/runner.go

Remote bazel does not set a workflow ID, but we still need to clean up the ci_runner in the bare isolation type
This should also fix some flakiness in remote bazel integration tests

[RB] Cleanup ci runner for bare isolation type

---

server/util/compression/compression_test.go

Now that #9270 has landed it's safe to land these tests.

unskip CompressingReader tests

---

enterprise/server/backends/redis_execution_collector/BUILD
enterprise/server/backends/redis_execution_collector/redis_execution_collector.go
enterprise/server/backends/redis_execution_collector/redis_execution_collector_test.go
enterprise/server/remote_execution/execution_server/execution_server.go
enterprise/server/remote_execution/execution_server/execution_server_test.go
server/interfaces/interfaces.go

Split out from #9211 but added tests and cleaned things up slightly.
Currently, only completed executions are stored in Redis, and only while they are waiting for the invocation to be completed.
This PR adds the functionality needed to store in-progress[^1] executions as well, which would allow us to replace MySQL reads/writes with redis reads/writes. Once each execution is completed and moved to the existing list of completed executions (for each invocation), we'll delete the in-progress execution state in favor of the per-invocation execution lists (or the ClickHouse executions for the invocation, if the invocation is complete).
The new functionality is not used anywhere yet.
Context: https://docs.google.com/document/d/1qf-veFLjAVbXMCtAn1a5IVymWIAaqOBpoQiUO5EOPyk/view
[^1]: One …

Add execution collector methods needed to replace MySQL

---

enterprise/server/raft/driver/driver.go
enterprise/server/raft/driver/driver_test.go
enterprise/server/raft/store/store_test.go
enterprise/server/raft/storemap/storemap.go

Occasionally when the driver runs, it didn't recognize the dead replica because
of delay in gossip.
1. Sometimes, it will see the replica as suspect, in these case, I change the driver to remove suspects when down replicating.
2. The driver previously can also get stuck if it removed a healthy replica, and then when it tries to replace dead replica, it cannot find a node. See https://github.com/buildbuddy-io/buildbuddy-internal/issues/4960 I change the driver code so that if we will finish the removal first for AddReplica and ReplaceDeadReplica if there is replicas in the progress of removal.
Also, I am skipping `TestCleanupZombieReplicaNotInRangeDescriptor` for now. This test need rework b/c the current set up is not realistic with the introduction of staging replica descriptors. …

[raft] fix flaky RemoveDeadReplica test

---

enterprise/server/raft/store/store_test.go

We will get out of range error when we call getReplica when we add a replica and
try to get the replica between 1) the time when the config change is committed at raft, the replica is created and the replica is caught up. This can cause TestUpReplicate to fail even when the replica is added successfully. 

[raft] store_test: remove out-of-range check from getReplica

---

enterprise/server/raft/store/store_test.go

Succeeds on two 500 runs including changes from https://github.com/buildbuddy-io/buildbuddy/pull/9302
https://app.buildbuddy.io/invocation/62b93d75-31a9-4731-8fca-3ad9aff21d5e and https://app.buildbuddy.io/invocation/493bd37e-acb0-4e78-9989-a66177d11aee

[raft] Remove TestRebalance from quarantine

---

enterprise/server/backends/redis_execution_collector/redis_execution_collector.go
enterprise/server/backends/redis_execution_collector/redis_execution_collector_test.go
enterprise/server/remote_execution/execution_server/execution_server.go
enterprise/server/remote_execution/execution_server/execution_server_test.go
server/interfaces/interfaces.go

Rename `InvocationLinks` to `ExecutionInvocationLinks` (since it maps execution ID => invocation IDs) and rename `ReverseInvocationLinks` to `InvocationExecutionLinks` (since it maps invocation ID => execution IDs)

Clarify InvocationLink naming in execution collector

---

server/build_event_protocol/build_event_handler/build_event_handler_test.go
server/tables/tables.go

After thinking about this more, I wonder if we should just change the default for now.
I see your reasoning that most people with workflows will always want a CI status, but from a code maintainability perspective it seems simplest to just enable this by default, and ask users who don't want statuses to disable the toggle or set `--build_metadata=DISABLE_COMMIT_STATUS_REPORTING=true`. Wdyt? We've already been asking users to do that up until this point, so doesn't seem like too heavy of a lift. Otherwise users may start relying on these subtle nuances in the code, which will make this column hyper-specific

Automatically report statuses for CI builds

---

enterprise/server/remoteauth/remoteauth.go
enterprise/server/remoteauth/remoteauth_test.go

This change makes the RemoteAuthenticator eagerly parse the JWT returned from the cache or AuthService and store the Claims in the context. This lets subsequent code using the same Context use the parsed Claims instead of reparsing the JWT, and saves a bit of CPU due to that.
Fixes: https://github.com/buildbuddy-io/buildbuddy-internal/issues/4942

Parse JWT once in remoteauth and store those Claims (or error) in Context

---

enterprise/server/auth_service/BUILD
enterprise/server/auth_service/auth_service.go
enterprise/server/remoteauth/BUILD
enterprise/server/remoteauth/remoteauth.go
enterprise/server/remoteauth/remoteauth_test.go
proto/auth.proto
server/util/subdomain/subdomain.go

This is a no-op without `--app.enable_subdomain_matching` which is false by default and in production Cache Proxies. But this makes it possible (with that flag and a couple others) to authenticate against a subdomain.
Related issues: https://github.com/buildbuddy-io/buildbuddy-internal/issues/4870

[Cache Proxy] propagate subdomain to AuthService.Authenticate

---

server/testutil/testserver/testserver.go

An experiment to see if `ci_runner_test` flake decreases.

[testserver] increase server start timeout to 60s

---

enterprise/server/util/ocicache/BUILD
enterprise/server/util/ocicache/ocicache.go
proto/ociregistry.proto

To make it clear that the OCI cache secret will never be stored, manually hash the key for looking up manifests in the AC.
Will eventually move to doing the same for OCI image layers, but this is the key change needed for protecting private OCI image manifests.

[oci cache] do not set secret on protobuf message

---

enterprise/server/raft/replica/replica.go
enterprise/server/raft/replica/replica_test.go

Add a unit test to replica to repo the bug: https://github.com/buildbuddy-io/buildbuddy-internal/issues/4965
Delete the range from the range descriptor in the snapshot instead of from the replica.

[raft] fix snapshot bug post-split

---

server/util/bazel/bazel.go

Add the "mod" and "vendor" commands to the list of recognized
Bazel commands in `server/util/bazel.go`.

bazelutil: Add mod and vendor commands

---

enterprise/server/remote_execution/containers/ociruntime/BUILD
enterprise/server/remote_execution/containers/ociruntime/ociruntime.go
enterprise/server/remote_execution/containers/ociruntime/ociruntime_test.go

Our [docs](https://www.buildbuddy.io/docs/rbe-platforms/#execution-properties:~:text=a%20historical%20artifact.%29-,dockerInit,-%3A%20determines%20whether%20%2D%2Dinit) mention that `oci` isolation type supports `dockerInit`, but we actually don't support it yet.
We currently support running `tini` but it's behind a flag (not enabled anywhere yet), and only for recyclable runners. This PR makes it so we just support the `dockerInit` property instead.

oci runtime: support dockerInit

---

enterprise/server/raft/metadata/metadata_test.go

`TestAutoBringup`, `TestDistributedRanges`, and `TestCacheShutdown` have flaked multiple times over the last 7 days. Let's quarantine them until we can find a way to make them pass consistently.

quarantine flaky metadata tests

---

enterprise/server/ociregistry/ociregistry_test.go
enterprise/server/util/ocicache/BUILD
enterprise/server/util/ocicache/ocicache.go
enterprise/server/util/ocicache/ocicache_test.go

The OCI cache has been fetching manifests from the AC since May 8. There rarely seem to be cache misses:
This change stops writing manifest contents to the CAS, and tests that `ocicache.WriteBlobOrManifestToCacheAndWriter` does not rely on a byte stream server or client to successfully write manifests.

[oci cache] only write manifests to AC, never to CAS

---

enterprise/server/backends/distributed/distributed.go
enterprise/server/backends/distributed/distributed_test.go

Currently, if the reader stops for any reason, we will write whatever we read to the lookaside cache. Instead, only write to the lookaside cache when the reader gets an EOF.

Don't write to lookaside cache on abandoned reads

---

enterprise/server/raft/store/store_test.go

Successes over 2 500 runs:
https://app.buildbuddy.io/invocation/50e0b294-d1f8-4f28-9f3f-6e79485c31bf
https://app.buildbuddy.io/invocation/ac4ee557-5569-4cc0-9542-70e679d1f0f0

[raft] Remove TestSplitMetaRange from quarantine

---

enterprise/server/raft/leasekeeper/leasekeeper.go
enterprise/server/raft/rangelease/rangelease.go
enterprise/server/raft/rangelease/rangelease_test.go

We only use rangeID.
Now that we don't call RemoveRange when we update the range, the rd in the lease
is not updated. Remove it from Lease b/c (1) the [start, end) in logs are confusing (2) can cause future bugs if rd is used.

[raft] remove rd from lease

---

rules/sha/BUILD
rules/sha/index.bzl
rules/sha/sha_test.sh

This breaks the gcs deployment because the target label is now ambiguous as to which sum file it refers to.
The .list.sum file was only needed for debugging. Instead add an env var that prints out the .list.sum file contents to stderr and fails.

Don't generate .list.sum file

---

enterprise/server/raft/store/store.go
enterprise/server/raft/store/store_test.go
proto/raft.proto
proto/raft_service.proto

ListReplicas is only used in test. Renamed it to ListReplicasForTest.
Removed ListReplicasTest

[raft] remove ListReplicas API

---

codesearch/index/index.go
codesearch/server/BUILD
codesearch/server/server.go

There are numerous race conditions that can occur when re-indexing the same repo concurrently - the same files may get added twice in many circumstances. 
This change makes the codesearch server lock on a per-repo basis. On it's own, this is not a scalable change, especially for large repos. However, it is made in preparation for implementing incremental index updates.

Codesearch server only processes one update per repo at a time

---

server/testutil/app/app.go

Several integration tests flake due to a failure to start the BuildBuddy server process.
On those same runs, I see warnings about slow queries.
I have also seen 5s+ IO stalls.
This change uses in-memory sqlite db for tests to avoid tests being bottlenecked on disk IO.

use in-memory sqlite db for tests

---

cli/parser/BUILD
cli/parser/bazelrc/BUILD
cli/parser/bazelrc/bazelrc.go
cli/parser/parser.go

Moves this code out so that we can depend on some of this stuff from files `parser.go` will depend on in the future.
Part of the larger overall refactoring effort for parser.go

Refactor code to split out code specifically for dealing with rc files from the core parser code

---

cli/parser/parsed/parsed.go

This makes the `Classified` interface more widely useful, which I need for refactoring config parsing.

CLI: Export `Arg` from `Classified` in `parsed.go`

---

enterprise/server/cmd/executor/executor.go

no real utility in making this a generally-configurable flag right now, so i'm making an executor-specific one.

add flag to set client type in executor specifically.  

---

enterprise/server/backends/distributed/distributed.go

I don't think this will have a large impact, but might as well, since we know how many peers we want to write to.

Presize a map in distributed.multiWriter

---

server/util/lockmap/BUILD
server/util/lockmap/lockmap.go
server/util/lockmap/lockmap_test.go

Instead of using a global lock on the entire `sync.Map` to avoid races with the custom GC routine, mark them as unusuable under their own write lock and have the `(R)Lock` function spin when it encounters such a mutex. This should only occur very rarely (GCs are performed at most once every 100ms) and the period of spinning should be short (as long as it takes to delete a key in the map). 
Reference counting is replaced with a call to `TryLock` for a particular entry, which combines a check for approximate unusedness with an acquire of the lock needed to mark the mutex as unusuable in a single atomic operation. This may succeed even though other goroutines were waiting on the lock, in which case they all have to refetch the new mutex from the map. This should also be a rare case since it …

Avoid a global lock and reference counting in `lockmap`

---

enterprise/server/backends/migration_cache/migration_cache.go
enterprise/server/backends/migration_cache/migration_cache_test.go

As far as I can tell, this code hasn't been doing anything in a while. If src.Write fails, then Commit is never called on the destination, so there is nothing to delete.
See the discussion in https://github.com/buildbuddy-io/buildbuddy/pull/9336

Don't attempt to delete from dst cache on src failure

---

tools/metrics/grafana/dashboards/buildbuddy.json

Don't know why the panels I add keep causing their rows to save as expanded.
Probably operator error.
Anyhow, here's the OCI registry mirror row collapsed when you first open the page, like a good little row:

[grafana] collapse OCI registry mirror row

---

enterprise/server/test/performance/cache/BUILD

Since I added a new benchmark in https://github.com/buildbuddy-io/buildbuddy/pull/9354, they've been timing out.

Give cache benchmarks a long timeout

---

server/build_event_protocol/accumulator/accumulator.go
server/build_event_protocol/build_event_handler/build_event_handler.go

These are artifacts created by TestRunner action defined by Bazel's native Java
code here (1). It's usually a fixed list of optional outputs, so it should be
relatively safe to bump the limit by 10x (we will do that in a separate
PR).
In case the limit is met, prioritize saving outputs from failed tests over outputs
from passed tests.  We differentiate the twos by checking if the test status is
PASSED or not.
(1): https://cs.opensource.google/bazel/bazel/+/615b63dd005923e12e1356c1368e80dd121f2c5a:src/main/java/com/google/devtools/build/lib/analysis/test/TestRunnerAction.java;l=402

build_event_handler: smarter persisted test artifacts

---

cli/parser/parser.go
cli/parser/parser_test.go

It is clearer to fail early, and means we do not need to create a potentially confusing partially-expanded list of command-line arguments to pass to bazel. The goal is that any command line that is actually passed to bazel is fully expanded and free from any `rc` options, save the single `ignore_all_rc` option we add when consuming the rc files.

CLI: Error out when attempting to expand unrecognized config option

---

enterprise/server/remote_execution/copy_on_write/BUILD
enterprise/server/test/performance/cache/BUILD

Benchmarks should only run in isolation, and only when explicitly invoked. It doesn't make much sense to run a benchmark as part of a wildcard target.

Tag benchmark tests `manual`

---

codesearch/cmd/cli/cli.go
codesearch/github/BUILD
codesearch/github/github.go
codesearch/github/github_test.go
codesearch/index/index.go
codesearch/index/index_test.go
codesearch/schema/schema.go
codesearch/server/server.go
codesearch/types/types.go
proto/codesearch_service.proto
proto/index.proto

This change adds the ability for index.Writer and index.Reader to record and produce the most recently indexed commit, per repository.
It also exposes this via a `RepoStatus` rpc in the codeearch service.
This is in support of a near-future change which will enable incremental updates of the codesearch index as individual commits are created on the indexed branch.
The factoring here could be improved in the future - all the core codesearch types (e.g. IndexReader/IndexWriter) should probably remain completely ignorant of anything git-specific, such as commits. Additionally, the logic for tracking commits is duplicated across the CLI tool and the server, and doesn't really belong directly in either of them. This should probably be addressed by introducing a more explicit git-specific layer …

Track and expose the most recently indexed commit per repository in codesearch

---

server/remote_cache/cachetools/BUILD
server/remote_cache/cachetools/cachetools.go
server/remote_cache/cachetools/cachetools_test.go

Now that we have tests for calling `UploadFromReader` on a blob that already exists in the CAS, this change re-introduces `UploadWriter`.

[cachetools] Re-introduce UploadWriter; use in UploadFromReader

---

cli/parser/bazelrc/bazelrc.go
cli/parser/parser_test.go

This is the behavior bazel does, as well.

CLI: Ignore lines in bazelrc that consist of single shlex tokens

---

enterprise/server/remote_execution/execution_server/BUILD
enterprise/server/remote_execution/execution_server/execution_server_test.go

Split out from https://github.com/buildbuddy-io/buildbuddy/pull/9357/files
Use a real collector to avoid having to mock out the new methods that were added.
The real collector is cheap to run, since it only depends on Redis, which is pretty lightweight.

Use real execution collector in test

---

cli/log/BUILD
cli/log/log.go
cli/plugin/plugin.go
cli/terminal/BUILD
cli/terminal/terminal.go

This matches bazel's behavior and is also pretty standard practice with CLI tools.

cli: disable color when not writing to tty

---

server/util/lockmap/lockmap_test.go

Previously, it was mostly benchmarking `random.String(64)`. I pulled that out of the loop by pre-creating keys. I also made the number of keys variable, so we can have benchmarks for high and low contention.
I didn't modify the read benchmark because I think it's good to have one benchmark that has no contention.
Current results on my machine:
```
goos: linux
goarch: amd64
│  /tmp/base  │
│   sec/op    │
LockQPS/1-24       138.2n ± 7%
LockQPS/10-24      48.45n ± 5%
LockQPS/1000-24    24.97n ± 1%
LockQPS/10000-24   17.18n ± 1%
RLockQPS-24        17.33n ± 1%
geomean            34.63n
│ /tmp/base  │
│    B/op    │
LockQPS/1-24       64.00 ± 0%
LockQPS/10-24      64.00 ± 0%
LockQPS/1000-24    64.00 ± 0%
LockQPS/10000-24   64.00 ± 0% …
```

Improve lockmap write benchmark

---

app/invocation/invocation_execution_table.tsx

Expand the action digest in the execution table only when the
associated target label is empty. This should help improve the visual a
little bit when the label is not available.

Expand digest when no target label

---

enterprise/server/remote_execution/execution_server/execution_server.go
enterprise/server/remote_execution/execution_server/execution_server_test.go
enterprise/server/util/execution/execution.go

Introduces 3 flags to the execution server:
- `remote_execution.write_execution_progress_state_to_redis`: if enabled, writes execution updates and invocation-execution links to Redis, using the new methods added in https://github.com/buildbuddy-io/buildbuddy/commit/9b6419d71a3a700873dcd35cdc505755241f6faf
- `remote_execution.write_executions_to_primary_db`: if enabled, writes Execution rows and InvocationExecution rows to mysql. Defaults to true in order to preserve our current behavior.
- `remote_execution.read_final_execution_state_from_redis`: if enabled, read the final execution state from redis instead of mysql when we write executions to clickhouse.
The rollout plan to fully stop writing executions to MySQL would then be:
- Rollout 1: enable …

Update execution server to allow storing metadata in Redis

---

enterprise/server/backends/distributed/BUILD
enterprise/server/backends/distributed/distributed_test.go

The problem was that the "failing" cache didn't finish shutting down before distributed_client.RemoteWriter returned a client for it. Giving the failing cache more time to shut down fixes this.
200 runs: https://app.buildbuddy.io/invocation/2aad935b-9719-4c08-9ea6-e37791ed8836

Unquarantine distributed_test.TestReadWriteWithFailedNode

---

enterprise/server/execution_service/execution_service.go
enterprise/server/test/webdriver/executions_clickhouse/executions_clickhouse_test.go

Today, if we were to start storing in-progress execution metadata in Redis instead of MySQL, the UI would not be able to view in-progress executions. We do already read execution state from Redis, but only for executions that have completed (and are sitting in Redis waiting for the invocation to complete).
This PR makes it so we read the in-progress execution state from Redis as well, so that in-progress executions can be displayed in the executions page.

Allow reading in-progress executions from Redis

---

server/build_event_protocol/build_event_handler/build_event_handler.go

If flushing executions from redis to ClickHouse fails, log the error instead of silently ignoring it.

Add logging when flushing executions to clickhouse fails

---

enterprise/server/remote_execution/execution_server/BUILD
enterprise/server/remote_execution/execution_server/execution_server.go
server/remote_cache/capabilities_server/capabilities_server.go

We are currently enforcing this limit in ExecutionServer.execute.
Let's make sure that we advertise the correct value through
GetCapabilities rpc.

capabilities_server: Limit priority range

---

enterprise/server/remote_execution/containers/firecracker/firecracker.go

Fixes https://github.com/buildbuddy-io/buildbuddy-internal/issues/4905

Fix potential nil dereference in firecracker.getVMMetadata

---

tools/metrics/grafana/dashboards/mac.json

This PR overhauls the mac monitoring dashboard. The key changes are that it:
* Makes the `inventory_hostname_pattern` work in all graphs.
* Adds a new `group_name` variable for easy filtering by group name.
* Makes the four bottom rows (Node disk/network IO, Node memory usage, Node swap usage, Node swap rate) repeat by `group_name` rather than `inventory_hostname`. This significantly reduces the number of graphs that need to be rendered when these rows are expanded, making them load much faster.
* Removes the `inventory_hostname` variable.
* Adds graphs showing disk usage by group.
* Removes some graphs that don't work on mac.
This should make the dashboard a fair bit easier to use and more useful, especially for oncall.

[Macs] revamp the mac monitoring dashboard

---

server/remote_cache/cachetools/BUILD
server/remote_cache/cachetools/cachetools.go
server/remote_cache/cachetools/cachetools_test.go
server/remote_cache/digest/digest.go

If we get a DataLoss error, re-hash the file to diagnose whether it was due to a concurrent mutation, and if there is a hash mismatch, report a clearer error message instead of DataLoss.
Context: https://buildbuddy-corp.slack.com/archives/C0495TM9UUE/p1747332726948839?thread_ts=1747332576.080259&cid=C0495TM9UUE

Check for concurrent mutations while uploading

---

codesearch/github/github.go
codesearch/github/github_test.go

This change adds some functions that will be used to create incremental update payloads for the codesearch indexer. This will eventually be wired into the BB CLI, and will be run on a local clone of a git repository. 
These functions look at a range of commits on a single branch, and extract the changes from each commit in the range that need to be sent to the indexer: the contents of all added/modified files, and the names of deleted / renamed files.

Codesearch incremental update extraction tools

---

enterprise/server/util/oci/BUILD
enterprise/server/util/oci/oci.go
server/metrics/metrics.go

I'm trying to see if the code that caches OCI image manifests in the OCI Resolver is working correctly, and would like to see how often `Resolve(...)` is being called at all. This change introduces a metric to track that count.

[oci resolver] track number of Resolve(...) calls

---

app/invocation/invocation_execution_table.tsx

- Fix left alignment of the action digest when both the target label and action mnemonic are missing.
- Don't show the duration for executions that are in-progress (currently we render things like "Executing in 0s" / "Starting in 0s")

Fix a few executions UI bugs

---

codesearch/github/github.go
codesearch/github/github_test.go

Why, what a nifty command this is! `git whatchanged ...` does the same thing as the combination of the previous `git log ...` and `git diff-tree ...` commands.
This change also imposes an arbitrary limit of ~1000 modified files for a single incremental update.

Switch incremental update computation to use "git whatchanged"

---

enterprise/server/api/api_server.go
enterprise/server/atime_updater/atime_updater.go
server/remote_cache/digest/digest.go

These functions fully parse the digest name, which is kind of expensive, and the only callers later call the corresponding `Parse` function. Change the callers to just call `Parse` and check for errors.

Remove digest.Is*ResourceName functions

---

cli/parser/bazelrc/bazelrc.go
cli/parser/parsed/parsed.go
cli/parser/parser.go
cli/parser/parser_test.go
cli/setup/setup.go

This change is a little odd, since many of the refactored functions in `parser.go` now belong in `parsed.go`, but I elected to make the changes first and then move them in a later PR so as to make viewing the diffs easier when reviewing.
Primarily, this change:
- Directly uses the options-retrieval abilities of parsed.Args to consume the rc file options
- Parses the rc files into `parsed.Config` structs in a map keyed by config name and into a default config struct for unnamed configs (for example, `common` or `build` as opposed to `common:foo` or `build:bar`)
- Uses these config structs to expand config options
Small behavior changes include that `common:` will no longer be equivalent to `common`, which mirrors bazel's bahavior, and that the `always` phase is now supported.
Once this is …

CLI: Refactor config parsing to use the new parsing constructs

---

codesearch/README.md
codesearch/cmd/cli/cli.go
codesearch/github/github.go
codesearch/github/github_test.go
codesearch/server/server.go

- Fix grpcurl example in the README to reflect now-required replacement strategy arg
- Make incremental update computation properly return an error when no changes found
- Don't crash the CS CLI when failing to add a document
- Expose the GitClient from github.go, it will be used by the BB CLI in a change shortly

Several cs fixes

---

tools/replay_invocation/BUILD
tools/replay_invocation/replay_invocation.go

This is useful for replaying the exact BES contents as they were originally streamed, which matters for things like logs / ANSI parsing debugging, and redaction debugging.
Context: https://buildbuddy-corp.slack.com/archives/C03JL0YT6G5/p1747426991216539?thread_ts=1747424427.201779&cid=C03JL0YT6G5

replay_invocation: allow replaying build_event_json_file

---

enterprise/server/raft/rangelease/BUILD
enterprise/server/raft/rangelease/rangelease_test.go

unquarantine rangelease test.
Right now some tests failed with deadline exceeded errors. The deadline is
reached before the renewLease is actually called.
The test passes with 4500 runs. 

[raft] rangelease_test: move ctx close to lease

---

cli/parser/parser.go

We should be checking that there is no error when evaluating the flag as a bool, not that there is one.

CLI: Fix errant negation when expanding `--enable_platform_specific_config`

---

server/remote_cache/cachetools/BUILD
server/remote_cache/cachetools/cachetools.go
server/remote_cache/cachetools/cachetools_test.go

This change introduces `NewUploadWriter` and tests for `UploadWriter`. It leaves the `UploadFromReader` path untouched, since my first need for `UploadWriter` is as a best-effort writer for caching OCI image layers. A later change will have `UploadFromReader` use `UploadWriter`.

[cachetools] add NewUploadWriter and tests

---

enterprise/server/util/ocicache/BUILD
enterprise/server/util/ocicache/ocicache_test.go

While adding support for writing layers to the cache for `Image`s returned by `oci.Resolver.Resolve(...)`, I realized I want to make sure blob caching as currently implemented works. So I wrote a test!

[oci cache] add tests for writing and fetching blobs

---

server/metrics/metrics.go

Previous buckets were `1ms, 10ms, 100ms, 1s, 10s, 1m40s, inf` which meant that every observation went into the infinity bucket.
New buckets are `30m0s, 1h0m0s, 2h0m0s, 4h0m0s, 8h0m0s, 16h0m0s, inf`. The current average is around 8 hours.

Fix buckets for lookaside_cache_eviction_age_msec

---

tools/metrics/grafana/dashboards/buildbuddy.json
tools/metrics/grafana/dashboards/cache-proxy.json

I added them for both the app and the cache-proxy. The buckets are broken for the eviction age metric, so I'm fixing them in https://github.com/buildbuddy-io/buildbuddy/pull/9432.
App: 
Cache proxy:

Add graphs for lookaside cache metrics

---

enterprise/server/remote_execution/execution_server/execution_server_test.go
server/remote_cache/digest/digest.go
server/remote_cache/digest/digest_test.go

This does away with the regular expression parsing in digest.go in favor of splitting the provided resource name on `/` and validating the individual pieces. There is probably still lots of room for improvement here, but according to the benchmark in https://github.com/buildbuddy-io/buildbuddy/pull/9405, this is a bit over 10x faster:
```
goos: linux
goarch: amd64
│ /home/iain/old.txt │         /home/iain/new.txt          │
│       sec/op       │   sec/op     vs base                │
ParseDownloadString-16         57.675µ ± 3%   4.821µ ± 1%  -91.64% (p=0.000 n=40)
│ /home/iain/old.txt │          /home/iain/new.txt          │
│        B/op        │     B/op      vs base                │
ParseDownloadString-16         3.835Ki ± 0% …
```

Make digest parsing faster by manually parsing the string

---

enterprise/server/backends/distributed/distributed.go
enterprise/server/util/distributed_client/distributed_client.go
server/remote_cache/digest/digest.go
server/util/log/log.go

These make lookaside cache hits 30% faster, by removing some overheads.
The log.go change is only about 1-2%. There's no point to enriching the log message from the context when we won't debug log.
The rest of the improvement is split roughly evenly between:
- pre-evaluating metrics with labels in getLookasideEntry
- lazy string formatting in distributed_client.ResourceIsolationString. This is only used in log statements, and mostly debug ones, so we avoid the formatting if we don't have debug logging enabled.
- using strings.Join instead of fmt.Sprintf in digest.*String functions.
```
goos: linux
goarch: amd64
│   base-look   │             after-look             │
│    sec/op     │   sec/op     vs base               │ …
```

More lookaside cache optimizations

---

enterprise/server/backends/pebble_cache/pebble_cache.go
proto/storage.proto
server/metrics/metrics.go

this approach only counts bytes that were written after a specified timestamp--without a "start" time, the byte count can go negative as items are evicted.  limiting the byte count to be positive would have similar issues: so long as a user's share of the cache isn't increasing, we would expect their byte count to stay near zero.
happy to hear other suggestions, but i kind of like how this one ties into our existing counting methods, so i'll take not knowing where some bytes came from as a starting point--if the "permanent" cache size (stuff that never gets evicted) is large enough that we care, we can try to figure out a sampling-based approach.

compute and log pebble cache partition space used by group ID.

---

enterprise/server/remote_execution/containers/firecracker/BUILD
enterprise/server/remote_execution/containers/firecracker/firecracker_test.go

I can't reproduce the flakiness, so let it run in CI until we have some flaky examples.

Unquarantine TestFirecrackerRun_Timeout_DebugOutputIsAvailable

---

enterprise/server/util/oci/oci.go

I spun up a local executor and saw several log messages like `Resolving OCI image for registry "[UNKNOWN]"` which seemed unexpected since `gcr.io` is a known registry. This PR fixes that.

Fix oci.Resolve metric

---

enterprise/server/backends/pebble_cache/pebble_cache.go

this effectively adds reset functionality

reset cache-size-by-group-id map when tracking start time is in the future.

---

enterprise/server/atime_updater/atime_updater_test.go
enterprise/server/hit_tracker_client/hit_tracker_client_test.go

Both of these have logic in them that discards entries and logs stuff if they have too many. The benchmarks could hit that, making the results unreliable.

Recreate atime-updater/hit-tracker-client in benchmarks

---

cli/parser/parsed/BUILD
cli/parser/parsed/parsed.go
cli/parser/parser.go

This PR moves the functions to the places specified by their TODOs and modifies them only the minimal amount necessary to make them work in the file they were moved to.

CLI: Move parser-related functions to the files they belong in

---

enterprise/server/remoteauth/BUILD
enterprise/server/remoteauth/remoteauth.go

These actually consume a bit of CPU, and are already covered under the `interceptors.AddAuthToContext` span:

Remove some not-too-useful trace spans from remoteauth

---

enterprise/server/experiments/experiments_test.go
enterprise/server/githubauth/githubauth.go
enterprise/server/oidc/oidc.go
enterprise/server/remote_execution/filecache/filecache_test.go
enterprise/server/remoteauth/remoteauth.go
enterprise/server/remoteauth/remoteauth_test.go
enterprise/server/saml/saml.go
enterprise/tools/upload_local_snapshot/upload_local_snapshot.go
server/testutil/testauth/testauth.go
server/util/claims/claims.go
server/util/claims/claims_test.go

[`RemoteAuthenticator.AuthenticatedGRPCContext`](https://github.com/buildbuddy-io/buildbuddy/blob/a171606c4fa589c2fe83d28712a547d92f83d19d/enterprise/server/remoteauth/remoteauth.go#L126-L171
) obtains a JWT for the incoming request, parses the `claims.Claims` out of it, and then sets those in the incoming context. It uses [`claims.AuthContextFromClaims`](https://github.com/buildbuddy-io/buildbuddy/blob/a171606c4fa589c2fe83d28712a547d92f83d19d/server/util/claims/claims.go#L306-L321
) to do that last step, which always re-assembles the JWT from the provided Claims and sets that JWT in the context. This is inefficient, because the RemoteAuthenticator already had a valid JWT! The Cache Proxy is spending about 2.5% of its CPU doing this right now:

Don't re-assemble JWTs in RemoteAuthenticator

---

enterprise/server/backends/redis_execution_collector/redis_execution_collector.go
enterprise/server/remote_execution/execution_server/execution_server.go
enterprise/server/remote_execution/execution_server/execution_server_test.go
enterprise/server/test/webdriver/executions_clickhouse/executions_clickhouse_test.go

Currently when an executor has finished execution, it sends a payload to the execution server which immediately flushes the data to clickhouse
In order to track runner recycling time in clickhouse, which may occur after the requested execution has finished, this PR first stores execution data in Redis. It then reads the data from Redis and flushes it to Clickhouse. In itself this PR should functionally be a no-op.
Next, my plan is to 
1. Move flushing data to clickhouse to after the client closes the PublishOperation stream
2. Executor publishes another update with runner recycling time. The execution server updates the in-progress execution data in Redis. Now, when the data is read in step 1, it will include the runner recycling time

Read execution data from Redis to flush to Clickhouse

---

enterprise/server/raft/cache/cache.go
enterprise/server/raft/metadata/BUILD
enterprise/server/raft/metadata/metadata.go
enterprise/server/raft/metadata/metadata_test.go
enterprise/server/raft/store/store.go

Fix TestGetAndSet:
1. put metadata_test on firecracker. Refactor the store so that we can use small
memory LogDBConfig option in test.
2. Remove the timeout context in TestGetAndSet. We used one context with 1 second
for both get and set so the test sometimes failed with deadline exceeded.

[raft] put metadata_test on firecracker

---

.bazelrc
shared.bazelrc

`--test_env` is still a `build` option in Bazel 8 (fixed in https://github.com/bazelbuild/bazel/commit/43ebb95d1b1a66e7d46dc5e573309ace68f471a8) and thus invalidates the analysis cache when it changes between `build` and `test`. Since that's obscure knowledge and there is no downside, migrate all test options to `common`.

Avoid analysis cache drop when switching between build and test

---

cli/test/integration/cli/cli_test.go

Has [flaked multiple times](https://app.buildbuddy.io/tests/?target=%2F%2Fcli%2Ftest%2Fintegration%2Fcli%3Acli_test&branch=master#flakes) on `master` in the last 7 days.

quarantine cli_test.TestParseGlobalFlags

---

enterprise/server/util/oci/oci.go
enterprise/server/util/ociconv/ociconv.go

In `ociconv`, the `authenticateWithRegistry` function resolves an image to check that credentials are valid, but does not use the returned image. This change creates a separate `AuthenticateWithRegistry` function that issues an HTTP HEAD request to check the credentials and does not otherwise fetch any data from the server.
This change also adds info logs for `AuthenticateWithRegistry` and `Resolve` indicating which upstream registry we're making requests to.

[oci resolver] separate AuthenticateWithRegistry from Resolve

---

enterprise/server/backends/distributed/distributed.go
enterprise/server/backends/distributed/distributed_test.go

Allow cache proxy to read-through into the local cache, to prevent cross-zone transfers from happening more than once.

Add a local-readthrough mode to distributed.go

---

enterprise/server/oidc/oidc.go

I think this was introduced in https://github.com/buildbuddy-io/buildbuddy/pull/9465. Not sure whether this would happen in practice, but I hit this while trying to test Entra + OIDC locally.

Fix panic when auth fails

---

codesearch/index/index.go
codesearch/index/index_test.go
codesearch/posting/posting.go
codesearch/posting/posting_test.go

Adds 3 functions:
- `DropNamespace`, which drops an entire namespace
- `DeleteMatchingDocuments`, which deletes all docs that match a given field. Intended to be used to delete an entire repository at once
- `CompactDeletes`, which removes deleted doc ids from all posting lists in a namespace. Note that this is a potentially very expensive operation for large indices, but it will keep the index size proportional to the size of the repo, rather than the number of updates that have been applied.
None of these are used or exposed anywhere yet.

Add several codesearch index utilities

---

enterprise/server/ociregistry/ociregistry.go
enterprise/server/util/oci/oci.go
enterprise/server/util/ocicache/ocicache.go
enterprise/server/util/ocicache/ocicache_test.go

Pass a Repository (includes the registry hostname and the image name) and a Hash (digest) to OCI cache functions.
This change eliminates redundant information (we were already only using the Repository part of References) and makes some follow-on changes smaller.

[oci cache] ref -> repo

---

shared.bazelrc

This was done originally in https://github.com/buildbuddy-io/buildbuddy/pull/8986 but I think it was unintentionally reverted by https://github.com/buildbuddy-io/buildbuddy/pull/9370. The `--test_tag_filters` flag is not additive, so the latter PR had the (unintended?) side effect of adding the `-docker` filter back to `--config=remote`.

Run docker tests when --config=remote is set

---

tools/metrics/grafana/dashboards/buildbuddy.json

Now that `oci.Resolver.Resolve(...)` writes to and reads from the cache, there are OCI registry events (should probably rename to OCI cache events) on both the app and executors. Change the metrics dashboard to plot events from any workload.

[grafana] do not restrict OCI registry cache events by workload

---

enterprise/server/util/distributed_client/distributed_client.go

This should be temporary, but I think it will fix the in-flight client RPC metric growing continuously.
It might also fix our memory leak.
If either is fixed, we should figure out which caller isn't closing the stream.

Close DistributedCache.Write stream in a cleanup function

---

codesearch/index/index.go
codesearch/index/index_test.go

This was supposed to have gone in with the initial PR for these tools, but it seems I forgot to push the fix

Fix codesearch DropNamespace and add test

---

dockerfiles/test_images/defs.bzl
dockerfiles/test_images/net_tools/Dockerfile
enterprise/server/remote_execution/containers/firecracker/firecracker.go
enterprise/server/remote_execution/containers/firecracker/firecracker_test.go
enterprise/server/remote_execution/containers/ociruntime/BUILD
enterprise/server/remote_execution/containers/ociruntime/ociruntime.go
enterprise/server/remote_execution/containers/ociruntime/ociruntime_test.go
proto/remote_execution.proto
server/testutil/testnetworking/BUILD
server/testutil/testnetworking/testnetworking.go
server/util/networking/BUILD
server/util/networking/networking.go
server/util/networking/networking_test.go

Depends on https://github.com/buildbuddy-io/buildbuddy/pull/9500
Captures `{tx,rx}_{bytes,packets}` and populates the UsageStats proto with this information (behind a flag).
Stats are collected from the host side of the veth pair to avoid having to enter a netns to collect stats from the namespaced side, which has too much overhead (especially since we probably want to poll these and show a chart, similar to disk usage). This means that we have to swap the tx/rx traffic for it to reflect the container's perspective, which is a bit of a hack, but IMO an OK tradeoff for now.

Record network metrics for VMs and OCI containers

---

enterprise/server/remote_execution/execution_server/execution_server.go
enterprise/server/test/integration/remote_execution/remote_execution_test.go

Realized that the cancellation codepath was still reading the in-progress execution IDs from mysql.

Fix invocation execution cancellation when mysql is disabled

---

enterprise/server/workflow/config/config.go

This action should now work on repos with or without bzlmod, and with different versions of bazel (although I've only tested back to 7.5.x)
I don't love putting all this bash into a string in a go file, but I also think that integration testing this script is probably more effort than it is worth right now, because it would involve setting up at least 4 test repos to hit the different cases.

Generalize kythe workflow action 

---

.bazelrc
shared.bazelrc

The config local-rbe does not exist.
Replace it with target-darwin-arm64 instead, since it's pretty safe to
assume that nobody on our team will be using an Intel Mac for
development.

bazelrc: fix wrong config on local-rbe-mac

---

enterprise/server/backends/codesearch/BUILD
enterprise/server/backends/codesearch/codesearch.go
server/interfaces/interfaces.go

Also, fix the arg name in `interfaces.go`. The sole implementation of this method does indeed take `owner`, not `repoUrl`: https://github.com/buildbuddy-io/buildbuddy/blob/master/enterprise/server/githubapp/githubapp.go#L186

Pass owner instead of repo url to GetGitHubAppForOwner

---

codesearch/github/github.go
codesearch/github/github_test.go
enterprise/server/workflow/config/config.go

1. When we clone repos for workflows, we clone with `depth=1`, which makes history unavailable. This change adds an `--unshallow` fetch to the codesearch incremental update action, which fetches history (but still avoids fetching blobs from history). Note we might be able to do this entire thing slightly more cheaply with a treeless clone (`--filter=tree:0`), as opposed to a blobless clone, but I'm sticking with the current blobless clone that's used already for now.
2. The parsing of `git whatchanged` is made more robust. The git output in the workflows included a warning about forced updates not being shown, probably due to some bit of config from the workflow setup. This output was breaking the parsing. We now parse the rows with regexes to be more resilient. The next most resilient …

Fix 2 codesearch incremental bugs

---

enterprise/server/remote_execution/workspace/workspace.go
enterprise/server/remote_execution/workspace/workspace_test.go
enterprise/server/test/integration/remote_execution/remote_execution_test.go

We were already not preserving output_files or output_directories, but never updated this logic for the new output_paths.

Don't preserve output_paths when preserve-workspace is true

---

enterprise/server/backends/distributed/distributed.go

AC entries can be updated, so we don't want nodes that aren't in the peer set to hold on to old values.

Don't write AC entries to the readthrough cache

---

enterprise/server/hit_tracker_client/hit_tracker_client.go

I added a separate alert for the dropped-hits metric in https://github.com/buildbuddy-io/buildbuddy-internal/pull/5092
I modified the existing benchmark to set the flags so the hit-tracker-client drops hits after the first one and then set the number of hits-to-enqueue to 1,000 to measure the impact of this when the client is full. Here are the results:
```
goos: linux
goarch: amd64
│ /home/iain/old.txt │          /home/iain/new.txt           │
│       sec/op       │   sec/op     vs base                  │
Enqueue-16       3064.1µ ± 262%   474.7µ ± 8%  -84.51% (p=0.000 n=7+10)
│ /home/iain/old.txt │           /home/iain/new.txt           │
│        B/op        │     B/op      vs base                  │
Enqueue-16         4.535Mi ± 1% …
```

Don't alert.UnexpectedEvent for dropped hit-tracker-client hits

---

website/yarn.lock

Addresses https://github.com/buildbuddy-io/buildbuddy/security/dependabot/214

Upgrade `tar-fs` for dependabot

---

shared.bazelrc

I found test_output=errors a bit inconvenient when working with tests with a lot
of logs like raft tests. To investigate these errors, I ususally open the test
log files with an editor. But the file is shown before all the log lines. And
sometimes, when there are a lot of logs, I cannot get to the file.

tweak deflake settings

---

app/invocation/invocation.css
app/invocation/invocation_target_group_card.tsx
app/target/target.tsx
app/target/target_test_document_card.tsx
app/target/target_v2.tsx

Adds a badge next to the target label in the invocation targets
list to display test cache status information.
The badge shows "Cached" if all runs were served from cache.
Nothing is displayed if only some of the runs, or none were cached.
Note that we are not currently using test cache status to sort the
target group. Such logic can be added later in a future change. Also,
there is insufficient information from Build Event Stream to indicate
whether a build target was cached or not, so all build targets are being
shown without the badge, which could be misinterpreted as no-cache.

invocation_target_group_card: show cache status

---

enterprise/server/ociregistry/ociregistry.go
enterprise/server/util/ocicache/BUILD
enterprise/server/util/ocicache/ocicache.go
enterprise/server/util/ocicache/ocicache_test.go

This change tests the WriteBlob and FetchBlob[Metadata] paths.
I'll want the same exact test when I introduce `ocicache.NewBlobUploader`, so landing it now!

[oci cache] test writing and fetching blobs

---

enterprise/server/execution_service/BUILD
enterprise/server/execution_service/execution_service.go

Screenshot (from a local execution with artificial `time.Sleep(100 * time.Millisecond)` after we record each timestamp)

Show execution local queue time in trace viewer

---

enterprise/server/atime_updater/BUILD
enterprise/server/atime_updater/atime_updater.go
enterprise/server/atime_updater/atime_updater_test.go

This should save a bit of CPU in the cache proxy.
```
goos: linux
goarch: amd64
│    base     │               values               │
│   sec/op    │   sec/op     vs base               │
Enqueue-24   146.6m ± 4%   138.0m ± 3%  -5.86% (p=0.005 n=11)
│     base     │                values                │
│     B/op     │     B/op      vs base                │
Enqueue-24   689.3Mi ± 0%   400.9Mi ± 0%  -41.84% (p=0.000 n=11)
│    base     │               values                │
│  allocs/op  │  allocs/op   vs base                │
Enqueue-24   7.531M ± 0%   5.730M ± 0%  -23.90% (p=0.000 n=11)
```

Use WithLabelValues instead of With for metrics in atime_updater

---

server/util/compression/compression.go

The labels are always the same, so we can call `With` just once.

Cache metrics with labels in compression.go

---

server/libmain/libmain.go
server/static/static.go

This will allow experiment flags to be resolved correctly. The auth information is included in the request, but wasn't being added to the context, and so wasn't available to the experiment flag evaluator.
This PR also adds processing of the codesearch_enabled experiment, which will control whether the "Enable Code Search" check box is shown on the settings page. I'll add the flag definition separately to buildbuddy-internal.

Add auth to context for index template

---

enterprise/server/util/oci/BUILD
enterprise/server/util/oci/oci.go
enterprise/server/util/oci/oci_test.go

This change adds the `read_manifests_from_cache` flag and will fetch image and index manifests from the cache when enabled.
In order to avoid pathological behavior wherein `Layer.DiffID()` fetches the entire uncompressed layer in order to compute a checksum, I also implement `layerFromDigest` in this change. A future change will cache the layer on calls to `Compressed()`.

[oci resolver] read manifests from cache (disabled by default)

---

server/util/lib/set/BUILD
server/util/lib/set/set.go
server/util/lib/set/set_test.go

This PR adds a formal `Set` type, which is simply defined as a `map[E any]struct{}`
Motivations for this change:
- I find myself very, very frequently needing to turn a slice or sequence into a "set", and writing the same for-loop every time. 
- Inserting a new element into a "set" is not very readable: `set[element] := struct{}{}` is technically understandable, but it is not a very intuitive way to represent what you're doing.
- Determining membership in a "set" is cumbersome. For any conditional, checking membership requires doing `if _, ok := set[element]; ok`. This means both that you cannot combine two checks for set membership in one conditional, and you cannot short-circuit checking set membership in a conditional since the check has to be evaluated before the actual conditional.
- …

Add `Set` type

---

enterprise/server/workflow/config/config.go

`bazel --version` breaks when other startup options are included (and in workflows, startup options seem to be injected). https://github.com/bazelbuild/bazel/issues/26225.
`bazel info release` seems to output the same string, so use that instead.

Use 'bazel info release' instead of 'bazel --version'

---

app/root/root.css
enterprise/app/history/history.tsx

Also simplify hover state logic a bit (we were previously using JS to track mouse movements to compute a `card-hovered` class, but can just use `:hover` in CSS instead)

Remove hover styling for non-clickable cards

---

enterprise/server/remote_execution/containers/docker/docker.go

A while back, the contract of the `Remove` method (from the `CommandContainer` interface) was changed so that (a) it must be idempotent ("removes **any** resources asociated with the container"), and (b) it is called even for the `Run` codepath (non-recycling case). But we never updated the `docker` impl to account for this, so it now tries to remove the container unconditionally, even though the current implementation in `Run` removes the container in the background. This PR fixes the `Remove` implementation to only remove if the container exists and has not yet been removed.
Side note: the current (ancient) implementation of `Run` spawns a background process to remove the container after the action finishes running, which is not great - in a follow up PR, I would like to remove that …

Fix error logged when removing docker container that is already removed

---

enterprise/server/util/ocicache/BUILD
enterprise/server/util/ocicache/ocicache.go
enterprise/server/util/ocicache/ocicache_test.go

This change introduces `ocicache.NewBlobReadThroughCacher`, which will be necessary to cache layers on read.

[oci cache] add NewBlobReadThroughCacher

---

enterprise/tools/vmstart/vmstart.go

* Take the snapshot key format that is displayed in our UI. It's easier to find than the format from the logs

Make VMstart easier to use

---

enterprise/server/raft/replica/replica.go
enterprise/server/raft/replica/replica_test.go

also add unit test to make sure that after committing txn, it is unlocked.

[raft] clean up mappedRangeLockTxnID

---

enterprise/server/backends/redis_execution_collector/BUILD
enterprise/server/backends/redis_execution_collector/redis_execution_collector.go
enterprise/server/backends/redis_execution_collector/redis_execution_collector_test.go

We're seeing some duplicate invocation-execution links in logs: https://github.com/buildbuddy-io/buildbuddy-internal/issues/5121
Add tests to make sure we ignore duplicates (to match the current MySQL behavior). Also add logging so that after switching to redis, we can keep investigating this issue.

Log duplicate invocation/execution links and add tests

---

enterprise/server/backends/pebble_cache/pebble_cache.go
proto/storage.proto
server/metrics/metrics.go

Reverts buildbuddy-io/buildbuddy#9595

Revert "sample partition size per group while evicting instead of trying to fully count size"

---

enterprise/server/remote_execution/containers/firecracker/firecracker_test.go
enterprise/server/remote_execution/snaploader/BUILD
enterprise/server/remote_execution/snaploader/snaploader.go
enterprise/server/remote_execution/snaputil/snaputil.go

When I moved the dev GCP cache proxy to a deployment model instead of a statefulset model, I broke snapshot sharing in dev. This is because there's now no guarantee that an entire snapshot will be present in the cache proxy that serves the snapshot read request. This PR adds a flag that control whether or not to read/write snapshots from/to the backing cache as well, so that we can do this in dev GCP, but not do it in SJC where we anticipate continuing to run a distributed cache ring in the Cache Proxies.

Flag-guard cluster-local reads/writes of workflow VM snapshots

---

app/auth/auth_service.ts
app/auth/user.ts
enterprise/app/org/org_form.tsx
proto/user.proto
server/buildbuddy_server/BUILD
server/buildbuddy_server/buildbuddy_server.go
server/libmain/libmain.go
server/static/static.go

We shouldn't send user- or group- specific data or experiment flags in the `FrontendConfig` - it requires a full page refresh to update these. Instead, this PR moves user-specific experiment data to `GetUser`.
- Add a new message to hold experiment data to `GetUserResponse`, and populate it in the `GetUser` call
- Plumb that to the frontend `User` struct
- Update the frontend to check the new codesearch experiment flag when deciding whether to render the "Enable Codesearch" checkbox on the settings page. 
- Set the selected group id cookie whenever group id changes.
- Undo the auth wrapping for root app requests from #9529, it is no longer needed.

Move user/group-specific experiments to GetUser

---

enterprise/server/backends/migration_cache/BUILD
enterprise/server/backends/migration_cache/migration_cache.go
server/metrics/metrics.go

This allows us to track migration progress per group, since we might migrate one group at a time.

Add groupID as a dimension to most of the migration cache metrics

---

enterprise/server/remote_execution/executor/executor.go

Somehow, the `executed_action_metadata_durations_usec` metric has entries in the infinite bucket for every stage. It seems unlikely that stages like `input_fetch` could take more than the biggest bucket, so log this to figure out what's going on.

Log when stage duration is longer than 20h

---

enterprise/server/remote_execution/containers/firecracker/BUILD
enterprise/server/remote_execution/containers/firecracker/firecracker.go
proto/BUILD
proto/firecracker.proto

This will allow us to expire snapshots that were created or updated a long time ago.
I'm still not sure if this is necessary, but storing the timestamps makes it easier to do this in the future. Also, it's cheap and it allows us to see how long snapshots survive.

[FC] store creation and update timestamps in VMMetadata

---

cli/parser/parser.go

This function is helpful when you want to parse args, consume rc file options, and expand configs in one go. It gets used when we are sure we are parsing args to forward to bazel.

CLI: Add an exported function to the parser to resolve args using the default workspace.

---

enterprise/server/raft/client/BUILD
enterprise/server/raft/client/client.go
enterprise/server/raft/config/config.go
enterprise/server/raft/store/BUILD
enterprise/server/raft/store/store.go
enterprise/server/raft/store/store_test.go

Increase the timeout, and also retries in gossip in driver tests to make tests
less flaky.
Also refactor the code to prevent from race conditions on setting the flag in
the test.

[raft] tune a few flags to make tests less flaky

---

cli/help/option_definitions/BUILD
cli/help/option_definitions/option_definitions.go
cli/log/option_definitions/BUILD
cli/log/option_definitions/option_definitions.go
cli/parser/BUILD
cli/parser/options/options.go
cli/parser/parser.go
cli/watcher/option_definitions/BUILD
cli/watcher/option_definitions/option_definitions.go

This PR adds native option definitions, which will be utilized by the parser in a later PR

CLI: Add option definitions for native options

---

enterprise/server/backends/migration_cache/migration_cache.go
enterprise/server/backends/migration_cache/migration_cache_test.go

Currently, we keep going if this errors, which means that dstMissing will be empty, so we assume that all the resources were found, and increment the `migration_double_read_hit_count` metric.
Instead, return early and enqueue all the resources for a potential copy.

Better handle the case where destination.FindMissing fails

---

server/util/lib/seq/BUILD
server/util/lib/seq/seq.go
server/util/lib/seq/seq_test.go

The `seq` library has three main motivations:
- Frequently, when doing complex processing on a slice, intermediary slice allocations are made to store intermediary values, or filtered versions of the slice. These allocations can be quite significant, depending on the size of the original slice. Using sequences prevents these allocations, as the sequence is necessarily only looped over once and does not store prior values, nor does it need to make copies in order to remove filtered elements, as those are just skipped when iterating.
- Similarly, lazy evaluation when processing a slice could lead to saving cpu time if it turns out that we only needed to process part of the slice. The sequence functions here are lazy, only processing a given element at time of access, so early returns or …

Add a library to handle sequence / slice operations seamlessly

---

server/util/lib/seq/seq.go
server/util/lib/seq/seq_test.go

This is to pair better with `Drop` and to open the door to implementing a `TakeWhile` and `DropWhile`.

Rename `seq.Truncate` to `seq.Take`

---

cli/parser/options/BUILD
cli/parser/options/options.go
cli/parser/parsed/parsed.go

This PR:
- accounts for an unhandled type, which can't happen in this version of the code, but could if someone expanded the function's type constraint without adding types to the type switch
- Returns an error if a `BoolOrEnum` tries to accumulate a non-bool type.
- Takes a `seq.Sequenceable` so we can pass options we are filtering without allocating a slice for them.

CLI: Improve `AccumulateValues`

---

cli/parser/parser.go

Permissive parsing is important for the forthcomming help parser, which should not error out just because it encounters options unsupported by the detected command.

CLI: Allow for permissive parsing

---

enterprise/server/backends/distributed/BUILD
enterprise/server/backends/distributed/distributed.go
enterprise/server/backends/distributed/distributed_test.go

Related issues: https://github.com/buildbuddy-io/buildbuddy-internal/issues/5175

Don't store contents for encrypted groups in the lookaside cache

---

enterprise/server/backends/migration_cache/BUILD
enterprise/server/backends/migration_cache/migration_cache.go
enterprise/server/experiments/experiments.go
server/util/alert/alert.go

Currently when flagd is not configured, we use `openfeature.NoopProvider`, which always returns the default value. Since this is nil, `config` always returns an error.
When flagd is configured, but the configuration is invalid, it also returns the default, so again `config` always returns an error.
Instead log errors when the config is invalid or when flagd returns an error. Don't log error when the config is missing, because this could be just because flagd isn't configured.

Make migration_cache.config more lenient with missing or invalid configs

---

codesearch/server/BUILD
codesearch/server/server.go
codesearch/server/server_test.go
proto/search.proto

This operation will populate data about overrides, inheritance, and (in the future) generated code. This will be used by the UI to display more complete reference for symbols.

Add an "extended cross references" operation to the kythe service

---

enterprise/app/code/code_v2.tsx

Previously, we fetched kythe decorations very often. We really only need to fetch them once when originally loading the file. The kythe decorations are stored on the model itself again, rather than on the ephemeral editor decoration collection.

Code browser: fetch kythe decorations once when loading files, rather than repeatedly

---

enterprise/server/remote_execution/container/BUILD
enterprise/server/remote_execution/container/container.go
enterprise/server/remote_execution/containers/ociruntime/ociruntime_test.go

Make sure we collect stats right after execution completes. This should guarantee that runners can be recycled if they've freed up enough memory to be under the 2GB limit. As a side benefit, it should also make our CPU usage slightly more accurate.

Ensure final stats measurement before recycling

---

server/testutil/testauth/testauth.go

This prevents the jwt from getting parsed over and over, which makes benchmarks non-representative.

Allow testauth.AuthenticatedUser to use the cached claims 

---

enterprise/server/backends/pebble_cache/pebble_cache.go
proto/storage.proto
server/metrics/metrics.go

actual tweaks on top of revert: https://github.com/buildbuddy-io/buildbuddy/pull/9730/files/f730f877423b64c2d6a3deda6f5e3b3587a3df18..c4fc52035364c798be04f643b40cdff864a505a9
data was noisy in prod, so i'm making things decay a little slower, too

sampled partition size by group id (re-re-revert)

---

cli/explain/explain.go
cli/flaghistory/flaghistory.go

Previously, the command tried to connect to `grpcs://` if it couldn't retrieve the BES backend from the last Bazel command.
Also drop the log message mentioning `--bes_backend`, which is a Bazel flag, not a bb flag, and is thus more confusing than helpful.

cli/explain: Use default API target as fallback

---

enterprise/server/workflow/config/config.go

- Add Java indexing to kythe workflow - this is straightforward (assuming jre is installed on the workflow machines)
- Add cpp indexing to kythe workflow - this requires a local memcached instance
- Modify go and proto indexers to use `parallel` and the kythe `dedup_stream` utility, to match java/cpp.`parallel` use speeds up indexing a bit for java/go/proto, but is basically required for cpp indexing to complete in a reasonable amount of time.

Add java and cpp indexing to kythe workflow

---

enterprise/server/experiments/experiments.go

This is causing the app canary to be rolled back.
I think it should be fine to reference flags that aren't yet defined in the flagd config, similar to how it's fine to reference go flags that we haven't yet set up in the app config YAML.
If the goal here was to catch typos in the flagd config, another solution might be to have a centralized definition of allowed experiment flags, and in the deployment workflow, validate the internal flagd configs against those definitions.

Don't log warnings on undefined experiments

---

enterprise/server/atime_updater/atime_updater.go
enterprise/server/atime_updater/atime_updater_test.go
enterprise/server/byte_stream_server_proxy/byte_stream_server_proxy.go
enterprise/server/content_addressable_storage_server_proxy/content_addressable_storage_server_proxy.go
enterprise/server/hit_tracker_client/BUILD
enterprise/server/hit_tracker_client/hit_tracker_client.go
enterprise/server/hit_tracker_client/hit_tracker_client_test.go
server/util/authutil/authutil.go

This is a little bit trickier than throwing it in an interceptor and calling it a day because these headers are only used in the atime_updater and the hit_tracker_client, and those are only called for requests that are served locally, so it's most efficient to do this work only when we know that's how the request will be processed. This is my attempt at that. 😛 
Related issues: https://github.com/buildbuddy-io/buildbuddy-internal/issues/5094

Don't parse auth headers twice between atime_updater and hit_tracker_client

---

enterprise/server/auditlog/auditlog.go
enterprise/server/iprules/iprules.go
server/interfaces/interfaces.go
server/util/claims/claims.go
server/util/claims/claims_test.go

This only affects to users that have parent/child groups.
Prior to this change, enforcement was done using the ACL list of the target child group rather than of the group that owns the API key.

Enforce IP rules against parent group ACLs.

---

enterprise/server/filestore/filestore.go
enterprise/server/remote_execution/containers/firecracker/firecracker.go
enterprise/server/remote_execution/containers/ociruntime/ociruntime.go
enterprise/server/remote_execution/filecache/filecache.go
enterprise/server/remote_execution/runner/runner.go
enterprise/server/util/ociconv/ociconv.go
enterprise/server/workflow/service/service.go
server/cache/dirtools/dirtools.go
server/remote_asset/fetch_server/fetch_server.go
server/remote_cache/byte_stream_server/byte_stream_server.go
server/remote_cache/cachetools/cachetools.go
server/remote_cache/content_addressable_storage_server/content_addressable_storage_server.go
server/remote_cache/digest/digest.go
server/remote_cache/digest/digest_test.go
server/testutil/testregistry/testregistry.go
server/util/blocklist/blocklist.go
server/util/hash/hash.go

EncodeToString is faster and more clear.
Benchmark results for digest.Compute:
```
│    base3     │                hex3                 │
│    sec/op    │    sec/op     vs base               │
DigestCompute/SHA256/1-24        272.2n ± 12%   194.4n ± 13%  -28.58% (p=0.001 n=7)
DigestCompute/BLAKE3/1-24        1.665µ ± 15%   1.293µ ± 10%  -22.34% (p=0.001 n=7)
DigestCompute/SHA256/10-24       235.3n ± 17%   185.9n ± 10%  -20.99% (p=0.001 n=7)
DigestCompute/BLAKE3/10-24       1.605µ ± 19%   1.300µ ±  8%  -19.00% (p=0.001 n=7)
DigestCompute/SHA256/100-24      259.2n ±  9%   241.6n ± 19%   -6.79% (p=0.026 n=7)
DigestCompute/BLAKE3/100-24      1.749µ ± 43%   1.328µ ±  9%  -24.07% (p=0.001 n=7)
DigestCompute/SHA256/1000-24     608.3n ±  9%   559.1n ±  3%   -8.09% (p=0.001 n=7) …
```

Use hex.EncodeToString instead of fmt.Sprintf("%x")

---

shared.bazelrc

In https://github.com/buildbuddy-io/buildbuddy/pull/9754, it was changed along with other flags, but it shouldn't have been.

Fix --bes_results_url in bazelrc

---

enterprise/server/cmd/cache_proxy/cache_proxy.go
enterprise/server/cmd/executor/executor.go
enterprise/server/hit_tracker_service/hit_tracker_service.go
enterprise/server/remote_execution/execution_server/execution_server.go
server/build_event_protocol/build_event_handler/build_event_handler.go
server/libmain/libmain.go
server/remote_cache/hit_tracker/hit_tracker.go
server/util/usageutil/usageutil.go
server/util/usageutil/usageutil_test.go

turns out it's easy to write a test that passes when it doesn't test the right flow.

Revert "populate server field in usages table (#9756)"

---

enterprise/app/code/code_v2.tsx

This is kind of hacky, but it does make the back button work when navigating through code. The overall fetching / rendering logic in this file deserves some untangling, but I'll leave that as an exercise to the reader for now.

Make the back button work in the code browser

---

enterprise/server/remote_execution/filecache/filecache.go

Currently, creating the labels and getting the metric is about 0.5% of executor CPU

Pre-compute filecache requests metric with labels

---

enterprise/server/remote_execution/runner/runner.go

Every time I come across the `else` branch in this code (which I probably wrote originally), I always think "this looks wrong" - we're checking whether the pool's total memory usage (across all runners) is less than the max limit for a _single_ runner. But it has been somewhat mystifying, because even though it looks clearly wrong, and seems like it would be triggering lots of unnecessary evictions, we never actually see the log message from that branch in practice.
Turns out, this code is unreachable. The first branch of the `if` is always true, because the outer loop is already checking the same condition `p.pausedRunnerCount() >= p.maxRunnerCount`, so because we're in the loop body, and because neither of those expressions can change between the `for` check and the `if` check, it must …

Clean up unreachable code in runner pool eviction loop

---

server/remote_cache/byte_stream_client/byte_stream_client.go

We have been running with this since Dec 2023.
Should be safe to enable by default.

byte_stream_client: default grpc_client.enable_pool_cache to true

---

server/buildbuddy_server/BUILD
server/buildbuddy_server/buildbuddy_server_test.go
server/remote_cache/byte_stream_client/byte_stream_client.go

Aggregate errors from all streaming attempts using `errors.Join`.

byte_stream_client: improve error handling

---

enterprise/app/executors/BUILD
enterprise/app/executors/executors.tsx

Link to Helm charts in self-hosted executor setup

---

enterprise/server/experiments/experiments.go
enterprise/server/experiments/experiments_test.go
server/interfaces/interfaces.go

It's sometimes necessary to know which `variant` was selected, e.g. https://github.com/buildbuddy-io/buildbuddy/pull/9799
This PR adds "Details" versions of each FlagProvider method so that this info can be retrieved. There are some other things in the flagd Details which might be interesting (such as Error) so I went with an interface exposing a `Variant()` method which we can extend later, rather than just exposing a `variant` string.

Add Details methods to FlagProvider

---

enterprise/app/trends/trends.tsx

we show the drilldows link in the left-hand-side menu.
going to split out the drilldowns page in a separate PR--i'm cooking up something to make a few different tabs on the trends page (for cache, RBE, etc.) so in the end i'll still need the tab field.

remove trends tabs, remove always-true trendsRangeSelection refs

---

enterprise/server/atime_updater/atime_updater.go
enterprise/server/atime_updater/atime_updater_test.go
enterprise/server/byte_stream_server_proxy/byte_stream_server_proxy.go
enterprise/server/content_addressable_storage_server_proxy/content_addressable_storage_server_proxy.go
enterprise/server/hit_tracker_client/BUILD
enterprise/server/hit_tracker_client/hit_tracker_client.go
enterprise/server/hit_tracker_client/hit_tracker_client_test.go
server/interfaces/interfaces.go
server/remote_cache/byte_stream_server/byte_stream_server.go
server/util/authutil/authutil.go

The difference between this and the previous attempt is in this commit: https://github.com/buildbuddy-io/buildbuddy/commit/812011a816ab7a81de9026d9b6aae23e5ac318a0
Related Issues: https://github.com/buildbuddy-io/buildbuddy-internal/issues/5094

Attempt #2: Don't parse auth headers twice between atime_updater and hit_tracker_client

---

server/remote_cache/digest/digest.go
server/remote_cache/digest/digest_test.go
tools/cas/cas.go

ActionCacheString was missing a slash between the digest and the size. I don't think this was causing any problems in practice since it's only used for the lookaside cache ([here](https://github.com/buildbuddy-io/buildbuddy/blob/d4f341434dceada7184d359403c4b25aeeb195db/enterprise/server/backends/distributed/distributed.go#L389)) but I hit this bug while trying to call this function from `tools/cas`.

Fix ActionCacheString missing slash

---

enterprise/server/ociregistry/ociregistry.go
enterprise/server/util/oci/oci.go
enterprise/server/util/ocicache/ocicache.go
enterprise/server/util/ocicache/ocicache_test.go

* Log OCI manifest cache hits and misses at info level (along with repository).
* Log warnings for any errors fetching manifests from the cache.

[oci cache] log manifest hits and misses at info level

---

enterprise/server/backends/pebble_cache/pebble_cache.go

Since the size of the pebble cache is doubling with GCS, the table cache hit rate went from 99.9% to 93.7%. I hope that doubling the table cache size will recover the cache hit rate. This only takes an extra 1MB per pebble cache (so 2MB during the migration).
The table cache size is controlled by the MaxOpenFiles option.

Double the size of the pebble table cache

---

enterprise/server/filestore/filestore.go
server/backends/blobstore/gcs/gcs.go
server/testutil/mockgcs/mockgcs.go

For large writes, keep it set to the default 16MiB, so we don't try to send a single HTTP POST with hundreds or thousands of MiB. This also allows the GCS client library to retry a failed chunk, so we don't lose the whole upload with a temporary error, which might help with tail latency.

Don't always set ChunkSize=0

---

proto/stat_filter.proto
server/util/filter/filter_test.go

Also rename a couple of the enums added in https://github.com/buildbuddy-io/buildbuddy/pull/9834/files to be less ambiguous.

Support all ExecutionMetricType enums with GenericFilter

---

enterprise/server/atime_updater/atime_updater.go
enterprise/server/atime_updater/atime_updater_test.go
server/interfaces/interfaces.go
server/testutil/testenv/testenv.go

This PR restructures the atime_updater to use a channel for enqueuing updates, instead of doing it synchronously. Updates are formed and sent to the channel only if sending to the channel will not block. Then, there is a goroutine that consumes updates from this channel and batches them into the per-group, and per-instance-name-and-digest-function maps. There is still another goroutine that consumes these batches and sends them to the backend, as before. This means that calls to atime_updater Enqueue functions should now never block, which should help cache proxy throughput under load a bit. This makes the code a little bit more complicated, but I think it's a reasonable tradeoff to make.
I also changed the tests to call the lifecycle functions on atime_updater directly, instead of …

Don't block on mutexes when calling atime_updater.Enqueue functions

---

enterprise/server/webhooks/github/BUILD
enterprise/server/webhooks/github/github.go

The `fieldgetter` utility was used to extract values from GitHub webhook
event structs using reflection. This commit removes its usage and
replaces it with direct method calls on the event objects. This
simplifies the code by removing an unnecessary dependency and allows for
direct, type-safe access to event fields.

github: remove fieldgetter usage

---

server/metrics/metrics.go
server/util/disk/BUILD
server/util/disk/disk.go

FileWriters are used to write artifacts to disk by the cache implementations. When there are bursts of file writer operations, it can cause the Go runtime to create an unbounded number of system threads as file writer ops end up blocked on syscalls.
The concurrency limit places an upper bound on the system threads created via this code path.
Fixes: https://github.com/buildbuddy-io/buildbuddy-internal/issues/5325

Add a concurrency limit on FileWriter ops.

---

enterprise/server/remote_execution/executor/executor.go
enterprise/server/remote_execution/executor/executor_test.go
enterprise/server/test/integration/remote_execution/rbetest/rbetest.go
server/remote_cache/cachetools/cachetools.go

The `DeadlineExceeded` error [here](https://github.com/buildbuddy-io/buildbuddy/blob/590882cce0978098f4610579f9e14e4cd0fc9016/server/remote_cache/cachetools/cachetools.go#L108) is a non-retryable error. This PR makes it so that this error, and any other `DeadlineExceeded` errors that might be returned from `DownloadInputs`, are always retried. We only want to return `DeadlineExceeded` if `Action.timeout` is reached.

Return retryable error for internal CAS download timeouts

---

enterprise/server/raft/store/store.go
enterprise/server/raft/store/store_test.go

https://github.com/buildbuddy-io/buildbuddy-internal/issues/4913
Also, fix a bug I found around waiting for replica to catch up. This call can
only be called on the machine with the new shard and calling it at the
promoteToVoter doesn't have any effect on the new shard.
Instead, I make sure we wait for the new shard to catch up when the shard
already exists.

Test add replicas from different intermediate states

---

server/metrics/metrics.go

The "Action stage durations" graph still can't load for 2 days. This halves the number of buckets, from 56 to 28.
Old bucket:
```
Bucket count: 56
0 = 1ms
1 = 1.4ms
2 = 1.959ms
3 = 2.743ms
4 = 3.841ms
5 = 5.378ms
6 = 7.529ms
7 = 10.541ms
8 = 14.757ms
9 = 20.661ms
10 = 28.925ms
11 = 40.495ms
12 = 56.693ms
13 = 79.371ms
14 = 111.12ms
15 = 155.568ms
16 = 217.795ms
17 = 304.913ms
18 = 426.878ms
19 = 597.63ms
20 = 836.682ms
21 = 1.171355s
22 = 1.639897s
23 = 2.295856s
24 = 3.214199s
25 = 4.499879s
26 = 6.299831s
27 = 8.819763s
28 = 12.347669s
29 = 17.286737s
30 = 24.201432s
31 = 33.882005s
32 = 47.434807s
33 = 1m6.40873s
34 = 1m32.972222s
35 = 2m10.161111s
36 = 3m2.225556s
37 = 4m15.115778s
38 = 5m57.16209s
39 = 8m20.026926s
40 = 11m40.037696s
41 = 16m20.052775s
42 = 22m52.073885s
43 = …
```

Further reduce the number of buckets for executed_action_metadata_durations_usec

---

enterprise/server/remote_execution/executor/BUILD
enterprise/server/remote_execution/executor/executor.go
enterprise/server/remote_execution/executor/executor_test.go

We need to return a digest.MissingDigestError to ensure that bazel reuploads action inputs, otherwise it will just retry the execution without attempting a reupload.

Fix NotFound error returned when inputs are missing

---

deps.bzl
go.mod
go.sum

I'm not sure this will fix the rbeperf bug I mentioned in #eng because were already on github.com/prometheus/common versions v0.62.0: https://github.com/prometheus/common/releases/tag/v0.62.0, but this shouldn't hurt.

Upgrade versions of prometheus dependencies

---

enterprise/server/filestore/filestore.go

I think this is simpler. It also avoids an allocation for LimitReader, and it returns a reader which implements a WriterTo.
Previously, we used a LimitReader even when limit was 0.
```
│    base     │               simple               │
│   sec/op    │   sec/op     vs base               │
GetSingle/LocalPebble10/AC-24       5.868µ ± 2%   5.775µ ± 3%  -1.58% (p=0.047 n=11)
GetSingle/LocalPebble10/CAS-24      4.372µ ± 2%   4.335µ ± 2%       ~ (p=0.217 n=11)
GetSingle/LocalPebble100/AC-24      6.161µ ± 1%   6.085µ ± 2%  -1.23% (p=0.040 n=11)
GetSingle/LocalPebble100/CAS-24     4.712µ ± 1%   4.697µ ± 1%       ~ (p=0.699 n=11)
GetSingle/LocalPebble1000/AC-24     6.932µ ± 3%   6.915µ ± 2%       ~ (p=0.156 n=11)
GetSingle/LocalPebble1000/CAS-24    5.666µ ± 2%   5.677µ ± 2% …
```

Simplify filestore.InlineReader

---

enterprise/server/api/api_server_test.go
server/build_event_protocol/build_event_handler/build_event_handler_test.go
server/buildbuddy_server/buildbuddy_server_test.go
server/testutil/testenv/testenv.go

Make sure we shutdown NewHealthChecker after the test has finished
running to avoid goroutine leakages.
Since the NewHealthChecker shutdown logic includes the
build_event_handler stop call, remove the defer stop calls from
api_server_test.go.
Added missing cleanup to buildbuddy_server_test and build_event_handler_test.

testenv: properly shutdown NewHealthChecker

---

tools/dev_qa.py

This reduces the number of places where we have to update commit hashes, and also makes it so we can re-run the release workflow if we need to update one of these hashes, without needing to re-cut the release.

Let dev_qa.py generate the GH actions matrix

---

tools/dev_qa.py

The checkout action expects repos to be referenced as `owner/repo`, and not by URL
https://buildbuddy-corp.slack.com/archives/C04M5190WLD/p1752694094448789

Fix dev_qa.py --print_matrix

---

enterprise/server/remote_execution/executor/BUILD
enterprise/server/remote_execution/executor/executor.go

Firecracker container image warmup currently logs errors because it's making anonymous AC requests to the cache_proxy. Attaching the executor API key to the warmup context _should_ make both snapshot loading and image caching Just Work™️.

[executor] pass executor API key to image warmup

---

enterprise/server/remote_execution/executor/executor.go

On-prem customers do not necessarily set an executor API key, so let's not log a warning for them.

[executor] log only when we're using executor api key in warmup

---

cli/download/download.go
cli/upload/BUILD
cli/upload/upload.go

Implement the same flag as the upload command.
Force both to use the new login.GetAPIKey api when the flag is not set
explicitly by the user.

cli: Add --api_key flag to download

---

enterprise/server/raft/txn/BUILD
enterprise/server/raft/txn/txn.go
server/metrics/metrics.go

If there is an error in processing one record, don't return immediately so that we can process other records too.

[raft] add monitoring to process txn records

---

server/backends/blobstore/aws/aws.go
server/backends/blobstore/azure/azure.go
server/backends/blobstore/disk/disk.go
server/backends/blobstore/gcs/gcs.go
server/backends/blobstore/util/util.go

It just takes the length of this slice anyway. This makes it possible to call this method without keeping the whole slice.

Make util.RecordReadMetrics accept a size instead of slice

---

enterprise/server/remote_execution/executor/BUILD
enterprise/server/remote_execution/executor/executor.go

`auth.AuthContextFromAPIKey(...)` relies on having an AuthDB in the environment, which is not the case on executors.
Simply append the executor API key to the context used for image warmups.
Tested in dev: no more warnings about `Missing API Key`.

[executor] simply append executor api key to context during warmup

---

enterprise/server/raft/store/store_test.go

Remove helper function and use standard header creation method in raft store tests.

Replace headerFromRangeDescriptor with header.MakeLinearizableWithRangeValidation

---

enterprise/server/test/integration/remote_bazel/remote_bazel_test.go

Given a test run like this
```
> bazel test \
--config=remote-minimal \
--test_tag_filters=docker \
--test_sharding_strategy=disabled \
--runs_per_test=20 \
--test_filter=TestCancel \
//enterprise/server/test/integration/remote_bazel:remote_bazel_test
```
We have flakes like this
```
...
2025/07/24 08:26:35.224 WRN               build_event_handler.go:1495 > Failed to read scorecard for invocation e4128763-9892-4777-ad4b-356b06bcf901: rpc error: code = NotFound desc = open /workspace/_tmp/ab35a989054042c28d12cc5826a84d1a/buildbuddy-test-895015488/storage/e4128763-9892-4777-ad4b-356b06bcf901/e4128763-9892-4777-ad4b-356b06bcf901-scorecard.pb: no such file or directory
2025/07/24 08:26:35.233 WRN                 build_event_server.go:132 > Disconnecting invocation …
```

remote_bazel_test: deflake TestCancel

---

MODULE.bazel

The patch has already been removed when we last upgrade rules_go
version. Remove the entire override to cleanup.

bzlmod: remove rules_go overrid

---

enterprise/server/hostedrunner/BUILD
enterprise/server/hostedrunner/hostedrunner.go
enterprise/server/workflow/service/BUILD
enterprise/server/workflow/service/service.go

[Example config](https://github.com/buildbuddy-io/buildbuddy-internal/pull/5418/files)

[WF] Support overriding executor pool based on workflow action name

---

enterprise/server/raft/metadata/metadata.go
enterprise/server/raft/store/store.go
enterprise/server/raft/testutil/testutil.go

I plan to remove zombieMinDuration as a heuristic to detect zombies. Instead,
I want to check against ranges in txnRecords in meta range. However, when we
start the clusters, we didn't use transactions to update the range descriptors
and also we don't need txn to update the meta range. By starting the janitor
after the cluster is configured, we can prevent the zombie janitor from deleting
shards that are being created during this phase.
https://github.com/buildbuddy-io/buildbuddy-internal/issues/5402

[raft] start the zombie janitor after the cluster is configured

---

.github/workflows/build-executor-win.yaml
server/util/fastcopy/BUILD
server/util/fastcopy/fastcopy.go
server/util/fastcopy/fastcopy_linux.go
server/util/fastcopy/fastcopy_windows.go

Moved `Clone` and `FastCopy` functions from `fastcopy.go` to
platform-specific files (`fastcopy_linux.go` and `fastcopy_windows.go`).
Enable running fastcopy_test on Windows Github Action.
This is a prepatory no-op patch for future implementation of
fastcopy.Clone on Windows.

fastcopy: Make Clone and FastCopy platform-specific

---

.github/workflows/test-executor-linux-arm64.yaml

The current pool was created during the arm runner beta and we never migrated to the newer runners which use the image provided by ARM Limited, which has more software pre-installed. This PR fixes that.

Use arm-limited runners for test workflow

---

enterprise/server/remote_execution/containers/firecracker/firecracker.go
enterprise/server/remote_execution/containers/firecracker/firecracker_test.go
proto/firecracker.proto

This would allow us to discard snapshots which have been updated many times.

[FC] store modified count in VMMetadata

---

dockerfiles/rbe-ubuntu20-04/Dockerfile

Reverts buildbuddy-io/buildbuddy#10002
turns out we don't need parallel.

Revert "Add parallel to workflows image"

---

pnpm-lock.yaml

Addresses https://github.com/buildbuddy-io/buildbuddy/security/dependabot/218
Ran `pnpm update brace-expansion`

Update `brace-expansion` in `pnpm` to `1.1.12` for dependabot

---

deps.bzl
enterprise/vmsupport/kernel/microvm-kernel-x86_64-v6.1.config

The last time we tried to upgrade the firecracker guest kernel to v6.1, we saw [some networking errors](https://buildbuddy-corp.slack.com/archives/C01D5GHRJ59/p1747062596622109). This config change should resolve them (I tested with the problematic test target to ensure it now passes)

[FC] Enable TUN in 6.1 kernel

---

enterprise/server/backends/migration_cache/migration_cache.go

This will make it easier to understand all the find missing, reader, and writter RPCs that result from this function.

Add a trace span for migration_cache.sendNonBlockingCopy

---

buildpatches/org_golang_google_grpc_remove_drain_panic.patch
deps.bzl
go.mod
go.sum

The last 2 release have multiple performance improvements and changes to the `xds` code, which I think is used by directpath.
https://github.com/grpc/grpc-go/releases/tag/v1.73.0
https://github.com/grpc/grpc-go/releases/tag/v1.74.2

Upgrade google.golang.org/grpc

---

app/invocation/invocation.tsx

In dense mode, the targets tab is the default tab when no hash is set - which breaks InvocationFilterComponent (which expects the hash to be targets).
This PR fixes that by passing down the active tab to the filter component (which is correct regardless of whether or not we're in dense mode).
Fixes: https://github.com/buildbuddy-io/buildbuddy/issues/8829

Fix target filtering in dense mode

---

app/target/target_v2.tsx

Particularly useful / interesting on test pages where runs_per_test is set to > 1.
Fixes: https://github.com/buildbuddy-io/buildbuddy-internal/issues/5462

Show average, min, and max duration on test target page

---

enterprise/app/executors/executor_card.tsx
enterprise/server/scheduling/scheduler_client/BUILD
enterprise/server/scheduling/scheduler_client/scheduler_client.go
proto/scheduler.proto

Fixes: https://github.com/buildbuddy-io/buildbuddy-internal/issues/5143

Show support isolation types on executors page

---

server/backends/blobstore/gcs/gcs.go

When using directpath, every connection in the pool actually results in many connections (because we're connecting directly to GCS jobs, and not a load balancer). Each of these connections creates multiple goroutines. All together, each increment of `storage.gcs.grpc_pool_size` seems to create ~5800 goroutines.

Decrease the default `--storage.gcs.grpc_pool_size`

---

enterprise/server/auth_service/BUILD
enterprise/server/auth_service/auth_service_test.go
enterprise/server/remoteauth/BUILD
enterprise/server/remoteauth/remoteauth_test.go
server/testutil/testgrpc/testgrpc.go
server/util/usageutil/BUILD
server/util/usageutil/usageutil_test.go

We have a few places where we simulate RPCs in tests by creating a new context and copying the RPC metadata from a context that's passed in to the new context. This PR just pulls that few lines out of the few places we have it into a little utility function, mostly because I want to add another one soon and thought four of them was too many.

Add a util for copying outgoing RPC metadata to incoming RPC metadata

---

enterprise/server/raft/bringup/bringup.go
enterprise/server/raft/sender/sender.go
enterprise/server/raft/store/store.go
enterprise/server/raft/store/store_test.go

1. extract out a method reserveIDs in store
2. move ReserveRangeID to store, so it can reuse the reserveIDs method

[raft] refactor: add functionality to reserve multiple range ids

---

tools/metrics/grafana/dashboards/buildbuddy.json

Also, a small change to pick up both blob and blob_metadata hits/misses in the OCI mirror panel.

[grafana] separate panels for outgoing http reqs by host and overall

---

enterprise/server/raft/bringup/bringup.go
enterprise/server/raft/metadata/metadata.go
enterprise/server/raft/sender/BUILD
enterprise/server/raft/sender/sender_test.go
enterprise/server/raft/store/store.go
enterprise/server/raft/store/store_test.go
enterprise/server/raft/testutil/BUILD
enterprise/server/raft/testutil/testutil.go

make one transaction to update range descriptors for all ranges
Also update testutil to use the new methods.

[raft] split out the methods to initialize shards for meta range and for partition

---

enterprise/server/test/integration/remote_execution/remote_execution_test.go

Force remote execution to avoid flaky failures that result in the execution uploading to the remote cache before its shard is dropped, but not reporting back success.
Also reduce the retry delay so that it's more likely that the redis shard is restarted before execution completes.

Deflake `remote_execution_test.TestRedisRestart`

---

enterprise/server/raft/bringup/bringup.go
enterprise/server/raft/metadata/metadata.go

In order to support a large p.NumRanges, we want to batch the number of ranges we initialize and also have partition descriptor where we can store the state of the initialization so that we can recover from failures. Before this happens, I don't want us accidentally put very large number of statements in a transaction.

[raft] return errors when partition.NumRanges is set to > 10

---

enterprise/server/backends/distributed/distributed_test.go
enterprise/server/util/distributed_client/distributed_client.go

It seems unlikely that some other write will  complete between the first and last request.

In distributed server `Write` only check find missing on the first request

---

enterprise/server/workspace/workspace_service.go
server/buildbuddy_server/buildbuddy_server.go

These are the endpoints that are called by the code v2 / pull request UIs.
`GetGitHubAppForOwner` requires the repo be installed / linked, but we want to be able to edit code for any public repo. 
Without this if you try to edit the bazelbuild repo in dev, you get `NotFound: no GitHub app installation for "bazelbuild" was found`.

Switch passthrough github endpoints to `GetGitHubAppForAuthenticatedUser`

---

enterprise/app/code/code_v2.tsx

My ultimate goal here is to launch v2 in prod and delete v1.
It looks like a few changes have been made to v1 since v2 was created. This PR ports these changes to v2:
- https://github.com/buildbuddy-io/buildbuddy/commit/5371c5e85bdc45114328a5d95ee35618844f2670
- https://github.com/buildbuddy-io/buildbuddy/commit/46aec2f9dea5deac236fab2b2051f224812028bc
- https://github.com/buildbuddy-io/buildbuddy/commit/5a024ef0790ba2da1da9c229870fcf966f06feb9

Catch v2 code editor up to v1 changes

---

buildpatches/go-grpc-channelz.patch
deps.bzl

[Pull request to the original repo ](https://github.com/rantav/go-grpc-channelz/pull/16)
Now the server page looks something like: 
Also fixed a bug around printing the socket address. Before it was printing the address pointer. Now it looks something like:

Display servers' connection sockets in channelz

---

enterprise/server/cmd/server/main.go

It's called ~20 lines above, on line 232, and nothing relevant seems to change between the 2 calls.

Don't call `RegisterRemoteExecutionClient` twice

---

server/remote_cache/digest/digest.go
server/remote_cache/digest/digest_test.go
server/util/compression/compression_test.go

- Reduced the locked region
- Stopped using io.Copy which resulted in more allocations and copying every byte twice. Instead, just fill random bytes directly into a buffer.
This helps cacheload.go send more QPS without locking up my machine.

Simplify and optimize digest.RandomDigestBuf

---

enterprise/server/util/distributed_client/BUILD
enterprise/server/util/distributed_client/distributed_client.go
server/remote_cache/byte_stream_server/BUILD
server/remote_cache/byte_stream_server/byte_stream_server.go

This will hopefully tell us if we are getting data too slowly, or writing it too slowly.

Add tracing around write stream receives

---

app/invocation/invocation_suggestion_card.tsx

Starting in Bazel 8, `--experimental_remote_cache_compression_threshold`'s default value changes from 0 to 100. The existing warning recommendation is a false positive for Bazel 8 workspaces. Check for Bazel 8 to not show the recommendation. If a Bazel 8 workspace explicitly sets `--experimental_remote_cache_compression_threshold` as well in Bazel 8 (even to 0), then the recommendation is not required anyways.

WebUI: Ignore unset experimental_remote_cache_compression_threshold for Bazel 8

---

proto/BUILD
proto/encryption.proto

This is the second step described in https://github.com/buildbuddy-io/buildbuddy-internal/issues/4758#issuecomment-3152798840.
Related Issues: https://github.com/buildbuddy-io/buildbuddy-internal/issues/4758

Add an RPC service for retrieving customer-managed encryption keys

---

go.mod
go.sum
go_deps.MODULE.bazel
server/util/tracing/BUILD
server/util/tracing/tracing.go

For basic auth support, support OTLP http endpoints too. This will be used to send traces across clusters so that we can aggregate all traces in a single clickhouse DB.
Example: `--app.trace_otlp_http_collector=https://user:pass@host:port`.
Tested in dev.

Support HTTP format for OTEL traces

---

enterprise/app/executors/executor_card.tsx
enterprise/app/executors/executors.tsx
enterprise/server/remote_execution/platform/platform_test.go
enterprise/server/scheduling/scheduler_client/BUILD
enterprise/server/scheduling/scheduler_client/scheduler_client.go
enterprise/server/scheduling/scheduler_server/scheduler_server.go
enterprise/server/scheduling/scheduler_server/scheduler_server_test.go
proto/scheduler.proto
server/interfaces/interfaces.go
server/resources/resources.go
server/xcode/BUILD
server/xcode/xcode.go
server/xcode/xcode_darwin.go
server/xcode/xcode_darwin_test.go

Looks like this (IP address redacted):
We could add some logic to improve the display names of the SDKs as opposed to what we get from Xcode, but I figured this was probably good enough for now. Also not sure if there are cases where we'd want to not show the full operating system with version, let me know if you can think of any.

Add specific operating system, Xcode version(s), and Xcode SDKs to executor card

---

WORKSPACE
dockerfiles/test_images/defs.bzl
enterprise/server/remote_execution/containers/ociruntime/BUILD
enterprise/server/remote_execution/containers/ociruntime/ociruntime.go
enterprise/server/remote_execution/containers/ociruntime/ociruntime_test.go
oci.MODULE.bazel

- Remove support for the hard-coded, readonly busybox rootfs that has a separate codepath from the overlayfs codepath. This was helpful while initially writing the oci isolation type (before we could pull and mount images) but isn't very useful now and complicates the code.
- Use a real busybox image everywhere that we were using the hard-coded busybox image.
- Don't pull any images (either busybox or net-tools) from the external internet - get all images from runfiles instead.

Clean up ociruntime_test OCI image setup

---

enterprise/server/backends/codesearch/codesearch.go
enterprise/server/remote_execution/redis_client/redis_client.go
enterprise/server/scheduling/scheduler_server/scheduler_server.go
enterprise/server/tasksize_model/tasksize_model.go
server/libmain/libmain.go
server/remote_cache/byte_stream_client/byte_stream_client.go
server/remote_cache/content_addressable_storage_server/content_addressable_storage_server.go

When we don't go through a proxy or load balancer, we can handle unlimited streams per client connection, so there's no reason to create 15 connections.
When connecting to localhost, we don't need to worry about the health of the peer, so we can totally skip pooling.
Lowering the number of client connections lowers the number of goroutines used by the targeted servers, and this seems to lower heap size and GC duration.

Lower pool size for client connections that are direct

---

enterprise/server/raft/store/store.go

If in AddReplica, after the replica descriptor is added to the staging replica, we failed to add it as a non-voter in raft. When AddReplica tries to run again, it tries to reserve a new replica ID and add it to staging replicas of the range descriptor. Even if the second time it succeeded, we will have a stale staging replica in the descriptor. The driver will try to resolve it by calling AddReplica again. But this time, verifyRequest fails since there is a replica descriptor with the requested NHID in the replica descriptor.

[raft] fix a bug in add replica

---

server/cache/dirtools/dirtools.go

An optimal value is not easy to figure out but we can set a conservatively high upper bound to prevent the executors from blowing up.
At 1000 concurrent ops, an executor can perform 20 million fs ops per second assuming 50 micros per op. Don't think anyone is going to be hitting this any time soon.
Fixes https://github.com/buildbuddy-io/buildbuddy-internal/issues/5050

Set a default value cache.client.input_tree_setup_parallelism.

---

app/compare/compare_invocations.tsx
app/invocation/invocation_model.tsx

This will help bb explain work in dev (otherwise it just defaults to looking up the invocations in prod).

Specify a `--target` for bb explain

---

tools/registry

This was useful for developing https://github.com/buildbuddy-io/buildbuddy/pull/10199 and https://github.com/buildbuddy-io/buildbuddy/pull/10200, since every registry request gets logged to the terminal which makes it easy to see when we're making unexpected requests.

Add a script to run a private registry locally

---

app/components/popup/popup.tsx
app/invocation/BUILD
app/invocation/invocation.css
app/invocation/invocation_card.tsx
app/invocation/invocation_compare_button.tsx
app/root/root.css

Currently comparing two invocations takes a lot of clicks (you have to actually click into the invocation) - this should reduce them:

Add a mini compare button to the invocation list view

---

enterprise/server/util/oci/oci.go
enterprise/server/util/oci/oci_test.go

- Skip registry ping (`/v2/`) if the image is cached. The fix is to just move `createRemoteLayer()` to later in the `Compressed()` function (after the cache check), since this seems to be what causes the ping request.
- Skip HEAD request to resolve the image to a digest if we already know the digest (i.e. the container-image string already contains a digest). The HEAD request just gives us an image descriptor (digest, length, content-type), but if we have a digest ref and we have the manifest cached, then we have everything we need already and can build the descriptor directly, without hitting the registry.
Work towards https://github.com/buildbuddy-io/buildbuddy/pull/10199

Skip image registry requests in a few more cases

---

app/invocation/invocation.tsx

Currently depending on ordering of componentDidUpdate calls, we have a chance of dropping out of this loop and stopping our periodic UI refreshes.

Make sure we don't drop out of the `scheduleRefetch` loop

---

enterprise/server/remote_execution/execution_server/execution_server.go
enterprise/server/remote_execution/platform/platform.go
enterprise/server/test/integration/remote_execution/rbeclient/rbeclient.go
enterprise/server/test/integration/remote_execution/remote_execution_test.go
enterprise/server/util/oci/oci.go
server/capabilities_filter/BUILD
server/capabilities_filter/capabilities_filter.go
server/util/authutil/authutil.go

This will allow replaying actions using only the cached image contents, bypassing requests to the registry but still requiring image cache auth. This also will require some updates to replay_action - will send those out separately.

Add property to allow pulling images only from cache

---

enterprise/server/backends/pebble_cache/pebble_cache.go
enterprise/server/backends/pebble_cache/pebble_cache_test.go

The previous version would delete the file (if there was one) but keep the metadata because it was using the wrong key version.

Fix pebble_cache.Delete

---

enterprise/server/remote_execution/platform/platform.go
enterprise/server/remote_execution/runner/runner.go

Context: https://buildbuddy-corp.slack.com/archives/C091JA2J1RU/p1757519819422909?thread_ts=1757469653.024489&cid=C091JA2J1RU
Based on the error message and the provided invocation link (specifically the platform props shown for the failing executions), it looks like the customer has `default_isolation_type: oci` configured, but not `enable_oci: true`. This is a configuration error that we can surface in a more obvious way.

Validate default_isolation_type flag

---

enterprise/server/remote_execution/runner/runner.go
enterprise/server/util/oci/oci.go

Once `executor.resolve_image_digests` is set to true, we should no longer see image names with tags in the logs. Make sure to log after resolving image names to digests.

[remote exec] log container image names after resolving to digest

---

enterprise/server/cmd/cache_proxy/cache_proxy.go
enterprise/server/cmd/executor/executor.go
server/libmain/libmain.go

This caused me some confusion during local development - the executor will happily start up if something is listening on port 8888 already, but it should probably fail. In my case I forgot I was running some pprof web stuff listening on port 8888, and I was confused when I tried to check /readyz on port 8888 (for the executor) and it gave me a 404.

Fail on startup if http port is busy

---

enterprise/server/backends/authdb/authdb.go
enterprise/server/backends/authdb/authdb_test.go
enterprise/server/backends/userdb/userdb.go
enterprise/server/scim/BUILD
enterprise/server/scim/scim.go
server/tables/tables.go

With the introduction of indirect memberships, a user could have more than one role assigned. In those cases, we'll not populate the role at all.
SCIM is the last remaining user of the role field and will only look at direct memberships for user attributes in which case it can continue to use the role field until everyone has been migrated to use uesr lists.

Make role field in GroupRole optional.

---

enterprise/server/remote_execution/vfs/vfs_unix.go

The NotifyEntry call will eventually result in the kernel telling the fuse server to forget the node which will also remove the child so if it's already gone we don't need to treat it as an error.

fuse: when updating layout make failing to rm child non-fatal

---

enterprise/server/backends/userdb/userdb.go

GORM logs an "unsupported data type" warning because `tables.GroupRole` contains a `[]cappb.Capability` field which is not scannable. To fix the warning, scan into the `Group` field instead, which is a DB-mapped struct.

Fix warning logged by GetImpersonatedUser group scan

---

enterprise/server/auth/auth.go
enterprise/server/backends/authdb/BUILD
enterprise/server/backends/authdb/authdb.go
enterprise/server/backends/authdb/authdb_test.go
enterprise/server/oidc/oidc.go
enterprise/server/remote_execution/execution_server/BUILD
enterprise/server/remote_execution/execution_server/execution_server.go
enterprise/tools/replay_action/replay_action.go
enterprise/tools/vmstart/vmstart.go
server/buildbuddy_server/buildbuddy_server.go
server/capabilities_filter/BUILD
server/capabilities_filter/capabilities_filter.go
server/capabilities_filter/capabilities_filter_test.go
server/interfaces/interfaces.go
server/nullauth/nullauth.go
server/testutil/testauth/testauth.go
server/util/authutil/authutil.go
server/util/capabilities/capabilities_test.go
server/util/claims/claims.go

Context: I'd like to add a new field `ExperimentTargetingGroupID` to `Claims`, which will be based on a gRPC header that only server admins should be able to set. The current code structure makes this difficult to implement - `ClaimsFromContext` does not currently get passed an `env` or an `Authenticator`, but the authenticator is needed to know the server admin group ID (using the `AdminGroupID()` method).
So, this PR shuffles things around so that `claims.go` has more direct access to the server admin group ID. In particular, it makes the server admin group ID a plain old flag, which makes things simpler overall.

refactor: move server admin flag / auth logic to claims package, and simplify

---

cli/cli_command/register/BUILD
cli/cli_command/register/register.go
cli/login/login.go
cli/view/BUILD
cli/view/view.go

Supports invocation ids and urls.
Examples:
bb view 12345678-1234-1234-1234-123456789012
bb view https://app.buildbuddy.io/invocation/12345678-1234-1234-1234-123456789012

Add `bb view` command that prints invocation logs

---

enterprise/tools/mdload/mdload.go

the current error count metric is counting inside a retry loop; We also want
to monitor error count metric outside a retry loop.

add a new error count metric in mdload

---

enterprise/server/experiments/BUILD
enterprise/server/experiments/experiments.go
enterprise/server/experiments/experiments_test.go
server/interfaces/interfaces.go
server/util/claims/BUILD
server/util/claims/claims.go
server/util/claims/claims_test.go

Allow server admins to override the experiment targeting group ID. Named the header `x-buildbuddy-experiment.group_id` since it seems likely that we'll want to allow overriding other vars too (for debugging purposes), and we could use the same naming convention (`x-buildbuddy-experiment.<var> = <value>`)

Allow overriding experiment targeting group ID

---

server/libmain/libmain.go
server/static/static.go

We set the hash query parameter (which isn't actually used) to make sure the browser makes a new request when a new version of style.css or app.js is pushed.
Currently we only check whether or not a hash query is present on static resource requests when deciding whether or not to set a cache header marking the resource as immutable.
This can lead to issues where during a rollout, if the index.html request and style.css?hash=foo request hit different servers - the old style.css file can be immutably cached under the new hash.
This change fixes that by only setting the immutable cache header if the hashes match, and setting a no-cache flag when the caches don't match so the new css file can be picked up on the next refresh.
There are other approaches here like:
- Actually serving the css …

Only set cache headers for static resources if hash matches

---

app/components/popup/popup.css
app/components/popup/popup.tsx
enterprise/app/filter/filter.css
enterprise/app/filter/filter.tsx

The reason why I initially hid filters under "Advanced filters" is because we were doing the filtering in MySQL and many of them were slow.
Now that we're using clickhouse - I don't think we need to hide them under an expando anymore.
Before:
Before expanded:
After:

Get rid of "advanced filters" distinction

---

enterprise/server/crypter_service/BUILD
enterprise/server/crypter_service/crypter_service.go
enterprise/server/crypter_service/crypter_service_test.go
server/interfaces/interfaces.go
server/libmain/BUILD
server/libmain/libmain.go

This is the second part of the second step described in https://github.com/buildbuddy-io/buildbuddy-internal/issues/4758#issuecomment-3152798840.
Related Issues: https://github.com/buildbuddy-io/buildbuddy-internal/issues/4758

Implement the RPC service for retrieving customer-managed encryption keys

---

enterprise/server/invocation_stat_service/invocation_stat_service.go

merged actions appear in clickhouse as multiple rows with the same `execution_id`, but a different `invocation_uuid`.  this change dedupes by `execution_id` and takes the highest value for the requested metric (all values for the metric should be identical, but taking `max` seems good)
I spot-checked against the last 7 days with:
```
SELECT target_label, SUM(cpu/ct) AS extras FROM (SELECT target_label, execution_id, count(*) AS ct, SUM(cpu_nanos) AS cpu FROM Executions WHERE updated_at_usec > 1757706462000000 AND group_id='***' GROUP BY (target_label, execution_id) ORDER BY ct DESC) WHERE ct > 1 GROUP BY target_label ORDER BY extras DESC;
```

don't double-count merged actions on targets page

---

.github/workflows/release-cli.yaml
MODULE.bazel
WORKSPACE

By updating toolchains_musl to 0.1.27 and using `--strip=always`.

Fix Linux arm64 CLI builds and strip the binaries

---

docs/config-database.md

A quick, small addition to the `database` configuration documentation, adding a note and example about PostgreSQL support.
Looks like this has been supported for 2 years but isn't in the documentation.

docs: document PostgreSQL support

---

app/invocation/action_comparison_service.ts
app/invocation/invocation_comparison_service.ts

When selecting invocations for comparison - we show a little dot indicator on the selected invocation's row that identifies which invocation is currently selected.
To update this when the user makes a selection in a different tab / window - we listen for "storage" window events which are triggered any time local storage is updated. Confusingly these [only trigger](https://developer.mozilla.org/en-US/docs/Web/API/Window/storage_event) when local storage is updated in a *different* tab.
Previously this wasn't an issue because you couldn't update comparison state from the invocation list view.
In https://github.com/buildbuddy-io/buildbuddy/pull/10209 I added a way to change the compared invocation from the list view - so now the fact that "storage" doesn't trigger in the same window becomes …

Fix comparison indicator updating

---

enterprise/server/raft/replica/replica.go
enterprise/server/raft/replica/replica_test.go
proto/raft.proto

we are not using partition metadata to track usage anymore. And it costs ~5%
cpus to update and flush the partition metadata.

remove partition metadata in replica

---

enterprise/server/test/performance/bytestream/bytestream_server_benchmark_test.go
enterprise/server/util/distributed_client/distributed_client.go
server/remote_cache/byte_stream_server/byte_stream_server.go
server/util/ioutil/BUILD
server/util/ioutil/ioutil.go
server/util/ioutil/ioutil_test.go

In order to get the full benefits of this, I also had to write to the cache first in the `io.MultiWriter` created in `byte_stream_server.beginWrite`.
```
goos: linux
goarch: amd64
│    base_4M    │           double_4M_flip           │
│    sec/op     │   sec/op     vs base               │
Write/cache_type=fast/object_size=1000/chunk_size=16384/compressor=IDENTITY-24          236.6µ ±  2%   244.6µ ± 2%   +3.37% (p=0.002 n=7)
Write/cache_type=fast/object_size=1000/chunk_size=16384/compressor=ZSTD-24              233.8µ ±  1%   234.4µ ± 1%        ~ (p=0.620 n=7)
Write/cache_type=fast/object_size=100000/chunk_size=16384/compressor=IDENTITY-24        1.098m ±  1%   1.121m ± 2%   +2.09% (p=0.007 n=7) …
```

Optimize bytestream.Write by double buffering in distributed client

---

server/rpc/interceptors/interceptors.go

Also actually set the user ID (instead of the group ID twice) in the log context.

Set group and user IDs in trace span context

---

enterprise/server/remote_execution/containers/ociruntime/ociruntime_test.go
enterprise/server/remote_execution/persistentworker/persistentworker.go
enterprise/server/remote_execution/runner/runner.go

`exec.Cmd.Wait` never returns in the case where `cmd.Stdin` is not an instance of `*os.File` and it's not receiving any input, even if the underlying process has exited already.
This means if a persistent worker crashes after we've already sent the persistent work request, we'll hang indefinitely due `exec.Cmd` being stuck.

Fix tasks hanging if persistent worker crashes

---

enterprise/server/remote_execution/containers/firecracker/firecracker.go
enterprise/server/util/ext4/ext4.go

If either `/sbin/mke2fs` or `/sbin/debugfs` are not present, the Firecracker pool will not be able to run any tasks. So ensure those binaries are present and executable at pool creation time, and error if not.

[firecracker] ensure ext4 dependencies are present during pool creation

---

server/metrics/metrics.go
server/util/clickhouse/clickhouse.go

This will allow us to ignore some errors in alerts

Add status label to clickhouse query error metric

---

enterprise/server/util/ocicache/ocicache.go
server/remote_cache/cachetools/BUILD
server/remote_cache/cachetools/cachetools.go
server/remote_cache/cachetools/cachetools_test.go

We would return io.ErrShortWrite instead of status.AlreadyExists when the resource already exists.
This is a bit clunky since byte_stream_server.go doesn't guarantee that it will notify the client if the object already exists. So in UploadWriter.Write, we do a best effort check so the caller can short-circuit, but in Commit, we treat that as success for consistency.

Fix bug in cachetools.UploadWriter

---

enterprise/server/test/performance/bytestream/bytestream_server_benchmark_test.go
enterprise/server/util/distributed_client/distributed_client.go
server/remote_cache/cachetools/cachetools.go

In benchmarks and dev experiments, these values seem to be the sweetspot. There's a few things at play:
- The smaller the chunk size, the earlier the server starts writing.
- gRPC flow control seems to be better with smaller payloads. According to https://github.com/grpc/grpc.github.io/issues/371, the ideal payload size is "16KiB - 64KiB, according to oral tradition". In my experiments, 128KiB worked just as well and seems safer. We can lower it even more later.
- The slower the underlying writer is, the better it is to send smaller chunks.
- gRPC has a variable buffer pool for receiving and sending payloads, but the [max size is 1MB](https://github.com/grpc/grpc-go/blob/e9e00cb28e350d6440145d883d1d6cf675f3c0f3/mem/buffer_pool.go#L43), so using payloads bigger than that allocates.
In the …

Optimize buffer sizes for bytestream.Write

---

enterprise/server/remote_execution/execution_server/execution_server.go
enterprise/server/remote_execution/execution_server/execution_server_test.go

Currently, if an action fails to dispatch (say because there are no executors available in its pool) - the actions remain in Starting state for ever and never get any failure details attached to them.
With this change, this actions are marked as failed - and they show up in the UI as failed with the appropriate error details.
Before:
After:

Mark executions that fail to dispatch as failed

---

deps/toolchains.MODULE.bazel

This has to reference the public repo by name so that it is properly resolved in the internal repo.

Fix toolchains_musl constraint label

---

.github/workflows/deps.yaml
WORKSPACE
deps/go_deps.MODULE.bazel
deps/toolchains.MODULE.bazel

With this change, the following build passes in the internal repo:
```
bazel build @com_github_buildbuddy_io_buildbuddy//cli --enable_bzlmod --noenable_workspace
```
Requires https://github.com/buildbuddy-io/buildbuddy-internal/pull/5736

Fix more labels for Bzlmod and update internal module file git ref

---

enterprise/server/remote_execution/execution_server/execution_server.go
enterprise/server/test/webdriver/executions_clickhouse/BUILD
enterprise/server/test/webdriver/executions_clickhouse/executions_clickhouse_test.go

This makes it so that we have the target and mnemonic available in the UI, even if the execution is in-progress. It also makes it so that if the execution hits certain errors (e.g. canceled) we will still store this metadata in ClickHouse.

Add target and mnemonic to initial execution metadata

---

server/util/clickhouse/clickhouse.go

Currently, we're just using the query SQL in metrics, which results in many very similar but distinct labels.
Use a short name instead.

Add a query template name for clickhouse inserts

---

cli/parser/parser.go

This PR should remove any problematic logging lines like the "Starting bazel server and connecting to it..." line from the base64 string we're trying to ingest programmatically.

CLI: Reduce logging when getting flag proto from bazel

---

WORKSPACE
deps/bazel_dep.MODULE.bazel
docs/rbe-setup.md

This change adds a `MODULE.bazel` snippet that points to the latest vetted commit for the BuildBuddy Toolchain.

[docs] show how to add BuildBuddy Toolchain to MODULE.bazel

---

enterprise/server/test/performance/bytestream/bytestream_server_benchmark_test.go
enterprise/server/util/distributed_client/distributed_client.go
server/remote_cache/byte_stream_server/byte_stream_server.go

This is similar to https://github.com/buildbuddy-io/buildbuddy/pull/10354, but for reads.
The smaller buffer size is faster and allocates less, in benchmarks and dev experiments. In dev experiments, this removes 33% of the RPC duration for reads of more than 5MB.
```
goos: linux
goarch: amd64
│ base_4M_4M_b  │          base_256K_256K_c           │
│    sec/op     │    sec/op     vs base               │
Read/cache_type=fast/object_size=1000/compressor=IDENTITY-24                   182.3µ ± 19%   178.0µ ±  3%   -2.39% (p=0.038 n=7)
Read/cache_type=fast/object_size=1000/compressor=ZSTD-24                       175.3µ ±  3%   175.0µ ±  3%        ~ (p=0.620 n=7)
Read/cache_type=fast/object_size=100000/compressor=IDENTITY-24 …
```

Optimize buffer sizes for bytestream reads

---

tools/metrics/grafana/dashboards/globalstatus.json

This PR adds a CPU meter for `.*-cache-proxy-.*` nodes, just like the app and executors ones, and adds a graph that shows the number of cache proxy pods running along with the autoscaler target at the bottom. Check out the branch and run it if you'd like to see.

Add a couple of Cache Proxy graphs to go/globalstatus

---

WORKSPACE
deps/toolchains.MODULE.bazel

Update to the latest LTS version of `node`.
This lets us upgrade docusaurus, which allows us to stop depending on a vulnerable version of tar-fs:
https://github.com/buildbuddy-io/buildbuddy/security/dependabot/223

Upgrade node to 20

---

.github/workflows/deps.yaml

They will no longer be used after the Bzlmod migration.

Don't sync over WORKSPACE and deps.bzl

---

enterprise/server/backends/distributed/distributed.go

Delete is only called in tests and benchmarks, so this isn't affecting prod, but it is nice to fix for tests and benchmarks.

Delete from lookaside cache in distributed.Delete
